- packages/ui/package.json
- packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
- packages/ui/src/hooks/use-bind-social.ts
- packages/ui/src/hooks/use-form.ts
- packages/ui/src/hooks/use-preview.ts
- packages/ui/src/hooks/use-social-sign-in-listener.ts
- packages/ui/src/pages/Passcode/index.tsx
- packages/ui/src/types/guard.ts
- packages/ui/src/types/index.ts
- packages/ui/src/utils/country-code.ts
- packages/ui/src/utils/index.ts
- packages/ui/src/utils/sign-in-experience.ts
- pnpm-lock.yaml
Fix most of the no-restricted-syntax in UI. 
Disable the lint for some corner cases. 
Introduce superstruct to the UI package. Use superstruct to guard some unknown input type like location.state. 
test locally
@logto-io/eng
> fix(ui): fix no-restrict-syntax in ui

- packages/connector-aliyun-dm/src/constant.ts
- packages/connector-aliyun-sms/src/constant.ts
- packages/connector-github/src/constant.ts
- packages/connector-sendgrid-mail/src/constant.ts
- packages/connector-smtp/src/constant.ts
- packages/connector-twilio-sms/src/constant.ts
Update connector description.
Some connectors' description are too long, shorten them for better display.
See description [here](https://www.notion.so/silverhand/db7fb449dc1344f2b94c4f854847bc2c?v=3172d0df286b4a17822660934b2caddc).
N/A
> chore(connector): update connector description

- packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
correct react sdk turorial content
> docs: correct react sdk turorial content

- .github/workflows/integration-test.yml
use full repo for integration tests to enable in-repo import
CI
> ci: use full repo for integration tests

- .github/workflows/close-stale.yml
close when it's stale
tested with dry run
https://github.com/logto-io/logto/actions/workflows/close-stale.yml
> chore: create close-stale.yml

- packages/connector-aliyun-dm/src/index.ts
- packages/connector-aliyun-sms/src/index.ts
- packages/connector-sendgrid-mail/src/index.ts
- packages/connector-smtp/src/index.ts
- packages/connector-twilio-sms/src/index.ts
Fix params order of passwordless connectors' sendMessageBy() method.
N/A
> chore(connector): fix methods params order

- .github/workflows/integration-test.yml
- packages/core/src/env-set/index.ts
- packages/core/src/middleware/koa-auth.test.ts
- packages/core/src/middleware/koa-auth.ts
- Support integration test env config
- Prepack project before run integration test
- Let integration test service run under integration test config.
Tested in ci and UT passed.
> feat(core): support integration test env config

- packages/integration-tests/package.json
- packages/schemas/package.json
- pnpm-lock.yaml
> chore(deps): upgrade ts-node

- packages/integration-tests/package.json
- packages/integration-tests/src/api.ts
- packages/integration-tests/src/constants.ts
- packages/integration-tests/tests/applications.test.ts
- packages/integration-tests/tests/username-password-flow.test.ts
- pnpm-lock.yaml
test(console): integration tests for applications
Integration tests passed.
> test(console): integration tests for applications

- .github/CONTRIBUTING.md
to clarify about signed commit and commit message
N/A
> chore: update contributing guideline

- .github/workflows/update-pr-metadata.yml
- .github/workflows/upload-annotations.yml
to unblock some workflows
pending new workflow runs
> ci: update workflow permission

- packages/integration-tests/src/utils.ts
- packages/integration-tests/tests/api-resources.test.ts
test(console): integration tests for api resources
Integration tests passed.
> test(console): integration tests for api resources

- packages/integration-tests/src/connector-api.ts
- packages/integration-tests/tests/connectors.test.ts
Integration tests: List connectors after initializing a new Logto instance and before manually setting up any connector.
There should be no connectors, or all default connectors should be disabled.
Ditto
> test: integration test for connector list before manually setting up any connector

- .github/workflows/pen-tests.yml
use zap full scan directly since it won't take long
https://github.com/logto-io/logto/runs/7442774835?check_suite_focus=true
> ci: use zap full scan

- packages/integration-tests/src/connector-api.ts
- packages/integration-tests/tests/connectors.test.ts
Integration tests: set up a social connector.
Ditto
> test: integration test for setting up a social connector

- packages/integration-tests/src/constants.ts
- packages/integration-tests/tests/username-password-flow.test.ts
We should not assume the created user has an "admin" role name, so we should use the demo app instead because a user without an "admin" role name can not sign in to the admin console application.
CI
> fix(test): use demo app to test username-password flow in integration test

- packages/integration-tests/tests/sign-in-experience.test.ts
test: integration tests for sign-in experience
LOG-3774: Setup Connectors in Sign-In Experience (on the connector's tests ready, for not sure what connector can be tested)
> test: integration tests for sign-in experience

- packages/integration-tests/tests/applications.test.ts
refactor: application integration tests
Integration tests passed.
> refactor(test): integration tests for applications

- packages/ui/src/hooks/use-social-landing-handler.ts
- packages/ui/src/pages/SocialLanding/index.test.tsx
Simple PR
protect window.location xss
test locally
@logto-io/eng
> fix(ui): protect window.location xss

- packages/integration-tests/tests/connectors.test.ts
Integration tests for setting up an SMS connector and changing to another SMS connector.
- There should be exactly one enabled SMS connector after changing to another SMS connector.
Ditto
> test: integration tests for setting up and changing SMS conectors

- packages/demo-app/src/App.tsx
Hide username if not exists on demo-app congrats page.
> fix(demo-app): hide username if not exists

- packages/integration-tests/tests/connectors.test.ts
Integration tests for setting up and changing email connectors
- There should be exactly one enabled email connector after changing to another email connector.
Ditto
> test: integration tests for setting up and changing email connectors

- packages/integration-tests/tests/connectors.test.ts
Integration tests: validate connector configs
Ditto
> test: integration tests for validating connector configs

- packages/integration-tests/src/connector-api.ts
- packages/integration-tests/tests/connectors.test.ts
Integration tests: delete connectors
Ditto
> test: integration tests for deleting connectors

- packages/core/src/routes/me.ts
GET /me to fetch current user data
> feat(core): api GET /me

- packages/integration-tests/tests/me.test.ts
test: integration tests for `/me`
None.
> test: integration tests for `/me`

- packages/integration-tests/src/helper.ts
- packages/integration-tests/tests/me.test.ts
- packages/integration-tests/tests/users.test.ts
test: integration tests for users
None.
> test: integration tests for users

- packages/console/src/pages/Connectors/components/Guide/index.tsx
Previously there was a nested form issue in connector creation guide. The guide `<Step>` component used to be wrapped by a form, and its inner component `<SenderTester>` also has a form built inside. Thus, the nested structure.
This PR refactored the Guide component by moving the outer form inside the `<Step>`.
> refactor(console): refactor connector guide to avoid nested forms

- packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
Improve `hasUnsavedChanges` logic in `ConnectorContent` component. Use form `isDirty` state instead.
> refactor(console): improve hasUnsavedChanges by leveraging form isDiry state

- packages/integration-tests/tests/connectors.test.ts
Integration tests: list connectors after manually setting up connectors
- The result of listing connectors should be same as the result of updating connectors above.
Ditto
> test: integration tests for list connectors after manually setting up connectors

- .github/workflows/main.yml
- .github/workflows/upload-annotations.yml
> ci: use macOS for annotations

- packages/core/src/routes/swagger.test.ts
- packages/core/src/routes/well-known.test.ts
Remove unnecessary `expect.objectContaining(…)`
Reference: jest [expect.toMatchObject](https://jestjs.io/docs/27.x/expect#tomatchobjectobject)
Pass existing tests.
> refactor(test): remove unnecessary expect.objectContaining

- packages/console/src/components/CodeEditor/index.module.scss
Remove this annoying horizontal scrollbar from code editor
> fix(console): remove annoying horizontal scrollbar from code editor

- packages/integration-tests/tests/connectors.test.ts
Refactor integration tests: list connectors after manually setting up connectors
- Remove duplicated code.
References:
- [Jest matching objects in array](https://medium.com/@andrei.pfeiffer/jest-matching-objects-in-array-50fe2f4d6b98)
- [expect.arrayContaining](https://jestjs.io/docs/expect#expectarraycontainingarray)
- [expect.objectContaining](https://jestjs.io/docs/27.x/expect#expectobjectcontainingobject)
> refactor(test): integration tests for list connectors after manually setting up connectors

- packages/connector-alipay-native/src/index.test.ts
- packages/connector-alipay-web/src/index.test.ts
- packages/connector-aliyun-dm/src/index.test.ts
- packages/connector-aliyun-sms/src/index.test.ts
- packages/connector-apple/src/index.test.ts
- packages/connector-facebook/src/index.test.ts
- packages/connector-github/src/index.test.ts
- packages/connector-google/src/index.test.ts
- packages/connector-sendgrid-mail/src/index.test.ts
- packages/connector-smtp/src/index.test.ts
- packages/connector-twilio-sms/src/index.test.ts
- packages/connector-wechat-native/src/index.test.ts
- packages/connector-wechat-web/src/index.test.ts
- packages/core/src/routes/connector.ts
Fix connectors' validator type in UTs.
N/A
> chore(connector): fix connector validator type

- .github/workflows/close-stale.yml
update exempt label config to match our latest labels
N/A
> ci: update exempt labels

- packages/console/src/pages/Connectors/components/Guide/index.tsx
- packages/phrases/package.json
- packages/phrases/src/index.ts
- packages/phrases/src/types.ts
- pnpm-lock.yaml
Refactor the logic of getting the connector's name of the preferred language.
N/A
> refactor(console): refactor the logic of getting connector name in preferred language

- .github/workflows/codeql-analysis.yml
to make it works for manual publish
pending publish
> ci: trigger CodeQL workflow on publish

- packages/phrases/src/locales/en/translation/demo-app.ts
- packages/phrases/src/locales/zh-cn/translation/demo-app.ts
message content update
Update the demo app notification message content
test locally
@eng
> chore(demo-app): message content update

- packages/integration-tests/src/helper.ts
- packages/integration-tests/tests/dashboard.test.ts
- packages/integration-tests/tests/username-password-flow.test.ts
test: integration tests for dashboard
Tests passed.
> test: integration tests for dashboard

- packages/integration-tests/package.json
Run integration test serially to avoid concurrency problems.
Refer to: https://jestjs.io/docs/cli#--runinband
CI
> fix(test): run integration test serially

- packages/integration-tests/tests/logs.test.ts
test: integration tests for logs
Tests passed.
> test: integration tests for logs

- packages/connector-google/src/index.ts
- packages/connector-wechat-native/src/index.ts
- packages/connector-wechat-native/src/types.ts
- packages/connector-wechat-web/src/index.ts
- packages/connector-wechat-web/src/types.ts
Refactor to resolve complexity lint in connectors.
Passed UTs.
> refactor(connector): refactor to resolve complexity lint in connectors

- packages/integration-tests/src/connectors-mock.ts
- packages/integration-tests/tests/connectors.test.ts
- packages/integration-tests/tests/sign-in-experience.test.ts
test: integration tests for setting up sign-in methods
Tests passed.
> test: integration tests for setting up sign-in methods

- packages/core/src/middleware/koa-auth.ts
- packages/integration-tests/jest.setup.js
- packages/integration-tests/package.json
- pnpm-lock.yaml
- Add dotenv to the integration test project. So ENV Logto-Url can be managed easily. 
- development-user-id from the request header should have a higher priority
@xiaoyijun @gao-sun cc: @logto-io/eng 
test locally
> chore(test): add dotenv

- packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
fix(console): should not display unsaved changes alert on connector config updated
Test locally.
> fix(console): should not display unsaved changes alert on connector config updated

- packages/connector-facebook/src/index.test.ts
Connectors' names should be capitalized.
N/A
> chore(connector): connectors names should be capitalized

- packages/integration-tests/src/api/connector.ts
- packages/integration-tests/tests/connector.test.ts
Integration tests: 
- Send SMS or email test messages successfully.
- Fail to send SMS or email test messages due to the wrong config.
Ditto.
> test: integration tests for sending SMS or email test messages

- packages/core/src/middleware/koa-log.test.ts
Improve the coverage of koa-log.ts
> test(core): improve the coverage of koa-log

- packages/integration-tests/tests/connector.test.ts
Refactor the integration tests for the connector set-up flow.
- Remove duplicated code.
- Add necessary comment for why keep using real connectors for now.
Ditto
> refactor(test): connector set-up flow

- packages/console/package.json
- packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
- packages/console/src/pages/SignInExperience/components/Preview.tsx
- packages/phrases-ui/src/index.ts
- packages/phrases-ui/src/types.ts
- pnpm-lock.yaml
Split mainflow UI language options from the ones used in admin console, as they are having their own dedicated i18n phrase templates and will have mismatched language options in the future.
> refactor: split mainflow ui language options from admin console

- packages/integration-tests/tests/connector.test.ts
Rename the wrong variable.
No need.
> refactor(test): rename wrong variable

- packages/integration-tests/src/api/dashboard.ts
- packages/integration-tests/src/api/index.ts
- packages/integration-tests/src/api/logs.ts
- packages/integration-tests/src/api/me.ts
- packages/integration-tests/src/helpers.ts
- packages/integration-tests/tests/dashboard.test.ts
- packages/integration-tests/tests/logs.test.ts
- packages/integration-tests/tests/me.test.ts
refactor log, dashboard, me
Refactor log, dashboard, and me test cases.
test locally
@logto-io/eng @xiaoyijun
> refactor(test): refactor log, dashboard, me

- packages/integration-tests/src/api/index.ts
- packages/integration-tests/src/api/wellknown.ts
- packages/integration-tests/src/client/index.ts
- packages/integration-tests/src/constants.ts
- packages/integration-tests/tests/wellknown.test.ts
Add wellknown api integration test
get sign-in-exp for admin console and general app.
log-3670
log-3671
test locally
@logto-io/eng
> test(test): add wellknown integration test

- packages/integration-tests/tests/connector.test.ts
Inline unnecessary functions (mixed up with some `expect` checks) for testing connector set-up flow
- To make the code easier to understand and avoid misleading.
Pass existing tests.
> refactor(test): inline unnecessary functions for testing connector set-up flow

- README.md
- packages/phrases-ui/src/types.ts
- packages/phrases/src/types.ts
- add "Language support" section
- update order and wording accordingly
N/A
> chore: update README and language options

- packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/next_zh-cn.mdx
- packages/console/src/pages/Applications/components/Guide/index.tsx
- packages/console/src/pages/Applications/components/GuideHeader/index.tsx
- packages/console/src/types/applications.ts
- packages/phrases/src/locales/en/translation/admin-console/applications.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
- packages/shared/package.json
- packages/shared/src/utilities/index.ts
- packages/shared/src/utilities/string.ts
- pnpm-lock.yaml
Add Next.js integration guide in admin console
> feat(console): add Next.js integration guide in admin console

- .github/workflows/close-stale.yml
align pr and issue stale time since we have "exempt labels"
N/A
> chore: align stale time

- packages/integration-tests/src/client/index.ts
- packages/integration-tests/src/helpers.ts
- packages/integration-tests/tests/get-access-token.test.ts
Add get access token flow test.
test locally
@logto-io/eng
> test(test): add get access token flow test

- packages/integration-tests/src/client/index.ts
- packages/integration-tests/tests/session.test.ts
add sign-in then sign-out test
test locally
@logto-io/eng
> test(test): add sign-in then sign-out test

- packages/integration-tests/src/__mocks__/connectors-mock.ts
- packages/integration-tests/tests/connector.test.ts
- packages/integration-tests/tests/sign-in-experience.test.ts
Replace the Facebook connector with the mock social connector in the integration test for connector set-up flow and sign-in experience
> refactor(test): replace facebook connector with mock social connector

- packages/shared/src/utilities/color.ts
Fix dark color generator.
Local tested.
> fix(shared): fix dark color generator

- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko-kr/index.ts
- packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
chore(console): remove unused language texts in i18n locale files
Test locally.
> chore(console): remove unused language texts in i18n locale files

- .github/workflows/integration-test.yml
- link-mock-connectors.sh
- package.sh
Update `package.json` and `pnpm-lock.json` in the `integration-test` GitHub 
workflow to install mock connectors for integration tests only.
> refactor(test): refactor integration-test workflow to link mock connectors

- packages/connector-mock-social/src/index.ts
- packages/integration-tests/src/api/session.ts
- packages/integration-tests/src/client/index.ts
- packages/integration-tests/tests/social-session.test.ts
add social integration tests
test locally
@xiaoyijun cc: @logto-io/eng
> test(test): add social integration tests

- packages/integration-tests/src/api/admin-user.ts
- packages/integration-tests/src/helpers.ts
- packages/integration-tests/tests/admin-user.test.ts
test: integration test for deleting user identities
Tests passed
> test: integration test for deleting user identities

- packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
Update assumed web app running port number to 3000 in all web SDK integration guides, as 3000 is the default port number for most of the frameworks.
> chore(console): update default app running port number from 1234 to 3000

- packages/console/package.json
- packages/demo-app/package.json
- pnpm-lock.yaml
Bump React SDK version to 1.0.0-beta.0
> chore: bump react sdk version to 1.0.0-beta.0

- packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/next_zh-cn.mdx
- packages/console/src/pages/Applications/components/Guide/index.tsx
Add app secret to application guide (express and next.js)
> feat(console): add app secret to guide

- packages/connector-alipay-native/jest.config.ts
- packages/connector-alipay-web/jest.config.ts
- packages/connector-aliyun-dm/jest.config.ts
- packages/connector-aliyun-sms/jest.config.ts
- packages/connector-apple/jest.config.ts
- packages/connector-azuread/jest.config.ts
- packages/connector-facebook/jest.config.ts
- packages/connector-github/jest.config.ts
- packages/connector-google/jest.config.ts
- packages/connector-sendgrid-mail/jest.config.ts
- packages/connector-smtp/jest.config.ts
- packages/connector-twilio-sms/jest.config.ts
- packages/connector-wechat-native/jest.config.ts
- packages/connector-wechat-web/jest.config.ts
- packages/core/jest.config.ts
Since [`testEnvironment`](https://jestjs.io/docs/configuration#testenvironment-string) defaults to `'node'` in jest configs, simplify the unnecessary code for merging it.
UTs
> refactor: simplify jest.config.ts

- packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/next_zh-cn.mdx
Added the missing "Protect API routes and pages" section in Next.js integration guide.
> docs(console): update next.js integration guide

- packages/core/src/lib/social.ts
- packages/core/src/middleware/koa-pagination.ts
- packages/core/src/queries/log.ts
- packages/core/src/utils/oidc-provider-event-listener.ts
- packages/schemas/src/types/log.ts
- packages/ui/src/types/index.ts
Fix the `eslint` issues about non-consistent type definitions.
UTs & Locally tested AC pages.
> refactor(core,schemas,ui): fix non-consistent type definitions

- packages/core/jest.setup.ts
- packages/core/src/env-set/oidc.test.ts
- packages/core/src/env-set/oidc.ts
- packages/core/src/env-set/utils.ts
- packages/core/src/middleware/koa-auth.ts
- packages/core/src/oidc/init.ts
- packages/core/src/utils/jwks.ts
- support signing key rotation
- use jwks to verify the access token in `koa-auth` middleware for now we can have multi keys in jwks.
- extend `exportJWK` method from `jose` to assign a `kid` to the exported jwk to support verifying the jwt token with `createLocalJWKSet` method.
- copy the `calculateKid` method from `node-oidc-provider` to support generating a jwk's `kid` as the `node-oidc-provider` does.
- refactor the `getStringArrayEnv` logic in `readCookieKeys`.
- Add `getStringArrayEnv` to `@silverhand/essentials` (LOG-3870)
Tests passed & Test locally
> feat(core): support signing key rotation

- packages/console/package.json
- packages/demo-app/package.json
- pnpm-lock.yaml
Bump React SDK to 1.0.0-beta.2 in admin console and demo app
> chore(console,demo-app): bump react sdk to 1.0.0-beta.2

- packages/console/src/index.tsx
- packages/demo-app/src/index.tsx
- packages/ui/src/index.tsx
Update react root render method align with react 18
test locally
@logto-io/eng
> fix(ui,console,demo-app): update react render method

- packages/core/src/env-set/oidc.ts
remove redundant try catch in `readPrivateKeys` for we don't need to wrap the errors when reading existing private key files.
UT passed.
> chore(core): remove redundant try catch in `readPrivateKeys`

- packages/console/src/components/AppContent/components/UserInfo/index.tsx
Removed an unused hook dependency
> chore(console): cleanup unused code

- packages/core/src/utils/id.ts
> refactor(core): update app secret length to 21

- packages/core/src/middleware/koa-root-proxy.ts
- packages/core/src/middleware/koa-spa-session-guard.ts
- packages/core/src/middleware/koa-welcome-proxy.test.ts
- packages/core/src/middleware/koa-welcome-proxy.ts
fix ac & ui proxy redirect logic under subpath deployment
Instead of redirecting to the root path, should read the endpoint from envSet. 
test locally
@logto-io/eng
> fix(core): fix ac & ui proxy under subpath deployment

- .github/workflows/update-pr-metadata.yml
fix pr assignee since we changed to `pull_request_target` trigger
CI
> ci: fix pr assignee

- packages/core/package.json
- packages/core/src/oidc/init.ts
- pnpm-lock.yaml
- enable OIDC userinfo endpoint
- differentiate ID Token and userinfo endpoint claims, make userinfo endpoint returns complete user data
> feat(core): enable userinfo endpoint

- packages/connector-google/README.md
docs(connector): change redirect uri prefix to `endpoint` on google connector readme file
N/A
> docs(connector): change redirect uri prefix to `endpoint` on google connector readme file

- packages/core/src/routes/init.ts
- packages/core/src/routes/session/index.test.ts
- packages/core/src/routes/session/index.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/social.test.ts
- packages/core/src/routes/session/social.ts
- packages/core/src/routes/session/username-password.test.ts
- packages/core/src/routes/session/username-password.ts
- reorg the file structure, no logic update
- use `session/index.ts` as the main entry and load other routes inside
UT + CI should be good
> refactor(core): session routes

- packages/core/src/routes/types.ts
refactor(core): flatten router parameter context types
Test locally & UTs passed.
> refactor(core): flatten router parameter context types

- packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
- packages/console/src/pages/Applications/components/GuideHeader/index.tsx
Add express integration guide in console.
> feat(console): express integration guide

- packages/core/src/routes/session/index.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/social.test.ts
- packages/core/src/routes/session/social.ts
- packages/core/src/routes/session/username-password.test.ts
- packages/core/src/routes/session/username-password.ts
- packages/core/src/routes/session/utils.ts
replace hard-coded duplicate strings with generated consts in session routes
UT + CI
> refactor(core): use consts for session prefix

- packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
As @BTX26 said, in AC's SDK guide, change step title to sentence case.
Local preview
> fix(console): change step title to sentence case

- packages/core/src/routes/connector.ts
- packages/integration-tests/tests/api/session.test.ts
1. Fix IT description.
2. Fix the bug that fetched the wrong property when enabling/disabling connectors.
UT, IT
> fix(core): fix IT description and undestructure error

- packages/core/src/__mocks__/connector.ts
- packages/core/src/connectors/consts.ts
- packages/core/src/connectors/index.test.ts
- packages/core/src/connectors/index.ts
- packages/core/src/connectors/types.ts
- packages/core/src/lib/passcode.test.ts
- packages/core/src/lib/passcode.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
- packages/core/src/routes/connector.update.test.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/social.test.ts
- packages/core/src/routes/session/social.ts
- packages/core/src/routes/sign-in-experience.ts
- packages/core/src/routes/well-known.test.ts
- packages/core/src/routes/well-known.ts
Rename logtoConnector.db as logtoConnector.dbEntry.
UT and IT.
> chore(connector): rename db in logto connector

- packages/connector-alipay-native/src/index.ts
- packages/connector-alipay-native/src/mock.ts
- packages/connector-alipay-native/src/utils.test.ts
- packages/connector-alipay-native/src/utils.ts
- packages/connector-alipay-web/src/constant.ts
- packages/connector-alipay-web/src/mock.ts
- packages/connector-alipay-web/src/utils.test.ts
Fix text encoding identifier cases. (use lower case 'utf8')
N/A
> chore(connector): fix text encoding identifier cases

- packages/connector-core/src/types.ts
Use literal enum for ConnectorErrorCodes.
UT and IT.
> chore(connector): use literal enum for ConnectorErrorCodes

- packages/console/src/scss/details.module.scss
Fix detail page height in small size window.
> style(console): fix detail page height in small window

- packages/connector-alipay-native/package.json
- packages/connector-alipay-web/package.json
- packages/connector-aliyun-dm/package.json
- packages/connector-aliyun-sms/package.json
- packages/connector-apple/package.json
- packages/connector-azuread/package.json
- packages/connector-facebook/package.json
- packages/connector-google/package.json
- packages/connector-mock-email/package.json
- packages/connector-mock-sms/package.json
- packages/connector-mock-social/package.json
- packages/connector-sendgrid-mail/package.json
- packages/connector-twilio-sms/package.json
- packages/connector-wechat-native/package.json
- packages/connector-wechat-web/package.json
- pnpm-lock.yaml
Remove unused dependency `@logto/shared` from related connectors.
UTs
> chore(connector): remove unused shared dep

- packages/connector-core/package.json
- packages/shared/package.json
- remove `private: true` in `@logto/shared`
- change `@logto/shared` and `@logto/connector-core` license to MIT
- add publishConfig to explicitly indicate package access
N/A
> refactor(shared,connector-core): prepare for publishing

- packages/connector-core/package.json
- packages/connector-core/src/types.ts
- packages/console/src/hooks/use-user-preferences.ts
- packages/console/src/i18n/init.ts
- packages/console/src/pages/Connectors/components/Guide/index.tsx
- packages/console/src/pages/Settings/index.tsx
- packages/console/src/pages/SignInExperience/components/Preview.tsx
- packages/console/src/pages/SignInExperience/types.ts
- packages/core/src/__mocks__/sign-in-experience.ts
- packages/core/src/routes/sign-in-experience.guard.test.ts
- packages/core/src/utils/zod.ts
- packages/demo-app/src/i18n/init.ts
- packages/phrases-ui/package.json
- packages/phrases-ui/src/index.ts
- packages/phrases-ui/src/types.ts
- packages/phrases/package.json
- packages/phrases/src/index.ts
- packages/phrases/src/types.ts
- packages/schemas/src/foundations/jsonb-types.ts
- packages/schemas/src/seeds/setting.ts
- packages/schemas/src/seeds/sign-in-experience.ts
- packages/shared/package.json
- packages/shared/src/index.ts
- packages/shared/src/language.ts
- packages/ui/src/__mocks__/logto.tsx
- packages/ui/src/components/Button/SocialLinkButton.tsx
- packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
- packages/ui/src/types/index.ts
- pnpm-lock.yaml
Rename type `Language` to `LanguageKey` and move to `shared`, so that connectors can use them directly.
UTs
> refactor(phrases,shared,connector-core): move language key to shared

- packages/connector-alipay-native/package.json
- packages/connector-alipay-web/package.json
- packages/connector-aliyun-dm/package.json
- packages/connector-aliyun-sms/package.json
- packages/connector-apple/package.json
- packages/connector-azuread/package.json
- packages/connector-facebook/package.json
- packages/connector-github/package.json
- packages/connector-google/package.json
- packages/connector-kakao/package.json
- packages/connector-mock-email/package.json
- packages/connector-mock-sms/package.json
- packages/connector-mock-social/package.json
- packages/connector-sendgrid-mail/package.json
- packages/connector-smtp/package.json
- packages/connector-twilio-sms/package.json
- packages/connector-wechat-native/package.json
- packages/connector-wechat-web/package.json
- pnpm-lock.yaml
Use [ncc](https://github.com/vercel/ncc) to build and package connector into a single bundle, then we can run connector's code without `npm install` which may cause long time and is unstable in some environments.
Also, remove "private: true" to get ready to publish.
No needed.
> build(connector): use ncc to package connector

- packages/connector-alipay-native/package.json
- packages/connector-alipay-web/package.json
- packages/connector-aliyun-dm/package.json
- packages/connector-aliyun-sms/package.json
- packages/connector-apple/package.json
- packages/connector-azuread/package.json
- packages/connector-facebook/package.json
- packages/connector-github/package.json
- packages/connector-google/package.json
- packages/connector-kakao/package.json
- packages/connector-mock-email/package.json
- packages/connector-mock-sms/package.json
- packages/connector-mock-social/package.json
- packages/connector-sendgrid-mail/package.json
- packages/connector-smtp/package.json
- packages/connector-twilio-sms/package.json
- packages/connector-wechat-native/package.json
- packages/connector-wechat-web/package.json
> refactor(connector): update access configs

- .github/workflows/integration-test.yml
use ikalnytskyi/action-setup-postgres to setup postgres avoid `cmd not found` issues in macOS
CI
> chore: fix postgres setup in integration test

- packages/integration-tests/jest.setup.js
- packages/integration-tests/src/api/api.ts
test: increase integration test case timeout to 10s
CI
> test: increase integration test case timeout to 10s

- package.json
Remove `--incremental` temporarily to resolve build error when executing `pnpm dev`.
This flag will be added back once #1839 and #1866 are merged
> fix: remove `--incremental` to temporarily fix `pnpm dev`

- .github/workflows/deploy-dev.yml
In deploy dev, run command to add official connectors
Need to merge to master to run this workflow.
> ci: add official connectors for dev server

- Dockerfile
add official connectors for dockerfile
Tested in gitpod: build image and run
> build: add official connectors for dockerfile

- packages/console/package.json
- packages/console/src/components/AppContent/components/UserInfo/index.tsx
- packages/demo-app/package.json
- packages/demo-app/src/App.tsx
- pnpm-lock.yaml
Bump Logto React SDK version to beta.3
> chore(console,demo-app): bump react sdk version to beta.3

- packages/console/src/assets/docs/tutorial/integrate-sdk/go-web.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/go-web_zh-cn.mdx
- packages/console/src/pages/Applications/components/Guide/index.tsx
- packages/console/src/pages/Applications/components/GuideHeader/index.tsx
- packages/console/src/types/applications.ts
docs: go web app integration guide (zh-cn)
Test locally
> docs: go web app integration guide

- packages/console/src/components/CodeEditor/index.tsx
When pressing the tab in the code editor, add 4 spaces instead of moving to the next control.
> feat(console): press tab to insert 2 spaces in code editor (#1871)

- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
Update the ui content capitalization
Tested locally
> chore(phrases): update admin console phrases

- packages/core/src/connectors/add-connectors.ts
Fetch official connectors list from npm, this will be more accurate, since we will download connector from npm too.
> fix: fetch connectors list from npm

- packages/console/src/hooks/use-connector-groups.ts
- packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
- packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.tsx
- packages/console/src/pages/ConnectorDetails/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
- packages/console/src/pages/Connectors/components/Guide/index.tsx
- packages/console/src/pages/SignInExperience/components/ConnectorSetupWarning.tsx
- packages/console/src/pages/SignInExperience/components/Preview.tsx
- packages/console/src/pages/UserDetails/components/UserConnectors.tsx
- packages/console/src/types/connector.ts
- packages/core/src/routes/connector.ts
- packages/integration-tests/src/api/connector.ts
- packages/schemas/src/types/connector.ts
Rename `ConnectorDto` to `ConnectorResponse`.
UTs and ITs.
> chore(schemas,core,console): rename ConnectorDto to ConnectorResponse

- packages/console/package.json
- packages/console/src/components/AppContent/components/UserInfo/index.tsx
- packages/demo-app/package.json
- packages/demo-app/src/App.tsx
- packages/integration-tests/jest.setup.js
- packages/integration-tests/package.json
- packages/integration-tests/src/client/index.ts
- packages/integration-tests/src/client/storage.ts
- packages/integration-tests/src/helpers.ts
- packages/integration-tests/tests/api/session.test.ts
- packages/integration-tests/tests/api/social-session.test.ts
- pnpm-lock.yaml
Downgrade SDK version from 1.0.0-beta.3 to 1.0.0-beta.2, in order to avoid sign-in issues caused by `async isAuthenticated()`
> fix: downgrade to sdk 1.0.0-beta.2

- .github/workflows/integration-test.yml
macOS runner poor performance
CI
> chore: update integration test workflow

- packages/console/src/assets/docs/tutorial/integrate-sdk/go-web.mdx
- packages/console/src/assets/docs/tutorial/integrate-sdk/go-web_zh-cn.mdx
docs: remove `persistAccessToken` from go web docs
Test locally.
> docs: remove `persistAccessToken` from go web docs

- packages/console/package.json
- packages/console/src/components/AppContent/components/UserInfo/index.tsx
- packages/console/src/components/AppContent/index.tsx
- packages/demo-app/package.json
- packages/demo-app/src/App.tsx
- packages/integration-tests/package.json
- packages/integration-tests/src/client/index.ts
- packages/integration-tests/src/client/storage.ts
- packages/integration-tests/src/helpers.ts
- packages/integration-tests/tests/api/session.test.ts
- packages/integration-tests/tests/api/social-session.test.ts
- pnpm-lock.yaml
> chore: bump to js sdk 1.0.0-beta.4

- packages/console/src/components/AppContent/index.tsx
Fix the bug that old value flashes back when saving form changes
> fix(console): old value does not flash back on saving form

- packages/console/package.json
- packages/demo-app/package.json
- packages/integration-tests/package.json
- pnpm-lock.yaml
Bump to SDK v1.0.0-beta.5 and fix a potential sign-in problem (Error: state mismatched)
> chore: bump sdk to 1.0.0-beta.5

- packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.test.tsx
- packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
- packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.tsx
- packages/ui/src/containers/SocialSignIn/SocialSignInList/index.tsx
- packages/ui/src/containers/SocialSignIn/SocialSignInPopUp/index.tsx
- packages/ui/src/hooks/use-social.ts
- packages/ui/src/pages/SignIn/registry.tsx
- packages/ui/src/types/index.ts
- packages/ui/src/utils/social-connectors.test.ts
- packages/ui/src/utils/social-connectors.ts
Check connector-related types and eliminate redundancy.
UTs and ITs.
> chore: check connector related types and eliminate redundancy

- packages/ui/src/components/Input/index.module.scss
- packages/ui/src/components/Toast/index.module.scss
- packages/ui/src/components/Toast/index.test.tsx
- packages/ui/src/components/Toast/index.tsx
- packages/ui/src/containers/AppContent/index.tsx
- packages/ui/src/scss/normalized.scss
Refactor toast using react modal. Clean up some custom tweak code of toast shading effect. Use ReactModal instead. 
Also update the element focus outline, instead of the agent default, and make it use primary color align with our input focus style. 
ut case updated.
test locally. 
@logto-io/eng @logto-io/mandatory-reviewers
> refactor(ui): refactor toast

- packages/connector-core/src/types.ts
Update GetUserInfo to accept possible boolean, or number typed values.
N/A
> chore: update GetUserInfo to accept possible boolean or number typed values

- packages/shared/src/utilities/index.ts
Expose fallback() from shared/utilities/zod.ts.
N/A
> chore: expose fallback() from shared/utilities/zod

- packages/console/src/consts/index.ts
- packages/console/src/hooks/use-api.ts
Increase ky request timeout to 20 seconds, in order to be able to run on some lower performant servers.
> chore(console): increase ky request timeout to 20s (fixes #1798)

- packages/console/src/pages/SignInExperience/components/Preview.tsx
Using fallback language in preview for the fixed language is deprecated.
Test locally.
> fix(console): use fallback language in preview

- .github/workflows/close-stale.yml
announcement issues are usually everlasting
N/A
> chore: exempt announcement issues from stale

- packages/console/package.json
- packages/core/package.json
- packages/demo-app/package.json
- packages/phrases-ui/package.json
- packages/phrases/package.json
- packages/schemas/package.json
- packages/ui/package.json
- pnpm-lock.yaml
Bump toolkit packages to 1.0.0-beta.13
N/A
> chore: bump toolkit to v1.0.0-beta.13

- packages/phrases-ui/src/locales/en.ts
- packages/phrases-ui/src/locales/fr.ts
- packages/phrases-ui/src/locales/ko-kr.ts
- packages/phrases-ui/src/locales/pt-pt.ts
- packages/phrases-ui/src/locales/tr-tr.ts
- packages/phrases-ui/src/locales/zh-cn.ts
- packages/ui/src/App.tsx
- packages/ui/src/pages/ResetPassword/index.module.scss
- packages/ui/src/pages/ResetPassword/index.test.tsx
- packages/ui/src/pages/ResetPassword/index.tsx
add reset password page
test locally
@logto-io/eng @logto-io/mandatory-reviewers
> feat(ui): add reset password page

- packages/ui/src/apis/api.test.ts
- packages/ui/src/apis/index.test.ts
- packages/ui/src/apis/reset-password.ts
- packages/ui/src/apis/utils.ts
- packages/ui/src/containers/ResetPassword/index.module.scss
- packages/ui/src/containers/ResetPassword/index.test.tsx
- packages/ui/src/containers/ResetPassword/index.tsx
- packages/ui/src/pages/ResetPassword/index.tsx
Add reset password form
Add reset password related APIs defination
ut added
test locally
> feat(ui): add reset password form

- packages/core/src/routes/session/forgot-password.test.ts
- packages/core/src/routes/session/forgot-password.ts
- packages/core/src/routes/session/index.ts
- packages/core/src/routes/session/middleware/koa-guard-session-action.ts
- packages/core/src/routes/session/utils.ts
- packages/schemas/src/types/log.ts
Add POST /session/forgot-password/{email,sms}/send-passcode and corresponding UTs.
Passed UTs and tested locally.
> feat(core): add POST /session/forgot-password/{email,sms}/send-passcode

- packages/ui/src/components/Button/index.test.tsx
- packages/ui/src/components/Button/index.tsx
- packages/ui/src/components/ConfirmModal/AcModal.tsx
- packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
- packages/ui/src/components/ConfirmModal/MobileModal.tsx
- packages/ui/src/containers/CreateAccount/index.tsx
- packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
- packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
- packages/ui/src/containers/ResetPassword/index.tsx
- packages/ui/src/containers/SocialCreateAccount/index.tsx
- packages/ui/src/containers/UsernameSignIn/index.tsx
- packages/ui/src/pages/ErrorPage/index.tsx
Refactored Button Component in packages/ui similar to the Button component in packages/console
(closes #1859)
Tested Locally.
> refactor: updated button component in packages/ui (closes #1859)

- packages/core/src/__mocks__/user.ts
- packages/core/src/routes/session/forgot-password.test.ts
- packages/core/src/routes/session/forgot-password.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko-kr/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/schemas/src/types/log.ts
Add POST /session/forgot-password/reset and corresponding UTs.
Passed UTs and tested all scenarios locally.
> feat(core): add POST /session/forgot-password/reset

- packages/core/src/migration/index.ts
- packages/core/src/migration/types.ts
When deploy migration, run each file as a transaction.
Local tested, for this "up" function:
```ts
export const up = async (connection: DatabaseTransactionConnection) => {
await connection.query(sql`INSERT INTO "_logto_configs" ("key", "value") VALUES ('foo', '{}');`);
// This line will fail, and the prev inserted value "foo" is expected to be removed after auto rollback
await connection.query(sql`INSERT INTO "_logto_configs" ("key1", "value") VALUES ('foo', '{}');`);
};
```
This will fail, but the database won't be dirty.
> feat(core): deploy migration in transaction mode

- packages/schemas/src/migrations/README.md
Add a simple readme for the migration files folder.
N/A
> docs(schemas): add migration file readme

- packages/console/src/components/ModalLayout/index.module.scss
- packages/console/src/components/ModalLayout/index.tsx
- packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/EditSection.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/EditSection.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/types.ts
- packages/console/src/pages/SignInExperience/components/index.module.scss
- packages/console/src/pages/SignInExperience/utilities.ts
- packages/console/src/scss/_dimensions.scss
- packages/phrases-ui/src/index.ts
- packages/phrases-ui/src/locales/fr.ts
- packages/phrases-ui/src/locales/ko-kr.ts
- packages/phrases-ui/src/locales/pt-pt.ts
- packages/phrases-ui/src/locales/tr-tr.ts
- packages/phrases-ui/src/locales/zh-cn.ts
- packages/phrases-ui/src/types.ts
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
feat: manage language
- Add Custom Language LOG-4146
- Delete Custom Language LOG-4150
- Unsaved Changes Alert LOG-4229
> feat(console): manage language

- packages/console/package.json
- packages/demo-app/package.json
- packages/integration-tests/package.json
- pnpm-lock.yaml
> chore: bump to js sdk 1.0.0-beta.8

- commitlint.config.js
> chore: update commitlint config

- packages/ui/src/components/ConfirmModal/index.tsx
- packages/ui/src/components/ConfirmModal/modalPromisify/index.test.tsx
- packages/ui/src/components/ConfirmModal/modalPromisify/index.tsx
- packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModal/index.tsx
- packages/ui/src/containers/TermsOfUse/TermsOfUseIframeModal/index.tsx
- packages/ui/src/containers/UsernameSignIn/index.test.tsx
- packages/ui/src/hooks/use-terms.ts
- packages/ui/src/types/index.ts
- packages/ui/src/utils/promisify.test.ts
- packages/ui/src/utils/promisify.ts
Refactor confirmModalPromisify
- add flattenPromise util method to simplify promise try.catch logic
- renames and extract termsOfUseModalPromisify to modalPromisify for future reference
- 
test locally
@logto-io/eng @logto-io/mandatory-reviewers
> refactor(ui): refactor confirmModalPromisify

- packages/core/package.json
- packages/core/src/lib/user.test.ts
- packages/core/src/lib/user.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/social.test.ts
- packages/core/src/routes/session/social.ts
- packages/core/src/routes/session/username-password.test.ts
- packages/core/src/routes/session/username-password.ts
Remove unnecessary updateLastSignInAt.
UTs.
> chore(core): remove unnecessary updateLastSignInAt

- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Display unsaved alert on custom phrases changed.
> feat(console): display unsaved alert on custom phrases changed

- packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
- packages/console/src/pages/SignInExperience/components/index.module.scss
- packages/console/src/pages/SignInExperience/types.ts
- packages/console/src/pages/SignInExperience/utilities.ts
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
This reverts commit 49b430394dc961451a6abca26a95ebba8d22f68c.
Revert "feat(console): auto detect language setting (#1941)" for this will be released in the language management feature.
Test locally.
> Revert "feat(console): auto detect language setting (#1941)"

- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/EditSection.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/types.ts
- packages/console/src/pages/SignInExperience/utilities.ts
refactor(console): use `Translation` type from `@logto/schemas`
Test locally.
> refactor(console): use `Translation` type from `@logto/schemas`

- .github/workflows/deploy-dev.yml
5s [may fail](https://github.com/logto-io/logto/actions/runs/3133489421/jobs/5086915856) but the dev is up
/
> chore: sleep 10s before dev health check

- packages/schemas/alterations/next-1663923211-machine-to-machine-app.ts
- packages/schemas/alterations/next-1664265197-custom-phrases.ts
Add `custom-phrases` alteration script
> chore(schemas): add custom phrases database alteration script

- packages/console/src/pages/ApplicationDetails/index.tsx
temp solution: open docs website when clicking "check guide" for M2M apps
> refactor(console): open docs website for M2M app guide

- packages/console/src/components/ModalLayout/index.module.scss
- packages/console/src/components/ModalLayout/index.tsx
- packages/console/src/components/RadioGroup/Radio.tsx
- packages/console/src/components/RadioGroup/index.module.scss
- packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
- packages/console/src/pages/Connectors/components/CreateForm/index.tsx
- packages/console/src/scss/_dimensions.scss
> style(console): new style for add connectors

- pnpm-lock.yaml
fixing build error
see parcel-bundler/parcel#8005
build ok
> chore: upgrade terser

- packages/core/jest.config.ts
- packages/core/src/middleware/koa-log.ts
- packages/schemas/src/types/log.ts
1. Refactor log types with Zod.
2. Ignore UTs of connectors since they should not be tested here.
N/A
> refactor(core,schemas): refactor log types with zod

- packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/types.ts
- packages/console/src/pages/SignInExperience/hooks/use-custom-phrases-context.ts
- packages/console/src/pages/SignInExperience/types.ts
feat(console): add custom language
- LOG-4147: Support Instant Search In Manage Language Editor Dropdown
- LOG-4276: Should be able to set custom language as default language
- LOG-4150: Delete Custom Language
Overview:
Updated dropdown items:
> feat(console): add custom language

- .github/workflows/release.yml
fix typo in release workflow, make it work!
/
> chore: fix typo in release workflow

- packages/core/src/queries/passcode.test.ts
- packages/core/src/queries/passcode.ts
fix deletePasscodeByIds bug
Before:
After:
UT case updated
Also tested using the local DB to delete some existing passcodes through API. 
@gao-sun cc: @wangsijie
> fix(core): fix deletePasscodeByIds bug

- packages/cli/package.json
- packages/cli/src/commands/database/index.ts
- packages/cli/src/commands/database/url.ts
- packages/cli/src/commands/install.ts
- packages/cli/src/config.ts
- packages/cli/src/index.ts
- packages/cli/src/utilities.ts
- pnpm-lock.yaml
- implement persist config for CLI
- implement database `get-url` and `set-url` command
- database `get-key` and `set-key` command for configuring keys in db
- migrate seed command from core
> feat(cli): database config command

- packages/cli/package.json
- packages/cli/src/commands/database/index.ts
- packages/cli/src/commands/database/key.ts
- packages/cli/src/commands/database/url.ts
- packages/cli/src/commands/install.ts
- packages/cli/src/database.ts
- packages/cli/src/include.d/slonik-interceptor-preset.d.ts
- packages/cli/src/index.ts
- packages/cli/src/queries/logto-config.ts
- packages/cli/src/utilities.ts
- packages/core/src/alteration/constants.ts
- packages/core/src/alteration/index.test.ts
- packages/core/src/alteration/index.ts
- packages/schemas/src/types/alteration.ts
- packages/schemas/src/types/index.ts
- packages/schemas/src/types/logto-config.ts
- pnpm-lock.yaml
- unify Logto config key/guard definitions in `schemas/src/types/logto-config.ts`
- add `logto db get-key` command to get config values by keys from database
- add `logto db set-key` command to set config value by key to database in a JSON favor
> feat(cli): get/set db config key

- packages/cli/package.json
- packages/cli/src/commands/database/index.ts
- packages/cli/src/commands/database/seed.ts
- packages/cli/src/database.ts
- packages/cli/src/utilities.ts
- pnpm-lock.yaml
- implement `db seed` command to:
- create database if not existed
- create tables and seed data
After `logto db seed`:
- new database created
- tables created
- data seeded
Manually make an error in the midway:
Check database, nothing changed
> feat(cli): `db seed` command

- packages/cli/package.json
`dev` -> `start:dev` to avoid unnecessary runs during root `pnpm dev` script
/
> chore: update cli script

- packages/cli/package.json
- packages/cli/src/commands/database/config.ts
- packages/cli/src/commands/database/index.ts
- rename database set/get by key to `get/set-config`
- remove `lg` alias
> refactor(cli): per review

- packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.tsx
- packages/console/src/pages/SignInExperience/hooks/use-language-editor-context.ts
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
- delete custom phrase
- disallow to select selected language items
> feat(console): delete custom phrase

- packages/console/package.json
- packages/console/src/components/AppContent/components/UserInfo/index.tsx
- packages/console/src/components/AppError/index.tsx
- packages/console/src/components/CopyToClipboard/index.tsx
- packages/console/src/components/DeleteConfirmModal/index.tsx
- packages/console/src/components/Drawer/index.tsx
- packages/console/src/components/Dropdown/DropdownItem.tsx
- packages/console/src/components/Dropdown/index.tsx
- packages/console/src/components/MultiTextInput/index.tsx
- packages/console/src/components/RadioGroup/Radio.tsx
- packages/console/src/components/Select/index.tsx
- packages/console/src/components/TabNav/TabNavItem.tsx
- packages/console/src/mdx-components/DetailsSummary/index.tsx
- packages/console/src/mdx-components/Step/index.tsx
- packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
- packages/console/src/pages/ConnectorDetails/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
- packages/console/src/pages/Connectors/components/CreateForm/index.tsx
- packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
- packages/console/src/pages/GetStarted/index.tsx
- packages/console/src/pages/SignInExperience/components/Preview.tsx
- packages/console/src/pages/UserDetails/components/UserConnectors.tsx
- packages/console/src/pages/UserDetails/index.tsx
- packages/console/src/pages/Users/components/CreateForm/index.tsx
- packages/console/src/pages/Users/index.tsx
- packages/console/src/utilities/a11y.ts
- pnpm-lock.yaml
add a11y lint to ac
test locally
lint should pass
> feat(console): add a11y lint to ac

- packages/core/src/__mocks__/sign-in-experience.ts
- packages/core/src/queries/sign-in-experience.test.ts
- packages/schemas/src/foundations/jsonb-types.ts
- packages/schemas/src/seeds/sign-in-experience.ts
- packages/schemas/tables/sign_in_experiences.sql
- packages/ui/src/__mocks__/logto.tsx
- packages/ui/src/types/index.ts
Update schema to fit SIE v2 design: https://www.figma.com/file/NJ7kpxondnIRMt3a933x4E/%F0%9F%8F%96%EF%B8%8F-%5BAC%5D-SIE-v2?node-id=215%3A7942
PLEASE NOTICE THAT this is merging to `feature/sie-v2` not `master`, so the project is not completed.
can not be tested now, wait for the incoming PRs.
> feat(schemas): add sie2 schema

- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.tsx
- packages/phrases/src/locales/en/translation/admin-console/general.ts
- packages/phrases/src/locales/fr/translation/admin-console/general.ts
- packages/phrases/src/locales/ko-kr/translation/admin-console/general.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
support searching in add language selector
> refactor(console): support searching in add language selector

- packages/cli/src/commands/database/seed/index.ts
- packages/cli/src/commands/database/seed/oidc-config.ts
- packages/cli/src/queries/logto-config.test.ts
- packages/cli/src/queries/logto-config.ts
- packages/schemas/src/types/logto-config.ts
to provide a better experience for config managing
> refactor(cli): flatten OIDC config keys

- packages/console/src/hooks/use-ui-languages.ts
- packages/console/src/pages/SignInExperience/components/Preview.tsx
refresh preview on custom phrases updated.
Test locally.
> refactor(console): refresh preview on custom phrases updated

- packages/ui/package.json
- packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
- packages/ui/src/components/Drawer/index.tsx
- packages/ui/src/components/Dropdown/DropdownItem.tsx
- packages/ui/src/components/Dropdown/index.tsx
- packages/ui/src/components/Input/PhoneInput.tsx
- packages/ui/src/components/NavBar/index.tsx
- packages/ui/src/components/Notification/index.tsx
- packages/ui/src/components/TermsOfUse/index.tsx
- packages/ui/src/components/Toast/index.tsx
- packages/ui/src/containers/CreateAccount/index.tsx
- packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
- packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
- packages/ui/src/containers/ResetPassword/index.tsx
- packages/ui/src/containers/SocialLanding/index.tsx
- packages/ui/src/containers/UsernameSignIn/index.tsx
- packages/ui/src/pages/Consent/index.tsx
- packages/ui/src/pages/ForgotPassword/index.tsx
- packages/ui/src/pages/Register/index.tsx
- packages/ui/src/pages/ResetPassword/index.tsx
- packages/ui/src/pages/SecondarySignIn/index.tsx
- packages/ui/src/utils/a11y.ts
- pnpm-lock.yaml
> feat(ui): add a11y support

- packages/console/src/components/RadioGroup/index.module.scss
> style(console): fix position of added tag

- packages/schemas/alterations/next-1665300135-sign-in-sign-up.ts
Add alteration script on the upgrade of sign in experience schema.
NOTICE that the old column will be removed in the end of this milestone.
Local tested with 2 cases:
> feat(schemas): add sie v2 alteration

- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/types.ts
- packages/core/src/routes/session/utils.ts
- packages/integration-tests/src/api/session.ts
- packages/integration-tests/tests/api/session.test.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko-kr/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/ui/src/apis/index.test.ts
- packages/ui/src/apis/register.ts
- packages/ui/src/apis/sign-in.ts
Sign-in and register flows mount on passwordless APIs.
Passed ITs and UTs.
> refactor(core,ui,test): sign-in and register flows mount on passwordless APIs

- commitlint.config.js
- for local commits the 100 max. limit still applies
- to allow the appending pr number for squash merges
> ci: increase commitlint length tolerance in CI

- README.md
make. it. faster.
https://gitpod.io/#https://github.com/logto-io/demo works, fast.
> chore: update GitPod demo link

- packages/core/src/__mocks__/sign-in-experience.ts
- packages/core/src/lib/sign-in-experience/index.ts
- packages/core/src/lib/sign-in-experience/sign-up.test.ts
- packages/core/src/lib/sign-in-experience/sign-up.ts
- packages/core/src/routes/sign-in-experience.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko-kr/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
Add validation for "sign up".
UTs.
> feat(core): validate sign up

- packages/core/src/routes/session/forgot-password.test.ts
- packages/core/src/routes/session/forgot-password.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/types.ts
- packages/core/src/routes/session/utils.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko-kr/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/ui/src/apis/forgot-password.ts
- packages/ui/src/apis/index.test.ts
Forgot password reuse passwordless verification flow.
> refactor(ui,phrases,core): forgot password reuse verification flow

- packages/core/src/routes/session/consts.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/types.ts
- packages/core/src/routes/session/utils.ts
Eliminate the barrier between sign-in and register verification sessions.
> refactor(core): sign-in and register flow share verification session

- merge-eslint-reports.js
> ci: fix eslint report script

- packages/core/src/__mocks__/sign-in-experience.ts
- packages/core/src/lib/sign-in-experience.test.ts
- packages/core/src/routes/custom-phrase.test.ts
- packages/core/src/routes/phrase.content-language.test.ts
- packages/core/src/routes/phrase.test.ts
- packages/schemas/src/foundations/jsonb-types.ts
- packages/schemas/src/seeds/sign-in-experience.ts
- packages/ui/src/__mocks__/logto.tsx
refactor: remove deprecated `fixedLanguage` property from `LanguageInfo`
UT passed.
> refactor: remove deprecated `fixedLanguage` property from `LanguageInfo`

- packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageItem.module.scss
Set language name font style to font-body-medium
> refactor(console): set language name font style to font-body-medium

- packages/demo-app/src/App.module.scss
- packages/demo-app/src/App.tsx
Improve button by adding `:focus` styles
Fix keyboard event handler by only accepting enter and spacebar taps
> refactor(demo-app): improve sign-out button in demo-app

- packages/core/src/__mocks__/sign-in-experience.ts
- packages/core/src/lib/sign-in-experience/index.ts
- packages/core/src/lib/sign-in-experience/sign-in.test.ts
- packages/core/src/lib/sign-in-experience/sign-in.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko-kr/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
Implement the validation of sign in configs: https://www.figma.com/file/NJ7kpxondnIRMt3a933x4E
UTs
> feat(core): validate sign in

- packages/console/src/components/Tooltip/index.module.scss
- packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
- packages/console/src/pages/Connectors/components/CreateForm/index.tsx
- packages/console/src/scss/_underscore.scss
- packages/ui/src/components/BrandingHeader/index.module.scss
- packages/ui/src/scss/_underscore.scss
For add connector modal: remove connector id and prevent text overflow
> fix(console): remove connector id and prevent text overflow

- packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
Stick the language details table header to the top
> refactor(console): stick the language details table header to the top

- packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageItem.module.scss
style(console): update font style of language item
> style(console): update font style of language item

- packages/console/src/components/Button/index.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/AddLanguageSelector.module.scss
- packages/demo-app/src/App.module.scss
- packages/ui/src/components/Button/index.module.scss
* Update default border color from `--color-outline` to `--color-border`
* Other related trivial style updates
> refactor: update default button border color

- packages/console/src/pages/SignInExperience/components/ManageLanguage/ManageLanguageButton.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguage/ManageLanguageButton.tsx
remove `margin-top` of the manage language button
> style(console): remove `margin-top` of the manage language button

- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko-kr/errors.ts
- packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
add translations for the manage language feature
> refactor(console): add translations for the manage language feature

- packages/cli/src/commands/database/alteration.test.ts
- packages/cli/src/commands/database/alteration.ts
- packages/cli/src/commands/database/alteration/index.test.ts
- packages/cli/src/commands/database/alteration/index.ts
- packages/cli/src/commands/database/alteration/type.ts
- packages/cli/src/commands/database/alteration/version.ts
- packages/cli/src/commands/install/index.ts
- packages/cli/src/index.ts
- packages/cli/src/package.json
- packages/cli/src/utilities.ts
- use simplified name as the option key of `install` command since
- yargs/yargs#1679
- prompt available versions and choose a target before proceeding alteration since there may be a gap between the Logto instance version and CLI version. to be refactored
- `deploy next` is available for developing, has to manually input
- update `-v` for a better output
version command
deploy next
deploy with prompt
deploy with no script found
> refactor(cli): update install, alteration, and version command

- .github/workflows/release.yml
to remove the `false` environment
https://github.com/logto-io/logto/actions/runs/3242783409/jobs/5316559491
this run doesn't show in [false env](https://github.com/logto-io/logto/deployments/activity_log?environment=false)
> ci: fix workflow env

- packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
- packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
style(console): fix clear button size to 16x16
> style(console): fix clear button size to 16x16

- packages/core/src/__mocks__/sign-in-experience.ts
- packages/core/src/routes/sign-in-experience.test.ts
- packages/core/src/routes/sign-in-experience.ts
The final part of new update SIE api.
UTs
> feat(core): update sie

- packages/console/src/components/Button/index.module.scss
Fix text button hover color from `focused-variant` to `hover-variant`.
> style(console): fix text button hover style

- packages/cli/src/commands/connector/add.ts
- packages/cli/src/commands/connector/index.ts
- packages/cli/src/commands/connector/list.ts
- packages/cli/src/commands/connector/remove.ts
- packages/cli/src/commands/connector/utils.ts
- `logto connector list`
- `logto connector remove`
> feat(cli): list & remove connectors

- .github/workflows/integration-test.yml
- .gitpod.yml
- Dockerfile
- package.json
- packages/cli/src/commands/connector/index.ts
- packages/cli/src/commands/install/index.ts
- packages/cli/src/commands/install/utils.ts
- packages/core/package.json
- pnpm-lock.yaml
- remove all cli-related scripts in `core`
- add `download-url` and support local path in order to enable multi-os integration tests.
- add `connectors` alias for connector command
- add cli scripts at project root
> feat(cli)!: add `download-url` option for install

- .github/workflows/commitlint.yml
- .github/workflows/main.yml
- .github/workflows/master-codecov-report.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/upload-annotations.yml
upgrade to v2 to follow to major-version-only convention
CI
> ci: upgrade node pnpm run steps

- .github/workflows/integration-test.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/upload-annotations.yml
- .gitpod.yml
- .husky/pre-commit
- Dockerfile
- package.json
- pnpm-lock.yaml
rip lerna, will remove the release script once we introduce changesets
CI, local dev, and precommit
> chore: remove lerna

- .github/workflows/publish.yml
fix publish script due to the [job failure](https://github.com/logto-io/logto/actions/runs/3264862246/jobs/5366170555).
> ci: fix publish script

- packages/cli/src/commands/database/alteration/version.ts
can a refactor or a fix, whatever you call it
> refactor(cli): supports `latest` version for db alteration 

- packages/core/src/cli/alteration.ts
- packages/schemas/alterations/next-1665300135-sign-in-sign-up.ts
Run alteration failed:
Inspect the data from the database:
Alteration succeed:
> fix(schemas): field name in sie db data type should be camel-case

- packages/cli/src/commands/database/config.ts
- packages/cli/src/commands/database/index.ts
reorg `set-config` `get-config` to `config <action>` to fit docs config
> refactor(cli): update config command

- packages/cli/src/commands/database/seed/index.ts
- packages/cli/src/queries/logto-config.ts
fix the type of the swe option, the original expression will always return true
> fix(cli): fix skip-when-exists option

- packages/console/src/components/RadioGroup/Radio.tsx
- packages/console/src/components/RadioGroup/index.module.scss
- packages/console/src/pages/Applications/components/CreateForm/index.module.scss
- packages/console/src/pages/Applications/components/CreateForm/index.tsx
- packages/console/src/pages/Applications/components/SdkSelector/index.module.scss
- packages/console/src/pages/Applications/components/TypeDescription/index.tsx
- packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
- packages/console/src/pages/Connectors/components/CreateForm/index.tsx
- packages/console/src/scss/_dimensions.scss
For new [design](https://www.figma.com/file/QcPmOptDCH1h8IaYUaYCZZ/%F0%9F%92%B0-%5BAC%5D-Supporting-more-Connectors-%26-SDK?node-id=162%3A11971): responsive modal layout, mainly for radio group.
> fix(console): responsive modal items layout

- packages/console/src/scss/normalized.scss
* Improve language selector dropdown by increasing scrollbar thumb to a minimum 40px.
> style(console): improve language selector dropdown styles

- packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageItem.tsx
refactor(console): avoid jumping when the language item is visible
> refactor(console): avoid jumping when the language item is visible

- package.json
- packages/cli/package.json
- packages/cli/src/commands/database/alteration/index.test.ts
- packages/cli/src/commands/database/alteration/index.ts
- packages/schemas/.gitignore
- packages/schemas/package.json
- packages/schemas/tsconfig.build.alterations.json
- remove `--incremental` for prepack command in dev script since prepack will remove all dist files make incremental meaningless
- add cli dev script
- move alteration dist to `alteration-js` to make it more clear
CI + Local `pnpm dev`. works as expected
> fix: alteration script in dev

- packages/cli/package.json
- packages/create/package.json
explicitly add `publishConfig` for public packages since they are scoped packages which default access is private
pending publish, should be good (hopefully, hopefully)
> fix: add publish config for public packages

- .github/workflows/main.yml
- Dockerfile
- packages/cli/src/commands/connector/utils.ts
- packages/cli/src/commands/database/alteration/version.ts
- packages/cli/src/commands/install/utils.ts
- packages/cli/src/utilities.ts
resolve LOG-4399
- fine-tune the CLI behavior when it's not in TTY
- add Docker build in main workflow
CI
now docker build [will fail](https://github.com/logto-io/logto/actions/runs/3275346595/jobs/5390072692) when the cli has no sufficient info
and connectors are added in successful Docker build
> ci: add docker build to main workflow

- packages/console/package.json
- packages/core/package.json
- packages/demo-app/package.json
- packages/phrases-ui/package.json
- packages/phrases/package.json
- packages/schemas/package.json
- pnpm-lock.yaml
chore: bump `@logto/language-kit` to `v1.0.0-beta.19`
Test locally.
> chore: bump `@logto/language-kit` to `v1.0.0-beta.19`

- docker-compose.yml
update commands to fit the latest version
> chore: update docker compose file

- packages/phrases-ui/package.json
- packages/phrases/package.json
- packages/schemas/package.json
- packages/shared/package.json
- packages go public for cli
- add missing files in `schemas`
> fix: make packages public

- .github/workflows/integration-test.yml
- packages/cli/src/database.ts
- packages/core/src/env-set/create-pool-by-env.ts
- packages/schemas/package.json
> refactor: require database name in URL

- packages/console/src/hooks/use-user-preferences.ts
refactor(console): remove deprecated `languageKeys`
Test locally.
> refactor(console): remove deprecated `languageKeys`

- packages/console/src/hooks/use-api.ts
Use react hook to get typescript support in `t` method.
> refactor: use hook for toastError in order to get type support

- docker-compose.yml
aww - i'm a fool
tested in gitpod, now the demo works
> ci: fix envrionment variable in docker compose

- .github/CONTRIBUTING.md
- packages/core/src/env-set/check-alteration-state.ts
- packages/schemas/alterations/README.md
update contributing content to reflect our status quo
/
> chore: update contributing

- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/username-password.test.ts
- packages/core/src/routes/session/username-password.ts
- packages/integration-tests/src/helpers.ts
- packages/integration-tests/tests/api/session.test.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko-kr/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
Add guards on sign up: only allow the configured sign up identifier.
UTs
> feat(core): guard sign up methods

- packages/ui/src/containers/AppContent/index.module.scss
- packages/ui/src/hooks/use-color-theme.ts
- packages/ui/src/scss/_desktop.scss
- packages/ui/src/scss/_mobile.scss
Pick up the latest MainFlow Design System update branding color token name.
test locally
> style(ui): update branding color token name

- packages/core/src/__mocks__/sign-in-experience.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/username-password.test.ts
- packages/core/src/routes/session/username-password.ts
- packages/core/src/routes/sign-in-experience.test.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko-kr/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/schemas/src/seeds/sign-in-experience.ts
limit sign in method according to SIE configs.
UTs.
> feat(core): limit sign in method

- renovate.json
add our monorepo package rules to renovate
pending renovate PR update
> chore: add renovate monorepo rules

- packages/ui/src/components/Button/index.module.scss
- packages/ui/src/components/Notification/index.module.scss
- packages/ui/src/containers/AppContent/index.module.scss
- packages/ui/src/scss/normalized.scss
fix test overflow issue
Before 
After:
test locally
> fix(ui): fix text overflow issue

- packages/ui/src/scss/_colors.scss
Add new color theme file according to the latest design
N/A not applied to any pages yet, will do the migration in the next PR
> style(ui): add new color theme file

- packages/ui/src/hooks/use-preview.ts
fix ac preview render delay bug when switching between platforms or thems
test locally
> fix(console): fix ac chunky preview experience

- packages/core/src/routes/well-known.test.ts
- packages/core/src/routes/well-known.ts
Let ac SIE language load from default SIE language settings.
Before it was hardcoded as en.
test locally.
> fix(core): let ac SIE language load from default SIE language settings

- packages/ui/src/hooks/use-preview.ts
page should render after language updates
test locally
@xiaoyijun
> fix(ui): fix prefiew render bug

- .changeset/README.md
- .changeset/config.json
- .github/CODEOWNERS
- .github/workflows/release.yml
- update changeset config and readme - make it more reasonable
- add code owner to changeset
pending practice
> ci: update changeset

- packages/ui/src/scss/_fonts.scss
> style(ui): add new font styling

- packages/console/src/pages/SignInExperience/components/AuthenticationForm.tsx
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
refactor(console): update enable create account phrases
> refactor(console): update enable create account phrases

- packages/console/src/components/ActionMenu/index.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/AddSignInMethodButton.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
- use `<ActionMenu />` in `AddSignInMethodButton`
- set min-width of dropdown to 208px
- support dropdown horizontal alignment and dropdown class name in the `ActionMenu` component
> refactor(console): add sign in method button

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/constants.ts
- packages/core/src/__mocks__/sign-in-experience.ts
- packages/core/src/lib/sign-in-experience/sign-in.test.ts
- packages/core/src/lib/sign-in-experience/sign-in.ts
- packages/core/src/lib/sign-in-experience/sign-up.test.ts
- packages/core/src/lib/sign-in-experience/sign-up.ts
- packages/core/src/routes/session/middleware/passwordless-action.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/username-password.test.ts
- packages/integration-tests/tests/api/session.test.ts
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
- packages/schemas/alterations/next-1665300135-sign-in-sign-up.ts
- packages/schemas/src/foundations/jsonb-types.ts
- packages/schemas/src/seeds/sign-in-experience.ts
- packages/ui/src/__mocks__/logto.tsx
rename phone signInMethods to sms
UT
> refactor(core): rename phone signInMethod to sms

- packages/phrases-ui/src/locales/zh-cn.ts
- packages/phrases/src/locales/zh-cn/errors.ts
Signed-off-by: Darcy Ye <darcyye@silverhand.io>
Update contents.
N/A
> chore(phrases): update contents

- packages/core/src/__mocks__/sign-in-experience.ts
- packages/core/src/routes/sign-in-experience.test.ts
- packages/core/src/routes/sign-in-experience.ts
- packages/schemas/src/seeds/sign-in-experience.ts
- packages/ui/src/__mocks__/logto.tsx
Guard on enable forgot password, require at least one passwordless connector.
UTs
> feat(core): enable forgot password check

- packages/ui/src/utils/a11y.ts
fix tab key not working bug
Issue: the submit button can not be focused using the keyboard tab key. 
Root cause:
i18nKeyboardHandler mistakenly blocked the key's default behavior. Should only run prevent default, if a key specific callback method is provided. 
test locally
> fix(ui): fix tab key not working bug

- packages/ui/src/components/Input/index.module.scss
Per our latest design. Renive the remove autofill styling. Use the default browser style
test locally
> style(ui): remove autofill styling

- packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.tsx
- packages/ui/src/utils/social-connectors.ts
fix apple logo not properly detected bug
test locally
> fix(ui): fix apple logo

- packages/console/src/hooks/use-api.ts
Fixed an issue in `useApi` hook that might cause component re-render.
> fix(console): useApi hook should not cause component re-render

- packages/ui/src/components/TextLink/index.module.scss
update link button styling
Test locally
> style(ui): update link button styling

- .github/workflows/main.yml
"The only reason you are not powerful enough is you didn't pay." - Pony Ma
CI
> chore: upgrade lint runners

- packages/ui/src/components/Notification/index.module.scss
- packages/ui/src/components/Notification/index.tsx
- packages/ui/src/scss/_colors.scss
update notification style
pick up the latest design:
test locally
> style(ui): update notification style

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignInForm.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SocialSignInForm.tsx
Provide default values for fields in the sign-up and sign-in forms to avoid getting an `undefined` value.
Test locally.
> fix(console): provide default values for fields in sign up and sign in forms

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/AddSignInMethodButton.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/AddButton.module.scss
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/AddButton.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/SelectedConnectorItem.module.scss
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/SelectedConnectorItem.tsx
refactor(console): add buttons in sie sign-up and sign-in form
- inline add button options
- make the <img /> fit the size of its parent `<div />` element.
Test locally.
> refactor(console): add buttons in sie sign-up and sign-in form

- packages/phrases-ui/src/locales/en.ts
- packages/phrases-ui/src/locales/fr.ts
- packages/phrases-ui/src/locales/ko.ts
- packages/phrases-ui/src/locales/pt-pt.ts
- packages/phrases-ui/src/locales/tr-tr.ts
- packages/phrases-ui/src/locales/zh-cn.ts
- packages/ui/src/containers/SignInMethodsLink/index.tsx
- packages/ui/src/containers/SocialCreateAccount/index.tsx
- packages/ui/src/containers/UsernameRegister/index.tsx
- packages/ui/src/pages/Register/Main.tsx
- packages/ui/src/pages/Register/index.module.scss
- packages/ui/src/pages/Register/index.test.tsx
- packages/ui/src/pages/Register/index.tsx
- packages/ui/src/pages/SignIn/Main.tsx
- packages/ui/src/pages/SignIn/index.tsx
Add primary register page
test locally
> refactor(ui): add primary register page

- .vscode/settings.json
- packages/core/src/middleware/koa-auth.ts
- packages/core/src/routes/authn.test.ts
- packages/core/src/routes/authn.ts
Implement per https://hasura.io/docs/latest/auth/authentication/unauthenticated-access/#webhooks
See test cases for details
UT + local API
> feat(core): hasura unauthed access support

- .gitpod.yml
> chore: fix gitpod config

- packages/core/src/routes/session/continue.test.ts
- packages/core/src/routes/session/continue.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/social.test.ts
- packages/core/src/routes/session/social.ts
- packages/core/src/routes/session/utils.ts
- packages/integration-tests/tests/api/dashboard.test.ts
- packages/integration-tests/tests/api/logs.test.ts
- packages/integration-tests/tests/api/social-session.test.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
After social register, continue to sign in:
- username
- email
- sms
UTs.
> feat(core): continue sign in with social

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignInForm.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
- packages/console/src/pages/SignInExperience/types.ts
- packages/console/src/pages/SignInExperience/utilities.ts
fix(console): should not render when `watch` return `undefined` in sign up and sign in form
LOG-4506
Test locally.
> fix(console): should not render when `watch` return `undefined` in sign up and sign in form

- packages/core/src/routes/session/password.test.ts
- packages/core/src/routes/session/password.ts
Add API to check if a username is available to register.
@simeng-li 
UTs
> feat(core): check username

- packages/ui/src/apis/register.ts
- packages/ui/src/containers/UsernameRegister/index.test.tsx
- packages/ui/src/containers/UsernameRegister/index.tsx
Update the check username API following PR #2290
UT passed
> refactor(ui): update the check username api

- packages/core/src/__mocks__/sign-in-experience.ts
- packages/core/src/queries/sign-in-experience.test.ts
- packages/core/src/routes/session/forgot-password.test.ts
- packages/core/src/routes/session/forgot-password.ts
- packages/core/src/routes/sign-in-experience.test.ts
- packages/core/src/routes/sign-in-experience.ts
- packages/core/src/routes/well-known.ts
- packages/schemas/alterations/next-1667283640-remove-forgot-password.ts
- packages/schemas/src/seeds/sign-in-experience.ts
- packages/schemas/tables/sign_in_experiences.sql
- packages/ui/src/__mocks__/logto.tsx
Remove the control "forgot password" from AC, now it is available when the connector is ready.
@simeng-li the "well-known" routes is updated.
Existing unit tests.
> feat: remove forgot password control

- .devcontainer/devcontainer.json
Config codespaces container:
1. run installs for dev.
2. start a database server.
3. set up envs.
Click "Code" in this PR page.
> chore: config codespaces container

- packages/console/src/components/Alert/index.tsx
- packages/console/src/hooks/use-user-preferences.ts
- packages/console/src/pages/Connectors/components/SignInExperienceSetupNotice/index.module.scss
- packages/console/src/pages/Connectors/components/SignInExperienceSetupNotice/index.tsx
- packages/console/src/pages/Connectors/index.module.scss
- packages/console/src/pages/Connectors/index.tsx
- packages/phrases/src/locales/en/translation/admin-console/connectors.ts
- packages/phrases/src/locales/en/translation/admin-console/general.ts
- packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/fr/translation/admin-console/general.ts
- packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
- packages/phrases/src/locales/ko/translation/admin-console/general.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
feat(console): add setup sie notice for the connectors page
LOG-4526: Replace `Got it` text with `general.got_it`
> feat(console): add setup sie notice for the connectors page

- .devcontainer/devcontainer.json
- .github/workflows/main.yml
- .gitignore
- .gitpod.yml
- .vscode/settings.json
- packages/console/package.json
- packages/console/src/hooks/use-api.ts
- packages/console/src/hooks/use-position.ts
- packages/core/src/middleware/koa-auth.ts
- packages/core/src/routes/authn.test.ts
- packages/core/src/routes/authn.ts
- packages/demo-app/package.json
- packages/integration-tests/package.json
- packages/phrases-ui/src/locales/zh-cn.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/ui/src/components/Button/index.module.scss
- packages/ui/src/components/Button/index.tsx
- packages/ui/src/components/ConfirmModal/AcModal.tsx
- packages/ui/src/components/Input/index.module.scss
- packages/ui/src/components/Notification/index.module.scss
- packages/ui/src/components/Notification/index.tsx
- packages/ui/src/components/TextLink/index.module.scss
- packages/ui/src/scss/_colors.scss
- packages/ui/src/utils/a11y.ts
- pnpm-lock.yaml
Merge `master` into feature/sie-v2
CI Passed.
> Merge `master` into feature/sie-v2

- packages/core/src/__mocks__/user.ts
- packages/schemas/alterations/next-1667374974-user-suspend.ts
- packages/schemas/tables/users.sql
Add `user.isSuspended`
No needed.
> feat(schemas): add user is suspended column

- packages/core/src/queries/user.test.ts
- packages/core/src/queries/user.ts
- packages/core/src/routes/admin-user.ts
Add case insensitive search for users.
UT and Locally Tested.
> feat: add case insensitive user search

- packages/ui/src/App.tsx
- packages/ui/src/hooks/use-sie.ts
- packages/ui/src/hooks/use-social-sign-in-listener.ts
- packages/ui/src/pages/Register/index.test.tsx
- packages/ui/src/pages/Register/index.tsx
- packages/ui/src/pages/SecondaryRegister/index.test.tsx
- packages/ui/src/pages/SecondaryRegister/index.tsx
- packages/ui/src/pages/SecondarySignIn/index.test.tsx
- packages/ui/src/pages/SecondarySignIn/index.tsx
- packages/ui/src/pages/SignIn/index.test.tsx
- packages/ui/src/pages/SignIn/index.tsx
Add signInMode guard
- add guard at all the sign-in and register entry pages. If not enabled should return 404
- add redirect logic at the root path level.  @charIeszhao this will address the welcome page can't register bug
- also block user jump to bind social page if register is disabled
test locally
ut added
> feat(ui): add signInMode guard

- .changeset/config.json
- .changeset/fifty-balloons-taste.md
- .changeset/pre.json
- remove changeset ignore packages to bump version correctly
- add German language changeset
local `pnpm changeset version` works as expected
> chore: add German language changeset

- Dockerfile
delay the source copy operation and update pnpm version
local build + CI
> chore: optimize Dockerfile

- packages/core/src/routes/custom-phrase.test.ts
- packages/core/src/routes/custom-phrase.ts
- packages/core/src/utils/translation.test.ts
- packages/core/src/utils/translation.ts
@IceHe 
- rename `isValidStructure()` to `isStrictlyPartial()` with comments added for better understanding
- optimize the amazing code readability and constant multiplier for time complexity
UT
> refactor(core): optimize translation strictly partial check

- packages/ui/src/apis/continue.test.ts
- packages/ui/src/apis/continue.ts
add continue related apis
UT added
> feat(ui): add continue related apis

- packages/phrases-ui/src/locales/en.ts
- packages/phrases-ui/src/locales/fr.ts
- packages/phrases-ui/src/locales/ko.ts
- packages/phrases-ui/src/locales/pt-pt.ts
- packages/phrases-ui/src/locales/tr-tr.ts
- packages/phrases-ui/src/locales/zh-cn.ts
- packages/ui/src/apis/continue.test.ts
- packages/ui/src/apis/continue.ts
- packages/ui/src/containers/PasscodeValidation/PasswordSignInLink.tsx
- packages/ui/src/containers/PasscodeValidation/index.module.scss
- packages/ui/src/containers/PasscodeValidation/index.tsx
- packages/ui/src/pages/Passcode/index.test.tsx
- packages/ui/src/pages/Passcode/index.tsx
Add password switch link
test locally
> feat(ui): add password switch link

- packages/console/src/pages/ConnectorDetails/index.tsx
- packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
feat(console): in-used connectors deletion alert
Test locally.
> feat(console): in-used connectors deletion alert

- packages/console/src/pages/Connectors/components/ConnectorStatusField/index.module.scss
- packages/console/src/pages/Connectors/components/ConnectorStatusField/index.tsx
- packages/console/src/pages/Connectors/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/connectors.ts
- packages/phrases/src/locales/en/translation/admin-console/connectors.ts
- packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
feat(console): add toggle tip for the sie not-in-use status
> feat(console): add toggle tip for the sie not-in-use status

- packages/console/src/components/Transfer/DraggableItem.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/index.module.scss
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SocialConnectorEditBox/index.tsx
refactor(console): remove draggle preview item background
Reference: https://github.com/react-dnd/react-dnd/issues/1218
> refactor(console): remove draggle preview item background

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
The verification code checkbox is disabled only when verification at sign-up is required and setting a password is not required at sign-up.
> refactor(console): enabled verification code checkbox when sign-up identifier set to none

- packages/console/src/pages/SignInExperience/components/Preview.tsx
For SIE preview, add "forgot" password field.
Local tested.
> fix(console): preview forgot password

- .changeset/unlucky-lizards-agree.md
- packages/cli/src/commands/database/config.ts
implement the command of trimming private or secret keys in database.
> feat(cli): trim keys

- packages/console/src/components/Checkbox/index.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/SignInMethodItem.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
refactor(console): the swap icon should be fixed in the sign-in method item
> refactor(console): the swap icon should be fixed in the sign-in method item

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
refactor(console): add margins to the draggable icon in sign-in method items
> style(console): add margins to the draggable icon in sign-in method items

- packages/console/src/components/Checkbox/index.module.scss
- packages/console/src/components/Checkbox/index.tsx
- packages/console/src/components/IconButton/index.module.scss
- packages/console/src/components/IconButton/index.tsx
- packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/SignInMethodItem.tsx
- packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
- refactor <Checkbox /> to support display tooltips when the checkbox is disabled
- refactor <IconButton /> to support tooltips when the <IconButton /> is disabled
- add tooltips to disabled action items on the sign-up and sign-in sie page.
> feat(console): add tool tips to disabled action items in sie

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/index.tsx
display full sign-up and sign-in config in the change alert
> refactor(console): display full sign-up and sign-in config in the change alert

- packages/ui/src/components/TermsOfUse/index.module.scss
Add cursor pointer to terms
test locally
> style(ui): add cursor pointer to terms

- packages/ui/src/containers/CreateAccount/index.test.tsx
- packages/ui/src/containers/CreateAccount/index.tsx
- packages/ui/src/containers/UsernameRegister/index.test.tsx
- packages/ui/src/containers/UsernameRegister/index.tsx
Update create account CTA button content
test locally
> fix(ui): update content

- packages/console/src/pages/SignInExperience/components/ColorForm.tsx
refactor(console): remove the required label from the dark mode color picker
> refactor(console): remove the required label from the dark mode color picker

- packages/core/src/lib/sign-in-experience/sign-in.test.ts
- packages/core/src/lib/sign-in-experience/sign-in.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
Each sign in method requires at least one authentication factor(password or verification code).
UTs.
> fix(core): sign in method requires at least one factor

- packages/core/src/routes/session/middleware/passwordless-action.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/social.bind-social.test.ts
- packages/core/src/routes/session/social.test.ts
- packages/core/src/routes/session/social.ts
- packages/core/src/routes/session/utils.test.ts
- packages/core/src/routes/session/utils.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
Block suspended user from sign in:
- password
- passwordless
- social
- social bind related user
Created LOG-4579 to refactor all sign in into a single function.
UTs
> feat(core): block suspended user from sign in

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/SignInDiffSection.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
fix(console): correct sentence cases in the sie change alert modal
> fix(console): correct sentence cases in the sie change alert modal

- packages/ui/src/components/BrandingHeader/index.module.scss
- packages/ui/src/components/Input/index.module.scss
- packages/ui/src/components/Passcode/index.module.scss
- packages/ui/src/components/SecondaryPageWrapper/index.module.scss
- packages/ui/src/components/SecondaryPageWrapper/index.tsx
- packages/ui/src/containers/EmailForm/index.module.scss
- packages/ui/src/containers/EmailPassword/index.module.scss
- packages/ui/src/containers/EmailPassword/index.tsx
- packages/ui/src/containers/PasswordSignInForm/index.module.scss
- packages/ui/src/containers/PhoneForm/index.module.scss
- packages/ui/src/containers/PhonePassword/index.module.scss
- packages/ui/src/containers/SetPassword/index.module.scss
- packages/ui/src/containers/UsernameSignIn/index.module.scss
- packages/ui/src/pages/Register/index.module.scss
- packages/ui/src/pages/Register/index.tsx
- packages/ui/src/pages/SignIn/index.module.scss
- packages/ui/src/pages/SignIn/index.tsx
layout styling updates
test locally
@logto-io/eng
> style(ui): layout styling updates

- packages/ui/src/components/TextLink/index.module.scss
- packages/ui/src/containers/PasscodeValidation/index.module.scss
- packages/ui/src/containers/PasscodeValidation/index.tsx
update text link styling
update text link styling
test locally
> style(ui): update text link styling

- packages/ui/src/apis/continue.test.ts
- packages/ui/src/apis/continue.ts
- packages/ui/src/containers/PasscodeValidation/index.test.tsx
- packages/ui/src/containers/PasscodeValidation/use-continue-set-email-passcode-validation.ts
- packages/ui/src/containers/PasscodeValidation/use-continue-set-sms-passcode-validation.ts
- packages/ui/src/containers/PasscodeValidation/utils.ts
- packages/ui/src/hooks/use-bind-social.ts
- packages/ui/src/types/guard.ts
Add set email and phone passcode validation hooks to hand the continue flow's passwordless verification
UT added
> feat(ui): add set email and phone passcode validation hooks

- packages/core/src/routes/session/continue.ts
- packages/core/src/routes/session/utils.ts
fix the check of whether "set a password" is required for a user
UTs
> fix(core): fix user password and identities check

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
fix(console): do not check sms or email connectors on verification code disabled in sign-in method
Test locally.
> fix(console): do not check sms or email connectors on verification code disabled in sign-in method

- packages/ui/src/containers/AppContent/index.module.scss
- packages/ui/src/containers/AppContent/index.tsx
Fix main page under short screen overflow styling
test locally
> style(ui): main page overflow

- packages/core/src/queries/user.ts
- packages/core/src/routes/admin-user.test.ts
- packages/core/src/routes/admin-user.ts
- packages/core/src/routes/session/utils.ts
Fixed field updating issues in patch user management API.
* Users should be able to use empty string or null to clear all clearable fields
* Users should be able to update their unique identifiers even with the same existing values
> fix(core): fix field updating issues in patch user management api

- packages/ui/src/components/Button/index.module.scss
fix the web button font size
test locally
> style(ui): fix web button font size

- packages/ui/src/components/ConfirmModal/Acmodal.module.scss
- packages/ui/src/components/ConfirmModal/MobileModal.module.scss
fix the modal border radius issue
test locally
> style(ui): fix modal border radius issue

- packages/console/src/components/Checkbox/index.module.scss
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
- packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
refactor(console): update the ac sign-up and sign-in phrases
Test locally.
> refactor(console): update the ac sign-up and sign-in phrases

- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
- Change `登陆` -> `登录`
Test locally.
> fix(phrases): zh-CN typo about sign-in

- packages/core/src/routes/admin-user.test.ts
- packages/core/src/routes/admin-user.ts
Add update user `isSuspended` API.
UTs
> feat(core): update user suspended

- .changeset/thin-oranges-act.md
Use case-insensitive strategy for searching emails
Add missing changeset
/
> chore: add changeset

- packages/ui/src/containers/AppContent/index.module.scss
fix mobile body font
test locally
> style(ui): fix mobile body font

- packages/ui/src/scss/_colors.scss
update bg color following latest design update
test locally
> style(ui): update bg color

- packages/ui/src/components/Toast/index.module.scss
hide toast outline when focus
test locally
> style(ui): hide toast outline

- packages/ui/src/pages/SignInPassword/index.tsx
fix i18n translation issue
test locally
> fix(ui): fix i18n content

- packages/ui/src/apis/index.test.ts
- packages/ui/src/apis/sign-in.ts
fix sign-in with phone password API namespace
fix sign-in with phone password API namespace
> fix(ui): sign-in with phone password api namespace

- packages/ui/src/components/ConfirmModal/AcModal.tsx
- packages/ui/src/components/ConfirmModal/Acmodal.module.scss
- packages/ui/src/components/ConfirmModal/MobileModal.module.scss
- packages/ui/src/components/ConfirmModal/type.ts
- packages/ui/src/components/TermsOfUse/index.tsx
feat(UI): add the key event to AC modal
on the desktop, press Enter should confirm the modal and Esc should cancel the modal
test locally
> feat(ui): add key event to AC modals

- packages/schemas/src/types/log.ts
add missing log types for continue with passwordless flow.
Local tested with API calls.
> fix(schemas): add missing log types for continue with passwordless

- packages/console/src/hooks/use-connector-in-use.ts
fix(console): correct SMS connector status
> fix(console): correct sms connector status

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/index.module.scss
style(console): sign-up and sign-in form field description margins
Test locally.
> style(console): sign-up and sign-in form field description margins

- packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
fix(phrases): connectors setup warnings
Test locally.
> fix(phrases): connectors setup warnings

- .changeset/quick-turtles-joke.md
> chore: add sign-in experience v2 changeset

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/utilities.ts
> refactor(console): enable password and verification code auth in sign-in method by default

- packages/phrases-ui/src/locales/zh-cn.ts
> fix(ui): update cn content

- packages/ui/src/components/SecondaryPageWrapper/index.module.scss
- packages/ui/src/pages/Continue/EmailOrPhone/index.tsx
- packages/ui/src/pages/Continue/SetEmail/index.tsx
- packages/ui/src/pages/Continue/SetPhone/index.tsx
- packages/ui/src/pages/Continue/SetUsername/index.tsx
hot fix the rebase issue. Some latest code was missing
test locally
> fix(ui): hot fix the rebase issue

- packages/console/src/pages/UserDetails/index.module.scss
- packages/console/src/pages/UserDetails/index.tsx
- packages/core/src/routes/admin-user.test.ts
- packages/phrases/src/locales/de/translation/admin-console/user-details.ts
- packages/phrases/src/locales/en/translation/admin-console/user-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
- packages/schemas/src/types/user.ts
Add suspended label to user details page.
> feat(console): add suspended label

- .changeset/quick-turtles-joke.md
- .changeset/thin-oranges-act.md
- .changeset/unlucky-lizards-agree.md
the generated changelog will look like:
which makes no sense. change all titles to bold text to see if it works.
pending merge, and see [this PR](https://github.com/logto-io/logto/pull/2329)
> chore: update changeset format

- .github/workflows/release.yml
job failed due to no token presents
https://github.com/logto-io/logto/actions/runs/3467463204/jobs/5792355966
after merge
> ci: add npm token

- .github/workflows/release.yml
https://github.com/logto-io/logto/actions/runs/3467554315/jobs/5792531675
NPM is good, git tag push not working
after merge
> ci: set bot token for release workflow

- packages/core/src/routes/admin-user.ts
- packages/core/src/routes/session/index.ts
- packages/core/src/routes/session/profile.test.ts
- packages/core/src/routes/session/profile.ts
- packages/core/src/routes/session/utils.ts
Add change username session API
> feat(core): add change username session api

- packages/core/src/routes/session/forgot-password.test.ts
- packages/core/src/routes/session/forgot-password.ts
- packages/core/src/routes/session/profile.test.ts
- packages/core/src/routes/session/profile.ts
Add change password session API.
> feat(core): add change password session api

- packages/ui/src/components/Input/phoneInput.module.scss
fix phone input android layout bug
test locally on android device
> fix(ui): fix phone input android layout bug

- .github/workflows/release.yml
avoid unnecessary tag actions
https://github.com/logto-io/logto/actions/runs/3468338510/jobs/5794057138
after merge
> ci: fetch all tags for release workflow

- packages/core/src/routes/session/profile.test.ts
- packages/core/src/routes/session/profile.ts
- packages/core/src/routes/session/utils.ts
Link email and unlink email session APIs
> feat: email related profile session apis

- packages/core/src/routes/session/profile.test.ts
- packages/core/src/routes/session/profile.ts
Link phone number, change phone number and unlink phone number profile session APIs.
> feat: phone related profile session APIs

- packages/console/src/hooks/use-enabled-connector-types.ts
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/ConnectorSetupWarning.tsx
- add a `useEnabledConnectorTypes` hook to reuse the same logic in the coming features.
- refactor connector setup warning component with the newly added `useEnabledConnectorTypes` hooks.
Test locally.
> refactor(console): connector setup warning

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
refactor(console): validate sign-up identifier
Test locally.
> refactor(console): validate sign-up identifier

- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignInForm.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/SignInMethodItem.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.module.scss
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/utilities.ts
- packages/console/src/pages/SignInExperience/types.ts
- packages/console/src/pages/SignInExperience/utilities.ts
- packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
- use the React-Hook-Form's `useFieldArray` API to refactor `<SignInEditBox />` to support array field level error.
- move the refreshing sign-in methods states logic into the `<SignUpForm />` component rather than in the `<SignInEditBox />`
> refactor(console): form validations on sign-up and sign-in page

- packages/console/src/components/AuditLogTable/index.tsx
- packages/console/src/components/Pagination/index.module.scss
- packages/console/src/components/Pagination/index.tsx
- packages/console/src/pages/ApiResources/index.tsx
- packages/console/src/pages/Applications/index.tsx
- packages/console/src/pages/Users/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/general.ts
- packages/phrases/src/locales/en/translation/admin-console/general.ts
- packages/phrases/src/locales/fr/translation/admin-console/general.ts
- packages/phrases/src/locales/ko/translation/admin-console/general.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
refactor(console): add pagination item range info
> refactor(console): add pagination item range info

- packages/core/src/routes/session/profile.test.ts
- packages/core/src/routes/session/profile.ts
Provide a profile session API to change other insensitive user info.
* display name
* avatar
* custom data
> feat: profile API to change other insensitive user info

- packages/console/package.json
- packages/core/package.json
- packages/core/src/__mocks__/connector-base-data.ts
- packages/core/src/__mocks__/connector.ts
- packages/core/src/connectors/index.ts
- packages/core/src/connectors/utilities/index.test.ts
- packages/core/src/queries/connector.test.ts
- packages/demo-app/package.json
- packages/phrases-ui/package.json
- packages/phrases/package.json
- packages/schemas/alterations/next-1668666590-support-multiple-connector-instances.ts
- packages/schemas/package.json
- packages/schemas/src/foundations/jsonb-types.ts
- packages/schemas/src/types/connector.ts
- packages/schemas/tables/connectors.sql
- packages/ui/package.json
- pnpm-lock.yaml
1. update `connectors` table
2. add alteration script
3. update load connector logic
> feat: update connectors table and load connector logic

- packages/console/src/components/SubmitFormChangesActionBar/index.module.scss
- packages/console/src/components/SubmitFormChangesActionBar/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/general.ts
- packages/phrases/src/locales/en/translation/admin-console/general.ts
- packages/phrases/src/locales/fr/translation/admin-console/general.ts
- packages/phrases/src/locales/ko/translation/admin-console/general.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
feat(console): submit form changes action bar
Requirements:
https://www.figma.com/file/hqAWH3Di8gkiV5TXAt6juO/%F0%9F%8C%B9-%5BAC%5D-Layout-UI-Optimization?node-id=174%3A23222&t=bKjlee8sZDBEwfTV-4
> feat(console): submit form changes action bar

- packages/console/src/App.tsx
- packages/console/src/components/AppContent/components/Sidebar/index.module.scss
- packages/console/src/components/AppContent/index.module.scss
- packages/console/src/components/FormCard/index.module.scss
- packages/console/src/components/FormCard/index.tsx
- packages/console/src/components/TabNav/index.module.scss
- packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
- packages/console/src/pages/ApplicationDetails/components/Settings.tsx
- packages/console/src/pages/ApplicationDetails/index.module.scss
- packages/console/src/pages/ApplicationDetails/index.tsx
- packages/console/src/scss/_underscore.scss
- packages/phrases/src/locales/de/translation/admin-console/application-details.ts
- packages/phrases/src/locales/de/translation/admin-console/general.ts
- packages/phrases/src/locales/en/translation/admin-console/application-details.ts
- packages/phrases/src/locales/en/translation/admin-console/general.ts
- packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/general.ts
- packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/general.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Refactor(console): application details:
- Merge the advanced settings tab into the settings page.
- Remove the advanced settings router and related components.
- Add a `<FormCard />` component to help to construct the common layout.
- Remove the margin-bottom from the `<TabNav />` to fit the new layout.
> refactor(console): application details

- packages/console/src/components/DetailsForm/index.module.scss
- packages/console/src/components/DetailsForm/index.tsx
- packages/console/src/components/SubmitFormChangesActionBar/index.tsx
- packages/console/src/pages/ApiResourceDetails/index.module.scss
- packages/console/src/pages/ApiResourceDetails/index.tsx
- packages/console/src/pages/ApplicationDetails/index.module.scss
- packages/console/src/pages/ApplicationDetails/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/de/translation/admin-console/application-details.ts
- packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/en/translation/admin-console/application-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
Requirements: 
https://www.figma.com/file/hqAWH3Di8gkiV5TXAt6juO/%F0%9F%8C%B9-%5BAC%5D-Layout-UI-Optimization?node-id=368%3A61311&t=bKjlee8sZDBEwfTV-4
- refactor(console): api resource details
- extract details-form saving logic into a `<DetailsForm />` component.
- fix: call `onDiscard` without passing parameters to it in `<SubmitFormChangesActionBar />`
- refactor pass `reset` function to the `<SubmitFormChangesActionBar />` on `ApplicationDetails` page directly.
> refactor(console): api resource details

- packages/core/src/connectors/index.ts
hot fix getConnectors bug
unsupported connector instance should not throw 404 error;
test locally
> fix(core): hot fix getConnectors bug

- packages/console/src/components/AuditLogTable/index.tsx
- packages/console/src/components/Pagination/index.tsx
- packages/console/src/pages/ApiResources/index.tsx
- packages/console/src/pages/Applications/index.tsx
- packages/console/src/pages/Users/index.tsx
- refactor: do not display pagination if the page count is less than two
- fix: page item range's max item index should not be greater than the total item count.
> refactor(console): hide pagination if the page count is less than two

- packages/console/src/scss/resources.module.scss
refactor(console): add padding-bottom to resources layout
https://linear.app/silverhand/issue/LOG-4700/bottom-padding-for-data-table
> refactor(console): add padding-bottom to resources layout

- packages/console/src/pages/UserDetails/components/UserLogs.module.scss
- packages/console/src/pages/UserDetails/components/UserLogs.tsx
- packages/console/src/pages/UserDetails/components/UserSettings.tsx
- packages/console/src/pages/UserDetails/index.module.scss
- packages/console/src/pages/UserDetails/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/user-details.ts
- packages/phrases/src/locales/en/translation/admin-console/user-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
Requirements:
https://www.figma.com/file/hqAWH3Di8gkiV5TXAt6juO/%F0%9F%8C%B9-%5BAC%5D-Layout-UI-Optimization?node-id=174%3A23744&t=bKjlee8sZDBEwfTV-4
- apply new layout to the user details page.
> refactor(console): user details

- packages/console/src/components/TabNav/TabNavItem.module.scss
- packages/console/src/components/TabNav/TabNavItem.tsx
- packages/console/src/pages/SignInExperience/components/Preview.module.scss
- packages/phrases/src/locales/de/translation/admin-console/general.ts
- packages/phrases/src/locales/en/translation/admin-console/general.ts
- packages/phrases/src/locales/fr/translation/admin-console/general.ts
- packages/phrases/src/locales/ko/translation/admin-console/general.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
Requirements:
https://www.figma.com/file/hqAWH3Di8gkiV5TXAt6juO/%F0%9F%8C%B9-%5BAC%5D-Layout-UI-Optimization?node-id=174%3A23246&t=bKjlee8sZDBEwfTV-4
- Add hover state to the `<TabNavItem />.`
- Change the under-line styles of the `<TabNavItem />` when that is selected.
- Remove the `<TabNav />`'s border-bottom in the preview component to make it aligned with the design file.
> refactor(console): tab nav

- packages/console/src/pages/Settings/components/ChangePassword.module.scss
- packages/console/src/pages/Settings/index.module.scss
- packages/console/src/pages/Settings/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/settings.ts
- packages/phrases/src/locales/en/translation/admin-console/settings.ts
- packages/phrases/src/locales/fr/translation/admin-console/settings.ts
- packages/phrases/src/locales/ko/translation/admin-console/settings.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/settings.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/settings.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/settings.ts
Requirements:
https://www.figma.com/file/hqAWH3Di8gkiV5TXAt6juO/%F0%9F%8C%B9-%5BAC%5D-Layout-UI-Optimization?node-id=174%3A23805&t=bKjlee8sZDBEwfTV-4
- refactor: settings page layout
- adjust the `<ChangePassword />` component styles to fit the new layout.
> refactor(console): settings

- packages/core/src/routes/session/profile.test.ts
- packages/core/src/routes/session/profile.ts
Provide session APIs to link and unlink social account to the current user.
> feat(core): social related profile session apis

- packages/console/src/pages/Settings/index.module.scss
- packages/console/src/pages/Settings/index.tsx
The `resourcesStyle` should be applied to the resources list page only, we should not use `resourcesStyles` on the settings page, as it will cause margin problems:
> style(console): settings

- packages/console/src/scss/resources.module.scss
Fix lint error in master branch
> fix: master lint error

- packages/core/src/routes/session/profile.ts
Remove unnecessary console.log. I'm sorry guys...
N/A
> chore: remove unnecessary console log

- packages/core/src/__mocks__/connector.ts
- packages/core/src/connectors/index.ts
- packages/core/src/connectors/types.ts
- packages/core/src/queries/connector.test.ts
- packages/core/src/queries/connector.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
- packages/integration-tests/src/api/connector.ts
- packages/integration-tests/src/helpers.ts
- packages/integration-tests/tests/api/connector.test.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
add POST /connectors
UTs and ITs.
> feat: add POST /connectors

- packages/core/src/queries/connector.test.ts
- packages/core/src/queries/connector.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
add DELETE /connectors/:id API
Passed ITs and UTs.
> feat: add DELETE /connectors/:id

- packages/console/src/components/AuditLogTable/index.tsx
- packages/console/src/pages/ApiResources/index.tsx
- packages/console/src/pages/Applications/index.tsx
- packages/console/src/pages/Connectors/index.tsx
- packages/console/src/pages/Users/index.module.scss
- packages/console/src/pages/Users/index.tsx
- packages/console/src/scss/resources.module.scss
- packages/console/src/scss/table.module.scss
refactor(console): resources table
- Refactor: the table background size should fit the table height.
- Remove the table border according to the new design file.
- Refactor: the pagination should always be at the bottom of the page.
- Refactor: extract some style's child classes into the outer scope to allow users to overwrite it in the `resource.module.scss` file.
- Refactor: do not display the border-bottom of the last row of items.
- remove `@include _.flex-column` from `resource.module.scss` and use custom-defined styles instead, for the `flex-column` mix-in contains `justify-content: center`, which is not suitable for our case.
Before:
After:
Before:
After:
Before:
After:
> refactor(console): resources table

- packages/core/src/__mocks__/connector.ts
- packages/core/src/connectors/index.ts
- packages/core/src/connectors/types.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
Update virtual connector loading to getConfig by id.
Passed UT and IT.
> feat: update virtual connector loading to getConfig by id

- packages/console/src/components/AuditLogTable/index.module.scss
- packages/console/src/components/AuditLogTable/index.tsx
refactor(console): audit log table
> refactor(console): audit log table

- packages/console/src/pages/Users/index.module.scss
- packages/console/src/pages/Users/index.tsx
refactor(console): inline search filter in the user table
> refactor(console): inline the search filter in the user table

- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/middleware/koa-session-sign-in-experience-guard.ts
- packages/core/src/routes/interaction/middleware/koa-session-sign-inexperience-guard.test.ts
Add middleware to guard session and sign-in mode. Also apply SIE settings to the context after guard
ut added
> refactor(core): add sign-in-mode guard

- packages/console/src/components/ModalLayout/index.module.scss
Remove border from all popup modal dialogs, as per the latest UX design updates
> refactor(console): remove border from all modal dialogs

- packages/console/src/components/AppContent/components/UserInfo/index.tsx
Remove the temp workaround on user claims from admin console.
> refactor(console): remove user claim temp workaround

- packages/console/src/pages/SignInExperience/tabs/Others/AuthenticationForm.tsx
- packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
Improve wording in SIE others tab. Change "AUTHENTICATION" to "ADVANCED OPTIONS".
> chore(console): improve wording in SIE others tab

- packages/console/src/components/DetailsForm/index.tsx
- packages/console/src/components/SubmitFormChangesActionBar/index.tsx
- support `onSubmit` in the `<SubmitFormChangesActionBar />` component, for it will be used outside a form in the future.
- refactor the `<DetailsForm />` to fit the new implementation of the `<SubmitFormChangesActionBar />`
Test locally.
> refactor(console): support `onSubmit` in `SubmitFormChangesActionBar`

- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/middleware/koa-session-sign-in-experience-guard.ts
- packages/core/src/routes/interaction/types/guard.ts
- packages/core/src/routes/interaction/types/index.ts
- packages/core/src/routes/interaction/utils/index.ts
- packages/core/src/routes/interaction/utils/verify-user-by-password.test.ts
- packages/core/src/routes/interaction/utils/verify-user-by-password.ts
- packages/core/src/routes/interaction/verifications/identifier-verification.test.ts
- packages/core/src/routes/interaction/verifications/identifier-verification.ts
- packages/core/src/routes/interaction/verifications/index.ts
- packages/schemas/src/types/interactions.ts
Add password identifier verification method. 
Verify the identifier + password and return the accountId if exist. 
UR case added.
> refactor(ui): add password identifier verification

- packages/core/src/routes/connector.ts
- packages/core/src/routes/connector.update.test.ts
- packages/core/src/routes/session/social.test.ts
- packages/core/src/routes/session/social.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
update PATCH /connectors/:id (now this API can be use to update `sync_profile`)
also, update users' profile when signing in as long as `sync_profile` is true 
UTs and ITs.
> feat: update PATCH /connectors/:id

- packages/core/package.json
- packages/core/src/routes/interaction/middleware/koa-interaction-body-guard.test.ts
- packages/core/src/routes/interaction/middleware/koa-session-sign-in-experience-guard.ts
- packages/core/src/routes/interaction/middleware/koa-session-sign-inexperience-guard.test.ts
- packages/core/src/routes/interaction/types/guard.ts
- packages/core/src/routes/interaction/types/index.ts
- packages/core/src/routes/interaction/utils/sign-in-experience-valiation.test.ts
- packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
- packages/core/src/routes/interaction/utils/verify-user-by-password.test.ts
- packages/core/src/routes/interaction/utils/verify-user-by-password.ts
- packages/core/src/routes/interaction/verifications/identifier-verification.test.ts
- packages/core/src/routes/interaction/verifications/identifier-verification.ts
- packages/schemas/src/types/interactions.ts
- pnpm-lock.yaml
update the interaction guard
1. Bump the TS version to 4.9, so we can use the in operator to narrow down the identifier entity's type
2. Refactor the old all optional identifier guard back to union strict type
3. Refactor the `koaSessionSignInExperience` middleware. **Instead of appending the SIE data to the context**, move all the SIE validation logic within the middleware
- signinMode validation
- identifier validation
- profile validation
test locally 
UT added
> refactor(core): update the interaction guard

- packages/core/src/__mocks__/connector.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
> feat: add GET /connector-factories

- packages/core/src/connectors/index.ts
Fix connector loading path error
> fix: connector loading path not found error

- packages/console/src/components/TabNav/index.module.scss
refactor(console): change tab nav border color to `surface-5`
> refactor(console): change tab nav border color to `surface-5`

- packages/console/src/components/SubmitFormChangesActionBar/index.module.scss
refactor(console): change the `SubmitFormChangesActionBar` background color to `float`
> refactor(console): change the `SubmitFormChangesActionBar` background color to `float`

- packages/console/src/components/CardTitle/index.module.scss
- packages/console/src/components/CardTitle/index.tsx
- packages/console/src/pages/Settings/index.module.scss
- packages/console/src/pages/Settings/index.tsx
- packages/console/src/pages/SignInExperience/index.module.scss
- packages/console/src/pages/SignInExperience/index.tsx
style(console): enable card title auto shrink by default
> style(console): enable card title auto shrink by default

- packages/core/src/queries/user.ts
- packages/core/src/routes/session/social.test.ts
- packages/core/src/routes/session/social.ts
refactor findUserByIdentity make it nullable. Align with `findUserByPhone`, `findUserByEmail`, `findUserById`.
No need to call `hasUserWithIdentity` ahead. 
UT updated
> refactor(core): refactor findUserByIdentity

- packages/console/src/components/TabNav/TabNavItem.module.scss
Tab nav error hover cursor should be default style.
Test locally.
> style(console): tab nav error hover cursor

- packages/console/src/pages/SignInExperience/index.module.scss
- packages/console/src/pages/SignInExperience/index.tsx
The preview should have the same margin-bottom as the form, so we need to apply the margin-bottom the preview and form wrapper.
> style(console): form and privew content margin-bottom

- packages/core/src/queries/connector.test.ts
- packages/core/src/queries/connector.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
Update available social targets after connector deletion.
Passed UTs, ITs and tested locally.
> feat: update available social targets after connector deletion

- packages/core/src/queries/connector.test.ts
- packages/core/src/queries/connector.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
remove old same type passwordless connectors before posting (for passwordless connector, we only accept one working connector for each type, including SMS and email)
Passed IT and UTs.
> feat: remove old same type passwordless connectors before posting

- packages/core/src/routes/interaction/types/guard.ts
- packages/core/src/routes/interaction/types/index.ts
- packages/core/src/routes/interaction/utils/find-user-by-identity.ts
- packages/core/src/routes/interaction/utils/index.ts.ts
- packages/core/src/routes/interaction/utils/social-verification.test.ts
- packages/core/src/routes/interaction/utils/social-verification.ts
- packages/core/src/routes/interaction/utils/verify-user.ts
- packages/core/src/routes/interaction/verifications/identifier-verification.ts
add social verification
Add social verification
- get authorized by connectorId and connectorData
- get user account by social identity. 
UT case added
> refactor(core): add social verification

- packages/console/src/components/FormField/index.tsx
- packages/console/src/components/MultiTextInput/index.module.scss
- packages/console/src/components/MultiTextInput/index.tsx
- packages/console/src/components/MultiTextInputField/index.module.scss
- packages/console/src/components/MultiTextInputField/index.tsx
- packages/console/src/mdx-components/UriInputField/index.module.scss
- packages/console/src/mdx-components/UriInputField/index.tsx
- packages/console/src/pages/ApplicationDetails/components/Settings.tsx
- packages/console/src/pages/ApplicationDetails/index.module.scss
Fix the `MultiTextInput` according to the design file:
https://www.figma.com/file/hqAWH3Di8gkiV5TXAt6juO/%F0%9F%8C%B9-%5BAC%5D-Layout-UI-Optimization?node-id=174%3A23222&t=UFwmBDbVBML13YqB-4
> style(console): fix multi-text input margin

- packages/phrases/src/locales/zh-cn/errors.ts
- packages/ui/src/pages/Continue/EmailOrPhone/index.tsx
- packages/ui/src/pages/Continue/SetEmail/index.tsx
- packages/ui/src/pages/Continue/SetPassword/index.tsx
- packages/ui/src/pages/Continue/SetPhone/index.tsx
- packages/ui/src/pages/Continue/SetUsername/index.tsx
error content update and remove notification
test locally
> fix(ui): bug bash fix

- packages/core/src/routes/interaction/middleware/koa-interaction-body-guard.ts
- packages/core/src/routes/interaction/types/guard.ts
- packages/core/src/routes/interaction/types/index.ts
- packages/core/src/routes/interaction/utils/index.ts
- packages/core/src/routes/interaction/utils/passcode-validation.test.ts
- packages/core/src/routes/interaction/utils/passcode-validation.ts
- packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
- packages/core/src/routes/interaction/utils/social-verification.ts
- packages/core/src/routes/interaction/verifications/identifier-verification.ts
- packages/schemas/src/types/interactions.ts
manage the type and guard variables properly.
1. move all guards ender the guard file, and type under type file.
2. Add the interaction result guard in order to retrieve the proper event, identifiers and profile properly from OIDC interaction results. 
UT passed
> refactor(core): refactor the type and guard

- packages/core/src/routes/session/utils.ts
chore(core): remove unused `checkMissingRequiredSignUpIdentifiers`
None.
> chore(core): remove unused `checkMissingRequiredSignUpIdentifiers`

- packages/console/src/components/DetailsForm/index.module.scss
- packages/console/src/components/DetailsForm/index.tsx
- packages/console/src/components/SubmitFormChangesActionBar/index.module.scss
- packages/console/src/components/SubmitFormChangesActionBar/index.tsx
refactor(console): add animations for the submit form action bar
> refactor(console): add animations for the submit form action bar

- packages/core/src/routes/session/utils.test.ts
- packages/core/src/routes/session/utils.ts
the `checkRequiredProfile` method should not throw an error when the `signUpIdentifiers` is `['email', 'sms']` and the user has an email or phone in the profile data.
UT added and passed.
> fix(core): `checkRequiredProfile` should work correctly when sign up identifier is `emailOrSms`

- packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
- packages/console/src/pages/Connectors/components/ConnectorForm/index.module.scss
- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
- packages/console/src/pages/Connectors/components/Guide/index.module.scss
- packages/console/src/pages/Connectors/components/Guide/index.tsx
- packages/console/src/pages/Connectors/types.ts
- packages/core/src/routes/connector.ts
- packages/core/src/routes/connector.update.test.ts
- packages/schemas/src/types/connector.ts
feature: edit standard connector data.
> feat(console): edit standard connector

- packages/console/src/scss/resources.module.scss
style(console): center align create buttons on list page
> style(console): center align create buttons on list page

- packages/console/src/components/FormField/index.module.scss
- packages/console/src/components/FormField/index.tsx
- packages/console/src/components/MultiTextInputField/index.tsx
- packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
- packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
- packages/console/src/pages/ApplicationDetails/components/Settings.tsx
- packages/console/src/pages/Dashboard/components/Block.module.scss
- packages/console/src/pages/Dashboard/components/Block.tsx
- packages/console/src/pages/Dashboard/index.tsx
- packages/console/src/pages/SignInExperience/tabs/Others/TermsForm.tsx
- packages/console/src/pages/UserDetails/components/UserSettings.tsx
- Replace info tooltips with toggle tips
- Rename props name from `tooltip` to `tip`
Test locally.
> refactor(console): replace info tooltips with toggle tips

- packages/core/src/routes/interaction/index.ts
api delete interaction
Fork the old delete session API as delete interaction api
N/A
> feat(core): api delete interaction

- packages/console/src/pages/Connectors/components/CreateForm/constants.ts
- packages/console/src/pages/Connectors/components/CreateForm/index.tsx
- packages/console/src/pages/Connectors/components/CreateForm/utils.ts
List connectors in preset orders.
The unknown connector will be placed in the last.
> feat(console): sort connectors

- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
Add error state for connector form.
> fix(console): error state for connector form

- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
- packages/core/src/routes/connector.update.test.ts
Drop empty string, undefined and null fields of connector configurable metadata when creating and updating connector configs.
> fix: drop empty string, undefined and null fields of connector configurable metadata

- .github/workflows/integration-test.yml
- packages/integration-tests/src/__mocks__/connectors-mock.ts
- packages/integration-tests/tests/api/admin-user.test.ts
- packages/integration-tests/tests/api/connector.test.ts
- packages/integration-tests/tests/api/social-session.test.ts
add IT for switching passwordless connector
> chore: add IT for switching passwordless connector

- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
- packages/console/src/pages/Connectors/components/Guide/index.tsx
- packages/core/src/routes/connector.ts
- packages/core/src/routes/connector.update.test.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
Once a connector is created, the "target" can not be modified.
UTs and local tested.
> feat(core,console): prevent target change after created

- packages/console/src/hooks/use-ui-languages.ts
- packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
- packages/core/src/app/init.ts
- packages/core/src/lib/sign-in-experience/index.ts
- packages/core/src/lib/user.ts
- packages/core/src/oidc/adapter.ts
refactor(core,console): replace deduplicate logic with `deduplicate` util
Test locally and UT passed.
> refactor(core,console): replace deduplicate logic with `deduplicate` util

- packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/use-language-editor-context.ts
- packages/ui/src/containers/ConfirmModalProvider/index.tsx
- packages/ui/src/hooks/use-page-context.ts
refactor(console,ui): import `noop` from `silverhand/essentials`
Test locally, and the UI UT passed.
> refactor(console,ui): import `noop` from `silverhand/essentials`

- packages/core/src/__mocks__/connector.ts
- packages/core/src/lib/connector.test.ts
- packages/core/src/lib/connector.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
prohibit multiple same-platform social connectors from sharing the same target.
Passed ITs and UTs.
> feat: prohibit multiple same-platform social connectors to share same target

- packages/core/src/routes/admin-user.test.ts
- packages/core/src/routes/admin-user.ts
- packages/core/src/routes/init.ts
- packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
- packages/core/src/routes/interaction/verifications/user-identity-verification.ts
enable the interaction routes online. Also, update the identifiers not found error code, `unauthorized` is not proper for the case. 
test locally replace UI password sign-in method with new ones.
> feat(core): enable interaction routes online

- packages/core/src/routes/admin-user.test.ts
- packages/core/src/routes/admin-user.ts
- packages/core/src/routes/init.ts
- packages/core/src/routes/interaction/actions/submit-interaction.ts
- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/utils/interaction.ts
- packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
- packages/core/src/routes/interaction/verifications/user-identity-verification.ts
add interaction route ut
1. Add UT cases for the PUT and PATCH interaction apis
2. Rename the API path to interaction, it was mistakenly set to identifier
3. Add an interaction util method to clear the interaction result.  For the forgot password flow, the interaction storage should be cleared after a successful reset call. 
UT passed.
> test(core): add interaction route ut

- packages/core/src/routes/admin-user.test.ts
- packages/core/src/routes/admin-user.ts
- packages/core/src/routes/init.ts
- packages/core/src/routes/interaction/actions/submit-interaction.ts
- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/utils/index.ts
- packages/core/src/routes/interaction/utils/interaction.test.ts
- packages/core/src/routes/interaction/utils/interaction.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
- packages/core/src/routes/interaction/verifications/profile-verification.ts
- packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
- packages/core/src/routes/interaction/verifications/user-identity-verification.ts
Per offline discussion with @charIeszhao. Added some comments and refactored the code for the user account verification flow for better understanding. Also, some minor method name updates. No logic changes. Also simplify the usage of `mergeIdentifiers`
UT passed
> refactor(core): refactor the user account verification

- packages/console/src/pages/SignInExperience/tabs/Branding/BrandingForm.tsx
- packages/console/src/pages/SignInExperience/tabs/index.module.scss
style(console): add radio groups margin-top on the sie branding page
> style(console): add radio groups margin-top on the sie branding page

- packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.tsx
- packages/console/src/components/ConfirmModal/index.tsx
- packages/console/src/pages/ApiResources/index.tsx
- packages/console/src/pages/Applications/components/CreateForm/index.tsx
- packages/console/src/pages/Applications/index.tsx
- packages/console/src/pages/Connectors/components/CreateForm/index.tsx
- packages/console/src/pages/Settings/components/ChangePassword.tsx
- packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx
- packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/index.tsx
- packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
- packages/console/src/pages/UserDetails/index.tsx
- packages/console/src/pages/Users/index.tsx
- packages/ui/src/components/ConfirmModal/AcModal.tsx
- packages/ui/src/components/ConfirmModal/MobileModal.tsx
support close modal on `esc` pressed`
Test locally.
> refactor(console): support close modal on `esc` pressed

- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
- packages/core/src/routes/connector.update.test.ts
- packages/integration-tests/src/api/connector.ts
- packages/integration-tests/tests/api/connector.test.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-br/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
add target constrain to POST and PATCH apis.
> feat: add target constrain to POST and PATCH apis

- packages/console/src/components/Markdown/index.module.scss
style(console): update link styles in markdown contents
> style(console): update link styles in markdown contents

- packages/console/src/components/ColorPicker/index.module.scss
style(console): add border to the color block of `ColorPicker`
> style(console): add border to the color block of `ColorPicker`

- packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
refactor(console): remove unnecessary required tag
> refactor(console): remove unnecessary required tag

- packages/console/src/pages/Connectors/components/Guide/index.tsx
fix(console): navigate to the details page on connector created
- Test on SMS & email connector set-up pages
- Test on social connector set-up pages.
> fix(console): navigate to the details page on connector created

- packages/core/src/__mocks__/user.ts
- packages/core/src/queries/user.test.ts
- packages/core/src/queries/user.ts
sort users data by `createdAt`
UT Passed.
> refactor(core): sort users data by `createdAt`

- packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
- packages/console/src/pages/Connectors/components/Guide/index.tsx
Remove "sync profile" field for non-social connector in both create and edit page.
Local tested.
> fix(console): remove sync profile field for non-social connector

- .github/workflows/master-codecov-report.yml
sync with the recent test script change in #2644 
after merge
> ci: fix codecov master workflow

- packages/core/src/routes/connector.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-br/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
> fix: correct error messages

- packages/schemas/alterations/next-1671039448-add-user-name-index.ts
- packages/schemas/tables/users.sql
speed up users search API
local DB, queries work fine
> refactor(schemas): add name index on users

- packages/core/package.json
- packages/core/src/utils/pagination.ts
- pnpm-lock.yaml
> refactor(core): remove `query-string`

- packages/console/src/App.tsx
- packages/console/src/consts/page-tabs.ts
- packages/console/src/pages/SignInExperience/index.tsx
Add sie tab constants to avoid potential handwriting mistakes.
Test locally.
> refactor(console): add sie tab constants

- packages/core/src/routes/connector.ts
- packages/core/src/routes/connector.update.test.ts
- packages/integration-tests/src/tests/api/connector.test.ts
PATCH connector metadata should be optional.
> fix: connector metadata update should be optional

- packages/integration-tests/src/tests/interaction/register-with-identifier.test.ts
- packages/integration-tests/src/tests/interaction/sign-in-with-passcode-identifier.test.ts
- packages/integration-tests/src/tests/interaction/sign-in-with-password-identifier.test.ts
- packages/integration-tests/src/tests/interaction/utils/client.ts
- packages/integration-tests/src/tests/interaction/utils/user.ts
Add username, phone, email register integration test cases.
This PR also includes the following updates:
- apply to expect Reject to replace the original expect reject to throw assert. Verify the reject code message strictly. 
- update the client util method that returns the userId after a successful sign-in. So we can clean up the user data after each test.
test passed
> feat(test): add username, phone, email register integration test

- packages/phrases/src/locales/zh-cn/errors.ts
Improve Chinese translation script
N/A
> chore(phrases): improve Chinese translation

- packages/core/src/libraries/social.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/utils/social-verification.test.ts
- packages/core/src/routes/interaction/utils/social-verification.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
- packages/core/src/routes/session/social.ts
- packages/core/src/routes/session/utils.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-br/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/toolkit/connector-kit/src/types.ts
Add social sign-in validation reference to interaction.
N/A
> chore: add social sign-in validation reference to interaction

- packages/integration-tests/src/__mocks__/connectors-mock.ts
- packages/integration-tests/src/tests/interaction/forgot-password.test.ts
add forgot password integration test
test passed locally
> feat(test): add forgot pasword integration test

- packages/console/src/components/AuditLogTable/components/EventName/index.tsx
- packages/console/src/components/AuditLogTable/index.tsx
- packages/console/src/consts/logs.ts
- packages/console/src/pages/AuditLogDetails/index.tsx
- packages/core/src/middleware/koa-audit-log-legacy.test.ts
- packages/core/src/middleware/koa-audit-log-legacy.ts
- packages/core/src/middleware/koa-audit-log.test.ts
- packages/core/src/middleware/koa-audit-log.ts
- packages/core/src/queries/log.ts
- packages/core/src/routes/log.test.ts
- packages/core/src/routes/log.ts
- packages/integration-tests/src/tests/api/logs-legacy.test.ts
- packages/phrases/src/locales/de/translation/admin-console/log-details.ts
- packages/phrases/src/locales/en/translation/admin-console/log-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/log-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/log-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/log-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/log-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/log-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/log-details.ts
- packages/schemas/alterations/next-1671336831-refactor-log-types.ts
- packages/schemas/tables/logs.sql
follow-up of #2675 
- write migrate scripts to migrate old token exchange log keys
- write migrate scripts to change log table column type -> key
- update Admin Console display components accordingly
locally
> refactor: log types 2

- packages/console/src/components/ConnectorLogo/index.tsx
- packages/console/src/pages/ConnectorDetails/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
- packages/console/src/pages/Connectors/components/CreateForm/index.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/AddButton.tsx
- packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/SelectedConnectorItem.tsx
use `logoDark` for all possible places.
> fix(console): use connector dark logo

- packages/console/src/App.tsx
- packages/console/src/pages/ApiResources/index.tsx
- packages/console/src/pages/ApplicationDetails/index.tsx
- packages/console/src/pages/Applications/index.tsx
- packages/console/src/pages/Users/index.tsx
Align with designer:
Modals used to create data should have a route.
Test locally.
> refactor(console): add routes for create modals

- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/connectors.ts
- packages/phrases/src/locales/en/translation/admin-console/connectors.ts
- packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
add toggle tip for connector target field
> feat(console): add toggle tip for connector target field

- packages/console/src/pages/Users/index.tsx
fix(console): `buildUserDetailsPathname`.
Test locally.
> fix(console): `buildUserDetailsPathname`

- .changeset/silly-rules-laugh.md
add changeset of connector-kit update
> chore: add changeset of connector-kit update

- .changeset/pre.json
- packages/toolkit/connector-kit/CHANGELOG.md
- packages/toolkit/connector-kit/package.json
manually run changeset version and publish - will add a workflow soon
/
> release: toolkit packages

- packages/console/src/components/Table/StickyHeaderTable.module.scss
- packages/console/src/components/Table/StickyHeaderTable.tsx
- packages/console/src/pages/Applications/index.tsx
The table scroll bar should not reach the table header.
Refactor all related pages.
> fix(console): table scrollbar on the applications page

- packages/console/src/consts/index.ts
- packages/console/src/pages/UserDetails/index.tsx
- packages/console/src/pages/Users/components/CreateForm/index.tsx
- packages/console/src/pages/Users/index.tsx
The old create user process:
create a user (on the users page) -> display user password and user name (on the user-details page)
In this case, we need to pass generated password from the users page to the user-details page, which is considered as a not secure operation.
Current process:
create a user (on the users page) -> display user password and user name (on the users page) -> leave the information modal -> user-detais page.
Test locally.
> refactor(console): create user process

- packages/core/src/routes/interaction/types/guard.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
- packages/integration-tests/src/api/interaction.ts
- packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
- packages/integration-tests/src/tests/api/interaction/utils/connector.ts
- packages/integration-tests/src/utils.ts
- packages/schemas/src/types/interactions.ts
social register and sign-in integration test
Add two social integration test flows:
1. register new social and sign-in
2. bind new social with existing account and sign-in
TODO: bind new social with related email/phone  
test passed
> feat(test): social register and sign-in integration test

- packages/cli/package.json
- packages/console/package.json
- packages/core/package.json
- packages/demo-app/package.json
- packages/integration-tests/package.json
- packages/phrases-ui/package.json
- packages/phrases/package.json
- packages/schemas/package.json
- packages/shared/package.json
- packages/toolkit/connector-kit/package.json
- packages/toolkit/core-kit/package.json
- packages/toolkit/language-kit/package.json
- packages/ui/package.json
- pnpm-lock.yaml
supports typescript 4.9 https://prettier.io/blog/2022/11/23/2.8.0.html
CI
> chore(deps): upgrade prettier to v2.8.1

- Dockerfile
save some time
[skipped](https://github.com/logto-io/logto/actions/runs/3758889239/jobs/6387783459#step:4:235)
> release: skip download pptr in dockerfile

- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/types/guard.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
- packages/integration-tests/src/api/interaction.ts
- packages/integration-tests/src/client/index.ts
- packages/integration-tests/src/helpers.ts
- packages/integration-tests/src/tests/api/audit-logs/index.test.ts
- packages/integration-tests/src/tests/api/get-access-token.test.ts
- packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
- packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
- packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
- packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
- packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
- packages/integration-tests/src/tests/api/interaction/utils/client.ts
- packages/integration-tests/src/tests/api/interaction/utils/connector.ts
- packages/integration-tests/src/utils.ts
- packages/schemas/src/types/interactions.ts
update interaction integration test
test passed
> fix(test): update interaction integration test

- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/connectors.ts
- packages/phrases/src/locales/en/translation/admin-console/connectors.ts
- packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Fix typo: `tootip` -> `tooltip`
> chore: fix typo in i18n phrase key

- packages/integration-tests/src/tests/ui/smoke.test.ts
Sleep 1 second before each test case in the UI integration test, in order to improve the overall stability
> test: sleep 1s before each case to improve ui test stability

- packages/console/src/components/RadioGroup/index.tsx
Improve typing in RadioGroup component.
> refactor: improve typing in RadioGroup component

- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/utils/social-verification.test.ts
- packages/core/src/routes/interaction/utils/social-verification.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
Refactor `createSocialAuthorizationUrl` and `verifySocialIdentity`.
Passing in callback function as input parameters to outer layer of nested function call is not a good practice.
UTs and ITs.
> refactor(core): refactor createSocialAuthorizationUrl and verifySocialIdentity

- packages/console/src/components/Checkbox/index.module.scss
- packages/console/src/components/Checkbox/index.tsx
> fix(console): tooltip should point to box center of the checkbox

- packages/core/src/app/init.test.ts
- packages/core/src/libraries/hook.test.ts
- packages/core/src/libraries/hook.ts
- packages/core/src/middleware/koa-audit-log.test.ts
- packages/core/src/middleware/koa-audit-log.ts
- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
- packages/integration-tests/jest.setup.js
- packages/integration-tests/src/helpers.ts
- packages/integration-tests/src/tests/api/audit-logs/index.test.ts
- packages/integration-tests/src/tests/api/hooks.test.ts
- packages/integration-tests/src/utils.ts
- packages/shared/src/utils/function.test.ts
- packages/shared/src/utils/function.ts
- log hook result and update unit tests accordingly
- add integration tests to ensure hooks can be triggered and logged correctly
- update `trySafe()` to support non-promise functions
CI
> test: add integration tests for interaction hooks

- packages/console/src/App.tsx
- packages/console/src/consts/page-tabs.ts
- packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.tsx
- packages/console/src/pages/ConnectorDetails/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
- packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
- packages/console/src/pages/Connectors/components/Guide/index.tsx
- packages/console/src/pages/Connectors/index.tsx
- packages/console/src/pages/GetStarted/hook.ts
Add a create-route for the connectors page since now we handle the create modal as a new page.
Related issue: LOG-4891
Test locally.
> refactor(console): add create route for connectors page

- packages/phrases/src/locales/en/translation/admin-console/get-started.ts
Update wording in get-started subtitle.
> chore(console): update wording in get-started subtitle

- packages/console/src/components/FormCard/index.module.scss
- packages/console/src/components/FormCard/index.tsx
Add space to learn more links rather than use margins, for margins will cause unwanted space when the link is at the start of a paragraph.
> refactor(console): add space to learn more links

- packages/core/src/__mocks__/index.ts
- packages/core/src/connectors/types.ts
- packages/core/src/libraries/passcode.test.ts
- packages/core/src/libraries/passcode.ts
- packages/core/src/queries/passcode.test.ts
- packages/core/src/queries/passcode.ts
- packages/core/src/routes/interaction/utils/passcode-validation.test.ts
- packages/core/src/routes/interaction/utils/passcode-validation.ts
- packages/core/src/routes/session/continue.test.ts
- packages/core/src/routes/session/forgot-password.test.ts
- packages/core/src/routes/session/middleware/passwordless-action.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/types.ts
- packages/core/src/routes/session/utils.ts
- packages/integration-tests/package.json
- packages/integration-tests/src/api/session.ts
- packages/schemas/alterations/next-1672119200-align-passcode-type-with-message-type.ts
- packages/schemas/tables/passcodes.sql
- packages/ui/package.json
- packages/ui/src/apis/continue.test.ts
- packages/ui/src/apis/continue.ts
- packages/ui/src/apis/forgot-password.ts
- packages/ui/src/apis/index.test.ts
- packages/ui/src/apis/register.ts
- packages/ui/src/apis/sign-in.ts
- pnpm-lock.yaml
remove database `PasscodeType` and use `MessageTypes` as SSOT
we'll change `MessageTypes` to `VerificationCodeType` in the following PR
CI
> refactor!: align `PasscodeType` to `MessageTypes`

- packages/ui/src/apis/index.test.ts
- packages/ui/src/apis/interaction.ts
- packages/ui/src/apis/sign-in.ts
- packages/ui/src/containers/EmailPassword/index.test.tsx
- packages/ui/src/containers/EmailPassword/index.tsx
- packages/ui/src/containers/PasswordSignInForm/index.test.tsx
- packages/ui/src/containers/PasswordSignInForm/index.tsx
- packages/ui/src/containers/PhonePassword/index.test.tsx
- packages/ui/src/containers/PhonePassword/index.tsx
- packages/ui/src/containers/UsernameSignIn/index.test.tsx
- packages/ui/src/containers/UsernameSignIn/index.tsx
- packages/ui/src/hooks/use-password-sign-in.ts
Replace the password sign-in API with the latest interaction API
- username-password
- email-password
- phone-password
test locally
UT passed and updated
> refactor(ui): replace the password sign-in api

- packages/core/src/libraries/passcode.test.ts
- packages/core/src/libraries/passcode.ts
- packages/core/src/routes/session/forgot-password.test.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-br/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/ui/src/containers/PasscodeValidation/use-shared-error-handler.ts
Change content 'passcode' to 'verification code'.
CI
> chore(phrases,core): change 'passcode' to 'verification code' in content

- packages/integration-tests/src/tests/ui/smoke.test.ts
Try to improve UI e2e test stability
> test: improve ui test stability

- packages/console/src/components/DetailsSkeleton/index.module.scss
- packages/console/src/components/DetailsSkeleton/index.tsx
- packages/console/src/pages/SignInExperience/components/Skeleton/index.module.scss
- packages/console/src/pages/SignInExperience/components/Skeleton/index.tsx
Update loading skeletons according to new AC layouts.
> refactor(console): update loading skeletons

- packages/core/src/__mocks__/index.ts
- packages/core/src/connectors/types.ts
- packages/core/src/libraries/passcode.test.ts
- packages/core/src/libraries/passcode.ts
- packages/core/src/queries/passcode.test.ts
- packages/core/src/queries/passcode.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
- packages/core/src/routes/interaction/utils/passcode-validation.test.ts
- packages/core/src/routes/interaction/utils/passcode-validation.ts
- packages/core/src/routes/session/continue.test.ts
- packages/core/src/routes/session/forgot-password.test.ts
- packages/core/src/routes/session/middleware/passwordless-action.ts
- packages/core/src/routes/session/passwordless.test.ts
- packages/core/src/routes/session/passwordless.ts
- packages/core/src/routes/session/types.ts
- packages/core/src/routes/session/utils.ts
- packages/integration-tests/src/api/session.ts
- packages/toolkit/connector-kit/src/types.ts
align naming. other "passcode"s will be replaced to "verification code" before GA
CI
> refactor: rename `MessageTypes` -> `VerificationCodeType`

- packages/core/src/utils/format.test.ts
- packages/core/src/utils/format.ts
- packages/ui/src/apis/index.test.ts
- packages/ui/src/apis/interaction.ts
- packages/ui/src/apis/social.ts
- packages/ui/src/apis/utils.ts
- packages/ui/src/containers/SocialCreateAccount/index.test.tsx
- packages/ui/src/containers/SocialCreateAccount/index.tsx
- packages/ui/src/hooks/use-bind-social.ts
- packages/ui/src/hooks/use-social-sign-in-listener.ts
- packages/ui/src/hooks/use-social.ts
- packages/ui/src/pages/SocialSignInCallback/index.test.tsx
- packages/ui/src/types/guard.ts
replace social flow api
test locally
ut updated
> refactor(ui): replace social flow api

- packages/core/src/routes/interaction/index.ts
- packages/ui/src/pages/Passcode/index.tsx
forgot password verification page 404. 
Should not verify for the forgotpassword page
test locally
@xiaoyijun
> fix(ui): forgotpassword passcode verification page 404

- packages/console/src/components/Select/index.module.scss
- packages/console/src/pages/SignInExperience/components/Preview/index.module.scss
update select component style according to the design file:
change size of the preview language selector to 112px:
Test locally.
> style(console): update select component style

- packages/console/src/pages/ConnectorDetails/index.tsx
fix(console): close deletion modal on connector changed
bug:
> fix(console): close deletion modal on connector changed

- packages/console/src/pages/UserDetails/index.tsx
fix(console): close modal on tab changed on user details page
Bug:
> fix(console): close modal on tab changed on user details page

- .github/workflows/changesets.yml
- .github/workflows/release.yml
- fix release workflow
- remove explicit node 18 option as it's already the default
after merge
> ci: fix workflows

- packages/integration-tests/src/__mocks__/connectors-mock.ts
- packages/integration-tests/src/tests/api/connector.test.ts
Fix IT due to new publish of mock connector.
Passed IT.
> fix: fix IT due to publish of mock connector

- .github/workflows/integration-test.yml
- .scripts/package.sh
- packages/cli/src/commands/connector/utils.ts
- add official connectors in source dist just like docker image
- check if official connectors exist in integration test workflow
CI
> refactor: add official connectors in dist

- .github/workflows/release.yml
- .scripts/publish.js
fix typo and log stdout when exec failed
should be good in master now
> ci: fix publish workflow

- .github/workflows/main.yml
- .scripts/check-alterations-sequence.js
- packages/cli/src/commands/database/alteration/index.ts
Add a workflow which runs a task to check alteration files seqence: new files should come last.
Then if a new commit is pushed to master (or PR merge), this workflow will run and throw an error if checks don't pass, to warn the developer to take a look.
commit this file:
then run the script:
> ci: check alteration sequence

- .scripts/check-alterations-sequence.js
Forget to rebase, the master branch is changed to use esm for `.scripts`.
Local tested
> ci: use import to fix alteration sequence check

- packages/console/src/pages/ApiResources/index.module.scss
- packages/console/src/pages/ApiResources/index.tsx
refactor api-resources table with new `<Table />` component.
Test locally.
> refactor(console): api resources table

- .changeset/lovely-rivers-sniff.md
> chore: add toolkit changeset

- .github/workflows/changesets.yml
- .scripts/version.js
- packages/integration-tests/package.json
- pnpm-lock.yaml
use group strategy for creating PRs and releases
PR created, error is due to the old command and should be fine after this PR is merged.
> ci: separate release groups

- .github/workflows/release.yml
otherwise existing tags won't be pulled
/
> ci: use depth 0 in checkout to fetch all tags

- packages/console/src/components/CopyToClipboard/index.module.scss
- packages/console/src/components/CopyToClipboard/index.tsx
- packages/console/src/components/Tip/TipBubble/index.module.scss
- packages/console/src/components/Tip/TipBubble/index.tsx
- packages/console/src/components/Tip/Tooltip/index.tsx
- packages/console/src/pages/ConnectorDetails/components/SenderTester/index.module.scss
- packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
the color of "Copied" tooltip should be green
> style(console): successful tooltip state

- packages/console/src/pages/UserDetails/components/ResetPasswordForm.tsx
add loading state to confirm reset password form
Test locally.
> refactor(console): add loading state to confirm reset password form

- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
Fix connector form tips to align with design.
Local tested
> fix(console): fix connector form tips

- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/connectors.ts
- packages/phrases/src/locales/en/translation/admin-console/connectors.ts
- packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
Add tips on sync profile field.
> fix(console): add sync profile tip

- packages/console/src/components/CodeEditor/index.module.scss
- packages/console/src/components/CodeEditor/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
- packages/console/src/utilities/validator.ts
Add jsonValidator to connector config field.
> fix(console): add json validator to connector config

- packages/ui/src/pages/Passcode/index.tsx
format phone number
test locally
> fix(ui): format phone number

- packages/console/src/pages/ConnectorDetails/index.module.scss
- packages/console/src/pages/ConnectorDetails/index.tsx
- packages/core/src/routes/connector.ts
display standard connector name (e.g. OIDC) for created connector.
> fix(console): display standard connector name

- packages/core/src/routes/interaction/actions/submit-interaction.test.ts
- packages/core/src/routes/interaction/actions/submit-interaction.ts
add social sync profile on sign-in
new UT added and passed
IT passed
> fix(core): add social sync profile on sign-in

- packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
show standard connector name in table
> feat(console): show standard connector name in table

- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
Update testing passcode to fixed 000000, for both SMS and email methods.
> chore: update testing passcode

- packages/phrases/src/locales/de/translation/admin-console/connectors.ts
- packages/phrases/src/locales/en/translation/admin-console/connectors.ts
- packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
update AC connector name tip content.
> chore: update AC connector name tip content

- packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
- packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
register with social should not ask for password again as social can take place of the password requirements
UT added
> fix(core): register with social should not ask for password

- packages/console/src/consts/logs.ts
- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/utils/passcode-validation.ts
- packages/core/src/routes/interaction/utils/social-verification.test.ts
- packages/core/src/routes/interaction/utils/social-verification.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
- packages/schemas/src/types/log/interaction.ts
add interaction API logs
UT passed
> feat(core): add interaction api logs

- .changeset/moody-timers-grin.md
> chore: add connect-kit changeset

- .changeset/plenty-ties-divide.md
- .changeset/quiet-shrimps-flow.md
- .changeset/six-mayflies-tan.md
- .changeset/small-knives-swim.md
- .scripts/package.sh
> chore: add new year release changesets

- .changeset-staged/README.md
- .dockerignore
- .scripts/package.sh
see readme. it's a temp solution until we find a proper one in the future.
/
> chore: add changeset-staged dir

- .github/workflows/pen-tests.yml
the report should be sent to slack instead of opening a public issue
/
> ci: turn off zap issue

- packages/console/src/hooks/use-connector-in-use.ts
- packages/console/src/pages/ConnectorDetails/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
The `useConnectorInUse` hook is better to be used at the data level instead of the page level, and we need to use the `isConnectorInUse` utilities in later page refactors.
> refactor(console): `useConnectorInUse` hook

- docker-compose.yml
> chore: improve comment for docker compose file

- packages/core/src/connectors/types.ts
- packages/core/src/libraries/social.ts
- packages/core/src/routes/interaction/types/guard.ts
- packages/core/src/routes/interaction/types/index.ts
- packages/core/src/routes/interaction/utils/social-verification.ts
- packages/core/src/routes/profile.test.ts
- packages/core/src/routes/session/social.test.ts
- packages/toolkit/connector-kit/src/types.ts
Define optional keys for connector.getUserInfo.
UTs
> feat(toolkit): define optional keys for connector.getUserInfo

- packages/core/src/__mocks__/index.ts
- packages/core/src/libraries/resource.test.ts
- packages/core/src/libraries/resource.ts
- packages/core/src/queries/scope.ts
- packages/core/src/routes/resource.test.ts
- packages/core/src/routes/resource.ts
- packages/schemas/src/types/index.ts
- packages/schemas/src/types/resource.ts
list resources with scopes: `GET /resource?includeScopes=true`
UTs
> feat(core): list resources with scopes

- packages/console/src/App.tsx
- packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
- packages/console/src/pages/RoleDetails/index.module.scss
- packages/console/src/pages/RoleDetails/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/index.ts
- packages/phrases/src/locales/de/translation/admin-console/role-details.ts
- packages/phrases/src/locales/en/translation/admin-console/index.ts
- packages/phrases/src/locales/en/translation/admin-console/role-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/index.ts
- packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/index.ts
- packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
feat(console): role details settings page
- delete role
- role users tab
- role permissions tab
> feat(console): role details settings page

- packages/console/src/App.tsx
- packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
- packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
- packages/console/src/pages/Roles/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/roles.ts
- packages/phrases/src/locales/en/translation/admin-console/roles.ts
- packages/phrases/src/locales/fr/translation/admin-console/roles.ts
- packages/phrases/src/locales/ko/translation/admin-console/roles.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
feat(console): create role
- add permissions to the role
- assign the role to users
> feat(console): create role

- packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
- packages/console/src/pages/RoleDetails/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/role-details.ts
- packages/phrases/src/locales/en/translation/admin-console/role-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
> feat(console): delete role

- packages/console/src/components/Pagination/index.module.scss
- packages/console/src/components/Pagination/index.tsx
- packages/console/src/pages/Applications/index.tsx
refactor(console): support tiny pagination variant
> refactor(console): support tiny pagination variant

- packages/core/src/queries/roles-scopes.ts
- packages/core/src/queries/scope.ts
- packages/core/src/routes/role.test.ts
- packages/core/src/routes/role.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-br/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/schemas/alterations/next-1672901841-roles-and-scopes-not-null.ts
- packages/schemas/tables/scopesroles.sql
Add the following API:
- `GET /roles/:id/scopes`
- `POST /roles (with scopeIds)`
- `POST /roles/:id/scopes`
- `DELETE /roles/:id/scopes/:scopeId`
UTs
> feat(core): role-scope api

- .changeset/slow-meals-enjoy.md
- .scripts/version.js
manually run `version` script after `changeset version`
> fix: version lifecycle script

- packages/toolkit/connector-kit/src/types.ts
Add a new `Generic` verification code type and mark `Continue` code type as deprecated
> refactor: add Generic type and remove deprecated Continue code type

- packages/console/src/components/Table/index.module.scss
- packages/console/src/components/Table/index.tsx
- packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
- packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.module.scss
- packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
- Refactor the Table component to support filter content
- Create permission on the permissions table
- Search permission
- permission paginations
- delete permission
> feat(console): create permission

- packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
feat(console): delete permission
> feat(console): delete permission

- packages/core/src/routes/resource.ts
> fix(core): fix typo

- packages/core/src/queries/user.ts
- packages/core/src/queries/users-roles.ts
- packages/core/src/routes/admin-user-role.test.ts
- packages/core/src/routes/admin-user-role.ts
- packages/core/src/routes/init.ts
- packages/core/src/routes/role.test.ts
- packages/core/src/routes/role.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-br/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
GET /users/:id/roles
GET /roles/:id/users
POST /roles/:id/users
DELETE /roles/:id/users/:userId
POST /users/:id/roles
DELETE /users/:id/roles/:roleId
UTs
> feat(core): user-role related api

- packages/core/src/libraries/resource.test.ts
- packages/core/src/libraries/resource.ts
- packages/core/src/queries/roles.ts
- packages/core/src/queries/scope.ts
- packages/core/src/queries/user.ts
prevent empty array to be used by sql `in`, which will raise an error.
UTs
> fix(core): prevent empty array to be used by sql in

- packages/core/src/queries/resource.ts
- packages/core/src/routes/role.test.ts
- packages/core/src/routes/role.ts
- packages/schemas/src/types/index.ts
- packages/schemas/src/types/scope.ts
`GET /roles/:roleId/scopes`: add resource to scope
UTs
> feat(core): add resource to response scopes

- package.json
- packages/cli/package.json
- packages/cli/src/commands/install/utils.ts
- packages/console/package.json
- packages/core/package.json
- packages/create/package.json
- packages/demo-app/package.json
- packages/integration-tests/package.json
- packages/phrases-ui/package.json
- packages/phrases/package.json
- packages/schemas/package.json
- packages/shared/package.json
- packages/toolkit/connector-kit/package.json
- packages/toolkit/core-kit/package.json
- packages/toolkit/language-kit/package.json
- packages/ui/package.json
- pnpm-lock.yaml
> chore!: drop Node 16

- packages/core/src/queries/roles.test.ts
- packages/core/src/queries/roles.ts
- packages/core/src/routes/role.test.ts
- packages/core/src/routes/role.ts
Add search support and pagination for `GET /roles`
UTs and local tested.
> feat(core): add search and pagination for roles

- packages/core/src/middleware/koa-pagination.ts
- packages/core/src/queries/scope.ts
- packages/core/src/routes/resource.test.ts
- packages/core/src/routes/resource.ts
add search and optional pagination to `GET /resources/:id/scopes`
UTs
> feat(core): add search and optional pagination to scopes

- packages/core/src/queries/resource.ts
- packages/core/src/routes/resource.test.ts
- packages/core/src/routes/resource.ts
Set resources pagination to optional.
UTs
> feat(core): set resources pagination to optional

- packages/schemas/alterations/next-1673001922-support-generic-passcode.ts
- packages/schemas/tables/passcodes.sql
* Alter `passcodes` table and set `interaction_jti` column to nullable
* Build 2 more indexes to support data query by `phone + type` and `email + type`
> refactor(schemas): alter passcodes table and set jti to nullable

- packages/core/src/queries/roles.ts
- packages/core/src/routes/role.ts
set roles pagination to optional
UTs
> feat(core): set roles pagination to optional

- packages/core/src/queries/roles.ts
- packages/core/src/queries/users-roles.ts
- packages/core/src/routes/role.test.ts
- packages/core/src/routes/role.ts
- packages/schemas/src/types/index.ts
- packages/schemas/src/types/role.ts
`GET /roles?page=1` will contain `usersCount` and `featuredUsers`
UTs
> feat(core): count role users and featured users

- packages/core/src/routes/admin-user.ts
Add a new param "excludeRoleId" to `GET /users`
Local tested.
> feat(core): filter users by exclude role id

- packages/console/src/components/RoleUsersTransfer/SourceUsersBox.tsx
- packages/console/src/components/RoleUsersTransfer/TargetUsersBox.tsx
- packages/console/src/components/RoleUsersTransfer/UserSourceBox.tsx
- packages/console/src/components/RoleUsersTransfer/index.module.scss
- packages/console/src/components/RoleUsersTransfer/index.tsx
feat(console): role users transfer component
https://www.figma.com/file/9g90szl22ypDd66qQHacp8/%F0%9F%8E%AD-RBAC?node-id=4%3A47725&t=42KOLrzZOXDZVfJ9-4
> feat(console): role users transfer component

- packages/core/package.json
- packages/core/src/app/init.test.ts
- packages/core/src/app/init.ts
- packages/core/src/tenants/Tenant.test.ts
- packages/core/src/tenants/Tenant.ts
- packages/core/src/tenants/index.ts
- pnpm-lock.yaml
move app in a tenant instance to prepare for the full tenant context
CI + local Chrome
> refactor(core): move app to tenant instance

- .github/workflows/release.yml
deploy next alteration scripts before deploying app
after merge
> ci: deploy db alteration before app

- packages/cli/src/commands/database/seed/index.ts
- packages/schemas/src/seeds/index.ts
- packages/schemas/src/seeds/resource.ts
- packages/schemas/src/seeds/roles.ts
- packages/schemas/src/seeds/scope.ts
seed default scope for management api
Local tested:
> feat(schemas,cli): seed default scope for management api

- packages/console/src/App.tsx
- packages/console/src/consts/page-tabs.ts
- packages/console/src/pages/UserDetails/UserRoles/index.module.scss
- packages/console/src/pages/UserDetails/UserRoles/index.tsx
- packages/console/src/pages/UserDetails/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/user-details.ts
- packages/phrases/src/locales/en/translation/admin-console/user-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
- List user roles on the user details page
- Remove roles from the user
- Search user roles by roles name
- Assign roles to the user
> feat(console): user roles page

- packages/console/src/App.tsx
- packages/console/src/consts/page-tabs.ts
- packages/console/src/pages/RoleDetails/RoleUsers/index.module.scss
- packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
- packages/console/src/pages/RoleDetails/index.module.scss
- packages/console/src/pages/RoleDetails/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/role-details.ts
- packages/phrases/src/locales/en/translation/admin-console/role-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
feat(console): role users page
- search role
- pagination
> feat(console): role users page

- packages/core/src/queries/oidc-model-instance.ts
- packages/core/src/queries/passcode.ts
- packages/core/src/queries/resource.ts
- packages/core/src/queries/roles-scopes.ts
- packages/core/src/queries/roles.ts
- packages/core/src/queries/scope.ts
- packages/core/src/queries/setting.ts
- packages/core/src/queries/sign-in-experience.ts
resolves LOG-5104, LOG-5105, LOG-5106, LOG-5107, LOG-5108, LOG-5109, LOG-5110, LOG-5111
CI
> refactor(core): multiple query factories

- packages/core/src/queries/user.ts
- packages/core/src/queries/users-roles.ts
resolves LOG-5112, LOG-5113
CI
> refactor(core): users and users roles query factories

- packages/cli/src/commands/database/alteration/meta-url.ts
- packages/cli/src/commands/database/alteration/utils.ts
- packages/cli/src/meta-url.ts
- packages/cli/src/utilities.ts
> refactor: remove unused files

- packages/core/src/queries/roles.ts
Hide the special role for admin console.
Local tested
> feat(core): hide admin console role

- packages/core/src/routes/interaction/consent.test.ts
- packages/core/src/routes/interaction/consent.ts
- packages/core/src/routes/interaction/const.ts
- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/test-utils/oidc-provider.ts
- packages/core/src/test-utils/tenant.ts
- packages/integration-tests/src/api/interaction.ts
- packages/integration-tests/src/api/session.ts
- packages/integration-tests/src/client/index.ts
- packages/ui/src/apis/consent.ts
- packages/ui/src/apis/index.test.ts
migrate consent API to the interaction routes. Prepare the session API deprecation. 
UT added
IT updated and passed
test locally
> refactor(core,ui,test): migrate consent api to interaction

- packages/console/src/components/Checkbox/index.module.scss
- packages/console/src/components/Checkbox/index.tsx
* Fix the issue that indeterminate state not working properly
* Fix the React warning by removing the internal input element, as it's not used at all
> fix(console): fix indeterminate state issue and react warning in checkbox component

- packages/core/src/queries/scope.ts
- packages/core/src/routes/resource.test.ts
- packages/core/src/routes/resource.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-br/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/schemas/alterations/next-1673165463-scope-name-index.ts
- packages/schemas/tables/scopes.sql
scope name within the same resource should be unique
UTs
> feat(core): scope name within the same resource should be unique

- packages/core/src/libraries/shared.ts
- packages/core/src/libraries/sign-in-experience/index.test.ts
- packages/core/src/libraries/sign-in-experience/index.ts
- packages/core/src/libraries/user.ts
- packages/core/src/routes/application.test.ts
- packages/core/src/routes/init.ts
- packages/core/src/routes/profile.ts
- packages/core/src/routes/sign-in-experience/guard.branding.test.ts
- packages/core/src/routes/sign-in-experience/guard.color.test.ts
- packages/core/src/routes/sign-in-experience/guard.test.ts
- packages/core/src/routes/sign-in-experience/index.test.ts
- packages/core/src/routes/sign-in-experience/index.ts
- packages/core/src/routes/well-known.test.ts
- packages/core/src/routes/well-known.ts
- packages/core/src/tenants/Libraries.ts
- packages/core/src/test-utils/tenant.ts
- migrate `libraries/sign-in-experience/*` to the factory mode and update related routes using the new factories
CI
> refactor(core): migrate sie library to factory mode

- packages/core/src/libraries/connector.test.ts
- packages/core/src/libraries/connector.ts
- packages/core/src/libraries/sign-in-experience/index.test.ts
- packages/core/src/libraries/sign-in-experience/index.ts
- packages/core/src/libraries/user.test.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
- packages/core/src/routes/connector.update.test.ts
- packages/core/src/routes/session/social.test.ts
- packages/core/src/routes/sign-in-experience/guard.branding.test.ts
- packages/core/src/routes/sign-in-experience/guard.color.test.ts
- packages/core/src/routes/sign-in-experience/guard.test.ts
- packages/core/src/routes/sign-in-experience/index.test.ts
- packages/core/src/routes/sign-in-experience/index.ts
- packages/core/src/routes/well-known.test.ts
- packages/core/src/routes/well-known.ts
- packages/core/src/tenants/Libraries.ts
- packages/core/src/test-utils/tenant.ts
migrate connector library to the factory mode and update related routes using the new factories
CI
> refactor(core): migrate connector library to factory mode

- packages/core/src/env-set/index.ts
- packages/core/src/libraries/__mocks__/logto-config.ts
- packages/core/src/libraries/logto-config.ts
factory mode is good, part of the libraries factory migration
CI
> refactor(core): migrate logto config library to factory mode

- packages/core/src/libraries/phrase.test.ts
- packages/core/src/libraries/phrase.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/phrase.content-language.test.ts
- packages/core/src/routes/phrase.test.ts
- packages/core/src/routes/phrase.ts
- packages/core/src/tenants/Libraries.ts
migrate phrase library to factory mode and update test cases accordingly
CI
> refactor(core): migrate phrase library to factory mode

- packages/core/src/queries/user.ts
fix findUsersByIds for empty ids case
UTs
> fix(core): fix findUsersByIds for empty ids case

- packages/console/src/components/RoleUsersTransfer/SourceUsersBox.tsx
- packages/console/src/components/RoleUsersTransfer/index.tsx
- packages/console/src/pages/RoleDetails/RoleUsers/components/AssignUsersModal/index.tsx
- packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
- packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/general.ts
- packages/phrases/src/locales/de/translation/admin-console/role-details.ts
- packages/phrases/src/locales/en/translation/admin-console/general.ts
- packages/phrases/src/locales/en/translation/admin-console/role-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/general.ts
- packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/general.ts
- packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
feat(console): assign users to a role
> feat(console): assign users to a role

- packages/core/package.json
- packages/core/src/libraries/resource.test.ts
- packages/core/src/libraries/resource.ts
- packages/core/src/routes/resource.test.ts
- packages/core/src/routes/resource.ts
- packages/core/src/tenants/Libraries.ts
migrate resource library to factory mode and update test cases accordingly
CI
> refactor(core): migrate resource library to factory mode

- packages/core/package.json
- packages/core/src/libraries/hook.test.ts
- packages/core/src/libraries/hook.ts
- packages/core/src/middleware/koa-audit-log.test.ts
- packages/core/src/middleware/koa-audit-log.ts
- packages/core/src/model-routers/index.ts
- packages/core/src/oidc/init.test.ts
- packages/core/src/oidc/init.ts
- packages/core/src/routes/hook.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
- packages/core/src/tenants/Libraries.ts
- packages/core/src/tenants/Tenant.ts
- packages/core/src/tenants/TenantContext.ts
- packages/core/src/test-utils/tenant.ts
create hook library factory and add model routers in tenant context
CI
> refactor(core): migrate hook library to factory mode

- packages/core/src/queries/roles.ts
- packages/core/src/routes/role.ts
- packages/shared/src/database/utils.ts
List roles filter by userId: list roles that are not assigned to the user.
Local tested
> feat(core): list roles filter by userId

- packages/console/src/components/AuditLogTable/index.tsx
- packages/console/src/components/RoleUsersTransfer/SourceUsersBox.tsx
- packages/console/src/pages/ApiResources/index.tsx
- packages/console/src/pages/Applications/index.tsx
- packages/console/src/pages/Users/index.tsx
- packages/console/src/utilities/url.ts
- Add a `buildUrl` util to build URL
- Replace handwriting URLs with `buildUrl`.
Test locally.
> refactor(console): build url by `buildUrl` util

- packages/console/src/components/AuditLogTable/index.tsx
- packages/console/src/components/RoleUsersTransfer/SourceUsersBox.tsx
- packages/console/src/pages/ApiResources/index.tsx
- packages/console/src/pages/Applications/index.tsx
- packages/console/src/pages/Users/index.tsx
refactor(console): parse number to string by `String()`
Test locally.
> refactor(console): parse number to string by `String()`

- packages/core/src/libraries/social.ts
- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/utils/social-verification.test.ts
- packages/core/src/routes/interaction/utils/social-verification.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
- packages/core/src/routes/interaction/verifications/identifier-verification.test.ts
- packages/core/src/routes/interaction/verifications/identifier-verification.ts
- packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
- packages/core/src/routes/interaction/verifications/user-identity-verification.ts
- packages/core/src/tenants/Libraries.ts
perform in-context actions for social library by implementing factory mode
CI
> refactor(core): migrate social library to factory mode

- packages/core/src/libraries/passcode.test.ts
- packages/core/src/libraries/passcode.ts
- packages/core/src/libraries/phrase.test.ts
- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/utils/verification-code-validation.test.ts
- packages/core/src/routes/interaction/utils/verification-code-validation.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
- packages/core/src/tenants/Libraries.ts
perform in-context actions for passcode library by implementing factory mode
CI
> refactor(core): migrate passcode library to factory mode

- packages/core/package.json
- packages/core/src/libraries/connector.ts
- packages/core/src/libraries/shared.ts
- packages/core/src/libraries/sign-in-experience/index.ts
- packages/core/src/libraries/user.ts
- packages/core/src/routes/interaction/actions/submit-interaction.test.ts
- packages/core/src/routes/interaction/actions/submit-interaction.ts
- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/middleware/koa-interaction-sie.ts
- packages/core/src/routes/interaction/utils/find-user-by-identifier.test.ts
- packages/core/src/routes/interaction/utils/find-user-by-identifier.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
- packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
- packages/core/src/routes/interaction/verifications/identifier-verification.test.ts
- packages/core/src/routes/interaction/verifications/identifier-verification.ts
- packages/core/src/routes/interaction/verifications/profile-verification.forgot-password.test.ts
- packages/core/src/routes/interaction/verifications/profile-verification.profile-exist.test.ts
- packages/core/src/routes/interaction/verifications/profile-verification.profile-registered.test.ts
- packages/core/src/routes/interaction/verifications/profile-verification.protected-identifier.test.ts
- packages/core/src/routes/interaction/verifications/profile-verification.ts
- packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
- packages/core/src/routes/interaction/verifications/user-identity-verification.ts
now all library functions will run in a tenant context
CI
> refactor(core): remove deprecated library functions

- packages/core/src/queries/users-roles.ts
- packages/core/src/routes/admin-user.test.ts
- packages/integration-tests/src/api/admin-user.ts
- packages/integration-tests/src/tests/api/admin-user.roles.test.ts
add IT for routes starting with `/users/:userId/roles`
ITs
> test: add it for admin-user roles

- packages/console/src/components/ModalLayout/index.tsx
- packages/console/src/components/UserRolesTransfer/components/SourceRoleItem/index.module.scss
- packages/console/src/components/UserRolesTransfer/components/SourceRoleItem/index.tsx
- packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.module.scss
- packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.tsx
- packages/console/src/components/UserRolesTransfer/components/TargetRoleItem/index.module.scss
- packages/console/src/components/UserRolesTransfer/components/TargetRoleItem/index.tsx
- packages/console/src/components/UserRolesTransfer/components/TargetRolesBox/index.module.scss
- packages/console/src/components/UserRolesTransfer/components/TargetRolesBox/index.tsx
- packages/console/src/components/UserRolesTransfer/index.module.scss
- packages/console/src/components/UserRolesTransfer/index.tsx
- packages/console/src/hooks/use-debounce.ts
- packages/console/src/pages/UserDetails/UserRoles/components/AssignRolesModal/index.tsx
- packages/console/src/pages/UserDetails/UserRoles/index.tsx
- packages/console/src/scss/transfer.module.scss
- packages/phrases/src/locales/de/translation/admin-console/user-details.ts
- packages/phrases/src/locales/en/translation/admin-console/user-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
- Assign roles to user
- Add the `UserRolesTranfer` component
- Extract common transfer styles into `transfer.module.scss`
- Share transfer component styles: LOG-5148
> feat(console): assign roles to user

- packages/console/src/components/Pagination/index.tsx
- packages/console/src/components/Table/index.module.scss
- packages/console/src/components/Table/index.tsx
- packages/console/src/consts/index.ts
- packages/console/src/hooks/use-table-search-params.ts
- packages/console/src/pages/Roles/index.tsx
- Extract pagination & search logic into `useTableSearchParams` hook
- Support pagination and search on the roles page
- Support pagination in the `TableComponent`
> refactor(console): support pagination and search on the roles page

- packages/integration-tests/src/tests/api/admin-user.roles.test.ts
Fix import file path to avoid building error.
Builds on CI.
> fix(test): fix import file path

- packages/integration-tests/src/api/scope.ts
- packages/integration-tests/src/tests/api/resource.scope.test.ts
- packages/integration-tests/src/utils.ts
> test: add IT for scopes

- packages/core/src/routes/role.test.ts
- packages/core/src/routes/role.ts
- packages/integration-tests/src/api/role.ts
- packages/integration-tests/src/tests/api/resource.scope.test.ts
- packages/integration-tests/src/tests/api/role.scope.test.ts
- packages/integration-tests/src/tests/api/role.test.ts
- packages/integration-tests/src/tests/api/role.user.test.ts
- packages/integration-tests/src/utils.ts
> test: add integration tests for roles

- packages/core/src/libraries/user.test.ts
- packages/core/src/libraries/user.ts
- packages/core/src/oidc/init.ts
- packages/core/src/queries/roles-scopes.ts
- packages/core/src/queries/scope.ts
implement oidc `getResourceServerInfo` to support granting access token with scopes.
UTs and local tested.
> feat(core): implement oidc getResourceServerInfo

- packages/console/src/pages/Roles/components/AssignedUsers/index.module.scss
- packages/console/src/pages/Roles/components/AssignedUsers/index.tsx
- packages/console/src/pages/Roles/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/roles.ts
- packages/phrases/src/locales/en/translation/admin-console/roles.ts
- packages/phrases/src/locales/fr/translation/admin-console/roles.ts
- packages/phrases/src/locales/ko/translation/admin-console/roles.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
feat(console): add assigned users column to roles table
> feat(console): add assigned users column to roles table

- packages/ui/src/containers/VerificationCode/use-identifier-error-alert.ts
- packages/ui/src/containers/VerificationCode/use-register-flow-code-verification.ts
- packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
format phone numbers in multiple places
test locally
> fix(ui): format phone number in multiple places

- packages/ui/src/components/Button/SocialLinkButton.module.scss
- packages/ui/src/components/Button/index.module.scss
update social button style
1. max two rows, overflow ellipsis
2. All button font line-height should be the same as font-size. 
test locally
> style(ui): update social button style

- packages/ui/src/assets/icons/radio-button-icon.svg
- packages/ui/src/components/BrandingHeader/index.module.scss
- packages/ui/src/components/Checkbox/index.tsx
- packages/ui/src/components/Input/phoneInput.module.scss
- packages/ui/src/components/TextLink/index.module.scss
- packages/ui/src/components/TextLink/index.tsx
- packages/ui/src/containers/AppNotification/index.module.scss
- packages/ui/src/containers/OtherMethodsLink/index.tsx
- packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModalContent/index.tsx
- packages/ui/src/containers/VerificationCode/index.module.scss
Change the basic style of some components, like color, size, and image.
- Update the branding logo height
- Remove the radio button style check box component for mobile, use the same square checkbox style as desktop. 
- Update the PhoneInput country code drop down icon color.
- Fix the inline Textlink font-size issue. Should inherit from the parent element.
- Fix the DemoApp notification styling, should center align on the widescreen device like iPad
- Remove the branding color for the verification-code count-down number text. Use the default font color instead. 
test locally
> style(ui): minor ui iteration

- packages/core/src/queries/scope.ts
- packages/core/src/routes/init.ts
- packages/core/src/routes/resource.test.ts
- packages/core/src/routes/resource.ts
- packages/core/src/routes/role.scope.test.ts
- packages/core/src/routes/role.scope.ts
- packages/core/src/routes/role.test.ts
- packages/core/src/routes/role.ts
add search and pagination to role scopes
UTs
> feat(core): add search and pagination to role scopes

- packages/core/src/queries/user.ts
- packages/core/src/routes/role.test.ts
- packages/core/src/routes/role.ts
add pagination and search to role users
UTs.
> feat(core): add pagination and search to role users

- packages/core/src/queries/roles.ts
- packages/core/src/routes/admin-user-role.test.ts
- packages/core/src/routes/admin-user-role.ts
- packages/core/src/routes/role.test.ts
- packages/core/src/routes/role.ts
- packages/integration-tests/src/tests/api/admin-user.roles.test.ts
add pagination and search to user roles api.
UTs and local tested.
> feat(core): add pagination and search to user roles api

- packages/console/src/components/Checkbox/index.tsx
- packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.tsx
- packages/console/src/components/RoleScopesTransfer/components/SourceScopeItem/index.tsx
- packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.tsx
- packages/console/src/components/UserRolesTransfer/components/SourceRoleItem/index.tsx
Make the `disabled` prop of the `CheckBox` optional
Test locally.
> refactor(console): make the `disabled` prop of the `CheckBox` optional

- .changeset-staged/cyan-buses-trade.md
- .changeset-staged/large-windows-scream.md
- .changeset-staged/tender-maps-burn.md
Add changeset files with all the previous breaking change PRs.
> chore(core): add changeset files

- packages/console/src/components/PermissionsTable/index.module.scss
- packages/console/src/components/PermissionsTable/index.tsx
- packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
- packages/console/src/pages/RoleDetails/RolePermissions/index.tsx
- packages/console/src/pages/RoleDetails/RoleUsers/index.module.scss
- packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
- packages/console/src/pages/UserDetails/UserRoles/index.module.scss
- packages/console/src/pages/UserDetails/UserRoles/index.tsx
Support pagination on rbac-related pages：
- API Resource Details -> Permissions Page
- Role Details -> Permissions Page
- Role Details -> Users Page
- User Details -> Roles Page
Test locally.
> refactor(console): support pagination on rbac-related pages

- packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
- packages/toolkit/core-kit/src/regex.ts
Do not allow spaces in permission names since OIDC separates scopes by space.
> refactor(console): do not allow spaces in the permission name

- packages/console/src/components/PermissionsTable/index.tsx
- packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
refactor(console): make scopes of the management api readonly
> refactor(console): make scopes of the management api readonly

- packages/schemas/alterations/next-1673349501-sms-sign-in-identifier-to-phone.ts
Update sms alteration script. Found an existing old bug in `1.0.0_beta.14-1665300135-sign-in-sign-up.ts`. In case someone has dirty data remaining in DB.  force lowercase. 
test locally
> fix(schemas): update sms alteration script

- packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.module.scss
- packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.tsx
- packages/console/src/components/RoleScopesTransfer/components/SourceScopeItem/index.module.scss
- Adjust the component styles according to the design file: 
https://www.figma.com/file/9g90szl22ypDd66qQHacp8/%F0%9F%8E%AD-RBAC?node-id=34%3A91730&t=QNoI3PqZXVrD97iZ-4
- The caret icon should be a button and have a hover state.
> style(console): role scopes transfer component

- packages/console/src/components/PermissionsTable/index.tsx
- packages/console/src/pages/UserDetails/UserRoles/index.tsx
- Click the resource name in the permission table should not open a new tab
- Click the role name in the user roles table should not open a new tab
Test locally.
> refactor(console): open resource and role details on current tab

- packages/console/src/components/ItemPreview/index.module.scss
- packages/console/src/pages/Users/index.module.scss
- packages/console/src/pages/Users/index.tsx
- Apply the table component to the users page
- Apply the useTableSearchParams hook to the users page
> refactor(console): users page

- packages/integration-tests/src/__mocks__/connectors-mock.ts
- packages/integration-tests/src/api/interaction.ts
- packages/integration-tests/src/api/verification-code.ts
- packages/integration-tests/src/helpers/index.ts
- packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
- packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
- packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
- packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
- packages/integration-tests/src/tests/api/verification-code.test.ts
- Add integration tests for generic verification APIs
- Rename `passcode` to `verification code` in integration tests
> test: add integration tests for generic verification APIs

- packages/console/src/components/PermissionsTable/index.tsx
- packages/console/src/components/Tip/Tooltip/index.module.scss
- packages/console/src/components/Tip/Tooltip/index.tsx
- packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
- packages/console/src/pages/UserDetails/UserRoles/index.tsx
Add deletion tip for rbac-related action buttons
> refactor(console): add deletion tip for rbac-related action buttons

- packages/console/package.json
- packages/console/src/App.tsx
- packages/core/src/middleware/koa-auth.test.ts
- packages/core/src/middleware/koa-auth.ts
- packages/core/src/routes/init.ts
- packages/core/src/routes/interaction/consent.ts
- packages/demo-app/package.json
- packages/integration-tests/package.json
- pnpm-lock.yaml
use RBAC's scope to control management api and admin console access.
Pass all tests.
Local tested with admin user and guest user, as expected.
> feat(console,core)!: use rbac scope to control management resource

- packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
- packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
refactor(console): make descriptions of the role and permission required
> refactor(console): make descriptions of the role and permission required

- packages/schemas/alterations/next-1673853579-ac-default-scope.ts
add alteration for default ac scope
local tested
> fix(schemas): add alteration for default ac scope

- packages/ui/src/containers/AppContent/index.module.scss
- packages/ui/src/containers/AppContent/index.tsx
- packages/ui/src/containers/SocialSignIn/SocialSignInList/index.test.tsx
- packages/ui/src/containers/SocialSignIn/SocialSignInList/index.tsx
- packages/ui/src/pages/Register/index.module.scss
- packages/ui/src/pages/Register/index.test.tsx
- packages/ui/src/pages/Register/index.tsx
- packages/ui/src/pages/SignIn/index.module.scss
- packages/ui/src/pages/SignIn/index.test.tsx
- packages/ui/src/pages/SignIn/index.tsx
main page layout update
1. remove the social list collapse logic, according to the latest design. Always display all social connectors
2. Reorg the AppContent Layout so the main element has a flexible height and is able to scroll auto within the page. 
test locally
> style(ui): main page layout update

- packages/core/src/routes/interaction/index.test.ts
- packages/core/src/routes/interaction/index.ts
- packages/core/src/routes/interaction/utils/interaction.ts
- packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
- packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
- packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
Automatically fill in the required email or phone using trusted social email or phone identities.
test using integration test
UT and integration test updated
> feat(core): auto fill social email or phone

- packages/schemas/alterations/next-1673863835-ac-scope-role.ts
add alteration for default ac role-scope relation.
Local tested
> fix(schemas): add alteration for default ac role scope

- packages/core/src/routes/role.scope.ts
fix scope resource finder
Local tested
> fix(core): fix scope resource finder

- packages/core/src/queries/roles.ts
Fix roles count: fix default parameter of `countRoles`
Local tested
> fix(core): fix roles count

- packages/console/src/components/DataEmpty/index.module.scss
- packages/console/src/components/DataEmpty/index.tsx
- packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.module.scss
- packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
- packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.module.scss
- packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.tsx
- packages/console/src/components/Table/TableEmpty.module.scss
- packages/console/src/components/Table/TableEmpty.tsx
- packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.module.scss
- packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/role-details.ts
- packages/phrases/src/locales/de/translation/admin-console/user-details.ts
- packages/phrases/src/locales/en/translation/admin-console/role-details.ts
- packages/phrases/src/locales/en/translation/admin-console/user-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
refactor(console): add empty state to transfers
> refactor(console): add empty state to transfers

- packages/phrases/src/locales/de/translation/admin-console/roles.ts
- packages/phrases/src/locales/en/translation/admin-console/roles.ts
- packages/phrases/src/locales/fr/translation/admin-console/roles.ts
- packages/phrases/src/locales/ko/translation/admin-console/roles.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
refactor(phrases): update the subtitle of the roles page
> refactor(phrases): update the subtitle of the roles page

- packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.tsx
- packages/console/src/components/RoleScopesTransfer/components/SourceScopeItem/index.module.scss
- packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.module.scss
- The caret icon button in the resource item should be small
- The target scope item should not wrap
- The source item check box should align with the caret icon.
> style(console): role transfer component

- packages/schemas/alterations/next-1673863835-ac-scope-role.ts
add an alteration to fix ac admin id and scope
local tested
> fix(schemas): fix ac admin id and scope

- packages/core/src/routes/role.scope.test.ts
- packages/core/src/routes/role.scope.ts
- packages/integration-tests/src/tests/api/role.scope.test.ts
get all scopes for a role
local tested
> feat(core): get all scopes for a role

- packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
- hide management API scope in role scopes transfer
- fix loading state logic
Before:
After:
> fix(console): hide management api scope in role scopes transfer

- packages/console/src/pages/UserDetails/UserRoles/index.module.scss
- packages/console/src/pages/UserDetails/UserRoles/index.tsx
style(console): search input on user roles page
Before:
After:
> style(console): search input on user roles page

- packages/console/src/components/Table/TableLoading.module.scss
- packages/console/src/components/Table/TableLoading.tsx
- packages/console/src/components/Table/index.tsx
style(console): table loading style
> style(console): table loading style

- packages/integration-tests/src/tests/api/resource.scope.test.ts
- packages/schemas/alterations/next-1673940577-scope-description-not-null.ts
- packages/schemas/tables/scopes.sql
set scope description to required
UTs
> fix(schemas): set scope description to required

- .github/workflows/integration-test.yml
- .github/workflows/main.yml
- .scripts/check-alterations-sequence.js
- .scripts/compare-database.js
- package.json
- packages/schemas/alterations/next-1673882867-fix-alteration-issues.ts
- pnpm-lock.yaml
- fix historic alteration issues
- add `compare-database.js` script to compare two databases from:
- tables
- columns
- enums
- constraints
- indexes
- add alteration `up` comparison in CI
- add cli command for downgrade database alteration
- fulfill the latest `down` script
- add alteration `down` comparison in CI
See those [failing workflow runs](https://github.com/logto-io/logto/actions/workflows/main.yml?query=branch%3Agao-fix-alteration)
> fix: alteration issues

- packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.module.scss
- packages/console/src/components/RoleScopesTransfer/components/SourceScopeItem/index.module.scss
style(console): role scopes item padding
> style(console): role scopes item padding

- packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
- packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
refactor(console): add error state to create role and permission form
> refactor(console): add error state to create role and permission form

- packages/phrases-ui/src/locales/de.ts
- packages/phrases-ui/src/locales/en.ts
- packages/phrases-ui/src/locales/fr.ts
- packages/phrases-ui/src/locales/ko.ts
- packages/phrases-ui/src/locales/pt-br.ts
- packages/phrases-ui/src/locales/pt-pt.ts
- packages/phrases-ui/src/locales/tr-tr.ts
- packages/phrases-ui/src/locales/zh-cn.ts
- packages/ui/src/components/Button/index.tsx
- packages/ui/src/containers/SocialLinkAccount/index.test.tsx
- packages/ui/src/containers/SocialLinkAccount/index.tsx
- packages/ui/src/pages/SocialLinkAccount/index.test.tsx
- packages/ui/src/pages/SocialLinkAccount/index.tsx
Update social bind account page content.  Display different content based on different signUp identifier settings. 
UT passed
> refactor(ui): update social bind account page content

- packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
- packages/console/src/pages/ApplicationDetails/index.tsx
- packages/core/src/__mocks__/index.ts
- packages/core/src/libraries/application.ts
- packages/core/src/oidc/init.ts
- packages/core/src/queries/applications-roles.ts
- packages/core/src/routes/application.test.ts
- packages/core/src/routes/application.ts
- packages/core/src/tenants/Libraries.ts
- packages/core/src/tenants/Queries.ts
- packages/schemas/alterations/next-1673941897-application-roles.ts
- packages/schemas/src/types/application.ts
- packages/schemas/src/types/index.ts
- packages/schemas/tables/applications.sql
- packages/schemas/tables/rolesapplications.sql
Migrate application (machine to machine) `roleNames` to RBAC.
UI design for managing application-role is not ready, so use `isAdmin` as a temp solution.
Local tested
> feat!: migrate application role names to RBAC

- packages/console/src/components/UserName/index.tsx
remove username's "admin" tag since is hard to determine if a user is admin after using RBAC.
Local tested
> fix(console): remove username admin tag

- packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
- packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
- packages/ui/src/containers/EmailForm/EmailContinue.tsx
- packages/ui/src/containers/EmailForm/index.module.scss
- packages/ui/src/containers/PhoneForm/PhoneContinue.tsx
- packages/ui/src/containers/PhoneForm/index.module.scss
- packages/ui/src/containers/VerificationCode/use-identifier-error-alert.ts
- packages/ui/src/hooks/use-required-profile-error-handler.ts
- packages/ui/src/hooks/use-social-sign-in-listener.ts
- packages/ui/src/pages/SignInPassword/index.tsx
- packages/ui/src/pages/VerificationCode/index.tsx
- packages/ui/src/types/guard.ts
- packages/ui/src/types/index.ts
display registered social identity message on continue page
test locally
> feat(core,ui): display registered social identity message on continue

- packages/console/src/components/ItemPreview/index.module.scss
- packages/console/src/pages/Roles/index.module.scss
- packages/console/src/pages/Roles/index.tsx
style(console): text ellipsis in roles table
> style(console): text ellipsis in roles table

- packages/console/src/components/AuditLogTable/components/EventName/index.module.scss
- packages/console/src/components/AuditLogTable/components/EventName/index.tsx
style(console): text ellipsis in audit logs table
> style(console): text ellipsis in audit logs table

- packages/console/src/pages/UserDetails/UserRoles/index.module.scss
- packages/console/src/pages/UserDetails/UserRoles/index.tsx
style(console): text ellipsis in user roles table
> style(console): text ellipsis in user roles table

- packages/ui/src/apis/interaction.ts
Per our offline alignment @charIeszhao , optimize some of the UI side APIs by bundling up those independent APIs in a promise all method. 
N/A
> refactor(ui): optimize api call stack

- .github/workflows/changesets.yml
- .github/workflows/commitlint.yml
- .github/workflows/integration-test.yml
- .github/workflows/main.yml
- .github/workflows/master-codecov-report.yml
- .github/workflows/pen-tests.yml
- .github/workflows/release.yml
- .github/workflows/update-pr-metadata.yml
- .github/workflows/upload-annotations.yml
using dynamic values from https://docs.github.com/en/actions/using-jobs/using-concurrency which would be better for workflow execution
CI
> ci: align workflow concurrency

- packages/ui/src/containers/AppContent/index.module.scss
adjust main panel web padding
test locally
> style(ui): adjust main panel web padding

- packages/ui/src/components/LoadingLayer/index.module.scss
remove loading layer bc
test locally
> style(ui): remove loading layer bc

- packages/ui/src/containers/VerificationCode/index.module.scss
align mobile countdown font color with desktop
test locally
> style(ui): align mobile countdown font color

- packages/ui/src/containers/PasswordSignInForm/index.module.scss
- packages/ui/src/containers/VerificationCode/index.module.scss
Add more space to the passwordless switch link
test locally
> style(ui): add space to the passwordless switch

- packages/console/src/components/PermissionsTable/index.module.scss
- packages/console/src/components/PermissionsTable/index.tsx
style(console): text ellipsis in permission table
> style(console): text ellipsis in permission table

- .changeset-staged/good-feet-own.md
- .changeset/good-feet-own.md
- packages/core/src/routes/interaction/utils/social-verification.ts
- packages/toolkit/connector-kit/src/types.ts
1. Pass parameters `connectorId`, `connectorFactoryId` and `jti` to `GetAuthorizationUri`.
2. Make `ConnectorSession` compatible with arbitrary keys.
3. Add the optional `validateSamlAssertion` method and its type definition to social connectors for the SAML connector's use case.
N/A
> feat: update GetAuthorizationUri, ConnectorSession and social connector member methods

- packages/ui/src/App.tsx
- packages/ui/src/pages/Callback/index.tsx
- packages/ui/src/pages/SocialLanding/index.test.tsx
- packages/ui/src/pages/SocialLanding/index.tsx
- packages/ui/src/pages/SocialLinkAccount/index.test.tsx
- packages/ui/src/pages/SocialLinkAccount/index.tsx
- packages/ui/src/pages/SocialSignInCallback/index.test.tsx
- packages/ui/src/pages/SocialSignInCallback/index.tsx
Rename connector params in the route path as connectorId
@charIeszhao 
test locally
> refactor(ui): rename connector params in route path

- packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
- packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.tsx
- packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.tsx
- packages/console/src/scss/transfer.module.scss
- Align empty image to vertical center in transfer components
> refactor(console): align empty image to vertical center

- packages/core/src/libraries/user.test.ts
- packages/core/src/libraries/user.ts
- packages/core/src/middleware/koa-auth.ts
- packages/core/src/routes/authn.test.ts
- packages/core/src/routes/authn.ts
use new roles table to replace old `roleNames` in authn route for Hasura
UTs
> refactor(core): update role in authn route for Hasura

- packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.module.scss
- add max-width to target scope tag
- disallow scope tag shrinking
> refactor(console): add max-width to target scope tag

- packages/core/src/__mocks__/user.ts
- packages/core/src/libraries/user.ts
- packages/core/src/oidc/init.ts
- packages/core/src/oidc/scope.test.ts
- packages/core/src/oidc/scope.ts
- packages/core/src/queries/user.test.ts
- packages/core/src/routes/admin-user.test.ts
- packages/core/src/routes/admin-user.ts
- packages/core/src/routes/interaction/actions/submit-interaction.test.ts
- packages/core/src/routes/interaction/actions/submit-interaction.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-br/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/schemas/src/foundations/jsonb-types.ts
- packages/schemas/src/types/user.ts
- packages/toolkit/core-kit/src/scope.ts
Remove all `user.roleNames`
UTs and ITs.
Local tested.
> refactor!: remove user roleNames

- packages/core/src/routes/resource.test.ts
- packages/core/src/routes/resource.ts
- packages/phrases/src/locales/de/errors.ts
- packages/phrases/src/locales/en/errors.ts
- packages/phrases/src/locales/fr/errors.ts
- packages/phrases/src/locales/ko/errors.ts
- packages/phrases/src/locales/pt-br/errors.ts
- packages/phrases/src/locales/pt-pt/errors.ts
- packages/phrases/src/locales/tr-tr/errors.ts
- packages/phrases/src/locales/zh-cn/errors.ts
scope name cannot contain any spaces
UTs
> fix(core): scope name cannot contain any spaces

- packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
- packages/ui/src/hooks/use-password-sign-in.ts
- packages/ui/src/hooks/use-required-profile-error-handler.ts
- packages/ui/src/hooks/use-social-sign-in-listener.ts
- packages/ui/src/pages/Continue/EmailOrPhone/index.tsx
- packages/ui/src/pages/Continue/SetEmail/index.tsx
- packages/ui/src/pages/Continue/SetPassword/index.tsx
- packages/ui/src/pages/Continue/SetPhone/index.tsx
- packages/ui/src/pages/Continue/SetUsername/index.tsx
- packages/ui/src/pages/Continue/index.tsx
- packages/ui/src/types/guard.ts
show notification on the sign-in profile fulfillment page
test locally
> feat(ui): show notification on the sign-in profile fulfill page

- packages/core/src/queries/user.ts
list users order by created_at
Local tested.
> fix(core): list users order by created_at

- packages/core/src/env-set/index.ts
- packages/core/src/utils/connectors/loader.ts
add `IGNORE_CONNECTOR_VERSION_CHECK` env for ignoring connector version check, it's useful during development
pending
> refactor(core): add IGNORE_CONNECTOR_VERSION_CHECK

- packages/console/package.json
- packages/console/src/App.tsx
- packages/console/src/components/OverlayScrollbar/index.tsx
- packages/console/src/components/Table/index.tsx
- packages/console/src/scss/overlayscrollbars.scss
- pnpm-lock.yaml
refactor(console): use overlay scrollbar in tables
> refactor(console): use overlay scrollbar in tables

- packages/console/src/components/UserName/index.module.scss
- packages/console/src/components/UserName/index.tsx
> style(console): username

- packages/integration-tests/src/helpers/index.ts
- packages/toolkit/connector-kit/src/index.ts
Fix integration test failure caused by a file path change to a tmp file. Issue was introduced by the recent connector version bump.
> fix: integration test failure

- packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.tsx
- packages/console/src/components/RoleScopesTransfer/components/TargetScopesBox/index.tsx
- packages/console/src/pages/ApiResourceDetails/index.tsx
- packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
- packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/de/translation/admin-console/role-details.ts
- packages/phrases/src/locales/de/translation/admin-console/roles.ts
- packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/en/translation/admin-console/role-details.ts
- packages/phrases/src/locales/en/translation/admin-console/roles.ts
- packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/fr/translation/admin-console/roles.ts
- packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
- packages/phrases/src/locales/ko/translation/admin-console/roles.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
polish wording, fix typos, handle plurals
locally
> refactor(phrases): update RBAC content

- packages/console/src/pages/Roles/components/AssignedUsers/index.module.scss
No user-assigned hyphen should be left aligned with the user icon.
> style(console): assigned users

- packages/console/src/components/Dropdown/DropdownItem.module.scss
- packages/console/src/components/Dropdown/DropdownItem.tsx
- packages/console/src/components/Dropdown/index.module.scss
- packages/console/src/components/Dropdown/index.tsx
- packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/AddLanguageSelector.module.scss
- packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/AddLanguageSelector.tsx
- packages/integration-tests/src/tests/ui/smoke.test.ts
refactor(console): use overlay scrollbar in dropdown
> refactor(console): use overlay scrollbar in dropdown

- packages/console/src/components/RoleUsersTransfer/components/SourceUsersBox/index.tsx
- packages/console/src/components/UserRolesTransfer/components/SourceRolesBox/index.tsx
- packages/console/src/hooks/use-debounce.ts
- set delay on `useDebounce` hook created.
- provide a default debounce delay value.
Test locally.
> refactor(console): useDebounce

- .github/CONTRIBUTING.md
- README.md
> chore: update node version in README

- packages/console/src/pages/ConnectorDetails/index.tsx
refactor(console): use small size copy component on connector details page
> refactor(console): use small size copy component on connector details page

- .github/workflows/main.yml
- .scripts/compare-database.js
- packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
- packages/core/src/queries/roles.ts
- packages/core/src/routes/application.ts
- packages/integration-tests/src/tests/api/admin-user.roles.test.ts
- packages/integration-tests/src/tests/api/get-access-token.test.ts
- packages/schemas/alterations/next-1673853579-ac-default-scope.ts
- packages/schemas/alterations/next-1673863835-ac-scope-role.ts
- packages/schemas/alterations/next-1675316731-update-seed-data.ts
- packages/schemas/src/seeds/roles.ts
- packages/schemas/src/seeds/scope.ts
- update role id `ac-admin-id` -> `admin-role`
- update scope id `management-api-scope` -> `management-scope-all` and name `management-api:default` -> `all`
- compare data between databases for alteration
CI
> **Note**
> the alteration error is expected since we fixed a previous alteration script. database comparison is good.
> refactor: update seed data

- .changeset/sweet-dolphins-own.md
> chore(core,ui): add social flow changeset

- packages/console/src/pages/UserDetails/UserRoles/index.tsx
The name of the description data column should be 'description'
> fix(console): user roles table column name

- packages/console/src/components/Markdown/index.module.scss
Fix table styles in markdown component, as table related styles have been removed from `normalized.scss`
> fix(console): improve table styles in markdown component

- packages/core/src/queries/applications-roles.ts
fix 500 error when enabling app admin access in console
local tested, updated an app with admin access
> fix(core): insert id when patch application

- .changeset/curly-hornets-end.md
> chore: add changesets

- packages/console/src/components/AppContent/components/Sidebar/hook.tsx
- packages/console/src/hooks/use-documentation-url.ts
- packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
- packages/console/src/pages/ApplicationDetails/components/Settings.tsx
- packages/console/src/pages/ApplicationDetails/index.tsx
- packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
- packages/console/src/pages/GetStarted/hook.ts
- packages/console/src/pages/UserDetails/UserSettings/index.tsx
refactor(console): i18n for documentation url
- refactor useDocumentationUrl
- replace all `https://docs.logto.io` with `useDocumentationUrl` hook.
Test locally.
> refactor(console): i18n for documentation url

- packages/phrases-ui/src/locales/de.ts
Update German locale for UI.
Didn't test :see_no_evil:
> fix(phrases): update German locale

- packages/ui/package.json
- packages/ui/src/components/InputFields/InputField/index.module.scss
- packages/ui/src/components/InputFields/InputField/index.test.tsx
- packages/ui/src/components/InputFields/InputField/index.tsx
- packages/ui/src/components/InputFields/PasswordInputField/index.test.tsx
- packages/ui/src/components/InputFields/PasswordInputField/index.tsx
- packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.module.scss
- packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.tsx
- packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.module.scss
- packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.tsx
- packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
- packages/ui/src/components/InputFields/SmartInputField/index.tsx
- packages/ui/src/components/InputFields/SmartInputField/use-smart-input-field.ts
- packages/ui/src/components/InputFields/index.tsx
- pnpm-lock.yaml
add the smart input field component.
Please ignore the large change size, half of them are test cases. 
[figma](https://www.figma.com/file/Yw6Z7TJGajAR7TX79vJJGT/Main-Flow-SIE-iteration?node-id=192%3A7682&t=A2pmsShBtcVoQjdJ-0)
https://user-images.githubusercontent.com/36393111/215768444-17c13f12-e0ff-4fae-831c-793855d1a28d.mp4
test locally
UT added
> feat(ui): add smart input field

- packages/console/src/pages/ApiResourceDetails/index.tsx
chore(console): replace `as` with `satisfies`
None.
> chore(console): replace `as` with `satisfies`

- packages/core/src/libraries/connector.ts
- packages/core/src/routes/connector.test.ts
- packages/core/src/routes/connector.ts
- packages/core/src/utils/connectors/index.ts
- packages/shared/package.json
- pnpm-lock.yaml
should validate config when creating a new connector instance
UTs and ITs.
> fix(core): should validate config when creating a new connector instance

- packages/console/src/components/RadioGroup/Radio.tsx
- packages/console/src/components/RadioGroup/index.module.scss
- packages/console/src/components/RadioGroup/index.tsx
feat(console): compact-style radio group
Default:
Selected:
Hover:
> feat(console): compact-style radio group

- packages/core/src/routes/interaction/utils/interaction.ts
- packages/core/src/routes/interaction/utils/social-verification.ts
Move connector session read/write methods to social verification.
UTs and ITs.
> refactor(core): move connector session read/write to social verification

- packages/console/src/pages/CloudPreview/components/MultiCardSelector/index.module.scss
- packages/console/src/pages/CloudPreview/components/MultiCardSelector/index.tsx
Add a `MultiCardSelector` component to the cloud preview page since it's only used on that page.
> feat(console): multi card selector on cloud preview page

- packages/console/src/pages/CloudPreview/components/CardSelector/index.tsx
Add `CardSelector` component for cloud preview:
> feat(console): add `CardSelector` component for cloud preview

- packages/console/src/pages/CloudPreview/components/CardSelector/CardSelector.tsx
- packages/console/src/pages/CloudPreview/components/CardSelector/MultiCardSelector/index.module.scss
- packages/console/src/pages/CloudPreview/components/CardSelector/MultiCardSelector/index.tsx
- packages/console/src/pages/CloudPreview/components/CardSelector/index.tsx
- packages/console/src/pages/CloudPreview/components/CardSelector/types.ts
- Support icon in the `MultiCardSelector` component.
- Refactor `MultiCardSelector` props.
- Group `MultiCardSelector` and `CardSelector` into one component folder.
> refactor(console): multi-card selector

- packages/phrases/src/locales/de/translation/admin-console/connectors.ts
- packages/phrases/src/locales/en/translation/admin-console/connectors.ts
- packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
- packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
- packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
- packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts
update sync profile tip content
> fix(phrases): update sync profile tip

- README.md
> chore: add web compatibility section in README

- packages/console/package.json
- packages/console/src/components/Textarea/index.module.scss
- packages/console/src/components/Textarea/index.tsx
- packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
- packages/console/src/pages/Connectors/components/ConfigForm/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorForm/hooks.tsx
- packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
- packages/console/src/pages/Connectors/components/ConnectorForm/utils.ts
- packages/console/src/pages/Connectors/components/Guide/index.tsx
- packages/console/src/pages/Connectors/types.ts
- packages/core/src/utils/connectors/index.ts
- packages/toolkit/connector-kit/src/types.ts
- pnpm-lock.yaml
Render connector config from from "formItems".
Check this PR for examples: https://github.com/logto-io/connectors/pull/90
> feat(console): connector config form

- packages/console/package.json
- packages/demo-app/package.json
- packages/phrases-ui/package.json
- pnpm-lock.yaml
Remove annoying "pnpm failed to install modules" warning message from parcel.
Make console clean again
> chore: remove annoying install module failure warning from parcel

- packages/console/src/pages/Connectors/components/ConnectorForm/hooks.tsx
fix connector json-mode config saving bug: should return `result.data`.
Local tested
> fix(console): fix connector json config save

- packages/core/src/routes/connector.ts
enable specified id when creating a new connector
UTs and ITs.
> feat(core): enable creating a new connector with specified id

- .changeset/big-turkeys-invite.md
Add change set for the `formItems` feature.
N/A
> chore: add changeset for connector kit

- packages/core/src/tenants/utils.ts
don't show redundant tables in the error message
/
> refactor(core): fix rls error alert message

- packages/core/src/oidc/init.ts
- packages/core/src/oidc/scope.ts
the user claims hotfix.
According to the oidc standard email_verified and phone_verified claim values should be boolean.
test locally
> fix(ui): user claims hot fix

- packages/console/src/pages/ApplicationDetails/index.tsx
fix(console): remove slash in the oidc config request
See: https://github.com/logto-io/logto/pull/3093
LOG-4326: Display error messages on fetch error occurred.
> fix(console): remove leading slash in the oidc config api path

- packages/core/jest.setup.js
- packages/core/src/app/init.ts
- packages/core/src/env-set/GlobalValues.ts
- packages/core/src/env-set/UrlSet.test.ts
- packages/core/src/env-set/UrlSet.ts
- packages/core/src/env-set/index.ts
- packages/core/src/env-set/utils.ts
- packages/core/src/middleware/koa-auth/utils.ts
- packages/core/src/routes/well-known.ts
- packages/core/src/tenants/Tenant.test.ts
- packages/core/src/tenants/Tenant.ts
- packages/core/src/tenants/consts.ts
- packages/core/src/tenants/index.ts
- packages/core/src/test-utils/env-set.ts
- packages/core/src/utils/tenant.test.ts
- packages/core/src/utils/tenant.ts
- packages/integration-tests/src/api/api.ts
- packages/integration-tests/src/api/interaction.ts
- packages/integration-tests/src/client/index.ts
- packages/integration-tests/src/helpers/admin-tenant.ts
- packages/integration-tests/src/helpers/client.ts
- packages/integration-tests/src/tests/api/health-check.test.ts
- packages/integration-tests/src/tests/api/me.test.ts
- packages/toolkit/core-kit/package.json
- pnpm-lock.yaml
- make all `UrlSet` props return `URL` as it's safer
- add missing unit tests for tenant utils
- add integration tests for `/me` APIs
CI
> test(core): add tests

- packages/schemas/alterations/next-1676190092-migrate-admin-data.ts
fix typo
local run alteration script to dev and dev works as expected
> refactor(schemas): fix alteration script

- packages/core/src/routes/init.ts
with restricted origin it's fine to expose all headers i think
local tested, headers are working
> refactor(core): expose all headers in CORS

- packages/core/src/app/init.ts
- packages/core/src/tenants/utils.ts
respond 404 instead of 500 when tenant not found in tenants table
tested with non-existing tenant ID
> refactor(core): optimize tenant not found error

- packages/console/src/pages/Cloud/pages/Congrats/index.tsx
fix(console): open demo app on cloud congrats page
Test locally.
> fix(console): open demo app on cloud congrats page

- packages/console/src/pages/Cloud/components/ActionBar/index.module.scss
- packages/console/src/pages/Cloud/components/ActionBar/index.tsx
- packages/console/src/pages/Cloud/components/ProgressBar/index.module.scss
- packages/console/src/pages/Cloud/components/ProgressBar/index.tsx
- packages/console/src/pages/Cloud/pages/About/index.tsx
- packages/console/src/pages/Cloud/pages/Congrats/index.tsx
- packages/console/src/pages/Cloud/pages/Welcome/index.tsx
feat(console): progress bar on cloud page
> feat(console): progress bar on cloud page

- packages/phrases-ui/src/locales/zh-cn.ts
- packages/phrases/src/locales/zh-cn/errors.ts
- packages/ui/src/scss/_colors.scss
style and content polish
test locally
> style(ui): style and content polish
