logto-io/logto

packages/ui/src/pages/Register/index.module.scss
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SignIn/index.module.scss

adjust sign-in and register switch link pos
test locally

style(ui): adjust signin and register switch link pos

---

LICENSE.cloud

provider a copy of [ELv2 license](https://github.com/elastic/elasticsearch/blob/main/LICENSE.txt)
we do specified the license in `packages/cloud/package.json`, it'll be good to provide a copy to show the info on GitHub
after merge, should show correct info in the right side of repo homepage

chore: add ELv2 license

---

packages/ui/src/containers/SetPassword/index.test.tsx
packages/ui/src/containers/SetPassword/index.tsx
packages/ui/src/pages/Continue/IdentifierProfileForm/index.tsx
packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/ui/src/pages/Register/IdentifierRegisterForm/index.test.tsx
packages/ui/src/pages/Register/IdentifierRegisterForm/index.tsx
packages/ui/src/pages/SignIn/IdentifierSignInForm/index.tsx
packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
packages/ui/src/pages/SignInPassword/PasswordForm/index.tsx

update form validation logic
1. change revalidate logic from onChange to onBlur
2. Hide server returned error if any form field error occurs. 
test locally

refactor(ui): update form validation logic

---

packages/console/src/pages/ConnectorDetails/components/ConnectorContent.module.scss
packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
packages/console/src/pages/Connectors/components/Guide/index.module.scss
packages/console/src/pages/Connectors/components/Guide/index.tsx
packages/console/src/pages/Connectors/utils/index.ts
packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
packages/phrases/src/locales/de/translation/admin-console/connectors.ts
packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
packages/phrases/src/locales/en/translation/admin-console/connectors.ts
packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts

New style for create and edit connector: [Figma Link](https://www.figma.com/file/EbkN9PCnIFAfgs6A35wI8a/%F0%9F%93%97-Standard-connector?node-id=1014%3A13107&t=bxhRrqLgAajzpwbp-0)

feat(console): new style for create and edit connector

---

packages/ui/src/containers/SocialSignIn/index.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SignIn/Main.tsx

Minor updates:
Aligh the usage of. `SocialSignIn` with  `SocialSignInList`.  Passing in social connectors as props from page level instead of read from the pageContext. Better keep SSO.
test locally

refactor(ui): passing in social connectors as props

---

.github/workflows/main.yml
.github/workflows/release-cloud.yml
Dockerfile.cloud

- build cloud image on pull requests
- build and push cloud image on master
- main CI
- [test workflow](https://github.com/logto-io/logto/actions/runs/4221002844/jobs/7327814932) success, the image shows in [packages](https://github.com/logto-io/logto/pkgs/container/logto)

ci: build cloud Docker image

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/schemas/alterations/next-1676874936-support-custom-css.ts
packages/schemas/src/seeds/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql
packages/ui/src/App.tsx
packages/ui/src/__mocks__/logto.tsx

add `custom_css` column in the SIE table and load the content as a style element

feat: custom css

---

.changeset/curly-apes-tease.md
packages/toolkit/connector-kit/src/types.ts

Add description and tooltip for connector config's formItems
N/A

feat(toolkit): add description and tooltip for formItems

---

packages/core/src/routes/phrase.test.ts
packages/core/src/routes/phrase.ts
packages/ui/src/App.tsx
packages/ui/src/apis/settings.ts
packages/ui/src/hooks/use-preview.ts
packages/ui/src/i18n/init.ts
packages/ui/src/i18n/utils.ts

prevent infinite getPhrases api call.  Prevent  getPhrases API being called on every preview update changes. 
test locally

fix(ui): prevent infinite getPhrase api call

---

packages/ui/src/components/InputFields/SmartInputField/index.tsx
packages/ui/src/components/InputFields/SmartInputField/utils.test.ts
packages/ui/src/components/InputFields/SmartInputField/utils.ts
packages/ui/src/pages/Continue/IdentifierProfileForm/index.tsx
packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/ui/src/pages/Register/IdentifierRegisterForm/index.tsx
packages/ui/src/pages/SignIn/IdentifierSignInForm/index.tsx
packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx

properly set autocomplete props
test locally

refactor(ui): properly set autocomplete props

---

packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts

align terms in phrase to capitalized case
test locally

chore(phrases): align terms in phrases to capitalized case

---

packages/phrases-ui/src/locales/de.ts
packages/phrases-ui/src/locales/en.ts
packages/phrases-ui/src/locales/fr.ts
packages/phrases-ui/src/locales/ko.ts
packages/phrases-ui/src/locales/pt-br.ts
packages/phrases-ui/src/locales/pt-pt.ts
packages/phrases-ui/src/locales/ru.ts
packages/phrases-ui/src/locales/tr-tr.ts
packages/phrases-ui/src/locales/zh-cn.ts
packages/ui/src/components/BrandingHeader/index.test.tsx
packages/ui/src/components/BrandingHeader/index.tsx
packages/ui/src/containers/LandingPageContainer/index.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SignIn/index.tsx

hard code the page slogan instead of read from SIE. The slogan settings will be removed. 
test locally

refactor(ui): hard code the page slogan

---

packages/phrases/src/locales/de/translation/admin-console/applications.ts
packages/phrases/src/locales/en/translation/admin-console/api-resources.ts
packages/phrases/src/locales/en/translation/admin-console/applications.ts
packages/phrases/src/locales/en/translation/admin-console/get-started.ts
packages/phrases/src/locales/en/translation/admin-console/logs.ts
packages/phrases/src/locales/fr/translation/admin-console/applications.ts
packages/phrases/src/locales/ko/translation/admin-console/applications.ts
packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts

chore(console): polish subtitle wording in various pages

---

Dockerfile
Dockerfile.cloud
package.json
packages/cloud/package.json
packages/cloud/src/env-set/index.ts
packages/core/package.json
packages/core/src/middleware/koa-cors.ts
packages/core/src/oidc/adapter.ts

- fix cloud dockerfile to make it work
- polish dockerfile format
- align env key `ADMIN_TENANT_ENDPOINT` for both cloud and core since they share the same value
- disable localhost CORS in production
- fix console Redirect URI on cloud

refactor: fix cloud env

---

packages/ui/package.json
packages/ui/src/components/InputFields/InputField/index.module.scss
packages/ui/src/components/InputFields/InputField/index.tsx
packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.module.scss
packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.tsx
packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.module.scss
packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
packages/ui/src/components/InputFields/SmartInputField/index.tsx
packages/ui/src/pages/ForgotPassword/index.test.tsx
pnpm-lock.yaml

MSIGA
https://user-images.githubusercontent.com/14722250/220646880-c952354a-a1e3-4bc6-9df4-7ebdf1ee0bc1.mov

refactor(ui): optimize smart input animation

---

packages/ui/src/components/InputFields/InputField/index.module.scss

adjust input suffic button padding space
N/A

style(ui): adjust input suffix button padding space

---

packages/ui/src/containers/AppContent/index.module.scss
packages/ui/src/containers/LandingPageContainer/index.module.scss
packages/ui/src/containers/SocialSignIn/SocialSignInList/index.module.scss

adjust LandingPage spacing
N/A

style(ui): adjust LandingPage spacing

---

packages/ui/src/containers/LandingPageContainer/index.module.scss

ajust mobile home page spacing
Change margin space to inner box padding space so the 15vh height style may take effect based on the padding space.
test locally

style(ui): mobile home page spacing

---

packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
packages/ui/src/hooks/use-password-sign-in.ts
packages/ui/src/hooks/use-required-profile-error-handler.ts
packages/ui/src/hooks/use-social-sign-in-listener.ts
packages/ui/src/pages/Continue/index.tsx
packages/ui/src/types/guard.ts

Remove continue page notification
test locally
UT passed

refactor(ui): remove continue page notification

---

packages/core/src/routes-me/init.ts
packages/core/src/routes-me/user.ts
packages/core/src/routes-me/verification-code.ts

Provide APIs to validate and update user password in cloud admin console.
Provide APIs to send and validate one-time verification code in cloud admin console.

feat(core): provide `/me` APIs for user password and verification code in cloud AC

---

packages/console/src/cloud/pages/Welcome/options.tsx
packages/console/src/cloud/types.ts
packages/phrases/src/locales/de/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts

chore: opensource -> open-source

---

packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
packages/ui/src/hooks/use-required-profile-error-handler.ts

Throw registered social email or phone info only for sign-in flow
test locally

refactor(core): throw registered social email or phone info

---

packages/console/src/cloud/pages/About/index.tsx
packages/console/src/cloud/pages/Congrats/index.tsx
packages/console/src/cloud/pages/Onboard/index.tsx
packages/console/src/cloud/pages/Welcome/index.tsx
packages/console/src/cloud/types.ts
packages/console/src/cloud/utils.ts

- rename `cloudPage` to `onboardPage`
- rename `getCloudPagePahtname` to `getOnboardPagePathname`
Test locally.

refactor(console): rename `cloudPage` to `onboardPage`

---

.gitpod.yml
Dockerfile.cloud
packages/cloud/src/env-set/index.ts
packages/console/src/consts/tenants.ts

- upgrade Node in GitPod
- adapt GitPod config to fit the new service model
- align admin tenant endpoint env key to `ADMIN_ENDPOINT` across the repo
GitPod works again

chore: update configs

---

packages/console/src/pages/Connectors/components/Guide/index.tsx

Fix passwordless connectors title of sender tester.

fix(console): fix passwordless connectors test title

---

.changeset-staged/lemon-cars-wonder.md

Add changeset for Russian translation
N/A

chore: add changeset for ru translation

---

packages/ui/src/__mocks__/logto.tsx
packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.tsx
packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
packages/ui/src/pages/ForgotPassword/index.test.tsx

update SmartInput animation
1. Fix react-spring api.start not trigger animation update bug. Add a domReady state, force to reinit the useString after dom is ready.
2. Add the getBoundingClientRectMock to test UT cases better. 
test locally
UT updated

fix(ui): update SmartInput animation

---

.changeset-staged/many-avocados-know.md

add change set for smart input field
N/A

chore(core): add change set for smart input field

---

packages/console/src/pages/Settings/components/ChangePassword.tsx

Fix admin change password failure by using new API under `/me` router

fix(console): change password should use me router api

---

packages/phrases/src/locales/en/translation/admin-console/connectors.ts

align term
Checked locally.
OR

chore(console): rename target to idp name

---

packages/phrases-ui/src/locales/de.ts
packages/phrases-ui/src/locales/en.ts
packages/phrases-ui/src/locales/fr.ts
packages/phrases-ui/src/locales/ko.ts
packages/phrases-ui/src/locales/pt-br.ts
packages/phrases-ui/src/locales/pt-pt.ts
packages/phrases-ui/src/locales/ru.ts
packages/phrases-ui/src/locales/tr-tr.ts
packages/phrases-ui/src/locales/zh-cn.ts

update per the multi-tenancy update
/
OR

refactor(phrases): update demo app notification

---

packages/phrases-ui/src/locales/de.ts
packages/phrases-ui/src/locales/en.ts
packages/phrases-ui/src/locales/fr.ts
packages/phrases-ui/src/locales/ko.ts
packages/phrases-ui/src/locales/pt-br.ts
packages/phrases-ui/src/locales/pt-pt.ts
packages/phrases-ui/src/locales/ru.ts
packages/phrases-ui/src/locales/tr-tr.ts
packages/phrases-ui/src/locales/zh-cn.ts
packages/ui/src/components/BrandingHeader/index.test.tsx
packages/ui/src/components/BrandingHeader/index.tsx
packages/ui/src/containers/LandingPageContainer/index.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SignIn/index.tsx

Revert "refactor(ui): hard code the page slogan"

---

README.md
docker-compose.yml

update docker-compose file and README
works like a charm

chore: update docker-compose file and README

---

packages/console/src/consts/external-links.ts
packages/console/src/consts/index.ts
packages/console/src/containers/AppContent/Sidebar/components/Contact/hook.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/Connectors/components/Guide/index.tsx
packages/console/src/pages/GetStarted/hook.ts
packages/core/src/__mocks__/index.ts
packages/core/src/routes/logto-config.test.ts
packages/phrases/src/locales/de/translation/admin-console/general.ts
packages/phrases/src/locales/de/translation/admin-console/get-started.ts
packages/phrases/src/locales/en/translation/admin-console/general.ts
packages/phrases/src/locales/en/translation/admin-console/get-started.ts
packages/phrases/src/locales/fr/translation/admin-console/general.ts
packages/phrases/src/locales/fr/translation/admin-console/get-started.ts
packages/phrases/src/locales/ko/translation/admin-console/general.ts
packages/phrases/src/locales/ko/translation/admin-console/get-started.ts
packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
packages/phrases/src/locales/pt-br/translation/admin-console/get-started.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/get-started.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/get-started.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/get-started.ts
packages/schemas/alterations/next-1677208902-update-admin-console-config.ts
packages/schemas/src/seeds/logto-config.ts
packages/schemas/src/types/logto-config.ts

- rename `demoChecked` -> `livePreviewChecked` in the admin console config.
- remove `socialSignInConfigured` & `furtherReadingsChecked` in the admin console config.
- add `selfHostingChecked`, `m2mApplicationCreated`, `communityChecked` to the admin console config.
- update get-started tasks according to new design.
The action of `Interact with ManagementAPI` task is WIP. 
Per offline disscussion, treat it the same as the create application temporary, and we will update it when the design is ready.
Test locally.

refactor(console): get-started tasks

---

packages/console/package.json
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorStatus/index.tsx
packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignInDiffSection.tsx
packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
packages/console/src/pages/SignInExperience/constants.ts
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/SignUpForm.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/ConnectorSetupWarning.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/AddButton.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/SignInMethodItem.tsx
packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
pnpm-lock.yaml

- remove i18n text context
- remove deprecated `snake-case` dep in console project

refactor(console): remove i18n text context

---

packages/console/src/containers/AppLayout/components/UserInfo/index.tsx
packages/console/src/pages/Profile/components/CardContent/index.module.scss
packages/console/src/pages/Profile/components/CardContent/index.tsx
packages/console/src/pages/Profile/components/Section/index.module.scss
packages/console/src/pages/Profile/components/Section/index.tsx
packages/console/src/pages/Profile/index.module.scss
packages/console/src/pages/Profile/index.tsx
packages/phrases/src/locales/de/translation/admin-console/index.ts
packages/phrases/src/locales/de/translation/admin-console/profile.ts
packages/phrases/src/locales/en/translation/admin-console/index.ts
packages/phrases/src/locales/en/translation/admin-console/profile.ts
packages/phrases/src/locales/fr/translation/admin-console/index.ts
packages/phrases/src/locales/fr/translation/admin-console/profile.ts
packages/phrases/src/locales/ko/translation/admin-console/index.ts
packages/phrases/src/locales/ko/translation/admin-console/profile.ts
packages/phrases/src/locales/pt-br/translation/admin-console/index.ts
packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/index.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/index.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/index.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts

Profile settings page (UI only)

feat(console): new profile settings page

---

packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts

fix typo which could result in undesirable reminder content
OR

fix(ui): fix typo which could result in undesirable reminder content

---

packages/ui/src/components/InputFields/InputField/index.module.scss

fix suffix button not show up issue
test locally
OR

fix(ui): fix suffix button z-index

---

packages/core/static/html/post-logout/index.html

Fix power by logto font size. Original CSS does not support font-size/line-height format. 
test locally
OR

style(core): fix power by logto font size

---

packages/phrases-ui/src/locales/de.ts
packages/phrases-ui/src/locales/en.ts
packages/phrases-ui/src/locales/fr.ts
packages/phrases-ui/src/locales/ko.ts
packages/phrases-ui/src/locales/pt-br.ts
packages/phrases-ui/src/locales/pt-pt.ts
packages/phrases-ui/src/locales/ru.ts
packages/phrases-ui/src/locales/tr-tr.ts
packages/phrases-ui/src/locales/zh-cn.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts
packages/ui/src/containers/SocialLinkAccount/index.test.tsx
packages/ui/src/containers/SocialLinkAccount/index.tsx

chore(phrases): content update

---

packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.module.scss
packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx
packages/console/src/pages/Connectors/components/Guide/index.tsx
packages/phrases/src/locales/de/translation/admin-console/connectors.ts
packages/phrases/src/locales/en/translation/admin-console/connectors.ts
packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts

Add "Callback URI" field, there is a special case for creating non-standard connector: the connector id is pre-generated in front-end.
OR

feat(console): add callback uri field

---

packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx

fix app endpoints import path
Local build pass.
OR

fix(console): fix app endpoints import path

---

packages/console/src/hooks/use-me-custom-data.ts
packages/console/src/hooks/use-swr-fetcher.ts
packages/console/src/hooks/use-swr-options.ts

refactor useMeCustomData.
Update `useSwrFetcher` take API  instance as a prop.
Should keep useSwrFetch as the SSOT for /me API as well. Passing in a admin API instance instead.
test locally
OR

fix(console): refactor useMeCustomData

---

packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/demo-app.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/demo-app.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts

"Link Social Connector" -> "Add Social Connector". try to align Portuguese translations as well. 
/

chore(phrases): update content

---

packages/phrases-ui/src/locales/de.ts
packages/phrases-ui/src/locales/en.ts
packages/phrases-ui/src/locales/fr.ts
packages/phrases-ui/src/locales/ko.ts
packages/phrases-ui/src/locales/pt-br.ts
packages/phrases-ui/src/locales/pt-pt.ts
packages/phrases-ui/src/locales/ru.ts
packages/phrases-ui/src/locales/tr-tr.ts
packages/phrases-ui/src/locales/zh-cn.ts

refactor(phrases): update live preview notification
Test locally.

refactor(phrases): update live preview notification

---

packages/console/package.json
packages/console/src/components/VerificationCodeInput/index.module.scss
packages/console/src/components/VerificationCodeInput/index.tsx
packages/console/src/pages/Main/index.tsx
packages/console/src/pages/Profile/components/MainFlowLikeModal/index.module.scss
packages/console/src/pages/Profile/components/MainFlowLikeModal/index.tsx
packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
packages/console/src/pages/Profile/containers/VerificationCodeModal/index.module.scss
packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
packages/console/src/pages/Profile/index.tsx
packages/console/src/pages/Profile/utils.ts
packages/core/src/routes-me/verification-code.ts
pnpm-lock.yaml

Allow changing email account via verification code.
Allow self verification via verification code in changing password flow.
OR

feat(console): allow linking email via verification code in profile

---

packages/console/src/pages/Profile/containers/DeleteAccountModal/index.module.scss
packages/console/src/pages/Profile/containers/DeleteAccountModal/index.tsx
packages/console/src/pages/Profile/index.tsx
packages/phrases/src/locales/en/translation/admin-console/profile.ts

Provided a dialog for user account deletion in Logto cloud.
OR

feat(console): add delete account dialog in profile page

---

packages/console/src/pages/Connectors/components/ConnectorName/index.tsx

Show platform icons for non-universal social connectors.
OR

fix(console): show platform icons for non-universal

---

packages/core/src/routes-me/user.ts

We should check if the identifier (username or email) is conflict before updating a user in admin tenant, by calling the `PATCH /me/user/:userId` API.
Will add unit tests and integration tests later
OR

fix(core): check identifier collision before updating admin tenant user

---

.changeset-staged/gorgeous-berries-smoke.md
packages/core/src/oidc/init.ts
packages/core/src/oidc/type.ts
packages/core/src/routes/consts.ts

Add interactionMode OIDC param:
- signUp: redirect to register route for a signUp first user experience
- signIn(default): redirect to signIn route.
test locally. Need SDK updates as well.
OR

feat(ui): add interactionMode OIDC param

---

packages/console/src/pages/SignInExperience/index.tsx

Update the base name of the `sign-in-experience` page since we now support multi-tenancy and the basename will not always be `/console`
Test locally.

fix(console): base path of sie pages

---

packages/console/src/pages/Profile/containers/HandleSocialCallback/index.tsx
packages/core/src/queries/user.ts
packages/core/src/routes-me/social.ts

Fix google account linking issues in admin profile. Now user should be able to link google account to profile, and also change to another google account.
OR

fix(console): admin user should be able to link google account to profile

---

packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
packages/console/src/pages/Profile/containers/HandleSocialCallback/index.tsx

Fix incorrect callback URL when linking social account in cloud AC profile page.
OR

fix(console): cloud ac profile should use correct callback URL when linking social

---

packages/console/src/cloud/components/CardSelector/MultiCardSelector/index.tsx
packages/console/src/cloud/constants/index.ts
packages/console/src/cloud/pages/Congrats/index.tsx
packages/console/src/cloud/pages/SignInExperience/components/PlatformTabs/PlatformTab.module.scss
packages/console/src/cloud/pages/SignInExperience/components/PlatformTabs/PlatformTab.tsx
packages/console/src/cloud/pages/SignInExperience/components/PlatformTabs/index.module.scss
packages/console/src/cloud/pages/SignInExperience/components/PlatformTabs/index.tsx
packages/console/src/cloud/pages/SignInExperience/components/Preview/index.module.scss
packages/console/src/cloud/pages/SignInExperience/components/Preview/index.tsx
packages/console/src/cloud/pages/SignInExperience/index.module.scss
packages/console/src/cloud/pages/SignInExperience/index.tsx
packages/console/src/cloud/pages/SignInExperience/utils.ts
packages/console/src/cloud/types.ts
packages/console/src/components/LivePreviewButton/index.tsx
packages/console/src/components/RadioGroup/Radio.module.scss
packages/console/src/components/SignInExperiencePreview/index.tsx
packages/phrases/src/locales/de/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts

- Add Sign-In Preview to the onboarding SIE page
- Remove the focus styles of the compact radio since it's will cause misunderstanding and it's deprecated in the new design 
OR

feat(console): onboarding sie preview

---

.github/workflows/integration-test.yml
.scripts/package.sh
packages/cli/src/commands/install/index.ts
packages/cli/src/commands/install/utils.ts
packages/integration-tests/package.json
packages/integration-tests/src/constants.ts
packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
packages/integration-tests/src/tests/ui/smoke.test.ts

- since cloud environment has a different setup, we'll separate them from oss tests
- added basic smoke tests for cloud
CI

refactor: init cloud ui tests

---

.github/workflows/release-cloud.yml

forgot to do this
most copied from core, should be fine to test after merge

ci: add deploy cloud workflow

---

.github/workflows/release-cloud.yml

ci: update cloud env name

---

packages/core/src/routes/admin-user.test.ts
packages/toolkit/core-kit/src/regex.ts

Update core password regex accordingly. related PR #3295 
test updated
OR

refactor(core): update core password regex

---

packages/console/src/cloud/constants/index.ts
packages/console/src/cloud/pages/About/index.tsx
packages/console/src/cloud/pages/Congrats/index.tsx
packages/console/src/cloud/pages/Onboarding/index.module.scss
packages/console/src/cloud/pages/Onboarding/index.tsx
packages/console/src/cloud/pages/SignInExperience/index.tsx
packages/console/src/cloud/pages/SignInExperience/utils.ts
packages/console/src/cloud/pages/Welcome/index.tsx
packages/console/src/cloud/types.ts
packages/console/src/cloud/utils.ts
packages/console/src/containers/AppContent/index.tsx
packages/console/src/pages/Main/index.tsx

The meaning of `onboard` is not the same as `onboarding`. Need to rename `onboard` to `onboarding`.
Reference: https://jkenglish.co/blog/on_board/
Test locally.
OR

chore(console): fix typo

---

.changeset-staged/giant-mice-applaud.md
packages/core/package.json
packages/core/src/utils/storage/index.ts
packages/core/src/utils/storage/s3-storage.ts
packages/schemas/src/types/system.ts
pnpm-lock.yaml

Add s3 storage provider.
Local tested
OR

feat(core): add s3 storage provider

---

.changeset-staged/loud-snakes-cross.md
packages/cli/src/commands/database/index.ts
packages/cli/src/commands/database/system.ts
packages/cli/src/queries/system.ts

Add get and set commands to update system table (storageProvider).
Local tested
OR

feat(cli): add system get and set commands

---

.changeset-staged/great-turkeys-fry.md
packages/console/src/pages/SignInExperience/tabs/Others/TermsForm.tsx
packages/console/src/pages/SignInExperience/utils/form.ts
packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience/guard.test.ts
packages/core/src/routes/sign-in-experience/index.test.ts
packages/core/src/routes/sign-in-experience/index.ts
packages/integration-tests/src/tests/api/sign-in-experience.test.ts
packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
packages/schemas/alterations/next-1678157950-privacy-policy-url.ts
packages/schemas/src/seeds/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql
packages/ui/src/__mocks__/logto.tsx

Add privacy policy URL to the SIE settings.
test locally
UT added
OR

feat(core,console,schemas,phrases): add privacy policy url

---

packages/cli/src/commands/database/seed/cloud.ts
packages/console/src/App.tsx
packages/console/src/consts/tenants.ts
packages/console/src/hooks/use-api.ts
packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
packages/core/src/env-set/index.ts
packages/core/src/middleware/koa-auth/utils.ts
packages/core/src/middleware/koa-spa-session-guard.ts
packages/core/src/oidc/adapter.ts
packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
packages/shared/src/utils/index.ts
packages/shared/src/utils/url.ts

always better to use `URL` than raw string.
`toString()` produces [the same result](https://developer.mozilla.org/en-US/docs/Web/API/URL/toString) as `href`. update to `href` since it's shorter
CI

refactor: use URL class

---

packages/integration-tests/src/tests/ui-cloud/smoke.test.ts

add more ui tests for cloud
CI

test: add ui cloud tests

---

packages/console/src/cloud/components/Broadcast/index.module.scss
packages/console/src/cloud/components/Broadcast/index.tsx
packages/console/src/cloud/constants/index.ts
packages/console/src/containers/AppContent/index.tsx
packages/phrases/src/locales/de/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts

Add the cloud preview broadcast to the admin console.
OR

feat(console): cloud preview broadcast

---

packages/console/src/components/ImageWithErrorFallback/index.tsx
packages/console/src/hooks/use-current-user.ts
packages/console/src/pages/Profile/components/BasicUserInfoSection/index.tsx
packages/console/src/pages/Profile/components/CardContent/index.tsx
packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
packages/console/src/pages/Profile/index.tsx
packages/core/src/routes-me/user.ts
packages/core/src/routes-me/verification-code.ts
packages/schemas/src/types/user.ts

Refactor profile related code by improving data types and API routes
Fix an issue that prevents google account avatars from being displayed
OR

refactor(console): polish code by improving data types and API routes

---

packages/console/src/pages/Profile/containers/HandleSocialCallback/index.tsx

Should better handle the error messages when linking social account to the current admin console user.
- [s] unit tests
- [s] integration tests
- [s] docs
OR

fix(console): better error handling when linking social in profile page

---

packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
packages/console/src/pages/Profile/utils.ts

Handle identifier collision error and display error messages inline with the text input.
OR

fix(console): properly handle errors on profile change basic info dialog

---

packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx

Verify email through verification code should work properly now
Locally tested with linking to another email, works properly
OR

fix(console): verify email via verification code should work properly

---

packages/console/src/pages/Profile/components/NotSet/index.module.scss

Change the font of "Not Set" placeholder text to `--font-body-2`.
OR

style(console): change "not set" font to body-2

---

.scripts/compare-database.js
packages/schemas/alterations/next-1678269972-use-restrictive-policies.ts
packages/schemas/tables/_after_all.sql
packages/schemas/tables/_after_each.sql

- use [restrictive policies](https://www.postgresql.org/docs/current/sql-createpolicy.html) for enhanced security and scalability. restrictive policies can be combined with permissive policies for advanced use cases. (coming next pr)
- add policy and grant comparison in CI
- CI passes if policies and grant are good
- CI fails if they [are different](https://github.com/logto-io/logto/actions/runs/4363025192/jobs/7628609360)

refactor(schemas): use restrictive policies

---

packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx

Remove "Change" button from link social section in AC profile page, as we cannot change to a different account without signing out from 3rd party first
OR

fix(console): remove "change" button from link social in profile

---

Dockerfile.cloud

update admin tenant endpoint in cloud Dockerfile to test if the console works for a separate domain.
/

chore: update admin tenant endpoint

---

.github/workflows/release-cloud.yml
Dockerfile.cloud

enable manually release Logto Cloud to prod by triggering workflow_dispatch
after merge

ci: release cloud prod

---

packages/phrases-ui/src/locales/de.ts

refactor(phrases): update de phrases

---

packages/phrases-ui/src/locales/fr.ts

refactor(ui): update fr phrases

---

packages/phrases-ui/src/locales/en.ts

refactor(phrases): update en phrases

---

.github/workflows/release-cloud.yml

fix workflow syntax error
deploy [works](https://github.com/logto-io/logto/actions/runs/4382953841)

ci: fix release cloud workflow

---

packages/phrases-ui/src/locales/ko.ts

refactor(phrases): update ko phrases

---

packages/phrases-ui/src/locales/pt-br.ts
packages/phrases-ui/src/locales/pt-pt.ts
packages/phrases-ui/src/locales/ru.ts
packages/phrases-ui/src/locales/tr-tr.ts
packages/phrases-ui/src/locales/zh-cn.ts

update pt-br, pt-pt, ru, tr-tr, zh-cn phrases
/

refactor(phrases): update multiple phrases

---

packages/ui/.parcelrc
packages/ui/.parcelrc.arm64
packages/ui/package.json
packages/ui/src/index.html
pnpm-lock.yaml

[preload](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload) sign-in experience and phrases for better ux
remove react app in UI, the page also loads those data

refactor(ui): preload data

---

packages/console/src/components/TextInput/index.tsx

Fixed a bug that value is not passed to the input field in TextInput component. Therefore the input value does not display properly.

fix(console): text input value should display properly

---

.scripts/compare-database.js
packages/cli/src/commands/database/seed/tables.ts
packages/cloud/src/libraries/tenants.ts
packages/cloud/src/queries/application.ts
packages/cloud/src/queries/index.ts
packages/cloud/src/queries/roles.ts
packages/schemas/alterations/next-1678425761-m2m-app-for-tenants.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/seeds/application.ts
packages/schemas/src/seeds/cloud-api.ts
packages/schemas/src/types/user.ts

Seed machine to machine app for each tenant, including:
1. New scopes and role for "cloud service": send sms/email
2. An m2m app for each tenant
3. Assign role to those app
Local tested
OR

feat(cli,cloud,schemas): seed m2m app for each tenant

---

packages/console/src/components/SignInExperiencePreview/index.module.scss
packages/console/src/components/SignInExperiencePreview/screen-size.module.scss
packages/ui/src/components/BrandingHeader/index.module.scss

optimize adaptation rules of sie preview
Update the onboarding SIE page on https://github.com/logto-io/logto/pull/3360 merged
OR

refactor(console): optimize adaptation rules of sie preview

---

packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx
packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx

Add auto focus to the first input in all profile modals
OR

fix(console): add auto focus to inputs in ac profile modals

---

packages/core/src/env-set/index.ts
packages/core/src/tenants/index.ts

update cache size to 100 and explicitly end pool when tenant disposes
pending online testing for better demonstration of resource usage

refactor(core): update cache size and end pool when tenant disposes

---

.changeset-staged/quick-schools-complain.md
packages/console/src/components/SignInExperiencePreview/index.tsx
packages/console/src/pages/SignInExperience/tabs/Branding/CustomCssForm.tsx
packages/console/src/pages/SignInExperience/tabs/Branding/index.module.scss
packages/console/src/pages/SignInExperience/tabs/Branding/index.tsx
packages/console/src/pages/SignInExperience/utils/form.ts
packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
packages/ui/src/App.tsx

Add AC custom CSS code editor and real-time preview of custom CSS.
1. Should have a timeout before the change applies to preview.
2. For all code editor components, trailing newline can not be properly displayed.
OR

feat(console): enable AC config and real-time live preview on customCss

---

packages/console/src/onboarding/pages/About/index.tsx
packages/console/src/onboarding/pages/About/options.tsx
packages/console/src/onboarding/types.ts
packages/phrases/src/locales/de/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts

1. The about user page should only have the reason options when the user uses Logto in a personal project.
2. The company size `1-49` should be `2-49` in phrases
Test Locally.
OR

refactor(console): fix onboarding about page

---

README.md
packages/console/src/onboarding/constants/index.ts

update in-app blog link and README blog title
/

chore: update blog url and title

---

packages/console/src/onboarding/pages/Welcome/index.tsx
packages/phrases/src/locales/de/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts

refactor(console): update onboarding welcome page image and description
OR

refactor(console): update onboarding welcome page image and description

---

packages/core/src/tenants/utils.ts
packages/schemas/alterations/next-1678716747-service-logs.ts
packages/schemas/tables/_after_all.sql
packages/schemas/tables/service_logs.sql

Add service logs table, this table will be used to store Logto's official SMS/Email service for tenants.
Local tested with the migration results.
OR

feat(schemas): add service logs table

---

packages/core/src/routes/well-known.test.ts
packages/toolkit/core-kit/jest.config.js
packages/ui/package.json
pnpm-lock.yaml

remove jest-matcher-specific-error config in core-kit
OR

fix(test): remove jest-matcher-specific-error

---

packages/cloud/src/libraries/services.ts
packages/cloud/src/queries/application.ts
packages/cloud/src/routes/index.ts
packages/cloud/src/routes/service.test.ts
packages/cloud/src/routes/services.ts
packages/cloud/src/routes/tenants.test.ts
packages/cloud/src/routes/tenants.ts
packages/cloud/src/test-utils/libraries.ts

Init service route in "cloud"
Local tested with real "access token" from m2m app.
OR

feat(cloud): init service route

---

packages/console/src/components/ApplicationName/index.tsx
packages/console/src/components/UserName/index.tsx
packages/console/src/pages/Connectors/components/ConnectorStatusField/index.tsx
packages/console/src/pages/Connectors/components/SignInExperienceSetupNotice/index.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/ConnectorSetupWarning.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/index.tsx

per discussion, in-app links should not open a new window unless specified
/

refactor(console): use in-place navigation for in-app links

---

packages/console/src/components/SignInExperiencePreview/index.tsx

Remove dirty code. Forgot to remove these codes in the previous PR.
OR

chore: remove dirty code

---

packages/ui/src/App.tsx
packages/ui/src/pages/ErrorPage/index.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SignIn/index.tsx

hide back CTA for root error pages
test locally
OR

style(ui): hide back CTA for root error pages

---

packages/ui/src/Layout/AppLayout/index.module.scss
packages/ui/src/Layout/LandingPageLayout/index.module.scss

fix secondary page spacing
Before
test locally
After
OR

style(ui): fix secondary page spacing

---

packages/console/src/components/RadioGroup/Radio.module.scss
packages/console/src/components/RadioGroup/index.module.scss
packages/console/src/onboarding/components/CardSelector/MultiCardSelector/index.module.scss
packages/console/src/onboarding/pages/SignInExperience/index.module.scss

refactor(console): update selector styles
- Swap the hover and selected states of onboarding cards (LOG-5652)
- Fix selector card style issue (LOG-5682)
- Update the sie config form min-width to 500px to improve the form style (LOG-5650)
- Change the card text color from `--color-text-link` to `--color-primary` (LOG-5661)
OR

refactor(console): update selector styles

---

.changeset-staged/real-carpets-wait.md
packages/cli/package.json
packages/cloud/package.json
packages/cloud/src/index.ts
packages/cloud/src/libraries/services.ts
packages/cloud/src/queries/connector.ts
packages/cloud/src/queries/index.ts
packages/cloud/src/routes/service.test.ts
packages/cloud/src/routes/services.ts
packages/cloud/src/test-utils/libraries.ts
packages/cloud/src/utils/connector/index.ts
packages/cloud/src/utils/connector/types.ts
packages/toolkit/connector-kit/src/types.ts
pnpm-lock.yaml

Implement send email on cloud: call admin tenant's connector to send.
UTs and local tested, email received.
OR

feat(cloud): send email

---

.scripts/package.sh
packages/cli/src/commands/connector/add.ts
packages/cli/src/commands/connector/utils.ts
packages/core/src/routes/connector.ts
packages/shared/src/models/connector.ts
packages/shared/src/models/index.ts

install demo connectors only in cloud
Local tested
OR

feat(cli,core,shared): install demo connectors only in cloud

---

packages/cloud/src/libraries/services.ts
packages/cloud/src/queries/index.ts
packages/cloud/src/queries/service-logs.ts
packages/cloud/src/routes/service.test.ts
packages/cloud/src/routes/services.ts
packages/cloud/src/test-utils/libraries.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/service-log.ts

limit control for send email, each tenant have 100 times.
UTs
OR

feat(cloud): limit control for send email

---

.github/workflows/release.yml
packages/core/src/env-set/create-pool.ts
packages/core/src/env-set/index.ts
packages/core/src/libraries/hook.ts
packages/core/src/tenants/index.ts
packages/shared/src/env/GlobalValues.ts

add two configs `TENANT_POOL_SIZE` and `DATABASE_POOL_SIZE` to dynamically adjust pool sizes for tuning performance without pushing code
on cloud

refactor: support setting pool sizes by env variable

---

packages/cloud/src/libraries/tenants.ts
packages/console/src/consts/connectors.ts
packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
packages/console/src/pages/Connectors/components/CreateForm/index.tsx
packages/console/src/pages/Connectors/index.tsx
packages/console/src/pages/Connectors/utils/index.ts
packages/console/src/types/connector.ts
packages/core/src/routes/connector.ts
packages/core/src/utils/connectors/index.ts
packages/schemas/src/types/connector.ts
packages/shared/src/models/connector.ts

Display demo connectors in AC, not allow to create/modify, and hide configs.
Local tested
OR

feat(core,console): display demo connectors

---

packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/SignInExperience/tabs/Branding/CustomCssForm.tsx
packages/console/src/pages/SignInExperience/types.ts
packages/console/src/pages/SignInExperience/utils/form.ts
packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts

update custom CSS content and add placeholder in code editor
OR

chore: update custom css content and add placeholder in code editor

---

.github/workflows/release.yml
Dockerfile

add "additional_connector_args" option to add cloud connector in Dockerfile
CI

ci: add cloud connectors when build for dev

---

.github/workflows/main.yml
.github/workflows/release.yml

ci: fix core dev build

---

packages/console/src/pages/SignInExperience/hooks/use-preview-configs.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts

update custom CSS render delay to 400ms
OR

chore: update custom css render delay to 400ms

---

Dockerfile.cloud

install connector in cloud dockerfile, because cloud "email" service depends on that.
Unable to tested in local.
OR

fix: install connector in cloud dockerfile

---

packages/console/src/components/CardTitle/index.module.scss
packages/console/src/components/CardTitle/index.tsx
packages/console/src/components/ModalLayout/index.tsx
packages/console/src/onboarding/components/EarlyBirdGift/GiftModal/index.tsx
packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
packages/console/src/pages/RoleDetails/RoleSettings/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
packages/console/src/pages/Roles/index.tsx

Add RBAC-related learn more links
OR

feat(console): add rbac related learn more links

---

packages/console/src/components/SignInExperiencePreview/index.tsx

fire post message only after the iframe is successfully loaded
test locally
OR

fix(console): fix preview post message error

---

packages/console/src/onboarding/pages/SignInExperience/index.module.scss
packages/console/src/pages/Connectors/components/Guide/index.module.scss
packages/console/src/pages/SignInExperience/index.module.scss

Update full-page content size
Design doc: https://www.figma.com/file/9cTrxRlkQCp4Fm1oQzoje0/%F0%9F%90%B0-Cloud-Preview-%E7%9B%B8%E5%85%B3?node-id=1522-111273&t=S2mQ60xVqnAiLEtn-0
OR

refactor(console): update full-page content size

---

packages/phrases/src/locales/de/translation/demo-app.ts
packages/phrases/src/locales/en/translation/demo-app.ts
packages/phrases/src/locales/fr/translation/demo-app.ts
packages/phrases/src/locales/ko/translation/demo-app.ts
packages/phrases/src/locales/pt-br/translation/demo-app.ts
packages/phrases/src/locales/pt-pt/translation/demo-app.ts
packages/phrases/src/locales/tr-tr/translation/demo-app.ts
packages/phrases/src/locales/zh-cn/translation/demo-app.ts

Replace 'demo app' with 'live preview' in the demo app.
Test locally
OR

refactor(demo-app): update phrases

---

packages/console/src/pages/SignInExperience/tabs/Branding/CustomCssForm.tsx
packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts

Manually put the link in tooltips at the beginning of a new line. Seems that CSS can not address the format issue.
OR

fix(console): correct display format

---

packages/console/src/cloud/App.tsx
packages/console/src/cloud/pages/SocialDemoCallback/index.module.scss
packages/console/src/cloud/pages/SocialDemoCallback/index.tsx
packages/console/src/cloud/types.ts
packages/phrases/src/locales/de/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts

add social callback page for demo connector.
Local tested
OR

feat(cloud): add social callback page

---

packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx

nonstandard social connector detail page `target` failed to display.
Before this change:
After the fix:
OR

fix(console): nonstandard social connector detail page target fail to display

---

.changeset-staged/breezy-moose-greet.md
packages/cloud/src/libraries/tenants.ts
packages/cloud/src/queries/connector.ts
packages/cloud/src/queries/index.ts
packages/cloud/src/queries/system.ts
packages/schemas/src/types/system.ts
packages/shared/src/models/connector.ts

Add 3 demo social connectors for new tenants, if the preset configs are exists in "systems"
Local tested
OR

feat(cloud,schemas): add demo social connectors for tenant

---

packages/console/src/onboarding/pages/SignInExperience/components/InspireMe/index.module.scss

style(console): update inspire me button border color
OR

style(console): update inspire me button border color

---

packages/console/src/onboarding/pages/SignInExperience/index.tsx
packages/core/src/__mocks__/connector.ts
packages/core/src/routes/sign-in-experience/index.test.ts
packages/core/src/routes/sign-in-experience/index.ts

remove unselected(onboarding) demo social connectors. (they are created on tenant creation)
UTs
OR

feat(core): remove unselected demo social connectors

---

packages/phrases/src/locales/de/translation/admin-console/connectors.ts
packages/phrases/src/locales/en/translation/admin-console/connectors.ts
packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts

update connector demo tip
Test locally.
OR

refactor(phrases): update connector demo tip

---

packages/console/src/pages/SignInExperience/tabs/Others/TermsForm.tsx
packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts

refactor(console): update terms form phrases

---

packages/cloud/jest.config.js
packages/cloud/jest.setup.js
packages/cloud/src/env-set/index.ts
packages/cloud/src/index.ts
packages/cloud/src/libraries/tenants.ts

- reuse `GlobalValues` class from shared
- use URL class for manipulation
CI

refactor(cloud): reuse `GlobalValues` class from shared

---

packages/ui/src/utils/form.ts

align the username regex with backend
import the username and email regex from core-kit package to keep SSOT.
test locally
OR

fix(ui): align the username regex with backend

---

packages/ui/src/App.tsx
packages/ui/src/pages/Consent/index.module.scss
packages/ui/src/pages/Consent/index.tsx

update consent page layout
test locally
OR

style(ui): update consent page layout

---

packages/phrases-ui/src/locales/en.ts
packages/ui/src/App.tsx
packages/ui/src/pages/ErrorPage/index.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SignIn/index.tsx

update the error page back button
Remove the bottom back button. 
Show the top nav bar only if the current history stack length exceeds 1. 
test locally
OR

style(ui): update error page back button

---

packages/console/src/pages/GetStarted/hook.ts
packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
packages/phrases/src/locales/de/translation/admin-console/get-started.ts
packages/phrases/src/locales/en/translation/admin-console/get-started.ts
packages/phrases/src/locales/fr/translation/admin-console/get-started.ts
packages/phrases/src/locales/ko/translation/admin-console/get-started.ts
packages/phrases/src/locales/pt-br/translation/admin-console/get-started.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/get-started.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/get-started.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/get-started.ts

Update get-started content according to new requirements.
OR

refactor(console): update get-started content

---

packages/console/src/containers/TenantAppContainer/index.tsx
packages/console/src/onboarding/hooks/use-user-onboarding-data.ts

- skip onboarding for admin tenant admins
- treat admin tenant admins using a business plan
Test locally.
OR

fix(console): skip onboarding for admin tenant admins

---

packages/console/src/pages/Connectors/components/CreateForm/index.module.scss

style(console): add padding-right for connector item name
OR

style(console): add padding-right for connector item name

---

packages/console/src/onboarding/pages/SignInExperience/index.module.scss

style(console): update onboarding sie page responsive layout
- the preview content and the form content should have equal width.
- the preview content and the form content should have a `540px` min-width.
Test locally.
OR

style(console): update onboarding sie page responsive layout

---

packages/console/src/pages/Connectors/components/Guide/index.module.scss

fix connector guide readme style
OR

style(console): fix connector guide style

---

packages/phrases-ui/src/locales/de.ts
packages/phrases-ui/src/locales/en.ts
packages/phrases-ui/src/locales/fr.ts
packages/phrases-ui/src/locales/ko.ts
packages/phrases-ui/src/locales/pt-br.ts
packages/phrases-ui/src/locales/pt-pt.ts
packages/phrases-ui/src/locales/ru.ts
packages/phrases-ui/src/locales/tr-tr.ts
packages/phrases-ui/src/locales/zh-cn.ts
packages/ui/src/components/BrandingHeader/index.test.tsx
packages/ui/src/pages/SignIn/index.tsx

update and polish title per our latest update
/

refactor(phrases,ui): update sign-in title

---

packages/console/src/onboarding/components/Broadcast/index.module.scss
packages/core/src/routes/sign-in-experience/index.ts
packages/phrases/src/locales/de/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts

refactor: update banner style

---

.github/workflows/release.yml
packages/cloud/package.json
packages/cloud/src/index.ts
packages/cloud/src/middleware/with-error-report.ts
packages/core/package.json
packages/core/src/app/init.ts
packages/core/src/errors/RequestError/index.ts
packages/core/src/errors/ServerError/index.ts
packages/core/src/index.ts
packages/core/src/middleware/koa-error-handler.ts
packages/core/src/middleware/koa-guard.ts
packages/shared/package.json
packages/shared/src/app-insights/index.ts
pnpm-lock.yaml

- manually setup Application Insights to avoid SDK version mismatch then we cannot record error trace
- report exception when status code >= 500 or other unhandled exceptions occurred
- use sha for deployment to avoid confusion (#3474)
see it

refactor(cloud,core): report exception to Application Insights

---

.changeset-staged/flat-guests-bathe.md
packages/console/src/pages/ConnectorDetails/components/DeleteConnectorConfirmModal/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorDeleteButton/index.tsx
packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts

feat(console): add deletion confirm for in-used passwordless connectors
OR

feat(console): add deletion confirm for in-used passwordless connectors

---

packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx

refactor(console): use image uploader for avatar field
OR

refactor(console): use image uploader for avatar field

---

.github/workflows/release.yml

leverage [deployment slots](https://learn.microsoft.com/en-us/azure/app-service/deploy-staging-slots) for smooth deployments (0 downtime)
this [workflow run](https://github.com/logto-io/logto/actions/runs/4459101156/jobs/7831382683) works and no downtime while deploying. pending more tests once merged.

ci: deploy to staging slot and swap

---

.github/workflows/release.yml

- separate core and cloud deployment since each of them needs about 10 min to finish
- set concurrency group to ensure there's no one deployment per time
[CI](https://github.com/logto-io/logto/actions/runs/4459414901)

ci: separate core and cloud deployment

---

packages/console/src/components/CodeEditor/index.module.scss
packages/console/src/components/CodeEditor/index.tsx
packages/console/src/pages/SignInExperience/tabs/Branding/CustomCssForm.module.scss
packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts

polish placeholder and copy icon

refactor(console,phrases): polish css editor

---

.changeset-staged/thin-balloons-brush.md
.changeset/thin-balloons-brush.md
packages/core/src/__mocks__/connector-base-data.ts
packages/core/src/__mocks__/connector.ts
packages/core/src/libraries/connector.test.ts
packages/core/src/libraries/social.ts
packages/core/src/queries/connector.test.ts
packages/core/src/queries/connector.ts
packages/core/src/routes-me/social.ts
packages/core/src/routes/interaction/utils/social-verification.test.ts
packages/core/src/routes/interaction/utils/social-verification.ts
packages/schemas/alterations/next-1679209413-drop-connector-database-storage.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/tables/connectors.sql
packages/toolkit/connector-kit/src/types.ts

Remove connector db storage column and its access for potential abuse.
UTs and ITs.
OR

refactor(schemas,core,toolkit): remove connector db storage and disable access

---

packages/console/src/pages/Profile/containers/DeleteAccountModal/index.tsx

refactor(console): fix contact email

---

packages/console/package.json
packages/console/src/onboarding/pages/About/index.tsx
packages/console/src/onboarding/pages/Congrats/index.tsx
packages/console/src/onboarding/pages/SignInExperience/index.tsx
packages/console/src/onboarding/pages/Welcome/index.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/AuditLogDetails/index.tsx
packages/console/src/pages/AuditLogs/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/index.tsx
packages/console/src/pages/Dashboard/index.tsx
packages/console/src/pages/GetStarted/index.tsx
packages/console/src/pages/Profile/index.tsx
packages/console/src/pages/RoleDetails/index.tsx
packages/console/src/pages/Roles/index.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/index.tsx
packages/console/src/utils/app-insights.ts
pnpm-lock.yaml

- add auto tracking for console
- add tracking for main components (first-level routes)
note arrow function component will be "Unnamed" for tracking, changing them to function declaration instead.
perform minimum update now. will merge #3520 after launch
report as expected

refactor(console): add tracking

---

packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/schemas/src/utils/index.ts
packages/schemas/src/utils/management-api.ts

since it should not be editable

refactor(console): hide Management API from editing

---

packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts

chore(phrases): update custom css content

---

packages/console/src/onboarding/assets/images/social-microsoft.svg
packages/console/src/onboarding/pages/SignInExperience/options.tsx

add microsoft connector template
OR

refactor(console): add microsoft connector template

---

packages/console/src/cloud/pages/SocialDemoCallback/index.module.scss

fix congrats size in social demo callback page
OR

style(cloud): fix congrats size in social demo callback page

---

packages/console/src/pages/Connectors/components/Guide/index.tsx

clear conflict connector notice on connector change.
local tested.
OR

fix(console): clear conflict connector notice

---

packages/console/src/onboarding/pages/SignInExperience/options.tsx
packages/phrases/src/locales/de/translation/admin-console/connectors.ts
packages/phrases/src/locales/de/translation/admin-console/general.ts
packages/phrases/src/locales/en/translation/admin-console/connectors.ts
packages/phrases/src/locales/en/translation/admin-console/general.ts
packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
packages/phrases/src/locales/fr/translation/admin-console/general.ts
packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
packages/phrases/src/locales/ko/translation/admin-console/general.ts
packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts

- remove cap limit tag in onboarding options
- update demo tag phrases
OR

refactor(console): remove cap limit tag in onboarding options

---

packages/console/src/pages/Connectors/components/CreateForm/constants.ts

Update SMS and Email connectors display order.
OR

feat(console): sms and email connectors order

---

packages/console/src/onboarding/pages/SignInExperience/components/PlatformTabs/index.tsx
packages/console/src/onboarding/pages/SignInExperience/components/Preview/index.tsx

The web platform should come first.
OR

refactor(console): change onboarding sie preview platform order

---

packages/cloud/src/libraries/tenants.ts

the console  initial redirect uri for new tenants should be generated by url set
tested locally

fix(cloud): correct initial redirect uris

---

.github/workflows/release.yml
Dockerfile.cloud

chore: set app insights connection string in cloud Dockerfile

---

packages/ui/src/Providers/IframeModalProvider/IframeModal/index.tsx

disallow js in terms iframe. Unless exceptions are received, we should apply all the restrictions.
OR

chore(ui): disallow js in terms iframe

---

packages/phrases/src/locales/de/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko/errors.ts
packages/phrases/src/locales/pt-br/errors.ts
packages/phrases/src/locales/pt-pt/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts

chore(phrases): update error phrases i18n

---

packages/console/src/App.tsx
packages/console/src/index.html
packages/console/src/utils/set-title.ts

set title based on isCloud
test locally
OR

feat(console): set title based on isCloud

---

packages/console/src/onboarding/pages/SignInExperience/utils.ts

- The authentications should not control the sign-up verification setting, which is only determined by the identifier.
- Set up the sign-in and sign-up config separately for a better understanding.
Test locally.
OR

fix(console): parse onboarding sie config

---

packages/cli/src/commands/database/seed/index.ts
packages/cli/src/commands/database/seed/tables.ts
packages/cloud/src/libraries/tenants.ts
packages/console/src/onboarding/components/Broadcast/index.tsx
packages/console/src/onboarding/constants/index.ts
packages/schemas/src/seeds/sign-in-experience.ts

update about link and initial sie configs
pending online

refactor: update initial data

---

packages/console/src/onboarding/pages/SignInExperience/components/InspireMe/index.module.scss

fix inspire me button spacing
OR

style(console): fix inspire me button spacing

---

packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/go.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx

update guide link
test locally
OR

chore(console): update guide link

---

packages/console/src/cloud/pages/Main/index.tsx
packages/console/src/containers/AppContent/index.tsx

fix cloud sign-up mode. Apply sign-up mode qs reading at the could route.
test locally
OR

fix(console): fix cloud sign-up mode

---

packages/console/src/pages/Connectors/index.tsx

Correct doc link.
Tested locally and can go to correct page.
OR

fix(console): doc link

---

packages/console/src/pages/Connectors/components/ConnectorName/DemoTag.tsx
packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
packages/phrases/src/locales/de/translation/admin-console/connectors.ts
packages/phrases/src/locales/en/translation/admin-console/connectors.ts
packages/phrases/src/locales/fr/translation/admin-console/connectors.ts
packages/phrases/src/locales/ko/translation/admin-console/connectors.ts
packages/phrases/src/locales/pt-br/translation/admin-console/connectors.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/connectors.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/connectors.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/connectors.ts

update connector demo tip phrases
Test locally.
OR

refactor(phrases): update connector demo tip phrases

---

packages/console/src/utils/app-insights.ts

safely init app insights without crash. also fix the string format during transformation.
tested in dev, finally it works

refactor(console): safely init app insights

---

.github/workflows/release.yml
README.md
docker-compose.demo.uffizzi.yml

change something since we're GA
/

chore: update README.md

---

packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
packages/integration-tests/src/tests/ui/smoke.test.ts

refactor(test): increase UI test timeout

---

.github/workflows/release.yml

that's why cloud is always pending
CI

ci: fix typo

---

packages/console/src/hooks/use-documentation-url.ts
packages/console/src/pages/SignInExperience/tabs/Branding/CustomCssForm.tsx

Fix custom CSS tooltip learn more link.
OR

fix(console): custom css learn more link

---

packages/console/src/pages/Applications/index.tsx

The mysterious smog rises up again when your first app is M2M type. This PR should fix this issue completely.

fix(console): mysterious smog should be gone on first app creation

---

packages/console/src/pages/Connectors/index.tsx

Correct learn more link when no social connector is added.
OR

fix(console): social connector learn more link

---

packages/phrases/src/locales/de/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts

fix custom CSS component card title.
OR

fix(console): custom css component card title

---

packages/console/src/pages/SignInExperience/index.module.scss

style(console): set min-width to sie form and preview
OR

style(console): set min-width to sie form and preview

---

packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx

chore(console): remove unwanted console log
No need.
OR

chore(console): remove unwanted console log

---

packages/cli/src/commands/connector/utils.ts

use conditional array to manage cloud connector list
OR

refactor(cli): use conditional array to manage cloud connector list

---

packages/console/src/components/FormCard/index.module.scss

style(console): fix outline cutting issue on form field
OR

style(console): fix outline cutting issue on form field

---

packages/console/src/pages/ConnectorDetails/components/DeleteConnectorConfirmModal/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorDeleteButton/index.tsx
packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/connector-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts

feat(console): add deletion confirm for connectors
OR

feat(console): add deletion confirm for connectors

---

packages/console/src/pages/Connectors/components/ConfigForm/index.tsx

Add connector form tooltip for each field.
OR

chore(console): add connector form tooltip

---

packages/console/src/pages/AuditLogDetails/index.module.scss

refactor(console): add word-break for audit logs

---

packages/console/src/hooks/use-documentation-url.ts

avoid zh-cn docs links since it has been removed
Tested locally on zh-CN AC and can jump to corresponding English doc webpage.
OR

fix(console): avoid zh-cn docs links since it has been removed

---

packages/phrases-ui/src/locales/de.ts

fix(phrases): capitalized username in de

---

packages/console/src/cloud/pages/Main/Tenants.tsx
packages/console/src/cloud/pages/Main/index.tsx
packages/console/src/components/SessionExpired/index.tsx
packages/console/src/containers/ErrorBoundary/index.tsx
packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
packages/console/src/pages/Profile/index.tsx

catch user interaction errors
Note: in the application, all HTTP errors, except for 'loadTenants', are caused by user actions.
OR

fix(console): catch user interaction errors

---

packages/console/src/containers/ConsoleContent/index.module.scss

Fix the cloud env code editor overflow error.
The AppInsightsWrapper prevents the CSS assignment to direct children.
https://user-images.githubusercontent.com/15182327/227846600-1756b71e-732a-4b21-9f6a-e09346d33a86.mov
OR

fix(console): cloud env code editor over-expanding error

---

packages/console/src/onboarding/pages/About/index.tsx
packages/console/src/onboarding/pages/Congrats/index.tsx
packages/console/src/onboarding/pages/SignInExperience/index.tsx
packages/console/src/onboarding/pages/Welcome/index.tsx

refactor(console): support navigating back by the browser when onboarding
Test locally.
OR

refactor(console): support navigating back by the browser when onboarding

---

packages/console/src/pages/ConnectorDetails/components/DeleteConnectorConfirmModal/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorDeleteButton/index.tsx
packages/console/src/pages/GetStarted/index.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.tsx

Add missing loading state for confirm modals.
Test locally.
OR

fix(console): add missing loading state for confirm modals

---

packages/console/src/pages/Users/components/CreateForm/index.tsx
packages/console/src/pages/Users/components/CreateForm/utils.ts

User password requires a minimum of 8 characters and contains a mix of letters, numbers, and symbols.
Test locally.
OR

fix(console): generate user password

---

.changeset/thick-pumpkins-count.md
packages/cli/package.json
packages/cli/src/commands/translate/create.ts
packages/cli/src/commands/translate/index.ts
packages/cli/src/commands/translate/list-tags.ts
packages/cli/src/commands/translate/openai.ts
packages/cli/src/commands/translate/utils.ts
packages/cli/src/index.ts
packages/cli/src/utils.ts
pnpm-lock.yaml

- iterate phrases files and translate to a new language using OpenAI API
translation PRs will be submitted separately

feat(cli): create translation command

---

packages/console/src/pages/Connectors/components/CreateForm/Skeleton.module.scss
packages/console/src/pages/Connectors/components/CreateForm/Skeleton.tsx
packages/console/src/pages/Connectors/components/CreateForm/index.tsx

refactor(console): add connector loading state
OR

refactor(console): add connector loading state

---

packages/console/src/components/TextInput/index.module.scss
packages/console/src/components/TextInput/index.tsx
packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
packages/console/src/pages/Connectors/components/ConfigForm/index.tsx

According to the offline discussion:
1. hide arrows from the number input
2. disallow changing number values by mouse wheel
3. convert value to number before send to the backend rather a raw string
Test locally.
OR

refactor(console): change number input appearance to text input

---

packages/console/src/pages/Connectors/components/Guide/index.module.scss

Fix create connector guide padding.
OR

fix(console): connector create guide padding

---

packages/console/src/pages/Profile/index.tsx

Temporarely disable Link Account feature in admin console profile for open-sourced version
Locally tested

fix(console): temp disable link account feature in open source version

---

packages/ui/src/containers/TermsAndPrivacy/index.module.scss

Update font style of terms links
test locally
OR

style(ui): update font style of terms links

---

packages/ui/src/pages/SignInPassword/PasswordForm/index.tsx

Chrome triggers the password autocompletion detection only if both username and password input fields are present. Following google's official recommendation, add a hidden field with the identifier value in the password form. 
test locally
OR

fix(ui): add hidden field in password sign-in form

---

packages/ui/src/Layout/AppLayout/index.module.scss
packages/ui/src/components/ConfirmModal/Acmodal.module.scss
packages/ui/src/components/Notification/AppNotification/index.module.scss
packages/ui/src/containers/AppNotification/index.module.scss

adjust narrow screen desktop style
test locally
OR

style(ui): adjust narrow screen desktop style

---

packages/console/src/components/Button/index.tsx
packages/console/src/containers/ConsoleContent/Sidebar/components/Contact/index.tsx

Add optional href prop to the Button component.

chore(console): add href to Button component

---

packages/phrases-ui/src/locales/pt-br/action.ts

Add translation fix in `phrase-ui` package
Tested locally
OR

fix(phrases): fix action change phrase

---

.changeset-staged/shiny-crabs-wink.md
packages/console/src/components/ImageWithErrorFallback/index.tsx
packages/console/src/components/Markdown/components/GithubRawImage/index.tsx
packages/console/src/components/Uploader/ImageUploader/index.tsx
packages/core/package.json
packages/core/src/middleware/koa-security-headers.ts
packages/core/src/tenants/Tenant.ts
packages/shared/src/env/UrlSet.test.ts
packages/shared/src/env/UrlSet.ts
packages/ui/src/Providers/IframeModalProvider/IframeModal/index.tsx
packages/ui/src/components/BrandingHeader/index.tsx
packages/ui/src/components/Button/SocialLinkButton.tsx
packages/ui/src/containers/SocialLanding/index.tsx
packages/ui/src/pages/Consent/index.tsx
pnpm-lock.yaml

Set the following security headers to logto core service:
- Expect-CT: max-age=0
- remove X-Powered-By header
- Strict-Transport-Security: max-age=15552000; includeSubDomains
- X-Download-Options: noopen
- X-Content-Type-Options: nosniff
- X-Permitted-Cross-Domain-Policies: none
- Referrer-Policy: no-referrer
- X-XSS-Protection: 0
- Cross-Origin-Opener-Policy: same-origin
- Cross-Origin-Resource-Policy: same-origin
OR

feat(core): apply standard security headers 1/2

---

packages/cli/src/commands/translate/create.ts
packages/cli/src/commands/translate/sync.ts

make the translation commands more clear for using.
/

chore(cli): update translate command description

---

packages/app-insights/src/node.ts
packages/app-insights/src/react.ts
packages/cloud/src/index.ts
packages/console/src/App.tsx
packages/core/src/index.ts
packages/ui/src/App.tsx

conditional import and setup app insights sdk for better experience, resolves LOG-5907
with `APPLICATIONINSIGHTS_CONNECTION_STRING`
without `APPLICATIONINSIGHTS_CONNECTION_STRING`

refactor: conditional import app insights sdk

---

packages/ui/src/hooks/use-social-callback-handler.ts

replace plain search string concatenate with URLSearchParams instances
OR

refactor(ui): replace plain search string concatenate

---

.changeset/curly-laws-hammer.md
packages/console/src/components/AuditLogTable/components/EventSelector/index.tsx
packages/console/src/components/AuditLogTable/index.tsx
packages/console/src/consts/logs.ts

ensure all log keys present in the filter, remove deprecated log keys, fix log event filter

fix(console): log event filter

---

.changeset/popular-wasps-begin.md
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

Provide a management API to detect is a user has set the password, which is useful when developing your own profile page.
Will update docs in another PR.
UT

feat(core): provide management API to detect if user has password

---

packages/cli/src/commands/translate/create.ts
packages/cli/src/commands/translate/openai.ts
packages/cli/src/commands/translate/prompts.ts
packages/cli/src/commands/translate/sync.ts
packages/cli/src/commands/translate/utils.ts
packages/phrases/src/locales/fr/translation/admin-console/components.ts
packages/phrases/src/locales/ja/translation/admin-console/components.ts
packages/phrases/src/locales/ko/translation/admin-console/components.ts
packages/phrases/src/locales/ru/translation/admin-console/components.ts

improve translation cli
The result is good:
OR

refactor(cli): improve translation cli

---

.changeset/config.json
.github/workflows/changesets.yml

- use changesets official workflow to generate a better PR
- set `updateInternalDependencies` to `"minor"` for less version bumping and we may do separate releases in the future
after merge, see the new "version packages" PR

chore: update changesets config

---

.github/workflows/changesets.yml

remove duplicate `version`
after merge

ci: remove duplicate version script

---

packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.module.scss
packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.tsx
packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.module.scss
packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.tsx
packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
packages/console/src/pages/UserDetails/index.module.scss
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/index.tsx
packages/console/src/utils/user.ts

Add user identity display rule.
See [Figma](https://www.figma.com/file/qJM3mUAJXjOFU5zqfuRgJO/%F0%9F%98%8A-User-Management-Small-Updates?node-id=1-19278&t=hyIc3cQOSkTqvS6y-0) for details.
OR

refactor(console): add user identity display rule

---

packages/console/src/scss/modal.module.scss

Change the modal overlay padding-top and padding-bottom from 96px to 12px.
Test locally.
OR

style(console): update modal overlay paddings

---

packages/cloud/src/middleware/with-security-headers.ts
packages/core/src/middleware/koa-security-headers.ts

add ApplicationInsights to CSP `connect-src` to comply with the definition
tested locally, no CSP violation error shows for both main flow and console while ApplicationInsights works as expected

refactor(core,cloud): add ApplicationInsights URL to CSP directive

---

packages/connectors/connector-alipay-native/README.md
packages/connectors/connector-alipay-web/README.md
packages/connectors/connector-aliyun-dm/README.md
packages/connectors/connector-aliyun-sms/README.md
packages/connectors/connector-apple/README.md
packages/connectors/connector-aws-ses/README.md
packages/connectors/connector-github/README.md
packages/connectors/connector-sendgrid-email/README.md
packages/connectors/connector-smtp/README.md
packages/connectors/connector-tencent-sms/README.md
packages/connectors/connector-twilio-sms/README.md
packages/connectors/connector-wechat-native/README.md
packages/connectors/connector-wechat-web/README.md

Update connector README docs links.
Tested links.
OR

docs(connector): update connector docs links

---

packages/core/package.json
packages/core/src/utils/storage/s3-storage.ts
pnpm-lock.yaml

use client s3 sdk to replace "aws-sdk".
Local tested.
OR

fix(core): use client s3 sdk

---

packages/integration-tests/jest.setup.js
packages/integration-tests/package.json
packages/integration-tests/src/utils.ts
packages/ui/jest.config.ts
packages/ui/package.json
packages/ui/src/jest.setup.ts
packages/ui/tsconfig.test.json
pnpm-lock.yaml

refactor(ui): use swc for testing

---

packages/console/src/components/Switch/index.tsx
packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx

Fix switch component in sign-in-experience. Previously the switch didn't work and couldn't switch on.

fix(console): switch component

---

packages/console/src/App.tsx

add useMemo to reduce render times
locally the console works as expected

refactor(console): add useMemo to resources and scopes

---

packages/core/src/libraries/user.ts

The existing "insert user" function has 2 steps inside:
1. insert a user in db
2. assign roles to that user
Now upgrade them to a single transction.
Local tested:
Add an error in the middle:
And then check DB, db is empty, the full 2 steps are reverted.
OR

refactor: use transaction to create user

---

packages/integration-tests/src/api/index.ts
packages/integration-tests/src/api/logto-config.ts
packages/integration-tests/src/tests/api/logto-config.test.ts

Add ITs for the logto-config APIs (already with response/status guard).
UTs and ITs.
OR

chore(test): add ITs for logto-config APIs

---

packages/cli/src/commands/install/utils.ts

a more friendly way to fill the release time gap #3770 #3776
- with current version, download ok
- with a non-existing version, fall back to "latest"

refactor(cli): fallback to latest when current version is unavailable

---

.github/CONTRIBUTING.md

update contribution guide connector part.
N/A
OR

chore: update contribution guide connector part

---

packages/console/src/containers/ConsoleContent/Sidebar/index.tsx
packages/console/src/containers/ConsoleContent/index.module.scss
packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/scss/overlayscrollbars.scss

Make scrollbar overflow on top of display content in sidebar and main content sections.
Shrink browser window size and hover on scrollable contents, we can see scrollbars are displayed on top of the display content without taking any physical space, and hide automatically when the mouse leaves
https://user-images.githubusercontent.com/12833674/234265423-af49da8e-2c92-4cf6-a5d7-27588bf58757.mov

feat: add overlay scrollbar on sidebar and main content

---

packages/toolkit/connector-kit/jest.config.js
packages/toolkit/connector-kit/package.json
packages/toolkit/connector-kit/src/index.test.ts
packages/toolkit/connector-kit/tsconfig.build.json
packages/toolkit/connector-kit/tsconfig.test.json
pnpm-lock.yaml

Add UTs for connector-kit.
UTs.
OR

chore(toolkit): add UTs for connector-kit

---

packages/core/src/routes/sign-in-experience/index.ts

Add SIE API guard.
The API-level ITs are simple for SIE APIs, and complicated restrictions are tested using UTs.
UTs and ITs.
OR

chore(test): add SIE API guard

---

packages/core/src/routes/custom-phrase.ts
packages/integration-tests/package.json
packages/integration-tests/src/api/custom-phrase.ts
packages/integration-tests/src/tests/api/custom-phrase.test.ts
pnpm-lock.yaml

complete custom phrase API guard and add ITs.
UTs and ITs.
OR

chore(test): complete custom phrase API guard and add ITs

---

packages/core/src/routes/connector/index.ts
packages/integration-tests/src/api/connector.ts
packages/integration-tests/src/tests/api/connector.test.ts
packages/schemas/src/types/connector.ts

1. Add IT to ensure mock connectors are properly installed.
2. Add response/status guards to connector factory APIs.
UTs and ITs.
OR

chore(schemas,test,core): add IT to ensure mock connectors are installed

---

.changeset/wise-jobs-push.md
packages/create/index.sh

feat: support passing cli arguments via `@logto/create`

---

packages/core/src/routes/dashboard.ts
packages/integration-tests/src/tests/api/dashboard.test.ts
packages/schemas/src/types/dashboard.ts
packages/schemas/src/types/index.ts

Add api response guard and error case tests to dashboard api
OR

test(core): add api response guard and error case tests to dashboard api

---

packages/core/src/routes/authn.test.ts

Remove legacy commented code.
UTs and ITs.
OR

chore(core): remove legacy commented code

---

packages/core/src/__mocks__/index.ts
packages/core/src/routes/role.scope.test.ts
packages/core/src/routes/role.scope.ts
packages/schemas/src/types/scope.ts

In `GET /roles/:id/scopes`, there is a bug: when the pagination is disabled, the element in response array doesn't have property "resource".
This PR fixes it and add response guard.
UTs
OR

fix(core): fix unpaginated scopes response

---

packages/core/src/routes/well-known.ts
packages/integration-tests/src/tests/api/well-known.test.ts

Add missing response guard and integration test case for `.well-known` apis
Locally tested

chore: add response guard and integration test for .well-known api

---

packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
packages/core/src/routes/dashboard.ts
packages/core/src/routes/role.scope.ts
packages/core/src/routes/role.ts
packages/core/src/utils/http.ts
packages/integration-tests/src/tests/api/role.scope.test.ts
packages/integration-tests/src/tests/api/role.test.ts
packages/integration-tests/src/tests/api/role.user.test.ts
packages/schemas/src/types/user.ts

Add API response guards and exception integration test cases to the role and scope related APIs. 
test locally
OR

test(core): add exception cases for role api and scope api

---

packages/console/package.json
packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx
packages/console/src/pages/Profile/utils.ts
packages/console/src/types/profile.ts
pnpm-lock.yaml

Remove superstruct from console project, and use zod instead.
Locally tested in console profile page, all worked properly

refactor(console): remove superstruct dependency from console

---

packages/core/src/routes/connector/index.ts
packages/integration-tests/src/tests/api/connector.test.ts
packages/schemas/src/types/connector.ts

add api response guard and error case tests to connector api
OR

test(core): add api response guard and error case tests to connector api

---

packages/core/src/routes-me/user.ts
packages/core/src/routes/admin-user-search.test.ts
packages/core/src/routes/admin-user-search.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/core/src/routes/init.ts
packages/core/src/routes/role.ts
packages/integration-tests/src/tests/api/admin-user.roles.test.ts
packages/integration-tests/src/tests/api/admin-user.test.ts
packages/schemas/src/types/user.ts

add api response guard and error case tests to admin user api
OR

test(core): add api response guard and error case tests to admin user

---

packages/core/src/middleware/koa-slonik-error-handler.test.ts
packages/core/src/middleware/koa-slonik-error-handler.ts

Use 422 for creation error, and 404 for entity not found situation on update in slonik
UT

fix(core): use correct status code for slonik errors

---

packages/core/src/routes/application.test.ts
packages/core/src/routes/application.ts
packages/integration-tests/src/api/application.ts
packages/integration-tests/src/tests/api/application.test.ts

Add response guards and integration tests for `application` APis
Locally tested OK (4/4)

chore: add response guard and integration tests for application APIs

---

packages/integration-tests/src/__mocks__/connectors-mock.ts
packages/integration-tests/src/api/connector.ts
packages/integration-tests/src/helpers/connector.ts
packages/integration-tests/src/tests/api/admin-user.test.ts
packages/integration-tests/src/tests/api/connector.test.ts

Update connector ITs:
1. add test cases: send test email/SMS messages before setting passwordless connectors
2. chore: clarify the usage of `id` and `connectorId` in API util functions.
3. refactor: set the connector instances config upon creating.
4. refactor: add util function for clearing connector table.
5. rename: rename `mockStandardEmailConnector*` as `mockAlternativeEmailConnector*` to avoid confusing since passwordless connectors can never be "standard" per our design.
UTs and ITs.
OR

chore(test): update connector integration tests

---

packages/core/src/routes/custom-phrase.test.ts
packages/core/src/routes/custom-phrase.ts
packages/core/src/routes/logto-config.ts
packages/core/src/routes/sign-in-experience/index.ts
packages/integration-tests/src/tests/api/custom-phrase.test.ts
packages/integration-tests/src/tests/api/sign-in-experience.test.ts

1. add status code guards for SIE, custom phrases, and logto configs APIs.
2. add counter cases.
UTs and ITs.
OR

chore(core,test): add status code guard for SIE, custom phrase and config APIs

---

packages/core/src/routes/log.ts
packages/integration-tests/src/tests/api/log.test.ts

add api response guard and error case tests to log api
OR

test(core): add api response guard and error case tests to log api

---

packages/core/src/routes/verification-code.ts
packages/integration-tests/src/api/verification-code.ts
packages/integration-tests/src/tests/api/verification-code.test.ts

test(core): add api response guard and error case tests for verification code
OR

test(core): add api response guard and error case tests for verification code

---

README.md

chore: fixed typo README.md

---

packages/core/src/routes/application.ts
packages/integration-tests/src/api/application.ts
packages/integration-tests/src/tests/api/application.test.ts

Add integration test for application's `isAdmin` update.
-
OR

test(core): add integration test for application isAdmin

---

packages/core/src/routes/authn.ts

add response and status guards for authn routes. note connector error status should be generated by detecting connector error handler
unit tests should cover

refactor(core): add guards for authn routes

---

packages/console/src/pages/WebhookDetails/index.tsx
packages/console/src/pages/Webhooks/index.tsx

chore(console): add app insights for webhook pages
N / A
OR

chore(console): add app insights for webhook pages

---

packages/core/src/routes/admin-user-role.ts

Add response and status guard to the `role` APIs.
The integration tests are already in-place, therefore this PR doesn't add any new integration tests
UT and IT

chore(core): add response guard for user roles APIs

---

packages/console/src/consts/external-links.ts
packages/console/src/onboarding/constants/index.ts
packages/console/src/pages/Profile/containers/DeleteAccountModal/index.tsx
packages/console/src/pages/Webhooks/components/CreateFormModal/index.tsx
packages/console/src/pages/Webhooks/index.tsx
packages/shared/src/constants.ts
packages/shared/src/universal.ts

- feat: add webhook creation limit reminder
- refactor: import contact-us email from `@/consts`
Test locally.
OR

feat(console): add webhook creation limit reminder

---

packages/core/src/queries/log.ts
packages/core/src/routes/hook.test.ts
packages/core/src/routes/hook.ts
packages/integration-tests/src/tests/api/hooks.test.ts
packages/schemas/alterations/next-1684739802-create-hook-id-index-for-logs.ts
packages/schemas/tables/logs.sql

- Add `GET /hooks/:id/recent-logs` to fetch recent hook logs
- create index for `payload.hookId` on `logs` table
OR

feat(core,schemas): support get hook recent logs

---

.changeset/perfect-hairs-marry.md
packages/core/src/routes/interaction/actions/submit-interaction.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
packages/integration-tests/src/tests/api/oidc/content-type-json.test.ts

Automatically sync socially verified email and phone for newly registered users.
This PR also refactored some internal methods and refined the variable naming. 
UT case added
Integration test added
OR

refactor(core): sync social email and phone for new registered user

---

packages/schemas/alterations/next-1684382842-add-name-tag-created-at-for-tenants-table.ts
packages/schemas/src/models/tenants.ts
packages/schemas/src/seeds/tenant.ts
packages/schemas/src/types/tenant.ts
packages/schemas/tables/_after_all.sql
packages/schemas/tables/_functions.sql

1. Add `name`, `tag` and `created_at` columns to tenants table.
2. Add `set_tenant_name` function and trigger to automatically set the default value of tenants `name` since column reference is not allowed as PG column default value.
3. Add alteration script to migrate old tenants data to fit new tenants table schema.
Alterations on roles and scopes will come later since they can be decoupled from this change so that we can make each change small and easy to be reviewed.
Tested by seeding a brand new DB and by migrating from an old DB.
OR
Will add changeset once the whole feature is completed. This modification is transparent to current users.

feat(schemas): update tenants table schema

---

packages/console/src/components/RoleUsersTransfer/components/SourceUserItem/index.tsx
packages/console/src/components/RoleUsersTransfer/components/TargetUserItem/index.tsx
packages/console/src/components/Tip/TipBubble/index.module.scss
packages/console/src/components/UserAvatar/index.module.scss
packages/console/src/components/UserAvatar/index.tsx
packages/console/src/components/UserName/index.module.scss
packages/console/src/components/UserName/index.tsx
packages/console/src/pages/AuditLogDetails/index.tsx
packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
packages/console/src/pages/UserDetails/UserRoles/components/AssignRolesModal/index.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/index.tsx
packages/console/src/utils/user.ts

Add user info hover tooltip for audit log details and role assignment user selection panel.

feat(console): add hover tooltip for micro user avatars

---

packages/console/src/containers/ConsoleContent/Sidebar/index.module.scss

Remove top margin from sidebar
Locally tested

style(console): sidebar item should align to top

---

packages/phrases/src/locales/de/errors/hook.ts
packages/phrases/src/locales/en/errors/hook.ts
packages/phrases/src/locales/es/errors/hook.ts
packages/phrases/src/locales/fr/errors/hook.ts
packages/phrases/src/locales/it/errors/hook.ts
packages/phrases/src/locales/ja/errors/hook.ts
packages/phrases/src/locales/ko/errors/hook.ts
packages/phrases/src/locales/pl-pl/errors/hook.ts
packages/phrases/src/locales/pt-br/errors/hook.ts
packages/phrases/src/locales/pt-pt/errors/hook.ts
packages/phrases/src/locales/ru/errors/hook.ts
packages/phrases/src/locales/tr-tr/errors/hook.ts
packages/phrases/src/locales/zh-cn/errors/hook.ts
packages/phrases/src/locales/zh-hk/errors/hook.ts
packages/phrases/src/locales/zh-tw/errors/hook.ts

Add send test payload error phrases
N/A
OR

chore(phrases): add send test payload error phrases

---

packages/core/src/libraries/hook/index.test.ts
packages/core/src/libraries/hook/index.ts
packages/core/src/libraries/hook/utils.test.ts
packages/core/src/libraries/hook/utils.ts
packages/core/src/routes/hook.test.ts
packages/core/src/routes/hook.ts
packages/core/src/tenants/Libraries.ts
packages/integration-tests/src/tests/api/hook/hook.testing.test.ts

- add `POST /hooks/:id/test` to support webhook testing
- move hook lib into the `/libraries/hook` folder and helper functions into a single file.
UT & Test locally & IT
OR

feat(core): test webhook

---

packages/console/src/pages/WebhookDetails/WebhookSettings/components/TestWebhook/index.module.scss
packages/console/src/pages/WebhookDetails/WebhookSettings/components/TestWebhook/index.tsx
packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx

Add test webhook form card on webhook details page to allow testing webhook from the console.
OR

feat(console): test webhook

---

packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
packages/console/src/containers/ConsoleContent/index.tsx

Enable webhook management feature for the console.
OR

feat(console): enable webhook management feature

---

packages/integration-tests/src/tests/api/hook/hook.testing.test.ts

chore(test): clean up created hooks on test done
IT
OR

chore(test): clean up created hooks on test done

---

packages/console/src/pages/WebhookDetails/index.tsx

Replace confirm modal with useConfirmModal hook.
Test locally, and everything works fine.
OR

refactor(console): replace confirm modal with useConfirmModal hook

---

.changeset/famous-tips-search.md
packages/schemas/src/types/system.ts

add cloudflare hostnames configs type definition to "systems".
local tested, use CLI to set configs.
OR

feat(schemas): add cloudflare hostnames configs

---

packages/schemas/alterations/next-1684822341-init-domains.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/tables/domains.sql

Add `domains` table, see [tech design doc](https://www.notion.so/silverhand/Custom-Domain-5d13ab5693304745bf4ac9a47e5dd797) for more info.
Local tested with the alter script.
OR

feat(schemas): add domains table

---

packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx

enforce SSOT for webhook signing key
Test locally.
OR

fix(console): enforce SSOT for webhook signing key

---

packages/core/src/libraries/hook/index.test.ts
packages/core/src/libraries/hook/utils.test.ts
packages/core/src/libraries/hook/utils.ts

Add message id for the webhook payload to allow the user to distinguish whether the message is consumed
Test locally & UT
OR

feat(core): add message id for the webhook payload

---

packages/core/src/database/find-all-entities.ts
packages/core/src/queries/application.ts
packages/core/src/queries/hooks.ts
packages/core/src/queries/resource.ts
packages/core/src/routes/hook.test.ts
packages/core/src/routes/hook.ts
packages/integration-tests/src/tests/api/hook/hook.test.ts

support pagination for `GET /hooks` api
UT & IT & Testlocally
OR

feat(core): support pagination for `GET /hooks` api

---

packages/console/src/pages/Webhooks/index.tsx

Support pagination for webhooks page
Test locally.
OR

feat(console): support pagination for webhooks page

---

packages/cloud/src/libraries/tenants.ts
packages/cloud/src/queries/tenants.ts
packages/cloud/src/routes/tenants.test.ts
packages/cloud/src/routes/tenants.ts
packages/cloud/src/test-utils/libraries.ts
packages/integration-tests/src/api/tenant.ts
packages/integration-tests/src/tests/api-cloud/tenant.test.ts

add PATCH /tenants/:id API
UTs and tested locally, can successfully update tenant info.
Will add changeset once the whole feature is completed. This modification is transparent to current users.
OR

feat(cloud,schemas): add PATCH /tenants/:id API

---

.github/workflows/integration-test.yml
packages/cloud/src/libraries/tenants.ts
packages/cloud/src/queries/tenants.ts
packages/cloud/src/routes/tenants.test.ts
packages/cloud/src/routes/tenants.ts
packages/cloud/src/test-utils/libraries.ts
packages/integration-tests/package.json
packages/integration-tests/src/api/tenant.ts
packages/integration-tests/src/tests/api-cloud/tenant.test.ts
pnpm-lock.yaml

Add DELETE /tenants/:id API and corresponding tests.
UTs, ITs and tested locally.
OR

feat(cloud,test): add DELETE /tenants/:id API

---

packages/integration-tests/src/tests/ui/user-management.test.ts
packages/integration-tests/src/tests/ui/webhooks.test.ts
packages/integration-tests/src/ui-helpers/index.ts

Add UI tests for webhook management
OR

test: add ui tests for webhook management

---

packages/cloud/src/middleware/with-security-headers.ts
packages/console/src/include.d/gtag.d.ts
packages/console/src/onboarding/App.tsx
packages/console/src/onboarding/constants/index.ts
packages/console/src/onboarding/utils.ts

> **Note**
> This PR is based on branch `v1.4.0`.
add google tag script and conversion report

refactor: add google tag conversion report

---

.changeset/pink-eggs-divide.md

add changeset for webhook features
N/A
OR

chore: add changeset for webhook features

---

packages/core/src/utils/cloudflare/index.ts

fix url resolver for cloudflare
Local tested.
OR

fix(core): fix url resolver for cloudflare

---

packages/core/src/libraries/domain.test.ts
packages/core/src/libraries/domain.ts
packages/core/src/routes/domain.test.ts
packages/core/src/routes/domain.ts
packages/core/src/utils/cloudflare/index.ts
packages/phrases/src/locales/de/errors/domain.ts
packages/phrases/src/locales/en/errors/domain.ts
packages/phrases/src/locales/es/errors/domain.ts
packages/phrases/src/locales/fr/errors/domain.ts
packages/phrases/src/locales/it/errors/domain.ts
packages/phrases/src/locales/ja/errors/domain.ts
packages/phrases/src/locales/ko/errors/domain.ts
packages/phrases/src/locales/pl-pl/errors/domain.ts
packages/phrases/src/locales/pt-br/errors/domain.ts
packages/phrases/src/locales/pt-pt/errors/domain.ts
packages/phrases/src/locales/ru/errors/domain.ts
packages/phrases/src/locales/tr-tr/errors/domain.ts
packages/phrases/src/locales/zh-cn/errors/domain.ts
packages/phrases/src/locales/zh-hk/errors/domain.ts
packages/phrases/src/locales/zh-tw/errors/domain.ts

Delete cloudflare custom domain before deleting the record in database.
Local tested
OR

fix(core): delete cloudflare custom domain

---

packages/core/src/libraries/hook/index.test.ts
packages/core/src/libraries/hook/index.ts

rename log payload field `json` -> `hookRequest.body` to reduce confusion
/

refactor(core): refine webhook log payload

---

.changeset/pink-eggs-divide.md
packages/core/src/libraries/hook/utils.test.ts
packages/core/src/libraries/hook/utils.ts

Remove message id from hook request headers since it doesn't have a clear use case, and the specific usage is currently undetermined.
https://github.com/logto-io/docs/pull/451
UT & Test with webhook Saas service.
OR

refactor(core): remove message id from hook request headers

---

packages/console/src/components/Uploader/ImageUploader/index.module.scss
packages/console/src/components/Uploader/ImageUploader/index.tsx

fix fallback image in image uploader
OR

fix(console): fix fallback image in image uploader 

---

packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/AddDomainForm/index.module.scss
packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/AddDomainForm/index.tsx
packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/index.module.scss
packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/index.tsx

feat(console): add custom domain form
OR

feat(console): add custom domain form

---

packages/app-insights/src/node.ts

mutating error message will break the api response, this PR ensures to create a new error before nomarlizing
api returns the correct error message

fix: clone error for AppInsights

---

packages/console/src/contexts/AppConfirmModalProvider/index.tsx
packages/console/src/pages/WebhookDetails/index.tsx

Close confirm modal on the location path changed
Test locally.
OR

fix(console): close confirm modal on the location path changed

---

.github/workflows/release.yml

fix the wrong condition test, should be triggered on manually dispatch
see the deployment record in this pr

ci: fix deploy workflow

---

packages/cli/src/commands/translate/openai.ts
packages/cli/src/commands/translate/prompts.ts

Polish translate prompts for OpenAI.
Local tested.
OR

fix(cli): polish translate prompts

---

packages/phrases/src/locales/de/translation/admin-console/domain.ts
packages/phrases/src/locales/en/translation/admin-console/domain.ts
packages/phrases/src/locales/es/translation/admin-console/domain.ts
packages/phrases/src/locales/fr/translation/admin-console/domain.ts
packages/phrases/src/locales/it/translation/admin-console/domain.ts
packages/phrases/src/locales/ja/translation/admin-console/domain.ts
packages/phrases/src/locales/ko/translation/admin-console/domain.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
packages/phrases/src/locales/ru/translation/admin-console/domain.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts

refactor(phrases): update custom domain notice phrases
N / A
OR

refactor(phrases): update custom domain notice phrases

---

packages/core/src/__mocks__/domain.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/types/domain.ts
packages/schemas/tables/domains.sql

Set domain status enum guard
Covered by existing tests.
OR

fix(schemas): set domain status enum guard

---

packages/cloud/src/routes/tenants.test.ts
packages/cloud/src/routes/tenants.ts
packages/integration-tests/src/tests/api-cloud/tenant.test.ts

fix delete tenant API:
should not delete built-in tenants (admin tenant and default tenant).
UTs and ITs.
OR

fix(cloud): delete tenant api

---

packages/ui/src/components/LogtoSignature/index.tsx

add utm params for better traffic recognization
plausible

refactor(ui): add utm params to powered by link

---

packages/console/src/components/InlineNotification/index.module.scss
packages/console/src/consts/custom-domain.ts
packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/index.module.scss
packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/index.tsx
packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx

Add activation error for custom domain
OR

feat(console): add activation error for custom domain

---

packages/console/src/components/InlineNotification/index.tsx
packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.module.scss
packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.tsx

feat(console): add update domain alert on custom domain activated
OR

feat(console): add update endpoint notice for custom domain

---

.github/CODEOWNERS

adjust the code-owner of major packages
OR

chore: adjust the code-owner of major packages

---

packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/pages/TenantSettings/index.tsx

Enable custom domain feature
Test locally.
OR

feat(console): enable custom domain feature

---

packages/console/package.json
packages/console/src/components/EmptyDataPlaceholder/index.tsx
packages/console/src/components/IconButton/index.tsx
packages/console/src/components/MultiTextInput/utils.ts
packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.tsx
packages/console/src/components/Uploader/index.tsx
packages/console/src/components/VerificationCodeInput/index.tsx
packages/console/src/contexts/AppConfirmModalProvider/index.tsx
packages/console/src/contexts/AppEndpointsProvider.tsx
packages/console/src/contexts/TenantsProvider.tsx
packages/console/src/hooks/use-confirm-modal.ts
packages/console/src/hooks/use-user-preferences.ts
packages/console/src/onboarding/constants/index.ts
packages/console/src/onboarding/pages/SignInExperience/index.tsx
packages/console/src/onboarding/types.ts
packages/console/src/pages/Connectors/components/ConnectorForm/hooks.tsx
packages/console/src/pages/Dashboard/types.ts
packages/console/src/pages/Profile/components/CardContent/index.tsx
packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
packages/console/src/pages/SignInExperience/tabs/Branding/BrandingForm.tsx
packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/use-language-editor-context.ts
packages/console/src/pages/Webhooks/components/BasicWebhookForm/index.tsx
packages/ui/src/containers/TermsAndPrivacy/TermsAndPrivacyConfirmModalContent/index.tsx

refactor(console): apply no-unused-modules

---

packages/console/src/components/RadioGroup/Radio.module.scss
packages/console/src/components/RadioGroup/Radio.tsx
packages/console/src/components/RadioGroup/index.module.scss
packages/console/src/components/RadioGroup/index.tsx
packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/contexts/TenantsProvider.tsx
packages/console/src/hooks/use-tenants.ts
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.module.scss
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/index.module.scss
packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/types.ts
packages/console/src/pages/TenantSettings/index.module.scss
packages/console/src/pages/TenantSettings/index.tsx

Add tenant settings page.
Tested locally, can correctly display and edit current tenant profile.
OR

feat(console): add tenant settings page

---

packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx

add appInsights for custom domain page
N/A
OR

chore(console): add appInsights for custom domain page

---

packages/console/src/components/ModalLayout/index.module.scss
packages/console/src/components/ModalLayout/index.tsx

Enable icon in modal header.
Tested locally with icon.
OR

feat(console): enable icon in modal header

---

packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.module.scss
packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.tsx

Update change custom domain notice
OR

refactor(console): update change custom domain notice

---

packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx

Remove redundant useSWR params from custom domain request since the `fetcher` is not needed.
Test locally.
OR

chore(console): remove redundant useSWR params from custom domain request

---

packages/console/src/containers/AppContent/components/Topbar/TenantSelector/components/TenantEnvTag/index.module.scss
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/components/TenantEnvTag/index.tsx
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.module.scss
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
packages/console/src/containers/AppContent/components/Topbar/index.tsx
packages/toolkit/core-kit/scss/_console-themes.scss

Add tenant list dropdown and can successfully switch between authenticated users' available tenants.
https://github.com/logto-io/logto/assets/15182327/97153165-de38-4b3b-822e-5111d6c55cb6
OR

feat(console): add tenant list dropdown

---

packages/ui/src/apis/utils.ts
packages/ui/src/containers/ForgotPasswordLink/index.tsx
packages/ui/src/containers/VerificationCode/PasswordSignInLink.tsx
packages/ui/src/containers/VerificationCode/index.test.tsx
packages/ui/src/containers/VerificationCode/index.tsx
packages/ui/src/containers/VerificationCode/use-continue-flow-code-verification.ts
packages/ui/src/containers/VerificationCode/use-forgot-password-flow-code-verification.ts
packages/ui/src/containers/VerificationCode/utils.ts
packages/ui/src/hooks/use-required-profile-error-handler.ts
packages/ui/src/hooks/use-social-landing-handler.ts
packages/ui/src/pages/Continue/SetEmailOrPhone/index.test.tsx
packages/ui/src/pages/Continue/SetEmailOrPhone/index.tsx
packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/ui/src/pages/Register/IdentifierRegisterForm/index.test.tsx
packages/ui/src/pages/Register/IdentifierRegisterForm/use-on-submit.ts
packages/ui/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
packages/ui/src/pages/SignIn/IdentifierSignInForm/use-on-submit.ts
packages/ui/src/pages/SignInPassword/PasswordForm/VerificationCodeLink.tsx
packages/ui/src/pages/SignInPassword/PasswordForm/index.test.tsx
packages/ui/src/pages/SocialLanding/index.test.tsx
packages/ui/src/pages/VerificationCode/index.tsx
packages/ui/src/types/guard.ts
packages/ui/src/types/index.ts
packages/ui/src/utils/social-connectors.test.ts
packages/ui/src/utils/social-connectors.ts

align enum key Pascal case
covered by CI
OR

refactor(ui): align enum key pascal case

---

packages/schemas/alterations/next-1685691718-domain-unique.ts
packages/schemas/tables/domains.sql

Per discussion, modify domain table unique index to `(tenant_id, domain)`
Local tested
OR

fix(schemas): modify domain table unique index

---

packages/console/src/pages/SignInExperience/utils/form.ts

Bug:
When updating SIE data, some fields are deleted, which causes React Hook Form to skip updating these deleted fields when updating the form with the latest data. As a result, these fields retain their previous values.
Therefore, we need to ensure that the local form includes all fields to ensure consistency between the form and the data content.
Test locally.
OR

fix(console): ensure optional fields exist in the sie form data

---

packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/android_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/go.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/go_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/next.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/next_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
packages/console/src/pages/Applications/components/Guide/index.tsx

add alternative endpoint for application get started guide
OR

feat(console): add alternative endpoint for application get started guide

---

.github/workflows/repository-dispatch.yml

Add repository event dispatch job on logto master push
test the job locally
OR

chore: add repository event dispatch job on logto master push

---

packages/phrases-ui/package.json
packages/phrases/package.json
packages/schemas/package.json

make zod peer dependency in common packages to avoid version conflict in the cloud repo
tested in cloud, can successfully build

chore(schemas,phrases): make zod peer dependency

---

packages/cloud/src/routes/tenants.test.ts
packages/cloud/src/routes/tenants.ts
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.module.scss
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
packages/integration-tests/src/tests/api-cloud/tenant.test.ts

Should block normal cloud users from creating more than 3 tenants.
UTs and ITs.
OR

fix(cloud,test): should block when users trying to create too many tenants

---

packages/core/src/libraries/domain.test.ts
packages/core/src/libraries/domain.ts
packages/core/src/utils/tenant.ts

Update domain redis cache:
1. no longer cache empty result
2. adjust cache ttl
3. clear cache when domain updates
Local tested, and UTs
OR

fix(core): update domain cache

---

packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/CreateTenantModal/index.tsx
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
packages/integration-tests/src/tests/ui-cloud/smoke.test.ts

direct to new created tenant and clear create modal on open.
UTs and ITs.
OR

fix(console): direct to new created tenant and clear create modal on open

---

packages/console/src/ds-components/Table/index.tsx
packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/DnsRecordsTable/index.module.scss
packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/DnsRecordsTable/index.tsx

The prop name in the Table is inaccurate.
```ts
type Props = {
headerClassName?: string;
bodyClassName?: string;
}
```
should be:
```ts
type Props = {
headerTableClassName?: string;
bodyTableWrapperClassName?: string;
}
```
OR

refactor(console): rename props name for table component

---

packages/console/src/assets/images/tenant-landing-page.svg

update tenant landing page LM image
N/A
OR

chore(console): update tenant landing page LM image

---

.github/CODEOWNERS

add cloud related code owner
OR

ci: add cloud related code owner

---

packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.tsx
packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx

feat(console): add custom domain related links
Test locally.
OR

feat(console): add custom domain related links

---

packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx

fix(console): correct domain settings page meta
OR

fix(console): correct domain settings page meta

---

packages/console/src/cloud/pages/Main/TenantLandingPage/index.module.scss
packages/console/src/cloud/pages/Main/TenantLandingPage/index.tsx

fix landing page placeholder CSS.
change z-index of topbar could cover part of dropdown modal so that the mouse click event on "topbar" area have no effect on dropdown.
OR

fix(console): landing page placeholder css

---

packages/console/src/onboarding/constants/index.ts

update conversion id since we've changed an account
after deployment

chore: update conversion id

---

packages/console/package.json
packages/console/src/App.tsx
packages/demo-app/package.json
pnpm-lock.yaml

upgrade SDK, reduce OIDC requests
tested locally, cache worked for OIDC config and JWKs

chore(deps): upgrade Logto React SDK

---

packages/console/src/pages/Connectors/index.tsx

Reorder passwordless connectors in the list, email connectors should come first.
OR

refactor(console): reorder passwordless connectors in the list

---

.changeset/flat-rice-rhyme.md
packages/console/src/containers/AppContent/index.module.scss
packages/toolkit/core-kit/scss/_console-themes.scss
packages/toolkit/core-kit/scss/_fonts.scss

Add new font tokens in Logto core-kit.
- font-display-1
- font-display-2
- font-display-3
- font-body-0
Also clean up some code lines related to core-kit usage
N/A

feat(toolkit): add new font tokens in core-kit

---

packages/console/src/pages/Connectors/CreateForm/index.tsx

set passwordless connector creation modal to large by default
OR

style(console): set passwordless connector creation modal to large by default

---

packages/toolkit/connector-kit/src/types.ts

add email service branding config guard.
N/A
OR

chore(toolkit): add email service branding config guard

---

packages/core/src/tenants/SystemContext.ts
packages/schemas/src/types/connector.ts
packages/schemas/src/types/system.ts
packages/toolkit/connector-kit/src/types.ts

1. add email service guard and system key.
2. can customize email/sms content's `fromName`, `companyAddress` and `appLogo`.
3. add `extraInfo` field to connector GET APIs' response.
N/A
OR

feat(schemas): add email service guard and system key

---

packages/console/src/containers/ErrorBoundary/index.tsx
packages/console/src/pages/Callback/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
packages/console/src/utils/url.ts
packages/integration-tests/src/tests/ui-cloud/operations.ts
packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
packages/integration-tests/tsconfig.json

Fix multi-tenancy flow:
1. should trigger redirect after deleting the current tenant.
2. console content already has tenant id in its path base name.
Sync cloud UI test from the `cloud` repo.
OR

fix(console): fix multi tenancy flow and sync ui-test

---

packages/schemas/src/types/system.ts

update email service config systems table key.
systems table key should be camel case not pascal case.
N/A
OR

fix(schemas): update email service config systems table key

---

packages/cloud/src/libraries/tenants.ts
packages/toolkit/connector-kit/src/types.ts

remove `demo` tag from logto email connector (1/2).
The following step includes:
replace DemoConnector.Email to ServiceConnector.Email in cloud
N/A
OR

chore(toolkit,core): remove demo tag from logto email connector (1/2)

---

packages/connectors/connector-logto-email/src/constant.ts
packages/connectors/connector-logto-email/src/index.ts
packages/connectors/connector-logto-email/src/types.ts
packages/toolkit/connector-kit/src/types.ts

Update logto email connector:
1. add `getUsage` method
2. enable branding configuration
Tested locally, can successfully send/receive email.
OR

feat(connector): update logto email connector

---

packages/connectors/connector-logto-email/src/constant.ts
packages/console/src/components/ConnectorTester/index.tsx
packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.module.scss
packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.tsx
packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx

Since the custom connector config form does not support i18n, we implement an `EmailServiceConnectorForm` for our built-in services.
We will support i18n for custom connector form configs in an independent project.
OR

feat(console): implement email service connector details page

---

packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
packages/console/src/pages/Connectors/Guide/index.tsx
packages/console/src/types/connector.ts
packages/console/src/utils/connector-form.ts

Refactor custom connector form initialization
- Improve `ConnectorFormType` to fit the connector type correctly.
- Extract response data parsing logic into helper methods.
- Simplify `formConfig` setup logic.
Test locally.
OR

refactor(console): refactor custom connector form initialization

---

packages/console/src/assets/icons/email-sent.svg
packages/console/src/pages/ConnectorDetails/EmailUsage/index.module.scss
packages/console/src/pages/ConnectorDetails/EmailUsage/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx

feat(console): add usage info for the email service connector

---

packages/console/src/pages/ConnectorDetails/index.tsx

Hide the 'check readme' button for the email service connector since it's provided by Logto and no setup guide is needed.
Test locally.
OR

feat(console): hide the check readme button for the email service connector

---

packages/core/src/utils/connectors/index.ts

Enable email service connector
@darcyYe 
OR

feat(core): enable email service connector

---

packages/schemas/alterations/next-1688613459-remove-m2m-credentials-from-existing-logto-email-connector-config.ts

drop m2m credentials in existing logto email connector config.
test by db-alteration CI.
OR

feat(schemas): drop m2m credentials in existing logto email connector config

---

packages/console/src/consts/env.ts
packages/console/src/consts/page-tabs.ts
packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/pages/TenantSettings/Subscription/index.tsx
packages/console/src/pages/TenantSettings/index.tsx

feat(console): add subscription page
OR

feat(console): add subscription page

---

.changeset/chatty-spoons-joke.md
packages/core/src/database/insert-into.ts
packages/core/src/event-listeners/access-token.test.ts
packages/core/src/event-listeners/access-token.ts
packages/core/src/event-listeners/index.test.ts
packages/core/src/event-listeners/index.ts
packages/core/src/oidc/init.ts
packages/core/src/oidc/utils.ts
packages/core/src/queries/daily-active-user.ts
packages/core/src/tenants/Queries.ts
packages/schemas/alterations/next-1688627407-daily-active-users.ts
packages/schemas/tables/daily_active_users.sql
packages/shared/src/database/sql.ts

Create table "daily_active_users" and insert records when users exchange access token.
Local tested.
OR

feat(core,schemas): record daily active users

---

packages/core/package.json
packages/core/src/__mocks__/cloud-connection.ts
packages/core/src/libraries/cloud-connection.test.ts
packages/core/src/libraries/cloud-connection.ts
packages/core/src/libraries/connector.test.ts
packages/core/src/libraries/connector.ts
packages/core/src/libraries/sign-in-experience/index.test.ts
packages/core/src/utils/json.ts
pnpm-lock.yaml

Add a `withtyped` client for Cloud service, will be used for getting subscription info.
Local tested.
OR

feat(core): add cloud client

---

packages/console/src/containers/ConsoleContent/index.tsx

The subscription entry is blocked on the tenant settings page, but we also need to block the page route in case users visit this page accidentally.
Test locally.
OR

chore(console): block subscritpion route

---

.scripts/compare-database.js

make compare script universal by comparing both `cloud` and `public` schemas in the database. thus the script can be reused in cloud.
CI

ci: compare multiple schemas including cloud

---

packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx

Should reset connector form with updated data.
Test locally.
OR

fix(console): reset connector form with updated data

---

packages/core/src/libraries/cloud-connection.ts
packages/core/src/libraries/connector.ts

The previous implementation can not get the value of `cloudConnection` key properly.
Tested locally. Can get the value of `cloudConnection`.
OR

fix(core): fix the argument type of createConnectorLibrary

---

packages/schemas/src/seeds/cloud-api.ts

add `manage:affiliate` cloud scope for viewing and managing affiliates
in cloud https://github.com/logto-io/cloud/pull/121

refactor(schemas): add manage affiliate scope

---

packages/schemas/src/seeds/cloud-api.ts

add a new scope for logto core to report affiliate data
in https://github.com/logto-io/cloud/pull/135

refactor(schemas): add create affiliate scope

---

packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts

chore(phrases): update subscription phrases
None.
OR

chore(phrases): update subscription phrases

---

packages/console/src/components/FormCard/index.module.scss
packages/console/src/components/FormCard/index.tsx
packages/console/src/components/ProTag/index.module.scss
packages/console/src/components/ProTag/index.tsx
packages/console/src/hooks/use-current-subscription-plan.ts
packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx
packages/console/src/pages/TenantSettings/TenantDomainSettings/index.module.scss
packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx

Add quota limit for custom domain
OR

feat(console): apply quota limit for custom domain

---

packages/console/src/components/CreateConnectorForm/Footer/index.tsx
packages/console/src/components/CreateConnectorForm/index.tsx

Apply quota limit for connector creation
OR

feat(console): apply quota limit for connector creation

---

packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx

Apply quota limit for resource and scope creation
OR

feat(console): apply quota limit for resource and scope creation

---

packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx

Apply subscription cost for current plan info
OR

feat(console): apply subscription cost for current plan info

---

packages/console/src/components/CreateConnectorForm/Footer/index.tsx
packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
packages/console/src/pages/RoleDetails/RolePermissions/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
packages/console/src/pages/Roles/index.tsx
packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx
packages/console/src/utils/quota.ts

Apply quota limit for roles
OR

feat(console): apply quota limit for roles

---

packages/core/src/libraries/quota.test.ts
packages/core/src/libraries/quota.ts
packages/core/src/queries/application.ts
packages/core/src/queries/roles-scopes.ts
packages/core/src/queries/roles.ts
packages/core/src/queries/scope.ts
packages/core/src/routes/connector/factory.ts
packages/core/src/routes/connector/index.post.test.ts
packages/core/src/routes/connector/index.ts
packages/core/src/routes/domain.test.ts
packages/core/src/routes/domain.ts
packages/core/src/routes/hook.test.ts
packages/core/src/routes/hook.ts
packages/core/src/routes/resource.ts
packages/core/src/routes/role.scope.test.ts
packages/core/src/routes/role.scope.ts
packages/core/src/routes/role.test.ts
packages/core/src/routes/role.ts
packages/core/src/tenants/Libraries.ts
packages/core/src/test-utils/connectors.ts
packages/core/src/utils/subscription/types.ts

Implement every quota limit guard. (hard limit)
Sorry for the large PR, guards are in many different routes.
Local tested
Just like other middlewares, it is not easy to test in every routes. So the unit tests for routers won't cover this.
There are unit tests for `quotaLibrary`.

feat(core): apply all quota guard

---

packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
packages/phrases/src/locales/de/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/en/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/en/translation/admin-console/tabs.ts
packages/phrases/src/locales/es/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/fr/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/it/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/ja/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/ko/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/pt-pt/errors/subscription.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/ru/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tab-sections.ts

chore(phrases): update content to sentence case

---

packages/schemas/package.json
pnpm-lock.yaml

chore(schemas): bump withTyped version

---

packages/console/src/cloud/types/router.ts
packages/console/src/consts/page-tabs.ts
packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/hooks/use-invoices.ts
packages/console/src/pages/TenantSettings/BillingHistory/InvoiceStatusTag/index.tsx
packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/PlanUsage/index.tsx
packages/console/src/pages/TenantSettings/index.tsx
packages/console/src/types/subscriptions.ts
packages/console/src/utils/subscription.ts
packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts

feat(console): add billing history page
- Extract `formatPeriod` into a util method
OR

feat(console): add billing history page

---

packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/Skeleton/index.module.scss
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/Skeleton/index.tsx
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/TenantStatusTag.tsx
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.module.scss
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.module.scss
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
packages/console/src/types/subscriptions.ts
packages/console/src/utils/subscription.ts

Add subscription info for tenant selector
OR

feat(console): add subscription info for tenant selector

---

packages/console/src/pages/TenantSettings/Subscription/NotEligibleDowngradeModalContent/index.tsx

Add contact us help tip for downgrade modal
Test locally.
OR

feat(console): add contact us help tip for downgrade modal

---

packages/core/src/middleware/koa-slonik-error-handler.ts
packages/core/src/oidc/init.ts
packages/integration-tests/src/tests/api/admin-user.test.ts
packages/integration-tests/src/tests/api/interaction/error-handling.test.ts
packages/phrases/src/locales/de/errors/entity.ts
packages/phrases/src/locales/en/errors/entity.ts
packages/phrases/src/locales/es/errors/entity.ts
packages/phrases/src/locales/fr/errors/entity.ts
packages/phrases/src/locales/it/errors/entity.ts
packages/phrases/src/locales/ja/errors/entity.ts
packages/phrases/src/locales/ko/errors/entity.ts
packages/phrases/src/locales/pl-pl/errors/entity.ts
packages/phrases/src/locales/pt-br/errors/entity.ts
packages/phrases/src/locales/pt-pt/errors/entity.ts
packages/phrases/src/locales/ru/errors/entity.ts
packages/phrases/src/locales/tr-tr/errors/entity.ts
packages/phrases/src/locales/zh-cn/errors/entity.ts
packages/phrases/src/locales/zh-hk/errors/entity.ts
packages/phrases/src/locales/zh-tw/errors/entity.ts

- handle findAccount error when user is deleted after the token is issued
- recognize slonik invalid input error
local tested, all handled as expected instead of 500

refactor(core): improve error handling

---

packages/console/src/cloud/AppRoutes.tsx
packages/console/src/containers/TenantAccess/index.tsx
packages/console/src/contexts/TenantsProvider.tsx
packages/console/src/onboarding/pages/Congrats/index.tsx
packages/console/src/pages/Callback/index.tsx
packages/console/src/pages/ConsoleRoutes/index.tsx

- fix callback and cloud routes by explicitly specifying anonymous routes
- check if the current route is in the anonymous path before extracting current tenant id from the pathname

fix(console): adapt callback and current tenant id logic

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
packages/console/src/hooks/use-invoices.ts
packages/console/src/hooks/use-subscription-plans.ts
packages/console/src/hooks/use-subscription-usage.ts
packages/console/src/hooks/use-subscription.ts
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx

Currently, we are implementing error handling and displaying it through toasts at each cloud API request.
This is a temporary solution, and eventually, this generic process will be improved when custom error handling is supported in the 'withtyped' client.
In order not to hinder the testing of the pricing feature, these handling processes should be merged.
Test locally.
OR

feat(console): handle subscription related request errors

---

packages/console/src/cloud/hooks/use-cloud-api.ts
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
packages/console/src/components/CreateTenantModal/index.tsx
packages/console/src/hooks/use-invoices.ts
packages/console/src/hooks/use-subscribe.ts
packages/console/src/hooks/use-subscription-plans.ts
packages/console/src/hooks/use-subscription-usage.ts
packages/console/src/hooks/use-subscription.ts
packages/console/src/pages/CheckoutSuccessCallback/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx

Currently the `withtyped` has supported custom error handling hooks, so we now improve the error handling logic by leveraging the `withtyped`'s new feature.
- Support toast error on cloud API requests failed.
Test locally.
OR

refactor(console): improve error handling for cloud api request

---

packages/console/package.json
packages/console/src/components/BillInfo/index.tsx
packages/console/src/components/PaymentOverdueModal/index.tsx
packages/console/src/hooks/use-subscribe.ts
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/PaymentOverdueNotification/index.tsx
pnpm-lock.yaml

Support open stripe payment management page from console
Test locally.
OR

feat(console): support open stripe payment management page from console

---

packages/console/src/components/CreateConnectorForm/index.tsx
packages/console/src/components/CreateTenantModal/index.tsx
packages/console/src/consts/env.ts
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
packages/console/src/containers/AppContent/index.tsx
packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/hooks/use-invoices.ts
packages/console/src/hooks/use-subscription-plans.ts
packages/console/src/hooks/use-subscription-usage.ts
packages/console/src/hooks/use-subscription.ts
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.tsx
packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/ConsoleRoutes/index.tsx
packages/console/src/pages/GetStarted/FreePlanNotification/index.tsx
packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
packages/console/src/pages/TenantSettings/index.tsx
packages/console/src/utils/quota.ts

chore(console): remove pricing feature switch
Test locally.
OR

chore(console): remove pricing feature switch

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.tsx

style(console): fix mau unit price style
Before:
After:
OR

style(console): fix mau unit price style

---

packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.module.scss

style(console): update quota table border radius to 16px
Test locally.
OR

style(console): update quota table border radius to 16px

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.module.scss
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx

feat(console): add most popular tag for pro plan item
OR

feat(console): add most popular tag for pro plan item

---

packages/console/src/components/BillInfo/index.tsx
packages/console/src/components/PaymentOverdueModal/index.tsx
packages/console/src/ds-components/Button/index.tsx
packages/console/src/ds-components/InlineNotification/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/PaymentOverdueNotification/index.tsx
packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx

feat(console): add loading state for stripe actions
Test locally.
OR

feat(console): add loading state for stripe actions

---

packages/phrases/src/locales/de/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/es/translation/admin-console/cloud.ts
packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
packages/phrases/src/locales/it/translation/admin-console/cloud.ts
packages/phrases/src/locales/ja/translation/admin-console/cloud.ts
packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
packages/phrases/src/locales/ru/translation/admin-console/cloud.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/cloud.ts

Update onboarding contents.
These changes are missed in [PR](https://github.com/logto-io/logto/pull/4214).
N/A
OR

chore(phrases): update onboarding contents

---

packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx

fix(console): reset loading state on plan downgraded
Test locally.
OR

fix(console): reset loading state on plan downgraded

---

packages/console/src/components/CreateConnectorForm/index.tsx
packages/console/src/components/ProTag/index.module.scss
packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx

refactor(console): hide pro tag when related features are available
Test locally.
OR

refactor(console): hide pro tag when related features are available

---

packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx

style(console): use large size for the webhook creation modal
Test locally.
OR

style(console): use large size for the webhook creation modal

---

packages/core/src/libraries/quota.ts

Remove pricing feature switch, ready to deploy to dev.
N/A

chore(core): remove pricing feature switch

---

packages/console/src/App.tsx
packages/console/src/components/ConnectorForm/ConfigForm/index.tsx
packages/console/src/components/LivePreviewButton/index.tsx
packages/console/src/components/SignInExperiencePreview/index.tsx
packages/console/src/contexts/AppDataProvider.tsx
packages/console/src/hooks/use-api.ts
packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
packages/console/src/pages/Applications/components/Guide/index.tsx
packages/console/src/pages/GetStarted/hook.ts
packages/console/src/pages/TenantSettings/TenantDomainSettings/DefaultDomain/index.tsx

rename userEndpoint -> tenantEndpoint, to make it more clear
CI

refactor(console): userEndpoint -> tenantEndpoint

---

packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts

refactor(phrases): update hook phrases to webhook
Test locally.
OR

refactor(phrases): update hook phrases to webhook

---

packages/console/package.json
packages/console/src/components/CreateConnectorForm/Footer/index.tsx
packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx
pnpm-lock.yaml

Bump `@logto/cloud` version
Test locally.
OR

chore(console): bump `@logto/cloud` version

---

packages/console/src/components/ItemPreview/index.tsx
packages/console/src/pages/TenantSettings/BillingHistory/index.tsx

Make billing history item clickable
OR

feat(console): make billing history item clickable

---

packages/console/src/components/CreateTenantModal/index.tsx

should reset the form every time we close CreateTenantModal.
Tested locally, work as expectation.
OR

fix(console): should reset the form every time close CreateTenantModal

---

.changeset/allow-editing-refresh-token-ttl.md
packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx

Allow editing refresh token TTL for non-M2M applications. Should improve [JS#527](https://github.com/logto-io/js/issues/527)
Locally tested using SPA type application

refactor(console): allow editing refresh token ttl for non-m2m apps

---

packages/core/src/libraries/quota.ts

When counting usage for quota limit, demo connectors should be excluded.
Local tested.

fix(core): exclude demo connector for quota

---

packages/console/src/components/PlanQuotaList/index.tsx
packages/console/src/consts/plan-quotas.ts
packages/console/src/hooks/use-subscription-plans.ts
packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
packages/console/src/utils/sort.ts

Sort quota list items based on the pricing list.
Test locally.
OR

refactor(console): sort quota list items

---

packages/connectors/connector-smsaero/CHANGELOG.md

Manually add a changelog file for smsaero connector since our changeset publish workflow throws an error, mentioning that can not find the CHANGELOG.md file of smsaero connector.
See [details](https://github.com/logto-io/logto/actions/runs/5664397696/job/15347593573).
WIP:
The workflow/script works fine on the local machine, checking whether we should explicitly add some config.
N/A
OR

fix(connector): manually add a changelog file for smsaero connector

---

packages/integration-tests/src/tests/ui/bootstrap.test.ts
packages/integration-tests/src/tests/ui/user-management.test.ts
packages/integration-tests/src/tests/ui/webhooks.test.ts
packages/integration-tests/src/ui-helpers/index.ts
packages/integration-tests/src/utils.ts

use the implementation in the [official docs](https://pptr.dev/api/puppeteer.page.waitfornavigation#example) to avoid random timeout in integration tests
CI

refactor(test): add `expectNavigation()`

---

packages/console/jest.setup.ts
packages/console/src/components/ReportConversion/index.tsx
packages/console/src/components/ReportConversion/utils.test.ts
packages/console/src/components/ReportConversion/utils.ts
packages/console/src/include.d/tags.d.ts

- report sign-up conversion to reddit
- make sure to hash email before sending data
locally tested, can see event in the Events Manager

refactor(console): report reddit conversion

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.module.scss
packages/console/src/components/ProTag/index.module.scss
packages/toolkit/core-kit/scss/_console-themes.scss

Now we have a specific color token for upsell tags, so we add and use it for our upsell tags.
Test locally.
OR

style(console): add color token for upsell tags

---

.github/workflows/pen-tests.yml
.zap/rules.conf
.zap/rules.tsv

disable cloud metadata rule in zap
OR

ci(core): disable cloud metadata rule in zap

---

packages/console/src/components/PlanUsage/index.tsx

Prepend space for plan usage percentage
Test locally.
OR

style(console): prepend space for plan usage percentage

---

packages/connectors/connector-mailgun/README.md
packages/connectors/connector-mailgun/src/constant.ts
packages/connectors/connector-mailgun/src/index.test.ts
packages/connectors/connector-mailgun/src/index.ts
packages/connectors/connector-mailgun/src/type.test.ts
packages/connectors/connector-mailgun/src/types.ts

support mailgun endpoint config for eu service
- locally changes the mailgun endpoint, resulted in different requests
- added unit tests

refactor(connector): support mailgun endpoint

---

packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx

Add learn more link for webhook settings description
OR

feat(console): add learn more link for webhook settings description

---

packages/phrases/src/locales/de/translation/admin-console/application-details.ts
packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/es/translation/admin-console/application-details.ts
packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
packages/phrases/src/locales/it/translation/admin-console/application-details.ts
packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
packages/phrases/src/locales/ko/errors/domain.ts
packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts

`pnpm cli translate sk --target all`
CI

chore(phrases): remove unused keys

---

packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/Skeleton/index.module.scss
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/Skeleton/index.tsx
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/TenantStatusTag.tsx
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.module.scss
packages/console/src/containers/AppContent/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx

Per disscussion, we don't display loading skeleton in the tenant selector dropdown since it's ugly.
OR

refactor(console): improve tenant selector loading state

---

packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx

Previously we will show loading status on all the subscription button when a subscription plan is selected, now we only show loading status on selected subscription button.
Before:
After:
OR

refactor(console): only show loading status on selected subscription button

---

packages/schemas/alterations/next-1691979708-add-is-suspend-column-to-tenants-table.ts
packages/schemas/src/models/tenants.ts

add isSuspended columns to support the future feature of the suspension of a given tenant. 
test locally
OR

feat(schemas): add isSuspended columns

---

packages/schemas/package.json
packages/schemas/src/models/tenants.ts
pnpm-lock.yaml

Expose the isSuspended to the TenenatInfo type and guard.
Bump the withTyped version to fix the  boolean typed data field parse to zod type return never bug. 
test locally
OR

refactor(schemas): add isSuspended to the tenantInfo type

---

packages/console/src/utils/connector-form.ts
packages/integration-tests/src/tests/ui/connectors/social-connector-test-cases.ts
packages/integration-tests/src/tests/ui/connectors/social-connectors.test.ts
packages/integration-tests/src/ui-helpers/index.ts

Add ui tests for social connectors:
- Creation
- Data update
- Deletion
- Fix: should display correct target on standard connector details form
IT
OR

test: add ui tests for social connectors

---

packages/integration-tests/src/tests/ui/rbac.test.ts

test: add ui tests for RBAC operations
IT
OR

test: add ui tests for RBAC operations

---

packages/integration-tests/src/tests/ui/sign-in-experience.test.ts

test: add ui tests for sie branding config
OR

test: add ui tests for sie branding config

---

packages/console/src/consts/env.ts
packages/console/src/pages/Applications/components/Guide/GuideModal.tsx

Enable guide v2 in production env (e.g. cloud)
N/A. Check it after deployed to cloud

chore(console): enable guide v2 in production env

---

packages/console/src/assets/docs/guides/web-gpt-plugin/components/ClientBasics/index.tsx
packages/console/src/assets/docs/guides/web-python/README.mdx
packages/console/src/assets/docs/guides/web-python/index.ts
packages/console/src/pages/Applications/components/GuideV2/index.module.scss
packages/console/src/pages/Applications/components/GuideV2/index.tsx

add tutorial from https://github.com/logto-io/python
looks good

feat(console): python guide

---

packages/core/package.json
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/schemas/alterations/next-1691913875-add-affiliate-scopes.ts
packages/schemas/alterations/next-1692194751-add-affiliate-scopes.ts
packages/schemas/src/seeds/cloud-api.ts
pnpm-lock.yaml

Read data from cookie and post to cloud when needed. This should only happen in Cloud and admin tenant.
tested locally via the following steps:
1. trigger the main flow for the admin tenant
2. manually set affiliate cookie
3. complete sign-up, see if data was successfully posted
integration tests will be added in the cloud repo once this is merged

feat: post affiliate data to cloud

---

packages/console/src/pages/Applications/components/GuideV2/index.tsx

the button didn't add the `onClick` handler - didn't working. this pr fixes it.
local tested

fix(console): add onClick handler to guide done button

---

packages/console/src/assets/docs/guides/native-android-java/README.mdx
packages/console/src/assets/docs/guides/native-android-kt/README.mdx
packages/console/src/assets/docs/guides/native-ios-swift/README.mdx
packages/console/src/assets/docs/guides/spa-react/README.mdx
packages/console/src/assets/docs/guides/spa-vanilla/README.mdx
packages/console/src/assets/docs/guides/spa-vue/README.mdx
packages/console/src/assets/docs/guides/web-express/README.mdx
packages/console/src/assets/docs/guides/web-go/README.mdx
packages/console/src/assets/docs/guides/web-next/README.mdx
packages/console/src/mdx-components-v2/Step/index.tsx
packages/console/src/mdx-components-v2/Steps/FurtherReadings.tsx
packages/console/src/mdx-components-v2/Steps/index.tsx

use the align the "Further readings" component across guides

refactor(console): align further readings section

---

packages/console/src/assets/docs/guides/native-flutter/README.mdx

feat(console): add flutter guide

---

packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
packages/console/src/assets/docs/guides/web-next-app-router/index.ts

Add Next.js App Router creation guide.
Local preview
OR

feat(console): nextjs app router guide

---

packages/console/src/assets/docs/guides/web-php/README.mdx
packages/console/src/assets/docs/guides/web-php/index.ts
packages/console/src/assets/docs/guides/web-python/README.mdx

add php guide, originally from https://github.com/logto-io/php

feat(console): php guide

---

packages/console/src/components/ProTag/index.tsx
packages/console/src/pages/Applications/components/GuideCard/index.module.scss
packages/console/src/pages/Applications/components/GuideCard/index.tsx
packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx

Upsell M2M feature, and if the current subscription plan does not enable M2M feature, we'll show a `Pro` tag on guide card that targeted to M2M and the guide library M2M filter checkbox.
Locally tested

feat(console): upsell m2m feature on guide card and library filter

---

packages/console/src/assets/docs/guides/web-php/README.mdx
packages/console/src/assets/docs/guides/web-python/README.mdx

add the post logout redirect uri config in the guide, align the experience with sign-in redirect uri

refactor(console): add post logout redirect uri in guides

---

packages/console/src/mdx-components-v2/UriInputField/index.tsx

Fix Golang guide crash issue.
Locally tested and it worked

fix(console): fix Golang guide crash

---

packages/console/src/assets/docs/guides/web-go/index.ts
packages/console/src/assets/docs/guides/web-next-app-router/index.ts
packages/console/src/assets/docs/guides/web-next/index.ts
packages/console/src/assets/docs/guides/web-remix/index.ts

Update some app guide description content. Make them shorter. 
OR

chore(console): update some app guide description content

---

packages/console/src/components/ReportConversion/utils.ts

add trySafe to report methods
OR

fix(console): add trySafe to report methods

---

packages/console/src/components/EmptyDataPlaceholder/index.tsx
packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx

Show a no data placeholder when no search result is found in guide library.
Locally tested

fix(console): show placeholder when no search is found in guide library

---

packages/console/src/pages/Applications/components/Guide/index.module.scss
packages/console/src/pages/Applications/components/GuideLibraryModal/index.module.scss

Use shadow-3 as the footer bar shadow style

style(console): use shadow-3 for footer action bar

---

packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/phrases/src/locales/de/translation/admin-console/applications.ts
packages/phrases/src/locales/en/translation/admin-console/applications.ts
packages/phrases/src/locales/es/translation/admin-console/applications.ts
packages/phrases/src/locales/fr/translation/admin-console/applications.ts
packages/phrases/src/locales/it/translation/admin-console/applications.ts
packages/phrases/src/locales/ja/translation/admin-console/applications.ts
packages/phrases/src/locales/ko/translation/admin-console/applications.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
packages/phrases/src/locales/ru/translation/admin-console/applications.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts

Display toast message after successfully creating application
Locally tested

refactor(console): add toast after creating application successfully

---

packages/integration-tests/src/tests/ui/sign-in-experience/helpers.ts
packages/integration-tests/src/tests/ui/sign-in-experience/sign-in-preview.test.ts

test: add ui tests for sign-in preview
IT
OR

test: add ui tests for sign-in preview

---

packages/console/src/onboarding/pages/SignInExperience/index.tsx
packages/console/src/onboarding/pages/SignInExperience/sie-config-templates.ts
packages/console/src/onboarding/pages/Welcome/index.tsx
packages/console/src/onboarding/types.ts

1. make all onboarding welcome page form fields to be optional (previously, only `project` is required for now).
2. update the "inspire me" options.
3. remove onboarding SIE page "save" button on bottom bar.
OR

chore(console): optimize onboarding process

---

.github/CODEOWNERS

chore: update console code owners

---

packages/console/src/ds-components/Search/index.tsx
packages/console/src/hooks/use-api.ts
packages/console/src/onboarding/pages/SignInExperience/components/PlatformTabs/PlatformTab.tsx
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/Dashboard/components/Block.tsx
packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
packages/console/src/pages/WebhookDetails/WebhookSettings/components/CustomHeaderField/index.tsx

Code cleanup:
* Removed some unused variables
* Fixed a missing react hook dependency warning
* Fixed a TypeScript type warning in use-api.ts

chore(console): code cleanup

---

.github/workflows/close-stale.yml

don't automatically close stale issues to avoid misunderstanding
n/a

chore: update stale issue workflow

---

packages/integration-tests/src/tests/ui/connectors/passwordless-connectors.test.ts
packages/integration-tests/src/tests/ui/connectors/social-connectors.test.ts
packages/integration-tests/src/tests/ui/sign-in-experience/helpers.ts
packages/integration-tests/src/tests/ui/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
packages/integration-tests/src/tests/ui/user-management.test.ts
packages/integration-tests/src/tests/ui/webhooks.test.ts
packages/integration-tests/src/ui-helpers/index.ts

Improve test codes about save & discard changes:
- Extract discard changes logic into a helper method: `expectToDiscardChanges`
- Rename `trySaveChanges` to `expectToSaveChanges`
- Use `expectToSaveChanges` for all save changes logic
IT
OR

refactor(test): improve test codes about save & discard changes

---

packages/console/src/pages/Applications/components/CreateForm/index.tsx

App creation quota upsell should be displayed properly when the total app count reaches the plan limit.
Locally tested

fix(console): app creation quota limit should be displayed on create app form

---

packages/integration-tests/src/tests/ui/connectors/helpers.ts
packages/integration-tests/src/tests/ui/connectors/social-connectors.test.ts
packages/integration-tests/src/tests/ui/rbac.test.ts
packages/integration-tests/src/tests/ui/user-management.test.ts
packages/integration-tests/src/tests/ui/webhooks.test.ts
packages/integration-tests/src/ui-helpers/index.ts

Add modal ui test helpers and apply these helpers to existing tests.
IT
OR

refactor(test): add modal ui test helpers

---

packages/core/src/routes/interaction/index.ts
packages/core/src/routes/interaction/types/guard.ts
packages/core/src/routes/interaction/types/index.ts
packages/schemas/src/types/interactions.ts

Clean up useless interaction guard.
We found several interaction result guard definitions that has never been used except for generate some intermediate InteractionResult types. 
Clean up those interaction guards. 
OR

refactor(core): clean up useless interaction guard

---

packages/toolkit/core-kit/jest.config.js
packages/toolkit/core-kit/jest.setup.js
packages/toolkit/core-kit/src/index.ts
packages/toolkit/core-kit/src/password-policy.test.ts
packages/toolkit/core-kit/src/password-policy.ts

init the checker per design. details may change later but it won't hurt.

feat(toolkit): init password policy checker

---

packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/index.tsx

Remove "not in the list" when the social connector is not set up yet.
OR

refactor(console): remove add connectors tip when no social connector is set up

---

packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SocialTargetsDiffSection.tsx
packages/integration-tests/src/tests/ui/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts

refactor(console): remove no-data social section from changes alert modal

---

packages/connectors/connector-azuread/README.md
packages/connectors/connector-azuread/src/constant.ts

update aad connector README and config for a better experience.
/

refactor(connector): update aad connector

---

packages/console/src/assets/docs/guides/spa-vanilla/README.mdx
packages/console/src/mdx-components/Steps/index.module.scss
packages/console/src/mdx-components/Steps/index.tsx
packages/console/src/mdx-components/UriInputField/index.tsx
packages/console/src/pages/ApplicationDetails/components/GuideDrawer/index.module.scss
packages/console/src/pages/ApplicationDetails/components/GuideDrawer/index.tsx
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/Applications/components/Guide/index.module.scss
packages/console/src/pages/Applications/components/Guide/index.tsx
packages/console/src/pages/Applications/components/GuideCard/index.module.scss
packages/console/src/pages/Applications/components/GuideCard/index.tsx
packages/console/src/pages/Applications/components/GuideGroup/index.tsx
packages/console/src/pages/Applications/components/GuideHeader/index.module.scss
packages/console/src/pages/Applications/components/GuideHeader/index.tsx
packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
packages/console/src/pages/Applications/components/GuideLibraryModal/index.module.scss
packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
packages/console/src/pages/Applications/components/GuideModal/index.module.scss
packages/console/src/pages/Applications/components/GuideModal/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/scss/_dimensions.scss

Refactor and improve responsive layout in app creation guide library page and SDK guide details page.
Locally co-tested with designer
~~- [ ] docs~~
OR

refactor: improve guide responsive rules

---

packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/Applications/components/Guide/index.tsx
packages/console/src/pages/Applications/components/GuideModal/index.tsx
packages/console/src/pages/Applications/components/StepsSkeleton/index.module.scss

Adjust loading screens when loading app guide content.
Locally tested, no details page skeleton page was observed.
~~- [ ] docs~~
OR

fix(console): optimize loading screens in app guides

---

packages/connectors/connector-saml/README.md
packages/connectors/connector-saml/src/index.ts
packages/console/src/components/ConnectorForm/ConfigForm/ConfigFormFields/index.tsx
packages/console/src/components/Markdown/index.module.scss
packages/console/src/pages/Connectors/Guide/index.module.scss

1. fix the bug that connector config form hidden fields can not be properly displayed
2. fix SAML error recording for debugging convenience (previously error stack was hard to check)
3. align SAML connector docs fields name and form field label so that users can better find the reference
4. add h3 style for Markdown component and update sub-title styles for connector guide
Tested locally. Will add test case later (LOG-7057).
Dynamic form works fine:
README headers style is good for now:
OR

fix(connector,console): fix SAML error recording and connector config form interaction

---

packages/toolkit/core-kit/src/password-policy.test.ts
packages/toolkit/core-kit/src/password-policy.ts
packages/ui/src/Layout/SecondaryPageLayout/index.tsx
packages/ui/src/containers/SetPassword/index.tsx
packages/ui/src/hooks/use-sie.ts
packages/ui/src/pages/Continue/SetPassword/index.tsx
packages/ui/src/pages/RegisterPassword/index.tsx
packages/ui/src/pages/ResetPassword/index.tsx

sync latest password rules per figma design.
updated unit tests accordingly

refactor(toolkit): sync latest password rules

---

packages/console/src/components/LivePreviewButton/index.tsx
packages/console/src/containers/AppContent/index.tsx
packages/console/src/hooks/use-connector-api.ts
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
packages/core/src/__mocks__/index.ts
packages/core/src/routes/logto-config.test.ts
packages/integration-tests/src/tests/api/logto-config.test.ts
packages/schemas/alterations/next-1694418456-remove-deprecated-challenge-flag.ts
packages/schemas/src/seeds/logto-config.ts
packages/schemas/src/types/logto-config.ts

The original challenge tasks have been deprecated, but related code are still existing in our code base.
So we need to remove all deprecated challenge task flags.
Test locally.
OR

chore: remove deprecated challenge task flags

---

.devcontainer/devcontainer.json

Update devcontainer config:
1. use prebuilt "typescript-node" image to start container easier
2. remove `updateContentCommand` and seed command, because we already have a [contribution guide](https://github.com/logto-io/logto/blob/master/.github/CONTRIBUTING.md), it is better to keep developer's own habit.
OR

chore: update devcontainer

---

packages/console/src/assets/docs/guides/native-flutter/README.mdx

Fix Android callback action settings. 
Set `android:exported="true" to make the callback action globally visible. 
OR

fix(console): update flutter integration guide

---

packages/core/src/libraries/sign-in-experience/mfa.test.ts
packages/core/src/libraries/sign-in-experience/mfa.ts
packages/core/src/routes/sign-in-experience/index.ts
packages/integration-tests/src/tests/api/sign-in-experience.test.ts
packages/phrases/src/locales/de/errors/sign-in-experiences.ts
packages/phrases/src/locales/en/errors/sign-in-experiences.ts
packages/phrases/src/locales/es/errors/sign-in-experiences.ts
packages/phrases/src/locales/fr/errors/sign-in-experiences.ts
packages/phrases/src/locales/it/errors/sign-in-experiences.ts
packages/phrases/src/locales/ja/errors/sign-in-experiences.ts
packages/phrases/src/locales/ko/errors/sign-in-experiences.ts
packages/phrases/src/locales/pl-pl/errors/sign-in-experiences.ts
packages/phrases/src/locales/pt-br/errors/sign-in-experiences.ts
packages/phrases/src/locales/pt-pt/errors/sign-in-experiences.ts
packages/phrases/src/locales/ru/errors/sign-in-experiences.ts
packages/phrases/src/locales/tr-tr/errors/sign-in-experiences.ts
packages/phrases/src/locales/zh-cn/errors/sign-in-experiences.ts
packages/phrases/src/locales/zh-hk/errors/sign-in-experiences.ts
packages/phrases/src/locales/zh-tw/errors/sign-in-experiences.ts

Add "mfa" to the api `/sign-in-exp` in both `GET` and `PATCH`.
Auto tests in the repo.
OR

feat(core): update mfa in sign in experience

---

packages/console/src/components/Guide/ModalFooter/index.module.scss
packages/console/src/components/Guide/ModalFooter/index.tsx
packages/console/src/components/Guide/hooks.ts
packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/pages/ApiResourceDetails/components/ApiGuide/index.tsx
packages/console/src/pages/ApiResourceDetails/components/GuideDrawer/index.module.scss
packages/console/src/pages/ApiResourceDetails/components/GuideDrawer/index.tsx
packages/console/src/pages/ApiResourceDetails/components/GuideModal/index.module.scss
packages/console/src/pages/ApiResourceDetails/components/GuideModal/index.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/ApiResources/components/GuideLibrary/index.module.scss
packages/console/src/pages/ApiResources/components/GuideLibrary/index.tsx
packages/console/src/pages/ApiResources/components/GuideLibraryModal/index.module.scss
packages/console/src/pages/ApiResources/components/GuideLibraryModal/index.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
packages/integration-tests/src/tests/console/rbac.test.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/guide.ts

Add guide support in API resource creation process.
Locally tested. Only express guide is available now.
~~- [ ] docs~~
OR

feat(console): add guide support in api resource creation process

---

.devcontainer/devcontainer.json

Fix container envs for codespaces, remove `ENDPOINT` and add `ADMIN_ENDPOINT`.
N/A
OR

chore: fix container envs for codespaces

---

.changeset/cold-deers-drive.md
.github/workflows/main.yml
packages/schemas/alterations/next-1694509714-keep-existing-password-policy.ts

add changeset and alteration script for releasing
CI

chore: password policy release prep

---

packages/ui/src/components/InputFields/InputField/index.module.scss
packages/ui/src/components/InputFields/InputField/index.tsx

Remove unused `isSuffixVisible` style settings
test locally
OR

refactor(ui): remove unused style settings

---

packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx

fix(console): hide mfa menu item before the feature is ready
Test locally.
OR

fix(console): hide mfa menu item before the feature is ready

---

packages/console/src/components/ConnectorForm/ConfigForm/index.tsx
packages/console/src/hooks/use-custom-domain.ts
packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
packages/console/src/pages/ApplicationDetails/components/AppGuide/index.tsx
packages/console/src/pages/ApplicationDetails/components/Settings.tsx
packages/console/src/utils/domain.ts

Should display custom domain as endpoint URL instead of the default tenant endpoint URL in app details and guides.
Localhost works fine. Pending online test...
~~- [ ] docs~~
OR

fix(console): should display custom domain as alternative endpoint in app details and guides

---

.github/workflows/integration-test.yml
packages/console/src/consts/env.ts
packages/console/src/pages/SignInExperience/index.tsx
packages/integration-tests/src/tests/console/sign-in-experience/password-policy.test.ts
packages/integration-tests/src/ui-helpers/expect-console.ts

add a dedicated environment constant for switching on/off dev features. integration tests for dev features should be available now.
CI

refactor(console): add isDevFeaturesEnabled env const

---

packages/integration-tests/package.json
packages/integration-tests/src/tests/experience/bootstrap.test.ts
packages/integration-tests/src/tests/experience/password-policy.test.ts
packages/integration-tests/src/ui-helpers/expect-experience.ts

align terms in integration-tests
CI

refactor: ui -> experience (part 1)

---

packages/integration-tests/src/ui-helpers/expect-console.ts
packages/integration-tests/src/ui-helpers/expect-page.ts
packages/integration-tests/src/utils.ts

Provide a standard method to build string for matching class names.
CI

refactor(test): add `cls` and `dcls` util functions

---

packages/console/src/assets/docs/guides/api-express/README.mdx
packages/console/src/assets/docs/guides/api-express/index.ts
packages/console/src/components/Guide/index.tsx
packages/console/src/pages/ApiResourceDetails/components/ApiGuide/index.tsx
packages/console/src/pages/ApiResourceDetails/components/GuideDrawer/index.tsx
packages/console/src/pages/ApiResourceDetails/components/GuideModal/index.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx

Support `endpoint` and `audience` variables in API guides
Locally tested
~~- [ ] docs~~
OR

refactor(console): add metadata and support endpoint and audience variables in api guides

---

.changeset/cold-deers-drive.md
.changeset/funny-bikes-press.md

fix changeset per updated package names
local tested:
changeset CI should pass once merged

chore: fix changeset

---

packages/console/src/pages/SignInExperience/index.tsx

chore(console): enable password policy

---

packages/console/src/assets/docs/guides/api-python/README.mdx

Correct a wrong section title in python api guide.
Locally tested
~~- [ ] docs~~
OR

chore(console): fix wrong section title in python api guide

---

.devcontainer/devcontainer.json

Update devcontainer using default image to improve container creation speed.
And add vscode extensions.
Tested using codespaces.

chore: update devcontainer using default image

---

packages/console/src/assets/docs/guides/m2m-general/README.mdx

- Improve guide content to provide better instructions to users
- Fix an error when appending endpoint URL
- Use sentence case in all section titles
~~- [ ] docs~~
OR

refactor(console): improve m2m app guide content

---

packages/core/src/queries/application.ts
packages/core/src/routes/application.test.ts
packages/core/src/routes/application.ts
packages/core/src/utils/search.ts
packages/integration-tests/src/api/application.ts
packages/integration-tests/src/tests/api/application.test.ts

enable advanced search parameters for GET /applications API.
Updated UTs and add IT cases, secured by CI.
OR

chore(core,test): enable advanced search params for GET /applications API

---

packages/core/package.json
packages/core/src/libraries/quota.ts
packages/core/src/routes/sign-in-experience/index.ts
pnpm-lock.yaml

Add quota guard for MFA feature.
Local tested.

fix(core): quota guard for mfa feature

---

packages/phrases/src/locales/de/errors/session.ts
packages/phrases/src/locales/en/errors/session.ts
packages/phrases/src/locales/es/errors/session.ts
packages/phrases/src/locales/fr/errors/session.ts
packages/phrases/src/locales/it/errors/session.ts
packages/phrases/src/locales/ja/errors/session.ts
packages/phrases/src/locales/ko/errors/session.ts
packages/phrases/src/locales/pl-pl/errors/session.ts
packages/phrases/src/locales/pt-br/errors/session.ts
packages/phrases/src/locales/pt-pt/errors/session.ts
packages/phrases/src/locales/ru/errors/session.ts
packages/phrases/src/locales/tr-tr/errors/session.ts
packages/phrases/src/locales/zh-cn/errors/session.ts
packages/phrases/src/locales/zh-hk/errors/session.ts
packages/phrases/src/locales/zh-tw/errors/session.ts

Add interaction MFA related phrases, to reduce the upcoming PR size.
N/A

chore(phrases): add mfa session phrases

---

.changeset/three-pigs-search.md
packages/cli/src/commands/connector/utils.ts
packages/cli/src/commands/database/seed/index.ts
packages/cli/src/commands/database/seed/oidc-config.ts
packages/cli/src/commands/install/utils.ts
packages/cli/src/utils.ts
packages/shared/src/node/env/ConsoleLog.ts

align cli output for a better looking
before
after

refactor(cli): polish cli output

---

packages/phrases/src/locales/de/errors/user.ts
packages/phrases/src/locales/en/errors/user.ts
packages/phrases/src/locales/es/errors/user.ts
packages/phrases/src/locales/fr/errors/user.ts
packages/phrases/src/locales/it/errors/user.ts
packages/phrases/src/locales/ja/errors/user.ts
packages/phrases/src/locales/ko/errors/user.ts
packages/phrases/src/locales/pl-pl/errors/user.ts
packages/phrases/src/locales/pt-br/errors/user.ts
packages/phrases/src/locales/pt-pt/errors/user.ts
packages/phrases/src/locales/ru/errors/user.ts
packages/phrases/src/locales/tr-tr/errors/user.ts
packages/phrases/src/locales/zh-cn/errors/user.ts
packages/phrases/src/locales/zh-hk/errors/user.ts
packages/phrases/src/locales/zh-tw/errors/user.ts

Add mfa totp related phrases, to reduce the upcoming PR's size.
N/A

feat(phrases): add mfa totp phrases

---

.github/workflows/master-codecov-report.yml

Fix experience codecov report
OR

fix: fix experience codecov report

---

.changeset/fuzzy-glasses-double.md
packages/console/src/assets/docs/guides/api-express/README.mdx

Update guide content based on [the new blog](https://blog.logto.io/protect-your-express-js-api/). Fixing errors and adding more code samples and also more intuitive for beginners.
Locally tested
~~- [ ] docs~~
OR
~~- [ ] This PR is not applicable for the checklist~~

refactor(console): update protect api guide for express.js

---

packages/schemas/alterations/next-1694854226-init-sentinel.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/gen/index.ts
packages/schemas/src/gen/schema.ts
packages/schemas/src/gen/types.ts
packages/schemas/src/gen/utils.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/sentinel.ts
packages/schemas/tables/logs.sql
packages/schemas/tables/sentinel_activities.sql

SQL:
Generated:
Sentinels are responsible for accepting activity reports and making decisions based on them.
For example, for a user sign-in activity, the sentinel might decide to:
- Accept since the user uses the same device and location as usual;
- Require a 2FA code since the user uses a new device or location;
- Block the user since the user tried to sign-in too many times with an incorrect password.
The implementation should be privacy-aware and not store any personal identifiable information.
The first sentinel to be implemented will be a basic verification sentinel. It will accepts activities for static or dynamic verification such as passwords, email or phone verification codes, OTPs, etc.
The sentinel will be able to verify if the activity is valid or not based on how many times …

feat: init sentinel

---

Dockerfile

add `dev_features_enabled` argument to dockerfile
N/A
OR

chore: add `dev_features_enabled` argument to dockerfile

---

commitlint.config.cjs

chore: rename `ui` to `experience` in commit message scope enums
No need.
OR

chore: rename `ui` to `experience` in commit message scope enums

---

packages/integration-tests/package.json
packages/integration-tests/src/api/interaction.ts
packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
pnpm-lock.yaml

Add integration tests for binding new MFA(TOTP, https://github.com/logto-io/logto/pull/4551) flow with register and sign in.
N/A

test: add tests for mfa totp flows

---

packages/console/src/components/RolesTransfer/components/SourceRoleItem/index.tsx
packages/console/src/components/RolesTransfer/components/SourceRolesBox/index.tsx
packages/phrases/src/locales/de/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/es/translation/admin-console/application-details.ts
packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
packages/phrases/src/locales/it/translation/admin-console/application-details.ts
packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts

update content of assigning new roles on app details page.
OR

fix(console,phrases): update content of assigning new roles on app details page

---

packages/console/src/components/RolesTransfer/components/SourceRoleItem/index.tsx
packages/console/src/components/RolesTransfer/components/SourceRolesBox/index.tsx
packages/console/src/components/RolesTransfer/components/TargetRoleItem/index.tsx

update content of assigning new roles on app details page on target box.
OR

fix(console): update content of assigning new roles on app details page

---

packages/schemas/alterations/next-1695198741-remove-m2m-app-admin-access-switch.ts

update management api access name/desc to sentence case.
This "Management API Access" role is automatically create for users who have at least one of their m2m app "admin access"  switch on. Change it's role name and desc to be sentence case.
N/A
OR

chore(schemas): update management api access name/desc to sentence case

---

.changeset/famous-zebras-begin.md
packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx
packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx

Add M2M RBAC changeset and remove feature switch.
N/A
OR

chore: add M2M RBAC changeset and remove feature switch

---

packages/integration-tests/src/tests/console/applications/helpers.ts
packages/integration-tests/src/tests/console/applications/index.test.ts
packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts
packages/integration-tests/src/tests/console/machine-to-machine-rbac/utils.ts

add M2M RBAC console test.
Secured by CI.
OR

chore(test): add M2M RBAC console test

---

packages/schemas/alterations/1.9.2-1695198741-remove-m2m-app-admin-access-switch.ts

format alteration script.
N/A
OR

chore(schemas): format alteration script

---

.changeset/early-squids-cheat.md
packages/console/CHANGELOG.md

Add M2M RBAC changeset for @logto/core and update changelog for @logto/console.
N/A
OR

chore: add M2M RBAC changeset for @logto/core and update changelog

---

packages/core/src/routes/interaction/actions/helpers.ts
packages/core/src/routes/interaction/actions/submit-interaction.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts

Should not sync the email automatically if the email or phone has been registered.
A bug has been found when trying to create/link a new social account. 
Whenever a user tries to link a new social identity and a conflict email has been discovered we have the following flow:
| name | screen-short|
| ----- | ------ |
| email required | <img width="361" alt="image" src="https://github.com/logto-io/logto/assets/36393111/2e315465-2d3e-4a23-a69e-ef8c1a007e76"> |
| email optional | <img width="398" alt="image" src="https://github.com/logto-io/logto/assets/36393111/87ffb9ca-f632-4ccb-b20b-cb34cfc2a0e2"> |
If the email is required in SIE then the user has to either link to the existing account or enter a new email identifier.
If the email is optional in SIE then the user may link the social to the …

fix(core): fix new linked social email conflict error

---

packages/integration-tests/src/constants.ts
packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/experience/mfa/totp/add-missing-profile-flow.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/passcode-identifier-flow.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/password-identifier-flow.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/social-flow.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/totp-testing-context.ts
packages/integration-tests/src/ui-helpers/expect-experience.ts
packages/integration-tests/src/ui-helpers/expect-totp-experience.ts

Add tests for totp experience flow
IT
OR

test(experience): add tests for totp experience flow

---

packages/core/src/oidc/init.ts

Use `envSet` reference directly in OIDC configurations. Avoid using closure and pre-deconstructed variables, so that the configurations can be hot replaced on reloading envSet.
This is useful, for example, when rotating private signing keys, as it allows OIDC server to immediately update the configurations on the fly.
Locally tested by rotating private signing keys, and the OIDC server can immediately switch to the new signing key and sign tokens using the new key. This works properly on my local machine and the rest of the code will be updated in follow-up PRs
~~- [ ] docs~~
OR

refactor(core): support oidc configuration hot replace

---

packages/cli/src/commands/database/config.ts
packages/cli/src/commands/database/utils.ts
packages/core/src/__mocks__/index.ts
packages/core/src/queries/logto-config.test.ts
packages/core/src/queries/logto-config.ts
packages/core/src/routes/logto-config.test.ts
packages/core/src/routes/logto-config.ts
packages/core/src/test-utils/tenant.ts
packages/core/src/utils/jwks.ts
packages/integration-tests/src/api/logto-config.ts
packages/integration-tests/src/tests/api/logto-config.test.ts
packages/phrases/src/locales/de/errors/oidc.ts
packages/phrases/src/locales/en/errors/oidc.ts
packages/phrases/src/locales/es/errors/oidc.ts
packages/phrases/src/locales/fr/errors/oidc.ts
packages/phrases/src/locales/it/errors/oidc.ts
packages/phrases/src/locales/ja/errors/oidc.ts
packages/phrases/src/locales/ko/errors/oidc.ts
packages/phrases/src/locales/pl-pl/errors/oidc.ts
packages/phrases/src/locales/pt-br/errors/oidc.ts
packages/phrases/src/locales/pt-pt/errors/oidc.ts
packages/phrases/src/locales/ru/errors/oidc.ts
packages/phrases/src/locales/tr-tr/errors/oidc.ts
packages/phrases/src/locales/zh-cn/errors/oidc.ts
packages/phrases/src/locales/zh-hk/errors/oidc.ts
packages/phrases/src/locales/zh-tw/errors/oidc.ts
packages/schemas/src/types/logto-config.ts
packages/schemas/tables/logto_configs.sql

Add APIs to support fetch, delete and rotate `oidc.privateKeys` and `oidc.cookieKeys`.
Note: changeset and unit test will be added later
Locally tested with postman
~~- [ ] `.changeset`~~ Will add changeset later with UI update
~~- [ ] docs~~ Will update docs later
OR
~~- [ ] This PR is not applicable for the checklist~~

feat(core,phrases): add apis to fetch, delete and rotate oidc private keys

---

packages/phrases/src/locales/de/translation/admin-console/tenants.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/es/translation/admin-console/tenants.ts
packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
packages/phrases/src/locales/it/translation/admin-console/tenants.ts
packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts

Add i18n phrases for private key rotation feature (1/2 parts)
Tested locally
~~- [ ] docs~~
OR

feat(phrases): add i18n phrases for private key rotation feature

---

packages/core/src/database/delete-by-id.ts
packages/core/src/database/row-count.ts
packages/core/src/middleware/koa-guard.ts
packages/core/src/middleware/koa-pagination.ts
packages/core/src/queries/organizations.ts
packages/core/src/routes/init.ts
packages/core/src/routes/organization-roles.ts
packages/core/src/routes/organizations.ts
packages/core/src/routes/types.ts
packages/core/src/tenants/Queries.ts
packages/core/src/utils/SchemaRouter.test.ts
packages/core/src/utils/SchemaRouter.ts
packages/core/src/utils/TenantQueries.ts
packages/integration-tests/src/api/organization.ts
packages/integration-tests/src/tests/api/organization.test.ts

- implement `SchemaRouter` for generic CRUD APIs with customizable actions
- the class extends `koa-router`, thus we can add more routes if needed
- implement organization CRUD APIs
added test cases

feat(core): org basic apis

---

packages/cli/src/database.ts
packages/core/src/database/find-all-entities.ts
packages/core/src/database/find-entity-by-id.ts
packages/core/src/database/insert-into.ts
packages/core/src/database/update-where.test.ts
packages/core/src/database/update-where.ts
packages/core/src/errors/SlonikError/index.ts
packages/core/src/middleware/koa-slonik-error-handler.ts
packages/core/src/routes/organization-roles.ts
packages/core/src/routes/organizations.ts
packages/core/src/utils/SchemaRouter.test.ts
packages/core/src/utils/SchemaRouter.ts
packages/core/src/utils/schema.ts
packages/schemas/src/foundations/schemas.ts
packages/schemas/src/gen/schema.ts
packages/shared/src/database/sql.test.ts
packages/shared/src/database/sql.ts
packages/shared/src/database/types.ts

specify keys for schemas to provide precise generic control for the generic schema routers and actions
CI. only type changes

refactor(schemas,shared)!: optimize schema types

---

packages/integration-tests/src/ui-helpers/expect-experience.ts
packages/integration-tests/src/ui-helpers/expect-totp-experience.ts

chore: update experience tests since it will fail randomly when running ci
IT
OR

chore: update experience tests since it will fail randomly when running ci

---

packages/integration-tests/src/api/factory.ts
packages/integration-tests/src/api/organization-scope.ts
packages/integration-tests/src/api/organization.ts
packages/integration-tests/src/tests/api/organization-scope.test.ts
packages/integration-tests/src/tests/api/organization.test.ts

reduce repeated code and make test apis extendable
CI

refactor(test): add ApiFactory for integration tests

---

packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
packages/phrases/src/locales/de/translation/admin-console/tenants.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/es/translation/admin-console/tenants.ts
packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
packages/phrases/src/locales/it/translation/admin-console/tenants.ts
packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts

Update wording for "rotate OIDC signing keys" feature.
Locally tested
~~- [ ] docs~~
OR

chore(phrases): update wording for rotate oidc signing keys

---

packages/console/src/ds-components/Table/index.module.scss
packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.module.scss

Update compact table styles per latest design system
~~- [ ] docs~~
OR

style(console): update compact table styles per latest design

---

packages/core/src/queries/organizations.ts
packages/core/src/routes/organization-roles.ts
packages/core/src/utils/RelationQueries.ts
packages/core/src/utils/SchemaRouter.ts
packages/integration-tests/src/api/organization-role.ts
packages/integration-tests/src/tests/api/organization-role.test.ts

resolves LOG-7243
- refactor `RelationQueries` class, add more query methods for relations
- implement relation APIs for organization role - scope
added integration tests accordingly

feat(core): role - scope relation apis

---

packages/core/src/database/row-count.ts
packages/core/src/routes/admin-user/basics.test.ts
packages/core/src/routes/admin-user/basics.ts
packages/core/src/routes/admin-user/index.ts
packages/core/src/routes/admin-user/role.test.ts
packages/core/src/routes/admin-user/role.ts
packages/core/src/routes/admin-user/search.test.ts
packages/core/src/routes/admin-user/search.ts
packages/core/src/routes/admin-user/social.test.ts
packages/core/src/routes/admin-user/social.ts
packages/core/src/routes/init.ts
packages/core/src/routes/organization/index.ts
packages/core/src/routes/organization/roles.ts
packages/core/src/routes/organization/scopes.test.ts
packages/core/src/routes/organization/scopes.ts
packages/core/src/utils/RelationQueries.ts
packages/core/src/utils/SchemaRouter.ts
packages/integration-tests/src/api/organization-role.ts
packages/integration-tests/src/tests/api/organization-role.test.ts

move admin-user and org routes to dedicated folders. reduce route init function callings.
no function change. CI should be good.

refactor(core): reorg routes

---

packages/console/src/ds-components/Switch/index.module.scss
packages/toolkit/core-kit/scss/_console-themes.scss

Update disable style of switch component according to the new design file.

style(console): update disable style of switch component

---

packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/experience/mfa/totp/add-missing-profile-flow.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/passcode-identifier-flow.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/password-identifier-flow.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/social-flow.test.ts

reset mfa settings after testing
IT

refactor(test): reset mfa settings after testing

---

packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
packages/phrases/src/locales/de/translation/admin-console/tenants.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/es/translation/admin-console/tenants.ts
packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
packages/phrases/src/locales/it/translation/admin-console/tenants.ts
packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts

Add toast messages on OIDC signing key rotated or deleted
Locally tested

feat(phrases,console): add toast messages on signing key rotated or deleted

---

packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
packages/core/src/routes/interaction/verifications/mfa-verification.ts
packages/experience/src/hooks/use-mfa-verification-error-handler.ts
packages/experience/src/types/guard.ts

Fix function `validateMandatoryBindMfa()`: the user only need any one of the factors, not all.
Unit tests.

fix(core): validate mandatory mfa

---

packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/experience/mfa/webauthn/index.test.ts
packages/integration-tests/src/ui-helpers/expect-experience.ts
packages/integration-tests/src/ui-helpers/expect-totp-experience.ts
packages/integration-tests/src/ui-helpers/expect-webauthn-experience.ts

add tests for webauthn experience flow
- Improve experience page path type from `mfa-binding/${MfaFactor.TOTP}` and `mfa-verification/${MfaFactor.TOTP}` to `mfa-binding/${MfaFactor}` and `mfa-binding/${MfaFactor}`, since now we have multiple factor paths
Since all experience flow is covered by the TOTP testings, so we just need to add a classical test case for binding and verfication flow of WebAuthn factor.
IT
OR

test(experience): add tests for webauthn experience flow

---

packages/integration-tests/src/tests/console/connectors/passwordless-connector-test-cases.ts
packages/integration-tests/src/tests/console/connectors/social-connector-test-cases.ts
packages/integration-tests/src/ui-helpers/index.ts

Per offline discussion, we not need to test all connectors.
So we only test featured connectors now.
- Increase the waiting timeout of the `waitForToast` helper.
IT

refactor(test): refactor connector ui tests

---

packages/console/src/pages/UserDetails/UserSettings/index.tsx
packages/phrases/src/locales/de/translation/admin-console/user-details.ts
packages/phrases/src/locales/en/translation/admin-console/user-details.ts
packages/phrases/src/locales/es/translation/admin-console/user-details.ts
packages/phrases/src/locales/fr/translation/admin-console/user-details.ts
packages/phrases/src/locales/it/translation/admin-console/user-details.ts
packages/phrases/src/locales/ja/translation/admin-console/user-details.ts
packages/phrases/src/locales/ko/translation/admin-console/user-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts
packages/phrases/src/locales/ru/translation/admin-console/user-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts

Add phrases for enterprise identities and update contents on user profile page.
N/A

chore(phrases): add phrases of enterprise identities

---

packages/integration-tests/src/tests/console/connectors/helpers.ts
packages/integration-tests/src/tests/console/connectors/passwordless-connector-test-cases.ts
packages/integration-tests/src/tests/console/connectors/passwordless-connectors.test.ts

Avoid sending connection tests to 3rd-party connector services since
related requests may take a longer duration, causing our tests to fail.
IT

refactor(test): avoid sending connection tests to 3rd-party connector services

---

.github/workflows/main.yml
packages/schemas/alterations/next-1697683802-add-sso-connectors-table.ts
packages/schemas/src/foundations/jsonb-types/index.ts
packages/schemas/src/foundations/jsonb-types/sso-connector.ts
packages/schemas/tables/sso_connectors.sql

Create the `sso_connectors` table.
Please check the inline comments for detailed field explanations. 
N/A
- ~[ ] `.changeset`~
- ~[ ] unit tests~
- ~[ ] integration tests~
- ~[ ] necessary TSDoc comments~

feat(schemas): create sso_connectors table

---

packages/phrases/src/locales/de/errors/session.ts
packages/phrases/src/locales/en/errors/session.ts
packages/phrases/src/locales/es/errors/session.ts
packages/phrases/src/locales/fr/errors/session.ts
packages/phrases/src/locales/it/errors/session.ts
packages/phrases/src/locales/ja/errors/session.ts
packages/phrases/src/locales/ko/errors/session.ts
packages/phrases/src/locales/pl-pl/errors/session.ts
packages/phrases/src/locales/pt-br/errors/session.ts
packages/phrases/src/locales/pt-pt/errors/session.ts
packages/phrases/src/locales/ru/errors/session.ts
packages/phrases/src/locales/tr-tr/errors/session.ts
packages/phrases/src/locales/zh-cn/errors/session.ts
packages/phrases/src/locales/zh-hk/errors/session.ts
packages/phrases/src/locales/zh-tw/errors/session.ts

feat(phrases): add backup code phrases

---

packages/console/src/components/MfaFactorName/index.tsx
packages/console/src/components/MfaFactorTitle/index.tsx

Hide WebAuthn user-agent info on user details page.

refactor(console): hide WebAuthn user-agent info on user details page

---

packages/console/src/consts/env.ts
packages/core/src/libraries/sign-in-experience/mfa.ts
packages/experience/src/App.tsx
packages/experience/src/constants/env.ts
packages/experience/src/hooks/use-pre-sign-in-error-handler.ts
packages/shared/src/node/env/GlobalValues.ts

Add `isDevFeatureEnabled` to core's EnvSet.
Local tested.

chore(core,shared): add isDevFeatureEnabled to envset

---

packages/console/src/components/MfaFactorTitle/index.module.scss
packages/console/src/components/MfaFactorTitle/index.tsx
packages/console/src/pages/Mfa/MfaForm/FactorLabel/WebAuthnTipContent/index.module.scss
packages/console/src/pages/Mfa/MfaForm/FactorLabel/WebAuthnTipContent/index.tsx
packages/console/src/pages/Mfa/MfaForm/FactorLabel/index.tsx
packages/phrases/src/locales/de/translation/admin-console/mfa.ts
packages/phrases/src/locales/en/translation/admin-console/mfa.ts
packages/phrases/src/locales/es/translation/admin-console/mfa.ts
packages/phrases/src/locales/fr/translation/admin-console/mfa.ts
packages/phrases/src/locales/it/translation/admin-console/mfa.ts
packages/phrases/src/locales/ja/translation/admin-console/mfa.ts
packages/phrases/src/locales/ko/translation/admin-console/mfa.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/mfa.ts
packages/phrases/src/locales/pt-br/translation/admin-console/mfa.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/mfa.ts
packages/phrases/src/locales/ru/translation/admin-console/mfa.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/mfa.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/mfa.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/mfa.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/mfa.ts

Add webauthn tips and update phrases

refactor(console): add webauthn tips and update phrases

---

packages/console/src/ds-components/Search/index.tsx

refactor(console): clear search input on clear search results
Before clear
After clear

refactor(console): clear search input on clear search results

---

packages/console/src/components/PermissionsTable/index.module.scss
packages/console/src/components/PermissionsTable/index.tsx
packages/console/src/ds-components/Select/MultiSelect.tsx
packages/console/src/pages/Organizations/CreateRoleModal/index.tsx
packages/console/src/pages/Organizations/PermissionsField/index.tsx
packages/console/src/pages/Organizations/RolesField/index.module.scss
packages/console/src/pages/Organizations/RolesField/index.tsx
packages/console/src/pages/Organizations/Settings/index.tsx
packages/console/src/pages/Organizations/index.module.scss
packages/console/src/pages/Organizations/index.tsx
packages/console/src/scss/_underscore.scss
packages/core/src/queries/organizations.ts
packages/core/src/routes/organization/roles.ts
packages/core/src/utils/SchemaQueries.ts
packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts
packages/integration-tests/src/tests/console/rbac.test.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/organization.ts

- init organization roles table
- add `<MultiSelect />` design system component
- Cannot edit both permissions and roles
- Search keyword not working
- Roles table styling
tested locally

feat(console): organization roles table

---

packages/console/src/pages/Organizations/ActionsButton/index.tsx
packages/console/src/pages/Organizations/PermissionsField/index.tsx
packages/console/src/pages/Organizations/RolesField/index.tsx
packages/phrases/src/locales/de/translation/admin-console/organizations.ts
packages/phrases/src/locales/en/translation/admin-console/organizations.ts
packages/phrases/src/locales/es/translation/admin-console/organizations.ts
packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
packages/phrases/src/locales/it/translation/admin-console/organizations.ts
packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts

refactor(console): use correct delete confirmation text

---

packages/console/src/consts/plan-quotas.ts

feat(console): add mfa to plan quota table

feat(console): add mfa to plan quota table

---

packages/core/src/routes/interaction/additional.test.ts
packages/core/src/routes/interaction/additional.ts
packages/shared/src/utils/index.ts
packages/shared/src/utils/user-display-name.test.ts
packages/shared/src/utils/user-display-name.ts

Improve the QRCode of TOTP: add service name tag and user name tag.
This also fix the scan failure in some devices.
Local tested.

fix(core): set totp qrcode service and user name

---

packages/core/src/routes/interaction/mfa.ts

Fix bind webauthn domain hostname, it should be read from `ctx.URL`.
Local tested.

fix(core): fix bind webauthn domain hostname

---

packages/experience/src/pages/MfaBinding/TotpBinding/index.tsx
packages/integration-tests/src/tests/experience/mfa/factor-switching.test.ts
packages/integration-tests/src/ui-helpers/expect-experience.ts

Should pass correct MFA flow state to the `SwitchMfaFactorsLink` component.
IT

fix(experience): correct mfa flow state for switch mfa factors link

---

packages/console/src/components/EntitiesTransfer/components/EntityItem/index.module.scss
packages/console/src/components/EntitiesTransfer/components/EntityItem/index.tsx
packages/console/src/components/EntitiesTransfer/components/SourceEntitiesBox/index.module.scss
packages/console/src/components/EntitiesTransfer/components/SourceEntitiesBox/index.tsx
packages/console/src/components/EntitiesTransfer/components/SourceEntityItem/index.module.scss
packages/console/src/components/EntitiesTransfer/components/SourceEntityItem/index.tsx
packages/console/src/components/EntitiesTransfer/components/TargetEntitiesBox/index.module.scss
packages/console/src/components/EntitiesTransfer/components/TargetEntitiesBox/index.tsx
packages/console/src/components/EntitiesTransfer/components/TargetEntityItem/index.module.scss
packages/console/src/components/EntitiesTransfer/components/TargetEntityItem/index.tsx
packages/console/src/components/EntitiesTransfer/index.module.scss
packages/console/src/components/EntitiesTransfer/index.tsx
packages/console/src/pages/OrganizationDetails/Members/AddMembersToOrganization.tsx
packages/console/src/pages/OrganizationDetails/Members/index.tsx
packages/console/src/types/general.ts

- refactor `<RoleEntitiesTransfer>` to a new component `<EntitiesTransfer>` make it generic for any entities.
- implement add org members modal
- replace `<RoleEntitiesTransfer>` with `<EntitiesTransfer>`
- add integration tests
- finishing touches (loading state, error handling, etc.)
add multiple members for multiple roles

feat(console): add org members

---

packages/console/src/components/ItemPreview/index.module.scss
packages/console/src/pages/OrganizationDetails/Members/AddMembersToOrganization.tsx
packages/console/src/pages/OrganizationDetails/Members/index.tsx
packages/console/src/pages/OrganizationDetails/index.module.scss
packages/console/src/pages/OrganizationDetails/index.tsx
packages/core/src/database/find-all-entities.ts
packages/core/src/database/utils.ts
packages/core/src/queries/organizations.ts
packages/core/src/routes/organization/index.ts
packages/core/src/routes/organization/utils.ts
packages/core/src/utils/RelationQueries.ts
packages/integration-tests/src/tests/api/organization-role.test.ts
packages/integration-tests/src/tests/api/organization-scope.test.ts
packages/phrases/src/locales/de/errors/entity.ts
packages/phrases/src/locales/en/errors/entity.ts
packages/phrases/src/locales/es/errors/entity.ts
packages/phrases/src/locales/fr/errors/entity.ts
packages/phrases/src/locales/it/errors/entity.ts
packages/phrases/src/locales/ja/errors/entity.ts
packages/phrases/src/locales/ko/errors/entity.ts
packages/phrases/src/locales/pl-pl/errors/entity.ts
packages/phrases/src/locales/pt-br/errors/entity.ts
packages/phrases/src/locales/pt-pt/errors/entity.ts
packages/phrases/src/locales/ru/errors/entity.ts
packages/phrases/src/locales/tr-tr/errors/entity.ts
packages/phrases/src/locales/zh-cn/errors/entity.ts
packages/phrases/src/locales/zh-hk/errors/entity.ts
packages/phrases/src/locales/zh-tw/errors/entity.ts
packages/shared/src/database/types.ts

- fixing to-dos in #4714
- add pagination for displaying organization members in console
- delete user role in organization api will throw as expected if no membership found
- organization members pagination works in console
- add organization members with no role works

refactor(core,console): fixing to-dos

---

packages/console/src/components/EntitiesTransfer/index.module.scss
packages/console/src/components/EntitiesTransfer/index.tsx
packages/console/src/ds-components/Select/MultiSelect.tsx
packages/console/src/pages/OrganizationDetails/Members/AddMembersToOrganization.tsx
packages/console/src/pages/OrganizationDetails/Members/index.tsx
packages/phrases/src/locales/de/translation/admin-console/organization-details.ts
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
packages/phrases/src/locales/es/translation/admin-console/organization-details.ts
packages/phrases/src/locales/fr/translation/admin-console/organization-details.ts
packages/phrases/src/locales/it/translation/admin-console/organization-details.ts
packages/phrases/src/locales/ja/translation/admin-console/organization-details.ts
packages/phrases/src/locales/ko/translation/admin-console/organization-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/organization-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/organization-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/organization-details.ts
packages/phrases/src/locales/ru/translation/admin-console/organization-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/organization-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/organization-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/organization-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/organization-details.ts

fixing to-dos in #4717 #4718 #4720
ci + local

refactor(console): fixing to-dos

---

packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/api/organization-role.ts
packages/integration-tests/src/api/organization-scope.ts
packages/integration-tests/src/api/organization.ts
packages/integration-tests/src/helpers/organization.ts
packages/integration-tests/src/helpers/user.ts
packages/integration-tests/src/tests/api/organization-role.test.ts
packages/integration-tests/src/tests/api/organization-scope.test.ts
packages/integration-tests/src/tests/api/organization.test.ts

create a disposable api class by extending existing pure test api class with a `cleanUp()` method. it will be helpful for reducing test code size and keeping tests clean.
existing tests.

refactor(test): manage test resource lifecycle

---

packages/core/src/routes/sso-connector/index.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/tests/api/sso-connectors.test.ts

Implement patch sso-connector config API

feat(core): implement patch sso-connector config api

---

packages/core/src/routes/sso-connector/index.ts
packages/core/src/routes/sso-connector/type.ts
packages/core/src/routes/sso-connector/utils.ts
packages/core/src/sso/types/index.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/tests/api/sso-connectors.test.ts

Implement delete sso-connector by id endpoint
integration test

feat(core): implement delete sso-connector by id endpoint

---

packages/core/src/routes/sso-connector/index.ts
packages/core/src/routes/sso-connector/type.ts
packages/core/src/routes/sso-connector/utils.ts
packages/core/src/sso/types/index.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/tests/api/sso-connectors.test.ts

Implement get sso-connector by id endpoint
Test locally

feat(core): implement get sso-connector by id endpoint

---

packages/experience/src/components/Button/MfaFactorButton.module.scss

style(experience): left align factor button text content
Test locally.

style(experience): left align factor button text content

---

packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.module.scss
packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.tsx

style(experience): increase padding for binding backup code page
Test locally.

style(experience): increase padding for binding backup code page

---

packages/experience/src/containers/TotpCodeVerification/index.tsx
packages/experience/src/containers/TotpCodeVerification/use-totp-code-verification.ts
packages/experience/src/hooks/use-send-mfa-payload.ts

refactor(experience): clear invalid totp code input
Test locally.

refactor(experience): clear invalid totp code input

---

packages/console/src/pages/Roles/components/AssignRoleModal/index.tsx
packages/phrases/src/locales/de/translation/admin-console/role-details.ts
packages/phrases/src/locales/en/translation/admin-console/role-details.ts
packages/phrases/src/locales/es/translation/admin-console/role-details.ts
packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
packages/phrases/src/locales/it/translation/admin-console/role-details.ts
packages/phrases/src/locales/ja/translation/admin-console/role-details.ts
packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/role-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
packages/phrases/src/locales/ru/translation/admin-console/role-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/role-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/role-details.ts

leverage template literal type to avoid ternaries
- looks ok
- can assign role to users
no function change, use the existing test suite

refactor(console): use phrase key for `<AssignRoleModal>`

---

packages/core/src/queries/sso-connectors.ts
packages/core/src/routes/sso-connector/index.ts
packages/core/src/routes/sso-connector/type.ts
packages/core/src/routes/sso-connector/utils.test.ts
packages/core/src/routes/sso-connector/utils.ts
packages/core/src/sso/OidcConnector/index.ts
packages/core/src/sso/OidcSsoConnector/index.ts
packages/core/src/sso/index.ts
packages/core/src/sso/types/index.ts
packages/core/src/sso/types/oidc.ts
packages/core/src/tenants/Queries.ts
packages/core/src/utils/SchemaQueries.ts
packages/core/src/utils/SchemaRouter.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/tests/api/sso-connectors.test.ts

Add `POST /sso-connectors` API.
- `providerName`: required
- `connectorName`: required
- `config`: partial guarded if provided
Test locally

feat(core): add POST sso-connectors api

---

packages/core/src/queries/sso-connectors.ts
packages/core/src/routes/init.ts
packages/core/src/routes/sso-connector/index.ts
packages/core/src/routes/sso-connector/type.ts
packages/core/src/routes/sso-connector/utils.test.ts
packages/core/src/routes/sso-connector/utils.ts
packages/core/src/sso/OidcConnector/index.ts
packages/core/src/sso/OidcSsoConnector/index.ts
packages/core/src/sso/index.ts
packages/core/src/sso/types/index.ts
packages/core/src/sso/types/oidc.ts
packages/core/src/tenants/Queries.ts
packages/core/src/utils/SchemaQueries.ts
packages/core/src/utils/SchemaRouter.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/tests/api/sso-connectors.test.ts

Add sso-connector-factories API.

feat(core): add sso-connector-factories api

---

packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
packages/core/src/queries/application.ts
packages/core/src/queries/organizations.ts
packages/core/src/routes/organization/index.ts
packages/core/src/routes/role.test.ts
packages/core/src/routes/role.ts
packages/core/src/utils/RelationQueries.ts
packages/core/src/utils/SchemaRouter.ts
packages/core/src/utils/search.ts
packages/integration-tests/src/api/organization.ts
packages/integration-tests/src/tests/api/organization.test.ts
packages/schemas/src/types/application.ts
packages/schemas/src/types/organization.ts
packages/schemas/src/types/role.ts
packages/schemas/src/types/user.ts

- query and show featured org members
- refactor featured types and guards
added integration tests accordingly

feat: organization featured members

---

packages/experience/src/components/Divider/index.module.scss
packages/experience/src/components/Divider/index.tsx

style(experience): remove the margin of dividers without a label

style(experience): remove the margin of dividers without a label

---

packages/integration-tests/src/tests/experience/mfa/user-controlled.test.ts

Add delay to ensure the skip mfa request and sign-in redirection to be handled or the UI test may fail randomly.
CI

chore(test): add delay to ensure the skip mfa request and sign-in redirection to be handled

---

packages/console/src/ds-components/Button/index.module.scss

Fix the issue that the margin between button icon and text margin is missing
Locally tested

fix(console): button icon and text margin

---

packages/experience/src/components/Button/MfaFactorButton.module.scss
packages/experience/src/components/NavBar/index.module.scss

style(experience): update mfa-related styles

style(experience): update mfa-related styles

---

packages/console/src/ds-components/RadioGroup/Radio.module.scss
packages/console/src/pages/Mfa/MfaForm/index.tsx
packages/integration-tests/src/tests/console/mfa/index.test.ts

Update radio disabled styles and disable policy settings when no factor is enabled.

style(console): update radio disabled styles

---

packages/experience/src/hooks/use-webauthn-operation.ts
packages/phrases-experience/src/locales/de/mfa.ts
packages/phrases-experience/src/locales/en/mfa.ts
packages/phrases-experience/src/locales/es/mfa.ts
packages/phrases-experience/src/locales/fr/mfa.ts
packages/phrases-experience/src/locales/it/mfa.ts
packages/phrases-experience/src/locales/ja/mfa.ts
packages/phrases-experience/src/locales/ko/mfa.ts
packages/phrases-experience/src/locales/pl-pl/mfa.ts
packages/phrases-experience/src/locales/pt-br/mfa.ts
packages/phrases-experience/src/locales/pt-pt/mfa.ts
packages/phrases-experience/src/locales/ru/mfa.ts
packages/phrases-experience/src/locales/tr-tr/mfa.ts
packages/phrases-experience/src/locales/zh-cn/mfa.ts
packages/phrases-experience/src/locales/zh-hk/mfa.ts
packages/phrases-experience/src/locales/zh-tw/mfa.ts

refactor(experience): update webauthn error message
Test locally.

refactor(experience): update webauthn error message

---

packages/experience/src/Layout/SecondaryPageLayout/index.tsx
packages/experience/src/components/NavBar/index.module.scss
packages/experience/src/components/NavBar/index.tsx
packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.tsx

refactor(experience): hide nav bar on backup code binding page

refactor(experience): hide nav bar on backup code binding page

---

packages/core/src/routes/interaction/utils/webauthn.ts

When generating WebAuthn registation options, we do not require user verification (touchID, faceID ...). So in the verification options, this should be set to false.
Local tested.

fix(core): remove user verification requirement for webauthn

---

packages/core/src/routes/interaction/mfa.ts

Fix MFA registration and verification log types.
Local tested.

fix(core): fix mfa log type

---

packages/console/src/pages/Mfa/MfaForm/index.tsx

fix(console): fix disable state of mfa policy options

fix(console): fix disable state of mfa policy options

---

packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
packages/core/src/routes/interaction/verifications/mfa-verification.ts

Fix `validateBindMfaBackupCode` to align with the new logic: if backup code is enabled in Console, every user who has other MFA should setup backup code before signing in.
Unit tests covered several cases.
~~- [x] unit tests~~

fix(core): fix validateBindMfaBackupCode to force linking backup code

---

packages/core/src/routes/interaction/index.ts
packages/core/src/routes/interaction/verifications/mfa-verification.backup-code.test.ts
packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
packages/core/src/routes/interaction/verifications/mfa-verification.ts

Block the use of unavailable (closed in Console) MFA.
And split the test file.
Unit tests.

fix(core): block the use of unavailable MFA

---

packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
packages/console/src/pages/Organizations/PermissionModal/index.tsx
packages/integration-tests/src/constants.ts
packages/integration-tests/src/tests/console/organizations.test.ts
packages/integration-tests/src/ui-helpers/expect-console.ts
packages/integration-tests/src/ui-helpers/expect-organizations.ts
packages/integration-tests/src/ui-helpers/expect-page.ts

add integration tests for crud organizations
self

chore(test): init org ui tests

---

packages/experience/src/hooks/use-mfa-error-handler.ts
packages/integration-tests/src/tests/experience/mfa/backup-code/index.test.ts
packages/integration-tests/src/tests/experience/mfa/multi-factors.test.ts
packages/integration-tests/src/ui-helpers/expect-mfa-experience.ts
packages/integration-tests/src/ui-helpers/expect-totp-experience.ts
packages/integration-tests/src/ui-helpers/expect-webauthn-experience.ts

refactor(experience): use last used factor when verifing mfa factors
IT

refactor(experience): use last used factor when verifing mfa factors

---

packages/console/src/ds-components/Select/index.module.scss
packages/console/src/ds-components/Select/index.tsx

Implement search functionality in the select component for better user experience.
Performed hands-on testing in a web browser and integration tests to validate the functionality.
fixes #4558 
#hacktoberfest

feat(console): add support for searching in select component

---

packages/core/src/libraries/user.test.ts
packages/core/src/libraries/user.ts
packages/core/src/routes/admin-user/basics.test.ts
packages/core/src/routes/admin-user/basics.ts
packages/core/src/routes/admin-user/index.ts
packages/core/src/routes/admin-user/mfa-verifications.test.ts
packages/core/src/routes/admin-user/mfa-verifications.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/tests/api/admin-user.mfa-verifications.test.ts
packages/phrases/src/locales/de/errors/user.ts
packages/phrases/src/locales/en/errors/user.ts
packages/phrases/src/locales/es/errors/user.ts
packages/phrases/src/locales/fr/errors/user.ts
packages/phrases/src/locales/it/errors/user.ts
packages/phrases/src/locales/ja/errors/user.ts
packages/phrases/src/locales/ko/errors/user.ts
packages/phrases/src/locales/pl-pl/errors/user.ts
packages/phrases/src/locales/pt-br/errors/user.ts
packages/phrases/src/locales/pt-pt/errors/user.ts
packages/phrases/src/locales/ru/errors/user.ts
packages/phrases/src/locales/tr-tr/errors/user.ts
packages/phrases/src/locales/zh-cn/errors/user.ts
packages/phrases/src/locales/zh-hk/errors/user.ts
packages/phrases/src/locales/zh-tw/errors/user.ts

Add management apis to support binding MFA.

feat(core,phrases): add mfa verifications by api

---

packages/experience/src/pages/MfaBinding/TotpBinding/SecretSection/index.module.scss

Add border radius for totp qr code

style(experience): add border radius for totp qr code

---

packages/experience/src/hooks/use-mfa-error-handler.ts

refactor(experience): polish handle mfa redirection codes and add comments
IT passed.

refactor(experience): polish handle mfa redirection codes and add comments

---

packages/core/package.json
packages/core/src/utils/storage/google-storage.ts
packages/core/src/utils/storage/index.ts
packages/schemas/src/types/system.ts
pnpm-lock.yaml

1. Integrated the @google-cloud/storage package to interact with Google Cloud Storage services.
2. Created the buildGoogleStorage function that takes in the projectId, keyFilename, bucketName to connect to google cloud bucket for file upload.
3. Updated the StorageProvider and storageProviderDataGuard in logto/packages/schemas/src/types/system.ts 
4. Fixes #4552
1. Created a bucket on google cloud buckets with the name logto and granted public view access.
2. Downloaded the keyfile for auth using https://cloud.google.com/iam/docs/keys-create-delete
3. Used the CLI to configure the storage provider.
`pnpm logto db system set storageProvider '{"provider":"GoogleStorage","projectId":"project_id123", "keyFilename":"path_to_the_key.json", "bucketName":"test"}'`
4. Tested the upload file …

feat(core): google cloud storage provider

---

packages/integration-tests/src/tests/console/organizations.test.ts

Temporarily disable organization related console integration tests.

chore(test): temporarily skip organization console integration tests

---

packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/core/src/routes/interaction/types/guard.ts
packages/core/src/routes/interaction/types/index.ts
packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
packages/core/src/routes/interaction/verifications/mfa-verification.ts

For user control policy, prompt the user to bind MFA (skippable). Previously, we only implement sign in flow.
Local tested and existing unit tests.

fix(core): prompt to bind mfa for register

---

packages/console/src/ds-components/Switch/index.module.scss
packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.module.scss
packages/experience/src/pages/MfaBinding/TotpBinding/SecretSection/index.module.scss
packages/experience/src/pages/MfaVerification/BackupCodeVerification/index.tsx
packages/experience/src/scss/_colors.scss
packages/toolkit/core-kit/scss/_console-themes.scss

style: update mfa-related styles
Test locally.

style: update mfa-related styles

---

packages/experience/src/apis/interaction.ts
packages/experience/src/hooks/use-skip-mfa.ts
packages/integration-tests/jest-puppeteer.config.js
packages/integration-tests/src/tests/experience/mfa/user-controlled.test.ts

Skip mfa manually
- Add UI tests for skiping MFA when registering 
IT

refactor(experience): skip mfa manually

---

packages/phrases/src/locales/de/translation/admin-console/general.ts
packages/phrases/src/locales/de/translation/admin-console/tenants.ts
packages/phrases/src/locales/en/translation/admin-console/general.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/es/translation/admin-console/general.ts
packages/phrases/src/locales/es/translation/admin-console/tenants.ts
packages/phrases/src/locales/fr/translation/admin-console/general.ts
packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
packages/phrases/src/locales/it/translation/admin-console/general.ts
packages/phrases/src/locales/it/translation/admin-console/tenants.ts
packages/phrases/src/locales/ja/translation/admin-console/general.ts
packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
packages/phrases/src/locales/ko/translation/admin-console/general.ts
packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
packages/phrases/src/locales/ru/translation/admin-console/general.ts
packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts

chore(phrases): add dev tenant phrases
No need.

chore(phrases): add dev tenant phrases

---

packages/schemas/alterations/next-1698820410-add-user-sso-identities-table.ts
packages/schemas/tables/user_sso_identities.sql

Add user sso identities table to store the user's SSO identities.
Note:
We have indexing issue on our current implementation of the social identities Jsonb field.
To avoid complex querying and indexing issue, define a separate table to store sso identities. 
test locally

feat(schemas): add user sso identities table

---

packages/console/src/consts/logs.ts
packages/core/src/routes/interaction/additional.ts
packages/core/src/routes/interaction/single-sign-on.ts
packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
packages/integration-tests/src/api/interaction-sso.ts
packages/schemas/alterations/next-1698820410-add-user-sso-identities-table.ts
packages/schemas/src/types/log/interaction.ts
packages/schemas/tables/user_sso_identities.sql

1. Rename the original `POST /interaction/sso/:connectorId/authentication` to `POST /interaction/sso/:connectorId/authorization-url`. Keep align with our existing social endpoints. Might migrate or update together in the future. 
2. Refactor the log key types to strictly guard the following flows:
- `ForgotPassword` flow does not support social or password identifier verification method. 
- `Password` identifier verification method only has the `Submit` action, while others have `Create` and `Submit`
3. Add the event !== ForgotPassword assertion in some of the code blocks. Following the above strict assertion. 
ci
- ~[ ] `.changeset`~
- ~[ ] unit tests~
- ~[ ] integration tests~
- ~[ ] necessary TSDoc comments~

refactor(core,schemas,console): refactor log key types and sso-connector authn-url api name

---

packages/core/src/routes/interaction/actions/submit-interaction.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/core/src/routes/interaction/mfa.test.ts
packages/core/src/routes/interaction/mfa.ts
packages/core/src/routes/interaction/types/index.ts
packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
packages/core/src/routes/interaction/verifications/mfa-verification.ts
packages/experience/src/apis/interaction.ts
packages/experience/src/hooks/use-skip-mfa.ts
packages/integration-tests/jest-puppeteer.config.js
packages/integration-tests/src/api/interaction.ts
packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
packages/integration-tests/src/tests/experience/mfa/user-controlled.test.ts
packages/phrases/src/locales/de/errors/session.ts
packages/phrases/src/locales/en/errors/session.ts
packages/phrases/src/locales/es/errors/session.ts
packages/phrases/src/locales/fr/errors/session.ts
packages/phrases/src/locales/it/errors/session.ts
packages/phrases/src/locales/ja/errors/session.ts
packages/phrases/src/locales/ko/errors/session.ts
packages/phrases/src/locales/pl-pl/errors/session.ts
packages/phrases/src/locales/pt-br/errors/session.ts
packages/phrases/src/locales/pt-pt/errors/session.ts
packages/phrases/src/locales/ru/errors/session.ts
packages/phrases/src/locales/tr-tr/errors/session.ts
packages/phrases/src/locales/zh-cn/errors/session.ts
packages/phrases/src/locales/zh-hk/errors/session.ts
packages/phrases/src/locales/zh-tw/errors/session.ts

Disable the "auto" skip for binding MFA, providing an API `PUT /interaction/mfa-skipped` for manual skip.
The failed integration tests are fixed in https://github.com/logto-io/logto/pull/4788
New unit tests and existing integration tests.

feat(core,phrases): disable auto skip mfa

---

packages/console/src/ds-components/CardTitle/index.module.scss
packages/console/src/ds-components/CardTitle/index.tsx
packages/console/src/pages/Mfa/PageWrapper/index.tsx

refactor(console): add pro tag for mfa feature
Updates:
- Support title tag for `CardTitle` component.

refactor(console): add pro tag for mfa feature

---

packages/phrases/src/locales/de/translation/admin-console/general.ts
packages/phrases/src/locales/de/translation/admin-console/tenants.ts
packages/phrases/src/locales/en/translation/admin-console/general.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/es/translation/admin-console/general.ts
packages/phrases/src/locales/es/translation/admin-console/tenants.ts
packages/phrases/src/locales/fr/translation/admin-console/general.ts
packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
packages/phrases/src/locales/it/translation/admin-console/general.ts
packages/phrases/src/locales/it/translation/admin-console/tenants.ts
packages/phrases/src/locales/ja/translation/admin-console/general.ts
packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
packages/phrases/src/locales/ko/translation/admin-console/general.ts
packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
packages/phrases/src/locales/ru/translation/admin-console/general.ts
packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts

Update dev tenant phrases
No need.

chore(phrases): update dev tenant phrases

---

packages/console/src/contexts/TenantsProvider.tsx
packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.module.scss
packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.tsx
packages/console/src/pages/GetStarted/index.tsx

feat(console): add dev tenant nofication on the get-started page

feat(console): add dev tenant nofication on the get-started page

---

packages/core/src/app/init.ts

Allow http 1.1 in core services. Should fix #4604
Pending community verification.

fix(core): allow http1 in core services

---

packages/console/src/components/ActionsButton/index.module.scss
packages/console/src/components/ActionsButton/index.tsx
packages/console/src/components/Breakable/index.module.scss
packages/console/src/components/Breakable/index.tsx
packages/console/src/components/FormCard/FormCardLayout/index.module.scss
packages/console/src/components/OrganizationRolesSelect/index.module.scss
packages/console/src/components/OrganizationRolesSelect/index.tsx
packages/console/src/components/OrganizationScopesSelect/index.tsx
packages/console/src/ds-components/ActionMenu/index.tsx
packages/console/src/ds-components/ModalLayout/index.tsx
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/console/src/pages/Organizations/OrganizationsTable/EmptyDataPlaceholder/index.tsx
packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
packages/console/src/pages/Organizations/PermissionsCard/index.tsx
packages/console/src/pages/Organizations/RolesCard/index.tsx
packages/console/src/pages/Organizations/consts.ts
packages/console/src/pages/Organizations/index.tsx
packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts
packages/integration-tests/src/ui-helpers/index.ts

resolves LOG-7383, LOG-7381, LOG-7390, LOG-7397, LOG-7399, LOG-7403
localhost. all layout/ui issues so no programmatic tests

refactor(console): fix organization issues

---

packages/integration-tests/src/ui-helpers/expect-mfa-experience.ts

Add delay before clicking switch mfa factors link otherwise sometimes the link is rendered but not clickable.
UI tests

test: add delay before clicking switch mfa factors link

---

packages/console/src/components/MfaFactorTitle/index.module.scss

The title font in the mfa factor title should be `label-2` accroding to the design file.

style(console): update mfa factor title font style

---

packages/core/src/routes/organization/index.ts

Add support to search organization by ID in the `GET /organizations` API, as the placeholder text in the UI suggests that.
Locally tested and it worked. Can search organization by either ID or name

feat(core): support searching organization by id

---

packages/console/src/ds-components/IconButton/index.module.scss
packages/console/src/ds-components/Select/MultiSelect.tsx
packages/console/src/ds-components/Select/index.module.scss
packages/toolkit/core-kit/scss/_console-themes.scss

https://github.com/logto-io/logto/assets/14722250/5d59ae64-edde-4e06-9465-a776ef3fc431

refactor(console): support using keyboard to remove option

---

packages/console/src/pages/Mfa/MfaForm/index.tsx

feat(console): add mfa docs link on the mfa config page

feat(console): add mfa docs link on the mfa config page

---

packages/core/src/include.d/oidc-provider/lib-keep/helpers/validate_presence.d.ts
packages/core/src/oidc/grants/organization-token.test.ts
packages/core/src/oidc/grants/organization-token.ts
packages/core/src/test-utils/oidc-provider.ts

add unit test to cover most paths of the new grant
itself

test(core): add organization token grant unit tests

---

packages/console/src/components/CreateConnectorForm/Skeleton/index.tsx
packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/pages/EnterpriseSso/SsoCreationModal/SsoConnectorRadioGroup/SsoConnectorRadio/index.module.scss
packages/console/src/pages/EnterpriseSso/SsoCreationModal/SsoConnectorRadioGroup/SsoConnectorRadio/index.tsx
packages/console/src/pages/EnterpriseSso/SsoCreationModal/SsoConnectorRadioGroup/index.module.scss
packages/console/src/pages/EnterpriseSso/SsoCreationModal/SsoConnectorRadioGroup/index.tsx
packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.module.scss
packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
packages/console/src/pages/EnterpriseSso/index.tsx
packages/phrases/src/locales/de/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/en/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/es/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/it/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso.ts

add SSO connector creation modal.
Tested locally, console integration tests will be added once the AC flow is completed.

feat(console,phrases): add SSO connector creation modal

---

packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx

Should not block dev tenant deletion
Tested locally in the cloud project && tests is covered.

fix(console): allow dev tenant deletion

---

packages/core/src/routes/swagger/index.ts

add cloud note in the swagger response for better understanding
n/a

chore(core): add cloud note for swagger response

---

packages/console/src/components/CreateConnectorForm/index.tsx
packages/console/src/components/FeatureTag/index.tsx
packages/console/src/components/Guide/GuideCard/index.tsx
packages/console/src/ds-components/CardTitle/index.tsx
packages/console/src/ds-components/InlineNotification/index.tsx
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
packages/console/src/pages/Applications/components/TypeDescription/index.tsx
packages/console/src/pages/Mfa/PageWrapper/index.module.scss
packages/console/src/pages/Mfa/PageWrapper/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
packages/phrases/src/locales/de/translation/admin-console/general.ts
packages/phrases/src/locales/en/translation/admin-console/general.ts
packages/phrases/src/locales/es/translation/admin-console/general.ts
packages/phrases/src/locales/fr/translation/admin-console/general.ts
packages/phrases/src/locales/it/translation/admin-console/general.ts
packages/phrases/src/locales/ja/translation/admin-console/general.ts
packages/phrases/src/locales/ko/translation/admin-console/general.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
packages/phrases/src/locales/ru/translation/admin-console/general.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts

refactor(console): show paywall tag and beta notice for mfa

---

.changeset/cuddly-ghosts-mix.md
packages/console/src/consts/plan-quotas.ts
packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/pages/SignInExperience/utils/constants.ts
packages/console/src/pages/UserDetails/UserSettings/index.tsx
packages/core/src/libraries/sign-in-experience/mfa.ts
packages/experience/src/App.tsx
packages/experience/src/hooks/use-pre-sign-in-error-handler.ts

Remove feature flag and get ready to release MFA.
N/A

chore: mfa feature release

---

packages/core/nodemon.json
packages/core/package.json

fix the following issues in dev script:
- rsync does not create the target directory when empty
- openapi json files do not copy when updated
can find updated openapi files in the `/build` folder

chore(core): fix dev script

---

packages/core/src/libraries/sign-in-experience/index.ts

fix the const value of development plan ID.
Local tested.

fix(core): fix devleopment plan id

---

packages/console/src/pages/Organizations/index.tsx

Fix organization guide navigation on clicking "set up organization" button
Locally tested, navigation worked

fix(console): organization guide router link

---

packages/console/src/pages/SignInExperience/utils/constants.ts

chore(console): update comments about hidden locale phrases

chore(console): update comments about hidden locale phrases

---

packages/console/src/consts/external-links.ts
packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.module.scss
packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.tsx

feat(console): add docs link for env tag feature
Test locally.

feat(console): add docs link for env tag feature

---

packages/console/src/pages/Organizations/Guide/PermissionsAndRoles/index.tsx

Filter out empty organization permissions and roles on submit during guide navigation. This can avoid popping out errors that caused by submitting empty permissions and roles to the server.
Locally tested. Guide navigation between pages will not pop out errors any more

fix(console): filter out empty org permissions and roles on guide submit

---

packages/console/src/pages/Organizations/Guide/Introduction/index.tsx
packages/console/src/pages/Organizations/Guide/OrganizationInfo/index.tsx
packages/console/src/pages/Organizations/Guide/OrganizationPermissions/index.tsx
packages/console/src/pages/Organizations/Guide/OrganizationRoles/index.tsx
packages/console/src/pages/Organizations/Guide/const.ts
packages/console/src/pages/Organizations/Guide/index.tsx

Split organization permissions and roles fields into two isolated guide steps, in order to simplify the overall coding logic.
Locally tested

refactor(console): organization permissions and roles are split into two isolated steps

---

packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts

feat(console): display 'no subscription' on dev tenant selector items

feat(console): display 'no subscription' on dev tenant selector items

---

packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.module.scss
packages/phrases/src/locales/de/translation/admin-console/tenants.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/es/translation/admin-console/tenants.ts
packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
packages/phrases/src/locales/it/translation/admin-console/tenants.ts
packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts

refactor(console): update phrases on the tenant creation modal
- Fix the font style of the option hint
- Apply responsive rules to the option description according the design (aligned with designers)

refactor(console): update phrases on the tenant creation modal

---

packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
packages/phrases/src/locales/de/translation/admin-console/tenants.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/es/translation/admin-console/tenants.ts
packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
packages/phrases/src/locales/it/translation/admin-console/tenants.ts
packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts

refactor(console): update phrases on the tenant settings page
- LOG-7505: Remove environment tag content & rename environment tag tenant type after the dev tenant feature is launched

refactor(console): update phrases on the tenant settings page

---

packages/console/src/pages/Mfa/PageWrapper/index.tsx

We should display paywall tag on mfa page for dev tenant.

refactor(console): display paywall tag on mfa page for dev tenant

---

packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx
packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx

Remove feature tag for custom domain feature since now the custom domain is available for all subscription plans.

fix(console): remove feature tag for custom domain feature

---

packages/console/src/consts/external-links.ts

chore: update tenant type doc link
Test locally

chore: update tenant type doc link

---

packages/phrases/src/locales/de/translation/admin-console/tenants.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/es/translation/admin-console/tenants.ts
packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
packages/phrases/src/locales/it/translation/admin-console/tenants.ts
packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts

chore: update dev tenant phrases
Test locally.

chore(console): update dev tenant phrases

---

packages/console/src/components/CreateConnectorForm/Footer/index.tsx
packages/console/src/components/CreateConnectorForm/index.tsx
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
packages/console/src/components/FeatureTag/index.tsx
packages/console/src/components/Guide/GuideCard/index.tsx
packages/console/src/components/PlanDescription/index.tsx
packages/console/src/consts/plan-quotas.ts
packages/console/src/consts/subscriptions.ts
packages/console/src/contexts/TenantsProvider.tsx
packages/console/src/ds-components/CardTitle/index.tsx
packages/console/src/hooks/use-subscribe.ts
packages/console/src/hooks/use-subscription-plans.ts
packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
packages/console/src/pages/Applications/components/TypeDescription/index.tsx
packages/console/src/pages/Mfa/PageWrapper/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
packages/console/src/pages/TenantSettings/Subscription/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
packages/console/src/utils/sort.ts
packages/console/src/utils/subscription.ts
packages/schemas/src/consts/index.ts
packages/schemas/src/consts/subscriptions.ts

Add a `ReservedPlanId` enum to the `schemas` packages since it will be shared among other packages.
- Console: import `ReservedPlanId` from the schemas package and rename all 'reserved plan id' to 'featured plan id' for accuracy.
Test locally and all tests passed.

refactor(console,schemas): add reserved plan id enum

---

packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx

Trying to fix the UT randomly fail issue.
UT

fix(experience): fix the ut randomly fail issue

---

packages/schemas/src/types/tenant.ts

Add JsDoc to enum `TenantTag`.
N/A

refactor(schemas): add js-doc to tenant tag enum

---

packages/console/src/cloud/AppRoutes.tsx
packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx
packages/console/src/components/CreateTenantModal/index.tsx
packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
packages/console/src/containers/AppContent/TenantNotificationContainer/index.tsx
packages/console/src/contexts/TenantsProvider.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
packages/experience/src/utils/sign-in-experience.ts
packages/phrases/src/locales/de/translation/admin-console/tenants.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/es/translation/admin-console/tenants.ts
packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
packages/phrases/src/locales/it/translation/admin-console/tenants.ts
packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts

chore(console,experience): remove feature flag for dev tenant
Test locally and all tests passed.
~~- [ ] `.changeset`~~(Note: this is a cloud only feature, so no changeset is needed)

chore(console,experience): remove feature flag for dev tenant

---

packages/console/src/consts/plan-quotas.ts
packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts

Remove org feature from coming soon list since it's ready now.

refactor(console): remove org feature from coming soon list

---

packages/console/src/ds-components/Table/Skeleton/index.module.scss
packages/console/src/ds-components/Table/Skeleton/index.tsx
packages/console/src/ds-components/Table/index.tsx
packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
packages/console/src/pages/Organizations/TemplateTable/index.tsx
packages/console/src/pages/Organizations/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
packages/console/src/pages/UserDetails/UserSettings/UserMfaVerifications/index.tsx
packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.tsx
packages/console/src/pages/UserDetails/UserSettings/components/UserSsoIdentities/index.tsx

Improve the "jumpy" table loading experience in admin console
1. Integrate the compact loading skeleton into the Table component, so that inline-style compact tables can have a built-in loading skeleton in component
2. Refactor the existing usages of all "inline-style" compact tables (with prop `hasBorder`) and make them show loading skeletons properly
Locally tested

refactor(console): improve table loading experience

---

packages/console/src/pages/EnterpriseSso/Guide/BasicInfo/index.tsx
packages/console/src/pages/EnterpriseSso/Guide/index.tsx
packages/core/src/routes/sso-connector/utils.ts
packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
packages/core/src/sso/OidcSsoConnector/index.ts
packages/core/src/sso/SamlConnector/index.ts
packages/core/src/sso/SamlSsoConnector/index.ts
packages/core/src/sso/types/index.ts
packages/core/src/sso/types/saml.ts
packages/schemas/src/types/sso-connector.ts

Remove get provider properties method.
Per our offline discussion, remove the get provider properties method. 
@darcyYe 
N/A

refactor(core,schemas): remove get provider properties method

---

packages/core/src/routes/interaction/single-sign-on.ts

Add signInMode guard to the sso register api
test locally

feat(core): add signInMode guard to sso register api

---

packages/core/src/sso/SamlConnector/index.ts
packages/core/src/sso/SamlSsoConnector/index.ts

Fix the SAML SSO connector bug.
- fix  the`handleSamlAssertion` input attribute type.  samilify requires the assertion response input to be an HTTPResponse-like data structure. Need to wrap the response body into an object.  
- `getIssuer` should return IdP entityId 
@darcyYe 
test locally

fix(core): fix saml sso connector bug

---

packages/console/src/pages/OrganizationDetails/Members/index.tsx
packages/console/src/pages/Organizations/TemplateTable/index.tsx

Remove row hover effects from organization inline tables

fix(console): remove row hover effects from organization inline tables

---

packages/core/src/routes/swagger/index.ts

as the docs website has been updated
N/A

chore: update management api docs url

---

packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
packages/console/src/containers/ConsoleContent/index.tsx
packages/core/src/oidc/init.ts
packages/core/src/routes/organization/index.ts

chore: remove dev feature flag for orgs

---

packages/console/src/assets/docs/guides/m2m-general/README.mdx

remove m2m app guide content feature switch
N/A

chore(console): remove m2m app guide content feature switch

---

packages/core/src/sso/SamlConnector/index.ts
packages/core/src/sso/SamlConnector/utils.ts

update generation of SAML service provider entity ID.
Should use `getTenantEndpoint` to generate the pathname.
CI.

chore(core): update generation of SAML service provider entity id

---

packages/integration-tests/src/ui-helpers/expect-experience.ts
packages/integration-tests/src/ui-helpers/expect-page.ts
packages/integration-tests/src/utils.ts

Fix experience ui test randomly fail issue
CI passed.

fix(test): fix experience ui test randomly fail issue

---

packages/core/src/sso/SamlConnector/index.ts
packages/core/src/sso/SamlSsoConnector/index.ts

simplify the saml getIssuer method.
Should leverage existing logics.
@darcyYe

refactor(core): simplify the saml getIssuer method

---

packages/core/src/sso/OidcConnector/utils.ts
packages/core/src/sso/OktaSsoConnector/index.ts
packages/core/src/sso/index.ts
packages/schemas/src/types/sso-connector.ts

Add OKTA SSO connector
Test locally

feat(core): add OKTA sso connector

---

packages/console/src/mdx-components/Steps/FurtherReadings.tsx
packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx

Update out-dated documentation links in application guide "further readings" and API resource details pages...
Locally tested all links worked

fix(console): update documentation links

---

packages/core/src/routes/sso-connector/index.ts
packages/core/src/routes/sso-connector/utils.ts
packages/core/src/sso/SamlConnector/index.ts
packages/core/src/sso/SamlConnector/utils.ts
packages/core/src/sso/SamlSsoConnector/index.test.ts
packages/core/src/sso/SamlSsoConnector/index.ts
packages/core/src/sso/types/saml.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
packages/integration-tests/src/tests/api/sso-connectors.test.ts
packages/integration-tests/src/tests/api/well-known.test.ts
packages/schemas/src/types/sso-connector.ts

Per our product design, remove the SSO connector config partial update logic. 
- remove the `PATCH /single-sign-on/connectors/:connectorId/config` endpoint
- remove partial validate logic of the `POST PATCH /single-sign-on/connectors` endpoint. Fully guard the config if any value is provided.
integration tests

refactor(core): remove SSO connector config partial update logic

---

packages/console/src/pages/EnterpriseSsoDetails/Settings/MultiInput/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/Settings/index.tsx
packages/phrases/src/locales/de/errors/single-sign-on.ts
packages/phrases/src/locales/en/errors/single-sign-on.ts
packages/phrases/src/locales/es/errors/single-sign-on.ts
packages/phrases/src/locales/fr/errors/single-sign-on.ts
packages/phrases/src/locales/it/errors/single-sign-on.ts
packages/phrases/src/locales/ja/errors/single-sign-on.ts
packages/phrases/src/locales/ko/errors/single-sign-on.ts
packages/phrases/src/locales/pl-pl/errors/single-sign-on.ts
packages/phrases/src/locales/pt-br/errors/single-sign-on.ts
packages/phrases/src/locales/pt-pt/errors/single-sign-on.ts
packages/phrases/src/locales/ru/errors/single-sign-on.ts
packages/phrases/src/locales/tr-tr/errors/single-sign-on.ts
packages/phrases/src/locales/zh-cn/errors/single-sign-on.ts
packages/phrases/src/locales/zh-hk/errors/single-sign-on.ts
packages/phrases/src/locales/zh-tw/errors/single-sign-on.ts

update email domain input field interaction:
1. accept both unblur or space to trigger new domain inputs
2. apply domain format validity check on each newly added input

chore(console,phrases): update email domain input field interaction

---

packages/core/src/sso/OidcConnector/index.ts
packages/core/src/sso/types/oidc.ts

fix OIDC SSO connector config guard.
Post processor of `scope` should not be placed in config guard since the parsed result will be saved to DB, which could pollute the config field stored in DB.
N/A

fix(core): fix OIDC SSO connector config guard

---

packages/core/src/routes/interaction/single-sign-on.ts
packages/core/src/routes/sso-connector/index.ts

add dev feature guard to SSO endpoints 
Test locally

chore(core): add dev feature guard to SSO endpoints 

---

packages/console/src/pages/EnterpriseSsoDetails/index.tsx

add page level loading for the SSO details page.
The image uploader component relies on the existence of storage config, and should add the load/check of storage config existence to page-level loading to avoid a flash on form change.
N/A

fix(console): add page level loading for SSO details page

---

packages/console/src/pages/EnterpriseSso/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/index.tsx
packages/phrases/src/locales/de/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/en/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/es/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/it/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso.ts

remove SSO connectors status tags.

fix(console,phrases): remove SSO connectors status tags

---

packages/console/src/assets/docs/single-sign-on/OIDC/README.mdx
packages/console/src/assets/docs/single-sign-on/SAML/README.mdx
packages/console/src/assets/docs/single-sign-on/index.ts
packages/console/src/contexts/SsoConnectorContextProvider/index.tsx
packages/console/src/mdx-components/OidcCallbackUri/index.module.scss
packages/console/src/mdx-components/OidcCallbackUri/index.tsx
packages/console/src/mdx-components/SsoSamlSpMetadata/index.module.scss
packages/console/src/mdx-components/SsoSamlSpMetadata/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/SsoGuide/index.module.scss
packages/console/src/pages/EnterpriseSsoDetails/SsoGuide/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/index.tsx

Add standard OIDC and SAML guides.
test locally

feat(console): add standard OIDC and SAML guides

---

packages/console/src/ds-components/Dropdown/DropdownItem.module.scss

Change dropdown item border radius to 6px accroding to the design requirement.

style(console): change dropdown item border radius to 6px

---

packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx

add required for email domain field input

chore(console): add required for email domain field input

---

packages/console/src/assets/docs/guides/web-php/README.mdx
packages/console/src/assets/docs/guides/web-python/README.mdx

chore(console): update php and python guide

---

packages/console/src/pages/EnterpriseSsoDetails/Experience/MultiInput/index.module.scss
packages/console/src/pages/EnterpriseSsoDetails/Experience/MultiInput/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/Experience/index.module.scss
packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx

1. put the description of the email domain input component under the input area
2. update the focus state style of the component when there is error
3. show error within the component (previously error only controls the style of the component)

chore(console): put description under email domain field

---

packages/core/src/routes/interaction/single-sign-on.ts
packages/integration-tests/src/tests/api/interaction/single-sign-on/happy-path.test.ts

Apply ssoEnabled guard to the connector fetch endpoint.
If `ssoEnabled` is set to false, should not return any SSO connectors data to the client side.
integration test.

feat(experience): apply ssoEnabled guard to the connector fetch endpoint

---

packages/console/src/pages/EnterpriseSsoDetails/Connection/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx

Fix accidental removal of empty objects/undefined values.
For PATCH API, undefined values and empty objects are essential when trying to remove existing values, should keep them when making the PATCH API calls.

fix(console): fix accidental removal of empty object/undefined values

---

packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx

client secret input of OIDC SSO form should be confidential

chore(console): client secret input of OIDC SSO form should be confidential

---

packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx

make button disabled when
1. `connectorName` is not filled
2. error (there is only one field in this form, which means the error on `connectorName` field) is not been resolved.
1. connector name not filled
2. error not resolved
3. connector not selected
4. button enabled

chore(console): update SSO connector creation modal interaction

---

packages/experience/src/pages/SingleSignOnConnectors/index.tsx

Move the navigate method to useEffect. Fix the following warning.

fix(experience): move the navigate method to useEffect

---

packages/core/src/routes/custom-phrases.openapi.json

chore(core): add custom-phrases api doc descriptions
Test locally.

chore(core): add custom-phrases api doc descriptions

---

packages/core/src/routes/verification-code.openapi.json

chore(core): add verficiation code api doc descriptions
Test locally.

chore(core): add verficiation code api doc descriptions

---

packages/core/src/routes/hooks.openapi.json

chore(core): add hooks api doc descriptions
Test locally.

chore(core): add hooks api doc descriptions

---

packages/experience/src/App.tsx
packages/experience/src/hooks/use-check-single-sign-on.ts
packages/experience/src/hooks/use-password-sign-in.ts
packages/experience/src/pages/SingleSignOnEmail/index.tsx

This PR fix the following bugs:
1. Missing loading layer for all the SSO pages.  (please check the changes at `packages/experience/src/App.tsx`)
2. Improve the sign-in and register form user experience when autofill is enabled
- We have a hook `useSingleSignOnWatch` implemented to watch the input value of the identifier form. If the given email is SSO only, auto switch to the single sign-on form mode
- However, with the chrome autofill enabled. User might submit the form directly with a prefilled SSO registered email. 
- Apply the `useCheckSingleSignOn` hook on those `onSubmit` methods to guard the form's submission. 
- This will prevent the user continue to the next sign-in step. 
- Previously, instead of apply a extra guard to the form `onSubmit` method, we sent out the request and mute …

fix(experience): fix silent error bug

---

packages/core/src/routes/interaction/index.ts
packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
packages/core/src/routes/interaction/utils/single-sign-on-guard.ts
packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
packages/integration-tests/src/tests/api/interaction/register-with-identifier/sad-path.test.ts
packages/integration-tests/src/tests/api/interaction/register-with-identifier/single-sign-on.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/single-sign-on.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/sad-path.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/single-sign-on.test.ts

should not guard email is SSO is not enabled.
Add integration tests for all the interaction flow.

fix(core): should not guard email if SSO is disabled

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/core/package.json
packages/core/src/libraries/quota.ts
packages/core/src/routes/sso-connector/index.ts
pnpm-lock.yaml

add SSO paywall for core management APIs.
1. block POST/PUT operation for management API if necessary.
2. update @logto/cloud dependency to get proper plan quota (this is preparation for upcoming AC paywall changes)
1. post API blocked for free plan
2. post API available for hobby, pro plan and dev tenant

feat(connector,console,core): add SSO paywall for core management APIs

---

packages/core/src/routes/well-known.openapi.json

chore(core): add well-known api doc descriptions
Test locally.

chore(core): add well-known api doc descriptions

---

packages/console/src/assets/docs/single-sign-on/AzureAD/README.mdx
packages/console/src/assets/docs/single-sign-on/GoogleWorkspace/README.mdx
packages/console/src/assets/docs/single-sign-on/OIDC/README.mdx
packages/console/src/assets/docs/single-sign-on/OKTA/README.mdx
packages/console/src/assets/docs/single-sign-on/SAML/README.mdx

Update the SSO integration guides content

feat(console): update content

---

packages/core/package.json
packages/core/src/routes/admin-user/basic.openapi.json
packages/core/src/routes/admin-user/mfa-verification.openapi.json
packages/core/src/routes/admin-user/organization.openapi.json
packages/core/src/routes/admin-user/role.openapi.json
packages/core/src/routes/admin-user/search.openapi.json
packages/core/src/routes/admin-user/social.openapi.json
packages/core/src/routes/admin-user/social.ts
packages/core/src/routes/application-role.openapi.json
packages/core/src/routes/application.openapi.json
packages/core/src/routes/hooks.openapi.json
packages/core/src/routes/organization/index.openapi.json
packages/core/src/routes/organization/roles.openapi.json
packages/core/src/routes/organization/scopes.openapi.json
packages/core/src/routes/resource.openapi.json
packages/core/src/routes/role.openapi.json
pnpm-lock.yaml

add a lot of api docs and lint parser for json. resolves
see preview [here](https://bump.sh/preview/35e2103b-3742-4797-a6ee-9fc1dd469333).
⬆️

chore(core): add api docs

---

packages/core/src/routes/domain.openapi.json

Add domains api doc descriptions.
Preview by bump.sh: https://bump.sh/preview/c1359c2d-dd58-415e-b9ca-2a5c58866e66/group/endpoint-domains

chore(core): add domains api doc descriptions

---

packages/core/src/routes/dashboard.openapi.json

Add dashboard api doc descriptions
Preview by bump.sh.

chore(core): add dashboard api doc descriptions

---

packages/core/src/routes/authn.openapi.json

feat(core): add authn docs

---

packages/core/src/routes/logto-config.openapi.json
packages/core/src/routes/logto-config.ts

chore(core): add logto-config api doc descriptions
Test locally.

chore(core): add logto-config api doc descriptions

---

packages/core/src/routes/log.openapi.json

chore(core): add logs api doc descriptions
Test locally.

chore(core): add logs api doc descriptions

---

packages/core/src/routes/connector/authorization-uri.openapi.json
packages/core/src/routes/connector/config-testing.openapi.json
packages/core/src/routes/connector/config-testing.ts
packages/core/src/routes/connector/factory.openapi.json
packages/core/src/routes/connector/index.openapi.json

add connector API doc descriptions

chore(core): add connector api doc descriptions

---

.changeset/calm-ladybugs-doubt.md
packages/core/src/routes/admin-user/basic.openapi.json
packages/core/src/routes/application.openapi.json
packages/core/src/routes/authn.openapi.json
packages/core/src/routes/custom-phrases.openapi.json
packages/core/src/routes/dashboard.openapi.json
packages/core/src/routes/hooks.openapi.json
packages/core/src/routes/interaction/index.openapi.json
packages/core/src/routes/logto-config.openapi.json
packages/core/src/routes/organization/index.openapi.json
packages/core/src/routes/organization/roles.openapi.json
packages/core/src/routes/organization/scopes.openapi.json
packages/core/src/routes/resource.openapi.json
packages/core/src/routes/role.openapi.json
packages/core/src/routes/sign-in-experience/index.openapi.json
packages/core/src/routes/status.openapi.json
packages/core/src/routes/swagger/index.openapi.json
packages/core/src/routes/swagger/index.ts
packages/core/src/routes/swagger/utils/general.ts
packages/core/src/routes/swagger/utils/parameters.ts
packages/core/src/routes/user-assets.openapi.json
packages/core/src/routes/verification-code.openapi.json

- add description to every tag
- enforce summary and description for every API in non-production and integration test environment
when one of the APIs has no summary or description, the `GET /api/swagger.json` API throws 500

chore(core): add api tags descriptions

---

.changeset/spotty-ants-clap.md
packages/core/src/libraries/hook/index.ts
packages/core/src/libraries/hook/utils.ts
packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.test.ts
packages/schemas/src/types/hook.ts

Add user ip to webhook event payload
Test locally and all hook related tests passed.

refactor(core): add user ip to webhook event payload

---

packages/core/src/routes/swagger/index.ts

instead of showing the default example url, show something useful

refactor(core): add base url to swagger json

---

.changeset/friendly-adults-swim.md

feat: add sso changeset

---

.changeset/bright-pumas-beam.md
.changeset/brown-cheetahs-hide.md
.changeset/cuddly-hornets-search.md
.changeset/metal-walls-enjoy.md
.changeset/thirty-bugs-hear.md
.changeset/wise-birds-itch.md

chore: split SSO changesets

---

packages/core/src/sso/OidcConnector/utils.ts

Hot fix increases the SSO OIDC-based connector id_token iat tolerance from 60s to 10min.
Since the third-party IdP server time status may vary, increase the tolerance to make the connector more robust.

chore(core): increase sso oidc token iat tolerance

---

packages/shared/src/utils/ttl-cache.ts

chore(shared): add JSDoc comments

---

.changeset/brave-hounds-clean.md
packages/schemas/src/types/tenant.ts

add enums and constants that will be used in admin tenant
n/a (tested with other code. will be separate PRs)

feat(schemas): add tenant role enum and scope enum
