logto-io/logto

packages/cli/src/commands/database/seed/tables.ts, packages/console/src/App.tsx, packages/console/src/consts/management-api.ts, packages/console/src/consts/tenants.ts, packages/console/src/hooks/use-api.ts, packages/core/src/middleware/koa-console-redirect-proxy.ts, packages/core/src/oidc/adapter.ts, packages/core/src/tenants/Tenant.ts, packages/schemas/alterations/next-1676956206-move-console-sie-to-database.ts, packages/schemas/alterations/next-1677059985-move-console-application-to-database.ts, packages/schemas/src/consts/index.ts, packages/schemas/src/consts/oidc.ts, packages/schemas/src/consts/system.ts, packages/schemas/src/seeds/application.ts
move admin console app to database since Logto Cloud needs dynamically add / remove Redirect URIs
local tested for OSS experience, works as expected for console sign in/out. will test on the cloud later
=> refactor: move admin console app to database

packages/console/src/App.tsx, packages/console/src/cloud/App.module.scss, packages/console/src/cloud/App.tsx, packages/console/src/cloud/pages/Cloud/index.module.scss, packages/console/src/cloud/pages/Main/index.tsx, packages/console/src/cloud/pages/Onboard/index.module.scss, packages/console/src/cloud/pages/Onboard/index.tsx, packages/console/src/cloud/types.ts, packages/console/src/consts/tenants.ts
- load cloud app if no tenant id found
- change `/cloud` to `/onboard`
- `/` -> Main
- `/onboard` -> onboard flow
- others -> normal console
=> refactor(console): refactor cloud router

packages/core/src/tenants/Tenant.ts
should mount OIDC after all middlewares loaded
Previous issue:
OIDC request error no properly catched.
Expected:
All OIDC error should goes through our errorHandler middleware and display the error message correctly.
test locally
=> fix(core): mount OIDC after all middlewares

packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
Observed a unexpected bug:
The forbidden sign-in method error returns a empty error message.
Issue:
The error instance is created ahead of i18n is init.
Fix:
Update the static error const as a factory method, generate the error at runtime. 
test locally
=> fix(core): fix empty error message

.scripts/check-alterations-sequence.js, packages/core/src/queries/user.ts, packages/schemas/alterations/next-1676956206-move-console-sie-to-database.ts
- fix alteration script for moving sie config to database
- filter out suspended users from `hasActiveUsers()`
- alteration detection now is for A (Added) C (Copied) R (Renamed) files only
added LOG-5501 LOG-5502 for further actions
CI
=> refactor: fix alteration script

packages/core/src/routes-me/init.ts, packages/core/src/routes-me/social.ts, packages/core/src/routes-me/types.ts, packages/phrases/src/locales/de/errors.ts, packages/phrases/src/locales/en/errors.ts, packages/phrases/src/locales/fr/errors.ts, packages/phrases/src/locales/ko/errors.ts, packages/phrases/src/locales/pt-br/errors.ts, packages/phrases/src/locales/pt-pt/errors.ts, packages/phrases/src/locales/tr-tr/errors.ts, packages/phrases/src/locales/zh-cn/errors.ts
New `/me` APIs for social linking/unlinking in cloud admin console
* `POST /me/social-authorization-uri`: get social platform authorization page URI and navigate to 3rd party social website
* `POST /me/link-social-identity`: fetch user info from 3rd party social paltform and update in Logto DB
* `DELETE /me/social-identity/:connectorId`: delete given social platform identity from current user
=> feat(cloud): new APIs for social linking/unlinking in cloud AC

packages/core/src/routes/interaction/utils/sign-in-experience-valiation.test.ts, packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts
Should not block social email/phone identifiers by SIE sign-in settings.
Issue:
Social bind related user flow. Should not block the API event if email is disabled in the sign-in-experience settings.
Solution, does not check the SIE settings for all social identity typed identifiers. 
test locally
UT updated
=> fix(core): should not block social email/phone identifiers by SIE

packages/console/src/pages/Connectors/components/Guide/index.module.scss
The font size of the readme title and card title (of connector create form) should be 16px (previous font size is 20px)
=> fix(console): font size of readme title and card title should be 16px

packages/core/src/__mocks__/index.ts, packages/core/src/routes/admin-user-role.test.ts, packages/core/src/routes/admin-user-role.ts
The api endpoint `POST /api/users/:userId/roles` accepts `roleIds[]` to assign roles to the user. As relevant to my use case, I implemented a `PUT /api/users/:userId/roles` to replace user's roles. Hoping to see this commit merged as I guess it might find its place in other projects as well.
Refer to here, Discord thread for origin of this:
https://discord.com/channels/965845662535147551/1077713036485349587
I've created relevant tests that you can see in committed files and they are part of usual test process.
=> feat(core): added a new endpoint to replace user roles

packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.module.scss, packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.tsx
Fix margin style for "show logo settings for dark mode".
OR
=> style(console): fix connector dark collapse button margin

packages/ui/src/components/Button/SocialLinkButton.module.scss, packages/ui/src/components/Button/index.module.scss
fix social button text cut-off issue
Line height was set less than the font-size. 
Before:
After:
test locally
OR
=> style(ui): fix social button text cut-off

packages/core/src/middleware/koa-cors.test.ts, packages/core/src/middleware/koa-cors.ts
should use `ctx.request.headers.origin` instead of `ctx.origin`
local tested CORS OK
=> refactor(core): fix CORS

packages/console/src/App.tsx, packages/console/src/cloud/pages/Main/Redirect.tsx, packages/console/src/cloud/pages/Main/Tenants.tsx, packages/console/src/cloud/pages/Main/index.module.scss, packages/console/src/cloud/pages/Main/index.tsx, packages/console/src/components/AppLoading/Offline.tsx, packages/console/src/consts/tenants.ts, packages/console/src/containers/AppLayout/components/UserInfo/index.tsx, packages/console/src/contexts/TenantsProvider.tsx, packages/console/src/hooks/use-theme.ts, packages/console/src/utils/theme.ts
this is the remaining part of #3205, which completes all paths in #3205.
note `useSWR()` is not suitable for `tenants` data since the `<Content>` component needs to build resources for `<LogtoProvider>` @xiaoyijun 
- optimize redirect and api calls
- implement and test create tenant
=> feat(console): support multi-tenancy (2/2)

packages/console/src/components/TextLink/index.module.scss, packages/console/src/containers/AppLayout/components/UserInfo/index.tsx, packages/console/src/hooks/use-logto-userinfo.ts, packages/console/src/pages/Profile/components/BasicUserInfoSection/index.module.scss, packages/console/src/pages/Profile/components/BasicUserInfoSection/index.tsx, packages/console/src/pages/Profile/components/CardContent/index.module.scss, packages/console/src/pages/Profile/components/CardContent/index.tsx, packages/console/src/pages/Profile/components/PasswordSection/index.tsx, packages/console/src/pages/Profile/index.tsx, packages/console/src/pages/Profile/modals/BasicUserInfoUpdateModal/index.tsx, packages/console/src/pages/Profile/modals/ChangePasswordModal/index.module.scss, packages/console/src/pages/Profile/modals/ChangePasswordModal/index.tsx, packages/core/src/routes-me/user.ts, packages/phrases/src/locales/de/translation/admin-console/profile.ts, packages/phrases/src/locales/en/translation/admin-console/profile.ts, packages/phrases/src/locales/fr/translation/admin-console/profile.ts, packages/phrases/src/locales/ko/translation/admin-console/profile.ts, packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts
Enable editing in the new AC profile page, now we can edit basic user information like avatar, name and username, and can also change password.
Basically, the OSS version use cases have all been covered. Need to implement linking email and social later
OR
=> feat(console): allow editing basic userinfo in profile page

packages/core/src/libraries/user.ts
When `invalid credential` error occurs, the core service should return http status code 401 instead of 400.
OR
=> fix(core): error invalid credentials should return 401 instead of 400

.changeset-staged/eight-rocks-wave.md, packages/console/src/App.tsx, packages/console/src/components/ConfirmModal/index.tsx, packages/console/src/contexts/AppConfirmModalProvider/index.tsx, packages/console/src/hooks/use-api.ts, packages/console/src/hooks/use-confirm-modal.ts, packages/console/src/hooks/use-me-custom-data.ts, packages/console/src/hooks/use-swr-fetcher.ts, packages/console/src/hooks/use-swr-options.ts, packages/core/src/routes/interaction/consent.ts
refactor AC 403 flow
- Add global confirm modal provider 
```js
const {show} = useConfirmModal();
await show({ModalContent});
```
- Add global 403 API error handler, show confirm modal
- Auto signout and redirect user to the sign-in page after click on the confirm button
OR
=> refactor(core,console): refactor AC 403 flow

packages/cloud/package.json, packages/cloud/src/libraries/tenants.ts, packages/cloud/src/queries/tenants.ts, packages/console/src/cloud/pages/Main/Tenants.tsx, packages/console/src/cloud/pages/Main/index.tsx, packages/core/nodemon.json, packages/core/package.json, packages/core/src/env-set/GlobalValues.ts, packages/core/src/env-set/UrlSet.ts, packages/core/src/env-set/parameters.ts, packages/core/src/oidc/adapter.ts, packages/core/src/routes/interaction/consent.ts, packages/core/src/routes/resource.ts, packages/core/src/utils/search.ts, packages/core/src/utils/tenant.ts, packages/schemas/src/seeds/logto-config.ts, pnpm-lock.yaml
this pr is a followup of #3247. resolves LOG-5487.
automatically create a new tenant if user has no tenant available in cloud service. console will call `POST /api/tenants` and redirect to the newly created tenant.
- optimize redirect and api calls
- add seed command for cloud database
- allow admin tenant admin to create multiple tenants
- tests will be added later
- frontend error handling
- (maybe) setup cloud dev env without custom domain, (e.g. `localhost`)
=> feat: create tenant for new users

packages/console/src/containers/AppLayout/components/SubMenu/index.module.scss
UserInfo sub-menu should have shadow effect properly applied.
OR
=> fix(console): userinfo submenu should have shadow effect

packages/console/src/App.tsx, packages/console/src/components/AppError/index.tsx, packages/console/src/components/AppLoading/Offline.tsx, packages/console/src/containers/ErrorBoundary/index.tsx, packages/console/src/hooks/use-swr-options.ts, packages/console/src/utils/theme.ts
- bring back `<ErrorBoundary>` and catch async errors
- make `<AppError>` an offline component
remembering the old days when typing `componentXyz` lifecycle functions
caught
=> refactor(console): handling cloud errors

packages/cli/src/commands/database/seed/cloud.ts, packages/console/src/contexts/AppEndpointsProvider.tsx, packages/core/src/routes/interaction/actions/submit-interaction.test.ts, packages/core/src/routes/interaction/actions/submit-interaction.ts, packages/core/src/utils/array.ts, packages/shared/src/env/GlobalValues.ts
- add admin console callback URI for cloud seed
- assign `admin:admin` role for the first admin user if cloud
- add warning for path-based multi-tenancy
- change admin SIE to `SignInAndRegister` after first registration if cloud
with env:
```env
PATH_BASED_MULTI_TENANCY=1
IS_CLOUD=1
```
with command:
```bash
pnpm cli db seed --cloud
pnpm dev:cloud
```
=> refactor: fix cloud dev

docker-compose.yml
looks like ghcr image is not available in GitPod, closes #3266 
[gitpod ok](https://gitpod.io/#https://github.com/logto-io/demo)
=> chore: update docker-compose

.changeset-staged/gold-mugs-allow.md, packages/cli/package.json, packages/cli/src/commands/database/seed/tables.ts, packages/cli/src/commands/database/seed/tenant.ts, packages/cloud/package.json, packages/cloud/src/routes/tenants.ts, packages/console/package.json, packages/console/src/App.tsx, packages/console/src/components/SessionExpired/index.tsx, packages/console/src/containers/AppLayout/index.tsx, packages/console/src/containers/ErrorBoundary/index.tsx, packages/console/src/hooks/use-api.ts, packages/console/src/pages/Welcome/index.tsx, packages/core/package.json, packages/core/src/routes/interaction/actions/submit-interaction.ts, packages/core/src/utils/array.ts, packages/integration-tests/package.json, packages/phrases-ui/package.json, packages/phrases/package.json, packages/schemas/alterations/next-1677907982-allow-admin-create-multiple-tenants.ts, packages/schemas/package.json, packages/schemas/src/seeds/cloud-api.ts, packages/shared/package.json, packages/toolkit/connector-kit/package.json, packages/toolkit/core-kit/package.json, packages/ui/package.json, pnpm-lock.yaml
- add `manage:tenant` scope in Cloud API, which indicates the ability to create tenants without limitation, update, and delete tenants
- show session expired page for cloud api 401 error
- refactor `<ErrorBoundary>` a little bit
a fresh setup, create the first user, and click "Create Tenant" has no limitation
=> refactor: allow admin to create tenants

packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx
Fix a bug in cloud environment that linking social account in profile ended up with double slashes (`//`) in the URL, which is illigal.
The fix leverages JavaScript `URL` utilities to handle possible double slashes in the URL
OR
=> fix(console): profile social linking in cloud env should use correct URL without double slashes

packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx, packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx
In admin console user profile page, user should be able to set email regardless the current email is empty or not. Previously, the UI will block the email linking process if the current email is empty.
https://linear.app/silverhand/issue/LOG-5591/link-email-error
OR
=> fix(console): admin user should be able to set email if current email is null

packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx, packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx, packages/console/src/pages/Connectors/components/Guide/index.tsx
passwordless connectors should not show callbackUri on both create and details pages.
Details page:
Create page:
OR
=> fix(console): passwordless connectors should not show callbackUri

packages/console/src/pages/AuditLogDetails/index.tsx, packages/core/src/oidc/adapter.ts, packages/core/src/routes/application.ts, packages/demo-app/src/index.html, packages/schemas/src/seeds/application.ts
demo app has been removed from database, but our audit logs will query the application data for info display
- update display name "Demo App" -> "Live Preview"
- return fixed data when query application by ID in core
- make demo app not clickable on audit log details
also no error is showing now
=> fix: should return demo app data when query api

packages/core/src/routes-me/user.ts
Should not guard password input when verifying password, as we might have some history passwords that cannot pass the new regex guard.
OR
=> fix(core): should not guard input when verifying password

packages/ui/src/components/InputFields/SmartInputField/use-smart-input-field.ts, packages/ui/src/hooks/use-update-effect.ts
This PR is aimed at fixing a bug in preview mode. The identifier InputField type is not updated when SIE settings are changed. Should reset the InputField if the enabled types are changed.
This fix is for preview mode use only. The input field's enabled types props in production should not be changed. 
test locally
UT passed
OR
=> fix(ui): reset InputField on enabledTypes change

packages/console/src/components/TextInput/index.module.scss, packages/console/src/components/TextInput/index.tsx, packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx, packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx, packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx, packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx
Support both 36px and 44px heights in TextInput component in admin console, and use 36px by default. Since in mainflow UI all text inputs are by default 44px in height, AC profile subpages should also align with it.
By default inputs are 36px in height:
In profile modals inputs are 44px:
OR
=> fix(console): text input in AC should support both 36px and 44px heights

packages/console/src/components/ConnectorLogo/index.module.scss, packages/console/src/components/ConnectorLogo/index.tsx, packages/console/src/components/ImageWithErrorFallback/index.tsx, packages/console/src/pages/ConnectorDetails/index.module.scss, packages/console/src/pages/ConnectorDetails/index.tsx, packages/console/src/pages/Connectors/components/ConnectorName/index.tsx, packages/console/src/pages/Connectors/components/CreateForm/index.module.scss, packages/console/src/pages/Connectors/components/CreateForm/index.tsx, packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/AddButton.module.scss, packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/AddButton.tsx, packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/SelectedConnectorItem.module.scss, packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/SelectedConnectorItem.tsx
Fallback broken connector logo to a system default image.
Before:
After:
OR
=> fix(console): fallback broken connector logo to default image

packages/core/src/routes/admin-user.test.ts, packages/toolkit/core-kit/src/regex.test.ts, packages/toolkit/core-kit/src/regex.ts
The previous backend password regex rule is simple:
- no less than 8 characters
- contains only digits, letters and special symbols
Need to align with the front-end validation rule. Add an additional rule to the regex:
- at least two different types of characters must be present.  
UT added
OR
=> refactor(core): refactor backend password regex rule

packages/ui/src/App.tsx, packages/ui/src/hooks/use-page-context.ts, packages/ui/src/hooks/use-preview.ts, packages/ui/src/hooks/use-theme.ts
We should not change the theme by applying the CSS class names directly. The page theme should always come from the theme value in the `PageContext`.
- Move the `isPreview` state to the `PageContext`.
- Disable auto theme detection in the `useTheme` hook when the page is in preview mode.
OR
=> fix(ui): theme adaption

packages/core/src/app/init.ts, packages/core/src/middleware/koa-body-etag.ts, packages/core/src/middleware/koa-spa-session-guard.ts, packages/core/src/routes/init.ts, packages/core/src/routes/well-known.ts, packages/core/src/utils/test-utils.ts
- provide a global `/status` API for health check
- redirect to the current tenant URL when session not found (previously it's fixed to tenant endpoint which may include `*`)
- send etag for all `GET` APIs
CI + local tested
etag:
=> refactor(core): fix api issues

packages/cloud/src/middleware/with-spa.ts, packages/core/src/middleware/koa-serve-static.ts
explicitly disable cache for the index file in order to keep fresh and avoid cache invalidation issues.
both console and main flow set the proper header
=> refactor(core,cloud): disable cache for index files

.changeset-staged/lemon-spies-switch.md, packages/core/src/middleware/koa-spa-session-guard.test.ts, packages/core/src/middleware/koa-spa-session-guard.ts, packages/core/src/queries/logto-config.ts, packages/core/src/tenants/Tenant.ts, packages/schemas/src/seeds/logto-config.ts, packages/schemas/src/types/logto-config.ts
- user can use this optional config to designate the URL to redirect if session not found in Sign-in Experience
- guard root path as well since admin tenant is separated from user tenant
local tested, Logto redirects as expected.
=> feat(schemas,core): add `sessionNotFoundRedirectUrl` tenant config

packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/pages/ApplicationDetails/index.tsx, packages/console/src/pages/Applications/components/ApplicationsPlaceholder/index.tsx, packages/console/src/pages/Applications/components/CreateForm/index.tsx, packages/console/src/pages/Applications/components/Guide/index.tsx, packages/console/src/pages/Applications/index.tsx, packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx, packages/console/src/pages/Connectors/components/CreateForm/index.tsx, packages/console/src/pages/Connectors/components/Guide/index.tsx, packages/console/src/pages/Connectors/index.tsx
- Add dedicated router paths for both application guides and connector guides in admin console
- De-couple creation form modals and guide modals, so that opening guide modals will automatically close creation forms. Currently the form and the guide modal are stacked on each other.
=> refactor(console): add dedicated routes to AC guides

.changeset-staged/smooth-steaks-cough.md, packages/core/src/__mocks__/sign-in-experience.ts, packages/core/src/queries/sign-in-experience.test.ts, packages/core/src/utils/zod.test.ts, packages/core/src/utils/zod.ts, packages/schemas/alterations/next-1678450233-support-custom-content.ts, packages/schemas/src/foundations/jsonb-types.ts, packages/schemas/src/seeds/sign-in-experience.ts, packages/schemas/tables/sign_in_experiences.sql, packages/ui/src/Layout/AppLayout/CustomContent.tsx, packages/ui/src/Layout/AppLayout/index.module.scss, packages/ui/src/Layout/AppLayout/index.tsx, packages/ui/src/Layout/LandingPageLayout/index.tsx, packages/ui/src/__mocks__/logto.tsx, packages/ui/src/hooks/use-sie.ts, packages/ui/src/utils/consts.ts
Add a new sign-in-experience field `custom_content`. Allows users to upload an HTML template jsonb record. 
- MainFlow Desktop AppLayout Component will read the customContent sie settings and try to locate HTML content with the current location pathname. If a match is found, insert the custom Content into the page dom. 
- Define multiple global classnames, making the custom CSS definition more convenient 
- now user could further customize their sign-in pages using customCSS and custom content
```
<style>
body.desktop .logto_page-container {
flex-direction: row;
}
body.desktop .logto_custom-content {
width: 500px;
margin-right: 120px;
}
body.desktop .logto_custom-content+.logto_main-content {
width: 500px;
min-height: 530px;
}
body.desktop .logto_custom-content+.logto_main-content …
```
=> feat(schemas,ui): add custom content slot

packages/core/src/database/find-entity-by-id.ts, packages/core/src/database/insert-into.ts, packages/core/src/database/update-where.ts, packages/core/src/errors/SlonikError/index.ts, packages/core/src/libraries/user.ts, packages/core/src/middleware/koa-slonik-error-handler.ts, packages/core/src/queries/application.ts, packages/core/src/queries/connector.ts, packages/core/src/queries/custom-phrase.ts, packages/core/src/queries/hooks.ts, packages/core/src/queries/log.ts, packages/core/src/queries/oidc-model-instance.ts, packages/core/src/queries/passcode.ts, packages/core/src/queries/resource.test.ts, packages/core/src/queries/resource.ts, packages/core/src/queries/roles.test.ts, packages/core/src/queries/roles.ts, packages/core/src/queries/scope.ts, packages/core/src/queries/sign-in-experience.ts, packages/core/src/queries/user.ts, packages/core/src/queries/verification-status.ts, packages/core/src/utils/schema.ts, packages/schemas/src/foundations/schemas.ts, packages/schemas/src/gen/schema.ts, packages/shared/src/database/utils.ts
refactor and fix by separating CreateSchema and Schema. also no need for explicitly set generic type for database builders like `buildInsertIntoWithPool()`.
CI (only type changes)
=> refactor: fix schema types

packages/console/src/hooks/use-api.ts, packages/console/src/hooks/use-swr-fetcher.ts, packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
don't show toast for errors when fetching custom phrases since it doesn't matter for updating
local tested, no toast when response with 404
=> refactor(console): hide error toast in language modal

packages/core/src/middleware/koa-guard.test.ts, packages/core/src/middleware/koa-guard.ts, packages/core/src/routes/hook.ts, packages/integration-tests/src/tests/api/hooks.test.ts
- fix an issue in koa-guard that response and status guard don't work if `body` or `files` is truthy
- add comments for koa-guard configs
- add response and status guards for hooks apis
CI
=> refactor(core): add response and status guard for hooks apis

packages/core/src/app/init.ts, packages/core/src/env-set/index.ts, packages/core/src/tenants/Tenant.ts, packages/core/src/tenants/index.ts
fix an issue that database pool ends early before all requests are finished when calling `.dispose()` in LRU cache
- add `dispose()` in Tenant for gracefully dispose tenant resources
- `dispose()` will end database pool when all requests are finished, or timeout
- store tenant middleware function for better performance
tested on cloud, a lot of requests, no 5xx failure
=> refactor(core): optimize tenant disposal

packages/cloud/src/libraries/tenants.ts, packages/cloud/src/queries/connector.ts, packages/cloud/src/queries/service-logs.ts, packages/core/src/routes/connector.ts, packages/shared/src/models/connector.ts
add demo connector configs on tenant create.
notice: there is no alteration script for existing tenant for 2 reasons:
1. Demo connector is only for "new tenant"
2. It is hard to get "endpoints" on current alter process.
Local tested: create a new tenant, and got a demo email connector, send email sucessfully.
OR
=> feat(cloud): add demo connector configs on tenant create

packages/core/src/routes/connector.test.ts, packages/core/src/routes/connector.ts, packages/toolkit/connector-kit/src/types.ts
Send testing sms/email using Generic template type.
After this change, four types of templates (Register, SignIn, ForgotPassword and Generic) are mandated.
ITs and UTs.
OR
=> chore: send testing sms/email using Generic template type

packages/ui/src/Layout/AppLayout/index.module.scss, packages/ui/src/Layout/AppLayout/index.tsx, packages/ui/src/components/LogtoSignature/index.module.scss
update ui main card style
1. shrink the main card size to 540 * 540 on desktop
2. Centralize the main card without LogtoSignature on the screen. 
(move the LogtoSignature within the main card element with absolute positon and transform style, so it won't takes extra vertical spaces)
test lcoally
OR
=> style(ui): update ui main card style

packages/ui/src/hooks/use-social-callback-handler.ts
Greetings from cheqd,
We're implementing a [Telegram connector](https://github.com/cheqd/community-credentials-auth/tree/develop).
- Basic flow is extracted from [Telegram Login Widget](https://core.telegram.org/widgets/login).
- Data integrity checks are being handled internally.
- Flow returns a hash string, which should be parsed as query param.
- Combination of ?state=x&tgAuthFlow=y should be parsed out of:
- window.location.search
- window.location.hash
- Implementation should be backwards compatible + interoperable with existing connectors.
PS:
=> fix(ui): added search + hash string interpolation

packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
hide the demo_app phrases in ac, demo_app phrase are not customizable.
test locally
OR
=> fix(console): hide the demo_app phrases in ac

packages/console/src/pages/ConnectorDetails/index.tsx
Switch to another passwordless connector should go to the guide page instead of the detailed page (since the connector has not been created, it will throw 404).
OR
=> fix: the destination of switch to another passwordless connector

packages/console/src/components/Button/index.module.scss, packages/console/src/components/Button/index.tsx, packages/console/src/components/LivePreviewButton/index.module.scss, packages/console/src/components/LivePreviewButton/index.tsx, packages/console/src/components/Select/index.module.scss, packages/console/src/onboarding/pages/SignInExperience/components/Preview/index.module.scss, packages/console/src/onboarding/pages/SignInExperience/components/Preview/index.tsx, packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.module.scss
- reorg the button trailing icon logic to align with the `icon` prop
- update the select component border-radius to 8px since it was missed in the previous adjustments and went unnoticed. This issue was only discovered when it was found alongside the button during this round of checks.
- add a 'violet' type button, since it's used in the onboarding
- refactor the live preview view button according to the design doc.
- fix the disabled state border color of the default type button.
OR
=> refactor(console): fix sie live preview button styles

packages/console/src/components/SignInExperiencePreview/index.module.scss, packages/console/src/components/SignInExperiencePreview/screen-size.module.scss
Per offline discussion with @fleuraly & @Rany0101 , set the mobile width to 260px and set the web display content to `700px x 880px` an increase padding to `40px`
OR
=> refactor(console): change sie preview size

packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx, packages/console/src/pages/Connectors/components/Guide/index.tsx
For connector creation form: Reset form values everytime connector factory update.
The previous "default value" is unrelyable when the form is being "reused".
Local tested
OR
=> fix(console): reset form values when creating connector

packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.module.scss
Move the scroll bar to the outer box, 
test locally
OR
=> style(ui): move scroll bar outside

packages/console/src/onboarding/pages/SignInExperience/components/InspireMe/index.module.scss
The icon for the light bulb is relatively large and specialized, a 24x24 box was used to frame it, leaving some padding on the left side, which made it look off-center. Therefore, the designer decided to add an additional 4px of padding after "inspire me".
Since the default margin-right is `_.unit(6)` so change it to `_.unit(7)`.
OR
=> style(console): fix inspire me button padding-right

packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.module.scss, packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.module.scss
Add a focus-visible border to countrySelector. Also removed legacy CSS styles. 
OR
=> fix(ui): add focus-visible border to countrySelector

packages/ui/src/components/LogtoSignature/index.tsx
The logto signature padding space on the desktop should not affect the default hyperlink's hitting area.
Apply spacing styles to an extra wrapper layer. So the hyperlink element's hitting area won't be affected. 
NOTICE: On the desktop, we styled the Logto Signature with position absolute + vertical transition. Outer box margin space will overflow. Have to use padding-bottom to guarantee the bottom spacing 
test locally
OR
=> style(ui): fix logto signature hit area

packages/console/src/components/Switch/index.tsx, packages/console/src/pages/Connectors/components/ConfigForm/index.tsx
- remove `defaultChecked` from `<Switch />` since it's not reasonable to use the prop when it's a controlled input
- build form common properties when needed to avoid submitting issue
- no "default checked and checked bot set" warning in console
- connector guide form is ok to submit with only strictly necessary info
- currently no switch needs `defaultValue`
=> refactor(console): fix connector guide form submit issue

packages/console/src/components/DetailsForm/index.tsx, packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx, packages/console/src/pages/Connectors/components/Guide/index.tsx
connector usually hold credentials that are not suitable for auto-complete
local tested, no auto complete
=> refactor(console): turn off auto-complete in connector forms

packages/console/src/components/Markdown/index.tsx, packages/console/src/components/TextInput/index.module.scss, packages/console/src/components/TextInput/index.tsx, packages/console/src/onboarding/pages/SignInExperience/index.tsx, packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx, packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx, packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx, packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx, packages/ui/src/Layout/AppLayout/index.module.scss
align console input field height. Remove all the large 44px height input styling. 
P.S. Also, commit a missing comment for PR #3472 
test locally
OR
=> fix(console): align console input field height

packages/core/src/oidc/init.ts, packages/core/src/routes/interaction/middleware/koa-interaction-sie.ts, packages/core/src/routes/well-known.ts, packages/core/src/utils/request.ts, packages/ui/src/App.tsx, packages/ui/src/apis/settings.ts, packages/ui/src/containers/AppNotification/index.tsx, packages/ui/src/utils/search-parameters.ts
- now ui reads search params and save data to session storage, which can offer a clean url
- use search params to trigger cache invalidation since
- the original method has the possibility not working in a cluster: initialize sign-in in machine A, but send phrases and sie config requests to machine B
- for normal sign-ins, we can still leverage html preload
initial sign-in from live preview:
initial sign-in from console:
=> refactor(core,ui): fix cache issue when sign in to live preview

packages/console/src/onboarding/pages/SignInExperience/index.tsx
The form state `isDirty` should be `true` after we apply the inspire me data.
And the `reset` function will reset the form's default values and the `isDirty` state, which is unexpected.
Test locally.
OR
=> fix(console): apply inspire me data

packages/cloud/src/index.ts, packages/core/src/index.ts
- the role name of Application Insight should be region-irrelevant, since they'll be distinguished by endpoints
- instead, role names should be different per-app
/
=> refactor: fix application insights role names

packages/console/src/pages/Connectors/components/ConnectorName/DemoTag.module.scss, packages/toolkit/core-kit/scss/_console-themes.scss
- add a color token `--color-alert-container`
- set the demo tag background color to `--color-alert-container`
light Mode:
darkMode:
OR
=> style(console): fix demo tag background color

packages/console/src/components/CodeEditor/index.tsx, packages/console/src/pages/Connectors/components/ConfigForm/index.tsx
In connector form's JSON field, if the value is empty, the form should not try to validate if it is a valid JSON.
Local tested
OR
=> fix(console): skip validation for empty value in json editor

.github/workflows/release.yml
fix concurrency group thus automatic triggers are not in the same group as workflow_dispatch
/
=> ci: fix concurrency group for release

packages/cli/src/connector/types.ts, packages/cli/src/connector/utils.ts, packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx, packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx, packages/console/src/pages/Connectors/components/ConnectorForm/hooks.tsx, packages/console/src/pages/Connectors/components/Guide/index.tsx, packages/core/src/routes/connector.test.ts, packages/core/src/routes/connector.ts, packages/integration-tests/src/tests/api/connector.test.ts, packages/toolkit/connector-kit/src/types.ts
passwordless connector sender test throws an invalid config error.
When creating connectors, the instance is not created (and hence can find no connector instance to test with), as a result, we should send message via connector built with corresponding connector factory.
OR
=> fix(console,core,toolkit): passwordless connector sender tester

packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/SignUpForm.tsx, packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/index.tsx
When we call the `trigger` method to validate the form data after `remove()`, the react hook form will validate the new data with the old data index rather than the data index after `delete()`, so add a time out to wait for the form to update.
Example:
we have an array data `[0, 1]`; after we remove the index `0` element, the array becomes `[1]`, but the react hook form will validate the old data index, so the index `1` item will be checked, and we will get `undefined` from the `[1]` at index `1`, and the app will crash:
Test locally.
OR
=> fix(console): fix sign-in methods deletion error

packages/console/src/App.tsx, packages/console/src/cloud/App.tsx, packages/console/src/contexts/AppThemeProvider/index.tsx, packages/console/src/hooks/use-user-preferences.ts, packages/console/src/onboarding/App.tsx, packages/console/src/pages/Main/index.tsx
- The default theme in the `AppThemeContext` should load from local storage.
- Wrap the whole app with `AppThemeProvider` since it provides the theme context for all apps.
- Export a `setFixedTheme` API to support modifying the fixed theme in specific apps.
- Export a `setAppearanceMode` API to support updating the appearance when the user preference is updated.
OR
=> fix(console): read default theme value from local storage

packages/core/src/caches/well-known.ts
reduce ttl to 5s since the sign-in experiences will be unusable if requests hit different instances during the cache-hit period. We need to use a real central cache like Redis with invalidation mechanism for it to enable longer cache ttl.
n/a
=> refactor(core): reduce cache ttl to 5s

packages/cloud/src/queries/connector.ts
remove redundant `storage` field for connectors
=> fix(cloud): remove redundant field

packages/console/package.json, packages/console/src/consts/index.ts, packages/console/src/containers/AppContent/index.tsx, pnpm-lock.yaml
Allow AC to use the signup first user experience by a given interaction mode query params. 
e.g.  http://localhost:3002/console?signup=true
- bump the @logto/react SDK version
- read queryString `signup` from the search params. If the signup mode is specified, should use signup first user experience. 
test locally
OR
=> feat(console): add interactionMode qs to AC

packages/console/src/containers/AppContent/components/UserInfo/index.module.scss
Click close icon on connector readme drawer should close the drawer. The button was affected by the underlying avatar mask that has z-index.
=> fix: close icon should work on connector readme drawer

packages/console/src/containers/AppContent/components/SubMenu/index.tsx, packages/console/src/containers/AppContent/components/UserInfo/index.tsx, packages/console/src/hooks/use-user-preferences.ts
Language and theme selection should have default value.
Clear user preference in database and click user avatar. In the popup menu, language and theme have selected value, which is `en` and `sync with system` by default.
=> fix(console): language and theme should have default value

.github/workflows/release.yml, packages/schemas/src/seeds/sign-in-experience.ts
correct sie initial config type and use `undefined` for logo urls on cloud
data looks good for initial tenants
=> refactor: fix initial sie config for cloud

packages/console/src/components/UserInfoCard/index.tsx, packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx, packages/console/src/types/profile.ts, packages/phrases/src/locales/de/translation/admin-console/profile.ts, packages/phrases/src/locales/en/translation/admin-console/profile.ts, packages/phrases/src/locales/fr/translation/admin-console/profile.ts, packages/phrases/src/locales/ko/translation/admin-console/profile.ts, packages/phrases/src/locales/pt-br/translation/admin-console/profile.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/profile.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/profile.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/profile.ts
fix linked social account not shown bug
Issue: 
When a GitHub user does not have a public email and name specified in their account, the resulting social user info data will have undefined values for the email and name fields. 
The original socialUserInfo guard has these two fields marked as required. Thus the returned identities did not pass the data guard. 
Fix: 
Use the same guard in @logto/connector-kit, keep SSOT. Allow name, email, phone optional.  Display anonymous if neither name nor email is found. 
OR
=> fix(console): fix linked social account not shown bug

packages/console/src/pages/ApplicationDetails/index.tsx, packages/console/src/pages/Applications/components/Guide/GuideModal.tsx, packages/console/src/pages/Applications/components/Guide/index.tsx
Click "Check Guide" button in application details page should open the guide in a drawer view.
=> fix(console): application guide drawer mode in details page

packages/console/src/scss/normalized.scss, packages/console/src/utils/app-insights.ts
fix the style issue caused by `withAITracking()`, added LOG-5820 for integration tests
tested locally, onboarding ok, console tabs ok
=> fix(console): fix style issue caused by additional div wrapper

.changeset/clever-taxis-complain.md, packages/core/src/queries/applications-roles.ts
prefixed fields cannot be used in `insert`
locally, m2m can enable admin access
=> fix(core): use unprefixed fields for query

packages/console/src/pages/Connectors/components/Guide/index.module.scss, packages/console/src/pages/Connectors/components/Guide/index.tsx, packages/console/src/scss/overlayscrollbars.scss
- The readme title should scroll with the readme content.
- Display the scroll bar only when the cursor is over the content.
- Adjust the overlay scrollbar paddings since the original paddings do not fit the scrollable content well.
OR
=> refactor(console): connector guide readme content scrollbar

packages/ui/src/apis/interaction.ts
Hotfix for binding social account link leads to register flow bug. 
Issue:
1. create an account with an email e.g. `logto@google.com`
2. sign-in with google social connector using the `logto@google.com`'s related google account.
3. should lead to the bind with the existing account page:
4.  Click on the Link to another email button at the bottom
5. should lead to the bind new email page
6. Click on the back button to navigate back to the previous bind with the existing account page
7. Click on the bind related user button on top
Expected behavior, bind the google social identity to the existing `logto@google.com` account and signin successfully.
Actual behavior, continue jumping to the bind new email page.
Root cause:
The current main-flow interaction API is not stateless. 
When first …
=> fix(ui): fix bind social account link lead to register bug

.changeset/small-ears-sip.md
NPM says in the [workflow run](https://github.com/logto-io/logto/actions/runs/4477672059/jobs/7869495586):
>  400 Bad Request - PUT https://registry.npmjs.org/@logto%2fschemas - Cannot publish over previously published version "1.0.0".
but we cannot find the version in NPM, i didn't force unpublish this version as well. try bumping the version. related #3568
wait for release
=> chore: force bump schemas version

.changeset-staged/pretty-hounds-sneeze.md, packages/console/src/pages/Connectors/components/ConfigForm/index.tsx
fix connector form validation for switch: the "false" value is treated as empty, so set the switch field's "required" to always false, because it won't have empty value actually.
OR
=> fix(console): fix connector form validation for switch

packages/console/src/components/CodeEditor/index.module.scss, packages/console/src/components/CodeEditor/index.tsx
code editor line wrap failed (while being selected in textarea) when showing code snippets read from mdx file.
=> fix(console): code editor line wrap

packages/console/src/containers/ConsoleContent/index.module.scss
fix app insights wrapper direct children style in AC main pages.
Previous:
After fix:
=> fix(console): app insights wrapper direct children style

.changeset/README.md, .changeset/config.json, .github/workflows/changesets.yml, .scripts/version.js
- reorg the "core release group" for better versioning
- remove the concept of "release group" for publishing to make life eaiser
> **Note**
> The choose of fixed group is for better context alignment, e.g. when we talk about "schemas@v1.2.3", we can make sure it's aligned with the core version. other packages can have their own versions.
CI, also pending a test publishing
=> refactor: update pubilsh flow

packages/console/src/components/Pagination/index.module.scss, packages/console/src/components/Pagination/index.tsx
The pagination label button should be set to disable when it's invalid. Otherwise, it will have click and hover effects.
OR
=> refactor(console): disable invalid pagination labels

.changeset/new-windows-rescue.md, packages/core/src/routes/admin-user.test.ts, packages/core/src/routes/admin-user.ts
Add management API to help verify user password. This is helpful when building a custom sign-in or profile page.
UT and local testing
=> feat(core): add management API to verify user password

packages/console/src/components/MultiTextInput/index.tsx, packages/console/src/components/TextInput/index.tsx, packages/console/src/mdx-components/UriInputField/index.tsx, packages/console/src/onboarding/pages/SignInExperience/index.tsx, packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx, packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx, packages/console/src/pages/ApplicationDetails/components/Settings.tsx, packages/console/src/pages/Applications/components/CreateForm/index.tsx, packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx, packages/console/src/pages/Connectors/components/ConfigForm/index.tsx, packages/console/src/pages/Connectors/components/ConnectorForm/BasicForm.tsx, packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx, packages/console/src/pages/Profile/containers/ChangePasswordModal/index.tsx, packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx, packages/console/src/pages/Profile/containers/VerifyPasswordModal/index.tsx, packages/console/src/pages/RoleDetails/RoleSettings/index.tsx, packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx, packages/console/src/pages/SignInExperience/tabs/Branding/BrandingForm.tsx, packages/console/src/pages/SignInExperience/tabs/Others/TermsForm.tsx, packages/console/src/pages/UserDetails/UserSettings/index.tsx, packages/console/src/pages/Users/components/CreateForm/index.tsx
Now we're using two props (`hasError` & `errorMessage`) to control the error state of the text input component.
The `hasError` prop controls the error style of the `TextInput`, and the `errorMessage` is the error message of the `TextInput`, and the `hasError` is redundant since an `error` prop is enough:
- When we don't need to display an error message in the `TextInput`, we set the `error` to be a `boolean`
- When we need to display an error message in the `TextInput`, we set the `error` to be a `string`
Test locally.
OR
=> refactor(console): remove redundant `hasError` prop from text input

packages/console/src/components/Uploader/FileUploader/index.tsx, packages/phrases/src/locales/de/translation/admin-console/components.ts, packages/phrases/src/locales/en/translation/admin-console/components.ts, packages/phrases/src/locales/es/translation/admin-console/components.ts, packages/phrases/src/locales/fr/translation/admin-console/components.ts, packages/phrases/src/locales/it/translation/admin-console/components.ts, packages/phrases/src/locales/ja/translation/admin-console/components.ts, packages/phrases/src/locales/ko/translation/admin-console/components.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/components.ts, packages/phrases/src/locales/pt-br/translation/admin-console/components.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/components.ts, packages/phrases/src/locales/ru/translation/admin-console/components.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/components.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/components.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/components.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/components.ts
refactor(console): guard file types in the file input dialog box
Guard file type in the file input dialog box:
Guard file type in the code:
1. Change format to allow select invalid types:
2. tested with the invalid type:
OR
=> refactor(console): guard file types in the file input dialog box

.changeset/wise-dingos-compete.md, packages/cli/src/commands/connector/utils.ts
except installation, use current directory as instance path if user doesn't input one
listed connector without inquiring instance path
=> refactor(cli): use current directory as instance path if no input

packages/console/src/components/TextInput/index.module.scss, packages/console/src/components/TextInput/index.tsx, packages/console/src/pages/Connectors/components/ConfigForm/index.tsx, packages/toolkit/connector-kit/src/types.ts
should mask confidential values in the connector config by default (on both create and detail pages).
Tested locally. 
OR
=> feat(console): should mask confidential connector config values by default

.changeset/little-carpets-change.md, packages/console/src/pages/Connectors/components/Guide/index.tsx, packages/schemas/alterations/next-1681267285-fix-get-started-passwordless-status.ts
Adding a social connector should mark the related "Scale passwordless sign in by adding your own connectors" action item as completed in get-started page.
Previously only adding email or SMS connectors can mark this as completed, which is a bit too strict, as social sign-in should also be considered as a passwordless sign-in option.
=> fix(console): adding social connector should mark related get-started action item as completed

packages/core/src/caches/index.test.ts, packages/core/src/caches/index.ts, packages/core/src/caches/well-known.ts, packages/core/src/index.ts
- use `.pong()` to measure success of cache connection since Redis may connect without any permission which will result a false positive 
- log well-known cache hit for better debugging
- `void` promises when app init with error
local tested with several Redis connection strings and well-known cache hits
=> refactor(core): improve cache behavior

packages/console/src/components/PermissionsTable/index.module.scss, packages/console/src/components/PermissionsTable/index.tsx, packages/console/src/components/Table/index.module.scss
The origin permission table has three style problems:
1. the table will clip the content when the table is small, so add a `min-with` to ensure the table will fully display the content.
2. the create button should have a margin between the search input component.
3. the delete column with `colspan=1` is too short to display the delete button correctly.
OR
=> style(console): update permission table style

.github/workflows/release.yml, Dockerfile
since we are tracking the main flow for Logto Cloud, it is required to pass an ApplicationInsights connection string to make it works.
the change is copied from our cloud image. hard to test it now, will test after merge.
=> chore: allow setting appinsights string in core Dockerfile

packages/console/src/components/Switch/index.tsx
Remove the React warning about "Changing an uncontrolled input to be controlled" from `Switch` component in Admin Console.
=> fix(console): remove react warning from Switch component

packages/console/src/components/CodeEditor/index.tsx, packages/console/src/components/Select/index.tsx, packages/console/src/components/TextInput/index.tsx, packages/console/src/components/Textarea/index.tsx, packages/console/src/pages/Connectors/components/ConfigForm/index.tsx, packages/console/src/pages/Connectors/components/ConnectorForm/ConfigForm.tsx, packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/SignUpForm.tsx
Remove React warning from connector config form, changing all `hasError` prop on input fields to `error`.
=> fix(console): remove react warning from connector config form

packages/cloud/src/libraries/services.ts, packages/cloud/src/queries/service-logs.ts, packages/cloud/src/routes/service.test.ts, packages/cloud/src/routes/services.ts, packages/cloud/src/utils/guard.ts
1. Add `payload` to `service logs`.
2. Replace `ArbitraryObject` with `JsonObject`.
Since @logto/cloud is using `JsonObject` and other packages are all using `ArbitraryObject`. `JsonObject` is actually used in PostgreSQL DB schemas, so it is reasonable to replace `ArbitraryObject` with `JsonObject`. Otherwise, any database-related types involved in the cloud would require manually replacing the value of type `ArbitraryObject` with `JsonObject`.
Call the corresponding API and found correct payloads has beed added.
OR
=> chore(cloud): add payload to service log

packages/console/src/pages/Main/index.tsx
define data router outside of the component to avoid creating new router on every render. this also fix the issue that route push doesn't work after `await`, e.g. after creating a new connector and finishing the guide
locally tested, route works, new connector guide can close normally
=> fix(console): fix react data router

packages/connectors/connector-alipay-web/README.md, packages/connectors/connector-alipay-web/src/constant.ts, packages/connectors/connector-alipay-web/src/index.ts, packages/connectors/connector-alipay-web/src/types.ts, packages/connectors/connector-discord/README.md, packages/connectors/connector-discord/src/constant.ts, packages/connectors/connector-discord/src/index.ts, packages/connectors/connector-discord/src/types.ts, packages/connectors/connector-facebook/README.md, packages/connectors/connector-facebook/src/constant.ts, packages/connectors/connector-facebook/src/index.ts, packages/connectors/connector-facebook/src/types.ts, packages/connectors/connector-github/README.md, packages/connectors/connector-github/src/constant.ts, packages/connectors/connector-github/src/index.ts, packages/connectors/connector-github/src/types.ts, packages/connectors/connector-google/README.md, packages/connectors/connector-google/src/constant.ts, packages/connectors/connector-google/src/index.ts, packages/connectors/connector-google/src/types.ts, packages/connectors/connector-wechat-web/README.md, packages/connectors/connector-wechat-web/src/constant.ts, packages/connectors/connector-wechat-web/src/index.ts, packages/connectors/connector-wechat-web/src/types.ts
Make official connectors' (non-standard social connectors) scope configurable.
Previously, we only supported fixed scopes, which are not flexible.
TODO: Non-empty scope for the Apple connector should have a different response handler than the current design, will do this later.
OR
=> feat(connector): make official connectors scope configurable

.github/workflows/clean-up-images.yml, .github/workflows/release.yml
- use the target deployment environment `dev` and `prod` to tag current deployed images instead of `sha-*` since it is unstable and unclear
- the original idea is to use tag to know which exact commit is deployed. since GitHub has [Deployments](https://github.com/logto-io/logto/deployments). to keep it simple, we can use a fixed tag for this.
- remove `sha-*` tagged and untagged images regularly.
will test after merge
=> ci: update release workflow

packages/console/src/components/CodeEditor/index.tsx
1. code editor is showing an error message all the time, which is not right.
2. code editor line number header width. Previously, content with 9 lines had the same line number header as content with 10 lines, which is wrong.
1. Error message:
2. line number header width:
OR
=> fix(console): code editor error and line number header width

packages/connectors/connector-aws-ses/src/index.test.ts, packages/connectors/templates/preset/rollup.config.js
`crypto` is not natively supported by @aws-sdk.
https://github.com/uuidjs/uuid/issues/544
Tested locally. Do not throw an error telling that `getRandomValues` not supported.
Before fix:
After fix:
OR
=> fix(connector): support crypto.getRandomValues in connectors

packages/console/src/containers/AppContent/components/SubMenu/index.tsx
Fix the language selection dropdown height on first load.
Previously since the parent container position is recalculated after loaded, we got wrong calculation result for the submenu dropdown height on first load, because the height calculation is done before the parent container position is updated.
Now it's changed to recalculate the height every time before it shows up (on mouse enter).
Refresh the page and click to open userinfo menu, and then hover on "Language" item, the submenu dropdown height should be calculated properly based on current browser size and its parent position.
=> fix(console): language dropdown height should be calculated properly on first load

packages/cloud/src/middleware/with-security-headers.ts
should allow admin endpoint to be loaded in admin ac iframe
Should allow admin endpoint to be loaded in admin ac iframe.
If you visit admin tenant AC, the SIE preview iframe source endpoint should be adminEndpoint instead of the logto urlSet. Add the adminOrigins to the allow list as well. 
test locally
OR
=> fix(cloud): fix cloud admin ac iframe src error

packages/console/src/pages/AuditLogDetails/index.tsx
Now the `pathname` from `useLocation` will start with `/`, so remove the redundant leading `/` in the `getAuditLogDetailsRelatedResourceLink` method.
Test locally.
OR
=> fix(console): fix the back link of the log details page

packages/console/src/pages/Applications/components/Guide/index.tsx
Trim trailing spaces of code samples in application guides to avoid empty code lines.
Before:
After fix:
OR
=> fix(console): trim trailing spaces in app guide code sample

pnpm-lock.yaml
Bump `caniuse-lite` version in order to get rid of the annoying warning when launching the app.
The warning is gone.
=> chore: bump caniuse-lite version

packages/console/src/containers/ConsoleContent/index.module.scss
Fix a main content height issue caused by introducing overlay scrollbar globally. The main content should take 100% of the available height.
=> fix(console): main content should take 100% available height

packages/core/src/libraries/hook.test.ts, packages/core/src/libraries/hook.ts, packages/integration-tests/src/tests/api/hooks.test.ts, packages/schemas/alterations/next-1683292832-update-hooks.ts, packages/schemas/src/foundations/jsonb-types.ts, packages/schemas/tables/hooks.sql
Update hook schema to support the new hooks feature.
Since this iteration is first deployed in a minor version, so we need to consider the new database schema works for both old API and new API 
- add `name`, `events`, `signingKey` and `enabled` fields to the hook schema.
- deprecated `event` field, but for backward compatibility, its type to nullable.
- deprecate `retries` field in the `HookConfig` schema and fix the webhook post request retry times to 3.
- [Hook v2 Tech Design (Phase 1)](https://www.notion.so/silverhand/Hook-Iteration-Tech-Design-cb62e7435c1d46d4bba47a1031943fb0)
Update related docs: https://github.com/logto-io/docs/pull/426
OR
=> refactor(schemas): update hook schema

.changeset/smooth-icons-fetch.md, packages/integration-tests/src/tests/api/resource.scope.test.ts, packages/schemas/src/gen/schema.ts
Add a non-empty string type guard to all the required, string typed DB fields.
Context:
We have a [empty string converter](https://github.com/logto-io/logto/blob/6c3a5a6899f6c608c5e9b7ae8b9c4cbd745417dc/packages/shared/src/database/sql.ts#L57) implemented what will convert all empty string value inputs into null before inserting into DB. 
For those not null fields, this will end up with a DB update error.  Without handling it exclusively, all our DB insertion-related APIs will throw 500. 
Per our convention, an empty string is not allowed for all the non-null fields. So a non-empty string guard should be applied to those required string fields. 
Solution:
Update the schema guard gen method to include the string().min(1) guard if the current field type is a string and not null without any …
=> fix(schemas): add non-empty string type guard

packages/core/src/routes/custom-phrase.test.ts, packages/core/src/routes/custom-phrase.ts
update custom phrase PUT API response status, per discussion in slack, POST and PUT operations should respond status 201 on success.
UTs and ITs.
OR
=> chore(core): update custom phrase PUT API response status

packages/console/src/pages/WebhookDetails/utils.ts, packages/core/src/libraries/hook.test.ts, packages/core/src/libraries/hook.ts, packages/integration-tests/src/tests/api/hooks.test.ts, packages/schemas/src/foundations/jsonb-types.ts
After the hook schema update, the old hook API should be able to fetch hook data with the `retries` field in the HookConfig.
UT & Test locally.
OR
=> fix(core): compatibility for `retries` field in HookConfig

packages/core/src/middleware/koa-auth/index.ts, packages/core/src/routes/role.scope.ts, packages/core/src/routes/swagger.ts
Automatically add 401,403 error codes status guard to all management API routes.
e.g. for GET & POST /applications API
test locally
OR
=> feat(core): add 401,403 status guard to all management api routes

packages/integration-tests/src/tests/api/application.test.ts, packages/schemas/src/gen/schema.ts
Remove the not null string min-length guard from the response type
Issue:
Previously to avoid the not-null string field db field throwing a 500 error when inserting an empty string into the DB, we added a min length of 1 guard to all the non-null string fields.
However, we have our secret application field defined as a non-null field with a static seed secret value empty. 
Remove the strict string length guard from the return type guard. Allow empty string to exist as a default value or some internal settings. Simply guard the external API through CreateGuard.
Add integration test to cover the case
OR
=> fix(schemas): remove the notnull string min-length guard from response type

packages/ui/src/components/InputFields/SmartInputField/AnimatedPrefix/index.tsx, packages/ui/src/components/InputFields/SmartInputField/CountryCodeSelector/index.tsx
setTabIndex -1 for hidden countryCode
Issue: 
Community report, when navigating through the sign-in form using the tab key, instead of directly focusing on the input element, it focused on the wrapper first.
Cause:
We have a hidden country code selector field that remains accessible through the key board. 
Fix: 
Set the prefix element tabIndex to -1 if it is not visible.
test locally
OR
=> fix(ui): set tabIndex -1 for hidden countryCode

packages/cli/package.json, pnpm-lock.yaml
Lock the dependency version of `@logto/schemas` in order to prevent unexpected issues when seeding or alterating database in an older version of cli.
=> chore(cli): lock logto schemas version

packages/schemas/src/gen/schema.ts, packages/schemas/src/seeds/application.ts
Enable min string length guard to all non-null string typed fields in Guards.
Also, replace the static empty string application secret value in demo-app with a 'N/A'. As the application secret field is required in DB thus, after we apply the string min length guard, an empty string is no longer accepted by the Application Model Guard. 
test locally
OR
=> refactor(schemas,core): enable min string length guard

.changeset/cool-oranges-cheer.md, packages/cloud/src/middleware/with-security-headers.ts, packages/core/src/middleware/koa-security-headers.ts
Remove all the reportOnly flags of the CSP security headers. Bring up strict policy check.
Before: 
After:
test locally
OR
- [] This PR is not applicable to the checklist
=> refactor(core): remove the reportOnly flag

packages/integration-tests/src/tests/api/admin-user.roles.test.ts
Remove some tests with `defaultManagementApi.role.id` since it is deprecated.
There are some cases still using it since we are not able to query the "id" of an internal role. @gao-sun 
N/A
OR
=> test: remove tests with defaultManagementApi.role.id

packages/cloud/src/middleware/with-security-headers.ts, packages/core/src/middleware/koa-security-headers.ts
fix CSP middleware to use correct origins
**Connect Src**
**Frame Src**
**Connect Src**
**Frame Ancestors**
=> fix: use only necessary domains in CSP

packages/schemas/src/gen/schema.ts
Should guard the string length for non-nullable fields event with a default value defined in DB.
test locally
OR
=> fix(schemas): guard string length for default value field

packages/core/src/libraries/hook.test.ts, packages/core/src/libraries/hook.ts, packages/core/src/queries/log.ts, packages/core/src/routes/hook.test.ts, packages/core/src/routes/hook.ts, packages/integration-tests/src/tests/api/hooks.test.ts, packages/schemas/src/types/hook.ts
Support `includeRecentState` query for `GET /hooks` and `GET /hooks/:id` to fetch hook recent state.
RecentState:
```ts
export const hookResponseGuard = Hooks.guard.extend({
recentState: z
.object({
successCount: z.number(),
requestCount: z.number(),
})
});
export type HookResponse = z.infer<typeof hookResponseGuard>;
```
The recent state is use in the coming feature:
UT & IT & Test locally.
OR
=> feat(core): get hook execution stats

packages/console/src/pages/WebhookDetails/index.module.scss, packages/console/src/pages/WebhookDetails/index.tsx, packages/console/src/pages/WebhookDetails/types.ts, packages/console/src/pages/Webhooks/components/SuccessRate/index.tsx, packages/console/src/pages/Webhooks/index.module.scss, packages/console/src/pages/Webhooks/index.tsx, packages/core/src/libraries/hook.test.ts, packages/core/src/libraries/hook.ts, packages/core/src/queries/log.ts, packages/core/src/routes/hook.test.ts, packages/core/src/routes/hook.ts, packages/integration-tests/src/tests/api/hooks.test.ts, packages/phrases/src/locales/de/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/en/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/es/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/fr/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/it/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/ja/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/ko/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/ru/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/webhook-details.ts, packages/schemas/src/types/hook.ts
Display the webhook execution stats in the admin console.
OR
=> feat(console): display webhook execution stats

packages/console/src/pages/WebhookDetails/index.tsx
hide success rate on the hook details page when no request happened
OR
=> fix(console): hide success rate on the hook details page when no request happened

packages/console/src/pages/WebhookDetails/index.tsx
When we change the enable state of a webhook, the state won't change when we return the details page from the list item since the `/hooks/:id` swr request caches the old data.
We need to refresh the hook data when its content has been changed.
Test locally.
OR
=> fix(console): refresh hook on data updated

Dockerfile
Modify Dockerfile so we can use cli from the docker image directly.
e.g. This PR adds support for something like `docker run ghcr.io/logto-io/logto:1.3.1 cli db seed`
N/A
OR
- [ x] This PR is not applicable for the checklist
=> chore: update Dockerfile to support custom command

packages/console/src/pages/WebhookDetails/WebhookSettings/components/CustomHeaderField/index.tsx
should not check duplicated keys when key is empty
OR
=> fix(console): should not check duplicated keys when key is empty

packages/console/src/components/Tip/ToggleTip/index.module.scss, packages/console/src/components/Tip/ToggleTip/index.tsx
The toggle tip react modal should share the same z-index with other modals, or when a toggle tip is used inside a modal, it'll be covered.
OR
=> fix(console): fix toggle tip z-index on modal layer

packages/cloud/src/libraries/tenants.ts, packages/cloud/src/queries/tenants.ts, packages/cloud/src/routes/tenants.test.ts, packages/cloud/src/routes/tenants.ts, packages/cloud/src/test-utils/libraries.ts, packages/console/src/cloud/pages/Main/Tenants.tsx, packages/console/src/contexts/TenantsProvider.tsx, packages/integration-tests/src/api/tenant.ts, packages/integration-tests/src/tests/api-cloud/tenant.test.ts, packages/schemas/src/seeds/tenant.ts, packages/schemas/src/types/tenant.ts
Update cloud service tenant GET and POST APIs:
1. POST /tenants
- can specify tenant's `name` and `tag` when creating new tenants
- both CloudScope.ManageTenant and CloudScope.CreateTenant can create more than one tenants
- update response guard since we've added `name` and `tag` for tenants
2. GET /tenants
- update response guard since we've added `name` and `tag` for tenants
UTs and call APIs locally.
Also update integration tests.
OR
=> feat(cloud,schemas,cli): update cloud service tenant APIs

packages/cli/src/commands/connector/utils.ts
We need to install connectors to the cloud package after the cloud migration. Intend to leverage the existing connector install logic in our @logto/cli
- Export the `fetchOfficialConnectorList` 
- Extract an `addConnectorsToPath` function from the original `addConnectors` unit method. Instead of accepting a logto instance path, allow install connectors to any given director.  Thus we can install connectors to a cloud-based directory. 
```js
// cloud/packages/cloud/,script/installConnectors.js
import {fetchOfficialConnectorList, addConnectorsToPath} from '@logto/cli/lib/command/connectors/utils.js' 
const officialConnectors = await fetchOfficialConnectorList();
await addConnectorsToPath('./connectors', officialConnectors);
```
test the cli command locally. 
OR
=> feat(cli): export add connectors utils

packages/core/src/libraries/hook/index.test.ts
We should use fake time in unit tests, or the test may fail by chance.
UT
OR
=> chore(test): use fake time in webhook unit tests

.changeset/silly-impalas-pump.md, packages/core/src/libraries/hook/index.test.ts, packages/core/src/libraries/hook/index.ts, packages/core/src/routes/interaction/actions/submit-interaction.test.ts, packages/core/src/routes/interaction/actions/submit-interaction.ts, packages/core/src/routes/interaction/consent.ts, packages/core/src/routes/interaction/index.ts, packages/core/src/routes/interaction/middleware/koa-interaction-details.ts, packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts, packages/core/src/routes/interaction/middleware/koa-interaction-sie.ts, packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts, packages/integration-tests/src/helpers/interactions.ts, packages/integration-tests/src/tests/api/hook/hook.trigger.test.ts
In this PR, we need to improve & fix the following problems:
- The current hook trigger logic relies on specific interaction details that may not have consistent data schema. 
- During the reset password process, the interaction details are cleared upon completion, which makes the reset password hook fails to trigger when needed.
- Store a hook-related interaction context in the middleware before processing an interaction; this context will be used when triggering hooks and will not lose during the interaction process.
- Add a hook-related interaction result variable in the middleware; we will trigger related hooks after we have processed the interaction when the result is assigned during the interaction process.
- Refactor and rename `triggerInteractionHooksIfNeeded` to …
=> fix(core): trigger reset password hook

packages/core/src/routes/admin-user.test.ts, packages/core/src/routes/admin-user.ts, packages/integration-tests/src/api/admin-user.ts, packages/integration-tests/src/tests/api/admin-user.test.ts
When verifing password, the input `password` in the request payload should not be an empty string. If the input password is an empty string, the API should return 400 instead of 500 error.
Locally tested. UT and IT will be updated tomorrow
=> fix(core): verify an empty string password should return 400 instead of 500

packages/core/src/libraries/domain.test.ts, packages/core/src/libraries/domain.ts, packages/core/src/routes/domain.test.ts, packages/core/src/routes/domain.ts
Call Cloudflare API to create and get remote ID before inserting to our database, this can prevent the hanging domain (without remote ID) from creation.
UTs
OR
=> fix(core): get cf id before insert

.changeset/odd-pumpkins-poke.md, packages/connectors/connector-aliyun-dm/src/utils.ts, packages/connectors/connector-aliyun-sms/src/utils.ts
1. Fix Aliyun DM and SMS connectors' signature process, should remove undefined keys before generating signature.
2. Use `generateStandardId` to generate a random signature nonce.
3. Align timestamp to the format of 'YYYY-MM-DDThh:mm:ssZ'.
Attached is the [up-to-date document](https://help.aliyun.com/document_detail/29440.html?spm=a2c4g.29442.0.0.361d3581nNwZqv).
Tested locally, can send and receive email/sms successfully.
Before this change, the client-generated signature does not match the Aliyun server-generated signature if `From Alias` is not given.
OR
=> fix(connector): signature method for both Aliyun DM and SMS

packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx, packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
The vanillajs examples still use the outdated  `logtoClient.isAuthenticated` that doesn't work with the latest SDKs, this PR replaces them with `await logtoClient.isAuthenticated()`
I will create a separate PR for the docs repo as well.
**Note:** I am unsure if the other JS libraries like next/vue/react/etc. also need this change, as I am not familiar with how to set up/use them.
Docs only
OR
=> fix(console): use correct vanillajs isAuthenticated method in guide

packages/app-insights/src/node.ts
AppInsights only shows error message and stack which is not convenient for debugging. This PR stringify the error object to provide a better experience.
=> refactor: stringify error before report to AppInsights

packages/core/src/libraries/hook/index.test.ts, packages/core/src/libraries/hook/index.ts, packages/core/src/routes/hook.ts, packages/integration-tests/src/tests/api/hook/hook.testing.test.ts
We should return 422 if failed to send a webhook test payload to the endpoint since we will record 500 errors in our error-tracking service.
UT & IT & Test locally.
OR
=> refactor(core): return 422 if failed to send a webhook test payload

packages/console/src/pages/AuditLogDetails/index.tsx, packages/schemas/src/types/log/hook.ts
Hide some log info from headers if the log type is webhook. As all the following properties are always empty. 
- ua
- userId
- ip-address
- appid
test locally
OR
=> fix(console): hide some log headers for webhook event

packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/DefaultDomain/index.module.scss, packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/DefaultDomain/index.tsx, packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/index.tsx
- This PR is for code review only since it's blocked by #3938.
- This PR won't be merged unless related PRs it depends on have been completed. 
- These codes are placed under the `console/src/pages/TenantSettings` folder temporarily, and after the #3938 has been complete, we may move them to a cloud-only related code folder if needed.
Add the default domain content for the domains page:
Note:
The `Domains` component is a temporary tab page, and we will have another PR to implement the whole tab page and integrate it onto the `TenantSettings` page after #3938.
OR
=> feat(console): add default domain content for domains page

packages/console/src/containers/AppContent/components/Topbar/Contact/ContactModal/index.module.scss, packages/console/src/containers/AppContent/components/Topbar/Contact/ContactModal/index.tsx, packages/console/src/containers/AppContent/components/Topbar/DocumentNavButton/index.tsx
1. fix console "docs button" bug, now icon is also clickable
2. use `<a>` component for console "get help" buttons.
1. "docs button" icon clickable
2. can preview link on left-bottom corner when hover on "get help" buttons
OR
=> fix(console): doc button and get help link

packages/console/src/components/ImageWithErrorFallback/index.tsx, packages/core/src/middleware/koa-security-headers.ts
remove the crossOrigin settings on the avatar image element. As the original GitHub user avatar URL does not specify the 
Access-Control-Allow-Origin policy.
Before:
After:
OR
=> fix(console): fix github avatar broken issue

packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/components/ActivationProcess/index.tsx, packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/components/CustomDomainHeader/index.tsx, packages/console/src/pages/TenantSettings/tabs/TenantDomainSettings/components/CustomDomain/utils.ts
Remove redundant domain status guard since now we have the type guard for the `DomainStatus` in the core.
Test locally.
OR
=> refactor(console): remove redundant domain status guard

packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/ActivationProcess/index.tsx
According to the new update https://github.com/logto-io/logto/pull/3986, we don't need to config dns for ssl now.
Test locally.
OR
=> refactor(console): remove redundant ssl dns config for custom domain

packages/core/src/oidc/init.ts
Re-enables the OIDC introspection endpoint, which was disabled in https://github.com/logto-io/logto/pull/886. Some applications require this, such as Mediawiki with the OpenIDConnect extension.
I built an image with the change, and used it with an application which requires the endpoint, Mediawiki.
=> feat: enable OIDC introspection endpoint

packages/console/src/mdx-components/UriInputField/index.tsx, packages/console/src/onboarding/pages/About/index.tsx, packages/console/src/onboarding/pages/SignInExperience/index.tsx, packages/console/src/onboarding/pages/Welcome/index.tsx, packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx, packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx, packages/console/src/pages/ApiResources/components/CreateForm/index.tsx, packages/console/src/pages/ApplicationDetails/index.tsx, packages/console/src/pages/Applications/components/CreateForm/index.tsx, packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx, packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx, packages/console/src/pages/Connectors/components/Guide/index.tsx, packages/console/src/pages/Profile/containers/LinkEmailModal/index.tsx, packages/console/src/pages/RoleDetails/RoleSettings/index.tsx, packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx, packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx, packages/console/src/pages/SignInExperience/index.tsx, packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx, packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx, packages/console/src/pages/UserDetails/UserSettings/index.tsx, packages/console/src/pages/Users/components/CreateForm/index.tsx, packages/console/src/pages/WebhookDetails/WebhookSettings/index.tsx, packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx, packages/console/src/utils/form.ts
After upgrading the react-hook-form to v7.42.0, the `isSubmitting` flag does not recover when the submit handler throws.
So we need to catch the error and do nothing if the error is an HTTPError and the status code is not 401 to prevent the `isSubmitting` flag from being stuck.
Reference: https://github.com/orgs/react-hook-form/discussions/10103#discussioncomment-5927542
Test locally.
OR
=> fix(console): reset form state when the submit handler throws

packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx
set RHF default value instead of manually triggering RHF reset().
Previously, the component could return before setting the RHF init value (where empty form can not provider current tenant info). Also, manually triggering RHF `reset()` could lead to too many rerenders.
Before this fix, can easily trigger by switching between sidebar buttons.
After the change, the tenant settings page does not crash again.
OR
=> fix(console): set RHF default value

packages/cloud/package.json, packages/cloud/tsconfig.json, packages/console/package.json, packages/console/src/cloud/hooks/use-cloud-api.ts, packages/console/src/cloud/hooks/use-cloud-swr.ts, packages/console/src/cloud/pages/Main/CreateTenantModal/index.tsx, packages/console/src/cloud/pages/Main/Tenants.tsx, packages/console/src/cloud/pages/Main/index.tsx, packages/console/src/hooks/use-swr-fetcher.ts, packages/console/src/hooks/use-tenants.ts, packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx, packages/integration-tests/src/tests/ui-cloud/smoke.test.ts, pnpm-lock.yaml
- introduce cloud api client
- added `useCloudSwr` hook
- enables auto type inference for SWR hooks and mutation APIs
- fix `useSwrFetcher` types
=> refactor(console): use withtyped client for SWR

packages/cloud/src/middleware/with-security-headers.ts, packages/core/src/middleware/koa-security-headers.ts
Remove the unsafe-inline and unsafe-eval allowance tags. It looks like ApplicationInsights is no longer adding inline script. 
test locally
OR
=> fix: remove unsafe-inline and unsafe-eval

packages/console/src/cloud/pages/Main/index.tsx, packages/integration-tests/src/tests/ui-cloud/smoke.test.ts
Fix cloud UI test URL mismatch.
The `onAdd` method passed to `<Tenants />` component triggers frequent re-rendering of the `useEffect` which automatically create tenant for new registered users. The re-render of this `useEffect` will create tons of tenants for the current use. This caused the redirect to onboarding process timeout.
N/A
OR
=> fix(test): fix cloud UI test create new account idling URL mismatch error

packages/console/src/pages/SignInExperience/index.module.scss, packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/SignInMethodItem.tsx, packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/index.module.scss
Currently, the min-width is set at 540, making the laptop view too big and exceeding the screen size.
So the designer changes the min-width to 510 and updates the gap between sie form and preview from 24px to 12px.
I also removed the redundant `checkbox` class for the signInMethod item since the original implementation is not perfect and will cause the style to break when the min-width is set to 510.
OR
=> style(console): update min-width of the sie page

.changeset/six-starfishes-hide.md, packages/ui/src/Providers/AppBoundary/AppMeta.tsx
Fix the preview class name has been overwritten bug.
Bug:
The preview UI is editable on AC.
Expected behavior:
Preview UI should not allow user interaction.
Cause:
Adding class names using react-helmet overwrites the body class name instead of merging.  Miss use of the react helmet. 
test locally
OR
=> fix(ui): fix preview classname overwrite bug

packages/core/src/middleware/koa-spa-session-guard.test.ts, packages/core/src/middleware/koa-spa-session-guard.ts
When session check failed, redirect to "unknown-session" with current hostname.
Fixed LOG-6314
OR
=> fix(core): fix session not found redirect hostname

packages/core/src/utils/storage/s3-storage.ts
Fixed a bug that broke integration with custom s3.
Added a fallback to "us-east-1" as recommended in [this comment](https://github.com/aws/aws-sdk-js-v3/issues/1845#issuecomment-754832210).
During the test, I found that an incorrectly specified region can still break the integration with Minio if the region specified in Minio itself is different from "us-east-1".
The region setting should still be moved to the S3 provider configuration. My solution is just a quick fix.
Locally
OR
=> fix(core): s3 region fallback

packages/console/src/consts/tenants.ts, packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx
should not block admin tenant owner from creating more tenants.
Logto team members' lives matter.
Can create new tenant since this is admin tenant owner.
Can not create more than three tenants since this is a normal user.
OR
=> fix(console): should not block admin tenant owner from creating more tenants

.changeset/tough-buckets-listen.md, packages/app-insights/jest.config.js, packages/app-insights/package.json, packages/app-insights/src/node.ts, packages/app-insights/src/normalize-error.test.ts, packages/app-insights/src/normalize-error.ts, packages/app-insights/tsconfig.json, packages/app-insights/tsconfig.test.json, packages/cloud/src/middleware/with-error-report.ts, packages/core/src/app/init.ts, packages/core/src/caches/index.ts, packages/core/src/middleware/koa-error-handler.ts, pnpm-lock.yaml
when normalizing an error object, it may have a circular structure especially for http requests / responses. which causes unnecessary 500 response
- implement a custom stringify replacer to address the circular issue.
- make `trackException()` async to force a `void` or `await` before calling it.
added tons of unit tests
=> fix: support circular reference when normalizing errors

packages/ui/src/Layout/AppLayout/index.module.scss, packages/ui/src/Providers/AppBoundary/AppMeta.tsx, packages/ui/src/Providers/AppBoundary/index.module.scss, packages/ui/src/Providers/SettingsProvider/use-preview.ts
fix ui switch platform and theme style messed up bug
Bug: when using the react Helmet concat existing classnames on body, failed to clean up the original platform and theme-related classnames. 
Instead of direct contact, the old classname should render new classnames directly. 
Move the preview classname logic under the AppMeta component as well. Let all the body classnames controlled at a same place. 
Test locally
test locally
OR
=> fix(ui): fix ui preview critical bug

packages/console/src/containers/AppContent/components/Topbar/Contact/index.module.scss, packages/console/src/containers/AppContent/components/Topbar/DocumentNavButton/index.module.scss
text color of docs and help button should be neutral variant 30 (currently is neutral variant 50, which is not right).
OR
=> fix(console): text color of docs and help button

packages/schemas/src/types/system.ts
fix Sendgrid email service config:
1. for sendgrid, only `apiKey` is required, previously the email service guard does not distinguish different providers.
2. also add required `fromName`.
N/A
OR
=> fix(schemas): fix sendgrid email service config

packages/core/jest.config.js, packages/ui/jest.config.ts
Set jest config coverage report to all files.
The default settings only collect the coverage info for all the test-covered files. 
Should cover test missed files as well. 
test localy
OR
=> chore(core,ui): set jest config coverage report to all files

packages/core/src/errors/RequestError/index.ts, packages/core/src/oidc/init.ts
should throw an invalid body request error for all OIDC endpoints' input syntax error
test locally
OR
=> fix(core): add invalid body request error on oidc endpoints

packages/core/src/utils/connectors/index.ts
block logto email connector:
1. enter detail page and change the connector config
2. create logto email connector
Will remove this block when the whole feature is ready for Prod.
1. can not enter detail page:
2. can not create logto email connector:
OR
=> fix(core): block logto email connector (create and enter detail page)

packages/console/src/components/ConnectorForm/ConfigForm/ConfigFormFields/index.tsx, packages/console/src/components/ConnectorForm/ConfigForm/index.tsx, packages/console/src/hooks/use-connector-form-config-parser.tsx, packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx, packages/console/src/pages/Connectors/Guide/index.tsx, packages/console/src/types/connector.ts, packages/console/src/utils/connector-form.ts
The previous ConnectorFormType type directly added the extended custom connector config data to the top-level of the data, whereas the correct approach would be to add it to the config field.
We need to fix it since if the fields in the custom config conflict with the reserved form fields, it can lead to unexpected bugs.
Bug: custom config fields now seat in the top-level of the data
Fixed:
OR
=> fix(console): avoid connector custom config fields conflict with reserved fields

packages/core/src/routes/connector/index.ts, packages/core/src/utils/connectors/index.ts
add `extraInfo` to connector APIs response.
at this stage, `extraInfo` return only `fromEmail` of the email service provider's sender email address for Logto Email connector. In the future, we may extend the use cases of `extraInfo`.
OR
=> refactor(core): add extraInfo to connector GET APIs response

packages/schemas/src/seeds/logto-config.ts, packages/schemas/src/types/logto-config.ts
sync cloud m2m credential to logto config:
1. utils functions and corresponding types' definition
Tested locally, can successfully sync `default` tenant's m2m app credentials.
OR
=> refactor(schemas): sync cloud m2m credential to logto config

packages/cli/src/commands/database/seed/tables.ts, packages/core/src/env-set/index.ts, packages/core/src/libraries/logto-config.ts, packages/core/src/queries/logto-config.ts, packages/core/src/tenants/Libraries.ts, packages/core/src/utils/endpoint.ts, packages/schemas/alterations/next-1688375200-sync-cloud-m2m-to-logto-config.ts, packages/schemas/src/seeds/logto-config.ts
save cloud service m2m app credentials for each tenant.
1. add alteration script to sync cloud service m2m app credentials to `logto_configs` table.
2. sync cloud service m2m app credentials to `logto_configs` when seeding non-admin tenants.
3. add corresponding methods for upcoming use cases:
- add queries/libraries methods for logto/core.
- add `getCloudConnectionEndpoints()` method to expose cloud connections `tokenEnpoint` and API `endpoint`.
niche:
- rename `createDefaultCloudConnectionConfig()` to `createCloudConnectionConfig()` to avoid misleading.
OR
=> refactor(core,schemas,cli): save cloud service m2m app credentials

packages/console/src/cloud/pages/Main/Redirect.tsx, packages/console/src/cloud/pages/Main/index.tsx, packages/console/src/containers/TenantAccess/index.tsx, packages/console/src/contexts/TenantsProvider.tsx, packages/console/src/hooks/use-user-default-tenant-id.ts
introduce and save "user's default tenant id" to custom data, which means the last tenant id that user opened or the first available tenant id. fall back to empty if there's no tenant available.
sorry i'm currently out of bandwidth for writing integration tests for this nice-to-have feature. will try to add some when we refactor the tenant navigation LOG-6474.
also due to this implementation, you may not see the `PATCH` request for local dev since the new page loads too quick. this will also be fixed in LOG-6474.
=> feat(console): save and update user default tenant id

packages/console/src/contexts/TenantsProvider.tsx
temporarily disable `setCurrentTenantId()` after tenant navigation because it will cause unnecessary network requests.
the current approach of switching between tenants is to open a new URL, while `setCurrentTenantId()` only fits the one-router approach (LOG-6474).
switching tenants cause no requests from the current page
=> fix(console): disable unnecessary fetchings when switching tenants

packages/connectors/connector-logto-email/src/constant.ts, packages/core/src/utils/connectors/index.ts
use `isProduction` as logto email service feature switch, users from production env can not access to WIP logto email service.
Can switch cloud service API `endpoint` and `isDemo` properly according to NODE_ENV.
NODE_ENV=production, isDemo = true
otherwise, isDemo = false
OR
=> fix(core,connector): use isProduction as email service feature switch

packages/console/src/pages/ApplicationDetails/index.tsx, packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx, packages/console/src/pages/SignInExperience/index.tsx, packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx, packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/index.tsx
When the connector usage data changes, we will get a brand new `connectorData`, this new data will cause the connector form to be reset.
Other pages may have the same issue, updated together.
We should not update dirty form data, user input should be kept.
This is a legacy issue since the beginning of the project.
We rely on the `useEffect` hook to set the default values of the form, which sometimes causes the form to be reset by `useEffect`.
The correct approach would be to render the form after retrieving the backend data.
- LOG-6514: Refactor: Render Form After the Data is Fetched
OR
=> fix(console): avoid updating dirty form data

packages/console/package.json, packages/console/src/cloud/hooks/use-cloud-swr.ts, packages/console/src/cloud/types/router.ts, packages/console/src/consts/subscriptions.ts, packages/console/src/ds-components/DynamicT/index.tsx, packages/console/src/ds-components/Table/index.tsx, packages/console/src/hooks/use-subscription-plans.ts, packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanName/index.tsx, packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaGroupKeyLabel/index.tsx, packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/PlanQuotaKeyLabel/index.tsx, packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.module.scss, packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.tsx, packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/utils.ts, packages/console/src/pages/TenantSettings/Subscription/index.tsx, packages/console/src/types/subscriptions.ts, pnpm-lock.yaml
Add plan quota table according to the design file (see [Figma](https://www.figma.com/file/KYdX2tPPOw3DEag0D3hAxr/%F0%9F%86%9A-Console-Payment?type=design&node-id=1-31308&mode=dev))
- Bring back `useCloudSwr` from this [PR](https://github.com/logto-io/logto/pull/4074#discussion_r1241076358)
- Update `<DynamicT />` props type to support [plural rendering](https://react.i18next.com/latest/trans-component#plural) in reactI18next
- LOG-6513: Support non-empty payload route requests for the `useCloudSwr` hook
OR
=> feat(console): add plan quota table

packages/schemas/src/models/tenants.ts
The type definition for `tenantInfoGuard` is incorret, resulting the lost of method "extend", remove it, use auto type infer.
Existing CI tests.
OR
=> fix(schemas): remove incorrect tenantInfoGuard type

packages/schemas/package.json, packages/schemas/src/models/tenants.ts, pnpm-lock.yaml
- upgrade withtyped packages
- specify tenant model schema to `public` since we're changing the search_path to cloud only in cloud queries
locally tested with cloud, can enter console (with tenant-related APIs called)
=> refactor(schemas): specify tenants table schema

packages/schemas/src/types/system.ts
update email service data guard, we will store and manage templates in send grid side and use `template_id` for indexing.
See discussion in [this slack thread](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1689065561696669).
Tested locally along with the change in `cloud` repo.
OR
=> refactor(schemas): update email service data guard

packages/connectors/connector-logto-email/src/constant.ts, packages/connectors/connector-logto-email/src/index.ts, packages/core/src/routes/connector/index.ts, packages/core/src/tenants/SystemContext.ts, packages/core/src/utils/connectors/extra-information.ts, packages/core/src/utils/connectors/index.ts, packages/toolkit/connector-kit/src/types.ts
store to and get `fromEmail` (for console display use) from logto email connector's metadata.
- background:
`fromEmail` is in the configuration of the email service vendor, used to represent the sender address of the email vendor. It cannot be modified by Logto users from the logto email service connector but needs to be displayed there.
- current status:
We stored the email service config in the systems table of the DB. Later the systems table will be separated into logto/core's and logto/cloud's. The email service config will be moved to the logto/cloud's systems table (since this will only be used by Logto cloud). As a result, the methods in logto/core will no longer be able to access the value of `fromEmail` in the config.
- expected status after the change:
The best practice is to …
=> refactor(core,connector): store and get fromEmail from logto email connector

packages/connectors/connector-mock-email-alternative/src/index.ts, packages/connectors/connector-mock-email-alternative/src/types.ts, packages/core/src/database/update-where.test.ts, packages/core/src/database/update-where.ts, packages/core/src/routes/connector/index.patch.test.ts, packages/core/src/routes/connector/index.ts, packages/integration-tests/src/tests/api/connector.test.ts
Fix patch connector API cannot reset `config` / `metadata` bug.
Previously, `cleanDeep` will remove empty objects and hence reset `config` or `metadata` field to {} is not accepted by API. It's because `cleanDeep` will remove empty object values' keys before this change.
Update logto mock email alternative connector config guard to accept empty object config, so that we can test the case via integration test.
Add UT and IT to cover this case and tested locally.
OR
=> fix(core,connector): fix patch connector api cannot reset config/metadata bug

packages/console/src/cloud/types/router.ts, packages/console/src/components/PlanDescription/index.module.scss, packages/console/src/components/PlanDescription/index.tsx, packages/console/src/consts/subscriptions.ts, packages/console/src/hooks/use-current-subscription-usage.ts, packages/console/src/hooks/use-subscription-plans.ts, packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx, packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/NextBillInfo/index.module.scss, packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/NextBillInfo/index.tsx, packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/PlanUsage/index.module.scss, packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/PlanUsage/index.tsx, packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.module.scss, packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx, packages/console/src/pages/TenantSettings/Subscription/index.tsx
Add the current plan form for the subscription page according to the design: https://www.figma.com/file/KYdX2tPPOw3DEag0D3hAxr/%F0%9F%86%9A-Console-Payment?type=design&node-id=1-24947&mode=dev
The `PlanDescription` component is added to the `@/components` folder since it will be used in other pages in up coming PRs
OR
=> feat(console): add current plan form for subscription page

package.json, pnpm-lock.yaml
Upgraded commitlint packages using `pnpm up "@commitlint/*@latest"` -w to ensure they point to to typescript@^5.0.0.
This is simply a chore, changes that do not relate to a fix or feature and don't modify src or test files
This PR is not applicable for the checklist
=> chore: upgrade commitlint packages

packages/core/src/routes/application.test.ts, packages/core/src/routes/application.ts
Support retrieving all applications without pagination because we need to separately count the number of m2m applications and other applications in some scenarios.
This approach is considered because we currently have limitations on applications (a maximum of 3 for free plans and 20 for hobby plans).
Additionally, in practical situations, each tenant's application count is not expected to be very high, so fetching all applications won't impact performance.
UT & IT passed & test locally.
OR
=> feat(core): support fetching all applications without pagination

packages/console/src/components/ContactUsPhraseLink/index.tsx, packages/console/src/components/QuotaGuardFooter/index.module.scss, packages/console/src/components/QuotaGuardFooter/index.tsx, packages/console/src/ds-components/ModalLayout/index.module.scss, packages/console/src/hooks/use-current-subscription.ts, packages/console/src/hooks/use-subscription-plans.ts, packages/console/src/pages/Webhooks/components/CreateFormModal/CreateForm.tsx, packages/console/src/pages/Webhooks/components/CreateFormModal/index.tsx, packages/console/src/pages/Webhooks/index.tsx, packages/console/src/utils/quota.ts
feat(console): apply quota limit for webhooks
- Add a commonly used `QuotaGuardFooter` for all quota limitation notifications on creation modals.
- Add feature switch for subscription-related requests, since now the related functionalities are not only used in cloud-only pages
OR
=> feat(console): apply quota limit for webhooks

packages/connectors/connector-logto-email/src/index.ts
update the parse of API call response since the update on the response  of the cloud GET /emails/usage API.
Tested locally along with the change on cloud API (see [this change](https://github.com/logto-io/cloud/pull/99)), can successfully get the usage.
OR
=> chore(connector): update the parse of email usage api response

packages/console/src/hooks/use-tenant-pathname.ts
In the old `getUrl` implementation, we want to use `useHref('/')` to get a URL that can be used to link to the given `to` location, but the react-router does not work as what the [doc](https://reactrouter.com/en/main/hooks/use-href) says. The `useHref('/')` always returns `/`, and the origin is missing.
So we prepend the origin to the URL to get a correct result.
Test locally.
OR
=> fix(console): add origin for `getUrl`

packages/console/src/cloud/hooks/use-cloud-api.ts, packages/console/src/utils/subscription.ts
In the original implementation, when we call `isExceededQuotaLimitError`, the response error body will be read, but if the error is not an `ExceedQuotaLimitedError`, the `toastResponseError` function will read the error body once again. At this time, we will get a "body stream already read" error.
Test locally.
OR
=> fix(console): avoid reading response error body more than once

packages/console/src/ds-components/ConfirmModal/index.tsx, packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx, packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
refactor(console): hide cancel button for not eligible switch plan modal
OR
=> refactor(console): hide cancel button for not eligible switch plan modal

packages/console/src/containers/TenantAccess/index.tsx, packages/console/src/contexts/AppDataProvider.tsx
user endpoints should have different cached values per tenant, while it's used to be only one cached value. it causes 401 when switching tenant because the endpoint is stable. use `useSWRImmutable` for user endpoint to fix it.
=> fix(console): use SWR for user endpoint

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx, packages/console/src/components/PlanDescription/index.tsx, packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
Use plan id to index plan descriptions since now we have reserved plan ids, so we should not rely on the old reserved plan name to index plan descriptions.
Test locally.
OR
=> refactor(console): use plan id to index plan descriptions

packages/schemas/alterations/next-1688375200-sync-cloud-m2m-to-logto-config.ts
use pool query to tolerate empty query results.
When users have no applicable m2m apps for cloud service in the table, `pool.many` could throw error while `pool.query` returns an empty array.
Tested locally on @charIeszhao 's local DB.
OR
=> fix(schemas): use pool.query to tolerate empty query results

packages/console/src/pages/GetStarted/FreePlanNotification/index.module.scss
the free plan notification's margin-bottom should be 16px, not 24px
Test locally.
OR
=> style(console): fix free plan notification margin-bottom

packages/console/src/pages/TenantSettings/Subscription/PlanQuotaTable/index.tsx
Odd rows of the plan quota table should have a colored background.
OR
=> chore(console): update quota table row style rules

packages/cli/src/commands/translate/sync-keys/utils.ts
a missing commit for #4265. use `tryThat()` to enforce exit since `trySafe()` could return `undefined`
CI
=> refactor(cli): use `tryThat()` to enforce exit

packages/console/src/pages/ApplicationDetails/index.tsx
The previous refactor #4191 forget to update the pathname matching method with the new `match` method, this causes the application creation guidance missing after an application is created.
Test locally.
OR
=> fix(console): display guidance on application created

packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx, packages/console/src/pages/ConnectorDetails/EmailUsage/index.tsx, packages/console/src/pages/ConnectorDetails/index.tsx
get real-time email service usage.
Previously we manually add the usage by 1 when users are testing with the config in the logto email service configuration form. This implementation is not good enough since the current usage on the front-end is not up-to-date, and the manual increment of the usage by 1 also leads to out-of-date display.
We hence manually trigger the GET API to get the real-time email service usage. W/o the `useSWR` config of `keepPreviousData` will cause the data used to render the email service connector detail page cleared and reloaded, which will trigger the page rerender by our current console implementation. This `keepPreviousData` config is brought by swr@v2 and we just have SWR upgraded from v1 and have this config available.
With the change, we …
=> refactor(console): get real time email service usage

packages/console/src/components/AuditLogTable/index.tsx, packages/console/src/consts/logs.ts, packages/core/src/queries/log.ts, packages/core/src/routes/hook.test.ts, packages/core/src/routes/hook.ts, packages/core/src/routes/log.test.ts, packages/core/src/routes/log.ts, packages/integration-tests/src/api/logs.ts, packages/integration-tests/src/tests/api/audit-logs/index.test.ts, packages/integration-tests/src/tests/api/hook/hook.trigger.test.ts, packages/integration-tests/src/tests/api/log.test.ts, packages/schemas/src/types/log/index.ts
filter out webhook logs from audit logs list.
1. Separate the findLogs/countLogs methods to find(Audit|Webhook)Logs/count(Audit|Webhook)Logs, since in our use case, these two kinds of logs should be decoupled.
2. Remove all webhook event types from audit log "filter by event" dropdown option lists.
Updated UTs, ITs and also tested locally, can successfully filter out webhook logs in audit logs list and do not affect the display of webhook logs in hook detail pages.
Before: (webhook log in the list)
After: (webhook log filtered out)
Can not find/select webhook related event type in "filter (audit log) by event" dropdown. (previously these options are presented before `RevokeToken`).
OR
=> refactor(core,console): filter out webhook logs from audit logs list

.changeset/fast-shirts-switch.md, packages/console/src/pages/ApplicationDetails/components/Settings.tsx, packages/console/src/pages/ApplicationDetails/index.tsx, packages/console/src/utils/validator.ts, packages/core/src/routes/application.test.ts, packages/schemas/src/foundations/jsonb-types.ts
unlike redirect uris which may cause critical security issues, allowed cors origins can be loosen in order to enable cross-platform frameworks like CapacitorJS, which uses the URL `capacitor://localhost` for window location and request origin.
can save cors origin `capacitor://localhost` and it worked in the simulator
=> refactor: allow non-http scheme in cors origin

packages/core/src/libraries/quota.ts
The usage of social connectors should not include standard connectors.
Sync with the update of [@logto/cloud](https://github.com/logto-io/cloud/pull/198) to keep accordance for now. Will remove the quota calculation in @logto/core and rely on @logto/cloud, which will be the SSOT.
N/A
OR
=> fix(core): exclude standard connectors when compute social connector usage

packages/console/src/components/ConnectorForm/ConfigForm/ConfigFormFields/index.tsx, packages/console/src/pages/Connectors/Guide/index.tsx
Fix connector post/patch error rendering.
The previous empty-string error (RHF throws an empty string error message when a required field is not filled) will result in `Boolean(error)` being false, which will not trigger the proper error style rendering.
Also, when creating new connectors, the hook `useConnectorApi` has a configuration with `hideToastError`, this will block the toast of error message so that users have no idea how to correct the connector configuration.
This is not an ultimate fix but a hot fix, we will show error messages in-place so that users can know whether did they make wrong configuration.
Tested locally, works fine.
1. Properly render unfilled field.
2. Can toast error when config is not right on creating.
OR
=> fix(console): fix connector post/patch error rendering

packages/console/src/components/MauExceededModal/index.tsx, packages/console/src/components/PaymentOverdueModal/index.tsx
According to the design requirement, MAU exceeded the reminder and the payment overdue reminder just shows for 1 time on the user signed in.
So we should use `useSWRImmutable` to avoid the related data auto-refreshing.
Test locally.
OR
=> refactor(console): use `useSWRImmutable` to avoid redundant subscrtipion data fetching

packages/integration-tests/src/helpers/admin-tenant.ts, packages/integration-tests/src/helpers/index.ts, packages/integration-tests/src/helpers/interactions.ts, packages/integration-tests/src/tests/api/admin-user.roles.test.ts, packages/integration-tests/src/tests/api/admin-user.search.test.ts, packages/integration-tests/src/tests/api/admin-user.test.ts, packages/integration-tests/src/tests/api/connector.test.ts, packages/integration-tests/src/tests/api/dashboard.test.ts, packages/integration-tests/src/tests/api/hook/hook.test.ts, packages/integration-tests/src/tests/api/hook/hook.testing.test.ts, packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts, packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts, packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts, packages/integration-tests/src/tests/api/log.test.ts, packages/integration-tests/src/tests/api/me.test.ts, packages/integration-tests/src/tests/api/resource.test.ts, packages/integration-tests/src/tests/api/sign-in-experience.test.ts, packages/integration-tests/src/tests/api/verification-code.test.ts
Refactor `expectRejects` helper method to support status code checking since now we need to add & test reponse status code for our core APIs.
- replace original `createResponseWithCode` logic with the new `expectRejects` helper method.
CI Passed.
OR
=> refactor(test): refactor `expectRejects` helper method to support status code checking

packages/integration-tests/src/api/admin-user.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/happy-path.test.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
Add sad paths for sign-in with passcode integration tests
Add response status guard for all interaction related APIs, We need do that after all tests is ready since a single flow will not cover all interaction API calls.
OR
=> test: add sad paths for sign-in with passcode flow

packages/core/src/libraries/domain.ts, packages/core/src/utils/cloudflare/index.ts, packages/phrases/src/locales/de/errors/domain.ts, packages/phrases/src/locales/en/errors/domain.ts, packages/phrases/src/locales/es/errors/domain.ts, packages/phrases/src/locales/fr/errors/domain.ts, packages/phrases/src/locales/it/errors/domain.ts, packages/phrases/src/locales/ja/errors/domain.ts, packages/phrases/src/locales/ko/errors/domain.ts, packages/phrases/src/locales/pl-pl/errors/domain.ts, packages/phrases/src/locales/pt-br/errors/domain.ts, packages/phrases/src/locales/pt-pt/errors/domain.ts, packages/phrases/src/locales/ru/errors/domain.ts, packages/phrases/src/locales/tr-tr/errors/domain.ts, packages/phrases/src/locales/zh-cn/errors/domain.ts, packages/phrases/src/locales/zh-hk/errors/domain.ts, packages/phrases/src/locales/zh-tw/errors/domain.ts
When deleting custom domain, ignore the 404 error returned by Cloudflare API, since we are deleting the domain anyway.
Local tested.
=> fix(core,phrases): ignore cloudflare not found when deleting domain

README.md
TRIVIAL AS IS.
@gao-sun I'm curious where we pull in the browserslist dependency? I don't find one in package.json.
=> chore: fix typo in README file

.github/CODEOWNERS, packages/integration-tests/src/api/admin-user.ts, packages/integration-tests/src/helpers/index.ts, packages/integration-tests/src/tests/api/admin-user.search.test.ts, packages/integration-tests/src/tests/ui/bootstrap.test.ts
Add hasActiveUser test case.
This PR includes two updates:
1. Remove the `isAdmin`  property from all the createUser methods.  The users' isAdmin property was dropped a long time ago. Our users' endpoints no longer read this property. Remove this legacy field in the integration test methods. 
2. Resolve the linear issue. Create two Admin console onboarding test cases to cover the `hasActiveUsers` query method. 
- if any active admin user exists, should not redirect the user to the welcome page
- if all the admin users are suspended, should treated as empty active users.  Should redirect the new user to the welcome page. 
- 
test locally
OR
=> test(core): add hasActiveUser test case

packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/sad-path.test.ts
- Add sad paths for sign in with password identifier integration tests
- refactor: align sie config reset logic for interaction api tests
Add response status guard for all interaction related APIs, We need do that after all tests is ready since a single flow will not cover all interaction API calls.
Integration tests
OR
=> test: add sad paths for sign in with password identifier flow

packages/core/src/env-set/create-pool.ts, packages/core/src/env-set/index.ts, packages/shared/src/node/env/GlobalValues.ts
clarify the `isTest` scope。
We have both `isIntegrationTest` and `isTest` defined in the global envSet. 
- isIntegrationTest is used to bypass some run time guard for integration tests.
- isTest is used to mock the DB connector under the unit test env. 
This PR renames the `isTest` to `isUnitTest` for better understanding.
Also makes the EnvSet.isTest private. As it is only used when creating DB connections.
OR
=> refactor(cloud): clarify the isTest scope

.github/workflows/changesets.yml
AS IS.
`BOT_PAT` is unavaiable on fork; or we may use `pull_request_target` but it seems just unrelated trigger.
Ref - https://github.com/logto-io/logto/actions/runs/5804486635/job/15734119233?pr=4302
=> ci: changeset workflow is invalid on pull_request

.zap/rules.conf
replace INFO with IGNORE for the ZAP scanning rules. 
Looks like the INFO setting does not prevent the alert from being thrown. Replace with IGNORE.
test locally using Zap Docker run on cloud dev. 
OR
=> fix: replace INFO with IGNORE in zap rules

packages/core/src/include.d/koa-router.d.ts, packages/core/src/routes/interaction/index.ts, packages/integration-tests/src/api/interaction.ts, packages/integration-tests/src/tests/api/interaction/api-counter-cases/interaction-details-guard.test.ts, packages/integration-tests/src/tests/api/interaction/api-counter-cases/interaction-results-checking.test.ts, packages/integration-tests/src/tests/api/interaction/api-counter-cases/patch-interaction-identifiers.test.ts, packages/integration-tests/src/tests/api/interaction/api-counter-cases/post-send-verification-code.test.ts, packages/integration-tests/src/tests/api/interaction/api-counter-cases/put-interaction-event.test.ts, packages/integration-tests/src/tests/api/interaction/api-counter-cases/put-interaction.test.ts
Add interaction api response status guard and add interaction API counter cases to cover all response status codes.
Thease API counter cases are designed to cover exceptional scenarios of API calls that cannot be covered within the auth flow.
Problem encountered:
When trying to add a `koaGuard` for the `POST /interaction/submit` API, the Typescript toast an error:
Thanks to @simeng-li , he found that when the middleware type uses a combination of more than 3 generic types, TypeScript will incorrectly infers the type as `unknown`.
So we make a type improvement: we ensure that the input types of these 3 middleware do not depend on their preceding types, but solely rely on the types provided by the router.
Note:
This new type might not handle cases where later middleware depends on preceding …
=> test: interaction api counter cases and response status guard

packages/core/src/libraries/domain.test.ts, packages/core/src/libraries/domain.ts
Fix Cloudflare hostname not found error handler, when 404 error occurs, the remaining code need to be run, so a “return” is not correct.
Also add unit test to cover this.
Unit test
=> fix(core): fix cloudflare hostname not found error handler

.changeset/serious-pants-beg.md, packages/cli/src/commands/database/config.ts, packages/cli/src/commands/database/utils.ts
Add key type option for rotating command:
```sh
pnpm cli db config rotate oidc.privateKeys --type rsa 
```
Background: the Cloudflare Zero Trust only support RSA key type.
Local tested, after running the command, the RSA key is prepended:
=> feat(cli): add key type for rotating command

packages/integration-tests/src/tests/ui/connectors/helpers.ts, packages/integration-tests/src/tests/ui/connectors/passwordless-connector-test-cases.ts, packages/integration-tests/src/tests/ui/connectors/passwordless-connectors.test.ts, packages/integration-tests/src/tests/ui/connectors/social-connectors.test.ts, packages/integration-tests/src/ui-helpers/index.ts
Add ui tests for passwordless connectors
- Extract common operactions into helper methods from both passwordless & social connectors tests
- Refactor `waitForToaster` to support waiting for an error toaster
IT
OR
=> test: add ui tests for passwordless connectors

packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
Add max-width to guide card groups.
Maximum allowed width = 4 * maximum-size-cards (460px each) + 3 aisles (12px each) = 1876px
Card layout looks OK even on super large screens
=> fix(console): add max-width to guide card group

packages/console/src/ds-components/CodeEditor/index.module.scss, packages/console/src/ds-components/CodeEditor/index.tsx
remove min-height for readonly code editors since it looks better
=> refactor(console): remove min-height for readonly code editors

packages/console/src/mdx-components-v2/Sample/index.module.scss, packages/console/src/mdx-components-v2/Sample/index.tsx, packages/console/src/pages/Applications/components/Guide/index.tsx
=> fix: logo size in get sample section in app integration guide

packages/console/src/pages/Applications/components/GuideGroup/index.module.scss, packages/console/src/pages/Applications/components/GuideLibrary/index.tsx, packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
Hide category filters from app list empty placeholder. Only show the filters in app creation fullscreen modal view.
Locally tested
=> fix(console): should hide filters from app list empty placeholder

packages/console/src/assets/docs/guides/index.ts
adjust the app guide order
Adjust the app guide order, also remove the web-java and web-csharp two guide entrance. 
OR
=> fix(console): adjust the app guide order

packages/console/src/mdx-components-v2/Steps/FurtherReadings.tsx
Resolve forwardRef warning in debugger console
Tested locally. Warning is gone.
=> fix(console): resolve forwardRef warning in debugger console

packages/console/src/mdx-components-v2/Steps/index.module.scss, packages/console/src/mdx-components-v2/Steps/index.tsx
Click the navigation anchors in each guide should be navigated to the specified step.
=> fix(console): guide navigation anchors should be clickable and jump to the step

packages/console/src/pages/Applications/components/CreateForm/index.tsx, packages/console/src/pages/Applications/components/GuideLibrary/index.tsx, packages/phrases/src/locales/de/translation/admin-console/applications.ts, packages/phrases/src/locales/en/translation/admin-console/applications.ts, packages/phrases/src/locales/es/translation/admin-console/applications.ts, packages/phrases/src/locales/fr/translation/admin-console/applications.ts, packages/phrases/src/locales/it/translation/admin-console/applications.ts, packages/phrases/src/locales/ja/translation/admin-console/applications.ts, packages/phrases/src/locales/ko/translation/admin-console/applications.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts, packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts, packages/phrases/src/locales/ru/translation/admin-console/applications.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts
Remove the "Pro" tag from app creation form for M2M type app in OSS version. Since we don't limit the usage of M2M in OSS distributions.
No "Pro" tag in OSS app creation form for M2M.
=> fix(console): remove pro tag from m2m app creation form in oss version

packages/console/src/onboarding/pages/SignInExperience/sie-config-templates.ts
remove inspire me the phone as identifier option.
Since we removed the phone as identifier option before, the randomly generated SIE can not contain this option either.
OR
=> fix(console): remove inspire me phone as identifier options

packages/console/src/mdx-components-v2/UriInputField/index.module.scss
Add margin around URI input fields in app integration guides.
Before:
After:
=> style(console): add margin around input fields in app guide

packages/console/src/pages/Applications/components/Guide/index.module.scss, packages/console/src/pages/Applications/components/Guide/index.tsx, packages/console/src/pages/NotFound/index.tsx
Manually visit an invalid guide URL will end up showing `404 not found` instead of error stack.
Before:
After:
Manually tested OK. See screenshot above.
=> fix(console): invalid guide url should show 404 not found

packages/connectors/connector-saml/README.md, packages/connectors/connector-saml/src/constant.ts, packages/connectors/connector-saml/src/index.ts, packages/connectors/connector-saml/src/types.ts
1. Fix SAML connector response guard.
Currently in SAML connector `getUserInfo`  method, the response guard only allow string record typed response data. 
When testing AzureAD SAML connector, its response data contains a string array typed value: 
```jsonc
"error": {
"message": "Error: ConnectorError: {\"issues\":[{\"code\":\"invalid_type\",\"expected\":\"string\",\"received\":\"array\",\"path\":[\"http://schemas.microsoft.com/claims/authnmethodsreferences\"],\"message\":\"Expected string, received array\"}],\"name\":\"ZodError\"}"
},
```
Update allow `string.array() ` for the response data.  
2. Update the connector config, set the idp signInEndpoint optional. 
- this field is used for idp initialed sign-in sessions. (currently logto does not support that)
- in AzureAD this field is also …
=> fix(connector): fix saml connector response guard

packages/console/src/components/SessionExpired/index.tsx, packages/console/src/consts/tenants.ts, packages/console/src/containers/AppContent/components/Topbar/UserInfo/index.tsx, packages/console/src/containers/ProtectedRoutes/index.tsx, packages/console/src/hooks/use-redirect-uri.ts, packages/console/src/pages/Welcome/index.tsx
since we now save the redirect path in the session storage, there's no need to add the tenant id to the sign-in redirect uri, thus we can save tons of entries in the OIDC client metadata.
=> refactor(console): align sign-in/out redirect uris

packages/console/src/containers/ErrorBoundary/index.tsx
Remove `unhandledrejection` event listener from `ErrorBoundary` component, in order not to show `TypeError: Failed to fetch` when any 3rd party lib or script is blocked by client or failed in prod env.
Pending Cloud prod online testing.
=> fix(console): remove 'unhandledrejection' listener from ErrorBoundary

packages/console/src/hooks/use-api.ts, packages/console/src/hooks/use-redirect-uri.ts
a fix of #4385, explicitly use `/` for `useHref` otherwise the function will return the path of the current location instead of the root path.
passed CI in https://github.com/logto-io/cloud/pull/250
=> fix(console): use correct sign-out redirect uri for api hooks

packages/cli/src/commands/database/seed/cloud.ts, packages/cli/src/commands/database/seed/tables.ts
This PR refactors the cloud service M2M application seeding logic.
- extract a common util method for cloudServiceApplication creation
- add the cloud service M2M seeding for admin tenant as well
@wangsijie  need to clean up the OSS default tenant Cloud Service separately.  Have to keep the code in place for OSS DB seeding, otherwise the DB alteration validation will fail. 
test locally
OR
=> refactor(cli): add server connection application to the admin tenant

packages/core/package.json, packages/core/src/middleware/koa-tenant-guard.test.ts, packages/core/src/middleware/koa-tenant-guard.ts, packages/core/src/routes/init.ts, packages/phrases/src/locales/de/errors/subscription.ts, packages/phrases/src/locales/en/errors/subscription.ts, packages/phrases/src/locales/es/errors/subscription.ts, packages/phrases/src/locales/fr/errors/subscription.ts, packages/phrases/src/locales/it/errors/subscription.ts, packages/phrases/src/locales/ja/errors/subscription.ts, packages/phrases/src/locales/ko/errors/subscription.ts, packages/phrases/src/locales/pl-pl/errors/subscription.ts, packages/phrases/src/locales/pt-br/errors/subscription.ts, packages/phrases/src/locales/pt-pt/errors/subscription.ts, packages/phrases/src/locales/ru/errors/subscription.ts, packages/phrases/src/locales/tr-tr/errors/subscription.ts, packages/phrases/src/locales/zh-cn/errors/subscription.ts, packages/phrases/src/locales/zh-hk/errors/subscription.ts, packages/phrases/src/locales/zh-tw/errors/subscription.ts, packages/toolkit/connector-kit/package.json, pnpm-lock.yaml
Add tenant is suspended guard to all management apis.
- bump the `withTyped/client` version and `@logto/cloud` version
- add new `koaTenantGuard` middleware. if is cloud, fetch the tenant info from cloud server and throw error if tenant is suspended. 
- apply the `koaTenantGuard` to the management api routes. 
test locally
OR
=> feat(core): add tenant is suspended guard

packages/ui/src/hooks/use-social-callback-handler.ts, packages/ui/src/utils/social-connectors.ts
This PR fixes how we handle the social connector callback storage. We do not remove the callback url from the session storage after we're done with the whole connection flow. This becomes as an issue when implementing a **Settings** page like functionality in an application & callback url is your application instead of Logto.
This is the flow:
1. Implement a settings page like the one available inside Logto cloud offering, where we have the option to connection multiple social profiles for a user
2. Use a custom logic for handling `link-identity` functionality using the [/api/users/:userId/identities](https://docs.logto.io/api/#tag/Users/paths/~1api~1users~1:userId~1identities/post). This also means that you need to use a different callback url that the logto callback url. This is what …
=> fix: remove connector link from session storage

packages/console/src/mdx-components-v2/UriInputField/index.module.scss, packages/console/src/mdx-components-v2/UriInputField/index.tsx
Fix the issue that unexpected margin top was added to all form elements across the admin console app, which was introduced by using element selector CSS in a mdx component.
Parcel compiles SCSS from all mdx components in a separated css file and this css file will affect all DOM elements globally. We should be aware of this and avoid using globally impactful CSS selectors in mdx components.
Locally tested and unexpected form margin top is gone.
=> fix(console): remove unexpected margin top from form elements

packages/console/src/containers/AppContent/components/Topbar/TenantSelector/index.tsx, packages/console/src/containers/TenantAccess/index.tsx, packages/console/src/hooks/use-user-default-tenant-id.ts
remove the automatic default tenant id update logic since it causes infinite loop and it's hard to debug. update on manually switching only to make it more clear and maintainable.
- manually switch tenant multiple times, default tenant id update and no infinite loop
=> fix(console): update default tenant id on manual navigation only

packages/console/src/pages/GetStarted/FreePlanNotification/index.module.scss
Remove unnecessary margin space on get-started page.
Before:
After:
~~- [ ] docs~~
OR
=> fix(console): block margin should be the same on get-started page

packages/schemas/src/types/system.ts, packages/toolkit/connector-kit/src/types.ts
Update input params type of SendMessageFunction.
Previously, we included the email service branding info as optional in the params, which is not used in @logto/core. The guard used to generate the payload data type is only used by @logto/cloud send email API.
The optional branding info defined in type could confuse community developers, we hence removed the branding info part of SendMessageFunction input parameter type and will update the guard used by @logto/cloud API in upcoming PR.
Hold until the integration tests on cloud service APIs are added in [this PR](https://github.com/logto-io/cloud/pull/211).
Covered by CI.
OR
=> refactor(toolkit): update input params type of SendMessageFunction

packages/core/src/middleware/koa-security-headers.ts, packages/ui/src/index.html
This PR address the following legacy issues:
1. Add the app insights endpoint to the allow list of OSS AC. So you won't see the annoying CORS error event with OSS version of AC. (This should not matter for our OSS users, as they do not have a valid Azure app insights report enabled)
2. Fix the warning message in preview and demo-app, preload link were never used.
- Under preview mode, all the `SIE` settings were load from the iframe post messages directly instead of send out the query requests. So all the preload links are useless
- Demo app sign-in page come with a `no_cache` flag, which force to load the `SIE` and `phrases` request under a no-cache mode. The original preload link need to add the `no_cache` flag accordingly. 
test locally
- ~~[ ] `.changeset`~~
- ~~[ ] unit tests~~
- ~~[ …
=> fix(core,ui): clear ui preload link not used warning

packages/console/src/hooks/use-window-resize.ts, packages/console/src/pages/Applications/components/GuideGroup/index.tsx, packages/console/src/pages/GetStarted/index.tsx
- Add missing section titles in get-started page
- Improve responsive rules and show 2,3 or 4 guide cards in one row based on current page width
~~- [ ] docs~~
OR
=> refactor(console): add missing section title and adjust card layout in get-started page

packages/console/src/ds-components/FormField/index.module.scss, packages/console/src/ds-components/FormField/index.tsx, packages/console/src/onboarding/pages/SignInExperience/index.module.scss, packages/console/src/onboarding/pages/SignInExperience/index.tsx, packages/console/src/onboarding/pages/Welcome/index.module.scss, packages/console/src/onboarding/pages/Welcome/index.tsx, packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.module.scss, packages/console/src/pages/ConnectorDetails/ConnectorContent/EmailServiceConnectorForm/index.tsx, packages/console/src/pages/SignInExperience/tabs/Branding/BrandingForm.tsx, packages/console/src/pages/SignInExperience/tabs/index.module.scss
Per our design, we have 2 spacing sizes for the `FormField` component.
In normal fields, the spacing is 4px.
In fields which contains a large block content, the spacing is 8px.
In the old implementation, we add classes manually to control the spacing, later we found that this should be a seperated style props of the `FormField` component.
Test locally.
OR
=> refactor(console): add headline spacing prop for `FormField` component

packages/console/src/components/CreateConnectorForm/PlatformSelector/index.module.scss, packages/console/src/components/CreateConnectorForm/index.tsx
reorg connector creation modal.
Previously, the select on platform for some cross-platform connector located at the bottom of the modal. Since standard connectors do not need to select specific platform (they are all universal connector), we move the platform select part before standard connectors.
OR
=> refactor(console): reorg connector creation modal

packages/console/src/mdx-components/UriInputField/index.tsx
Fix error message display in redirect URI input field in SDK guides
Before:
After:
~~- [ ] docs~~
OR
=> fix(console): redirectUri input error message should be displayed properly

packages/console/src/pages/Applications/components/Guide/index.module.scss
Fix the issue that code editor text background is weird in light theme mode.
Looks normal now
~~- [ ] docs~~
OR
=> fix(console): code editor text background

packages/console/src/assets/docs/guides/web-go/README.mdx, packages/console/src/pages/Applications/components/Guide/index.module.scss
Selected text in Go SDK guide should not have unexpected shadows.
- Replace all tabs with spaces
- Fixed a typo in Go SDK guide
Before:
After:
~~- [ ] docs~~
OR
=> fix(console): selected text in go sdk guide should not have shadows

packages/core/src/routes/interaction/index.ts, packages/core/src/routes/interaction/utils/find-user-by-identifier.ts, packages/core/src/routes/interaction/utils/validate-password.ts
- check personal info when setting passwords in the main flow
- validate password after other validations, thus we can keep more context in the audit log
more tests will be added after bug bash
=> refactor(core): check personal info when setting password

packages/schemas/alterations/next-1694418765-specify-check-role-type-function-to-be-public-schema.ts, packages/schemas/tables/applications_roles.sql, packages/schemas/tables/roles.sql, packages/schemas/tables/users_roles.sql
fix check role type fucntion's db schema.
Previously, we did not specify the DB schema of the function `check_role_type`. The fact is, cloud may call this function under `cloud` DB schema and can not find out `public.check_role_type`. We hence should specify the DB schema of this function.
OR
=> fix(schemas): specify function db schema of check_role_type

.github/workflows/integration-test.yml
same as https://github.com/logto-io/cloud/pull/274
see this [workflow run](https://github.com/logto-io/cloud/actions/runs/6143792997/job/16668464353), failed with logs shown
=> ci: always show logs for integration tests

.vscode/settings.json, packages/core/package.json, packages/core/src/routes/status.openapi.json, packages/core/src/routes/swagger.test.ts, packages/core/src/routes/swagger.ts
support supplementary openapi json files (ends with `.openapi.json`) under `packages/core/src/routes`. the file content will be deeply merged to the generated data.
looks good
=> chore(core): add supplementary openapi json

.changeset/mean-jeans-clap.md, packages/console/src/hooks/use-redirect-uri.ts
Hot fix: The app should not crash when inputting verification code in user profile page in admin console.
~~- [ ] docs~~
OR
~~- [] This PR is not applicable for the checklist~~
=> fix(console): input verification code in profile page should not crash the app

packages/console/src/components/RoleScopesTransfer/components/SourceScopesBox/index.tsx, packages/console/src/components/RoleScopesTransfer/index.tsx, packages/console/src/consts/env.ts, packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx, packages/console/src/pages/RoleDetails/RolePermissions/index.tsx, packages/console/src/pages/Roles/components/CreateRoleForm/index.module.scss, packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx, packages/phrases/src/locales/de/translation/admin-console/roles.ts, packages/phrases/src/locales/en/translation/admin-console/roles.ts, packages/phrases/src/locales/es/translation/admin-console/roles.ts, packages/phrases/src/locales/fr/translation/admin-console/roles.ts, packages/phrases/src/locales/it/translation/admin-console/roles.ts, packages/phrases/src/locales/ja/translation/admin-console/roles.ts, packages/phrases/src/locales/ko/translation/admin-console/roles.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/roles.ts, packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts, packages/phrases/src/locales/ru/translation/admin-console/roles.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/roles.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/roles.ts
Add role type selection radio button for role creation modal.
1. should also show management API scopes for m2m roles.
OR
=> feat(console,phrases): add type selection for role creation modal

.changeset/lucky-wolves-buy.md, packages/core/src/utils/storage/index.ts, packages/core/src/utils/storage/s3-storage.ts, packages/schemas/src/types/system.ts
Support region option for s3 storage.
`region` is required for s3, previously, it is derived from `endpoint`, this is not working for  other s3-compatible service which is not fit the expected endpoint format.
Now, `region` and `endpoint` are all optional, the user can choose either one.
Local tested with real s3 service.
OR
=> feat(core,schemas): support region option for s3 storage

packages/core/src/middleware/koa-security-headers.ts
Allow UI unsafe inline script in the CSP header. 
test locally
OR
=> fix(core): allow ui unsafe inline script

packages/console/src/containers/ConsoleContent/Sidebar/index.tsx, packages/integration-tests/src/tests/console/bootstrap.test.ts
fix sidebar highlight issue and add integration test accordingly
=> fix(console): highlight current tab in sidebar

packages/console/src/assets/docs/guides/m2m-general/README.mdx, packages/console/src/mdx-components/ApplicationCredentials/index.module.scss, packages/console/src/pages/ApplicationDetails/components/AppGuide/index.tsx
Improve M2M app guide content. Previously, there were issues with the endpoint display.
- The endpoint should display custom domain first, instead of always showing the default tenant ID
- Should not have double slashes in endpoint URL
- The basic authorization credential should use the base64 encoded value of the real-time app id and app secret combination.
Locally tested
~~- [ ] docs~~
OR
=> refactor(console): improve m2m app guide content

packages/console/src/assets/docs/guides/m2m-general/README.mdx, packages/console/src/assets/docs/guides/native-android-java/README.mdx, packages/console/src/assets/docs/guides/native-android-kt/README.mdx, packages/console/src/assets/docs/guides/native-capacitor/README.mdx, packages/console/src/assets/docs/guides/native-flutter/README.mdx, packages/console/src/assets/docs/guides/native-ios-swift/README.mdx, packages/console/src/assets/docs/guides/spa-react/README.mdx, packages/console/src/assets/docs/guides/spa-vanilla/README.mdx, packages/console/src/assets/docs/guides/spa-vue/README.mdx, packages/console/src/assets/docs/guides/web-asp-net-core-mvc/README.mdx, packages/console/src/assets/docs/guides/web-asp-net-core/README.mdx, packages/console/src/assets/docs/guides/web-express/README.mdx, packages/console/src/assets/docs/guides/web-go/README.mdx, packages/console/src/assets/docs/guides/web-gpt-plugin/README.mdx, packages/console/src/assets/docs/guides/web-next-app-router/README.mdx, packages/console/src/assets/docs/guides/web-next/README.mdx, packages/console/src/assets/docs/guides/web-outline/README.mdx, packages/console/src/assets/docs/guides/web-php/README.mdx, packages/console/src/assets/docs/guides/web-python/README.mdx, packages/console/src/assets/docs/guides/web-remix/README.mdx, packages/console/src/components/Guide/index.tsx, packages/console/src/pages/ApplicationDetails/components/AppGuide/index.tsx
- Remove `alternativeEndpoint` from all app guides and apply custom domain to `endpoint` directly
- Add border radius effect to some screenshots used in guides
Locally tested OK, pending online test for custom domain display
~~- [ ] docs~~
OR
=> refactor(console): remove alternative endpoint from app guides

packages/console/src/components/UserAvatar/index.module.scss, packages/console/src/components/UserAvatar/index.tsx
Avatars should stack on each other in the avatar group
~~- [ ] docs~~
OR
=> fix(console): grouped avatars should stack on each other

packages/core/src/routes/role.test.ts, packages/core/src/routes/role.ts, packages/schemas/src/types/role.ts
Should show user initials as avatar in roles, even if the user doesn't have name (display name). Should fallback the display logic to username and email initials to construct the initial avatar.
Before:
After:
~~- [ ] docs~~
OR
=> fix(console): should show user initial letter avatar in roles

packages/console/src/components/RoleEntitiesTransfer/components/TargetEntityItem/index.module.scss, packages/console/src/components/RoleEntitiesTransfer/components/TargetEntityItem/index.tsx, packages/console/src/components/RoleScopesTransfer/components/ResourceItem/index.tsx, packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.module.scss, packages/console/src/components/RoleScopesTransfer/components/TargetScopeItem/index.tsx, packages/console/src/components/UserRolesTransfer/components/TargetRoleItem/index.module.scss, packages/console/src/components/UserRolesTransfer/components/TargetRoleItem/index.tsx
All source and target items in `Transfer` component should be rendered as 40px.
1. Assign roles to user: 
2. Assign users to role:
3. Assign permissions to role:
~~- [ ] docs~~
OR
=> fix(console): transfer items should all be rendered as 40px in height

packages/console/src/components/DetailsForm/index.module.scss
Tabs in details form should not have unexpected margin-top. Use flex `gap` instead of `:not(:first-child)` + `margin-top` in CSS to solve the issue.
Before:
Now:
GREAT AGAIN!
~~- [ ] docs~~
OR
=> fix(console): detail form tabs should not have unexpected margin-top

packages/console/src/components/ContactUsPhraseLink/index.tsx, packages/console/src/ds-components/Switch/index.module.scss, packages/console/src/pages/Mfa/MfaForm/index.module.scss, packages/console/src/pages/Mfa/MfaForm/index.tsx
feat(console): add quota paywall for mfa feature
- Update the disable style of the `Switch` compontent according to the design system
- Remove `target=_blank` from the `ContactUsPhraseLink` since it's redundant
LOG-7098: This feature is cloud only, need to add UI tests in the cloud repo when this PR is merged in to the cloud.
Test locally.
OR
=> feat(console): add quota paywall for mfa feature

packages/console/package.json, packages/console/src/hooks/use-invoices.ts, packages/console/src/pages/TenantSettings/BillingHistory/index.tsx, pnpm-lock.yaml
Previously we had an issue on expired invoice links.  When is invoice is finalized or overdue, the original stripe-hosted invoice page URL will expire in 30 days.  
So we need to retrieve a new one from Stripe every time, just to make sure the URL is not expired. Please check [cloud#298](https://github.com/logto-io/cloud/pull/298) for more details.
Instead of using the hostedInvoiceUrl link from invoice DB, we call the Logto cloud endpoint to retrieve a new invoice url. 
- update the cloud dependency to pick up the latest GET `/api/tenants/:tenantId/invoices/:invoiceId/hosted-invoice-url` API
- Remove the URL link, and implement an onClick callback method instead. 
test locally.
(The invoice page integration test in still in the todo list)
OR
=> refactor(console): retrieve latest invoice id from stripe

packages/core/src/sentinel/basic-sentinel.test.ts, packages/core/src/sentinel/basic-sentinel.ts, packages/core/src/test-utils/query.ts, packages/schemas/src/types/sentinel.ts
implement a basic sentinel that blocks a user after 5 failed attempts in 1 hour. the definition of "attempt" including both verification code and password submission.
unit tests
=> feat(core): init basic sentinel

packages/cli/src/commands/translate/sync-keys/utils.ts, packages/core/jest.setup.js, packages/core/src/libraries/hook/index.test.ts, packages/core/src/libraries/sign-in-experience/sign-up.test.ts, packages/core/src/middleware/koa-connector-error-handler.test.ts, packages/core/src/middleware/koa-error-handler.ts, packages/core/src/middleware/koa-oidc-error-handler.test.ts, packages/core/src/middleware/koa-oidc-error-handler.ts, packages/core/src/oidc/init.ts, packages/core/src/tenants/Tenant.ts, packages/phrases/src/locales/de/errors/oidc.ts, packages/phrases/src/locales/en/errors/oidc.ts, packages/phrases/src/locales/es/errors/oidc.ts, packages/phrases/src/locales/fr/errors/oidc.ts, packages/phrases/src/locales/it/errors/oidc.ts, packages/phrases/src/locales/ja/errors/oidc.ts, packages/phrases/src/locales/ko/errors/oidc.ts, packages/phrases/src/locales/pl-pl/errors/oidc.ts, packages/phrases/src/locales/pt-br/errors/oidc.ts, packages/phrases/src/locales/pt-pt/errors/oidc.ts, packages/phrases/src/locales/ru/errors/oidc.ts, packages/phrases/src/locales/tr-tr/errors/oidc.ts, packages/phrases/src/locales/zh-cn/errors/oidc.ts, packages/phrases/src/locales/zh-hk/errors/oidc.ts, packages/phrases/src/locales/zh-tw/errors/oidc.ts
build a unified handler for `oidc-provider` errors by checking if the status is >= 400 and there's a string property `error` in the response. this is the only way we can check if the error is handled by the oidc-provider, because it doesn't call `renderError` when the [request prefers JSON response](https://github.com/panva/node-oidc-provider/blob/37d0a6cfb3c618141a44cbb904ce45659438f821/lib/shared/error_handler.js#L48-L55).
we may submit a pull request for allowing a more generic error handler config to `oidc-provider`, and update accordingly afterwards.
- updated and added unit tests
- local test
=> refactor(core): improve oidc error handling

packages/console/src/ds-components/RadioGroup/Radio.module.scss, packages/console/src/ds-components/RadioGroup/Radio.tsx, packages/console/src/pages/Roles/components/CreateRoleForm/index.module.scss, packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx, packages/phrases/src/locales/de/translation/admin-console/roles.ts, packages/phrases/src/locales/en/translation/admin-console/roles.ts, packages/phrases/src/locales/es/translation/admin-console/roles.ts, packages/phrases/src/locales/fr/translation/admin-console/roles.ts, packages/phrases/src/locales/it/translation/admin-console/roles.ts, packages/phrases/src/locales/ja/translation/admin-console/roles.ts, packages/phrases/src/locales/ko/translation/admin-console/roles.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/roles.ts, packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts, packages/phrases/src/locales/ru/translation/admin-console/roles.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/roles.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/roles.ts
hide role type selection on the role creation modal by default.
1. add `PRO` tag to the role type selection field on the `m2m role` options (show up for free plan).
2. when the plan is free plan and select m2m role, should pop up upsell footer.
3. fixed the footer, there will always be only ONE upsell message.
1. This is a free plan, with one existing user role.
2. the role type selection part is hidden by default
3. a hobby plan without `pro` tag
OR
=> refactor(console,phrases): hide role type selection on creation modal by default

packages/core/package.json, packages/core/src/__mocks__/mfa-verification.ts, packages/core/src/routes/interaction/actions/submit-interaction.test.ts, packages/core/src/routes/interaction/actions/submit-interaction.ts, packages/core/src/routes/interaction/additional.test.ts, packages/core/src/routes/interaction/additional.ts, packages/core/src/routes/interaction/index.test.ts, packages/core/src/routes/interaction/index.ts, packages/core/src/routes/interaction/mfa.test.ts, packages/core/src/routes/interaction/mfa.ts, packages/core/src/routes/interaction/types/guard.ts, packages/core/src/routes/interaction/types/index.ts, packages/core/src/routes/interaction/utils/index.ts, packages/core/src/routes/interaction/utils/sign-in-experience-valiation.test.ts, packages/core/src/routes/interaction/utils/sign-in-experience-validation.ts, packages/core/src/routes/interaction/utils/totp-validation.test.ts, packages/core/src/routes/interaction/utils/totp-validation.ts, packages/core/src/routes/interaction/verifications/index.ts, packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts, packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts, packages/core/src/routes/interaction/verifications/mfa-verification.test.ts, packages/core/src/routes/interaction/verifications/mfa-verification.ts, packages/schemas/src/types/interactions.ts, pnpm-lock.yaml
Implement the first MFA feature, binding new TOTP flow.
1. Add mandatory MFA checks for the existing sign in and sign up flow.
2. New endpoint `POST /verification/totp` to generate secret in the server side
3. New endpoint `PUT /bind-mfa` to set up the MFA that will be linked to the user, TOTP code will be checked here.
4. Refactor `/interaction/index.ts` file, split into files, it is too large now.
To reduce PR size and make it easy for review, integration tests are separated in https://github.com/logto-io/logto/pull/4566
=> feat(core,phrases,schemas): implement bind mfa totp

packages/console/src/components/AuditLogTable/components/ApplicationSelector/index.tsx
should not show admin console in audit log app selector (for user tenant), only show this for admin tenant.
OR
=> fix(console): should not show admin console in audit log app selector

packages/console/src/pages/ApplicationDetails/components/MachineToMachineApplicationRoles/index.module.scss, packages/console/src/pages/ApplicationDetails/components/MachineToMachineApplicationRoles/index.tsx, packages/console/src/pages/ApplicationDetails/index.tsx, packages/console/src/pages/RoleDetails/RoleApplications/index.module.scss, packages/console/src/pages/RoleDetails/RoleApplications/index.tsx, packages/console/src/pages/RoleDetails/index.tsx, packages/console/src/pages/Roles/components/AssignedEntities/index.tsx, packages/console/src/pages/Roles/index.tsx, packages/console/src/pages/UserDetails/UserRoles/index.module.scss, packages/console/src/pages/UserDetails/UserRoles/index.tsx, packages/integration-tests/src/tests/console/rbac.test.ts, packages/phrases/src/locales/de/translation/admin-console/application-details.ts, packages/phrases/src/locales/en/translation/admin-console/application-details.ts, packages/phrases/src/locales/es/translation/admin-console/application-details.ts, packages/phrases/src/locales/fr/translation/admin-console/application-details.ts, packages/phrases/src/locales/it/translation/admin-console/application-details.ts, packages/phrases/src/locales/ja/translation/admin-console/application-details.ts, packages/phrases/src/locales/ko/translation/admin-console/application-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts, packages/phrases/src/locales/ru/translation/admin-console/application-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
fix console UI issues:
1. update "remove role modal" description in m2m app details pages. (LOG-7155)
2. fix avatar of m2m apps on role table (LOG-7156)
3. 'Advanced Settings' tab name on role/app details pages to 'Advanced setting' (Title case to sentence case) (LOG-7153)
4. add role avatar 'Roles' tab of user/app details page (LOG-7157)
5. remove 'machine logs' tab from non-m2m apps (LOG-7154)
Tested locally:
1. update "remove role modal" description in m2m app details pages. (LOG-7155)
2. fix avatar of m2m apps on role table (LOG-7156)
3. 'Advanced Settings' tab name on role/app details pages to 'Advanced setting' (Title case to sentence case) (LOG-7153)
4. add role avatar 'Roles' tab of user/app details page (LOG-7157)
5. remove 'machine logs' tab from non-m2m apps (LOG-7154)
OR
=> chore(console,phrases): fix console UI issues

packages/console/src/components/AuditLogTable/index.tsx
fix AuditLogTable components application selector.
1. can successfully filter by application and add its corresponding `applicationId` to search parameters.
2. can correctly get audit logs of specific application (characterized by `applicationId`) and hide application selector
OR
=> fix(console): fix AuditLogTable components application selector

packages/console/package.json, packages/console/src/containers/ErrorBoundary/index.tsx, pnpm-lock.yaml
Fix the invalid_target error block console consent issue.
In PR #4573 we aligned the error response format of all OIDC thrown errors. Including errors like `invalid_grant` and `invalid_target`. Aligned with our  LogtoRequestError data structure.
- before response body: {error: 'invalid_grant', error_description: 'The resource indicator is missing or unknown'}.
- after response body: {code: 'oidc.invalid_grant', message: 'Invalid resource indicator'， error: 'invalid_grant', error_description: 'The resource indicator is missing or unknown' }
In AC we have an exclusive logic to handle the multi-tenant token exchanging flow. If an `invalid_target` or `invalid_grant` error is thrown, should treated as an unknown session and redirect the user to re-consent. 
- before: oidc error is not …
=> fix(console): fix the invalid_target error block console consent issue

.changeset/sweet-cows-burn.md, packages/core/src/oidc/init.ts, packages/core/src/oidc/scope.ts, packages/integration-tests/src/tests/api/oidc/id-token.test.ts, packages/toolkit/core-kit/src/scope.ts
create a new scope `roles` to add `roles` claim to the ID token. the claim will be an array of role names. this should resolve #3411.
tested locally and added integration tests
=> refactor(core): support `roles` scope for ID token

.changeset/lucky-brooms-hide.md, packages/cli/src/commands/database/seed/oidc-config.ts, packages/cli/src/commands/database/utils.ts, packages/core/src/env-set/oidc.ts, packages/core/src/middleware/koa-auth/utils.ts, packages/schemas/alterations/next-1695647183-update-private-key-type.ts, packages/schemas/src/types/logto-config.ts
Alter Logto signing key type, convert it from `string` to `JSON Object`, in order to provide additional information in Console, such as key ID and creation time.
Alteration script works fine, both upgrade and downgrade.
OR
~~- [ ] This PR is not applicable for the checklist~~
=> refactor(schemas,core,cli): alter signing key type to json object

packages/console/src/pages/WebhookDetails/WebhookSettings/CustomHeaderField/index.tsx, packages/phrases/src/locales/de/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/en/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/es/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/fr/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/it/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/ja/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/ko/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/ru/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/webhook-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/webhook-details.ts
**Improved Header Validation in CustomHeaderField Component**
Changes:
1. Added validation for header key and value based on RFC 9110 standard to ensure:
- Header keys use printable ASCII characters (excluding the colon).
- Header values exclude control characters.
2. ValidHeaderKey and isValidHeaderValue functions were added to perform the validation
3. Fixes #4557
These changes ensure that the input headers in the CustomHeaderField component are compliant with expected standards.
Tested the required CustomHeaderField component on the WebhookDetails page and it is working as expected.
=> feat: guard text inputs for CustomHeaderField component

packages/cli/package.json, packages/cli/src/connector/factories.ts, packages/cli/src/connector/types.ts, packages/cli/src/connector/utils.ts, packages/connectors/connector-logto-email/package.json, packages/connectors/connector-logto-email/src/index.ts, packages/core/src/__mocks__/connector.ts, packages/core/src/routes/connector/config-testing.test.ts, packages/core/src/routes/connector/config-testing.ts, packages/core/src/routes/connector/index.ts, packages/core/src/utils/connectors/index.ts, packages/toolkit/connector-kit/package.json, packages/toolkit/connector-kit/src/types.ts, pnpm-lock.yaml
Refactor and eliminate connector-kit dependency on @logto/cloud.
To unblock https://github.com/logto-io/cloud/pull/262 since @logto/cloud will hence depend on @logto/connector-kit.
Secured by CI.
OR
=> refactor: eliminate connector-kit dependency on logto/cloud

packages/experience/src/components/SwitchMfaFactorsLink/index.tsx, packages/experience/src/containers/MfaFactorList/index.tsx, packages/experience/src/hooks/use-mfa-verification-error-handler.ts, packages/experience/src/hooks/use-start-totp-binding.ts, packages/experience/src/pages/MfaBinding/TotpBinding/index.module.scss, packages/experience/src/pages/MfaBinding/TotpBinding/index.tsx, packages/experience/src/pages/MfaBinding/index.tsx, packages/experience/src/pages/MfaVerification/TotpVerification/index.tsx, packages/experience/src/pages/MfaVerification/index.tsx, packages/experience/src/types/guard.ts
Reorg mfa factor switching logic and extract the switch link into a component (`SwitchMfaFactorsLink`).
- Remove redundant `totpVerificationStateGuard` since the `mfaFactorsStateGuard` is enough.
- Rename hook filename from `use-start-binding-totp` to `use-start-totp-binding`, since it should be align with the hook name in the code.
OR
=> refactor(experience): reorg mfa factor switching logic

packages/console/src/ds-components/Dropdown/index.module.scss, packages/console/src/ds-components/Dropdown/index.tsx, packages/console/src/ds-components/Select/index.tsx, packages/console/src/ds-components/Table/index.module.scss, packages/console/src/ds-components/Table/index.tsx, packages/console/src/ds-components/Table/types.ts, packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.module.scss, packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx, packages/toolkit/core-kit/scss/_console-themes.scss
Implement console UI to rotate OIDC private keys and cookie keys. (2/2 parts)
Locally tested
~~- [ ] `.changeset`~~ Add later
~~- [ ] integration tests~~ later
~~- [ ] docs~~ later
OR
=> feat(console): add console UI for private keys rotation

packages/core/src/queries/organization-scopes.ts, packages/core/src/routes/init.ts, packages/core/src/routes/organization-scopes.test.ts, packages/core/src/routes/organization-scopes.ts, packages/core/src/tenants/Queries.ts, packages/integration-tests/src/api/organization-scope.ts, packages/integration-tests/src/tests/api/organization-scope.test.ts, packages/phrases/src/locales/de/errors/entity.ts, packages/phrases/src/locales/en/errors/entity.ts, packages/phrases/src/locales/es/errors/entity.ts, packages/phrases/src/locales/fr/errors/entity.ts, packages/phrases/src/locales/it/errors/entity.ts, packages/phrases/src/locales/ja/errors/entity.ts, packages/phrases/src/locales/ko/errors/entity.ts, packages/phrases/src/locales/pl-pl/errors/entity.ts, packages/phrases/src/locales/pt-br/errors/entity.ts, packages/phrases/src/locales/pt-pt/errors/entity.ts, packages/phrases/src/locales/ru/errors/entity.ts, packages/phrases/src/locales/tr-tr/errors/entity.ts, packages/phrases/src/locales/zh-cn/errors/entity.ts, packages/phrases/src/locales/zh-hk/errors/entity.ts, packages/phrases/src/locales/zh-tw/errors/entity.ts
add organization scope CRUD APIs with the new SchemaRouter and SchemaActions classes.
it's almost the same comparing to organization APIs, with the name uniqueness constraint.
resolves LOG-7236
unit + integration tests
=> feat(core): add organization scope APIs

packages/console/src/ds-components/Dropdown/index.tsx, packages/console/src/ds-components/Select/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
Per designers, select dropdown should always pop downwards, as long as the dropdown content is still visible.
Locally tested
~~- [ ] docs~~
OR
=> refactor(console): select dropdown should always pop downwards

packages/console/src/ds-components/Table/index.module.scss, packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx
[Design system update] Remove bottom padding from tables in compact view.
Also removed hover effect from "OIDC signing keys" table, as there is no row click interaction.
Locally tested
=> refactor(console): remove bottom padding from compact tables

packages/console/src/pages/TenantSettings/TenantBasicSettings/SigningKeys/index.tsx, packages/core/src/routes/logto-config.ts, packages/integration-tests/src/api/logto-config.ts, packages/integration-tests/src/tests/api/logto-config.test.ts, packages/schemas/src/types/logto-config.ts
Previously when reviewing the code, @darcyYe pointed out an issue that we have duplicated OIDC `keyType` enum/union declared ini both frontend and backend, which increases the risks of inconsistence in future development.
Therefore, I decided to move it to schemas and share it across the project.
Now, when we write API rotate OIDC keys API routes or call these APIs from frontend, we should use the `LogtoOidcConfigKeyType` enum, whereas if we write DB SQL queries or execute rotate OIDC key CLI commands, we should use `LogtoOidcConfigKey` enum.
`LogtoOidcConfigKeyType` has values in kebab case and thus is suitable for API routes
```ts
export enum LogtoOidcConfigKeyType {
PrivateKeys = 'private-keys',
CookieKeys = 'cookie-keys',
}
```
`LogtoOidcConfigKey` has values that map to the config …
=> refactor(schemas,core,console): unify the usage of OIDC "keyType" in both frontend and backend

packages/core/src/queries/organizations.ts, packages/core/src/routes/admin-user/index.ts, packages/core/src/routes/admin-user/organization.ts, packages/core/src/utils/SchemaRouter.ts, packages/integration-tests/src/api/organization.ts, packages/integration-tests/src/tests/api/organization.test.ts
api to get all organizations for a user with all roles the user has for each organization. resolves LOG-7237
`GET /users/:userId/organizations`
```ts
type RoleEntity = {
id: string;
name: string;
};
type OrganizationWithRoles = Organization & {
/** The roles of the current member of the organization. */
roles: RoleEntity[];
};
```
Response body will be an array of `OrganizationWithRoles`.
added api tests accordingly
=> feat(core): get organizations for user api

packages/cli/src/connector/factories.ts, packages/cli/src/connector/types.ts, packages/core/src/__mocks__/connector.ts, packages/core/src/libraries/connector.ts, packages/core/src/routes/connector/index.post.test.ts, packages/core/src/routes/connector/index.ts
Refactor the POST /connectors endpoint.
1. Return the `configGuard` directly in the `connectorFactory`. No need to rebuild the connector to validate the config data. 
2. Extract the fide duplicate social connector with the given `target` and `platform` into a library method. 
3. Move all the social-only validation statements into the `ConnectorType === 'Social'` block.
UT
=> refactor(core): refactor post connector endpoint

packages/core/src/middleware/koa-pagination.ts, packages/core/src/routes/organization/index.ts, packages/core/src/routes/organization/roles.ts, packages/core/src/routes/organization/scopes.ts, packages/core/src/utils/SchemaQueries.ts, packages/core/src/utils/SchemaRouter.test.ts, packages/core/src/utils/SchemaRouter.ts
apply Occam's razor - the class looks redundant since we can use `disabled` config to disable certain paths
no logic change, existing tests should be good. also added more tests to the router.
=> refactor(core): remove `SchemaActions` class

packages/core/src/routes/interaction/utils/totp-validation.ts, packages/integration-tests/src/ui-helpers/expect-totp-experience.ts
Considering T1 and T2 two consecutive time steps, any token generated within T1 but checked with T2 could be considered valid according to [RFC 6238 5.2](https://datatracker.ietf.org/doc/html/rfc6238#section-5.2).
FYI: https://github.com/yeojz/otplib/issues/697#issuecomment-1655749578
- test: Extract filling totp code logic into a helper method
- test: Remove `getUserIdFromDemoAppPage` method from the `ExpectTotpExperience` class since it's available in the base class(`ExpectExperience`).
IT
=> refactor(core): add time window validation tolerance for otp authenticator

packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts, packages/core/src/routes/interaction/actions/submit-interaction.ts, packages/core/src/routes/interaction/mfa.test.ts, packages/core/src/routes/interaction/mfa.ts, packages/core/src/routes/interaction/types/guard.ts, packages/core/src/routes/interaction/types/index.ts, packages/core/src/routes/interaction/verifications/mfa-verification.test.ts, packages/core/src/routes/interaction/verifications/mfa-verification.ts, packages/experience/src/apis/interaction.ts, packages/integration-tests/src/api/interaction.ts, packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts, packages/phrases/src/locales/de/errors/session.ts, packages/phrases/src/locales/en/errors/session.ts, packages/phrases/src/locales/es/errors/session.ts, packages/phrases/src/locales/fr/errors/session.ts, packages/phrases/src/locales/it/errors/session.ts, packages/phrases/src/locales/ja/errors/session.ts, packages/phrases/src/locales/ko/errors/session.ts, packages/phrases/src/locales/pl-pl/errors/session.ts, packages/phrases/src/locales/pt-br/errors/session.ts, packages/phrases/src/locales/pt-pt/errors/session.ts, packages/phrases/src/locales/ru/errors/session.ts, packages/phrases/src/locales/tr-tr/errors/session.ts, packages/phrases/src/locales/zh-cn/errors/session.ts, packages/phrases/src/locales/zh-hk/errors/session.ts, packages/phrases/src/locales/zh-tw/errors/session.ts
Change `interaction.bindMfa` to `interaction.bindMfas` to support binding 2 factors in one time, prepares for the implementation of "totp + backup code" and "webauthn + backup code".
The route method is changed to "post".
~~- [ ] necessary TSDoc comments (no function added)~~
=> refactor(core,phrases): change interaction bind-mfa to array

.github/workflows/alteration-compatibility-integration-test.yml, .github/workflows/integration-test.yml
To address the issue of production errors caused by incompatible database alterations, we're introducing a new CI job dedicated to ensuring the compatibility of alteration scripts with our production code. This job aims to prevent altered data from breaking our production systems when the production DB has been altered but the new release code is launched to staging only.
1. returns directly if no alteration script changes are detected
2. pull the base branch codebase and init logto
3. run the db alteration from the  current branch
4. run the integration tests on the base branch logto server
This PR refactors the integration test, all the shared integration steps are extracted to the latest created custom GitHub actions:
- [logto-io/actions-package-logto-artifact](https://github.com/silver …
=> ci: add alteration scripts compatibility test jobs

packages/core/src/__mocks__/mfa-verification.ts, packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts, packages/core/src/routes/interaction/actions/submit-interaction.ts, packages/core/src/routes/interaction/index.test.ts, packages/core/src/routes/interaction/index.ts, packages/core/src/routes/interaction/mfa.test.ts, packages/core/src/routes/interaction/mfa.ts, packages/core/src/routes/interaction/utils/backup-code-validation.test.ts, packages/core/src/routes/interaction/utils/backup-code-validation.ts, packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts, packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts, packages/core/src/routes/interaction/verifications/mfa-verification.test.ts, packages/core/src/routes/interaction/verifications/mfa-verification.ts, packages/core/src/utils/user.ts, packages/schemas/src/foundations/jsonb-types/users.ts, packages/schemas/src/types/interactions.ts, packages/schemas/src/types/user.ts
Implement the feature: bind backup code:
If "backup code" is enabled in Console, then if a user want to bind a new MFA, backup code should be added together. The process is:
1. Submit interaction with new `bindMfa`.
2. Return error of missing backup code, and generate codes to session, send to front end with error, the front end can then show backup codes to the user.
3. Resubmit the interaction to "confirm" backup code.
Unit tests.
~~- [ ] integration tests~~ will add in "verify backup code" PR
=> feat(core,schemas): bind backup code

packages/core/src/database/find-all-entities.ts, packages/core/src/database/row-count.ts, packages/core/src/database/utils.ts, packages/core/src/queries/organizations.ts, packages/core/src/routes/organization/index.ts, packages/core/src/routes/organization/roles.ts, packages/core/src/routes/organization/scopes.ts, packages/core/src/utils/SchemaQueries.ts, packages/core/src/utils/SchemaRouter.test.ts, packages/core/src/utils/SchemaRouter.ts
- now `SchemaQueries.findAll` supports fuzzy search for one or multiple fields
- when initializing `SchemaRouter`, it's able to pass a `searchFields` config to specify which field(s) to search
permission search works
=> feat(core): schema with search fields

packages/core/src/database/find-all-entities.ts, packages/core/src/database/row-count.ts, packages/core/src/database/utils.ts, packages/core/src/include.d/koa-router.d.ts, packages/core/src/queries/organizations.ts, packages/core/src/queries/user.ts, packages/core/src/routes/admin-user/organization.ts, packages/core/src/routes/admin-user/search.test.ts, packages/core/src/routes/admin-user/search.ts, packages/core/src/routes/dashboard.test.ts, packages/core/src/routes/dashboard.ts, packages/core/src/routes/organization/index.ts, packages/core/src/routes/organization/utils.ts, packages/core/src/routes/role.user.ts, packages/core/src/utils/RelationQueries.ts, packages/core/src/utils/SchemaQueries.ts, packages/core/src/utils/SchemaRouter.ts, packages/core/src/utils/search.ts, packages/integration-tests/src/api/organization.ts, packages/integration-tests/src/tests/api/organization.test.ts, packages/schemas/src/types/organization.ts
- add and update necessary organization APIs for console implementation.
- `GET /users` now supports `excludeOrganizationId` for excluding users that have membership in an organization
- `GET /organizations/:id/users` now attaches user roles in the response
- add `POST /organizations/:id/users/roles` for assigning multiple users with organization roles in batch
- refactor user search with subquery
since this PR is already large, i left several inline to-dos in the change set. integration tests for the new APIs will also be added later.
original tests
=> feat(core): organization apis

packages/core/src/routes/interaction/verifications/mfa-verification.test.ts, packages/core/src/routes/interaction/verifications/mfa-verification.ts, packages/integration-tests/src/helpers/sign-in-experience.ts, packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
Implement skippable bind mfa prompt: for "user-controlled" MFA policy, will prompt for user to bind MFA for only once (the user can skip).
Prompt: throw "missing_mfa" error, and auto mark as skipped.
Skip: save data in user's custom data.
=> feat(core): skippable bind mfa prompt

packages/core/src/routes/interaction/additional.ts, packages/core/src/routes/interaction/mfa.ts
For MFA (WebAuthn and TOTP) hostname, use `ctx.URL` to replace `EnvSet.values.endpoint`:
1. `ctx.URL` is more accurate if the user is using custom domain.
2. `EnvSet.values.endpoint` will not contain tenantId in the cloud, this is a bug.
Local tested.
=> fix(core): get hostname from ctx for webauthn

packages/cli/src/commands/database/config.ts
Fix a bug that causes "Unsupported private key {type}" error when generating `oidc.privateKeys` or `oidc.cookieKeys` using Logto CLI.
Tested CLI locally and it works properly now
=> fix(cli): fix unsupported signing key error when generating keys with cli

packages/console/src/components/OrganizationRolesSelect/index.tsx, packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/pages/OrganizationDetails/Members/EditOrganizationRolesModal.tsx, packages/console/src/pages/OrganizationDetails/Members/index.module.scss, packages/console/src/pages/OrganizationDetails/Members/index.tsx, packages/console/src/pages/OrganizationDetails/Settings/index.tsx, packages/console/src/pages/OrganizationDetails/index.module.scss, packages/console/src/pages/OrganizationDetails/index.tsx
- add `<OrganizationRolesSelect />` component
- init organization details page with settings and members tab
- allow user organization roles to be edited
large PR already. missing tests will be added later.
- can view organization details
- can change organization name or description
- can edit organization roles in the organization members tab
=> feat(console): organization details

packages/console/src/pages/OrganizationDetails/Members/AddMembersToOrganization.tsx, packages/core/src/middleware/koa-auth/index.ts, packages/core/src/routes/organization/index.ts, packages/integration-tests/src/api/organization.ts, packages/integration-tests/src/helpers/organization.ts, packages/integration-tests/src/helpers/user.ts, packages/integration-tests/src/tests/api/admin-user.search.test.ts, packages/integration-tests/src/tests/api/organization-user.test.ts, packages/integration-tests/src/tests/api/organization.test.ts, packages/integration-tests/src/utils.ts
- add integration tests for #4714
- add integration tests for `/users?excludeRoleId=some_id`
- replace body key `roleIds` with `organizationRoleIds` in `POST /organization/:id/users/roles` to align our key convention
the pr itself
=> chore(test): add integration tests for new APIs

packages/core/src/routes/sso-connector/index.ts, packages/core/src/routes/sso-connector/type.ts, packages/core/src/routes/sso-connector/utils.ts, packages/core/src/sso/types/index.ts, packages/integration-tests/src/api/sso-connector.ts, packages/integration-tests/src/tests/api/sso-connectors.test.ts
Implement patch sso-connectors API
- Directly update the connector data for the following fields
- branding
- syncProfile
- ssoOnly
- connectorName
- Parse and verify the `config`  before inserting it into DB. 
Test locally
=> feat(core): implement patch sso-connectors api

packages/core/src/routes/sso-connector/index.ts, packages/core/src/routes/sso-connector/type.ts, packages/core/src/routes/sso-connector/utils.test.ts, packages/core/src/routes/sso-connector/utils.ts, packages/core/src/sso/types/index.ts, packages/core/src/sso/types/oidc.ts, packages/core/src/utils/SchemaQueries.ts, packages/core/src/utils/SchemaRouter.ts, packages/integration-tests/src/api/sso-connector.ts, packages/integration-tests/src/tests/api/sso-connectors.test.ts
Add GET `sso-connectors` API.
Fetch connector configs from the connector provider e.g. fetch token endpoints from the OIDC provider, and fetch metadata details from the SAML provider. 
Return connector DB data with the fetched provider configs, if any.
=> feat(core): add GET sso-connectors api

packages/experience/src/pages/MfaBinding/TotpBinding/SecretSection/index.tsx
refactor(experience): display secret code first when bindning totp on mobile devices
=> refactor(experience): display secret code first when binding totp on mobile devices

packages/console/src/consts/page-tabs.ts, packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/pages/OrganizationDetails/Members/index.tsx, packages/console/src/pages/Organizations/OrganizationsTable/index.tsx, packages/console/src/pages/Organizations/TemplateTable/index.tsx, packages/console/src/pages/UserDetails/UserOrganizations/index.module.scss, packages/console/src/pages/UserDetails/UserOrganizations/index.tsx, packages/console/src/pages/UserDetails/index.tsx, packages/phrases/src/locales/de/translation/admin-console/user-details.ts, packages/phrases/src/locales/en/translation/admin-console/user-details.ts, packages/phrases/src/locales/es/translation/admin-console/user-details.ts, packages/phrases/src/locales/fr/translation/admin-console/user-details.ts, packages/phrases/src/locales/it/translation/admin-console/user-details.ts, packages/phrases/src/locales/ja/translation/admin-console/user-details.ts, packages/phrases/src/locales/ko/translation/admin-console/user-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/user-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/user-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/user-details.ts, packages/phrases/src/locales/ru/translation/admin-console/user-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/user-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/user-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/user-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/user-details.ts
- implement the 'Organizations' tab for user details page, resolves LOG-7226
- add missing table empty placeholders
- implement search for organizations table
all organization-related console integration tests will be added soon
=> feat(console): organizations tab for user details

packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts
make M2M RBAC console integration test stable.
The test case "assign permission to an m2m role app on app details page" occasionally fails because the previous permission deletion operation will idle for a while until the DB is updated. Before this, the deletion confirmation modal still exists and the "add permission" button is not clickable.
CI.
=> fix(test): make m2m RBAC console integration test stable

packages/experience/src/hooks/use-webauthn-operation.ts, packages/integration-tests/src/tests/experience/mfa/backup-code/index.test.ts, packages/integration-tests/src/tests/experience/mfa/webauthn/index.test.ts, packages/integration-tests/src/ui-helpers/expect-webauthn-experience.ts, packages/phrases-experience/src/locales/de/mfa.ts, packages/phrases-experience/src/locales/en/mfa.ts, packages/phrases-experience/src/locales/es/mfa.ts, packages/phrases-experience/src/locales/fr/mfa.ts, packages/phrases-experience/src/locales/it/mfa.ts, packages/phrases-experience/src/locales/ja/mfa.ts, packages/phrases-experience/src/locales/ko/mfa.ts, packages/phrases-experience/src/locales/pl-pl/mfa.ts, packages/phrases-experience/src/locales/pt-br/mfa.ts, packages/phrases-experience/src/locales/pt-pt/mfa.ts, packages/phrases-experience/src/locales/ru/mfa.ts, packages/phrases-experience/src/locales/tr-tr/mfa.ts, packages/phrases-experience/src/locales/zh-cn/mfa.ts, packages/phrases-experience/src/locales/zh-hk/mfa.ts, packages/phrases-experience/src/locales/zh-tw/mfa.ts
Due to limitations in the iOS system, user interaction is required for the use of the WebAuthn API.
Therefore, we should avoid asynchronous operations before invoking the WebAuthn API or the operating system may consider the WebAuthn authorization is not initiated by the user.
So, we need to prepare the necessary WebAuthn options before calling the WebAuthn API.
Tested on iOS devices.
=> fix(experience): invoke webauthn on iOS devices

packages/core/src/__mocks__/sso.ts, packages/core/src/libraries/sso-connector.test.ts, packages/core/src/libraries/sso-connector.ts, packages/core/src/routes/sso-connector/index.ts, packages/core/src/routes/sso-connector/type.ts, packages/core/src/routes/sso-connector/utils.test.ts, packages/core/src/routes/sso-connector/utils.ts, packages/core/src/sso/index.ts, packages/core/src/sso/types/index.ts, packages/core/src/sso/utils.test.ts, packages/core/src/sso/utils.ts, packages/core/src/tenants/Libraries.ts
In DB schema `providerName` type is string.  But in practice, for most of the use cases of the connector data, we need to ensure the `providerName` is one of the Logto-provided SsoConnector provider types.  Assert `providerName` is the `SsoProviderName` type.
Define a new type assertion helper function to clarify the input connector is `SupportedSsoConnector`. This may simplify some of the internal logic with a strict output type guard.  
Also extract those common connector's get queries into a library, with the `SupportedSsoConnector` assertion added. 
UT updated
=> refactor(core): add the isSupportedSsoConnector type assertion

packages/core/src/__mocks__/sso.ts, packages/core/src/libraries/sso-connector.test.ts, packages/core/src/libraries/sso-connector.ts, packages/core/src/routes/sso-connector/index.ts, packages/core/src/routes/sso-connector/utils.test.ts, packages/core/src/routes/sso-connector/utils.ts, packages/core/src/sso/index.ts, packages/core/src/sso/types/index.ts, packages/core/src/sso/utils.test.ts, packages/core/src/sso/utils.ts, packages/core/src/tenants/Libraries.ts, packages/integration-tests/src/tests/api/sso-connectors.test.ts
Refactor the `sso-connector` config guard logic.
Per offline discussion with the product team, we have the following major updates on the API input guard logic of the connector's config. 
1. Providing partial `config` is ONLY acceptable for the `POST` method. (When creating a new connector).
2. All `PATCH` methods with a given `config` must be fully guarded using the connector factory's `configGuard`.
- update the `parseConnectorConfig` util method with an additional argument `allowPartial`. Partially validate the `config` inputs only if it is true. 
- set `allowPartial` to true in the POST method
- update the integration tests accordingly to cover the new logic update. 
integration tests
=> refactor(core): refactor the sso-connector config guard logic

packages/experience/src/hooks/use-mfa-error-handler.ts, packages/experience/src/hooks/use-webauthn-operation.ts, packages/phrases-experience/src/locales/de/mfa.ts, packages/phrases-experience/src/locales/en/mfa.ts, packages/phrases-experience/src/locales/es/mfa.ts, packages/phrases-experience/src/locales/fr/mfa.ts, packages/phrases-experience/src/locales/it/mfa.ts, packages/phrases-experience/src/locales/ja/mfa.ts, packages/phrases-experience/src/locales/ko/mfa.ts, packages/phrases-experience/src/locales/pl-pl/mfa.ts, packages/phrases-experience/src/locales/pt-br/mfa.ts, packages/phrases-experience/src/locales/pt-pt/mfa.ts, packages/phrases-experience/src/locales/ru/mfa.ts, packages/phrases-experience/src/locales/tr-tr/mfa.ts, packages/phrases-experience/src/locales/zh-cn/mfa.ts, packages/phrases-experience/src/locales/zh-hk/mfa.ts, packages/phrases-experience/src/locales/zh-tw/mfa.ts
Hide the webauthn factor on native webview if the user has other options, since it's not supported.
With this config:
The display content:
Not supported message:
=> refactor(experience): hide webauthn on native webview

packages/console/src/ds-components/Select/index.module.scss, packages/console/src/pages/Organizations/RoleModal/index.tsx, packages/console/src/pages/Organizations/TemplateTable/index.module.scss, packages/console/src/pages/Organizations/TemplateTable/index.tsx, packages/core/src/utils/SchemaRouter.ts
- show loading spinner for organization settings page
- fix i18n display
- adjust multi-select padding to make it look better
- allow empty relation id array for relation apis (`POST` and `PUT`)
localhost tested
=> refactor(console): improve org settings page

packages/core/src/__mocks__/index.ts, packages/core/src/libraries/sign-in-experience/index.test.ts, packages/core/src/libraries/sign-in-experience/index.ts, packages/core/src/libraries/sign-in-experience/types.ts, packages/core/src/libraries/sso-connector.ts, packages/core/src/routes/well-known.test.ts, packages/core/src/tenants/Libraries.ts, packages/integration-tests/src/tests/api/sso-connectors.test.ts, packages/integration-tests/src/tests/api/well-known.test.ts, packages/schemas/src/types/index.ts, packages/schemas/src/types/sso-connector.ts
Add ssoConnectors to the sie well-known api.
- filter out connectors with invalid or insufficient config.
minor:
Call deleteSsoConnectorById after each test case in the integration test. Clean up those new created connectors, just in case we need a clean connector  DB environment every time. 
test locally
=> feat(core): add ssoConnectors to the sie well-known api

.changeset/sixty-ladybugs-exercise.md, packages/console/src/components/RolesTransfer/components/SourceRolesBox/index.tsx, packages/console/src/pages/Roles/components/AssignRoleModal/index.tsx, packages/core/src/queries/application.ts, packages/core/src/queries/roles.ts, packages/core/src/routes/admin-user/role.ts, packages/core/src/routes/application-role.ts, packages/core/src/routes/application.ts, packages/core/src/routes/role.ts, packages/core/src/utils/search.ts, packages/integration-tests/src/api/admin-user.ts, packages/integration-tests/src/api/application.ts, packages/integration-tests/src/api/role.ts, packages/integration-tests/src/tests/api/admin-user.roles.test.ts, packages/integration-tests/src/tests/api/application.roles.test.ts, packages/integration-tests/src/tests/api/role.application.test.ts, packages/integration-tests/src/tests/api/role.user.test.ts, packages/integration-tests/src/tests/console/machine-to-machine-rbac/machime-to-machime-rbac.test.ts, packages/integration-tests/src/tests/console/machine-to-machine-rbac/utils.ts
support filter by type for GET roles and apps APIs and no longer reuse advanced search for both role and application filtering by type, made the following changes:
1. add optional `type` as GET /roles API's query parameter. Show all roles (including both m2m app roles and user roles if `type` is not specified)
2. add optional `types` as GET /applications API's query parameter (list all apps if not presented)
3. remove the monkey-patched `fieldsTypeMapping` input parameters when parsing query parameters for advanced search. Usually, the string values used for advanced search apply to multiple fields in DB records, and in most cases, the non-exact match mode is applied. While `type` is likely an enum type and needs an exact match mode, which means reusing advanced search for `type` …
=> fix(console,core,test): support filter by type for GET roles and apps APIs

packages/console/src/pages/Organizations/Guide/CreateOrganization/index.tsx, packages/console/src/pages/Organizations/index.tsx, packages/core/src/__mocks__/index.ts, packages/integration-tests/src/tests/api/logto-config.test.ts, packages/schemas/alterations/next-1698646271-add-organization-created-flag.ts, packages/schemas/src/seeds/logto-config.ts, packages/schemas/src/types/logto-config.ts
Add a new config flag `organizationCreated` in database to record organization creation status. Defaults to `false`.
Show the organization creation guide when the flag is false, and set the flag to `true` when the organization is created successfully.
When it's true, users should see the create form instead of the guide when clicking on the "Create Organization" button.
Tested locally, the DB alteration script and the feature are functional.
=> feat(console,schemas): add new db config to record organization creation status

packages/core/src/routes/interaction/mfa.test.ts, packages/core/src/routes/interaction/mfa.ts, packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts, packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts, packages/core/src/routes/interaction/verifications/mfa-verification.test.ts, packages/core/src/routes/interaction/verifications/mfa-verification.ts, packages/schemas/src/foundations/jsonb-types/users.ts
Add `lastUsedAt` to `user.mfaVerifications`, when a auth factor is verified, it will be updated with current time.
And sort `availableFactors` when throw error.
Unit tests.
=> feat(core): add last use time to user mfa verifications

packages/console/src/consts/logs.ts, packages/core/src/routes/interaction/const.ts, packages/core/src/routes/interaction/index.ts, packages/core/src/routes/interaction/single-sign-on.ts, packages/core/src/routes/interaction/utils/social-verification.ts, packages/integration-tests/src/api/interaction-sso.ts, packages/integration-tests/src/api/interaction.ts, packages/integration-tests/src/constants.ts, packages/integration-tests/src/tests/api/interaction/single-sign-on/happy-path.test.ts, packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts, packages/schemas/src/types/log/interaction.ts
Add post single-sign-on authentication endpoint.
Introduce new subpath for the interaction apis `/interaction/single-sign-on`  as SSO has a different sign-in flow and shares different validation and handling logics compare to our existing interaction identifiers. 
POST `/interaction/single-sign-on/:connectorId/authentication` will create a single sign on connector authn session and return the authorization url to the client. 
test locally
=> feat(core): add post single-sign-on authentication endpoint

packages/console/src/pages/Organizations/Guide/CreatePermissions/index.tsx, packages/console/src/pages/Organizations/Guide/CreateRoles/index.tsx
Fix the issue that organization guide should check required field input before navigation, when there's no pre-saved data available.
Locally tested
=> fix(console): organization guide should check required fields on navigation

packages/core/src/__mocks__/sso.ts, packages/core/src/libraries/sign-in-experience/index.test.ts, packages/core/src/libraries/sign-in-experience/index.ts, packages/core/src/libraries/sso-connector.test.ts, packages/core/src/libraries/sso-connector.ts, packages/core/src/routes/interaction/single-sign-on.ts, packages/integration-tests/src/api/interaction-sso.ts, packages/integration-tests/src/tests/api/interaction/single-sign-on/happy-path.test.ts, packages/integration-tests/src/tests/api/well-known.test.ts, packages/schemas/src/types/sso-connector.ts
Add get sso-connectors by email interaction api.
- extract a new sso connector library method `getAvailableSsoConnectors`. This method should query sso connectors from the DB and filter out those with invalid connector configs or empty domain settings.
- remove the `domains` property from the `ssoConnectorMetadata`. All the `domains` mapping and validation logic should kept in backend, instead of return everything to the client side.
- add a new interaction api: `GET /interaction/sso/connectors?email=XXX`. Allow the client side to fetch available connectors by a given email address.
ut + integration test
=> feat(core): add get sso-connectors by email interaction api

packages/experience/src/containers/MfaFactorList/index.tsx, packages/experience/src/hooks/use-mfa-error-handler.ts, packages/experience/src/hooks/use-start-webauthn-processing.ts, packages/experience/src/hooks/use-webauthn-operation.ts, packages/experience/src/pages/MfaBinding/WebAuthnBinding/index.tsx, packages/experience/src/pages/MfaVerification/WebAuthnVerification/index.tsx, packages/experience/src/types/guard.ts, packages/experience/src/types/index.ts, packages/experience/src/utils/webauthn.ts
In the original implementation, WebAuthn options will be generated on the WebAuthn page, it will cause an unexpected loading state on the page.
This time, we need to generate WebAuthn options before we navigating the page to the WebAuthn page.
To achieve this goal, we do following things:
- add an `useStartWebAuthnProcessing` hook to generate WebAuthn options and pass generated options to the WebAuthn page via the navigation state
- add a `WebAuthnState` type to guard the navigation state
- add an `isWebAuthnOptions` function to assert the options' type before we calling the native WebAuthn API, since the WebAuthn options is a complex object and is already guarded by the backend API, so we don't add a navigation state guard for the options ( use `Record<string, unkonwn>` instead).
- Since …
=> refactor(experience): generate webauthn options before switching to the webauthn page

packages/core/src/routes/interaction/mfa.test.ts, packages/core/src/routes/interaction/mfa.ts
When checking if "backup code" is the user's only factor, should check both interaction's `bindMfa` and user's `mfaVerifications`.
Unit tests.
=> fix(core): check user mfa when binding backup code

packages/console/src/components/DetailsPage/DetailsPageHeader/index.module.scss
Details page header text should not overflow its container. Ellipsis should be appended and text content should be cut off.
=> fix(console): details page header text should not overflow its container

packages/core/src/routes/organization/index.ts
disable for non-dev envs until the feature is ready.
setting `NODE_ENV` to `production`, organization routes return 404
=> refactor(core): disable org apis for non-dev envs

packages/console/src/components/TenantEnvTag/index.module.scss, packages/console/src/components/TenantEnvTag/index.tsx, packages/console/src/components/Topbar/TenantSelector/index.module.scss, packages/console/src/consts/external-links.ts, packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.module.scss, packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.module.scss, packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
refactor(console): refactor tenant settings page
- Add data host region info
- Refactor tenant env info content
- Ranme `tenantTagMap` to `tenantTagNameMap` for better understanding
- Support large size for the `TenantEnvTag` component
- Refactor the `TenantEnvTag` component since it's a tag and should be an inline-block item
- Remove the `font: var(--font-body-3)` style in the tenant tag on the tenant selector, since it never took effect and it's style should be align with the tenant tag on the topbar.
- Refactor tenant-related UI tests in the cloud repo
=> refactor(console): refactor tenant settings page

packages/console/src/ds-components/CardTitle/index.module.scss, packages/console/src/pages/Applications/index.module.scss
Since now, the `CardTitle` component support a `titleTag` component and we use `flex` to align the title text and the title tag. so we need to use `flext` layout for the whole `CardTitle` component. This allow us to center the card title content by using `align-items: center`.
Before:
After:
=> style(console): center align `CardTitle` content for application placeholder page

packages/console/src/components/CreateConnectorForm/index.tsx, packages/console/src/components/Guide/GuideCard/index.tsx, packages/console/src/components/ProTag/index.tsx, packages/console/src/containers/AppContent/TenantNotificationContainer/index.tsx, packages/console/src/containers/AppContent/index.tsx, packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/pages/Applications/components/GuideLibrary/index.tsx, packages/console/src/pages/Applications/components/TypeDescription/index.tsx, packages/console/src/pages/Mfa/PageWrapper/index.tsx, packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx, packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx, packages/console/src/pages/TenantSettings/index.tsx
Control console content by tenant env tag
- Hide plan & billing page when the tenant is a dev tenant
- Display all pro tags when the tenant is a dev tenant
- Refactor the `ProTag` component: use the `isVisibleInProdEnv` prop to control the visibility of the pro tag, it allows us to override the visibility inside the pro tag component according to the tenant env tag
- Extract all tenant notificaton modals in to a `TenantNotificationContainer` so we can manage them in one place.
Test locally.
=> feat(console): control console content by tenant env tag

packages/core/src/libraries/sign-in-experience/index.test.ts, packages/core/src/libraries/sign-in-experience/index.ts, packages/core/src/libraries/sign-in-experience/types.ts, packages/core/src/tenants/Libraries.ts
Add `isDevelopmentTenant` to `/.well-known/sign-in-exp`, the front-end will use this to show the banner.
Notice that there is no integration tests, because we are unable to test "cloud" related features for now.
Unit tests and local tested.
=> feat(core): add isDevelopmentTenant to SIE well-known api

packages/console/src/cloud/AppRoutes.tsx, packages/console/src/consts/subscriptions.ts, packages/console/src/contexts/TenantsProvider.tsx, packages/console/src/hooks/use-subscribe.ts, packages/console/src/pages/ConsoleRoutes/index.tsx, packages/console/src/utils/url.ts
Support plan subscription from the tenant landing page.
- Add a global reserved route `checkout-success-callback` to handle the checkout success callback for cloud app
- Replace the original `checkout-success` route with `checkout-succes-callback`, since we have an error handling convention for all `callback` pages, which requires the page path have a `-callback` tail.
- Apply plan subscription logic for the tenant landing page after the creation modal is refactored in later PR.
- Add & refactor UI tests in the cloud repo after all dev tenant features is ready.
- Select plan:
https://github.com/logto-io/logto/assets/10806653/ec9b375e-82b2-492c-952d-57c52ccc4fcb
- After payment:
https://github.com/logto-io/logto/assets/10806653/19be1e41-6145-43e5-84c0-2277dd9dad91 …
=> feat(console): support plan subscription from the tenant landing page

packages/console/src/pages/Organizations/TemplateTable/index.module.scss
Fix icon color on create buttons in organization template. Make sure the icon is using `text-secondary` color token
=> fix(console): icon color on add buttons in organization template

packages/console/src/pages/UserDetails/UserOrganizations/index.tsx
Use organization role tag instead of normal string tag for organization roles in user details page.
Using the correct UI styles now
=> fix(console): should use organization role tag in user details page

packages/console/src/components/PermissionsTable/index.module.scss, packages/console/src/components/PermissionsTable/index.tsx, packages/console/src/pages/ApplicationDetails/components/MachineToMachineApplicationRoles/index.module.scss, packages/console/src/pages/ApplicationDetails/components/MachineToMachineApplicationRoles/index.tsx, packages/console/src/pages/Roles/index.module.scss, packages/console/src/pages/Roles/index.tsx, packages/console/src/pages/UserDetails/UserRoles/index.module.scss, packages/console/src/pages/UserDetails/UserRoles/index.tsx, packages/console/src/pages/Users/index.module.scss, packages/console/src/pages/Users/index.tsx
In addition to #4833, remove all fixed width applied to search fields, and auto fit to its placeholder content as minimum width.
Locally tested
=> refactor(console): search fields should auto fit its placeholder as minimum width

packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx, packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.module.scss, packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.tsx, packages/console/src/components/CreateTenantModal/index.module.scss, packages/console/src/components/CreateTenantModal/index.tsx, packages/console/src/ds-components/RadioGroup/Radio.module.scss, packages/console/src/ds-components/Tag/index.module.scss, packages/console/src/ds-components/Tag/index.tsx
refactor tenant creation form:
- Support small size styles for `<Tag />` component according to the design system
- Navigate to the plan subscription modal if the creating tenant is a `production` env tenant
- Deprecated `staging` env in the UI since we don't need it right now
- Remove the `trySafe` wrapper for the tenant creation request since now the error will be handled by the `useCloudApi` hook
Test locally and realted UI tests will be added in the cloud repo.
=> refactor(console): refactor tenant creation form

packages/core/src/middleware/koa-guard.ts, packages/core/src/routes/log.test.ts, packages/core/src/routes/log.ts, packages/core/src/routes/organization/index.ts, packages/schemas/src/foundations/jsonb-types/users.ts, packages/schemas/src/types/organization.ts
resolves LOG-7245. this can ensure the api response strips out unnecessary fields and matches the schema definition. also added LOG-7318 for follow-up.
=> refactor(core): overwrite response with parsed result

packages/console/src/App.tsx, packages/core/src/oidc/init.ts, packages/core/src/oidc/scope.ts, packages/core/src/queries/organizations.ts, packages/integration-tests/src/tests/api/oidc/id-token.test.ts, packages/schemas/src/types/organization.ts, packages/toolkit/core-kit/src/scope.ts
support the new `urn:logto:scope:organizations` scope per [RFC 0001](https://github.com/logto-io/rfcs/pull/2). 
note:
- some constants (e.g. scope name, grant type name) may differ during the implementation. rfc will be updated afterwards to match them.
- the new grant type will be a separate PR.
tested locally + added api test cases
=> feat: support organizations scope for ID token

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx, packages/console/src/consts/subscriptions.ts, packages/console/src/pages/TenantSettings/Subscription/index.tsx, packages/console/src/utils/subscription.ts
We will have "dev" plan in the next cloud version. But in the console, we should only display reserved plans on subscription pages, this PR is used to filter out all invisible plans on the page.
Test locally.
=> refactor(console): only display reserved plans in the console

packages/core/src/__mocks__/sso.ts, packages/core/src/libraries/sign-in-experience/index.test.ts, packages/core/src/libraries/sign-in-experience/index.ts, packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts, packages/core/src/routes/interaction/utils/single-sign-on-guard.ts, packages/core/src/routes/sso-connector/type.ts, packages/experience/src/__mocks__/logto.tsx, packages/integration-tests/src/constants.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts, packages/integration-tests/src/tests/api/interaction/single-sign-on/happy-path.test.ts, packages/integration-tests/src/tests/api/sso-connectors.test.ts, packages/integration-tests/src/tests/api/well-known.test.ts, packages/schemas/alterations/next-1699598903-remove-sso-only-column-in-sso-connectors-table.ts, packages/schemas/src/types/sso-connector.ts, packages/schemas/tables/sso_connectors.sql
Per our latest product updates,  the`ssoOnly` property is removed from the single-sign-on connector. For the MVP stage, we give a strict restriction on all the registered domains to use the single sign on authentication method.
This PR will cause the db alteration compatibility ci job fails. Since a property has been removed, the API response guard from the base code with throw error.
Since we are still under the development cycle. To eliminate the painful steps of migration,  will force push this PR. 
ci
=> feat(core,schemas): remove the ssoOnly setting of the sso connectors

.changeset/warm-tips-attack.md, .vscode/settings.json, packages/core/package.json, packages/core/src/routes/init.ts, packages/core/src/routes/swagger/index.test.ts, packages/core/src/routes/swagger/index.ts, packages/core/src/routes/swagger/utils/general.ts, packages/core/src/routes/swagger/utils/parameters.ts, packages/core/src/utils/SchemaRouter.ts, packages/core/src/utils/zod.ts
refactor the swagger (openapi) json generator.
generate components to reuse `:id` and `:entityId` path parameters. for example:
- path `/users/:id` and `/users/:id/roles/:roleId` can reuse the `:id` parameter.
- path `/roles/:id/users/:userId` and `/organizations/:id/users/:userId` can reuse the `:userId` parameter.
since different `:id` parameters may have different types, we'll generate two parameters for each entity:
```jsonc
{
"components": {
"parameters": {
"userId": { "name": "userId", "in": "path", /* ... */ },
"userId:root": { "name": "id", "in": "path", /* ... */ },
"roleId": { "name": "roleId", "in": "path", /* ... */ },
"roleId:root": { "name": "id", "in": "path", /* ... */ }
}
}
}
```
the entity needs to specify in the `identifiableEntityNames` variable in the …
=> refactor(core): generate shared id parameters definition for swagger

packages/core/src/routes/organization/roles.ts, packages/integration-tests/src/helpers/organization.ts, packages/integration-tests/src/tests/api/organization-role.test.ts
bring back role api updates mistakenly removed in [this commit](https://github.com/logto-io/logto/commit/e244b62a39fe8bd7f88164c0279312e98a5cbfb2#diff-dd163871188b9c4201f9addfa28787133effb3460e6ad02c170211c63b72c260)
added integration tests
=> refactor(core): fix org apis

packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.module.scss, packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.tsx, packages/console/src/pages/UserDetails/UserSettings/components/UserSsoIdentities/index.tsx, packages/console/src/pages/UserDetails/UserSettings/index.tsx, packages/console/src/pages/UserDetails/index.tsx, packages/console/src/pages/UserDetails/types.ts, packages/core/src/queries/user-sso-identities.ts, packages/core/src/routes/admin-user/basics.ts, packages/integration-tests/src/api/admin-user.ts, packages/integration-tests/src/tests/api/admin-user.test.ts, packages/schemas/src/types/user.ts
1. reorg the user details page and make SSO identities visible.
2. update `GET /api/users/:userId` and corresponding zod guard/type definitions to return the user's (characterized using `userId`) SSO identities.
- Update SSO identity queries as well since the previous syntax is not right.
~~- [x] integration tests~~
=> feat(console): show SSO identities on user details page and reorg the page

packages/console/src/components/Drawer/index.module.scss, packages/console/src/pages/OrganizationDetails/index.tsx, packages/console/src/pages/Organizations/Guide/Introduction/components/User/index.tsx, packages/console/src/pages/Organizations/Guide/Introduction/index.module.scss, packages/console/src/pages/Organizations/Guide/Introduction/index.tsx
Improve organization guide in drawer view by:
1. adding a brief header that consists of the title, subtitle and a close button
2. improving the layout and padding of the drawer content
=> fix(console): add a brief header to the organization guide in drawer view

packages/experience/src/App.tsx, packages/experience/src/Providers/SingleSignOnContextProvider/index.tsx, packages/experience/src/hooks/use-check-single-sign-on.ts, packages/experience/src/pages/Register/IdentifierRegisterForm/index.test.tsx, packages/experience/src/pages/Register/IdentifierRegisterForm/use-on-submit.ts, packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx, packages/experience/src/pages/SignIn/IdentifierSignInForm/use-on-submit.ts, packages/experience/src/pages/SingleSignOnEmail/index.tsx
Block email sign-in and register if SSO is enabled for that domain address.
In the sign-in and register home page,  if the input identifier type is email and has SSO connectors enabled, check the single sign-on first. If the email is registered with some SSO connectors should directly navigate to the SSO sign-in page. 
https://github.com/logto-io/logto/assets/36393111/b891b860-ed37-440f-b31d-d232aabe3f73
- move the `SingleSignOnContextProvider` to the top level, so all the page can have the SSO context.
- move and rename the singleSignOn email check onSubmit hook to the shared hook level. So all the pages can call this hook to check the sso connectors for a given email input.
- call the`checkSingleSignOn` first in the `sign-in` and `register` …
=> feat(experience): block email sign-in and register

packages/core/src/routes/interaction/utils/single-sign-on-guard.ts, packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts, packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
Add social returned email sso guard. If the social userInfo contains a email with SSO registered domain, we should reject the social identity, and throw SSO enabled error.
UT
=> feat(core): add social returned email sso guard

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx, packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx, packages/console/src/consts/external-links.ts, packages/console/src/ds-components/TextLink/index.tsx, packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.module.scss, packages/console/src/pages/GetStarted/DevelopmentTenantNotification/index.tsx
feat(console): add pricing link for dev tenant notification
- Remove redundant fragment item for the text link component
- Extract the link style into a single line of code
- Replace the pricing page link with a constant
- Add missing `rel="noopener"` props for pricing links
- LOG-7478: Provide default `rel` prop value for `TextLink` component
Test locally.
=> feat(console): add pricing link for dev tenant notification

packages/experience/src/hooks/use-check-single-sign-on.ts, packages/experience/src/hooks/use-password-sign-in.ts, packages/experience/src/pages/SignIn/PasswordSignInForm/index.module.scss, packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx, packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx, packages/experience/src/pages/SignIn/PasswordSignInForm/use-single-sign-on-watch.ts, packages/phrases-experience/src/locales/de/description.ts, packages/phrases-experience/src/locales/en/description.ts, packages/phrases-experience/src/locales/es/description.ts, packages/phrases-experience/src/locales/fr/description.ts, packages/phrases-experience/src/locales/it/description.ts, packages/phrases-experience/src/locales/ja/description.ts, packages/phrases-experience/src/locales/ko/description.ts, packages/phrases-experience/src/locales/pl-pl/description.ts, packages/phrases-experience/src/locales/pt-br/description.ts, packages/phrases-experience/src/locales/pt-pt/description.ts, packages/phrases-experience/src/locales/ru/description.ts, packages/phrases-experience/src/locales/tr-tr/description.ts, packages/phrases-experience/src/locales/zh-cn/description.ts, packages/phrases-experience/src/locales/zh-hk/description.ts, packages/phrases-experience/src/locales/zh-tw/description.ts
Add single sign on switch to the password sign-in form. 
Unlike other identifier input only forms, for password sign-in form we auto detect wheter a input email has registered with any sso connectors. If sso is enabled for this email we switch the form to single-sign-on and nav to the single sign-on page.
https://github.com/logto-io/logto/assets/36393111/8c11a665-dce6-4121-b4a6-c6e0e63d9fdb
test locally
UT case added
=> feat(experience): add single sign on switch to the password sign-in form

packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/index.tsx, packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
The MFA feature item should be displayed in downgrade plan modal.
**Note**: this bug only affect the Logto cloud.
=> fix(console): display mfa feature item in downgrade plan modal

packages/console/src/components/PlanQuotaList/index.tsx, packages/console/src/pages/TenantSettings/Subscription/DowngradeConfirmModalContent/index.tsx, packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx, packages/console/src/types/subscriptions.ts
Per offline discussion with designers, we should hide coming soon features in the downgrade plan modal.
- Extract the `SubscriptionPlanQuotaEntries` into a type since it's used in many places.
Before:
After:
=> fix(console): hide coming soon features from the downgrade plan modal

.changeset/empty-buttons-ring.md, packages/cli/src/commands/translate/sync-keys/utils.ts, packages/cli/src/commands/translate/sync.ts
support sync array keys with string and nested objects:
```ts
{
foo: ['bar', { baz: 'baz' }]
}
```
tested with website phrases. works as expected
=> feat(cli): support sync array keys

packages/console/src/ds-components/Button/index.module.scss, packages/console/src/pages/Organizations/TemplateTable/index.module.scss, packages/console/src/pages/Organizations/TemplateTable/index.tsx
The default button should have icons rendered in secondary text color. Previously it was following the color of the button text and the designers said no no.
Previously the icon was black, same as the text color. Now it's gray
=> fix(console): default button icon should use secondary color

packages/experience/package.json, packages/experience/src/hooks/use-session-storages.test.ts, packages/experience/src/hooks/use-session-storages.ts, packages/experience/src/types/guard.ts, pnpm-lock.yaml
Based on our [discussion_r1395090089](https://github.com/logto-io/logto/pull/4865#discussion_r1395090089).
@charIeszhao 
Implement a strict return value type guard using superstruct. 
Guard the return value. Clear the storage if the value in session storage is type-incompatible and returns undefined. 
UT
=> feat(experience): add struct guard to session storage hook 

packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx, packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx, packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx, packages/console/src/utils/subscription.ts
When downgrading and not eligible, only shows the criteria which users don't meet with.
Note: Per discussion, since `withtyped` only returns a `message` field in the error response body, so we retrieve the exceeded quota data from the `message` field.
=> refactor(console): only display exceeded quota items on not eligible switch plan modal

packages/experience/src/hooks/use-native-message-listener.ts, packages/experience/src/pages/SocialSignInCallback/SingleSignOn.tsx
Add the native message listener to the SSO callback page.
In the previous implementation, we have the native message listener being registered in two places:
1. `SocialSignIn` Container:  Listed on the SignIn/Register home page.
2. `SingleSignOnConnecters` Page.
There are two steps we need to listen to the native message:
1. when the user clicks on the connector button (Social or SSO) to init a sign-in flow
2. when IdP redirects the user back to our `sign-in/callback` page.
This PR adds the native message listener to the SSO `sign-in/callback` page. Also add a condition `bypass` parameter. Only register the new listener if there are no social connectors. As it will be registered by the `SocialSignIn` Container.
N/A
=> feat(experience): add native listener to SSO callback page

packages/core/src/routes/interaction/single-sign-on.ts, packages/core/src/routes/interaction/utils/single-sign-on-guard.ts, packages/core/src/routes/interaction/utils/single-sign-on-session.ts, packages/core/src/routes/interaction/utils/single-sign-on.test.ts, packages/core/src/routes/interaction/utils/single-sign-on.ts, packages/core/src/sso/types/session.ts, packages/experience/src/apis/single-sign-on.ts, packages/experience/src/pages/SocialSignInCallback/use-single-sign-on-listener.ts
Extract SSO register api.
Previously the SSO authentication flow was simple and straightforward. Only two interaction APIs are designed:
- `GET /interaction/single-sign-on/:connectorId/authorization-url`:  Initiate an SSO sign-in interaction and get the authorization URL for the SSO
- `POST /interaction/single-sign-on/:connectorId/authentication`: Get authenticated by the SSO provider and try to sign in with Logto. If no related user SSO identity is found we automatically create a new account. 
In short words, the register flow is merged with the sign-in flow. 
Now per our product design, all the new users have to confirm the terms of use before actually registering a new account. Thus, we need to split the register request apart from the authentication endpoint. 
In this PR:
1. Remove …
=> refactor(core,experience): extract sso register api

packages/console/src/pages/EnterpriseSso/Guide/index.tsx
partially check `config` on the guide page.
Can continue on guide page when leave OIDC SSO connector's form blank.
=> fix(console): partially check config on guide page

packages/console/src/pages/EnterpriseSso/index.tsx, packages/console/src/pages/EnterpriseSsoDetails/index.tsx
Fix SAML SSO connector status.
Not configured SAML SSO connectors show "in use".
Before this fix, all SAML SSO connectors show "in use".
=> fix(console): fix SAML SSO connector status

packages/console/src/pages/EnterpriseSso/Guide/BasicInfo/index.tsx, packages/console/src/pages/EnterpriseSso/Guide/SamlMetadataForm/index.tsx
update SSO console display:
1. Fix the value showing as `entityId` and `acsUrl`
2. Should not show inline notification on guide page
=> fix(console): update SSO console display

packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx, packages/console/src/pages/Organizations/index.tsx, packages/core/src/middleware/koa-quota-guard.ts, packages/core/src/routes/organization/index.ts, packages/core/src/routes/organization/roles.ts, packages/core/src/routes/organization/scopes.ts, packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts
Add paywalls to organization APIs and create modal in console.
Locally tested
Call organization APIs from Free plan tenant will end up with an error:
If the Free plan somehow has pre-existed organizations (dev testing data), you will not be able to create more organizations through the UI, either.
=> feat(console,core,phrases): add more organization paywalls

packages/console/src/pages/EnterpriseSso/Guide/BasicInfo/index.tsx, packages/console/src/pages/EnterpriseSso/Guide/OidcMetadataForm/ParsedConfigPreview/index.tsx, packages/console/src/pages/EnterpriseSso/Guide/OidcMetadataForm/index.module.scss, packages/console/src/pages/EnterpriseSso/Guide/OidcMetadataForm/index.tsx, packages/console/src/pages/EnterpriseSso/Guide/index.tsx, packages/console/src/pages/EnterpriseSso/index.tsx, packages/console/src/pages/EnterpriseSsoDetails/Connection/index.tsx, packages/console/src/pages/EnterpriseSsoDetails/index.tsx
1. Map out-of-the-box SSO connectors' form to either SAML or OIDC form according to the protocol the SSO connector is based on.
2. Remove the isReadonly flag for SAML attribute mapping component, edit on attribute mapping is always allowed.
3. For SAML protocol-based SSO connectors (SAML and AAD), it should pass default attribute mapping.
4. Update the SSO connectors' isUse check logic.
=> feat(console): reuse existing oidc/saml form for OOTB SSO connector config

packages/core/src/sso/SamlConnector/index.ts, packages/core/src/sso/SamlConnector/utils.ts, packages/core/src/sso/SamlSsoConnector/index.test.ts, packages/core/src/sso/SamlSsoConnector/index.ts, packages/core/src/sso/types/saml.ts
LOG-7549
@darcyYe 
Based on the previous PR #4958 we no longer allow partial SSO config to exist in DB. Either empty or safely parsed.
So in this PR we update the SAML config type to be more strict. 
Previously, all the fields are optional.
```ts
{
metadataUrl?: string;
metadata?: string;
entityId?: string;
signInEndpoint?: string;
x509Certificate?: string;
attributeMapping?: Map
}
```
In this PR we use a strict union type to guard the config
```ts
{
metadataUrl: string;
attributeMapping?: Map
} | {
metadata: string;
attributeMapping?: Map
} | {
entityId: string;
signInEndpoint: string;
x509Certificate: string;
attributeMapping?: Map
}
```
This refactors some of the implementation logics in the SAML connector.
test locally
=> refactor(core): refactor SAML SSO idpConfig type

packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts, packages/core/src/sso/OidcConnector/index.ts
Set google SSO connector prompt always select-account.
This PR fix the following situation:
Local browser has a personal google account sign-in session.
Sign-in to Logto using a workspace account specific google sso connector.
Unable to select/sign-in to another workspace google account. 
Fix: Set the prompt to select_account for google
Test locally
=> fix(core): update google SSO connector prompt always select-account

packages/core/src/routes/interaction/utils/single-sign-on.test.ts, packages/core/src/routes/sso-connector/index.ts, packages/core/src/routes/sso-connector/utils.test.ts, packages/core/src/routes/sso-connector/utils.ts, packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts, packages/core/src/sso/OidcConnector/index.ts, packages/core/src/sso/OidcConnector/utils.test.ts, packages/core/src/sso/OidcConnector/utils.ts, packages/core/src/sso/OidcSsoConnector/index.test.ts, packages/core/src/sso/OidcSsoConnector/index.ts, packages/core/src/sso/OktaSsoConnector/index.ts, packages/core/src/sso/SamlConnector/index.ts, packages/core/src/sso/SamlConnector/utils.ts, packages/core/src/sso/SamlSsoConnector/index.test.ts, packages/core/src/sso/SamlSsoConnector/index.ts, packages/core/src/sso/index.ts, packages/core/src/sso/types/error.ts, packages/core/src/sso/types/index.ts, packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
Per our latest product design we need to fetch and guard the config on all the config update endpoints. (POST, PATCH).
Throws error if the config schema is invalid
Throws error if the config fetching url (issuer for OIDC, metadata URL for SAML) request failed.
Throws error if the SAML metadata file is invalid.
This PR also includes the following updates:
- Shrink the `SsoConnector` class input data type to a limited fields only usable to the SsoConnector. So we may able to create the Connector instance without actually creating a full DB schema. e.g. on the POST endpoint. 
- Define new `SsoConnectorError` class based on the `Connector` class. Refine all the exception details.
test locally
=> feat(core): guard sso config

packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx, packages/experience/src/pages/SignIn/IdentifierSignInForm/use-on-submit.ts
should use absolute path for the password sign-in form navigation.
On the social/SSO sign-in callback page, the location URL is specified as `/sign-in/social/:connectorId`, but shares a same page rendering logic as default `/sign-in` page. In the event of a failed social/SSO authentication, users should have the option to utilize the default sign-in form to log in using their password.
However, a previous issue arose where the navigation to the password sign-in form used a relative path, directing users to `/sign-in/social/:connectorId/password`, resulting in a 404 error.
To address this, the password sign-in form navigation now uses an absolute path, ensuring that both `/sign-in` and `/sign-in/social/:connectorId` paths should lead users to the `/sign-in/password` page. T
test locally
=> fix(experience): use absolute path for password sign-in form nav

packages/core/src/libraries/sign-in-experience/index.test.ts, packages/core/src/libraries/sign-in-experience/index.ts, packages/core/src/queries/sso-connectors.ts, packages/core/src/routes/sso-connector/index.ts, packages/integration-tests/src/constants.ts, packages/integration-tests/src/tests/api/interaction/register-with-identifier/sad-path.test.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/sad-path.test.ts, packages/integration-tests/src/tests/api/sso-connectors.test.ts, packages/integration-tests/src/tests/api/well-known.test.ts, packages/integration-tests/src/utils.ts, packages/phrases/src/locales/de/errors/single-sign-on.ts, packages/phrases/src/locales/en/errors/single-sign-on.ts, packages/phrases/src/locales/es/errors/single-sign-on.ts, packages/phrases/src/locales/fr/errors/single-sign-on.ts, packages/phrases/src/locales/it/errors/single-sign-on.ts, packages/phrases/src/locales/ja/errors/single-sign-on.ts, packages/phrases/src/locales/ko/errors/single-sign-on.ts, packages/phrases/src/locales/pl-pl/errors/single-sign-on.ts, packages/phrases/src/locales/pt-br/errors/single-sign-on.ts, packages/phrases/src/locales/pt-pt/errors/single-sign-on.ts, packages/phrases/src/locales/ru/errors/single-sign-on.ts, packages/phrases/src/locales/tr-tr/errors/single-sign-on.ts, packages/phrases/src/locales/zh-cn/errors/single-sign-on.ts, packages/phrases/src/locales/zh-hk/errors/single-sign-on.ts, packages/phrases/src/locales/zh-tw/errors/single-sign-on.ts, packages/schemas/src/foundations/jsonb-types/sso-connector.ts
Add SSO displayName
Per our product updates need to add a new branding field `displayName` to the SSO connector schema.
Previously: we use `connectorName` for both AC and experience display use. And `connectorName` is not unique.
New updates: set a unique constrain on the `connectorName`  field. It will be only used in AC. Add a new branding field `displayName` for the client side experience connect button display use.
- Schema: add unique constrain on the `connectorName`  field
- Schema: add new field `displayName` on the branding Jsonb type
- API: update the post and patch method, add a `connectorName`  exist validation. 
- Phrases: add new `connector.duplicate_connector_name` error phrase
- SIE: update the original sign-in-experience response. Returns the connector's displayName as …
=> refactor(core,schemas): add SSO displayName

packages/console/src/pages/EnterpriseSso/SsoConnectorLogo/index.tsx, packages/console/src/pages/EnterpriseSsoDetails/Settings/index.tsx
fix the wrong illustration status.
Update the fallback logic of SSO connector logos.
=> fix(console): fix wrong illustration status

packages/console/src/pages/EnterpriseSsoDetails/Settings/LogosUploader/index.tsx
update SSO connector logo uploader file types, only allow PNG, JPG and SVG file types.
=> fix(console): update SSO connector logo uploader file types

packages/console/src/pages/EnterpriseSsoDetails/Experience/MultiInput/index.module.scss, packages/console/src/pages/EnterpriseSsoDetails/Experience/index.module.scss, packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx, packages/phrases/src/locales/de/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/es/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/it/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso-details.ts
1. Add email domain fields inline notification when not configured.
2. Add error style for email domain field
Save with email domain not configured.
Inline notification disappears after email domain is not empty.
=> feat(console,phrases): add inline notification if email domain not configured

packages/console/src/pages/EnterpriseSso/SsoConnectorLogo/index.tsx, packages/console/src/pages/EnterpriseSso/SsoConnectorLogo/utils.test.ts, packages/console/src/pages/EnterpriseSso/SsoConnectorLogo/utils.ts, packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.module.scss, packages/console/src/pages/UserDetails/UserSettings/components/UserSsoIdentities/index.tsx
1. fix the SSO connector logo fallback logic, when the system was in dark mode and only the light mode logo was configured, the configured light mode logo should be displayed.
2. Add missed `branding` field to SSO identity `displayConnectors`.
Previously this user management page throws an error since `branding` is not passed.
=> fix(console): fix SSO connector logo fallback logic

packages/core/src/libraries/sign-in-experience/index.test.ts, packages/core/src/libraries/sign-in-experience/index.ts, packages/core/src/routes/well-known.ts, packages/core/src/utils/translation.ts
Use the new added name attribute as the default connector name for the client side. 
test locally
=> refactor(core): use name attribute as the default connector name

packages/console/src/pages/SignInExperience/tabs/Content/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss, packages/console/src/pages/SignInExperience/tabs/Content/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
Per offline discussion, should change the save button to medium size and fix the language footer to `60px`.
=> style(console): update save button styles on language editor

packages/console/src/pages/EnterpriseSso/types.ts, packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlMetadataForm/ParsedConfigPreview/index.module.scss, packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlMetadataForm/ParsedConfigPreview/index.tsx, packages/core/src/sso/SamlConnector/index.ts, packages/core/src/sso/SamlConnector/utils.test.ts, packages/core/src/sso/SamlConnector/utils.ts, packages/core/src/sso/types/saml.ts, packages/phrases/src/locales/de/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/es/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/fr/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/it/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/ja/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/ko/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/ru/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/enterprise-sso-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/enterprise-sso-details.ts
update certificate display:
For valid SAML SSO connectors' config, return the parsed result of the certificate as well (in Logto, this includes both `expirationTime` and `isValid`)
We only support PEM encoding certificates in this PR.
We hence show:
- Whether the certificate is still valid
- The expiration time of the certificate
We also provide a copy button to load the parsed PEM certificate to the clipboard.
TODO:
Support certificates in other decoding (like DER).
Parsed certificate got via copy icon.
=> feat(console): update certificate display

.changeset/silent-eyes-leave.md, packages/core/src/oidc/init.ts, packages/core/src/oidc/scope.test.ts, packages/core/src/oidc/scope.ts, packages/toolkit/core-kit/src/openid.ts
- userinfo endpoint will return `organization_data` claim if organization scope is requested
- refactor user claim fetch function to share organization query between organization cliaims 
The new claim includes all organizations that the user is a member of with the following structure:
```json
{
"organization_data": [
{
"id": "organization_id",
"name": "organization_name",
"description": "organization_description",
}
]
}
```
=> refactor(core): return organization data in userinfo endpoint

packages/core/src/__mocks__/sign-in-experience.ts, packages/core/src/libraries/sign-in-experience/index.test.ts, packages/core/src/libraries/sign-in-experience/index.ts, packages/core/src/queries/sign-in-experience.test.ts, packages/experience/src/__mocks__/logto.tsx, packages/integration-tests/src/tests/api/sign-in-experience.test.ts, packages/integration-tests/src/tests/api/well-known.test.ts, packages/schemas/alterations/next-1701245520-add-single-sign-on-enabled-flag-to-sie.ts, packages/schemas/tables/sign_in_experiences.sql
Per latest product design we are adding a  new singleSignOnEnabled field to the sign-in-experience data. 
When ssoEnabled set to false,  no sso connectors should been enabled. sie always return empty array to the client.
The default value is false.
Test locally
=> feat(core,schemas): add new singleSignOnEnabled field to sie

packages/experience/src/Providers/SingleSignOnFormModeContextProvider/SingleSignOnFormModeContext.tsx, packages/experience/src/Providers/SingleSignOnFormModeContextProvider/index.tsx, packages/experience/src/components/InputFields/SmartInputField/index.tsx, packages/experience/src/containers/TermsAndPrivacy/index.module.scss, packages/experience/src/hooks/use-sie.ts, packages/experience/src/hooks/use-single-sign-on-watch.ts, packages/experience/src/pages/Register/IdentifierRegisterForm/index.module.scss, packages/experience/src/pages/Register/IdentifierRegisterForm/index.test.tsx, packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx, packages/experience/src/pages/Register/index.test.tsx, packages/experience/src/pages/Register/index.tsx, packages/experience/src/pages/SignIn/IdentifierSignInForm/index.module.scss, packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx, packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx, packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx, packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx, packages/experience/src/pages/SignIn/index.tsx
Enable SSO auto watch to the sign-in and register form.
Previously we have SSO auto detect feature enabled for the password sign-in form only. If a input email is detected as SSO enabled, auto switch the form to SSO mode. 
Base on latest design, apply this flow to all the sign-in and register forms.
https://github.com/logto-io/logto/assets/36393111/00af7326-62b8-435a-b2f8-e0b2f9d08831
Major updates:
- introduce a page level `SingleSignOnFormModeContextProvider`. This is used to share the single sign on form visibility between the child form component with its parent component. If the form is switch to SSO mode, should hide all related footer elements. 
- Move the `useSingleSignOnWatch` to the shared `hooks` directory, and apply it to the `sign-in-identifier` form and `register-identifier` …
=> feat(experience): enable SSO auto watch to the sign-in and register form

packages/experience/src/hooks/use-check-single-sign-on.ts
should not show error message on sign-in page
Should not show the invalid query (invalid email) error message on the identifier form submit flow. Should handle silently.
Unexpected:
Show error message only on the SSO page:
test locally
=> fix(experience): should not show error message on sign-in page

packages/console/src/pages/EnterpriseSso/types.ts, packages/console/src/pages/EnterpriseSsoDetails/Connection/index.tsx, packages/core/package.json, packages/core/src/sso/SamlConnector/index.ts, packages/core/src/sso/types/error.ts, pnpm-lock.yaml
show invalid SSO config/metadata error message inline.
1. for OIDC based SSO connectors, all invalid config error comes from invalid `issuer`, show error message inline to `issuer` input field.
2. for SAML based SSO connectors, previous XML validator swallows the error, should check explicit check the validity of XML metadata. Catch the invalid metadata error for SAML based SSO connectors and show inline. Only `metadata` or `metadataURL` fields can result in creating IdP instance with XML metadata.
=> chore(console,core): show invalid SSO config/metadata error message inline

packages/console/src/components/CreateConnectorForm/index.tsx, packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx, packages/console/src/pages/EnterpriseSso/index.tsx, packages/integration-tests/src/tests/console/connectors/social-connector-test-cases.ts
1. Hide SAML Social creation entrance (the filter has been accidentally deleted).
2. Fix SSO connector paywall, when there is existing SSO connectors, the paywall should locate at the footer of creation modal.
=> refactor(console): hide saml social connector entrance and fix SSO creation paywall

packages/core/src/routes/sso-connector/index.ts
fix SSO quota guard.
The guard should directly apply to the route instead of using router.use() (this could affect all APIs.)
Does not block other POST/PUT APIs.
Also `POST /sso-connectors` API is guarded:
`GET /sso-connectors` API works fine:
TODO:
Add quota guard tests for APIs.
=> fix(core): fix SSO quota guard

.changeset/tame-crabs-breathe.md, packages/console/src/components/CreateConnectorForm/index.tsx
should hide upsell tag for standard connectors in OSS version.
1. Upsell tag not showing up in OSS version.
2. Upsell tag should be visible for the cloud version.
=> fix: should hide upsell tag for standard connectors in OSS version

packages/core/src/routes/sso-connector/index.ts
rename SSO connectors management API routes.
Both interaction-related SSO APIs and SSO connectors management APIs routes are both called `singleSignOnRoutes`, which can lead to confusion. Rename the SSO connector management API routes to be `singleSignOnConnectorsRoutes` to avoid repeated names. cc @xiaoyijun 
N/A
=> chore(core): rename SSO connectors management API routes

packages/console/src/pages/UserDetails/UserSettings/components/UserSocialIdentities/index.tsx
Fix an infinite loading issue on user social identities table, when there's no data
=> fix(console): user identities table should not always be loading when no data

packages/console/src/components/UnsavedChangesAlertModal/index.tsx, packages/console/src/pages/ApplicationDetails/index.tsx
Fix: discard applicaiton settings changes when switching tabs.
- Support add confirmation callback to the `UnsavedChangesAlert` modal
- Add reset data callback to the `UnsavedChangesAlert` on the application settings page
=> fix(console): discard application settings changes when switching tabs

packages/core/src/queries/application.test.ts, packages/core/src/queries/application.ts, packages/core/src/routes/applications/application.ts, packages/core/src/routes/applications/types.ts, packages/integration-tests/src/api/application.ts, packages/integration-tests/src/tests/api/application.test.ts, packages/phrases/src/locales/de/errors/application.ts, packages/phrases/src/locales/en/errors/application.ts, packages/phrases/src/locales/es/errors/application.ts, packages/phrases/src/locales/fr/errors/application.ts, packages/phrases/src/locales/it/errors/application.ts, packages/phrases/src/locales/ja/errors/application.ts, packages/phrases/src/locales/ko/errors/application.ts, packages/phrases/src/locales/pl-pl/errors/application.ts, packages/phrases/src/locales/pt-br/errors/application.ts, packages/phrases/src/locales/pt-pt/errors/application.ts, packages/phrases/src/locales/ru/errors/application.ts, packages/phrases/src/locales/tr-tr/errors/application.ts, packages/phrases/src/locales/zh-cn/errors/application.ts, packages/phrases/src/locales/zh-hk/errors/application.ts, packages/phrases/src/locales/zh-tw/errors/application.ts
Update applications API to support third-party apps.
- Delete the `findAllApplications` query as it is no longer used.
- Update the `getApplications` query method to filter by isThirdParty field
- Update the `GET /applications` API. By default should return only `isThirdParty=false` applications. And return third-party applications only `isThirdParty` flag is present in the query parameters.
- Update the `POST /applications` API. Add application type guard for third-party applications.  All the third-party applications must be Traditional. 
- Also fix a bug `excludeRoleId` should be listed in the query guard, instead of directly read from raw search parameters. @darcyYe 
test locally
=> feat(core,phrases): update applications api to support third-party app

.changeset/chilly-bobcats-doubt.md, packages/core/src/routes/organization/index.openapi.json, packages/core/src/routes/organization/roles.openapi.json, packages/core/src/utils/RelationQueries.ts, packages/integration-tests/src/tests/api/organization-role.test.ts
Set `on conflict do nothing` for the `RelationQueries` insert operation.
For all the relation table entities, we want to insert them into the database safely. If the relation entity already exists, instead of throwing an error, ignore the insert operation,
=> refactor(core): add on conflic ignore to the Relation insert query method

.vscode/settings.json, packages/core/src/database/find-entity-by-id.ts, packages/core/src/libraries/application.ts, packages/core/src/queries/application-user-consent-scopes.ts, packages/core/src/queries/application.ts, packages/core/src/routes/applications/application-user-consent-scope.openapi.json, packages/core/src/routes/applications/application-user-consent-scope.ts, packages/core/src/routes/init.ts, packages/core/src/utils/SchemaQueries.ts, packages/integration-tests/package.json, packages/integration-tests/src/api/application-user-consent-scope.ts, packages/integration-tests/src/tests/api/application-user-consent-scope.test.ts, packages/phrases/src/locales/de/errors/application.ts, packages/phrases/src/locales/en/errors/application.ts, packages/phrases/src/locales/es/errors/application.ts, packages/phrases/src/locales/fr/errors/application.ts, packages/phrases/src/locales/it/errors/application.ts, packages/phrases/src/locales/ja/errors/application.ts, packages/phrases/src/locales/ko/errors/application.ts, packages/phrases/src/locales/pl-pl/errors/application.ts, packages/phrases/src/locales/pt-br/errors/application.ts, packages/phrases/src/locales/pt-pt/errors/application.ts, packages/phrases/src/locales/ru/errors/application.ts, packages/phrases/src/locales/tr-tr/errors/application.ts, packages/phrases/src/locales/zh-cn/errors/application.ts, packages/phrases/src/locales/zh-hk/errors/application.ts, packages/phrases/src/locales/zh-tw/errors/application.ts, pnpm-lock.yaml
Add POST application user consent scopes API.
1.  Add the batch `findByIds` method to the `SchemaQueries` class. So we may batch query entities.
2. Add three new application library methods along with the query methods for the API use
- `validateThirdPartyApplicationById`: Find the application by id and assert type is a third-party app. 
- `validateApplicationUserConsentScopes`: Find all the `organizationScopes` and `resourceScopes` in the request body. This makes sure all the requested scopes exist in DB. 
- `assignApplicationUserConsentScopes`: Insert `application-user-consent-organization-scopes`, `application-user-consent-resource-scopes` and `application-user-consent-user-scopes` to DB,
3. Add new API `POST …
=> feat(core,phrases): add post application user consent scopes api

packages/console/src/components/CreateConnectorForm/index.tsx
`null` value stands for 'unlimited' in our plan quota, so we need to check if the quota value is `0` to determine the standard connectos feature is enabled or not.
=> fix(console): hide feature tag when standard connectors is unlimited

.github/workflows/alteration-compatibility-integration-test.yml, .github/workflows/main.yml, .scripts/compare-database.js, packages/cli/src/commands/database/seed/index.ts, packages/cli/src/commands/database/seed/tables.ts, packages/cli/src/commands/database/seed/tenant-organizations.ts, packages/cli/src/database.ts, packages/schemas/alterations/next-1702544178-sync-tenant-orgs.ts, packages/schemas/src/seeds/application.ts, packages/schemas/src/types/index.ts, packages/schemas/src/types/mapi-proxy.ts, packages/schemas/src/types/tenant-organization.ts, packages/schemas/src/types/tenant.ts
This is the beginning of the tenant organization series.
The main goal of this series is to leverage Logto Organizations for managing user tenants, replacing the current API resource-based approach. This will allow us to provide a better user experience for Logto Cloud, and it is also the foundation for collaboration features.
- Tenant organization: An organization that represents a user tenant in the admin tenant.
- Management API proxy: An endpoint in Logto Cloud that proxies all requests to the corresponding tenant's Management API.
- Database alteration script
- Common types, enums, and utils for tenant organizations
- CLI now supports only seeding test data for legacy versions
When creating a new tenant (e.g. `foo`), the following resources will be created in the admin tenant: …
=> refactor(schemas,core,cli): init tenant organizations

packages/console/src/App.tsx, packages/console/src/containers/TenantAccess/index.tsx, packages/console/src/contexts/TenantsProvider.tsx, packages/console/src/hooks/use-api.ts
> [!Warning]
> this pull depends on https://github.com/logto-io/cloud/pull/398 to work properly.
a follow-up of #5105. uses organizations for cloud multi-tenancy, and keep the API resource method for OSS.
tested locally with OSS and Cloud. currently no additional test is needed since it does not change business logic.
=> refactor(console): use organization token for management api

packages/console/src/components/QuotaGuardFooter/index.tsx, packages/console/src/hooks/use-api-resources-usage.ts, packages/console/src/hooks/use-applications-usage.ts, packages/console/src/hooks/use-subscribe.ts, packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx, packages/console/src/pages/ApiResources/components/CreateForm/index.tsx, packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx, packages/console/src/pages/Applications/components/CreateForm/index.tsx
- Update instuction phrase
- Skip m2m quota guard for paid plan since the m2m app will be an add-on feature
- Skip API resources quota guard for paid plan since the API resource will be an add-on feature
- Add loading state to `useSubscribe` hook since we need to display loading state befor navigating to the checkout page
- Support customizing the upgrade plan action and add a loading state for `QuotaFooter` component, since sometimes we will need to navigate to the checkout page from the upgrade button on the footer.
- Reorg the API resources `CreateForm` component code by extracting the footer logic into a new component, since the fallback logic is complex.
- Add 2 hooks to manage application and API resources usage, since they will be used in …
=> refactor(console): update upsell instruction for m2m app & resource creation

packages/console/src/components/CreateConnectorForm/index.tsx, packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.tsx, packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx, packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx, packages/console/src/components/Guide/GuideCard/index.tsx, packages/console/src/components/PlanDescription/index.tsx, packages/console/src/components/PlanName/index.tsx, packages/console/src/consts/subscriptions.ts, packages/console/src/pages/Applications/components/GuideLibrary/index.tsx, packages/console/src/pages/Applications/components/TypeDescription/index.tsx, packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx, packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
For migration compatibility, in new pricing feature, we treat the orginal hobby plan as the new pro plan. So we need to update following items in the console:
- Remove pro plan from featured subscription plans. (Will hide pro plan in the console)
- Map all hobby plan phrases to pro plan phrases
- Replace all 'hobby' feature paywall tag with 'pro' tag. (We display the plan id in the feature tag, will deprecated the pro id after the new pricing feature is launched)
- Replace orignial pro plan usages with hobby plan
- Deprecate the hobby plan id after the new pricing feature is luanched
- Remove deprecated phrases for hobby plan
Test locally.
=> refactor(console): treat hobby plan as the new pro plan

packages/console/src/components/Guide/GuideCard/index.tsx, packages/console/src/pages/EnterpriseSso/index.tsx, packages/console/src/pages/Mfa/PageWrapper/index.tsx, packages/console/src/pages/Organizations/index.tsx
We no longer have a Hobby Plan at the moment, so we need to change the tags originally used for displaying hobbies to 'pro'.
The previous update overlooked changing the tags displayed in the card title.
=> refactor(console): update feature tag in card titles

packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx, packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
Per offline discussion, we won't navigate to the stripe checkout page directly when the paywall button is clicked, since the user may need to know the actrual price, but in our MVP pricing version, the prices is not settled, and the stripe page will not display the price. So navigate to the 'plan & billing page' as usual.
Test locally.
=> refactor(console): navigate to plan & billing page on paywall button clicked

packages/core/src/middleware/koa-security-headers.ts
Remove the COOP policy.
Based on the use case of the issue https://github.com/logto-io/logto/issues/5109,  it is a common use case for web apps using a popup window to handle their sign-in interaction flow.  
Per offline discussion remove the COOP policy for now, as it will block all the cross-origin pop-up window's opener communication. 
Test locally
=> fix(core): remove the COOP policy

packages/console/src/components/ChargeNotification/index.tsx, packages/console/src/components/CreateConnectorForm/Footer/index.tsx, packages/console/src/hooks/use-api-resources-usage.ts, packages/console/src/hooks/use-applications-usage.ts, packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx, packages/console/src/pages/ApiResources/index.tsx, packages/console/src/pages/Applications/index.tsx, packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx, packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx, packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx, packages/console/src/utils/quota.ts, packages/phrases/src/locales/de/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/es/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/fr/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/it/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/ja/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/ko/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/pt-br/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/ru/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/index.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts
This PR includes following updates:
- Do not display charge notifications if the quota usage does not go beyond the quota limit
- Update styles and phrases for the charge notification
- Fix: hide charge notifications for OSS version
- Feat: add a `hasSurpassedQuotaLimit` method
- Refactor the `hasReachedQuotaLimit` helper method, make the plan paramerter required, since the helper method should not care the plan is loaded or not
=> refactor(console,phrases): update charge notification for add-on features

packages/console/src/components/ChargeNotification/index.tsx, packages/console/src/pages/ApiResources/index.tsx, packages/console/src/pages/Applications/index.tsx
In the orginal implementation, we guard the `ChargeNotification` by the `hasSurpassedLimit` props, which will always `false` in the cloud version.
But this couples the `isCloud` and limit checking, which makes it hard to known if the `ChargeNotification` should be displayed or not.
So we need to guard the `ChargeNotification` directly by using `isCloud` and also avoid to add the `isDevFeaturesEnabled` guard inside the `ChargeNotification`, since they should be decoupled.
Test locally.
=> refactor(console): guard charge notification directly in the cloud version

packages/console/src/hooks/use-api.ts
a temp solution to prevent users with legacy refresh tokens being stuck in Console.
the user will be signed out automatically when organization token has insufficient permissions
=> refactor(console): sign out user when insufficient permissions

packages/console/src/ds-components/TextInput/index.module.scss
The background color of `TextInput` should be inherit from its parent.
Test locally.
=> style(console): inherit background-color for text input

packages/console/src/components/CreateTenantModal/EnvTagOptionContent/index.tsx, packages/console/src/components/TenantEnvTag/index.tsx, packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx, packages/console/src/components/Topbar/TenantSelector/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx, packages/phrases/src/locales/de/translation/admin-console/tenants.ts, packages/phrases/src/locales/en/translation/admin-console/tenants.ts, packages/phrases/src/locales/es/translation/admin-console/tenants.ts, packages/phrases/src/locales/fr/translation/admin-console/tenants.ts, packages/phrases/src/locales/it/translation/admin-console/tenants.ts, packages/phrases/src/locales/ja/translation/admin-console/tenants.ts, packages/phrases/src/locales/ko/translation/admin-console/tenants.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts, packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts, packages/phrases/src/locales/ru/translation/admin-console/tenants.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts, packages/schemas/src/types/tenant.ts
refactor: deprecate staging env tag
Note:
The tag type in the TenantInfo returned by the Cloud does not match the newly updated tag type, but they are compatible. So we add some ts comments to avoid type error in this PR.
However, we need to update the tenant type in the schema before we can update the type of the Cloud response.
So we will update the `@logto/cloud` package for the console when the cloud repo get updated.
- deprecate `staging` tag in the cloud repo & publish a new `@logto/cloud` package version (https://github.com/logto-io/cloud/pull/436)
- update the `@logto/cloud` package for the console, will be "deprecate staging env tag (2/2)"
Test locally.
=> refactor: deprecate staging env tag (1/2)

packages/console/package.json, packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx, packages/console/src/components/Topbar/TenantSelector/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/DeleteModal/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx, packages/core/package.json, pnpm-lock.yaml
Deprecate staging env tag (2/2)
see the previous PR: https://github.com/logto-io/logto/pull/5180
This PR upgrade the `@logto/cloud` to the latest version and remove redunant type infers and comments.
Test locally and all tests passed.
=> refactor: deprecate staging env tag (2/2)

packages/experience/src/Providers/SettingsProvider/use-preview.ts, packages/experience/src/i18n/init.ts
The original implementation have a bug that when the experience phrases are customized, the text content in the preview will not update.
Updates:
- Move out `i18next.use(initReactI18next)` from the i18n init functions and call it once globally, since we don't want to call it multiple times when call the `initI18n` more than 1 time.
- Support specifing an `initialLanguage` when calling `initI18n`, since in the preview, we need to reload the phrases with the given language from the console privew config
- Call `initI18n` function to reload custom phrases from the backend on custom phrases changed.
Test locally.
=> fix(experience): update text content in the preview on custom phrases updated

packages/console/src/consts/user-assets.ts, packages/console/src/hooks/use-image-mime-types.ts, packages/console/src/utils/uploader.ts, packages/schemas/src/types/user-assets.ts
Since the `.ico` file's mime type will may be treated as `image/x-icon` in some browser, so we need to add support for this mime type or this may cause a bug when uploading a `.icon` file:
Refer to: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#ico_microsoft_windows_icon
Test locally.
=> fix(console): allow image/x-icon mime type

packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx, packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx, packages/console/src/pages/SignInExperience/hooks/use-preview-configs.ts, packages/console/src/pages/SignInExperience/index.tsx, packages/console/src/pages/SignInExperience/types.ts, packages/console/src/pages/SignInExperience/utils/form.ts, packages/console/src/pages/SignInExperience/utils/parser.ts
Refactor sie form data parser:
- Extract all related data parser into a `parser.ts` file
- Split `signInExperienceParser` into `signUpFormDataParser` and `sieFormDataParser` and apply these parsers to the code base
- Add a `toUpdateSignInExperienceData` parser method  for the `sieFormDataParser` to convert the form data to the update request payload since we will not update the `mfa` data from the sign-in experience page
Test locally and all sign-in experience UI tests passed.
=> refactor(console): refactor sie form data parser

packages/schemas/src/types/logto-config.ts
Now we've deprecated the `staging` tag from `TenantTag`, but the tenant migration data, which is stored in the admin console data, saves the tenant's original tenant tag, when the tenant's original tenant is `staging`, it will cause an API type guard error, so we need to update the type guard for the `AdminConsoleData`.
Construct migration data with a `staging` tenant tag:
Tested in the admin console:
=> fix(core): fix dev tenant migration data guard

packages/console/src/consts/page-tabs.ts, packages/console/src/pages/ApplicationDetails/components/Branding/LogoUploader.tsx, packages/console/src/pages/ApplicationDetails/components/Branding/index.module.scss, packages/console/src/pages/ApplicationDetails/components/Branding/index.tsx, packages/console/src/pages/ApplicationDetails/components/Branding/use-application-sign-in-experience-swr.ts, packages/console/src/pages/ApplicationDetails/components/Branding/use-sign-in-experience-swr.ts, packages/console/src/pages/ApplicationDetails/components/Branding/utils.ts, packages/console/src/pages/ApplicationDetails/components/EndpointsAndCredentials.tsx, packages/console/src/pages/ApplicationDetails/components/Settings.tsx, packages/console/src/pages/ApplicationDetails/index.tsx, packages/console/src/pages/Applications/hooks/use-application-data.ts, packages/integration-tests/src/tests/console/applications/index.test.ts, packages/phrases/src/locales/de/translation/admin-console/application-details.ts, packages/phrases/src/locales/en/translation/admin-console/application-details.ts, packages/phrases/src/locales/es/translation/admin-console/application-details.ts, packages/phrases/src/locales/fr/translation/admin-console/application-details.ts, packages/phrases/src/locales/it/translation/admin-console/application-details.ts, packages/phrases/src/locales/ja/translation/admin-console/application-details.ts, packages/phrases/src/locales/ko/translation/admin-console/application-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts, packages/phrases/src/locales/ru/translation/admin-console/application-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Please ignore the large PR size, as most of them are phrases updates.
1. hide the application `description` and `logto_endpoint` fields for third-party applications, as they are useless.
2. Add a new `branding` tab to the application details page for third-party applications.
3. Add a new `branding` form to manage application-level sign-in-experiences.
image uploader enabled and dark mode enabled:
image uploader enabled and dark mode disabled:
image uploader disabled and dark mode enabled:
image uploader disabled and dark mode disabled:
test locally
=> feat(console): : add application branding tab

packages/experience/package.json, packages/experience/src/index.tsx, pnpm-lock.yaml
This PR is relative to https://github.com/logto-io/logto/issues/3878 ， https://github.com/logto-io/logto/issues/3059
Current Parcel config use 
- `Object: fromEntries` ( support by chrome >=73 )
- `Optional chaining operator` ( support by chrome >= 80 )
cover 69.72% of Chinese people.
Since described in [Parcel does not include polyfill for older browsers even when browserslist is declared in the package.json](https://github.com/parcel-bundler/parcel/issues/7419)
- Parcel only transpiles the code according to the browserslist but doesn't handle runtime polyfills.
- Parcel always pass `mode: entry` to swc, and SWC treats it similarly to `useBuiltIns: entry` in Babel.
This PR add `core-js` to the entry of the experience package, and SWC will include the required parts of it for the …
=> feat(experience): experience support old browser

.github/workflows/alteration-compatibility-integration-test.yml
Fix a bug found in the `check-alteration-changes` ci job. 
Issue found in PR: #5130 
Should diff the merge base changes only. Otherwise, if the base branch is behind the latest master, it may contain unexpected diff files.  e.g. alteration changes should not occur in this PR. 
ci
=> fix: update the alteration change detection script

packages/console/src/ds-components/Table/TableEmptyWrapper.module.scss, packages/console/src/ds-components/Table/TableEmptyWrapper.tsx
Per design requirement, the empty placeholder should have a top and bottom spacing, and the space height aspect ratio is 2:3.
Test locally.
=> style(console): update space size for table placeholder

packages/core/src/__mocks__/index.ts, packages/core/src/libraries/domain.test.ts, packages/core/src/libraries/protected-app.test.ts, packages/core/src/libraries/protected-app.ts, packages/core/src/routes/applications/application.test.ts, packages/core/src/routes/applications/application.ts, packages/core/src/tenants/Libraries.ts, packages/core/src/tenants/SystemContext.ts, packages/core/src/utils/cloudflare/index.ts, packages/core/src/utils/cloudflare/kv.ts, packages/core/src/utils/cloudflare/types.ts, packages/core/src/utils/cloudflare/utils.ts, packages/integration-tests/src/tests/api/application/application.test.ts, packages/phrases/src/locales/de/errors/application.ts, packages/phrases/src/locales/en/errors/application.ts, packages/phrases/src/locales/es/errors/application.ts, packages/phrases/src/locales/fr/errors/application.ts, packages/phrases/src/locales/it/errors/application.ts, packages/phrases/src/locales/ja/errors/application.ts, packages/phrases/src/locales/ko/errors/application.ts, packages/phrases/src/locales/pl-pl/errors/application.ts, packages/phrases/src/locales/pt-br/errors/application.ts, packages/phrases/src/locales/pt-pt/errors/application.ts, packages/phrases/src/locales/ru/errors/application.ts, packages/phrases/src/locales/tr-tr/errors/application.ts, packages/phrases/src/locales/zh-cn/errors/application.ts, packages/phrases/src/locales/zh-hk/errors/application.ts, packages/phrases/src/locales/zh-tw/errors/application.ts, packages/schemas/src/types/system.ts
Sync site configs to KV for new protected app:
1. new library ProtectedAppsLibrary.
2. new method for KV operations in Cloudflare utils.
3. new system configs for KV.
4. Sync configs to Cloudflare KV when creating new protected application.
Unit tests added.
No integration tests since we don't do test for outside services. There is no change in our side.
Local tested, when creating a new app, new KV record created:
=> feat(core): sync site configs to KV for new protected app

packages/connectors/connector-aliyun-dm/src/index.test.ts, packages/connectors/connector-aliyun-sms/src/index.test.ts, packages/connectors/connector-aws-ses/src/index.test.ts, packages/connectors/connector-sendgrid-email/src/mock.ts, packages/connectors/connector-smsaero/src/mock.ts, packages/connectors/connector-tencent-sms/src/index.test.ts, packages/connectors/connector-twilio-sms/src/mock.ts
Remove legacy `Test` passwordless template type use cases.
For now, we still keep the `Test` verification code type enum since the deprecation of this could bring breaking change.
N/A
=> chore(connector): remove legacy Test passwordless template type use case

.github/workflows/alteration-compatibility-integration-test.yml
Fix the DB alter detect ci script. 
We trigger the db alteration detection ci job on both `pull_request` and `push` events. For a `push` event, no merge base exists and the `github.base_ref` is also empty.  Should conditionally set the git diff based on the event type. 
ci
=> fix: fix the db alter detect ci script

packages/console/src/pages/UserDetails/UserSettings/index.tsx
Should not try to parse phone number if it's empty. Otherwise the util method will report an unexpected error in browser console.
Locally tested
=> fix(console): should not parse phone number if it is empty

packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx, packages/console/src/pages/TenantSettings/Subscription/index.tsx
upcoming billing info should be updated when the subscription changes.
As you can see in the screenshot, the upcoming billing info is calculated based on the response of cloud `GET /:tenantId/usage` endpoint and the `cost` varies with subscription.
Since the subscription changes, we need to revalidate the response of the `GET /:tenantId/usage` API to make sure the upcoming billing is up-to-date.
=> fix(console): upcoming billing info not updated when subscription changes

packages/core/src/database/utils.ts, packages/core/src/queries/organizations.ts, packages/core/src/routes/organization/index.ts, packages/core/src/routes/organization/invitations.openapi.json, packages/core/src/routes/organization/invitations.ts, packages/schemas/src/types/organization.ts, packages/schemas/tables/magic_links.sql
resolves LOG-7976.
- init organization invitation queries
- implement `GET /organization-invitations`
local tested the get api, organization roles and magic links can be correctly aggregated. integration tests will be added once mutation methods (e.g. `POST`) are implemented.
=> feat(schemas, core): init organization invitation apis

packages/core/src/routes/organization/invitations.openapi.json, packages/core/src/routes/organization/invitations.ts, packages/core/src/routes/swagger/index.ts
leverage `SchemaRouter` for routing. add `GET` and `DELETE` routes for organization invitations. resolve LOG-7981, LOG-7974
local tested. will add full integration tests once `POST` API is implemented
=> feat(core): get and delete org invitation by id

packages/core/src/libraries/application.ts, packages/core/src/queries/application-user-consent-organizations.ts, packages/core/src/queries/application.ts, packages/core/src/routes/applications/application-user-consent-organization.openapi.json, packages/core/src/routes/applications/application-user-consent-organization.ts, packages/core/src/routes/init.ts, packages/integration-tests/src/api/application-user-consent-organization.ts, packages/integration-tests/src/tests/api/application/application-sign-in-experience.test.ts, packages/integration-tests/src/tests/api/application/application-user-consent-organization.test.ts, packages/integration-tests/src/tests/api/application/application-user-consent-scope.test.ts
Implement application user consent organizations management API.
Users will be able to grant organizations access to the third-party consent page. Those grant statuses can be managed throw these APIs. 
- POST /applications/:id/users/:userId/consent-organizations
- PUT /applications/:id/users/:userId/consent-organizations
- GET /applications/:id/users/:userId/consent-organizations
- DELETE /applications/:id/users/:userId/consent-organizations/:organizationId
test locally using postman
=> feat(core): implement application user consent organizations api 

packages/console/src/consts/page-tabs.ts, packages/console/src/pages/ApplicationDetails/components/Branding/index.tsx, packages/console/src/pages/ApplicationDetails/index.tsx, packages/phrases/src/locales/de/translation/admin-console/application-details.ts, packages/phrases/src/locales/en/translation/admin-console/application-details.ts, packages/phrases/src/locales/es/translation/admin-console/application-details.ts, packages/phrases/src/locales/fr/translation/admin-console/application-details.ts, packages/phrases/src/locales/it/translation/admin-console/application-details.ts, packages/phrases/src/locales/ja/translation/admin-console/application-details.ts, packages/phrases/src/locales/ko/translation/admin-console/application-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts, packages/phrases/src/locales/ru/translation/admin-console/application-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Add the permissions tab to the application details page. 
Split the feature into 4 subsequent PRs. This the PR 4-1.
Test locally. Integration tests will be added later
=> feat(console,phrases): add permissions tab to the application details page 4-1

packages/console/src/components/TemplateTable/index.tsx, packages/console/src/ds-components/Table/index.tsx, packages/console/src/ds-components/Table/types.ts, packages/console/src/pages/ApplicationDetails/components/Permissions/index.module.scss, packages/console/src/pages/ApplicationDetails/components/Permissions/index.tsx, packages/console/src/pages/ApplicationDetails/components/Permissions/use-permissions-table.ts, packages/console/src/pages/ApplicationDetails/index.tsx, packages/phrases/src/locales/de/translation/admin-console/application-details.ts, packages/phrases/src/locales/en/translation/admin-console/application-details.ts, packages/phrases/src/locales/es/translation/admin-console/application-details.ts, packages/phrases/src/locales/fr/translation/admin-console/application-details.ts, packages/phrases/src/locales/it/translation/admin-console/application-details.ts, packages/phrases/src/locales/ja/translation/admin-console/application-details.ts, packages/phrases/src/locales/ko/translation/admin-console/application-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts, packages/phrases/src/locales/ru/translation/admin-console/application-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Implement the third-party app permissions table using the `TemplateTable` component.
Permissions tab page implementation PR 4-3
TODO: 
- resource scopes edit modal
- organization scopes edit modal
- permissions new assignment modal
test locally
=> feat(console,phrases): add permissions tab to the application details page 4-3

packages/core/src/routes/organization/index.ts, packages/core/src/routes/organization/roles.ts, packages/core/src/routes/organization/scopes.ts, packages/core/src/utils/SchemaRouter.ts
Add pre-middlewares to SchemRouter configs, in order to apply quota guard before generating actual routes. This fix can guarantee the quota guard is executed before going into API routes.
Tested locally, quota guard protected API returns 403 and the post data was not persisted in DB
=> fix(core): fix quota guard for schema routers

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx, packages/console/src/pages/ApplicationDetails/index.module.scss, packages/console/src/pages/ApplicationDetails/index.tsx, packages/console/src/pages/ApplicationDetails/utils.ts
In the original implementation, we set default value for the application form:
```jsx
const formMethods = useForm<ApplicationForm>({
defaultValues: { customClientMetadata: customClientMetadataDefault, isAdmin: false },
});
```
but the `customClientMetadata` from application data will be `{}` by default.
This will overwrite the default values specified in the `useForm` hook, and will causes `reset` function works not as expected.
So in this PR, we wrap the page content with a `ApplicationDetailsContent` component, and render the react hook form after the application data is fetch. In this case, we can specify correct default values for the react hook form, and the `reset` function works fine.
- Add a `ApplicationDetailsContent` component to wrap the original details page content
- Extract …
=> fix(console): fix application refresh token settings

packages/core/src/middleware/koa-auto-consent.ts, packages/core/src/oidc/adapter.ts, packages/core/src/oidc/grants/index.ts, packages/core/src/oidc/grants/refresh-token.test.ts, packages/core/src/oidc/grants/refresh-token.ts, packages/core/src/oidc/init.ts, packages/core/src/oidc/resource.ts
This PR implements the application-level user consent scopes and organization restriction logic for third-party applications. 
The restriction was added in the following flows:
[OIDC provider](https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#clients) supports specifying the `scope` claim in the `client_metadata`.  If provided, the authorization request will throw [`InvalidScope`](https://github.com/panva/node-oidc-provider/blob/main/lib/actions/authorization/check_scope.js#L49) error if any of the requested scope is not listed in the `metadata.scope` field. This includes `OIDC reserved scopes`,  and `user claims scopes`. 
Resource scopes (including Logto organization scopes) are [not included](https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#scopes) …
=> feat(core): add third-party application scopes and organizations restriction

packages/core/src/libraries/session.ts, packages/core/src/routes/interaction/consent.ts, packages/schemas/src/types/consent.ts, packages/schemas/src/types/index.ts
Implement the  get consent info API to fetch user consent detail info including
- user identity info
- application info
- user organization info if requested
- missing scopes
test locally
=> feat(core): add get consent info api

packages/core/src/__mocks__/index.ts, packages/core/src/__mocks__/protected-app.ts, packages/core/src/libraries/protected-app.test.ts, packages/core/src/libraries/protected-app.ts, packages/core/src/routes/applications/application.test.ts, packages/core/src/routes/init.ts, packages/core/src/routes/system.openapi.json, packages/core/src/routes/system.test.ts, packages/core/src/routes/system.ts
Add api `GET /systems/application` to get protected app default domain (e.g. protected.app)
Unit tests.
=> feat(core): api to get protected app default domain

packages/core/src/__mocks__/index.ts, packages/core/src/libraries/application.ts, packages/core/src/libraries/protected-app.test.ts, packages/core/src/libraries/protected-app.ts, packages/core/src/routes/applications/application-protected-app-metadata.openapi.json, packages/core/src/routes/applications/application-protected-app-metadata.test.ts, packages/core/src/routes/applications/application-protected-app-metadata.ts, packages/core/src/routes/applications/application.test.ts, packages/core/src/routes/init.ts
New route `POST /applications/:applicationId/protected-app-metadata/custom-domains` to add custom domain for protected apps.
This route only adds domain records, the status sync will be in the next PR.
Unit tests and local tested.
=> feat(core): add custom domain for protected app

packages/console/src/components/RoleScopesTransfer/index.tsx, packages/console/src/ds-components/ConfirmModal/index.tsx, packages/console/src/ds-components/DataTransferBox/SourceDataItem/index.module.scss, packages/console/src/ds-components/DataTransferBox/SourceDataItem/index.tsx, packages/console/src/ds-components/DataTransferBox/SourceGroupItem/index.module.scss, packages/console/src/ds-components/DataTransferBox/SourceGroupItem/index.tsx, packages/console/src/ds-components/DataTransferBox/SourcePanel/index.module.scss, packages/console/src/ds-components/DataTransferBox/SourcePanel/index.tsx, packages/console/src/ds-components/DataTransferBox/TargetDataItem/index.module.scss, packages/console/src/ds-components/DataTransferBox/TargetDataItem/index.tsx, packages/console/src/ds-components/DataTransferBox/TargetPanel/index.module.scss, packages/console/src/ds-components/DataTransferBox/TargetPanel/index.tsx, packages/console/src/ds-components/DataTransferBox/index.module.scss, packages/console/src/ds-components/DataTransferBox/index.tsx, packages/console/src/ds-components/DataTransferBox/type.ts
Implement new DataTransferBox ds-component.
This new component set is forked and refactored directly from the `RoleScopesTransfer` component. Currently, Logto has multiple places that use a Data-Transfer-Box user experience:
- `RoleScopesTransfer`
- `RolesTransfer`
- `EntitiesTransfer`
All coupled with the data layer. Some support list data display, and some support tree data display. 
Extract a new pure DS component instead that can support both list data and tree data at the same time. 
Test locally please check the next PR for the usages.
=> feat(console): implement DataTransferBox ds-component

packages/core/src/middleware/koa-auto-consent.ts, packages/core/src/routes/interaction/consent.ts, packages/schemas/src/types/consent.ts
Update the consent APIs. This PR includes the following updates:
1. Refactor the `koaAutoConsent`, and make it more clear.  If it is a third-party app, continue to experience the consent page. Otherwise, directly grant all the missing scopes and consent. 
2. Update the `GET /consent` API's `missingResourceScopes` data parsing logic. As logto reserved organization resource does not exist in our API resource DB. We need to treat it differently.  Fetch the scopes from organization scopes instead of resource scopes. Use the reserved resource name as the resource id. 
3. Update the old consent API. Besides consenting all the missing scope on request. If there are any user-granted organizations provided. Grant the organization access to that application ahead. 
test locally
=> refactor(core): update the consent apis

packages/core/src/__mocks__/domain.ts, packages/schemas/src/foundations/jsonb-types/custom-domain.ts
Remove `catchall` from `cloudflareDataGuard` to simplify the type.
This change will lost the other fields of cloudflare response, but these are not useful, and can be fetched from Cloudflare in any time, so it is OK to remove.
Local tested with existing data, the parsing is OK:
=> fix(schemas): remove catchall from cloudflare data guard

packages/console/src/pages/Applications/hooks/use-application-data.ts, packages/core/src/queries/application.ts, packages/core/src/routes/applications/application.ts, packages/integration-tests/src/api/application.ts, packages/integration-tests/src/tests/api/application/application.test.ts
Fix the application count bug.
Bug description:
With the thrid-party application implemented. previously we added a new query parameter `isThirdParty` to the `GET /applications` API. 
To make it compatible with the existing online behavior, the logic was if the `isThirdParty` query parameter is absent, return all the first-party apps. Otherwise, return third-party applications.  However, we use the same API to get the total count of the applications in the console. Including first-party and third-party apps.  
Fix:
To make the API precise, update the query logic, if the `isThirdParty` query parameter is not provided return all the applications without filtering.  
Filter the first-party or third-party applications exclusively based on the `isThirdParty`'s exact value. 'true' | 'false'. …
=> fix(console,core): fix application count bug

packages/core/src/routes/user-assets.ts
When upload file to remote (for example, S3) and error occurs, the status code should be 500.
Any 4xx error should be raised before calling the final upload function.
Local tested.
=> fix(core): should throw 500 on file upload error

packages/core/src/__mocks__/index.ts, packages/core/src/libraries/protected-app.ts, packages/core/src/routes/applications/application-protected-app-metadata.test.ts, packages/core/src/routes/applications/application.test.ts, packages/core/src/routes/applications/application.ts, packages/phrases/src/locales/de/errors/application.ts, packages/phrases/src/locales/en/errors/application.ts, packages/phrases/src/locales/es/errors/application.ts, packages/phrases/src/locales/fr/errors/application.ts, packages/phrases/src/locales/it/errors/application.ts, packages/phrases/src/locales/ja/errors/application.ts, packages/phrases/src/locales/ko/errors/application.ts, packages/phrases/src/locales/pl-pl/errors/application.ts, packages/phrases/src/locales/pt-br/errors/application.ts, packages/phrases/src/locales/pt-pt/errors/application.ts, packages/phrases/src/locales/ru/errors/application.ts, packages/phrases/src/locales/tr-tr/errors/application.ts, packages/phrases/src/locales/zh-cn/errors/application.ts, packages/phrases/src/locales/zh-hk/errors/application.ts, packages/phrases/src/locales/zh-tw/errors/application.ts, packages/schemas/src/foundations/jsonb-types/applications.ts
…ists
In `DELETE /applications/:applicationId`, check if custom domains are deleted.
Users should delete custom domains before they can delete an application.
Unit tests.
=> fix(core,phrases): prevent application deletion for custom domain

packages/console/src/ds-components/Textarea/index.module.scss
There is a large gap between the scrollbar and the right border of the `TextArea` component, by update the textarea's box-sizing to `content-box` and add a `padding-right` for the scrollbar, the scrollbar now will be in a good place.
Before:
After:
=> style(console): adjust textarea scrollbar position

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/index.tsx
hide the selected scopes count on the tab if it is 0
Before:
After:
test locally
=> refactor(console): hide the empty count on tab

packages/experience/src/pages/Consent/ScopesListCard/index.tsx
Add empty scopes fallback layout. This is a fallback layout of the consent page for corner cases like:
- no user scopes and resource scopes are requested e.g. only 'openid' and 'offline_access';
- all the requested scopes are granted previously. 
test locally
=> fix(experience): add empty scopes fallback layout

packages/experience/src/pages/Consent/ScopesListCard/index.tsx
Auto expands the scopes list if there are only user scopes or only one group of resource scopes is being requested.
| user scopes | resource scopes |
| ------------ | ---------------- |
| ![WX20240124-135247@2x](https://github.com/logto-io/logto/assets/36393111/ecda3e03-8428-4cf3-98c2-77b23ca60484) | ![WX20240124-135350@2x](https://github.com/logto-io/logto/assets/36393111/7fcf4c53-095b-44c3-a0bd-7fdb79c51130) |
test locally
=> feat(experience): auto expand the scopes list

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
Hide the guide button on the application detail page's header if the current application is a third-party app. 
test locally
=> fix(console): hide the guide button for third-party app

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.module.scss, packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-scopes-table.ts
Should hide the organization row group if the data is empty
Adjust the spacing of the row group header
Before:
After:
test locally
=> fix(console): hide the organization row group

packages/console/src/ds-components/Button/index.module.scss, packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.module.scss, packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-scopes-table.tsx, packages/phrases/src/locales/de/translation/admin-console/application-details.ts, packages/phrases/src/locales/en/translation/admin-console/application-details.ts, packages/phrases/src/locales/es/translation/admin-console/application-details.ts, packages/phrases/src/locales/fr/translation/admin-console/application-details.ts, packages/phrases/src/locales/it/translation/admin-console/application-details.ts, packages/phrases/src/locales/ja/translation/admin-console/application-details.ts, packages/phrases/src/locales/ko/translation/admin-console/application-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts, packages/phrases/src/locales/ru/translation/admin-console/application-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts
Add the user permission tooltips.
- Fix the button trailing icon style
- Add a tooltip button on the user data permission's table header
test locally
=> feat(console): add the user permission tooltips

packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
Remove "Pro" tag from app category filter list, since the tag was initially trying to attach to M2M app, but later the M2M is not a "Pro" feature any more. Also, the implementation was quite confusing and we were trying to refactor it in the first place. Anyways... Now, it's gone.
Locally tested using Cloud dev env. It's gone
=> refactor(console): remove pro tag from app category filter

packages/schemas/alterations/next-1705991158-update-invitation-indices.ts, packages/schemas/tables/organization_invitations.sql
for admins, it makes no sense to require an inviter when creating invitation. so we remove the restriction.
next pull (with api tests)
=> refactor(schemas): allow null inviter

packages/console/src/components/EmptyDataPlaceholder/index.module.scss, packages/console/src/components/EmptyDataPlaceholder/index.tsx, packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss, packages/console/src/pages/Applications/components/GuideLibrary/index.tsx, packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx, packages/console/src/pages/Applications/components/ProtectedAppCard/index.module.scss, packages/console/src/pages/Applications/components/ProtectedAppCard/index.tsx, packages/console/src/pages/Applications/index.module.scss, packages/console/src/pages/Applications/index.tsx, packages/console/src/scss/page-layout.module.scss, packages/console/src/types/applications.ts
Improve applications page empty state layout:
1. Protected app card should have border when it's in the empty state component
2. The empty state component should not be framed and scrolled inside the frame, but stretched out and scroll with the entire page
3. Hide protected app creation card from application gallery, if the filtered category doesn't contain protected app.
4. Add the missing "View all ->" button on the bottom
=> refactor(console): improve app creation page empty state layout

packages/toolkit/core-kit/src/regex.test.ts, packages/toolkit/core-kit/src/regex.ts
Currently the domain regex does not allow short subdomain and top-level domain that contain only 1 character. For example, the following domains are considered invalid at this point:
- f.bar.com
- foo.b.com
- f.b.com
But they are actually valid in real life. E.g. `x.com`
Locally tested and it works
=> fix(toolkit): domain regex should allow short subdomain and top-level domain

packages/experience/src/pages/Consent/OrganizationSelector/OrganizationSelectorModal/index.tsx
Fix the organization selector position.
This PR includes the following fix:
Based on the current page layout, all the page-level overflow scroll event is triggered on a `view-box`  div element instead of the window.  So the original `window.onScroll` event won't be triggered. This organization selector modal pos can not be recalculated properly. 
To fix this: 
1. Remove the window on scroll event listener, as it is useless
2. Add the 'isOpen' property as the `useEffect` dependency, so the dropdown pos may be recalculated whenever the modal is opened. 
3. Calculate the modal height and provide a min Top threshold to make sure the drop-down menu won't go off the screen
test locally
=> fix(experience): fix the organization selector position

packages/experience/src/pages/Consent/ScopesListCard/index.module.scss
fix the terms section padding.
The card wrapper contains an 8px wrapping. 
The terms section should shrink the padding-bottom space by 8px in order to make the content centralized. 
test locally
=> style(experience): fix the terms padding

packages/console/src/pages/Applications/components/GuideLibrary/index.tsx, packages/integration-tests/src/tests/console/applications/helpers.ts, packages/integration-tests/src/tests/console/applications/index.test.ts
Hide m2m and third-party apps in the empty app list guide page. Click on View More and show all the application categories on the create modal page. 
test locally
=> feat(console): hide m2m and third-party app in the empty app list guide

packages/core/src/libraries/protected-app.test.ts, packages/core/src/libraries/protected-app.ts, packages/core/src/middleware/koa-slonik-error-handler.test.ts, packages/core/src/middleware/koa-slonik-error-handler.ts, packages/core/src/queries/application.test.ts, packages/core/src/queries/application.ts, packages/core/src/routes/applications/application.test.ts, packages/core/src/routes/applications/application.ts, packages/schemas/alterations/next-1706510290-protected-app-host-index.ts, packages/schemas/tables/applications.sql
Create an unique index for protected app's free subdomain, to ensure that domains will not conflict.
The previous solution won't work because of RLS.
Local tested and unit tests.
=> fix(core,schemas): use database index to prevent subdomain conflict

packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx, packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/hooks/use-user-preferences.ts, packages/schemas/alterations/next-1706512952-restore-get-started-page.ts
Remove `getStartedHidden` property from user preferences, to forcefully bring back the get-started page that might be set to hidden by users.
Locally tested and the previously hidden get-started page was restored.
=> refactor(console,schemas): bring back hidden get-started page

packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
Improve error handling logic on creating protected apps.
- `'application.protected_application_subdomain_exists'` should be catched and inline-displayed underneath the form field
- Others non-401 errors should be "toasted" up
- 401 errors and other unknown errors should still be thrown up to the upper level error handlers. e.g. ErrorBoundary
Locally tested
=> fix(console): fix error handling on creating protected apps

packages/core/src/libraries/organization-invitation.ts, packages/integration-tests/src/__mocks__/connectors-mock.ts, packages/integration-tests/src/api/organization-invitation.ts, packages/integration-tests/src/helpers/index.ts, packages/integration-tests/src/tests/api/organization/organization-invitation.creation.test.ts
since we removed magic links, update the api to be more specific about connector message payload for organization invitation creation.
updated and added api tests accordingly
=> refactor: update organization invitation api connector payload

packages/core/src/middleware/koa-slonik-error-handler.test.ts, packages/core/src/middleware/koa-slonik-error-handler.ts, packages/core/src/queries/application.test.ts, packages/core/src/queries/application.ts, packages/core/src/routes/applications/application-protected-app-metadata.test.ts, packages/core/src/routes/applications/application-protected-app-metadata.ts, packages/schemas/alterations/next-1706585206-protected-app-custom-domain-unique.ts, packages/schemas/tables/applications.sql
Similar to https://github.com/logto-io/logto/pull/5326, use database unique index to prevent custom domain conflict. 
Notice that Postgres can not create index on the whole array, so we pick the first element. Left a comment, in the future, we can create a custom function to handle this.
Unit tests and local tested.
=> fix(core,schemas): use database index to prevent custom domain conflict

packages/console/src/pages/Applications/components/ProtectedAppForm/index.module.scss, packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
Protected app form field should have `layer-1` background
=> fix(console): protected app form field should have layer-1 background

packages/core/src/libraries/protected-app.ts, packages/core/src/middleware/koa-guard.test.ts, packages/core/src/middleware/koa-guard.ts, packages/core/src/routes/applications/application-protected-app-metadata.test.ts, packages/core/src/routes/applications/application-protected-app-metadata.ts, packages/core/src/routes/applications/application-sign-in-experience.ts, packages/core/src/routes/applications/application.test.ts, packages/core/src/routes/applications/application.ts, packages/core/src/routes/authn.ts, packages/core/src/routes/connector/index.ts, packages/core/src/routes/interaction/additional.ts, packages/core/src/routes/interaction/index.ts, packages/core/src/routes/organization/invitations.openapi.json, packages/core/src/routes/organization/invitations.ts, packages/core/src/routes/resource.ts, packages/core/src/routes/sso-connector/index.ts, packages/core/src/routes/system.ts, packages/core/src/routes/verification-code.ts, packages/core/src/utils/assert-that.ts, packages/integration-tests/src/tests/api/application/application-sign-in-experience.test.ts, packages/integration-tests/src/tests/api/resource.scope.test.ts, packages/integration-tests/src/tests/api/sso-connectors.test.ts
previously `koaGuard` doesn't check request errors thrown by the inner middleware functions, this pull adds the check for the request error status code to ensure the guard config covers them. updated code accordingly.
resolves the conversation https://github.com/logto-io/logto/pull/5330#discussion_r1470507681
ci, updated tests accordingly
=> refactor(core): guard status from request errors

packages/app-insights/package.json, packages/cli/package.json, packages/connectors/templates/package.json, packages/console/package.json, packages/core/package.json, packages/core/src/utils/SchemaRouter.ts, packages/experience/package.json, packages/integration-tests/package.json, packages/phrases-experience/package.json, packages/phrases/package.json, packages/schemas/package.json, packages/shared/package.json, packages/toolkit/connector-kit/package.json, packages/toolkit/core-kit/package.json, pnpm-lock.yaml
use deepmerge for config. leveraging `isPlainObject()` thus we can keep the zod guard in config unchanged
ci (fail without `isPlainObject()`)
=> refactor(core): use deepmerge

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
Add defaut value for custom page rules in protected app details page on the client side, as the default values are removed from server side.
It's back.
=> fix(console): add default value for custom auth rules in protected app details

packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.module.scss
Fix domain items vertical spacing in get-started page.
=> fix(console): fix domain items vertical spacing in get-started page

packages/console/src/pages/EnterpriseSso/index.tsx
SSO connector upsell should show on the creation modal footer (not on the create button)
=> fix(console): upsell should locate on modal footer

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
Fix the bug that the delete button does not turn to loading & disabled state when deleting applications, potentially causing making subsequent deleting requests to the server.
Works as expected on my local machine. You can only make one delete request now on deleting apps
=> fix(console): block subsequent requests on deleting apps

packages/console/src/assets/docs/guides/api-python/README.mdx, packages/console/src/assets/docs/guides/web-python/README.mdx
refactor(console): update import paths and type annotations in Python app guide
- Update import paths for components in `api-python` and `web-python` README files
- Remove unnecessary imports and update type annotations in `web-python` README file
- Ensure consistency and accuracy in component import paths and type annotations across relevant documentation files. Since our tutorial is based on Python 3.8 and 3.8 does not support the union type operation with `|` (should use `Union` util method).
Tested locally, content updated.
=> refactor(console): update import paths and type annotations in Python app guide

packages/console/src/consts/external-links.ts, packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx, packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.tsx, packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
Add third-party docs links to the AC page.
- Add the `Logto as IdP` doc link to the third-party detail page guide button.
- Add the `permissions-management` doc link as the Permission tab learn more button.
- Add the `branding-customization` doc link as the Branding tab learn more button.
test locally
=> feat(console): add third-party doc links

packages/console/src/ds-components/TextInput/index.tsx, packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
Protected app creation form field should not render background color on error messages.
=> fix(console): protected app form field background should exclude error message

packages/core/src/routes/applications/application-protected-app-metadata.openapi.json, packages/core/src/routes/applications/application.openapi.json, packages/core/src/routes/init.ts, packages/phrases/src/locales/de/errors/application.ts, packages/phrases/src/locales/en/errors/application.ts, packages/phrases/src/locales/es/errors/application.ts, packages/phrases/src/locales/fr/errors/application.ts, packages/phrases/src/locales/it/errors/application.ts, packages/phrases/src/locales/ja/errors/application.ts, packages/phrases/src/locales/ko/errors/application.ts, packages/phrases/src/locales/pl-pl/errors/application.ts, packages/phrases/src/locales/pt-br/errors/application.ts, packages/phrases/src/locales/pt-pt/errors/application.ts, packages/phrases/src/locales/ru/errors/application.ts, packages/phrases/src/locales/tr-tr/errors/application.ts, packages/phrases/src/locales/zh-cn/errors/application.ts, packages/phrases/src/locales/zh-hk/errors/application.ts, packages/phrases/src/locales/zh-tw/errors/application.ts
Protected App is not available in open source version, add this notice in openapi docs and error messages.
N/A
=> fix(core,phrases): add notice that protected app is cloud only

packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
Protected app creation form field should have correct error background color. Previously the issue was partially fixed.
=> fix(console): protected app creation form field should have correct error background

packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.tsx
Improve protected app form loading state in get started page. Previously when you have created 3 or more apps in Free plan, you will notice the protected form show up in protected app after the initial loading, then the form disappears, as it has reached the quota limit of total app count.
This fix improve the process and you will not be able to see the form, even not in a blink of eye.
Locally tested with slow 3G network throttling. Works fine.
=> fix(console): improve protected app loading state in get started page

.github/workflows/release.yml
the `publish-and-tag` job should run for every push, only `dockerize` should be constraint.
after merge
=> ci: fix release workflow trigger

packages/core/src/middleware/koa-tenant-guard.test.ts, packages/core/src/middleware/koa-tenant-guard.ts, packages/core/src/queries/tenant.ts, packages/core/src/routes/init.ts, packages/core/src/tenants/Queries.ts, packages/schemas/alterations/next-1707360939-grant-is-suspended-read-permission.ts, packages/schemas/tables/_after_all.sql
Remove the cloudConnection dependency in the koaTenantGuard.
- update the read permission of the tenants table to include `is_suspended`
- instead of call the cloudConnection to read tenant status, directly read the DB. 
test locally.
=> refactor(core,schemas): remove cloudConnection call in koaTenantGuard

packages/console/src/ds-components/TextInput/index.module.scss, packages/console/src/ds-components/TextInput/index.tsx, packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/components/SessionForm.module.scss, packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/components/SessionForm.tsx, packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.module.scss, packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx, packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx, packages/phrases/src/locales/de/translation/admin-console/protected-app.ts, packages/phrases/src/locales/en/translation/admin-console/protected-app.ts, packages/phrases/src/locales/es/translation/admin-console/protected-app.ts, packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts, packages/phrases/src/locales/it/translation/admin-console/protected-app.ts, packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts, packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts, packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts, packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts, packages/toolkit/core-kit/src/utils/url.test.ts, packages/toolkit/core-kit/src/utils/url.ts
In protected app form, if the origin url is localhost, the validation will fail with a link to the docs site.
The "message" in react-hook-form can only be string, so I have to render the error message manually, to add the link.
Refactored "SessionForm" because the file is too long.
=> feat(console): add localhost notice

packages/console/src/components/ListPage/index.tsx, packages/console/src/pages/ApiResources/index.tsx, packages/console/src/pages/Connectors/SignInExperienceSetupNotice/index.module.scss, packages/console/src/pages/Connectors/SignInExperienceSetupNotice/index.tsx, packages/console/src/scss/page-layout.module.scss
style(console): fix unexpected spacing under page title
In #5125 , we add a common style for the `subHeader` section of the `ListPage` component, this will case the page to have an unexpected spacing under the page title.
In this PR, we revert related code changes and custom the `subHeader` style manually.
Everything works fine:
=> style(console): fix unexpected spacing under page title

packages/console/src/components/DetailsPage/DetailsPageHeader/index.tsx, packages/console/src/pages/ApiResourceDetails/index.tsx, packages/core/src/routes/init.ts, packages/core/src/routes/resource.scope.test.ts, packages/core/src/routes/resource.scope.ts, packages/core/src/routes/resource.test.ts, packages/core/src/routes/resource.ts, packages/integration-tests/src/tests/api/resource.test.ts, packages/phrases/src/locales/de/errors/resource.ts, packages/phrases/src/locales/en/errors/resource.ts, packages/phrases/src/locales/es/errors/resource.ts, packages/phrases/src/locales/fr/errors/resource.ts, packages/phrases/src/locales/it/errors/resource.ts, packages/phrases/src/locales/ja/errors/resource.ts, packages/phrases/src/locales/ko/errors/resource.ts, packages/phrases/src/locales/pl-pl/errors/resource.ts, packages/phrases/src/locales/pt-br/errors/resource.ts, packages/phrases/src/locales/pt-pt/errors/resource.ts, packages/phrases/src/locales/ru/errors/resource.ts, packages/phrases/src/locales/tr-tr/errors/resource.ts, packages/phrases/src/locales/zh-cn/errors/resource.ts, packages/phrases/src/locales/zh-hk/errors/resource.ts, packages/phrases/src/locales/zh-tw/errors/resource.ts
block deletion on management API:
1. [core] Fix DELETE /resource/:id API, throws when the target is a management API.
2. [core] Separate `resource.ts` API file into two API files `resource.ts` and `resource.scope.ts` due to the file size limit.
3. [console] Refactor <DetailsPageHeader /> component, hide "..." button when there are no menu items.
4. [console] Update API resource details page, hide the delete button when the API resource is management API.
5. [phrases] Add error message `resource.cannot_delete_management_api`.
Covered by unit test and integration test.
=> fix(core,console): block deletion on management API

packages/console/src/assets/docs/guides/api-express/README.mdx
Refactor the error handling in the Express tutorial to use the 'new Error()' constructor instead of 'throw an Error()'.
Test locally
=> refactor(console): refactor error handling in Express tutorial

packages/console/src/ds-components/DangerousRaw/index.tsx
Remove the unexpected 4px margin introduced by the ghost subtitle from the guide step, in order to center align the card title when the subtitle is not available.
=> fix(console): center align card title when subtitle is not available

packages/core/src/libraries/role-scope.ts, packages/core/src/routes/role.scope.test.ts, packages/core/src/routes/role.scope.ts, packages/core/src/routes/role.test.ts, packages/core/src/routes/role.ts, packages/core/src/tenants/Libraries.ts, packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts, packages/integration-tests/src/tests/api/role.scope.test.ts, packages/integration-tests/src/tests/api/role.test.ts, packages/phrases/src/locales/de/errors/role.ts, packages/phrases/src/locales/en/errors/role.ts, packages/phrases/src/locales/es/errors/role.ts, packages/phrases/src/locales/fr/errors/role.ts, packages/phrases/src/locales/it/errors/role.ts, packages/phrases/src/locales/ja/errors/role.ts, packages/phrases/src/locales/ko/errors/role.ts, packages/phrases/src/locales/pl-pl/errors/role.ts, packages/phrases/src/locales/pt-br/errors/role.ts, packages/phrases/src/locales/pt-pt/errors/role.ts, packages/phrases/src/locales/ru/errors/role.ts, packages/phrases/src/locales/tr-tr/errors/role.ts, packages/phrases/src/locales/zh-cn/errors/role.ts, packages/phrases/src/locales/zh-hk/errors/role.ts, packages/phrases/src/locales/zh-tw/errors/role.ts, packages/schemas/alterations/next-1708916601-remove-management-api-scopes-assigned-to-user-role.ts
Fix: management API scopes are not assignable to user roles
1. [core] refactor:  add `roleScope` library method to validate whether a bunch of scopes is eligible to be assigned to a role. Updated unit tests and integration tests as well.
2. [tests] fix: since management API scopes are not assignable to user role, replace the API resource used in `get-access-token` integration tests.
3. [schemas] chore: add alteration scripts to remove management API scopes that have already been assigned to user roles via API (bypassed console constraints).
We have already hidden the assignment of management API scopes to user roles in the Admin Console. Hence we only need to update corresponding APIs.
Covered by unit tests and integration tests.
=> fix(core): mgmt API scopes are not assignable to user roles

.changeset/wet-squids-move.md, packages/connectors/connector-smtp/src/constant.ts
Always show SMTP connector TLS configurations in the admin console.
This PR fixes [discord bug reports](https://discord.com/channels/965845662535147551/1210615787820163143).
=> fix(connector): always show SMTP connector TLS configurations in the admin console

packages/integration-tests/src/tests/console/sign-in-experience/helpers.ts, packages/integration-tests/src/tests/console/sign-in-experience/sign-in-preview.test.ts, packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts, packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/helpers.ts, packages/integration-tests/src/ui-helpers/index.ts, packages/integration-tests/src/ui-helpers/select-dropdown-menu-item.ts
Remove the dropdown modal waitForTimeout statement. Use a `selectDropdownMenuItem` util method instead.
integration tests
=> refactor(test): remove dropdown modal waitForTimeout

packages/schemas/package.json, packages/schemas/src/types/organization.ts, pnpm-lock.yaml
- upgrade `@withtyped/server` to `^0.13.1` in `@logto/schemas` (this is intentional, will upgrade other packages later)
- update `@logto/schemas` guard types to make organization type guard reusable
cloud can use it
=> refactor(schemas): update schema to fit cloud

packages/schemas/alterations/next-1709528944-regenerate-dau-data.ts
Regenerate `daily_active_users` table data from the `logs` table data.
🚨 This PR is a data migration and should be merged after the #5451 is launched for our cloud version, otherwise old format data will still insert into the `daily_active_users` when staging.
Currently, we retrieve DAU date from `logs` table.
Since the data in the `logs` table will be cleared, so we should not rely on it anymore, now we plan to read DAU date from the `daily_active_users` table.
But there is one problem in the `daily_active_users` table:
the original `daily_active_users` table record the active user data based on UTC date, and only record the “date” time:
```tsx
export const recordActiveUsers = async (accessToken: { accountId?: string }, queries: Queries) => {
const { accountId } = accessToken;
const { …
```
=> refactor(schemas): regenerate dau table data from logs

packages/core/src/queries/log.ts
deprecate unused `countActiveUsersByTimeInterval` and `getDailyActiveUserCountsByTimeInterval` methods from `LogQueries`.
N/A
=> chore(core): deprecate unused query methods for logs table

packages/console/package.json, packages/console/src/pages/JwtClaims/MonacoCodeEditor/config.ts, packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.module.scss, packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx, packages/console/src/pages/JwtClaims/MonacoCodeEditor/type.ts, packages/console/src/pages/JwtClaims/config.ts, packages/console/src/pages/JwtClaims/index.module.scss, packages/console/src/pages/JwtClaims/index.tsx, packages/console/src/pages/JwtClaims/type.ts, packages/console/src/scss/_code-editor.scss, packages/console/src/scss/normalized.scss, packages/core/src/middleware/koa-security-headers.ts, packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts, pnpm-lock.yaml
integrate Monaco editor. This PR includes the following updates:
1. add the [monaco-react](https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#loader-config) dependency. This library provides a comprehensive code editor solution including auto-suggestions and basic code data scheme validation.  Powered by the VS code team. 
2. Update the console's CSP header settings to allow external script `https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/`. By default monaco-react loads the full Monaco instance from CDN. Issue created to consider removing the external dependency using the local Monaco instance. 
3. Implement the static MonacoCodeEditor component with type auto-suggestions and basic typescript syntax validation. 
test locally
=> feat(console,phrases): integrate monaco editor

packages/schemas/src/types/index.ts, packages/schemas/src/types/logto-config/index.ts, packages/schemas/src/types/logto-config/oidc-provider.ts
We will support two custom JWT scenarios, `AccessToken` (for end-user) and `ClientCredentials` (for machine connection), Logto users can customize the logic to manipulate the raw token payload, and the result of the parsed token payload will be further processed by Logto OIDC service and then issued to the client.
For each scenario, Logto user can customize the token payload manipulation by providing a code snippet, env variables, and sample token/context (for testing purposes). This is a group of data that will be stored in `logto_config` table as a single DB record.
This PR is the preparation for upcoming custom JWT-related APIs, with the following update/refactor:
1. Enable new `key` column value `LogtoJwtTokenKey` for `logto_config` table.
2. For each `LogtoJwtTokenKey`, we provide …
=> feat(schemas): update `logto_configs` table related types

packages/core/src/libraries/cloud-connection.test.ts, packages/core/src/libraries/logto-config.ts, packages/core/src/libraries/sign-in-experience/index.test.ts, packages/core/src/queries/logto-config.ts, packages/core/src/routes/logto-config.openapi.json, packages/core/src/routes/logto-config.test.ts, packages/core/src/routes/logto-config.ts, packages/integration-tests/src/api/logto-config.ts, packages/integration-tests/src/tests/api/logto-config.test.ts
Add `GET /configs/jwt-customizer/:tokenType` API
Covered by unit test and integration tests.
=> feat(core): add GET /configs/jwt-customizer API

packages/core/src/queries/logto-config.ts, packages/core/src/routes/logto-config.openapi.json, packages/core/src/routes/logto-config.test.ts, packages/core/src/routes/logto-config.ts, packages/integration-tests/src/api/logto-config.ts, packages/integration-tests/src/tests/api/logto-config.test.ts
Add `DELETE /configs/jwt-customizer/:tokenType` API
Covered by unit tests and integration tests.
=> feat(core): add DELETE /configs/jwt-customizer API

.changeset/clever-buttons-behave.md, packages/core/src/routes/admin-user/basics.ts, packages/integration-tests/src/helpers/index.ts, packages/integration-tests/src/tests/api/admin-user.search.test.ts, packages/integration-tests/src/tests/api/admin-user.test.ts, packages/integration-tests/src/tests/api/dashboard.test.ts, packages/integration-tests/src/tests/api/oidc/always-issue-refresh-token.test.ts, packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts, packages/integration-tests/src/tests/api/oidc/id-token.test.ts
Add 2 fields to create user API: avatar and customData, brings the ability to create a user with full fields (except identites) in a single API call, this is helpful when importing users.
And refactor `createUserByAdmin` in integration tests because this function has too many arguments.
Integration tests should pass.
=> feat(core): create user with avatar and custom data

packages/core/src/libraries/user.test.ts, packages/core/src/libraries/user.ts, packages/core/src/routes-me/user.ts, packages/core/src/routes/admin-user/basics.test.ts, packages/core/src/routes/admin-user/basics.ts, packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts, packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts, packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
Add password algorithm transition, when a user whoes password algorithm is not argon, it will auto migrate to algon upon successful password sign in.
Unit tests and integration tests.
=> feat(core): add password algorithm transition

packages/console/src/ds-components/TextInput/index.module.scss
Confirmed with our designers, the input field in console should not inherit its background color from parent element, and should be set to `--color-layer-1`.
This PR fixes the bug that form fields in organization template have different background colors, like this:
=> fix(console): fix input field background color

packages/console/src/pages/JwtClaims/MonacoCodeEditor/ActionButton/CodeClearButton.tsx, packages/console/src/pages/JwtClaims/MonacoCodeEditor/ActionButton/CodeRestoreButton.tsx, packages/console/src/pages/JwtClaims/MonacoCodeEditor/ActionButton/index.tsx, packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.module.scss, packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx, packages/console/src/pages/JwtClaims/MonacoCodeEditor/type.ts, packages/console/src/pages/JwtClaims/ScriptSection.tsx, packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx, packages/console/src/pages/JwtClaims/config.tsx, packages/console/src/pages/JwtClaims/index.tsx, packages/console/src/pages/JwtClaims/type.ts, packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
1. Replace the copy icon button with AC CopyToClipboard component
2. Implement the clear and reset button
3. Wrap the CodeEditor with react-hook-form so the code content is controllable through the form state.
=> feat(console, phrases): implement the copy, clear and reset button

packages/core/src/libraries/jwt-customizer.ts, packages/core/src/libraries/user.ts, packages/core/src/tenants/Libraries.ts, packages/schemas/src/types/index.ts, packages/schemas/src/types/jwt-customizer.ts
Add `getUserContext` method to the user library.
=> feat(core,schemas): add JWT customizer user info context

.changeset/silent-singers-trade.md, packages/experience/src/hooks/use-native-message-listener.ts
see changeset - clear enough
tested with iOS simulator. all good (with sign-in and sign-out).
=> refactor(experience): skip non-object messages in native

packages/core/src/libraries/organization-invitation.ts, packages/core/src/queries/organization/index.ts, packages/core/src/queries/organization/relations.ts, packages/core/src/routes/organization/invitations.openapi.json, packages/core/src/routes/organization/invitations.ts, packages/integration-tests/src/api/api.ts, packages/integration-tests/src/api/organization-invitation.ts, packages/integration-tests/src/tests/api/organization/organization-invitation.creation.test.ts, packages/integration-tests/src/tests/api/organization/organization-invitation.get.test.ts
update accordingly per https://github.com/logto-io/cloud/pull/516
=> refactor(core): update organization invitation apis

packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/pages/JwtClaims/ScriptSection.tsx, packages/console/src/pages/JwtClaims/SettingsSection/InstructionTab.tsx, packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx, packages/console/src/pages/JwtClaims/config.tsx, packages/console/src/pages/JwtClaims/index.tsx, packages/console/src/pages/JwtClaims/type.ts, packages/core/src/routes/logto-config.ts, packages/schemas/src/types/jwt-customizer.ts
Align the jwt token path enum used in the console and core.
test locally
=> refactor(core,console): align the jwt token path enum

packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/pages/JwtClaims/Main.tsx, packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx, packages/console/src/pages/JwtClaims/ScriptSection.tsx, packages/console/src/pages/JwtClaims/SettingsSection/EnvironmentVariablesField.tsx, packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx, packages/console/src/pages/JwtClaims/SettingsSection/index.module.scss, packages/console/src/pages/JwtClaims/index.tsx, packages/console/src/pages/JwtClaims/use-jwt-customizer.ts, packages/console/src/pages/JwtClaims/utils.ts, packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
Integrate JWT customizer API.
1. Extract a Main component. Render the form elements after the fetch request is completed
2. Rename the frontend `jwt-claims` pathName with backend API naming convention `jwt-customizer`
3. Integrate the GET `api/configs/jwt-customizer/:type` fetch API
4. Integrate the PUT `api/config/jwt-customizer/:type` form submit api
5. Add a front-end test sample code validator. The input code must be a valid JSON. 
test locally. Integration tests will be added later
=> feat(console,phrases): integrate jwt customizer api

packages/console/src/pages/JwtClaims/CodeEditorLoadingContext.ts, packages/console/src/pages/JwtClaims/Main.tsx, packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx, packages/console/src/pages/JwtClaims/PageLoadingSkeleton/index.module.scss, packages/console/src/pages/JwtClaims/PageLoadingSkeleton/index.tsx, packages/console/src/pages/JwtClaims/ScriptSection.tsx, packages/console/src/pages/JwtClaims/index.module.scss, packages/console/src/pages/JwtClaims/index.tsx
Add a global loading skeleton for the jwt-customizer page.
1. Should show the loading skeleton while the swr request is loading.
2. Render the main content and form only after the remote data is ready.
3. Keep the main content hidden till the Monaco editor is ready. (it will load monaco entity and language configs asynchronously)  
4. Remove the loading component and show the main content once both data and code editor are ready.
test locally
=> feat(console): add global loading skeleton

packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx, packages/console/src/pages/JwtClaims/ScriptSection.tsx, packages/console/src/pages/JwtClaims/utils.ts
Fix the code editor set undefined value bug.  react-hook-form does not allow set undefined value to a form field.
- Replace the undefined value with an empty string for all the setForm touch point. 
- Convert the empty string to undefined when sending the request to the logto endpoint.
test locally
=> fix(console): fix code edtior set undefined value bug

packages/core/src/routes/interaction/single-sign-on.ts
Reported by [issue 5502](https://github.com/logto-io/logto/issues/5502), missing 422 status code declared in koa status code guard and `handleSsoAuthentication` could throw 422 errors.
N/A
=> fix(core): the koa response status guard missing 422 in sso integration API

.changeset/thin-shoes-jog.md
Add changeset for the bug fix PR #5506 
test on logto dev environment
=> chore: add changeset for the bug fix PR

packages/core/src/app/init.ts, packages/core/src/env-set/index.ts, packages/core/src/middleware/koa-spa-session-guard.ts, packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts, packages/core/src/routes/interaction/actions/submit-interaction.test.ts, packages/core/src/routes/interaction/actions/submit-interaction.ts, packages/core/src/routes/user-assets.ts, packages/core/src/tenants/Tenant.ts, packages/core/src/tenants/index.ts, packages/core/src/utils/tenant.test.ts, packages/core/src/utils/tenant.ts
Auto set OIDC issuer (`iss`) to the current domain (custom domain or default subdomain).
Previously, the issuer is set to the default endpoint (xxx.logto.app), now it can be changed to the custom domain if the `ctx.URL` matches a tenant's custom domain.
Some unit tests, and local tested mainly, hard to implement integration tests.
After signing in with custom domain endpoint, the `iss` in id token:
=> feat(core): set oidc issuer to custom domain

packages/core/src/libraries/user.test.ts, packages/core/src/routes/interaction/additional.test.ts
Mock crypto related functions in password unit tests, because they may timeout, and there is no need to test them.
Unit tests
=> test(core): mock crypto functions in password tests

.changeset/witty-moose-kick.md, packages/core/src/utils/zod.ts, packages/toolkit/connector-kit/src/index.test.ts, packages/toolkit/connector-kit/src/index.ts, packages/toolkit/connector-kit/src/types/passwordless.ts
the limitation brings more trouble than benefit. the payload type should be guidance instead of enforcement.
added test cases
=> refactor: allow unknown keys in send message payload

packages/console/src/pages/JwtClaims/SettingsSection/InstructionTab.tsx, packages/console/src/pages/JwtClaims/utils/config.tsx, packages/console/src/pages/JwtClaims/utils/type-definitions.ts
As the original hardcoded context property table definition is not scalable and hard to maintain, replace the field table with the type definition code. 
test locally
=> refactor(console): replace the field table with type definition code

packages/core/src/sso/OidcConnector/index.ts, packages/core/src/sso/OktaSsoConnector/index.ts
Refactor the OIDC SSO connector.
- replace the original idToken claims based `getUserInfo`  using the user-info endpoint. So we may fetch additional user info claims and store whatever IdP returned data to the user SSO identities field
- remove the original OKTA connector's overwrite method, as we make it a general solution for general OIDC connector. 
test locally using logto dev IdP and OKTA
=> refactor(core): refactor oidc sso connector

.changeset/seven-socks-perform.md, packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx, packages/experience/src/pages/Consent/ScopesListCard/index.tsx, packages/integration-tests/src/api/interaction.ts, packages/integration-tests/src/client/index.ts, packages/integration-tests/src/tests/api/interaction/third-party-sign-in/happy-path.test.ts, packages/integration-tests/src/tests/api/resource.scope.test.ts, packages/schemas/alterations/next-1710408335-make-resource-scopes-description-nullable.ts, packages/schemas/src/types/consent.ts, packages/schemas/tables/scopes.sql
- Create an organization scope with an empty description and assign this scope to a third-party application.
- Login to the third-party application and request the organization scope.
- Proceed through the interaction flow until reaching the consent page.
- An internal server error 500 is returned.
For the /interaction/consent endpoint, the organization scope is returned alongside other resource scopes in the missingResourceScopes property.
In the consentInfoResponseGuard, we utilize the resource Scopes zod guard to validate the missingResourceScopes property. However, the description field in the resource scope is mandatory while the organization scopes' description is optional. An organization scope with an empty description will not pass the validation.
Modify the …
=> fix(schemas): fix the get interation/consent api bug

packages/console/src/components/ItemPreview/UserPreview.tsx, packages/console/src/components/UserAccountInformation/index.tsx, packages/console/src/pages/Roles/components/AssignToRoleModal/index.tsx, packages/console/src/pages/UserDetails/utils.ts, packages/console/src/utils/user.ts, packages/core/src/libraries/jwt-customizer.ts, packages/core/src/libraries/scope.ts, packages/core/src/routes/role.scope.ts, packages/core/src/tenants/Libraries.ts, packages/schemas/src/types/jwt-customizer.ts, packages/schemas/src/types/user.ts
update user context type:
1. In previous implementation, `userInfoGuard` was broken when applying `.merge()` or `.extend()` zod object method. Fixed by explicitly declare the mask key type used in zod object `.pick()` method.
2. use update user context organizations from record to array.
3. optimize the DB query in user context library method to improve performance.
=> refactor(core): update user context type

packages/core/package.json, packages/core/src/routes/logto-config.openapi.json, packages/core/src/routes/logto-config.ts, packages/core/src/routes/swagger/index.ts, packages/core/src/routes/swagger/utils/general.ts, packages/schemas/src/types/jwt-customizer.ts, pnpm-lock.yaml
Add POST /configs/jwt-customizer/test API.
Since the custom JWT is a cloud 'service' and should be init by Logto core backend, we need to add this API to forward the console cloud service request.
Tested locally, since this API relies on cloud service API, will add tests to Cloud service API.
=> feat(core): add POST /configs/jwt-customizer/test API

packages/console/src/pages/JwtClaims/MonacoCodeEditor/index.tsx, packages/console/src/pages/JwtClaims/MonacoCodeEditor/use-editor-height.ts, packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx, packages/console/src/pages/JwtClaims/SettingsSection/index.module.scss, packages/console/src/pages/JwtClaims/utils/config.tsx, packages/console/src/pages/JwtClaims/utils/format.ts, packages/core/src/libraries/cloud-connection.ts, packages/core/src/routes/logto-config.ts
Integrate the test API.  PR #5525 
Add add the console nav
=> feat(console): integrate jwt customizer test api

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanContent/use-featured-plan-content.ts, packages/console/src/consts/subscriptions.ts, packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
refactor(console): extract shared quota between featured plan content and comparison table
Test locally:
=> refactor(console): extract shared quota between featured plan and comparison table

packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
The `AssignRoleModal` and `CreateRoleForm` should not nested in one modal layout.
Test locally and IT passed
=> refactor(console): avoid nested modal content for role creation

packages/core/src/routes/logto-config.ts, packages/phrases/src/locales/de/errors/jwt-customizer.ts, packages/phrases/src/locales/en/errors/jwt-customizer.ts, packages/phrases/src/locales/es/errors/jwt-customizer.ts, packages/phrases/src/locales/fr/errors/jwt-customizer.ts, packages/phrases/src/locales/it/errors/jwt-customizer.ts, packages/phrases/src/locales/ja/errors/jwt-customizer.ts, packages/phrases/src/locales/ko/errors/jwt-customizer.ts, packages/phrases/src/locales/pl-pl/errors/jwt-customizer.ts, packages/phrases/src/locales/pt-br/errors/jwt-customizer.ts, packages/phrases/src/locales/pt-pt/errors/jwt-customizer.ts, packages/phrases/src/locales/ru/errors/jwt-customizer.ts, packages/phrases/src/locales/tr-tr/errors/jwt-customizer.ts, packages/phrases/src/locales/zh-cn/errors/jwt-customizer.ts, packages/phrases/src/locales/zh-hk/errors/jwt-customizer.ts, packages/phrases/src/locales/zh-tw/errors/jwt-customizer.ts
Fix custom JWT PUT API block admin tenant logic.
1. This custom JWT feature should be available for user tenant, which means should throw error when the current tenant id admin tenant. (previous implementation made mistake)
2. Can not use `auth.forbidden` 403 error because we will call sign out and redirect the user to login page for all console 403 error, this is not expected. Add another error instead.
3. We should bypass the error for unit tests and integration test cases since the user is admin tenant in integration test setup.
=> fix(core,phrases): fix custom JWT PUT API block admin tenant logic

packages/console/src/App.tsx, packages/console/src/cloud/AppRoutes.tsx, packages/console/src/cloud/types/router.ts, packages/console/src/contexts/TenantsProvider.tsx, packages/console/src/pages/AcceptInvitation/SwitchAccount/index.module.scss, packages/console/src/pages/AcceptInvitation/SwitchAccount/index.tsx, packages/console/src/pages/AcceptInvitation/index.tsx
Add a console landing page to accept user invitation. Users who have received the email invitation will click the link to navigate to this console page: `https://cloud.logto.io/accept/:invitationId`
This page will check if the user has signed-in:
- If not, navigate user to sign-in page
- If yes, then check if the sign-in user is the invitee of the invitation:
- If not, display a dialog with "Sign in to another account" button. User clicks the button and navigates to sign-in page
- If yes, auto-accept the invitation and navigate to the target tenant
Locally
Invitee not matching current user:
Invalid invitation status: accepted, expired or revoked
=> feat(console): add console landing page to accept user invitation

.changeset/hungry-dodos-do.md, packages/console/src/pages/ApiResources/components/CreateForm/index.tsx, packages/phrases/src/locales/de/translation/admin-console/api-resources.ts, packages/phrases/src/locales/en/translation/admin-console/api-resources.ts, packages/phrases/src/locales/es/translation/admin-console/api-resources.ts, packages/phrases/src/locales/fr/translation/admin-console/api-resources.ts, packages/phrases/src/locales/it/translation/admin-console/api-resources.ts, packages/phrases/src/locales/ja/translation/admin-console/api-resources.ts, packages/phrases/src/locales/ko/translation/admin-console/api-resources.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/api-resources.ts, packages/phrases/src/locales/pt-br/translation/admin-console/api-resources.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/api-resources.ts, packages/phrases/src/locales/ru/translation/admin-console/api-resources.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/api-resources.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/api-resources.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/api-resources.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/api-resources.ts
=> fix(console,phrases): api resource indicator should be a valid absolute uri

packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx, packages/console/src/pages/JwtClaims/utils/config.tsx
fix the test context code editor bug
1. fix the field name 'client_id' using 'clientId'
2. add the logic if the updated value is the same as the defaultValue e.g. click on the reset button. Instead of saving the default value to db, simply return undefined. 
test locally
=> fix(console): fix jwt test context code editor bug

packages/console/scripts/generate-jwt-customizer-type-definition.ts
fix the zod-to-ts type infer bug
zod-to-ts has multiple rare cases. We have met two issues:
1. nativeEnum. Fix with the settings `{nativeNum: 'Union'}`
Before: 
After:
2. We use the z.lazy method to define the JsonObject type.  zod-to-ts can not infer the type properly. Have to set a workaround. Take the fact the it always uses the root type identifier to inder the z.lazy type field. We always set the identifier as record. 
before:
after:
test locally
=> fix(console): fix the zod-to-ts type infer bug

packages/console/src/components/PermissionsTable/EditPermissionModal.tsx, packages/console/src/components/PermissionsTable/index.module.scss, packages/console/src/components/PermissionsTable/index.tsx, packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx, packages/console/src/pages/RoleDetails/RolePermissions/index.tsx, packages/integration-tests/src/tests/console/rbac/helper.ts, packages/integration-tests/src/tests/console/rbac/machime-to-machime-rbac.test.ts, packages/integration-tests/src/tests/console/rbac/user-rbac.test.ts, packages/phrases/src/locales/de/translation/admin-console/permissions.ts, packages/phrases/src/locales/en/translation/admin-console/permissions.ts, packages/phrases/src/locales/es/translation/admin-console/permissions.ts, packages/phrases/src/locales/fr/translation/admin-console/permissions.ts, packages/phrases/src/locales/it/translation/admin-console/permissions.ts, packages/phrases/src/locales/ja/translation/admin-console/permissions.ts, packages/phrases/src/locales/ko/translation/admin-console/permissions.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/permissions.ts, packages/phrases/src/locales/pt-br/translation/admin-console/permissions.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/permissions.ts, packages/phrases/src/locales/ru/translation/admin-console/permissions.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/permissions.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/permissions.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/permissions.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/permissions.ts
- Support permission editing for permission table
- Reorg `PermissionTable` component's props and add related comments
- Reorg RBAC integration tests:
- rename the original `rbac.test.ts` to `user-rbac.test.ts`
- move the `machine-to-machine.test.ts` into the `rbac` folder
=> feat(console): support permission editing

packages/console/src/pages/JwtClaims/utils/config.tsx, packages/core/src/oidc/init.ts, packages/schemas/src/types/logto-config/oidc-provider.ts
1. update custom JWT sample token payload guard, add some fields not defined in OIDC token type but provided by Logto OIDC provider in real cases;
2. make the custom JWT token sample payload as `.strict()` guard, since even if user give some extra fields in sample token payload, we will not provide that in real case. This could avoid misleading.
3. Filter undefined fields in custom JWT main flow when getting the read only raw token payload.
N/A
=> chore(schemas,core): update custom JWT sample token payload guard

packages/console/src/components/ActionsButton/index.tsx, packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/hooks/use-current-tenant-scopes.ts, packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx, packages/console/src/pages/TenantSettings/TenantBasicSettings/index.tsx, packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx, packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx, packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx, packages/console/src/pages/TenantSettings/TenantMembers/index.tsx, packages/console/src/pages/TenantSettings/index.tsx
Update tenant settings access, show and hide stuff based on user tenant scopes
Locally
=> refactor(console): update tenant settings access per user tenant scopes

packages/schemas/alterations/next-1711607772-remove-invite-member-scope-from-tenant-member-role.ts, packages/schemas/src/types/tenant-organization.ts
Remove `invite:member` scope from tenant member role, so that only admin can invite other members
Locally and CI
=> refactor(schemas): remove invite member scope from tenant member role

packages/schemas/alterations/next-1711624564-add-read-member-scope-to-tenant-roles.ts, packages/schemas/src/types/tenant-organization.ts
Add a new "read:member" scope to both tenant admin and member roles, for browsing tenant members.
CI
=> feat(schemas): add new scope read:member to both tenant admin and member roles

packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx, packages/console/src/pages/JwtClaims/SettingsSection/index.module.scss, packages/console/src/pages/JwtClaims/index.module.scss
revert the custom jwt forms overflow hidden styles.
This PR will fix the page overflow not scrollable and IntelliSense cut-off issue. 
We will refactor the overall page layout in the following PRs. 
test locally
=> fix(console): revert the custom jwt forms overflow hidden

packages/connectors/connector-logto-email/package.json, packages/console/package.json, packages/core/package.json, packages/core/src/oidc/init.ts, packages/core/src/routes/logto-config.ts, packages/schemas/src/types/jwt-customizer.ts, pnpm-lock.yaml
update cloud version and the way to call cloud custom JWT API.
Context: we have updated the API interface of Logto Cloud POST /services/custom-jwt API in previous PRs ([1](https://github.com/logto-io/logto/pull/5557), [2](https://github.com/logto-io/cloud/pull/567)), we need to update the cloud dependency version as well and update the API call to the POST /services/custom-jwt API.
N/A
=> chore: update cloud version and the way to call cloud custom JWT API

packages/schemas/src/types/tenant-organization.ts
Logto Cloud multi-tenancy is built on top of organizations feature, and each user tenant is an associated organization that has ID starts with `t-` and followed by the user tenant ID.
This PR provides a util method to check and convert a given admin tenant organization ID to a user tenant ID.
E.g. `t-abcdef` => `abcdef`
* This util is intended for Logto Cloud features only.
N/A
=> feat(schemas): add util method to convert admin tenant org id to user tenant id

packages/core/src/libraries/logto-config.ts, packages/integration-tests/src/tests/api/logto-config.test.ts
Update GET /configs/jwt-customizer/:tokenPath API error handling. Previously, the Object can not be properly displayed in console error message.
Before the change:
After the change:
=> chore(core): update GET /configs/jwt-customizer/:tokenPath API error handling

packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx, packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx, packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
Refresh invitation list after successfully inviting other members.
=> fix(console): refresh invitation list after inviting members

packages/cli/src/commands/translate/openai.ts
1. Add the support of custom `OPENAI_API_PROXY_ENDPOINT`, since OPENAI sometimes banned some account for no reasons and there are lot of OPENAI API forwarding services we can take advantage of.
2. Update the support to custom OPENAI model, can specify using `OPENAI_MODEL_NAME` env variables. And we updated the default model to be `gpt-3.5-turbo-0125`.
N/A
=> chore(cli): update translate CLI configs

packages/core/src/libraries/organization-invitation.ts, packages/core/src/queries/organization/index.ts
When inserting a new invitation entity, check if the invitee has expired invitations first. If yes, update the invitation status to "Expired" first, in order to avoid the "unique_integrity_violation".
Root cause:
- The invitation table has a unique index based on "pending invitation status + invitee + org id"
- Also, when fetching invitation entities, the `findEntity` query "fakes" the expired status but not being able to update it
Therefore, we can only update the invitation status to expired before inserting a new one to the same invitee. This seems to be the best opportunity to do it.
Tested with cloud API locally.
~~- [ ] integration tests~~ Integration test will be covered in Cloud repo
=> fix(core): update expired invitation to expired before inserting a new one

packages/console/src/cloud/pages/Main/InvitationList/index.tsx, packages/console/src/components/Topbar/TenantSelector/TenantInvitationDropdownItem/index.tsx, packages/console/src/pages/AcceptInvitation/index.tsx
Joining tenant should immediately navigate user to the new tenant.
Previously, the tenants list data was not updated before navigating, so the navigation failed, and user would stay in the old tenant.
Discussed and the solution is just fetching all tenants before navigating user to the new one.
Locally tested
=> fix(console): joining tenant should navigate user to the new tenant

packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/ErrorContent/index.tsx, packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/use-test-handler.ts, packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx, packages/console/src/pages/CustomizeJwtDetails/utils/format.ts, packages/core/src/errors/RequestError/index.ts, packages/core/src/routes/logto-config/jwt-customizer.ts, packages/schemas/src/types/index.ts, packages/schemas/src/types/logto-config/index.ts, packages/schemas/src/types/logto-config/jwt-customizer.ts
update error handling of testing custom JWT:
1. add API request body error handling for custom JWT console when testing
2. update the custom JWT test API interface, which brings a more understandable error message (we reused zod error message formatter to compose the zod error message, previous interface is not easy to be understood by Logto user due to the nested zod variable path)
3. reorder the content of sample user context to align with the zod guard, so that clicking reset button of sample user context does not change the content in the code editor
Before this change, the error only show error code without detailed error message, which is hard for debugging.
=> chore(core,console): update error handling of testing custom JWT

packages/console/src/pages/CustomizeJwt/CustomizerItem/index.tsx, packages/console/src/pages/CustomizeJwt/use-jwt-customizer.ts, packages/console/src/pages/CustomizeJwt/utils/path.ts, packages/console/src/pages/CustomizeJwtDetails/MainContent/index.tsx
1. Reset form as soon as JWT customizer is created.
2. Use GET /configs/jwt-customizer to get the JWT customizer list instead of calling GET JWT customizer by key for all entities.
Tested locally. Will add console integration test later, see LOG-8362.
https://github.com/logto-io/logto/assets/15182327/18de63e7-2c79-49e0-b98d-e6378a0c89b9
=> fix(console): reset form as soon as JWT customizer is created

packages/console/src/consts/logs.ts, packages/console/src/pages/WebhookDetails/WebhookLogs/index.tsx, packages/core/src/oidc/init.ts, packages/schemas/src/types/log/index.ts, packages/schemas/src/types/log/jwt-customizer.ts
log extraTokenClaims exception
N/A
=> feat(core,schemas): log extraTokenClaims exception

packages/console/src/pages/CustomizeJwt/CreateButton/index.module.scss, packages/console/src/pages/CustomizeJwt/CreateButton/index.tsx, packages/console/src/pages/CustomizeJwt/CustomizerItem/index.module.scss, packages/console/src/pages/CustomizeJwt/CustomizerItem/index.tsx, packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx, packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/index.module.scss, packages/console/src/pages/CustomizeJwtDetails/MainContent/index.tsx, packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx, packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
1. reorder guide card and update content on console details page
2. fix the CSS of JWT customizer listing page
3. update default script template by adding `envVariables` as input params
1. reorder guide card and update content on console details page
2. fix the CSS of JWT customizer listing page
3. update default script template by adding `envVariables` as input params
=> chore(console,phrases): update content and fix console

packages/phrases-experience/src/locales/zh-cn/description.ts
I have translated the "authorization page" following third-party IdP login within OIDC into Chinese. I carefully examined the translated result, meticulously cross-checking it using both my personal language preferences and translation software.
=> refactor(phrases): add zh-cn phrases in OIDC consent page

packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
Temporarily fix the bug that cannot invite members in Pro plan tenant.
=> fix(console): temporarily fix pro plan cannot invite members issue

packages/console/src/components/SubmitFormChangesActionBar/index.tsx, packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.module.scss, packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.tsx, packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/index.module.scss, packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/index.tsx, packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/index.module.scss, packages/console/src/pages/CustomizeJwtDetails/MainContent/index.module.scss, packages/console/src/pages/CustomizeJwtDetails/MainContent/index.tsx, packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
Update console styles:
1. the result panel of writing custom JWT code snippet should be the same height as code editor part.
2. code editor should stick to the top.
3. set min height for code editor.
4. update default custom JWT code samples.
5. remove the top margin of submit action bar in custom JWT page.
6. fix some typos.
=> chore(console): update style

packages/console/src/components/PermissionsTable/index.tsx, packages/console/src/consts/page-tabs.ts, packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx, packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx, packages/console/src/pages/ApiResourceDetails/index.tsx, packages/console/src/pages/ApiResourceDetails/types.ts, packages/console/src/pages/ApiResources/index.tsx, packages/integration-tests/src/tests/console/rbac/machime-to-machime-rbac.test.ts, packages/integration-tests/src/tests/console/rbac/user-rbac.test.ts, packages/integration-tests/src/ui-helpers/index.ts, packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/es/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/it/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/ja/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/ru/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/api-resource-details.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/api-resource-details.ts
Per new design, we need to make some updates for the resource details page:
- Rename "Settings" tab to "General"
- Swap "Settings" and "Permissions" tab in the nav list
- Navigate to the "Permissions" tab by default
This PR also refactor related routes in the `ConsoleContent` file, and move routes definition the the details page for a better maintainability since the `ConsoleContent` file is large.
Test locally and integration test passed.
=> refactor(console): reorg resource details page

.changeset/quick-kings-tie.md, packages/core/src/queries/organization/index.ts, packages/core/src/routes/organization/roles.ts, packages/integration-tests/src/tests/api/organization/organization-role.test.ts
Support searching organization roles.
Integration tests and local tested.
=> feat(core): search organization roles

packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx, packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts
Update the JWT test section content. Also, remove the unused `tester.title` phrase.
test locally
=> fix(console,phrases): update the jwt test section content

packages/console/src/pages/CustomizeJwtDetails/MainContent/ScriptSection/index.module.scss, packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.module.scss, packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx, packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/TestTab/index.module.scss, packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/TestTab/index.tsx, packages/console/src/pages/CustomizeJwtDetails/MainContent/index.module.scss, packages/console/src/pages/CustomizeJwtDetails/index.module.scss
1. Remove the script section code editor sticky property. As it may cause other side-effects like IntelliSense overflow cutoff, and vertical scroll area limited to the form field instead of page container level. 
2. Instead, set a smaller constant code editor height for all the data type definition editors, so the right settings section's height is manageable.
3. Remove several duplicate styles.
=> style(console): fix the jwt details page style

packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.module.scss, packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.tsx
This OR fixes the test result panel overflow bug. If the test result content size is huge it will cause the parent flexbox element height to overflow.
Rever the [PR ](https://github.com/logto-io/logto/pull/5625/files#diff-c9494caa1840bf25eda109bf4a77c91edcdc263fe5eeb80e337dc8c37be04d16)
Use CSS to adjust the panel size.
=> fix(console): fix test result panel overflow bug

packages/console/src/pages/OrganizationTemplate/index.tsx
feat(console): add guide for organization template page
=> feat(console): add guide for organization template page

packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx, packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/CustomDomainHeader/index.tsx, packages/console/src/pages/TenantSettings/TenantDomainSettings/CustomDomain/index.tsx, packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx, packages/console/src/pages/TenantSettings/index.tsx
Collaborator role members can see tenant domain settings, but in readonly mode.
No deleting menu, 
=> refactor(console): collaborator can see tenant domain settings in readonly mode

packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
For collaborator role members, hide the switching tabs since they can't invite the others and only have "Members" left.
Admin:
Collaborator:
=> refactor(console): hide switching tabs and invite button for collaborators

packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/hooks.ts, packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.module.scss, packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.tsx, packages/console/src/pages/TenantSettings/TenantMembers/types.ts, packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts, packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
Improve invite email input error messages and logics. Now when inviting new members, this component will check potential email collisions with both existing members and pending invitations.
=> refactor(console,phrases): improve invite email input

packages/connectors/connector-azuread/README.md
Improve the Microsoft social connector readme.  
related issue: #5651 
test locally
=> fix(connector): fix microsoft social connector readme

packages/experience/src/pages/SocialSignInWebCallback/index.test.tsx, packages/experience/src/pages/SocialSignInWebCallback/index.tsx, packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts, packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts, packages/integration-tests/src/tests/experience/direct-sign-in.test.ts, packages/integration-tests/src/tests/experience/social-sign-in.test.ts, packages/integration-tests/src/ui-helpers/expect-experience.ts, packages/integration-tests/src/ui-helpers/expect-page.ts, packages/integration-tests/src/ui-helpers/index.ts, packages/integration-tests/src/utils.ts
when user cancel "terms of use" or it occurs error during social / sso sign-in, redirect to the `/sign-in` page as the fall back. it's an improvement for our experience.
- added integration tests for experience social sign-in, now we covers edge cases like cancel / error handling.
- redirect to the sign-in page for most of errors. they look like patches in this pull request, and we are going to refactor the whole flow soon.
- added unit tests for `<SocialSignInWebCallback>` fallback
integration tests + manual tests
=> refactor(experience): fall back to sign-in page when error

packages/console/src/components/EditScopeModal/index.tsx, packages/console/src/components/PermissionsTable/index.tsx, packages/console/src/pages/OrganizationRoleDetails/Permissions/ResourceName/index.module.scss, packages/console/src/pages/OrganizationRoleDetails/Permissions/ResourceName/index.tsx, packages/console/src/pages/OrganizationRoleDetails/Permissions/index.tsx, packages/console/src/pages/OrganizationRoleDetails/Permissions/use-organization-role-scopes.ts, packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.tsx
feat(console): display api resources in org role permission table
This PR also includes the following updates:
- Extract & rename `EditPermissionModal` into `EditScopeModal` and share it between resource permissions and org role permissions page
- Support editing API resource scope on role permissions page
=> feat(console): display api resources in org role permission table

packages/console/src/containers/ConsoleContent/index.tsx, packages/console/src/pages/Organizations/index.tsx
Deprecate original organization template page since it has been moved to a single page.
This PR also deprecate the original guide when creating a organization, since the guide has simplified and displayed on the organizaion template page.
=> refactor(console): deprecate original organization template page

packages/core/package.json, packages/core/src/libraries/cloud-connection.test.ts, packages/core/src/libraries/logto-config.ts, packages/core/src/libraries/sign-in-experience/index.test.ts, packages/core/src/routes/logto-config/jwt-customizer.test.ts, packages/core/src/routes/logto-config/jwt-customizer.ts, packages/core/src/utils/custom-jwt.ts, pnpm-lock.yaml
Call the custom JWT cloud's worker deployment service when upsert a new jwt-customizer.
This PR includes the following changes:
1. bump the @logto/cloud package version to pick up the latest cloud /service/custom-jwt/worker endpoints
2. Define a new `deployJwtCustomizerScript` library method. It takes the latest jwt-customizer data as input merges with the values stored in DB and deploys to the external worker service. 
3. Update the PUT/PATCH `/logto-configs/jwt-cuszomizer/:tokenTypePath` endpoints to call the deploy method before insert into DB. 
test locally
UT added
=> feat(core): add custom jwt worker deploy

packages/core/src/libraries/cloud-connection.test.ts, packages/core/src/libraries/logto-config.ts, packages/core/src/libraries/sign-in-experience/index.test.ts, packages/core/src/routes/logto-config/jwt-customizer.test.ts, packages/core/src/routes/logto-config/jwt-customizer.ts, packages/core/src/test-utils/mock-libraries.ts
Undeloy the worker script when the JWT customizer is deleted.
Add new method to:
1. call the delete worker cloud service if the only JWT customizer has been deleted
2. call the put worker cloud service to redeploy the worker with the deleted token customizer script being removed. 
test locally
=> feat(core): undeploy worker scripts when jwt customizer is deleted

packages/console/src/hooks/use-console-routes/index.tsx, packages/console/src/hooks/use-console-routes/routes/api-resources.tsx, packages/console/src/hooks/use-console-routes/routes/applications.tsx, packages/console/src/hooks/use-console-routes/routes/audit-logs.tsx, packages/console/src/hooks/use-console-routes/routes/connectors.tsx, packages/console/src/hooks/use-console-routes/routes/customize-jwt.tsx, packages/console/src/hooks/use-console-routes/routes/enterprise-sso.tsx, packages/console/src/hooks/use-console-routes/routes/organization-template.tsx, packages/console/src/hooks/use-console-routes/routes/organizations.tsx, packages/console/src/hooks/use-console-routes/routes/profile.tsx, packages/console/src/hooks/use-console-routes/routes/roles.tsx, packages/console/src/hooks/use-console-routes/routes/sign-in-experience.tsx, packages/console/src/hooks/use-console-routes/routes/tenant-settings.tsx, packages/console/src/hooks/use-console-routes/routes/users.tsx, packages/console/src/hooks/use-console-routes/routes/webhooks.tsx
split the huge route object into files. basically copy-pastes.
- local previewed
- ci should be ok
=> refactor(console): split route objects

packages/core/src/routes/logto-config/jwt-customizer.test.ts, packages/core/src/routes/logto-config/jwt-customizer.ts, packages/schemas/alterations/next-1712912361-delete-jwt-customier-with-empty-script.ts, packages/schemas/src/types/logto-config/jwt-customizer.test.ts, packages/schemas/src/types/logto-config/jwt-customizer.ts
Make the JWT customizer script field mandatory. 
Since we change the user flow in the admin console to create and delete a jwt-customizer, a customizer with an empty script (undefined) value is no longer valid.  Update the guard type to be required. 
Add a db alteration to delete all the dev jwt-customizer records with undefined script. 
test locally
=> refactor(core,schemas): make the jwt customizer script field mandatory

packages/console/src/components/QuotaGuardFooter/index.module.scss
Fix the quota guard layout.
Issue: the `QuotaGuardFooter` component is not displayed in full width under the large-size modal. 
Cause: We have a `justify-content: flex-end` style applied to all the model footer containers. 
Before:
After:
test locally
=> fix(console): fix the quota guard layout

.changeset/real-camels-cheat.md, packages/core/package.json, packages/core/src/oidc/grants/refresh-token.test.ts, packages/core/src/queries/organization/relations.ts, packages/core/src/routes/organization/index.openapi.json, packages/core/src/routes/organization/index.ts, packages/integration-tests/src/api/organization.ts, packages/integration-tests/src/tests/api/organization/organization-user.test.ts
Add a new API to fetch user's organization scopes. The returned scopes will be tailored by user's organization roles.
Should pass API integration tests
=> feat(core): add api to fetch organization scopes for a user

packages/console/src/pages/OrganizationRoleDetails/index.module.scss, packages/console/src/pages/OrganizationRoleDetails/index.tsx, packages/console/src/pages/OrganizationTemplate/index.module.scss
Should have paddings for organization related pages.
=> style(console): update organization template layout

packages/console/src/hooks/use-console-routes/routes/api-resources.tsx, packages/console/src/hooks/use-console-routes/routes/organization-template.tsx, packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/index.tsx, packages/console/src/pages/ApiResourceDetails/ApiResourceSettings/index.tsx, packages/console/src/pages/ApiResourceDetails/index.tsx, packages/console/src/pages/ApiResourceDetails/types.ts, packages/console/src/pages/OrganizationRoleDetails/Permissions/index.tsx, packages/console/src/pages/OrganizationRoleDetails/Settings/index.tsx, packages/console/src/pages/OrganizationRoleDetails/index.tsx, packages/console/src/pages/OrganizationRoleDetails/types.ts
Part of https://github.com/logto-io/logto/pull/5698
Test locally and all UI tests passed.
=> refactor(console): update console routes
