logto-io/logto

package.json
src/database/utils.ts
src/init/router.ts
src/queries/user.ts
src/routes/register.ts
yarn.lock

api: register with username / password

---

.github/workflows/deploy-dev.yml
package.json

master pushes will rsync to dev server

chore: add deploy dev workflow

---

packages/ui/razzle.config.js
packages/ui/src/App.tsx
packages/ui/src/hooks/use-theme.ts
packages/ui/src/init/i18n.ts
packages/ui/src/jest.setup.ts

This PR adds `useTheme()` hook to detect `'(prefers-color-scheme: dark)')` media change and apply the result to app theme automatically.
Change system theme and the app changes its too.

feat(ui): set theme according to system configuration

---

.github/workflows/commitlint.yml

enforce commitlint for every commit in pr

chore: add commitlint workflow

---

.github/workflows/core-main.yml
.github/workflows/ui-main.yml

the main workflow should run if dep has changed

chore: refine workflow trigger

---

.github/workflows/core-main.yml
packages/core/jest.config.js
packages/core/package.json
packages/core/src/utils/env.test.ts
packages/core/tsconfig.base.json
packages/core/tsconfig.test.json
pnpm-lock.yaml

the first step for engineering quality

feat(core): setup jest

---

packages/core/src/routes/application.ts

feat(core): `GET /application/:id`

---

packages/core/src/queries/application.ts
packages/core/src/routes/application.ts

feat(core): `GET /applications`

---

packages/core/src/database/insert-into.test.ts

all 100% test coverage for `insert-into.ts`

test(core): add unit tests for database insert into factory

---

.github/workflows/deploy-dev.yml
packages/core/src/routes/init.ts
packages/core/src/routes/status.ts

feat(core): add status api and health check after deployment

---

packages/core/src/lib/user.test.ts
packages/core/src/lib/user.ts
packages/core/src/routes/user.ts

test(core): add unit tests for `generateUserId()`

---

.github/workflows/deploy-dev.yml

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
官方逼死同人系列

ci: use concurrency for deploy

---

packages/core/src/routes/init.ts
packages/core/src/routes/user.ts
packages/ui/src/hooks/use-api.ts
packages/ui/src/pages/Consent/index.tsx

This PR Includes following updates:
1. Add redirectURI to the response body of register endpoint /user
2. Update the ui consent api call using useApi hooks.
@wangsijie @gao-sun

fix(core):  add redirectURI to the response body of register endpoint /user

---

.github/pull_request_template.md

Implement  pull_request template 
@gao-sun @wangsijie

docs: add pull_request template

---

.github/pull_request_template.md

fix: format PR template

---

packages/core/src/middleware/koa-ui-proxy.ts

- load dist prod when needed
- conditionally build proxy

fix(core): load dist files when needed

---

packages/core/src/queries/user.ts
packages/core/src/routes/user.ts

Basic CRUD APIs for `user`.
According to [LOG-271](https://linear.app/silverhand/issue/LOG-271/post-applications-or-application) , use plural in pathname.
LOG-30 LOG-31 LOG-33 LOG-35
no auto test for now, manually tested with PostMan

feat(core): users basic API

---

packages/core/src/routes/application.ts
packages/core/src/routes/user.ts
packages/ui/src/apis/register.ts

change `user` to `users`, `application` to `applications` in API router

refactor(core): use plural in endpoint

---

packages/core/src/lib/user.test.ts
packages/core/src/lib/user.ts
packages/core/src/routes/user.ts
packages/core/src/utils/password.ts

Add lib `encryptUserPassword()`
Add UT in `user.test.ts`

refactor(core): encryptUserPassword

---

packages/core/src/middleware/koa-guard.ts

chore(core): fix comment mistake

chore(core): fix comment mistake

---

packages/schemas/src/foundations/schemas.ts

Previous Context:
[pr](https://github.com/logto-io/logto/pull/147)
[zod issue](https://github.com/colinhacks/zod/issues/787)
fix manual guard infer type breaks optional zod field type:
Root Cause:
```jsx
export type Guard<T extends Record<string, unknown>> = ZodObject<
{
[key in keyof T]: ZodType<T[key]>;
}
>;
```
Default ZodObject inferred type: 
```jsx
export const dummyData = z.object({
id: z.string(),
name: z.string(),
optionalField: z.number().optional(),
});
type DummyDataZodObjectType = typeof dummyData;
export const omited = dummyData.omit({ optionalField: true });
```
Omitted:
After force declared using  `Guard<DummySchema>` :
```jsx
type DummySchema = {
id: string;
name: string;
optionalField?: number;
};
export const dummyData: Guard<DummySchema> = z.object({
id: z.string(), …
```

fix(schema): fix zod guard infer type for option fields

---

packages/core/src/env/consts.ts
packages/core/src/index.ts

* feat(core): support trusting TLS offloading proxies config
FYI: [Trusting TLS offloading proxies](https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#trusting-tls-offloading-proxies)
* Support trusting TLS offloading proxies config ([LOG-416](https://linear.app/silverhand/issue/LOG-416/support-trusting-tls-offloading-proxies-config))
None

feat(core): support trusting TLS offloading proxies config

---

packages/core/src/middleware/koa-pagination.test.ts

* refactor: disable eslint rule for entire `describe`
* Disable eslint rule for entire `describe` ([LOG-406](https://linear.app/silverhand/issue/LOG-406/disable-eslint-rule-for-entire-describe))
None

refactor: disable eslint rule for entire `describe`

---

packages/core/src/database/find-many.test.ts
packages/core/src/database/find-many.ts

a function to build "findMany" functions for database Models, simalar to `buildInsertInto`.
`find-many.test.ts`
Notice that, instead of mocking and testing database return data, only compare generated sql string and expected sql string.

feat: buildFindMany

---

packages/core/src/errors/SlonikError/index.ts
packages/core/src/queries/application.ts
packages/core/src/queries/resources.ts
packages/core/src/queries/scopes.ts
packages/core/src/queries/user.ts

Define new types of SlonikError - DeletionError for query deletion action exceptions. Should throw 500 externally, and identified as a SlonikError. 
Replace all deletion query RequestError with DeletionError
[reference](https://github.com/logto-io/logto/pull/172#discussion_r783709860)
LOG-1328
Run locally. 
@logto-io/eng

refactor(errors): introduce Slonik Deletion Error

---

packages/core/src/routes/init.ts
packages/core/src/routes/resource.ts

Implement Resources related apis
- GET /resources
- GET /resources/:id
- POST /resources
- PATCH /resources/:id
- DELETE /resources/:id
LOG-712
Test locally on dev
- GET /resources
- GET /resources/:id
- POST /resources
Exception:
- PATCH /resources/:id
- DELETE /resources/:id
@logto-io/eng

feat(core): add resource apis

---

packages/core/src/database/insert-into.test.ts
packages/core/src/database/update-where.test.ts
packages/core/src/oidc/adapter.ts
packages/core/src/queries/application.ts
packages/core/src/queries/connector.ts
packages/core/src/queries/oidc-model-instance.ts
packages/core/src/queries/resource.ts
packages/core/src/queries/scope.ts
packages/core/src/queries/setting.ts
packages/core/src/queries/user-log.ts
packages/core/src/queries/user.ts
packages/core/src/routes/application.ts
packages/core/src/routes/resource.ts
packages/core/src/routes/setting.ts
packages/schemas/src/db-entries/application.ts
packages/schemas/src/db-entries/connector.ts
packages/schemas/src/db-entries/oidc-model-instance.ts
packages/schemas/src/db-entries/resource-scope.ts
packages/schemas/src/db-entries/resource.ts
packages/schemas/src/db-entries/setting.ts
packages/schemas/src/db-entries/user-log.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/src/foundations/schemas.ts
packages/schemas/src/gen/schema.ts
packages/schemas/src/types/user.ts

Per offline discussion:
- rename schema type `FooUpdate` to `FooCreate`
- rename schema `guard` to `createGuard`
TODO: will implement updateGuard based on createGuard on the next PR
UT case & test on locally server
@logto-io/eng

refactor(schema): rename schema

---

packages/core/src/connectors/aliyun-dm/index.ts
packages/core/src/connectors/types.ts

Implement default email template for "Test", LOG-1353 will use this.

feat(aliyun-dm): test message template

---

packages/core/src/connectors/github/constant.ts
packages/core/src/connectors/github/index.test.ts
packages/core/src/connectors/github/index.ts
packages/core/src/connectors/types.ts

GitHub connector's `getAuthorizeUri`
https://www.notion.so/silverhand/Social-470168a733904b7ba2b1f52dd5b131d0
UT
@logto-io/eng

feat(github): getAuthorizeUri

---

packages/core/package.json
packages/core/src/connectors/github/constant.ts
packages/core/src/connectors/github/index.test.ts
packages/core/src/connectors/github/index.ts
packages/core/src/connectors/types.ts
pnpm-lock.yaml

GitHub connector's `getAccessToken`
https://www.notion.so/silverhand/Social-470168a733904b7ba2b1f52dd5b131d0
UT
@logto-io/eng

feat(github): getAccessToken

---

packages/core/src/connectors/github/index.test.ts
packages/core/src/connectors/github/index.ts
packages/core/src/connectors/types.ts

GitHub connector's `validateConfig`
https://www.notion.so/silverhand/Social-470168a733904b7ba2b1f52dd5b131d0
UT

feat(github): validateConfig

---

packages/core/src/connectors/github/constant.ts
packages/core/src/connectors/github/index.test.ts
packages/core/src/connectors/github/index.ts
packages/core/src/connectors/types.ts

GitHub connector's `getUserInfo`
https://www.notion.so/silverhand/Social-470168a733904b7ba2b1f52dd5b131d0
UT
@logto-io/eng

feat(github): getUserInfo

---

packages/phrases/package.json
packages/phrases/src/index.ts
packages/phrases/src/types.ts
pnpm-lock.yaml

- refactor(phrases): replace Normalize with NormalizeKeyPaths from @silverhand/essentials
Related PR: https://github.com/silverhand-io/essentials/pull/6
LOG-1399
LOG-1402
---
@logto-io/eng

refactor(phrases): replace Normalize with NormalizeKeyPaths

---

packages/core/src/connectors/index.ts
packages/core/src/queries/connector.ts

use `hasConnector` in `initConnector` to avoid error
@darcyYe

fix: initConnector use hasConnector

---

packages/core/src/routes/init.ts
packages/core/src/routes/session.ts
packages/core/src/routes/user.ts
packages/ui/src/apis/register.ts

implement API `POST /session/register`
Local tested.

feat: user register

---

packages/core/src/lib/passcode.test.ts
packages/core/src/lib/passcode.ts
packages/core/src/queries/passcode.ts

implement function: `createPasscode`
see LOG-846
UTs

feat(core): createPasscode

---

packages/core/src/connectors/index.ts
packages/core/src/connectors/types.ts
packages/core/src/lib/passcode.test.ts
packages/core/src/lib/passcode.ts
packages/core/src/queries/passcode.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

sendPasscode function implementation: find a suitable connector and send message to target (can be found on passcode in DB)
UTs
@darcyYe may have some conflicts with #203

feat: sendPasscode

---

packages/core/src/lib/passcode.test.ts
packages/core/src/lib/passcode.ts
packages/core/src/queries/passcode.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

`verifyPasscode` function implementation: verify user sent code with current session's passcode.
UTs

feat: verifyPasscode

---

packages/core/src/connectors/aliyun-dm/index.ts

call validateConfig before sending any message.

fix(aliyun-dm): validate config before sending

---

packages/core/src/lib/sign-in.ts
packages/core/src/lib/user.ts
packages/core/src/middleware/koa-user-log.ts
packages/core/src/queries/passcode.ts
packages/core/src/queries/user.ts
packages/core/src/routes/session.ts
packages/core/src/utils/regex.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/db-entries/custom-types.ts
packages/schemas/tables/user_logs.sql

Sign in with email (and passcode).
`POST /session`
if no `code` in body, send passcode.
else, verify passcode and sign in.
LOG-865
Local test:

feat(core): sign in with email

---

packages/core/src/lib/sign-in.ts
packages/core/src/queries/user.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Check email existency before sending code for sign in.
LOG-1469
Local tested.

feat(core): check email existency before sending code

---

packages/core/src/oidc/init.ts

hard code resource access_token format to jwt
if not provided, OIDC Provider will return the default format of the access_token
@gao-sun cc: @logto-io/eng

fix(core): hard code resource access_token format

---

packages/core/src/lib/register.ts
packages/core/src/lib/sign-in.ts
packages/core/src/routes/session.ts
packages/core/src/utils/regex.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Register with email and passcode. Including 3 major changes:
1. Send passcode for register
2. Register
3. Refactor registerWithUsernameAndPassword for clearer route
LOG-863
Local tested.

feat(core): register with email

---

packages/core/src/database/find-many.test.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/tables/users.sql

Add column `identities` for user table.
Notice that `identities` is desigend to be a record instead of array for better quering and indexing.
An example identity for GitHub sign in:
```json
{
"github": {
"userId": "wangsijie",
"details": {
"name": "Wang Sijie"
}
}
}
```

feat(schema): user identities

---

packages/core/src/connectors/github/index.ts
packages/core/src/connectors/index.ts
packages/core/src/lib/sign-in.ts
packages/core/src/middleware/koa-user-log.ts
packages/core/src/queries/user.ts
packages/core/src/routes/session.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/db-entries/custom-types.ts
packages/schemas/tables/user_logs.sql

Sign in with social connector.
LOG-632
Local test with GitHub:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>

feat: social sign in

---

packages/core/src/lib/register.ts
packages/core/src/lib/sign-in.ts
packages/core/src/lib/social.ts
packages/core/src/routes/session.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Register through social account.
LOG-629
<details>
</details>
<details>
</details>
<details>
</details>

feat: social register

---

packages/core/src/database/find-many.test.ts
packages/core/src/lib/register.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/tables/users.sql

On social registration, set profiles granting from social connector to the new user.
LOG-1541

feat: set profiles from social connector

---

packages/core/src/lib/sign-in.ts

Update social userinfo in `user.identities` each time a user is successfuly signed in by social connector.
LOG-876
before:
after:

feat: update social info on sign in

---

packages/core/src/middleware/koa-pagination.test.ts
packages/core/src/middleware/koa-pagination.ts

Throw a internal error if no totalCount returned to the pagination middleware
LOG-1336
ut updated and test case added
@wangsijie cc: @logto-io/eng

refactor(core): throw error on pagination middleware

---

packages/core/src/database/find-many.test.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/tables/users.sql

feat(core): add `custom_data` to the user schema
* LOG-1219
* LOG-1553
None.

feat(core): add `custom_data` to the user schema

---

packages/core/src/errors/RequestError/request-error.test.ts
packages/core/src/errors/SlonikError/slonik-error.test.ts

add error type ut
- RequestError
- Slonik DeletionError
LOG-1538
add ut case
@logto-io/eng

test(ut): add error type ut

---

packages/core/src/i18n/detect-language.test.ts

add detectLanguage util test
LOG-1537
ut case added
@logto-io/eng

test(i18n): add detectLanguage util test

---

packages/core/src/lib/register.ts
packages/core/src/lib/social.ts

forgot to commit some changes for #223

fix: connector_id_mismatch and mergeWithLastSubmission

---

.github/workflows/main.yml
.gitignore
.npmrc
packages/console/README.md
packages/console/package.json
packages/console/src/App.module.scss
packages/console/src/App.tsx
packages/console/src/include.d/react-app.d.ts
packages/console/src/index.html
packages/console/src/index.tsx
packages/console/tsconfig.json
pnpm-lock.yaml

init console project with parceljs

feat(console): init

---

package.json
packages/console/package.json
packages/core/package.json
packages/phrases/package.json
packages/schemas/package.json
packages/ui/package.json
pnpm-lock.yaml

upgrade TypeScript to `^4.5.5`
UT

refactor: upgrade TypeScript

---

packages/core/src/queries/user.ts
packages/core/src/routes/admin-user.ts

feat(core): get `/users`
* LOG-792
content:
pagination

feat(core): get `/users`

---

packages/core/src/routes/admin-user.ts

feat(core): get `/users/:userId`
* LOG-613

feat(core): get `/users/:userId`

---

packages/core/src/routes/admin-user.ts

feat(core): post `/users`
* LOG-614
Post with invalid body
Post with existed username
Post with valid body

feat(core): post `/users`

---

packages/core/src/routes/admin-user.ts
packages/schemas/src/types/user.ts

feat(core): patch `/user/:userId/custom-data`
* LOG-805
Before (GET):
Patch with invalid custom data:
Patch with correct custom data:
Partial update (PATCH):
After (GET):

feat(core): patch `/user/:userId/custom-data`

---

packages/console/src/index.html
packages/ui-new/README.md
packages/ui-new/package.json
packages/ui-new/src/App.module.scss
packages/ui-new/src/App.tsx
packages/ui-new/src/include.d/react-app.d.ts
packages/ui-new/src/index.html
packages/ui-new/src/index.tsx
packages/ui-new/tsconfig.json
pnpm-lock.yaml

init `ui-new` to gradually migrate `ui` stuff to parcel, will replace the original project once the migration is done.
works as expected

feat(ui): init `ui-new` package

---

packages/core/src/middleware/koa-auth.test.ts
packages/core/src/middleware/koa-guard.test.ts
packages/core/src/middleware/koa-i18next.test.ts
packages/core/src/middleware/koa-oidc-error-handler.test.ts
packages/core/src/middleware/koa-oidc-error-handler.ts
packages/core/src/middleware/koa-slonik-error-handler.test.ts
packages/core/src/middleware/koa-ui-proxy.test.ts
packages/core/src/middleware/koa-user-info.test.ts
packages/core/src/middleware/koa-user-log.test.ts
packages/core/src/middleware/koa-user-log.ts
packages/core/src/utils/test-utils.ts

- add more middleware tests
- fix a typo `createContextWithRouteParamters` -> `createContextWithRouteParameters`
- fix koa-user-log bug
log-1528
ut case added
@logto-io/eng

test(core): add more middleware tests [2 of 2]

---

packages/core/src/routes/admin-user.ts

* feat(core): delete `/users/:userId`
* feat(core): patch `/users/:userId/password`
* feat(core): patch `/users/:userId/username`
* feat(core): patch `/users/:userId/primary-email`
* feat(core): patch `/users/:userId/primary-phone`
* LOG-1261
* LOG-1260
* LOG-1259
* LOG-1251
* LOG-1250
feat(core): delete `/users/:userId`
feat(core): patch `/users/:userId/password`
feat(core): patch `/users/:userId/username`
feat(core): patch `/users/:userId/primary-email`
feat(core): patch `/users/:userId/primary-phone`

feat(core): users sensitive operation api

---

packages/core/package.json
packages/core/src/middleware/koa-user-info.test.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/core/src/utils/test-utils.ts
pnpm-lock.yaml

add admin-user route ut
LOG-1530
ut case added
@logto-io/eng

test(core): add admin-user route UT

---

packages/ui/src/apis/register.ts
packages/ui/src/apis/sign-in.ts

chore(core): fix UI router

---

packages/core/src/utils/assert-that.test.ts
packages/core/src/utils/id.test.ts
packages/core/src/utils/zod.test.ts

add ut for util methods
LOG-1539
test case added
@logto-io/eng

test(core): add ut for util methods

---

packages/core/src/middleware/koa-user-info.test.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/application.test.ts
packages/core/src/routes/resource.test.ts
packages/core/src/routes/role.test.ts
packages/core/src/routes/setting.test.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/status.test.ts
packages/core/src/routes/swagger.test.ts
packages/core/src/utils/mock.ts
packages/core/src/utils/test-utils.ts

add ut for core router
- application
- resource
- role
- setting
- sign-in-experience
- status
- swagger
todo:
- admin-user: @xiaoyijun 
- session: @simeng-li 
- connector: @wangsijie @darcyYe 
log-1530
ut case added
@logto-io/eng

test(core): add ut for core routers

---

packages/core/src/lib/register.ts
packages/core/src/routes/session.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Bind social account to an existing user.
LOG-630

feat: bind social account

---

packages/core/src/lib/register.ts
packages/core/src/lib/sign-in.ts
packages/core/src/lib/social.ts
packages/core/src/routes/session.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Implement the following flow:
1. Try to sign in with social, but Logto account not found
2. User choose to bind Logto account by register
LOG-1542

feat: continue to register with social

---

packages/core/src/connectors/index.ts
packages/core/src/connectors/types.ts
packages/core/src/lib/passcode.test.ts
packages/core/src/lib/passcode.ts
packages/core/src/lib/sign-in.ts

To make typings more specifc and clear, seperate them into 2 kind of types:
Connector: without database info
ConnectorInstance: with database info
Then:
```
connector.connector.enabled
```
instead of
```
connector.connector?.enabled
```
LOG-1449

chore: make connectorInstance.connector non-nullable

---

packages/core/src/middleware/koa-role-guard.test.ts
packages/core/src/middleware/koa-role-guard.ts
packages/schemas/src/types/user.ts

Add user role guard middleware
check user role contains admin. temp solution before RBAC.
log-722
ut case added
@logto-io/eng

feat(core): add koa user role guard middleware

---

packages/core/src/oidc/adapter.test.ts
packages/core/src/oidc/init.test.ts
packages/core/src/oidc/init.ts
packages/core/src/oidc/utils.test.ts

Add oidc adapter test case
log-1533
ut case added
@logto-io/eng

test(oidc): add oidc adapter test case

---

packages/core/src/routes/session.ts

chore: rename route for bind and sign in

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/core/src/utils/test-utils.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Setup unit tests for session route, the tests are different from those in other routes, because it has a "provider".
@simeng-li

test(session): test setup for session route

---

packages/core/src/routes/admin-user.test.ts

test(core): add ut for admin-user
* LOG-1598
UT

test(core): add ut for admin-user

---

packages/core/src/lib/user.test.ts
packages/core/src/lib/user.ts
packages/core/src/utils/password.ts
packages/schemas/src/db-entries/custom-types.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/tables/users.sql

refactor(core): add prefix for `password_encryption_method`
* LOG-356
UT

refactor(core): add prefix for `password_encryption_method`

---

packages/core/src/routes/session.ts
packages/core/src/utils/regex.ts

Add username existence check when registering. (share API with register with username-and-password flow, hence password field is optional)
LOG-1468
N/A

feat(core): get `/session/register/:username/existence`

---

packages/core/src/lib/session.ts
packages/core/src/routes/session.ts

Put all username/phone/email validity checks into koaGuard middleware (in /session routes).
`assertThat` method is used previously.
LOG-1604
N/A
UT of session routes is on its way, coming soon!

chore(core):  username/phone/email validity checks to koaGuard middleware (in /session routes)

---

packages/core/package.json
packages/core/src/queries/application.test.ts
packages/core/src/queries/application.ts
packages/core/src/utils/test-utils.ts
pnpm-lock.yaml

Add ut for appliction queries
LOG-1531
ut case added 
@logto-io/eng

test(core): add ut for application query

---

packages/core/src/lib/session.ts
packages/core/src/routes/session.ts

Enable pass redirectUri when sign-in with social.
LOG-1629
N/A

chore(core): enable pass redirectUri when sign-in with social

---

packages/core/src/lib/social.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/core/src/utils/test-utils.ts

Add unit tests for the following routes:
- DELETE /session
- POST /session/sign-in/username-password
- POST /session/sign-in/passwordless/phone/send-passcode
- POST /session/sign-in/passwordless/phone/verify-passcode
- POST /session/sign-in/passwordless/email/send-passcode
- POST /session/sign-in/passwordless/email/verify-passcode
- POST /session/sign-in/bind-social-related-user
- POST /session/bind-social
tests for all routes in session will be seperated into several PRs.

test: session route

---

.vscode/scss.code-snippets
.vscode/settings.json
.vscode/tsx.code-snippets
packages/console/package.json
packages/console/src/App.module.scss
packages/console/src/App.tsx
packages/console/src/components/Content/index.module.scss
packages/console/src/components/Content/index.tsx
packages/console/src/components/Sidebar/index.module.scss
packages/console/src/components/Sidebar/index.tsx
packages/console/src/components/Topbar/index.module.scss
packages/console/src/components/Topbar/index.tsx
packages/console/src/scss/_underscore.scss
packages/console/src/scss/normalized.scss
packages/console/tsconfig.json

init admin console layout
to-dos:
- upgrade all eslint configs
- extract common files in a separate package

feat(console): init layout

---

packages/core/src/connectors/types.ts
packages/core/src/connectors/utilities/index.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/schemas/src/db-entries/connector.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/tables/connectors.sql
packages/schemas/tables/users.sql

refactor(core): add arbitrary object guard type
LOG-1553
UT

refactor(core): add arbitrary object guard type

---

packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/core/src/routes/session.ts
packages/core/src/utils/regex.ts

refactor(core): add regex for commonly used fields
These rules for fields are temporary and will be replaced with proper rules before v1 is launched and this is tracked by LOG-1630.
LOG-1569
UT

refactor(core): add regex for commonly used fileds

---

packages/core/src/connectors/github/index.test.ts
packages/core/src/connectors/utilities/aliyun.ts
packages/core/src/connectors/utilities/index.test.ts
packages/core/src/connectors/utilities/index.ts

add tests for:
`github/index.test.ts`
`utilities/index`
@logto-io/eng

test(core): github and connector utilities

---

packages/phrases/package.json
pnpm-lock.yaml

remove unused dependency to eliminate cyclic warning
CI

fix(schemas): remove unused dependency

---

packages/core/src/connectors/aliyun-dm/index.test.ts
packages/core/src/connectors/aliyun-dm/index.ts

Add unit tests for `aliyun-dm/index.ts`
@logto-io/eng

test(core): aliyun-dm

---

packages/phrases/src/locales/en.ts

chore(phrases): fix typos in locales/en.ts
None.
No need.
---
@logto-io/eng

chore(phrases): fix typos in locales/en.ts

---

packages/core/src/routes/session.test.ts

Refactor unit tests in session route, mock `oidc-provider` in a more clear approach.
@simeng-li @darcyYe

refactor(core): session tests

---

packages/core/src/routes/session.test.ts

Add unit tests for `POST /session/consent`
@simeng-li @darcyYe @gao-sun

test(core): session consent

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts

Add UTs for following routes:
POST /session/sign-in/social
POST /session/register/username-password
GET /session/register/:username/existence
POST /session/register/passwordless/phone/send-passcode
POST /session/register/passwordless/phone/verify-passcode
POST /session/register/passwordless/email/send-passcode
POST /session/register/passwordless/email/verify-passcode
POST /session/register/social
LOG-1532
UT

test(core): add UTs for session routes

---

packages/console/package.json
packages/console/src/App.tsx
packages/console/src/components/Sidebar/components/Item/index.module.scss
packages/console/src/components/Sidebar/components/Item/index.tsx
packages/console/src/components/Sidebar/index.tsx
packages/console/src/components/Sidebar/utils.ts
packages/console/src/index.tsx
pnpm-lock.yaml

- make console default route to the very first tab
- activate tab by current route
- navigate to route by click
LOG-1650
@logto-io/eng

feat(console): active tab by route

---

packages/console/src/App.module.scss
packages/console/src/App.tsx
packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/AppContent/index.tsx
packages/console/src/components/Sidebar/components/Item/index.module.scss
packages/console/src/components/Topbar/index.module.scss
packages/console/src/scss/_underscore.scss
packages/console/src/scss/normalized.scss

implement `<AppContent>` for color and font in css variables
LOG-1649
looks good locally

feat(console): theme

---

packages/console/src/components/Sidebar/components/Item/index.tsx
packages/console/src/components/Sidebar/index.tsx

fix tab route link issue caused by i18n
localhost

fix(console): tab route link

---

packages/console/src/App.module.scss
packages/console/src/App.tsx
packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/Card/index.module.scss
packages/console/src/components/Card/index.tsx
packages/console/src/pages/ApiResources/index.tsx

init api resources page
@logto-io/eng

feat(console): init api resources

---

packages/console/src/components/Topbar/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

refactor(console): title i18n

---

packages/console/src/App.module.scss
packages/console/src/App.tsx
packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/Button/index.module.scss
packages/console/src/components/Button/index.tsx
packages/console/src/components/Card/index.module.scss
packages/console/src/components/CardTitle/index.module.scss
packages/console/src/components/CardTitle/index.tsx
packages/console/src/pages/Applications/index.module.scss
packages/console/src/pages/Applications/index.tsx
packages/phrases/src/index.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

- implement `<CardTitle>`
- implement `<Button>` with 2 types and 3 sizes
- init applications page layout
- plus icon for "Create Application" button is not ready (add afterwards)
- i18n is not settle (use English for now)
LOG-1684

feat(console): applications layout

---

packages/console/package.json
packages/console/src/App.tsx
packages/console/src/components/ItemPreview/index.tsx
packages/console/src/pages/Applications/index.module.scss
packages/console/src/pages/Applications/index.tsx
packages/console/src/swr/index.ts
packages/console/src/types/applications.ts
packages/core/src/include.d/koa.d.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
pnpm-lock.yaml

- fetch & display application data from api
- table loading / error / empty state (LOG-1820)
- no Logto SDK integrated (LOG-1821)
LOG-1688
read data from api
@logto-io/eng

feat(console): retrieve applications from api

---

packages/console/src/pages/ApiResources/index.module.scss
packages/console/src/pages/ApiResources/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

feat(console): api resources list page
* LOG-1694

feat(console): api resources list page

---

packages/core/src/connectors/github/index.test.ts
packages/core/src/connectors/google/index.test.ts

test(core): fix typos in connectors/*/index.test.ts
LOG-1621
No need.
---
@logto-io/eng

test(core): fix typos in connectors/*/index.test.ts

---

packages/core/src/connectors/aliyun-dm/index.ts
packages/core/src/connectors/aliyun-sms/index.ts
packages/core/src/connectors/github/index.ts
packages/core/src/connectors/google/index.ts

chore(core): add TODO comments for adding the real connector logo URL
LOG-1621
#321 [comment](https://github.com/logto-io/logto/pull/321#discussion_r820335019)
No need.

chore(core): add TODO comments for adding the real connector logo URL

---

packages/console/src/App.tsx
packages/console/src/pages/Connectors/Connector.tsx
packages/core/src/connectors/types.ts
packages/core/src/routes/connector.ts
packages/schemas/src/types/connector.ts
packages/schemas/src/types/index.ts

Init connector detail page.
LOG-1720

feat(console): init connector page

---

packages/core/src/connectors/aliyun-dm/index.ts
packages/core/src/connectors/aliyun-sms/index.ts
packages/core/src/connectors/github/index.ts
packages/core/src/connectors/google/index.ts

refactor(core): simplify check-and-throw-ConnectorError with assertThat
LOG-1621 #321 [comment](https://github.com/logto-io/logto/pull/321#discussion_r820426707)
---
@logto-io/eng

refactor(core): simplify check-and-throw-ConnectorError with assertThat

---

packages/console/package.json
packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/components/CopyToClipboard/index.tsx
packages/console/src/components/Tooltip/index.module.scss
packages/console/src/components/Tooltip/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/package.json
pnpm-lock.yaml

- implement tooltip component
- integrate with `<CopyToClipboard />`
@logto-io/eng

feat(console): implement tooltip and integrate with copy

---

packages/console/src/App.tsx
packages/console/src/pages/Connectors/index.module.scss
packages/console/src/pages/Connectors/index.tsx
packages/core/src/connectors/aliyun-dm/index.ts
packages/core/src/connectors/aliyun-sms/index.ts
packages/core/src/connectors/github/index.ts
packages/core/src/connectors/google/index.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Init connectors list page.
LOG-1713

feat(console): init connectors

---

packages/core/src/connectors/facebook/constant.ts
packages/core/src/connectors/facebook/index.test.ts
packages/core/src/connectors/facebook/index.ts
packages/core/src/connectors/index.ts

- feat(core): facebook connector
- test(core): facebook connector
---
Failed to get user info → HTTP Code 400
LOG-1621
---
User info from Facebook Graph API:
Console.log when 
Called logto/core `/api/session/sign-in/social`:

feat(core): facebook connector

---

packages/console/package.json
packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/Button/index.tsx
packages/console/src/components/FormField/index.module.scss
packages/console/src/components/FormField/index.tsx
packages/console/src/components/RadioGroup/index.module.scss
packages/console/src/components/RadioGroup/index.tsx
packages/console/src/components/TextInput/index.module.scss
packages/console/src/components/TextInput/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.module.scss
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
packages/console/src/pages/Applications/index.tsx
packages/console/src/scss/modal.module.scss
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
pnpm-lock.yaml

- implement text input
- complete app create form
- submit form to api
To-do:
- implement form loading / error state (pending design)
LOG-1824
create and re-fetch app successfully

feat(console): app create form

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts

Add POST /session/forgot-password/phone/verify-passcode-and-reset-password and corresponding UT.
LOG-1815
UT.

feat(core): post /session/forgot-password/phone/verify-passcode-and-reset-password

---

packages/console/src/scss/_underscore.scss
packages/ui/src/__mocks__/logto.tsx
packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/BrandingHeader/index.module.scss
packages/ui/src/components/BrandingHeader/index.test.tsx
packages/ui/src/components/BrandingHeader/index.tsx
packages/ui/src/pages/Register/index.module.scss
packages/ui/src/pages/SignIn/index.module.scss
packages/ui/src/scss/_underscore.scss

- Add Branding Component 
- Fix typo of the flex-column
- Update the primary color according to the latest design
- Mark all legacy styles, need to clean up after full implementation
LOG-1762
UT added

feat(ui): add Branding component

---

packages/console/src/pages/Applications/index.tsx

navigate to application details when clicking application row
it works
@logto-io/eng

feat(console): applications list navigation

---

packages/console/src/components/RadioGroup/Radio.tsx
packages/console/src/components/RadioGroup/index.module.scss
packages/console/src/components/RadioGroup/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.module.scss
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

- add error message for application type selection
- add focus effect for `<Radio>`
- add key press handler for `<Radio>`
also tested with keyboard events
@logto-io/eng

refactor(console): improve create app form ux

---

packages/console/src/pages/ApiResources/components/CreateForm/index.module.scss
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/scss/_underscore.scss

feat(console): create resource page
* LOG-1696
Create Page:
After Create:

feat(console): create resource page

---

packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/Button/index.module.scss
packages/console/src/components/Button/index.tsx
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/Connectors/components/ConnectorRow.tsx
packages/console/src/pages/Connectors/index.tsx

Add "default" button type, and set type default value to "default" instead of "primary".

feat(console): default button style

---

packages/console/src/pages/Applications/index.tsx

once a new app is created, jump to different url based on settings
LOG-1691
locally
@logto-io/eng

feat(console): conditional navigation after create app

---

packages/console/src/App.tsx
packages/console/src/pages/ApiResourceDetails/index.module.scss
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

feat(console): api resource details
* LOG-1695

feat(console): api resource details

---

packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/scss/drawer.module.scss
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Open a drawer for README, the content is not implemented, awaiting LOG-1858

feat(console): connector details readme

---

packages/core/src/routes/connector.test.ts
packages/core/src/utils/mock.ts

Add UTs for connector route.
LOG-1844
UT.
Before UTs were added:
Afterward,

test(core): add UT for connector route

---

packages/console/src/pages/Applications/components/CreateForm/index.module.scss

refactor(console): replace the text-filed css with mixin in the application create form
None.

refactor(console): replace the text-filed css with mixin in the application create form

---

packages/console/src/components/CodeEditor/index.module.scss
packages/console/src/components/CodeEditor/index.tsx
packages/console/src/components/TabNav/index.module.scss
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/index.module.scss
packages/core/src/middleware/koa-connector-error-handle.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Add config area in connector details page.
JSON Editor will be implemented in LOG-1708
`{saveError && <div>{saveError}</div>}` will be refactored once the design is finished.
LOG-1722

feat(console): connector config

---

packages/console/src/components/Card/index.module.scss
packages/console/src/pages/ApiResources/index.module.scss
packages/console/src/pages/Applications/index.module.scss
packages/console/src/pages/Connectors/index.module.scss

Restore paddings to Card component
-[x] Tested on Applications page, and the UI looks good

refactor(console): restore paddings to Card component

---

packages/core/src/database/find-many.test.ts
packages/core/src/database/find-many.ts
packages/core/src/database/types.ts
packages/core/src/queries/application.test.ts
packages/core/src/queries/application.ts

- feat(core): find many data order by
- feat(core): findAllApplications order by createdAt desc
LOG-1855
---
---
@logto-io/eng

feat(core): findAllApplications order by createdAt desc

---

package.json
packages/console/package.json
packages/core/package.json
packages/phrases/package.json
packages/schemas/package.json
packages/ui/package.json
pnpm-lock.yaml

- upgrade parcel to 2.3.2 for [bug fixing](https://github.com/parcel-bundler/parcel/issues/7697)
- upgrade typescript to 4.6.2
localhost & UT

chore: upgrade packages

---

packages/console/src/components/Tooltip/index.tsx
packages/console/src/pages/ConnectorDetails/components/SenderTester/index.module.scss
packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/utils/regex.ts
packages/core/src/connectors/types.ts
packages/core/src/routes/connector.test.ts
packages/core/src/routes/connector.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

* console: connector sender test
* core: add connector sender test routes
* test: add uts for connecter routes
* LOG-1723
console:
email:
phone message:

feat(console): connector sender test

---

packages/core/src/connectors/aliyun-dm/README.md
packages/core/src/connectors/aliyun-dm/index.ts
packages/core/src/connectors/aliyun-sms/README.md
packages/core/src/connectors/aliyun-sms/index.ts
packages/core/src/connectors/facebook/README.md
packages/core/src/connectors/facebook/index.ts
packages/core/src/connectors/github/README.md
packages/core/src/connectors/github/index.ts
packages/core/src/connectors/google/README.md
packages/core/src/connectors/google/index.ts
packages/core/src/lib/passcode.test.ts
packages/core/src/routes/connector.test.ts
packages/core/src/utils/mock.ts
packages/schemas/src/types/connector.ts

Add README.md placeholder for connectors.
(Did not consider multiple-language support at this stage.)
LOG-1809
UT.

feat(core): add README.md for connectors

---

packages/core/src/routes/connector.test.ts

Fix connector route tests.
UT.

fix(core): fix connector route tests

---

packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/CopyToClipboard/index.tsx
packages/console/src/components/Topbar/index.module.scss
packages/console/src/pages/ApplicationDetails/index.module.scss
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/scss/_underscore.scss
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

refactor(console): application detail header
* LOG-1882

refactor(console): application detail header

---

packages/console/package.json
packages/console/src/components/Markdown/index.module.scss
packages/console/src/components/Markdown/index.tsx
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/core/src/connectors/github/README.md
pnpm-lock.yaml

Add Markdown component: render markdown content fetched from API.
LOG-1867

feat(console): markdown component

---

packages/console/src/components/ActionMenu/ActionMenuButton.tsx
packages/console/src/components/ActionMenu/ActionMenuItem.module.scss
packages/console/src/components/ActionMenu/ActionMenuItem.tsx
packages/console/src/components/ActionMenu/index.module.scss
packages/console/src/components/ActionMenu/index.tsx
packages/console/src/components/ActionMenu/use-position.ts
packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/Button/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Add component ActionMenu.
LOG-1870
4 sides:

feat(console): action menu

---

packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/Button/index.module.scss
packages/console/src/components/Card/index.module.scss
packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/components/Status/index.module.scss
packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
packages/console/src/scss/_colors.scss
packages/console/src/scss/normalized.scss

Refactor tonal palette colors in admin console, and prepare mixins for dark theme.
-[x] Confirmed by UX designer

refactor(console): tonal palette colors and theme mixins

---

packages/console/src/components/Button/index.module.scss
packages/console/src/components/Button/index.tsx

Add `plain` and `outline` button types
Figma link: https://www.figma.com/file/bcSRcMyKEQc0c7k7QfP9fG/%F0%9F%AA%90-%5BWeb%5D-AC-Design-System?node-id=22%3A87
Tested in local

feat(console): add outline and plain button types

---

packages/console/src/components/ActionMenu/ActionMenuItem.tsx
packages/console/src/components/ActionMenu/index.tsx
packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.module.scss
packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

This PR is opened for the purpose of implementing all delete pages in a more consistent way.
Notes:
* There are bugs when requesting to `DELETE /resources/:id`.
* Full logic will be implemented once the Todos below have been done.
* LOG-1888: Waiting for the refactoring of `Button` Component
* LOG-1899: fix `DELETE /resources/:id` in logto core
* LOG-1900: Research: i18n text styles
* LOG-1697
Hightligt in i18n:

feat(console): delete api resource

---

packages/console/src/App.tsx
packages/console/src/pages/NotFound/index.tsx

add fallback not found page in routes
localhost
@eng

feat(console): not found page

---

packages/console/src/components/Status/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorRow.tsx

Change Status component's type to "enabled" and "disabled".
@demonzoo 
LOG-1856

fix(console): change status component type

---

packages/core/src/oidc/init.ts

try to fix origin issue
pending test in dev

refactor(console): add dev origin to allowed CORS domain in OIDC

---

packages/console/src/components/TabNav/TabNavLink.module.scss

Fix css font in TabNavLink: font-size -> font
@gao-sun 
LOG-1911
Local tested.

fix(console): tab nav link font

---

packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/Button/SocialLinkButton.module.scss
packages/ui/src/components/Button/SocialLinkButton.tsx
packages/ui/src/components/Button/index.module.scss
packages/ui/src/components/Button/index.test.tsx
packages/ui/src/components/Button/index.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SignIn/index.module.scss
packages/ui/src/pages/SignIn/index.tsx

Add button components
Design Reference: https://www.figma.com/file/I5g12dQOLjWWbLLO77QKIn/Product-Design?node-id=1533%3A13765
Primary:
Secondary:
Social:
LOG-1768
LOG-1769
LOG-1770
UT case added test locally

feat(ui): add button components

---

packages/console/src/components/AppContent/components/Sidebar/components/Item/index.module.scss

- adjust padding
- add hover state

refactor(console): update sidebar styles

---

packages/core/src/connectors/index.test.ts

**( PR Order: #413 → #405 )**
- test(core): connectors
- test packages/core/src/connectors/index.ts
LOG-1921
---
@logto-io/eng

test(core): connectors

---

packages/console/src/pages/ApiResourceDetails/index.module.scss
packages/console/src/pages/ApiResourceDetails/index.tsx

fix(console): operation button align in api resource detail
None.
before fix:
after fix:

fix(console): operation button align in api resource detail

---

packages/console/src/pages/ApiResources/index.tsx

fix(console): api resource table data style
Need to align the data with the header.
None.

fix(console): api resource table data style

---

packages/console/src/components/Card/index.module.scss
packages/console/src/components/ModalLayout/index.module.scss
packages/console/src/components/ModalLayout/index.tsx
packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.module.scss
packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.tsx
packages/console/src/scss/modal.module.scss

feat(console): modal layout
* LOG-1907
padding-top:
padding-bottom:
in the center:

feat(console): modal layout

---

.vscode/scss.code-snippets
packages/console/src/components/ItemPreview/index.module.scss
packages/console/src/components/ItemPreview/index.tsx
packages/console/src/components/ModalLayout/index.module.scss
packages/console/src/pages/ApiResources/components/CreateForm/index.module.scss
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.module.scss
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/UserDetails/components/CreateSuccess.module.scss
packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
packages/console/src/pages/UserDetails/components/DeleteForm.module.scss
packages/console/src/pages/UserDetails/components/DeleteForm.tsx
packages/console/src/pages/UserDetails/components/ResetPasswordForm.tsx
packages/console/src/pages/Users/components/CreateForm/index.module.scss
packages/console/src/pages/Users/components/CreateForm/index.tsx
packages/console/src/scss/_dimensions.scss
packages/console/src/scss/_underscore.scss
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

refactor(console): refactor modals with modallayout
* LOG-1934
Tested in Admin Console.

refactor(console): refactor modals with modallayout

---

packages/console/src/pages/UserDetails/components/UserConnectors.module.scss
packages/console/src/pages/UserDetails/components/UserConnectors.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/types/user.ts

Add component "UserConnectors", to show user's connected connectors in details page.
The API endpoint is not available now, see LOG-1960
LOG-1917

feat(console): user details connectors

---

packages/console/src/pages/ConnectorDetails/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Add feature: delete connector. Though the label is "delete", but actually it will be "disabled".
LOG-1869

feat(console): delete connector

---

packages/console/src/components/ModalLayout/index.tsx
packages/console/src/components/RadioGroup/Radio.tsx
packages/console/src/components/RadioGroup/index.module.scss
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorRow.tsx
packages/console/src/pages/Connectors/components/SetupModal.module.scss
packages/console/src/pages/Connectors/components/SetupModal.tsx
packages/console/src/pages/Connectors/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Add connector selection modal, this is used for adding or replacing connector.
LOG-1725

feat(console): add connector

---

packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/queries/sign-in-experience.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts

fix(core): missing some commits
LOG-1941

fix(core): missing some commits

---

packages/console/src/components/Table/ItemPreviewLoading.module.scss
packages/console/src/components/Table/ItemPreviewLoading.tsx
packages/console/src/components/Table/TableLoading.module.scss
packages/console/src/components/Table/TableLoading.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/Connectors/index.tsx
packages/console/src/pages/Users/index.tsx

Add table loading component.
LOG-1968

feat(console): table loading component

---

packages/console/src/pages/ApplicationDetails/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

feat(console): save changes in application detail page
LOG-1678

feat(console): save changes in application detail page

---

packages/console/src/components/Button/index.module.scss

Switch `hover` and `pressed` effects. Add background color on mouse hover
[LOG-1980](https://linear.app/silverhand/issue/LOG-1980/refactor-plain-button-styles)

refactor(console): minor adjustments made to plain button styles

---

packages/core/src/queries/connector.test.ts
packages/core/src/queries/connector.ts

- feat(core): order connectors by enabled desc, id asc
- See Slack [thread](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1647588486594879)
LOG-1945
---
@logto-io/eng

feat(core): order connectors by enabled desc, id asc

---

packages/console/src/pages/UserDetails/index.tsx

As per discussion in LOG-1928, refactor form typing's with `Nullable`.
LOG-1928
@logto-io/eng

refactor(console): use nullable in form type

---

packages/console/src/components/Table/TableEmpty.tsx
packages/console/src/components/Table/TableError.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/Connectors/index.tsx
packages/console/src/pages/UserDetails/components/UserConnectors.tsx
packages/console/src/pages/Users/index.tsx

Remove all `colSpan=0` statements, because is not safe.
LOG-1974
Local tested.

refactor(console): remove zero-colspan

---

packages/console/src/utilities/markdown.ts

Update code comments in markdown util
N/A

chore(console): update code comments in markdown util

---

packages/core/src/connectors/index.test.ts
packages/core/src/connectors/index.ts
packages/core/src/lib/social.ts
packages/core/src/routes/session.test.ts

- fix(core): error message interpolation
---
e.g.
```ts
connector: {
not_found: 'Cannot find any available connector for type: {{type}}.',
```
Wrong usage:
```ts
new RequestError('connector.not_found', { type })
```
Correct usage:
```ts
new RequestError({ code: 'connector.not_found', type });
```
LOG-1921

fix(core): error message interpolation

---

packages/core/src/connectors/wechat/index.test.ts
packages/core/src/connectors/wechat/index.ts

Fix WeChat web response code and related UTs.
UTs passed.

fix(core): fix WeChat web response code and related UTs

---

packages/ui/src/apis/index.test.ts
packages/ui/src/apis/register.ts
packages/ui/src/apis/sign-in.ts

Add password less related api
LOG-1790
align with core/router
ut added
@logto-io/eng

feat(ui): add password less related api

---

packages/core/src/connectors/wechat/index.test.ts

Fix the WeChat connector testing bug where the request is not mocked and resulted in a timeout.
Passed UTs.

fix(core): did not mock test request which results in a timeout

---

packages/core/package.json
packages/core/src/utils/regex.ts
packages/schemas/package.json
packages/schemas/src/foundations/jsonb-types.ts
pnpm-lock.yaml

Update Zod type guards of sign in exp jsonb fields
LOG-2058
Next up: will test it in #391

feat(schemas): zod type guards of sign-in experience jsonb fields

---

packages/core/src/routes/connector.test.ts
packages/core/src/routes/connector.ts

Check connector config before enabling.
LOG-2044
Passed UTs.

feat(core): validate connector config before enabling

---

packages/console/src/pages/Users/index.module.scss
packages/console/src/pages/Users/index.tsx
packages/console/src/scss/normalized.scss
packages/console/src/scss/table.module.scss

Table can now be given a fixed height, the content is scrollable and the table header is fixed when scrolling.
LOG-1975

feat(console): table scroll

---

packages/core/src/lib/sign-in-experience.test.ts
packages/core/src/lib/sign-in-experience.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts
packages/core/src/utils/mock.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Validate sign-in experience branding and terms of use
#477 → #475 → #480 → …
LOG-2064

feat(core,phrases): validate sign-in experience branding and terms of use

---

packages/core/src/lib/sign-in-experience.test.ts
packages/core/src/lib/sign-in-experience.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts
packages/core/src/utils/mock.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Validate there must be one and only one primary sign-in method
#477 → #475 → #480 → …
LOG-2059

feat(core,phrases): validate there must be one and only one primary sign-in method

---

packages/console/src/pages/ApiResourceDetails/index.module.scss
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApplicationDetails/index.module.scss
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/UserDetails/index.module.scss
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/scss/details.module.scss

Align styles for all details page(userDetails, applicationDetails...), and add a sticky(floating) footer that will always present on view window.
You can preview this effect by checking the following GIF.
LOG-1894

feat(console): sticky footer in details page

---

packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/components/ImagePlaceholder/index.tsx
packages/console/src/components/ItemPreview/index.module.scss
packages/console/src/components/ItemPreview/index.tsx
packages/console/src/components/Table/ItemPreviewLoading.module.scss
packages/console/src/pages/ApiResources/index.module.scss
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.module.scss
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/Connectors/index.module.scss
packages/console/src/pages/Connectors/index.tsx
packages/console/src/pages/Users/index.module.scss
packages/console/src/pages/Users/index.tsx
packages/console/src/scss/_colors.scss
packages/console/src/scss/_underscore.scss
packages/console/src/scss/normalized.scss
packages/console/src/scss/table.module.scss

We have a new design on table(aka resource list), [Figma: AC Design System](https://www.figma.com/file/bcSRcMyKEQc0c7k7QfP9fG/%F0%9F%AA%90-%5BWeb%5D-AC-Design-System?node-id=77%3A741). Adjust styles to match it.
LOG-2050
compact:
default:

fix(console): adjust styles on table

---

packages/core/src/lib/sign-in-experience.test.ts
packages/core/src/lib/sign-in-experience.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts
packages/core/src/utils/mock.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Validate sign-in methods with enabled connectors
#477 → #475 → #480 → …
LOG-2068

feat(core,phrases): validate sign-in methods with enabled connectors

---

packages/console/src/pages/ApplicationDetails/index.tsx

Fix the issue in ApplicationDetails: all FormFields should have a className.

fix(console): add textField class to application details formfields

---

packages/core/src/lib/sign-in-experience.test.ts
packages/core/src/lib/sign-in-experience.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Validate the social sign-in method and social connector IDs
… → #480 → #485 → …
LOG-2069

feat(core,phrases): validate social sign-in method with social connector IDs

---

.github/workflows/upload-annotations.yml
.gitignore
merge-eslint-reports.js
packages/console/package.json
packages/core/package.json
packages/phrases/package.json
packages/schemas/package.json
packages/ui/package.json

ci: upload eslint annotations

---

packages/console/src/pages/Users/index.tsx

Store filters value (currently only UserManagement page) in url search params, for better experience with browser's native features.
`http://localhost:3001/console/users?search=wang&page=2`
LOG-2034
Local tested.

feat(console): store filters in url search params

---

packages/ui/package.json
packages/ui/src/App.tsx
packages/ui/src/apis/utils.ts
packages/ui/src/containers/PasscodeValidation/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/pages/Passcode/index.test.tsx
packages/ui/src/pages/Passcode/index.tsx
packages/ui/src/pages/Register/index.test.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SecondarySignIn/index.test.tsx
packages/ui/src/pages/SecondarySignIn/index.tsx
packages/ui/src/types/index.ts
pnpm-lock.yaml

Update the react-router version, and optimized some of the routing logic.
1. extract global type UserFlow and SignInMethod
2. replace `useHistory` with `useNavigate`
LOG-2078
ut case added
@logto-io/eng

refactor(ui): update react router version

---

packages/core/src/routes/sign-in-experience.test.ts

Test GET /sign-in-exp
LOG-2045

test(core): get sign-in experience

---

packages/core/src/routes/sign-in-experience.branding.guard.test.ts
packages/core/src/routes/sign-in-experience.guard.test.ts
packages/core/src/utils/mock.ts

Test sign-in-methods and social-connector-ids guards
**Since `sign-in-experience.guard.test.ts` is too long (more than 300 lines), split it into `sign-in-experience.guard.test.ts` and `sign-in-experience.branding.guard.test.ts`**
LOG-2096

test(core): guard sign-in methods and social connector ids

---

packages/ui/src/containers/UsernameSignin/index.tsx

display request error message for now
test locally
@logto-io/eng cc: @IceHe

fix(bug): display request message for now

---

packages/console/package.json
packages/ui/package.json

change hmr port to enable this feature according to https://github.com/parcel-bundler/parcel/issues/6994
hmr works

fix: enable hmr in parcel projects

---

packages/console/src/pages/ApiResources/index.module.scss
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.module.scss
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/Users/index.tsx

* add paginations for applications and resources
* show paginations only if the total data count is bigger than the page size
None.
Tested in the admin console.

feat(console): add paginations for applications and resources

---

packages/ui/src/assets/icons/loading.svg
packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/AppContent/index.tsx
packages/ui/src/components/Icons/LoadingIcon.tsx
packages/ui/src/components/Icons/index.ts
packages/ui/src/components/LoadingLayer/index.module.scss
packages/ui/src/components/LoadingLayer/index.tsx
packages/ui/src/containers/CreateAccount/index.test.tsx
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/PasscodeValidation/index.test.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/UsernameSignin/index.test.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/hooks/use-api.ts

Add global page level loading layer
add page level loading layer
LOG-2091
test locally
@logto-io/eng

feat(ui): add page level loading layer

---

packages/console/src/components/ImagePlaceholder/index.module.scss
packages/console/src/components/ImagePlaceholder/index.tsx
packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss

Add 8px padding to placeholder image.

fix(console): fix placeholder image padding

---

packages/docs/docs/integrate-sdk/_category_.json
packages/docs/docs/integrate-sdk/react/_category_.json
packages/docs/docs/integrate-sdk/react/_step-1.mdx
packages/docs/docs/integrate-sdk/react/_step-2.md
packages/docs/docs/integrate-sdk/react/_step-3.md
packages/docs/docs/integrate-sdk/react/_step-4.md
packages/docs/docs/integrate-sdk/react/_step-5.md
packages/docs/docs/integrate-sdk/react/index.mdx
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current.json
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-1.mdx
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-2.md
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-3.md
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-4.md
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-5.md
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/index.mdx

init React SDK get started tutorial
LOG-2117

feat(docs): init React SDK tutorial

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/package.json
packages/ui/src/containers/PasscodeValidation/index.test.tsx
packages/ui/src/containers/PasscodeValidation/index.tsx
packages/ui/src/containers/SignInMethodsLink/index.module.scss
packages/ui/src/containers/SignInMethodsLink/index.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
pnpm-lock.yaml

Implement signin methods link component
Add new dependency `react-string-replace` to replace content in i18n translation text with react component
Update the passcode validation component countdown timer using the  `react-string-replace` as well
Test locally
@logto-io/eng

feat(ui): impelment signin methods links component

---

packages/schemas/src/foundations/jsonb-types.ts

feat(core): validate redirect uris of application
* LOG-2076

feat(core): validate redirect uris of application

---

packages/cli/package.json
packages/cli/src/database.ts
packages/cli/src/index.ts
packages/cli/tsconfig.json
pnpm-lock.yaml

- init CLI package
- implement basic `createTables()` function
LOG-2123
locally

feat(cli): init

---

packages/core/src/oidc/init.ts
packages/core/src/oidc/utils.test.ts
packages/core/src/oidc/utils.ts
packages/schemas/src/foundations/jsonb-types.ts

- Add allowed origins of application in custom OIDC client metadata
- Check CORS origin by application
LOG-2102
LOG-2103
LOG-2104

feat(core,schemas): cors allowed origins

---

packages/ui/src/apis/index.test.ts
packages/ui/src/apis/register.ts
packages/ui/src/apis/sign-in.ts
packages/ui/src/apis/social.ts

Add social apis
Fix some old api path bug
ut case updated
@logto-io/eng

feat(ui): add social apis

---

packages/cli/package.json
packages/cli/src/database.ts
packages/cli/src/include.d/slonik-interceptor-preset.d.ts
packages/cli/src/utilities.ts
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/core/src/__mocks__/index.ts
packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/routes/setting.test.ts
packages/core/src/routes/sign-in-experience.branding.guard.test.ts
packages/schemas/src/db-entries/sign-in-experience.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/index.ts
packages/schemas/src/seeds/index.ts
packages/schemas/src/seeds/resource.ts
packages/schemas/src/seeds/setting.ts
packages/schemas/src/seeds/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql
pnpm-lock.yaml

- implement `seedTables()` in CLI
- update sign in experience schema
- add seeds in schemas package
LOG-2128
LOG-1083
LOG-720
LOG-1294
seed with empty tables succeeded

feat(cli): seed tables

---

packages/cli/package.json
packages/cli/src/database.ts
packages/cli/src/index.ts
pnpm-lock.yaml

implement `createDatabase()` in CLI
LOG-2134
locally, created database

feat(cli): create database

---

packages/docs/package.json

fix(docs): package name

---

packages/cli/package.json
packages/cli/src/commands/database/index.ts
packages/cli/src/commands/database/library.ts
packages/cli/src/commands/database/utilities.ts
packages/cli/src/index.ts
pnpm-lock.yaml

run commands and read options from command line / env
LOG-2139

feat(cli): integrate with command line

---

packages/ui/src/assets/icons/radio-button.svg

fix svg radio box icon fill color on production eng
test locally
@wangsijie

fix(ui): fix svg radio box icon fill color

---

packages/docs/docs/integrate-sdk/react/_step-1.mdx
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/integrate-sdk/react/_step-1.mdx

group installation methods to save space

refactor(docs): optimize React get started

---

packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts

add sample sign-in-settigns api for client use
UT case added 
@logto-io/eng

feat(core): add sign-in-settings api for client use

---

packages/console/src/App.tsx
packages/console/src/pages/SignInExperience/index.module.scss
packages/console/src/pages/SignInExperience/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Init sign in experience page.
LOG-1728

feat(console): init sign in exp page

---

packages/core/src/__mocks__/index.ts
packages/core/src/oidc/utils.test.ts
packages/core/src/oidc/utils.ts
packages/core/src/routes/application.test.ts
packages/core/src/routes/application.ts
packages/schemas/src/foundations/jsonb-types.ts

Validate custom client metadata when POST /applications or PATCH /applications/:id
LOG-2103
LOG-1885

feat(core): validate custom client metadata when post or patch application

---

packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/core/package.json
packages/core/src/__mocks__/index.ts
packages/core/src/routes/application.test.ts
packages/core/src/routes/application.ts
packages/schemas/package.json
packages/schemas/src/types/application.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/oidc-config.ts
pnpm-lock.yaml

feat(core): add oidc config to the response of application apis
* LOG-1908
UT & Tested in the admin console.

feat(core): add oidc config to the response of application apis

---

packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
packages/console/src/pages/SignInExperience/components/TermsForm.tsx
packages/console/src/pages/SignInExperience/components/index.module.scss
packages/console/src/pages/SignInExperience/index.module.scss
packages/console/src/pages/SignInExperience/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Implement form fields in tab "Experience".
In order to make PR more clear, form field components will be implemented in other PRs, you can see those TODOs in code comment.
LOG-1729

feat(console): add experience form fields

---

packages/core/src/routes/application.test.ts
packages/core/src/routes/application.ts

Refactor POST /applications
LOG-1885

refactor(core): post application

---

packages/console/src/components/Switch/index.module.scss
packages/console/src/components/Switch/index.tsx
packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
packages/console/src/pages/SignInExperience/components/TermsForm.tsx
packages/console/src/pages/SignInExperience/index.tsx

Implement toggle switch component.
LOG-2152

feat(console): toggle switch

---

packages/core/src/connectors/alipay/config-template.md
packages/core/src/connectors/aliyun-dm/config-template.md
packages/core/src/connectors/aliyun-sms/config-template.md
packages/core/src/connectors/facebook/config-template.md
packages/core/src/connectors/github/config-template.md
packages/core/src/connectors/google/config-template.md
packages/core/src/connectors/wechat/config-template.md

Add connector config examples.
LOG-2150
UTs.

feat(core): add connector config examples

---

packages/console/src/components/RadioGroup/Radio.tsx
packages/console/src/components/RadioGroup/index.module.scss
packages/console/src/components/RadioGroup/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/Applications/components/LibrarySelector/index.tsx
packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
packages/console/src/pages/Applications/components/TypeDescription/index.tsx
packages/console/src/pages/SignInExperience/components/BrandingForm.tsx

Implement component: plain radio
LOG-2153

feat(console): plain radio

---

.github/workflows/update-pr-metadata.yml

- rename file and job
- upgrade run steps to add size label
CI

ci: update workflow

---

packages/console/package.json
packages/ui/package.json

Reference: 
- Slack [thread](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1649998840645499)
- https://parceljs.org/features/development/#caching
LOG-2192

chore(console,ui): parcel build --no-cache

---

packages/schemas/src/foundations/jsonb-types.ts

Extract sign-in method key
See #554 [comment](https://github.com/logto-io/logto/pull/554#discussion_r851069986)
LOG-1730

refactor(schemas): extract sign-in method key

---

packages/core/src/middleware/koa-error-handler.test.ts
packages/core/src/middleware/koa-spa-proxy.test.ts
packages/core/src/middleware/koa-user-log.test.ts

Clear mocks after each test
LOG-1925

refactor(core): clear mocks after each test

---

packages/ui/src/apis/index.test.ts
packages/ui/src/apis/register.ts
packages/ui/src/apis/sign-in.ts
packages/ui/src/apis/utils.ts
packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx

api method renaming
UT passed
@logto-io/eng

refactor(ui): api method renaming

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/lib/sign-in-experience.test.ts
packages/core/src/lib/sign-in-experience.ts
packages/core/src/middleware/koa-role-guard.test.ts
packages/core/src/routes/sign-in-experience.guard.test.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/seeds/sign-in-experience.ts
packages/schemas/src/types/user.ts

Make all enum keys pascalcase
None

refactor(core,schemas): pascalcase enum keys

---

packages/schemas/tables/applications.sql
packages/schemas/tables/passcodes.sql
packages/schemas/tables/resources.sql
packages/schemas/tables/settings.sql
packages/schemas/tables/sign_in_experiences.sql
packages/schemas/tables/users.sql

Conform ID length to 21
- Except user id (length 12)
LOG-2181
LOG-2182

refactor(schemas): conform id length

---

packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
packages/console/src/pages/SignInExperience/components/TermsForm.tsx
packages/console/src/pages/SignInExperience/components/index.module.scss
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/SignInExperience/types.ts
packages/console/src/pages/SignInExperience/utilities.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Add form fields for "sign in methods" tab in page: sign in experience.
Please notice that there are still many issues in this page, this PR focused on "setup" of fields and data models.
LOG-1730

feat(console): sign-in-methods form setup

---

packages/console/package.json
packages/console/src/components/ColorPicker/index.module.scss
packages/console/src/components/ColorPicker/index.tsx
packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
pnpm-lock.yaml

Add component: color picker.
LOG-1729

feat(console): color picker

---

packages/schemas/src/db-entries/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql

Remove the unnecessary and wrong default values from sign-in experience schema
LOG-2198

fix(schemas): remove wrong default values from sign-in experience schema

---

packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/core/package.json
packages/core/src/__mocks__/index.ts
packages/core/src/routes/application.test.ts
packages/core/src/routes/application.ts
packages/schemas/src/types/application.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/oidc-config.ts
pnpm-lock.yaml

fix(core): revert add oidc config to application response
None.
UT

fix(core): revert add oidc config to application response

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/containers/PasscodeValidation/index.test.tsx
packages/ui/src/containers/PasscodeValidation/index.tsx

fix: typos in phrases

---

packages/docs/docusaurus.config.js
packages/docs/static/CNAME

update config for GitHub pages deployment
https://github.com/logto-io/website-docs
https://docs.logto.io

docs: update config for deployment

---

packages/console/src/components/CardTitle/index.module.scss
packages/console/src/components/TextInput/index.module.scss
packages/console/src/pages/UserDetails/components/UserConnectors.module.scss
packages/console/src/pages/UserDetails/components/UserConnectors.tsx
packages/console/src/pages/UserDetails/index.module.scss
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Fix the following issues:
1. remove focus effect on readOnly text input.
2. allow multi-line text on subtitle.
3. user connectors: move empty text out of table.
4. user details: hide readonly fields with empty value.
5. add unnamed placeholder.
All changes to UI are aligend with latest design.

fix(console): fix issues on user management

---

packages/console/src/pages/UserDetails/components/RoleSelect.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Add user role select in UserDetails. For v1, we only support `admin` role, so hard code for now.
LOG-2229

feat(console): user role select

---

packages/core/src/queries/log.ts

#587 (current) → #588 → #590
Insert a log into DB
LOG-2239
No need for now

feat(core): insert log into DB

---

packages/core/src/app/init.test.ts
packages/core/src/app/init.ts
packages/core/src/middleware/koa-log.test.ts
packages/core/src/middleware/koa-log.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/log.ts

#588 → #590 (current) → #591
Add new koa-log middleware
LOG-2201

feat(core,schema): new koa-log middleware

---

.github/workflows/main.yml

to enable those pull with non-master target branch
CI

ci: trigger main workflow on all pull requests

---

packages/console/src/components/ActionMenu/index.tsx
packages/console/src/components/Dropdown/DropdownItem.module.scss
packages/console/src/components/Dropdown/DropdownItem.tsx
packages/console/src/components/Dropdown/index.module.scss
packages/console/src/components/Dropdown/index.tsx
packages/console/src/components/Dropdown/use-position.ts
packages/console/src/components/Select/index.module.scss
packages/console/src/components/Select/index.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
packages/console/src/pages/SignInExperience/constants.ts
packages/console/src/scss/_colors.scss

Add form component: Select.
LOG-2191

feat(console): select

---

packages/schemas/tables/logs.sql

See Slack [thread](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1650468086844649)
LOG-2147

chore(schemas): conform sql style

---

packages/ui/src/App.tsx
packages/ui/src/components/Input/index.module.scss
packages/ui/src/i18n/init.ts
packages/ui/src/utils/sign-in-experience.test.ts
packages/ui/src/utils/sign-in-experience.ts

load lanuage settings from sign-in-experience settings
LOG-2164
test locally
@logto-io/eng

feat(ui): load lanuage settings from sign-in-experience settings

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/schemas/src/types/log.ts

feat(core,schemas): log sign-in

---

packages/ui/src/containers/CreateAccount/index.tsx

fix(ui): show response error toast

---

packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
packages/ui/src/hooks/use-social.ts
packages/ui/src/include.d/global.d.ts

nativeCallback renaming
Align with SDK update `callbackUriScheme` field name with `callbacLink`
None
UT passed
@logto-io/eng

refactor(ui): nativeCallback renaming

---

renovate.json

to remove default version pin behavior
CI

ci: extends renovate `:preserveSemverRanges` preset

---

packages/console/src/pages/ApiResourceDetails/index.module.scss
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApplicationDetails/index.module.scss
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/UserDetails/index.module.scss
packages/console/src/pages/UserDetails/index.tsx

fix(console): detail top card spacing
* LOG-2189

fix(console): detail top card spacing

---

packages/docs/docs/sdk/Swift/LogtoClient/Classes/LogtoClient.md
packages/docs/docs/sdk/Swift/LogtoClient/Structs/LogtoClient.NotificationObject.md
packages/docs/docs/sdk/Swift/LogtoClient/Structs/LogtoConfig.md
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Swift/LogtoClient/Classes/LogtoClient.md
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Swift/LogtoClient/Structs/LogtoClient.NotificationObject.md
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Swift/LogtoClient/Structs/LogtoConfig.md

renaming docs to align with the latest update in SDK
LOG-2251
N/A

docs: update LogtoClient `clientId` -> `appId`

---

package.json
package.sh
packages/console/package.json
packages/docs/package.json
packages/ui/package.json
pnpm-lock.yaml

- per discussion build and tar logto
- change all dependencies to dev for frontend packages
LOG-2255
tested with [workflow](https://github.com/logto-io/logto/actions/runs/2201317835):
```yml
name: Package
on:
pull_request:
jobs:
package:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Setup Node and pnpm
uses: silverhand-io/actions-node-pnpm-run-steps@v1.1.0
- name: Package
run: ./package.sh
- name: Archive package
uses: actions/upload-artifact@v3
with:
path: /tmp/logto.tar.gz
retention-days: 1
```
the result looks expected
and ok to run locally

chore: add package script

---

packages/cli/package.json
packages/core/package.json
packages/phrases/package.json
packages/schemas/package.json

align node version in `package.json`
- leave `docs` empty since it's maintained by @docusaurus
- leave parcel packages empty since https://github.com/parcel-bundler/parcel/issues/6769
CI

refactor: align node version

---

packages/console/src/components/Checkbox/Icon.tsx
packages/console/src/components/Checkbox/index.module.scss
packages/console/src/components/Checkbox/index.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
packages/console/src/pages/SignInExperience/components/index.module.scss

feat(console): add component checkbox

---

packages/console/src/App.tsx
packages/console/src/components/AppContent/components/Sidebar/index.tsx
packages/console/src/pages/Settings/index.tsx
packages/core/src/__mocks__/index.ts
packages/core/src/routes/setting.test.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/seeds/setting.ts

feat(console): page settings

---

packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.module.scss
packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.tsx
packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/components/CopyToClipboard/index.tsx
packages/console/src/components/Pagination/index.module.scss
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApiResources/index.module.scss
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/Applications/index.module.scss
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/index.module.scss
packages/console/src/scss/_colors.scss

Fix the following issues in AC iterations:
1. LOG-2215
2. LOG-2206
3. LOG-2143
4. LOG-2141

fix(console): ac iterations fixes

---

packages/core/src/oidc/init.test.ts

remove OIDC  useless todo comment, as OICD init file is ignored
@logto-io/eng

fix(core): remove useless todo comment

---

packages/ui/src/components/AppContent/index.module.scss

fix overlay color in dark mode
test locally
@logto-io/eng

fix(ui): fix overlay

---

packages/cli/package.json
packages/connector-types/package.json
packages/console/package.json
packages/core/package.json
packages/jest-config/package.json
packages/phrases/package.json
packages/schemas/package.json
packages/shared/package.json

align `author` in package.json
N/A

chore: align author

---

packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/hooks/use-form.ts
packages/ui/src/utils/field-validations.ts
packages/ui/src/utils/index.ts

Create useForm hook
Refactor all sign-in / register forms using global useForm hooks. Extract common logic and handle the input field update and validation logic universally. 
LOG-2092
ut case passed
test locally
@logto-io/eng

refactor(ui): refactor ui form

---

packages/core/package.json
packages/core/src/middleware/koa-log.test.ts
packages/core/src/middleware/koa-log.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/types/log.ts
pnpm-lock.yaml

Make it type-safer to append log
Reference: https://github.com/TehShrike/deepmerge
LOG-2240
- Support the value type check by the declared key in the log payload
- Support temporary key-value in the log payload

refactor(core,schemas): make it type-safer to log

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/schemas/src/types/log.ts

feat(core,schemas): log register

---

packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/SignInExperience/types.ts
packages/console/src/pages/SignInExperience/utilities.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Add the last form in sign in experience setup: others.
LOG-1731

feat(console): sign in experience setup others tab

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/containers/SignInMethodsLink/index.module.scss
packages/ui/src/containers/SignInMethodsLink/index.tsx
packages/ui/src/pages/SignIn/registry.tsx

Refactor signin method link.
Take an i18n key as its input and render the text with the link dynamically.
Use the i18n embedded list formator to render the list items. 
log-2303
test locally
@logto-io/eng

refactor(ui): refactor signin method link

---

packages/core/src/database/utils.ts
packages/core/src/queries/application.ts
packages/core/src/queries/connector.ts
packages/core/src/queries/resource.ts

add `manyRows()` to avoid throwing error when no entry found
LOG-2261
init with an empty database ok to listen

refactor(core): add `manyRows()` for queries

---

packages/connector-facebook/README.md
packages/connector-facebook/docs/config-template.md
packages/connector-facebook/jest.config.ts
packages/connector-facebook/package.json
packages/connector-facebook/src/constant.ts
packages/connector-facebook/src/index.test.ts
packages/connector-facebook/src/index.ts
packages/connector-facebook/src/mock.ts
packages/connector-facebook/tsconfig.base.json
packages/connector-facebook/tsconfig.build.json
packages/connector-facebook/tsconfig.json
packages/connector-facebook/tsconfig.test.json
pnpm-lock.yaml

Wrap Facebook web connector as a package.
UTs.

feat(core): wrap facebook connector

---

packages/console/src/pages/ApiResourceDetails/index.module.scss
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApplicationDetails/index.module.scss
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/CreateForm/index.tsx
packages/console/src/pages/Settings/index.module.scss
packages/console/src/pages/Settings/index.tsx
packages/console/src/pages/SignInExperience/index.module.scss
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/UserDetails/index.module.scss
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/scss/details.module.scss

Apply new UI design on "save changes footer".
LOG-2144

fix(console): new ui in save changes footer

---

packages/ui/src/apis/api.ts
packages/ui/src/apis/consent.ts
packages/ui/src/apis/register.ts
packages/ui/src/apis/settings.ts
packages/ui/src/apis/sign-in.ts
packages/ui/src/apis/social.ts

update api lang header. Load the Accept-language settings according to the use sign-in experience settings.
test locally
@logto-io/eng

refactor(ui): update api lang header

---

packages/ui/src/apis/index.test.ts

fix(ut): fix ut

---

packages/core/package.json
packages/core/tsconfig.json
packages/jest-config/jest.config.ts

since the latest version of some of deps are ESM only
CI

refactor(core): use esm in core

---

packages/console/src/components/Checkbox/index.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
packages/console/src/pages/SignInExperience/components/index.module.scss

Implement dynamic form for SignInMethods, including several cases when primary method changed.
You can check the [Figma Link](https://www.figma.com/file/iroUuWbeZ9fqcqXNwqYZai/Admin-Console-UI?node-id=589%3A17483) to see details.
LOG-1736
Local tested.

feat(console): dynamic sign in methods form

---

packages/connector-alipay/package.json
packages/connector-alipay/src/index.ts
packages/connector-aliyun-dm/package.json
packages/connector-aliyun-sms/README.md
packages/connector-aliyun-sms/docs/config-template.md
packages/connector-aliyun-sms/jest.config.ts
packages/connector-aliyun-sms/package.json
packages/connector-aliyun-sms/src/constant.ts
packages/connector-aliyun-sms/src/index.test.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-aliyun-sms/src/mock.ts
packages/connector-aliyun-sms/src/single-send-text.test.ts
packages/connector-aliyun-sms/src/single-send-text.ts
packages/connector-aliyun-sms/src/utils.test.ts
packages/connector-aliyun-sms/src/utils.ts
packages/connector-aliyun-sms/tsconfig.base.json
packages/connector-aliyun-sms/tsconfig.build.json
packages/connector-aliyun-sms/tsconfig.json
packages/connector-aliyun-sms/tsconfig.test.json
packages/connector-facebook/package.json
packages/connector-facebook/src/index.test.ts
packages/connector-facebook/src/index.ts
packages/connector-types/package.json
packages/connector-types/src/index.ts
pnpm-lock.yaml

Wrap Aliyun short message service connector as a package.
UTs.

feat(core): wrap aliyun short message service connector

---

packages/connector-github/README.md
packages/connector-github/docs/config-template.md
packages/connector-github/jest.config.ts
packages/connector-github/package.json
packages/connector-github/src/constant.ts
packages/connector-github/src/index.test.ts
packages/connector-github/src/index.ts
packages/connector-github/src/mock.ts
packages/connector-github/tsconfig.base.json
packages/connector-github/tsconfig.build.json
packages/connector-github/tsconfig.json
packages/connector-github/tsconfig.test.json
pnpm-lock.yaml

Wrap Github web connector as a package.
UTs.

feat(core): wrap github connector

---

packages/connector-google/README.md
packages/connector-google/docs/config-template.md
packages/connector-google/jest.config.ts
packages/connector-google/package.json
packages/connector-google/src/constant.ts
packages/connector-google/src/index.test.ts
packages/connector-google/src/index.ts
packages/connector-google/src/mock.ts
packages/connector-google/tsconfig.base.json
packages/connector-google/tsconfig.build.json
packages/connector-google/tsconfig.json
packages/connector-google/tsconfig.test.json
pnpm-lock.yaml

Wrap Google web connector as a package.
UTs.

feat(core): wrap google connector

---

README.md
install.js

- add one-liner bash command for installation
- fix postgres version check
- don't throw error if no postgres found

chore: add one-liner install command

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/hooks/use-api.ts
packages/ui/src/hooks/use-social.ts
packages/ui/src/pages/Callback/index.module.scss
packages/ui/src/pages/Callback/index.tsx

refactor all social sign-in related error handling
1. jump to social register page if 'user.identity_not_exists' error returned
2. Add several new toast messages if state or code is missing in any auth flow
3. redesign the social callback page
test locally
Social register flow need to test manually on the simulator will test later
@logto-io/eng

refactor(ui):  refactor all social sign-in related error handling

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/App.tsx
packages/ui/src/pages/NotFound/index.module.scss
packages/ui/src/pages/NotFound/index.tsx

not found page
LOG-9
test locally
@logto-io/eng

feat(ui): not found page

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/Button/SocialLinkButton.module.scss
packages/ui/src/components/Button/index.module.scss
packages/ui/src/components/ConfirmModal/index.module.scss
packages/ui/src/components/Drawer/index.module.scss
packages/ui/src/components/Input/index.module.scss
packages/ui/src/utils/field-validations.ts
pnpm-lock.yaml

1. Fix validation utils i18n, not pickup latest language settings. Have to break it into different phrases.
2. Update dark more overlay and dialogue color.
3. Fix secondary button fill color  (see above)
4. Make the primary button font color fix white in both dark and primary mode
5. fix the auto-fill font-color 
test locally
@logto-io/eng

fix(ui): ui design review fix

---

packages/jest-config/jest.config.ts
packages/ui/jest.config.ts
packages/ui/src/components/Button/SocialIconButton.tsx
packages/ui/src/containers/CreateAccount/index.test.tsx
packages/ui/src/containers/UsernameSignin/index.test.tsx

Fix some of the ci issues
1. update jest.config file to fix the ky module import exception
2. fix import styles bug
3. fix phrases ut bug
ut test passed

fix(ui): fix ci fail

---

packages/ui/package.json
pnpm-lock.yaml

fix(ui): fix ui i18n package error

---

packages/console/src/App.module.scss
packages/console/src/App.tsx
packages/console/src/components/AppContent/components/Topbar/index.module.scss
packages/console/src/components/AppContent/components/Topbar/index.tsx
packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/AppContent/index.tsx
packages/console/src/components/Drawer/index.module.scss
packages/console/src/consts/index.ts
packages/console/src/icons/Logo.tsx
packages/console/src/pages/Connectors/components/GuideModal/index.module.scss
packages/console/src/pages/Settings/index.tsx
packages/console/src/scss/_colors.scss
packages/console/src/scss/normalized.scss
packages/console/src/scss/table.module.scss
packages/phrases/src/locales/en.ts
packages/schemas/src/foundations/jsonb-types.ts

Integrate dark mode settings
[LOG-2267](https://linear.app/silverhand/issue/LOG-2267/adminconsoles-dark-mode-config)

feat(console): integrate dark mode settings

---

packages/console/src/App.tsx
packages/console/src/i18n/init.ts

We can switch language in Admin Console now.
[LOG-2266](https://linear.app/silverhand/issue/LOG-2266/adminconsoles-language-config)

feat(console): integrate language settings

---

pnpm-lock.yaml

5.3 -> 5.4 due to pnpm 7 upgrade
CI

chore: upgrade lockfile version

---

packages/docs/docs/tutorial/integrate-sdk/android/_category_.json
packages/docs/docs/tutorial/integrate-sdk/android/index.mdx
packages/docs/docs/tutorial/integrate-sdk/react/_category_.json
packages/docs/docusaurus.config.js

docs: android sdk integration guide
* LOG-2277

docs: android sdk integration guide

---

packages/ui/src/scss/_underscore.scss

Remove second attribute in unit scss function
LOG-1666
@logto-io/eng

refactor(ui): remove second attribute in unit scss function

---

packages/core/src/__mocks__/user.ts
packages/core/src/database/insert-into.test.ts
packages/core/src/database/update-where.test.ts
packages/core/src/lib/session.ts
packages/core/src/middleware/koa-slonik-error-handler.test.ts
packages/core/src/oidc/adapter.test.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/tables/users.sql

Save application id that the user first consented
LOG-2308
Pass all existing tests and

feat(core,schemas): save application id that the user first consented

---

packages/core/src/middleware/koa-log.test.ts
packages/core/src/middleware/koa-log.ts
packages/schemas/src/types/log.ts

Log user's IP address and user agent from the request.
LOG-327
- Success
- Error

feat(core,schemas): log IP and user agent

---

packages/console/package.json
packages/console/src/components/DateTime/index.tsx
packages/console/src/pages/Users/index.tsx
packages/core/src/__mocks__/user.ts
packages/core/src/lib/user.test.ts
packages/core/src/lib/user.ts
packages/core/src/queries/user.test.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/src/types/user.ts
packages/schemas/tables/users.sql
pnpm-lock.yaml

Add column lastSignIn in user management. The date format (`YYYY/MM/DD`) is aligend with Guamian.
Thanks for the research work in `timestamptz` of @IceHe 
LOG-2249

feat(console): add column lastSignIn in user management

---

packages/connector-alipay/package.json
packages/connector-aliyun-dm/package.json
packages/connector-aliyun-sms/package.json
packages/connector-facebook/package.json
packages/connector-github/package.json
packages/connector-google/package.json
packages/connector-types/package.json
packages/connector-wechat-native/package.json
packages/connector-wechat/package.json
packages/console/package.json
packages/core/package.json
packages/jest-config/package.json
packages/phrases/package.json
packages/schemas/package.json
packages/shared/package.json
packages/ui/package.json

fix: `lint:report` script

---

packages/console/package.json
packages/console/src/App.tsx
pnpm-lock.yaml

Update React SDK to v0.1.5
* Replace `clientId` with `appId`
* Remove sessionStorage after successful sign-in
* Several bug fixes

chore(console): update react sdk to v0.1.5

---

packages/core/src/env-set/index.ts
packages/core/src/env-set/oidc.ts
packages/core/src/index.ts
packages/docs/docs/tutorial/README.md
packages/docs/docs/tutorial/configuration.md

- docs configuration page
- `HTTPS_CERT` -> `HTTPS_CERT_PATH`
- `HTTPS_KEY` -> `HTTPS_KEY_PATH`
- `TRUSTING_TLS_OFFLOADING_PROXIES` -> `TRUST_PROXY_HEADER`
LOG-2355
looks good

docs: introduction

---

packages/console/src/App.tsx
packages/console/src/components/AppContent/index.tsx

Promote ErrorBoundary to project root level, in order to capture all errors even in routes like `/callback`
[LOG-2339](https://linear.app/silverhand/issue/LOG-2339/promote-errorboundary-to-highest-level)

refactor(console): promote error boundary to highest level

---

packages/console/src/pages/Settings/index.tsx
packages/core/src/__mocks__/index.ts
packages/core/src/database/seed.ts
packages/core/src/env-set/create-pool-by-env.ts
packages/core/src/env-set/index.ts
packages/core/src/queries/setting.test.ts
packages/core/src/routes/setting.test.ts
packages/schemas/src/db-entries/setting.ts
packages/schemas/src/seeds/setting.ts
packages/schemas/tables/settings.sql

Delete custom domain since is not needed in v1.
LOG-2363
Local tested.
@logto-io/eng

fix: delete custom domain

---

packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/NavBar/index.module.scss
packages/ui/src/components/Passcode/index.module.scss
packages/ui/src/containers/CreateAccount/index.module.scss
packages/ui/src/containers/PasscodeValidation/index.module.scss
packages/ui/src/containers/Passwordless/index.module.scss
packages/ui/src/containers/SocialCreateAccount/index.module.scss
packages/ui/src/containers/SocialSignIn/index.module.scss
packages/ui/src/containers/UsernameSignin/index.module.scss
packages/ui/src/pages/Callback/index.module.scss
packages/ui/src/pages/Consent/index.module.scss
packages/ui/src/pages/Passcode/index.module.scss
packages/ui/src/pages/Passcode/index.tsx
packages/ui/src/pages/Register/index.module.scss
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SecondarySignIn/index.module.scss
packages/ui/src/pages/SecondarySignIn/index.tsx
packages/ui/src/pages/SignIn/index.module.scss
packages/ui/src/pages/SocialRegister/index.module.scss
packages/ui/src/pages/SocialRegister/index.tsx
packages/ui/src/scss/_underscore.scss

Refactor page layout and base style
1. fix a page bug as the root element `content` min-height: 100vh. exceed the default window size in ios browser
2. Move the NavBar element out side of the page main wrapper
3. rename `_.mobile-container-width` to `_.container-width` as it may be used in desktop as well
4. extract a page wrapper mixin for all page wrapper element use
test locally
@logto-io/eng

refactor(ui): refactor page layout and base style

---

.vscode/settings.json
packages/core/src/env-set/create-pool-by-env.ts
packages/core/src/env-set/index.ts
packages/core/src/env-set/oidc.ts
packages/core/src/index.ts
packages/docs/docs/tutorial/README.md
packages/docs/docs/tutorial/configuration.md

- init the very first introduction
- configuration doc
- `HTTPS_CERT` -> `HTTPS_CERT_PATH`
- `HTTPS_KEY` -> `HTTPS_KEY_PATH`
- `TRUSTING_TLS_OFFLOADING_PROXIES` -> `TRUST_PROXY_HEADER`
LOG-2343 LOG-2355

docs: init introduction

---

packages/console/src/components/Dropdown/index.module.scss
packages/console/src/pages/Settings/index.module.scss
packages/console/src/pages/Settings/index.tsx
packages/console/src/scss/_colors.scss

Fix small UI issues on Settings page:
1. Apply textField style.
2. Fix shadow, the previous variable is no longer exists.
N/A
Local tested.

fix(console): text field style in settings

---

packages/console/src/pages/Users/components/ApplicationName/index.tsx
packages/console/src/pages/Users/index.tsx
packages/schemas/src/types/user.ts

Add application column in user management
LOG-2248

feat(console): add application column in user management

---

packages/console/src/utilities/regex.ts
packages/core/src/routes/session.test.ts
packages/core/src/utils/regex.ts

refactor(core): guard phone number with digital-only regex
reference: https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1651816775314959
* LOG-2369
UT

refactor(core): guard phone number with digital-only regex

---

packages/schemas/src/foundations/jsonb-types.ts

Add two properties to settings:
1. experienceGuideDone: whether to show guide page on sign in experience.
2. experienceNoticeConfirmed
LOG-1746
Pass UTs.

feat(core): add experience configs

---

packages/console/package.json
packages/console/src/pages/Guide/index.module.scss
packages/console/src/pages/Guide/index.tsx

Adjust admin console code to meet new changes in mdx files from `docs`

refactor(console): align with new mdx content from docs

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
pnpm-lock.yaml

Separate social sign-in API.
LOG-2361
LOG-2362
Passed UTs.

feat(core): separate social sign-in api

---

packages/console/src/components/TextInput/index.module.scss
pnpm-lock.yaml

prevent autofill background color
Before
After:
LOG-2326
test locally 
@logto/eng

fix(console): prevent autofill background color

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Per our discussion, change the column name to "From application" in user management.

fix(console): change application column name

---

packages/console/src/pages/SignInExperience/components/SaveAlert.module.scss
packages/console/src/pages/SignInExperience/components/SaveAlert.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsPreview.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/SignInExperience/utilities.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Add an alert(confirm) modal when user try to modify sign in methods.
LOG-2302

feat(console): sign in methods change alert

---

packages/console/src/scss/_underscore.scss

Remove second param from `unit` mixin

refactor(console): remove second param from 'unit' mixin

---

packages/docs/docs/tutorial/integrate-sdk/README.md
packages/docs/docs/tutorial/integrate-sdk/ios.mdx
packages/docs/docs/tutorial/integrate-sdk/react.mdx

integration guide for iOS SDK
LOG-2156

docs: integrate iOS SDK

---

packages/console/src/pages/SignInExperience/components/ConnectorSetupWarning.tsx
packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
packages/console/src/pages/SignInExperience/types.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Add connector warnings: 
1. When a sign in methods is enabled (primary/secondary), check if the corresponding connectors are enabled, and display a warning when needed.
2. If no social connector is added, show a warning.
LOG-1741

feat(console): connector warnings in sign in methods

---

packages/docs/docs/tutorial/integrate-sdk/components/AppNote.tsx
packages/docs/docs/tutorial/integrate-sdk/components/SignInNote.tsx
packages/docs/docs/tutorial/integrate-sdk/ios.mdx
packages/docs/docs/tutorial/integrate-sdk/react.mdx

- rephrase React SDK integration guide
- extract components for SDK integration guides

docs: rephrase React SDK integration guide

---

packages/ui/src/apis/index.test.ts
packages/ui/src/apis/social.ts
packages/ui/src/hooks/use-social.ts

social sign-in api update. Following core's latest API update
LOG-2167
ut updated
@logto-io/eng

refactor(ui): social sign-in api update

---

packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/AppContent/index.tsx
packages/ui/src/components/ConfirmModal/index.tsx
packages/ui/src/components/Drawer/index.module.scss
packages/ui/src/components/Drawer/index.tsx
packages/ui/src/scss/_basic.scss
packages/ui/src/scss/_colors.scss
packages/ui/src/scss/modal.module.scss

refactor ui style foundations. 
- Clean up and extract color and fonts mixins
- Apply theme styling at the body level
- Apply ReactModel at the body level
log-2378
test locally
@logto-io/eng

refactor(ui): refactor ui style foundations

---

packages/console/src/components/Drawer/index.module.scss
packages/console/src/components/Drawer/index.tsx

Add drawer animation
log-1891
test locally 
@logto-io/eng

feat(console): add drawer animation

---

packages/docs/docs/tutorial/README.md
packages/docs/docs/tutorial/configuration.md

docs: update content

---

.github/workflows/update-pr-metadata.yml

calculate and comment size diff message
CI

ci: add pr size diff check

---

.github/workflows/update-pr-metadata.yml

show detailed size diff in comment
see the comment below

ci: show size diff per file

---

.github/workflows/update-pr-metadata.yml

fix file size diff display bug on multiple files

ci: fix file size diff comment display

---

packages/docs/docs/tutorial/integrate-sdk/android.mdx
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/tutorial/integrate-sdk/android.mdx

* docs: android sdk integration guide (zh_CN)
* update android sdk integration guide
* LOG-2381

docs: android sdk integration guide (zh_CN)

---

packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/Users/components/CreateForm/index.tsx

Add autofocus effect in Modal Form.
LOG-2385
Local tested.

feat(console): autofocus in create modal

---

.github/workflows/update-pr-metadata.yml

to reduce size of the comment when file number is large
CI

ci: add collapse for file diff

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/hooks/use-api.ts

catch request exceptions with no response body
test locally
@logto-io/eng

fix(ui): catch request exceptions with no response body

---

packages/ui/src/pages/SignIn/index.tsx
packages/ui/src/pages/SignIn/registry.tsx

fix(ui): fix typo

---

packages/console/src/components/Alert/index.module.scss
packages/console/src/components/Alert/index.tsx
packages/console/src/pages/SignInExperience/components/GuideModal.module.scss
packages/console/src/pages/SignInExperience/components/GuideModal.tsx
packages/console/src/pages/SignInExperience/components/Welcome.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/foundations/jsonb-types.ts

Implement sign in experience guide.
LOG-1747

feat(console): sign in exp guide

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/components/Divider/index.module.scss
packages/ui/src/components/NavBar/index.module.scss
packages/ui/src/components/NavBar/index.tsx
packages/ui/src/components/Passcode/index.module.scss
packages/ui/src/containers/CreateAccount/index.module.scss
packages/ui/src/containers/PasscodeValidation/index.module.scss
packages/ui/src/containers/Passwordless/index.module.scss
packages/ui/src/containers/SocialCreateAccount/index.module.scss
packages/ui/src/containers/SocialSignIn/index.module.scss
packages/ui/src/containers/UsernameSignin/index.module.scss
packages/ui/src/pages/Callback/index.module.scss
packages/ui/src/pages/Callback/index.tsx
packages/ui/src/pages/Consent/index.module.scss
packages/ui/src/pages/Consent/index.tsx
packages/ui/src/pages/ErrorPage/index.module.scss
packages/ui/src/pages/ErrorPage/index.tsx
packages/ui/src/pages/Passcode/index.module.scss
packages/ui/src/pages/Register/index.module.scss
packages/ui/src/pages/SecondarySignIn/index.module.scss
packages/ui/src/pages/SignIn/index.module.scss
packages/ui/src/pages/SocialRegister/index.module.scss
packages/ui/src/pages/SocialRegister/index.tsx
packages/ui/src/scss/_desktop.scss
packages/ui/src/scss/_mobile.scss
packages/ui/src/scss/_underscore.scss

refactor page level styling for both mobile & desktop;
log-2373
test locally
@logto-io/eng

style(ui): refactor page level styling for both mobile & desktop

---

packages/console/src/pages/ApplicationDetails/components/DeleteForm/index.module.scss
packages/console/src/pages/ApplicationDetails/components/DeleteForm/index.tsx

fix(console): typo

---

packages/console/src/hooks/use-position.ts

refactor(console): use switch-case to make the select aligment logic more readable
N/A
N/A

refactor(console): use switch-case to make the select aligment logic more readable

---

packages/console/src/components/RadioGroup/index.module.scss
packages/console/src/components/Toast/index.module.scss

the old `--shadow-light-s2` and `--light-shadow-s1` have been removed.
N/A
N/A

fix(console): update shadow styles

---

packages/console/src/components/FormField/index.module.scss

Fix tip icon color.
LOG-2410
Local tested.

fix(console): tip icon color

---

packages/core/src/lib/passcode.ts

Expose `connector` and `metadata` from sendPasscode().
LOG-2384
UTs.

feat(core): expose connector and metadata from sendPasscode

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/ui/src/__mocks__/logto.tsx
packages/ui/src/apis/settings.ts
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
packages/ui/src/hooks/use-social.ts
packages/ui/src/pages/Callback/index.tsx
packages/ui/src/types/index.ts
packages/ui/src/utils/sign-in-experience.ts

Add social connector details for `GET /sign-in-settings` API.
LOG-2389
UTs.

feat(core): add socialConnectors details for get sign-in-settings

---

packages/connector-wechat-native/src/constant.ts
packages/core/src/connectors/index.test.ts

Fix wechat native connector target
UTs.

fix(connector-wechat-native): fix wechat-native target

---

packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
packages/ui/src/hooks/use-social.ts
packages/ui/src/hooks/utils.test.ts
packages/ui/src/hooks/utils.ts
packages/ui/src/types/index.ts

Add ui social connector filters
extract the hook utils file
log-2437
add ut case test locally
test locally UT case added
@logto-io/eng

refactor(ui): add ui social connector filters

---

packages/core/src/middleware/koa-log-session.test.ts
packages/core/src/middleware/koa-log-session.ts
packages/core/src/middleware/koa-log.test.ts
packages/core/src/middleware/koa-log.ts
packages/core/src/routes/init.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/schemas/src/types/log.ts

- Log session id and application id from OIDC Interaction
LOG-2323
and all existing tests.

feat(core,schemas): koaLogSession middleware

---

packages/ui/src/components/NavBar/index.module.scss
packages/ui/src/containers/PasscodeValidation/index.module.scss
packages/ui/src/containers/SignInMethodsLink/index.module.scss
packages/ui/src/containers/SocialCreateAccount/index.module.scss
packages/ui/src/pages/ErrorPage/index.module.scss
packages/ui/src/scss/_desktop.scss
packages/ui/src/scss/_mobile.scss

Container level style adjustment
log-2414
test locally 
@logto-io/eng

style(ui): container style adjustment

---

packages/ui/src/scss/_desktop.scss
packages/ui/src/scss/_mobile.scss

Add desktop styling variabled
log-2414
test locally
@logto-io/eng

style(ui): add desktop styling

---

packages/core/src/middleware/koa-log-session.test.ts
packages/core/src/middleware/koa-log-session.ts

Catch and print interaction not found error in `koaLogSession`
LOG-2323

fix(core): catch and print interaction not found error

---

packages/console/src/components/ColorPicker/index.module.scss
packages/console/src/components/ColorPicker/index.tsx

Instead of cover an div to color input, now using native color input, and use pseudo selectors to apply styles.
LOG-2199
Local tested.

fix(console): use native color picker style

---

packages/ui/src/components/BrandingHeader/index.module.scss
packages/ui/src/components/Divider/index.module.scss
packages/ui/src/components/Input/PasswordInput.tsx
packages/ui/src/components/Input/PhoneInput.tsx
packages/ui/src/components/Input/index.module.scss
packages/ui/src/components/Input/index.tsx
packages/ui/src/components/Input/phoneInput.module.scss
packages/ui/src/components/Passcode/index.module.scss
packages/ui/src/components/Passcode/index.tsx
packages/ui/src/components/TextLink/index.module.scss
packages/ui/src/components/Toast/index.module.scss

desktop component style update
1. BrandingHeader
2. Input fields 
3. Textlink font styling
log-2414
test locally
@logto-io/eng

style(ui): rest components style update

---

packages/ui/src/components/AppContent/index.module.scss

add body background color, make sure dark theme is applied to the page background when page bouncing in webview
log-2425
test locally
@logto-io/eng

fix(ui): add body background color

---

packages/ui/src/components/Dropdown/DropdownItem.module.scss
packages/ui/src/components/Dropdown/DropdownItem.tsx
packages/ui/src/components/Dropdown/index.module.scss
packages/ui/src/components/Dropdown/index.tsx
packages/ui/src/components/Icons/MoreSocialIcon.tsx
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.module.scss
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.module.scss
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
packages/ui/src/containers/SocialSignIn/SocialSignInDropdown.module.scss
packages/ui/src/containers/SocialSignIn/SocialSignInDropdown.tsx
packages/ui/src/containers/SocialSignIn/index.ts
packages/ui/src/scss/_desktop.scss
packages/ui/src/utils/sign-in-experience.ts

Add social dropdown list for desktop
Also clean up all the social component styles. Break theme into different CSS module files.
log-2431
test lodally
@logto-io/eng

feat(ui): add social dropdown list for desktop

---

packages/ui/src/__mocks__/logto.tsx
packages/ui/src/components/Button/SocialIconButton.tsx
packages/ui/src/components/Button/SocialLinkButton.tsx
packages/ui/src/components/Button/index.test.tsx
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
packages/ui/src/types/index.ts

Fix connector target and id used in @logto/ui.
UT.

fix(UI): fix connector target and id used in UI

---

packages/console/src/App.tsx

Fix admin console infinite loading issue when user is not authenticated

fix(console): fix infinite loading issue when not authenticated

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/schemas/src/types/log.ts

Log sending passcode with connector id.
LOG-2230

feat(core): log sending passcode with connector id

---

packages/core/src/queries/log.ts
packages/core/src/routes/init.ts
packages/core/src/routes/log.test.ts
packages/core/src/routes/log.ts

Add route `GET /logs`
LOG-2221

feat(core): get /logs

---

packages/core/src/middleware/koa-client-session-guard.ts

fix sign-in not found bug.  
Should return if session found...
test locally
@logto-io/eng

fix(ui): fix sign-in not found bug

---

packages/console/src/components/Transfer/index.module.scss
packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx

Open new tab when clicking "set up more connectors" in sign in experience setup, and fix link styles.
LOG-2453
Local tested.

fix(console): open new tab for setup connectors

---

.github/workflows/integration-test.yml
.vscode/settings.json
packages/integration-tests/jest.config.ts
packages/integration-tests/package.json
packages/integration-tests/src/api.ts
packages/integration-tests/tests/health-check.test.ts
packages/integration-tests/tsconfig.json
packages/integration-tests/tsconfig.test.json
packages/jest-config/package.json
pnpm-lock.yaml

- setup `integration-tests` package to use jest for api tests
- run integration test on every PR
see Checks -> Integration Test

test: setup integration test package

---

packages/core/src/middleware/koa-client-session-guard.ts

disabled session check for preview mode
test locally
@logto-io/eng cc: @wangsijie

fix(core): disabled session check for preview mode

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/ConfirmModal/AcModal.tsx
packages/ui/src/components/ConfirmModal/MobileModal.tsx
packages/ui/src/components/Drawer/index.tsx
packages/ui/src/components/Input/index.module.scss
packages/ui/src/components/Passcode/index.module.scss
packages/ui/src/containers/PasswordlessConfirmModal/index.tsx
packages/ui/src/containers/UsernameSignin/index.module.scss
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/hooks/use-form.ts
packages/ui/src/pages/Passcode/index.tsx
packages/ui/src/scss/modal.module.scss

UI refinement by designer review
1. content updates
2. Fix body scroll on Modal popUp issue. Instead of add new static classname to the body, simply using `ReactModal__Body--open`
3. Fix desktop styling overwrite input focus and error border issue.
4. Fix Invalid credential error message layout.
6. Clear  Invalid credential error message on form submit
7. Fix mobile short device on social list expand page jumping issue. set main body justify-content normal on mobile.
log-2501
test locally
@logto-io/eng

fix(ui): ui refinement

---

packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
packages/console/src/pages/SignInExperience/utilities.ts
packages/core/src/routes/sign-in-experience.branding.guard.test.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/seeds/sign-in-experience.ts

Add dark logo url in sign in experience form.
LOG-2332
Local tested.
@simeng-li

feat(console): dark logo

---

.github/workflows/main.yml
package.json

add `ci:*` scripts for easier local debug
CI

chore: add `ci:*` scripts

---

packages/ui/src/components/AppContent/index.tsx

fix undefined dark-primary-color bug
test locally

fix(ui): fix undefined dark-primary-color bug

---

packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/ConfirmModal/Acmodal.module.scss
packages/ui/src/components/Dropdown/index.module.scss
packages/ui/src/components/LoadingLayer/index.module.scss
packages/ui/src/components/Toast/index.module.scss
packages/ui/src/scss/_desktop.scss
packages/ui/src/scss/_mobile.scss

Some desktop ui component style update
1. set desktop body bg-color color-base, and main content bg-color using surface
2. Adjust dropdown, toast, loading icon color and border style
3. Add border to ACModal
log-2503
test locally, will recheck with designer later
@logto-io/eng

style(ui): some desktop ui component style update

---

packages/console/src/pages/ConnectorDetails/index.tsx

In social connector detail page, the "back" link should go back and switch to social connectors tab.
Local tested.

fix(console): back to social connectors

---

packages/console/src/scss/_colors.scss

Fix the wrong styles applied to shadow-2
None. Guamian asked me to do this :-)

style(console): fix the shadow-2 style

---

packages/console/src/pages/SignInExperience/components/Preview.tsx
packages/ui/src/hooks/use-preview.ts

Add socialConnectors to preview data. @simeng-li 
LOG-2496
Local tested with preview.

fix(console): socialConnectors in preview data

---

packages/ui/src/hooks/use-page-context.ts
packages/ui/src/hooks/use-theme.ts
packages/ui/src/pages/SignIn/index.tsx
packages/ui/src/types/index.ts

Load dark mode logo according to the current theme.
log-2515
test locally
@logto-io/eng

feat(ui): add darkmode logo

---

packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
packages/ui/src/hooks/utils.test.ts
packages/ui/src/hooks/utils.ts
packages/ui/src/include.d/global.d.ts

Rename native supported connctors param name
test locally
@xiaoyijun @gao-sun  cc: @logto-io/eng

refactor(ui): rename native supported connctors param name

---

packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/Button/IconButton.module.scss
packages/ui/src/components/Button/IconButton.tsx
packages/ui/src/components/ConfirmModal/AcModal.tsx
packages/ui/src/components/ConfirmModal/Acmodal.module.scss
packages/ui/src/components/Drawer/index.module.scss
packages/ui/src/components/Drawer/index.tsx
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.module.scss
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.module.scss
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
packages/ui/src/pages/SignIn/index.module.scss
packages/ui/src/scss/_desktop.scss
packages/ui/src/scss/_mobile.scss

web ui refinement
1. Add IconButton to support desktop icon button hover and press style
2. Add border-radius and shadow to desktop main content card
3. Adjust ACModal border-radius
4.  Create Account link should not stick at buttom on desktop
log-2503
log-2560
log-2488
test locally
@logto-io/eng

style(ui): web ui refinement

---

packages/connector-alipay/src/constant.ts
packages/connector-facebook/src/constant.ts
packages/connector-github/src/constant.ts
packages/connector-google/src/constant.ts
packages/connector-wechat-native/src/constant.ts
packages/connector-wechat/src/constant.ts
packages/console/src/hooks/use-connector-groups.ts
packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.module.scss
packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
packages/console/src/types/connector.ts

In sign in experience page's connectors setup, add logo and supported platform icons.
Notice that icon only show in multi-platform connector.
Also, to align with the design, "Sign in with" has been removed from connector's name, @simeng-li you may need to add "sign in with" in social buttons.
LOG-2565

feat(console): connector logo and platform icon

---

packages/core/src/oidc/init.ts
packages/core/src/utils/oidc-provider-event-listener.test.ts
packages/core/src/utils/oidc-provider-event-listener.ts

Add grantErrorListener for logging token exchange error
LOG-325
LOG-2421

feat(core): grantErrorListener for logging token exchange error

---

packages/console/src/pages/SignInExperience/components/GuideModal.module.scss

Fix header background color in sign-in experience guide

style(console): fix header background color in sign-in experience guide

---

packages/core/jest.setup.ts
packages/core/src/env-set/index.ts
packages/core/src/env-set/oidc.ts
packages/core/src/oidc/init.ts
packages/docs/docs/tutorial/configuration.md

add env `OIDC_COOKIE_KEYS` to enable cookie keys customization
LOG-2552
along with localhost sign in

feat(core): cookie keys configuration

---

packages/connector-twilio-sms/README.md
packages/connector-twilio-sms/docs/config-template.md
packages/connector-twilio-sms/jest.config.ts
packages/connector-twilio-sms/package.json
packages/connector-twilio-sms/src/constant.ts
packages/connector-twilio-sms/src/index.test.ts
packages/connector-twilio-sms/src/index.ts
packages/connector-twilio-sms/src/mock.ts
packages/connector-twilio-sms/src/types.ts
packages/connector-twilio-sms/tsconfig.base.json
packages/connector-twilio-sms/tsconfig.build.json
packages/connector-twilio-sms/tsconfig.json
packages/connector-twilio-sms/tsconfig.test.json
packages/core/package.json
packages/core/src/connectors/index.test.ts
packages/core/src/connectors/index.ts
pnpm-lock.yaml

Add twilio sms connector.
LOG-1616
Passed UTs.

feat(connector-twilio-sms): add twilio sms connector

---

packages/core/src/lib/social.ts
packages/core/src/routes/session.ts
packages/core/src/utils/format.test.ts
packages/core/src/utils/format.ts

Add phone number and email mask to the userInfo found in the social auth result
log-2346
ut case added 
@logto-io/eng 
@wangsijie

feat(core): add phone number and email mask

---

packages/connector-types/src/index.ts
packages/connector-wechat-native/src/constant.ts
packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-native/src/index.ts

1. Fix native WeChat connector getAuthorizationUri() return value.
2. Add GetNativeAuthorizationUri type.
LOG-2567
UTs.

feat(connector-types/wechat-native): fix wechat native getAuthUri

---

packages/schemas/src/seeds/resource.ts

refactor(core): update management API indicator

---

packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
packages/ui/src/hooks/utils.test.ts
packages/ui/src/hooks/utils.ts
packages/ui/src/include.d/global.d.ts

Refactor native supported social connectors jsbridge api schema
```
supportedConnector: {
universal: Boolean;
nativeTargets: string[]
}
```
log-2571
log-2563
test locally
UT case updated
@logto-io/eng  @xiaoyijun  @gao-sun

refactor(ui): refactor native supported social connectors jsbridge

---

packages/connector-alipay/tsconfig.test.json
packages/connector-aliyun-dm/tsconfig.test.json
packages/connector-aliyun-sms/tsconfig.test.json
packages/connector-facebook/tsconfig.test.json
packages/connector-github/tsconfig.test.json
packages/connector-google/tsconfig.test.json
packages/connector-sendgrid-mail/tsconfig.test.json
packages/connector-wechat-native/tsconfig.test.json
packages/connector-wechat/tsconfig.test.json
packages/core/tsconfig.test.json
packages/integration-tests/tsconfig.json

to remove the annoying warning since it doesn't matter in tests
it doesn't warn anymore

test: allow JS in tests

---

packages/core/src/oidc/init.ts
packages/core/src/utils/oidc-provider-event-listener.test.ts
packages/core/src/utils/oidc-provider-event-listener.ts
packages/schemas/src/types/log.ts

Add grantRevokedListener for logging token revocation of the access token or the refresh token
LOG-2422

feat(core): grantRevokedListener for logging revocation of access and refresh token

---

packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

fix(core): update role names
* LOG-2595
UT & Test In AC

fix(core): update role names

---

packages/core/src/routes/session.ts
packages/schemas/src/types/log.ts

Remove the passcode object data from the sending passcode logs
See Slack thread [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1653038577833989)
LOG-322

refactor(core,schemas): remove passcode in logs

---

packages/core/src/oidc/init.ts

This reverts commit 9ccda932a45816be2089d3e58c8e91f55b9ecce9.
Reference to https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1653057631960549
N/A
UT

fix(core): revert add custom claims to id token

---

.github/workflows/main.yml

ci: separate main workflow jobs

---

packages/connector-alipay-native/src/constant.ts
packages/connector-alipay/src/constant.ts
packages/connector-aliyun-dm/src/constant.ts
packages/connector-aliyun-sms/src/constant.ts
packages/connector-facebook/src/constant.ts
packages/connector-github/src/constant.ts
packages/connector-google/src/constant.ts
packages/connector-sendgrid-mail/src/constant.ts
packages/connector-twilio-sms/src/constant.ts
packages/connector-wechat-native/src/constant.ts
packages/connector-wechat/src/constant.ts

Add connectors' logo.
LOG-1838
Passed UTs.
Before:
After:

feat(connectors): add logo for connectors

---

packages/connector-alipay-native/src/index.ts
packages/connector-alipay/src/index.ts
packages/connector-aliyun-dm/src/index.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-facebook/src/index.ts
packages/connector-github/src/index.ts
packages/connector-google/src/index.ts
packages/connector-sendgrid-mail/src/index.ts
packages/connector-twilio-sms/src/index.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat/src/index.ts

refactor(connector): connector constructor
Refer to: https://github.com/logto-io/logto/pull/674/#discussion_r860455670
* LOG-2324
UT

refactor(connector): connector constructor

---

packages/connector-facebook/src/constant.ts
packages/connector-github/src/constant.ts
packages/connector-google/src/constant.ts
packages/core/src/connectors/index.test.ts

Change 3 connectors' platform to universal.
LOG-2461
Local tested in web, for native cases, awaiting our bug bash.

fix: connectors platform

---

packages/ui/src/hooks/use-preview.ts
packages/ui/src/hooks/utils.test.ts
packages/ui/src/hooks/utils.ts
packages/ui/src/utils/sign-in-experience.ts

add preview social connectors filter
Since. under preview mode we need to enable all possible native connectors, add a `filterPreviewSocialConnectors` method that does not rely on the nativeSDK injection.
log-2593
test locally
@logto-io/eng

refactor(ui): add preview social connectors filter

---

packages/ui/src/apis/index.test.ts
packages/ui/src/apis/social.ts
packages/ui/src/hooks/use-social.ts

fix social bug， native should redirect to sign-in/callback page
test locally
@xiaoyijun

fix(ui): fix social bug

---

packages/connector-github/src/index.test.ts

test(connector-github): convert `null` to `undefined` in user info response
N/A
UT

test(connector-github): convert `null` to `undefined` in user info response

---

packages/schemas/tables/logs.sql

Create log indices on application id and user id so that we can query by application id or user id faster.
See Slack thread [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1653296975190569)
LOG-2521

feat(schemas): create log indices on application id and user id

---

packages/docs/docs/tutorial/integrate-sdk/README.md
packages/docs/docs/tutorial/integrate-sdk/vue.mdx
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/tutorial/integrate-sdk/components/AppNote.tsx
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/tutorial/integrate-sdk/components/SignInNote.tsx
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/tutorial/integrate-sdk/vue.mdx

Add documentation for Vue SDK integration
[LOG-2674](https://linear.app/silverhand/issue/LOG-2674/add-vue-sdk-integration-guide-in-docs)
N/A

docs: integrate Vue SDK

---

packages/connector-alipay-native/src/index.test.ts
packages/connector-alipay-native/src/index.ts
packages/connector-alipay/src/index.test.ts
packages/connector-alipay/src/index.ts
packages/connector-facebook/src/index.test.ts
packages/connector-facebook/src/index.ts
packages/connector-github/src/index.test.ts
packages/connector-github/src/index.ts
packages/connector-google/src/index.test.ts
packages/connector-google/src/index.ts
packages/connector-types/src/index.ts
packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat/src/index.test.ts
packages/connector-wechat/src/index.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts

Pass random state to native connector SDK.
UTs.

feat(native-connectors): pass random state to native connector sdk

---

packages/core/src/queries/log.ts
packages/core/src/routes/log.test.ts
packages/core/src/routes/log.ts

feat(core): get /logs/:id

---

packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
packages/docs/docs/tutorial/integrate-sdk/react.mdx
packages/docs/docs/tutorial/integrate-sdk/vue.mdx
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/tutorial/integrate-sdk/react.mdx
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/tutorial/integrate-sdk/vue.mdx

Refine React SDK documentation, also add Chinese translation
[LOG-2676](https://linear.app/silverhand/issue/LOG-2676/refine-react-sdk-documentation-content)
N/A

docs: refine react sdk documentation content

---

packages/console/src/pages/ApiResourceDetails/components/DeleteForm/index.tsx
packages/console/src/pages/ApplicationDetails/components/DeleteForm/index.tsx

Improve delete confirm experience on application delete and API delete popup dialogs, by auto focusing resource name input field

refactor(console): improve delete confirm experience by auto focusing input

---

packages/core/src/routes/dashboard.test.ts
packages/core/src/routes/dashboard.ts
packages/core/src/routes/init.ts

Add GET /dashboard/users/total
LOG-942
LOG-2481

feat(core): get /dashboard/users/total

---

packages/console/src/pages/SignInExperience/components/Preview.module.scss

adjust preview ifram size for web.
Local tested

fix(console): adjust preview size

---

packages/console/src/pages/SignInExperience/components/Preview.module.scss

add border and shadow to preview
LOG-2707

fix(console): add border and shadow to preview

---

packages/console/src/components/Status/index.module.scss
packages/console/src/components/Status/index.tsx
packages/console/src/pages/ConnectorDetails/components/ConnectorTypeName/index.module.scss
packages/console/src/pages/ConnectorDetails/components/ConnectorTypeName/index.tsx
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Implement new design of connector details top card.
LOG-1995

feat(console): connector detail top card

---

packages/connector-google/src/index.ts

We do not need this redirect feature in the access token request.
Refer to: https://github.com/sindresorhus/got/blob/5cbcf526b6e7be5e40f1ad137172d7b2b68988da/documentation/2-options.md#followredirect
N/A
UT & Test in sign-in flow

chore(google-connector): remove redundant request options

---

packages/console/package.json
packages/console/src/components/AppContent/index.tsx
packages/console/src/components/AppError/index.module.scss
packages/console/src/components/AppError/index.tsx
packages/console/src/components/SessionExpired/index.module.scss
packages/console/src/components/SessionExpired/index.tsx
packages/console/src/hooks/use-configs.ts
packages/console/src/pages/Callback/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
pnpm-lock.yaml

Improved error handling in admin console:
* Session expired page re-uses AppError component, and now detailed error message is displayed as well.
* Improved full screen error page display logic, now the error screen will be displayed and the app won't hang at loading stage when error occurs.
* Will show error message from oidc provider on callback
* Whenever an error occurs, the swr will not repeatedly retry fetching the setting configs on app init.
* Bump @logto/react SDK to v0.1.11

refactor(console): improve error handling in admin console

---

packages/connector-alipay-native/src/index.test.ts
packages/connector-alipay-native/src/index.ts
packages/connector-alipay/src/index.test.ts
packages/connector-alipay/src/index.ts
packages/connector-apple/src/index.test.ts
packages/connector-apple/src/index.ts
packages/connector-apple/src/types.ts
packages/connector-facebook/src/index.test.ts
packages/connector-facebook/src/index.ts
packages/connector-github/src/index.test.ts
packages/connector-github/src/index.ts
packages/connector-google/src/index.test.ts
packages/connector-google/src/index.ts
packages/connector-types/package.json
packages/connector-types/src/index.ts
packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat-native/src/types.ts
packages/connector-wechat/src/index.test.ts
packages/connector-wechat/src/index.ts
packages/core/src/lib/social.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/ui/src/apis/index.test.ts
packages/ui/src/apis/social.ts
packages/ui/src/hooks/use-social-sign-in-listener.ts
packages/ui/src/utils/index.ts
pnpm-lock.yaml

- update `getAuthorizationUri()` signature to be more precise
- remove `getAccessToken()`
- update `getUserInfo()` signature to support arbitrary data
- change `POST /session/sign-in/social/auth` to support arbitrary data
- update test cases accordingly
- fix wechat native connector issue
to be filled by @darcyYe

refactor: social connectors

---

packages/ui/src/hooks/use-social-callback-handler.ts

fix callback link params for apple
apple callback URL:
```
https://logto.dev/callback/apple-universal#state=V9nQP362jxg&code=c7a41aa37cb8749bf9f00dccec2a4e328.0.rrquy.rG-eoDclanrq3lndI_4mOQ&id_token=eyJraWQiOiJmaDZCczhDIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiaW8ubG9ndG8udGVzdCIsImV4cCI6MTY1Mzk2ODE4MywiaWF0IjoxNjUzODgxNzgzLCJzdWIiOiIwMDEwNDguYWNkNGQzNzdlNDUxNDU5OWI3ZDU4MjdkOGUwOTBkNzAuMDc1OSIsImNfaGFzaCI6InNhbG80OFpnVThRcTNEMmk5cHRRUmciLCJhdXRoX3RpbWUiOjE2NTM4ODE3ODMsIm5vbmNlX3N1cHBvcnRlZCI6dHJ1ZX0.C3PXPuqrA6yO3T3WFVTUgFIRIWgZD7KgUn-yMHFs2j8hpxxivEzSSzNA4cJp97MMrB9jX6TV6gsR50oOkAw6vPoexYYTciC4iBZUa2aPpr8mIYEPdVlzl3fb-lI803ZbkTlZH_u8u7dZqilcihNlDu_Y2AEXxWb_eiZmv__EQmP4gc4QCbba0zWGy7pgr6HvDLG7AwHQnkZo2CXFmz_cHGalFbg92ybTihPtcEyFBTGAkc7rqWB3BHuiEDcoD3yR_S …
```

fix(ui): fix callback link params for apple

---

packages/console/src/pages/Callback/index.tsx

This reverts commit 540812d0605e31247d6bd07a7727449842a28f98.
This fix resolves sign-in failures in admin console

fix: revert "refactor(console): handle user navigates to 'callback' after authenticated"

---

packages/console/src/components/Status/index.module.scss
packages/console/src/consts/connectors.ts
packages/console/src/hooks/use-connector-groups.ts
packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
packages/console/src/pages/Connectors/components/ConnectorRow/index.module.scss
packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
packages/console/src/pages/Connectors/index.tsx
packages/console/src/types/connector.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Rendor connector groups for social connectors.
LOG-2315

feat(console): connector groups table

---

packages/core/src/queries/log.ts
packages/core/src/routes/dashboard.test.ts
packages/core/src/routes/dashboard.ts
packages/shared/src/regex.ts

Add GET /dashboard/users/active?date=${targetDate}
- DAU: Daily Active User
- WAU: Weekly Active User
- MAU: Monthly Active User
Input:
- The target `date` is optional. It defaults to today.
Output:
- e.g. assume the query string is `?date=2022-05-30` or today is 2022-05-30.
```json
{
// DAUs in recent 30 days
"dauCurve": [
{
"date": "2022-05-01",
"count": 55
},
// ……,
{
"date": "2022-05-29",
"count": 80
},
{
"date": "2022-05-30",
"count": 100
}
],
"dau": {
"count": 100, // DAU on target date
// target date [2022-05-30]
"delta": 20, // // DAU on target date - DAU on previous date
// previous date [2022-05-29] 
},
"wau": {
"count": 150, // WAU in recent 7 days
// recent 7 days: [2022-05-24 ~ 2022-05-30]
"delta": 80, // WAU in recent 7 days - WAU in previous 7 days
// previous 7 days: …
```

feat(core,shared): get /dashboard/users/active

---

packages/ui/src/components/Drawer/index.module.scss
packages/ui/src/components/Drawer/index.tsx

fix drawer overflow bug
log-2738
test locally
@logto-io/eng

fix(ui): fix drawer overflow bug

---

packages/core/src/queries/log.ts

Allow empty condition when we're finding the logs
LOG-2528

fix(core): allow empty condition in logs

---

packages/connector-alipay-native/src/index.test.ts
packages/connector-alipay-native/src/index.ts

Fix Alipay Native data guard.
UTs.

fix(connector-alipay-native): fix data guard

---

packages/core/src/queries/log.ts

Order logs by `created_at` desc in GET /logs API
LOG-2528

feat(core): order logs by created_at desc

---

packages/console/src/pages/Users/components/ApplicationName/index.tsx

Since "admin console" is a special app that doesn't exist on database, need to show a fixed name instead of making a request to query the app name.

fix(console): special application name for admin console

---

packages/connector-alipay-native/docs/config-template.json
packages/connector-alipay-native/src/constant.ts
packages/connector-alipay/docs/config-template.json
packages/connector-alipay/src/constant.ts
packages/connector-aliyun-dm/docs/config-template.json
packages/connector-aliyun-dm/src/constant.ts
packages/connector-aliyun-sms/docs/config-template.json
packages/connector-aliyun-sms/src/constant.ts
packages/connector-apple/docs/config-template.json
packages/connector-apple/src/constant.ts
packages/connector-facebook/docs/config-template.json
packages/connector-facebook/src/constant.ts
packages/connector-github/docs/config-template.json
packages/connector-github/src/constant.ts
packages/connector-google/docs/config-template.json
packages/connector-google/docs/config-template.md
packages/connector-google/src/constant.ts
packages/connector-sendgrid-mail/docs/config-template.json
packages/connector-sendgrid-mail/src/constant.ts
packages/connector-twilio-sms/docs/config-template.json
packages/connector-twilio-sms/src/constant.ts
packages/connector-wechat-native/docs/config-template.json
packages/connector-wechat-native/src/constant.ts
packages/connector-wechat/docs/config-template.json
packages/connector-wechat/docs/config-template.md
packages/connector-wechat/src/constant.ts
packages/core/src/__mocks__/connector.ts

Turn `configTemplate.md` files to `configTemplate.json` files for a better AC-end visual experience.
Fix contents according to config guard definition.
LOG-2729
UTs.

chore(connectors): config template md files to json files

---

packages/connector-alipay-native/package.json
packages/connector-aliyun-dm/package.json
packages/connector-aliyun-sms/package.json
packages/connector-apple/package.json
packages/connector-facebook/package.json
packages/connector-github/package.json
packages/connector-google/package.json
packages/connector-sendgrid-mail/package.json
packages/connector-twilio-sms/package.json
packages/connector-types/package.json
packages/connector-wechat-native/package.json
packages/connector-wechat/package.json

Remove default private config from package.json files
LOG-2329
UTs.

chore(connectors): remove default private config from package.json files

---

packages/console/src/pages/Connectors/components/GuideModal/index.tsx
packages/console/src/pages/Connectors/index.tsx

1. When all steps are done, set connector.enabled to true.
2. Button in step 1 should be "done" if only 1 step is available.
3. Fix SMS's setup button function;.
N/A
Local tested.

fix(console): connector guide

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/App.tsx
packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/AppContent/index.tsx
packages/ui/src/components/Button/SocialLinkButton.module.scss
packages/ui/src/components/Button/SocialLinkButton.tsx
packages/ui/src/components/Button/index.test.tsx
packages/ui/src/components/LoadingLayer/index.module.scss
packages/ui/src/components/Toast/index.module.scss
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/PasscodeValidation/index.tsx
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn/index.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn/index.tsx
packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
packages/ui/src/containers/SocialSignIn/SocialSignInList/index.test.tsx
packages/ui/src/containers/SocialSignIn/SocialSignInList/index.tsx
packages/ui/src/containers/SocialSignIn/SocialSignInPopUp/index.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/hooks/use-bind-social.ts
packages/ui/src/hooks/use-social-sign-in-listener.ts
packages/ui/src/hooks/use-social.ts
packages/ui/src/pages/Consent/index.tsx
packages/ui/src/pages/Passcode/index.test.tsx
packages/ui/src/pages/SocialLanding/index.test.tsx
packages/ui/src/pages/SocialRegister/index.test.tsx
packages/ui/src/pages/SocialSignInCallback/index.test.tsx
packages/ui/src/utils/social-connectors.test.ts

Refactor and fix some minor ui issues
1. fix. loading icon and modal z-index issue
2. Only show hidden connectors in the mobile social connector drawer
3. Fix web page UI layout issue under extreme short webview
4. refactor some social-related page path /social/register and /social/landing
5. Update social link button style and content
6. Replace all `location.assign` method with `loction.replace` for after signin redirect. As it should replace current history. 
7. Remove the InvokeSocialSignIn callback method. Hide the popUp right after the button click, no need to await for the request to complete. 
log-2787
log-2786
log-2772
log-2754
log-2776
log-2728
log-2802
test locally
@logto-io/eng

refactor(ui): refactor and fix some minor ui issues

---

packages/connector-apple/src/index.test.ts

test(connector): `getUserInfo` of apple connector
* LOG-2726
UT

test(connector): `getUserInfo` of apple connector

---

packages/core/src/oidc/init.ts

set claims for profile scope and return `customData` in userinfo endpoint
with 'profile' scope:

feat(core): set claims for `profile` scope

---

packages/connector-alipay-native/src/constant.ts
packages/connector-alipay-native/src/index.test.ts
packages/connector-alipay-native/src/index.ts
packages/connector-alipay/src/constant.ts
packages/connector-alipay/src/index.test.ts
packages/connector-alipay/src/index.ts

1. Refactor Alipay Web and Alipay Native connector UTs.
2. Remove unnecessary DB query.
LOG-2744
Passed UTs.

refactor(connector-alipay*): refactor Alipay UTs and pass config into getAccessToken

---

packages/core/src/oidc/init.ts

roles -> role_names
pending dev testing

refactor(core): align `role_names` claim with DB

---

packages/core/src/oidc/init.ts

use snake_case for extra access token claims
none

refactor(core): use snake_case for extra claims

---

packages/console/src/App.tsx
packages/console/src/components/AppBoundary/index.module.scss
packages/console/src/components/AppBoundary/index.tsx
packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/AppContent/index.tsx

Add an `AppBoundary` bootstrap component to load theme and language settings on top level, instead of from inner `AppContent` layer component.

refactor(console): add AppBoundary in admin console

---

packages/console/src/components/TextInput/index.module.scss
packages/console/src/components/TextInput/index.tsx

Fix ac text input
test locally
@wangsijie  cc: @demonzoo @logto-io/eng

fix(ac): fix ac text input

---

packages/connector-aliyun-dm/jest.config.ts
packages/connector-aliyun-dm/package.json
packages/connector-aliyun-dm/tsconfig.json
packages/connector-aliyun-sms/jest.config.ts
packages/connector-aliyun-sms/package.json
packages/connector-aliyun-sms/tsconfig.json
packages/connector-apple/jest.config.ts
packages/connector-apple/package.json
packages/connector-apple/tsconfig.json
packages/connector-sendgrid-mail/jest.config.ts
packages/connector-sendgrid-mail/package.json
packages/connector-sendgrid-mail/tsconfig.json
packages/connector-twilio-sms/jest.config.ts
packages/connector-twilio-sms/package.json
packages/connector-twilio-sms/tsconfig.json
packages/connector-types/package.json
pnpm-lock.yaml

Remove unused `jest-matcher-specific-error` in connector packages.
LOG-2711
UTs.

chore(connectors): remove unused jest-matcher-specific-error in connector

---

packages/core/src/middleware/koa-auth.test.ts
packages/core/src/middleware/koa-auth.ts

Update `roleNames` to `role_names` to resolve 401 errors

fix(core): update roleNames to role_names to resolve 401 errors

---

packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/pages/ApiResourceDetails/index.module.scss
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApplicationDetails/index.module.scss
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/UserDetails/index.module.scss
packages/console/src/pages/UserDetails/index.tsx

In connector details, wrap connector id with CopyToClipboard.
LOG-2840

fix(console): wrap connector id with copytoclipboard

---

packages/console/src/pages/SignInExperience/components/Preview.module.scss
packages/console/src/pages/SignInExperience/components/Preview.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

fix(console): add mobile platform preview description
* LOG-2795

fix(console): add mobile platform preview description

---

packages/core/src/middleware/koa-auth.test.ts
packages/core/src/middleware/koa-auth.ts

prepare for more integration tests
UT

refactor(core): recognize developer id in header

---

packages/demo-app/src/App.tsx
packages/schemas/src/consts/index.ts
packages/schemas/src/index.ts
packages/ui/src/containers/AppNotification/index.test.tsx
packages/ui/src/utils/session-storage.ts

improved demo app UX, will implement i18n in another PR

feat(demo-app): show notification in main flow

---

packages/console/src/pages/UserDetails/components/UserConnectors.module.scss

fix(console): user connector table bottom line
* LOG-2798

fix(console): user connector table bottom line

---

packages/console/src/components/AppContent/components/Sidebar/components/Section/index.module.scss
packages/console/src/components/Dropdown/index.module.scss
packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss
packages/console/src/pages/SignInExperience/components/index.module.scss
packages/console/src/scss/_underscore.scss

fix(console): add letter spacing for sign-in-experience title
* LOG-2797

fix(console): add letter spacing for sign-in-experience title

---

packages/console/package.json
packages/console/src/components/AppContent/components/UserInfo/index.tsx
packages/demo-app/package.json
pnpm-lock.yaml

* Ditch the api/user/:userId usage in UserInfo component, since this API is protected by admin role. Instead, call `fetchUserInfo` SDK method to get user info from OIDC server.
* Bump React SDK to 0.1.14 to have 'profile' as a reserved scope, with which we can have access to user info claims.

refactor(console): replace user api with fetchUserInfo

---

packages/console/src/components/ItemPreview/index.module.scss
packages/console/src/components/ItemPreview/index.tsx
packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx

Implement platform labels in connectors table.
LOG-2819

feat(console): platform label in connectors table

---

packages/ui/src/components/Input/index.module.scss
packages/ui/src/scss/_desktop.scss
packages/ui/src/scss/_mobile.scss

1. Input auto fill style overwrite
2. update background color cording to the latest design.
log-2871
test locally
@logto-io/eng

style(ui): input auto fill style

---

packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat-native/src/types.ts
packages/connector-wechat/src/index.test.ts
packages/connector-wechat/src/index.ts
packages/connector-wechat/src/types.ts

Fix WeChat connectors error handler, comments, and UTs.
LOG-2753
Passed UTs.

chore(connector-wechat*): fix wechat connectors error handler, comments and UTs

---

packages/console/src/components/TextInput/index.tsx
packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
packages/console/src/pages/SignInExperience/components/TermsForm.tsx

fix(console): error message in text input component
N/A
Test in the Admin Console

fix(console): error message in text input component

---

packages/connector-aliyun-dm/src/index.ts
packages/connector-aliyun-dm/src/types.ts
packages/connector-aliyun-sms/src/index.test.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-aliyun-sms/src/single-send-text.ts
packages/connector-aliyun-sms/src/types.ts
packages/connector-aliyun-sms/src/utils.ts
packages/connector-sendgrid-mail/src/index.ts
packages/connector-sendgrid-mail/src/types.ts
packages/connector-twilio-sms/src/index.ts
packages/connector-twilio-sms/src/types.ts

Expose third-party API request error messages.
LOG-2817
UT and test with real malformed inputs.

feat(sms/email-connectors): expose third-party API request error message

---

packages/docs/.gitignore
packages/docs/docusaurus.config.js
packages/docs/package.json
pnpm-lock.yaml

Add API reference page.
- Generate the static html file of API Reference according to the specification `https://logto.dev/api/swagger.json`
- Should put the HTML file in the directory `/static/*` for storing static resources that need to be controlled by Docusaurus.
- [How to link a static HTML file not generated by Docusaurus · Issue #3894 · facebook/docusaurus](https://github.com/facebook/docusaurus/issues/3894)
- Add the link to the static html file: [Navbar link](https://docusaurus.io/docs/api/themes/configuration#navbar-link)
References:
- Redoc: 
- Deploy via CLI: https://redocly.com/docs/redoc/deployment/cli/#redoc-cli-commands
- `redoc-cli build` options: https://github.com/Redocly/redoc/blob/2100b549c0f1d54c95c41fd0d3eb0b6b23deccb1/cli/index.ts#L68
- Docusaurus: 
- Navbar: …

docs: api reference

---

packages/core/src/lib/sign-in-experience.ts
packages/core/src/utils/assert-that.ts
packages/core/src/utils/password.ts

remove a signature of `assertThat` to avoid confusion
UT

refactor(core): remove confusing `assertThat` signature

---

packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/Button/index.module.scss
packages/ui/src/components/Input/PhoneInput.tsx
packages/ui/src/components/LoadingLayer/index.module.scss
packages/ui/src/components/Passcode/index.tsx
packages/ui/src/components/Toast/index.module.scss
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/PasscodeValidation/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/scss/_desktop.scss
packages/ui/src/scss/_mobile.scss

fix some of the bug bash issues:
1. clear the error message when the user clicks on resend passcode
2. on the social bind account flow, for the passwordless signin method, if an account does not exist error returned should not popup the register modal, directly showing the error message instead.
3. fix the toast and loading border issue
4. add auto focus to the sign-in forms
5. remove the auto-fill  props of all the register form inputs
6. add font antialiased
7. adjust button size with fix height 44px
log-2864
test locally
@logto-io/eng

fix(ui): fix some of the bug bash issues

---

packages/console/src/App.tsx
packages/console/src/hooks/use-swr-options.ts

Stop SWR retry on error status 401 and 403.

fix(console): stop swr retry on error 401 and 403

---

packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx

fix(console): select the old primary sign-in method when the primary method change
* LOG-2810

fix(console): select the old primary sign-in method when the primary method change

---

packages/console/src/components/Select/index.tsx
packages/console/src/pages/SignInExperience/components/Preview.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx

Support generic type T in Select component.

refactor(console): support generic type in select component

---

packages/console/src/components/Table/TableEmpty.module.scss
packages/console/src/components/Table/TableError.module.scss
packages/console/src/components/Table/TableError.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/AuditLogs/index.tsx
packages/console/src/pages/Connectors/index.tsx
packages/console/src/pages/Users/index.tsx
packages/console/src/scss/table.module.scss

Improve table error display
Improve table empty display
Before:
After:

refactor(console): table error display

---

packages/core/src/middleware/koa-auth.test.ts

Removed an unnecessary usage of `console.log()`
N/A

refactor(core): remove unnecessary console.log

---

packages/connector-google/README.md

docs: google universal connector
* LOG-2620
N/A

docs: google universal connector

---

packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

Refer to: https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1654758149111489
* LOG-2892
UT

refactor(core): remove unused `/users/:userId/custom-data` APIs

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts

Remove the unnecessary check on `password` in the route of registering with username and password.
Remove unused route of checking the existence of a `username` and corresponding UTs.
UTs.

feat(core): remove unnecessary variable check and unused route

---

packages/console/package.json
packages/console/src/pages/Callback/index.tsx
packages/demo-app/package.json
packages/demo-app/src/App.tsx
packages/demo-app/src/Callback.tsx
pnpm-lock.yaml

* Bump React SDK to 0.1.15
* Use callback function instead of a `returnToPageUrl` in `useHandleSignInCallback` hook

refactor: bump react sdk 0.1.15 and use callback function instead of url

---

packages/connector-alipay-native/src/index.test.ts
packages/connector-alipay-native/src/index.ts
packages/connector-alipay-native/src/types.ts
packages/connector-alipay/src/index.test.ts
packages/connector-alipay/src/index.ts
packages/connector-alipay/src/types.ts
packages/connector-aliyun-dm/src/index.test.ts
packages/connector-aliyun-dm/src/index.ts
packages/connector-aliyun-dm/src/single-send-mail.ts
packages/connector-aliyun-dm/src/types.ts
packages/connector-aliyun-dm/src/utils.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-facebook/src/index.test.ts
packages/connector-facebook/src/index.ts
packages/connector-facebook/src/types.ts
packages/connector-github/src/index.test.ts
packages/connector-github/src/index.ts
packages/connector-github/src/types.ts
packages/connector-google/src/index.test.ts
packages/connector-google/src/index.ts
packages/connector-google/src/types.ts
packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat-native/src/types.ts
packages/connector-wechat/src/index.test.ts
packages/connector-wechat/src/index.ts
packages/connector-wechat/src/types.ts

Use Zod guard instead of got generics.
Elaborate connector info.
Fix UTs.
LOG-2157
LOG-2688
LOG-2863
UTs, tested Alipay, Aliyun and WeChat locally. Other connectors are not quite convenient to test locally.

refactor(connectors): use zod guard instead of got generic and elaborate error info

---

packages/connector-github/package.json
packages/connector-github/src/index.test.ts
packages/connector-github/src/index.ts
pnpm-lock.yaml

Fix the way of parsing Github `getAccessToken` response.
UTs.

fix(github): fix the way of parsing github getAccessToken response

---

packages/console/src/App.tsx

Revert lazy loading in Admin Console temporarely, for we have noticed a few user experience issues

refactor(console): revert ac lazy loading

---

packages/ui/src/utils/social-connectors.test.ts
packages/ui/src/utils/social-connectors.ts

Add native sdk guard logic.
Per our offline sync add some social connectors guard logic on the native SDK injection methods.
1. Under native webview. If no `nativeSDK.getPostMessage` method is found, should filter out all social connectors, as the user may not be able to invoke any connectors through the native SDK. 
2. Under native webview.  in no `nativeSDK.callbackLink` settings are found, should filter out all universal connectors, as the user may not be able to redirect back to the current app once jumped to the social connector's signin page. 
log-2576
ut case added
@logto-io/eng

feat(ui): add native sdk guard logic

---

packages/console/src/pages/Dashboard/index.tsx

Handle dashboard errors in general: if any API request occurs error, stop rendering page, show a page-level error box.
LOG-2808

feat(console): error handling in dashboard

---

packages/console/package.json
packages/console/src/components/AppContent/components/Sidebar/index.module.scss
packages/console/src/components/AppContent/components/UserInfo/index.tsx
packages/console/src/components/AppContent/components/UserInfoSkeleton/index.module.scss
packages/console/src/components/AppContent/components/UserInfoSkeleton/index.tsx
packages/console/src/components/ApplicationName/index.tsx
packages/console/src/components/CodeEditor/index.module.scss
packages/console/src/components/CodeEditor/index.tsx
packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/components/UserName/index.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/ConnectorDetails/components/SenderTester/index.module.scss
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
packages/console/src/pages/Connectors/index.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/UserDetails/components/UserConnectors.module.scss
packages/console/src/pages/UserDetails/components/UserConnectors.tsx
packages/console/src/pages/Users/index.tsx

Misc improvements and trivial UI style fixes in admin console, including paddings, margins, button sizes adjustments, etc.

fix(console): misc improvements and ui fixes

---

packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx

Make the whole row clickable in connector table.
LOG-2854

fix(console): connector row clickable

---

packages/console/src/pages/Applications/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Update `Client ID` to `App ID` in admin console

chore(console): update Client ID to App ID

---

packages/connector-alipay-native/package.json
packages/connector-alipay/package.json
packages/connector-aliyun-dm/package.json
packages/connector-aliyun-sms/package.json
packages/connector-apple/package.json
packages/connector-facebook/package.json
packages/connector-github/package.json
packages/connector-google/package.json
packages/connector-sendgrid-mail/package.json
packages/connector-twilio-sms/package.json
packages/connector-types/package.json
packages/connector-wechat-native/package.json
packages/connector-wechat/package.json
packages/console/package.json
packages/core/package.json
packages/demo-app/package.json
packages/phrases/package.json
packages/schemas/package.json
packages/shared/package.json
packages/ui/package.json

Remove `npx only-allow pnpm` from all sub-packages
Also re-formatted package.json in all connectors, in order to use 2 tab spaces instead of 4
N/A

chore: remove only-allow pnpm from all sub-packages

---

packages/console/src/components/AppContent/components/UserInfo/index.module.scss
packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss

Update hover and focus colors for the following two components in AC:
* GetStartedProgress
* UserInfo
Use `--color-hover-variant` and `--color-focus-variant` colors

style(console): update hover and focus background colors of topbar items

---

packages/integration-tests/jest.config.ts
packages/integration-tests/jest.setup.js
packages/integration-tests/package.json
packages/integration-tests/src/api.ts
packages/integration-tests/src/constants.ts
packages/integration-tests/src/logto-context.ts
packages/integration-tests/src/utils.ts
packages/integration-tests/tests/username-password-flow.test.ts
packages/integration-tests/tsconfig.json
pnpm-lock.yaml

test(integration): username and password flow
* LOG-3022

test(integration): username and password flow

---

packages/integration-tests/tests/swagger-check.test.ts

Check whether `GET /api/swagger.json` can succeed to provide a swagger.json
LOG-3077
LOG-2868
UTs

test(integration-tests): swagger check

---

packages/console/src/pages/Users/components/CreateForm/index.tsx
packages/console/src/scss/modal.module.scss

A change on creating new user: generate a random password (in the front-end) instead of user input.
LOG-3035

fix(console): auto generate password

---

packages/console/src/pages/UserDetails/components/UserConnectors.tsx

`user.identities` is not use `target` as key, sync this change to "user connectors table".
LOG-3034
Local tested.
@darcyYe

feat(console): use target in user connectors

---

.github/workflows/commitlint.yml
.github/workflows/deploy-dev.yml
.github/workflows/integration-test.yml
.github/workflows/main.yml
.github/workflows/update-pr-metadata.yml
.github/workflows/upload-annotations.yml

to save parallel running count for workflows
- Using concurrency: https://docs.github.com/en/actions/using-jobs/using-concurrency
- GitHub context: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
CI

refactor(ci): add concurrency

---

packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.test.tsx
packages/ui/src/containers/TermsOfUse/TermsOfUsePromiseModal/index.test.tsx

add some ut test case to improve the coverage
ut case passed
@logto-io/eng

test(ui): add ut

---

packages/console/src/components/TabNav/TabNavItem.module.scss

make tab item easier to click
locally

refactor(console): improve tab item click area

---

packages/core/src/database/seed.ts
packages/schemas/src/seeds/index.ts
packages/schemas/src/seeds/roles.ts

add role table seed 
add admin as default role seed
test locally
@logto-io/eng cc: @IceHe @gao-sun

feat(core): add role table seed 

---

packages/console/src/components/Dropdown/index.module.scss

fix(console): dropdown max height
https://www.figma.com/file/bcSRcMyKEQc0c7k7QfP9fG/%F0%9F%AA%90-%5BWeb%5D-AC-Design-System?node-id=237%3A697
* LOG-3050

fix(console): dropdown max height

---

packages/console/src/components/Pagination/index.module.scss
packages/console/src/components/Pagination/index.tsx

feat(console): update pagination size and color
* LOG-2564

feat(console): update pagination size and color

---

packages/console/src/pages/Users/index.module.scss
packages/console/src/pages/Users/index.tsx

Update user management table row height  to 48px and avatar size to 28px * 28px.
* LOG-2575

feat(console): update user management table row height and avatar size

---

packages/console/src/pages/Connectors/components/ConnectorName/index.tsx
packages/console/src/pages/Connectors/index.tsx

Only show enabled connectors (platforms) in table.
LOG-3103
LOG-3078
LOG-3090

fix(console): only show enabled connectors in table

---

packages/console/src/hooks/use-connector-in-use.ts
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx

Read sign in experience settings to decide whether is "in use" or not for Email/SMS connector. Previously, only social connectors support that.
LOG-3091
Local tested with different status.

fix(console): sms and email connector in use status

---

packages/core/src/routes/sign-in-settings.ts

Fix settings API throw session not found bug.
In the previous PR, we add some AdminConsole-specific logic to the setting API, which requires OIDCProviders interaction details data. 
However, the settings API should not hard depending on the app session.  Catch and return an empty response instead it the error is SessionNotFound. 
test locally
@logto-io/eng

fix(core): settings api should not throw session not found error

---

packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.module.scss
packages/shared/scss/_console-themes.scss

Implement new connector platform tab colors.
LOG-3025

fix(console): new platform tab colors

---

packages/console/src/pages/UserDetails/components/UserConnectors.tsx

Revert https://github.com/logto-io/logto/pull/1147
N / A

fix(console): user connectors name

---

packages/console/src/components/Dropdown/index.module.scss

fix(console): dropdown padding
* LOG-3044

fix(console): dropdown padding

---

packages/console/src/pages/Settings/index.tsx
packages/phrases/src/locales/en.ts

* Change the button size to `large`
* Change the button text to `Save Changes`
* LOG-3116

fix(console): save changes button on settings page

---

packages/console/src/pages/UserDetails/components/UserConnectors.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

feat: User Details Page Connectors Deletion Confirm
N / A

feat(console): user connector delete confirmation

---

packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/UserDetails/index.module.scss
packages/console/src/pages/UserDetails/index.tsx

fix(console): icon colors on the action menu
* LOG-3039

fix(console): icon colors on the action menu

---

packages/console/src/pages/Dashboard/components/ChartTooltip/index.module.scss
packages/console/src/pages/Dashboard/components/ChartTooltip/index.tsx
packages/console/src/pages/Dashboard/index.tsx

Implement mouse hover "tooltip" in dashboard chart.
LOG-3023

fix(console): dashboard chart tooltip

---

packages/console/src/pages/SignInExperience/components/GuideModal.tsx

Remove sign in methods form fields in guide.
LOG-3110
Local tested, those fields are removed.

fix(console): remove sign in methods form fields in guide

---

packages/console/src/pages/Dashboard/components/ChartTooltip/index.module.scss
packages/console/src/pages/Dashboard/components/ChartTooltip/index.tsx
packages/console/src/pages/Dashboard/index.tsx
packages/shared/scss/_fonts.scss

Fix dashboard chart style:
1. Axis label font and color
2. Line stroke and fill color
LOG-3062

fix(console): dashboard chart style

---

packages/console/src/pages/AuditLogDetails/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

fix(console): add code editor field label
* LOG-3030
* LOG-3031

fix(console): add code editor field label

---

packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
packages/console/src/pages/Connectors/components/ConnectorName/index.tsx

fix(console): add bottom color for connector logos
* LOG-3028

fix(console): add bottom color for connector logos

---

packages/connector-facebook/README.md

Add Facebook Universal connector README.
LOG-2621
No need.
---

docs(connector-facebook): readme

---

packages/console/src/components/TextInput/index.module.scss

Fix date picker input height, set to 20px.
LOG-3024
Local tested

fix(console): date picker input height

---

packages/console/src/components/Drawer/index.module.scss
packages/console/src/components/Drawer/index.tsx
packages/console/src/pages/ApplicationDetails/index.tsx

Show application SDK integration guide in the "Check Help Guide" drawer on application details page

feat(console): show app guide in "Check Help Guide" drawer

---

.github/workflows/main.yml

add missing ui code cov job
@logto-io/eng

fix(ui): add missing ui codecov job

---

packages/console/src/components/AppContent/components/UserInfo/index.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/index.tsx

fix(console): display default avatar when the avatar is empty
N / A

fix(console): display default avatar when the avatar is empty

---

packages/console/src/pages/UserDetails/components/UserConnectors.tsx

refactor(console): rename `id` -> `target` in display connector
N/A

refactor(console): rename `id` -> `target` in display connector

---

.github/pull_request_template.md

Remove the "Linear issue reference" from the PR template
No need.

chore: remove Linear issue reference from PR template

---

.github/workflows/integration-test.yml
.github/workflows/main.yml

- reduce integration test OS
- run main on every push
CI

ci: optimize workflows

---

packages/console/src/components/AppContent/components/UserInfo/index.tsx
packages/console/src/consts/avatars.ts
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/index.tsx

refactor(console): rename `getAvatarById` -> `generateAvatarPlaceHolderById`
* LOG-3156
Tested in the admin console.

refactor(console): rename `getAvatarById` -> `generateAvatarPlaceHolderById`

---

packages/console/src/components/Switch/index.tsx

Set switch's default value to false
Local tested with existing forms.

fix(console): set switch default value to false

---

packages/phrases/src/locales/en.ts

Refine the username description in the **Add User** dialog.
`User username` → `Username`
Original:
After refinement:

chore(phrases): refine username description in add-user dialog

---

.dockerignore
.github/workflows/deploy-dev.yml
.github/workflows/dockerize.yml
Dockerfile
docker-compose.yml
packages/core/src/env-set/parameters.ts

- add `Dockerfile`
- add `docker-compose.yml` for quick demo
- read core launching params from env
- build, test, and upload docker image on master push
- locally with `docker compose up`, works fine
- workflow [works fine](https://github.com/logto-io/logto/actions/runs/2542786904)

ci: dockerize

---

packages/console/src/components/Search/index.module.scss
packages/console/src/components/Search/index.tsx
packages/console/src/pages/Users/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

feat(console): clear search results
Refer to the design: https://www.figma.com/file/iroUuWbeZ9fqcqXNwqYZai/%F0%9F%92%BB-%5BWeb%5D-Admin-Console-UI?node-id=1894%3A47370
* LOG-3080

feat(console): clear search results

---

packages/connector-alipay-native/src/constant.ts
packages/connector-alipay/src/constant.ts
packages/connector-apple/src/constant.ts
packages/connector-facebook/src/constant.ts
packages/connector-github/src/constant.ts
packages/connector-google/src/constant.ts
packages/connector-wechat-native/src/constant.ts
packages/connector-wechat/src/constant.ts

Update social connector description.
UT.

chore(connector-*): update social connector description

---

packages/connector-alipay-native/README.md

Add Alipay Native README.md US-en part.
UTs.

docs(connector-alipay-native): add readme.md (en-US)

---

packages/console/src/pages/SignInExperience/components/Preview.tsx

pass enabled connectors to preview.
Local tested.

fix(console): pass enabled connectors to preview

---

packages/console/src/pages/SignInExperience/index.module.scss

fix(console): fix SIE title padding

---

packages/console/src/pages/SignInExperience/index.module.scss
packages/console/src/pages/SignInExperience/index.tsx

Fix "others" form height in SIE

fix(console): others form height in SIE

---

packages/console/src/components/ItemPreview/index.module.scss
packages/console/src/pages/SignInExperience/components/Preview.tsx

prevent cell overflow for user table

fix(console): prevent cell overflow for user table

---

packages/console/src/pages/SignInExperience/components/Preview.module.scss
packages/console/src/pages/SignInExperience/components/Preview.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/hooks/use-preview.ts
packages/ui/src/utils/social-connectors.test.ts
packages/ui/src/utils/social-connectors.ts

Add a new tab "Mobile Web" in SIE Preview.
Notice the Alipay connector:

feat(console): add mobile web tab in preview

---

packages/console/src/pages/Connectors/index.tsx

Fix the add connector button (onClick) in table empty state.
Local tested.

fix(console): add connector button in table empty state

---

packages/connector-aliyun-sms/docs/config-template.json
packages/connector-aliyun-sms/src/index.test.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-aliyun-sms/src/mock.ts
packages/connector-aliyun-sms/src/types.ts

Fix config guard (remove unnecessary fields in config guard).
UTs.

fix(connector-aliyun-sms): fix config guard, remove unnecessary fields

---

.github/workflows/dockerize.yml
docker-compose.yml

upload image to ghcr and use the registry in docker compose
[run#7036614056](https://github.com/logto-io/logto/runs/7036614056?check_suite_focus=true)

ci: upload image to ghcr

---

packages/ui/.parcelrc
packages/ui/src/assets/index.d.ts
packages/ui/src/assets/logo/logto-dark.svg
packages/ui/src/assets/logo/logto-light.svg
packages/ui/src/pages/SignIn/index.tsx

add default logto icon
test locally 
@logto-io/eng

refactor(ui): add default logto  icon

---

packages/ui/src/components/Button/index.module.scss

button user select none
per design update, all the button text should not be selected
test locally
@logto-io/eng

style(ui): button user select none

---

packages/connector-alipay-native/src/index.test.ts
packages/connector-alipay-native/src/index.ts
packages/connector-alipay/src/index.test.ts
packages/connector-alipay/src/index.ts
packages/connector-apple/jest.config.ts
packages/connector-apple/package.json
packages/connector-apple/src/index.test.ts
packages/connector-apple/src/index.ts
packages/connector-apple/tsconfig.json
packages/connector-facebook/src/index.test.ts
packages/connector-facebook/src/index.ts
packages/connector-facebook/src/types.ts
packages/connector-github/src/index.test.ts
packages/connector-github/src/index.ts
packages/connector-github/src/types.ts
packages/connector-google/src/index.test.ts
packages/connector-google/src/index.ts
packages/connector-types/src/index.ts
packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat/src/index.test.ts
packages/connector-wechat/src/index.ts
packages/core/src/middleware/koa-connector-error-handler.test.ts
packages/core/src/middleware/koa-connector-error-handler.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
pnpm-lock.yaml

1. Handle authorization callback parameters in each connector respectively.
2. Add `ConnectorErrorCodes.UnsuccessfulAuthorization` and corresponding error handler.
LOG-2929
UTs.

feat(connectors): handle authorization callback parameters in each connector respectively

---

packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

align the phrase "Post Sign-out Redirect URI"
CI

refactor: align `Post Sign-out Redirect URI`

---

packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat-native/src/types.ts
packages/connector-wechat/src/index.test.ts
packages/connector-wechat/src/index.ts
packages/connector-wechat/src/types.ts
packages/ui/src/utils/social-connectors.test.ts

Fix wechat variable names and display names according to wechat naming convention.
UTs.

chore(connector-wechat-*): fix according to wechat naming convention

---

packages/connector-alipay-native/package.json
packages/connector-alipay-native/src/constant.ts
packages/connector-alipay/package.json
packages/connector-alipay/src/constant.ts
packages/connector-aliyun-dm/package.json
packages/connector-aliyun-dm/src/constant.ts
packages/connector-aliyun-sms/package.json
packages/connector-aliyun-sms/src/constant.ts
packages/connector-apple/package.json
packages/connector-apple/src/constant.ts
packages/connector-facebook/package.json
packages/connector-facebook/src/constant.ts
packages/connector-github/package.json
packages/connector-github/src/constant.ts
packages/connector-google/package.json
packages/connector-google/src/constant.ts
packages/connector-sendgrid-mail/package.json
packages/connector-sendgrid-mail/src/constant.ts
packages/connector-smtp/package.json
packages/connector-smtp/src/constant.ts
packages/connector-twilio-sms/package.json
packages/connector-twilio-sms/src/constant.ts
packages/connector-wechat-native/package.json
packages/connector-wechat-native/src/constant.ts
packages/connector-wechat/package.json
packages/connector-wechat/src/constant.ts
packages/core/src/connectors/index.ts

Load config template and readme files' contents while connector initialization.
UTs.

refactor(connector-*): load config template and readme contents while initialization

---

packages/console/src/pages/ApiResources/index.module.scss
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.module.scss
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/Connectors/components/ConnectorName/index.module.scss
packages/console/src/pages/Users/index.module.scss

fix(console): item preview shrink

fix(console): icons in item preview should not be shrinked

---

packages/ui/src/components/Button/SocialLinkButton.module.scss
packages/ui/src/components/Button/SocialLinkButton.tsx
packages/ui/src/components/Button/index.module.scss

update the social button style according to the latest design
@logto-io/eng

style(ui): update the social button style

---

packages/connector-alipay-native/README.md
packages/connector-alipay/README.md
packages/connector-facebook/README.md
packages/connector-google/README.md

Add Alipay Web README.md (en-US).
UTs.

docs(connector-alipay-web): add Alipay web readme

---

packages/connector-aliyun-sms/README.md
packages/connector-aliyun-sms/docs/config-template.json

Add Aliyun SMS README.md (en-US).
UTs.

docs(connector-aliyun-sms): add readme.md (en-US)

---

.github/workflows/integration-test.yml
.github/workflows/main.yml

to run required workflows when PR is from forked repo
CI

ci: change workflows trigger

---

packages/core/src/connectors/index.ts

Fix connector readme and configTemplate content parsing.
N/A

fix(core): fix connector readme and configTemplate content parsing

---

packages/console/src/pages/Dashboard/index.tsx

Fix dashboard date, add it to query.

fix(console): fix dashboard date

---

packages/console/src/pages/ConnectorDetails/index.tsx

clear error message before saving connector config
Local tested.

fix(console): clear error message before saving connector config

---

packages/connector-alipay-native/README.md
packages/connector-alipay/README.md
packages/connector-facebook/README.md
packages/connector-github/README.md
packages/connector-google/README.md

Add GitHub README.md (en-US).
UTs.

docs(connector-github): add GitHub README.md (en-US)

---

packages/console/src/pages/SignInExperience/components/Preview.module.scss

fix(console): add sie preview nav margin

---

packages/console/src/pages/Users/index.tsx

Per latest design, show user id in users table.

fix(console): show user id in users table

---

packages/console/src/pages/SignInExperience/components/GuideModal.tsx

Fix SIE guide skip button: should update "customizeSignInExperience" settings.
Local tested

fix(console): sie guide skip

---

packages/phrases/src/locales/zh-cn.ts

refactor(console): update zh-cn.ts

---

packages/console/src/scss/_underscore.scss

Update loading skeleton base color
https://user-images.githubusercontent.com/12833674/176343972-debdb172-de22-4880-b26c-92d79e55eeb0.mov

style(console): update loading skeleton base color to layer-2

---

packages/console/src/pages/GetStarted/hook.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Update button text from "Create" to "Enable"

fix(console): update get-started enable passwordless button text to "Enable"

---

packages/connector-wechat-native/README.md

use emoji to replace gfm tips, since it's more flexible
github md review

refactor(connector-wechat-native): use emoji

---

packages/console/src/components/AuditLogTable/index.tsx

Hide user column in "user logs"

fix(console): hide user column

---

packages/console/src/components/AppContent/index.module.scss
packages/console/src/pages/SignInExperience/components/GuideModal.module.scss
packages/console/src/scss/_underscore.scss

Set SIE guide modal max-width.

style(console): sie guide max width

---

packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
packages/console/src/mdx-components/Step/index.module.scss
packages/console/src/mdx-components/UriInputField/index.module.scss
packages/console/src/pages/Applications/components/Guide/index.tsx

Update React sdk integration guide in admin console, based on the latest content from docs recipes.

refactor(console): react sdk integration guide

---

.github/workflows/clean-up-images.yml

clean up untagged + three days long images
[CI](https://github.com/logto-io/logto/runs/7109444717?check_suite_focus=true)

ci: clean up old untagged images

---

packages/connector-sendgrid-mail/README.md

Add SendGrid mail README.md (en-US).
N/A

docs(connector-sendgrid-mail): add readme.md (en-US)

---

packages/connector-twilio-sms/README.md

Add Twilio SMS README.md (en-US).
N/A

docs(connector-twilio-sms): add Twilio SMS README.md (en-US)

---

packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
packages/console/src/pages/Applications/components/Guide/index.tsx
packages/console/src/types/applications.ts

Add Vanilla JS integration guide in admin console

refactor(console): add vanilla js integration guide

---

packages/connector-aliyun-dm/README.md
packages/connector-aliyun-sms/README.md
packages/connector-facebook/README.md
packages/connector-github/README.md

Add Aliyun DM README.md (en-US).
UTs.

docs(connector-aliyun-dm): add Aliyun DM README.md (en-US)

---

packages/console/package.json
packages/console/src/components/AppContent/components/UserInfo/index.tsx
packages/core/src/oidc/init.ts
packages/demo-app/package.json
packages/demo-app/src/App.tsx
pnpm-lock.yaml

disable userinfo endpoint and provide `defaultResource` to fulfill more claims in the id token of `getTokenByCode()` response
tested with 0, 1, 2 resources in LogtoConfig:
- 0: getTokenByCode returns access token with no resource
- 1: getTokenByCode returns access token with the only resource
- 2: getTokenByCode returns access token with no resource

refactor(core): disable userinfo endpoint

---

packages/console/package.json
packages/demo-app/package.json
packages/demo-app/src/App.tsx
pnpm-lock.yaml

to make sure the user can see the sign in page
locally

refactor(demo-app): use `login` as prompt

---

packages/console/src/components/Toast/index.module.scss
packages/console/src/components/Toast/index.tsx

fix(console): remove the close button from toast

fix(console): remove the close button from toast

---

packages/connector-smtp/README.md

Add SMTP README.md (en-US).
N/A

docs(connector-smtp): add SMTP README.md (en-US)

---

packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios_zh-cn.mdx
packages/console/src/pages/Applications/components/Guide/index.tsx

* Update iOS SDK integration guide
* Add Chinese translation

refactor(console): update iOS guide

---

packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx

Update Vue SDK integration guide.
Here are the Chinese translated version

refactor(console): update vue sdk integration guide

---

packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/android_zh-cn.mdx
packages/phrases/src/locales/en.ts

Update Android SDK integration guide.

refactor(console): update android sdk integration guide

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

chore(console): update get sample wording

---

packages/ui/src/components/Button/SocialIconButton.module.scss
packages/ui/src/components/Button/SocialIconButton.tsx
packages/ui/src/components/Button/SocialLinkButton.tsx
packages/ui/src/components/Button/index.test.tsx
packages/ui/src/containers/SocialLanding/index.tsx
packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx
packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.tsx
packages/ui/src/containers/SocialSignIn/SocialSignInList/index.tsx
packages/ui/src/hooks/use-social.ts
packages/ui/src/utils/social-connectors.ts

Add dark mode social icon.
test locally
@logto-io/eng

style(ui): add dark mode social icon

---

packages/console/src/pages/SignInExperience/components/GuideModal.module.scss
packages/console/src/pages/SignInExperience/components/GuideModal.tsx

In SIE guide: move "done" button to the right side.

style(console): move done button to right in sie guide

---

packages/demo-app/src/App.module.scss
packages/demo-app/src/App.tsx

Remove "Continue to explore" section from demo app

refactor(demo-app): remove "continue to explore" section

---

packages/console/src/pages/ApplicationDetails/index.module.scss
packages/console/src/scss/details.module.scss

fix(console): details page should not be shrinked

fix(console): details page should not be shrinked

---

packages/console/src/pages/UserDetails/components/CreateSuccess.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

fix(console): reset password label

---

packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss

fix(console): get-started progress style

fix(console): get-started progress style

---

.vscode/settings.json
packages/console/src/components/AppContent/components/Topbar/index.tsx
packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/AppContent/index.tsx
packages/console/src/hooks/use-scroll.ts

feat(console): display topbar shadow while scrolling

feat(console): display topbar shadow while scrolling

---

packages/core/src/middleware/koa-root-proxy.ts

refactor root path behavior. 
Redirect to /welcome directly.
if not initiated, show the welcome page
else jump to the console directly.
test locally
@logto-io/eng

refactor(core): refactor root path

---

packages/console/src/components/AppContent/components/UserInfo/index.tsx

feat(console): hard code admin display name with username

feat(console): hard code admin display name with username

---

packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.tsx

fix connector platform label i18n

fix(console): fix connector platform label i18n

---

.github/workflows/integration-test.yml
.github/workflows/main.yml

a more reasonable trigger for main and integration test from [this post](https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/16?u=gao-sun)
CI

ci: update workflow trigger

---

.github/workflows/publish.yml
commitlint.config.js
lerna.json
package.json
packages/demo-app/package.json

refactor publish workflow for a workable solution
locally, commit looks as expected

ci: update publish workflow 

---

packages/connector-alipay-native/README.md

docs(conector-alipay-native): android SDK guide
N / A

docs(conector-alipay-native): android SDK guide

---

.github/workflows/release.yml
package.sh

should be the tag just tagged
after merge

ci: fix release tag

---

.github/workflows/release.yml

- locally test docker after push to remote
after merge

ci: fix test tag

---

packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
packages/console/src/pages/Applications/components/Guide/index.tsx
packages/console/src/pages/Applications/components/GuideHeader/index.tsx
packages/console/src/types/applications.ts

Add express js guide for traditional web tutorial

feat(console): add traditional web guide - express js demo

---

packages/core/src/database/seed.ts
packages/core/src/env-set/dot-env.ts
packages/core/src/middleware/koa-spa-proxy.ts
packages/core/src/oidc/init.ts
packages/core/static/html/logout.html

auto sign-out for rp initiated logout.
ref: https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#logoutsource

feat(core): auto sign-out

---

.github/workflows/release.yml
packages/schemas/package.json

extract changelog from previous commit and add the content to GitHub release

ci: add changelog to release

---

commitlint.config.js

chore: add scope enum

---

packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
packages/phrases/src/locales/zh-cn.ts

- polish content
- hide slogan when needed

refactor(console): update branding area

---

.github/workflows/release.yml

add prerelease tag for every sevmer git tag
after merge

ci: add prelease tag on docker images

---

README.md

chore: remove WIP

---

.github/workflows/release.yml

misunderstood the meaning of `pattern`, should work now
after merge

ci: fix prerelease tag

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

update console -> sie -> connectors content to reduce confusion
N/A

refactor(console): update content

---

packages/console/src/pages/Connectors/index.tsx

refactor(console): swap sms and email connector

---

packages/phrases/src/locales/en.ts

refactor(console): update en.ts

---

packages/console/src/pages/Users/components/CreateForm/index.tsx

remove add user subtitle and name requirement

refactor(console): remove add user subtitle

---

packages/console/src/pages/ApplicationDetails/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

chore: update i18n keys

---

packages/connector-wechat/README.md

Add WeChat web readme zh-CN contents.
N/A

docs(connector): wechat web readme zh-CN

---

packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx

fix(console): remove userinfo endpoint on application details page

fix(console): remove userinfo endpoint on application details page

---

packages/connector-alipay-native/docs/config-template.json
packages/connector-alipay/docs/config-template.json

Update Alipay configTemplates for better illustration.
N/A

chore(connector): update Alipay configTemplates for better demonstration

---

packages/connector-alipay-native/src/constant.ts
packages/connector-alipay/src/constant.ts
packages/connector-aliyun-dm/src/constant.ts
packages/connector-aliyun-sms/src/constant.ts
packages/connector-apple/src/constant.ts
packages/connector-facebook/src/constant.ts
packages/connector-github/src/constant.ts
packages/connector-google/src/constant.ts
packages/connector-sendgrid-mail/src/constant.ts
packages/connector-smtp/src/constant.ts
packages/connector-twilio-sms/src/constant.ts
packages/connector-wechat-native/src/constant.ts
packages/connector-wechat/src/constant.ts

Update connectors' description.
As for contents, see [doc](https://www.notion.so/silverhand/db7fb449dc1344f2b94c4f854847bc2c?v=3172d0df286b4a17822660934b2caddc).
N/A

chore(connector): update connectors description

---

packages/console/src/pages/GetStarted/hook.ts
packages/schemas/src/seeds/application.ts

for a better display
locally sign in/out demo app works

refactor: update demo app id

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

- lowercase "t" in "the"
- update zh-cn accordingly
N/A

refactor(phrases): sign out the demo app

---

packages/phrases/src/locales/en.ts

fix: update en.ts

---

packages/console/src/components/Button/index.module.scss
packages/console/src/pages/Welcome/index.module.scss
packages/ui/src/components/Button/SocialIconButton.module.scss
packages/ui/src/containers/SocialSignIn/SocialSignInIconList/index.tsx
packages/ui/src/containers/UsernameSignin/index.module.scss
packages/ui/src/scss/_desktop.scss
packages/ui/src/scss/_mobile.scss

style(ui): ui & console style update 
1. fix the apple light mode icon color, including hover state
2. Fix the error message layout issue when terms of use disabled
3. Update the welcome page button effects, add apply snowflake icon to both light & dark mode.
test locally
@logto-io/eng

style(ui): ui & console style update 

---

packages/phrases/src/locales/zh-cn.ts

refactor(phrases): get started l10n

---

README.md

for a better experience
In preview

chore: add link for badges

---

packages/connector-wechat-native/README.md

remove redundant query configs, which are already added in the Android SDK, in the WeChat native readme.
N / A

docs(connector): remove redundant query configs in wechat native readme

---

packages/core/src/oidc/utils.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

refactor: improve allow CORS tooltip wording

---

packages/schemas/src/seeds/sign-in-experience.ts
packages/ui/src/containers/AppNotification/index.module.scss

add dark logo seed
adjust notification width
test locally
@logto-io/eng

fix(ui): dark mode seed

---

packages/connector-smtp/README.md
packages/connector-twilio-sms/README.md
packages/connector-wechat-native/README.md

docs: update node component in docs
N / A

docs: update node component in docs

---

packages/console/src/components/Status/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Dashboard/components/Block.tsx
packages/console/src/pages/Dashboard/index.tsx

fix typo for variant
no needed.

fix(console): fix typo for variant

---

packages/core/src/middleware/koa-slonik-error-handler.ts

Per offline discussion, no need to handle LOG-1665 Refactor Deletion Handle
N / A

chore(core): remove needless todo

---

packages/schemas/tables/resources.sql

Adjust access token default TTL for api resources. Align with the OIDC provider default settings. 
test locally @logto-io/eng

refactor(core): adjust access token ttl

---

packages/console/src/pages/UserDetails/components/UserLogs.tsx
packages/console/src/pages/UserDetails/components/UserSettings.tsx
packages/console/src/pages/UserDetails/components/UserSettingsForm.tsx
packages/console/src/pages/UserDetails/index.tsx

feat(console): user settings unsaved changes alert

feat(console): user settings unsaved changes alert

---

packages/console/src/pages/UserDetails/components/CreateSuccess.tsx

change user added modal close button to "done", and add onClose prop.

fix(console): change user added modal button to done

---

packages/console/src/components/AppContent/components/UserInfo/index.module.scss

Use default dropdown item styles (to fix padding) in sign out dropdown.

style(console): sign out dropdown

---

packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/components/CopyToClipboard/index.tsx

use `IconButton` in `CopyToClipboard`.

fix(console): use icon button in copytoclipboard

---

packages/console/src/i18n/init.ts
packages/ui/src/i18n/init.ts

set ui specific i18n storage key
to distinguish it from ac settings. 
@logto-io/eng

fix(ui): set ui specific i18n storage key

---

packages/console/src/pages/Connectors/components/CreateForm/index.module.scss

Set connector name font in create modal.
Local tested.

style(console): connector name font

---

.gitpod.yml

make the port 3001 public by default
pending

chore: gitpod logto port public

---

commitlint.config.js

allow deps scope for renovate
after merge

chore: allow deps for commit scope

---

packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios_zh-cn.mdx

refactor(console): update iOS tutorial

---

packages/console/src/components/LinkButton/index.module.scss

set user select to none for link button
local tested.

fix(console): set user select to none for link button

---

packages/integration-tests/package.json
packages/integration-tests/tests/swagger-check.test.ts
pnpm-lock.yaml

Update the integration test to validate swagger.json using `openapi-schema-validator`.
Reference: [@open-api](https://github.com/kogosoftwarellc/open-api) / [openapi-schema-validator](https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-schema-validator)

test(test): validate swagger.json using openapi-schema-validator

---

packages/console/src/components/AppContent/components/Sidebar/hook.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

read current language and generate the link accordingly
locally tested links

refactor(console): link to localized docs website

---

packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx

Fix mistakes in VanillaJS SDK integration guide

fix(console): vanilla sdk integration guide

---

packages/phrases/src/locales/en.ts

refactor(phrases): remove unused tip

---

packages/connector-alipay-native/README.md

docs(connector): alipay native connector
Tested in the admin console.

docs(connector): alipay native connector

---

packages/core/src/routes/session/session.ts
packages/core/src/routes/session/social.ts

Add session check to some session routes
ut passed
@logto-io/eng

fix(core): add session check

---

packages/connector-alipay/README.md
packages/connector-alipay/docs/config-template.json
packages/connector-alipay/src/constant.ts
packages/connector-alipay/src/index.test.ts
packages/connector-alipay/src/index.ts
packages/connector-alipay/src/mock.ts
packages/connector-alipay/src/types.ts
packages/connector-alipay/src/utils.ts

Add `charset` to Alipay web config.
N/A

chore(connector): add `charset` to Alipay web config

---

packages/connector-apple/README.md
packages/connector-wechat-native/README.md
packages/connector-wechat/README.md

docs(connector): apple readme (zh-CN)

---

packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

feat(console): add placeholder for connector sender test

feat(console): add placeholder for connector sender test

---

packages/ui/src/components/BrandingHeader/index.module.scss

Adjust headline style with max 2 lines
test locally
@logto-io/eng

style(ui): adjust headline style

---

packages/ui/src/components/Input/index.module.scss

increase desktio input padding
Increase desktop input padding from 12 -> 16 same as mobile
test locally
@logto-io/eng

style(ui): increase desktop input padding

---

packages/core/src/middleware/koa-slonik-error-handler.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

in API endpoint `PATCH /users/:userId`, remove `InvalidInputError`, use `RequestError` instead.
pass existing UTs.

refactor(core): remove InvalidInputError

---

packages/console/src/pages/Settings/index.tsx

Add unsaved changes warning in settings page

fix(console): add unsaved changes warning in settings page

---

packages/console/src/pages/SignInExperience/components/GuideModal.module.scss
packages/console/src/pages/SignInExperience/components/GuideModal.tsx

make SIE tutorial topbar stick to the top
locally

refactor(console): stick sie tutorial topbar

---

packages/connector-alipay-native/src/index.ts
packages/connector-alipay/src/index.ts
packages/connector-aliyun-dm/src/index.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-facebook/src/index.ts
packages/connector-github/src/index.ts
packages/connector-google/src/index.ts
packages/connector-sendgrid-mail/src/index.ts
packages/connector-smtp/src/index.ts
packages/connector-twilio-sms/src/index.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat/src/index.ts

align with other connectors, follow-up of #1474

refactor(connector): use raw error for config guard

---

packages/core/src/database/find-entity-by-id.ts
packages/core/src/middleware/koa-slonik-error-handler.ts
packages/core/src/queries/application.ts
packages/core/src/queries/log.ts
packages/core/src/queries/resource.ts
packages/core/src/queries/setting.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/queries/sign-in-experience.ts

Fix resource not found error message not clear issue.
Introduce a global  findEntityById util method to handle all findResourceById query
if not found throw a notFountWithId error:
test locally
ut passed
@logto-io/eng

refactor(core): add findEntityById utils

---

packages/connector-aliyun-dm/README.md
packages/connector-aliyun-dm/docs/config-template.json
packages/connector-wechat/README.md

Add Aliyun DM README zh-CN.
N/A

docs(connector): add Aliyun DM README zh-CN

---

packages/console/src/pages/ConnectorDetails/index.tsx

Call mutate immediatly after delete a connector.
Local tested, @xiaoyijun would you mind help confirming it?

fix(console): mutate after connector delete

---

packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/UsernameSignin/index.tsx

Add form submit event. On the desktop, when clicking enter button after a proper input, a form submit evet is fired. Should be handled properly as well. 
test locally
@logto-io/eng

fix(ui): add form submit event

---

packages/console/src/pages/Connectors/components/Guide/index.tsx
packages/core/src/lib/passcode.ts
packages/core/src/routes/admin-user.ts
packages/ui/src/utils/sign-in-experience.ts

Remove TODOs with linear issues.
N/A

chore: remove TODOs with linear issues

---

packages/console/src/pages/SignInExperience/components/Preview.tsx
packages/phrases/src/locales/zh-cn.ts

update order and "native" tag i18n

refactor(console): update sie preview tab

---

packages/connector-aliyun-dm/README.md
packages/connector-aliyun-sms/README.md

Add Aliyun SMS README zh-CN.
N/A

docs(connector): add Aliyun SMS README zh-CN

---

packages/core/src/connectors/consts.ts

Read env `CONNECTOR_PACKAGES` to set value for `connectorPackages`, provide the ability to add custom connector without changing core code.
Local tested.

feat(core): read connector packages env

---

packages/connector-twilio-sms/README.md

Fix wrong indents in connector-twilio-sms/README.md
No need.

docs(connector): fix wrong indents in connector-twilio-sms

---

.github/CONTRIBUTING.md

create contributing guideline (draft)
N/A

chore: create contributing guideline

---

packages/core/src/queries/passcode.ts

Simplify increasePasscodeTryCount and consumePasscode: remove unnecessary <code>sql``</code>

refactor(core): simplify increasePasscodeTryCount and consumePasscode

---

packages/connector-sendgrid-mail/README.md

Fix wrong indents in connector-sendgrid-mail/README.md
No need.

docs(connector): fix wrong indents in connector-sendgrid-mail

---

packages/connector-twilio-sms/README.md

Fix Twilio readme according to bug bash.
See sub-issues here: [LOG-3571](https://linear.app/silverhand/issue/LOG-3571/twilio)
N/A

docs(connector): fix twilio readme according to bug bash

---

packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx

Improve code sample in Vue tutorial

docs(console): improve code sample in vue tutorial

---

packages/connector-smtp/README.md
packages/connector-smtp/docs/config-template.json

docs(connector): smtp readme zh-CN

---

packages/console/src/components/CopyToClipboard/index.tsx
packages/console/src/components/Tooltip/index.module.scss
packages/console/src/components/Tooltip/index.tsx

- fix arrow and tooltip position
- set max width
- add line clamp
- update state name
tested with `-webkit-line-clamp: 2`

fix(console): tooltip style

---

packages/connector-twilio-sms/README.md

docs(connector): twilio readme zh-CN

---

packages/connector-aliyun-sms/README.md
packages/connector-sendgrid-mail/README.md
packages/connector-sendgrid-mail/docs/config-template.json

Add SendGrid README zh-CN.
N/A

docs(connector): sendgrid readme zh-CN

---

packages/connector-aliyun-dm/src/index.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-sendgrid-mail/src/index.ts
packages/connector-smtp/src/index.ts
packages/connector-twilio-sms/src/index.ts
packages/connector-types/src/index.ts
packages/core/src/middleware/koa-connector-error-handler.ts
packages/core/src/routes/connector.test.ts
packages/core/src/routes/connector.ts
packages/phrases/src/languages/en/errors.ts
packages/phrases/src/languages/zh-cn/errors.ts

Passwordless connector send test message with unsaved config.
UTs and tested locally.

fix(connector): passwordless connector send test msg with unsaved config

---

packages/ui/src/hooks/use-phone-number.ts
packages/ui/src/utils/country-code.ts

fix multiple libphonmenumber metadata instance packed bug
test locally
@eng

fix(ui): fix multiple libphonmenumber packed bug

---

packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx

default is in the left
locally

refactor(console): center tooltip for test message

---

packages/console/src/components/AppContent/components/Sidebar/components/Contact/hook.tsx
packages/console/src/components/AppContent/components/Sidebar/components/Contact/index.tsx
packages/phrases/src/languages/en/translation/admin-console/contact.ts
packages/phrases/src/languages/zh-cn/translation/admin-console/contact.ts

- put onclick handler on the correct element
- polish content

refactor(console): fix contact us ux

---

packages/ui/src/containers/Passwordless/PasswordlessConfirmModal.tsx
packages/ui/src/hooks/use-phone-number.ts
packages/ui/src/utils/country-code.test.ts
packages/ui/src/utils/country-code.ts

Format phone number with country calling code
test locally
UT added
@logto-io/eng

fix(ui): format phone number with country calling code

---

packages/connector-aliyun-sms/README.md

- Add description for finding the test-only signature and template.
- Fix typos in Chinese and English
No need.

docs(connector): refine readme of connector-aliyun-sms

---

packages/connector-facebook/README.md
packages/connector-google/README.md

docs(connector): add fb readme zh-CN

---

.github/codeql/codeql-config.yml
.github/workflows/codeql-analysis.yml
packages/connector-aliyun-dm/src/utils.ts
packages/connector-aliyun-sms/src/utils.ts

created for security, generated by GitHub
wait for the trigger

chore: create codeql-analysis.yml

---

README.md

launched by accident, ooof
N/A

chore: add producthunt badge

---

.github/workflows/pen-tests.yml
.github/workflows/release.yml

- run [zap baseline scan](https://github.com/marketplace/actions/owasp-zap-baseline-scan) after a successful master docker release
- remove health check in dockerize workflow since it should be covered by tests
issue created
https://github.com/logto-io/logto/issues/1564

ci: add pen tests

---

.github/workflows/pen-tests.yml

should be edge for master workflows
N/A

ci: fix pen tests docker tag

---

packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/UsernameSignin/index.tsx

Enable submit on Enter button pressing by adding a hidden submit input to all the forms.
Related Issue: #1577 
test locally
@logto-io/eng

feat(ui): add submit input to all the sign-in & register forms

---

.github/workflows/update-pr-metadata.yml

the workflow will overwrite preassigned labels - as we have issue templates now, no need for this anymore
after merge and someone creates a new issue

ci: remove issues trigger

---

packages/core/src/connectors/index.test.ts
packages/core/src/connectors/index.ts
packages/core/src/routes/sign-in-experience.test.ts

Remove unused unneeded `getEnabledSocialConnectorIds`

refactor(core): remove unused getEnabledSocialConnectorIds

---

packages/connector-github/README.md
packages/connector-wechat-native/README.md

docs(connector): add github readme zh-CN
