packages/core/src/init/oidc.ts

temporarily remove resource indicator since jwt access token cannot call `/userinfo` endpoint.
will try to figure out how they (scope, claim, resource indicator) work and summarize into doc once dev environment has been set up.

chore(core): remove resource indicator

---

packages/core/src/init/apis.ts
packages/core/src/routes/session.ts
packages/core/src/routes/user.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/apis/consent.ts
packages/ui/src/apis/register.ts
packages/ui/src/apis/sign-in.ts
packages/ui/src/pages/Register/index.test.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SignIn/index.test.tsx
packages/ui/src/pages/SignIn/index.tsx

According to this [SO answer](https://stackoverflow.com/a/7252311/12514940), RESTful APIs should have noun in URL and use HTTP Method to describe its behavior. The changes in this PR:
1. Use `session` to imply the object of a sign-in flow. E.g. `POST /session` means user is try to create a new session (sign-in).
2. `POST /register` -> `POST /user`.
Tested in playground, looks good.

refactor: conform RESTful convention

---

packages/core/src/errors/RequestError/index.ts
packages/core/src/middleware/koa-auth.ts
packages/core/src/routes/application.ts
packages/core/src/routes/init.ts
packages/phrases/src/index.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

- init `POST /application` api
- init `koaAuth()` middleware to require bearer token in request header
- fixing error message i18n issue
- validate access token in `koaAuth()`
- implement application creating

feat: init application api

---

packages/core/package.json
packages/core/src/env/consts.ts
packages/core/src/middleware/koa-auth.ts
packages/core/src/middleware/koa-guard.ts
packages/core/src/oidc/consts.ts
packages/core/src/oidc/init.ts
packages/core/src/routes/application.ts
packages/core/src/routes/init.ts
packages/schemas/src/index.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/user.ts
pnpm-lock.yaml

1. Separate anonymous routes and authed routes into different routers.
2. Add `koaAuth()` middleware to verify JWT.
`POST /api/application`
Note: The valid JWT can be generated from playground now with `resource=https://api.logto.io` in auth request.
`GET /api/application`

feat: validate access token if needed

---

packages/core/src/oidc/adapter.ts
packages/core/src/queries/oidc-model-instance.ts
packages/schemas/src/gen/utils.ts
packages/schemas/tables/applications.sql
packages/schemas/tables/oidc_model_instances.sql

Per discussion, use `timestamptz` as database timestamp type. Value will still be `number` in Node.

refactor: unify timestamp usage

---

packages/core/src/middleware/koa-error-handler.ts
packages/schemas/src/api/error.ts
packages/ui/package.json
packages/ui/razzle.config.js
packages/ui/src/hooks/use-api.ts
packages/ui/src/include.d/dom.d.ts
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SignIn/index.tsx
pnpm-lock.yaml

Implement useApi hooks to handle api call flow. Wrap-up api call flow with `loading`, `error`, `result`, `fetch` as its return value. 
Leverage page loading status & error message with useApi hooks response.  Display the error message from api error response. 
update  jest config to allow babelTransform job runs on ky modules. As in jest env we are not able to access ky es6 modules.
By default all node_modules files are ignored by jest config:
filter out /node_modules/ky/ paths.
@wangsijie @gao-sun

feat: Read and show error from API response

---

packages/core/src/routes/session.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

when user tries to consent a session, the API should throw an error if user requested invalid scope (since user is signed in). thus, available scopes should be documented or we can offer a special scope for listing all scopes for an app after sign-in.
created [LOG-50](https://linear.app/silverhand/issue/LOG-50/discussion-available-scopes) for discussion.

refactor: throw an error when requesting invalid scope

---

packages/schemas/package.json
pnpm-lock.yaml

schemas: move `zod` to dependencies to avoid unexpected prune on prod:

fix(schemas): move `zod` into dependencies

---

packages/core/package.json
pnpm-lock.yaml

Added [LOG-97](https://linear.app/silverhand/issue/LOG-97/paseto-access-tokens-research) for paseto access tokens research.

chore(core): upgrade `oidc-provider`

---

packages/core/src/database/update-where.test.ts
packages/core/src/database/update-where.ts
packages/core/src/oidc/utils.ts
packages/core/src/routes/application.ts
packages/schemas/src/foundations/jsonb-types.ts

1. fulfill correct `applicationType` for [`node-oidc-provider`](https://github.com/panva/node-oidc-provider/blob/a751406d5df178b2ce40c2e28b9ae40d379c34f2/lib/helpers/client_schema.js#L594) when creating and patching application.
2. remove `undefined` before updating
LOG-135

refactor(core): fulfill correct `applicationType` when needed

---

packages/ui/package.json
packages/ui/razzle.config.js
pnpm-lock.yaml

1. 
`ky` use `globalThis` reference
Which lead to `globalThis is undefined` error on older browsers, and it will breaks the whole login ui page.
Adding a [ungap/global-this](https://github.com/ungap/global-this) polyfill to the ky  bundle
2. Update webpack to 5
The import-loader we are using use `this.getOptions` method to get the loader options. 
On webpack4  `this.getOptions` is part of the `loader-utils` but removed since webpack5. Added to the loaderContext by default.
So update to webpack5 in order to use the `imports-loader`
test on chrome version 64
@wangsijie @gao-sun cc: @xiaoyijun @IceHe

chore(ui): add global-this polyfill to ky

---

packages/core/package.json
packages/core/src/middleware/koa-pagination.test.ts
packages/core/src/middleware/koa-pagination.ts
packages/core/src/utils/pagination.test.ts
packages/core/src/utils/pagination.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
pnpm-lock.yaml

Add middleware `koaPagination` to handle pagination in both request and response.
1. Parse page-related query: `page`, `per_page`，can set default value. Wrapped into `context.pagination`.
2. After data is fetched and handled properly, set total count to `context.pagination.count`, this middleware will then set response headers: customized `Total-Page` and standard `Link` (https://datatracker.ietf.org/doc/html/rfc5988).
`src/middleware/koa-pagination.test.ts`
`src/utils/pagination.test.ts`

feat: add koa-pagination

---

packages/core/src/middleware/koa-auth.ts
packages/core/src/middleware/koa-user-info.ts
packages/core/src/middleware/koa-user.ts
packages/core/src/routes/types.ts

refactor: wrap detailed user info extraction code block in koaAuth as a new middleware koaUser
wrap detailed user info extraction code block in middleware koa-auth as a new middleware koa-user as detailed user info is not necessary in all cases.
https://linear.app/silverhand/issue/LOG-270/koaauth-remove-finduserbyid-by-default
tested by sending requests with Postman App and checking console logs in both cases (with/without detailed user info).
case1 (only middleware koaAuth() was called when initializing AuthedRouter):
case2 (both middleware koaAuth() and middleware koaUserInfo() were called when initializing AuthedRouter):

refactor: wrap detailed user info extraction code block in koaAuth as a new middleware koaUser

---

packages/core/src/oidc/init.ts
packages/core/src/queries/resources.ts
packages/core/src/queries/scopes.ts
packages/schemas/tables/resource_scopes.sql

Following the [oidc-provide](https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#featuresresourceindicators)r docs  enable the `resourceIndicators` feature and provide a drafted `getResourceServerInfo` implementation. 
connect to the `resources` & `resource-scopes` table to query resource server info & scopes info return the `resourceServer` data or throw a `invalidTarget` error. 
Test the cases locally 
1. insert test data to the dev table
2. modify the client sdk to pass invalid & valid resource params
-  non URI resource indicator
-  unknown  resource indicator
- valid resource indicator
@wangsijie @xiaoyijun @gao-sun cc: @darcyYe @IceHe

feat: implement getResourceIndicators logic

---

packages/core/package.json
packages/core/src/utils/pagination.ts
pnpm-lock.yaml

The querystring API is considered legacy and it just works on node env.
Replace it with query-string which is supported in all platforms.
FYI: [Slack Disscussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1638260142014900)
* Replace `querystring` with `query-string` or URLSearchParams ([LOG-408](https://linear.app/silverhand/issue/LOG-408/replace-querystring-with-query-string-or-urlsearchparams))
None

refactor(core): replace `querystring` with `query-string`

---

packages/core/src/middleware/koa-pagination.test.ts

Any mutation on object named `context` will trigger `no-mutation` lint error. 
So use `ctx` as context object name instead of `context`, because `ctx` is in eslint exception list.
* Rename `context` to `ctx` in test file ([LOG-442](https://linear.app/silverhand/issue/LOG-442/rename-context-to-ctx-in-test-file))
None

refactor(core): rename `context` to `ctx` in test file

---

packages/core/src/database/insert-into.ts
packages/core/src/database/update-where.ts
packages/core/src/queries/application.ts
packages/core/src/queries/oidc-model-instance.ts
packages/core/src/queries/resources.ts
packages/core/src/queries/scopes.ts
packages/core/src/queries/user.ts
packages/schemas/src/db-entries/application.ts
packages/schemas/src/db-entries/oidc-model-instance.ts
packages/schemas/src/db-entries/resource-scope.ts
packages/schemas/src/db-entries/resource.ts
packages/schemas/src/db-entries/user-log.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/src/foundations/schemas.ts
packages/schemas/src/gen/index.ts
packages/schemas/src/gen/schema.ts
packages/schemas/src/gen/types.ts

Each table in database will generate 2 interface: one for returning data, the other for insert and update.
An example:
```sql
create table users (
id varchar(24) not null,
username varchar(128),
role varchar(24) not null default('guest'),
primary key (id)
);
```
```ts
interface User {
id: string;
username: string | null;
role: string;
}
interface UserDBEntry {
id: string;
username?: string | null;
role?: string;
}
```
Please check if the naming rule `User` and `UserDBEntry` is suitable.
`buildUpdateWhere` and `buildInsertInto` are updated: now have 2 type templates, "insert type" and "return type".
tip: you can ingore auto generated files on reviewing this PR, considering remove those out of version control [LOG-439](https://linear.app/silverhand/issue/LOG-439/move-generated-schema-code-ou …

feat: generate 2 types for db table schema

---

packages/ui/src/hooks/use-api.ts

We have observed a dead loop call on the UI user consent page:
The root cause is when calling the request method within a `useEffect` hook:
Note: the `useEffect` dependency was newly added, that's why we observe the issue till recently. 
The request was refreshed after each request status change. 
Fix: wrap up the request method in `useApi` hook into a `useCallback` hook. As it only depends on the `api` param.  Should not redefine every time. 
test locally
should successfully run the auth flow without dead loop. 
@logto-io/eng

fix(ui): fix useApi request in useEffect dead loop bug

---

packages/schemas/src/gen/utils.ts

Add DB type `boolean`.
According to [document](https://www.postgresql.org/docs/14/datatype-boolean.html), `boolean` is the standard name.
And support syntax highlighting.

chore: add boolean type for postgres

---

.github/workflows/main.yml
codecov.yml
packages/core/jest.config.js
packages/core/package.json
packages/core/src/database/update-where.test.ts
packages/ui/package.json
packages/ui/razzle.config.js
pnpm-lock.yaml

- add the `cannot read properly of undefined` platform based TypeError message mapper in the UT , to bypass the test case fail issue.
- add coverage report on `core` and `ui` project
- add codecov uploader job
core
ui
Using node deprecated version of `codecov` uploader as well. Need to track  LOG-1276  issue to migrate the deprecate uploader to the new one. 
current coverage settings are :
default overall 70%,
each individual project: no less than the previous commit report.
We use global [settings](https://app.codecov.io/account/gh/logto-io/yaml) in codecov for all over logto-io repos. 
Run the test on CI
@logto-io/eng

ci(codecov): add jest coverage report

---

packages/core/src/oidc/adapter.ts
packages/core/src/oidc/utils.ts
packages/core/src/routes/application.ts
packages/schemas/src/db-entries/application.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/tables/applications.sql

Update application DB
1. add optional field `description`
2. add optional field `logo_uri` to the `oidc_client_metadata`. As supported by the OIDC provider
3. add `idTokenTTL` with a default value
4. add `refreshTokenTTL` with a default value
5. remove the `application_type` field in `oidc_client_metadata` in order to keep a single source of truth of the application type
6. Update the OIDC provider adapter, load the application type from the ApplicationDB's type field directly 
7. Update the `buildOidcClientMetadata` util methods accordingly. 
test locally on playground. 
public db updated accordingly. 
UT passed 
@logto-io/eng

feat(schema): update application db

---

packages/core/src/database/utils.ts
packages/core/src/queries/application.ts
packages/core/src/queries/utils.ts
packages/core/src/routes/application.ts

Add pagination middleware to findAllApplications
1. update the `findAllApplications` query method to take limit and offset as its query input
2. add `koa-pagination` middle to the GET /applications api
3. Return total num of applications as totalCount to the pagination middleware
Test locally with post man
Request:
Response:
Response Header:
@logto-io/eng

feat(applications): add pagination middleware to findAllApplications

---

packages/core/src/database/insert-into.test.ts
packages/core/src/database/update-where.test.ts
packages/core/src/oidc/adapter.ts
packages/core/src/queries/application.ts
packages/core/src/queries/connector.ts
packages/core/src/queries/oidc-model-instance.ts
packages/core/src/queries/resources.ts
packages/core/src/queries/scopes.ts
packages/core/src/queries/user-log.ts
packages/core/src/queries/user.ts
packages/schemas/src/db-entries/application.ts
packages/schemas/src/db-entries/connector.ts
packages/schemas/src/db-entries/oidc-model-instance.ts
packages/schemas/src/db-entries/resource-scope.ts
packages/schemas/src/db-entries/resource.ts
packages/schemas/src/db-entries/setting.ts
packages/schemas/src/db-entries/user-log.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/src/gen/schema.ts
packages/schemas/src/types/user.ts

Rename all `\w+DBEntry` as `\w+Update` to eliminate misunderstanding (per [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1641802893048900)) by:
1. fix the variable naming convention in `packages/schemas/src/gen/schemas.ts`
2. fix the names of variables that can not be auto-generated
LOG-1303
All UT passed.

chore: rename all `\w+DBEntry` as `\w+Update` to eliminate misunderstanding

---

packages/core/src/connectors/utils.ts
packages/core/src/queries/connector.ts

Wrap database query into `updateConnectorConfig` for connector.
Then the connector's code won't call database directly.
That is part of connector's convention design: https://www.notion.so/silverhand/updateConnectorConfig-aeca364ceefe4cbaa3a3b4a3ce79ef59

feat: updateConnectorConfig

---

packages/core/src/include.d/oidc-provider.d.ts
packages/core/src/oidc/adapter.ts
packages/core/src/oidc/consts.ts
packages/core/src/oidc/init.ts
packages/schemas/src/db-entries/application.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/tables/applications.sql

Attempt to set `idToken` and `refreshToken` ttl based on the client metadata settings.
Researched on the OIDC Provider's [extra client metadata config ](https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#extraclientmetadataproperties). 
We should implement and manage all our potential customized client metadata within a single jsonb field and passed to the OIDC Provider as `extraClientMetadataProperties`, guarded using the Zod type guard. 
1. update the DB, remove the field of `idTokenTtl` and `refreshTokenTtl` add a new jsonb field called `customeClientMetadata` field instead
2. Implement an oidc-provider type declaration to extend the `AllClientMetadata` interface with our `CustomClientMetadata`.
3. Pass in the keys of `CustomClientMetadata` as OIDC-Provider …

feat(application): set idToken and refreshToken ttl based on client metadata

---

packages/core/src/middleware/koa-error-handler.ts
packages/core/src/queries/application.ts
packages/core/src/routes/application.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Add application query exceptions. Need to align the exception thrown logic. 
Pure our online & offline discussion:
1. Should not add any custom exception handle logic at the query script level by default. Exceptions on extreme cases may apply.
2. Should not handle slonik exceptions except for the "not found" error. Throw 500 for all the rest.
3. Catch the slonik NotFount error and return a 404 RequestError with a custom error message at the error-handler middleware.
4. Run query script first then delete script on all the delete apis. 
GET
DELETE
@logto-io/eng

feat(application): add application query exceptions

---

packages/core/src/connectors/aliyun-dm/index.ts
packages/core/src/connectors/types.ts

Implement `validateConfig` in convention.
Common usage for this function: when a user try to enable this connector, all config should be valid.

feat(aliyun-dm): validate config

---

packages/core/src/oidc/init.ts
packages/core/src/routes/session.ts

This PR is aiming to unblock the possible incoming implementations and testings on the authorization endpoints did the following config updates on Logto core:
1. Enable userinfo feature of OIDC Provider. Allow access to the OIDC's `getUserInfo` endpoint
2. Set `resourceIndicators.useGrantedResource` to false. We allow users to request multiple resources on the authorization_code flow.  Disable the auto fulfill token resource with the granted resources feature. Users have to pass the request resource indicator through the resource param of the /token endpoint manully. 
3. Remove the restriction of OIDC scopes only on the user consent flow. Add the resource scopes consent logic. 
The settings are open to discussion and may be updated by the future's mainflow-related PR. 
test locally on dev …

refactor(core): enable userinfo endpoint and resource scope consent

---

packages/core/src/database/insert-into.test.ts
packages/core/src/database/insert-into.ts

Only insert fields(keys) that exists on `data`.
That is useful when a column has a default value on database.

fix(database): insertKeys filtering

---

packages/core/src/queries/connector.ts
packages/core/src/routes/connector.ts
packages/core/src/routes/user.ts

align the routers' return process of updating DB properties. (stick to use the return value of `updateXXX` without re-requesting DB)
LOG-1405

chore: align routers return process of updating DB

---

packages/core/src/queries/sign-in-experience.ts
packages/core/src/routes/init.ts
packages/core/src/routes/sign-in-experience.ts

Add sign-in experience query and API
For v1 we only return the default settings to the developers. All `GET` method by default returns the `sign_in_experience`  data where id = 'default'.
Currently, `default` as an id is hardcoded in the query method.  Let me know if anyone has a better option.  Don't like it either. 
LOG-1410
LOG-1061
GET /sign-in-ex should return `default` settings
PATCH /sign-in-ex
case 1: more than there primary signInMethods are not allowed:
case 2:  at lease one primary signInMethods are required
case 3: success update
@logto-io/eng

feat(core): add sign-in experience query and api

---

packages/core/src/database/update-where.test.ts
packages/core/src/database/utils.test.ts
packages/core/src/database/utils.ts
packages/core/src/queries/roles.ts
packages/core/src/routes/admin-user.ts
packages/core/src/routes/init.ts
packages/core/src/routes/role.ts
packages/core/src/routes/user.ts
packages/schemas/src/db-entries/user.ts
packages/schemas/src/types/user.ts
packages/schemas/tables/users.sql

1. Add `roleNames` to the `userInfoSelectFields`. Let the GET /users API could return users rolename data
2. Add admin-user authed routers and PATCH /users/:id/roles API
- add temp validation of the input roles, in not found in roles table, throw a foreign key exception.
3. Add role router and GET /roles api
4. Update the `convertToPrimitiveOrSql` that accepts array liked JSON inputs.
test locally:
GET roles:
GET user:
PATCH roleNames:
- set to Null:
- Invalid roleNames:

feat(core): add user roles related api

---

packages/core/src/lib/passcode.test.ts
packages/core/src/lib/passcode.ts
packages/core/src/queries/passcode.ts
packages/schemas/src/db-entries/passcode.ts
packages/schemas/tables/passcodes.sql

Rename `sessionId` to `interactionJti` in passcode.
According to `node-oidc-provider`'s [doc](https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#user-flows), `session` is not create before signing in, so there is no `sessionId`. `interaction.jti` is what we need.
pass previous UTs.

fix(passcode): use interaction_jti instead of session_id

---

packages/core/src/connectors/utilities/aliyun.ts

Skip non-string (null and undefined) value before sending request to Aliyun.
That is useful for optional params.

fix(aliyun): skip undefined fields

---

packages/core/src/database/update-where.test.ts
packages/core/src/database/update-where.ts
packages/core/src/routes/application.ts

Following the pg [doc](https://www.postgresql.org/docs/current/functions-json.html) 
allow jsonb '||' oprator to shallow merge two jsonb object. 
- only works on the non-nullable field
- only merge map instead of list
test locally 
@logto-io/eng

feat(core): allow jsonb partial update

---

packages/core/src/lib/sign-in.ts
packages/core/src/queries/user.ts
packages/core/src/routes/session.ts
packages/core/src/utils/regex.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/db-entries/custom-types.ts
packages/schemas/tables/user_logs.sql

Passwordless sign-in flow with SMS.
Added to `POST /session` router.
If no code but the phone number is provided in `body`, send passcode.
else, verify passcode and sign-in as well as its valid.
LOG-867
1. no user can be found with phone number.
2. send and receive passcode on phone.
3. sign-in successfully.

feat(phone passwordless): add passwordless sign-in with phone

---

packages/core/src/connectors/types.ts
packages/core/src/lib/register.ts
packages/core/src/lib/sign-in.ts
packages/core/src/lib/social.ts
packages/core/src/routes/session.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Reuse social results(userInfo) to continue sign in.
Flow:
1. A user try to register with a social result (granted a code, exchanged accessToken, and got userInfo), but the user is exists in our database, throw an error with promt
2. The user then decide to sign in and reuse last step's social result
User info is cached in `oidc-provider`'s "interaction result".
Ignore the complex route, it will be refactored immediatly in LOG-1482.
LOG-1508

feat: continue social sign in

---

packages/core/src/app/init.ts
packages/core/src/connectors/aliyun-dm/index.ts
packages/core/src/connectors/aliyun-sms/index.ts
packages/core/src/connectors/github/index.ts
packages/core/src/connectors/types.ts
packages/core/src/middleware/koa-connector-error-handle.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Create an error class `ConnectorError` with predefined `ConnectorErrorCodes` enum. In connector's code, all errors are expected as instance of `ConnectorError`. Those errors will then be processed in middleware, transform into `RequestError`.
Connector's documentation on "Error Handling": https://www.notion.so/silverhand/Connector-a2f9998db51e493c92e383c522fa08fb#67f251ea33c94f09979971b3020e932d
In order to make connectors "independant" and make it easy for developers to contribute code to connectors, we don't expose `RequestError` to connector directly.
LOG-1381

chore: connector error

---

packages/core/src/lib/sign-in.ts
packages/core/src/lib/social.ts
packages/core/src/routes/session.ts

Implement the following sign in flow:
1. try to sign in with social, but cannot find Logto accout by social connector's userId. 
2. the API found a Logto account by social userInfo's phone or email, return this info.
3. the user confirm to sign in and bind this social info to the user found above.
LOG-1513

feat: sign in to social related user

---

packages/core/package.json
packages/core/src/include.d/koa-router.d.ts
pnpm-lock.yaml

due to the limit of TypeScript, we cannot extend existing class definitions. so this PR copies original `koa-router` types and adds additional function signatures to support more precise type definition while chaining middleware functions.
works as expected when using multiple middleware functions in one route

refactor(core): use custom `koa-router` types

---

packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/application.test.ts
packages/core/src/routes/resource.test.ts
packages/core/src/routes/role.test.ts
packages/core/src/routes/setting.test.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/status.test.ts
packages/core/src/routes/swagger.test.ts
packages/core/src/utils/test-utils.ts

Inspired by pr https://github.com/logto-io/logto/pull/272
update the requester test utils:
takes anonymousRoutes, authedRoutes, and provider as inputs. 
ut passed 
@wangsijie  cc: @logto-io/eng

test(core): update the requester test utils

---

packages/core/src/routes/setting.test.ts
packages/core/src/routes/setting.ts

Hide default id from the return value after updating global settings.
N/A

chore(core): hide settings default id

---

packages/core/src/lib/session.ts
packages/core/src/routes/session.ts

Separate passwordless flow routes.
Originally send passcode and verify passcode are integrated as a single route, this PR separates them.
Includes:
/session/sign-in/passwordless/email
/session/sign-in/passwordless/phone
/session/register/passwordless/email
/session/register/passwordless/phone
LOG-1603
N/A

feat(core): separate passwordless flow routes

---

.vscode/settings.json

enable eslint formatter on save for workspace
format on save successfully

fix: update VSCode settings to format js/ts on save

---

packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

fix(core): patch `/users/:userId` should not fail if only `name` or `avatar` is provided
None.
UT

fix(core): patch `/users/:userId` should not fail if only `name` or `avatar` is provided

---

packages/core/src/oidc/adapter.test.ts
packages/core/src/oidc/adapter.ts
packages/core/src/queries/application.test.ts
packages/core/src/queries/connector.test.ts
packages/core/src/queries/oidc-model-instance.test.ts
packages/core/src/queries/oidc-model-instance.ts
packages/core/src/queries/passcode.test.ts
packages/core/src/queries/passcode.ts
packages/core/src/queries/resource.test.ts
packages/core/src/queries/resource.ts
packages/core/src/queries/roles.test.ts
packages/core/src/queries/roles.ts
packages/core/src/queries/scope.test.ts
packages/core/src/queries/scope.ts
packages/core/src/queries/setting.test.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/queries/user-log.test.ts
packages/core/src/queries/user.test.ts
packages/core/src/queries/user.ts
packages/core/src/utils/mock.ts
packages/core/src/utils/test-utils.ts

1. add ut for logto core queries
- application
- connector
- oidc-model-instance
- passcode
- resource
- roles
- scope
- settings
- sign-in-experience
- user-log
- users
2. fix some typo: `destoryInstanceById` => `destroyInstanceById`
LOG-1531
UT case added
@logto-io/eng

test(core): add ut for queires

---

packages/console/src/App.tsx
packages/console/src/components/Sidebar/components/Item/index.tsx
packages/console/src/include.d/node.d.ts
packages/core/src/middleware/koa-spa-proxy.ts

- console: set base url when console is running under core
- console: replace `<a>` with `<Link>`
- core: check mounted apps only when no prefix is found
tested with global `pnpm dev` and `console: pnpm start`, router works as expected
@logto-io/eng

fix(console): set base url when needed

---

packages/core/src/connectors/aliyun-sms/index.ts
packages/core/src/connectors/github/index.test.ts
packages/core/src/connectors/github/index.ts

refactor(core): remove unnecessary check in github and aliyun-sms connector
- Since githubConfigGuard.safeParse can also assert it non-empty.
LOG-1619
See #321
- [comment](https://github.com/logto-io/logto/pull/321#discussion_r820367231) : Since githubConfigGuard.safeParse can also assert it non-empty, remove unnecessary empty-check.
- [comment](https://github.com/logto-io/logto/pull/321#discussion_r820330689) : Since we have the input param type guard, remove the test case of no parameter.

refactor(core): remove unnecessary check in github and aliyun-sms connector

---

package.json

Add prepare script to the logto root post-install life cycle. Simplify the steps we need to run after schema and phrases repo updates. 
Run `pnpm i` under the logto root path should run all the prepack build.  
LOG-1590
@logto-io/eng

build(core): add prepare script to the logto root postinstall life cycle

---

packages/core/src/lib/user.test.ts
packages/core/src/lib/user.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/db-entries/custom-types.ts
packages/schemas/tables/user_logs.sql

Add route POST /session/forgot-password/phone/send-passcode.
Add method to lib/user.ts which detects sign-in methods an account can use (as well as corresponding UTs).
Add 'ForgotPasswordEmail' and 'ForgotPasswordPhone' to user log type and re-generate dependent files.
LOG-1814
UT.

feat(core): add forgot password send passcode to phone route

---

packages/core/src/routes/connector.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Only allow one enabled SMS/Email connector:
1. `PATCH /connectors/:connectorId/enabled`, disable other connectors first.
2. `GET /connectors`, throw error if database data is against the rule.
@logto-io/eng

feat(core): only allow one enabled sms/email

---

packages/console/src/components/ItemPreview/index.module.scss
packages/console/src/components/ItemPreview/index.tsx
packages/console/src/pages/Applications/index.tsx

support `to` property in `<ItemPreview>` to make it a11y friendly
@logto-io/eng

refactor(console): support `to` in `<ItemPreview>`

---

.gitignore
packages/console/src/App.module.scss
packages/console/src/components/Card/index.module.scss
packages/console/src/components/TabNav/index.tsx
packages/console/src/components/Topbar/index.module.scss
packages/console/src/pages/ApiResources/index.module.scss
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.module.scss
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/Connectors/components/ConnectorRow.tsx
packages/console/src/pages/Connectors/index.module.scss
packages/console/src/pages/Connectors/index.tsx
packages/console/src/scss/normalized.scss

Fix page layout issues by adding scroll wrapper to display tables and enforcing vertical scrollbar around table content.
This layout problem is seen on multiple pages:
* Applications
* API Resources
* Connectors
Before:
After:

fix(console): page layout issues

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts

Add two routes for email-based forgot password flow:
POST /session/forgot-password/email/send-passcode
POST /session/forgot-password/email/verify-passcode-and-reset-password
LOG-1816
LOG-1817
UT.

feat(core): add email forgot password flow (send/verify passcode)

---

packages/console/src/pages/Applications/components/CreateForm/index.tsx

Fixed a mismatched form field registry. Field `description` should be registered on the description field, not the submit button.

fix(console): correct form field registry

---

packages/core/src/lib/user.test.ts
packages/core/src/lib/user.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/db-entries/custom-types.ts
packages/schemas/tables/user_logs.sql

Manually revert forgot-password-related logic as well as UTs.
This PR is used to archive the current forgot-password flow implementation. As the flow is not finalized, related cases are not clear enough at this stage, we decide to remove this part temporarily for later improvement.
LOG-1846
All UTs passed.

revert(core): manually revert forgot password logic

---

packages/console/package.json
packages/console/src/components/CodeEditor/index.module.scss
packages/console/src/components/CodeEditor/index.tsx
packages/console/src/components/Status/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
pnpm-lock.yaml

Use VSCode's editor "Monaco Editor" as our code editor and code preview with hightlight.
Monaco editor is loaded on demand, won't increse the bundle size:
before:
after:
LOG-1708
dark mode:
@demonzoo @gao-sun

feat(console): code editor component

---

packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/utilities/api.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Wrap `ky` into `api` to handle response error message automaticly:
If you don't need the toast in some situation, you can still use `ky` directly.

feat(console): wrap ky to handle response error

---

packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts

- refactor(core): rename sign-in-experience api paths from sign-in-ex to sign-in-exp
- See [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1647330937873609) on Slack
LOG-1811
---
@logto-io/eng

refactor(core): rename sign-in-experience api paths from sign-in-ex to sign-in-exp

---

packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/Input/PasswordInput.tsx
packages/ui/src/components/Input/PhoneInput.tsx
packages/ui/src/components/Input/index.module.scss
packages/ui/src/components/Passcode/index.module.scss
packages/ui/src/components/Passcode/index.test.tsx
packages/ui/src/components/Passcode/index.tsx
packages/ui/src/index.html

Add passcode input component
This component Include following feature:
- autofocus to the next input field after code input
- auto-delete the previous input field value when keep clicking on the Backspace key
- numeric input only
- navigate throw input field using ArrowLeft and ArrowRight key
- auto paste the input fields from the clipboard
- auto-update current field value when typing new chars
LOG-1766
UT cases added
test locally
@logto-io/eng

feat(ui): add passcode input component

---

packages/console/src/components/IconButton/index.tsx

Fix a bug: if set classname to "IconButton", the inner classname will be overrided.
before:
after:
@logto-io/eng

fix(console): icon button classname

---

packages/console/src/components/Button/index.module.scss
packages/console/src/components/Button/index.tsx

I set button's display to "flex" in previous PR, this will cause render problems. Now change to "inline-flex", and only apply to it if "icon" is present.
before:
after:
@logto-io/eng

fix(console): button inline flex

---

packages/console/src/components/ItemPreview/index.tsx
packages/console/src/components/UnnamedTrans/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorName.tsx

Add component to render custom translation resource object, like:
```
{
en: 'Sign In with GitHub',
'zh-CN': 'GitHub登录',
}
```
I dont use `addResourceBundle`, because i18n use "key" to do the translation, but we don't have a key in this situation, and it doesn't make sense to create a "temp key" or "hash key". Besides, the translation resource here is used only one time, for this component instance only, so add it to i18n resource is not suitable.
LOG-1845
Locally tested with existing "connectors" page.

feat(console): add component UnnamedTrans

---

packages/console/src/components/TextInput/index.module.scss
packages/console/src/scss/_colors.scss

Add readonly style for `<TextInput />`.
Readonly is different from "disabled", an input with readonly prop can still be focused.
LOG-1914

fix(console): add readonly style for text input

---

packages/core/src/connectors/wechat/index.test.ts
packages/core/src/connectors/wechat/index.ts

According to the WeChat open docs, the response of successful requests should be with code 0 (not 200).
Add comments for error handling of not providing 'openid' when requesting user information.
UT.

fix(core): fix response code for requesting WeChat APIs

---

packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/queries/sign-in-experience.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts

- refactor(core): updateDefaultSignInExperience, findDefaultSignInExperience
- refactor(core): change PATCH /sign-in-exp/:id to PATCH /sign-in-exp
According to the sign-in experience design,
**since there is only one sign-in experience per DB instance, do not require `id`.**
LOG-1941
---
@logto-io/eng

refactor(core): change PATCH /sign-in-exp/:id to PATCH /sign-in-exp

---

packages/core/src/connectors/index.test.ts
packages/core/src/connectors/index.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts
packages/core/src/utils/mock.ts

- feat(core): getEnabledSocialConnectorIds
- test(core): getEnabledSocialConnectorIds
- refactor(core): get sign-in experience
- test(core): get sign-in experience
LOG-1939
---
@logto-io/eng

refactor(core): get sign-in experience

---

packages/core/src/connectors/index.test.ts
packages/core/src/connectors/index.ts

- refactor(core): make getConnectorInstances access DB only once
- test(core): make getConnectorInstances access DB only once
- refactor(core): getConnectorInstanceByType merge .filter into .find for running in one loop
LOG-1944
---
@logto-io/eng

refactor(core): make getConnectorInstances access DB only once

---

packages/console/src/components/Card/index.module.scss
packages/console/src/components/Table/TableLoading.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/Connectors/components/ConnectorRow.tsx
packages/console/src/pages/Connectors/index.tsx
packages/console/src/pages/Users/index.tsx
packages/console/src/scss/normalized.scss

Instead of add a className to each row's first `<td>`, now using `<colgroup>` and `<col>` to control each column's width in a table together.
This PR breaks the table body scrolling feature, per offline discussion with @demonzoo we will rewrite this feature in LOG-1975.
LOG-1972
Local tested.

refactor(console): use colgroup in table

---

packages/core/src/connectors/index.test.ts
packages/core/src/connectors/index.ts
packages/core/src/queries/connector.test.ts
packages/core/src/queries/connector.ts

- refactor(core): make initConnectors check existing connectors in DB once
- refactor(core): remove unnecessary hasConnector
LOG-1944
---
@logto-io/eng

refactor(core): make initConnectors check existing connectors in DB once

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/BrandingHeader/index.tsx
packages/ui/src/components/ErrorMessage/index.tsx
packages/ui/src/components/Input/PasswordInput.test.tsx
packages/ui/src/components/Input/PasswordInput.tsx
packages/ui/src/components/Input/index.module.scss
packages/ui/src/components/Input/index.test.tsx
packages/ui/src/components/Input/index.tsx
packages/ui/src/components/TermsOfUse/index.module.scss
packages/ui/src/components/TermsOfUse/index.tsx
packages/ui/src/containers/UsernameSignin/index.module.scss
packages/ui/src/containers/UsernameSignin/index.test.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/hooks/use-api.ts
packages/ui/src/jest.setup.ts
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SignIn/index.module.scss
packages/ui/src/pages/SignIn/index.test.tsx
packages/ui/src/pages/SignIn/index.tsx
packages/ui/src/scss/_underscore.scss

Re-implement username signin page using the new added components.
1. Add UsernameSignin Container to handle the signing logic
2. Merge dark mode with light mode for now
3.  Refactor the input field that will take default HTML input props as much as possible
4. Refactor ErrorMessage component that can take LogtoErrorCode with extra data
TODO:
1. API redesign handle api error and loading status globally in PageContext
2. Input field validation, should move the validation rule to the input field scope
3. Forgot password URL
4. read terms of use settings from SignInExperience Settings
LOG-1782
ut case added test locally
@logto-io/eng

feat(ui): re-implement username signin page

---

packages/console/src/components/Table/TableLoading.module.scss
packages/console/src/components/Table/TableLoading.tsx

fix bug: ItemPreviewLoading's css has less priority than default TableLoading component.
Now set a explict class name as "rect".
@logto-io/eng

fix(console): prevent css overiding in table-loading

---

packages/console/src/hooks/use-swr-fetcher.ts
packages/console/src/pages/Users/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Extract "Total-Number" from response header to useSWR's `data`, if `page` and `page_size` is present in url.
Is unnable to get response header in useSWR directly, so we have to "break" data.
LOG-1979
Local tested.

feat(console): extract total number from headers for useSWR

---

packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/UserDetails/components/ResetPasswordForm.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/components/CreateForm/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

The react-hook-form provides a submitting form state for us, so we don't need to define a state by ourselves.
Meanwhile, if there are errors occurred during the request process, the form state, `isSubmitting`, will be set to `false` automatically.
* LOG-2008
Test In Logto Admin Console.

refactor(console): the submit state of forms

---

packages/console/src/components/TextInput/index.module.scss

fix(console): input outline should be red in the error state
LOG-1906

fix(console): input outline should be red in the error state on focused

---

packages/core/src/lib/sign-in-experience.test.ts
packages/core/src/lib/sign-in-experience.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts

Update social sign-in connector IDs only when social sign-in is enabled
LOG-2070

feat(core): update social sign-in connector IDs only when social sign-in is enabled

---

packages/console/src/components/CodeEditor/index.module.scss
packages/console/src/components/CodeEditor/index.tsx
packages/console/src/pages/GetStarted/components/Step/index.tsx

Support code editor in get-started steps.
[LOG-1682](https://linear.app/silverhand/issue/LOG-1682/support-code-editor-in-steps)

feat(console): support code editor in get-started steps

---

packages/core/src/connectors/index.test.ts
packages/core/src/connectors/index.ts
packages/core/src/connectors/utilities/index.test.ts
packages/core/src/lib/passcode.test.ts
packages/core/src/queries/connector.test.ts
packages/core/src/routes/connector.test.ts
packages/core/src/utils/mock.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/db-entries/connector.ts
packages/schemas/src/db-entries/custom-types.ts
packages/schemas/src/types/connector.ts
packages/schemas/tables/connectors.sql

Status quo: we have to query `BaseConnector.metadata.type` from the code to know the connector type.
We often just need `Connector` from DB but not `BaseConnector.metadata`, therefore we'd better be able to query connectors by `type` and `enabled` from DB.
In order to query connectors by `type` and `enabled` from DB:
- Add connector field `type` in `connectors` schema
- Sync `type` from code `BaseConnector.metadata.type` to DB `connectors.type`.
Next up:
- LOG-2074: Update connector DB queries
- LOG-2055
- LOG-2070
- LOG-2073

feat(schemas,core,phrases)!: add type to connector schema and sync to DB

---

packages/console/src/components/CodeEditor/index.tsx

Page scroll should not be affected when scrolling on top of a Monaco editor.
Previously if you scroll your mouse wheel on a Monaco editor, it only scrolls the editor content and consumes the scrolling event. So the page scroll would not work unless you move the mouse cursor out of the editor.
[LOG-2098](https://linear.app/silverhand/issue/LOG-2098/fix-monaco-editor-consumes-scroll-events)

fix(console): page scroll should work when scrolling on monaco editor

---

packages/schemas/tables/connectors.sql

Default `enabled` value of newly added connectors should be FALSE.
UT.

fix(core): fix default enable value of new connectors

---

packages/core/src/routes/sign-in-experience.guard.test.ts
packages/core/src/utils/mock.ts

Test terms-of-use and language-info guards for sign-in experience
LOG-2095

test(core): guard terms of use and language info

---

packages/console/public/get-started/application/react/en/step3.md
packages/console/public/get-started/application/react/en/step4.md
packages/console/public/get-started/application/react/zh-CN/step3.md
packages/console/public/get-started/application/react/zh-CN/step4.md
packages/console/src/components/FormField/index.tsx
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/Applications/components/GetStartedModal/index.tsx
packages/console/src/pages/Applications/components/LibrarySelector/index.module.scss
packages/console/src/pages/GetStarted/components/CodeComponentRenderer/index.tsx
packages/console/src/pages/GetStarted/components/Step/index.module.scss
packages/console/src/pages/GetStarted/components/Step/index.tsx
packages/console/src/pages/GetStarted/hooks/index.ts
packages/console/src/pages/GetStarted/index.tsx
packages/console/src/types/get-started.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

* Support form field inputs and form validation in get-started steps.
* Scroll to the first step that contains invalid fields on form submit
[LOG-1683](https://linear.app/silverhand/issue/LOG-1683/support-input-form-fields)
https://user-images.githubusercontent.com/12833674/161924744-0d08dfdc-1170-4748-9e1f-fd3851f261e6.mov

feat(console): support input form fields in get-started steps

---

packages/core/src/oidc/init.ts

Fix extraClientMetadata properties
- CustomClientMetadataKey: Its keys are different from its values.
```ts
export enum CustomClientMetadataKey {
CorsAllowedOrigins = 'corsAllowedOrigins',
IdTokenTtl = 'idTokenTtl',
RefreshTokenTtl = 'refreshTokenTtl',
}
```
LOG-2102

fix(core): extraClientMetadata properties

---

packages/console/src/components/Button/index.module.scss

Align with new design, set Button's default border-color to `color-component-border`.

fix(console): change button border color to color-component-border

---

packages/console/src/components/Drawer/index.module.scss

Drawer component is using a background color that no longer exists in the code base. Hence, replace it with the correct color variable.

fix(console): drawer component background

---

packages/console/src/components/RadioGroup/index.tsx
packages/console/src/pages/Connectors/components/CreateForm/index.tsx
packages/console/src/pages/Connectors/components/GetStartedModal/index.module.scss
packages/console/src/pages/Connectors/components/GetStartedModal/index.tsx
packages/console/src/pages/Connectors/index.tsx
packages/console/src/pages/GetStarted/components/Step/index.module.scss
packages/console/src/pages/GetStarted/components/Step/index.tsx
packages/console/src/pages/GetStarted/index.tsx
packages/console/src/scss/_colors.scss
packages/core/src/connectors/github/README.md
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Implement "get-started" page on creating connectors
[LOG-1943](https://linear.app/silverhand/issue/LOG-1943/connector-getstarted-page)

feat(console): connectors get-started page

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/ui/src/apis/index.test.ts
packages/ui/src/apis/register.ts
packages/ui/src/apis/sign-in.ts
packages/ui/src/apis/utils.ts
packages/ui/src/containers/PasscodeValidation/index.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/SignInMethodsLink/index.tsx
packages/ui/src/pages/Passcode/index.tsx
packages/ui/src/pages/Register/index.test.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SecondarySignIn/index.test.tsx
packages/ui/src/pages/SecondarySignIn/index.tsx
packages/ui/src/types/index.ts

Replace phone signin method with sms
Per our offline discussion, align sms as the phone passwordless signInMethod naming. 
UT case passed
test locally on demo app
@logto-io/eng

refactor(core): phone method refactor

---

packages/ui/src/App.tsx
packages/ui/src/__mocks__/logto.tsx
packages/ui/src/apis/settings.ts
packages/ui/src/apis/utils.ts
packages/ui/src/components/AppContent/index.tsx
packages/ui/src/containers/PasscodeValidation/index.test.tsx
packages/ui/src/containers/PasscodeValidation/index.tsx
packages/ui/src/containers/SignInMethodsLink/index.tsx
packages/ui/src/hooks/page-context.ts
packages/ui/src/hooks/use-theme.ts
packages/ui/src/pages/Passcode/index.test.tsx
packages/ui/src/pages/Passcode/index.tsx
packages/ui/src/pages/Register/index.test.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SecondarySignIn/index.test.tsx
packages/ui/src/pages/SecondarySignIn/index.tsx
packages/ui/src/types/index.ts
packages/ui/src/utils/sign-in-experience.test.ts
packages/ui/src/utils/sign-in-experience.ts

Load sign-in experience settings from the server ahead
SSR takes some effort and needs to figure out a better solution.  Add the client-side request ahead. 
- load theme settings from the sign-in experience return value
- rename channel param to method to better match the experience settings naming convention
- keep the AppContent component clean move the context to App top level
test locally 
@logto-io/eng

feat(ui): load sign-in experience settings from server

---

packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts

Fix sign-in settings api route not-authorized bug
test locally 
@logto-io/eng

fix(core): fix sign-in settings api route

---

packages/console/src/components/AppContent/index.tsx
packages/console/src/components/ErrorBoundary/index.module.scss
packages/console/src/components/ErrorBoundary/index.tsx

Add error boundary page in order to improve error handling (no blank page on app crash)
[LOG-1880](https://linear.app/silverhand/issue/LOG-1880/error-handling)

feat(console): add react error boundary

---

packages/console/src/components/ErrorBoundary/index.module.scss
packages/console/src/components/ErrorBoundary/index.tsx

* Fixed error boundary page content alignment. Image and title should be center aligned... Issue was caused by accidentally committed local testing code
* Fixed the error message localization issue

fix(console): center align image and error message in error boundary

---

packages/console/src/components/AppContent/index.tsx
packages/console/src/components/LogtoLoading/index.module.scss
packages/console/src/components/LogtoLoading/index.tsx
packages/console/src/pages/Callback/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Drafted loading state animation page when logto SDK state is loading or redirecting back to main app
_Note: The current page is just a placeholder component. Will update styles once we receive a newer design_
[LOG-1879](https://linear.app/silverhand/issue/LOG-1879/loading-state-animations)

feat(console): draft logto loading state animation page

---

packages/core/src/routes/sign-in-experience.branding.guard.test.ts
packages/core/src/utils/regex.test.ts

- Separate the color validation cases from tests of sign-in experience
LOG-2138

test(core): separate the color validation cases from tests of sign-in experience

---

packages/console/src/components/Button/index.module.scss
packages/console/src/scss/_colors.scss

Update button hover and pressed state colors, per the latest UX design.
_Note: This PR only updates colors for "primary" and "danger" buttons_
[LOG-2227](https://linear.app/silverhand/issue/LOG-2227/update-button-hover-and-pressed-state-colors)

fix(console): button hover and pressed state colors

---

packages/core/src/middleware/koa-user-log.test.ts
packages/core/src/middleware/koa-user-log.ts

#587 → #588 (current) → #590
Rename koa-user-log types and functions to avoid naming conflicts
e.g. `insertLog` in #587 
LOG-2238

refactor(core): rename koa-user-log types and functions to avoid naming conflicts

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/routes/sign-in-experience.guard.test.ts
packages/phrases/src/index.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/seeds/sign-in-experience.ts

- Move `Language` enum from `schemas` to `phrases`
- Fix `Language.Chinese` value from `zh-cn` → `zh-CN`
Reference: 
- Slack thread [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1650440942212639)
- http://www.i18nguy.com/unicode/language-identifiers.html
None

refactor(phrases,schemas): move language enum and fix Lanugage.Chinese value

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/pages/Consent/index.module.scss
packages/ui/src/pages/Consent/index.tsx
packages/ui/src/pages/SignIn/index.test.tsx
packages/ui/src/pages/SignIn/index.tsx

Load branding info from settings.
Update the sign-in home page style, load header info from sign-in experience settings.
Update the consent page, read the logo from sign-in experience settings.
LOG-2163
Test locally 
@logto-io/eng

refactor(ui): load branding info from settings

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/__mocks__/RenderWithPageContext/SettingsProvider.tsx
packages/ui/src/__mocks__/logto.tsx
packages/ui/src/components/ConfirmModal/index.tsx
packages/ui/src/components/TermsOfUse/index.test.tsx
packages/ui/src/components/TermsOfUse/index.tsx
packages/ui/src/components/TermsOfUseModal/index.module.scss
packages/ui/src/components/TermsOfUseModal/index.test.tsx
packages/ui/src/components/TermsOfUseModal/index.tsx
packages/ui/src/components/TextLink/index.tsx
packages/ui/src/containers/CreateAccount/index.test.tsx
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/TermsOfUse/index.tsx
packages/ui/src/containers/TermsOfUse/intext.test.tsx
packages/ui/src/containers/UsernameSignin/index.test.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/hooks/use-terms.ts

This PR contains the refactor of terms of use.
1. Since both social connectors and other sign-in methods share the same `Terms of Use` check status, we need to have a centralized place to manage the `Terms of Use` UI component. So on the previous PR we add a global `termsAgreement` status to the `PageContext`. Thus a new container that loads and set global termsAgreement status is needed. 
2. The use experience is updated. Instead of old error message, we will show a new `ConfirmModal` to users and ask them to confirm the Terms of Use agreement.  We need to update and embed the whole flow within the same place. In this new container. 
Design:
Before:
After:
1. New Phrases for the terms Modal
2. New mock SettingsProvider to provide mock SignInExperienceSettings for the test component
3. …

refactor(ui): refactor terms of use

---

packages/ui/src/__mocks__/RenderWithPageContext/SettingsProvider.tsx
packages/ui/src/components/TermsOfUseModal/index.module.scss
packages/ui/src/containers/CreateAccount/index.test.tsx
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/TermsOfUse/intext.test.tsx
packages/ui/src/containers/UsernameSignin/index.test.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/hooks/use-social.ts
packages/ui/src/hooks/use-terms.ts

Follow the latest design: Replace old `TermsOfUse` component in all sign-in/register forms with the new implemented `TermsOfUser` container.  
Run `termsValidation` logic from the `useTerms` hook  before submit.
Add the `termsValidation` logic be for `invokeSocialSignIn`
LOG-2258
UT case updated
test locally
@logto-io/eng

refactor(ui): replace termsOfUse Component with Container

---

packages/core/src/env-set/create-pool-by-env.ts
packages/core/src/env-set/oidc.ts
packages/core/src/env-set/parameters.ts
packages/core/src/env-set/password.ts

with this option Logto will not inquire user to take action if required env not found
LOG-2254

refactor(core): add `--no-inquiry` option

---

package.json
packages/core/src/env-set/append-dot-env.ts
packages/core/src/env-set/create-pool-by-env.ts
packages/core/src/env-set/dot-env.ts
packages/core/src/env-set/oidc.ts
packages/core/src/env-set/parameters.ts
packages/core/src/env-set/password.ts
packages/core/src/index.ts
packages/core/src/middleware/koa-spa-proxy.ts

allow `[npm/pnpm/yarn] start` from project root by:
- add `--from-root` option to change working directory
- adjust UI proxy
also clean up unnecessary code when reading private key
LOG-2259
start from project root, AC ok

refactor: allow start from project root

---

packages/core/src/env-set/oidc.ts

since `dotenv` supports multi-line env now, we bring back this as it can also be good for docker environment
LOG-2268

refactor(core): allow read private key from env

---

packages/phrases/src/locales/zh-cn.ts
packages/ui/src/__mocks__/logto.tsx
packages/ui/src/components/ConfirmModal/index.module.scss
packages/ui/src/components/ConfirmModal/index.tsx
packages/ui/src/components/Input/phoneInput.module.scss
packages/ui/src/containers/Passwordless/index.module.scss
packages/ui/src/containers/SignInMethodsLink/index.tsx
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.test.tsx
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
packages/ui/src/containers/SocialSignIn/SocialSignInPopUp.tsx
packages/ui/src/containers/UsernameSignin/index.module.scss
packages/ui/src/hooks/use-social.ts
packages/ui/src/pages/SignIn/index.module.scss
packages/ui/src/pages/SignIn/index.test.tsx
packages/ui/src/pages/SignIn/index.tsx
packages/ui/src/pages/SignIn/registry.tsx
packages/ui/src/scss/modal.module.scss
packages/ui/src/types/index.ts
packages/ui/src/utils/sign-in-experience.ts

Render page using sign-in exp settings
This PR includes following updates:
1. Fix the CN phrase sign-in methods link content bug
2. Make confirm modal index higher than social popUp
3. Sign-In input fields styling updates
4. Update PrimarySocialSignInr and SecondarySocialSignIn to load the social connectors from the global sign-in experience settings provided by `useSocial` hook 
5. update useSocial hook to load the social connector's settings from page context and merge with the native supported ones in any. 
6. Add the `SocialPopUp` modal to the `SecondarySocialSignIn` container. Close the modal when `invokeSocialSignIn` request returns. 
7.  Create the PrimarySection & SectiondarySection render components to provide the dynamic sign-in page content render logic. 
log-2164
test locally …

feat(ui): render page using sign-in exp settings

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/App.tsx
packages/ui/src/apis/index.test.ts
packages/ui/src/apis/social.ts
packages/ui/src/components/NavBar/index.module.scss
packages/ui/src/components/NavBar/index.tsx
packages/ui/src/containers/SocialCreateAccount/index.module.scss
packages/ui/src/containers/SocialCreateAccount/index.test.tsx
packages/ui/src/containers/SocialCreateAccount/index.tsx
packages/ui/src/pages/SocialRegister/index.module.scss
packages/ui/src/pages/SocialRegister/index.test.tsx
packages/ui/src/pages/SocialRegister/index.tsx

add social sign-in binding page after success social sign-in but no account found in logto
todo: 
1. sign-in flow redesign, need to create different sign-in button based on user-exp settings
2. detect the related user info format and blur the phone/email address
log-1797
ut case added
test locally
@logto-io/eng

feat(ui): add social sign-in binding page

---

packages/console/src/components/CopyToClipboard/index.module.scss

Remove padding in CopyToClipboard when varient is not contained.
before
after

fix(console): remove plain CopyToClipboard padding

---

packages/ui/src/apis/index.test.ts
packages/ui/src/apis/sign-in.ts
packages/ui/src/containers/PasscodeValidation/index.test.tsx
packages/ui/src/containers/PasscodeValidation/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/SocialCreateAccount/index.module.scss
packages/ui/src/containers/SocialCreateAccount/index.test.tsx
packages/ui/src/containers/SocialCreateAccount/index.tsx
packages/ui/src/containers/UsernameSignin/index.test.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/hooks/use-bind-social.ts
packages/ui/src/types/index.ts
packages/ui/src/utils/index.test.ts
packages/ui/src/utils/index.ts

add bind social account flow
redesign the social bind account page, add secondary sign-in links
Pass down the socialToBind context as queryParams
invoke bind social API in all sign-in API methods if in the socialBind flow, by detecting the social To Bind query parameter.
test locally
ut case added
@logto-io/eng

feat(ui): add bind social account flow

---

install.js
package.json

- provide a script to download and run Logto distribution
- change `start` script in root to set `NODE_ENV=production` by default
LOG-2135
after changing `package.json`

chore: download and install logto

---

packages/core/src/database/utils.test.ts
packages/core/src/database/utils.ts
packages/core/src/queries/oidc-model-instance.test.ts

Update timestamp field with millisecond precision in SQL
Past:
After fixing:
LOG-2310

fix(core): update timestamp field with millisecond precision

---

packages/connector-wechat-native/README.md
packages/connector-wechat-native/docs/config-template.md
packages/connector-wechat-native/jest.config.ts
packages/connector-wechat-native/package.json
packages/connector-wechat-native/src/constant.ts
packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat-native/src/mock.ts
packages/connector-wechat-native/tsconfig.base.json
packages/connector-wechat-native/tsconfig.build.json
packages/connector-wechat-native/tsconfig.json
packages/connector-wechat-native/tsconfig.test.json
packages/connector-wechat/README.md
packages/connector-wechat/docs/config-template.md
packages/connector-wechat/jest.config.ts
packages/connector-wechat/package.json
packages/connector-wechat/src/constant.ts
packages/connector-wechat/src/index.test.ts
packages/connector-wechat/src/index.ts
packages/connector-wechat/src/mock.ts
packages/connector-wechat/tsconfig.base.json
packages/connector-wechat/tsconfig.build.json
packages/connector-wechat/tsconfig.json
packages/connector-wechat/tsconfig.test.json
pnpm-lock.yaml

Wrap WeChat connectors (both web and native).
There is only slight different between native and web WeChat connectors: getAuthorizationUri() and its corresponding input parameters (see in /src/connector-wechat(-native)/constant.ts). Other parts are the same.
The implementation tried to make these two connectors less dependent and developers of Logto can install only one of them.
UTs.

feat(core): wrap wechat connector

---

packages/ui/package.json
packages/ui/src/components/AppContent/index.tsx
pnpm-lock.yaml

add debounced loading
add debounced loading. Avoid loading layer popup if the reqest response in 400ms.
log-2244
test locally
@logto-io/eng

refactor(ui): add debounced loading

---

packages/ui/jest.config.ts
packages/ui/src/App.tsx
packages/ui/src/pages/Passcode/index.test.tsx
packages/ui/src/pages/Passcode/index.tsx
packages/ui/src/pages/Register/index.test.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SecondarySignIn/index.test.tsx
packages/ui/src/pages/SecondarySignIn/index.tsx
packages/ui/src/pages/SocialRegister/index.test.tsx
packages/ui/src/pages/SocialRegister/index.tsx

Per @wangsijie suggestion, the /404 path should be removed. Instead of redirect user to the /404 route, should render the NotFound page directly under the current page
Show error toast at the Passcode page if no email or phone is passed to the page
LOG-2337
test locally
ut added
@wangsijie  cc: @logto-io/eng

refactor(ui): remove /404 path

---

packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx

Fix connector details page footer display, make the content's flex to "1", in order to make the footer always "stick" to the bottom.
N/A
Local tested.

fix(console): connector details save changes footer

---

packages/console/src/App.tsx

Fix an unexpected 401 response on settings API call, if user is not authenticated yet.

fix(console): call settings API after user authentication

---

packages/console/src/components/MultiTextInput/DeleteConfirm.tsx
packages/console/src/components/MultiTextInput/DeletionReminder.tsx
packages/console/src/components/MultiTextInput/index.module.scss
packages/console/src/components/MultiTextInput/index.tsx
packages/console/src/pages/ApplicationDetails/components/Settings.tsx
packages/console/src/pages/Guide/components/MultiTextInputField/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

feat(console): multi-text-input delete reminder
Refer to the design doc:
https://www.figma.com/file/iroUuWbeZ9fqcqXNwqYZai/Admin-Console-UI?node-id=2371%3A51066
* LOG-2306

feat(console): multi-text-input delete reminder

---

packages/console/src/mdx-components/Tabs/index.module.scss
packages/console/src/mdx-components/Tabs/index.tsx

Improve tabs component used in mdx files, in order to enable tab switches in guide steps, e.g. SDK integration guide - step 1.

refactor(console): improve tabs used in mdx files

---

packages/phrases/src/locales/en.ts
packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/ConfirmModal/index.module.scss
packages/ui/src/components/ConfirmModal/index.tsx
packages/ui/src/components/Drawer/index.module.scss
packages/ui/src/components/Drawer/index.tsx
packages/ui/src/components/Input/index.module.scss
packages/ui/src/components/Input/index.tsx
packages/ui/src/components/NavBar/index.module.scss
packages/ui/src/components/Passcode/index.module.scss
packages/ui/src/components/Passcode/index.tsx
packages/ui/src/containers/CreateAccount/index.module.scss
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/SignInMethodsLink/index.module.scss
packages/ui/src/pages/Callback/index.module.scss
packages/ui/src/pages/Callback/index.tsx
packages/ui/src/scss/modal.module.scss
packages/ui/src/scss/normalized.scss

1. Update the divider Or content to lowercase
2. Set the input field container height fixed with overflow hidden. As in safari input field,[ line-height is differ](https://stackoverflow.com/questions/42529257/input-text-height-is-broken-in-safari) 
3. Update the font-family settings that fix the passcode secret mast dot size and styling
5. Disable all elements on-touch event shadow effect
6. Update the modal padding space
7. Adjust the text link underline space
9. Update the NavBar icon fill color use the base text color
10. Add border-radius to the drawer element
11. Prevent body scall when modal occurred
12. Adjust the link size within hint text content.
13. Callback Page layout redesign
LOG-2367
test locally
@logto-io/eng

refactor(ui): main flow ui refine part 2

---

packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
packages/ui/src/hooks/use-api.ts
packages/ui/src/hooks/use-social.ts
packages/ui/src/include.d/global.d.ts

fix social native interaction bug
1. rename the `supportedSocialConnectors` to `supportedSocialConnectorIds` according to the latest SDK code
2. refactor the invokeSocialSignInHandler callback method. Simply replace the original `redirectTo` URL is buggy. Hard code the URL for native use only. 
test locally.
@logto-io/eng

fix(ui): fix social native interaction bug

---

packages/console/src/hooks/use-configs.ts
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/Connectors/components/GuideModal/index.tsx
packages/console/src/pages/GetStarted/index.tsx
packages/console/src/pages/SignInExperience/components/Welcome.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/core/src/__mocks__/index.ts
packages/core/src/routes/setting.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/seeds/setting.ts

Support persisting "get-started" task progress in Admin Console settings config
[LOG-2403](https://linear.app/silverhand/issue/LOG-2403/update-server-api-to-support-persisting-get-started-progress-in-ac)

feat(console): support persisting get-started progress in settings config

---

packages/console/src/components/CodeEditor/index.tsx

Resolve JavaScript warning reported in code editor component

fix(console): resolve js warning reported in code editor component

---

packages/console/src/scss/_colors.scss
packages/console/src/scss/_underscore.scss

Provide a SCSS mixin that offers page skeleton animation effects
https://user-images.githubusercontent.com/12833674/168198738-d8306f42-e54d-436d-bf6f-f6126d0086ba.mov
https://user-images.githubusercontent.com/12833674/168202126-26f0e1e4-28fa-4ed5-a45a-bd3f78197803.mov
Will add skeleton to each page in a follow-up task. [LOG-2423](https://linear.app/silverhand/issue/LOG-2423/add-page-skeleton-for-each-page-that-loads-data-on-init)

feat(console): page skeleton animation mixin

---

packages/console/package.json
packages/console/src/App.tsx
packages/console/src/components/AppContent/components/Sidebar/components/Item/index.module.scss
packages/console/src/components/Button/index.module.scss
packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/components/ItemPreview/index.module.scss
packages/console/src/components/LinkButton/index.module.scss
packages/console/src/components/TabNav/TabNavItem.module.scss
packages/console/src/components/TextButton/index.module.scss
packages/console/src/mdx-components/Tabs/index.module.scss
packages/console/src/pages/Applications/components/GuideModal/index.module.scss
packages/console/src/pages/GetStarted/index.module.scss
packages/console/src/scss/_colors.scss
pnpm-lock.yaml

* Adjust dark theme styles according to latest UX design
* Included `Roboto Mono` google font and used for ID display

refactor(console): adjust dark theme styles per updated UX design

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/components/Button/SocialIconButton.module.scss
packages/ui/src/components/Button/SocialLinkButton.module.scss
packages/ui/src/components/Button/SocialLinkButton.tsx
packages/ui/src/components/Button/index.module.scss
packages/ui/src/components/Button/index.tsx
packages/ui/src/components/Checkbox/index.tsx
packages/ui/src/components/ConfirmModal/AcModal.tsx
packages/ui/src/components/ConfirmModal/Acmodal.module.scss
packages/ui/src/components/ConfirmModal/MobileModal.module.scss
packages/ui/src/components/ConfirmModal/MobileModal.tsx
packages/ui/src/components/ConfirmModal/index.tsx
packages/ui/src/components/ConfirmModal/type.ts
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
packages/ui/src/containers/SocialSignIn/index.module.scss
packages/ui/src/scss/modal.module.scss

button and confirm modal desktop styling
1. adjust the socialButton style
2. Add the desktop button styling 
3, add AcModal for desktop-style confirm modal,  while keep the mobile modal
log-2424
test locally
@logto-io/eng

style(ui):  button & confirm modal

---

packages/console/src/components/AppContent/index.module.scss
packages/console/src/scss/normalized.scss

Refine scrollbar styles and adjust positions
* Detail page scrollbar should stick to the very right of the page
* Customized scrollbar track and thumb
https://www.figma.com/file/bcSRcMyKEQc0c7k7QfP9fG/%F0%9F%AA%90-%5BWeb%5D-AC-Design-System?node-id=1588%3A8826

refactor(console): refine scrollbar styles and positions

---

packages/console/src/components/CodeEditor/index.module.scss
packages/console/src/components/CodeEditor/index.tsx

* Fixed an issue that long text in code editor did not wrap, so user was not able to see the whole content.
* Use `Roboto Mono` font face in editor

fix(console): long text should wrap in code editor

---

packages/core/src/app/init.ts
packages/core/src/middleware/koa-client-session-guard.test.ts
packages/core/src/middleware/koa-client-session-guard.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/App.tsx
packages/ui/src/pages/ErrorPage/index.test.tsx
packages/ui/src/pages/ErrorPage/index.tsx

Add session guard to ui page
- add session check guard to UI page request only
- redirect to the unknonwn-session page if no session is found
test locally 
ut case added
@logto-io/eng

refactor(ui): add session guard to ui page

---

packages/ui/src/components/TextLink/index.tsx
packages/ui/src/pages/SignIn/registry.tsx

Bug fixing. CreateAccount link uses href to navigate which causes an unexpected page to reload.  Apply the react-router link instead. 
log-2448
test locally
@logto-io/eng

fix(ui): fix create account page reload issue

---

packages/console/src/components/AppContent/index.module.scss
packages/console/src/components/Drawer/index.module.scss
packages/console/src/pages/SignInExperience/index.module.scss

Add min-width and max-width to  center stage page contents, especially the max-width. This will improve the overall user experience in extra wide screens, as the content is still kept in the central part of the screen.

style(console): add min & max widths to center stage page contents

---

packages/console/src/pages/SignInExperience/components/GuideModal.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/schemas/src/foundations/jsonb-types.ts

Align usage of `customizeSignInExperience` in settings.adminConsole.
Share this variable for "Get Started" and "Guide Modal in sign in experience".
@demonzoo 
Local tested.

fix(console): align usage of customizeSignInExperience

---

packages/ui/src/apis/index.test.ts
packages/ui/src/apis/register.ts
packages/ui/src/apis/sign-in.ts

Add default success true for no response api
Fix bug send passcode API success, front end does not redirect to the passcode validation page. 
As UI subscribes to the API result mutation to trigger the next step. Need to provide a default success result.
Also fix a API params name miss align issue:
passcode -> code
test locally
@wangsijie

fix(ui): add default success true for no response api

---

packages/console/src/hooks/use-api.ts
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/index.tsx
packages/console/src/pages/Settings/index.tsx
packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsPreview.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/UserDetails/components/UserConnectors.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/index.tsx

Since not all error object has `body` prop (for example a canceled request), we need to improve the `RequestError` type and change `body` to optional.
This way, we can improve error handling in each page, in order to make the app not crash in case there is no error body returned.
[LOG-2489](https://linear.app/silverhand/issue/LOG-2489/improve-requesterror-type-make-body-optional)

fix(console): improve swr error handling to avoid app crash

---

packages/console/src/pages/SignInExperience/components/Preview.tsx
packages/ui/src/App.tsx
packages/ui/src/components/AppContent/index.tsx
packages/ui/src/components/Checkbox/index.tsx
packages/ui/src/components/ConfirmModal/AcModal.tsx
packages/ui/src/components/ConfirmModal/index.tsx
packages/ui/src/components/NavBar/index.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.tsx
packages/ui/src/hooks/use-api.ts
packages/ui/src/hooks/use-page-context.ts
packages/ui/src/hooks/use-platform.ts
packages/ui/src/hooks/use-preview.ts
packages/ui/src/hooks/use-theme.ts
packages/ui/src/pages/SocialRegister/index.tsx
packages/ui/src/types/index.ts
packages/ui/src/utils/sign-in-experience.ts

Implement preview mode and integrate with Admin Console
1. implement `usePreview` hook parse preview and config from QueryParams
2. Add `platform` state to the PageContext so it can be applied as the SSO everywhere across the site components.
3. if is preview mode instead of query from API, get settings from qs config
4. if is preview mode read and apply the ThemeMode from qs config
5. if is preview mode overwrite the default isMobile detection in PageContext
6. if is preview mode, prevent all useApi request
https://user-images.githubusercontent.com/36393111/168736851-319ea314-e01c-493f-bdc1-5fd58d87c6e6.mp4
TODO: social connectors @wangsijie 
log-2450
test locally
@logto-io/eng

feat(ui): implement preview mode

---

packages/console/src/pages/SignInExperience/components/GuideModal.module.scss
packages/console/src/pages/SignInExperience/components/GuideModal.tsx
packages/console/src/pages/SignInExperience/components/Preview.module.scss
packages/console/src/pages/SignInExperience/components/Preview.tsx

Add preview component to GuideModal in sign in experience. Preview is an existing component, and its final styles is not set yet.

feat(console): add preview in guide modal

---

packages/console/src/hooks/use-connector-groups.ts
packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsPreview.tsx
packages/console/src/pages/SignInExperience/utilities.ts
packages/console/src/types/connector.ts
packages/core/src/__mocks__/connector.ts
packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/lib/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/core/src/routes/sign-in-experience.guard.test.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/seeds/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql
packages/ui/src/__mocks__/logto.tsx

In "sign in experience setup", as for connectors, we don't care about `platform`, we are actually sorting and setting connectors by `target`.
So change `socialConnectorIds` to `socialConnectorTargets`, when requesting settings (in UI), map targets to related connectors.
LOG-2438
Pass all tests, and local tested:

feat(core,console): social connector targets

---

packages/phrases/src/locales/en.ts
packages/ui/src/containers/PasscodeValidation/index.tsx

Fix countdown bug. 
Issue: the `restart` method return by useTimer is not wrapped up in useCallback hook, so re-initialized every time when timer is reset. Which cause infinite call within the useEffect event. 
Instead of using useEffect to handle the resend passcode flow, simply provide a synchronized useCallback method.  Handler the result synchronizly. 
log-2529
test locally
@logto-io/eng

fix(ui): fix countdown bug

---

packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/AppContent/index.tsx
packages/ui/src/scss/_desktop.scss
packages/ui/src/scss/_mobile.scss

Add global primary color settings. So we can easily sync primary color in the preview mode for now. Still WIP, overall color theme update need to be refined after design update. 
test locally
@logto-io/eng

feat(ui): add global primary color settings

---

packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/components/Dropdown/DropdownItem.module.scss
packages/console/src/components/Dropdown/index.module.scss
packages/console/src/components/Dropdown/index.tsx
packages/console/src/components/Index/index.module.scss
packages/console/src/components/ModalLayout/index.module.scss
packages/console/src/components/RadioGroup/index.module.scss
packages/console/src/components/Select/index.module.scss
packages/console/src/components/TextButton/index.module.scss
packages/console/src/components/TextInput/index.module.scss
packages/console/src/components/Tooltip/index.module.scss
packages/console/src/pages/Applications/components/CreateForm/index.module.scss
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/GetStarted/components/GetStartedProgress/index.module.scss
packages/console/src/scss/_colors.scss
packages/console/src/scss/modal.module.scss

Improve dark theme styles
* dropdown components
* popup modals
* tooltips
* misc others

refactor(console): improve dark theme styles

---

packages/core/src/routes/init.ts
packages/core/src/routes/session.test.ts
packages/core/src/routes/session.ts
packages/core/src/routes/sign-in-settings.test.ts
packages/core/src/routes/sign-in-settings.ts

Move GET /sign-in-settings from sessionRouter to signInSettingsRouter
LOG-2441

refactor(core): move GET /sign-in-settings out of sessionRouter

---

packages/core/src/oidc/init.ts

per [offline disscussion](https://www.notion.so/silverhand/OIDC-Provider-d532ae5b67fb4beea1bb85450a8dca1b#10c1459996824ecba7a9286a7ed84964), we don't need this feature in v1.
* LOG-2554
1. UT
2. The introspection configs are not included in the OIDC config.

feat(core): disable introspection feature

---

packages/core/src/routes/session.ts

Remove SignInSocial log from POST /session/sign-in/social
and keep SignInSocial log only in the new route POST /session/sign-in/social/auth
See Slack thread [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1652937521361529)
LOG-2361
LOG-2561

refactor(core): remove SignInSocial log from POST /session/sign-in/social

---

packages/ui/package.json
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn.test.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn.test.tsx
packages/ui/src/containers/TermsOfUse/index.tsx
packages/ui/src/containers/TermsOfUsePromiseModal/index.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/hooks/use-page-context.ts
packages/ui/src/hooks/use-social.ts
packages/ui/src/hooks/use-terms.ts
packages/ui/src/pages/SignIn/index.test.tsx
pnpm-lock.yaml

Refactor terms modal as a promisified function
**Previously:**
`TermsModal` is a standalone `ReactModal` component bundled with `TermsOfUse` Component. Controllable throw PageContext's `showTermsModal` and `setShowTermsModal`.
Each sign-in endpoint will call `termsValidation` sync method to check whether the global `TermsOfUse` status is checked, if not, show the TermsModal and return directly.  When the user confirms the `TermsModal` it will set the global `TermsOfUse` status to true, then do nothing. 
**New Expectations:**
After the user confirms the `TermsModal`, it should not only check the global `TermsOfUse` status bug but also proceed with the sign-in request directly. 
**Solution**
Making the `termsValidation` method as an async Promise.  Wait for the modal result. If resolved …

refactor(ui): refactor terms modal as a promisified function

---

packages/ui/src/hooks/use-social.ts
packages/ui/src/pages/SignIn/index.tsx
packages/ui/src/pages/SignIn/registry.tsx
packages/ui/src/utils/sign-in-experience.ts

Hide social signin method if connectors are empty
Social Connectors are filtered in the useSocial hook which is applied within each social signin method containers. When social connectors are empty, terms of use component and divider component are still shown. 
Move the filter logic at the parse settings data level. Which makes sure whatever is stored in pageContext is filtered.  If connectors are empty, do not show the social section at all. 
Social as secondary if social connectors are empty:
Social as Primary if social connectors are empty:
log-2449
test locally
@logto-io/eng

fix(ui): hide social signin method if connectors are empty

---

packages/core/src/app/init.ts
packages/core/src/middleware/koa-proxy-guard.test.ts
packages/core/src/middleware/koa-proxy-guard.ts

Empty path should redirect to the console page.
Rename the koa-client-session-guard to koa-proxy-guard. 
Add console redirect if empty path. 
log-2597
test locally
UT passed
@logto-io/eng

feat(core): empty path sould redirect to the console page

---

packages/console/src/pages/SignInExperience/components/Preview.tsx
packages/ui/src/App.module.scss
packages/ui/src/App.tsx
packages/ui/src/components/AppContent/index.module.scss
packages/ui/src/components/AppContent/index.tsx
packages/ui/src/hooks/use-api.ts
packages/ui/src/hooks/use-page-context.ts
packages/ui/src/hooks/use-preview.ts
packages/ui/src/hooks/use-theme.ts

Use postMessage on preview.
1. Replace iframe URL config qs with the post message methods. 
- Add postMessage event on AC to pass the config 
- Add message event listener on UI to pick up the config updates
2. Update the usePreview hook. Dynamically update all the settings.
3. Remove the preview useApi hook blocker
4. Add pointer-events none styling at main element under preview mode 
https://user-images.githubusercontent.com/36393111/169834116-0a0d5e9b-a389-4bbe-a900-8fcf66c32247.mp4
log-2591
test locally
@logto-io/eng

refactor(ui): use postMessage on preview

---

packages/core/src/middleware/koa-auth.test.ts
packages/core/src/middleware/koa-auth.ts
packages/core/src/oidc/init.ts

1. Add extra roles claims to the access_token
2. validate if roles exist and include admin role in koaAuth middleware
This solution should be optimized once we have rbac feature implemented. As it should be controlled through scopes only.
log-2598
test locally
@logto-io/eng  @gao-sun @wangsijie

feat(core): add admin role validation to the koaAuth

---

packages/connector-github/src/index.ts

Our GitHub universal sign-in flow will be failed when the user info response contains a `null` value.
N/A
UT

fix(connector-github): convert `null` value to `undefined` in user info response

---

packages/core/src/lib/session.ts
packages/core/src/routes/session.ts

Flow: bind a social account to existing user (sign in with other methods).
The social info is stored in session, after signing in with other methods, those info will be overwritten, causing a "session not found" error. (Please see LOG-2685 for details)
Now change to "merge" and fixed this issue.
Local tested with account "xyj".
@logto-io/eng

fix(core): prevent session lost for bind social

---

packages/console/src/pages/UserDetails/index.module.scss
packages/console/src/pages/UserDetails/index.tsx

User Details: hide split line when username is empty, and fix paddings.
LOG-2530

fix(console): hide split line when username is empty

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/components/ConfirmModal/IframeConfirmModal.module.scss
packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
packages/ui/src/components/ConfirmModal/index.tsx
packages/ui/src/components/TermsOfUse/index.tsx
packages/ui/src/components/TextLink/index.module.scss
packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModal/index.tsx
packages/ui/src/containers/TermsOfUse/TermsOfUseIframeModal/index.test.tsx
packages/ui/src/containers/TermsOfUse/TermsOfUseIframeModal/index.tsx
packages/ui/src/containers/TermsOfUse/TermsOfUsePromiseModal/index.tsx
packages/ui/src/containers/TermsOfUse/index.tsx
packages/ui/src/hooks/use-terms.ts

Add mobile terms of use iframe modal
Under the mobile webview, users and not open the terms of use link in a new tab like in a browser. We have to implement a page modal to display the terms of use content. 
design:
1. add a new IframeComfirmModal component
2. add a new TermsOfUseIframeModal container
3. TermsOfUse link onclick, if is mobile show the confirm modal
log-2426
test locally
@logto-io/eng

feat(ui): add mobile terms of use iframe modal

---

packages/ui/src/hooks/use-social.ts

Social bind account should back to sign-in page
Fix the social nav flow:
Before:
web/moweb:   `sign-in` -push-> `social` -replace-> `callback` -push-> `sign-in/callback` -push-> `bind-social`
native: `sign-in` -push-> `social` -> `SDK`  -push->   `sign-in/callback` -push-> `bind-social`
After:
web/moweb: `sign-in` -push-> `social` -replace-> `callback` -replace-> `sign-in/callback` -replace-> `bind-social`
native: `sign-in` -push-> `social` -> `SDK`  -push->   `sign-in/callback` -replace-> `bind-social`
Always keep the history stack only have `sign-in` and the current page. 
test locally
@logto-io/eng

fix(ui): social bind account should back to sign-in page

---

packages/core/src/queries/log.ts
packages/core/src/routes/dashboard.test.ts
packages/core/src/routes/dashboard.ts

Add GET /dashboard/users/new
Input: none
Output:
```json
{
"today": {
"count": 111, // today new user count
"delta": 11 // today new user count - yesterday new user count
},
"recent7Days": {
"count": 500, // last 7 days new user count
"delta": 25 // last 7 days new user count - previous 7 days new user count
}
}
```
- e.g. assumed `today` is 5.14, the `last 7 days` is [5.8, 5.14] and `previous 7 days` is [5.1, 5.7]
See Notion [doc](https://www.notion.so/silverhand/Dashboard-API-956dadaf287c428ea79a7018b39948b0)
LOG-942
LOG-2482
---
FIXME:
- Conclusion: `up percent` is replaced by `delta`
- e.g. the delta between `today new user count` and `yesterday new user count`
- See the Slack thread [discussion](https://silverhand-io.slack.com/archives/C0243P3E4KS/p1653449049214669)

feat(core): get /dashboard/users/new

---

packages/core/src/middleware/koa-proxy-guard.test.ts
packages/core/src/middleware/koa-proxy-guard.ts

Update proxy guard middleware. As we continuously find edge cases for session guard route requests:
1. social callback page
2. static files request
Instead of by default guarding all incoming routes excluding provided exceptions, only protect the provided paths.
ut case updated
@logto-io/eng

fix(core): update proxy guard middleware

---

packages/schemas/tables/users.sql

Remove the foreign key on `application_id` in the `users` schema
See Slack thread [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1653554538776739)
LOG-2709
No need.

fix(core): remove user foreign key on application id

---

packages/ui/src/App.tsx
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn/index.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn/index.tsx
packages/ui/src/hooks/use-api.ts
packages/ui/src/hooks/use-native-message-listener.ts
packages/ui/src/hooks/use-social-callback-handler.ts
packages/ui/src/hooks/use-social-signin-listener.ts
packages/ui/src/hooks/use-social.ts
packages/ui/src/pages/Callback/index.tsx

useSocial hooks refactor. Break down `useSocial` hooks into Four:
1. useSocial: Provides socialConenctors from PageContext, and invokeSocialSignIn API (ref: social sign-in components)
2. useNativeMessageListener: Add native postMessage listener (ref: useSocialSignInListener)
3. useSocialCallbackHandler: Provide callback handler for the social connector callback page. (ref: callback page)
4. useSocialSignInListener: Provide social sign-in callback listener, auto sign-in to logto. (ref: sign-in/callback page)
log-2699
test locally
@logto-io/eng

refactor(ui): useSocial hooks refactor

---

packages/connector-alipay-native/src/index.ts
packages/connector-alipay/src/index.ts

now, `code` can be a json, and `connector-alipay` can parse it and get `auth_code`.
@simeng-li

feat(connector-alipay): parse code from json

---

packages/core/src/middleware/koa-proxy-guard.ts

fix preview session not found bug
preview query string filter is mistakenly removed on the session guard refactor PR
add it back
test locally
@logto-io/eng

fix(core): fix preview session not found bug

---

packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat/src/index.test.ts
packages/connector-wechat/src/index.ts
packages/core/src/routes/connector.test.ts
packages/core/src/routes/connector.ts
packages/core/src/routes/connector.update.test.ts

1. Separate connector route UTs to make each testing file under 300 lines.
2. Fix WeChat Web and WeChat Native connector error handler of getUserInfo() to fit the max-complexity of 5 for each code block.
LOG-2405
Passed UTs.

refactor(core, connector): fix code to fit new ESlint rule

---

packages/console/src/components/AppError/index.module.scss

Fix the issue that long text content in error callstack would overflow the container width.
Before:
After:

fix(console): error callstack content should not overflow container

---

packages/console/src/pages/Callback/index.tsx

In Admin Console, if the user mistakenly / manually navigates to `/callback` route after a successful authentication, we should navigate the user back to home page, instead of stuck in `Navigating…` state.

refactor(console): handle user navigates to 'callback' after authenticated

---

packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.module.scss
packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx
packages/core/src/routes/sign-in-settings.ts

Only show enabled(configured) connector targets in sign in methods.
LOG-2733
Local tested.

fix(console,core): only show enabled connectors in sign in methods

---

packages/console/src/pages/SignInExperience/components/GuideModal.tsx
packages/console/src/pages/SignInExperience/components/Preview.tsx
packages/console/src/pages/SignInExperience/hooks.ts
packages/console/src/pages/SignInExperience/index.tsx

Pass form data to preview box only when form is dirty, otherwise, use remote data directly.
This can reduce "postMessage" frequency to avoid unexpected refresh.
Local tested, change one form value, and count postMessage calls:
before:
after reduce:

fix(console): reduce refresh frequency in preview

---

packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.module.scss
packages/console/src/pages/ConnectorDetails/components/ConnectorTabs/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Now only show enabled platforms in connector details tabs(in top).
And remove old "not set" tag.
LOG-2770
Local tested.

fix(console): show enabled platforms in detail tab

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/components/Notification/index.module.scss
packages/ui/src/components/Notification/index.tsx
packages/ui/src/containers/AppNotification/index.module.scss
packages/ui/src/containers/AppNotification/index.test.tsx
packages/ui/src/containers/AppNotification/index.tsx
packages/ui/src/pages/SignIn/index.tsx
packages/ui/src/utils/session-storage.ts

Further integrate App Notification
1. read the message from session storage if any display the notification
2. close the alert and remove from session storage after read
3. Remove usage of react modal, seems useless. 
test locally
ut case added
@logto-io/eng

feat(ui): app notification

---

packages/phrases/src/locales/zh-cn.ts
packages/ui/src/i18n/init.ts

Add a custom i18n formattor for the zh-CN list. As i18n build-in list formattor does not have extra space between ‘或’. Need to handle it explicitly. 
Before:
After:
[reference](https://www.i18next.com/translation-function/formatting) 
test locally
@logto-io/eng

fix(ui): add i18n formater for zh-CN list

---

packages/console/package.json
packages/demo-app/package.json
pnpm-lock.yaml

Bump React SDK to 0.1.13 to resolve sign in issue (introduced in #1014) in Admin Console.

fix(console): bump react sdk to 0.1.13 to resolve sign in issue

---

packages/console/src/pages/SignInExperience/components/BrandingForm.tsx

fix(console): display dark mode color setting only when dark mode is enabled.
* LOG-2789

fix(console): display dark mode color setting only when dark mode is enabled

---

packages/console/src/pages/Settings/index.tsx
packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx
packages/console/src/pages/SignInExperience/components/TermsForm.tsx

fix(console): remove redundant `required` label
* LOG-2791

fix(console): remove redundant `required` label

---

packages/core/src/lib/user.ts
packages/core/src/queries/user.ts
packages/core/src/routes/session.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Elaborate error message of signing in with username and password.
Ensure all English/Chinese error messages end with './。'.
Remove duplicated tailing '。's.
LOG-2825
UTs.

chore(core,locale): fix error messages of signing in with non-existing username

---

packages/core/src/routes/init.ts
packages/core/src/routes/swagger.test.ts
packages/core/src/routes/swagger.ts
packages/core/src/utils/zod.test.ts
packages/core/src/utils/zod.ts

Make GET /api/swagger.json contain all `/api/*` routes
( Next PR: LOG-2809 Convert the Zod types (`ZodUnion`, `ZodUnknown` and etc.) to OpenAPI schemas )
LOG-2609
LOG-2811
TODO:

feat(core): make GET /api/swagger.json contain all api routes

---

packages/console/src/components/RadioGroup/index.module.scss
packages/console/src/consts/connectors.ts
packages/console/src/hooks/use-connector-groups.ts
packages/console/src/pages/Connectors/components/CreateForm/PlatformSelector.module.scss
packages/console/src/pages/Connectors/components/CreateForm/PlatformSelector.tsx
packages/console/src/pages/Connectors/components/CreateForm/index.tsx
packages/console/src/types/connector.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

In add social connector modal, group connectors by target. If select a multi-platform connector group, show another radio group to let users pick up one platform.
LOG-2771

feat(console): group connectors in add modal

---

packages/console/src/pages/Connectors/components/ConnectorName/index.tsx

Fix k18n key prefix for `connectorPlatformLabel`, this issue is caused by uncorrect merge conflict pick.
Local testd.

fix(console): fix platform label prefix caused by merge

---

packages/console/src/App.tsx

Some routes are not wrapped by root route (AppContent), this may be caused by some mishandling of merge conflict.
Local tested, all pages are normal now.

fix(console): wrap routes with AppContent

---

packages/console/src/components/TextInput/index.module.scss
packages/console/src/components/TextInput/index.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApplicationDetails/components/Settings.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
packages/console/src/pages/SignInExperience/components/TermsForm.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/components/CreateForm/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

feat(console): input error message
* For we need to control the error state of the input widget independently, so we add an `errorMessage` to control the message display.
* LOG-2867: Refactor `uriValidator` to support nullable value verification, now it is ready in https://github.com/logto-io/logto/pull/1051
* LOG-2067

feat(console): input error message

---

packages/core/src/routes/swagger.test.ts
packages/core/src/routes/swagger.ts
packages/core/src/utils/zod.test.ts
packages/core/src/utils/zod.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Convert the koa guards of `params`, `query` and `body` to the swagger.json
- Convert the used Zod types and `arbitraryObjectGuard` to `OpenAPIV3.SchemaObject`
- Convert the parameters of `path` and `query` to `OpenAPIV3.ParameterObject[]`.
- path parameter: e.g. `id` in `GET /connectors/:id` 
- query parameter: e.g. `target` in `GET /connectors?target=github`
References:
- Parameter serialization: https://swagger.io/docs/specification/serialization/
- Data types: https://swagger.io/docs/specification/data-models/data-types/
LOG-2609
LOG-2809

feat(core): convert route guards to swagger.json

---

packages/console/package.json
packages/console/src/components/AppBoundary/index.tsx
packages/console/src/components/AppContent/components/Sidebar/hook.tsx
packages/console/src/components/AppContent/components/Sidebar/index.tsx
packages/console/src/components/AppContent/index.tsx
packages/console/src/consts/index.ts
packages/console/src/hooks/use-settings.ts
packages/console/src/hooks/use-user-preferences.ts
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/Connectors/components/GuideModal/index.tsx
packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
packages/console/src/pages/GetStarted/hook.ts
packages/console/src/pages/GetStarted/index.tsx
packages/console/src/pages/Settings/index.tsx
packages/console/src/pages/SignInExperience/components/GuideModal.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/core/src/__mocks__/index.ts
packages/core/src/middleware/koa-auth.test.ts
packages/core/src/middleware/koa-auth.ts
packages/core/src/oidc/init.ts
packages/core/src/routes/admin-user.ts
packages/core/src/routes/init.ts
packages/core/src/routes/me.ts
packages/schemas/src/foundations/jsonb-types.ts
pnpm-lock.yaml

- core: implement `GET/PATCH /me/custom-data` for current user
- console: `useConfig` -> `useSettings` to match entity name
- console: implement `useUserPreferences` for user-level data
LOG-2460

feat: use user level custom data to save preferences

---

packages/console/src/hooks/use-api.ts
packages/console/src/hooks/use-swr-fetcher.ts
packages/console/src/pages/GetStarted/components/Skeleton/index.module.scss
packages/console/src/pages/GetStarted/components/Skeleton/index.tsx
packages/console/src/pages/GetStarted/hook.ts
packages/console/src/pages/GetStarted/index.tsx

Hide "check demo" from get-started page if demo app is deleted from applications list

refactor(console): hide check demo button if demo app is deleted

---

packages/core/src/middleware/koa-log.test.ts
packages/core/src/middleware/koa-log.ts
packages/schemas/src/types/log.ts

Save the error context from `RequestError.body` in logs
See Slack thread [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1654570553888139)
- [LOG-2875 : Save RequestError.data in the logs](https://linear.app/silverhand/issue/LOG-2875/save-requesterrordata-in-the-logs)
LOG-2875

feat(core): log error body

---

packages/console/src/mdx-components/MultiTextInputField/index.tsx
packages/console/src/pages/ApplicationDetails/components/Settings.tsx
packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
packages/console/src/pages/SignInExperience/components/TermsForm.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/utilities/validator.ts

* refactor(console): refactor `uriValidator` logic
* fix: should guard blank uri string before sending it to the backend
* LOG-2867
Before:
After:

refactor(console): refactor `uriValidator` verification logic

---

packages/console/src/App.tsx

Lazy loading admin console page routes

refactor(console): lazy loading admin console routes

---

packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
packages/console/src/pages/GetStarted/hook.ts
packages/console/src/pages/GetStarted/index.tsx

We check if demo app exists in the `useGetStartedMetadata` hook. However, the hook is used in two different places, one in get-started page, another one in the get-started progress indicator on top bar.
We only want to check demo app existence when user is on get-started page, because if it does not exist, we should hide "Check Demo" button from that page.

fix(console): only check demo app existence on get-started page

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/App.tsx
packages/ui/src/assets/icons/loading-icon-light.svg
packages/ui/src/assets/icons/loading-icon.svg
packages/ui/src/components/AppContent/index.tsx
packages/ui/src/components/LoadingLayer/LoadingIcon.tsx
packages/ui/src/components/LoadingLayer/LoadingIconLight.tsx
packages/ui/src/components/LoadingLayer/index.module.scss
packages/ui/src/components/LoadingLayer/index.tsx
packages/ui/src/containers/LoadingLayerProvider/index.tsx
packages/ui/src/containers/SocialLanding/index.module.scss
packages/ui/src/containers/SocialLanding/index.tsx
packages/ui/src/hooks/use-social-callback-handler.ts
packages/ui/src/hooks/use-social-landing-handler.ts
packages/ui/src/pages/Callback/index.module.scss
packages/ui/src/pages/Callback/index.tsx
packages/ui/src/pages/Consent/index.module.scss
packages/ui/src/pages/Consent/index.tsx
packages/ui/src/pages/SocialLanding/index.tsx

Refactor ui loading:
1. Extract a `LoadingLayerProvider` provider that applies a global loading layer to specific pages
2. Move the `Consent` page outside of the `LoadingLayerProvider`, so it won't pick up the global loading layer. 
3.  Add `LoadingIcon` and `LoadingIconLight` for in-page loadings
4. Update the loading animation effect
5. Update the consent page. Show in page loading icon
7. Update the social callback and landing page to show the in page loading icon
9. Remove the social landing page bottom button as it is no longer needed
10. Align the useSocialLandingHandler and useSocialCallbackHandler hook usage. Instead of wrapup everything in the hook, return the callback method out, and make it visible at the page level. 
1
log-2876
test locally
@logto-io/eng

refactor(ui): refactor ui loading

---

packages/console/src/pages/Dashboard/components/Skeleton/index.module.scss
packages/console/src/pages/Dashboard/components/Skeleton/index.tsx
packages/console/src/pages/Dashboard/index.tsx

Add loading skeleton for dashboard.
LOG-2807
Local tested, and it matches the blocks after loading finished.

feat(console): dashboard skeleton

---

packages/docs/docs/sdk/JavaScript/README.md
packages/docs/docs/sdk/JavaScript/browser/README.md
packages/docs/docs/sdk/JavaScript/js/README.md
packages/docs/docs/sdk/JavaScript/react/README.md
packages/docs/docs/sdk/JavaScript/vue/README.md
packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/README.md

[LOG-2891](https://linear.app/silverhand/issue/LOG-2891/adjust-sorting-order-of-js-sdk-references)

chore(docs): adjust sdk reference sorting order

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/containers/SocialLanding/index.module.scss
packages/ui/src/containers/SocialLanding/index.tsx
packages/ui/src/hooks/use-api.ts
packages/ui/src/hooks/use-social-callback-handler.ts
packages/ui/src/pages/Callback/index.tsx

display error message on social callback page
Temp solution displays the social connector's error message in the callback page if any. 
Will update and remove it, once we refactored the connector error handling flow. Should parse all query params to the backend connector handlers. 
Remove the prefix for server-side error message displays. 
log-2434
test locally
@logto-io/eng

feat(ui): display error message on social callback page

---

packages/console/src/pages/SignInExperience/components/Preview.tsx
packages/ui/src/components/Input/PhoneInput.tsx
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/UsernameSignin/index.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SecondarySignIn/index.tsx

Adjust input field auto focus logic
1. For now only apply auto focus on all secondary pages. As the default sign-in page, user may select a different sign-in method other than the primary one.
2. Add tabIndex={-1} to the console preview iframe element
log-2899
test locally
@logto-io/eng

refactor(ui): adjust input field auto focus logic

---

packages/console/src/App.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/GetStarted/hook.ts

Add dedicated route path for create application popup dialog, so that clicking "create application" button from get-started page will open create app popup directly

refactor(console): add dedicated route path for create app popup dialog

---

packages/core/src/utils/zod.test.ts
packages/core/src/utils/zod.ts

The any-type parameter shows an empty object in the APi request example.
LOG-2994
UTs
API reference page
GET /api/swagger.json response

feat(core): any-type parameter shows empty object in swagger example

---

packages/console/src/pages/Dashboard/components/Block.module.scss

Fix info icon vertical position, now is in center position.
LOG-2926

fix(console): fix info icon vertical alignment

---

packages/core/src/routes/admin-user.ts
packages/shared/src/regex.ts

Remove `nameRegEx` since is no longer necessary, `name` is user's nickname, and have no limitation.
When users in AC remove name string in form input, the formdata's `name` will become an empty string, this is an issue before. Is now fixed by this PR.
LOG-2601
Local tested.

fix(core): remove name regex

---

packages/console/src/pages/SignInExperience/components/TermsForm.tsx
packages/core/src/routes/sign-in-experience.guard.test.ts
packages/schemas/src/foundations/jsonb-types.ts

This pr fix these issues:
- The `<Switch />` component treats the uncheck value as `""`, which will cause the `required` rule to fail.
- The Zod rule `string().url().optional()` does not allow `""`, but the text input will generate `""` by default without any input.
- If we convert the `contentUrl` from `""` to `undefined`, then the back end will ignore this partial update.
* LOG-3059: Return `false` When The Switch is Unchecked
* LOG-2868
UT & Test in the admin console.

fix(console): update terms of use

---

packages/core/src/middleware/koa-pagination.ts
packages/core/src/routes/swagger.test.ts
packages/core/src/routes/swagger.ts

Append the `page` and `page_size` to the query parameters in the `swagger.json` when the routes use `pagination`
---
Check the pagination middleware like the guard middleware:
- `isPaginationMiddleware`:
- `isGuardMiddleware`:
LOG-2856
- UTs
- GET /api/swagger.json
- API Reference page

feat(core): append page and page_size to the query parameters in swagger.json

---

packages/console/src/pages/Users/index.tsx

- Search users with a keyword that matches more than the page-size count results.
- Click page 2 in the pagination
- You will see the items displayed on page 2 are not search results.
- Add the missing query `search` on the page number changed.
* LOG-3081

fix(console): user management search result

---

packages/ui/src/components/Input/PhoneInput.tsx
packages/ui/src/components/Passcode/index.test.tsx
packages/ui/src/components/Passcode/index.tsx
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/hooks/use-preview.ts
packages/ui/src/include.d/dom.d.ts

input fields auto complete fix.
1. Update all autoCompleteSettings 
2. Update some of the inputMode settings to better interact with mobile keyboards.
3. Fix a bug in the Passcode component.  Previously only 1 input digit is allowed for each input field, which does not support the passcode autoComplete feature.  Allow multiple digits input, and carry over the floated digits to the next few input fields automatically. 
ut case updated
test locally
@logto-io/eng

fix(ui): input fields

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/routes/init.ts
packages/core/src/routes/sign-in-settings.test.ts
packages/core/src/routes/sign-in-settings.ts
packages/schemas/src/seeds/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql
packages/ui/src/__mocks__/logto.tsx
packages/ui/src/pages/SignIn/index.tsx
packages/ui/src/pages/SignIn/registry.tsx
packages/ui/src/types/index.ts

Add sign-in-mode to sign-in-experience settings.
1. Introduce sign-in-mode to the sign-in-experience settings.  `SignIn`, `Register` and `SignInAndRegister`
2. Update SignInSettings API, for admin console, always set signInMethods to `username`. If no user is found set sign-in mode to Register, else set to SignIn. 
3. Update UI signin page settings to reflect the updates
log-2870
test locally
ut case update
@logto-io/eng

feat(core): add sign-in-mode

---

packages/console/src/App.tsx
packages/console/src/components/AuditLogTable/index.tsx
packages/console/src/pages/AuditLogDetails/index.tsx
packages/console/src/pages/AuditLogs/index.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

* Rename the `id` param name under the `/user` route to `userId` for clarity.
* Per AC design, we should be able to nav back to user-details page from user-log-details page:
* LOG-3096

fix(console): return to user-details page from user-log-details page

---

packages/console/src/App.tsx

We can not navigate back to the previous page on the sign-in-experience and app details page for the react-router's redirect action.
Now use `replace` when redirecting these two pages.
* LOG-3098

fix(console): should return to previous page when on sign-in-experience and app details page

---

packages/core/src/queries/application.ts
packages/core/src/queries/setting.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/queries/sign-in-experience.ts
packages/core/src/queries/user.test.ts
packages/core/src/queries/user.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

Align all jsonb replace mode on APIs, based on the rule:
For an endpoint, if the body guard only allows first level partial (that means you can only pass in a full object for a jsonb column), then the update mode is "replace", if guard allows deep partial (second level actually), the update mode is "merge".
Now, only the `PATCH /settings` is in "merge" mode.
LOG-2745
Passed all UTs.

fix(core): align jsonb replace mode

---

packages/console/src/pages/UserDetails/components/UserConnectors.tsx

fix(console): connector name in user details
We store the `connectorId` in the user table, so we should use `connectorId` to retrieve the connector information here.
N / A
before:
after:

fix(console): connector name in user detials

---

packages/console/src/components/TextInput/index.module.scss

fix(console): read-only text field background color should use color-layer-2
* LOG-3049

fix(console): read-only text field background color should use color-layer-2

---

packages/core/src/routes/session/session.test.ts
packages/core/src/routes/session/session.ts

Add the register user with the admin role feature for the `session/register/username-password` API
Check if target client_id is admin role, and has no active users, our Logto very first user should be created as admin. 
log-3099
ut case added
@logto-io/eng

feat(core): register with admin role

---

packages/console/src/components/ItemPreview/index.module.scss
packages/console/src/components/ItemPreview/index.tsx

Fix the item preview aligment.
Related PR: https://github.com/logto-io/logto/pull/1152
* For the `<ItemPreview />` is used in tables that have a min-width limit, so the icon will not be shrunk anymore.
N / A

fix(console): item preview alignment

---

packages/console/src/components/Table/TableEmpty.module.scss
packages/console/src/components/Table/TableEmpty.tsx

fix(console): remove underline in the empty table
* LOG-3068

fix(console): remove underline in the empty table

---

packages/console/src/pages/UserDetails/index.module.scss

Fix user details card footer, auto grow form's height, to make sure "footer" is always in the bottom of page.
LOG-3029

fix(console): user details card footer

---

packages/console/src/pages/UserDetails/components/UserConnectors.tsx
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

1. In Admin Console UserDetails page, the deletion of user identities info should be indexed by `target` instead of `connectorId`.
2. Fix backend API and UTs as well.
LOG-3133
Passed UTs and tested locally.

fix(core,console): delete specific user identity by target

---

packages/console/src/components/Button/index.module.scss

Fix button loading spinner position, since we now using flex layout in button component.
Previously, the spinner was slightly shifted to the right. Now it's right in the middle

fix(console): button loading spinner position

---

.github/workflows/master-codecov-report.yml

Add master codecov report job.
We have observed that the master base branch codecov report hasn't been updated since PR #1123 
We need to upload the report to codecov on each master push. So create an individual workflow job for that. 
@logto-io/eng

fix(worklow): add master codecov report job

---

packages/console/src/components/ApplicationName/index.tsx
packages/console/src/components/UserName/index.tsx
packages/console/src/pages/Users/index.tsx
packages/core/src/queries/user.test.ts
packages/core/src/queries/user.ts
packages/core/src/routes/admin-user.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Hide admin user in AC:
1. In user management table list, admin users are filtered.
2. In audit log detail, if is admin user, the "user" link is removed and a tag is added.
3. Add a tag on special "Admin Console" app.
LOG-3041

feat(console,core): hide admin user

---

packages/console/src/components/RadioGroup/index.module.scss
packages/console/src/pages/Connectors/components/CreateForm/index.module.scss

- Instead of removing the border from the disabled radio item, we change the border color to the background color to ensure the disabled radio item will have the same size as the enabled item.
LOG-3027

fix(console): connector card item style

---

packages/console/src/pages/UserDetails/index.tsx
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

* Allow update user data with empty avatar string.
* Remove required rule from `customData` field, for the JSON syntax check will guard this situation.
* LOG-2596
Test in the Admin Console.

fix(console): update user data

---

packages/connector-aliyun-dm/src/index.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-types/src/index.ts
packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/core/src/routes/connector.test.ts
packages/core/src/routes/connector.ts

Add `config` param to email/sms connector test API, in order to allow testing the email/sms connector on the fly, without having to save the configs first.

refactor(connector,core): add config param to email/sms connector test API

---

packages/console/src/components/Drawer/index.module.scss
packages/console/src/components/Drawer/index.tsx
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorRow/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

* Refactor drawer component by adding a fixed header on the top
* Show connector README.md content when clicking "Check README" button in connector details page.

refactor(console): show connector readme content in drawer

---

packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/Guide/index.tsx
packages/core/src/routes/connector.test.ts
packages/core/src/routes/connector.ts

* pass connectorId to email/sms test API => `/connectors/:id/test`
* combine `/connectors/test/email` and `/connectors/test/sms` APIs into one

refactor: email/sms connector test API

---

packages/console/src/hooks/use-settings.ts
packages/console/src/pages/SignInExperience/components/GuideModal.tsx
packages/console/src/pages/SignInExperience/components/Welcome.tsx
packages/console/src/pages/SignInExperience/index.tsx

Mutate settings after SIE guide done, this will refresh the state (`settings.admin_console.customizeSignInExperience`) on whether to show welcome guide modal.
Previously, this is done by `location.reload`.
Local tested and performed as expected.

fix(console): mutate settings after SIE guide done

---

packages/console/src/App.tsx
packages/console/src/pages/SignInExperience/components/BrandingForm.tsx
packages/console/src/pages/SignInExperience/components/ColorForm.tsx
packages/console/src/pages/SignInExperience/components/GuideModal.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/SignInExperience/utilities.ts
packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.branding.guard.test.ts
packages/core/src/routes/sign-in-experience.color.guard.test.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/seeds/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql
packages/ui/src/__mocks__/logto.tsx
packages/ui/src/containers/AppContent/index.tsx
packages/ui/src/hooks/use-preview.ts
packages/ui/src/hooks/use-theme.ts
packages/ui/src/types/index.ts

Reorg SIE form:
1. Move terms of use to others.
2. Rename Experience to Branding.
3. Split the first section into Color and Branding Area two parts.
See LOG-3125

feat(console): sie form reorg

---

packages/console/src/pages/SignInExperience/components/Preview.tsx

Limit preview options (language and appearence mode), those options are limited by current SignInExperience config.
Local tested.

fix(console): limit preview options

---

packages/console/src/components/TextInput/index.module.scss

Fix text input autofill styles
Before:
After:

fix(console): text input autofill styles

---

packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/ConnectorName/index.tsx

support dark logo for connectors

feat(console): support dark logo for connectors

---

packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/android_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx

Fixed errors on saving redirect URI in native SDK guide, caused by missing `appId` in mdx files

fix(console): application integrate SDK guides

---

packages/console/src/components/Checkbox/index.tsx
packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx

Change `<Checkbox />` from ref component to controlled component. This will fix the bug: 
change value from `true` to `false`, then change back to `true`, and then, continue to change the checkbox state won't cause form value change, even won't trigger react render.
You can see LOG-3167 for more details.
Local tested in SIE, now checkbox value change will map to "Preview" immediatly.

fix(console): change checkbox to controlled comp

---

packages/ui/src/components/Notification/index.module.scss
packages/ui/src/containers/AppNotification/index.module.scss

fix notification length
Before
After
@logto-io/eng

style(ui): fix notification length

---

packages/ui/src/containers/CreateAccount/index.test.tsx
packages/ui/src/containers/CreateAccount/index.tsx

Rename create account form name
chrome uses the input name only to determine whether an auto-fill data is fitted in.  So have to use a different name for the creation forms 
test case updated
@logto-io/eng

refactor(ui): rename create account form name

---

packages/ui/src/containers/SocialLanding/index.tsx
packages/ui/src/hooks/use-social-callback-handler.ts
packages/ui/src/pages/Callback/index.tsx

To unblock PR #1166.
Remove all callback page search params validation logic. 
Instead, pass all search params as a json object to the connector server side.
Let the connector handler handle all the logic.
1. remove the message UI from social landing component. As it is no longer needed
2. remove the error,error_description, state, connectorId validation logic from the socialCallbackHandler
UT case passed
@logto-io/eng  cc: @darcyYe 
@darcyYe we can test the flow again once this is merged.

refactor(ui): remove all social callback page search params validation

---

packages/console/src/components/ApplicationIcon/index.tsx
packages/console/src/consts/applications.ts
packages/console/src/pages/ApplicationDetails/index.module.scss
packages/console/src/pages/ApplicationDetails/index.tsx

* Refactor the `<ApplicationIcon />` to support style settings.
* Fix the application icon size on the details page.

fix(console): application icon size

---

packages/core/src/routes/sign-in-settings.ts
packages/demo-app/src/App.tsx
packages/schemas/src/consts/index.ts
packages/schemas/src/index.ts
packages/ui/src/containers/AppNotification/index.test.tsx
packages/ui/src/containers/AppNotification/index.tsx
packages/ui/src/hooks/use-page-context.ts
packages/ui/src/types/index.ts
packages/ui/src/utils/session-storage.ts

Refactor app notification logic
Avoid session storage being shared by the different Logto SignIn flows, move the notification settings to the sign-in-exp settings API for now. 
Remove the AppNotification storage key definition.
In the UI, read and update the `notification` settings from sign-in-experience settings instead.
test locally
ut case added
@logto-io/eng

refactor(ui): refactor app notification logic

---

packages/core/src/lib/user.ts
packages/core/src/routes/session/session.test.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Signing in with a non-existing username should throw invalid credentials.
UTs.

fix(core): signing in with a non-existing username should throw invalid credentials

---

packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/android_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
packages/console/src/pages/Applications/components/Guide/index.tsx

Pre-populate the `appId` and `endpoint` values in the code samples in guides.

refactor(console): pre-fill app id and endpoint in guides

---

packages/console/src/mdx-components/UriInputField/index.tsx

Add toast message on save URI success in guides, including:
* Redirect URI
* Post Sign-out Redirect URI

fix(console): add toast message on save uri success in guide

---

packages/console/src/components/Markdown/index.module.scss
packages/console/src/mdx-components/Step/index.module.scss

Improve bullet list and link styles in application guide
* Remove underline style from hyperlinks
* Use bullet instead of hyphen in unordered lists

style(console): improve link and bullet styles in guide and readme

---

packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/android_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
packages/console/src/mdx-components/Step/index.tsx
packages/console/src/pages/Connectors/components/Guide/index.tsx

* `Done` button in last step in guide should be primary
* `Save and done` button in connector guide should be primary

fix(console): last button in guide should be primary

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Improve AC dashboard tooltip description
Next up: LOG-3279 @wangsijie will replace the placeholder with the real timestamp.
Notion doc: [AC UI - Content & Phrases](https://www.notion.so/silverhand/65730ed49d51463588862d19353ed834?v=15184bd20d4c46e68e1dede98813105b)

chore(phrases): improve ac dashboard tooltip description

---

packages/console/src/components/AppContent/index.module.scss
packages/console/src/pages/SignInExperience/index.module.scss

The page content size will change when the scrollbar is present.
Change the related page's style from `overflow-y: auto` to `overflow-y: scroll`, then the page content's size will always contain the scrollbar size.
When switching to the page without a scrollbar, the page will not jump.

fix(console): page content should not jump on scrollbar present

---

packages/console/src/pages/GetStarted/hook.ts

Bug:
Get-started task "Add a social connector" is never completed even if we have successfully added a social connector.
Now all get-started tasks can be completed (6/6).

fix(console): adding social connector should complete corresponding get-started task

---

packages/console/src/pages/Applications/components/GuideHeader/index.module.scss

fix(console): button space on the guide header

fix(console): button space on the guide header

---

packages/console/src/pages/Applications/components/SdkSelector/index.module.scss
packages/console/src/pages/Applications/components/SdkSelector/index.tsx

sdk selector content in the guide should be left-aligned
- apply `width:100%` to the congrats and radioGroup to adjust their size to fit the card content
- add `margin-right: 0;` to **override** the default radioGroup style.

fix(console): sdk selector content in the guide should be left-aligned

---

packages/console/src/pages/Connectors/components/Guide/index.module.scss
packages/console/src/pages/Connectors/components/Guide/index.tsx

fix(console): connector guide setup content should scroll in the whole container

---

packages/console/src/components/RadioGroup/index.module.scss

fix(console): use box shadow on radio group item hovered

fix(console): use box shadow on radio group item hovered

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Due to the complexity of handing timezone issue, remove the specific time range label from dashboard tooltips.
No need to test.

fix(console): remove dashboard tip time range

---

packages/core/src/routes/init.ts
packages/core/src/routes/well-known.test.ts
packages/core/src/routes/well-known.ts
packages/ui/src/apis/settings.ts

Update sign-in-settings api path.
The original path name is confusing, introduce the /.well-known path accordingly. All open configs API should lies under this subpath.
ut passed, test locally
@logto-io/eng

refactor(core): update sign-in-settings api path

---

packages/console/src/pages/SignInExperience/components/Preview.tsx

Set preview background color for "Desktop Web", according to selected appearence mode.

fix(console): set preview desktop background color

---

packages/console/src/pages/Settings/components/ChangePassword.module.scss
packages/console/src/pages/Settings/components/ChangePassword.tsx

Fix change account password modal margin by moving "description" to "subTitle".

fix(console): change account password modal margin

---

packages/console/src/pages/Dashboard/components/ChartTooltip/index.module.scss

fix dark mode char tooltip background

fix(console): fix dark mode char tooltip background

---

packages/ui/src/containers/AppContent/index.module.scss
packages/ui/src/index.html
packages/ui/src/pages/SignIn/index.module.scss
packages/ui/src/pages/SignIn/registry.tsx

update create account link style
1. replace the secondary link style use primary
2. add the safe-area-padding on mobile
test locally
@logto-io/eng

style(ui): update create account link style

---

.github/workflows/integration-test.yml
.github/workflows/main.yml
.github/workflows/upload-annotations.yml

provide fallback on some workflows to fix unnecessary cancels
ref: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
CI

ci: fix concurrency issue

---

packages/console/src/components/Markdown/index.module.scss
packages/console/src/mdx-components/DetailsSummary/index.module.scss
packages/console/src/mdx-components/Step/index.module.scss
packages/console/src/mdx-components/Tabs/index.module.scss

* Adjust paragraph margins in AC guide: inner 12px, outer 24px
* Improve `<strong>` element font styles
* Improve `<a>` element hover styles, add underline text decoration

style(console): improve styles in guides

---

packages/console/src/components/AppContent/components/Sidebar/hook.tsx
packages/console/src/hooks/use-user-preferences.ts
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/Connectors/components/Guide/index.tsx
packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
packages/console/src/pages/GetStarted/hook.ts
packages/console/src/pages/GetStarted/index.tsx
packages/console/src/pages/SignInExperience/components/GuideModal.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/core/src/__mocks__/index.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/src/seeds/setting.ts

Improve get-started task corresponding keys in DB. Use past tense, e.g.:
e.g. 
createApplication => applicationCreated
checkFurtherReadings => furtherReadingsChecked

refactor: get-started task corresponding keys in DB

---

.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/update-pr-metadata.yml

github can only bypass pull request to push, but not status check
we don't want to bypass status check, so use 
refactored publish flow:
1. dispatch
2. push to temp branch
3. wait status check
4. push and tag master
5. create release and push docker
commit works as expected
https://github.com/logto-io/logto/runs/7155623671?check_suite_focus=true
wait for a real test

ci: update publish workflow

---

packages/console/src/pages/SignInExperience/components/Skeleton/index.module.scss
packages/console/src/pages/SignInExperience/components/Skeleton/index.tsx
packages/console/src/pages/SignInExperience/index.tsx

feat(console): add loading skeleton to sign in experience page

---

packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/ui/src/containers/AppNotification/index.module.scss

* In desktop mode, notification text in demo-app should not wrap.
* Update wording

style(console): notification text in demo-app should not wrap on desktop

---

packages/core/src/routes/well-known.test.ts
packages/core/src/routes/well-known.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/seeds/sign-in-experience.ts
packages/ui/src/pages/SignIn/index.module.scss
packages/ui/src/pages/SignIn/index.tsx

Refactor ac signin exp
1. Refactor the sign-exp API. Should not query user sign-in-exp data for AC app. Use hardcoded AC experience settings instead.
2. Add a slogan to AC sign-in-exp
3. Adjust the web sign-in page layout according to the latest design
Updates:
AC:
Rest:
test locally
@logto-io/eng

refactor(ui): refactor ac signin exp

---

packages/ui/src/containers/AppNotification/index.module.scss

fix app notification position under short screen
Before:
After:
test locally
@logto-io/eng

style(ui): add short screen notification style

---

packages/console/src/pages/SignInExperience/utilities.ts

When disable secondary sign in, all other methods should be set to "disabled".

fix(console): disable secondary should remove sign in methods

---

packages/core/src/env-set/create-pool-by-env.ts

if user is pull a new logto image without resetting postgres, it's likely to encounter the error below:
because for a new logto image with `--all-yes` specified, it will try to create a new database which will cause 42P04 (duplicate_database) error.
also, the original question "Do you have an empty database for Logto?" is confusing when it comes with "Would you like to set up a new Logto database?".
1. remove the confusing question
2. ask user if we can go with the existing database without seed if logto database exists.
then we can use `--all-yes` even if there's an existing logto database
with local logto database created:
1. remove env `DB_URL`, the question shows; choose `y` then the app runs, and the correct `DB_URL` will be appended to `.env`
2. remove env `DB_URL`, the question …

refactor(core): db seed question

---

packages/console/src/pages/SignInExperience/components/ColorForm.tsx

fix(console): hide reset description on dark-mode primary color matched

fix(console): hide reset description on dark-mode primary color matched

---

packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx

fix sie cannot save when secondary sign-in methods are disabled
the required rule will fail if `checked` is false
ref https://github.com/react-hook-form/react-hook-form/issues/2323
save successfully when secondary sign-in methods are disabled

fix(console): save sie when secondary method is disabled

---

packages/core/src/routes/swagger.test.ts
packages/core/src/routes/swagger.ts

DO NOT titlize the tags of .well-known APIs

fix(core): do not titlize tags of .well-known APIs

---

packages/console/package.json
packages/console/src/components/ConfirmModal/index.tsx
packages/console/src/components/UnsavedChangesAlertModal/index.tsx
packages/console/src/hooks/use-unsaved-changes-alert-modal.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
packages/console/src/pages/ApplicationDetails/components/Settings.tsx
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/SignInExperience/tabs/BrandingTab.tsx
packages/console/src/pages/SignInExperience/tabs/OthersTab.tsx
packages/console/src/pages/SignInExperience/tabs/SignInMethodsTab.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
pnpm-lock.yaml

feat(console): unsaved changes alert
React-Router V6 has removed the `useBlocker` & `usePrompt` API, so I implemented a workaround solution to support this feature. 
FYI: https://github.com/remix-run/react-router/issues/8139
- [Refactor & Add unsaved changes alert for user settings](https://github.com/logto-io/logto/pull/1411)
- [Refactor & Add unsaved changes alert for connector details](https://github.com/logto-io/logto/pull/1414)

feat(console): unsaved changes alert

---

packages/console/src/pages/Dashboard/index.tsx

Use new color for dashboard chart grid line.

fix(console): dashbaord chart grid color

---

packages/console/src/components/ConfirmModal/index.tsx
packages/console/src/components/UnsavedChangesAlertModal/index.tsx

leave page button should be a danger button and on the right of the unsaved changes alert modal

fix(console): leave page button should be a danger button

---

packages/console/src/pages/SignInExperience/tabs/BrandingTab.tsx
packages/console/src/pages/SignInExperience/tabs/OthersTab.tsx
packages/console/src/pages/SignInExperience/tabs/SignInMethodsTab.tsx

For the data will be reset by the logic on the sign-in experience index page, so we don't need to reset the data on tab pages.
Test in the Admin Console.

refactor(console): remove redundant reset logic on sign-in experience tabs

---

packages/console/src/components/Button/index.module.scss

Plain button is now looks like "link button", change hover state from background effect to underline decoration.

style(console): plain button

---

packages/core/src/oidc/init.ts

Add default ttl settings to avoid oidc warning
e.g.
Provide the configs with the same default value.
test locally
@logto-io/eng

chore(core): add default ttl settings

---

packages/console/src/pages/Dashboard/index.tsx

In dashboard, fix chart padding by setting width to "YAxis".
There is still some space remained, incase number grows (with more digits).

fix(console): dashboard chart yaxis width

---

packages/console/package.json
packages/console/src/pages/SignInExperience/components/ColorForm.tsx
packages/schemas/src/seeds/sign-in-experience.ts
packages/shared/src/utilities/color.ts
pnpm-lock.yaml

extract dark mode color generator to `shared`, and use it in seed.
pass existing UTs, and UI looks fine in local test.

refactor(console,schemas,shared): extract dark mode color generator

---

packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/android_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
packages/console/src/pages/Applications/components/Guide/index.tsx

Sync user input `Redirect URIs` and `Post Sign-out Redirect URIs` in the provided code samples as well in each guide.

refactor(console): sync input URI values in code samples in guide

---

packages/console/src/i18n/init.ts

The admin console failed to detect user language on initial run, and user always gets English language.
We suspect it is the `undefined` language param passed in to the i18next initializer that causes this problem.
Thus try to set react-i18next language only when language param is not empty

fix(console): language auto detection

---

packages/console/src/components/Pagination/index.module.scss

pagination active color should be `var(--color-text-link)`

fix(console): pagination color should be color-text-link

---

packages/console/src/hooks/use-user-preferences.ts
packages/console/src/i18n/init.ts

* Revert the previous fix #1456 for it didn't work
* Re-fix the language auto detection problem in admin console

fix(console): admin console language detection

---

packages/console/src/pages/Connectors/components/Guide/index.tsx

- remove sub title from connector guide
- apply i18n to the connector guide title

fix(console): connector guide should not have sub title

---

packages/console/src/pages/SignInExperience/components/ConnectorsTransfer.tsx

hide the add connectors hint when no connectors found on sign-in-experience page

fix(console): hide the add connectors hint when no connectors found on sign-in-experience page

---

packages/connector-apple/src/index.ts
packages/connector-types/src/index.ts
packages/console/src/components/Toast/index.module.scss
packages/console/src/hooks/use-api.ts
packages/core/src/errors/RequestError/index.ts
packages/core/src/middleware/koa-connector-error-handler.ts
packages/core/src/middleware/koa-guard.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts
packages/schemas/src/api/error.ts

- support multiline toast display
- expose data for connector errors
- format `invalid_type` zod errors
- provide `details` prop for detailed error message
- specify which part of request data is invalid (params, body, or query)
Save API Resource without TTL
Save Apple connector config without Client ID
Request test API with multiple errors

feat: expose zod error

---

packages/console/src/pages/GetStarted/components/GetStartedProgress/index.tsx
packages/console/src/pages/GetStarted/hook.ts
packages/console/src/pages/GetStarted/index.tsx

Delete `demo-app` from application list, we should only see 5 get-started tasks listed in both places.

fix(console): hide demo-app from topbar get-started progress if it is deleted

---

packages/console/src/pages/GetStarted/hook.ts

If user is using Chinese translation in admin console, clicking "further readings" button should open Chinese docs site.
Otherwise, should open English docs site

fix(console): docs link in get-started should be localized

---

packages/console/src/pages/Settings/index.tsx

Provide fallback language value for language selection field in settings.
Previously if user never selected language, there would be no language setting in user preferences, thus the field would be empty.

fix(console): provide fallback value for language field in settings

---

packages/ui/package.json
packages/ui/src/components/Input/PhoneInput.test.tsx
packages/ui/src/components/Input/PhoneInput.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/hooks/use-phone-number.ts
packages/ui/src/pages/Register/index.test.tsx
packages/ui/src/pages/SecondarySignIn/index.test.tsx
packages/ui/src/pages/SignIn/index.test.tsx
packages/ui/src/utils/country-code.test.ts
packages/ui/src/utils/country-code.ts
pnpm-lock.yaml

refactor country code logic, introduce country-code utils to handle all the logics
1. remove the country name display for now
2. extract and detect the country code from the i18n language suffix
3. if no valid country code found, search for the local hardcoded  i18n language mapped country code
4. if no valid found, fallback to 'US'
5. countryList should always place default detected countryCallingCode at the first place
6. countryList should filter the duplicate countryCallingCode
7. countryList should ordered by countryCallingCode
test locally
UT case added
@logto-io/eng

refactor(ui): refactor country code

---

packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Improved error handling in connector details and sender tester.
* If config json is invalid, error message will now popup in toast when clicking "Save Changes" button
* If config json is invaild, error message will popup in toast when clicking "Send" button in sender tester

fix(console): improve error handling in connector details and sender tester

---

packages/connector-alipay-native/src/constant.ts
packages/connector-alipay-native/src/index.test.ts
packages/connector-alipay-native/src/index.ts
packages/connector-alipay-native/src/types.ts
packages/connector-alipay/src/constant.ts
packages/connector-alipay/src/index.test.ts
packages/connector-alipay/src/index.ts
packages/connector-alipay/src/types.ts
packages/connector-aliyun-dm/src/index.ts
packages/connector-aliyun-dm/src/types.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-facebook/src/index.test.ts
packages/connector-facebook/src/index.ts
packages/connector-github/src/index.ts
packages/connector-google/src/index.ts
packages/connector-twilio-sms/src/types.ts
packages/connector-wechat-native/src/constant.ts
packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat/src/constant.ts
packages/connector-wechat/src/index.test.ts
packages/connector-wechat/src/index.ts
packages/core/src/middleware/koa-connector-error-handler.test.ts
packages/core/src/middleware/koa-connector-error-handler.ts
packages/phrases/src/locales/en.ts
packages/phrases/src/locales/zh-cn.ts

Update connector error handler, throw error description on General errors.
UTs and tested locally.

feat(connector): connector error handler, throw errmsg on general errors

---

packages/demo-app/src/App.module.scss

Long username will no longer overflow the outer card

fix(demo-app): username should not overflow info card

---

packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx

set error type when save connector config with empty data

fix(console): specify toast type

---

packages/connector-apple/README.md

explain the reason of why we don't support custom scope in Apple connector
N/A

docs(connector): add note for why we dont support custom scope

---

packages/console/src/pages/UserDetails/index.tsx

Fix user avatar failure from google connector social sign-in.
Bug description:
There was a 403 error in browser console, but the link worked fine if you open it in new browser tab
Solution:
Need to add `referrer-policy="no-referrer"` attribute
https://stackoverflow.com/questions/40570117/http403-forbidden-error-when-trying-to-load-img-src-with-google-profile-pic

fix(console): should display user avatar through google connector

---

packages/core/src/routes/session/session.test.ts
packages/core/src/routes/session/session.ts

temp solution add admin guard to the username-password signin route. As we will switch to RBAD once implemented. 
test locally
@logto-io/eng

feat(core): add admin guard to signin

---

packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx

Connector config should not optional, as it always has a string value, at least an empty string.

refactor(console): connector config should be required

---

packages/ui/src/components/Input/index.module.scss
packages/ui/src/components/Input/phoneInput.module.scss
packages/ui/src/scss/normalized.scss

To improve the input field autofill issue make the input field full-width. In case of any special autofill agent styles occurred. 
test locally
@logto-io/eng

style(ui): input auto fill style update

---

packages/connector-alipay-native/src/index.ts
packages/connector-alipay/src/index.ts
packages/connector-aliyun-dm/src/index.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-apple/src/index.ts
packages/connector-facebook/src/index.ts
packages/connector-github/src/index.ts
packages/connector-google/src/index.ts
packages/connector-sendgrid-mail/src/index.ts
packages/connector-smtp/src/index.ts
packages/connector-twilio-sms/src/index.ts
packages/connector-types/src/index.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat/src/index.ts
packages/core/src/connectors/index.ts
packages/core/src/connectors/types.ts
packages/core/src/lib/passcode.ts
packages/core/src/lib/sign-in-experience.test.ts
packages/core/src/lib/sign-in-experience.ts
packages/core/src/routes/connector.test.ts
packages/core/src/routes/connector.ts

Refactor ConnectorInstance as class.
Passed UTs and tested locally, can save connector config for now.

fix(connector): refactor ConnectorInstance as class

---

packages/console/src/components/Markdown/index.tsx

Markdown TOC links that contain special characters should be supported.
ID generating rule:
* Added new regex to strip special characters when generating the internal link (element id)
* Dashes `-` and underscores `_` are kept
* Whitespaces are converted to dash `-`

fix(console): markdown toc links that contain special characters should work

---

packages/core/src/routes/well-known.ts
packages/ui/src/hooks/use-preview.ts
packages/ui/src/i18n/init.ts

fix some of the i18n issues
1. AC preview settings &  fixed language sign-in-exp should not affect the i18n localStorage value. 
- previously i18n `LanguageDetector` plugin initialize regardless of the preview or  fixed language settings
- previously AC preview language settings may affect the local i18n LNG storage as well
- previously when switching fixed language to auto-detect settings. UI i18n does not update properly since the local storage was set to the previous fixed language settings
fix: should not init `LanguageDetector` if is a preview or is fixed language.
2.  App notifications in sign-in exp should pick up the sign-in-ex language settings properly. If it is set to fixed LNG, should use the specified language instead of detecting from the header. 
test locally
@logto-io/eng

fix(ui,core): fix i18n issue

---

packages/console/src/assets/docs/tutorial/integrate-sdk/android.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/android_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/express.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/express_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/ios_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vanilla_zh-cn.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/vue_zh-cn.mdx
packages/console/src/mdx-components/UriInputField/index.tsx
packages/console/src/pages/ApplicationDetails/components/Settings.tsx
packages/phrases/src/languages/en/translation/admin-console/application-details.ts
packages/phrases/src/languages/zh-cn/translation/admin-console/application-details.ts

Fixed `Redirect URI` field label issue as follows:

fix(console): redirect uri field label should display properly in guide

---

packages/console/src/components/Markdown/index.tsx

External links in connector README should be opened in new tab.

fix(console): external links in readme should be opened in new tab

---

packages/core/src/errors/ServerError/index.ts
packages/core/src/middleware/koa-error-handler.test.ts
packages/core/src/middleware/koa-error-handler.ts
packages/core/src/middleware/koa-guard.ts
packages/core/src/routes/log.test.ts
packages/core/src/routes/log.ts
packages/core/src/routes/status.ts
packages/schemas/src/foundations/schemas.ts
packages/schemas/src/gen/index.ts
packages/schemas/src/gen/schema.ts

- add response and status guard to `koaGuard()`
- guard `/api/status` status 204
- guard `/api/logs/:id` body
- auto generate DB schema zod guard

feat(core): add response guard

---

packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/pages/Connectors/components/CreateForm/index.tsx

Fixed a bug that in connectors, if we switch to another connector provider (e.g. Aliyun DM => Sendgrid), after saving the new connector config, the page is still navigated back to the old connector details.
The fix now will navigate users to the new connector details.

fix(console): navigate to new connector details page after switching connector

---

packages/console/src/pages/Settings/index.tsx

Second fix for the "empty value in language selection box" issue

fix(console): language select box initial value should not be empty

---

packages/console/src/pages/Dashboard/index.tsx

Per discussion with @fleuraly , we need to put the Y-Axis on the left and compact the tick number when it is a huge number and increase the Y-Axis width to fit the max width of the tick number.

feat(console): update dashboard chart y-axis tick format

---

packages/console/src/components/AppContent/components/Sidebar/hook.tsx
packages/console/src/hooks/use-language.ts
packages/console/src/pages/GetStarted/hook.ts
packages/console/src/pages/Settings/index.tsx

Fixed an issue that if user first login to AC without specifying language, with a default locale like `en-US`, the documentation links would be incorrect and clicking it will end up in an non-existing page.

fix(console): docs link should work for en-US locale

---

packages/console/src/components/CodeEditor/index.module.scss

Fixed the issue that content in code editor is not editable on Firefox

fix(console): code editor content should be editable on firefox

---

README.md
render.yaml

This pull request introduces "One Click deploy" section. People can deploy a new instance of Logto in a click.
Currently support:
- Render
/

chore: add Render deploy

---

packages/console/src/assets/docs/tutorial/integrate-sdk/react.mdx
packages/console/src/assets/docs/tutorial/integrate-sdk/react_zh-cn.mdx

docs(console): use "appId" instead of "clientId" in React SDK guide

---

packages/ui/src/components/Input/phoneInput.module.scss
packages/ui/src/components/Passcode/index.module.scss
packages/ui/src/scss/normalized.scss

fix some firefox standout bug
1. Number input field should hide arrow icon
Before:
Before:
After:
3. Select font size 
Before:
After:
#1612 
test locally
@logto-io/eng @demonzoo

fix(ui): fix some firefox standout bug

---

packages/core/src/env-set/oidc.ts
packages/core/src/queries/oidc-model-instance.ts

Add refresh token rotation reuse interval, to avoid concurrency issues.
Local tested, a refresh token that is consumed, can be reuse during the interval seconds.

feat(core): refresh token rotation reuse interval

---

packages/core/package.json
packages/core/src/database/utils.ts
packages/core/src/lib/passcode.test.ts
packages/core/src/middleware/koa-guard.ts
packages/core/src/middleware/koa-i18next.ts
packages/core/src/middleware/koa-oidc-error-handler.ts
packages/core/src/middleware/koa-slonik-error-handler.ts
packages/core/src/routes/swagger.ts
packages/core/src/utils/oidc-provider-event-listener.ts
packages/core/src/utils/test-utils.ts
packages/core/src/utils/zod.ts

Resolve some core no-restricted-syntax lint errors.
Comment added for those hard-to-bypass issues. 
test locally
@logto-io/eng

fix(core): resolve some core no-restricted-syntax lint error

---

packages/console/src/pages/Settings/index.tsx
packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
packages/phrases/src/index.ts
packages/phrases/src/locales/en/translation/admin-console/settings.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/settings.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
packages/phrases/src/types.ts

Use non-i18n raw string as language names in language select box.
Settings:
Sign-in Experience:

refactor(console): use non-i18n raw string in language select box

---

.github/workflows/update-pr-metadata.yml

for job "add assignees":
- only trigger when the PR (re)opens
- filter out bot user
- add PR creator as the assignee instead of actor
reopen PR, assignee added
https://github.com/logto-io/logto/runs/7429497160?check_suite_focus=true
other events "add assignee" is skipped

ci: refine add assignees trigger

---

packages/integration-tests/tests/api-resources.test.ts

Use random names and indicators in the create-resource integration test to avoid `resourceIndicator` conflict when developing in the local env.
None.

refactor(test): use random name and indicator in create resource integration test

---

packages/ui/src/components/Passcode/index.tsx

should clear prev passcode input when clicking on backspace btn
Prev: need to click twice to clear the value
https://user-images.githubusercontent.com/36393111/180394014-37a9f7b9-bda5-4ac1-8c16-03b5e2a53c83.mp4
test locally
@logto-io/eng

fix(ui): should clear prev passcode input when click on backspace

---

packages/console/src/components/Transfer/DraggableItem.tsx

Fixed the issue that social connector can only be dragged downwards when re-ordering in sign-in experience page. Now user can drag connector upwards or downwards freely to re-order them.

fix(console): connector can be dragged upwards to reorder

---

packages/console/src/components/AppError/index.module.scss

Fixed the illustration size issue when the browser height is low.

fix(console): app error illustration height should not be shrunk

---

packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx

When secondary sign-in is enabled, the primary method was not checked, so that could be misunderstood that the primary method is not enabled by the end user.
This commit will check the primary method.
I have tested it on the local machine.

feat(console): checked if sign in method is primary

---

packages/connector-mock-mail/src/index.ts
packages/connector-mock-sms/src/index.ts
packages/integration-tests/src/api/session.ts
packages/integration-tests/src/helpers.ts
packages/integration-tests/src/utils.ts
packages/integration-tests/tests/connector.test.ts
packages/integration-tests/tests/session.test.ts

Add passwordless integration test
- update the email & SMS connector mock to write passcode to `/temp/logto_mock_passcode_record` so can be read by the test case
- remove the connector integration test's initial empty status check as the test order is not guaranteed. 
test locally
@logto-io/eng

test(test): add passwordless integration test

---

packages/connector-alipay-native/tsconfig.test.json
packages/connector-twilio-sms/tsconfig.test.json
packages/connector-types/src/index.ts
packages/console/src/pages/UserDetails/components/UserConnectors.tsx

Temp fix: make i18n optional for connector metadata
i18n translation should not block the user from providing new connectors
test locally
@logto-io/eng

chore(core): make the i18n optional for connector metadata

---

packages/console/src/pages/SignInExperience/components/SignInMethodsForm.tsx

Reverts logto-io/logto#1706
@pemassi we had an internal discussion, your feedback is very valid.
the checkbox is for “secondary sign-in”, so keep it unchecked is logically correct. thus I’ll revert this. but we’re trying to figure out a way to reduce the confusion - thank you for the PR and feedback!

Revert "feat(console): checked if sign in method is primary"

---

packages/ui/src/components/Button/SocialLinkButton.tsx

connector name should fall back to en not target.
test locally
@logto-io/eng

fix(ui): connector name  should fallback to en

---

packages/core/src/__mocks__/index.ts
packages/core/src/database/seed.ts
packages/core/src/oidc/adapter.test.ts
packages/core/src/oidc/adapter.ts
packages/core/src/routes/application.test.ts
packages/core/src/routes/application.ts
packages/core/src/utils/id.ts
packages/schemas/src/seeds/application.ts
packages/schemas/tables/applications.sql

Add support of "client_secret", Now, traditional app's `token_endpoint_auth_method` is set to `client_secret_basic`, the client (SDK) is REQUIRED to pass in a valid `Authorization` in headers.
`Authorization` format: `basic base64(client_id:client_secret)`, see [doc1](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) and [doc2](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1)
You can check https://github.com/logto-io/js/pull/372 for client implementation.
UTs and local tested:
Run `next-sample` without "client_secret" will occur an error:
When authorization header is set, token will be granted.

feat(core,schemas): add application secret

---

packages/core/src/routes/session/session.ts
packages/core/src/utils/zod.test.ts

Replace deprecated `.nonempty()` with `.min(1)` for `ZodString`
Reference: https://github.com/colinhacks/zod#strings
Pass existing UTs.

refactor(core): replace deprecated .nonempty() with .min(1) for ZodString

---

packages/core/src/utils/jwks.ts

remove redundant `isBuffer('base64url')` for the min NODE version of Logto is 16 which support `base64url` encoding by default.
Test locally.

refactor(core): remove redundant `isBuffer('base64url')`

---

packages/ui/src/components/ConfirmModal/AcModal.tsx
packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
packages/ui/src/components/ConfirmModal/MobileModal.tsx
packages/ui/src/components/Drawer/index.tsx
packages/ui/src/containers/CreateAccount/index.test.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
packages/ui/src/containers/SocialSignIn/SecondarySocialSignIn/index.test.tsx
packages/ui/src/index.tsx
packages/ui/src/pages/SocialSignInCallback/index.test.tsx

extract ReactModal elementApp and fix act() warning in ut
test locally @eng

fix(ui): extract ReactModal elementApp and fix act warning in ut

---

packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
packages/ui/src/include.d/dom.d.ts

Add sandbox props to the iframe. Set undefined to allow all restrictions.
Also add the related issue for API response guard, inorder to remove the JSON response type assert. 
test locally
@logto-io/eng

fix(ui): add sandbox props to iframe

---

packages/schemas/jest.config.ts
packages/schemas/package.json
packages/schemas/src/gen/index.ts
packages/schemas/src/gen/schema.ts
packages/schemas/src/gen/types.ts
packages/schemas/src/gen/utils.test.ts
packages/schemas/src/gen/utils.ts
packages/schemas/tsconfig.build.json
packages/schemas/tsconfig.json
packages/schemas/tsconfig.test.json
pnpm-lock.yaml

Append the fields' string max length limitations to `guard` and `createGuard` of the database table schemas.
- If the field in the table column definition (e.g. `field_a` in `create table examples (field_a varchar(16), …);`) is the character type with the length limit (`varchar(16)`), we will append the `.max(n)` to its `ZodString` guard to check its max length.
Diff generated `db-entries/*.ts` (just for preview):
Generated `API Reference` page:
UTs

feat(schemas): guard string max length

---

packages/core/jest.setup.ts
packages/core/src/connectors/consts.ts
packages/core/src/connectors/index.ts
packages/core/src/env-set/index.ts
packages/core/src/env-set/oidc.test.ts
packages/core/src/env-set/oidc.ts
packages/core/src/env-set/utils.ts

- use comma separated values as a string array in the env file
- use `getEnvAsStringArray` to read `additionalConnectorPackages` from env
- add `additionalConnectorPackages` to the `env-set` and read `additionalConnectorPackages` after the `env-set` is loaded.
- update oidc private keys config and treat old envs (`OIDC_PRIVATE_KEY` and `OIDC_PRIVATE_KEY_PATHS`) as deprecated.
Test Locally & UT passed.

feat(core)!: use comma separated values as a string array in the env file

---

packages/core/src/env-set/oidc.ts

In `readPrivateKeys` method:
- rename `defaultLogtoOidcPrivateKey` -> `defaultLogtoOidcPrivateKeyPath`
- update the comment about the private key config reading logic.
- rename `notExistPrivateKeys` -> `nonExistentPrivateKeys` 
UT passed.

chore(core): update inaccurate content in `readPrivateKeys` method

---

.github/workflows/update-pr-metadata.yml

- use pull request ref to fix pr size diff (shows 0 in [this run](https://github.com/logto-io/logto/actions/runs/2847803408))
- https://github.com/actions/checkout/issues/518
- only `pull_request_target` is needed for workflow run, dkw it didn't trigger in the last PR
update: i think the `pull_request_target` event has a special trigger, as the update in this PR doesn't work as well. wait for another PR workflow run to confirm this.
pending CI

chore: fix and dedup workflow runs

---

packages/core/src/middleware/koa-auth.test.ts
packages/core/src/middleware/koa-auth.ts
packages/core/src/routes/authn.ts
packages/core/src/routes/init.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko-kr/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts

- add `/authn/hasura` route for [hasura authn webhook](https://hasura.io/docs/latest/auth/authentication/webhook)
- `/authn/hasura?resource=` where `resource` stands for the resource indicator for hasura API
- pass `authorization` header with bearer token as usual
- pass `expected-role` with the role that to expect the user have
- `/authn` will be used as a general authn transformation API in the future
<details>
<br />
Hasura env
```
HASURA_GRAPHQL_AUTH_HOOK: http://host.docker.internal:3001/api/authn/hasura?resource=https://api.logto.io
```
Hasura Request
With JWT
</details>
Response
and Hasura works ✅
**In Hasura**

feat(core): hasura authn

---

packages/console/src/pages/Connectors/components/ConnectorName/index.tsx

Show platform icons in connector table for multi-platform connectors, no matter how many platforms are enabled.
Local tested.

fix(console): show platform icons in connector table

---

packages/core/src/env-set/index.ts
packages/core/src/lib/user.ts
packages/core/src/queries/roles.ts
packages/core/src/queries/user.test.ts
packages/core/src/queries/user.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/core/src/routes/session/passwordless.test.ts
packages/core/src/routes/session/passwordless.ts
packages/core/src/routes/session/session.test.ts
packages/core/src/routes/session/session.ts
packages/core/src/routes/session/social.test.ts
packages/core/src/routes/session/social.ts

- set env `USER_DEFAULT_ROLE_NAMES` to add default roles when inserting a new user
- remove original `insertUser` query, replace with `insertUser` lib function

feat(core): set user default roles from env

---

package.json
packages/connector-alipay-native/package.json
packages/connector-alipay-web/package.json
packages/connector-aliyun-dm/package.json
packages/connector-aliyun-sms/package.json
packages/connector-apple/package.json
packages/connector-azuread/package.json
packages/connector-facebook/package.json
packages/connector-github/package.json
packages/connector-google/package.json
packages/connector-mock-email/package.json
packages/connector-mock-sms/package.json
packages/connector-mock-social/package.json
packages/connector-sendgrid-mail/package.json
packages/connector-smtp/package.json
packages/connector-twilio-sms/package.json
packages/connector-types/package.json
packages/connector-wechat-native/package.json
packages/connector-wechat-web/package.json
packages/core/nodemon.json
packages/core/package.json
packages/core/src/routes/authn.ts
packages/phrases-ui/package.json
packages/phrases/package.json
packages/schemas/package.json
packages/shared/package.json
pnpm-lock.yaml

- remove `tsc-watch` in all packages
- watch and incrementally build lib packages
- watch all `core` source files and dependencies using `nodemon`, rebuild and restart core if needed
- watch all frontend project using `parcel`
note the watch scripts are all independent. thus only necessary rebuilds/restarts will be triggered.
Run `pnpm dev` to execute the actions in order:
Then change some source code in `packages/connectors-apple`:
Then change some source code in `packages/console`:
All jobs are executed as expected in a very neat way. Looks good for dev.

refactor: watch all packages when dev

---

packages/console/src/pages/SignInExperience/components/AuthenticationForm.tsx
packages/console/src/pages/SignInExperience/tabs/OthersTab.tsx
packages/console/src/pages/SignInExperience/types.ts
packages/console/src/pages/SignInExperience/utilities.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts

- allow to disable account in Admin Console, resolves #1716 
- still have a follow up issue for API guarding LOG-3981
- toggle off the switch, see no "create account" in preview, either in the real SIE

feat(console): allow to disable create account

---

packages/core/src/routes/session/index.ts
packages/core/src/routes/session/middleware/koa-guard-session-action.ts
packages/core/src/routes/session/username-password.test.ts

- guard session APIs according to sign-in exp `signInMode`
- ignore guard if target app is admin console
- disable register in AC, try to call register API in a valid session, responds `403 Forbidden`
- update database to disable sign-in, successfully sign in to AC

feat(core): guard session with sign-in mode

---

packages/console/src/components/CopyToClipboard/index.module.scss

fix copytoclipboard padding, to align with design system.

style(console): fix copytoclipboard padding

---

packages/console/src/pages/SignInExperience/components/TermsForm.tsx
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts

Move terms_of_use translations from `sign_in_exp.terms_of_use` to `sign_in_exp.others.terms_of_use`
(to align with the frontend page form hierarchy.)

refactor(phrases,console): move terms_of_use translations

---

packages/console/src/components/CopyToClipboard/index.module.scss

fix border style `CopyToClipboard` padding
The new height is 36px

style(console): fix border style copy field padding

---

packages/integration-tests/src/api/api.ts

Increasing request timeout in integration tests to 10s to avoid integration tests failing on low macOS machines.
None.

test: increase request timeout in integration tests

---

packages/core/src/routes/session/middleware/koa-guard-session-action.ts

`koaGuardSessionAction` function's naming should stick to camel-case.
N/A

chore(core): function naming should stick to camel case

---

.gitpod.yml

Previously, our demo in GitPod is running in production mode with a prebuild docker image. 
But running in dev mode would be better, the user can then preview the latest code in any branch, and can even change code and get preview in real time.
This will be helpful for the new users.
With the help of the feature [prebuilds](https://www.gitpod.io/docs/prebuilds), we don't need to wait for something like `pnpm i`, so this is almost as quick as the docker image.
Open this link: https://gitpod.io/#https://github.com/logto-io/logto/pull/1878

chore: run dev mode in gitpod

---

.gitpod.yml

In gitpod, `prepack` is ensured in `init`, so we can skip this to accelerate the preparation for a dev preview.
Btw, this PR is created via Gitpod in a browser.
https://gitpod.io/#https://github.com/logto-io/logto/pull/1883

chore: skip prepack for gitpod

---

packages/console/src/pages/Connectors/components/Guide/index.tsx
packages/console/src/pages/Settings/index.tsx
packages/shared/src/language.ts
packages/shared/src/utilities/zod.ts
packages/ui/src/containers/SocialSignIn/SocialSignInDropdown/index.tsx

Fixed an issue that prevent users from going to "Settings" page in admin console when using "en-US" or any other browser locale.

fix(console,ui): fix locale guard issue in settings page

---

packages/console/src/components/MultiTextInput/types.ts
packages/console/src/components/MultiTextInput/utils.ts

Fixed the bug that inputting invalid format content in MultiTextInput component will end up with app crash and showing exception message in ErrorBoundary, instead of showing the message under the field.
Instead of

fix(console): input invalid format content in multitextinput will not crash the app

---

packages/core/src/database/utils.test.ts
packages/core/src/database/utils.ts

Per offline discussion, the empty string is meaningless in our database, so we save `''` as `null` value in our database.
UT & Testlocally.

feat(core): save empty string as null value in DB

---

packages/core/src/queries/custom-phrase.ts
packages/core/src/routes/custom-phrase.test.ts
packages/core/src/routes/custom-phrase.ts
packages/core/src/routes/init.ts
packages/schemas/src/foundations/jsonb-types.ts
packages/schemas/tables/custom_phrases.sql

- Add `phrases` schema (LOG-4060)
- Add `GET /custom-phrases/:languageKey` to get the custom phrase translation of the specified language.

feat(core,schemas): add phrases schema and GET /custom-phrases/:languageKey route

---

packages/core/src/lib/session.ts
packages/core/src/routes/session/passwordless.test.ts
packages/core/src/routes/session/social.test.ts
packages/core/src/routes/session/username-password.test.ts

Record sign in time, and save to interaction session as `ts`, also this will be exposed in every sign in API along with `redirectTo`.
This is used to verify if the user can modify sensitive profile info. If the `ts` is within a short period of time, the user can continue, and if it is exceeded, the user will be redirect to "sign in again" to refresh `ts`.
`ts` is the recommended key name in `node-oidc-provider`:
Local tested, the key `ts` can be found in session:

feat(core): add ts to interaction result

---

packages/core/src/queries/custom-phrase.ts
packages/core/src/routes/custom-phrase.test.ts
packages/core/src/routes/custom-phrase.ts

- Add `DELETE /custom-phrases/:languageKey` route
- If the specified custom phrase does not exist before deleting, it will return 404 status.
- If the specified custom phrase exists before deleting, it will return 204 status when the process succeeds.
First deletion (the specified custom phrase exists before deleting)
Second deletion (the specified custom phrase does not exist before deleting)

feat(core): add DELETE /custom-phrases/:languageKey route

---

install.js
packages/core/src/env-set/parameters.ts

Support capital letter "Y" in logto command line prompt.
Previously when prompt (Y/n) in command line, if user inputs "Y", it will be considered as negative answer and the command line tool will be terminated.

fix: support capital letter "Y" in command line prompt

---

packages/core/src/lib/session.ts
packages/core/src/utils/format.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko-kr/errors.ts
packages/phrases/src/locales/pt-pt/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts

Add a function to check if current session have the access to perform a protected action (sign in within a period of time), if not, throw an error with code `auth.require_re_authentication`. And the front-end(@simeng-li) will guide the user to re-authentice to get the access.
Local tested with the following code:
And the error payload structure is:

feat(core,phrases): add check protected access function

---

packages/console/src/pages/SignInExperience/components/Preview.tsx

Add [sandbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) attribute to iframe in SIE preview.
Have to disable the lint rule, for we need to set both "allow-scripts" and "allow-same-origin" to allow communication between the iframe and parent.
Local tested.

fix(console): add sandbox attribute to iframe

---

packages/core/src/database/insert-into.ts
packages/core/src/queries/custom-phrase.ts
packages/core/src/routes/custom-phrase.test.ts
packages/core/src/routes/custom-phrase.ts
packages/core/src/routes/swagger.ts
packages/core/src/utils/zod.test.ts
packages/core/src/utils/zod.ts

- Add `PUT /custom-phrases/:languageKey` route
- Bugfix: `returning *` should be after `on conflict …` in the `insert into …` SQL statement
(see [doc](https://www.postgresql.org/docs/current/sql-insert.html) for more details)
- Update swagger.json content about `translationGuard`
- UTs
- Request
- API reference page

feat(core): add PUT /custom-phrases/:languageKey route

---

packages/schemas/tables/logto_configs.sql

Add `_logto_configs` table to store "metadata", a usage is to store "dbVersion" that will be used to implement database migration.
Notice that in our schema, table name should be countable noun, so "logto" and "logto_info" are not valid.
Tested in local DB engine.

feat(schemas): add logto configs table

---

packages/core/src/queries/custom-phrase.ts
packages/core/src/routes/custom-phrase.test.ts
packages/core/src/routes/custom-phrase.ts

Get all custom phrases in the database.
- UTs
- HTTP request

feat(core): add GET /custom-phrases route

---

packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
packages/console/src/pages/SignInExperience/components/index.module.scss
packages/console/src/pages/SignInExperience/types.ts
packages/console/src/pages/SignInExperience/utilities.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/ko-kr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp.ts
packages/schemas/src/foundations/jsonb-types.ts

- feat(console): auto detect language setting
- treat `fallbackLanguage` as the "default language" in the admin console.
Test locally.

feat(console): auto detect language setting

---

packages/phrases-ui/src/locales/ko-kr.ts
packages/phrases-ui/src/locales/tr-tr.ts

Fix the typo `en` → `trTR` and add the resource type

fix(phrases): phrases-ui typo and types

---

packages/console/src/App.tsx
packages/console/src/utilities/router.ts

Fixed a issue that caused by incorrect react router basename in console, which blocks devs from signing-in to admin console in their local dev environment.

fix(console): get prefixed router basename in local dev env

---

packages/ui/src/App.tsx
packages/ui/src/apis/utils.ts
packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/Passwordless/index.module.scss
packages/ui/src/pages/ForgotPassword/index.test.tsx
packages/ui/src/pages/ForgotPassword/index.tsx
packages/ui/src/pages/Passcode/index.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SecondarySignIn/index.module.scss
packages/ui/src/pages/SecondarySignIn/index.tsx
packages/ui/src/types/guard.ts
packages/ui/src/types/index.ts

add forget password flow
refactored the passwordless container, extract the terms related widget to the outer scope, so it can be reused in other pages like forget the password.
test locally
@logto-io/eng 
@logto-io/mandatory-reviewers

feat(ui): add forget password flow

---

packages/core/src/routes/custom-phrase.test.ts
packages/core/src/routes/custom-phrase.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko-kr/errors.ts
packages/phrases/src/locales/pt-pt/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts

Cannot delete the specified custom phrase used as default language in sign-in experience.
- Add translations of a new error message in `@logto/phrases` (marked by `// UNTRANSLATED` comments) that should be determined by @fleuraly @BTX26 later.
- UTs
- HTTP request

feat(core): cannot delete custom phrase used as default language in sign-in exp

---

packages/core/src/lib/session.ts
packages/core/src/routes/session/index.test.ts
packages/core/src/routes/session/index.ts
packages/core/src/routes/session/username-password.test.ts
packages/core/src/routes/session/username-password.ts
packages/integration-tests/src/client/index.ts
packages/integration-tests/tests/api/session.test.ts

LOG-4214
refactor admin user auth check logic. Previously we only have blockers on the username-password sign-in route which won't block the consent flow of an authenticated user. Move the blocker to the consent route.  
test locally
@logto-io/eng 
@logto-io/mandatory-reviewers 
@charIeszhao

refactor(core): refactor admin user auth check logic

---

packages/core/src/middleware/koa-spa-session-guard.ts
packages/phrases-ui/src/locales/en.ts
packages/phrases-ui/src/locales/fr.ts
packages/phrases-ui/src/locales/ko-kr.ts
packages/phrases-ui/src/locales/pt-pt.ts
packages/phrases-ui/src/locales/tr-tr.ts
packages/phrases-ui/src/locales/zh-cn.ts
packages/ui/src/containers/CreateAccount/index.module.scss
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PasswordlessSwitch.test.tsx
packages/ui/src/containers/Passwordless/PasswordlessSwitch.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/Passwordless/index.module.scss
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn/index.module.scss
packages/ui/src/containers/SocialSignIn/PrimarySocialSignIn/index.tsx
packages/ui/src/containers/UsernameSignIn/index.module.scss
packages/ui/src/containers/UsernameSignIn/index.tsx
packages/ui/src/pages/ForgotPassword/index.tsx
packages/ui/src/pages/Register/index.tsx
packages/ui/src/pages/SecondarySignIn/index.tsx
packages/ui/src/pages/SignIn/index.module.scss
packages/ui/src/pages/SignIn/registry.tsx

Add passwordless switch.
This PR includes following updates:
1. Add the new forgot password page paths to the require session list
2. Update the overall styles of the sign-in/register form styles according to the latest design.
3. Make the Terms element and PasswordlessSwitch element configurable using the new `hasTerms` and `hasSwitch` props in the PassworldLess Containers.
4. Refactor the Sign-In page registry, Move the Terms element within PrimarySocialSignIn container. Just to align with the Passwordless containers. Do not show terms at the page level 
UT added
test locally

feat(ui): add passwordless switch

---

packages/core/src/connectors/add-connectors.ts

We renamed "connector-core" to "connector-kit" some days before, this breaks the filter of "add-official-connectors". Change to package name match to fix it.

fix(core): filter out connector-kit

---

package.json
packages/core/src/env-set/check-migration-state.ts
packages/core/src/env-set/index.ts
packages/core/src/migration/index.test.ts

Before app start, we must ensure that there is no undeployed migration.
Add migration state checking in `envSet.load()`:
1. for "all-yes", throw an error and stop the app from starting
2. for normal environment, prompt the user to confirm the migration deploy, if no, throw and stop.
The reference link is not available now, see LOG-4203
Also, remove tests for "getMigrationFiles" since is hard to mock the "fs" module. That is because our "jest.setup" will import this file, see https://stackoverflow.com/questions/70566676/jest-mock-doesnt-work-inside-tests-only-outside-tests

feat(core): check migration state before app start

---

packages/ui/src/components/Passcode/index.module.scss

Align passcode input with text field input styles.
on mobile view, input field does not show outline. 
test locally
@logto-io/eng 
@logto-io/mandatory-reviewers

fix(ui): align mobile input outline

---

packages/core/src/database/seed.ts
packages/core/src/env-set/index.ts
packages/core/src/migration/index.ts

After database init (`createTables()`), update migration state to latest migration file. Then the database is ready for the next migration.
notice: the word "migration" will be changed later.

feat(core): update migration state after db init

---

packages/core/src/alteration/index.ts
packages/schemas/src/types/alteration.ts

Move alteration types into schemas's `src` folder.
Previously, alteration types are in `@logto/schemas/alterations/types`, this is out of `src` folder, causing problems for `pnpm dev`:
The reason is that, `lerna` can not handle the dependencies order properly, and the "build" order for packages is wrong, the `core` does not wait for `schemas`'s `build:alterations`.
`pnpm dev` works fine.

fix(core,schemas): move alteration types into schemas src

---

packages/console/src/pages/SignInExperience/components/Preview.tsx

This reverts commit de4c46e400bb4c3f3552a984366ec99b7032ed18.
Revert "fix(console): use fallback language in preview (#1960)", for this is will be released in the language management feature.
Test locally.

Revert "fix(console): use fallback language in preview (#1960)"

---

packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
packages/console/src/pages/SignInExperience/tabs/OthersTab.tsx

Hide the manage language button in the sign-in-experience guide according to the [design](https://www.figma.com/file/UlI7FAyFMuGqxS8j1vFy0D/%F0%9F%8C%8D-%5BAC%5D-SIE-Localization?node-id=1168%3A37797).

refactor(console): hide manage language button in sign-in-experience guide

---

packages/core/src/alteration/index.ts
packages/schemas/package.json
packages/schemas/update-next.sh

- when versioning, update `@logto-io/schemas/alteration/next-*.ts` to `$version-*.ts`
- print log when alteration is done
**Execute `pnpm lerna version --no-push` in the project root**
**Execute `pnpm alteration deploy`**

refactor(schemas): auto update next alteration scripts

---

packages/console/package.json
packages/console/src/pages/SignInExperience/components/LanguagesForm.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.module.scss
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/types.ts
packages/console/src/pages/SignInExperience/components/Preview.tsx
packages/core/package.json
packages/core/src/lib/phrase.ts
packages/core/src/routes/phrase.ts
packages/phrases-ui/package.json
packages/phrases-ui/src/index.ts
packages/phrases-ui/src/types.ts
packages/phrases/package.json
pnpm-lock.yaml

- refactor(console,core,phrases): replace `LanguageKey` with `LangaugeTag` in phrase-ui related code
- add `getDefaultLanguageTag` to `phrases-ui` package, because this logic should not shared with `phrases` package by the `@logto/core-kit`.
- add `isBuiltInLanguageTag` util to `phrases-ui` package because the `built-in` is only related to the phrases-ui translations.
- add new types in `phrases-ui` package for better type resolution.
Test locally and UT passed.

refactor(console,core,phrases): replace `LanguageKey` with `LangaugeTag` in phrase-ui related code

---

packages/core/src/routes/session/forgot-password.test.ts
packages/core/src/routes/session/forgot-password.ts

Should not use the `login` field as it is a build-in field for oidc-provider interactions and will trigger auto sign-in which is not desired.
Passed UTs and tested locally.

refactor(core): should not use login to store session info

---

packages/core/package.json
packages/core/src/lib/sign-in-experience.test.ts
packages/core/src/lib/sign-in-experience.ts
packages/core/src/routes/sign-in-experience.guard.test.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts
packages/core/src/utils/zod.test.ts
packages/core/src/utils/zod.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko-kr/errors.ts
packages/phrases/src/locales/pt-pt/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts
packages/schemas/package.json
packages/schemas/src/foundations/jsonb-types.ts
pnpm-lock.yaml

Validate fallback language before updating sign-in experience
---
Related:
- _Fixed language_ will be deprecated and replaced by _default language_ according to the new sign-in experience configuration designed by @fleuraly.
- _Default language_ shown on the page is _fallback language_ stored in `SignInExperience.LanguageInfo.fallbackLanguage`.
Locally tested
UTs
- src/routes/sign-in-experience.guard.test.ts
- src/lib/sign-in-experience.test.ts
HTTP requests
- Invalid language tag
- Unsupported language
- Supported language
API reference generated by swagger.json

refactor(core,phrases,schemas): validate fallback language before updating sign-in experience

---

packages/core/src/__mocks__/user.ts
packages/core/src/queries/log.ts
packages/core/src/queries/user.ts
packages/core/src/routes/dashboard.test.ts
packages/core/src/routes/dashboard.ts
packages/schemas/alterations/next-1664356000-add-created-at-column-to-users.ts
packages/schemas/src/types/user.ts
packages/schemas/tables/users.sql

- [Add 'reated_at' column to 'users' table](https://github.com/logto-io/logto/commit/e28f3cd5aea784fc15a369076dfb67725bff1f87)
- [Analyze new user counts with 'users' table 'created_at' column](https://github.com/logto-io/logto/commit/ef75fbdd2a92c0259347a0757848593bfd56710b) 
Reference: original Slack discussion [thread](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1658922858838919)

refactor(core): count new users by created_at

---

packages/core/src/routes/custom-phrase.test.ts
packages/core/src/routes/custom-phrase.ts
packages/core/src/utils/translation.test.ts
packages/core/src/utils/translation.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko-kr/errors.ts
packages/phrases/src/locales/pt-pt/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts

`PUT /custom-phrase` route
- Remove empty string values in the input translation.
- If the input translation structure is invalid, it will fail.
Locally tested
- UTs
- HTTP requests

refactor(core,phrases): rm empty strings and check structure in PUT /custom-phrase

---

packages/schemas/alterations/next-1664462389-correct-user-created-at-column-by-user-logs.ts

Add a database alteration script to repair user `created_at` column by user logs
References: Related PR #2027 [comment](https://github.com/logto-io/logto/pull/2027#discussion_r983166717) & related Slack thread [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1664436981148519)
The test data is dumped from logto.dev database instance:
- user count = 251
- log count = 14677
Import the test data and test SQL in the local database instance:

chore(schemas): add db alteration script to repair user created_at column by user logs

---

packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/types.ts
packages/core/src/__mocks__/custom-phrase.ts
packages/core/src/lib/phrase.test.ts
packages/core/src/lib/phrase.ts
packages/core/src/lib/sign-in-experience.test.ts
packages/core/src/lib/sign-in-experience.ts
packages/core/src/queries/custom-phrase.ts
packages/core/src/routes/custom-phrase.test.ts
packages/core/src/routes/custom-phrase.ts
packages/core/src/routes/phrase.content-language.test.ts
packages/core/src/routes/phrase.test.ts
packages/core/src/routes/phrase.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko-kr/errors.ts
packages/phrases/src/locales/pt-pt/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts
packages/schemas/alterations/next-1664347703-rename-language-key-to-tag.ts
packages/schemas/tables/custom_phrases.sql

Replace language key with [language tag](https://www.w3.org/International/articles/language-tags)
- Rename `custom_phrases` table column `language_key` to `language_tag`
- Replace related types and guards: e.g. `LanguageKey` → `LanguageTag`
- Rename variables, constants, functions, comments, etc.: e.g. ”*LanguageKey“ → ”*LanguageTag“
UTs & Locally tested.

refactor(core,console,phrases,schemas): replace language key with language tag

---

packages/ui/src/components/ConfirmModal/AcModal.tsx
packages/ui/src/components/ConfirmModal/IframeConfirmModal.tsx
packages/ui/src/components/ConfirmModal/MobileModal.tsx
packages/ui/src/components/ConfirmModal/index.tsx
packages/ui/src/components/ConfirmModal/type.ts
packages/ui/src/containers/AppContent/index.tsx
packages/ui/src/containers/ConfirmModalProvider/index.tsx
packages/ui/src/containers/ConfirmModalProvider/indext.test.tsx
packages/ui/src/containers/PasscodeValidation/index.test.tsx
packages/ui/src/containers/PasscodeValidation/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.test.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/TermsOfUse/TermsOfUseConfirmModal/index.tsx
packages/ui/src/hooks/use-confirm-modal.ts

Introduce global `ConfirmModalProvider` to handle all the confirm modal actions within the page.
Add `useConfirmModal` hook to interact with the global confirm modal context provider. The show modal method will return a promise to promisify a modal confirm flow. 
Show the alert modal at the passcode validation page, if no target email/sms address is found. 
Will refactor all current passwordlessModal and TermsOfUseModal using the new implemented global `ConfirmModalProvider`.
test locally
ut added

feat(ui): global confirm modal

---

packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
packages/console/src/pages/SignInExperience/utilities.ts

The react hook form `reset` function will set the form `isDirty` state to `false` even if the value passed to `reset` function is not equal to the form default value. So we call `setValue` to get a correct `isDirty` state.
- fix: language editor form should be dirty on clear button clicked
- fix: flattenTranslation should not skip `''` string
Test locally.

fix(console): language editor form should be dirty on clear button clicked

---

packages/ui/src/App.tsx
packages/ui/src/apis/settings.ts
packages/ui/src/hooks/use-preview.ts
packages/ui/src/i18n/init.ts
packages/ui/src/i18n/utils.ts
packages/ui/src/types/index.ts
packages/ui/src/utils/sign-in-experience.test.ts
packages/ui/src/utils/sign-in-experience.ts

Refactor ui i18n logic to pick up the latest i18n design
- add new API `/getPhrase`
- remove the UI's build in resource loading logic, using the resource and language returned from the phrase api
- use build-in en as default fallback language
-  update the preview logic to load resource dynamically from the api
test locally
@xiaoyijun @IceHe

refactor(ui): refactor ui i18n

---

packages/console/src/pages/UserDetails/components/ResetPasswordForm.tsx

show correct password after reset, remove the original "btoa"
local tested, sign in with the new password

fix(console): show correct password after reset

---

packages/console/src/pages/Connectors/components/CreateForm/index.tsx

For add connector modal: clear select state on close modal.
This can prevent "select" on last "added" connector which should be unselectable.
Local tested.

fix(console): clear select state on close modal

---

packages/console/package.json
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.tsx
pnpm-lock.yaml

When we switching between custom phrases with some undefined values, the form won't work correctly with undefined values:
So, we convert all undefined values to empty string by merge it with the `emptyUiTranslation`.

fix(console): set undefined value to empty string in custom phrases

---

packages/console/src/i18n/init.ts
packages/console/src/include.d/react-i18next.d.ts
packages/console/src/pages/Settings/index.tsx
packages/demo-app/package.json
packages/demo-app/src/i18n/init.ts
packages/demo-app/src/include.d/react-i18next.d.ts
packages/phrases/package.json
packages/phrases/src/index.ts
packages/phrases/src/locales/fr/index.ts
packages/phrases/src/locales/ko-kr/index.ts
packages/phrases/src/locales/pt-pt/index.ts
packages/phrases/src/locales/tr-tr/index.ts
packages/phrases/src/locales/zh-cn/index.ts
packages/phrases/src/types.ts
pnpm-lock.yaml

For the `LangaugeKey` is now deprecated, replace the `LanguageKey` type with `LanguageTag`.
- replace `LanguageKey` with `LanguageTag`.
- refactor `LanguageKey` related logic in `@logto/phrases` for the existing logic is coupled to the `LangaugeKey` type.
- [Refactor: Align Terms with Production Design Docs](https://linear.app/silverhand/issue/LOG-4335/refactor-align-terms-with-production-design-docs)
Test locally and UTs passed.

refactor: replace `LanguageKey` with `LanguageTag`

---

packages/phrases-ui/src/locales/en.ts
packages/phrases-ui/src/locales/fr.ts
packages/phrases-ui/src/locales/ko-kr.ts
packages/phrases-ui/src/locales/pt-pt.ts
packages/phrases-ui/src/locales/tr-tr.ts
packages/phrases-ui/src/locales/zh-cn.ts
packages/ui/src/apis/forgot-password.ts
packages/ui/src/apis/utils.ts
packages/ui/src/containers/PasscodeValidation/index.test.tsx
packages/ui/src/containers/PasscodeValidation/index.tsx
packages/ui/src/containers/Passwordless/PasswordlessSwitch.test.tsx
packages/ui/src/containers/Passwordless/PasswordlessSwitch.tsx
packages/ui/src/containers/ResetPassword/index.module.scss
packages/ui/src/containers/ResetPassword/index.test.tsx
packages/ui/src/containers/ResetPassword/index.tsx

add reset password error handling flow
test locally
ut updated
@wangsijie @darcyYe cc: @logto-io/eng

feat(ui): add reset password error handling flow

---

packages/console/src/components/Tooltip/index.module.scss
packages/console/src/components/Tooltip/index.tsx
packages/console/src/hooks/use-position.ts

This PR adds vertical center support in usePosition hook (#1852)
The tooltip can be flipped to `'right' | 'left'` and the tail points correctly.
See the following examples
- `<Tooltip verticalAlign='center' horizontalAlign='end' flip='left' anchorRef={tipRef} content={t(tooltip)} />`
- `<Tooltip verticalAlign='center' horizontalAlign='start' flip='right' anchorRef={tipRef} content={t(tooltip)} />`
Locally Tested

feat: add vertical center support

---

packages/core/src/routes/well-known.ts

The `fixedLanguage` is deprecated, we now use the `fallbackLangauge` as the default language.
Tested in the demo app.

refactor(core): use fallback language as default in demo app

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/lib/sign-in-experience/index.test.ts
packages/core/src/lib/sign-in-experience/index.ts
packages/core/src/lib/sign-in-experience/sign-in-methods.test.ts
packages/core/src/lib/sign-in-experience/sign-in-methods.ts
packages/core/src/lib/sign-in-experience/sign-up.test.ts
packages/core/src/lib/sign-in-experience/sign-up.ts
packages/core/src/routes/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko-kr/errors.ts
packages/phrases/src/locales/pt-pt/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts

Split `lib/sign-in-experience.ts` into files, preparing for the complex new rules.
UTs

refactor(core): split sign in experience lib

---

packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.module.scss
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/AddLanguageSelector.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/EditSection.module.scss
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageEditor.module.scss
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageItem.module.scss
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/LanguageNav.module.scss
packages/console/src/pages/SignInExperience/components/ManageLanguageModal/index.module.scss

- Change the front of the language name in the drop-down item from `--font-label-large` to `--font-body-medium`
- Change the border color from `--color-border` to `--border-divider`
- Change the `AddLanguageSelector` button type to `default`
- Add shadow to the language selector drop-down menu
- Change the section header color to `--color-neutral-variant-60` and add paddings in the vertical direction.
- Change the front of the language name in the language nav area from `--font-title-medium` to `--font-label-large`

refactor(console): fix language editor styles

---

packages/console/src/consts/index.ts
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/Users/components/CreateForm/index.tsx
packages/console/src/pages/Users/index.tsx

Previously, in order to pass generated password from "Users Page" to "User Detail Page", the password is attached to url's query, this may become a security issue. Now save it in sessionStorage.
Local tested:

fix(console): save generated password in session storage

---

packages/cli/src/commands/connector/add.ts
packages/cli/src/commands/connector/utils.ts
packages/cli/src/commands/install/index.ts
packages/cli/src/commands/install/utils.ts

- add `--oc` option for adding connectors during init
- ask user to init if no option found

refactor(cli): add official connectors during init

---

packages/console/src/hooks/use-ui-languages.ts
packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageNav.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/index.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/use-language-editor-context.ts

According to the new product requirement, once the user adds a new language, the language is added immediately, even if 
the user does not click save or edit the language content.

refactor(console): create languages immediately on languages added in the editor

---

packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/scss/normalized.scss
packages/console/src/scss/table.module.scss

Update styles for table components per [latest design system updates](https://www.figma.com/file/RFBSbreIEYfaxJLdsb1KX1/%F0%9F%98%84-DS-components-updates?node-id=0%3A59)
* Table column text color updated to `--color-text` (darker)
* Table radius increase from 8px to 12px
* Copy icon size shrinked to 16px x 16px

refactor(console): update table styles

---

packages/core/src/routes/session/forgot-password.test.ts
packages/core/src/routes/session/forgot-password.ts
packages/core/src/routes/session/middleware/passwordless-action.ts
packages/core/src/routes/session/passwordless.test.ts
packages/core/src/routes/session/passwordless.ts
packages/core/src/routes/session/types.ts
packages/core/src/routes/session/utils.ts
packages/integration-tests/src/api/session.ts
packages/integration-tests/tests/api/session.test.ts

refactor passwordless route
- rename the forgot password identity name `id` to `userId` to be more precise. 
- remove the `VerifiedIdentity` type as it is useless. Could infer the type from StorageType directly
- remove the `parseVerificationStorage` method, as the logic is simple put it directly under `getVerificationStorageFromInteraction`;
- refactor the `assignVerificationResult`. As it is an internal method, we should use type to guard the inputs instead of using zod guard. 
- extract `smsSignIn`,`smsRegister`, `emailSignIn`, `emailRegister` actions as middlewares. So passwordless verify API could directly run the following actions without extra API call. 
ut case update
@darcyYe @wangsijie

refactor(core): refactor passwordless route

---

packages/console/src/components/Textarea/index.module.scss
packages/console/src/components/Textarea/index.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/EditSection.module.scss
packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/EditSection.tsx
packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss

- add a `Textarea` component for multiline content editing.
- display full contents in the language edit section.
- adjust the table style to fit the design doc when displaying the language content.

refactor(console): display full contents in language edit section

---

packages/console/src/pages/SignInExperience/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx

the clear button should be a small-size button for the hover-state background area is 24 x 24.

style(console): use small size button for clear button

---

packages/cli/src/commands/database/seed/index.ts
packages/cli/src/queries/logto-config.ts

since we removed init process in `core` (to keep the core service clean), hence we need to manually add the seed command to our `docker-compose.yml`.
in the CLI database seed command, add `--skip-when-exists` option to skip seeding if Logto configs table exists. helpful for demo purpose.

refactor(cli): add skip when exists option

---

packages/cli/src/commands/database/alteration/index.test.ts
packages/cli/src/commands/database/alteration/version.ts

The `end` param in `Array.prototype.slice(start, end)` will not include the end index element, so we will miss the last alteration script when choosing alteration scripts with version `next`.
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice
UT

fix(cli): `chooseAlterationsByVersion` should contain the last `next` version alteration script

---

packages/ui/src/components/Button/IconButton.module.scss
packages/ui/src/components/Checkbox/index.module.scss
packages/ui/src/components/Divider/index.module.scss
packages/ui/src/components/Drawer/index.module.scss
packages/ui/src/components/Input/index.module.scss
packages/ui/src/components/Input/phoneInput.module.scss
packages/ui/src/components/Notification/index.module.scss
packages/ui/src/components/Passcode/index.module.scss
packages/ui/src/components/TermsOfUse/index.module.scss
packages/ui/src/components/TextLink/index.module.scss
packages/ui/src/containers/PasscodeValidation/index.module.scss
packages/ui/src/containers/SocialLanding/index.module.scss
packages/ui/src/pages/ForgotPassword/index.module.scss
packages/ui/src/pages/Passcode/index.module.scss
packages/ui/src/scss/_underscore.scss

Revert recent changes to color tokens in `ui` package, as it is by design using a different design system from `console`. And @simeng-li will update it later based on the new design.

fix(ui): revert color token changes in ui as it uses different design system

---

packages/schemas/update-next.sh

https://superuser.com/questions/519374/how-to-handle-bash-matching-when-there-are-no-matches

fix: handle versioning when no `next-*.ts` found

---

packages/console/src/hooks/use-api.ts

Fixed an issue that admin console failed to display i18n content for the error key  "error.unknown_server_error"

fix(console): show i18n content of "errors.unknown_server_error"

---

packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx

This PR adds the userinfo endpoint information when viewing the "Advanced settings" pages of an application.
1. Created a new application in console
2. Navigated to "Advanced settings" tab
3. Verified userinfo endpoint information is in a field

feat(console): show userinfo endpoint information

---

packages/console/src/hooks/use-position.ts

Fix axis calculations in `use-position` hook. Previously, the dropdown position is incorrect when the page element has been scrolled.

fix(console): axis calculations in use-position hook

---

packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/ConnectorSetupWarning.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx

- refactor: `<ConnectorSetupWarning />`' should depend on the `requiredConnectors`
- fix: `<ConnectorSetupWarning />` in `SignInForm` should depend on current selected sign-in method identities.

refactor(console): connector setup warning

---

packages/ui/src/components/Button/index.module.scss
packages/ui/src/components/Button/index.tsx
packages/ui/src/components/ConfirmModal/AcModal.tsx

use the basic button style to replace old outline button style
Before:
After:
test locally

style(ui): remove outline button style

---

packages/core/src/routes/session/password.test.ts
packages/core/src/routes/session/password.ts
packages/core/src/routes/session/utils.test.ts
packages/core/src/routes/session/utils.ts
packages/integration-tests/src/helpers.ts
packages/integration-tests/tests/api/session.test.ts
packages/schemas/src/types/log.ts

Add 2 APIs:
1. `/session/sign-in/password/email`
2. `/session/sign-in/password/sms`
Integration tests are not implemented yet 
UTs.

feat(core): password sign in with phone or email

---

packages/core/src/__mocks__/user.ts
packages/core/src/routes/session/consts.ts
packages/core/src/routes/session/continue.test.ts
packages/core/src/routes/session/continue.ts
packages/core/src/routes/session/index.ts
packages/core/src/routes/session/middleware/passwordless-action.ts
packages/core/src/routes/session/passwordless.test.ts
packages/core/src/routes/session/types.ts
packages/core/src/routes/session/utils.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko/errors.ts
packages/phrases/src/locales/pt-pt/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts

If check "set a password" on SIE configs, then users sign in or register through verification code will get an error `user.require_password`, and need to call the new route `/session/sign-in/continue/password` to set a password, then will auto sign in with last verification state.
UTs

feat(core): require set a password

---

packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignInForm.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignUpForm.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/SignInMethodItem.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/utilities.ts

refactor(console): the sign-up and sign-in form interactions
- should not reset the `signUp.pasword` value on the sign-up method change. (keep user's choice)
- refactor the `computeOnSignInMethodAppended` parameters to make this method more meaningful.
- add a `getSignInMethodAuthValue` to get the correct authentication check state when modifying the sign-up identifier and authentications.
- refactor related components to make the logic simple.

refactor(console): the sign-up and sign-in form interactions

---

packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/SignInMethodItem.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/utilities.ts

- the `verificationCode` prop of SMS and Email sign-in methods should be true by default.
- the password checkbox should be enabled only when the sign-in method is not `username` and `set a password` is not required in the sign-up config.
- the verification code checkbox should be enabled when the `set a password` and the `verify at sign up` are both required in the sign-up config or the `set a password` is required and the sign-in method is SMS or Email. (the latter case will occur when we set `Username` to the `Sign Up Identifier`)
- refactor the props of `<SignInMethod />` for clarification.
Test locally.

fix(console): correct sign-in method item state

---

packages/ui/src/containers/EmailForm/EmailForm.tsx
packages/ui/src/containers/PhoneForm/PhoneForm.test.tsx
packages/ui/src/containers/PhoneForm/PhoneForm.tsx
packages/ui/src/containers/PhoneForm/SmsRegister.tsx
packages/ui/src/containers/PhoneForm/index.module.scss
packages/ui/src/containers/PhoneForm/index.tsx
packages/ui/src/containers/PhoneForm/use-sms-register.ts
packages/ui/src/hooks/use-sie.ts
packages/ui/src/pages/Register/Main.tsx
packages/ui/src/pages/SecondaryRegister/index.test.tsx
packages/ui/src/pages/SecondaryRegister/index.tsx
packages/ui/src/types/guard.ts

Following the previous PR. Add `SmsRegister` container.
- new `PhoneForm` container
- new `useSmsRegister` hook
- new `SmsRegister` container with the integration of PhoneForm` container and `useSmsRegister` hook
- Update the Primary Register page and Secondary Register page to pick up the latest `SmsRegister`  and `EmailRegister`  instead of the old `Passwordless` container. 
UT added

refactor(ui): add SmsRegister Container

---

.gitignore

Should ignore `fly.toml`, which is a configuration file of fly.io

chore: ignore fly.toml

---

packages/ui/src/apis/index.test.ts
packages/ui/src/apis/sign-in.ts
packages/ui/src/containers/EmailForm/EmailForm.tsx
packages/ui/src/containers/EmailPassword/index.tsx
packages/ui/src/containers/PhoneForm/PhoneForm.test.tsx
packages/ui/src/containers/PhonePassword/index.module.scss
packages/ui/src/containers/PhonePassword/index.test.tsx
packages/ui/src/containers/PhonePassword/index.tsx
packages/ui/src/pages/SignIn/index.test.tsx

Add PhonePassword container and new signInWithPhonePassword API.
Also minor fix:
- should clear the form error when clicking on submit in the EmailPassword Form. 
test locally
UT added

feat(ui): add PhonePassword container

---

packages/ui/src/App.tsx
packages/ui/src/containers/EmailForm/EmailForm.tsx
packages/ui/src/containers/EmailForm/EmailRegister.test.tsx
packages/ui/src/containers/EmailForm/EmailRegister.tsx
packages/ui/src/containers/EmailForm/EmailSignIn.test.tsx
packages/ui/src/containers/EmailForm/EmailSignIn.tsx
packages/ui/src/containers/EmailForm/use-email-sign-in.ts
packages/ui/src/containers/EmailPassword/index.test.tsx
packages/ui/src/containers/EmailPassword/index.tsx
packages/ui/src/containers/PhoneForm/PhoneForm.tsx
packages/ui/src/containers/PhoneForm/SmsRegister.tsx
packages/ui/src/pages/Register/index.test.tsx
packages/ui/src/pages/SecondaryRegister/index.test.tsx
packages/ui/src/pages/SecondarySignIn/index.test.tsx
packages/ui/src/pages/SecondarySignIn/index.tsx
packages/ui/src/pages/SignIn/Main.tsx
packages/ui/src/pages/SignIn/index.test.tsx
packages/ui/src/pages/SignIn/index.tsx
packages/ui/src/pages/SignInPassword/index.tsx

Add `EmailSignIn` container with `useEmailSignIn` hook
- if {password: true, isPasswordPrimary: true, verificationCode: true}: should jump to email password flow
- if {password: true, isPasswordPrimary: true, verificationCode: false} should jump to email password flow
- if {password: true, isPasswordPrimary: false, verificationCode: true}: should send passcode and jump to passwordless flow 
- if {password: false, isPasswordPrimary: true, verificationCode: true}: should send passcode and jump to passwordless flow 
Update both EmailForm and PhoneForm render button text conditionally based on sign-in or register flow.
Add tests for both EmailRegister and EmailSignIn
Replace all old `passwordless` containers with new `EmailSignIn` on all the SignIn pages. 
Add new empty page `SignInPassword` …

feat(ui): add EmailSignIn container

---

packages/ui/package.json
packages/ui/src/components/Input/PhoneInput.tsx
packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/EmailForm/EmailForm.tsx
packages/ui/src/containers/EmailForm/index.tsx
packages/ui/src/containers/EmailForm/use-email-register.ts
packages/ui/src/containers/EmailPassword/index.tsx
packages/ui/src/containers/Passwordless/EmailPasswordless.tsx
packages/ui/src/containers/Passwordless/PhonePasswordless.tsx
packages/ui/src/containers/PhoneForm/PhoneForm.tsx
packages/ui/src/containers/PhoneForm/SmsRegister.test.tsx
packages/ui/src/containers/PhoneForm/SmsSignIn.test.tsx
packages/ui/src/containers/PhoneForm/SmsSignIn.tsx
packages/ui/src/containers/PhoneForm/index.tsx
packages/ui/src/containers/PhoneForm/use-sms-register.ts
packages/ui/src/containers/PhoneForm/use-sms-sign-in.ts
packages/ui/src/containers/PhonePassword/index.tsx
packages/ui/src/containers/SetPassword/index.tsx
packages/ui/src/containers/UsernameSignIn/index.tsx
packages/ui/src/pages/ForgotPassword/index.tsx
packages/ui/src/pages/PasswordRegisterWithUsername/index.tsx
packages/ui/src/pages/ResetPassword/index.tsx
packages/ui/src/pages/SecondaryRegister/index.tsx
packages/ui/src/pages/SecondarySignIn/index.test.tsx
packages/ui/src/pages/SecondarySignIn/index.tsx
packages/ui/src/pages/SignIn/Main.tsx
packages/ui/src/pages/SignIn/index.test.tsx

Add SmsSignIn container with useSmsSignIn hook
if {password: true, isPasswordPrimary: true, verificationCode: true}: should jump to the phone password flow
if {password: true, isPasswordPrimary: true, verificationCode: false} should jump to the phone password flow
if {password: true, isPasswordPrimary: false, verificationCode: true}: should send passcode and jump to passwordless flow
if {password: false, isPasswordPrimary: true, verificationCode: true}: should send passcode and jump to passwordless flow
Add tests for both SmsRegister and SmsSignIn
Replace all old passwordless containers with new SmsSignIn on all the SignIn pages.
UT passed

feat(ui): add SmsSignIn container

---

packages/console/src/components/IconButton/index.tsx
packages/console/src/components/TipBubble/index.module.scss
packages/console/src/components/TipBubble/index.tsx
packages/console/src/components/TipBubble/utils.ts
packages/console/src/components/Tooltip/index.module.scss
packages/console/src/components/Tooltip/index.tsx
packages/console/src/hooks/use-position.ts

- Rename the `center` value in `VerticalAlignment` to `middle`; Now the `VerticalAlignment` is `top | middle | bottom` like the CSS `vertical-align` prop.
- Fix a bug when calculating the Y position of the overlay item when vertical alignment is set to `middle` in the `usePosition` hook.
- Fix vertical offset usage in `usePosition`: the vertical offset should always be added to the calculated Y value.
- Extract the tooltip display widget into `TipBubble` and make it easy to be reused when a new `ToggleTip` is added to our AC.
- Refactor the `Tooltip` props to make the component easy to use.
```js
<Tooltip position="top" horizontalAlign="start" />
```
```js
<Tooltip position="top" horizontalAlign="center" />
```
```js
<Tooltip position="top" horizontalAlign="end" />
```
```js
<Tooltip …
```

refactor(console): tooltip

---

packages/console/src/components/ToggleTip/index.module.scss
packages/console/src/components/ToggleTip/index.tsx

feat(console): toggle tip
The toggletip component has two states—active and inactive. By default, the toggletip is hidden and inactive. Toggletips are displayed on `Click` and `Enter`.
Toggletips are triggered on `Click` and is dismissed by clicking anywhere outside the toggletip’s active popover or UI trigger.
Users can trigger a toggletip by pressing `Enter` or `Space` while the trigger element has focus. Users can dismiss a toggletip by pressing `Escape`. For additional keyboard interactions, see the accessibility tab.
DS: https://www.notion.so/silverhand/Web-Toggletips-c573fdb1fdb34fbc8c2f3901b307aca0

feat(console): toggle tip

---

packages/cli/src/commands/connector/utils.ts
packages/cli/src/utilities.ts
packages/core/src/connectors/index.ts

use shared `getConnectorPackagesFromDirectory()` function to get connectors and filter out invalid packages

refactor(core): reuse connector reading function in cli

---

packages/core/src/lib/session.ts
packages/core/src/routes/session/continue.test.ts
packages/core/src/routes/session/password.test.ts
packages/core/src/routes/session/passwordless.test.ts
packages/core/src/routes/session/social.test.ts
packages/core/src/routes/session/utils.test.ts

Add sign-in timestamp to session interaction. Originally introduced in #1917 but got reverted for we didn't think it clearly enough back in the day.

feat(core): add sign-in timestamp in session interaction

---

packages/core/src/lib/session.ts
packages/phrases/src/locales/de/errors.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko/errors.ts
packages/phrases/src/locales/pt-pt/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts

Originally introduced in #1927 
Add a function to check if current session have the access to perform a protected action (sign in within a period of time), if not, throw an error with code auth.require_re_authentication. And the front-end(@simeng-li) will guide the user to re-authentice to get the access.

feat(core,phrases): add re-authentication check function for protected access

---

packages/core/src/routes/session/password.test.ts
packages/core/src/routes/session/password.ts
packages/core/src/routes/session/utils.ts

add `checkRequiredProfile` to password routes, other sign-in/register routes were added before.
UTs

fix(core): add check required profile to password routes

---

.changeset/unlucky-lizards-agree.md
packages/cli/src/commands/database/config.ts
packages/cli/src/commands/database/seed/oidc-config.ts
packages/cli/src/commands/database/utilities.ts

`logto db config rotate <key>` to rotate OIDC private and cookie keys
there's no timestamp when key created, thus user need to manually remove the old keys. perhaps to provide a command to remove outdated keys.
checked database, works as expected

feat(cli): rotate keys

---

packages/console/src/components/Dropdown/index.tsx
packages/console/src/components/ToggleTip/index.tsx
packages/console/src/components/Tooltip/index.tsx

Popup and tooltip will show in the top-left corner in the first rendering since there is no position returned in `usePosition()`.
Set the opacity to 0 when no position returns to fix the issue.
Tested locally, not improper appearance for these components.

refactor(console): fix undesired appearance for popup and tooltip

---

packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

Remove SIE identifier check from user management API, as this is management API it shouldn't bind too much business logic into it

refactor(core): remove SIE identifier check from user management API

---

packages/console/src/pages/SignInExperience/index.tsx

Unset compare data on the sie data updated to avoid the sign-up and sign-in change alert modal splashing with empty data.
- Once the SIE data is updated, the change alert modal is closed immediately.

fix(console): unset compare data on the sie data updated

---

packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/SignInForm.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignInMethodEditBox/index.tsx

The inline connector setup warning should display only once on the sign-up and sign-in page.

refactor(console): make the inline connector setup warning display only once

---

packages/core/src/queries/user.test.ts
packages/core/src/queries/user.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/api/session.ts
packages/integration-tests/src/helpers.ts
packages/integration-tests/src/utils.ts
packages/integration-tests/tests/api/dashboard.test.ts
packages/integration-tests/tests/api/get-access-token.test.ts
packages/integration-tests/tests/api/session.test.ts
packages/integration-tests/tests/api/social-session.test.ts

Adopt our [new strategy](https://www.notion.so/silverhand/Email-Address-Resolution-99ee44b471c2409884e4ea4d86815b19): store email in case-sensitive, search in case-insensitive
- use `lower()` to check email existency
- enable admin user API to create user with email, and make username optional
- add integration tests of email and password sign-in

refactor(core)!: use case insensitive search for emails

---

packages/core/src/lib/sign-in-experience/sign-in.test.ts
packages/core/src/lib/sign-in-experience/sign-in.ts

Require connector to setup before add a sms/email sign in method with "verification code".
UTs

fix(core): require connector when verification code is enabled

---

packages/core/src/queries/oidc-model-instance.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

Revoke tokens (refresh token) when user is suspended by calling management API.
UTs

feat(core): revoke tokens when user is suspended

---

packages/core/src/lib/session.ts
packages/core/src/routes/session/continue.test.ts
packages/core/src/routes/session/password.test.ts
packages/core/src/routes/session/passwordless.test.ts
packages/core/src/routes/session/social.test.ts
packages/core/src/routes/session/utils.test.ts

Change session health validation method by reverting the previous `ts` injection into the interaction object. As we found interaction object will be destroyed once the user is signed in.
Change it to directly fetch the `loginTs` property from the session object.

refactor(core): change session health validation method for session APIs

---

packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/SignInExperience/tabs/BrandingTab.tsx
packages/console/src/pages/SignInExperience/tabs/OthersTab.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/index.tsx

The old reset logic under the sie tabs will cause the form to reset data with old values when the tab is destroyed to reconstruct. This will cause some unexpected behaviors on the SIE page.
- remove the old reset logic under the SIE tabs
- unsaved changes alert now can be placed on the SIE index page for now we use the `tab` URL param to trigger the unsaved alert.
Test locally.

fix(console): avoid unexpected data reset in sign-up and sign-in tab

---

packages/console/src/pages/SignInExperience/tabs/SignUpAndSignInTab/components/SignUpAndSignInDiffSection/SignUpDiffSection.tsx

Sign-up identifier translation context should be snake case of the identifier definition.

fix(console): sign-up identifier translation

---

packages/ui/src/App.tsx
packages/ui/src/containers/PasswordlessSwitch/index.tsx
packages/ui/src/hooks/use-required-profile-error-handler.ts
packages/ui/src/pages/Continue/EmailOrPhone/index.test.tsx
packages/ui/src/pages/Continue/EmailOrPhone/index.tsx
packages/ui/src/pages/Continue/SetEmail/index.test.tsx
packages/ui/src/pages/Continue/SetEmail/index.tsx
packages/ui/src/pages/Continue/SetPassword/index.tsx
packages/ui/src/pages/Continue/SetPhone/index.test.tsx
packages/ui/src/pages/Continue/SetPhone/index.tsx
packages/ui/src/pages/Continue/SetUsername/index.tsx

Refactor continue with email or phone.
1. Remove all the SIE guards from the continue pages.  As the identifier fulfillment request comes from the server side, it may not share the same config as the SIE returned from` .well-known` SIE API.  i.e. AdminConsole.  So we need to remove the SIE guards. Let the backend to guard the update request
2. Since we can not use the SIE to validate emailOrPhone status. Implement a new route `/continue/email-or-sms/:method` that renders the email or phone switchable pages. 
3. Update the switch link logic that replaces the last segment of the paths with the target method. 
test locally
UT updated

refactor(ui): refactor continue with email or phone

---

packages/core/src/lib/session.ts
packages/core/src/lib/sign-in-experience/index.ts
packages/core/src/lib/sign-in-experience/sign-up.test.ts
packages/core/src/routes/session/continue.ts
packages/core/src/routes/session/middleware/koa-guard-session-action.ts
packages/core/src/routes/session/middleware/passwordless-action.ts
packages/core/src/routes/session/password.test.ts
packages/core/src/routes/session/password.ts
packages/core/src/routes/session/passwordless.test.ts
packages/core/src/routes/session/social.ts
packages/core/src/routes/session/utils.ts
packages/core/src/routes/well-known.ts

Create a function to get sign in experience configs according to `applicationId`, then session routes and UI are based on the same SIE configs.
UTs

fix(core): get per app sie

---

packages/core/src/lib/user.ts

Throw "invalid credentials" when a user is tring to sign in but has no password in DB.
UTs

fix(core): throw invalid credentials for empty password users

---

packages/console/src/pages/SignInExperience/components/Preview.tsx

Fix forgot password not shown on preview bug
root cause: forgot password settings were attached to the wrong position under preview configs instead of signInExperiences. 
related PR: https://github.com/logto-io/logto/pull/2358
test locally

fix(console): fix forgotpassword not shown on preview

---

docker-compose.uffizzi.yml

Add support for creating pull request environment on every PR using Uffizzi.
- Build an image for every PR build in github actions
- Uffizzi deploy github action which uses the built image to deploy the PR Environment
- Docker compose template with uses postgres instance for every PR environment
Tested this PR locally and on my fork of the repo https://github.com/waveywaves/logto/pull/2
I want to invite the maintainers of Logto to the Uffizzi project created for them. The PR setups up PR Environments for Logto to ease development and reviews. Reviewers should be able to see a preview of the PR as a hosted service. The URL of the service will be provided in a comment on the PR itself. I want to invite the maintainers of Logto to the uffizzi project to get an idea of what the platform looks …

chore: integrate Uffizzi PR Environments

---

packages/console/src/scss/_underscore.scss

Per discussion with @fleuraly, we should not remove the main content size limitations in [this PR](https://github.com/logto-io/logto/pull/2453/files#diff-94ba094bf16f4eb6b8d36f593c65bccf57e499efed80df34ee5561901e25e817), so we add the limitations back.

refactor(console): recover the main content size limitations

---

packages/console/src/pages/SignInExperience/components/Preview.module.scss

set background color for preview iframe, useful when the web page is loading slowly.
Local tested, no color difference when swiching tabs.

fix(console): set background color for preview iframe

---

packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
packages/console/src/pages/ConnectorDetails/index.module.scss
packages/console/src/pages/ConnectorDetails/index.tsx
packages/console/src/scss/resources.module.scss
packages/phrases/src/locales/de/translation/admin-console/connector-details.ts
packages/phrases/src/locales/en/translation/admin-console/connector-details.ts
packages/phrases/src/locales/fr/translation/admin-console/connector-details.ts
packages/phrases/src/locales/ko/translation/admin-console/connector-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/connector-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/connector-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/connector-details.ts

- refactor(console): connector details page
- wrap the `<SenderTester />` with `div` instead of `<form />` to make it possible to be placed into a form.
- reset connector data when the connector switches between different types without saving unsaved changes.

refactor(console): connector details page

---

packages/console/src/components/ConfirmModal/index.tsx

Secondary "Cancel" buttons in confirm modal dialogs should use the default gray style border color, instead of the light purple one.
Before:
After:

fix(console): secondary "cancel" button should use default border style

---

packages/console/src/components/CardTitle/index.module.scss

style(console): `CardTitle` should not be shrunk in the flex layout

style(console): `CardTitle` should not be shrunk in the flex layout

---

packages/core/src/__mocks__/interactions.ts
packages/core/src/routes/interaction/index.ts
packages/core/src/routes/interaction/middleware/koa-interaction-body-guard.test.ts
packages/core/src/routes/interaction/middleware/koa-interaction-body-guard.ts
packages/core/src/routes/interaction/middleware/koa-session-sign-in-experience-guard.ts
packages/core/src/routes/interaction/middleware/koa-session-sign-inexperience-guard.test.ts
packages/core/src/routes/interaction/types/guard.ts
packages/core/src/routes/interaction/types/index.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/interactions.ts

Add `koaInteractionBodyGuard`;
1. Define the payload type for all sign-in and sign-up identifiers
2. Define a guard middleware
Our existing koaGuard takes a standard Zod type as its input and infers the Output type directly from the ZodType. 
However, as we are using the [transform](https://github.com/colinhacks/zod#transform) after the Zod type parser. Its return type is `ZodEffects`<T, T[_output], T[_input]>.  The Output generic type is slightly different. Define a separate guard instead. 
UT case added.

refactor(core): add interactionGuard middleware

---

packages/console/src/pages/AuditLogDetails/index.module.scss
packages/console/src/pages/AuditLogDetails/index.tsx

refactor(console): audit log details page
- add margin-bottom to the page body
- move out nav tabs from the body card

refactor(console): audit log details page

---

packages/core/src/__mocks__/index.ts
packages/core/src/lib/user.ts
packages/core/src/routes/admin-user.test.ts
packages/schemas/alterations/next-1669091623-roles-and-scopes.ts
packages/schemas/src/seeds/roles.ts
packages/schemas/tables/roles.sql
packages/schemas/tables/scopes.sql
packages/schemas/tables/scopesroles.sql

Add RBAC related tables:
1. Add table `scopes`, with a foreign key pointing to `resources`
2. Add `id` to `roles`, because we have a display name now, and judge access by `role_name` is deperecated.
3. Add table `roles_scopes` to implement many-to-many relations.
After consideration and research, instead of `jsonb`, use the traditional foreign key constraints and a "relation" table, that would be more flexable and efficency: https://dba.stackexchange.com/questions/82009/postgres-json-field-for-many-to-many-relationships
/

feat(schemas): add roles and permissions

---

packages/console/src/components/AuditLogTable/index.module.scss
packages/console/src/components/AuditLogTable/index.tsx
packages/console/src/pages/AuditLogs/index.tsx
packages/console/src/pages/UserDetails/components/UserLogs.module.scss
packages/console/src/pages/UserDetails/components/UserLogs.tsx
packages/console/src/pages/UserDetails/index.module.scss
packages/console/src/pages/UserDetails/index.tsx

refactor(console): user logs
- remove page-related layout styles from `<AuditLogTable />`
- wrap `<AuditLogTable />` with a `div` tag for better reusability on different pages.
- when switching to the user logs tab on the user-details page, change the main content's height to `100%` to avoid scrolling.
- add `flex:1` to the `<AuditLogTable />` table section, for we want to keep the pagination on the bottom of the page.

refactor(console): user logs

---

packages/console/src/components/DetailsForm/index.tsx

- remove redundant `forwardRef` from `DetailsForm`

fix(console): remove redundant `forwardRef` from `DetailsForm`

---

packages/console/src/pages/UserDetails/components/UserSettings.tsx
packages/console/src/pages/UserDetails/index.tsx
packages/console/src/pages/UserDetails/types.ts
packages/console/src/pages/UserDetails/utils.ts

We have an unsaved changes bug on the user details page:
when the user's `name` is a `null` value, after we edit the name field and delete all our inputs, the `name` value in the form data will be `''`, and the form compares the `''` value with the raw `null` value, which will cause the form 'dirty'.
so we need to treat the `null` value as `''` in the user details form to avoid this bug. 
- refactor: remove the redundant `userFormData` prop from the `<UserSettings />` component.

fix(console): treat null value as empty in the user details form

---

packages/console/src/pages/SignInExperience/components/Preview/index.module.scss
packages/console/src/pages/SignInExperience/components/Preview/index.tsx

The customized preview style will not overwrite the `<Card />` styles, use `<div />` to wrap the `<Preview />` component.

style(console): preview

---

packages/console/src/components/AuditLogTable/index.module.scss
packages/console/src/components/Pagination/index.module.scss
packages/console/src/pages/ApiResources/index.module.scss
packages/console/src/pages/Applications/index.module.scss
packages/console/src/pages/Users/index.module.scss

refactor(console): pagination paddings
- set pagination height to 28px to avoid unexpected paddings in the page layout.
- align the pagination number info to the center.

refactor(console): pagination paddings

---

packages/console/src/scss/table.module.scss

add padding-bottom to the scrollable table to avoid hover state fading in the background

refactor(console): add padding-bottom to the scrollable table

---

packages/console/src/components/UnsavedChangesAlertModal/index.tsx
packages/console/src/pages/SignInExperience/components/TabWrapper/index.module.scss
packages/console/src/pages/SignInExperience/components/TabWrapper/index.tsx
packages/console/src/pages/SignInExperience/index.tsx
packages/console/src/pages/SignInExperience/tabs/Branding/index.tsx
packages/console/src/pages/SignInExperience/tabs/Others/index.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/index.tsx
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/index.tsx
packages/console/src/pages/SignInExperience/tabs/index.module.scss
packages/console/src/pages/SignInExperience/utilities.ts

refactor(console): sie saving logic
- feat(console): add `tabKey` and `skipPathnames` to support `<UnsavedChangesAlertModal />` to skip some specific target pathnames. the `tabKey` is used to re-render the `<UnsavedChangesAlertModal />` component on tab changes, it ensures the `<UnsavedChangesAlertModal />` takes effect when we `unblock` the navigation transition behavior in side the component when we encounter the 'skipping pathnames'.
- refactor(console): add a `TabWrapper` to ensure the form field will always be alive in the DOM tree, so the `react-hook-form` can validate all registered fields across the three tabs on submit. Otherwise, the react-hook-form will only validate the 'displayed' form fields.
- refactor(console): revalidate the form when the `SignInMethod` changed.

feat(console): sie cross tabs saving

---

packages/core/src/routes/interaction/index.test.ts
packages/core/src/routes/interaction/index.ts
packages/core/src/routes/interaction/types/guard.ts
packages/core/src/routes/interaction/types/index.ts
packages/core/src/routes/interaction/utils/find-user-by-identity.ts
packages/core/src/routes/interaction/utils/index.ts.ts
packages/core/src/routes/interaction/utils/social-verification.test.ts
packages/core/src/routes/interaction/utils/social-verification.ts
packages/core/src/routes/interaction/utils/verify-user.ts
packages/core/src/routes/interaction/verifications/identifier-verification.ts

Migrate original `social/sign-in ` API to `/verification/social/authorization_uri`;
Also renamed the passcode API, current router naming:
PUT/PATCH `/interaction`: routes that manage the interaction details
POST `/verification/:method`: initiate a new verification entity like passcode or social authorization. 
UT case added

refactor(core): migrate social/sign-in

---

packages/console/src/pages/SignInExperience/index.module.scss

The form tab content children margin-top is now specified in the tab wrapper:
So we don't need to set it in the form wrapper:
This causes unexpected margin-top in the second tab content. (`<SignInAndSignUp />`).

style(console): form tab content margin

---

packages/console/src/pages/SignInExperience/components/Preview/index.module.scss
packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.module.scss
packages/console/src/pages/SignInExperience/components/Welcome/GuideModal.tsx
packages/console/src/pages/SignInExperience/components/Welcome/index.module.scss
packages/console/src/pages/SignInExperience/components/Welcome/index.tsx
packages/console/src/pages/SignInExperience/index.module.scss

Split the SIE settings and the preview content equally, also the SIE setup guide modal.

style(console): split the sie settings and the preview content equally

---

packages/console/src/pages/AuditLogDetails/index.tsx

The tab nav link should be different when we visit the audit-logs details page from the user details pages.

fix(console): correct tab nav link on the audit-logs details page

---

packages/ui/src/containers/PasscodeValidation/use-register-with-email-passcode-validation.ts
packages/ui/src/containers/PasscodeValidation/use-register-with-sms-passcode-validation.ts
packages/ui/src/containers/PasscodeValidation/use-sign-in-with-email-passcode-validation.ts
packages/ui/src/containers/PasscodeValidation/use-sign-in-with-sms-passcode-validation.ts

Add mandatory profile missing error handle logic.
For all the passwordless sign-in and register flow. Missing the secondary profile missing error handling logic. 
- sign-in flow account not exsit error -> switch to register -> handle required profile error -> jump to continue page
-  register flow account exsit error -> switch to sign-in -> handle required profile error -> jump to continue page
test locally

fix(ui): add mandatory profile missing error handle logic

---

packages/core/src/routes/interaction/types/guard.ts
packages/core/src/routes/interaction/types/index.ts
packages/core/src/routes/interaction/utils/index.ts
packages/core/src/routes/interaction/utils/interaction.ts
packages/core/src/routes/interaction/verifications/identifier-verification.test.ts
packages/core/src/routes/interaction/verifications/identifier-verification.ts
packages/core/src/routes/interaction/verifications/profile-verification-profile-exist.test.ts
packages/core/src/routes/interaction/verifications/profile-verification-profile-registered.test.ts
packages/core/src/routes/interaction/verifications/profile-verification-protected-identifier.test.ts
packages/core/src/routes/interaction/verifications/profile-verification.ts

Add profile verification method to verify the provided profile payload:
1. For all the protected identifiers, email, phone, and social, a verified identifier record must present
2. Profile fulfilling, a valid user account must be present in the identifier record.
3. Profile fulfilling, all the field must not exist
4. New register profile payload must contain valid identifiers to create a new account.  i.e. (a single username is invalid)
5. New registered and profile-fulfilling fields must not be registered by other user accounts.
6. ForgotPassord profile, new password must not equal the old one.
Please ignore the huge PR size, mostly are test cases. 
UT case added

refactor(core): add profile verification

---

packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/AddLanguageSelector.module.scss
packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/AddLanguageSelector.tsx

Fix add language button display issue. The button should be hidden after being clicked and be replaced by the search box.
Before:
After:

fix(console): add language button should be hidden on click

---

packages/console/src/pages/Connectors/components/CreateForm/index.module.scss
packages/console/src/pages/Connectors/components/CreateForm/index.tsx

Hide added connectors in "Create Connector Modal", previously, they are marked as "added" and disabled.
Local tested

feat(console): hide added connectors in modal

---

packages/console/src/components/ColorPicker/index.module.scss

Increase the `ColorPicker` interaction area for a better UX and remove redundant styles in the `label`.
Currently, we can only click the color square to open the color picker.
Click the whole input content, the color picker will pop up.

refactor(console): increase the color picker interaction area

---

packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/components/CopyToClipboard/index.tsx
packages/console/src/components/IconButton/index.tsx

According to the new design, the `CopyToClipboard` component should be 28px in height, and its icon should be 16px * 16px.

style(console): `CopyToClipboard` component

---

packages/console/src/components/TabNav/TabNavItem.module.scss

According to the design file, set the `TabNavItem` text color to neutral-30.

style(console): set the `TabNavItem` text color to neutral-30

---

packages/console/src/scss/table.module.scss

style(console): skeletons should not overlap the table header

style(console): skeletons should not overlap the table header

---

packages/console/src/components/ToggleTipButton/index.module.scss
packages/console/src/components/ToggleTipButton/index.tsx
packages/console/src/pages/Connectors/components/ConnectorStatusField/index.module.scss
packages/console/src/pages/Connectors/components/ConnectorStatusField/index.tsx

According to the new design standard, we need to replace all info tooltips with toggle tips and add a hover state to the toggle tip button.
So we added a `ToggleTipButton` component to extract related logic, and we will share this component in the future PR which will replace old tooltips.

refactor(console): extract toggle tip logic into a `ToggleTipButton` component

---

packages/console/src/scss/table.module.scss

Reverts logto-io/logto#2592
This fix caused another bug:
And the root solution is that we should scroll the table to the top when the page number changes.

Revert "style(console): skeletons should not overlap the table header"

---

packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

Context:
Trying to implement user creation util method for integration test use. Notice our admin-user management API post new user only accepts username and email as user identifiers. Should allow to set phone as well. Align with the PATCH method. 
Allow set primaryPhone in post user admin API
UT case updated

feat(core): allow set primaryPhone in post user admin api

---

packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.module.scss
packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx
packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageNav.module.scss
packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/index.module.scss
packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/index.tsx

The new `LanguageEditor` modal display rules do not fit our standard `ModalLayout` rules, so we need to customize it to make it responsive.

refactor(console): make the `LanguageEditor` responsive

---

packages/core/src/routes/connector.test.ts
packages/core/src/routes/connector.ts

should block add of social connector when original target and platform exists.
The add of non-standar social connector does not check the target+platform conflicting, which is not right.
Passed ITs and UTs.
Also tested locally.

fix: should block add of social connector when original target and platform exists

---

packages/console/src/components/CopyToClipboard/index.module.scss
packages/console/src/components/CopyToClipboard/index.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/UserDetails/index.tsx

The small-size `CopyToClipboard`'s icon is not the same as the small-size `IconButton`.
Customize the icon button size when the `CopyToClipBoard` used as "small" size component.

refactor(console): support small-size `CopyToClipBoard`

---

packages/console/src/components/Select/index.module.scss
packages/console/src/components/Select/index.tsx

the select title text ellipsis rule should apply to the title not the whole component.

style(console): fix dropdown title text ellipsis

---

packages/console/src/components/TabNav/TabNavItem.tsx

the `TabNavItem` component has to style:
1. link style, which will receive a `href` prop
2. tab style, which will receive an `onClick` prop
Refactor the `TabNavItem` props type to limit the props; we can only pass a `href` or an `onClick`.
```js
<TabNavItem href="test">Test</TabNavItem> // success
<TabNavItem onClick={() => { console.log('test'); }}>Test</TabNavItem> // success
<TabNavItem href="test" onClick={() => { console.log('test'); }}>Test</TabNavItem> // type error
<TabNavItem>Test</TabNavItem> // type error
```

refactor(console): `TabNavItem` props type

---

packages/console/src/pages/ConnectorDetails/components/SenderTester/index.tsx
packages/console/src/utilities/a11y.ts

Now, we can hit `Enter` to send test messages to the target account.
- Fix(console): the `onKeyDownHandler` should not block unregistered event key input.
Hit `Enter` and the POST request is made.

refactor(console): add a11y to the `SenderTester`

---

packages/console/src/pages/SignInExperience/components/Preview/index.tsx

Align the preview background color with the UI page, for the UI page's background has been updated.

fix(console): align the preview background color with the ui page

---

packages/console/src/components/AuditLogTable/index.tsx
packages/console/src/components/Pagination/index.tsx
packages/console/src/hooks/use-cache-value.ts
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/Users/index.tsx

Bug: the pagination is disappeared when the table is loading.
Root cause:
The `totalCount` will become `undefined` when fetching data on page changes, and this causes the pagination to disappear.

refactor(console): keep pagination when the table is loading

---

packages/schemas/generate.sh
packages/schemas/package.json
packages/schemas/src/gen/schema.ts

as we don't commit the generated files, we also don't care that much about the format. it's already readable.
10x faster for generate script alone. good for `prepack` script (tons of execution) as well.

refactor(schemas): remove eslint in generate script

---

packages/ui/src/App.tsx
packages/ui/src/containers/AppBoundary/index.module.scss
packages/ui/src/containers/AppBoundary/index.tsx
packages/ui/src/containers/AppContent/index.module.scss
packages/ui/src/containers/AppContent/index.tsx
packages/ui/src/pages/Profile/index.tsx
packages/ui/src/scss/normalized.scss

The mainflow ui has a default layout for the sign-in forms, however the profile page needs to be displayed in full-screen mode.
Therefore, we need to refactor the structure of the code to add a new full-screen layout container.

refactor(ui): add support for fullscreen profile layout

---

packages/core/src/routes/session/utils.ts

should clear connector session after getSession() as values stored in `connectorSession` is for one-time validation use.
N/A

chore: should clear connector session after getSession()

---

packages/core/src/routes/connector.test.ts
packages/core/src/routes/connector.ts

response of the connector's POST API should be ConnectorResponse, this aligns with other connector APIs.
The current response of POST API is `Connector`, which is the type of connector table.

chore: response of connector POST API should be ConnectorResponse

---

packages/cli/src/commands/database/alteration/utils.ts
packages/cli/src/commands/database/seed/index.ts

check alteration timestamp before table seeding to make sure alteration folder structure is expected
removed compiled scripts, then:

refactor: check alteration timestamp when seed database

---

packages/core/src/routes/interaction/index.test.ts
packages/core/src/routes/interaction/index.ts
packages/core/src/routes/interaction/utils/interaction.ts
packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
packages/core/src/routes/session/social.ts
packages/core/src/routes/session/utils.ts

Move assign/get connector session result under the /interaction folder. Since /session path will be removed in the near future.
UT and IT.

refactor: move assign/get connector session to interaction path

---

packages/console/src/components/Checkbox/index.module.scss
packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SignInMethodEditBox/index.module.scss

The checkbox label should not wrap in narrow containers.
Before:
After:
Since the checkbox cannot be shrunk any further, the outer panel cannot be shrunk, either.
Btw, the swap button in SIE should also have a margin left.

fix(console): checkbox label should not wrap

---

packages/console/src/pages/SignInExperience/index.module.scss

Set a minimum 535px to the left control panel in Sign-In Experience page, in order to avoid being shrunk in a narrower browser window.
535px is a magic number determined by the minimum requirement of the elements in English translation. I think we can use it before our designers make the final decision.
Before:
After:

fix(console): set min-width to left control panel in SIE

---

packages/core/src/routes/interaction/index.test.ts
packages/core/src/routes/interaction/index.ts
packages/integration-tests/src/api/interaction.ts
packages/integration-tests/src/tests/api/interaction/forgot-password.test.ts
packages/integration-tests/src/tests/api/interaction/register-with-identifier.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier.test.ts
packages/integration-tests/src/tests/api/interaction/social-interaction.test.ts
packages/integration-tests/src/tests/api/interaction/utils/sign-in-experience.ts

add fulfill user profile integration tests
Introduce a new `PUT /interaction/profile` to be able to overwrite the whole profile data.
e.g. 
1. the user has a username in the file
2. user sign-in and fulfill the profile using username and password
3. a username already exists error should be thrown
4. user should be able to remove the username, and replace the profile using a single password.
test passed

feat(test): add fulfill user profile integration tests

---

packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignInDiffSection.tsx
packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx

the `get` method will throw an error if we try to get a value from an undefined prop value. Use `getSafe` to avoid this error on the SIE page.
Test locally.

fix(console): use `getSafe` on the sie page

---

packages/core/src/routes/connector.test.ts
packages/core/src/routes/connector.ts

1. When POST non-standard social connectors, `metadata` should not be updated. As a result, when `metadata` is not presented in `ctx.body.guard`, `target` of `connectorFactory` should be checked.
2. Potential undesired empty string of `ctx.body.guard.metadata.target` could be given, this case should be considered.
Tested locally with AC.
Also updated related UTs.

fix(core): should block POST of non-standard social connectors with conflicting `target`

---

packages/console/src/pages/Users/index.tsx

The % character is used in URL encoding to represent special characters or reserved characters in a URL.
Before the string is sent to the back-end, the browser will decode it, converting %12345% back into the original character. If %12345% cannot be decoded, it will appear as \x12345% on the back end.
This causes the bug when searching users by phone; we send `%{phone}%`, and the back end will get `\x{phone}%`.

fix(console): search users by phone

---

packages/console/src/pages/SignInExperience/tabs/SignUpAndSignIn/components/SocialConnectorEditBox/AddButton.tsx

Remove the full-width limit of add social dropdown because now the connector name is customized and maybe longer than the add button.

style(console): remove full-width limit of add social dropdown

---

packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx

Add url checks for connector logo `TextInput`.

fix(console): add url check for logo

---

packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx

auto expand dark logo field is value is set.
local tested

fix(console): auto expand dark logo field

---

packages/console/src/components/Table/index.tsx
packages/console/src/components/Table/types.ts
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx

When refactoring, we found that in most cases, we render a table cell relying on multi-field of the row data and the `dataIndex` used to index the specific data field seems redundant. So the `dataIndex` is now a string to index the column and have a `string` type, and the `render` function now passes the row data directly.
Test locally.

refactor(console): table column type

---

packages/core/src/routes/interaction/utils/social-verification.ts
packages/core/src/routes/session/social.ts
packages/toolkit/connector-kit/src/types.ts

pass user agent to connectors.
CI.
Also tested locally and connector can get `userAgent` as expected.

feat: pass user agent to connector

---

packages/core/src/routes/interaction/actions/submit-interaction.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/core/src/routes/interaction/types/guard.ts
packages/core/src/routes/interaction/types/index.ts
packages/core/src/routes/interaction/utils/interaction.test.ts
packages/core/src/routes/interaction/utils/interaction.ts
packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
packages/core/src/routes/interaction/verifications/profile-verification-forgot-password.test.ts
packages/core/src/routes/interaction/verifications/profile-verification-protected-identifier.test.ts
packages/core/src/routes/interaction/verifications/user-identity-verification.test.ts
packages/core/src/routes/interaction/verifications/user-identity-verification.ts

This update is pre-condition  for LOG-4985
We removed all the identifiers from the interaction storage after the user authentication for performance improvement.
On the user sign-in flow, we need to sync the social identity's user name and avatar if sync-on-sign-in is enabled. So we must keep the social identifiers even after the user authentication is verified. 
Rename the `userAccountIdentifiers` to `authIdentifiers` @charIeszhao 
Keep all the identifiers in the record after user account verification flow.
Update the related type of SIgnIn and ForgotPassword interaction results. Identifiers must exist. 
UT updates
Integration passed

refactor(core): refactor interaction identifier verification flow

---

packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/index.module.scss
packages/console/src/pages/SignInExperience/components/SignUpAndSignInChangePreview/index.module.scss

BUG:
FIX:
- remove the `min-width` limit of the container, because this should have an auto width, the `552px` comes from the design file but it's not a limit.
- 'wrap word' in the `DiffSection` `li` items, or the content will be overflowed when the connector name is too long.

style(console): `SignUpAndSignInChangePreview`

---

packages/console/src/pages/Connectors/index.tsx

Clear connector create form state on closed.
BUG:
The create form modal state will reserve when we close the form by clicking the back button of the browser.
So we decide to re-render the create form modal each time we open it.
https://user-images.githubusercontent.com/10806653/210036775-58a92b71-9ab2-4a4c-bcfa-eca647f4749e.mp4
Test locally.

fix(console): clear connector create form state on closed

---

packages/console/src/pages/ConnectorDetails/components/ConnectorContent.tsx
packages/console/src/pages/Connectors/components/ConnectorForm/index.tsx
packages/console/src/pages/Connectors/components/Guide/index.tsx

Set default dark visibility based on the initial formdata: if `darkLogo` has value.
Local tested

fix(console): dark visible base on initial form data

---

.changeset/config.json
packages/cli/src/commands/install/index.ts
packages/cli/src/commands/install/utils.ts

- remove official connectors inquiry since we added them as built-in in all distributions
- lock default download to make sure the schemas in cli matches the distribution - we use an in-CLI schema module to provide a convenient way for DB alteration without source code. So CLI have to keep the schema dependency - maybe we can ask user to choose the schema source in the future.
- lock cli version with the core group since now cli will download the fixed version distribution when init
- no official connector prompt during init
- default download version now points to a specific release

refactor(cli): remove official connectors inquiry

---

.github/workflows/integration-test.yml
.github/workflows/main.yml
Dockerfile

- remove explicit node 18 since our [run steps](https://github.com/silverhand-io/actions-node-pnpm-run-steps/blob/master/action.yml#L6) now uses 18 as default
- use node 18 to build docker image
CI

ci: use node 18 as default

---

packages/core/src/libraries/sign-in-experience/index.ts

demo app notification should always follow the system language discard of SIE language settings.
test locally

fix(demo-app): demo app notificaiton should always follow system language

---

packages/console/src/components/UserName/index.tsx
packages/console/src/pages/UserDetails/components/UserSettings.tsx
packages/console/src/pages/UserDetails/types.ts
packages/console/src/pages/UserDetails/utils.ts
packages/core/src/__mocks__/user.ts
packages/core/src/libraries/user.ts
packages/core/src/oidc/scope.ts
packages/core/src/queries/roles.test.ts
packages/core/src/queries/roles.ts
packages/core/src/queries/user.test.ts
packages/core/src/queries/user.ts
packages/core/src/queries/users-roles.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/integration-tests/src/tests/api/admin-user.test.ts
packages/schemas/alterations/next-1672815959-user-roles.ts
packages/schemas/src/seeds/roles.ts
packages/schemas/src/types/user.ts
packages/schemas/tables/users.sql
packages/schemas/tables/usersroles.sql

1. create table `users_roles` to store user->role relations
2. remove old `user.role_names`
3. create an alteration to migrate old data
The "roleNames" is still available in many place, it is selected from new table "users_roles".
pass all tests.
and local tested with the alter script.

feat: add users_roles table and remove role_names

---

packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts

return `roleNames` for admin user detail api: `/users/:id`.
please notice that `roleNames` will be removed before lunching RBAC, so this is a temp solution.
Local tested with "Audit Logs" page.

fix(core): return role names for admin user detail api

---

.changeset-staged/six-falcons-sin.md
packages/cli/src/commands/database/utilities.ts
packages/core/src/env-set/oidc.ts
packages/core/src/event-listeners/index.ts
packages/core/src/oidc/init.ts
packages/core/src/oidc/utils.ts

- cli: use `ec` with `secp384r1` as the default key generation type
- core: use `ES384` as the signing algorithm for EC keys
the tests are executed in order:
The new token has a significant length reduction but it's still secure. See the links in code.

refactor: support EC key and ES signing algorithms

---

packages/core/src/libraries/session.ts
packages/core/src/libraries/user.test.ts
packages/core/src/libraries/user.ts
packages/core/src/queries/application.test.ts
packages/core/src/queries/application.ts
packages/core/src/queries/connector.test.ts
packages/core/src/queries/oidc-model-instance.test.ts
packages/core/src/queries/oidc-model-instance.ts
packages/core/src/queries/passcode.test.ts
packages/core/src/queries/resource.test.ts
packages/core/src/queries/roles.test.ts
packages/core/src/queries/setting.test.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/queries/user.test.ts
packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/core/src/routes/application.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/core/src/routes/interaction/index.ts
packages/core/src/routes/interaction/verifications/identifier-payload-verification.test.ts
packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
packages/core/src/routes/profile.test.ts
packages/core/src/routes/profile.ts
packages/core/src/tenants/Libraries.ts
packages/core/src/tenants/Tenant.ts
packages/core/src/tenants/TenantContext.ts
packages/core/src/test-utils/tenant.ts

- add `Libraries` class to aggregate all libraries with a tenant context
- migrate `libraries/user.ts` to the factory mode and update related routes using the new factories
- make `MockTenant` more extendable by allowing **PARTIAL OVERRIDE** queries and libraries
- update unit tests accordingly
@logto-io/eng after this migration of all queries and libraries, mocking becomes more reasonable, see examples:
- `packages/core/src/queries/passcode.test.ts` mocking single query set only
- `packages/core/src/routes/admin-user.test.ts` mocking multiple query sets and library
CI

refactor(core): migrate user library to factory mode

---

packages/schemas/alterations/next-1673349501-sms-sign-in-identifier-to-phone.ts

fix alteration script typo
fix a bug in the alteration script.  The enum value has a typo and failed to migrate the data properly. 
test locally

fix(schemas): fix aleration script typo

---

packages/console/src/pages/SignInExperience/constants.ts
packages/console/src/pages/SignInExperience/types.ts

fix sign-up identifier key
AC uses the `SignUpIdentifier.Sms` as phrase index.  Replace with phone
test locally

fix(console): fix sign-up identifier key

---

.changeset-staged/unlucky-months-clap.md
.vscode/settings.json
packages/core/src/libraries/passcode.test.ts
packages/core/src/libraries/passcode.ts
packages/core/src/queries/passcode.test.ts
packages/core/src/queries/passcode.ts
packages/core/src/routes/init.ts
packages/core/src/routes/interaction/index.ts
packages/core/src/routes/interaction/types/guard.ts
packages/core/src/routes/interaction/types/index.ts
packages/core/src/routes/interaction/utils/index.ts
packages/core/src/routes/interaction/utils/verification-code-validation.ts
packages/core/src/routes/interaction/verifications/identifier-payload-verification.ts
packages/core/src/routes/verification-code.test.ts
packages/core/src/routes/verification-code.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/interactions.ts
packages/schemas/src/types/verification-code.ts

* Add `/verification-code` API route to support `Generic` type passcode
* Add `request code` and `verify code` APIs and util logics
* Refactor: extract verification code related zod guards and types to `schemas`, and re-use them everywhere

feat(core): add send and verify APIs for generic type verification code

---

packages/ui/src/components/Toast/index.tsx
packages/ui/src/components/VerificationCode/index.test.tsx
packages/ui/src/components/VerificationCode/index.tsx
packages/ui/src/containers/VerificationCode/index.tsx

1. Prevent toast from taking away the active element focus status
2. Prevent ['e', '+', '-', '.'] from input box typing. By default, they were allowed by the numeric input field. 
3. Filter numeric chars only from the clipboard
4. Clear the input fields after click on the resend code button 
test locally
UT updated

fix(ui): verification-code iteration fix

---

packages/schemas/alterations/next-1673465463-ac-scope-name.ts
packages/schemas/src/seeds/scope.ts

modify management api default scope name to `mangement-api-default`, the original name `default` may be ambigous in some situations.
Local tested with the DB seeded from master branch.

fix(schemas): modify management api default scope name

---

packages/core/src/oidc/init.ts
packages/integration-tests/src/tests/api/get-access-token.test.ts
packages/integration-tests/src/utils.ts
pnpm-lock.yaml

fix getResourceServerInfo userId: use `ctx.session.userId` as the `userId`, because the previous one may not be empty.
Local tested.

fix(core): fix getResourceServerInfo userId

---

packages/console/src/components/Table/index.module.scss
packages/console/src/components/Table/index.tsx
packages/console/src/pages/SignInExperience/tabs/Others/components/ManageLanguage/LanguageEditor/LanguageDetails.tsx

Per offline discussion, the `Table` component should have the following behaviors on hover:
- The hover effect should exist by default
- When the row is clickable, the pointer should be a cursor
- When the row is unclickable, the pointer should be default

refactor(console): table hover behaviors

---

packages/console/src/components/Table/index.tsx

The table component will display the empty and error state when an error occurs.

fix(console): hide table empty state on table error

---

packages/console/src/components/UserRolesTransfer/components/TargetRoleItem/index.module.scss

- hidden role item info on overflow
- add margin-right to the info content.

style(console): hidden role item info on overflow

---

.github/workflows/main.yml

use the current version tag as the base ref, and compare it to all `next` alteration scripts for database alteration test, as it's closer to the real use case.
CI

ci: use current version for alteration test

---

packages/ui/src/components/Input/index.module.scss
packages/ui/src/components/Input/phoneInput.module.scss

Fix phone input field padding issue. CSS rule fixing.
Before:
After:
test locally

style(ui): fix phone input field padding issue

---

packages/console/src/components/PermissionsTable/index.tsx
packages/console/src/pages/RoleDetails/RolePermissions/index.tsx
packages/console/src/pages/RoleDetails/RoleUsers/index.tsx
packages/console/src/pages/UserDetails/UserRoles/index.tsx
packages/phrases/src/locales/de/translation/admin-console/general.ts
packages/phrases/src/locales/de/translation/admin-console/role-details.ts
packages/phrases/src/locales/en/translation/admin-console/general.ts
packages/phrases/src/locales/en/translation/admin-console/role-details.ts
packages/phrases/src/locales/fr/translation/admin-console/general.ts
packages/phrases/src/locales/fr/translation/admin-console/role-details.ts
packages/phrases/src/locales/ko/translation/admin-console/general.ts
packages/phrases/src/locales/ko/translation/admin-console/role-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
packages/phrases/src/locales/pt-br/translation/admin-console/role-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/role-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/role-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/role-details.ts

In the following 3 situations, we should use 'remove' instead of 'delete':
- Remove permissions from a role
- Remove users from a role
- Remove roles from a user
Test locally.

refactor(phrases): update rbac-related removing phrases

---

packages/ui/src/components/ConfirmModal/MobileModal.module.scss

Add mobile modal max-width on a wide screen like iPad.
test locally.

style(ui): fix mobile modal max-width

---

packages/ui/src/apis/interaction.ts

Reverts logto-io/logto#2988
As we do not have a reader–writer lock on the interaction storage. All the interaction requests can not run async.

Revert "refactor(ui): optimize api call stack"

---

packages/ui/src/containers/VerificationCode/use-continue-flow-code-verification.ts
packages/ui/src/containers/VerificationCode/use-forgot-password-flow-code-verification.ts
packages/ui/src/hooks/use-api.ts

should call the error callback after the async error handler is resolved.
E.g. 
The verification code should clear after the error confirm modal is closed. 
test locally

fix(ui): call error callback  after async error handler

---

packages/ui/src/components/Input/PhoneInput.tsx

https://caniuse.com/?search=replaceAll
This is not a complete solution, but a workaround, but I found that there is no reason to use the replaceAll api in this scenario (it does exactly same thing as replace, but require modern browser (chrome > 85).
Locally tested use android emulator with chrome 80

fix(ui): use String.prototype.replace to make it compatible with legacy version browsers

---

.changeset/good-feet-own.md
packages/core/src/libraries/social.ts
packages/core/src/routes/init.ts
packages/core/src/routes/interaction/utils/interaction.ts
packages/core/src/routes/interaction/utils/social-verification.ts
packages/core/src/routes/saml-assertion-handler.test.ts
packages/core/src/routes/saml-assertion-handler.ts
packages/core/src/utils/saml-assertion-handler.ts

1. Per offline discussion, add a POST API (POST /saml-assertion-handler/:connectorId) for IdPs SAML assertion handling.
2. Add `assignConnectorSessionResultViaJti` (use shallow merge updating scheme) and `getConnectorSessionResultFromJti` (do not clear session after getting) to read/write provider's interaction.
3. Add `getConnector` to `tenant.socials.libraries` for convenience.
Locally tested with SAML connector, works fine.

feat(core): add POST API for handling IdP SAML assertion

---

.scripts/version.js

partially execute lifecycle scripts based on the release group
[CI](https://github.com/logto-io/logto/actions/runs/4035528020), see the core group runs db alteration renaming script but the toolkit group does not

ci: filter out ignore group when exec lifecycle scripts

---

packages/cli/package.json
pnpm-lock.yaml

- it's for build scripts and we don't use it in other packages
- `rm -rf` works in powershell too i think
/

refactor(cli): remove rimraf

---

packages/ui/src/hooks/use-social-register.ts
packages/ui/src/hooks/use-social-sign-in-listener.ts

Remove the social callback page from history.
We have a social sign-in callback page implemented.  It will parse the social auth data from callback URL search parameters and trigger a social sign-in request to the Logto server. 
Depending on different social account statuses, the user may be redirected to the link social account or bind email/phone page. 
When the user clicks on the back button at the next link page, it will return to the social callback page and triggers the sign-in request again, ending with an authorization failed error. 
Checked with designers. Using the `replace` type nav for all the navigation actions on the social callback page. This will remove the page from the history stack.  Click on the back button should lead the user back to the third-party sign-in page. …

fix(ui): remove social callback page from history

---

packages/console/src/App.tsx

The route of the `AuditLogDetails` component should be independent since we use `Outlet` to handle the user details page's tabs.

fix(console): navigate to log details page on user log clicked

---

packages/ui/src/hooks/use-social-link-related-user.ts

should handle required profile errors on bindSocialRelatedUser flow
bug noticed on the social bindRelatedUserInfo flow. fulfill additional profile is not handled.
test locally

fix(ui): should handle requiredProfile error on bindSocialRelatedUser

---

packages/integration-tests/src/tests/ui/smoke.test.ts
packages/phrases-ui/src/locales/de.ts
packages/phrases-ui/src/locales/en.ts
packages/phrases-ui/src/locales/fr.ts
packages/phrases-ui/src/locales/ko.ts
packages/phrases-ui/src/locales/pt-br.ts
packages/phrases-ui/src/locales/pt-pt.ts
packages/phrases-ui/src/locales/tr-tr.ts
packages/phrases-ui/src/locales/zh-cn.ts
packages/ui/package.json
packages/ui/src/components/InputField/index.module.scss
packages/ui/src/components/InputField/index.tsx
packages/ui/src/components/TermsOfUse/index.module.scss
packages/ui/src/components/TermsOfUse/index.tsx
packages/ui/src/containers/SetPassword/TogglePassword.tsx
packages/ui/src/containers/SetPassword/index.module.scss
packages/ui/src/containers/SetPassword/index.test.tsx
packages/ui/src/containers/SetPassword/index.tsx
packages/ui/src/pages/Continue/SetPassword/index.test.tsx
packages/ui/src/pages/PasswordRegisterWithUsername/index.test.tsx
packages/ui/src/pages/ResetPassword/index.test.tsx
packages/ui/src/utils/form.ts
pnpm-lock.yaml

This PR is the start of a series of MainFlow form refactors.  
1. Define the new `InputField` Component.  the old `Input` component will be deprecated gradually. 
2. Add react-hook-form as a new dependent. Deprecate the local useForm hook gradually. 
3. Add a password toggle checkbox to control password visibility. 
4. Did some minor optimize of the password form following the suggestion from this [blog](https://web.dev/sign-in-form-best-practices/#accessible-password-inputs)
test locally
UT updated

refactor(ui): update set password form

---

.changeset-staged/nine-apes-attend.md
packages/core/src/libraries/social.ts
packages/toolkit/connector-kit/src/types.ts

Update connector interfaces since `getSession` and `setSession` passed to both `getAuthorizationUri` and `getUserInfo` are actually used as REQUIRED parameters.
Tested locally, UTs and ITs.

refactor: update connector interfaces

---

README.md
docker-compose.demo.uffizzi.yml

This PR adds a button to the project `README` which allows visitors to the logto project to get a live, interactive demo of logto with one click. Each demo instance is a sandboxed [Uffizzi](https://www.uffizzi.com) environment that is isolated from other demos, like all Uffizzi previews. This button requires **no configuration** by visitors, and it **does not** require them to have a Uffizzi account.  
[![Demo](https://cdn.uffizzi.com/demo-button.svg)](https://app.uffizzi.com/demo/github.com/logto-io/logto)
This button makes a request to a public route `https://app.uffizzi.com/demo/github.com/logto-io/logto` which will trigger a demo deployment of logto on Uffizzi Cloud based on [this configuration](https://github.com/gadkins/logto/blob/uffizzi-live-demo-button/docker-compose.demo.uffizzi. …

chore: add Uffizzi demo button in README

---

packages/ui/src/containers/CreateAccount/index.tsx
packages/ui/src/containers/SetPassword/index.test.tsx
packages/ui/src/containers/SetPassword/index.tsx
packages/ui/src/containers/UsernameForm/SetUsername/use-set-username.ts
packages/ui/src/containers/UsernameForm/UsernameRegister/use-username-register.ts
packages/ui/src/containers/VerificationCode/use-continue-flow-code-verification.ts
packages/ui/src/containers/VerificationCode/use-forgot-password-flow-code-verification.ts
packages/ui/src/containers/VerificationCode/use-general-verification-code-error-handler.ts
packages/ui/src/containers/VerificationCode/use-register-flow-code-verification.ts
packages/ui/src/containers/VerificationCode/use-resend-verification-code.ts
packages/ui/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
packages/ui/src/hooks/use-api.ts
packages/ui/src/hooks/use-error-handler.ts
packages/ui/src/hooks/use-password-sign-in.ts
packages/ui/src/hooks/use-required-profile-error-handler.ts
packages/ui/src/hooks/use-send-verification-code.ts
packages/ui/src/hooks/use-social-link-account.ts
packages/ui/src/hooks/use-social-link-related-user.ts
packages/ui/src/hooks/use-social-register.ts
packages/ui/src/hooks/use-social-sign-in-listener.ts
packages/ui/src/hooks/use-social.ts
packages/ui/src/pages/Consent/index.tsx
packages/ui/src/pages/Continue/SetPassword/use-set-password.ts
packages/ui/src/pages/PasswordRegisterWithUsername/index.tsx
packages/ui/src/pages/PasswordRegisterWithUsername/use-username-password-register.ts
packages/ui/src/pages/ResetPassword/use-reset-password.ts
packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx

refactor `useApi` logic. Call API synchronize.
When trying to merge our input fields using smart input-field, the previous implementation of `useApi` hook becomes painful.  
previously:
```js
import someApi from '@/api/someApi';
const errorHandlers = { /* ...  */};
const {result, run} = useApi(someApi, errorHandlers);
useEffect(() => { /* callback */}, [result]);
void run(args);
```
As you may see, the error handlers and API calls are coupled together and handled centrally.  It is hard to customize error-handling logic based on API runtime input. 
Update:
decouple the errorHandler hook and API hook. Make everything sync as we used to write API requests. Not smart but straight forward. 
```js
import someApi from '@/api/someApi';
const errorHandlers = { /* ...  */};
const request= …
```

refactor(ui): refactor useApi

---

packages/ui/src/components/InputFields/InputField/index.test.tsx
packages/ui/src/components/InputFields/InputField/index.tsx
packages/ui/src/components/InputFields/PasswordInputField/index.test.tsx
packages/ui/src/components/InputFields/SmartInputField/index.tsx
packages/ui/src/containers/SetPassword/index.test.tsx
packages/ui/src/containers/SetPassword/index.tsx
packages/ui/src/hooks/use-social-sign-in-listener.ts
packages/ui/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
packages/ui/src/pages/SignIn/IdentifierSignInForm/index.tsx
packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
packages/ui/src/pages/SignInPassword/PasswordForm/index.test.tsx
packages/ui/src/pages/SignInPassword/PasswordForm/index.tsx
packages/ui/src/utils/form.ts

Simplify the usage of inputField error message. 
Issue met:
react-hook-form provided validate method only returns a string type error message value. It is hard to parse it to a strictly i18n error translation key type. 
Refactor the input field error type to raw string instead of the ErrorType.  Do the i18n translation at the upper scope. Directly pass is a translated string value. 
test locally
UT updated

refactor(ui): simplify the usage of inputField error message

---

packages/ui/src/App.tsx
packages/ui/src/hooks/use-send-verification-code.ts
packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
packages/ui/src/pages/SignInPassword/PasswordForm/index.test.tsx

Fx the continue flow verification-code 404 bug.
Context:
1. Among the previous SmartInputField refactor PRs, all secondary pages like` sign-in/email,` or `register/email` have been removed, except for the continue page. We still use subpaths `/continue/email`, `/continue/phone`.  
2. The verification code page route was updated as `/${flow}/verification-code`.  
3.  the `sendVerificationCode` callback handler uses related path navigation
- 'sign-in' -> 'sign-in/verification-code'
- 'register' -> 'register/verification-code'
- 'forgot-password' -> 'forgot-password/verification-code'
- 'continue/email' -> 'continue/email/verification-code'
Bug:
'continue/email/verification-code' route path will lead to a 404 page.
Fix: use the absolute path for verification-code page. 
test locally

fix(ui): fix continue flow verification-code 404 bug

---

.github/workflows/release.yml

use depot to build on release only
the master workflow run showed depot can [build and push](https://github.com/logto-io/logto/actions/runs/4182578476/jobs/7245842130) arm64 images

ci: build arm64 per release

---

packages/ui/src/containers/VerificationCode/PasswordSignInLink.tsx

Fix the verification-code page switch to the password sign-in page throwing the session not found bug
The verification-code page as well as password page location.state data schema has been updated to {`identifier: SignInIdentifier, value: string}.`
All the state passed by the manual navigation method  has been updated, the state value of 'PasswordSignInLink' here is missed. 
test locally.

fix(ui): update password sign-in link state value

---

.changeset-staged/afraid-eagles-retire.md
packages/core/src/middleware/koa-audit-log.test.ts
packages/core/src/middleware/koa-audit-log.ts

Mask the password in the audit logs.
TODO:
should encrypt the password ahead before insert into the interaction storage. 
test locally
UT added

fix(core): mask password in audit log

---

commitlint.config.cjs
package.json
packages/cloud/package.json
packages/cloud/src/index.ts
packages/cloud/src/middleware/with-http-proxy.ts
packages/cloud/src/middleware/with-spa.ts
packages/cloud/src/queries/index.ts
packages/cloud/src/queries/tenants.ts
packages/cloud/src/routes/index.ts
packages/cloud/src/routes/tenants.ts
packages/cloud/src/utils/postgres.ts
packages/cloud/src/utils/tenant.ts
packages/cloud/src/utils/url.ts
packages/console/package.json
packages/console/src/App.tsx
packages/console/src/consts/tenants.ts
packages/console/src/containers/AppEndpointsProvider/index.tsx
packages/console/src/utils/router.ts
pnpm-lock.yaml

- init router and queries
- add `ignorePathnames` option to SPA middleware functions to filter out API requests
- add `GET /api/tenants` API to fetch all available tenant info for the current user
- admin console become dedicated SPA for cloud, mount it under the root path `/`
- dynamically fetch tenant ID from URL in console
- add `POST /api/tenants` for onboarding
- add `withAuth()` to auth requests via Access Token
- add cloud `EnvSet` to aggregate env variables
- `http://localhost:3003` loads admin console correctly
- `GET http://localhost:3003/api/tenants` returns an array of available tenant info

feat(cloud): `GET /api/tenants`

---

packages/core/src/routes/admin-user.test.ts
packages/core/src/routes/admin-user.ts
packages/core/src/routes/application.test.ts
packages/core/src/routes/application.ts
packages/core/src/routes/resource.test.ts
packages/core/src/routes/resource.ts

Remove the duplication findEntityById query before calling the deletion query. For those deletion queries we throw a DeletionError internally, calling findById is duplicate. 
UT updated

refactor(core): remove duplicate findEntityById query before delete

---

packages/cloud/package.json
packages/cloud/src/consts/rbac.ts
packages/cloud/src/index.ts
packages/cloud/src/libraries/tenants.ts
packages/cloud/src/middleware/with-auth.ts
packages/cloud/src/queries/tenants.ts
packages/cloud/src/queries/users.ts
packages/cloud/src/queries/utils.ts
packages/cloud/src/routes/tenants.ts
packages/schemas/src/seeds/management-api.ts

- support development user id header
- wrap create tenant in transaction to ensure it's an one-or-nothing action
- use class for libraries for a better closure management
- check scope for tenant creating
- tested success creating
- failed to create due to "already has a tenant"
- failed to create due to a query error (in this case, manually update development user id to a non-existing one), check database nothing changed

refactor(cloud): wrap create tenant in transaction

---

packages/ui/src/components/InputFields/SmartInputField/index.test.tsx
packages/ui/src/components/InputFields/SmartInputField/index.tsx
packages/ui/src/components/InputFields/SmartInputField/use-smart-input-field.ts
packages/ui/src/components/InputFields/SmartInputField/utils.test.ts
packages/ui/src/components/InputFields/SmartInputField/utils.ts
packages/ui/src/components/InputFields/index.tsx
packages/ui/src/containers/ForgotPasswordLink/index.tsx
packages/ui/src/containers/SetPassword/index.test.tsx
packages/ui/src/containers/SetPassword/index.tsx
packages/ui/src/pages/Continue/IdentifierProfileForm/index.tsx
packages/ui/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/ui/src/pages/ForgotPassword/index.tsx
packages/ui/src/pages/Register/IdentifierRegisterForm/index.test.tsx
packages/ui/src/pages/Register/IdentifierRegisterForm/index.tsx
packages/ui/src/pages/SignIn/IdentifierSignInForm/index.tsx
packages/ui/src/pages/SignIn/PasswordSignInForm/index.test.tsx
packages/ui/src/pages/SignIn/PasswordSignInForm/index.tsx
packages/ui/src/pages/SignInPassword/PasswordForm/index.tsx
packages/ui/src/utils/form.ts

Refactor smart input field after product feature review.
This PR address the following feature updates:
1. Should hide the country code selector (show default input type) if the value is empty
2. Should hide the country code selector when clicking on the clear input button.
3. Should switch to phone number input mode if more than 2 digits are detected
Also, include the following tech improvements:
1. Set the default input type to be undefined unless specified. 
-  previously at least one non-empty input type must be specified for the SmartInputField
- should keep the input type undefined if the input value is empty and more than one possible input type is enabled
- this will resolve the first two feature requests listed above
2. Since we use the react-hook-form's controller on all smart …

refactor(ui): refactor smart input field

---

packages/ui/src/containers/SocialSignIn/SocialSignInList/index.tsx
packages/ui/src/containers/SocialSignIn/index.tsx

Move native app postMessage listener from `<SocialSignIn />` container to its sub-component `<SocialSignInList />`, as the former container is used conditionally when no other sign-in method is configured other than social.
This seems only affects the sign-in flow using native platform connectors (alipay-native, wechat-native).

fix(ui): native app postMessage listener should be registered properly

---

packages/phrases-ui/src/index.ts
packages/phrases-ui/src/locales/ru.ts

Added localization for Russian language.
Locally built and launched the docker image. Checked that the translation appeared in sign-in experience.

feat(phrases): add "ru" language

---

packages/cloud/src/index.ts
packages/cloud/src/middleware/with-pathname.ts
packages/cloud/src/routes-anonymous/index.ts

add two APIs for status check. not sure [I'm a teapot](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418) is proper, but it looks harmless
locally. status APIs don't need auth

feat(cloud): add status apis

---

packages/ui/src/utils/country-code.test.ts
packages/ui/src/utils/country-code.ts

update country code detection logic. Languages like Russan has the language code as `ru`. 
Add the fallback logic, trying to detect the country code directly from the language code prefix.
UT added.

fix(ui): update country code detection logic

---

packages/core/src/routes/phrase.test.ts
packages/core/src/routes/phrase.ts
packages/ui/src/App.tsx
packages/ui/src/apis/settings.ts
packages/ui/src/i18n/init.ts
packages/ui/src/i18n/utils.ts

Refactor gets phrases for preview.
Previous design:
Core:
`GET /phrases` API reads the requested language from the header as the detected language and reads the DB SIE language settings; if is auto detect enabled, it returns the detected language phrases, else it returns the fallback language phrases. 
UI:
Detect the system language using i18n. Load the SIE language settings and preview configs. 
- If is preview, set the request header content as preview configs returned language. 
- If SIE has auto-detect disabled, set the request header content as the fallback language.  
- Else detect from the i18n system.
| DB auto detect | DB fallback lng | useragent language | preview config | request header | response language |
| --- | --- | --- | --- | --- | --- |
| true | zh | en | N/A | en | en …

refactor(core,ui): refactor get phrases for preview

---

packages/core/src/routes/connector.ts
packages/core/src/utils/connectors/factories.ts
packages/phrases/src/locales/de/errors.ts
packages/phrases/src/locales/en/errors.ts
packages/phrases/src/locales/fr/errors.ts
packages/phrases/src/locales/ko/errors.ts
packages/phrases/src/locales/pt-br/errors.ts
packages/phrases/src/locales/pt-pt/errors.ts
packages/phrases/src/locales/tr-tr/errors.ts
packages/phrases/src/locales/zh-cn/errors.ts

1. should throw when multiple factories are found with given `id`.
2. refactor response of GET /connector-factories(/:id) APIs.

fix(core): should throw error when multiple connector factories have same id
