packages/console/src/pages/EnterpriseSsoDetails/Experience/DomainsInput/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx
packages/integration-tests/src/tests/console/sso-connectors/sso-connectors.test.ts

1. Should clear error for email domain input as long as invalid email domains have been removed.
2. Add integration tests to cover interactions with the email domain input component.
Covered by integration tests.

fix(console,test): should clear error message and add console integration test

---

packages/cli/src/commands/database/seed/index.ts
packages/cli/src/commands/database/seed/tables.ts

add `--test` for seeding test data in CLI

feat(cli): add option to seed test data

---

packages/core/src/libraries/application.ts
packages/core/src/queries/application-user-consent-scopes.ts
packages/core/src/routes/applications/application-user-consent-scope.openapi.json
packages/core/src/routes/applications/application-user-consent-scope.ts
packages/core/src/utils/RelationQueries.ts
packages/integration-tests/src/api/application-user-consent-scope.ts
packages/integration-tests/src/tests/api/application-user-consent-scope.test.ts
packages/schemas/src/types/application.ts

add GET application user consent scopes API.
test locally

feat(core,schemas): add GET application user consent scopes api

---

packages/console/src/consts/plan-quotas.ts
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaKeyLabel/index.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/MauUnitPrices.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/utils.ts
packages/console/src/types/subscriptions.ts

Add org feature items for comparison table
This PR also remove `console.log` codes which added by accident.
feat(console): add org feature items for comparison table

feat(console): add org feature items for comparison table

---

packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericFeatureFlag.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts

Now we add an usage-based beta tip for the org feature. So we need to add related phrases and apply it for org feature.
This PR also add comments to the related `GenericFeatureFlag` components.

refactor(console): update usage-based beta features tip for org feature

---

packages/console/src/components/Guide/hooks.ts
packages/console/src/consts/applications.ts
packages/console/src/types/applications.ts
packages/core/src/routes/applications/types.ts
packages/phrases/src/locales/de/translation/admin-console/guide.ts
packages/phrases/src/locales/en/translation/admin-console/guide.ts
packages/phrases/src/locales/es/translation/admin-console/guide.ts
packages/phrases/src/locales/fr/translation/admin-console/guide.ts
packages/phrases/src/locales/it/translation/admin-console/guide.ts
packages/phrases/src/locales/ja/translation/admin-console/guide.ts
packages/phrases/src/locales/ko/translation/admin-console/guide.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/guide.ts
packages/phrases/src/locales/pt-br/translation/admin-console/guide.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/guide.ts
packages/phrases/src/locales/ru/translation/admin-console/guide.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/guide.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/guide.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/guide.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/guide.ts
packages/schemas/alterations/next-1702871078-protected-application-type.ts
packages/schemas/tables/applications.sql

Add new application type "Protected".
Existing tests.

feat(schemas): add new application type for protected app

---

packages/core/src/__mocks__/index.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/applications/types.ts
packages/schemas/alterations/next-1702877515-protected-app-configs.ts
packages/schemas/src/foundations/jsonb-types/applications.ts
packages/schemas/src/foundations/jsonb-types/index.ts
packages/schemas/src/seeds/application.ts
packages/schemas/tables/applications.sql

Alter table `applications` to add new column `protected_app_configs`.
The existing tests should pass.

feat(schemas): add column protected_app_metadata

---

packages/connectors/connector-logto-email/package.json
packages/core/package.json
packages/core/src/libraries/quota.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/connector/index.ts
packages/core/src/routes/role.ts
packages/core/src/utils/subscription/types.ts
pnpm-lock.yaml

update koaQuotaGuard to fit new pricing model
1. `applicationsLimit` should include `m2mLimit`
2. separate `machineToMachineRolesLimit` from `rolesLimit`
3. do not guard `standardConnectorsLimit`
Test locally.

feat(core,connector): update koaQuotaGuard to fit new pricing model

---

packages/integration-tests/src/tests/console/sso-connectors/sso-connectors.test.ts

add IT cases for testing config on SSO details page experience tab, including following fields:
1. connectorName
2. branding.displayName
3. branding.logo
4. branding.darkLogo
Integration test cases added, secured by CI.

chore(test): add test cases for testing config on SSO details page experience tab

---

packages/core/src/routes/interaction/actions/submit-interaction.ts

cloud integration tests will fail due to lack of permissions. this pr adds necessary data for the first admin.
local tested with onboarding. all good

refactor(core): create tenant organization for first admin

---

packages/core/src/libraries/application.ts
packages/core/src/queries/application-user-consent-scopes.ts
packages/core/src/routes/applications/application-user-consent-scope.openapi.json
packages/core/src/routes/applications/application-user-consent-scope.ts
packages/integration-tests/src/api/application-user-consent-scope.ts
packages/integration-tests/src/tests/api/application-user-consent-scope.test.ts
packages/schemas/src/types/application.ts

Add application user consent scope delete API

feat(core,schemas): add application user consent scope delete api

---

packages/connectors/connector-alipay-native/README.md
packages/connectors/connector-apple/README.md
packages/connectors/connector-wechat-native/README.md
packages/connectors/connector-wechat-web/README.md

update connector readme images URL.
Can see images in connector guides.

fix(connector): update connector readme images URL

---

packages/console/src/components/ChargeNotification/index.tsx
packages/console/src/components/ListPage/index.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.module.scss
packages/console/src/pages/Applications/index.tsx
packages/console/src/pages/Connectors/SignInExperienceSetupNotice/index.module.scss
packages/console/src/pages/Connectors/SignInExperienceSetupNotice/index.tsx
packages/console/src/scss/page-layout.module.scss
packages/phrases/src/locales/de/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/en/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/es/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/fr/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/it/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/ja/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/ko/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/pt-br/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/ru/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/index.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/index.ts

Add charge notification for add-on features
- Add sub header styles to the `ListPage` component, and reorg related codes

feat(console): add charge notification for add-on features

---

packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
packages/console/src/pages/Roles/components/CreateRoleModal/index.tsx
packages/console/src/pages/Roles/index.tsx
packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts

Add machine-to-machine roles limit guard & reorg related codes by move original logic into a `Footer` component.

refactor(console): add machine-to-machine roles limit guard

---

packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx

Use `isDevFeatureEnabled` flag to hide the new "Protected" type in application creation guide.
Local tested.

fix(console): hide new protected app type in console guide

---

packages/console/src/consts/plan-quotas.ts

- Hide standard connectors item since it will be removed in the new pricing feature
- Change the MFA order

refactor(console): update plan comparison table

---

packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts

refactor(phrases): update quota item phrases
Test locally.

refactor(phrases): update quota item phrases

---

packages/core/src/routes/applications/application.test.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/applications/constants.ts
packages/core/src/routes/applications/types.ts
packages/core/src/routes/applications/utils.ts
packages/integration-tests/src/tests/api/application/application.test.ts
packages/integration-tests/src/tests/console/applications/index.test.ts
packages/phrases/src/locales/de/errors/application.ts
packages/phrases/src/locales/en/errors/application.ts
packages/phrases/src/locales/es/errors/application.ts
packages/phrases/src/locales/fr/errors/application.ts
packages/phrases/src/locales/it/errors/application.ts
packages/phrases/src/locales/ja/errors/application.ts
packages/phrases/src/locales/ko/errors/application.ts
packages/phrases/src/locales/pl-pl/errors/application.ts
packages/phrases/src/locales/pt-br/errors/application.ts
packages/phrases/src/locales/pt-pt/errors/application.ts
packages/phrases/src/locales/ru/errors/application.ts
packages/phrases/src/locales/tr-tr/errors/application.ts
packages/phrases/src/locales/zh-cn/errors/application.ts
packages/phrases/src/locales/zh-hk/errors/application.ts
packages/phrases/src/locales/zh-tw/errors/application.ts

Modify `POST /applications` for new protected app.

feat(core): route for add protected application

---

.github/workflows/alteration-compatibility-integration-test.yml
.github/workflows/integration-test.yml
packages/cli/src/commands/install/utils.ts

update cli accordingly as we updated our engine requirement
CI in https://github.com/logto-io/cloud/pull/421

refactor(cli): update node version check

---

packages/console/src/components/ChargeNotification/index.tsx
packages/console/src/pages/ApiResources/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/schemas/src/types/logto-config.ts

Support hidding charge notification on read
- Rename `quotaItem` to `quotaItemPhraseKey` in the props of the `ChargeNotification` for better understanding

feat(console,core): support hidding charge notification on read

---

packages/console/package.json
packages/console/src/contexts/TenantsProvider.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
packages/schemas/src/types/logto-config.ts
pnpm-lock.yaml

feat(console): add charge notification for token usage

feat(console): add charge notification for token usage

---

packages/console/src/hooks/use-applications-usage.ts

Correct surpass limitation check for m2m apps

fix(console): correct surpass limitation check for m2m apps

---

packages/console/src/components/ChargeNotification/index.tsx

Hide charge notification when loading or it will flashes and disappears on every page refresh.
Test locally.

refactor(console): hide charge notification when loading

---

packages/cli/src/commands/database/seed/tables.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/schemas/alterations/next-1703152016-update-tenant-roles.ts
packages/schemas/src/types/tenant-organization.ts

update organization roles and descriptions per design.
> [!Note]
> the failing compatibility integration test (console) is expected as it's a breaking change. it's fine to proceed since the previous version hasn't been deployed to production yet.
CI + localhost

refactor: remove tenant owner role

---

packages/console/src/components/ChargeNotification/index.tsx
packages/console/src/consts/external-links.ts

refactor(console): apply new plans blog link for charge notifications
Test locally.

refactor(console): apply new plans blog link for charge notifications

---

packages/console/src/components/BillInfo/index.tsx

fix(console): update price calculation blog link
Test locally.

fix(console): update price calculation blog link

---

packages/core/src/routes/interaction/additional.test.ts
packages/core/src/routes/interaction/index.test.ts

resolve legacy unit test comments and refactor.
CI.

chore(core): resolve legacy unit tests comments and refactor

---

.changeset/fresh-lies-breathe.md
packages/core/src/queries/user.test.ts
packages/core/src/queries/user.ts
packages/shared/src/node/env/GlobalValues.ts

This PR copied the changes from https://github.com/logto-io/logto/pull/4996 and add unit tests due to the original one has master protection.
Unit tests.

feat(core): case insensitive usernames

---

packages/console/src/ds-components/CopyToClipboard/index.module.scss
packages/console/src/ds-components/CopyToClipboard/index.tsx
packages/console/src/mdx-components/ApplicationCredentials/index.module.scss
packages/console/src/mdx-components/ApplicationCredentials/index.tsx
packages/console/src/pages/ApplicationDetails/components/AdvancedSettings.tsx
packages/console/src/pages/ApplicationDetails/components/Settings.tsx
packages/console/src/pages/ApplicationDetails/index.module.scss
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.module.scss
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
packages/console/src/scss/_dimensions.scss

Support `isFullWidth` for `CopyToClipboard` component and remove duplicated codes.
Test locally.

refactor(console): support `isFullWidth` for `CopyToClipboard` component

---

packages/console/src/consts/plan-quotas.ts
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/PlanQuotaKeyLabel/index.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/components/TableDataWrapper/index.module.scss
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/components/TableDataWrapper/index.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.module.scss
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/BasePrice.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericFeatureFlag.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/GenericQuotaLimit.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/renderers/index.tsx
packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts

Update plan comparison data and styles

refactor(console): update plan comparison data and styles

---

packages/integration-tests/src/tests/console/sso-connectors/helpers.ts
packages/integration-tests/src/tests/console/sso-connectors/sso-connectors-test-cases.ts
packages/integration-tests/src/tests/console/sso-connectors/sso-connectors.test.ts

add it cases for SSO connection info, including:
1. [OIDC based]: redirect URI
2. [SAML based]: assertion consumer service URL
3. [SAML based]: entity ID
4. SSO connector ID
Covered by CI.

chore(test): add test cases for SSO connection info

---

packages/console/src/ds-components/CopyToClipboard/index.tsx
packages/console/src/ds-components/Tip/ToggleTip/index.tsx

fix(console): remove hover state from tip button after tip is closed

fix(console): remove hover state from tip button after tip is closed

---

packages/console/src/pages/Organizations/OrganizationsTable/index.tsx
packages/console/src/pages/Roles/index.tsx
packages/console/src/pages/SignInExperience/tabs/Content/components/ManageLanguage/LanguageEditor/AddLanguageSelector.module.scss
packages/console/src/pages/SignInExperience/tabs/Content/components/ManageLanguage/LanguageEditor/AddLanguageSelector.tsx
packages/console/src/pages/Users/index.tsx

fix(console): display no data when no data is found by search filter
Test locally.

fix(console): display no data when no data is found by search filter

---

packages/connectors/connector-oidc/src/utils.ts

remove unused code.
1. remove check on access token existence, since access token is unnecessary.
2. remove unused util function `isIdTokenInResponseType`
N/A

chore(connector): remove unused code

---

packages/core/src/routes/applications/application.test.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/applications/utils.ts

generate oidc metadata for protected app: `callbackUri` and `postLogoutUri`
unit tests

feat(core): generate oidc metadata for protected app

---

packages/console/src/assets/docs/guides/web-next-server-actions/README.mdx

fix next server action guide:
1. remove the export of logto client since "use server" can only export async functions
2. add a ref to ensure that the callback page only redirect once
Local preview

fix(core): fix next server action guide

---

packages/core/src/middleware/koa-pagination.ts
packages/core/src/routes/swagger/utils/parameters.ts

use const pagination key name for swagger
the swagger json looks good.

refactor(core): use const pagination key name for swagger

---

packages/console/src/pages/ApplicationDetails/index.tsx
packages/console/src/pages/ApplicationDetails/utils.ts
packages/core/src/routes/applications/application.test.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/applications/types.ts
packages/integration-tests/src/api/application.ts
packages/integration-tests/src/tests/api/application/application.test.ts
packages/phrases/src/locales/de/errors/application.ts
packages/phrases/src/locales/en/errors/application.ts
packages/phrases/src/locales/es/errors/application.ts
packages/phrases/src/locales/fr/errors/application.ts
packages/phrases/src/locales/it/errors/application.ts
packages/phrases/src/locales/ja/errors/application.ts
packages/phrases/src/locales/ko/errors/application.ts
packages/phrases/src/locales/pl-pl/errors/application.ts
packages/phrases/src/locales/pt-br/errors/application.ts
packages/phrases/src/locales/pt-pt/errors/application.ts
packages/phrases/src/locales/ru/errors/application.ts
packages/phrases/src/locales/tr-tr/errors/application.ts
packages/phrases/src/locales/zh-cn/errors/application.ts
packages/phrases/src/locales/zh-hk/errors/application.ts
packages/phrases/src/locales/zh-tw/errors/application.ts

update `PATCH /applications/:id` for protected app:
1. update protected app metadata
2. sync new configs to Cloudflare.

feat(core,phrases): update protected app

---

packages/core/src/libraries/protected-app.ts
packages/core/src/routes/applications/application.test.ts
packages/core/src/routes/applications/application.ts
packages/core/src/utils/cloudflare/kv.ts

When delete a protected app, should also delete remote configs.
No integration tests for this feature, we are not mocking Cloudflare service for now.
Unit tests.

feat(core): delete protected app

---

packages/console/src/assets/docs/guides/native-android-java/README.mdx
packages/console/src/assets/docs/guides/native-android-kt/README.mdx

refactor: update android integration guides
- Update the Android Logto SDK version to 1.1.3.
- Avoid using AppCompatActivity to demonstrate the LogtoClient initialization process, as Android now provides various patterns for initializing configurations. Users can flexibly choose these patterns (eg. ViewModel), and saving LogtoClient in an Activity is not a good practice because Activities will be recreated occasionally.
Test locally.

refactor: update android integration guides

---

packages/integration-tests/src/tests/console/sso-connectors/helpers.ts
packages/integration-tests/src/tests/console/sso-connectors/sso-connectors-test-cases.ts
packages/integration-tests/src/tests/console/sso-connectors/sso-connectors.test.ts

Add integration test cases for SAML and OIDC SSO connection configuration and fetcher preview.
Secured by CI itself.

chore(test): add test cases for SAML and OIDC SSO configuration

---

packages/core/src/oidc/grants/refresh-token.ts
packages/core/src/queries/organization/index.ts
packages/core/src/queries/organization/relations.ts
packages/core/src/tenants/Queries.ts

split org queries as the single file is too large
N/A

refactor(core): reorg organization queries

---

packages/core/src/libraries/domain.test.ts
packages/core/src/libraries/domain.ts
packages/core/src/utils/domain.test.ts
packages/core/src/utils/domain.ts
packages/phrases/src/locales/de/errors/domain.ts
packages/phrases/src/locales/en/errors/domain.ts
packages/phrases/src/locales/es/errors/domain.ts
packages/phrases/src/locales/fr/errors/domain.ts
packages/phrases/src/locales/it/errors/domain.ts
packages/phrases/src/locales/ja/errors/domain.ts
packages/phrases/src/locales/ko/errors/domain.ts
packages/phrases/src/locales/pl-pl/errors/domain.ts
packages/phrases/src/locales/pt-br/errors/domain.ts
packages/phrases/src/locales/pt-pt/errors/domain.ts
packages/phrases/src/locales/ru/errors/domain.ts
packages/phrases/src/locales/tr-tr/errors/domain.ts
packages/phrases/src/locales/zh-cn/errors/domain.ts
packages/phrases/src/locales/zh-hk/errors/domain.ts
packages/phrases/src/locales/zh-tw/errors/domain.ts
packages/schemas/src/types/system.ts

Add support for setting a list of blocked domains.
Unit tests and local tested.

feat(core,schemas): add block domain list

---

packages/schemas/alterations/next-1705288654-add-application-user-consent-organizations-table.ts
packages/schemas/tables/application_user_consent_organizations.sql

Add new application user consent organizations table. This relation represents the user-granted organizations' access to a third-party application.  user-organization relation must be present. 
Test locally

feat(schemas): add new application user consent orgs table

---

packages/core/src/libraries/application.ts
packages/core/src/queries/scope.ts
packages/core/src/routes/applications/application-user-consent-scope.ts
packages/phrases/src/locales/de/errors/application.ts
packages/phrases/src/locales/en/errors/application.ts
packages/phrases/src/locales/es/errors/application.ts
packages/phrases/src/locales/fr/errors/application.ts
packages/phrases/src/locales/it/errors/application.ts
packages/phrases/src/locales/ja/errors/application.ts
packages/phrases/src/locales/ko/errors/application.ts
packages/phrases/src/locales/pl-pl/errors/application.ts
packages/phrases/src/locales/pt-br/errors/application.ts
packages/phrases/src/locales/pt-pt/errors/application.ts
packages/phrases/src/locales/ru/errors/application.ts
packages/phrases/src/locales/tr-tr/errors/application.ts
packages/phrases/src/locales/zh-cn/errors/application.ts
packages/phrases/src/locales/zh-hk/errors/application.ts
packages/phrases/src/locales/zh-tw/errors/application.ts

Management API scopes are not allowed to be assigned to the third-party app

fix(core): add management api scopes guard

---

packages/phrases/src/locales/de/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-item.ts

Update "MFA" to "Multi-factor authentication"
Test locally.

refactor(phrases): update mfa title phrase

---

packages/core/src/tenants/SystemContext.ts
packages/schemas/src/foundations/jsonb-types/applications.ts
packages/schemas/src/types/system.ts

prepare schemas for protected app custom domain:
1. add "customDomains" to protected app metadata
2. add "protectedAppHostnameProviderConfig"
existing tests should pass.

feat(core,schemas): prepare schemas for protected app custom domain

---

packages/core/src/queries/application.test.ts
packages/core/src/queries/application.ts
packages/core/src/routes/applications/application-protected-app-metadata.test.ts
packages/core/src/routes/applications/application-protected-app-metadata.ts

Check if a domain is already in use when creating custom domain for protected app.
Unit tests.

feat(core): check application custom domain conflict

---

packages/phrases-experience/src/locales/de/action.ts
packages/phrases-experience/src/locales/de/description.ts
packages/phrases-experience/src/locales/en/action.ts
packages/phrases-experience/src/locales/en/description.ts
packages/phrases-experience/src/locales/es/action.ts
packages/phrases-experience/src/locales/es/description.ts
packages/phrases-experience/src/locales/fr/action.ts
packages/phrases-experience/src/locales/fr/description.ts
packages/phrases-experience/src/locales/it/action.ts
packages/phrases-experience/src/locales/it/description.ts
packages/phrases-experience/src/locales/ja/action.ts
packages/phrases-experience/src/locales/ja/description.ts
packages/phrases-experience/src/locales/ko/action.ts
packages/phrases-experience/src/locales/ko/description.ts
packages/phrases-experience/src/locales/pl-pl/action.ts
packages/phrases-experience/src/locales/pl-pl/description.ts
packages/phrases-experience/src/locales/pt-br/action.ts
packages/phrases-experience/src/locales/pt-br/description.ts
packages/phrases-experience/src/locales/pt-pt/action.ts
packages/phrases-experience/src/locales/pt-pt/description.ts
packages/phrases-experience/src/locales/ru/action.ts
packages/phrases-experience/src/locales/ru/description.ts
packages/phrases-experience/src/locales/tr-tr/action.ts
packages/phrases-experience/src/locales/tr-tr/description.ts
packages/phrases-experience/src/locales/zh-cn/action.ts
packages/phrases-experience/src/locales/zh-cn/description.ts
packages/phrases-experience/src/locales/zh-hk/action.ts
packages/phrases-experience/src/locales/zh-hk/description.ts
packages/phrases-experience/src/locales/zh-tw/action.ts
packages/phrases-experience/src/locales/zh-tw/description.ts

Add experience consent page phrases

feat(phrases): add experience consent page phrases

---

packages/console/src/ds-components/FormField/index.module.scss
packages/console/src/ds-components/FormField/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.module.scss
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/utils.ts
packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.module.scss
packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.tsx
packages/phrases/src/locales/de/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/es/translation/admin-console/application-details.ts
packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
packages/phrases/src/locales/it/translation/admin-console/application-details.ts
packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts

Refactor application details page in order to support protected apps
- UI layout is OK
- Submit works

refactor(console): refactor app details page to support protected apps

---

packages/console/src/components/TemplateTable/index.tsx
packages/console/src/ds-components/DataTransferBox/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/constants.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/type.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/use-application-scopes-assignment.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/use-organization-scopes-assignment.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/use-resource-scopes-assignment.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/use-user-scopes-assignment.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-scopes-table.ts
packages/phrases/src/locales/de/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/es/translation/admin-console/application-details.ts
packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
packages/phrases/src/locales/it/translation/admin-console/application-details.ts
packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts

Implement application permissions assignment using the newly added `DataTransferBox` component.
Test locally
Will add integration tests later

feat(console,phrases): implement application permissions assignment 4-4

---

packages/phrases/src/locales/de/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/es/translation/admin-console/cloud.ts
packages/phrases/src/locales/fr/translation/admin-console/cloud.ts
packages/phrases/src/locales/it/translation/admin-console/cloud.ts
packages/phrases/src/locales/ja/translation/admin-console/cloud.ts
packages/phrases/src/locales/ko/translation/admin-console/cloud.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-br/translation/admin-console/cloud.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/cloud.ts
packages/phrases/src/locales/ru/translation/admin-console/cloud.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/cloud.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/cloud.ts

chore(phrases): reword onboarding option

---

packages/core/src/__mocks__/index.ts
packages/core/src/libraries/domain.ts
packages/core/src/libraries/protected-app.test.ts
packages/core/src/libraries/protected-app.ts
packages/core/src/routes/applications/application-protected-app-metadata.openapi.json
packages/core/src/routes/applications/application-protected-app-metadata.test.ts
packages/core/src/routes/applications/application-protected-app-metadata.ts
packages/core/src/utils/cloudflare/index.ts
packages/core/src/utils/cloudflare/utils.ts
packages/schemas/src/foundations/jsonb-types/applications.ts

Sync custom status of protected app from Cloudflare.
Unit tests.

feat(core): sync protected app domain status

---

packages/console/src/assets/docs/guides/native-android/README.mdx
packages/console/src/assets/docs/guides/web-go/README.mdx

refactor(console): update go sdk integration guide
This PR also move the android API version notification into the step1, and should notice before the dependency installation.
Test locally.

refactor(console): update go sdk integration guide

---

packages/core/src/libraries/protected-app.test.ts
packages/core/src/libraries/protected-app.ts
packages/core/src/routes/applications/application-protected-app-metadata.test.ts
packages/core/src/routes/applications/application-protected-app-metadata.ts

When adding a new subdomain:
1. sync site configs to Cloudflare Workers KV
2. update OIDC metadata: `postLogoutRedirectUris` and `redirectUris`
Unit tests.

feat(core): sync site configs and oidc metadata for custom domain

---

packages/core/src/libraries/protected-app.test.ts
packages/core/src/libraries/protected-app.ts
packages/core/src/routes/applications/application-protected-app-metadata.openapi.json
packages/core/src/routes/applications/application-protected-app-metadata.test.ts
packages/core/src/routes/applications/application-protected-app-metadata.ts
packages/phrases/src/locales/de/errors/application.ts
packages/phrases/src/locales/en/errors/application.ts
packages/phrases/src/locales/es/errors/application.ts
packages/phrases/src/locales/fr/errors/application.ts
packages/phrases/src/locales/it/errors/application.ts
packages/phrases/src/locales/ja/errors/application.ts
packages/phrases/src/locales/ko/errors/application.ts
packages/phrases/src/locales/pl-pl/errors/application.ts
packages/phrases/src/locales/pt-br/errors/application.ts
packages/phrases/src/locales/pt-pt/errors/application.ts
packages/phrases/src/locales/ru/errors/application.ts
packages/phrases/src/locales/tr-tr/errors/application.ts
packages/phrases/src/locales/zh-cn/errors/application.ts
packages/phrases/src/locales/zh-hk/errors/application.ts
packages/phrases/src/locales/zh-tw/errors/application.ts

New route: `DELETE /applications/:applicationId/protected-app-metadata/custom-domains/:domain`
Unit tests and local test.

feat(core,phrases): delete custom domain

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx

Per product decision,  keep the description input field for the third-party app. 
test locally

chore(console): keep app description input field

---

packages/console/src/pages/ApplicationDetails/index.tsx

Fix third-party app return link. The third-party application details page should return to the third-party application tab. 
test locally

fix(console): fix third-party app return link

---

.github/workflows/release.yml

no need to run since we already did it in the main workflow
N/A

ci: do not run release on master pushes

---

packages/console/src/pages/Users/components/CreateForm/index.tsx

refactor(console): auto focus on the email field when creating user
Test locally.

refactor(console): auto focus on the email field when creating user

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx

Use the application name as the placeholder for the display name input field. 
test locally

fix(console): add displayName input placeholder

---

packages/core/src/routes/interaction/consent.ts
packages/experience/src/pages/Consent/index.module.scss
packages/experience/src/pages/Consent/index.tsx
packages/phrases-experience/src/locales/de/description.ts
packages/phrases-experience/src/locales/en/description.ts
packages/phrases-experience/src/locales/es/description.ts
packages/phrases-experience/src/locales/fr/description.ts
packages/phrases-experience/src/locales/it/description.ts
packages/phrases-experience/src/locales/ja/description.ts
packages/phrases-experience/src/locales/ko/description.ts
packages/phrases-experience/src/locales/pl-pl/description.ts
packages/phrases-experience/src/locales/pt-br/description.ts
packages/phrases-experience/src/locales/pt-pt/description.ts
packages/phrases-experience/src/locales/ru/description.ts
packages/phrases-experience/src/locales/tr-tr/description.ts
packages/phrases-experience/src/locales/zh-cn/description.ts
packages/phrases-experience/src/locales/zh-hk/description.ts
packages/phrases-experience/src/locales/zh-tw/description.ts
packages/schemas/src/types/consent.ts

Add redirect uri info at the consent page. Also, update the cancel button logic to return to the redirect Uri. 
test locally

feat(experience): add redirect uri info

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/console/src/pages/Applications/index.tsx
packages/console/src/types/applications.ts
packages/phrases/src/locales/de/translation/admin-console/applications.ts
packages/phrases/src/locales/en/translation/admin-console/applications.ts
packages/phrases/src/locales/es/translation/admin-console/applications.ts
packages/phrases/src/locales/fr/translation/admin-console/applications.ts
packages/phrases/src/locales/it/translation/admin-console/applications.ts
packages/phrases/src/locales/ja/translation/admin-console/applications.ts
packages/phrases/src/locales/ko/translation/admin-console/applications.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
packages/phrases/src/locales/ru/translation/admin-console/applications.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts

Update the third-party app details page tag to Third-party app
Before:
After:
Also, align the third-party phrases. 
test locally

fix(console): update the third-party app details page tag

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx

fix(console): add UnsavedChangesAlert

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/LogoUploader.module.scss
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/LogoUploader.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.module.scss

Fix the image uploader style.
test locally

fix(console): fix the image uploader style

---

packages/phrases/src/locales/de/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/user-details.ts
packages/phrases/src/locales/es/translation/admin-console/application-details.ts
packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
packages/phrases/src/locales/it/translation/admin-console/application-details.ts
packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts

console phrases updates, align the user data naming cross admin console and experience page.

chore(phrases): console phrases updates

---

packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/phrases/src/locales/de/translation/admin-console/applications.ts
packages/phrases/src/locales/en/translation/admin-console/applications.ts
packages/phrases/src/locales/es/translation/admin-console/applications.ts
packages/phrases/src/locales/fr/translation/admin-console/applications.ts
packages/phrases/src/locales/it/translation/admin-console/applications.ts
packages/phrases/src/locales/ja/translation/admin-console/applications.ts
packages/phrases/src/locales/ko/translation/admin-console/applications.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/applications.ts
packages/phrases/src/locales/pt-br/translation/admin-console/applications.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/applications.ts
packages/phrases/src/locales/ru/translation/admin-console/applications.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/applications.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/applications.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/applications.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/applications.ts

Adjust the application creation modal
- update the subtitle if the application type is third-party
- adjust the modal size to medium
- auto focus on the name input field if it has a default application type

feat(console,phrases): adjust the application creation modal

---

packages/phrases/src/locales/de/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/applications.ts
packages/phrases/src/locales/es/translation/admin-console/application-details.ts
packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
packages/phrases/src/locales/it/translation/admin-console/application-details.ts
packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts

chore(phrases): update application content

---

packages/core/src/libraries/protected-app.ts

Fix the endpoint value in protected app site configs, use `getTenantEndpoint` to get the correct value.
Local tested.

fix(core): get tenant endpoint

---

packages/core/src/__mocks__/index.ts
packages/core/src/constants/index.ts
packages/core/src/libraries/protected-app.test.ts
packages/core/src/libraries/protected-app.ts
packages/core/src/routes/applications/application-protected-app-metadata.test.ts
packages/core/src/routes/applications/application-protected-app-metadata.ts
packages/core/src/routes/applications/application.test.ts

Fix protected app callback uri, the path should be "sign-in-callback".

fix(core): fix protected app callback uri

---

packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx

Only request protected app domain if it is cloud and has dev features enabled.
Locally tested

fix(console): only request protected app domain if it is cloud and has dev features enabled

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx

The application form data should be reset by the parsed data rather than the form data, since the form data will be processed by the backend and new form data should be parsed from the responded data. Otherwise the empty input fields will not be removed, since they could exist in the form data, but will be removed by the backend.
Test locally.

fix(console): reset applicaiton form data with parsed data

---

packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/pages/AuditLogDetails/index.tsx
packages/integration-tests/src/api/api.ts
packages/integration-tests/src/api/application.ts
packages/integration-tests/src/tests/console/applications/index.test.ts

Fix the bug that the machine log can not enter its details page.
Tested locally and secured by console integration test.

fix(console): fix m2m app log not accessible bug

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx

Fix the incorrect external link in protected app details page
Worked locally

fix(console): external link should use to the correct URL in protected app details

---

packages/console/src/pages/Applications/components/CreateForm/index.tsx

Fix the app creation modal size.
- use medium size for application creation modal with a default application type selected
- keep a large size for the modal with application type selection content

style(console): fix the app creation modal size

---

packages/core/src/libraries/organization-invitation.ts
packages/core/src/queries/organization/index.ts
packages/core/src/routes/organization/invitations.ts
packages/core/src/utils/SchemaRouter.ts
packages/integration-tests/src/api/organization-invitation.ts
packages/integration-tests/src/helpers/organization.ts
packages/integration-tests/src/tests/api/organization/organization-invitation.test.ts
packages/schemas/alterations/next-1706449174-update-organization-invitation-column.ts
packages/schemas/tables/organization_invitation_role_relations.sql

- add basic api tests for organization invitations. 
- rename `invitation_id` to `organization_invitation_id` for naming consistency
itself

refactor: add invitation api tests

---

packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx

Add `.` before first-level domain for protected apps.
Locally tested. Easy peasy

fix(console): add dot before protected app first-level domain

---

packages/experience/src/pages/Consent/index.tsx
packages/experience/src/pages/Consent/util.test.ts
packages/experience/src/pages/Consent/util.ts

For security reasons, we only show the URL origin on the consent page if it is an HTTP URL. 
test locally

feat(experience): hide the path and parameter in redirectUri

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/use-scopes-table.tsx

should hide the personal user data row if it is empty
test locally

fix(console): should hide personal user data row if is empty

---

packages/core/src/libraries/quota.ts
packages/core/src/queries/application.ts

fix(core): application limit should include m2m apps
Test locally and will add test cases in the cloud.

fix(core): include m2m apps in application limit

---

packages/core/src/__mocks__/index.ts
packages/core/src/routes/applications/constants.ts

Remove the default page rule `^/`, empty rule will match all files by default.
The existing tests should pass.

refactor(core): remove default page rules

---

packages/core/src/routes/user-assets.ts

When uploading files, the provider may report errors, print them for better debugging.
Local tested.

chore(core): show errors of storage provider

---

packages/console/src/assets/docs/guides/web-next/README.mdx

Update guide, align with https://github.com/logto-io/docs/pull/557

refactor(console): update next guide

---

packages/console/src/assets/docs/guides/web-express/README.mdx

Update express guide, align with https://github.com/logto-io/docs/pull/556
Local tested.

refactor(console): update express guide

---

packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts
packages/shared/src/utils/sub-domain.test.ts
packages/shared/src/utils/sub-domain.ts

Only allow lowercase letters, numbers and hyphens in subdomains.
- Locally tested in console.
- Unit test passed.

fix(phrases,shared): only allow lowercase letters, numbers and hyphens in subdomains

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts

Display notification when user modify "Origin URL" in protected app details page, as this might take a while to go effective

refactor(console,phrases): show notification when modify origin url in protected app details

---

packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx

Should navigate to details page after creating protected apps.
Works on my machine

fix(console): should navigate to details page after creating protected app

---

packages/app-insights/package.json
packages/cli/package.json
packages/connectors/templates/package.json
packages/console/package.json
packages/core/package.json
packages/core/src/libraries/organization-invitation.ts
packages/core/src/queries/organization/index.ts
packages/core/src/routes/organization/invitations.openapi.json
packages/core/src/routes/organization/invitations.ts
packages/experience/package.json
packages/integration-tests/package.json
packages/integration-tests/src/api/organization-invitation.ts
packages/integration-tests/src/tests/api/organization/organization-invitation.creation.test.ts
packages/integration-tests/src/tests/api/organization/organization-invitation.status.test.ts
packages/phrases-experience/package.json
packages/phrases/package.json
packages/schemas/package.json
packages/schemas/src/types/organization.ts
packages/shared/package.json
packages/toolkit/connector-kit/package.json
packages/toolkit/core-kit/package.json
pnpm-lock.yaml

resolves LOG-7975. provide management api to accept or revoke an organization invitation. since this pull is already large, the following change will be separate pulls:
- request error i18n
- update on magic links
added a lot of api tests

feat(core): put invitation status

---

.changeset/clean-peaches-run.md
.changeset/two-moles-hope.md
packages/connectors/connector-mock-email-alternative/src/index.ts
packages/connectors/connector-mock-email/src/index.ts
packages/connectors/connector-mock-sms/src/index.ts
packages/core/src/libraries/organization-invitation.ts
packages/integration-tests/src/helpers/index.ts
packages/integration-tests/src/helpers/interactions.ts
packages/integration-tests/src/tests/api/interaction/forgot-password/happy-path.test.ts
packages/integration-tests/src/tests/api/interaction/forgot-password/sad-path.test.ts
packages/integration-tests/src/tests/api/interaction/register-with-identifier/happy-path.test.ts
packages/integration-tests/src/tests/api/interaction/register-with-identifier/sad-path.test.ts
packages/integration-tests/src/tests/api/interaction/register-with-identifier/single-sign-on.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/happy-path.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/sad-path.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-passcode-identifier/single-sign-on.test.ts
packages/integration-tests/src/tests/api/interaction/sign-in-with-password-identifier/happy-path.test.ts
packages/integration-tests/src/tests/api/verification-code.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/add-missing-profile-flow.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/passcode-identifier-flow.test.ts
packages/integration-tests/src/tests/experience/password-policy.test.ts
packages/integration-tests/src/ui-helpers/expect-experience.ts
packages/toolkit/connector-kit/src/index.ts

split mock connector record files by their types. update names and test utils accordingly.
ci

refactor!: update mock connector file paths

---

packages/console/src/hooks/use-applications-usage.ts
packages/console/src/pages/Applications/components/CreateForm/Footer/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx
packages/phrases/src/locales/de/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/es/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/fr/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/it/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/ja/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/ko/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/pt-br/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/ru/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/upsell/paywall.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/upsell/paywall.ts

Implement the quota guard footer on third-party app creation modal.
test locally

feat(console,phrases): implement quota guard footer

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/FeaturedPlanQuotaList/index.tsx

Update the tenant creation plan modal to include third-party apps quota limit.

feat(console): update the tenant creation plan modal

---

packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.module.scss
packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.tsx

- Add quota guard to protected app creation form modal.
- Fix a wrong gap setting in get-started page

feat(console): add quota guard to protected app creation form

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.module.scss
packages/toolkit/core-kit/scss/_console-themes.scss

- Add the misterious missing "--color-static-white" color token
- Improve "Try it" button styles.
Normal state:
Hover state:
Pressed state:

fix(console): improve "try it" button style in protected app details page

---

packages/console/src/pages/Applications/components/TypeDescription/index.module.scss
packages/console/src/pages/Applications/components/TypeDescription/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx

Remove pro tag for m2m app, since now the m2m app is availiable for free plan but the tag still exists in dev teannt.
In dev tenant:

refactor(console): remove pro tag for m2m app in dev tenant

---

packages/console/src/components/FeatureTag/index.module.scss
packages/console/src/pages/Applications/components/ProtectedAppCard/index.module.scss
packages/console/src/pages/Applications/components/ProtectedAppCard/index.tsx

Add beta tag to protected app card (3 occurances)

feat(console): add beta tags to protected app card

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.module.scss
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.module.scss
packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.tsx

Add loading masks to protected app forms and fields
Locally tested

feat(console): add loading masks for protected app

---

packages/phrases/src/locales/de/translation/admin-console/guide.ts
packages/phrases/src/locales/en/translation/admin-console/guide.ts
packages/phrases/src/locales/es/translation/admin-console/guide.ts
packages/phrases/src/locales/fr/translation/admin-console/guide.ts
packages/phrases/src/locales/it/translation/admin-console/guide.ts
packages/phrases/src/locales/ja/translation/admin-console/guide.ts
packages/phrases/src/locales/ko/translation/admin-console/guide.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/guide.ts
packages/phrases/src/locales/pt-br/translation/admin-console/guide.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/guide.ts
packages/phrases/src/locales/ru/translation/admin-console/guide.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/guide.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/guide.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/guide.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/guide.ts

Update category name for protected app in create application modal.

refactor(phrases): update category name in app creation modal for protected app

---

packages/core/package.json
packages/core/src/libraries/quota.ts
packages/core/src/queries/application.ts
packages/core/src/routes/applications/application.ts
pnpm-lock.yaml

Add third-party application creation quota guard
test locally

feat(core): add third-party application creation quota guard

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/phrases/src/locales/de/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/es/translation/admin-console/application-details.ts
packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
packages/phrases/src/locales/it/translation/admin-console/application-details.ts
packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts

1. Add "ENDPOINTS & CREDENTIALS" section to protected app details page
2. Update wording: `Implement JWT verification` -> `Protect your origin server`

feat(console): add endpoints and credentials section to protected app details

---

packages/phrases-experience/src/locales/de/user-scopes.ts
packages/phrases-experience/src/locales/en/user-scopes.ts
packages/phrases-experience/src/locales/es/user-scopes.ts
packages/phrases-experience/src/locales/fr/user-scopes.ts
packages/phrases-experience/src/locales/it/user-scopes.ts
packages/phrases-experience/src/locales/ja/user-scopes.ts
packages/phrases-experience/src/locales/ko/user-scopes.ts
packages/phrases-experience/src/locales/pl-pl/user-scopes.ts
packages/phrases-experience/src/locales/pt-br/user-scopes.ts
packages/phrases-experience/src/locales/pt-pt/user-scopes.ts
packages/phrases-experience/src/locales/ru/user-scopes.ts
packages/phrases-experience/src/locales/tr-tr/user-scopes.ts
packages/phrases-experience/src/locales/zh-cn/user-scopes.ts
packages/phrases-experience/src/locales/zh-hk/user-scopes.ts
packages/phrases-experience/src/locales/zh-tw/user-scopes.ts

profile scope should include username
test locally

fix(phrases): profile should include username

---

packages/console/src/assets/docs/guides/native-flutter/README.mdx

update the flutter guide
test locally

refactor(console): update the flutter guide

---

packages/console/src/consts/env.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
packages/console/src/pages/GetStarted/index.tsx

Remove `isDevFeaturesEnabled` flag for protected apps from console client.
N/A

chore(console): remove dev features flag from console client

---

packages/core/src/routes/applications/application.openapi.json

Update API docs for creating protected app.
Local preview.

chore(core): update api doc for create protected app

---

packages/console/src/assets/docs/guides/spa-react/README.mdx
packages/console/src/assets/docs/guides/spa-vue/README.mdx
packages/console/src/assets/docs/guides/web-express/README.mdx
packages/console/src/assets/docs/guides/web-next/README.mdx
packages/console/src/mdx-components/Steps/FurtherReadings.tsx
packages/console/src/mdx-components/Steps/index.tsx

Update React and Vue SDK integration guide in admin console.

refactor(console): update react and vue sdk integration guides

---

.changeset/silent-windows-behave.md
packages/console/src/components/ApplicationName/index.tsx
packages/console/src/hooks/use-swr-options.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/use-application-sign-in-experience-swr.ts
packages/console/src/pages/SignInExperience/PageContent/Content/LanguagesForm/ManageLanguage/LanguageEditor/LanguageDetails.tsx
packages/console/src/utils/request.ts
packages/phrases/src/locales/de/translation/admin-console/general.ts
packages/phrases/src/locales/en/translation/admin-console/general.ts
packages/phrases/src/locales/es/translation/admin-console/general.ts
packages/phrases/src/locales/fr/translation/admin-console/general.ts
packages/phrases/src/locales/it/translation/admin-console/general.ts
packages/phrases/src/locales/ja/translation/admin-console/general.ts
packages/phrases/src/locales/ko/translation/admin-console/general.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
packages/phrases/src/locales/ru/translation/admin-console/general.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts

Improve error handling when the user associated app is removed.
User management:
Audit logs:
Audit log details:
User logs:

fix(console,phrases): improve error handling when user associated app is removed

---

packages/console/src/consts/external-links.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/console/src/pages/Applications/components/ProtectedAppCard/index.tsx

Update documentation links in admin console
Locally tested

chore(console): update documentation links

---

packages/core/src/routes/applications/application.ts
packages/core/src/routes/applications/types.ts
packages/core/src/routes/init.ts
packages/core/src/routes/role.application.ts
packages/core/src/routes/system.ts

Remove isDevFeaturesEnabled flag for protected apps from core.
N/A

chore(core): remove dev features flag from core

---

packages/console/src/consts/external-links.ts
packages/console/src/pages/Organizations/Guide/OrganizationInfo/index.tsx
packages/phrases/src/locales/de/translation/admin-console/organizations.ts
packages/phrases/src/locales/en/translation/admin-console/organizations.ts
packages/phrases/src/locales/es/translation/admin-console/organizations.ts
packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
packages/phrases/src/locales/it/translation/admin-console/organizations.ts
packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts

Update organization guide next step action link. Change "Bulk add members and assign roles" to "Configure organization".
Locally tested

refactor(console,phrases): update organization guide next step action link

---

packages/console/src/consts/external-links.ts
packages/console/src/pages/Organizations/index.tsx
packages/console/src/scss/page-layout.module.scss
packages/phrases/src/locales/de/translation/admin-console/organizations.ts
packages/phrases/src/locales/en/translation/admin-console/organizations.ts
packages/phrases/src/locales/es/translation/admin-console/organizations.ts
packages/phrases/src/locales/fr/translation/admin-console/organizations.ts
packages/phrases/src/locales/it/translation/admin-console/organizations.ts
packages/phrases/src/locales/ja/translation/admin-console/organizations.ts
packages/phrases/src/locales/ko/translation/admin-console/organizations.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/organizations.ts
packages/phrases/src/locales/pt-br/translation/admin-console/organizations.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/organizations.ts
packages/phrases/src/locales/ru/translation/admin-console/organizations.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/organizations.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/organizations.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/organizations.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/organizations.ts

Update phrases in organizations page, in page subtitle and empty placeholder text.

refactor(console,phrases): update phrases in organizations

---

packages/console/src/pages/Mfa/PageWrapper/index.module.scss
packages/console/src/pages/Mfa/PageWrapper/index.tsx
packages/phrases/src/locales/de/translation/admin-console/general.ts
packages/phrases/src/locales/en/translation/admin-console/general.ts
packages/phrases/src/locales/es/translation/admin-console/general.ts
packages/phrases/src/locales/fr/translation/admin-console/general.ts
packages/phrases/src/locales/it/translation/admin-console/general.ts
packages/phrases/src/locales/ja/translation/admin-console/general.ts
packages/phrases/src/locales/ko/translation/admin-console/general.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/general.ts
packages/phrases/src/locales/pt-br/translation/admin-console/general.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/general.ts
packages/phrases/src/locales/ru/translation/admin-console/general.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/general.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/general.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/general.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/general.ts

refactor(console): remove mfa beta notice
Test locally.

refactor(console): remove mfa beta notice

---

.changeset/light-impalas-suffer.md
.changeset/serious-schools-whisper.md
.changeset/six-carrots-join.md
.changeset/six-pens-hope.md
.changeset/tame-keys-itch.md

add changeset files for IdP feature

chore: add changeset files for IdP feature

---

packages/console/src/assets/docs/guides/web-next-app-router/README.mdx

Update Next.js App Router console guide.

refactor(console): update next app router guide

---

.github/workflows/main.yml

update the option per comment
ci

ci: use new test option for seeding

---

packages/core/src/routes/applications/application.ts
packages/core/src/utils/cloudflare/utils.ts

log cloudflare error thus we can debug

refactor(core): log cloudflare error

---

packages/console/src/assets/docs/guides/m2m-general/index.ts
packages/console/src/assets/docs/guides/native-android/index.ts
packages/console/src/assets/docs/guides/spa-react/index.ts
packages/console/src/assets/docs/guides/spa-vanilla/index.ts
packages/console/src/assets/docs/guides/spa-vue/index.ts
packages/console/src/assets/docs/guides/types.ts
packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/index.ts
packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/index.ts
packages/console/src/assets/docs/guides/web-dotnet-core-mvc/index.ts
packages/console/src/assets/docs/guides/web-express/index.ts
packages/console/src/assets/docs/guides/web-go/index.ts
packages/console/src/assets/docs/guides/web-next-app-router/index.ts
packages/console/src/assets/docs/guides/web-next/index.ts
packages/console/src/assets/docs/guides/web-php/index.ts
packages/console/src/assets/docs/guides/web-python/index.ts
packages/console/src/mdx-components/Steps/FurtherReadings.tsx
packages/console/src/mdx-components/Steps/index.tsx

Add complete tutorial doc links for app guide
Test locally.

feat(console): add complete tutorial doc links for app guide

---

packages/console/src/ds-components/TextInput/index.tsx

- Update visibility logic for the suffix based on input confidentiality in the TextInput component
- Ensure consistent behavior for displaying suffix based on input confidentiality

refactor(console): improve input confidentiality handling in TextInput component

---

packages/core/src/routes/admin-user/social.openapi.json
packages/core/src/routes/admin-user/social.test.ts
packages/core/src/routes/admin-user/social.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/tests/api/admin-user.test.ts
packages/schemas/src/foundations/jsonb-types/users.ts

Add PUT /users/:userId/identities/:target API, so that Logto users can manipulate end-users social identities via management API.
Add unit test and integration test cases.

feat(core,test): add PUT /users/:userId/identities/:target API

---

packages/toolkit/core-kit/src/regex.test.ts
packages/toolkit/core-kit/src/regex.ts

Support "dash" in domain name, for example, "auth-gate.bar.com" is a valid custom domain.
Unit tests.

fix(toolkit): support dash in domain

---

packages/phrases/src/locales/de/translation/admin-console/protected-app.ts
packages/phrases/src/locales/en/translation/admin-console/protected-app.ts
packages/phrases/src/locales/es/translation/admin-console/protected-app.ts
packages/phrases/src/locales/fr/translation/admin-console/protected-app.ts
packages/phrases/src/locales/it/translation/admin-console/protected-app.ts
packages/phrases/src/locales/ja/translation/admin-console/protected-app.ts
packages/phrases/src/locales/ko/translation/admin-console/protected-app.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/protected-app.ts
packages/phrases/src/locales/pt-br/translation/admin-console/protected-app.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/protected-app.ts
packages/phrases/src/locales/ru/translation/admin-console/protected-app.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/protected-app.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/protected-app.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/protected-app.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/protected-app.ts

Change phrases, use "Fast create'.
Local preview

fix(phrases): use fast create for protected app

---

packages/schemas/src/seeds/cloud-api.ts

Add `cleanup:outdated-logs` cloud scope in the schemas package, it will be used in both `core` and `cloud` repo.
This scope will be used when triggering cleanup actions.
Test locally.

feat(schemas): add `cleanup:outdated-logs` cloud scope

---

packages/console/src/ds-components/Table/index.tsx
packages/console/src/ds-components/Table/types.ts

chore(console): add comments for table component
N/A

chore(console): add comments for table component

---

packages/console/src/assets/docs/guides/web-php/README.mdx
packages/console/src/assets/docs/guides/web-php/index.ts
packages/console/src/assets/docs/guides/web-python/README.mdx

align PHP/Python guide structure with docs
N/A

chore(console): align PHP/Python guide structure with docs

---

packages/console/src/assets/docs/guides/m2m-general/index.ts
packages/console/src/assets/docs/guides/native-android/index.ts
packages/console/src/assets/docs/guides/spa-react/index.ts
packages/console/src/assets/docs/guides/spa-vanilla/index.ts
packages/console/src/assets/docs/guides/spa-vue/index.ts
packages/console/src/assets/docs/guides/types.ts
packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/index.ts
packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/index.ts
packages/console/src/assets/docs/guides/web-dotnet-core-mvc/index.ts
packages/console/src/assets/docs/guides/web-express/index.ts
packages/console/src/assets/docs/guides/web-go/index.ts
packages/console/src/assets/docs/guides/web-next-app-router/index.ts
packages/console/src/assets/docs/guides/web-next/index.ts
packages/console/src/assets/docs/guides/web-php/index.ts
packages/console/src/assets/docs/guides/web-python/index.ts
packages/console/src/mdx-components/Steps/FurtherReadings.tsx
packages/console/src/mdx-components/Steps/index.tsx

tutorial -> guide for alignment
n/a

refactor(console): tutorial -> guide

---

packages/console/src/assets/docs/guides/web-next-server-actions/README.mdx

Upgrade the guide of Next.js Server Actions to align with https://github.com/logto-io/docs/pull/608
Local preview

feat(console): upgrade nextjs server actions guide

---

packages/console/src/assets/docs/guides/spa-vanilla/README.mdx

Update Vanilla JS integration guide in console
Locally tested

chore(console): update vanilla js integration guide

---

packages/connectors/connector-wecom/package.json

Fix connector-wecom's package.json file, align with the template.
The CI jobs should pass.

chore(connector): fix wecom package file

---

packages/schemas/src/seeds/cloud-api.ts

Per our new tech design, rename `cleanup:outdated-logs` scope to`prune:logs`
N/A

refactor(schemas): rename `cleanup:outdated-logs` scope to`prune:logs`

---

packages/core/src/event-listeners/record-active-users.ts
packages/schemas/alterations/next-1709190131-enhance-dau-data-accuracy.ts
packages/schemas/tables/daily_active_users.sql

Per offline discussion, we need to enhance the time accuracy of dau data, since in later iteration, this `daily_active_users` table will be used to generate dau statistics data for dashboard.
Test locally and original tests passed.

refactor(core, schemas): enhance the time accuracy of dau data

---

packages/cli/src/commands/database/seed/index.ts
packages/cli/src/commands/database/seed/tables.ts
packages/schemas/tables/_before_all.sql

This PR fixed #4535, neon is able to finish seeding now.
Tested on local machine.

fix(schemas): set default password for tenant (#4535)

---

packages/schemas/package.json
pnpm-lock.yaml

the new version is required for cloud devlopment
ci

chore(schemas): upgrade withtyped pacakge

---

.changeset/real-eels-jam.md
packages/core/src/routes/admin-user/basic.openapi.json
packages/core/src/routes/admin-user/basics.test.ts
packages/core/src/routes/admin-user/basics.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/helpers/index.ts
packages/integration-tests/src/tests/api/admin-user.test.ts
packages/phrases/src/locales/de/errors/user.ts
packages/phrases/src/locales/en/errors/user.ts
packages/phrases/src/locales/es/errors/user.ts
packages/phrases/src/locales/fr/errors/user.ts
packages/phrases/src/locales/it/errors/user.ts
packages/phrases/src/locales/ja/errors/user.ts
packages/phrases/src/locales/ko/errors/user.ts
packages/phrases/src/locales/pl-pl/errors/user.ts
packages/phrases/src/locales/pt-br/errors/user.ts
packages/phrases/src/locales/pt-pt/errors/user.ts
packages/phrases/src/locales/ru/errors/user.ts
packages/phrases/src/locales/tr-tr/errors/user.ts
packages/phrases/src/locales/zh-cn/errors/user.ts
packages/phrases/src/locales/zh-hk/errors/user.ts
packages/phrases/src/locales/zh-tw/errors/user.ts

For the create user api, add support for password digest.
Unit & integration tests.

feat(core): create user with password digest

---

packages/console/src/pages/JwtClaims/SettingsPanel/TestResult.tsx
packages/console/src/pages/JwtClaims/SettingsPanel/TestTab.tsx
packages/console/src/pages/JwtClaims/SettingsPanel/index.module.scss
packages/phrases/src/locales/de/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/es/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/fr/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/it/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/ja/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/ko/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/pt-br/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/ru/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/jwt-claims.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/jwt-claims.ts

Add test result component
test locally
<image src="https://github.com/logto-io/logto/assets/36393111/ba4c5bd9-3021-4694-892e-26288dd5da77" width="50%" />

feat(console,phrases): add test result component

---

packages/console/src/pages/JwtClaims/index.tsx

add unsaved changes alert and save changes footer
test locally

feat(console): add change alert and save changes footer

---

packages/console/src/pages/JwtClaims/Main.tsx
packages/console/src/pages/JwtClaims/use-jwt-customizer.ts
packages/console/src/pages/JwtClaims/utils.ts
packages/core/src/routes/logto-config.ts
packages/integration-tests/src/api/logto-config.ts
packages/schemas/src/types/logto-config/index.ts

Rename the jwtCustomizer related type and guards
N/A

refactor(console,core,schemas): rename the jwtCustomizer related type and guards

---

packages/schemas/src/types/jwt-customizer.ts

export custom JWT API request body type, will be used in Azure Function.
N/A

chore(schemas): export custom JWT API request body type

---

.changeset/seven-socks-perform.md
packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
packages/integration-tests/src/tests/api/resource.scope.test.ts
packages/schemas/alterations/next-1710408335-make-resource-scopes-description-nullable.ts
packages/schemas/src/types/consent.ts
packages/schemas/tables/scopes.sql

Alter the resource scopes description field to nullable. Align the resource scopes structure with organization scopes. 
related PR #5503 
test locally

refactor(schemas, console): alter the resource scopes description field to nullable

---

.github/workflows/alteration-compatibility-integration-test.yml
.github/workflows/integration-test.yml

use the new version for better workflow output (no verbose logs)
⬇️ see integration test output, no lengthy api logs

ci: bump workflow version

---

packages/schemas/src/seeds/cloud-api.ts

Remove deprecated `prune:logs` scope
N/A

chore(schemas): remove deprecated `prune:logs` scope

---

packages/console/src/pages/JwtClaims/SettingsSection/TestTab.tsx
packages/console/src/pages/JwtClaims/SettingsSection/index.module.scss
packages/console/src/pages/JwtClaims/index.module.scss
packages/console/src/pages/JwtClaims/utils/format.ts

Fix the jwt customizer test panel layout
1. should close the test result window on token type switch
2. Set multiple overflow hidden styles to restrict the test result height
3. remove the unused table styles. 
test locally

style(console): fix the jwt test panel layout

---

packages/core/src/routes/interaction/verifications/mfa-verification.ts

Remove unused function `markMfaSkipped` resolving #5482 
All tests should pass.

refactor(core): remove unused mark mfa skip function

---

packages/schemas/src/consts/subscriptions.ts

To better understand the code and its context, add comments for `ReservedPlanId`.
N/A

chore(schemas): add comments for `ReservedPlanId`

---

packages/console/package.json
packages/core/src/libraries/cloud-connection.ts
packages/core/src/libraries/logto-config.ts
packages/core/src/oidc/init.test.ts
packages/core/src/oidc/init.ts
packages/core/src/routes/logto-config.openapi.json
packages/core/src/routes/logto-config.test.ts
packages/core/src/routes/logto-config.ts
packages/core/src/tenants/Tenant.ts
packages/schemas/src/foundations/jsonb-types/users.ts
pnpm-lock.yaml

Add the support on the custom JWT feature.
N/A

feat(core): add the support on custom JWT feature

---

packages/core/src/routes/domain.ts

fix the post domains API error status code not allowed bug. Add 400 to the status code list. 
test locally

fix(core): fix the post domains api error status code

---

packages/console/src/containers/ConsoleContent/Sidebar/hook.tsx
packages/phrases/src/locales/de/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/en/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/es/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/fr/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/it/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/ja/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/ko/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/ru/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tab-sections.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tab-sections.ts

Reorg sidebar menu items
Before:
After:

refactor(console): reorg sidebar menu items

---

packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.module.scss
packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/utils.ts
packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/types.ts
packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts

Implement invite member dialog
Locally

feat(console): invite members dialog

---

packages/core/src/sso/AzureAdSsoConnector/index.ts
packages/core/src/sso/AzureOidcSsoConnector/index.ts
packages/core/src/sso/OidcConnector/index.ts
packages/core/src/sso/index.ts
packages/schemas/src/types/sso-connector.ts

Add new Azure OIDC SSO connector
- Overwrite the standard OIDC SSO connector's get userInfo endpoint as azure emails are all unverified. We need to store
unverified emails exclusively. 
test locally

feat(core,schemas): add new Azure OIDC SSO connector

---

packages/console/src/hooks/use-api.ts

Refactor useApi `hideToast` logic to accept custom `LogtoErrorCodes`. 
- extract the `toastError` method to a separate `useGlobalRequestErrorHandler` hook.
- update the `hideToast`  props to accept a bool or an array of `LogtoErrorCodes`. If bool value is provided the hideToast settings will be applied globally. If a an array of `LogtoErrorCodes` is provided, only request error with the specified `LogtoErrorCode` will be muted, such errors need to be handled manually.  All the request error will keep showing global toasts. 
test locally

refactor(console): refactor useApi

---

packages/console/src/scss/_code-editor.scss

fix the color code white CSS. Originally using `var(--color-base)` will become dark under the dark mode. 
test locally

style(console): fix the color code white css

---

packages/schemas/src/types/jwt-customizer.ts

Update `customJwtFetcherGuard` to specify custom JWT use case (this is used as the request body guard of custom jwt AZ function), this change will be used when we update the implementation on custom-jwt AZ functions to distinguish the use case and apply different way of calling the user customized `getCustomJwtClaims` function.
N/A

chore(schemas): update customJwtFetcherGuard to specify custom jwt use case

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/console/src/cloud/pages/Main/InvitationList/index.module.scss
packages/console/src/cloud/pages/Main/InvitationList/index.tsx
packages/console/src/cloud/pages/Main/index.tsx
packages/console/src/cloud/types/router.ts
packages/console/src/hooks/use-user-invitations.ts
packages/console/src/pages/AcceptInvitation/SwitchAccount/index.module.scss
packages/console/src/pages/AcceptInvitation/index.tsx
packages/core/package.json
pnpm-lock.yaml

Implement an interim console landing page for new users to join invited tenants, if they have pending invitations.

feat(console): implement interim landing page for new users to join invited tenants

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/console/src/cloud/pages/Main/InvitationList/index.module.scss
packages/console/src/cloud/pages/Main/InvitationList/index.tsx
packages/console/src/cloud/pages/Main/index.tsx
packages/console/src/cloud/types/router.ts
packages/console/src/components/Topbar/TenantSelector/TenantInvitationDropdownItem/index.module.scss
packages/console/src/components/Topbar/TenantSelector/TenantInvitationDropdownItem/index.tsx
packages/console/src/components/Topbar/TenantSelector/index.tsx
packages/console/src/hooks/use-user-invitations.ts
packages/console/src/pages/AcceptInvitation/SwitchAccount/index.module.scss
packages/console/src/pages/AcceptInvitation/index.tsx
packages/core/package.json
pnpm-lock.yaml

Add quick join options in topbar tenant selector dropdown

feat(console): add quick join options in tenant selector dropdown

---

packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts

Add integration tests for JWT (access token), use `jwtVerify` from `jose` to implement a real jwt verification with several claims.

test: add integration tests for jwt

---

packages/cli/src/commands/database/seed/tables.ts

add necessary comments for why tenant organization data are contained in the OSS seed command.
n/a

chore: add comments for cloud seed data

---

.changeset/great-peaches-work.md
packages/experience/src/pages/DirectSignIn/index.test.tsx
packages/experience/src/pages/DirectSignIn/index.tsx
packages/integration-tests/src/tests/experience/direct-sign-in.test.ts
packages/integration-tests/src/ui-helpers/expect-experience.ts
packages/schemas/src/consts/oidc.ts

add sso connector support for direct sign-in
local tested + unit tests added + integration tests added

feat: support direct sign-in for sso

---

packages/integration-tests/src/tests/api/admin-user.username-case.test.ts

Add integration tests for username case sensitivity.

test: add tests for username case sensitive

---

packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx

Only pending invitations can be resent.
Locally

fix(console): only pending invitations can be resent

---

packages/core/src/libraries/cloud-connection.test.ts
packages/core/src/libraries/logto-config.ts
packages/core/src/libraries/sign-in-experience/index.test.ts
packages/core/src/routes/logto-config/jwt-customizer.test.ts
packages/core/src/routes/logto-config/jwt-customizer.ts
packages/core/src/routes/logto-config/logto-config.openapi.json
packages/integration-tests/src/__mocks__/jwt-customizer.ts
packages/integration-tests/src/api/logto-config.ts
packages/integration-tests/src/tests/api/logto-config.test.ts
packages/schemas/src/types/logto-config/jwt-customizer.test.ts
packages/schemas/src/types/logto-config/jwt-customizer.ts

Add `PATCH /configs/jwt-customizer/:tokenType` API
Covered by unit tests and integration tests.

feat(core): add PATCH /configs/jwt-customizer API

---

packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
packages/schemas/alterations/next-1712041436-rename-organization-member-role-to-collaborator.ts
packages/schemas/src/types/tenant-organization.ts

Rename the tenant "Member" role to "Collaborator"
CI

refactor(schemas): rename tenant member role to collaborator

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
packages/core/package.json
packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
pnpm-lock.yaml

Rename tenant "Member" role to "Collaborator"

refactor(console,phrases): rename tenant member role to collaborator

---

packages/experience/src/pages/SocialSignInWebCallback/SingleSignOn.tsx

align sso callback ui with social's, resolves LOG-8553
local previewed

refactor(experience): fix sso callback page style

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
packages/core/package.json
packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts
pnpm-lock.yaml

Display inviter name and replace "Sent Date" on tenant invitations table.
Note: Pending `@logto/cloud` new release, so the CI is expected to fail at this point

refactor(console,phrases): display inviter name on tenant invitations table

---

packages/core/src/queries/organization/index.ts
packages/core/src/routes/organization/roles.openapi.json
packages/core/src/routes/organization/roles.ts
packages/integration-tests/src/api/factory.ts
packages/integration-tests/src/api/organization-role.ts
packages/integration-tests/src/helpers/resource.ts
packages/integration-tests/src/tests/api/organization/organization-role.test.ts
packages/schemas/alterations/next-1711955211-organization-resource-scope.ts
packages/schemas/tables/organization_role_resource_scope_relations.sql

Add organization "resource scope" relation and corresponding routes.

feat(core,schemas): add organization resource scope relations

---

packages/core/src/queries/organization/index.ts
packages/core/src/routes/organization/roles.openapi.json
packages/core/src/routes/organization/roles.ts
packages/integration-tests/src/api/factory.ts
packages/integration-tests/src/api/organization-role.ts
packages/integration-tests/src/tests/api/organization/organization-role.test.ts
packages/schemas/src/types/organization.ts

Implement edit and query for resource scopes in organization role routes.

feat(core,schemas): edit and query resource scopes for org role

---

packages/schemas/alterations/next-1712545011-fix-organization-resource-scope.ts

https://github.com/logto-io/logto/pull/5608 was merged but the alteration tiemstamp is not greater then existing scripts, that causes alteration error, try to fix it.
CI

chore(schemas): fix alteration timestamp

---

packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.module.scss
packages/console/src/pages/OrganizationTemplate/OrganizationRoles/index.tsx

feat(console): support searching for organization roles

feat(console): support searching for organization roles

---

packages/schemas/alterations/next-1712559358-fix-down-organization-resource-scope.ts

https://github.com/logto-io/logto/pull/5645 does not fix "down" issue, add a new alteration script to fix it.
Notice that the "up" script contains a "if" statement, so it is OK to run again.

chore(schemas): fix alteration down

---

packages/console/src/ds-components/ConfirmModal/index.module.scss
packages/console/src/ds-components/ConfirmModal/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.module.scss
packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.module.scss
packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx

Show confirm box when inviting a new member as admin.

refactor(console): show confirm box when inviting a member as admin

---

packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/index.module.scss
packages/console/src/pages/TenantSettings/TenantMembers/index.module.scss

Improve switch button visual styles in JWT claims page and tenant members page.
Will extract a new component in a future PR.

refactor(console): improve switch button styles

---

packages/console/package.json
packages/console/src/pages/AcceptInvitation/index.tsx
packages/demo-app/package.json
packages/integration-tests/package.json
pnpm-lock.yaml

- Bump JS SDKs
- Fix the issue that access token is not cleared on sign-in, which resulted in an issue that prevents user from switching accounts properly (LOG-8538).
- Automatically accept the invitation after switching to the invited account

fix(console): user should switch account and accept invitation properly in console

---

packages/console/src/cloud/pages/Main/InvitationList/index.tsx

Go to onboarding process when user clicks "Create a new tenant" button on this page:
Tested locally. It automatically creates a tenant and goes to the onboarding process:

fix(console): go to onboarding process on clicking create new tenant button

---

packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx

Update pricing plan items for JWT claims feature. Update it to "Coming soon".

chore(console): update pricing plan items for jwt claims

---

packages/console/src/containers/ProtectedRoutes/index.tsx

[Cloud feature] Force navigate users to sign-up page if they click the collaboration invitation link from email. Existing Cloud users with authenticated status will not be impacted.
Locally

refactor(console): redirect to sign-up page on clicking invitation links

---

packages/core/src/routes/organization/index.ts

mount invitation routes
will deploy soon

refactor: uncomment feature guard

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.tsx

Update "Custom domain" field name to "App domain" in protected app details page.

refactor(console): update protected app custom domain field to app domain

---

.changeset/four-goats-rush.md
packages/core/src/routes/resource.scope.test.ts
packages/core/src/routes/resource.scope.ts
packages/core/src/routes/resource.test.ts
packages/core/src/routes/resource.ts
packages/integration-tests/src/tests/api/resource.scope.test.ts
packages/integration-tests/src/tests/api/resource.test.ts
packages/phrases/src/locales/de/errors/resource.ts
packages/phrases/src/locales/en/errors/resource.ts
packages/phrases/src/locales/es/errors/resource.ts
packages/phrases/src/locales/fr/errors/resource.ts
packages/phrases/src/locales/it/errors/resource.ts
packages/phrases/src/locales/ja/errors/resource.ts
packages/phrases/src/locales/ko/errors/resource.ts
packages/phrases/src/locales/pl-pl/errors/resource.ts
packages/phrases/src/locales/pt-br/errors/resource.ts
packages/phrases/src/locales/pt-pt/errors/resource.ts
packages/phrases/src/locales/ru/errors/resource.ts
packages/phrases/src/locales/tr-tr/errors/resource.ts
packages/phrases/src/locales/zh-cn/errors/resource.ts
packages/phrases/src/locales/zh-hk/errors/resource.ts
packages/phrases/src/locales/zh-tw/errors/resource.ts

Not allow to modify management api resource and its scopes.
Unit & integration tests.

fix(core): not allow to modify management api resource

---

packages/console/src/pages/OrganizationTemplate/index.module.scss
packages/console/src/pages/OrganizationTemplate/index.tsx

feat(console): add paywall for organizaion template
In free tenant:
In dev tenant:
In pro tenant

feat(console): add paywall for organization template

---

packages/console/src/consts/external-links.ts

refactor(console): update reservation link

---

packages/core/src/routes/logto-config/jwt-customizer.test.ts
packages/core/src/routes/logto-config/jwt-customizer.ts
packages/core/src/test-utils/mock-libraries.ts
packages/core/src/test-utils/tenant.ts

For paid tenants using CF workers, we need to deploy the given script first to run the test script on the worker. 
Call the cloud worker deploy endpoint when custom-jwt test endpoint is called. 
test locally
unit test added

feat(core): add jwt-customizer test script deployment

---

packages/console/src/pages/OrganizationRoleDetails/Permissions/ResourceName/index.module.scss

Align resource icon with resource name in the organization role permissions table.

style(console): align resource icon with resource name

---

packages/console/.eslintrc.cjs
packages/console/package.json
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/pages/OrganizationDetails/index.tsx
packages/console/src/pages/OrganizationRoleDetails/index.tsx
packages/console/src/pages/Organizations/Guide/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/index.tsx

- add lint rule to fit the latest convention
- added linear issues accordingly
eslint reports errors

chore(console): restrict route component in pages

---

packages/console/src/hooks/use-console-routes/routes/organizations.tsx
packages/console/src/pages/OrganizationDetails/Members/index.tsx
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/console/src/pages/OrganizationDetails/index.tsx
packages/console/src/pages/OrganizationDetails/types.ts

update routes to fit the new convention
local tested organization settings and members page, works as expected

refactor(console): reorg organization details routes

---

packages/schemas/src/types/system.ts

add Cloudflare worker config for custom JWT.
N/A

chore: add Cloudflare worker config for custom JWT

---

packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
packages/console/src/pages/CustomizeJwtDetails/PageLoadingSkeleton/index.module.scss

Minor custom jwt page style iteration
- update the detail page loading skeleton column flex rate to be 9 : 7, same as the page content.
- shrink the sample token payload editor height for the `ClientCredentials` token. 
test locally

style(console): minor custom jwt page style iteration

---

packages/integration-tests/src/tests/api/organization/organization-user.test.ts

Improve test stability, since the modified return array is created asynchronously, the sorting order may vary. Thus, sorting the array and asserting strictly equal should fix the occational failure.
CI: API integration test

chore(test): improve organization user test stability

---

.changeset/cuddly-buses-obey.md
packages/core/src/middleware/koa-guard.test.ts
packages/core/src/middleware/koa-guard.ts

it caused more trouble than benefit. updated to a more gentle manner.
added unit test

refactor(core): dont throw for status errors in prod

---

.changeset/forty-grapes-relax.md
packages/core/src/oidc/grants/refresh-token.ts
packages/integration-tests/src/tests/api/oidc/refresh-token-grant.test.ts

Set oidc `AccessDenied` error code to 403.
@gao-sun would you mind take a look and confirm that this won't be a breaking change.

fix(core): set oidc access denied error code to 403

---

packages/console/src/consts/env.ts

Temp hot fix: force dev feature enabled false. 
Will revert the changes later.

fix(console): force dev feature enabled false

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
packages/core/package.json
packages/core/src/libraries/logto-config.script-merging.test.ts
packages/core/src/libraries/logto-config.ts
packages/core/src/oidc/extra-token-claims.ts
packages/core/src/routes/logto-config/jwt-customizer.test.ts
packages/core/src/routes/logto-config/jwt-customizer.ts
packages/core/src/utils/custom-jwt/custom-jwt.ts
packages/core/src/utils/custom-jwt/index.ts
packages/core/src/utils/custom-jwt/types.ts
pnpm-lock.yaml

update cloud dependency, cloud client calls
1. we updated the API interface in [previous cloud changes](https://github.com/logto-io/cloud/pull/617/files#diff-ee801056b7210a92bd716efeaeff4468c9eda32a3886983df032b85a48075f83), as a result, we need to update the API calls in Logto core
2. refactor the way to get custom JWT deploy script object
Tested locally and add complete unit test for the refactor custom JWT deploy script util method.

refactor(core): update cloud dependency, cloud client calls

---

packages/console/src/consts/env.ts

Revert the isDevFeatureEnabled hotfix. PR #5752 
test locally

fix(console): revert the isDevFeaturesEnabled changes in console

---

pnpm-lock.yaml

chore: upgrade json5 to 2.2.3

---

packages/experience/package.json
pnpm-lock.yaml

react-device-detect package update. Trying to fix the vulnerable js library pen-test error.

chore(experience): package update

---

.zap/rules.conf

fix: fix zap config file

---

.github/workflows/main.yml
.github/workflows/master-codecov-report.yml

Add the secret token to the code coverage action, since it becomes mandatory.

chore: add code coverage token

---

packages/console/src/consts/logs.ts

remove useless log title definitions
N/A

refactor(console): remove useless log title definitions

---

packages/core/src/routes/admin-user/basics.ts

Fix status code of `POST /users`, add 400.
N/A

fix(core): fix status code of create new user api

---

packages/console/src/components/Conversion/utils.ts

use aggregate domain for better analytics
n/a

refactor: update plausible domain

---

packages/cli/package.json
packages/console/package.json
packages/core/package.json
packages/schemas/package.json
packages/toolkit/connector-kit/package.json
pnpm-lock.yaml

to use some new features
ci should be good

chore(deps): upgrade withtyped packages

---

packages/core/src/main.ts
packages/core/src/tenants/index.ts

- use static import in init for better static analytics (i.e. lint)
- log `Custom domain` prefix for more clear display
ci should be good

refactor(core): optimize init

---

packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx

Make the invitee email address breakable in the list table
Before:
After:

refactor(console): make invitee email breakable in invitation list

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/index.tsx

fix(console): focus on org socpes tab on app scopes assignment modal opened
Select API permissions tab and reopen the modal

fix(console): focus on org socpes tab on app scopes modal reopened

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/PermissionsCard/ApplicationScopesAssignmentModal/use-resource-scopes-assignment.ts
packages/phrases/src/locales/de/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/es/translation/admin-console/application-details.ts
packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
packages/phrases/src/locales/it/translation/admin-console/application-details.ts
packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts

refactor(console, phrases): update resource scopes assignment form title

refactor(console, phrases): update resource scopes assignment form title

---

.changeset/thirty-cameras-explain.md

Add change set for the new feature of organization API resource.
N/A

chore: add changeset for org api resource

---

pnpm-lock.yaml

We bumped several packages, and the lock file is broken.
CI should pass.

chore: fix pnpm-lock

---

.scripts/publish.js

Build connectors before publish since some connectors rely on the generated types from oauth2 connector package.
CI passed.

ci(connector): build connectors before publish

---

packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx

Update "JWT claims" item in the plan comparison table, removing the "coming soon..." status.
N/A

chore(console): update jwt claims status in plan comparison table

---

.github/workflows/alteration-compatibility-integration-test.yml
.github/workflows/integration-test.yml
.github/workflows/main.yml

until we have a better plan
ci

ci: use default runner

---

packages/core/src/routes/interaction/consent/utils.ts
packages/integration-tests/src/tests/api/interaction/consent/happy-path.test.ts

fix consent scopes filter rule for non-3rd-party app, only third party app should be filtered.
Integration tests should pass.

fix(core): fix consent scopes filter rule for non-3rd-party app

---

packages/integration-tests/src/ui-helpers/expect-organizations.ts
packages/phrases/src/locales/de/translation/admin-console/organization-template.ts
packages/phrases/src/locales/en/translation/admin-console/organization-template.ts
packages/phrases/src/locales/es/translation/admin-console/organization-template.ts
packages/phrases/src/locales/fr/translation/admin-console/organization-template.ts
packages/phrases/src/locales/it/translation/admin-console/organization-template.ts
packages/phrases/src/locales/ja/translation/admin-console/organization-template.ts
packages/phrases/src/locales/ko/translation/admin-console/organization-template.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/organization-template.ts
packages/phrases/src/locales/pt-br/translation/admin-console/organization-template.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/organization-template.ts
packages/phrases/src/locales/ru/translation/admin-console/organization-template.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/organization-template.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/organization-template.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/organization-template.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/organization-template.ts

chore(phrases): update organization permission column name

chore(phrases): update organization permission column name

---

packages/console/src/assets/docs/guides/m2m-general/index.ts
packages/console/src/assets/docs/guides/native-android/index.ts
packages/console/src/assets/docs/guides/native-expo/index.ts
packages/console/src/assets/docs/guides/spa-angular/index.ts
packages/console/src/assets/docs/guides/spa-react/index.ts
packages/console/src/assets/docs/guides/spa-vanilla/index.ts
packages/console/src/assets/docs/guides/spa-vue/index.ts
packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/README.mdx
packages/console/src/assets/docs/guides/web-dotnet-core-blazor-server/index.ts
packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/README.mdx
packages/console/src/assets/docs/guides/web-dotnet-core-blazor-wasm/index.ts
packages/console/src/assets/docs/guides/web-dotnet-core-mvc/README.mdx
packages/console/src/assets/docs/guides/web-dotnet-core-mvc/index.ts
packages/console/src/assets/docs/guides/web-dotnet-core/README.mdx
packages/console/src/assets/docs/guides/web-express/index.ts
packages/console/src/assets/docs/guides/web-go/index.ts
packages/console/src/assets/docs/guides/web-next-app-router/index.ts
packages/console/src/assets/docs/guides/web-next/index.ts
packages/console/src/assets/docs/guides/web-nuxt/index.ts
packages/console/src/assets/docs/guides/web-php/README.mdx
packages/console/src/assets/docs/guides/web-php/index.ts
packages/console/src/assets/docs/guides/web-python/README.mdx
packages/console/src/assets/docs/guides/web-python/index.ts
packages/console/src/assets/docs/guides/web-sveltekit/index.ts

Update SDK documentation links in Console:
`https://docs.logto.io/sdk/...` => `https://docs.logto.io/quick-starts/...`.
N/A

chore(console): update sdk doc reference links

---

.github/workflows/main.yml

ci: remove corepack

---

packages/console/src/components/Conversion/utils.ts
packages/console/src/onboarding/pages/SignInExperience/index.tsx
packages/console/src/pages/Applications/components/CreateForm/index.tsx

- make `reportConversion` a sync function
- report first app creation conversion
once deployed

refactor(console): report first app creation conversion

---

packages/console/src/assets/docs/guides/web-sveltekit/README.mdx

Refine the svelte integration guide.

fix(console): update the svelte integration guide

---

packages/console/src/pages/Webhooks/index.tsx

update webhook list page styles
- replace the event separator using '/'
- adjust the column width ratio

style(console): update webhook list page styles

---

pnpm-lock.yaml

for a better web experience
n/a

chore(deps): upgrade caniuse-lite

---

packages/core/src/libraries/hook/utils.ts

Update test hook payload to be dynamic based on InteractionHook or DataHook event

feat(core): update test hook payload

---

packages/connectors/connector-wechat-web/README.md

Fix invalid image path referenced in `connector-wechat-web` README
N/A

fix(connector): fix invalid image path in connector readme

---

packages/connectors/connector-wecom/README.md

Improve wecom connector README
N/A

chore(connector): update wecom connector readme

---

packages/console/src/assets/docs/guides/web-nuxt/README.mdx

This pull request fixes a misspelling in the Nuxt SDK docs.
N/A

fix(console): fix Nuxt doc typo

---

packages/phrases/src/locales/de/translation/admin-console/tenants.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/es/translation/admin-console/tenants.ts
packages/phrases/src/locales/fr/translation/admin-console/tenants.ts
packages/phrases/src/locales/it/translation/admin-console/tenants.ts
packages/phrases/src/locales/ja/translation/admin-console/tenants.ts
packages/phrases/src/locales/ko/translation/admin-console/tenants.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenants.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenants.ts
packages/phrases/src/locales/ru/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenants.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenants.ts

chore(phrases): update tenant deletion modal content
N/A

chore(phrases): update tenant deletion modal content

---

packages/console/src/pages/CustomizeJwt/index.tsx

fix(console): add pro tag for custom JWT page

---

packages/core/src/routes/applications/application.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/integration-tests/src/tests/api/role.scope.test.ts
packages/integration-tests/src/tests/api/role.test.ts
packages/schemas/alterations/next-1716278409-remove-internal-role-database-policies.ts
packages/schemas/src/types/user.ts
packages/schemas/src/utils/role.ts
packages/schemas/tables/_after_all.sql

- remove internal role RLS policies since internal roles are not in use and the policies are making troubles now.
- add `deprecated` marks
ci - no logic change

refactor: remove internal role policies

---

packages/console/src/cloud/pages/Main/index.tsx
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
packages/console/src/hooks/use-subscribe.ts

send region data to the checkout session for paid plans
test in dev once logto-io/cloud#717 is merged

refactor(console): support multi-region for paid plans

---

packages/console/src/components/CreateTenantModal/index.tsx
packages/console/src/onboarding/pages/CreateTenant/index.tsx
packages/console/src/onboarding/scss/layout.module.scss
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts

- add icon and i18n keys for tenant creation
- add description for tenant region when creating a new tenant

refactor(console): improve onboarding ux

---

packages/phrases/src/locales/de/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/en/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/es/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/fr/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/it/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ja/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ko/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pt-br/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/ru/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/tenant-members.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/tenant-members.ts

Update invite member modal title. "Silverhand" => "Logto Cloud"
N/A

chore(phrases): update cloud collaboration invite modal title

---

packages/console/package.json
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
packages/console/src/components/PlanName/index.tsx
packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
pnpm-lock.yaml

refactor: optmize phrases

---

packages/console/src/cloud/hooks/use-cloud-api.ts
packages/console/src/components/CreateTenantModal/index.tsx
packages/console/src/onboarding/pages/CreateTenant/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.module.scss
packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/tenants.ts

- for better onboarding experience
- show toasts for tenant creation / invitation

feat(console): invite collaborators during onboarding

---

.changeset/gentle-flies-boil.md
packages/console/src/pages/ApiResourceDetails/components/ManagementApiNotice/index.tsx
packages/core/src/env-set/preconditions.ts

Update invalid documentation links.
Locally

fix(core,console): update invalid documentation links in console and core

---

packages/core/src/routes/organization/invitations.openapi.json

Remove "with pagination" information from `GET /organization/invitations` API docs, since we haven't support pagination on this API yet. Temporarily fixes #5926
N/A

docs(core): remove pagination from get organization invitation api docs

---

.changeset/shaggy-tables-taste.md
packages/cli/src/commands/translate/sync-keys/utils.ts

Fix translation CLI, by adding a missing import
CLI command run successfully after the fix, previously there was a missing import which causes the compilation error.

chore: update translate cli

---

packages/connectors/connector-logto-social-demo/src/constant.ts
packages/experience/src/containers/SocialSignInList/use-social.ts
packages/experience/src/pages/SocialSignInWebCallback/SocialSignIn.tsx
packages/phrases/src/locales/en/translation/admin-console/cloud.ts
packages/phrases/src/locales/en/translation/admin-console/connectors.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts

social sign in -> social sign-in
n/a

chore: fix typo

---

packages/console/src/components/SignInExperiencePreview/index.tsx
packages/console/src/contexts/AppDataProvider.tsx
packages/console/src/onboarding/pages/SignInExperience/Preview/index.tsx
packages/console/src/onboarding/pages/SignInExperience/index.tsx

- fix onboarding sign-in preview not showing
- fix onboarding social connectors not showing

refactor(console): fix onboarding issues

---

packages/phrases/src/locales/de/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/en/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/es/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/fr/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/it/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/ja/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/ko/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/ru/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/api-resource-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/api-resource-details.ts

upate management api notification phrase to:
Test locally.

refactor(phrases): update management api notification

---

packages/console/src/consts/env.ts
packages/console/src/consts/storage.ts
packages/console/src/containers/ConsoleContent/Sidebar/index.module.scss
packages/console/src/containers/ConsoleContent/index.module.scss
packages/console/src/containers/ConsoleContent/index.tsx

for better testing and previewing

feat(console): support localStorage override and show dev feature status

---

.changeset/thirty-zoos-compare.md
packages/connectors/connector-dingtalk-web/package.json
packages/connectors/connector-dingtalk-web/src/index.ts

1. Add DingTalk web connector changeset for `changeset` to do version control and add changelog.
2. Refactor code a little bit.
N/A

feat(connector): add DingTalk web connector changeset

---

packages/console/src/consts/external-links.ts

as we updated the links in docs
tested in the docs repo

chore: update links

---

packages/console/src/components/Conversion/utils.ts
packages/console/src/hooks/use-plausible-pageview.ts

the hostname should differ from the data domain per actual situation to correctly display on the dashboard
once deployed

refactor(console): fix plausible hostname

---

packages/schemas/src/consts/subscriptions.ts

add reserved plan ID for admin tenant.
N/A

chore(schemas): add reserved plan ID for admin tenant

---

packages/console/src/components/Topbar/index.module.scss
packages/console/src/components/Topbar/index.tsx

Clicking on the console logo should navigate users back to console root page. Currently it's not clickable.
Tested locally in both Cloud and OSS environments. Worked as expected.

refactor(console): click console logo should navigate to root page

---

packages/core/src/tenants/Tenant.ts

sometimes the exception will unexpectedly crash the service. try to catch it by wrapping a try-catch block.
once merged

refactor(core): try to catch uncaught exception

---

packages/console/src/pages/Profile/containers/DeleteAccountModal/components/FinalConfirmationModal/index.tsx
packages/phrases/src/locales/en/translation/admin-console/profile.ts

use a stronger word for the last confirmation
n/a

refactor(console): use permanently delete

---

packages/core/package.json
packages/core/src/caches/index.ts
pnpm-lock.yaml

- define max retry number (currently it'll retry forever)
- log redis error to console
- catch redis connect errors

refactor(core): optimize redis error handling

---

.changeset/cool-cows-relax.md
packages/console/src/components/ApplicationCreation/index.tsx
packages/console/src/components/RolesTransfer/components/RoleInformation/index.tsx
packages/console/src/components/RolesTransfer/index.tsx
packages/console/src/pages/RoleDetails/index.tsx

Ready for m2m guide feature release.
Test locally.

chore: remove dev flags and add changeset for m2m guide feature

---

packages/core/src/libraries/user.ts
packages/core/src/queries/organization/email-domains.ts
packages/core/src/routes/organization/index.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/helpers/interactions.ts
packages/integration-tests/src/tests/api/admin-user.organization-jit.test.ts
packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
packages/integration-tests/src/tests/api/interaction/register-with-identifier/happy-path.test.ts

implement just-in-time provision
SSO tests will be added once the test foundation utils have been set by @simeng-li

feat(core): implement organization jit provisioning

---

.changeset/stale-shrimps-compare.md
.vscode/settings.json
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/BackchannelLogout.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/utils.ts
packages/core/src/oidc/init.ts
packages/integration-tests/src/client/index.ts
packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/console/applications/helpers.ts
packages/integration-tests/src/tests/console/backchannel-logout.test.ts
packages/integration-tests/src/tests/experience/bootstrap.test.ts
packages/integration-tests/src/ui-helpers/expect-console.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/schemas/src/foundations/jsonb-types/oidc-module.ts
packages/schemas/src/utils/zod.ts

enable backchannel logout and provide API + console configuration

feat(core,console): enable backchannel logout

---

packages/console/src/mdx-components/Tabs/index.module.scss
packages/console/src/mdx-components/Tabs/index.tsx

style(console): update tab item style in readme docs

---

packages/console/src/pages/WebhookDetails/WebhookSettings/TestWebhook/index.tsx

`useApi({ hideErrorToast: true })` will disable global error handling, and now the `hideErrorToast` supports to config ignored error codes, so now we can pass specific error codes to this option. Based on that, we improve the webhook test request error handling.
Note: this PR only improves the robustness of the code and theoretically will not affect any users, so no changeset is needed.
Test locally and IT passed.

refactor(console): improve webhook test request error handling

---

packages/console/src/assets/docs/guides/api-spring-boot/README.mdx

update spring boot api protection guide

refactor(console): update spring boot api protection guide

---

packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/core/src/oidc/grants/refresh-token.test.ts
packages/core/src/oidc/grants/refresh-token.ts
packages/core/src/queries/organization/index.ts
packages/integration-tests/src/api/organization.ts
packages/integration-tests/src/client/index.ts
packages/integration-tests/src/helpers/organization.ts
packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
packages/integration-tests/src/tests/api/oidc/organization-token.test.ts
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
packages/schemas/alterations/next-1717818597-organization-mfa-requirement.ts
packages/schemas/tables/organizations.sql

configure mfa requirement per organization
unit and integration tests added

feat(core,console): organization mfa requirement

---

packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts

update styles to prepare for org default roles
local tested, save ok

refactor(console): update jit styles

---

packages/console/src/components/ApplicationName/index.tsx
packages/console/src/components/UserName/index.tsx

Similar to #6015, improving error handling logic that previously completed ommitted by applying "hideErrorToast" config.
Locally

refactor(console): improve swr error handling that previously omitted

---

packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/console/src/pages/OrganizationDetails/index.tsx
packages/console/src/pages/OrganizationDetails/types.ts
packages/core/src/libraries/user.ts
packages/core/src/queries/organization/email-domains.ts
packages/core/src/queries/organization/index.ts
packages/core/src/routes/organization/index.jit.email-domains.openapi.json
packages/core/src/routes/organization/index.jit.email-domains.ts
packages/core/src/routes/organization/index.jit.roles.openapi.json
packages/core/src/routes/organization/index.ts
packages/integration-tests/src/api/organization.ts
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
packages/schemas/alterations/next-1718340884-rename-org-email-domains-and-add-jit-roles-table.ts
packages/schemas/tables/organization_jit_email_domains.sql
packages/schemas/tables/organization_jit_roles.sql

> [!Note]
> 1. Consider this pull is already large, tests will be added through another pull.
> 2. The API compatibility test is expected to fail. It should be ok as the APIs are unpublished yet.
implement apis and ui for organization jit roles.

feat(core,console): organization jit roles

---

.changeset/smart-laws-compare.md
packages/core/src/routes/organization/index.jit.roles.openapi.json
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts

update changeset and content to match our latest update
n/a

chore: update changeset

---

.changeset/breezy-bags-help.md
.changeset/cold-masks-film.md
packages/connectors/connector-google/package.json
packages/connectors/connector-google/src/constant.ts
packages/connectors/connector-google/src/index.test.ts
packages/connectors/connector-google/src/index.ts
packages/connectors/connector-google/src/types.ts
packages/toolkit/connector-kit/src/types/foundation.ts
packages/toolkit/connector-kit/src/types/metadata.ts
packages/toolkit/connector-kit/src/types/social.ts
pnpm-lock.yaml

the Google One Tap series:
- #6030 ⬅️
- #6031 
- #6032
- #6034
- update Google connector to support decoding ID token from Google One Tap
- extract Google connector related common data to `connector-kit`

feat(connector): google one tap

---

.github/workflows/dev-feature-disabled-integration-test.yml
packages/integration-tests/src/utils.ts

Add new dev feature disabled integration tests. 
Trigger the tests only if there are any newly added `isDevFeaturesEnabled` code changes in the upcoming git diff. 
Dev feature-only test case statements, `devFeatureDescribe` and `devFeatureIt`, have been added in this PR. Use these statements for all dev feature-specific test cases. These test cases will be automatically skipped during integration tests when the dev feature is disabled.
> Hint: Don't forget to switch them back to the standard `jest.describe` and `jest.it` once the dev feature is launched.
organization jit related integration tests failed on the dev feature disabled compatibility integration test

feat: add dev feature disabled test

---

.changeset/nine-carrots-roll.md
packages/experience/src/apis/interaction.ts
packages/experience/src/components/GoogleOneTap/index.tsx
packages/experience/src/containers/SocialSignInList/index.tsx
packages/experience/src/containers/SocialSignInList/use-social.ts
packages/experience/src/hooks/use-connectors.ts
packages/experience/src/pages/Register/index.tsx
packages/experience/src/pages/SignIn/Main.tsx
packages/experience/src/pages/SignIn/index.tsx
packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts
packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
packages/experience/src/types/index.ts
packages/experience/src/utils/social-connectors.ts

the Google One Tap series:
- #6030
- #6031 
- #6032 ⬅️
- #6034
tested locally. experience shows Google One Tap and works as expected

feat(experience): google one tap

---

packages/connectors/connector-alipay-native/README.md
packages/connectors/connector-alipay-web/README.md
packages/connectors/connector-aliyun-dm/README.md
packages/connectors/connector-aliyun-sms/README.md
packages/connectors/connector-apple/README.md
packages/connectors/connector-aws-ses/README.md
packages/connectors/connector-dingtalk-web/README.md
packages/connectors/connector-github/README.md
packages/connectors/connector-mailgun/README.md
packages/connectors/connector-sendgrid-email/README.md
packages/connectors/connector-smsaero/README.md
packages/connectors/connector-smtp/README.md
packages/connectors/connector-tencent-sms/README.md
packages/connectors/connector-twilio-sms/README.md
packages/connectors/connector-wechat-native/README.md
packages/connectors/connector-wechat-web/README.md
packages/console/src/assets/docs/guides/web-outline/README.mdx

Update out-dated documentation links in connector READMEs.
NA

chore(connector): update outdated links in connector readme

---

packages/console/src/pages/SignInExperience/PageContent/Content/TermsForm.tsx
packages/phrases/src/locales/de/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/es/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/fr/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/it/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/ja/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/ko/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/pt-br/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/ru/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/sign-in-exp/content.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/sign-in-exp/content.ts

**2/3 steps for agree to terms policy feature implementation**
Support agree to terms policy configuration in the console.
Test locally.

feat(console,phrases): support agree to terms policy configuration

---

packages/core/src/libraries/user.ts
packages/core/src/queries/organization/email-domains.ts
packages/core/src/routes/admin-user/basics.test.ts
packages/core/src/routes/admin-user/basics.ts
packages/core/src/routes/admin-user/mfa-verifications.test.ts
packages/core/src/routes/admin-user/search.test.ts
packages/core/src/routes/admin-user/social.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/core/src/routes/interaction/utils/single-sign-on.test.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/integration-tests/src/tests/api/admin-user.organization-jit.test.ts
packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts

resolves LOG-9157, implement organization default role provision
integration tests updated

feat(core): jit organization roles

---

packages/schemas/src/consts/subscriptions.ts

rename legacy pro to grandfathered pro, salute!
N/A

chore: rename legacy pro to grandfathered pro

---

packages/core/src/queries/organization/index.ts
packages/core/src/routes/organization/index.jit.roles.openapi.json
packages/core/src/routes/organization/index.jit.sso-connectors.openapi.json
packages/core/src/routes/organization/index.ts
packages/integration-tests/src/api/organization-jit.ts
packages/integration-tests/src/tests/api/organization/organization-jit.test.ts
packages/schemas/alterations/next-1718786576-organization-jit-sso-connectors.ts
packages/schemas/tables/organization_jit_sso_connectors.sql

basic apis for organization jit sso connectors.

feat(core): organization jit sso apis

---

packages/core/src/libraries/user.test.ts
packages/core/src/libraries/user.ts
packages/core/src/libraries/user.utils.ts
packages/core/src/queries/organization/email-domains.ts
packages/core/src/queries/organization/index.ts
packages/core/src/queries/organization/sso-connectors.ts
packages/core/src/routes-me/user.ts
packages/core/src/routes/admin-user/basics.test.ts
packages/core/src/routes/admin-user/basics.ts
packages/core/src/routes/admin-user/mfa-verifications.test.ts
packages/core/src/routes/admin-user/search.test.ts
packages/core/src/routes/admin-user/social.test.ts
packages/core/src/routes/interaction/actions/helpers.ts
packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/integration-tests/src/helpers/interactions.ts
packages/integration-tests/src/tests/api/admin-user.organization-jit.test.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts

- implement provisioning by sso connectors for organization jit
- update triggers for jit
integration tests added / updated

feat(core): organization jit sso

---

packages/console/src/components/MultiOptionInput/index.tsx
packages/console/src/ds-components/ActionMenu/index.tsx
packages/console/src/pages/EnterpriseSso/SsoConnectorLogo/index.module.scss
packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/console/src/pages/OrganizationDetails/Settings/utils.ts
packages/console/src/pages/OrganizationDetails/index.tsx
packages/console/src/pages/OrganizationDetails/types.ts
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts

console update for jit:
- update jit sso connector
- update styles, content, components
> [!Note]
> The real content may differ from the screenshot.

feat(console): update jit config

---

packages/core/src/libraries/organization-invitation.ts
packages/core/src/libraries/user.ts
packages/core/src/oidc/grants/refresh-token.test.ts
packages/core/src/oidc/grants/refresh-token.ts
packages/core/src/queries/organization/application-role-relations.ts
packages/core/src/queries/organization/index.ts
packages/core/src/queries/organization/user-role-relations.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/core/src/routes/organization/index.application-role-relations.ts
packages/core/src/routes/organization/index.applications.openapi.json
packages/core/src/routes/organization/index.jit.email-domains.ts
packages/core/src/routes/organization/index.ts
packages/core/src/routes/organization/index.user-role-relations.ts
packages/core/src/routes/organization/index.users.openapi.json
packages/integration-tests/src/tests/api/organization/organization-application.test.ts

make the names to be more intuitive
- `rolesUsers` -> `usersRoles`
- `rolesApps` -> `appsRoles`
n/a

refactor(core): update naming and fix typos

---

packages/core/src/routes/organization/application/index.openapi.json
packages/core/src/routes/security/index.openapi.json
packages/core/src/routes/swagger/index.ts
packages/core/src/routes/swagger/utils/general.ts

filter out the whole supplement document when `Dev feature` tag shows up in the document `tags` field.
updated document accordingly, ci should ok

refactor: filter whole supplement document if needed

---

packages/core/src/queries/application.ts
packages/core/src/queries/organization/application-relations.ts
packages/core/src/queries/organization/index.ts
packages/core/src/queries/organization/user-relations.ts
packages/core/src/queries/organization/utils.ts
packages/core/src/queries/user.ts
packages/core/src/routes/organization/application/index.ts
packages/core/src/routes/organization/user/index.openapi.json
packages/core/src/routes/organization/user/role-relations.ts
packages/integration-tests/src/api/factory.ts
packages/integration-tests/src/tests/api/organization/organization-application.test.ts
packages/integration-tests/src/tests/api/organization/organization-user.test.ts
packages/schemas/src/types/organization.ts

return `oragnizationRoles` in `GET /api/organizations/:id/applications` response

refactor(core): return roles in organization app get api

---

packages/core/src/queries/application.ts
packages/core/src/queries/organization/application-relations.ts
packages/core/src/routes/admin-user/search.ts
packages/core/src/routes/applications/application-organization.openapi.json
packages/core/src/routes/applications/application-organization.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/init.ts
packages/integration-tests/src/api/application.ts
packages/integration-tests/src/tests/api/application/application.organization.test.ts
packages/integration-tests/src/tests/api/application/application.test.ts

- implement `GET /api/applications/{id}/organizations`
- support `excludeOrganizationId` for `GET /api/applications`
- refactor application queries

feat(core): add organization - application apis

---

packages/console/package.json
packages/console/parcel-transformer-mdx2.js
packages/console/src/assets/docs/fragments/_sign_in_explanation.md
packages/console/src/assets/docs/guides/web-nuxt/README.mdx
packages/console/src/ds-components/CodeEditor/index.module.scss
packages/console/src/ds-components/CodeEditor/index.tsx
packages/console/src/mdx-components/Code/index.tsx
packages/console/src/mdx-components/Steps/index.tsx
pnpm-lock.yaml

resolves LOG-9381
- support `title` for code snippets like Docusaurus
- update Nuxt guide according to the new template

refactor: update nuxt guide

---

packages/core/src/oidc/grants/client-credentials.ts

refactor(core): update grant comments

---

packages/console/src/assets/docs/guides/web-express/README.mdx

Added a missing backtick that breaks layout
There is one MD block that is missing a backtick. This breaks the layout in the application.
I did not test this.

chore: update README.mdx

---

packages/console/src/components/OrganizationList/index.tsx
packages/console/src/components/OrganizationRolePermissionsAssignmentModal/index.tsx
packages/console/src/consts/external-links.ts
packages/console/src/ds-components/CodeEditor/index.module.scss
packages/console/src/hooks/use-console-routes/index.tsx
packages/console/src/hooks/use-console-routes/routes/mfa.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/console/src/pages/OrganizationDetails/Settings/JitSettings.tsx
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/integration-tests/src/ui-helpers/expect-organizations.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts

- show CTA when no organization found in m2m app details page
- show an inline notification in organization jit section when no enterprise sso enabled
- update "Discard" to "Skip" in the organization role permission assignment modal
- add "Learn more" links in the JIT section
- add MFA tab link when organization MFA requirement is on and no MFA method enabled
related issues: LOG-9495, LOG-9192, LOG-9494, PRD-734, PRD-737
locally previewed

refactor(console): polish ui

---

packages/integration-tests/src/utils.ts

Improve the random method used in integration test util, since it previously raised security concerns.

refactor(test): use secure random method in integration test util

---

packages/console/src/pages/OrganizationDetails/Settings/index.tsx

- changeset ready (`.changeset/smart-laws-compare.md`)
- api ready
- console check removed
- no test prefixed with `devFeatureTest`
n/a

chore: launch jit

---

packages/core/src/event-listeners/grant.ts
packages/core/src/oidc/grants/index.ts
packages/core/src/oidc/grants/token-exchange.test.ts
packages/core/src/oidc/grants/token-exchange.ts
packages/core/src/oidc/utils.test.ts
packages/core/src/oidc/utils.ts
packages/core/src/queries/subject-token.ts
packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts
packages/schemas/src/types/log/token.ts
packages/schemas/src/types/oidc-config.ts

Implement the basic token exchange grant: exchange an access token with a subject token, along with optional resource and scopes parameters.
To reduce PR size, there are some todos in the code, they will be implemented in separated PRs.
Integration and unit tests.

feat(core,schemas): token exchange grant

---

packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts

Add missing `agreeToTermsPolicy` deps
Test locally.

fix(experience): add missing `agreeToTermsPolicy` deps

---

packages/console/src/mdx-components/Mermaid/index.tsx
packages/core/src/middleware/koa-security-headers.ts

- use dynamic CDN import to use Mermaid as Parcel has issues on handling the static import in production
- adjust security headers accordingly

refactor: fix mermaid in production

---

packages/console/src/assets/docs/guides/spa-vue/README.mdx

Update Vue integration guide in Console
Locally tested

refactor(console): update vue integration guide

---

packages/console/src/assets/docs/guides/spa-angular/README.mdx

Refactor angular integration guide in Console
Locally tested

refactor(console): update angular integration guide

---

packages/core/src/oidc/grants/index.ts
packages/core/src/oidc/grants/token-exchange.test.ts
packages/core/src/oidc/grants/token-exchange.ts
packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts

For security concern, third-party applications are not allowed for token exchange.

feat(core): third-party applications are not allowed for token exchange

---

packages/console/package.json
packages/demo-app/package.json
packages/integration-tests/package.json
packages/integration-tests/src/tests/api/oidc/organization-token.test.ts
pnpm-lock.yaml

bump sdks for better error handling (https://github.com/logto-io/js/pull/756)
locally works fine. will also test in dev.

refactor: upgrade logto sdks

---

packages/experience/src/App.tsx
packages/experience/src/Providers/UserInteractionContextProvider/UserInteractionContext.tsx
packages/experience/src/Providers/UserInteractionContextProvider/index.tsx
packages/experience/src/hooks/use-check-single-sign-on.ts
packages/experience/src/hooks/use-single-sign-on-watch.ts
packages/experience/src/pages/Register/IdentifierRegisterForm/index.test.tsx
packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
packages/experience/src/pages/SignIn/PasswordSignInForm/index.test.tsx
packages/experience/src/pages/SingleSignOnConnectors/index.tsx
packages/experience/src/pages/SingleSignOnEmail/index.tsx

This pull request refactors the `SingleSignOnContext` to `UserInteractionContext` to better reflect its broader purpose in managing user interaction data during the sign-in process. The changes aim to improve code clarity and provide more flexibility for future enhancements.
Key changes:
- Renamed `SingleSignOnContextProvider` to `UserInteractionContextProvider`
- Updated related imports and usages across multiple files
- Renamed email state to ssoEmail for more specific context
- Updated comments to clarify the purpose and usage of the context
- Adjusted test files to use the new context provider
Test locally and all IT passed.

refactor(experience): rename `SingleSignOnContext` to `UserInteractionContext`

---

packages/console/src/assets/docs/guides/spa-react/README.mdx
packages/console/src/mdx-components/Mermaid/index.tsx

- add missing import for react guide
- mock mermaid for testing environments
viewed locally

fix(console): fix page issues

---

packages/console/src/mdx-components/Mermaid/index.tsx

checking `CI` will also affect the production build. update to checking integration test env.
ci (double check in dev later)

refactor(console): check mermaid by integration test env

---

packages/console/package.json
packages/experience/package.json
packages/experience/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.test.tsx
packages/experience/src/hooks/use-send-verification-code.ts
packages/experience/src/jest.setup.ts
packages/experience/src/pages/DirectSignIn/index.test.tsx
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
packages/experience/src/pages/SocialLanding/index.test.tsx
packages/integration-tests/jest.setup.js
packages/integration-tests/package.json
pnpm-lock.yaml

- no need for the global path since Node now supports the global `TextEncoder` / `TextDecoder`
- improve test cases to make them cleaner
ci

refactor: remove unused patches

---

packages/console/scripts/generate-jwt-customizer-type-definition.ts
packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/GuideCard/index.tsx
packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
packages/console/src/pages/CustomizeJwtDetails/utils/type-definitions.ts
packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
packages/schemas/src/types/logto-config/jwt-customizer.ts

Add new context "grant context" to the console UI and code editor.
This context is only available for "token exchange" flow (impersonation).
Local preview:

feat(console,schemas): add grant context to custom jwt

---

packages/experience/src/components/InputFields/InputField/NotchedBorder/index.module.scss

style(experience): update floating label position

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/routes/experience/classes/verifications/totp-verification.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/verification-routes/totp-verification.ts
packages/core/src/routes/interaction/additional.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/totp-verification.ts
packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts
packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts
packages/phrases/src/locales/en/errors/session.ts
packages/schemas/src/types/interactions.ts

Implement the TOTP verification routes:
- Implement the `TotpVerification` record class
- Implement the `POST /verification/totp/secret/` route that generates a new TOTP secret for the user.
- Implement the `POST /verification/totp/verify/ route that verifies the TOTP secret. 

feat(core): implement TOTP verification routes

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/verifications/backup-code-verification.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/verifications/backup-code-verification.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts
packages/schemas/src/types/interactions.ts

This PR implement the BackupCode verification type, includes:
1. BackupCodeVerification class
2. /experience/verification/backup-code/verify endpoint

feat(core,schemas): implement backup codes verification

---

packages/core/src/oidc/grants/client-credentials.ts
packages/core/src/oidc/grants/refresh-token.test.ts
packages/core/src/oidc/grants/refresh-token.ts
packages/core/src/oidc/grants/token-exchange/index.ts
packages/core/src/oidc/grants/utils.ts
packages/integration-tests/src/tests/api/oidc/refresh-token-grant.test.ts

Refactor 3 grants: extract organization token code to a util function.

refactor(core): refactor organizations in grants

---

packages/core/src/oidc/grants/client-credentials.ts
packages/core/src/oidc/grants/refresh-token.test.ts
packages/core/src/oidc/grants/refresh-token.ts
packages/core/src/oidc/grants/token-exchange/index.ts
packages/core/src/oidc/grants/utils.ts
packages/integration-tests/src/tests/api/oidc/refresh-token-grant.test.ts
packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts

Add more test cases for token exchange.

test: add resource test cases for token exchange

---

packages/console/src/components/ConnectorForm/BasicForm/index.tsx
packages/console/src/components/ImageInputs/LogoAndFavicon.tsx
packages/console/src/components/ImageInputs/index.module.scss
packages/console/src/ds-components/Tip/TipBubble/utils.ts
packages/console/src/ds-components/Uploader/FileUploader/index.module.scss
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.module.scss
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/console/src/pages/OrganizationDetails/Settings/JitSettings.tsx
packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts
packages/schemas/src/seeds/sign-in-experience.ts

a batch of fixes for bug bash, resolve LOG-9610, LOG-9611, LOG-9604, LOG-9605, LOG-9607, LOG-9612, LOG-9606, LOG-9608, LOG-9609
locally tested all issues

refactor(console): improve branding experience

---

packages/core/src/routes/init.ts
packages/core/src/routes/subject-token.openapi.json
packages/core/src/routes/subject-token.ts
packages/core/src/routes/swagger/index.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/integration-tests/src/api/subject-token.ts

Per discusson, remove the "security" prefix of subject tokens API.

refactor(core): remove subject token api prefix

---

packages/experience/src/components/InputFields/InputField/index.tsx

This pr includes the following changes and fixes:
1. Fixed an issue with the clear icon:
- When clicked, the value becomes an empty string, but it didn't trigger the `hasValue` state change.
- Now listening to `value` changes to update the `active` state.
2. Improved handling of autofill:
- Added an `onAnimationStart` event listener to detect autofill.
- This ensures the input field has the correct active style when autofilled.
3. Refactored the component:
- Moved the `isActive` logic into a `useMemo` hook for better performance.
These changes improve the user experience by ensuring the input field's visual state accurately reflects its content, whether entered manually, cleared, or autofilled.
Test locally and everything works well.
~~- [ ] …

fix(experience): correct active state for input field

---

packages/experience/src/Providers/LoadingLayerProvider/index.tsx
packages/experience/src/components/LoadingLayer/index.module.scss
packages/experience/src/components/LoadingLayer/index.tsx
packages/experience/src/components/LoadingMask/index.module.scss
packages/experience/src/components/LoadingMask/index.tsx
packages/experience/src/containers/SetPassword/Lite.tsx
packages/experience/src/containers/SetPassword/SetPassword.tsx
packages/experience/src/containers/SetPassword/index.tsx
packages/experience/src/containers/TotpCodeVerification/index.module.scss
packages/experience/src/containers/TotpCodeVerification/index.tsx
packages/experience/src/containers/TotpCodeVerification/use-totp-code-verification.ts
packages/experience/src/containers/VerificationCode/index.module.scss
packages/experience/src/containers/VerificationCode/index.tsx
packages/experience/src/pages/Consent/index.tsx
packages/experience/src/pages/Continue/IdentifierProfileForm/index.tsx
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/experience/src/pages/MfaBinding/BackupCodeBinding/index.tsx
packages/experience/src/pages/MfaBinding/WebAuthnBinding/index.tsx
packages/experience/src/pages/MfaVerification/BackupCodeVerification/index.tsx
packages/experience/src/pages/MfaVerification/WebAuthnVerification/index.tsx
packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx
packages/experience/src/pages/SingleSignOnEmail/index.tsx

This refactoring aims to provide a more responsive and user-friendly experience by avoiding global loading indicators as much as possible:
- Refactor `LoadingLayer`
- Introduce `LoadingMask` component to prevent user input during loading states.
- Introduce `LoadingMask` to hide the global loading icon when loading
- Implement button loading states in various forms and actions
- Add continue buttons to verification code and MFA flows
- Improve error handling and state management in forms
- Enhance user feedback during form submissions and asynchronous operations
TOTP
Passkey
Backup code
TOTP
Passkey
Backup code

refactor(console): use button loading in experience flow if possible

---

packages/core/src/routes/experience/classes/experience-interaction.test.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/provision-library.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/organization-jti.test.ts
packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts

Add the new user provision process to the registration flow:
- new admin user provisioning
- admin tenant user provisioning
- default roles provisioning
- organization jit provisioning

feat(core): add the new user provision

---

packages/experience/src/components/InputFields/InputField/NotchedBorder/index.module.scss
packages/experience/src/components/InputFields/InputField/index.module.scss

style(experience): improve input filed style

---

packages/console/src/onboarding/pages/SignInExperience/index.tsx

Fix the broken image upload during the Cloud onboarding process. (fixes #6233) 
Locally tested and the image upload is working properly now

fix(console): fix image upload in onboarding process

---

packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx

Fix grant data card height in "Custom JWT".

fix(console): fix grant data card height

---

packages/experience/src/components/InputFields/InputField/NotchedBorder/index.module.scss

Per offline discussion, we need to add animation effect to the input filed for a better looking.
Test  locally.

style(experience): add transition for notched border

---

packages/core/package.json
packages/core/src/libraries/quota.ts
packages/core/src/routes/sign-in-experience/custom-ui-assets/index.ts
pnpm-lock.yaml

Add API qutoa guard for "bring your UI" feature
Locally

feat(core): add api quota guard for bring your ui feature

---

packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts

Add impersonation to the "upgrade" plan table.

feat(console): add impersonation price item

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/validators/mfa-validator.ts
packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/verifications/totp-verification.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
packages/core/src/routes/interaction/verifications/mfa-verification.ts
packages/integration-tests/src/helpers/experience/totp-verification.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/mfa-verification.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts

Add the MFA verifications guard.
- Implement a new `MfaValidator` helper class to provide MFA validation logic.
- Add the MFA verification status guard at the submit handler method. 

feat(core): add mfa verification guard

---

.changeset/seven-comics-tan.md

chore: add changeset for impersonation

---

packages/elements/package.json
packages/elements/xliff/de.xlf
packages/elements/xliff/es.xlf
packages/elements/xliff/fr.xlf
packages/elements/xliff/it.xlf
packages/elements/xliff/ja.xlf
packages/elements/xliff/ko.xlf
packages/elements/xliff/pl-PL.xlf
packages/elements/xliff/pt-BR.xlf
packages/elements/xliff/pt-PT.xlf
packages/elements/xliff/ru.xlf
packages/elements/xliff/tr-TR.xlf
packages/elements/xliff/zh-CN.xlf
packages/elements/xliff/zh-HK.xlf
packages/elements/xliff/zh-TW.xlf

move `check` script to `build` to avoid [error](https://github.com/logto-io/logto/actions/runs/10006005728/job/27657816146) when running `changeset version`
locally run `changeset version` ok

chore(elements): move check to build

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/console/src/consts/quota-item-phrases.ts
packages/console/src/consts/tenants.ts
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
pnpm-lock.yaml

Add "bring your UI" and the missing part (Related PR: #6269) of "Impersonation" features to pricing table.
Locally

feat(console,phrases): add bring your ui quota item to pricing table

---

packages/console/src/ds-components/Uploader/FileUploader/index.tsx
packages/phrases/src/locales/de/translation/admin-console/components.ts
packages/phrases/src/locales/en/translation/admin-console/components.ts
packages/phrases/src/locales/es/translation/admin-console/components.ts
packages/phrases/src/locales/fr/translation/admin-console/components.ts
packages/phrases/src/locales/it/translation/admin-console/components.ts
packages/phrases/src/locales/ja/translation/admin-console/components.ts
packages/phrases/src/locales/ko/translation/admin-console/components.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/components.ts
packages/phrases/src/locales/pt-br/translation/admin-console/components.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/components.ts
packages/phrases/src/locales/ru/translation/admin-console/components.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/components.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/components.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/components.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/components.ts
packages/schemas/src/types/user-assets.ts

- Increase file upload size limit to 10 MB.
- Improve i18n error message.

refactor(console,phrases,schemas): increase file upload size limit to 10mb

---

packages/experience/src/components/InputFields/InputField/NotchedBorder/index.module.scss

1. fix label padding and left postion to avoid label swing when label is shrinking.
2. add color transition for label
Test locally.

style(experience): improve notched border animation

---

packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx

Remove the final dev feature guard of "impersonation".
N/A

chore(console): remove dev feature guard

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/helpers.ts
packages/core/src/routes/experience/classes/utils.ts
packages/core/src/routes/experience/classes/validators/provision-library.ts

Extract helpers and provision methods.
This PR further refactors the current `ExperienceInteraction` class. Extract some of the standard logic into to newly created `helpers` file and `ProvisionLibrary` class.
- Move the `getNewUserProfileFromVerificationRecord` and `identifyUserByVerificationRecord` two methods from `utils.js` to the newly added `helpers.js`. Util functions should be simple with no business logic.
- Extract the entirely new user creation logic into the `ProvisionLibrary` as a new method `provisionNewUser`
- Extract the new `EnterpriseSsoIdentity` linking logic into the `ProvisionLibrary` as a new method `provisionNewSsoIdentity`
This will clean up and redeem the complexity of the main  `ExperienceInteraction` class.
integration test covered.

refactor(core): extract helpers and provision methods

---

packages/console/src/pages/Profile/index.tsx
packages/core/src/middleware/koa-cors.ts
packages/elements/index.html
packages/elements/package.json
packages/elements/src/elements/logto-profile-card.ts
packages/elements/src/index.ts
packages/elements/src/providers/logto-user-provider.ts
packages/elements/src/react.ts
packages/elements/src/utils/api.ts
pnpm-lock.yaml

- implement api get/update user
- implement name update

feat(elements): update name of user

---

packages/console/src/ds-components/Uploader/FileUploader/index.module.scss
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts

- Update file uploader componet to 80px fixed height
- Improve bring your UI field description
locally

refactor(console,phrases): minor ui changes to file uploader component and ui description

---

packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx
packages/schemas/src/types/user-assets.ts

- Add `isCloud` guard to "Bring your UI` form field since this should be a Cloud only feature
- Increase file upload size limit to 20MB
Locally

refactor(console,schemas): misc updates for bring your ui feature

---

packages/core/src/routes/sign-in-experience/custom-ui-assets/index.ts
packages/phrases/src/locales/en/errors/guard.ts

Disable "Bring your UI" feature for admin tenant, guarding it on the API.
Locally

fix(core): disable bring your ui feature for admin tenant

---

packages/console/src/pages/OrganizationDetails/index.tsx

Loading and error state should be handled by the `DetailsPage` component, or error and loading state will be displayed together with the detail content.
Test locally.

fix(console): fix loading and error handling for org details page

---

packages/core/package.json
packages/core/src/event-listeners/index.ts
packages/core/src/middleware/koa-app-secret-transpilation.test.ts
packages/core/src/middleware/koa-app-secret-transpilation.ts
packages/core/src/middleware/koa-oidc-error-handler.ts
packages/core/src/middleware/koa-slonik-error-handler.ts
packages/core/src/oidc/init.ts
packages/core/src/queries/application-secrets.ts
packages/core/src/routes/applications/application-secret.openapi.json
packages/core/src/routes/applications/application-secret.ts
packages/core/src/routes/applications/application.test.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/init.ts
packages/core/src/tenants/Queries.ts
packages/integration-tests/src/api/application.ts
packages/integration-tests/src/tests/api/application/application.secrets.test.ts
packages/integration-tests/src/tests/api/application/application.test.ts
packages/integration-tests/src/tests/api/oidc/client-authentication.test.ts
packages/phrases/src/locales/en/errors/application.ts
pnpm-lock.yaml

> [!Note]
> Hey don't get scared by the # of rows. They are mainly tests, lockfile updates, docs, and comments.
resolve LOG-9673
- implement `koaAppSecretTranspilation()` to check the client authentication with the new app secrets implementation. see its comments for details.
- improve `koaOidcErrorHandler()`, to make it more accurate for error reports
- improve `koaSlonikErrorHandler()` to handle more database errors
- refactor the way we handle request body in OIDC endpoints - replicate what `oidc-provider` does
- implement new application secrets routes with related queries
- insert a new secret to `application_secrets` table when an application creates
and integration tests

feat(core): multiple app secrets

---

packages/core/src/event-listeners/grant.ts
packages/core/src/event-listeners/utils.ts
packages/core/src/middleware/koa-app-secret-transpilation.ts
packages/integration-tests/src/tests/api/oidc/client-authentication.test.ts

when an app secret transpilation happened, the app secret name should be loged

refactor(core): log app secret name

---

packages/console/src/consts/env.ts
packages/console/src/mdx-components/Mermaid/index.tsx
packages/core/src/middleware/koa-security-headers.ts
vite.shared.config.ts

- use local mermaid for better compatibility
- enable sourcemap for better debugging

refactor(console): use local mermaid import

---

.changeset/clever-lemons-yawn.md
packages/core/src/__mocks__/index.ts
packages/core/src/routes/applications/application-custom-data.openapi.json
packages/core/src/routes/applications/application-custom-data.ts
packages/core/src/routes/applications/application.ts
packages/integration-tests/src/api/application.ts
packages/integration-tests/src/tests/api/application/application-custom-data.test.ts
packages/schemas/alterations/next-1721645392-add-application-custom-data-column.ts
packages/schemas/src/seeds/application.ts
packages/schemas/tables/applications.sql

Add `custom_data`  column to the application. 
Also, add a new endpoint `PATCH /applications/:applicationId/custom-data`.
test locally

feat(schemas): add custom data to application

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/helpers.ts
packages/core/src/routes/experience/classes/libraries/mfa-validator.ts
packages/core/src/routes/experience/classes/mfa.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/routes/experience/classes/verifications/totp-verification.ts
packages/core/src/routes/experience/classes/verifications/web-authn-verification.ts
packages/core/src/routes/experience/const.ts
packages/core/src/routes/experience/profile-routes.ts
packages/core/src/routes/experience/verification-routes/web-authn-verification.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/mfa-verification.test.ts
packages/phrases/src/locales/en/errors/session.ts

Implement the missing mfa bind and guard flow
- New class `Mfa` that stores new linked MFA data and provides the linking methods.
- New profile endpoints:
- `/experience/profile/mfa/mfa-skipped`
- `/experience/profile/mfa`
- `/experience/profile/mfa/backup-codes/generate`
- `/experience/profile/mfa/backup-codes`
integration tests in a separate PR. Working on tests. 
See #6330 for integration tests.

feat(core): implement the missing mfa bind and guard flow

---

packages/core/src/routes/experience/classes/libraries/mfa-validator.ts
packages/core/src/routes/experience/classes/verifications/backup-code-verification.ts
packages/core/src/routes/experience/classes/verifications/totp-verification.ts
packages/core/src/routes/experience/classes/verifications/verification-record.ts
packages/core/src/routes/experience/classes/verifications/web-authn-verification.ts

Define a  `isNewMfaVerifrication` property in the MfaVerification records.  @wangsijie

refactor(core): extract isNewMfaVerification property

---

packages/core/src/routes/experience/classes/mfa.ts
packages/core/src/routes/experience/classes/verifications/backup-code-verification.ts
packages/core/src/routes/experience/classes/verifications/verification-record.ts
packages/core/src/routes/experience/profile-routes.ts
packages/core/src/routes/experience/verification-routes/backup-code-verification.ts

Refactor backup code generates flow. Align with TOTP and WebAuthn.  Use verification record as the single source of truth for new generated backup codes. 
All the MFAs should be bound by a MfaVerificationRecord. 
@wangsijie 
integration test updated

refactor(core): refactor backup code generates flow

---

packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx

Update "Bring your UI" documentation link. [Related PR](https://github.com/logto-io/docs/pull/752)(unpublished)
Locally

chore(console): update bring your ui documentation link

---

packages/elements/src/providers/logto-user-provider.ts

The user context tag name should be `user-context`
No need.

fix(elements): fix user context tag name

---

packages/console/src/pages/Applications/components/ProtectedAppCard/index.tsx

Remove beta tag protected app.
Local preview.

feat(console): remove beta tag for protected app

---

packages/console/src/components/Conversion/index.tsx

see https://github.com/logto-io/website/pull/552
n/a

chore: update plausible urls

---

packages/core/src/routes/applications/application-protected-app-metadata.openapi.json

refactor openapi docs for protected app, to align with other APIs.
N/A

refactor(core): refactor openapi docs for protected app

---

.changeset/stale-planets-sneeze.md
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
packages/core/src/oidc/init.ts
packages/core/src/routes/applications/application-secret.openapi.json
packages/core/src/routes/applications/application.openapi.json
packages/core/src/routes/applications/application.ts
packages/core/src/routes/init.ts
packages/core/src/routes/organization/application/index.openapi.json
packages/core/src/routes/swagger/index.ts
packages/core/src/routes/swagger/utils/general.ts
packages/integration-tests/src/tests/api/application/application.secrets.test.ts
packages/schemas/tables/applications.sql

🚀 resolves LOG-9675
updated test flags accordingly

chore: launch multiple app secrets

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/CreateSecretModal.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EditSecretModal.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials/use-secret-table-columns.tsx
packages/core/src/middleware/koa-security-headers.ts
packages/core/src/queries/application-secrets.ts
packages/core/src/routes/applications/application-secret.openapi.json
packages/core/src/routes/applications/application-secret.ts
packages/integration-tests/src/api/application.ts
packages/integration-tests/src/tests/api/application/application.secrets.test.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts

resolve LOG-9703, allowing app secret name editing
- tested locally
- added integration tests

feat: allow app secret edit

---

packages/core/src/routes/experience/profile-routes.ts
packages/core/src/routes/experience/verification-routes/backup-code-verification.ts

Extract profile routes shared verified interaction guard logic as a middleware. 
Guard by integration tests.

refactor(core): extract verified interaction guard middleware

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/mfa.ts
packages/core/src/routes/experience/classes/profile.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/middleware/koa-experience-interaction.ts
packages/core/src/routes/experience/middleware/koa-experience-verifications-audit-log.ts
packages/core/src/routes/experience/profile-routes.ts
packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts
packages/core/src/routes/experience/verification-routes/password-verification.ts
packages/core/src/routes/experience/verification-routes/social-verification.ts
packages/core/src/routes/experience/verification-routes/totp-verification.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts
packages/core/src/routes/experience/verification-routes/web-authn-verification.ts
packages/schemas/src/types/log/interaction.ts

Add audit logs to experience API
test locally

feat(core,schemas): add auditLogs to experience API

---

packages/core/src/routes/experience/classes/libraries/password-validator.ts
packages/core/src/routes/experience/classes/mfa.ts

Api exception data bug fix.
This PR fixes two API exception error data bugs while migrating our experience app. 
1. `password.rejected` error: The `issues` array should be directly returned to the error body.
2. `user.missing_mfa`: Should return the missing MFA factors instead of the user's existing ones. Rename the variables to avoid misleading. 
test locally
covered by the experience smoke test

fix(core): error data bug fixing

---

packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx

Update the upcoming bill info displayed in console page.
Both the `cost` (new pricing model and legacy pricing model) passed to the `<BillInfo />` component is in US cents, so don't worry.
N/A

refactor(console): update billing info showed in subscription details page

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/utils.ts
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/console/src/pages/OrganizationDetails/Settings/utils.ts
packages/console/src/utils/json.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts

Refactor the customData error display logic. Add the inline error message display and validation logic.

fix(console): add in-line error message

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts

Based on the Logto sign-in experience design, should not ask for additional MFA validations and profile fulfillment for enterprise SSO verified users. 
- auto return the MFA validation if the interaction has verified enterprise SSO verification record
- skip the user profile fulfilled validation if the interaction has verified enterprise SSO verification record
- skip the user MFA bind validation if the interaction has verified enterprise SSO verification record

refactor(core): should not guard sso authentication flow

---

packages/console/src/assets/docs/guides/web-next-auth/README.mdx

Support next auth v5 in guide.

feat(console): support next auth v5

---

packages/console/vite.config.ts
packages/demo-app/index.html
packages/demo-app/package.json
packages/demo-app/vite.config.ts
packages/experience/vite.config.ts
pnpm-lock.yaml

we still need to produce br outputs as CDN may not cache the assets promptly
observed br outputs for `build` scripts

refactor: produce br outputs

---

packages/cli/src/commands/database/seed/tables.ts
packages/core/src/libraries/cloud-connection.ts
packages/schemas/alterations/next-1722914357-add-report-sub-updates-cloud-scope.ts
packages/schemas/src/seeds/cloud-api.ts

add `report:subscription:updates` Cloud scope
Should be covered by CI.

refactor: add `report:subscription:updates` Cloud scope

---

packages/schemas/alterations/next-1722506508-personal-access-tokens.ts
packages/schemas/tables/personal_access_tokens.sql

Init personal access tokens table, refer to https://github.com/logto-io/rfcs/pull/13
CI should pass.

feat(schemas): init personal access tokens table

---

packages/core/src/routes/admin-user/personal-access-token.openapi.json
packages/core/src/routes/admin-user/personal-access-token.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/tests/api/admin-user.personal-access-tokens.test.ts

Implement API to get PATs for user.

feat(core): list PATs

---

packages/core/src/queries/personal-access-tokens.ts
packages/core/src/routes/admin-user/personal-access-token.openapi.json
packages/core/src/routes/admin-user/personal-access-token.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/tests/api/admin-user.personal-access-tokens.test.ts

Implement API to update and delete PATs.

feat(core): modify and delete PATs

---

.changeset/friendly-rice-sell.md
packages/console/src/pages/CustomizeJwt/CreateButton/index.tsx

should not block custom JWT creation for OSS user

fix(console): should not block custom JWT creation for OSS user

---

.changeset/long-rabbits-roll.md
packages/cli/src/commands/tunnel/index.ts
packages/cli/src/commands/tunnel/types.ts
packages/cli/src/commands/tunnel/utils.ts
packages/cli/src/index.ts

- Rename the `proxy` cli command to `tunnel`
- Add changeset since it was removed from the release notes of v1.19.0
Locally tested

refactor(cli): rename proxy cli to tunnel

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
packages/core/src/routes/experience/experience.openapi.json
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/profile-routes.openapi.json
packages/core/src/routes/experience/verification-routes/backup-code-verification.openapi.json
packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.openapi.json
packages/core/src/routes/experience/verification-routes/new-password-identity-verification.openapi.json
packages/core/src/routes/experience/verification-routes/password-verification.openapi.json
packages/core/src/routes/experience/verification-routes/password-verification.ts
packages/core/src/routes/experience/verification-routes/social-verification.openapi.json
packages/core/src/routes/experience/verification-routes/totp-verification.openapi.json
packages/core/src/routes/experience/verification-routes/totp-verification.ts
packages/core/src/routes/experience/verification-routes/verification-code.openapi.json
packages/core/src/routes/experience/verification-routes/web-authn-verification.openapi.json
packages/core/src/routes/experience/verification-routes/web-authn-verification.ts
packages/core/src/routes/init.ts
packages/core/src/routes/swagger/index.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/integration-tests/src/tests/api/experience-api/verifications/backup-code-verification.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts

Add experience API openapi docs. 
test locally

feat(core): add experience APIs openapi docs

---

packages/console/src/components/FeatureTag/index.module.scss
packages/console/src/components/FeatureTag/index.tsx

update add on tag CSS.
For `<AddOnTag />`, disable `text-transform` CSS to show `Add-on` instead of `Add-On`.

chore(console): update add on tag CSS

---

packages/cli/src/commands/tunnel/utils.test.ts
packages/cli/src/commands/tunnel/utils.ts

Fix the `isFileAsset()` util, in order to better support the Google social callback URL. Details can be found in attached Linear issue (LOG-9827).
Locally tested. And Google social sign-in callback can be proxied properly

fix(cli): should proxy google social callback url properly to exp ui

---

packages/experience/src/constants/env.ts
packages/experience/vite.config.ts

We're using Vite now, so need to update the dev features flag env handling as well.
Integration tests passed in https://github.com/logto-io/logto/pull/6464

fix(experience): update dev features flag env handling

---

packages/integration-tests/src/tests/experience/first-screen.test.ts
packages/integration-tests/src/ui-helpers/expect-experience.ts

Add integration tests for first screen feature
CI

test(experience): add integration tests for first screen feature

---

packages/console/src/consts/logs.ts

Add labels for new experience API logs:

feat(console): add label for new experience API logs

---

packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
packages/console/src/components/BillInfo/index.tsx
packages/console/src/components/ChargeNotification/index.tsx
packages/console/src/components/PlanUsage/index.tsx
packages/console/src/consts/external-links.ts
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx

fix add-on issues.
1. update billing info article links (resolves LOG-9790)
2. fix app creation modal paywall display (should show Pro tag when the current plan is not Pro)
3. only show add-on tag on creation modal when quota limit is reached (for API resource, m2m app, and tenant member invitation modals, this resolves LOG-9830 and LOG-9850)

chore(console): fix add-on issues

---

packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/CreateTokenModal.tsx
packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/index.module.scss
packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/index.tsx
packages/console/src/pages/UserDetails/UserSettings/index.tsx
packages/phrases/src/locales/en/translation/admin-console/user-details.ts

Implement user personal access tokens (PAT) management in Console.

feat(console): user personal access tokens

---

packages/experience/src/pages/IdentifierRegister/index.tsx
packages/experience/src/pages/SingleSignOnLanding/index.tsx
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/tests/experience/first-screen.test.ts

Identifier register page: fallback to sign-in if registration is not enabled
Single sign-on page: fallback to sign-in if signle sign-on is not enabled
Test locally & Integration tests

fix(experience): correct first screen fallbacks

---

packages/console/src/assets/docs/guides/web-next-auth/README.mdx

fix next auth guide typo, remove duplicated `'`.

fix(console): fix next auth guide typo

---

packages/console/src/ds-components/FormField/index.module.scss
packages/console/src/ds-components/FormField/index.tsx
packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx

Add beta tag to "Bring your UI" feature
- Free plan
- Paid pro plan

chore(console): add beta tag to bring your ui feature

---

packages/console/src/components/Guide/GuideCard/index.tsx
packages/console/src/components/Guide/GuideCardGroup/index.tsx

- Remove beta tag from 3rd party app.
- Move the tag display logic to the outer parent component
Locally tested

chore(console): remove beta tag from 3rd party app

---

packages/schemas/alterations/next-1724229102-add-report-sub-updates-cloud-scope.ts

fix alteration script dependency
should not import `generateStandardId()` from @logto/shared package.
N/A

fix: fix alteration script dependency

---

packages/experience/src/scss/_colors.scss

Add the missing `color-brand-60` color token.
Test locally.

style(experience): add missing brand-60 color token

---

packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/EditTokenModal.tsx
packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/index.tsx

Edit name of personal access tokens.
Local tested.

feat(console): edit personal access token name

---

packages/console/src/pages/CustomizeJwt/index.tsx

should always show upsell notice for custom JWT for free tenants

fix(console): always show upsell notice for custom JWT

---

packages/core/src/routes/experience/anonymous-routes/index.openapi.json
packages/core/src/routes/experience/experience.openapi.json
packages/core/src/routes/experience/profile-routes.openapi.json
packages/core/src/routes/experience/verification-routes/backup-code-verification.openapi.json
packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.openapi.json
packages/core/src/routes/experience/verification-routes/new-password-identity-verification.openapi.json
packages/core/src/routes/experience/verification-routes/password-verification.openapi.json
packages/core/src/routes/experience/verification-routes/social-verification.openapi.json
packages/core/src/routes/experience/verification-routes/totp-verification.openapi.json
packages/core/src/routes/experience/verification-routes/verification-code.openapi.json
packages/core/src/routes/experience/verification-routes/web-authn-verification.openapi.json
packages/core/src/routes/swagger/utils/general.ts
packages/core/src/routes/swagger/utils/operation-id.ts

Add custom openapi `operationId` to experience APIs so we may have a better meaningful API name generated when using API SDK generators. 
test locally.

chore(core): add openapi operationId to experience APIs

---

packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts

Add integration test for PAT exchanged access token, should pass token introspection check.
Integration test.

test: add integration tests for pat token introspection

---

packages/core/src/oidc/grants/token-exchange/index.test.ts
packages/core/src/oidc/grants/token-exchange/index.ts
packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts

Implement a real grant model in token exchange, this will be used in features like token introspection and user info endpoint.
Add an integrationt test to get userinfo by access token, this will check the grant record.

fix(core): add grant record for token exchange

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials/index.tsx
packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/index.tsx
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/user-details.ts
vite.shared.config.ts

Change empty placeholder and create button text of PAT and app secrets.

fix(console): change PAT and app secrets phrases

---

vite.shared.config.ts

Remove optimize deps config for local dev, since it will cause the development environment to use outdated cache.
None

chore: remove optimize deps config for local dev

---

packages/console/src/pages/UserDetails/UserSettings/index.tsx
packages/core/src/routes/admin-user/index.ts
packages/core/src/routes/admin-user/personal-access-token.openapi.json
packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts

remove dev feature guard of PAT

chore: remove dev feature guard of PAT

---

packages/core/src/libraries/verification-status.ts

Should be able to change password in Profile page, after verifying self identify via email verification code.
Locally tested

fix(core): should be able to update password in profile if verified via email

---

.changeset/nine-vans-whisper.md
packages/core/src/oidc/utils.ts
packages/experience/src/App.tsx
packages/experience/src/pages/IdentifierRegister/index.tsx
packages/experience/src/pages/IdentifierSignIn/index.tsx
packages/integration-tests/src/tests/experience/first-screen.test.ts

Remove dev feature guard for first screens
None.

chore: remove dev feature guard for first screens

---

.changeset/dry-candles-design.md
packages/console/src/pages/Users/components/CreateForm/index.tsx

a patch for better experience
locally tested, the name field can be successfully captured

refactor(console): support entering name while creating a user

---

packages/cli/package.json
packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/core/package.json
packages/core/src/libraries/quota.ts
packages/core/src/middleware/koa-quota-guard.ts
packages/core/src/utils/subscription/types.ts
packages/toolkit/connector-kit/package.json
pnpm-lock.yaml

update withtyped and cloud dependency version

fix(deps): update withtyped and cloud dependency version

---

packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts

Bug bash fix. adjust sample code editor height and phrases update.
test locally

style(console): adjust sample code editor height

---

packages/console/src/pages/CustomizeJwt/index.tsx
packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
packages/phrases/src/locales/en/errors/jwt-customizer.ts
packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts

Update custom JWT phrases to avoid using the word `JWT claims` in the console.
Add learn more link.

chore(console,phrases): update custom JWT phrases

---

.changeset/spicy-cameras-sleep.md
packages/console/scripts/custom-jwt-customizer-type-definition.ts
packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
packages/core/src/libraries/jwt-customizer.ts
packages/core/src/oidc/extra-token-claims.ts
packages/integration-tests/src/__mocks__/jwt-customizer.ts
packages/integration-tests/src/tests/api/admin-user.personal-access-tokens.test.ts
packages/integration-tests/src/tests/api/logto-config.test.ts
packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
packages/schemas/src/types/logto-config/jwt-customizer.ts

Remove custom token claims api context dev guard.

feat(console,core): remove custom token claims api context dev guard

---

packages/core/src/middleware/koa-spa-proxy.test.ts
packages/core/src/middleware/koa-spa-proxy.ts

fix custom UI not triggered on `legacy-experience` package bug

fix(core): fix custom UI not triggered bug

---

packages/console/src/consts/logs.ts

fix(console): fix log label typo

---

commitlint.config.ts
packages/experience-legacy/src/Providers/AppBoundary/AppMeta.tsx

Add `dir` html attribute to better support RTL in `experience-legacy` package
Locally

fix(experience-legacy): add html attribute dir to better support RTL

---

packages/experience-legacy/src/components/Button/MfaFactorButton.module.scss
packages/experience-legacy/src/components/InputFields/InputField/NotchedBorder/index.module.scss
packages/experience-legacy/src/containers/SocialLinkAccount/index.module.scss

Update text alignment to better support RTL in `experience-legacy` package.
Locally tested

fix(experience-legacy): update text alignment for RTL support

---

packages/experience-legacy/src/components/Button/MfaFactorButton.tsx
packages/experience-legacy/src/components/FlipOnRtl/index.module.scss
packages/experience-legacy/src/components/FlipOnRtl/index.tsx
packages/experience-legacy/src/components/NavBar/index.tsx

Flip arrow icons on RTL in `experience-legacy` package.
Locally tested

fix(experience-legacy): flip arrow icons on rtl

---

packages/console/src/components/Region/index.tsx
packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.module.scss
packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.module.scss
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.tsx

fix alignment and adopt the new design of tenant selector. resolve LOG-10083, LOG-10085, LOG-10082

refactor(console): fix region-related styles

---

packages/console/src/components/CreateConnectorForm/index.tsx

Hide the entrance of the new http email connector, at this stage, this connector can only be added through API requests manually.
Local tested.

feat(console): hide the entrance of http email connector

---

packages/connectors/connector-http-email/README.md

Add README of http email connector.
N/A

docs(connector): add readme of http email connector

---

packages/connectors/connector-http-email/src/constant.ts

Fix connector id of HTTP email connector, the `id` value is replaced to a wrong value during rebase.
Local tested.

fix(connector): fix http email connector id

---

packages/connectors/connector-http-email/src/constant.ts

Add tooltip of the field "Authorization header" in http email connector.
Local preview.

fix(connector): add tooltip of authorization header field

---

packages/connectors/connector-http-email/README.md

Add full type list link in README of http email connector.
N/A

fix(connector): add type list in readme

---

packages/core/src/libraries/verification.ts
packages/core/src/queries/verification-records.ts
packages/core/src/routes/experience/classes/libraries/sentinel-guard.ts
packages/core/src/routes/experience/classes/utils.ts
packages/core/src/routes/experience/classes/verifications/password-verification.ts
packages/core/src/routes/init.ts
packages/core/src/routes/profile/index.openapi.json
packages/core/src/routes/profile/index.ts
packages/core/src/routes/swagger/consts.ts
packages/core/src/routes/swagger/utils/documents.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/core/src/routes/types.ts
packages/core/src/routes/verification/index.openapi.json
packages/core/src/routes/verification/index.ts
packages/core/src/routes/well-known/well-known.openapi.json
packages/core/src/routes/well-known/well-known.openapi.ts
packages/core/src/tenants/Queries.ts
packages/integration-tests/src/api/profile.ts
packages/integration-tests/src/api/verification-record.ts
packages/integration-tests/src/helpers/admin-tenant.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/password-verification.test.ts
packages/integration-tests/src/tests/api/profile/index.test.ts
packages/integration-tests/src/tests/api/well-known.openapi.test.ts
packages/phrases/src/locales/en/errors/index.ts
packages/phrases/src/locales/en/errors/verification-record.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
packages/schemas/src/types/interactions.ts

Implement API `POST /profile/password` for changing password. Include the use of verification record and end user's oidc access token.
Reuse the class `PasswordVerification` with some changes:
1. Extend `identifier` to accept `userId` as an identifier
Please notice that the class `PasswordVerification` is still in the old directory for better code review, will move them to another folder in LOG-9983

feat(core): update password in profile

---

packages/core/src/middleware/koa-security-headers.ts

Update code comments in `koa-security-headers.ts`.
N/A

chore(core): update code comments in security header middleware

---

.changeset/tasty-kings-fetch.md
.changeset/violet-ligers-carry.md

Split changeset for tunnel from #6630, since tunnel will be released separately from Logto core.
N/A

chore: split and add dedicated changeset for tunnel

---

packages/core/src/routes/profile/index.openapi.json
packages/core/src/routes/profile/index.ts
packages/integration-tests/src/api/profile.ts
packages/integration-tests/src/tests/api/profile/index.test.ts

Add support of updating username in Profile API.

feat(core): update username

---

packages/core/src/routes/init.ts
packages/core/src/routes/profile/index.ts
packages/core/src/routes/types.ts
packages/core/src/routes/verification/index.ts
packages/integration-tests/src/api/api.ts
packages/integration-tests/src/helpers/profile.ts
packages/integration-tests/src/tests/api/profile/index.test.ts

Trigger webhook event in Profile API. Reuse the middleware `koaManagementApiHooks`, and will rename it later.
Also change the integration tests to call Profile API in default tenant instead of admin tenant.

feat(core): trigger webhook event in profile api

---

packages/core/src/middleware/koa-error-handler.ts

If an invalid JSON body is provided, a 500 internal server error will be returned to the client, which is not developer-friendly. 
A detailed syntax error message should be returned to the API error response body with status code 400. 
test locally
Before:
```json
{
"message": "Internal server error.",
"status": 500
}
```
After:
```json
{
"message": "Unexpected token ']', ...\"gto\",\n    ],\n    \"po\"... is not valid JSON",
"status": 400
}
```

fix(core): expose syntax error response

---

packages/core/src/routes/profile/index.ts
packages/integration-tests/src/tests/api/profile/index.test.ts

In change password API of profile, check if the new password meets the password policy.

feat(core): check password policy before changing password

---

packages/core/src/routes/profile/index.openapi.json
packages/core/src/routes/profile/index.ts
packages/core/src/routes/profile/utils/get-scoped-profile.ts
packages/integration-tests/src/api/profile.ts
packages/integration-tests/src/tests/api/profile/email-and-phone.test.ts
packages/integration-tests/src/tests/api/profile/index.test.ts

Implement `GET /api/profile` to get user profile information, the response is a partial "UserProfileResponse" because some fields will be filtered out based on scopes.

feat(core): get user profile

---

packages/schemas/alterations/next-1728357690-add-sso-connector-idp-initated-auth-configs-table.ts
packages/schemas/src/foundations/jsonb-types/sso-connector.ts
packages/schemas/tables/sso_connector_idp_initiated_auth_configs.sql

Add SAML SSO IdP initiated auth config table.

feat(schemas): add SAML SSO IdP initated auth config table

---

packages/core/src/libraries/sign-in-experience/index.test.ts
packages/core/src/libraries/sso-connector.ts
packages/core/src/queries/sso-connectors.ts
packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
packages/core/src/routes/sso-connector/idp-initiated-auth-config.openapi.json
packages/core/src/routes/sso-connector/idp-initiated-auth-config.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/tests/api/sso-connectors/sso-connector-idp-initiated-auth-config.test.ts

Add `PATCH` and `DELETE` SSO connector IdP initiated auth config API

feat(core): add patch and delete SAML IdP initiated config API

---

packages/core/src/routes/profile/index.openapi.json
packages/core/src/routes/profile/index.ts
packages/integration-tests/src/api/profile.ts
packages/integration-tests/src/tests/api/profile/index.test.ts

feat(core): update other profile data

---

commitlint.config.ts
packages/account-elements/README.md
packages/account-elements/index.html
packages/account-elements/package.json
packages/account-elements/src/index.ts
packages/account-elements/src/providers/logto-account-provider.ts
packages/account-elements/src/react.ts
packages/account-elements/tsconfig.json
packages/account-elements/tsup.config.ts
packages/account-elements/web-dev-server.config.js
pnpm-lock.yaml

The setup for this project comes from the existing elements project within the current project (which will be deprecated later).

chore(account-elements): setup account elements project

---

packages/account-elements/src/api/index.ts
packages/account-elements/src/index.ts
packages/account-elements/src/react.ts

Add initial account api which will be used in the later `logto-account-provider`.
Note:
- The error handling is not included in this PR, will implement the error handler in other pull requests.
No need.

feat(account-elements): add initial account api

---

packages/console/src/consts/page-tabs.ts
packages/console/src/ds-components/Select/index.module.scss
packages/console/src/ds-components/Select/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/ConfigForm.tsx
packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/index.module.scss
packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/use-idp-initiated-auth-config-swr.ts
packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/utils.ts
packages/console/src/pages/EnterpriseSsoDetails/index.tsx
packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
packages/phrases/src/locales/en/translation/admin-console/errors.ts

Add idp-initiated SSO config page
test locally

feat(console): add idp-initiated sso config page

---

packages/core/src/routes/profile/index.openapi.json
packages/core/src/routes/profile/index.ts
packages/core/src/routes/verification/index.ts
packages/integration-tests/src/api/profile.ts
packages/integration-tests/src/tests/api/profile/email-and-phone.test.ts

In profile API, implement phone update and create, similar to email.

feat(core): add and change phone

---

packages/console/src/components/CreateTenantModal/index.tsx

:rocket:
try to create an au tenant in prod (test after merge)

chore: launch au region

---

packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx

fix enterprise tenants not displayed issue.

fix(console): fix enterprise tenants not displayed issue

---

packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
packages/console/src/pages/CheckoutSuccessCallback/index.tsx
packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
packages/console/src/pages/TenantSettings/Subscription/index.tsx

manually update current tenant's data when corresponding data get updated, which includes:
1. subscription data
2. quota and usage data
3. open invoice data
N/A

fix(console): manually update tenant data when data get updated

---

packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/ConfigForm.tsx
packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/index.module.scss
packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts

Update selector styles and content:
- Update the application details font color in the `Select` component.
- Update the Authentication type content and font color.
Test locally

style(console,phrases): update selector styles

---

packages/console/src/pages/TenantSettings/Subscription/index.tsx

fix inf loop for updating tenant context.
Previous implementation triggers inf loop of calling `GET /:tenantId/subscription` API. `updateTenant()` triggers the update of `onCurrentSubscriptionUpdated()` and `onCurrentSubscriptionUpdated()` triggers the update of `updateTenant()`.

fix(console): fix inf loop for updating tenant context

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/console/src/consts/quota-item-phrases.ts
packages/console/src/consts/tenants.ts
packages/console/src/pages/EnterpriseSsoDetails/index.tsx
packages/core/package.json
packages/core/src/routes/authn.ts
packages/core/src/routes/sso-connector/idp-initiated-auth-config.openapi.json
packages/core/src/routes/sso-connector/idp-initiated-auth-config.ts
packages/core/src/routes/sso-connector/index.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
pnpm-lock.yaml

Guard the IdP-initiated SSO auth configs management API to cloud-only.
Apply the quota guard to the console and management API as well. 
test locally

chore(core): guard idp-initiated sso console and api

---

packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/ConfigForm.tsx
packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/utils.ts
packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts

1. Set the first available application on the list as the default one, if the `defaultApplicationId` is empty
2. Add `No applications` placeholder, if no application is available
3. Add `Select redirect URI` placeholder
test locally

fix(console): add applications and redirect uri placeholder

---

.github/workflows/main.yml
packages/elements/package.json
packages/elements/src/account/__mocks__/account-api.ts
packages/elements/src/account/providers/logto-account-provider.test.ts
packages/elements/src/account/providers/logto-account-provider.ts
packages/elements/web-test-runner.config.js
pnpm-lock.yaml

This PR introduces the `LogtoAccountProvider` component and sets up a comprehensive testing infrastructure for the `@logto/elements` package and the `LogtoAccountProvider` will be a central component for managing user authentication state and providing account data to other components.
- Implemented the LogtoAccountProvider component to provide account information to child components.
- Added the LogtoAccountApi class for interacting with Logto backend APIs.
- Created logtoAccountContext for sharing account information throughout the component tree.
- Added unit tests for LogtoAccountProvider to ensure proper initialization and error handling.
- Configured the testing environment, including the addition of Playwright and Web Test Runner.
- Updated CI workflow to support the new tests.
- …

feat(elements): introduce basic logto-account-provider

---

packages/core/package.json
pnpm-lock.yaml

chore: bump nodemon

---

packages/connectors/connector-postmark/package.json
packages/core/package.json
packages/integration-tests/package.json
pnpm-lock.yaml

Bump dependency versions to fix the [axios](https://github.com/logto-io/logto/security/dependabot/49) security issue

chore: bump dependency versions

---

.changeset/tender-peaches-listen.md
.changeset/wild-beers-run.md

Add changeset of GatewayAPI connector.
N/A

chore: add changeset of gatewayapi connector

---

.github/workflows/master-codecov-report.yml

Should install playwright before runing element tests in coverage tests.
No need.

ci: install playwright for element tests

---

packages/core/src/routes/experience/classes/verifications/social-verification.ts
packages/core/src/routes/verification/index.ts

refactor social verification class to support profile API. Manage the social authorization session using the current verification record.

refactor(core): refactor social verification class

---

packages/console/src/consts/logs.ts
packages/core/src/routes/authn.ts
packages/schemas/src/types/log/interaction.ts

Add an IdP-initiated SSO session log upon receiving the SAML SSO assertion request from IdP

feat(core,console,schemas): add idp-initiated sso session create log

---

packages/elements/index.html
packages/elements/src/account/elements/logto-account-center.test.ts
packages/elements/src/account/elements/logto-account-center.ts
packages/elements/src/account/index.ts
packages/elements/src/account/react.ts

Add `logto-account-center` element  that combines all profile elements into a single, cohesive interface.
Test locally & UTs

feat(elements): add logto-account-center element

---

packages/console/package.json
packages/experience-legacy/package.json
packages/experience/package.json
pnpm-lock.yaml

Update postcss-modules version to address the [security issue](https://github.com/logto-io/logto/security/dependabot/10).

chore(deps): update postcss-modules version

---

packages/core/src/routes/interaction/utils/social-verification.ts
packages/core/src/routes/profile/index.openapi.json
packages/core/src/routes/profile/index.ts
packages/integration-tests/src/api/profile.ts
packages/integration-tests/src/tests/api/profile/social.test.ts

feat(core): remove social identity

---

package.json
pnpm-lock.yaml

Override braces dependency version to avoid the [security issue](https://github.com/logto-io/logto/security/dependabot/46)

chore(deps): override braces dependency version

---

packages/console/src/components/CreateConnectorForm/index.tsx

Fix Vonage SMS connector id.
Local tested.

fix(console): fix vonage connector id

---

packages/core/src/routes/profile/index.ts
packages/core/src/routes/profile/middlewares/koa-account-center.ts
packages/core/src/routes/profile/utils/get-scoped-profile.ts
packages/core/src/routes/types.ts
packages/core/src/routes/well-known/well-known.openapi.ts
packages/integration-tests/src/api/account-center.ts
packages/integration-tests/src/tests/api/account-center.test.ts
packages/integration-tests/src/tests/api/profile/account-center-reject.test.ts
packages/integration-tests/src/tests/api/profile/email-and-phone.test.ts
packages/integration-tests/src/tests/api/profile/index.test.ts
packages/integration-tests/src/tests/api/profile/social.test.ts
packages/phrases/src/locales/en/errors/account-center.ts
packages/phrases/src/locales/en/errors/index.ts

Apply the account center control for Profile API and every field.
For better code review experience, the file `packages/core/src/routes/profile/index.ts` is not refactored for exeeding 300 lines, created LOG-10349 to do it later.

feat(core): apply account center field control

---

packages/schemas/src/seeds/index.ts

export function `createDefaultAccountCenter`, will be used in Cloud when creating new tenant.
N/A

fix(schemas): export account center seed function

---

packages/core/src/routes/sign-in-experience/index.test.ts
packages/core/src/routes/sign-in-experience/index.ts
packages/integration-tests/src/tests/api/sign-in-experience.test.ts

Add support email and website URL format guard.
- support email: must be a valid email format
- support website URL: must be a valid URL format

feat(core): add support email & website url format guard

---

packages/console/src/pages/SignInExperience/PageContent/Content/SupportForm/index.tsx
packages/console/src/pages/SignInExperience/PageContent/Content/index.tsx
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/content.ts

Add support fields to the page

feat(console): add support fields config to sie

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/AdvancedOptions/index.tsx
packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
packages/core/src/middleware/koa-spa-session-guard.test.ts
packages/core/src/middleware/koa-spa-session-guard.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts

Add unknown session redirect URL input field to console SIE settings page.
test locally

feat(console): add unknown session redirect url input field

---

packages/console/src/pages/SignInExperience/PageContent/Content/SupportForm/index.tsx
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/content.ts

Add support field descriptions so users can better understand these two newly added configurations.

feat(console,phrases): add support field description

---

.changeset/early-numbers-attend.md
.changeset/four-deers-divide.md
.changeset/wet-nails-guess.md
packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
packages/console/src/pages/SignInExperience/PageContent/Content/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/AdvancedOptions/index.tsx
packages/core/src/middleware/koa-spa-session-guard.test.ts
packages/core/src/middleware/koa-spa-session-guard.ts

Remove dev feature guard and add changesets for the following newly added updates:
1. unknown session redirect URI
2. support channels on the error page
3. trust unverified email switch for Microsoft EntraID OIDC SSO connector.

chore: remove dev feature guard

---

packages/core/src/routes/profile/identities.ts
packages/core/src/routes/profile/index.ts

Split the file of profile route, to avoid exeeding 300 lines.

refactor(core): split profile route

---

packages/core/src/middleware/koa-oidc-error-handler.ts

For a better debugging experience, add an app insights log for OIDC original server errors.

chore: add app insights log for oidc server error

---

packages/core/src/routes/account-center/index.openapi.json
packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/index.ts
packages/core/src/routes/init.ts
packages/core/src/routes/swagger/utils/documents.ts
packages/core/src/routes/verification/index.openapi.json
packages/core/src/routes/verification/index.ts
packages/integration-tests/src/tests/api/account-center.test.ts
packages/integration-tests/src/tests/api/account/account-center-reject.test.ts
packages/integration-tests/src/tests/api/account/email-and-phone.test.ts
packages/integration-tests/src/tests/api/account/index.test.ts
packages/integration-tests/src/tests/api/account/social.test.ts

Remove feature guard of Account API.
N/A

chore: remove feature guard

---

.changeset/warm-pugs-divide.md

Add changeset of Account API.
N/A

chore: add changeset of account api

---

packages/schemas/alterations/next-1731054001-init-account-center.ts

Fix the alteration script, to run in chunks, to avoid failure in large tenant numbers.
N/A

fix(schemas): fix init account center alter run in chunks

---

.scripts/compare-database.js

add DB constraints sorting reference
N/A

fix: add DB constraints sorting reference

---

packages/core/src/saml-applications/libraries/saml-applications.ts
packages/core/src/saml-applications/libraries/utils.test.ts
packages/core/src/saml-applications/libraries/utils.ts
packages/core/src/saml-applications/queries/secrets.ts
packages/core/src/saml-applications/routes/anonymous.ts
packages/core/src/saml-applications/routes/index.ts
packages/integration-tests/src/tests/api/application/saml-application.test.ts
packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
packages/schemas/src/types/saml-application.ts

fix some SAML app bugs
1. fix the way of building IdP `entityId` (resolves LOG-10560)
2. create an `active` secret on SAML app creation (previously we create a inactive secret and manually activation is required) (resolves LOG-10558)
3. expand the `config` (includes `attributeMapping`, `acsUrl` and `entityId`) in POST and PATCH APIs (resolves LOG-10556)
4. update `SamlAcsUrl` type, `binding` field should be required. (resolves LOG-10561)
5. add `fingerprints` to SAML app secrets APIs response (resolves LOG-10563)
Update integration tests.

fix: fix some SAML app bugs

---

.scripts/compare-database.js

Whitelist `add_on_sku_id` on db alteration data compare.
This will address the ci issue under the cloud repo. 
We need to whitelist the randomly generated `add_on_sku_id` while seeding the new created `basic_sku_usage_add_on_relations` table.

chore: whitelist add_on_sku_id

---

packages/integration-tests/src/tests/console/user-management.test.ts

Remove unexpected `console.log` from integration test cases
N/A

chore: remove unexpected console log

---

package.json
pnpm-lock.yaml

Bump transitive dependency `ws`.
Local `pnpm-lock.yaml` looks good

chore: bump ws version

---

packages/core/src/routes/interaction/index.ts

Address the following unexpected error:
Add the missing status code [422] to the status code guard list. 
test locally

fix(core): add the missing status code

---

.changeset/hot-oranges-join.md
packages/console/src/pages/Mfa/MfaForm/constants.ts
packages/console/src/pages/Mfa/MfaForm/index.tsx
packages/console/src/pages/Mfa/MfaForm/utils.ts
packages/console/src/pages/Mfa/types.ts
packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/libraries/sign-in-experience/mfa.test.ts
packages/core/src/routes/experience/classes/mfa.ts
packages/core/src/routes/interaction/mfa.ts
packages/core/src/routes/interaction/middleware/koa-interaction-sie.ts
packages/core/src/routes/interaction/verifications/mfa-verification.backup-code.test.ts
packages/core/src/routes/interaction/verifications/mfa-verification.test.ts
packages/core/src/routes/interaction/verifications/mfa-verification.ts
packages/experience-legacy/src/__mocks__/logto.tsx
packages/experience/src/__mocks__/logto.tsx
packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/happpy-path.test.ts
packages/integration-tests/src/tests/api/sign-in-experience.test.ts
packages/phrases/src/locales/en/translation/admin-console/mfa.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts

This PR implement New MFA prompt policies to replace "UserControlled":
1. No Prompt
2. Prompt at first registration or first sign in (existing users)
3. Prompt at next sign in
Integration tests & unit tests & local tested.

feat(core,console): new mfa prompt policy

---

packages/console/src/pages/Mfa/MfaForm/index.tsx

Close "require MFA" switch when the policy settings are disabled.
Local tested.

fix(console): auto close mfa switch

---

packages/phrases/src/locales/en/translation/admin-console/mfa.ts

refactor(phrases): update mfa prompt selection text

---

packages/connectors/connector-feishu-web/README.md
packages/connectors/connector-tencent-sms/README.md

Update connector readme translations.
- Feishu
- Tencent SMS
Locally

chore: update translation of connector readmes

---

packages/console/src/components/PlanUsage/PlanUsageCard/index.module.scss
packages/console/src/components/PlanUsage/PlanUsageCard/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/TokenLimitExceededNotification/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts

Add token usage banner notification.

feat(console): add token usage notification banner

---

packages/console/src/pages/Mfa/MfaForm/index.tsx

Fix MFA form `isMandatory` reset: use `setValue` instead to prevent losing "dirty" state.
Local tested.

fix(console): fix mfa form mandatory reset

---

packages/demo-app/src/scss/normalized.scss

update the default font color on demo-app

style(console): update the default font color

---

packages/core/src/middleware/koa-slonik-error-handler.ts

This PR catches all the unexpected unique user identifier DB `UniqueIntegrityConstraintViolationError`, and returns a user-friendly error message. 
test locally

fix(core): handle unexpected user unique identifier error

---

packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/TenantStatusTag.tsx
packages/phrases/src/locales/en/translation/admin-console/tenants.ts

Add the token exceeded tag to the tenant drop-down item.

feat(console): add token exceed tag

---

packages/core/src/oidc/init.ts

Remove token limit dev feature guard

chore(core): remove token limit dev feature guard

---

packages/core/src/saml-applications/SamlApplication/index.test.ts
packages/core/src/saml-applications/SamlApplication/index.ts
packages/core/src/saml-applications/SamlApplication/utils.test.ts
packages/core/src/saml-applications/SamlApplication/utils.ts
packages/core/src/saml-applications/routes/anonymous.ts
packages/core/src/saml-applications/routes/utils.test.ts
packages/core/src/saml-applications/routes/utils.ts

Refactor SAML app utils methods to SamlApplication class, to organize code, resolves LOG-10599 and LOG-10600
Update unit tests to cover basic cases.

refactor(core): build SamlApplication class

---

packages/console/src/components/ItemPreview/ApplicationPreview.tsx
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CreateSecretModal.tsx
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/index.tsx
packages/console/src/types/applications.ts
packages/phrases/src/locales/en/translation/admin-console/applications.ts

fix SAML app text display:
1. remove `permission` tab in SAML app details page
2. SAML app details page header "Third-party app" -> "SAML App"
3. Applications listing page, app preview of SAML applications, "Third-party app" -> "SAML App"
4. Use empty string as `name` to avoid showing placeholder of success toast of creating new SAML app secret

chore(console): fix SAML app text display

---

packages/console/src/consts/logs.ts
packages/core/src/saml-applications/routes/anonymous.ts
packages/schemas/src/types/log/index.ts
packages/schemas/src/types/log/saml.ts

add audit logs for SAML apps (resolves LOG-10376 and LOG-10377), on:
1. OIDC callback proxy endpoint
2. SAML auth request endpoints
N/A

feat(core): add SAML app audit logs

---

packages/core/src/saml-applications/SamlApplication/index.test.ts
packages/core/src/saml-applications/SamlApplication/index.ts
packages/core/src/saml-applications/queries/sessions.ts
packages/core/src/saml-applications/routes/anonymous.ts
packages/phrases/src/locales/en/errors/application.ts

add state/redirect URI validate on SP init SAML SSO callback endpoint (resolves LOG-10593)
Update test cases.

feat(core): add state/redirect URI validate on SP init SAML SSO callback endpoint

---

packages/console/package.json
packages/console/src/consts/quota-item-phrases.ts
packages/console/src/consts/tenants.ts
packages/core/package.json
packages/core/src/__mocks__/cloud-connection.ts
packages/core/src/saml-applications/routes/index.ts
packages/core/src/utils/subscription/types.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
pnpm-lock.yaml

add SAML app quota guard to core (API), resolves LOG-10710
N/A

refactor(core): add SAML app quota guard

---

.github/workflows/integration-test.yml
packages/console/src/assets/docs/guides/saml-idp/index.ts
packages/console/src/components/Guide/hooks.ts
packages/console/src/types/applications.ts
packages/phrases/src/locales/en/translation/admin-console/guide.ts

1. add SAML app flow (resolves LOG-10700).
2. also updated integration test CI to fix [the failure](https://github.com/logto-io/logto/actions/runs/12803809008/job/35697654974?pr=6944) by locking Ubuntu env version

feat(console): add SAML app flow

---

packages/console/src/components/Guide/hooks.ts
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx

hide entrance for creating SAML apps, the SAML app creation is available only when: (this resolves LOG-10709)
1. Cloud env
2. dev feature enabled
3. `quota.samlApplicationsLimit` is not 0

feat(console): hide entrance for creating SAML apps

---

packages/core/src/saml-applications/SamlApplication/index.test.ts
packages/core/src/saml-applications/SamlApplication/index.ts
packages/core/src/saml-applications/SamlApplication/utils.ts

fix SAML attributes data (resolves LOG-10717)
Before this change, attribute data is not properly attached to SAML response.
Add unit test cases.

fix(core): fix SAML attributes data

---

packages/core/src/saml-applications/SamlApplication/index.ts

fix SAML validator setup
SAML validator should be set after we create SAML IdP/SP instance, previous implementation did not set SAML scheme validator properly.

fix(core): fix SAML validator setup

---

packages/core/src/queries/saml-application/index.ts
packages/core/src/routes/saml-application/anonymous.ts

update error message.
Add more detailed error message, resolves LOG-10737

chore: update error message

---

.changeset/wicked-kids-rescue.md

Bump version of the dependency "nanoid" in `@logto/shared` package, preparing for a patch release.
N/A

chore: add changeset to patch @logto/shared

---

packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.tsx
packages/core/src/libraries/saml-application/saml-applications.ts
packages/integration-tests/src/tests/api/application/saml-application.test.ts

fix SAML app attribute mapping issues:
1. fix SAML attribute mapping removal save does not take affect issue (resolves LOG-10736)
2. fix SAML attribute mapping selector dropdown empty item issue (resolves LOG-10734)
3. fix SAML attribute mapping search item duplicated issue (resolves LOG-10735)

fix(console,core): fix SAML app attribute mapping issues

---

packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.tsx

update SAML app attribute mapping doc link.
N/A

chore: update SAML app attribute mapping doc link

---

packages/console/src/assets/docs/guides/saml-idp/index.ts
packages/console/src/components/Guide/GuideCard/index.tsx

remove SAML app guide card feature guard.
N/A

chore: remove SAML app guide card feature guard

---

.changeset/loud-trees-check.md
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.tsx
packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
packages/toolkit/core-kit/src/openid.ts

Add core-kit changeset to show latest changes.
N/A
~~- [] necessary TSDoc comments~~

chore: add core-kit changeset

---

packages/core/src/middleware/koa-quota-guard.ts
packages/core/src/routes/organization-role/index.ts
packages/core/src/routes/organization-scope/index.ts

1. remove unnecessary quota guard and usage report (org role/scope)
2. make subscription usage report to be synchronous for better performance.
N/A

refactor: remove unnecessary quota guard and usage report

---

packages/core/src/routes/saml-application/anonymous.ts
packages/core/src/routes/saml-application/utils.ts
packages/core/src/saml-application/SamlApplication/consts.ts
packages/core/src/saml-application/SamlApplication/index.test.ts
packages/core/src/saml-application/SamlApplication/index.ts

1. Add AuthnStatement for SAML assertion response.
2. Refactor AuthnAttributes fallback logic to align with SSOT scheme.
3. Refactor SAML application `state` verification and parsing logic to be a separated util methods.
Tested locally with [SAML test tool](https://sptest.iamshowcase.com/instructions#spinit).

fix(core): add AuthnStatement for SAML assertion response

---

.changeset/rich-seas-burn.md
packages/tunnel/CHANGELOG.md
packages/tunnel/package.json

-   6144149bb: disallow zstd compression to fix potential garbled text response

release(tunnel): release tunnel cli 0.2.6

---

.changeset/twelve-glasses-dance.md
packages/console/src/consts/external-links.ts

Update an incorrect documentation link in Console.
Locally

fix(console): update docs link

---

packages/experience/src/hooks/use-send-verification-code.ts
packages/experience/src/pages/SignInPassword/PasswordForm/VerificationCodeLink.tsx

Add an on-submit lock to the verification code link to prevent multiple requests from being triggered.
test locally.

fix(experience): add loading status

---

packages/schemas/alterations/next-1740982044-add-one-time-tokens-table.ts
packages/schemas/src/foundations/jsonb-types/index.ts
packages/schemas/src/foundations/jsonb-types/one-time-tokens.ts
packages/schemas/tables/one_time_tokens.sql

Add `one_time_tokens` table, we will add APIs for this table later to implement magic link feature. (resolves LOG-10867)
We are not adding session enforcement for the magic link scenario for now since by product researching, almost all products allow cross-device use of the magic link. And current table design is easy to add same-device/session enforcement.
New table and alteration should be covered by CI.

feat: add `one_time_tokens` table

---

packages/core/src/queries/one-time-tokens.ts
packages/core/src/routes/init.ts
packages/core/src/routes/one-time-tokens.openapi.json
packages/core/src/routes/one-time-tokens.ts
packages/core/src/routes/swagger/utils/documents.ts
packages/core/src/routes/swagger/utils/general.ts
packages/core/src/tenants/Queries.ts
packages/integration-tests/src/api/one-time-token.ts
packages/integration-tests/src/tests/api/one-time-tokens.test.ts

Add `POST /one-time-tokens` API. (resolves LOG-10868)
Should be covered by integration tests.

feat: add POST /one-time-tokens API

---

packages/console/src/pages/Mfa/MfaForm/index.tsx
packages/console/src/pages/Mfa/MfaForm/utils.ts
packages/console/src/pages/Mfa/types.ts
packages/phrases/src/locales/en/translation/admin-console/mfa.ts

Add the organization-required MFA prompt policy settings to the admin console. 
This feature is only available for the cloud admin tenant. 
test locally

feat(console): add organizationRequiredMfaPolicy config

---

packages/phrases/src/locales/ar/errors/organization.ts
packages/phrases/src/locales/de/errors/organization.ts
packages/phrases/src/locales/es/errors/organization.ts
packages/phrases/src/locales/fr/errors/organization.ts
packages/phrases/src/locales/it/errors/organization.ts
packages/phrases/src/locales/ja/errors/organization.ts
packages/phrases/src/locales/ko/errors/organization.ts
packages/phrases/src/locales/pl-pl/errors/organization.ts
packages/phrases/src/locales/pt-br/errors/organization.ts
packages/phrases/src/locales/pt-pt/errors/organization.ts
packages/phrases/src/locales/ru/errors/organization.ts
packages/phrases/src/locales/tr-tr/errors/organization.ts
packages/phrases/src/locales/zh-cn/errors/organization.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-hk/errors/organization.ts
packages/phrases/src/locales/zh-tw/errors/organization.ts

The translation CLI has been updated recently, I ran the CLI and found some untranslated scripts. Thus, sync and update these i18n phrases.
N/A

chore: sync and update translations

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/experience-legacy/src/__mocks__/logto.tsx
packages/experience/src/__mocks__/logto.tsx
packages/schemas/alterations/next-1741240284-add-captcha-policy.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql

Add new field to sign in experience: captcha policy
CI

feat(schemas): add captcha policy field

---

packages/schemas/alterations/next-1741572426-add-captcha-providers.ts
packages/schemas/src/foundations/jsonb-types/captcha.ts
packages/schemas/src/foundations/jsonb-types/index.ts
packages/schemas/tables/captcha_providers.sql

Add new table "captcha_providers".
CI

feat(schemas): add captcha provider table

---

.dockerignore

ignore readme assets in docker build
N/A

chore: ignore readme assets in docker build

---

packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/verification-routes/verification-code.openapi.json
packages/integration-tests/src/tests/api/experience-api/verifications/verification-code.test.ts

chore: fix typos

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/profile.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/profile-routes.ts
packages/core/src/routes/experience/types.ts

Refactor `setProfileByVerificationId` making it more flexible.

refactor(core): refactor setProfileByVerificationId

---

packages/console/src/components/Region/index.tsx
packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.tsx

support showing unknown region info in console, instead of crash.
tested with a new region that not included in the console enum

refactor(console): support unknown region

---

Dockerfile

Remove embedded pricing url for docker build since it's not needed in the opensource project.
Added in the cloud repo: https://github.com/logto-io/cloud/pull/1153
N/A

chore: remove embedded pricing url for docker build

---

packages/console/src/pages/Security/RequiredFlows/index.module.scss
packages/console/src/pages/Security/RequiredFlows/index.tsx
packages/console/src/pages/Security/index.module.scss
packages/console/src/pages/Security/index.tsx
packages/phrases/src/locales/en/translation/admin-console/security.ts

feat(console): captcha required flows

---

packages/core/src/oidc/utils.test.ts
packages/core/src/oidc/utils.ts
packages/schemas/src/consts/oidc.ts

Whitelist `one_time_token` param in OIDC redirect.
Locally tested

refactor: whitelist one_time_token param in oidc redirection

---

packages/console/src/pages/CaptchaDetails/CaptchaContent/index.tsx
packages/console/src/pages/Security/CaptchaFormFields/index.tsx
packages/console/src/pages/Security/CreateCaptchaForm/constants.ts
packages/console/src/pages/Security/CreateCaptchaForm/types.ts
packages/console/src/pages/Security/Guide/index.tsx
packages/console/src/pages/Security/types.tsx
packages/integration-tests/src/tests/api/captcha-provider.test.ts
packages/phrases/src/locales/en/translation/admin-console/security.ts
packages/schemas/src/foundations/jsonb-types/captcha.ts

Add reCAPTCHA enterprise to Console.

feat(console): add recaptcha enterprise

---

packages/console/src/components/UnsavedChangesAlertModal/index.tsx

Prevent unsaved modal from flashing when navigating within parent path.
Test locally.

fix(console): prevent unsaved modal from flashing when navigating within parent path

---

packages/console/src/components/BillInfo/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx

fix visibility of Stripe customer portal
The Stripe customer portal should be visible for all paid tenant users. Previously, when created subscription on Stripe dashboard and the invoices are not created, user can not access customer portal, which is unexpected.
Tested locally with manually created Stripe subscription thru dashboard.

fix(console): fix visibility of Stripe customer portal

---

.changeset/bright-pans-deny.md
packages/connectors/connector-azuread/README.md
packages/connectors/connector-azuread/src/constant.ts
packages/connectors/connector-azuread/src/index.ts
packages/connectors/connector-azuread/src/types.ts

support `scopes` field to MS Azure AD connector
N/A

chore: add scopes field to MS Azure AD connector

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpForm.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/SignUpIdentifierItem.module.scss
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/SignUpIdentifierItem.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.module.scss
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.module.scss
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/utils.ts
packages/console/src/pages/SignInExperience/PageContent/constants.ts
packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
packages/console/src/pages/SignInExperience/types.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts

update SIE page to support multi sign-up identifiers
test locally

feat(console): add multi sign-up identifiers

---

packages/core/src/__mocks__/captcha.ts
packages/core/src/__mocks__/index.ts
packages/core/src/libraries/sign-in-experience/index.test.ts
packages/core/src/libraries/sign-in-experience/index.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/libraries/captcha-validator.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/well-known/index.ts
packages/core/src/routes/well-known/well-known.experience.ts
packages/core/src/routes/well-known/well-known.test.ts
packages/integration-tests/src/helpers/captcha.ts
packages/integration-tests/src/helpers/client.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts
packages/phrases/src/locales/en/errors/session.ts
packages/schemas/src/types/interactions.ts
packages/schemas/src/types/sign-in-experience.ts

Add captcha support to interaction:
1. Accept optional param "captchaToken" when creating interaction, if provided, perform check and record the result in storage.
2. Check captcha requirement before interaction submit.
TODO:
1. Refactor the `captchaPolicy` to a single swich, per offline discussion, we are not going to provider detailed configuration.
2. Skip captcha check for social / sso and similar flows.

feat(core): check captcha token when creating interaction

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/integration-tests/src/helpers/admin-tenant.ts
packages/integration-tests/src/helpers/client.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/api/email-templates/experience-api.test.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/happpy-path.test.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/organization-required-mfa.test.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/sad-path.test.ts
packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts
packages/integration-tests/src/tests/api/experience-api/interaction.test.ts
packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
packages/integration-tests/src/tests/api/experience-api/profile/reset-password.test.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/enterprise-sso.test.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/one-time-token.test.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/username-password.test.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.experience.test.ts

For register flow, we should guard captcha before creating any user.
This PR also fixes the type changing in https://github.com/logto-io/logto/pull/7184

feat(core): guard captcha before creating users

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.module.scss
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.tsx

Add a disabled status of conflicted sign-up identifier options instead of directly filtering them out. 
test locally

fix(console): disable conflicted sign-up identifiers

---

packages/core/src/libraries/quota.ts

enable quota guard for cloud integration test
By Cloud integration tests.

chore: enable quota guard for cloud integration test

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/index.tsx

Added new signUpDiff modal to support multi sign-up identifier changes
test locally

feat(console): add new signUpDiff modal

---

packages/core/src/libraries/user.ts
packages/core/src/queries/organization/index.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/libraries/provision-library.ts
packages/core/src/routes/experience/classes/verifications/one-time-token-verification.ts

Provision new users to organizations that assigned with the one-time token context.
Local dev testing

refactor(core): provision user to organizations upon successful one-time token auth

---

packages/console/src/components/CreateConnectorForm/index.tsx

Show Vonage connector in Console, it is ready now.
N/A

fix(console): show vonage connector

---

packages/core/src/middleware/koa-security-headers.ts

Add security headers for Cloudflare Turnstile scripts.
Local tested.

feat(core): add security headers for captcha

---

packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
packages/core/src/routes/experience/verification-routes/social-verification.ts
packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts

Skip CAPTCHA verification for social and sso, because it is the provier's responsibility to perform similar protection.

feat(core): skip captcha for social and sso

---

packages/experience/src/apis/experience/index.ts
packages/experience/src/apis/experience/interaction.ts
packages/experience/src/apis/utils.ts
packages/experience/src/components/IdentifierRegisterForm/index.test.tsx
packages/experience/src/components/IdentifierRegisterForm/index.tsx
packages/experience/src/components/IdentifierRegisterForm/use-on-submit.ts
packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
packages/experience/src/components/IdentifierSignInForm/index.test.tsx
packages/experience/src/components/Turnstile/index.module.scss
packages/experience/src/components/Turnstile/index.tsx
packages/experience/src/containers/CaptchaBox/index.tsx
packages/experience/src/hooks/use-captcha.ts
packages/experience/src/hooks/use-send-verification-code.ts
packages/experience/src/pages/Continue/SetEmailOrPhone/index.test.tsx
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
packages/experience/src/pages/SignInPassword/PasswordForm/index.test.tsx

Render CAPTCHA(Turnstile) in register form.

feat(experience): render captcha in register form

---

packages/integration-tests/src/tests/console/backchannel-logout.test.ts

Increase wait time to 500ms for backchannel logout test, to ensure proper redirect processing.

test: increase wait time for backchannel logout test

---

packages/integration-tests/src/tests/console/backchannel-logout.test.ts
packages/integration-tests/src/tests/console/bootstrap.test.ts

Improve CI test stability by increasing waiting timeout.
See CI status in this PR

chore(test): improve CI test stability

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts
packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts

Check if CAPTCHA is verified before sending a verification code.
Integrationt ests.

feat(core): check captcha before sending verification code

---

packages/core/src/routes/experience/classes/libraries/captcha-validator.ts

Fix reCAPTCHA enterprise verification API call.
Tested locally with real token.

fix(core): fix recaptcha verification

---

packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
packages/experience/src/containers/VerificationCode/use-sign-in-with-exist-identifier-confirm-modal.ts

Fix the interaction event in the continue sign-in flow error callback.
test locally

fix(experience): fix the interaction event in continue sign-in

---

packages/console/src/pages/Security/CreateCaptchaForm/constants.ts

Add Turnstile README in create guide.

fix(console): add turnstile readme

---

packages/console/src/pages/Security/CreateCaptchaForm/constants.ts

Add reCAPTCHA enterprise README in guide.

fix(console): add recaptcha readme

---

packages/integration-tests/src/tests/api/application/saml-application.test.ts

remove dev feature test for SAML app
CI.

chore: remove dev feature test for SAML app

---

.changeset/hungry-elephants-look.md
packages/core/src/utils/password.ts
packages/core/src/workers/tasks/argon2i.ts

Remove password encryption worker dev guard. Add change set.

chore(core): remove password encryption worker dev guard

---

packages/phrases/src/locales/ar/translation/admin-console/security.ts
packages/phrases/src/locales/de/translation/admin-console/security.ts
packages/phrases/src/locales/es/translation/admin-console/security.ts
packages/phrases/src/locales/fr/translation/admin-console/security.ts
packages/phrases/src/locales/it/translation/admin-console/security.ts
packages/phrases/src/locales/ja/translation/admin-console/security.ts
packages/phrases/src/locales/ko/translation/admin-console/security.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/security.ts
packages/phrases/src/locales/pt-br/translation/admin-console/security.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/security.ts
packages/phrases/src/locales/ru/translation/admin-console/security.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/security.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/security.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/security.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/security.ts

chore(phrases): sync password policy phrases

---

packages/console/src/pages/Security/Captcha/CaptchaFormFields/index.tsx

Add required tag to captcha create form fields.

fix(console): add required tag to captcha form guide

---

packages/console/src/pages/Security/Captcha/CreateCaptchaForm/index.tsx

Fix the route path when click "change captcha provider", the original structure has been changed in #7258 
Local tested

fix(console): fix change captcha guide route path

---

packages/core/src/middleware/koa-spa-proxy.test.ts

chore(core): clean up legacy test cases

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/experience/src/__mocks__/logto.tsx
packages/schemas/alterations/next-1744013256-add-sentinel-policy-column-to-sie-table.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql

Add sentinel polity to SIE settings。

feat(schemas): add sentinel policy

---

packages/console/src/ds-components/CopyToClipboard/index.module.scss

Before:
After:
See summary section

style(console): add paddings to identifier information

---

packages/core/src/libraries/sign-in-experience/index.ts

optimize public captcha config fetching, https://github.com/logto-io/logto/pull/7176#discussion_r2013274705
N/A

refactor(core): optimize public captcha config fetching

---

packages/console/src/consts/logs.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/libraries/captcha-validator.ts
packages/schemas/src/types/log/interaction.ts

Add audit log of CAPTCHA verification.

feat(core,console): add captcha log

---

packages/console/package.json
packages/console/src/components/FormCard/index.tsx
packages/console/src/components/Region/assets/jp.svg
packages/console/src/components/Region/index.tsx
packages/console/src/consts/quota-item-phrases.ts
packages/console/src/consts/tenants.ts
packages/console/src/pages/Security/Captcha/UpsellNotice/index.module.scss
packages/console/src/pages/Security/Captcha/UpsellNotice/index.tsx
packages/console/src/pages/Security/Captcha/index.module.scss
packages/console/src/pages/Security/Captcha/index.tsx
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts
pnpm-lock.yaml

Add paywall to security's bot protection.

feat(console): add paywall to security

---

packages/experience/src/Providers/CaptchaContextProvider/index.tsx

Clear dom element before rendering captcha widget, to prevent multiple instance.
Local tested.

fix(experience): prevent multiple captcha widget

---

packages/console/src/pages/Security/Captcha/CreateCaptchaForm/constants.ts

Update README of Turnstile: users can customize the widget mode freely.
Local preview.

fix(console): update readme of turnstile widget mode

---

packages/console/src/pages/Security/General/SentinelUnlockModal/index.tsx
packages/console/src/pages/Security/index.tsx
packages/phrases/src/locales/ar/translation/admin-console/security.ts
packages/phrases/src/locales/de/translation/admin-console/security.ts
packages/phrases/src/locales/en/translation/admin-console/security.ts
packages/phrases/src/locales/es/translation/admin-console/security.ts
packages/phrases/src/locales/fr/translation/admin-console/security.ts
packages/phrases/src/locales/it/translation/admin-console/security.ts
packages/phrases/src/locales/ja/translation/admin-console/security.ts
packages/phrases/src/locales/ko/translation/admin-console/security.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/security.ts
packages/phrases/src/locales/pt-br/translation/admin-console/security.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/security.ts
packages/phrases/src/locales/ru/translation/admin-console/security.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/security.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/security.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/security.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/security.ts

This PR includes the following updates
1. Change the tab order of the security page.
2.  Update the sentinel unlock modal form
- Always enabled the unlock submit button
- Display form error if the identifier's input value is empty
test locally

feat(console): update security page

---

.github/workflows/close-stale.yml

update comment to reflect more accurate info.
n/a

ci: update stale tag days

---

packages/experience/src/components/PasswordSignInForm/index.tsx
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx

Render CAPTCHA box near the submit button.
Local preview.

fix(experience): render captchabox near submit button

---

packages/core/src/routes/sign-in-experience/index.ts

Add dev guard for sentinel policy settings

feat(core): add dev guard for sentinel policy

---

packages/console/src/consts/env.ts
packages/console/src/pages/TenantSettings/Subscription/ConsoleEmbeddedPricing/index.tsx

chore: provide default console embedded pricing url as a fallback url
Test locally.

chore(console): provide default console embedded pricing url

---

packages/experience/src/Providers/CaptchaContextProvider/index.tsx
packages/experience/src/include.d/global.d.ts
packages/phrases-experience/src/locales/ar/error/index.ts
packages/phrases-experience/src/locales/de/error/index.ts
packages/phrases-experience/src/locales/en/error/index.ts
packages/phrases-experience/src/locales/es/error/index.ts
packages/phrases-experience/src/locales/fr/error/index.ts
packages/phrases-experience/src/locales/it/error/index.ts
packages/phrases-experience/src/locales/ja/error/index.ts
packages/phrases-experience/src/locales/ko/error/index.ts
packages/phrases-experience/src/locales/pl-pl/error/index.ts
packages/phrases-experience/src/locales/pt-br/error/index.ts
packages/phrases-experience/src/locales/pt-pt/error/index.ts
packages/phrases-experience/src/locales/ru/error/index.ts
packages/phrases-experience/src/locales/tr-tr/error/index.ts
packages/phrases-experience/src/locales/zh-cn/error/index.ts
packages/phrases-experience/src/locales/zh-hk/error/index.ts
packages/phrases-experience/src/locales/zh-tw/error/index.ts

Handle CPATCHA front-end error, such as invalid site key, show a toast message on this case.
Local tested.

fix(experience): handle captcha front-end error

---

packages/core/src/routes/captcha-provider/index.ts

Per discussion, remove the auto enabl of cpatcha policy.
Local tested.

fix(core): remove auto captcha enable

---

packages/console/src/ds-components/Button/index.module.scss

fix disabled button icon color

style(console): fix disabled button icon color

---

packages/console/src/pages/Security/Captcha/index.module.scss

Fix CAPTCHA from bottom action position.

style(console): fix captcha form bottom action position

---

packages/schemas/src/types/system.ts

Slean up experience feature flag system key definitions.

chore(schemas): clean up experience feature flag key

---

packages/console/src/pages/Security/Captcha/CaptchaFormFields/index.tsx
packages/console/src/pages/Security/Captcha/CreateCaptchaForm/constants.ts
packages/console/src/pages/Security/Captcha/CreateCaptchaForm/types.ts

Add placeholder to CAPTCHA form fields.
Local preview.

fix(console): add placeholder to captcha form

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/console/src/consts/quota-item-phrases.ts
packages/console/src/consts/tenants.ts
packages/core/package.json
packages/core/src/__mocks__/cloud-connection.ts
packages/core/src/libraries/quota.ts
packages/core/src/queries/tenant-usage/index.ts
packages/core/src/queries/tenant-usage/types.ts
packages/core/src/routes/sign-in-experience/index.ts
packages/core/src/utils/subscription/types.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-item.ts
pnpm-lock.yaml

Add security features, quota guard.
- free tenant: should not be able to enable security features
- dev tenant: should be able to enabled security features
- pro & enterprise tenant: should be able to enable security features with add-on report.
test locally

feat(core): add security features quota guard

---

packages/console/src/consts/plan-quotas.ts

Remove the unused `isCaptchaEnabled` quota key, unblock publising.

chore: remove captcha quota key

---

packages/experience/src/Providers/CaptchaContextProvider/index.tsx

Add loading yer while executing CAPTCHA token challenge, this can block user interactions.
Local tested.

fix(experience): add loading layer while executing captcha

---

packages/experience/src/components/IdentifierRegisterForm/index.tsx
packages/experience/src/components/IdentifierRegisterForm/use-on-submit.ts
packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
packages/experience/src/components/PasswordSignInForm/index.tsx
packages/experience/src/hooks/use-password-sign-in.ts
packages/experience/src/hooks/use-send-verification-code.ts
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx

Updated the `IdentifierRegisterForm`, `PasswordSignInForm`, `ForgotPasswordForm`, and related hooks to eliminate the need for a captcha token in form submissions. The captcha execution is now handled within the registration and sign-in hooks, streamlining the form logic.
Local tested with all flows.

refactor(experience): handle captcha in hooks

---

packages/console/src/components/Topbar/InkeepAskAi/index.tsx
packages/console/src/components/Topbar/index.tsx
packages/console/vite.config.ts

Optimize Console build js chunks, by merging major inkeep independencies into a dedicated js chunk. Since the uncompressed chunk size is greater than 500K.
Everything still works!

chore(console): optimize console build chunks

---

packages/console/src/hooks/use-console-routes/routes/security.tsx

fix(console): fix security page default tab

---

packages/console/src/consts/external-links.ts

Update the latest security docs link.

fix(console): update security docs link

---

packages/console/src/pages/CaptchaDetails/CaptchaContent/index.tsx
packages/console/src/pages/Security/Captcha/Guide/index.tsx

Update descriptions in CAPTCHA page.

fix(console): update captcha card description

---

.changeset/plenty-roses-rhyme.md

Add changeset of CAPTCHA feature.
N/A

chore: add changeset of captcha

---

packages/core/src/libraries/sign-in-experience/index.ts
packages/core/src/routes/captcha-provider/index.openapi.json
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/init.ts
packages/core/src/routes/swagger/utils/documents.ts
packages/core/src/routes/well-known/index.ts
packages/core/src/routes/well-known/well-known.experience.ts
packages/experience/src/Providers/CaptchaContextProvider/index.tsx
packages/integration-tests/src/tests/api/captcha-provider.test.ts
packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/one-time-token.test.ts

Remove CAPTCHA feature guard in core and experience.

refactor(core,experience): remove captcha dev feature guard

---

packages/core/src/routes/logto-config/jwt-customizer.ts

enable Cloudflare Worker deploy/delete when doing Cloud integration tests
Will be test with Cloud integration test CI.
See https://github.com/logto-io/cloud/pull/1220.

chore: enable Cloudflare Worker deploy/delete when doing Cloud integration tests

---

packages/experience/src/Providers/CaptchaContextProvider/index.tsx

This reverts commit f9f1110962d57a01a1bc9008e68b33e87d267b26.
Revert the change of loading layer, because this layer will block the interaction of the CAPTCHA widget

Revert "fix(experience): add loading layer while executing captcha"

---

packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx

Remove beta tag from the "Bring your UI" component in Sign-in Experience page.
Local dev test

chore(console): remove beta tag from bring your ui

---

packages/console/src/components/Topbar/index.tsx

Remove dev feature guard from Inkeep AI bot
N/A

chore(console): remove dev feature guard from inkeep ai bot

---

packages/phrases-experience/src/locales/uk-ua/error/index.ts

Fixed mistake translate in captcha_verification_failed key
No need

fix: uk-ua mistake translate captcha_verification_failed

---

packages/cli/src/commands/database/seed/tables.ts
packages/console/src/assets/docs/guides/web-dotnet-core-mvc/fragments/_sign-in-and-sign-out-flows.mdx

fix: typos

---

.changeset/swift-glasses-drive.md
packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
packages/experience/src/components/IdentifierSignInForm/index.tsx
packages/experience/src/hooks/use-password-sign-in.ts
packages/experience/src/hooks/use-send-verification-code.ts

fix(experience): captcha not show on indetifier singin form
fix captcha not show on indetifier singin form
Tested on my instance.

fix(experience): captcha not show on indetifier singin form

---

packages/core/src/routes/account/email-and-phone.ts
packages/integration-tests/src/tests/api/account/email-and-phone.test.ts

Add email blocklist validation to the account API.

feat(core): add email blocklist validation to account API

---

packages/core/src/libraries/sign-in-experience/email-blocklist-policy.test.ts
packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
packages/core/src/queries/tenant-usage/index.ts
packages/core/src/routes/sign-in-experience/index.ts

Add email blocklist policy, paywall guard.
test locally. Unit test added.

feat(core): add email blocklist policy paywall guard

---

packages/console/src/pages/Security/Blocklist/BlocklistForm/index.tsx
packages/console/src/pages/Security/Captcha/index.tsx
packages/console/src/pages/Security/General/GeneralForm/index.tsx

Manually trigger the usage update on security feature updates. So we may keep the tenant usage page data up to date.
test locally

fix(console): manual trigger usage update

---

packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts

Add email blocked error handler to SSO registration
test locally

fix(experience): add email blocked error handler

---

packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts
packages/experience/src/hooks/use-send-verification-code.ts
packages/experience/src/pages/Continue/IdentifierProfileForm/index.tsx
packages/integration-tests/src/tests/api/experience-api/register-interaction/email-blocklist.test.ts

Enhance the user experience by pre-validating the email against the email blocklist policy before sending the verification code on user registration.
Add email blocklist validation to the Experience API `POST /verification/verification-code` endpoint.
If the interaction event is `Register`, the system will now pre-validate the email address before creating an email verification record.
Additional fixes and improvements
- Improved error messaging: Updated the error message shown when users attempt to enable unsupported email blocklist features.
- Optimized validation order: Moved the disposable email domain validation to the end of the validation chain. Since it requires an external request, this change avoids unnecessary API calls if the email already fails earlier blocklist validations, …

feat(core,experience): pre validate email blocklist

---

.changeset/perfect-phones-relax.md
packages/console/src/pages/CaptchaDetails/index.tsx
packages/console/src/pages/Security/Captcha/EnableCaptcha/index.tsx
packages/console/src/pages/Security/Captcha/index.tsx

Always show enable CAPTCHA toggle, even if there is no CAPTCHA provider, the toggle will be shown but disabled.
Also the back link of the captcha details page is changed to `/security/captcha`.
Local tested.

fix(console): update captcha backlink and always show captcha toggle

---

.changeset/honest-news-rush.md
.changeset/soft-eggs-sell.md
packages/console/src/hooks/use-console-routes/routes/security.tsx
packages/console/src/pages/Security/index.tsx
packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
packages/core/src/routes/account/email-and-phone.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/core/src/routes/sign-in-experience/index.openapi.json
packages/integration-tests/src/tests/api/account/email-and-phone.test.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/email-blocklist.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts

Remove dev feature guard, enabled email blocklist

feat(core): remove dev feature guard for email blocklist

---

.changeset/perfect-phones-relax.md
packages/console/src/pages/CaptchaDetails/index.tsx
packages/console/src/pages/Security/Captcha/EnableCaptcha/index.tsx
packages/console/src/pages/Security/Captcha/index.tsx

Revert "fix(console): update captcha backlink and always show captcha toggle"

---

packages/console/package.json
packages/console/src/components/MfaFactorName/index.module.scss
packages/console/src/components/MfaFactorName/index.tsx
packages/console/src/components/MfaFactorTitle/index.tsx
packages/core/src/utils/user.ts
packages/schemas/src/foundations/jsonb-types/users.ts
packages/schemas/src/types/interactions.ts
packages/schemas/src/types/user.ts
pnpm-lock.yaml

1. Add optional `name` to passkey (webauthn), users can cutomize the name (in nother PR).
2. Add name to Console's passkey display, if name is not present, generate a friendly name from user agent.

feat(console,core,schemas): support multiple passkeys with custom name

---

packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/mfa-verifications.ts
packages/core/src/routes/verification/index.openapi.json

Add the ability to specify name of a passkey, and also update the name.
Local tested.

feat(core): update webauthn passkey name

---

packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/mfa-verifications.ts
packages/phrases/src/locales/en/errors/account-center.ts

Add new endpoint: `GET /my-account/mfa-verifications`.
No integration tests for now because we don't have the ability to add verification in integration tests now.
Local tested.

feat(core): get mfa verifications

---

AWESOME.md

Add [Logto provisioning](https://github.com/LBF38/logto_provisioning) CLI tool to Logto Awesome list.
N/A

chore: update awesome list

---

packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts

Add test cases for PAT granting organization tokens.

feat(test): add test cases for PAT organization token

---

packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
packages/core/src/libraries/session.ts
packages/core/src/oidc/extra-token-claims.ts

Add dev feature guards to hide the custom token claims interaction context from production.

chore(console, core): add dev feature guard

---

.changeset/purple-zebras-deliver.md

add changeset of account api webauthn

chore: add changeset of account api webauthn

---

packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/mfa-verifications.ts
packages/integration-tests/src/api/my-account.ts
packages/integration-tests/src/tests/api/account/mfa.test.ts

Add API to generate TOTP secrets, this can be used to bind new TOTP factor.

feat(core): generate totp secret

---

packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/mfa-verifications.ts
packages/integration-tests/src/api/my-account.ts
packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/api/account/mfa.test.ts

Add backup code via account api.
Integration tests and local tested.

feat(core): add backup code

---

packages/integration-tests/src/helpers/mfa-test.ts
packages/integration-tests/src/tests/api/account/mfa-backup-codes.test.ts
packages/integration-tests/src/tests/api/account/mfa-totp.test.ts
packages/integration-tests/src/tests/api/account/mfa-webauthn.test.ts

Add test cases for backup code. And also refactored the test file, split into 3 files for better code reading.

test: add backup code test cases

---

package.json
pnpm-lock.yaml

Bump transient deps using `pnpm audit --fix`
Locally checked

chore: transient deps audit fix

---

packages/core/src/libraries/social.ts
packages/core/src/routes/account/identities.ts
packages/integration-tests/src/tests/api/account/social.test.ts

Update the user account API to support token storage on linked social identities.
This PR also include the following refactor:
- Add `try..catch` on token encryption flow to ensure any unexpected error does not block user social identities authentication flow. 

feat(core): update social account API

---

packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/index.ts
packages/integration-tests/src/tests/api/account/index.test.ts

Users can now manage custom data via Account API.

feat(core): manage custom data in account api

---

packages/core/src/__mocks__/sso.ts
packages/core/src/routes/sso-connector/index.ts
packages/core/src/routes/sso-connector/type.ts
packages/schemas/alterations/next-1751529530394-add-enable-token-storage-column-to-sso-connectors-table.ts
packages/schemas/tables/sso_connectors.sql

Add `enable_token_storage` config field to SSO connector.

feat(schemas,core): add enable_token_storage field to SSO connector

---

packages/experience/package.json
packages/experience/src/App.tsx
packages/experience/src/components/Dropdown/DropdownItem.module.scss
packages/experience/src/components/Dropdown/DropdownItem.tsx
packages/experience/src/components/Dropdown/index.module.scss
packages/experience/src/components/Dropdown/index.tsx
packages/experience/src/components/InputFields/InputField/index.module.scss
packages/experience/src/components/InputFields/InputField/index.tsx
packages/experience/src/components/InputFields/SelectField/index.module.scss
packages/experience/src/components/InputFields/SelectField/index.tsx
packages/experience/src/components/OverlayScrollbar/index.tsx
packages/experience/src/hooks/use-position.ts
packages/experience/src/scss/_colors.scss
packages/experience/src/scss/overlayscrollbars.scss
packages/experience/src/types/positioning.ts
pnpm-lock.yaml

Add "SelectField" component in experience.

feat(experience): add select field component

---

packages/core/src/routes/experience/classes/libraries/profile-validator.ts
packages/core/src/routes/experience/classes/profile.ts
packages/experience/src/pages/Continue/SetEmailOrPhone/index.tsx
packages/schemas/src/types/interactions.ts

Check custom profile fields fulfillment when submit interaction, and redirect to `/continue/extra` route to collect extra profile info if check fails.

refactor(core): support extra profile validation and redirection

---

packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/index.ts
packages/integration-tests/src/api/my-account.ts
packages/integration-tests/src/tests/api/account/mfa-settings.test.ts

Add results to response body of `PATCH /mfa-settings`.

fix(core): add response data for mfa settings

---

packages/console/src/pages/EnterpriseSsoDetails/Experience/index.tsx

Add the token storage switch field to the enterprise SSO connector details page.
- Only visible to the OIDC SSO connectors. 
test locally

fix(console): add token storage switch to SSO connector

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/console/src/consts/plan-quotas.ts
packages/console/src/consts/quota-item-phrases.ts
packages/console/src/consts/tenants.ts
packages/core/package.json
packages/core/src/__mocks__/cloud-connection.ts
packages/core/src/utils/subscription/types.ts
pnpm-lock.yaml

Update `@logto/cloud` and remove deprecated `captchaEnabled` usage (SKU) key.
Local tested.

chore: remove catpcha enabled key

---

packages/console/src/components/DetailsForm/index.tsx
packages/console/src/components/DetailsPage/DetailsPageHeader/index.module.scss
packages/console/src/components/DetailsPage/DetailsPageHeader/index.tsx
packages/console/src/components/FormCard/index.tsx
packages/console/src/components/SubmitFormChangesActionBar/index.tsx
packages/console/src/ds-components/Checkbox/CheckboxGroup/index.tsx
packages/console/src/ds-components/TextInput/NumericInput.tsx
packages/console/src/ds-components/TextInput/index.module.scss
packages/console/src/ds-components/TextInput/index.tsx

Update design-system components in Console, in order to adapt new requirements in the "Collect user profile" feature.

refactor(console): update console components for new requirements

---

packages/console/src/ds-components/DragDrop/DraggableItem.tsx
packages/console/src/ds-components/Table/TablePlaceholder.tsx
packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/index.module.scss
packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/index.tsx
packages/core/src/queries/custom-profile-fields.ts

- Add drag and drop support to the custom profile fields list view, to change sorting order.
- Fix a bug on the server side that the returning value is not the latest sorting order

feat(console): add drag and drop support to changing profile fields sorting order

---

packages/core/src/libraries/social.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts

Should only store the token response if the access token is present.
test locally

refactor(core): add access token existence check

---

packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/CreateProfileFieldModal/index.tsx

Should not show paywall on profile field creation modal in OSS version
Locally tested using OSS build

fix(console): should not show paywall on profile field creation modal in OSS version

---

packages/core/src/routes/connector/index.ts
packages/core/src/routes/sso-connector/index.ts

Add an environment variable check for SECRET_VAULT_KEK. The token storage feature cannot be enabled if this variable is not set.
test locally

feat(core): add KEK environment variable guard

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/SignInMethodItem.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/utils.ts
packages/console/src/pages/SignInExperience/PageContent/index.tsx
packages/core/src/libraries/sign-in-experience/sign-in.test.ts
packages/core/src/libraries/sign-in-experience/sign-in.ts
packages/core/src/routes/sign-in-experience/index.test.ts
packages/core/src/routes/sign-in-experience/index.ts
packages/integration-tests/src/tests/api/sign-in-experience.test.ts
packages/phrases/src/locales/en/errors/sign-in-experiences.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts

Handle sign in method and Email/Phone MFA conflict: disable verification code sign in method if used by sign in method.
And integration tests for API.

feat(console,core): handle sign in and mfa email phone confict

---

packages/connectors/connector-facebook/README.md
packages/connectors/connector-github/README.md
packages/connectors/connector-google/README.md
packages/connectors/connector-oauth2/README.md
packages/connectors/connector-oidc/README.md
packages/console/src/assets/docs/single-sign-on/google-workspace/README.mdx
packages/console/src/assets/docs/single-sign-on/oidc/README.mdx

Update social connector README:
1. Google
2. Facebook
3. GitHub
4. OIDC social
5. OAuth 2.0 social
Update enterprise connector README:
1. Google Workspace
2. OIDC enterprise

chore: update social and enterprise connector readme for token storage

---

packages/core/src/utils/password.ts

Adding support PBKDF2-hashed passwords on user import
1. Migration user payload:
```javascript
{
username: 'john_doe',
primaryEmail: 'john.doe@example.com',
passwordAlgorithm: 'Legacy',
passwordDigest: JSON.stringify(['pbkdf2Sync', [SALT, "1000", "20", 'sha512', "@"], expected_hashed_value]),
}
```
2. Args(can be changed according to pbkdf2Sync function arguments):
- salt: user defined
- iterations: 1000
- keylen: 20
- digest: sha512
- password: `@` placeholder and expected_hashed_value

feat: adding pbkdf2 support

---

.changeset/add-pbkdf2-support.md

Add changeset of https://github.com/logto-io/logto/pull/7585
N/A

chore: add changeset of pbkdf2

---

packages/console/src/cloud/AppRoutes.tsx

remove dev feature guard for console Google One Tap landing page
N/A

chore(console): remove dev feature guard for console GOT landing page

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/ForgotPasswordMethodEditBox/VerificationMethodItem.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/ForgotPasswordMethodEditBox/index.module.scss
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/ForgotPasswordMethodEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/ForgotPasswordMethodEditBox/utils.ts
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/ForgotPasswordMethodsDiffSection.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/index.tsx
packages/console/src/pages/SignInExperience/PageContent/utils/form.ts
packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts

Implement the frontend setup of forgot password methods.
Local tested.

feat(console): setup forgot password methods

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/helpers.ts
packages/core/src/routes/experience/classes/libraries/mfa-validator.ts
packages/core/src/routes/experience/classes/mfa.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/profile-routes.ts
packages/core/src/routes/experience/types.ts
packages/experience/src/apis/experience/mfa.ts
packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/email-mfa-binding.test.ts

Add API support for setting up email as an MFA factor. The verification function will be implemented later.

feat(core): bind Email MFA

---

packages/experience/src/components/InputFields/InputField/index.tsx
packages/experience/src/components/InputFields/PrimitiveProfileInputField/index.tsx
packages/experience/src/components/InputFields/SelectField/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/AddressSubForm/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/FullnameSubForm/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/index.tsx
packages/phrases-experience/src/locales/ar/input.ts
packages/phrases-experience/src/locales/de/input.ts
packages/phrases-experience/src/locales/en/input.ts
packages/phrases-experience/src/locales/es/input.ts
packages/phrases-experience/src/locales/fr/input.ts
packages/phrases-experience/src/locales/it/input.ts
packages/phrases-experience/src/locales/ja/input.ts
packages/phrases-experience/src/locales/ko/input.ts
packages/phrases-experience/src/locales/pl-pl/input.ts
packages/phrases-experience/src/locales/pt-br/input.ts
packages/phrases-experience/src/locales/pt-pt/input.ts
packages/phrases-experience/src/locales/ru/input.ts
packages/phrases-experience/src/locales/tr-tr/input.ts
packages/phrases-experience/src/locales/uk-ua/input.ts
packages/phrases-experience/src/locales/zh-cn/input.ts
packages/phrases-experience/src/locales/zh-hk/input.ts
packages/phrases-experience/src/locales/zh-tw/input.ts

Introduces a`required` prop to input field components and updates their usage to display an ` (Optional)` suffix for non-required fields.

refactor(experience,phrases): add optional label support to input fields

---

packages/integration-tests/src/tests/api/experience-api/verifications/email-mfa-verification.test.ts

Add integration tests for email MFA verification.

test: add email mfa verification tests

---

packages/experience/src/components/InputFields/DateField/index.module.scss
packages/experience/src/components/InputFields/DateField/index.tsx
packages/experience/src/components/InputFields/PrimitiveProfileInputField/index.tsx

Introduces a new DateField component with custom styling and logic for handling date input formats, enhancing input flexibility and user experience.
https://github.com/user-attachments/assets/f693e90a-a15d-429e-a290-c8456611b44e
https://github.com/user-attachments/assets/409ee583-dd66-4274-82ee-9566a4dcdb0b

feat(experience): add a new DateField component to improve user input experience

---

packages/experience/src/components/InputFields/DateField/index.module.scss
packages/experience/src/components/InputFields/DateField/index.test.tsx
packages/experience/src/components/InputFields/DateField/index.tsx
packages/experience/src/components/InputFields/PrimitiveProfileInputField/index.tsx
packages/experience/src/components/InputFields/SelectField/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/AddressSubForm/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/FullnameSubForm/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/happy-path.test.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/sad-path.test.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/test-helpers.ts

Introduces test coverage for ExtraProfileForm, including validation and submission for all supported custom profile field types.

test: add ExtraProfileForm unit tests for both happy and sad paths

---

packages/console/src/pages/SignInExperience/PageContent/components/ProfileFieldPartSubForm/index.tsx
packages/phrases-experience/src/locales/en/profile.ts

- Update console to hide the "Need localization?" hint from custom data fields
- Update translation in Experience to show `First name` and `Last name` instead of `Given name` and `Family name`, in order to keep it consistent with the translations used in Console.
Locally tested

refactor(console,experience): minor improvements to hints and translation

---

packages/console/src/pages/SignInExperience/PageContent/index.tsx
packages/core/src/libraries/sign-in-experience/index.test.ts
packages/core/src/libraries/sign-in-experience/index.ts
packages/core/src/routes/custom-profile-fields.openapi.json
packages/core/src/routes/experience/experience.openapi.json
packages/core/src/routes/experience/index.ts
packages/core/src/routes/init.ts
packages/core/src/routes/swagger/utils/documents.ts
packages/core/src/routes/swagger/utils/general.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/experience/src/hooks/use-required-profile-error-handler.ts
packages/integration-tests/src/tests/api/custom-profile-fields.test.ts
packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
packages/schemas/src/types/sign-in-experience.ts

Remove dev feature guard of the "Collect user profile" feature, and prepare for a feature release.
CI should pass.

chore: remove dev feature guard of the collect user profile feature

---

packages/core/src/routes/experience/verification-routes/verification-code.ts

In verification code route, require captcha only for unidentified users.
In the flow of Email MFA binding, the user is already identified, which means the captcha check is passed, so no need to verify again.
Local tested.

refactor(core): require captcha only for unidentified users

---

packages/core/src/event-listeners/index.ts

With the latest pricing model, we’ve removed the `refresh_token.saved` event from the token usage report. Refresh tokens are no longer counted toward token usage.
test locally

refactor(core): remove refresh_token token usage report

---

.changeset/tasty-panthers-cross.md
packages/connectors/connector-mock-email/CHANGELOG.md
packages/connectors/connector-mock-email/package.json
packages/connectors/connector-mock-sms/CHANGELOG.md
packages/connectors/connector-mock-sms/package.json
packages/toolkit/connector-kit/CHANGELOG.md
packages/toolkit/connector-kit/package.json

release(connector): release connector kit 4.5.0

---

packages/experience/src/components/InputFields/DateField/index.test.tsx
packages/experience/src/components/InputFields/DateField/index.tsx

- Refine `DateField` input logic so backspace deletes a single character instead of clearing the entire sub-field.
- Update tests
UT and manual test

refactor(experience): improve date field backspace behavior and tests

---

packages/connectors/connector-logto-email/package.json
packages/connectors/connector-logto-email/src/index.ts
packages/console/package.json
packages/core/package.json
pnpm-lock.yaml

Update `@logto/cloud` package to support the new email verification type. With that in place we can now drop `@ts-expect-error`.
N/A

chore: update cloud package

---

packages/integration-tests/src/tests/api/organization/organization.test.ts
packages/schemas/alterations/next-1756191517-add-organization-custom-css.ts
packages/schemas/tables/organizations.sql

Add organization level custom CSS support in DB schemas.
Integration tests

feat(schemas): add organization level custom css support

---

packages/connectors/connector-logto-email/package.json
packages/console/package.json
packages/console/src/components/CreateTenantModal/index.module.scss
packages/console/src/components/CreateTenantModal/index.tsx
packages/console/src/components/Region/index.tsx
packages/console/src/onboarding/pages/CreateTenant/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantRegion/index.tsx
packages/core/package.json
pnpm-lock.yaml

- upgrade logto cloud package
- support dynamic region fetching when creating a new tenant
tested locally
- the region list properly shows the result from the api
- show error message when api responds with error

feat(console): support dynamic regions when creating a new tenant

---

.changeset/kind-cherries-yawn.md
packages/connectors/connector-logto-email/src/index.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts
packages/integration-tests/src/__mocks__/connectors-mock.ts
packages/toolkit/connector-kit/src/types/passwordless.ts

Add new verification code type "BindMFA" to align with the expected behavior: When the user is adding Email as new MFA (2FA), the email content should be different with the normal link email.

fix(core,connector): add bind mfa verification code type

---

packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/FeaturedSkuContent/use-featured-sku-content.ts
packages/console/src/components/Guide/GuideCardGroup/index.tsx
packages/console/src/components/PlanUsage/utils.ts
packages/console/src/consts/subscriptions.ts
packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
packages/console/src/pages/Roles/index.tsx
packages/core/src/event-listeners/index.ts
packages/core/src/middleware/koa-security-headers.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/role.ts
packages/core/src/routes/saml-application/index.ts
packages/core/src/utils/subscription/types.ts

Remove new pricing dev feature guards in console and core.

refactor(console,core): remove new pricing dev feature guards

---

packages/console/src/pages/ApplicationDetails/components/Branding/NonThirdPartyBrandingForm.tsx
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/console/src/pages/OrganizationDetails/index.tsx

Add dev features guard for the new org-level branding settings
CI

chore: add dev feature guard for org-level branding settings

---

packages/connectors/connector-aliyun-dm/src/constant.ts
packages/connectors/connector-aliyun-sms/src/constant.ts
packages/connectors/connector-aws-ses/src/constant.ts
packages/connectors/connector-gatewayapi-sms/src/constant.ts
packages/connectors/connector-postmark/src/constant.ts
packages/connectors/connector-sendgrid-email/src/constant.ts
packages/connectors/connector-smsaero/src/constant.ts
packages/connectors/connector-smtp/src/constant.ts
packages/connectors/connector-tencent-sms/src/constant.ts
packages/connectors/connector-twilio-sms/src/constant.ts
packages/connectors/connector-vonage-sms/src/constant.ts
packages/connectors/connector-yunpian-sms/src/constant.ts

Add full usage types to connector's default template value.

fix(connector): add full usage types to default value

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignInDiffSection.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/SignUpDiffSection.tsx

Remove title "sign up" or "sign in" if the diff section is empty.

refactor(console): hide title for empty diff section

---

packages/console/src/pages/SignInExperience/PageContent/index.tsx

skip forgot password migration for empty value
Local tested

fix(console): skip forgot password migration for empty value

---

packages/console/src/pages/Mfa/MfaForm/FactorLabel/index.module.scss
packages/console/src/pages/Mfa/MfaForm/FactorLabel/index.tsx

Add beta tag to Email and Phone SMS MFA factors.

fix(console): add beta tag to email phone MFA

---

packages/console/src/pages/ApplicationDetails/components/Branding/NonThirdPartyBrandingForm.tsx
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/console/src/pages/OrganizationDetails/index.tsx
packages/console/src/pages/OrganizationDetails/utils.ts

Remove dev feature guard and prepare for the formal release of the new org-level branding feature.
Locally

chore(console): remove dev feature guard for org-level branding

---

packages/core/src/routes/experience/classes/mfa.ts

Sort available factors, follow the rule based on security:
WebAuthn -> TOTP -> SMS -> Email -> Backup code
Local tested.

refactor(core): sort available factors

---

packages/core/src/routes/experience/classes/mfa.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/mfa-suggestion.test.ts

This PR fixes an issue with MFA suggestions where users were inappropriately prompted for additional MFA factors when they had already fulfilled MFA requirements through different identifiers than their registration method.
Previously, we suggest additional MFA even when users had sufficient MFA factors from sources other than their registration identifier. For example:
- User registers with email
- User adds phone as MFA factor
- System would still suggest additional MFA despite user having both email and phone factors
Another example:
- User registers with username
- User adds phone as MFA factor
- System would still suggest additional MFA despite user having phone factor already

fix(core): skip MFA suggestion when user has factors from non-reg

---

.changeset/chilled-houses-arrive.md
.changeset/short-balloons-suffer.md

chore: add changeset of email/phone mfa

---

packages/experience/src/components/Button/MfaFactorButton.tsx
packages/phrases-experience/src/locales/ar/mfa.ts
packages/phrases-experience/src/locales/de/mfa.ts
packages/phrases-experience/src/locales/en/mfa.ts
packages/phrases-experience/src/locales/es/mfa.ts
packages/phrases-experience/src/locales/fr/mfa.ts
packages/phrases-experience/src/locales/it/mfa.ts
packages/phrases-experience/src/locales/ja/mfa.ts
packages/phrases-experience/src/locales/ko/mfa.ts
packages/phrases-experience/src/locales/pl-pl/mfa.ts
packages/phrases-experience/src/locales/pt-br/mfa.ts
packages/phrases-experience/src/locales/pt-pt/mfa.ts
packages/phrases-experience/src/locales/ru/mfa.ts
packages/phrases-experience/src/locales/th/mfa.ts
packages/phrases-experience/src/locales/tr-tr/mfa.ts
packages/phrases-experience/src/locales/uk-ua/mfa.ts
packages/phrases-experience/src/locales/zh-cn/mfa.ts
packages/phrases-experience/src/locales/zh-hk/mfa.ts
packages/phrases-experience/src/locales/zh-tw/mfa.ts

Add localized "Send to {{identifier}}" phrases.

feat(experience): improve MFA button text for email/phone verification

---

packages/console/src/consts/logs.ts

deduplicate audit log event titles, they will be used in filter.
N/A

fix(console): deduplicate audit log event titles

---

packages/console/src/pages/TenantSettings/TenantDomainSettings/AddDomainForm/index.tsx
packages/console/src/pages/TenantSettings/TenantDomainSettings/MultipleCustomDomainsFormField/index.tsx
packages/phrases/src/locales/ar/translation/admin-console/domain.ts
packages/phrases/src/locales/de/translation/admin-console/domain.ts
packages/phrases/src/locales/en/translation/admin-console/domain.ts
packages/phrases/src/locales/es/translation/admin-console/domain.ts
packages/phrases/src/locales/fr/translation/admin-console/domain.ts
packages/phrases/src/locales/it/translation/admin-console/domain.ts
packages/phrases/src/locales/ja/translation/admin-console/domain.ts
packages/phrases/src/locales/ko/translation/admin-console/domain.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/domain.ts
packages/phrases/src/locales/pt-br/translation/admin-console/domain.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/domain.ts
packages/phrases/src/locales/ru/translation/admin-console/domain.ts
packages/phrases/src/locales/th/translation/admin-console/domain.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/domain.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/domain.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/domain.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/domain.ts

1. style fix: hide the "Custom domain" label when no value is present
2. rename form field name from "custom domain" to "custom domains"
3. make the add domain button "active" by default even if no content is inputed.
4. update the example domain string to "auth.domain.com" in the error message
Test locally.

style: update add domain input styles and copy

---

.changeset/great-starfishes-help.md

Add changeset for the newly supported auth parameter `ui_locales`
N/A

chore: add changeset for ui_locales feature

---

.changeset/wicked-mails-peel.md
packages/connectors/connector-x/README.md
packages/connectors/connector-x/src/index.test.ts
packages/connectors/connector-x/src/index.ts
packages/connectors/connector-x/src/types.ts

fixed #7809
Add support for the scope `users.email`.
Local tested, email synced from X for new users.

feat(connector): add email support for x connector

---

packages/console/src/components/PlanUsage/PlanUsageCard/index.tsx

The “Learn More” link on the usage card should open in a new tab.
test locally

fix(console): open learn more link in blank target

---

packages/connectors/connector-logto-email/package.json
packages/connectors/connector-logto-email/src/index.ts
packages/console/package.json
packages/console/src/consts/env.ts
packages/console/src/pages/TenantSettings/TenantDomainSettings/index.tsx
packages/console/vite.config.ts
packages/core/package.json
pnpm-lock.yaml

Feature flags now come from tenant response, not build environment.
Test locally.

refactor: read feature flag from tenant response
