logto-io/logto

packages/console/src/pages/OrganizationRoleDetails/index.tsx

- Fix: should mutate 'organization-roles' rather than 'roles' once a org role is deleted
- Refactor: extract organization api endpoint as a const
- Refactor: rename `orgRolesPath` to `organizationRolesPath`
Test locally.

fix(console): mutate org roles once a org role is deleted

---

packages/core/src/libraries/user.ts
packages/core/src/oidc/extra-token-claims.ts
packages/core/src/oidc/grants/refresh-token.test.ts
packages/core/src/oidc/grants/refresh-token.ts
packages/core/src/oidc/init.ts
packages/core/src/oidc/resource.ts
packages/core/src/queries/organization/relations.ts
packages/core/src/queries/user.ts
packages/integration-tests/src/client/index.ts
packages/integration-tests/src/tests/api/oidc/organization-api-resource.test.ts

1. Issue access token with `organization_id` and `resource`.
2. In normal token exchange flow, add all the API resource scopes found in organization roles
Organization roles can now be assigned with normal scopes, as known as "API resource scopes".
And then the users can get scopes for the API resource if he has the organization role that contains the scope.
If `organization_id` is not set, all scopes will be granted, if `organization_id` is set, will narrow down the scopes by only searching for that specific organization.
The new token is like:
```json
{ "aud": "https://myapi.com/", "scope": "read:channels", "organization_id": "xyz" }
```
1. The access token grant request can have both "organization_id" and "resource".
3. The original organization token flow only handle the case that …

feat(core): handle access token with organization api resource

---

packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/hooks.ts
packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/hooks.ts
packages/console/src/pages/TenantSettings/TenantMembers/index.tsx

Update incorrect cloud SWR cache key usages in console. Should use real tenant ID in the cache key, so that the cache can be properly cleared when switching tenants.

chore(console): update incorrect swr cache key usages

---

packages/console/src/containers/ConsoleContent/hooks.ts
packages/console/src/hooks/use-current-tenant-scopes.ts

- Fix a bug that when user is removed from a tenant, they should immediately navigate back to the previous visited tenant or fallback to the page where they can create a new one.
- Should not request tenant scopes from console in OSS version, since that is a cloud API

fix(console): cloud collaboration minor bug fixes

---

.changeset/afraid-stingrays-perform.md
packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/hooks.ts
packages/core/src/queries/organization/index.ts
packages/integration-tests/src/tests/api/organization/organization-invitation.get.test.ts

Fix the bug that invitation emails are not handled case insensitively, which blocks Cloud users from accepting invitations that are sent to their email addresses with a different letter case pattern.
Locally

fix(core,console): invitee emails should be case insensitive

---

packages/integration-tests/src/tests/console/rbac/organization-rbac.test.ts
packages/integration-tests/src/ui-helpers/expect-api-resources.ts
packages/integration-tests/src/ui-helpers/expect-console.ts
packages/integration-tests/src/ui-helpers/expect-organizations.ts

assign permissions to organization role
IT tests passed.

test(console): assign permissions to organization role

---

packages/console/src/pages/Organizations/index.tsx
packages/integration-tests/src/tests/console/organizations.test.ts
packages/integration-tests/src/ui-helpers/expect-organizations.ts

Always display create org button for new version and re-enable organization page tests.
CI passed.

fix(console): always display create org button

---

.changeset/dull-frogs-perform.md
packages/core/src/caches/index.test.ts
packages/core/src/caches/index.ts
packages/core/src/tenants/Tenant.ts

This adds support for redis cluster and additional TLS options
Fixes #5598 
I've tested it against a real redis cluster.

feat(core): add redis cluster and tls extra options support

---

packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx

Update the custom JWT scripts sample code since we updated the execution logic of Azure Functions and Cloudflare workers in [the previous PR](https://github.com/logto-io/cloud/pull/617/files).
Previously, we export `getCustomJwtClaims` method in sample codes; after the previously mentioned change, we do not export `getCustomJwtClaims` from sample code. As a result, no need to declare global function interface in code editor setup.
N/A

chore(console): update custom JWT scripts sample

---

packages/console/src/pages/TenantSettings/TenantMembers/EditMemberModal/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/index.module.scss

Fix the bug that pagination bar is not fully visible, caused by unexpected applying global styles to `<ul />` elements.
Before
After

fix(console): pagination bar should be fully visible

---

packages/console/src/pages/CustomizeJwtDetails/MainContent/MonacoCodeEditor/index.tsx
packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx

Replace ts with js for JWT customizer.
Since CF worker does not support typescript files by default, we need to change the languages from typescript to plan javascript. 
- keep the editor language as typescript since we need all the `d.ts` files successfully compiled
- replace the script file name from `.ts` to `.js` to indicate the current file is a javascript file
-  add allow compile and check javascript option
- fix the js doc annotation for better jshint 
test locally

fix(console): replace ts with js for JWT customizer

---

packages/console/src/components/Guide/ModalFooter/index.module.scss
packages/console/src/components/Guide/index.module.scss
packages/console/src/ds-components/Button/index.module.scss
packages/console/src/ds-components/CodeEditor/index.module.scss
packages/console/src/ds-components/ConfirmModal/index.module.scss
packages/console/src/ds-components/Dropdown/index.module.scss
packages/console/src/ds-components/Tip/TipBubble/index.module.scss
packages/console/src/pages/ApiResourceDetails/components/GuideDrawer/index.module.scss
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/GuideDrawer/index.module.scss
packages/console/src/pages/ApplicationDetails/components/AppGuide/index.module.scss
packages/console/src/pages/Applications/components/GuideLibrary/index.module.scss
packages/console/src/scss/_underscore.scss

- Fix the bug that rotating signing-key dropdown is not visible, caused by a mis-use of z-index values.
- Cosolidate all available z-index values into a SCSS mixin function, and limit the available options with a value map.
- Locally tested and the dropdown worked.
- If I try to use a value not defined in the z-index value map, the compiler will report an error.

fix(console): rotate signing-key dropdown should be visible

---

packages/console/src/components/ConnectorForm/ConfigForm/index.module.scss
packages/console/src/components/ConnectorForm/ConfigForm/index.tsx
packages/console/src/ds-components/CopyToClipboard/index.module.scss
packages/console/src/ds-components/CopyToClipboard/index.tsx
packages/console/src/mdx-components/ApplicationCredentials/index.tsx
packages/console/src/mdx-components/OidcCallbackUri/index.module.scss
packages/console/src/mdx-components/OidcCallbackUri/index.tsx
packages/console/src/mdx-components/SsoSamlSpMetadata/index.module.scss
packages/console/src/mdx-components/SsoSamlSpMetadata/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.module.scss
packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlAttributeMapping/index.module.scss
packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlAttributeMapping/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlMetadataForm/ParsedConfigPreview/index.module.scss
packages/console/src/pages/EnterpriseSsoDetails/Connection/SamlMetadataForm/ParsedConfigPreview/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/Connection/ServiceProviderInfo/OidcConnectorSpInfo.tsx
packages/console/src/pages/EnterpriseSsoDetails/Connection/ServiceProviderInfo/SamlConnectorSpInfo.tsx
packages/console/src/pages/EnterpriseSsoDetails/Connection/ServiceProviderInfo/index.module.scss
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/index.tsx
packages/integration-tests/src/tests/console/sso-connectors/helpers.ts

Fix the bug that copy to clipboard component is not displayed properly at full width in Enterprise SSO and some other pages. Root cause is that the CSS defined in pages do not override the component built-in styles properly.
Before
After

fix(console): copy to clipboard component should display at full width properly

---

packages/console/src/pages/CustomizeJwtDetails/MainContent/index.tsx
packages/console/src/pages/CustomizeJwtDetails/use-data-fetch.ts
packages/console/src/pages/CustomizeJwtDetails/utils/path.ts

fix the JWT creation page idle bug after submitting the form
- replace the `useJwtCustomizer` hook using useSWR global mutate to avoid the unnecessary API fetching
- remove the duplicate `getApiPath` util method
- change the await mutate to void, so the page can navigate immediately. 
test locally

fix(console): fix the jwt creation page idle bug after submit form

---

packages/console/src/contexts/AppConfirmModalProvider/index.tsx
packages/console/src/pages/CustomizeJwt/CustomizerItem/index.tsx
packages/console/src/pages/CustomizeJwt/DeleteConfirmModal.tsx
packages/console/src/pages/CustomizeJwt/index.tsx

This PR fixes the page idle moment when deleting a JWT customizer. 
Previously, there was no delete loading status implemented.  We use a global `useConfirmModal` to handle the `onDelete` request.  The delete API will be triggered after the confirm modal is closed.  
Since we need to undeploy the worker services upon a JWT customizer deletion request, the API may take some time to process.  Need to implement the loading status feedback to the user. 
- Replace the original `useConfirmModal` with a dedicated DeleteModal. As the global inline confirm modal does not support async callback handlers. Add loading status on the delete confirm button.
- In the meantime, our old global `AppConfirmModal` component is hard to maintain. Add some refactors in this PR.
- Rename the …

refactor(console): implement new jwt customizer delete modal

---

packages/console/src/hooks/use-console-routes/index.tsx
packages/console/src/hooks/use-console-routes/routes/tenant-settings.tsx
packages/console/src/pages/Organizations/Guide/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/index.tsx

Refactor page routers nested in organization guide and tenant member pages.
Locally tested and page navigation works as expected.

refactor(console): update organization guide and tenant member routers

---

packages/core/src/oidc/init.ts

Fix a typo in code comments.
N/A

chore(core): fix typo in code comments

---

.changeset/rare-lamps-worry.md
packages/core/src/middleware/koa-resource-param.test.ts
packages/core/src/middleware/koa-resource-param.ts
packages/core/src/oidc/init.ts

Add support to comma separated resource param in core service.
E.g. `?resource=foo,bar` => `?resource=foo&resource=bar`
Fixes https://github.com/logto-io/js/issues/670
- Tested locally with sample project
- Unit test

feat(core): support comma separated resource param

---

.changeset/thick-carrots-tickle.md
packages/core/package.json
pnpm-lock.yaml

Bump the latest version of `oidc-provider` in order to fix the resource indicator check. Previously there was a [bug](https://github.com/panva/node-oidc-provider/pull/1258) that prevents user from using simple domain (e.g. `https://example.com`) as the resource indicator.
Fixes #5779

fix(core): bump oidc-provider to fix resource indicator check

---

.github/workflows/release.yml

When running a pen-test diagnosis, we noticed that our edge docker image hadn't been updated for a few months. Related PR #5398. 
GitHub does not provide a proper container environment for the `arm64` platform docker image build. We have to use the depot instead. But, we do not want to use the depot build quota on every edge image build.
Add the new dockerize-edge-image job.  Build `amd64` platform only edge image, using the default local docker build. Triggers on every master push. 
ci workflow

feat: add the new dockerize-edge job

---

.changeset/chilled-pugs-notice.md
.github/workflows/main.yml
.github/workflows/upload-annotations.yml
packages/connectors/connector-oauth2/README.md
packages/connectors/connector-oauth2/package.json
packages/connectors/connector-oauth2/src/constant.ts
packages/connectors/connector-oauth2/src/index.ts
packages/connectors/connector-oauth2/src/oauth2/form-items.ts
packages/connectors/connector-oauth2/src/oauth2/index.ts
packages/connectors/connector-oauth2/src/oauth2/types.ts
packages/connectors/connector-oauth2/src/oauth2/utils.test.ts
packages/connectors/connector-oauth2/src/oauth2/utils.ts
packages/connectors/connector-oauth2/src/types.ts
packages/connectors/connector-oauth2/src/utils.ts
packages/connectors/connector-oidc/README.md
packages/connectors/connector-oidc/package.json
packages/connectors/connector-oidc/src/constant.ts
packages/connectors/connector-oidc/src/index.ts
packages/connectors/connector-oidc/src/types.ts
packages/connectors/connector-oidc/src/utils.ts
packages/core/jest.config.js
packages/core/nodemon.json
packages/shared/package.json
pnpm-lock.yaml

Some users have encountered integration issues between our OAuth2.0 connector, including the OIDC connector, and Hugging Face's OIDC OAuth2.0 service.
The primary issue is that our OAuth2 connector only supports the `client_secret_post` method for client authentication when requesting tokens from the OIDC service's token endpoint.
In contrast, Hugging Face's OIDC service accepts `client_secret_basic` and `client_secret_jwt` for client authentication methods (see [HF oidc metadata](https://huggingface.co/.well-known/openid-configuration)):
Consequently, we are unable to use our OAuth2.0 connector to integrate with Hugging Face’s OAuth 2.0 login system.
In this PR, we are aligning with [the OIDC protocol](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) by adding …

feat(connector): support `client_secret_basic` and `client_secret_jwt` methods for oauth2 connectors

---

.zap/rules.conf

ignore the hidden file found zap alert
Since we render the experience react app under the root path, any non-existing path will be handled by the experience app. A 404 page will be returned with an HTTP status code 200. 
When running the hidden file detection, the zap pen-test receives a 200 response code， so it assumes the hidden file exists on the server side. 
Temporarily ignore the alter for now. 
ci

chore: ignore the hidden file found zap alert

---

.changeset/healthy-knives-draw.md
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/integration-tests/src/helpers/organization.ts
packages/integration-tests/src/tests/api/organization/organization.test.ts
packages/phrases/src/locales/de/translation/admin-console/organization-details.ts
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
packages/phrases/src/locales/es/translation/admin-console/organization-details.ts
packages/phrases/src/locales/fr/translation/admin-console/organization-details.ts
packages/phrases/src/locales/it/translation/admin-console/organization-details.ts
packages/phrases/src/locales/ja/translation/admin-console/organization-details.ts
packages/phrases/src/locales/ko/translation/admin-console/organization-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/organization-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/organization-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/organization-details.ts
packages/phrases/src/locales/ru/translation/admin-console/organization-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/organization-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/organization-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/organization-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/organization-details.ts
packages/schemas/alterations/next-1713942039-add-organization-custom-data.ts
packages/schemas/tables/organizations.sql

support organization custom data for storing additional data associated with the organization.
- integration tests added
- tested console locally. organization custom data can be updated.

feat: support organization custom data

---

.changeset/funny-books-sell.md
packages/experience/src/containers/SocialSignInList/use-social.ts
packages/experience/src/hooks/use-single-sign-on.ts
packages/experience/src/pages/SocialSignInWebCallback/index.test.tsx

in a native environment, the social sign-in callback could not be handled due to the misconfigured callback path. this pull fixes the issue. see changeset for more details.
- tested locally, social sign-in can be complete in iOS simulator
- (next) add integration tests to cover this scenario

fix(experience): use correct callback path for native environments

---

.changeset/nine-turtles-learn.md
packages/core/src/routes/interaction/single-sign-on.ts
packages/experience/src/apis/interaction.ts
packages/experience/src/apis/single-sign-on.ts

Thx to the issue #5795 report, we have identified a bug in the SSO registration flow. The `PostRegister` hook event was not triggered as expected. 
When a new user registers via SSO, the `PostRegister` interaction hook event is not triggered. `PostSignIn` event is mistakenly triggered instead.
In the SSO `post /api/interaction/sso/:connectionId/registration` API, we update the interaction event to `Register`.
However, the hook middleware reads the event from the interaction session ahead of the API logic, and the event is not updated resulting in the wrong event being triggered.
In the current interaction API design, we should mutate the interaction event by calling the `PUT /api/interaction/event` API, instead of updating the event directly in the submit interaction APIs. (Just like the …

fix(experience,core): fix SSO register hook event not triggering bug

---

packages/schemas/alterations/next-1714270244-application-org-resource-scope.ts
packages/schemas/tables/application_user_consent_organization_resource_scopes.sql

Add new table `application_user_consent_organization_resource_scopes`.
This table will be used to store "organization resource scopes" for third-party applications.
Similar to `application_user_consent_resource_scopes`, but different relations, we need to filter out some organizations.

feat(schemas): add table for app org resource scope consent

---

.changeset/smart-melons-shop.md
packages/connectors/connector-feishu-web/src/index.ts
packages/core/src/routes/user-assets.ts

Fix file upload API.
The `koa-body` has been upgraded to the latest version, which caused the file upload API to break. This change fixes the issue.
The `ctx.request.files.file` in the new version is an array, so the code has been updated to pick the first one.
Local tested.

fix(core): fix upload file guard

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/constants.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/use-application-scopes-assignment.ts
packages/core/src/libraries/application.ts
packages/core/src/queries/application-user-consent-scopes.ts
packages/core/src/queries/application.ts
packages/core/src/routes/applications/application-user-consent-scope.openapi.json
packages/core/src/routes/applications/application-user-consent-scope.ts
packages/integration-tests/src/api/application-user-consent-scope.ts
packages/integration-tests/src/tests/api/application/application-user-consent-scope.test.ts
packages/schemas/src/types/application.ts

Implement the new field `ApplicationUserConsentOrganizationResourceScopes` in the following APIs:
- `GET /applications/:applicationId/user-consent-scopes`
- `POST /applications/:applicationId/user-consent-scopes`
- `DELETE /applications/:applicationId/user-consent-scopes/:scopeType/:scopeId`

feat(core,schemas): add CRUD for consent organization resource scopes

---

packages/core/src/middleware/koa-security-headers.ts

as we don't use it in frontend anymore
n/a

refactor: remove app insights domains from security headers

---

.changeset/popular-chicken-share.md
packages/core/src/libraries/organization-invitation.ts

Fix the bug that invitee cannot accept invitation if the email letter case is not matching
Will update integration tests in the Cloud repo

fix(core): invitee email check should be case insensitive

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Permissions/ApplicationScopesAssignmentModal/index.tsx

hide org resource scopes tab from 3rd-party app modal

fix(console): hide org resource scopes tab from 3rd-party app modal

---

packages/core/src/libraries/user.ts
packages/core/src/oidc/init.ts
packages/core/src/oidc/resource.ts
packages/core/src/routes/interaction/consent.ts
packages/integration-tests/src/tests/api/interaction/third-party-sign-in/happy-path.test.ts
packages/schemas/src/types/consent.ts

Add organization resource scopes info to `GET /interaction/consent`:
1. Filter out organizations-only resource scopes from `missingResourceScopes`.
2. Add `missingResourceScopes` to `organizations`.
To implement it, this PR includes:
1. Split `filterResourceScopesForTheThirdPartyApplication` into 2 functions, one for non-organizations, another for organizations. This helps the "filter out" operation in consetn GET.
2. Rebuild the scopes list in this API route. Because `missingResourceScopes` contains only scope name, without id. So I copied some of the code lines from `getResourceServerInfo` where the original `missingResourceScopes` comes from.
Integration tests and local tested.

feat(core,schemas): add org resource scopes to consent get

---

.changeset/pretty-mirrors-peel.md
packages/connectors/connector-github/package.json
packages/connectors/connector-github/src/constant.ts
packages/connectors/connector-github/src/index.test.ts
packages/connectors/connector-github/src/index.ts
packages/connectors/connector-github/src/types.ts
pnpm-lock.yaml

Sometimes, GitHub users do not set a public email. In previous implementation, Logto users who sign in with GitHub account need to manually add their email address.
In this change, we add default scope `user:email` which can be used to access GitHub accounts' private emails. And Logto will fallback to the verified primary email address in the GitHub account private email address list. This change can make GitHub social sign-in smoother.
What's more, we also migrate from `got` to `ky` for the GitHub connector and upgrade `nock` to a new version to update the unit test as well (old `nock` version can not successfully mock the HTTP requests made by `ky`).
Tested locally, removed my GitHub account public email, and as you can see no email is available but we can successfully fallback to a …

feat(connector): can access all user email even if no public email is set

---

packages/console/src/cloud/AppRoutes.tsx
packages/console/src/components/Topbar/UserInfo/index.module.scss
packages/console/src/components/Topbar/UserInfo/index.tsx
packages/console/src/components/Topbar/index.tsx
packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/containers/ConsoleRoutes/index.tsx
packages/console/src/contexts/TenantsProvider.tsx
packages/console/src/ds-components/Uploader/FileUploader/index.tsx
packages/console/src/ds-components/Uploader/ImageUploaderField/index.tsx
packages/console/src/hooks/use-console-routes/index.tsx
packages/console/src/hooks/use-console-routes/routes/profile.tsx
packages/console/src/hooks/use-user-assets-service.ts
packages/console/src/pages/Profile/containers/BasicUserInfoUpdateModal/index.tsx
packages/console/src/pages/Profile/index.module.scss
packages/console/src/pages/Profile/index.tsx
packages/core/src/routes-me/init.ts
packages/core/src/routes-me/user-assets.ts

Make the profile page "tenant-independent", so that even though a user has no tenant, he/she can still go to the profile page and check/update user information. The profile page will be opened in a new browser tab instead of being nested in the console main content area.
This PR fixes the issue that currently in Logto Cloud, when user has removed all tenants, the profile page is not accessible.
For OSS users, this PR does not change too much, except that the profile page is opened in a new tab instead of being nested in the main console content.
Add an external icon to the "Profile" menu item. Click it will open Profile page in a new browser tab

fix(console): make profile a tenant independent page

---

packages/console/src/pages/Profile/components/LinkAccountSection/index.tsx

Fix a bug that prevents "Link social" from working properly on Cloud, introduced by the router change made in #5687.
To be tested on dev

fix(console): fix the link social feature on logto cloud

---

packages/experience/src/pages/Consent/ScopesListCard/index.tsx

fix(experience): hide scope list if no user scopes and resource scopes

fix(experience): hide scope list if no user scopes and resource scopes

---

packages/console/src/cloud/AppRoutes.tsx
packages/console/src/containers/ConsoleRoutes/index.tsx
packages/console/src/contexts/TenantsProvider.tsx

1. The `/handle-social` route should be moved outside of the tenant context, following the `/profile` router change
2. Move `/accept` (accept invitation) router to `GlobalAnonymousRoutes` since it does not require tenant ID
To be tested on Cloud

refactor(console): refactor some console global routes

---

packages/console/src/cloud/AppRoutes.tsx
packages/console/src/containers/ConsoleRoutes/index.tsx
packages/console/src/contexts/TenantsProvider.tsx

Move `/handle-social` route to `GlobalAnonymousRoute` enum, in order to bypass the tenant ID check on Console loading. `/handle-social` route has been moved outside of tenant context, along with the changes made for `/profile` route.
To be tested on Cloud dev

fix(console): move handle social route to global anonymous route enum

---

packages/core/src/oidc/resource.ts
packages/core/src/routes/interaction/consent/index.ts
packages/core/src/routes/interaction/consent/utils.ts
packages/integration-tests/src/tests/api/interaction/third-party-sign-in/happy-path.test.ts

In consent API, should always filter resource scopes for third party application.
Although the "missiongResourceScopes" from the prompt details are already filtered, there may be duplicated scopes from either resources or organization resources.
For example, if `scope1` is enabled in "personal" but not in "organizations", then it can appear in "missiongResourceScopes".
Local tested, and integration tests case added.

fix(core): filter scopes for 3rd-party app

---

packages/core/src/oidc/extra-token-claims.ts
packages/core/src/oidc/grants/refresh-token.ts
packages/core/src/oidc/resource.ts
packages/core/src/routes/applications/application-user-consent-scope.ts
packages/core/src/routes/interaction/consent/index.ts
packages/core/src/routes/interaction/consent/utils.ts
packages/core/src/routes/organization/roles.ts
packages/schemas/src/types/organization.ts

Remove feature guard of organization api resource.
N/A

chore(core,schemas): remove feature guard of organization api resource

---

.github/workflows/main.yml
.github/workflows/upload-annotations.yml
.scripts/publish.js
packages/connectors/connector-oauth2/package.json
packages/connectors/templates/sync-preset.js

Build oauth2 connector on prepack since some connectors rely on its generated types.
CI passed.

chore: build oauth2 connector on prepack

---

packages/core/src/utils/request.ts
packages/core/src/utils/test-utils.ts

All the custom domain requests are marked as "domains.logto.app", try to add "Host" to recognize the original domain name.
N/A

chore(core): add custom domain host to app insights

---

packages/core/src/middleware/koa-management-api-hooks.ts
packages/core/src/routes/hook.ts
packages/schemas/src/foundations/jsonb-types/hooks.ts

- add devFeature guard DataHooks to the hook management API
- fix bug `koaManagementApi` will throw 404 on all management APIs is devFeature is off. 
test locally

fix(core): add devFeature guard for DataHooks

---

packages/core/src/routes/interaction/actions/submit-interaction.ts

add more checks to make it more secure
ci

refactor(core): update first admin user preconditions

---

packages/console/src/utils/route.ts

use the parameter value for guide ids since they have no PII and are good for analytics.
test online later

refactor(console): do not parameterize guide id

---

.changeset/green-cougars-behave.md
packages/core/src/libraries/user.ts
packages/core/src/routes/admin-user/basics.test.ts
packages/core/src/routes/admin-user/basics.ts
packages/integration-tests/src/tests/api/admin-user.test.ts

fixed #5572
should sign out user after deletion or suspension:
1. delete refresh token
2. delete opaque access token
3. delete session
Local tested, and integration tests.

fix(core): should sign out user after deletion or suspension

---

packages/core/src/routes/interaction/actions/submit-interaction.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.interaction.test.ts
packages/integration-tests/src/tests/api/hook/test-cases.ts
packages/integration-tests/src/tests/console/webhooks/helpers.ts
packages/schemas/alterations/next-1715829731-rename-data-hook-schema-update-event.ts
packages/schemas/src/foundations/jsonb-types/hooks.ts

rename the DataHook Schema data update event name:
User.Updated -> User.Data.Updated
Scope.Updated -> Scope.Data.Updated
Role.Updated -> Role.Data.Updated
Organization.Updated -> Organization.Data.Updated
OrganizationRole.Updated -> OrganizationRole.Data.Updated
OrganizationScope.Updated -> OrganizationScope.Data.Updated
integration tests updated

refactor(core,schemas,test): rename DataHook data update event name

---

packages/core/src/libraries/hook/context-manager.ts
packages/core/src/libraries/hook/index.test.ts
packages/core/src/libraries/hook/utils.ts
packages/core/src/middleware/koa-management-api-hooks.ts
packages/core/src/routes/dashboard.ts
packages/core/src/routes/organization/roles.ts
packages/core/src/routes/role.scope.test.ts
packages/core/src/routes/role.scope.ts
packages/core/src/routes/role.ts
packages/core/src/routes/sso-connector/index.ts
packages/core/src/routes/types.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.interaction.test.ts
packages/integration-tests/src/tests/api/hook/utils.ts

1. Extract the management API hook context build logic as a util method. 
2. Simplify the logic in `koaManagementApiHooks` middleware. Move the `getRegisteredDataHookEventContext` check into the `DataHookContextManager`
3. Mannually trigger `OrganizationRole.Scopes.Updated` on `OrganizationRole` creation with scopeIds provided
4. Mannually trigger `Role.Scopes.Updated` on `Role` creation with scopeIds provided.
5. Mark the return body of `POST /roles/:id/scopes` as deprecated. All relation assignment should not return entity details
6. Fix the status code for the post method. 

feat(core): add suctom scopes.updated hook events

---

packages/cli/src/commands/database/seed/tenant.ts
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
packages/console/src/components/CreateTenantModal/index.tsx
packages/console/src/components/CreateTenantModal/type.ts
packages/console/src/components/CreateTenantModal/types.ts
packages/console/src/hooks/use-subscribe.ts
packages/integration-tests/src/api/tenant.ts
packages/schemas/src/models/tenants.ts
packages/toolkit/core-kit/src/models/tenant.ts

- `TenantInfo` type should be imported from a cloud package instead of defining in schemas, as it's a pure cloud type
- update `TenantMetadata` to `TenantDatabaseMetadata` for better clarity
not marking this as a breaking change since they are for internal use only.
n/a

refactor: remove `TenantInfo` type

---

.changeset/friendly-chicken-pump.md
packages/experience/src/containers/SocialLinkAccount/use-social-link-related-user.ts
packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
packages/experience/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
packages/experience/src/hooks/use-global-redirect-to.ts
packages/experience/src/hooks/use-password-sign-in.ts
packages/experience/src/hooks/use-send-mfa-payload.ts
packages/experience/src/hooks/use-skip-mfa.ts
packages/experience/src/hooks/use-social-link-account.ts
packages/experience/src/hooks/use-social-register.ts
packages/experience/src/pages/Consent/index.tsx
packages/experience/src/pages/Continue/SetPassword/index.tsx
packages/experience/src/pages/Continue/SetUsername/use-set-username.ts
packages/experience/src/pages/RegisterPassword/index.tsx
packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts

Add a new `useGlobalRedirect` hook to handle all the sign-in/sign-up success redirections. Show the global loading status on redirect. 
This will prevent user interaction from the sign-in page while the HTTP redirect request is still loading.  
WIP

refactor(experience): add global loading status on page redirect

---

packages/phrases-experience/src/locales/de/description.ts
packages/phrases-experience/src/locales/fr/description.ts
packages/phrases-experience/src/locales/ko/description.ts

fix legacy sie phrase `social_bind_with_existing`.
Issue:
Some of the i18n translations of the phrase `social_bind_with_existing` are outdated.  We no longer pass the variable `method` to the phrase.
Fix: 
Sync with the latest en phrase. 
test locally

fix(phrases): fix legacy sie phrases

---

packages/console/src/assets/docs/guides/web-php/index.ts

In the description for the PHP SDK, the word "Laravel" is misspelled.
N/A

fix(console): fix Laravel misspelling

---

packages/core/src/utils/request.ts

for better debugging
after merge will test in dev

refactor(core): report forwarded headers

---

.changeset/hip-fireants-talk.md
packages/console/src/components/BasicWebhookForm/index.tsx
packages/console/src/consts/env.ts
packages/console/src/pages/WebhookDetails/WebhookLogs/index.tsx
packages/core/src/middleware/koa-management-api-hooks.ts
packages/core/src/routes/hook.ts
packages/core/src/routes/interaction/middleware/koa-interaction-hooks.ts
packages/core/src/routes/organization/roles.ts
packages/core/src/routes/role.ts

remove DataHook devFeature guard and add changeset. 
by integration tests

feat(console,core): remove DataHook devFeature guard

---

.changeset/angry-tables-repeat.md
packages/cli/src/commands/database/seed/roles.ts
packages/cli/src/commands/database/seed/tables.ts
packages/schemas/alterations/next-1716291265-create-pre-configured-m-api-role.ts
packages/schemas/src/seeds/management-api.ts

Create a pre-configured role with Management API access when seeding the database for a better Logto Management API integration experience
Since this feature is only for new user, so we don't need an alteration script.
After the Logto instance setup:

feat: create pre-configured role with m-api access when seeding db

---

packages/core/src/sso/AzureOidcSsoConnector/index.ts
packages/core/src/sso/OidcConnector/utils.ts

Skip the issuer validation for Azure OIDC SSO connector. 
For multi-tenant audience connectors, the issuer value in idToken may vary depending on the authenticated user's tenantId. Thus, unable to varify the exact value of the issuer. 
test locally

fix(core): skip iss validation for azure oidc sso

---

packages/schemas/alterations/next-1716291265-create-pre-configured-m-api-role.ts

Should import `generateStandardId` from `@logto/shared/universal`
CI passed

fix(schemas): import `generateStandardId` from correct source

---

packages/schemas/alterations/next-1716291265-create-pre-configured-m-api-role.ts
packages/schemas/alterations/utils/1716643968-id-generation.ts
packages/schemas/package.json
pnpm-lock.yaml

We need to add ID generation utilities for alteration scripts and import the generateStandardId functions from this utility file. 
This helps prevent missing dependencies when deploying alterations to the cloud environment. See https://github.com/logto-io/cloud/actions/runs/9222739336/job/25374687799
The issue arises because the database-alteration Azure function copies alteration scripts without installing dependencies for the schema package during deployment.
Test locally.

fix: add id generation utils for alteration scripts

---

packages/console/src/assets/docs/guides/m2m-general/README.mdx

fix m2m guide curl code syntax error
- endpoint should be placed after `--location`
- add trailing `/` at the end of lines

fix(console): fix m2m guide curl code syntax error

---

.changeset/olive-deers-wink.md
packages/connectors/connector-github/src/index.test.ts
packages/connectors/connector-github/src/index.ts

Fix GitHub connector GET /emails forbidden error.
Some users use GitHub App instead of OAuth App to collect user permissions.
In GitHub App, you can set Account permissions that block access to Email addresses.
In this situation, the server will reject the `GET /users/emails` request and cause an error. We need to try and catch this error and use an empty array as fallback to prevent the disruption of the Social sign in flow.
When `GET /users/emails` API is not accessible, the social sign-in flow works fine, `userEmails` is set to be empty array.

fix(connector): fix GitHub connector GET /emails forbidden error

---

.changeset/serious-geese-admire.md
packages/core/src/routes/interaction/single-sign-on.ts
packages/core/src/sso/AzureOidcSsoConnector/index.ts
packages/core/src/sso/OidcConnector/utils.ts
packages/core/src/sso/types/oidc.ts

This PR fix a online azure SSO invalid authentication error:
- For public organizations access EntraID OIDC applications, the token endpoint returns `expires_in` value type in number.
- For private organization access only applications, the token endpoint returns `expires_in` value type in string.
String type `expires_in` value is not supported by the OIDC connector, a invalid authorization response error will be thrown.
Update the token response guard to handle both number and string type `expires_in` value. Make the SSO connector more robust.
Also, update the response code guard for SSO routes. So the error detail won't lost. 
test locally

fix(core): fix azure oidc sso connector authorization error

---

packages/console/src/containers/ConsoleContent/index.tsx
packages/console/src/hooks/use-plausible-pageview.ts
packages/console/src/onboarding/index.tsx
packages/console/src/pages/Profile/index.tsx

add prefix to the pageview path per app for bettering analytics
n/a (will test in dev)

refactor(console): add prefix to pv path

---

packages/console/src/cloud/pages/Main/TenantLandingPage/TenantLandingPageContent/index.tsx
packages/console/src/components/Topbar/TenantSelector/index.tsx
packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.module.scss
packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.tsx
packages/console/src/containers/AppContent/TenantNotificationContainer/index.tsx
packages/console/src/ds-components/TextLink/index.module.scss
packages/phrases/src/locales/en/translation/admin-console/tenants.ts

show a banner for guiding user to create a prod tenant when there are only dev tenants under the user's account

feat(console): show banner when only dev tenant found

---

packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.module.scss
packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.tsx
packages/console/src/scss/modal.module.scss
packages/console/src/scss/normalized.scss

set `z-index` for top-level portals to ensure proper dom layering
the production tenant banner doesn't show when modal opened

refactor(console): set portal `z-index` properly

---

packages/console/src/components/RolesTransfer/SourceRolesBox/index.tsx

Open the role assignment modal and delete the default management API role and open the role assignment modal again, we will see a resource not found error:
This is because SWR cached the deleted role, and try to fetch the deleted role's information.
Solution: we should always use the latest data to reflect the latest available roles since using cached data before new data is loaded can result in roles that have been assigned or deleted being rendered in the list.
Test locally.

fix(console): avoid rendering outdated role options

---

packages/console/src/assets/docs/guides/m2m-general/README.mdx

Per offline discussion, the notification about the RBAC policy in Logto is not necessary, remove it.
Test locally.

refactor(console): remove redundant notification from m2m guide

---

.changeset/quick-hairs-fail.md
packages/core/src/libraries/jwt-customizer.ts
packages/core/src/libraries/user.ts
packages/core/src/oidc/scope.test.ts
packages/core/src/oidc/scope.ts
packages/core/src/routes/admin-user/basics.ts
packages/toolkit/core-kit/src/openid.ts

Add new `sso_identities` claim to the userinfo endpoint. 
This new claim will share the same `identities` scope with the social identities claim.

feat(core,toolkit): add new sso_identities claim

---

packages/schemas/alterations/next-1717148078-remove-service-log-reference.ts
packages/schemas/tables/service_logs.sql

remove the `tenant_id` fkey in the `service_logs` table since it should be a cloud table with no fkey
ci

refactor: remove service log fkey

---

packages/console/src/contexts/TenantsProvider.tsx
packages/console/src/hooks/use-subscription.ts
packages/console/src/onboarding/hooks/use-user-onboarding-data.ts
packages/console/src/onboarding/pages/Welcome/index.tsx

- remove unused code
- remove `currentTenantId` dependency in `useUserOnboardingData` as it is not applicable now
- check `tenantId` non-emptiness before fetch the subscription info to avoid the random `URL parameter not found` error when switching tenants.
- the root cause is sometimes the path will become `/` after clicking the target tenant, which is unexpected (should be `/:tenantId`). pending further investigation.
tested locally. with path `/` no error prompted.

refactor(console): improve onboarding data and subscription fetching

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
packages/console/src/components/CreateTenantModal/index.tsx
packages/console/src/onboarding/pages/CreateTenant/index.tsx

- remove `isDevFeaturesEnabled` flag for US region
- add loading state when creating tenants
tested locally. can create us region tenant.

chore: launch us region

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx

`buttonProps` overrides the original `disabled` logic, which should be combined. this pull update to the correct logic.
ci (cloud)

fix: use correct `disabled` logic for free plan

---

packages/console/src/pages/RoleDetails/index.tsx

M2M role notification should not be displayed on user roles page.
Bug:

fix(console): only show m2m role notification for m2m roles

---

packages/console/src/pages/Roles/index.module.scss
packages/console/src/pages/Roles/index.tsx

In small screen, the description and type of the role will be omitted, per offline discussion, make it breakable, and also adjust the `col-span` for the role type and role description column.
Before:
After:

refactor(console): make long text breakable in roles page

---

packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
packages/console/src/pages/Applications/components/GuideLibraryModal/index.tsx
packages/console/src/pages/Applications/index.tsx

If we switch browser tabs when the m2m role assignment modal is opened during the application creation flow for the first app, the m2m role assignment modal will be skipped:
https://github.com/logto-io/logto/assets/10806653/0aac046e-d8c9-462e-9a57-5e10bfbf3703
This is because when no application data in the table, the table will display a placeholder to show applicaiton guide items, and when we open the `ApplicationCreation` component from the guide items, the creation component will be rendered in the placeholder component, after the first app is created, table list will not empty (list refreshed by SWR when we switch browser tab), and this cause the placeholder with the role assignment modal to disappeared.
- render the `ApplicationCreation` component in the list page, rather than the …

fix(console): avoid skipping m2m role assignment after switching browser tabs

---

packages/core/src/routes-me/user-assets.ts

The profile avatar upload is currently down on Logto Cloud. Need to update this body guard in order to adjust the breaking change of the `ky` lib.
Pending Cloud dev testing

fix(core): profile avatar upload should not return 400 error

---

packages/core/src/middleware/koa-oidc-error-handler.ts

For better debugging on those OIDC endpoint requests, report the OIDC exceptions to the appInsights.

feat(core): report oidc exceptions to the appInsights

---

packages/console/src/pages/Profile/index.tsx

Fix the bug that language switch does not work on profile page in Cloud env.
Locally tested and it was working properly

fix(console): language switch should work on profile page

---

packages/console/src/components/ApplicationCreation/index.tsx
packages/console/src/components/RoleAssignmentModal/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/index.module.scss
packages/console/src/pages/Roles/components/CreateRoleForm/index.tsx
packages/integration-tests/src/tests/console/rbac/helper.ts
packages/phrases/src/locales/de/translation/admin-console/roles.ts
packages/phrases/src/locales/en/translation/admin-console/roles.ts
packages/phrases/src/locales/es/translation/admin-console/roles.ts
packages/phrases/src/locales/fr/translation/admin-console/roles.ts
packages/phrases/src/locales/it/translation/admin-console/roles.ts
packages/phrases/src/locales/ja/translation/admin-console/roles.ts
packages/phrases/src/locales/ko/translation/admin-console/roles.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/roles.ts
packages/phrases/src/locales/pt-br/translation/admin-console/roles.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/roles.ts
packages/phrases/src/locales/ru/translation/admin-console/roles.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/roles.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/roles.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/roles.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/roles.ts

Per offline discussion, we should always display the role creation hint in the role assignment modal.
And the role type options in the role creation modal should not be hidden.

refactor(console): always display role creation hint in role assignment modal

---

.changeset/fuzzy-eyes-add.md
packages/core/src/libraries/hook/context-manager.ts
packages/core/src/routes/admin-user/basics.test.ts
packages/core/src/routes/admin-user/basics.ts
packages/core/src/routes/well-known.test.ts
packages/core/src/utils/test-utils.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
packages/integration-tests/src/tests/api/hook/test-cases.ts
packages/schemas/src/foundations/jsonb-types/hooks.ts

Add the user data to the `User.Deleted` webhook event payload.
- Remove the `User.Deleted` from the auto-triggered management API webhook event registration list.
- Manually trigger the event instead. 
- Fetch the user data before deleting it from DB. Insert the data in the webhook event payload
test locally

refactor(core,schemas): add user detail payload to User.Deleted webhook event

---

packages/core/src/queries/organization/index.ts
packages/core/src/queries/organization/role-user-relations.ts
packages/core/src/queries/organization/user-relations.ts
packages/core/src/routes/organization/index.ts
packages/core/src/routes/organization/index.user-role-relations.ts

- split organization role routes into another file to be prepared for more routes
- split organization queries into files
ci

refactor(core): reorg organization routes

---

packages/core/src/queries/organization/email-domains.ts
packages/core/src/queries/organization/index.ts
packages/core/src/routes/organization/index.email-domain.openapi.json
packages/core/src/routes/organization/index.email-domains.ts
packages/core/src/routes/organization/index.ts
packages/integration-tests/src/api/organization.ts
packages/integration-tests/src/tests/api/organization/organization-email-domains.test.ts

implement basic email domain apis:
- `GET /api/organizations/:id/email-domains`
- `POST /api/organizations/:id/email-domains`
- `PUT /api/organizations/:id/email-domains`
- `DELETE /api/organizations/:id/email-domains/:emailDomain`

feat(core): organization email domains apis

---

.changeset/mean-dogs-pump.md
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SocialSignInForm/index.tsx
packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/experience/src/__mocks__/logto.tsx
packages/experience/src/hooks/use-sie.ts
packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
packages/integration-tests/src/tests/experience/automatic-account-linking.test.ts
packages/integration-tests/src/tests/experience/direct-sign-in.test.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
packages/schemas/alterations/next-1717567857-social-sign-in-linking.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql

per community request, provide an option to skip manually account linking during sign-in

feat: automatic social account linking

---

packages/core/src/main.ts
packages/core/src/tenants/Tenant.ts

Globally catch unhandled promise rejections and log them to Application Insights.
The unhandled promise rejection was first observed in the TenantPool class's get method. If the `tenantId` is not found, the `getTenantDatabaseDsn` method will throw a tenant not found error.  We use a try-catch block to catch the error and throw it with logging. However, if the `Tenant.create` Promise is read from the cache, somehow the error is not caught. 
An unhandled promise rejection is thrown, which will crash the app. 
The root cause of this error is still unknown. To prevent our production app from frequently crashing, we add this global catch instead.

fix(core): prevent uncaught promise rejection

---

packages/console/src/components/MultiOptionInput/index.module.scss
packages/console/src/components/MultiOptionInput/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/Experience/DomainsInput/index.tsx
packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/console/src/pages/OrganizationDetails/index.tsx
packages/console/src/pages/OrganizationDetails/types.ts
packages/console/src/pages/TenantSettings/TenantMembers/InviteEmailsInput/index.tsx
packages/core/src/routes/organization/index.email-domains.ts
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts

- implement console configuration ui
- allow empty array in `PUT /api/organizations/:id/email-domains`
local tested:
- from no domain to two domains
- from two domains to no domain
- save with no domain

feat(console): implement organization jit ui

---

.changeset/smart-laws-compare.md
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/core/src/libraries/user.ts
packages/core/src/routes/organization/index.ts

> [!Note]
> This pull is ready for review but should be held until a bug bash is done.
launch organization jit provisioning by removing dev feature flags and adding changeset.
ci

chore(console,core): launch organization jit

---

packages/console/src/pages/SignInExperience/PageContent/Content/LanguagesForm/ManageLanguage/LanguageEditor/LanguageDetails.tsx

`useApi({ hideErrorToast: true })` will disable global error handling, and now the `hideErrorToast` supports to config ignored error codes, so now we don't need to set the `hideErrorToast` to `true` when fetching custom phrases in the console, only `entity.not_found` error should be ignored.
Note: this PR only improves the robustness of the code and theoretically will not affect any users, so no changeset is needed.
Test locally.

refactor(console): imporve custom phrase fetch request error handling

---

.github/workflows/alteration-compatibility-integration-test.yml
.github/workflows/integration-test.yml
packages/console/src/consts/env.ts
packages/experience/src/constants/env.ts
packages/integration-tests/src/constants.ts
packages/integration-tests/src/tests/console/bootstrap.test.ts
packages/shared/src/node/env/GlobalValues.ts

To improve test case coverage and protect development feature code, we need to split the existing integration tests into two separate jobs, one with the development feature enabled and one without. This ensures that the development feature code does not break our production environment.
As the first step, this PR decouples the isDevFeatureEnabled environment variable from isIntegrationTest. Previously, we had:
```js
const isDevFeatureEnabled = yes(getEnv('DEV_FEATURES_ENABLED')) || yes(getEnv('INTEGRATION_TEST'));
```
Instead of automatically enabling the development feature for the integration test environment, we now need to explicitly set the DEV_FEATURES_ENABLED flag.
```js
const isDevFeatureEnabled = yes(getEnv('DEV_FEATURES_ENABLED'));
```
Create a new console dev feature enabled …

refactor(console,experience,test): decouple isDevFeatureEnabled with isIntegrationTest

---

.changeset/gold-bulldogs-draw.md
packages/console/src/consts/external-links.ts
packages/console/src/pages/UserDetails/UserSettings/index.tsx
packages/console/src/pages/UserDetails/types.ts
packages/console/src/pages/UserDetails/utils.ts
packages/phrases/src/locales/en/translation/admin-console/user-details.ts

we've add the support of `user.profile` via Management API but the user settings page in Console is missing the capability. this pull add it to Console.
> [!Note]
> The docs link will be available once https://github.com/logto-io/docs/pull/697 merged.

refactor(console): allow view and update `user.profile` in settings

---

packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts

- display sso icon in the jit domains list per design
- update enterprise sso phrases to eliminate ambiguity
configured `foo.com` for enterprise sso:

refactor(console): show sso status in jit domains

---

packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/core/src/sso/OidcConnector/index.ts
packages/core/src/sso/OidcConnector/test-utils.ts
packages/integration-tests/src/api/interaction-sso.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/helpers/single-sign-on.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts
packages/integration-tests/src/tests/api/interaction/single-sign-on/happy-path.test.ts

implement SSO related integration tests
integration test

test(core): implement sso related integration tests

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/experience/src/__mocks__/logto.tsx
packages/schemas/alterations/next-1718594164-add-agree-to-terms-policy.ts
packages/schemas/tables/sign_in_experiences.sql

**1/3 steps for agree to terms policy feature implementation**
Support config agree to terms policy in sign-in experience.
Note: for new users, the policy is default to `AutoAgree`, for existing users, the policy is still `RegistrationOnly`.
Test locally.

feat(schemas): add `agree_to_terms_policy` for sie table

---

packages/connectors/connector-google/README.md
packages/core/src/middleware/koa-security-headers.ts
packages/experience/src/Providers/IframeModalProvider/IframeModal/index.module.scss
packages/experience/src/Providers/IframeModalProvider/IframeModal/index.tsx

- improve google connector readme clarity
- disable COEP due to google's malformed response header
- clean global iframe style pollution
previewed locally, google one tap shows when it fall back to the iframe (non-FedCM)

refactor: fix google one tap issues

---

packages/schemas/src/consts/subscriptions.ts

add legacy-pro tag to reserved plan ID.
This change is the prerequisite of migrate `hobby` plan ID to `pro` plan ID since we want to keep legacy records.
N/A

chore(schemas): add legacy-pro tag to reserved plan ID

---

packages/experience/src/pages/SignIn/IdentifierSignInForm/index.module.scss
packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx

style(experience): add margin-bottom for terms checkbox on sign-in page

style(experience): add margin-bottom for terms checkbox on sign-in page

---

packages/core/src/libraries/application.ts
packages/core/src/libraries/organization-invitation.ts
packages/core/src/libraries/user.ts
packages/core/src/oidc/grants/refresh-token.ts
packages/core/src/oidc/resource.ts
packages/core/src/routes/applications/application-user-consent-organization.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/core/src/routes/interaction/consent/index.ts
packages/core/src/routes/organization/index.ts
packages/core/src/routes/organization/index.user-role-relations.ts
packages/core/src/routes/organization/roles.ts
packages/core/src/utils/RelationQueries.ts
packages/core/src/utils/SchemaRouter.ts

use object with explicit keys instead of arrays for relation queries (insert and exists). this makes the parameters clearer and eliminate the risk of element disorder.
no api change, integration tests should cover

refactor(core): update relation queries

---

packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts
packages/integration-tests/src/tests/api/interaction/organization-jit.test.ts

reorg the sso connector api cleanup logic

chore(test): reorg the sso connector api cleanup logic

---

packages/console/src/assets/docs/guides/native-expo/README.mdx

Add the troubleshooting section in the expo integration guide

docs(console): add the troubleshooting section in expo guide

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/PlanCardItem/index.tsx
packages/console/src/components/FeatureTag/index.tsx
packages/console/src/components/PlanDescription/index.tsx
packages/console/src/consts/plan-quotas.ts
packages/console/src/consts/subscriptions.ts
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx

Update subscription plan ID since we now use `ReservedPlanId.Pro` for Logto pro plan subscribers (see [@logto/cloud changes](https://github.com/logto-io/cloud/pull/769), before the change, we were using `ReservedPlanId.Hobby` to represent Logto pro plan subscribers, which is counterintuitive).

refactor(console): update subscription plan ID

---

packages/core/src/routes/swagger/index.ts
packages/core/src/routes/swagger/utils/general.ts

Add `Dev feature` tag for openapi.json operations to mark operations so that they will not show up in swagger API.
Tested locally, also should be covered by CI.

chore(core): add dev feature tag for openapi.json

---

packages/experience/src/hooks/use-single-sign-on-watch.ts
packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx

In the orginal implemantaion, the agree to terms plicy for SSO is not implemented for the lack of product design.
Now we introduce related implementation to fix the bug that agree to terms policy is not applied to for sso sign-in.
- Display agree to terms policy checkbox in SSO sign-in page when the policy is set to `Manual`
- Display agree to terms policy checkbox in SSO sing-up page when the policy is set to `Manual` or `ManualRegistrationOnly`
- Validating terms of use policy agreement before single sign-on.
Test by go though all flows

fix(experience): apply agree to terms policy for sso

---

packages/core/src/queries/organization/index.ts
packages/core/src/queries/organization/role-application-relations.ts
packages/core/src/queries/organization/role-user-relations.ts
packages/core/src/routes/organization/index.application-role-relations.ts
packages/core/src/routes/organization/index.applications.openapi.json
packages/core/src/routes/organization/index.ts
packages/integration-tests/src/api/organization.ts
packages/integration-tests/src/tests/api/organization/organization-application.test.ts
packages/integration-tests/src/tests/api/organization/organization-user.test.ts
packages/schemas/alterations/next-1718807616-organization-role-application-relations.ts
packages/schemas/tables/organization_role_application_relations.sql

- create organization - application - organization role relations table
- add apis for handling organization - application - organization role relations
- add `PUT` api for replacing all organization role relations for a organization - user pair

feat(core): organization app role apis

---

packages/core/src/constants/index.ts
packages/core/src/queries/subject-token.ts
packages/core/src/routes/init.ts
packages/core/src/routes/security/index.openapi.json
packages/core/src/routes/security/index.ts
packages/core/src/routes/swagger/index.ts
packages/core/src/tenants/Queries.ts
packages/integration-tests/src/api/subject-token.ts
packages/integration-tests/src/tests/api/security.test.ts
packages/schemas/alterations/next-1718865814-add-subject-tokens.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/subject-token.ts
packages/schemas/tables/subject_tokens.sql

Implement the API endpoint for creating new subject tokens.
Reference: [Tech design](https://www.notion.so/silverhand/Impersonation-35cde7be53094addb6797e757608e9ee)

feat(core): issue subject tokens

---

.changeset/fresh-gorillas-obey.md
packages/core/src/routes/organization-role/index.ts
packages/core/src/routes/organization/application/index.openapi.json
packages/core/src/routes/organization/application/index.ts
packages/core/src/routes/organization/application/role-relations.ts
packages/core/src/routes/organization/user/index.openapi.json
packages/core/src/routes/organization/user/role-relations.ts
packages/integration-tests/src/api/organization.ts
packages/integration-tests/src/helpers/organization.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
packages/integration-tests/src/tests/api/interaction/consent/happy-path.test.ts
packages/integration-tests/src/tests/api/organization/organization-application.test.ts
packages/integration-tests/src/tests/api/organization/organization-user.test.ts

- implement `POST /api/organizations/{id}/applications/roles` for batch applications - organization roles assignment
- make pagination optional for `GET /api/organizations/:id/users/:userId/roles` and `GET /api/organizations/:id/applications/:applicationId/roles`
- rationale: we have those pages shows organization members or applications with all their roles in that organization, thus the get roles api should be ok to have no pagination

feat(core): update application organization role apis

---

.changeset/heavy-badgers-jog.md
packages/core/src/routes/swagger/index.test.ts
packages/core/src/routes/swagger/index.ts
packages/core/src/routes/swagger/utils/parameters.ts

This PR partially addresses an issue reported in #6043 that caused OpenAPI tooling to fail when validating the generated OpenAPI specification document from `http://ip:port/api/swagger.json`. This fix aims to resolve two problems identified during the investigation:
1. The `:` character is invalid in parameter names, such as `organizationId:root`. These characters have been replaced with `-`.
2. The `tenantId` parameter of the `/api/.well-known/endpoints/{tenantId}` route was missing from the generated OpenAPI spec document, resulting in validation errors. This has been fixed.
> [!NOTE]
> ~Although the above steps result in a valid OpenAPI being generated, the Go client stubs produced by `openapi-generator-cli` (`go` extension) are still invalid. I believe the duplication of parameters …

fix: generate valid OpenAPI spec

---

.changeset/breezy-dodos-cheer.md
.changeset/orange-dryers-joke.md
.changeset/quick-schools-obey.md
packages/connectors/connector-azuread/README.md
packages/connectors/connector-azuread/src/constant.ts
packages/connectors/connector-azuread/src/index.ts
packages/connectors/connector-azuread/src/types.ts
packages/connectors/connector-google/README.md
packages/connectors/connector-google/src/constant.ts
packages/connectors/connector-google/src/index.ts
packages/console/src/components/ConnectorForm/ConfigForm/ConfigFormFields/index.module.scss
packages/console/src/components/ConnectorForm/ConfigForm/ConfigFormFields/index.tsx
packages/toolkit/connector-kit/src/types/config-form.ts
packages/toolkit/connector-kit/src/types/social.ts

Support config of `prompt` on built-in MS/Google connector.
1. add support of multi-select field of connector configuration
2. support dynamic connector config form rendering of multi-select field
3. support `prompt` config on built-in MS and Google social connectors

feat: support prompt config for some built-in connectors

---

.github/workflows/alteration-compatibility-integration-test.yml
.github/workflows/dev-feature-disabled-integration-test.yml

This PR refactors the integration test ci jobs.
1. Remove the `devFeatureEnabled` git diff detection. As it can only check a newly added dev feature code flow. For any existing dev feature code changes, the test won't be triggered.  Always trigger the dev feature disabled integration tests instead. 
2. Set the DB alteration compatibility integration tests devFeatureEnabled flag to false.  Should run the test under the dev feature disabled mode. 
3. Replace the old `set-output` command with the latest `$GITHUB_OUTPUT` syntax, as the `set-output` command is deprecated. See [github actions](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) for more details. 
ci job

refactor: refactor integration test ci job

---

packages/schemas/alterations/next-1719221205-fix-functions.ts
packages/schemas/tables/applications.sql
packages/schemas/tables/organization_roles.sql

In Logto Cloud, we have multiple schemas and the default search behavior will be problematic. This alteration script will fix it by setting the search path to public for the functions.
locally ran a cloud test set, no error

fix(schemas): explicitly set search path

---

packages/console/src/components/OrganizationList/index.module.scss
packages/console/src/components/OrganizationList/index.tsx
packages/console/src/consts/page-tabs.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/MachineToMachineApplicationRoles/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/console/src/pages/OrganizationDetails/Members/EditOrganizationRolesModal.tsx
packages/console/src/pages/UserDetails/UserOrganizations/index.tsx
packages/integration-tests/src/tests/console/rbac/machime-to-machime-rbac.test.ts
packages/phrases/src/locales/de/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
packages/phrases/src/locales/es/translation/admin-console/application-details.ts
packages/phrases/src/locales/fr/translation/admin-console/application-details.ts
packages/phrases/src/locales/it/translation/admin-console/application-details.ts
packages/phrases/src/locales/ja/translation/admin-console/application-details.ts
packages/phrases/src/locales/ko/translation/admin-console/application-details.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-br/translation/admin-console/application-details.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/application-details.ts
packages/phrases/src/locales/ru/translation/admin-console/application-details.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/application-details.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/application-details.ts

show organizations for m2m applications in the application details page

feat(console): show organization list for m2m apps

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx

currently there's no way to trigger backchannel logout within a m2m app. hide it first.
n/a

refactor(console): hide backchannel for m2m apps

---

packages/core/src/routes/swagger/consts.ts
packages/core/src/routes/swagger/index.ts

add a brief introduction on Management API authentication in the response of `api/swagger.json`

refactor: add brief intro in swagger.json

---

packages/core/src/routes/swagger/utils/parameters.ts
packages/core/src/utils/zod.ts

This will add `tenantId` back to responses, so that the generated Go client SDK doesn't complain about unknown JSON field being unmarshalled. This is the continuation of #6089 and (possibly completely) fixes #6043. The SDK works fine now, at least for a few routes I checked.

fix: include `tenantId` and its root param in responses

---

.changeset/sharp-cooks-explain.md
packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
packages/core/src/libraries/jwt-customizer.ts
packages/integration-tests/src/__mocks__/jwt-customizer.ts
packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
packages/schemas/src/types/logto-config/jwt-customizer.ts

Add `hasPassword` field to custom JWT user context.
Should be covered by integration test.

feat(core): add hasPassword field to custom JWT user context

---

packages/core/src/middleware/koa-auth/index.ts

This pull request enhances error handling in the validation process by specifically addressing potential issues that may arise when making requests using the ky library. The modifications ensure that TypeError and HTTPError are appropriately thrown, allowing backend error messages to be properly traced.
realted issue: #6048 
the error was thrown correctly:
Display internal error in the Console:

refactor: handle potential errors during ky requests in koa-auth middleware

---

packages/core/src/oidc/grants/client-credentials.test.ts
packages/core/src/oidc/grants/client-credentials.ts
packages/core/src/oidc/grants/refresh-token.test.ts
packages/core/src/oidc/grants/refresh-token.ts
packages/core/src/oidc/init.ts
packages/core/src/oidc/resource.ts
packages/core/src/queries/organization/application-role-relations.ts
packages/integration-tests/src/api/api.ts
packages/integration-tests/src/api/application.ts
packages/integration-tests/src/tests/api/application/application.roles.test.ts
packages/integration-tests/src/tests/api/oidc/client-credentials-grant.test.ts

implement `client_credentials` grant for organization access tokens (with and without resource)

feat(core): issue organization token via client credentials

---

packages/console/src/assets/docs/fragments/_experience-overview.md
packages/console/src/assets/docs/fragments/_redirect-uris-native.mdx
packages/console/src/assets/docs/fragments/_redirect-uris-web.mdx
packages/console/src/assets/docs/guides/native-ios-swift/README.mdx
packages/console/src/assets/docs/guides/native-ios-swift/index.ts
packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
packages/console/src/assets/docs/guides/web-next/README.mdx
packages/console/src/assets/docs/guides/web-nuxt/README.mdx
packages/console/src/assets/docs/guides/web-ruby/README.mdx
packages/console/src/assets/docs/guides/web-ruby/index.ts

resolves LOG-9367
- update swift app guide per our latest convention
- split native and web redirect uris fragments
- add missing full guide links (swift + ruby)
locally previewed

refactor(console): update swift guide

---

packages/console/src/pages/OrganizationDetails/Settings/JitSettings.tsx
packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
packages/console/src/pages/OrganizationDetails/Settings/index.tsx

fix sso connector check conditions in the organization jit section
local previewed

refactor(console): use correct array for checking enterprise sso

---

packages/console/src/assets/docs/guides/native-android/README.mdx

refactor(console): polish android guide
Test locally.

refactor(console): polish android guide

---

packages/console/src/assets/docs/fragments/_redirect-uris-web.mdx
packages/console/src/assets/docs/guides/web-next-app-router/README.mdx
packages/console/src/assets/docs/guides/web-next/README.mdx
packages/console/src/assets/docs/guides/web-php/README.mdx
packages/console/src/assets/docs/guides/web-python/README.mdx

- update export names in `_redirect-uris-web.mdx`
- adjust next guide section orders
locally previewed

refactor(console): polish guides

---

packages/console/src/assets/docs/guides/web-go/README.mdx

refactor(console): update golang guide
Test locally.

refactor(console): update golang guide

---

packages/console/src/components/ConnectorForm/GoogleOneTapCard/index.module.scss
packages/console/src/components/ConnectorForm/GoogleOneTapCard/index.tsx
packages/console/src/ds-components/Switch/index.module.scss

one tap should be a special case for the switch component, since in other cases a "Learn more" link may need to show at the end of the sentence.
locally previewed, both google one tap and text with learn more link worked as expected

refactor(console): fix switch styles

---

packages/console/src/assets/docs/fragments/_checkpoint.md
packages/console/src/assets/docs/guides/web-php/README.mdx

fix char escaping in PHP guide
locally previewed

refactor(console): fix php guide

---

packages/console/src/assets/docs/guides/web-sveltekit/README.mdx

docs(console): update the sveltekit guide

---

.changeset/gentle-camels-film.md
packages/console/src/hooks/use-console-routes/routes/organizations.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/console/src/pages/OrganizationDetails/index.tsx
packages/console/src/pages/OrganizationTemplate/OrganizationRoles/CreateOrganizationRoleModal.tsx
packages/core/src/oidc/grants/client-credentials.ts
packages/core/src/routes/applications/application-organization.openapi.json
packages/core/src/routes/applications/application-organization.ts
packages/core/src/routes/organization/application/index.openapi.json
packages/core/src/routes/organization/application/index.ts
packages/core/src/routes/swagger/index.ts
packages/integration-tests/src/tests/api/application/application.organization.test.ts
packages/integration-tests/src/tests/api/oidc/client-credentials-grant.test.ts
packages/integration-tests/src/tests/api/organization/organization-application.test.ts
packages/integration-tests/src/tests/api/organization/organization-user.test.ts

- changeset added
- api is ready
- console checks removed
- no test prefixed with devFeatureTest
local preview + ci

chore: launch m2m app for organizations

---

.scripts/compare-database.js

Add Logto DB role name normalization logics for region roles.
Since we are going to enable both cloud DB connection and region DB connection in @logto/cloud DB alteration, we need to check region-role grantee as well.
The random suffix of the region role name does not really matter, so we simply remove these random suffix from region role name to normalize region role names like what we have done to tenant roles' names.
N/A

chore: normalize Logto DB region role names for DB alteration CI

---

packages/console/src/assets/docs/fragments/_redirect-uris-native.mdx
packages/console/src/assets/docs/guides/native-expo/README.mdx

Update the expo SDK integration guide

docs(console): update the expo SDK integration guide

---

packages/console/src/assets/docs/fragments/_redirect-uris-native.mdx
packages/console/src/assets/docs/guides/native-flutter/README.mdx
packages/console/src/assets/docs/guides/native-ios-swift/README.mdx

Update the Flutter integration guide

docs(console): update flutter intergration guide

---

.github/workflows/alteration-compatibility-integration-test.yml
.github/workflows/integration-test.yml
.github/workflows/rerun.yml

add rerun logic for integration tests
hard to test now since the `rerun.yml` does not exists yet. the cli does not work even if `--ref` specified. will test once merged.

ci: rerun integration tests on failure

---

packages/console/src/assets/docs/fragments/_redirect-uris-web.mdx
packages/console/src/assets/docs/guides/web-java-spring-boot/README.mdx

docs(console): update the java spring guide

---

packages/console/src/components/AppError/index.module.scss
packages/console/src/components/AppError/index.tsx

add retry button to clear tokens and trigger reload on error

refactor(console): add retry button on error

---

packages/console/src/assets/docs/guides/spa-vanilla/README.mdx

Update Vanilla JS integration guide in Console
Locally tested

refactor(console): update vanilla js integration guide

---

packages/console/src/assets/docs/guides/spa-react/README.mdx
packages/console/src/components/Guide/index.module.scss

Update React SDK integration guide in Console
Locally tested

refactor(console): update react integration guide

---

packages/console/src/mdx-components/Mermaid/index.tsx

Parcel is not smart enough when building production and too smart when developing. there's a Chinese idiom for this situation: "自作聪明"

refactor(console): load mermaid in dev

---

.scripts/compare-database.js

When we create region role, we also create a corresponding `policy` (see [PR#738](https://github.com/logto-io/cloud/pull/738)). We hence extract `nomalizeRoleName()` as a reusable method and refactored the DB alteration compare logic.
Need to test on cloud CI.

refactor: update compare DB alteration scripts

---

packages/console/src/assets/docs/guides/api-python/README.mdx
packages/console/src/assets/docs/guides/api-spring-boot/README.mdx

Fix broken API resource guides: `Python` and `Springboot`.
Issue was introduced by nested `<p>` tags in mdx-generated html.
Locally tested and those guides can be rendered successfully.

fix(console): fix broken api resource guides

---

packages/core/src/oidc/grants/index.ts
packages/core/src/oidc/grants/token-exchange.test.ts
packages/core/src/oidc/grants/token-exchange.ts
packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts

Implement organization token for "token exchange": if `organization_id` param is set, will return organization token.
There are some similar code in current 3 grants, created an issue LOG-9191 to track, will refactor them before release.

feat(core): organization token for token exchange flow

---

packages/console/src/assets/docs/guides/api-python/README.mdx
packages/console/src/assets/docs/guides/api-spring-boot/README.mdx
packages/console/src/components/Guide/index.tsx

follow-up of #6161
- pass correct child (string instead of object) to `<code>`
- use `title` for code blocks
- show action bar in api resource guides
local preview ok

refactor(console): optimize api resource guides

---

packages/console/src/assets/docs/guides/api-python/README.mdx
packages/console/src/assets/docs/guides/native-flutter/README.mdx
packages/console/src/assets/docs/guides/native-ios-swift/README.mdx
packages/console/src/assets/docs/guides/web-go/README.mdx
packages/console/src/components/Guide/index.module.scss
packages/console/src/mdx-components/Anchor/index.tsx
packages/console/src/mdx-components/MdxProvider/index.tsx

Fix custom element tag swap out in MDX.
Before:
After:

fix(console): fix custom element swap in mdx

---

.github/workflows/integration-test.yml
.github/workflows/rerun.yml
packages/integration-tests/package.json
packages/integration-tests/src/tests/api/oidc/organization-token.test.ts
pnpm-lock.yaml

also like a chore:
- add the missing workflow name
- specify `-r` for the rerun step for better display (otherwise the `branch` for `rerun.yml` will always be `master`)
- update `@logto/node` to the latest version
ci
rerun works as expected for `-r`

refactor: update ci and package

---

.changeset/good-shrimps-cover.md
packages/console/src/components/ApplicationName/index.tsx

A patch fix to #6021. It seems the error code used in the previous PR was wrong for the scenario that showing deleted application ID in audit logs.
And it has a regression bug that the console keeps popping up the error toast again for deleted application ID.
Tested locally with a deleted application record in Audit logs, and the error toast did not show up again.

fix(console): hide error toast for non-existed application in audit logs

---

.changeset/brown-cobras-know.md
packages/core/src/routes/swagger/index.test.ts
packages/core/src/routes/swagger/index.ts
packages/core/src/routes/swagger/utils/general.ts
packages/core/src/routes/swagger/utils/operation-id.test.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/integration-tests/src/api/index.ts
packages/integration-tests/src/tests/api/swagger-check.test.ts

This PR adds `operationId` to the each HTTP method on each endpoint. As per [the specification](https://swagger.io/docs/specification/paths-and-operations/), "`operationId` is an optional unique string used to identify an operation. If provided, these IDs must be unique among all operations described in your API". This greatly simplifies the creation of client SDKs in different languages, because it generates more meaningful function names instead of auto-generated ones, like the following examples:
```diff
- org, _, err := s.Client.OrganizationsAPI.ApiOrganizationsIdGet(ctx, req.GetId()).Execute()
+ org, _, err := s.Client.OrganizationsAPI.GetOrganization(ctx, req.GetId()).Execute()
```
```diff
- users, _, err := s.Client.OrganizationsAPI.ApiOrganizationsIdUsersGet(ctx, …
```

feat: add `operationId` to HTTP methods on paths

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/experience/src/__mocks__/logto.tsx
packages/schemas/alterations/next-1719312694-custom-ui-assets.ts
packages/schemas/src/seeds/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql

Update DB for "bring your own UI" feature. Added new "custom_ui_asset_id" column in "sign_in_experiences" table.
The "custom_ui_asset_id" will be generated when user uploads the assets to Logto storage, and will be used as part of its CDN storage key.
Alteration scripts executes successfully

feat(schemas): custom ui assets db update

---

packages/core/src/oidc/extra-token-claims.ts
packages/integration-tests/src/tests/api/oidc/client-credentials-grant.test.ts

`getExtraTokenClaimsForOrganizationApiResource` does not recognize client credentials grant so the `organization_id` claim is missing in the token. this pull fixes the issue.

fix(core): issue `organization_id` claim for client credentials

---

packages/core/src/oidc/grants/index.ts
packages/core/src/oidc/grants/token-exchange.ts
packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts

In token exchange grant: filter out non-oidc scopes when resource is not present (the audience is OP).
In other grant type flow, this is done by `Grant` class. But there is no `Grant` instance in token exchange, so we have to do it manually. The `oidcScopes` list comes from `oidc.provider`, SSOT is ensured. https://github.com/panva/node-oidc-provider/blob/0c569cf5c36dd5faa105fb931a43b2e587530def/lib/helpers/oidc_context.js#L159

feat(core): handle oidc scopes for token exchange

---

packages/connectors/connector-mock-social/src/index.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/routes/experience/classes/verifications/social-verification.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/verification-routes/social-verification.ts
packages/core/src/routes/interaction/types/index.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/social-verification.ts
packages/integration-tests/src/tests/api/experience-api/verifications/social-verification.test.ts
packages/schemas/src/types/interactions.ts

Implement the social verification class and social verification endpoints.
- `experience/verification/social/:connectorId/authorization-uri`
- `experience/verification/social/:connectorId/verify`
These two endpoints handle the social verification creation and verification logic. 
This PR also includes mockSocialConnector updates, and adds the `connectorSession` write and read logic. So in our integration tests, the `connectorSession`  write and retrieve logic can be tested. 

feat(core,schemas): implement social verification experience API endpoints

---

packages/experience/src/Providers/UserInteractionContextProvider/UserInteractionContext.tsx
packages/experience/src/Providers/UserInteractionContextProvider/index.tsx
packages/experience/src/components/InputFields/SmartInputField/use-smart-input-field.ts
packages/experience/src/containers/ForgotPasswordLink/index.tsx
packages/experience/src/containers/VerificationCode/PasswordSignInLink.tsx
packages/experience/src/containers/VerificationCode/index.tsx
packages/experience/src/hooks/use-check-single-sign-on.ts
packages/experience/src/hooks/use-global-redirect-to.ts
packages/experience/src/hooks/use-send-verification-code.ts
packages/experience/src/hooks/use-session-storages.ts
packages/experience/src/pages/Continue/SetEmailOrPhone/index.tsx
packages/experience/src/pages/Continue/SetUsername/index.tsx
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/experience/src/pages/ForgotPassword/index.test.tsx
packages/experience/src/pages/ForgotPassword/index.tsx
packages/experience/src/pages/Register/IdentifierRegisterForm/index.test.tsx
packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
packages/experience/src/pages/ResetPassword/index.tsx
packages/experience/src/pages/SignIn/IdentifierSignInForm/index.test.tsx
packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
packages/experience/src/pages/SignIn/IdentifierSignInForm/use-on-submit.ts
packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
packages/experience/src/pages/SignInPassword/PasswordForm/index.test.tsx
packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx
packages/experience/src/pages/SignInPassword/index.test.tsx
packages/experience/src/pages/SignInPassword/index.tsx
packages/experience/src/pages/VerificationCode/index.test.tsx
packages/experience/src/pages/VerificationCode/index.tsx
packages/experience/src/types/guard.ts

This PR introduces a significant refactoring of the user input identifier caching mechanism to enhance the sign-in experience. The main changes include:
-  Implementation of a new UserInteractionContext to manage and persist user input identifiers across different pages and flows.
-  Introduction of session storage for caching identifier input values, improving user experience when navigating between pages.
- Refactoring of various components and hooks to utilize the new context and storage mechanism, including:
- ForgotPassword flow
- SignIn flow
- Registration flow
- Password reset flow
- Removal of state passing through react-router, replacing it with the new context-based approach.
- Updates to relevant test cases to accommodate the new caching mechanism.
These changes aim to provide …

refactor(experience): cache user input identifier for a better sign-in experience

---

packages/experience/src/containers/SetPassword/HiddenIdentifierInput.tsx
packages/experience/src/containers/SetPassword/Lite.tsx
packages/experience/src/containers/SetPassword/SetPassword.tsx
packages/experience/src/types/guard.ts

This PR introduces a new `HiddenIdentifierInput` component to enhance the user experience with browser password managers. The component is integrated into the password setting flows, both in the standard and lite versions.
These changes ensure that browser password managers accurately store and autofill user credentials, improving user experience and security.
Test locally.
For new registered user:
For password reset:

refactor(experience): add hidden identifier input for browser password manager

---

.changeset/dull-goats-help.md
.changeset/lazy-geese-bow.md
packages/connectors/connector-mock-social/src/index.ts
packages/console/src/hooks/use-user-assets-service.ts
packages/console/src/pages/OrganizationDetails/Settings/Branding.tsx
packages/console/src/pages/OrganizationDetails/Settings/index.module.scss
packages/console/src/pages/OrganizationDetails/Settings/index.tsx
packages/console/src/pages/OrganizationDetails/Settings/utils.ts
packages/core/src/libraries/sign-in-experience/index.test.ts
packages/core/src/libraries/sign-in-experience/index.ts
packages/core/src/oidc/utils.ts
packages/core/src/routes/well-known.ts
packages/demo-app/src/App.tsx
packages/demo-app/src/DevPanel.tsx
packages/demo-app/src/utils.ts
packages/experience/src/apis/settings.ts
packages/experience/src/utils/search-parameters.ts
packages/integration-tests/src/constants.ts
packages/integration-tests/src/tests/api/admin-user.test.ts
packages/integration-tests/src/tests/api/sign-in-experience.test.ts
packages/integration-tests/src/tests/experience/overrides.test.ts
packages/phrases/src/locales/en/translation/admin-console/organization-details.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
packages/schemas/alterations/next-1720253939-add-organization-branding.ts
packages/schemas/src/consts/oidc.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
packages/schemas/tables/application_sign_in_experiences.sql
packages/schemas/tables/organizations.sql

- upload and remove organization logo in console
- support sign-in parameter `organization_id` for overriding the logo with the organization's

feat: organization logo

---

packages/core/src/oidc/utils.test.ts
packages/core/src/oidc/utils.ts
packages/experience/src/apis/settings.ts
packages/experience/src/index.html
packages/experience/src/utils/search-parameters.ts

this param is not in use anymore
ci

refactor(core, experience): remove `no_cache` param

---

packages/core/src/oidc/extra-token-claims.ts
packages/core/src/oidc/grants/index.ts
packages/core/src/oidc/grants/token-exchange/actor-token.test.ts
packages/core/src/oidc/grants/token-exchange/actor-token.ts
packages/core/src/oidc/grants/token-exchange/index.test.ts
packages/core/src/oidc/grants/token-exchange/index.ts
packages/core/src/oidc/grants/token-exchange/types.ts
packages/core/src/oidc/init.ts
packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts

Implement "actor token" feature in token exchange according to the [RFC](https://github.com/logto-io/rfcs/blob/master/draft/0005-impersonation.md).
If `actor_token` is present, will add an extra claim `act` to the response access token.
Because the class `AccessToken` can only accept a list of predefined claims, so we have to set the `act` claim to `extra` first, and then extract it to the outside in `extraTokenClaims` option of `node-oidc-provider`.
This PR also includes the refactor of `token-exchange.ts`, it is now splited into a folder of files.

feat(core): actor token

---

packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
packages/core/src/oidc/extra-token-claims.ts
packages/integration-tests/src/__mocks__/jwt-customizer.ts
packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts

Add subject token context to JWT cutomizer.

feat(core): add subject token context to jwt customizer

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/routes/experience/classes/verifications/social-verification.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/enterprise-sso-verification.ts
packages/integration-tests/src/tests/api/experience-api/verifications/enterprise-sso-verification.test.ts

Implement the enterprise SSO verification flow.
Same approach as the social connector. 
Unlike social, SSO should auto-link the related user identity. (TODO)
integration tests

feat(core): implement enterprise sso verification flow

---

packages/experience/src/components/InputFields/InputField/NotchedBorder/index.module.scss
packages/experience/src/components/InputFields/InputField/NotchedBorder/index.tsx
packages/experience/src/components/InputFields/InputField/index.module.scss
packages/experience/src/components/InputFields/InputField/index.tsx
packages/experience/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.module.scss
packages/experience/src/components/InputFields/SmartInputField/CountryCodeSelector/CountryCodeDropdown/index.tsx
packages/experience/src/components/InputFields/SmartInputField/CountryCodeSelector/index.module.scss
packages/experience/src/components/InputFields/SmartInputField/CountryCodeSelector/index.tsx
packages/experience/src/components/InputFields/SmartInputField/index.tsx
packages/experience/src/components/InputFields/SmartInputField/utils.test.ts
packages/experience/src/components/InputFields/SmartInputField/utils.ts
packages/experience/src/containers/SetPassword/Lite.tsx
packages/experience/src/containers/SetPassword/SetPassword.tsx
packages/experience/src/pages/MfaVerification/BackupCodeVerification/index.tsx
packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx

This PR introduces significant changes to our input field components, enhancing their functionality and improving the user experience. The main updates include:
- Added a new `NotchedBorder` component for input fields, providing a more visually appealing and accessible design.
- Refactored the `InputField` component to support labels and improve its overall structure.
- Updated various form components throughout the application to use the new label feature.
- Modified the `SmartInputField` and related components to support the new labeling system.
- Updated test files to reflect the new changes in input field props.
These changes aim to enhance the visual consistency of our forms, improve accessibility by providing clear labels for input fields, and create a more polished user interface …

refactor(experience): add label for input field

---

packages/core/package.json
packages/core/src/libraries/quota.ts
packages/core/src/routes/security/index.ts
pnpm-lock.yaml

Add quota guard to the API of create subject tokens.

feat(core): add quota guard for subject tokens

---

.vscode/settings.json
packages/console/src/ds-components/Checkbox/Checkbox/index.module.scss
packages/console/src/ds-components/ColorPicker/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/LogoUploader.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.module.scss
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/core/src/caches/well-known.ts
packages/core/src/libraries/sign-in-experience/index.test.ts
packages/core/src/libraries/sign-in-experience/index.ts
packages/core/src/oidc/init.ts
packages/core/src/oidc/utils.test.ts
packages/core/src/oidc/utils.ts
packages/core/src/routes/applications/application-sign-in-experience.ts
packages/core/src/routes/well-known.ts
packages/core/src/tenants/Libraries.ts
packages/demo-app/src/App.tsx
packages/demo-app/src/DevPanel.tsx
packages/demo-app/src/utils.ts
packages/experience/src/apis/settings.ts
packages/experience/src/components/LogtoSignature/index.module.scss
packages/experience/src/index.html
packages/experience/src/utils/search-parameters.ts
packages/integration-tests/src/tests/api/application/application-sign-in-experience.test.ts
packages/integration-tests/src/tests/experience/overrides.test.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/index.ts
packages/schemas/alterations/next-1720345784-add-color-to-app-sie.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
packages/schemas/tables/application_sign_in_experiences.sql

support app-level logos and brand colors for sign-in experience, resolve LOG-9595
- a new search parameter `app_id=<curren-app-id>` will be passed to the sign-in experience
- cache `isDevelopmentTenant` (more to come in the following pulls)
- allow application-level sign-in experience for all apps
- `/api/.well-known/sign-in-exp` now accepts both `organizationId` and `appId` as search parameters
- organization branding > application branding > default branding
- demo app now accepts other app IDs (via dev panel or search parameter)
- remove sign-in experience prefetch as it needs parameters now (should use ssr for these data in the future)

feat: support app-level branding

---

packages/experience/src/Providers/AppBoundary/AppMeta.tsx
packages/integration-tests/src/tests/experience/overrides.test.ts

show dark favicon when possible, resolve LOG-9595

refactor(experience): show dark favicon

---

packages/experience/src/pages/VerificationCode/index.tsx

In the verfication code page, if the flow is forgot password, we should read the forgot password input identifier.
Updates:
- fix typo `useFlow` -> `userFlow`
Test locally.

fix(experience): use forgot password identifier in related flow

---

packages/core/src/oidc/grants/client-credentials.ts
packages/core/src/oidc/grants/refresh-token.ts
packages/core/src/oidc/grants/token-exchange/index.ts
packages/core/src/oidc/grants/utils.ts

Implement DPoP and client certificate validation and support for token exchange.
This PR also refactored the implementation in refresh token grant and client credential grant.
There is no additional tests, the code is copied from the original implementation of node-oidc-provider.
The existing tests should pass.

feat(core): handle dpop and client certificate for token exchange

---

packages/experience/src/Providers/AppBoundary/AppMeta.tsx
packages/integration-tests/src/tests/experience/overrides.test.ts
packages/integration-tests/src/ui-helpers/expect-experience.ts

fixes LOG-9614. favicon should be able to fall back to the light one when dark mode is on but only light favicon provided.
added a bunch of tests for the fallback logic

refactor: fix experience branding fallback

---

packages/console/src/components/ImageInputs/index.tsx
packages/core/src/libraries/sign-in-experience/index.ts
packages/core/src/queries/application-sign-in-experience.ts
packages/integration-tests/src/tests/experience/overrides.test.ts

resolves LOG-9599 and LOG-9596. third-party apps should not overwrite the existing experience branding.

refactor: fix third-party app experience branding

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/middleware/koa-experience-interaction.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/interaction.test.ts
packages/schemas/src/types/interactions.ts

Introduce new PUT experience API. See [RFC update](https://github.com/logto-io/rfcs/pull/11) for more details.
This PR adds two new experience root-level endpoints:
- `PUT /experience`: Init a brand new interaction with a given interaction event. A new interaction instance will be created and overwrite any existing interaction data in the session. 
- `PUT /experience/interaction-event`: Interchange between `Register` and `SignIn`.
Also includes the following refactoring:
1. Update the identification endpoint payload. `InteractionEvent` is removed from the body. Per our latest design, the interaction event should be specified ahead by calling the newly added `PUT /experience` API.
2. Update the `ExperienceInteraction` class constructor. Make the `interactionDetails` input optional.  If no …

feat(core,schemas): introduce new PUT experience API

---

.changeset/shy-baboons-occur.md
packages/core/src/middleware/koa-experience-ssr.test.ts
packages/core/src/middleware/koa-experience-ssr.ts
packages/core/src/middleware/koa-serve-static.ts
packages/core/src/oidc/init.ts
packages/core/src/oidc/utils.ts
packages/core/src/routes/well-known.ts
packages/core/src/tenants/Tenant.ts
packages/core/src/utils/i18n.ts
packages/experience/src/i18n/utils.ts
packages/experience/src/include.d/global.d.ts
packages/experience/src/index.html
packages/experience/src/jest.setup.ts
packages/experience/src/utils/search-parameters.ts
packages/experience/src/utils/sign-in-experience.ts
packages/integration-tests/src/include.d/global.d.ts
packages/integration-tests/src/tests/experience/server-side-rendering.test.ts
packages/schemas/src/types/cookie.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/sign-in-experience.ts
packages/schemas/src/types/ssr.ts

support experience data server-side rendering and fall back to network fetching if needed.
locally tested and ⬇️

refactor: experience ssr

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/sign-in-experience-settings.test.ts
packages/core/src/routes/experience/classes/sign-in-experience-settings.ts
packages/core/src/routes/experience/classes/utils.ts
packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.test.ts
packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
packages/core/src/routes/experience/verification-routes/totp-verification.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/interaction.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/verification-code.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/backup-code-verification.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/password-verification.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/social-verification.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/totp-verification.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/verification-code.test.ts
packages/phrases/src/locales/en/errors/session.ts
packages/schemas/src/types/interactions.ts

```caution
Please ignore the largest PR size, have of them are ut test cases definitions.
```
Previously we had a new `InteractionIdentifierType` enum value defined. To represent the type of identifiers supported in Logto. `username`, `email`, and `phone`. 
It turns out, we have had a `SignInIdentifier` enum defined already with the exact same definition, and being used in the sign-in-experience settings. 
Thus, remove the new `InteractionIdentifierType`  definition, and replace all the references using `SignInIdentifier`.
We had a new `session.not_identified` error code defined for the experience API. For a similar reason as above, we already have a `session.identifier_not_found` defined and used in the current interaction API. It represents the …

feat(core,schemas): implement the sie settings guard

---

packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/verifications/enterprise-sso-verification.test.ts

Add get available SSO connectors endpoint. Retrieve available SSO connectorIds for a given email. 

feat(core): add get available sso connectors endpoint

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/utils.ts
packages/core/src/routes/experience/classes/validators/profile-validator.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
packages/core/src/routes/experience/classes/verifications/password-verification.ts
packages/core/src/routes/experience/classes/verifications/social-verification.ts
packages/core/src/routes/experience/classes/verifications/verification-record.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/types.ts
packages/schemas/src/types/interactions.ts

1.  Define a new abstract class `IdentifierVerificationRecord`, extending the root `VerificationRecord` abstract class. This class defines an extra `identifyUser` method.  All the verification records used to identify a user are considered an `IdentifierVerificationRecord`. An `identifyUser` method must be implemented properly. 
2. Defines the interaction profile type and guard. 
3. Implement the `toUserProfile` methods in the `VerificationCode`, `SocialVerification`, and `SsoVerirification` classes.  This method will be used to convert the verified verification record to a new user profile, for new user registration and profile fulfillment use.
4. Implement a `ProfileValidator` class. This library class will be used to guard and validate new users …

feat(core,schemas): implement the register flow

---

packages/core/src/routes/experience/index.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts

Add register flow integration tests.

test(core): add register integration tests

---

packages/core/src/libraries/user.utils.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/utils.test.ts
packages/core/src/routes/experience/classes/utils.ts
packages/core/src/routes/experience/classes/validators/profile-validator.ts
packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.test.ts
packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
packages/core/src/routes/experience/classes/verifications/password-verification.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/username-password.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/new-password-identity-verification.test.ts
packages/schemas/src/types/interactions.ts

This PR implements the username+password registration flow.
We defined a new `NewPasswordIdentifyVerification` verification record class in this PR. It represents a verification record that is used to return a valid new password+identifier for new user registration use. 
This verification record will verify the uniqueness of the given identifier and validate the password against the password policy checker.
This endpoint will create and verify a new password identity. A verification record will be stored in the interaction storage after a successful verification. 
This method will validate the new given password against the password policy checker. Throws an error if any violation is found. 
As the `PasswordPolicyChecker` relys on the SIE settings to generate a proper policy checker. We …

feat(core,schemas): implement the username password registration flow

---

packages/experience/src/Providers/ConfirmModalProvider/index.tsx
packages/experience/src/Providers/ConfirmModalProvider/indext.test.tsx
packages/experience/src/components/ConfirmModal/AcModal.tsx
packages/experience/src/components/ConfirmModal/MobileModal.tsx
packages/experience/src/components/ConfirmModal/type.ts
packages/experience/src/containers/VerificationCode/use-identifier-error-alert.ts
packages/experience/src/containers/VerificationCode/use-link-social-confirm-modal.ts
packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
packages/experience/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
packages/experience/src/hooks/use-confirm-modal.ts
packages/experience/src/hooks/use-terms.ts
packages/experience/src/pages/Continue/SetPassword/index.tsx
packages/experience/src/pages/RegisterPassword/index.tsx
packages/experience/src/pages/ResetPassword/index.tsx

This PR refactors the `ConfirmModal` component and its related hooks to support a loading state in modals and applies it to the experience flow.
Notably, it introduces a new callback-based usage pattern for confirm modals, providing greater flexibility in handling modal actions while offering improved user feedback during asynchronous operations.
Key changes:
1. Added support for modal loading state:
- Introduced `isConfirmLoading` prop to `ModalProps` and `ConfirmModalState`
- Updated `AcModal` and `MobileModal` components to handle the loading state
- Confirm button automatically enters loading state during async confirm actions when using callback-style confirm modals
2. Implemented callback-based confirm modal usage:
- Created `CallbackConfirmModalProps` type with `onConfirm` and …

refactor(experience): support and apply modal loading state

---

.changeset/slow-boxes-greet.md
packages/connectors/connector-smtp/src/constant.ts
packages/connectors/connector-smtp/src/index.test.ts
packages/connectors/connector-smtp/src/index.ts
packages/connectors/connector-smtp/src/mock.ts
packages/connectors/connector-smtp/src/types.ts

Enable custom headers for SMTP connector.
This PR resolved [this Discord channel](https://discord.com/channels/965845662535147551/1259220504380969020) and LOG-9591.

feat(connector): enable custom headers for SMTP connector

---

.changeset/cool-otters-unite.md
packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
packages/console/src/utils/connector-form.ts

Fix the bug that Google connector `scope` field can not be unset.
It's because in `parseFormConfig()` method, we removed key-value pairs from form config.
Due to the changes in [PR#6034](https://github.com/logto-io/logto/pull/6034), when submitting the connector config form, the fields from `parseFormConfig()` will be used to overwrite the values in `rawConfig`, where `rawConfig` is the old connector config. In `parseFormConfig()`, if the value of `scope` is an empty string, it would be dropped in the original logic, thus failing to overwrite the old `config.scope` value.
In this fix, we no longer remove key-value pairs corresponding to falsy values in `parseFormConfig()`. Instead, we remove the falsy values after the overwrite is completed.
This PR fixes …

fix(console): fix Google connector `scope` field can not be unset bug

---

packages/core/src/middleware/koa-serve-custom-ui-assets.test.ts
packages/core/src/middleware/koa-serve-custom-ui-assets.ts
packages/core/src/middleware/koa-spa-proxy.test.ts
packages/core/src/middleware/koa-spa-proxy.ts
packages/core/src/tenants/Tenant.ts

Set up proxy rules for those who uploaded custom UI assets for their sign-in experience. The proxy will host the uploaded html assets instead of the pre-built experience UI.
Locally tested

feat(core): set up proxy to host custom ui assets if available

---

packages/experience/src/components/InputFields/InputField/index.module.scss

The autofill style in the browser is ugly, we use a trick to remove it (see the code).

style(experience): remove autofill style from input component

---

packages/console/src/hooks/use-connector-form-config-parser.tsx
packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
packages/console/src/utils/connector-form.ts

Fix passwordless connector tester send failed bug.
This bug was brought in [PR#6254](https://github.com/logto-io/logto/pull/6254), we do not apply falsy key-value pairs removal logics in `parseFormConfig()` (which is a branch of `useConnectorFormConfigParser()` method). Hence we need to manually remove falsy key-values pairs for cases that we explicitly skip this logic.
In order to make the code easier to maintain, we add a switch to control whether we want to skip this falsy value removal logic, and the default value is false. So that this could keep the original logic of other `useConnectorFormConfigParser()` use cases.
Tested locally and thru cloud UI integration tests.

fix(console): fix passwordless connector tester send failed bug

---

.github/workflows/alteration-compatibility-integration-test.yml

using `run-logto` as the requirement may cause unexpected hang up since not all pulls have alterations
⬇️ `alteration-compatibility-conclusion` exits successfully

ci: always set conclusion for alteration tests

---

packages/console/src/onboarding/pages/CreateTenant/index.tsx

Fix a bug that when creating tenant without filling in any invitee emails, there's an unexpected "Invitation sent" toast message popping up.
Locally tested

fix(console): should not toast invitation sent message when creating tenant w/o invitee

---

packages/experience/src/components/InputFields/InputField/index.module.scss
packages/experience/src/components/InputFields/InputField/index.tsx

This PR addresses the issue of input field styling and behavior when browsers autofill the field. By adding specific CSS rules and corresponding JavaScript handling, it's now possible to better detect and respond to autofill events, ensuring that input fields maintain the correct style and size when autofilled.
https://github.com/user-attachments/assets/e86d3b19-87ca-4240-8f99-7b0c4b3a5df5

fix(experience): shrink input field when autofilled by the browser

---

packages/console/src/components/AuditLogTable/components/EventName/index.module.scss
packages/console/src/components/AuditLogTable/components/EventName/index.tsx
packages/console/src/consts/logs.ts
packages/console/src/pages/AuditLogDetails/index.module.scss
packages/console/src/pages/AuditLogDetails/index.tsx

Add "impersonation" tag to the token change event in Audit Logs.

feat(console): add impersonation tag to audit log

---

packages/console/package.json
packages/console/src/pages/Profile/index.tsx
packages/elements/README.md
packages/elements/package.json
packages/elements/src/components/logto-card.ts
packages/elements/src/components/logto-form-card.ts
packages/elements/src/components/logto-theme-provider.ts
packages/elements/src/index.ts
packages/elements/src/locales/en.ts
packages/elements/src/locales/index.ts
packages/elements/src/react.ts
packages/elements/src/utils/css.ts
packages/elements/src/utils/string.ts
packages/elements/src/utils/theme.ts
packages/elements/tsconfig.json
packages/elements/tsup.config.ts
pnpm-lock.yaml

introduce the `@logto/elements` package
we are starting the account center and direct sign-in elements projects, which requires us to deliver a set of ui elements for our developers. per our strategy, these elements should cover the major frameworks, or be framework-agnostic.
so Web Components is definitely a choice. besides, we can use these elements in the Logto Cloud's account center to always be the first user of these elements (i.e. eat your own dog food).
- Web Components: [lit](https://github.com/lit/lit/). lit uses decorators but it's the most popular existing Web Components library. stencil is also cool but is has a [memory leak issue](https://github.com/ionic-team/stencil/issues/3607) since 2022. apparently the company has no enough resource on this project.
- bundling: …

feat: init elements

---

packages/connectors/connector-mock-social/src/index.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/utils.ts
packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
packages/core/src/routes/experience/classes/verifications/social-verification.ts
packages/core/src/routes/experience/classes/verifications/verification-record.ts
packages/core/src/routes/experience/index.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/helpers/connector.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/organization-jti.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
packages/schemas/src/types/interactions.ts

Implement the social and enterprise SSO identity linking and profile syncing logic:
1. Implement the social-related user linking flow.  Per RFC design, the `/experience/identification` endpoint takes an extra `linkSocialIdentity` parameter to indicate that instead of identifying the user using social identity, identify him using the related user and then link the new social identity to his profile. 
2. Implement the enterprise SSO-related user auto-linking flow.  Unlike social, the user needs to resend the identification request with a `linkSocialIdentity` parameter. EnterpriseSso verification record will auto fallback to use related user info to identify the user. SSO identity will be auto-added to the interaction profile. 
3. Also implement the social and SSO sign-in profile syncing …

feat(core,schemas): implement social/sso link and sync logic

---

packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
packages/core/src/routes/subject-token.openapi.json
packages/core/src/routes/subject-token.ts
packages/core/src/routes/swagger/index.ts
packages/integration-tests/src/tests/api/oidc/token-exchange.test.ts
packages/integration-tests/src/tests/api/security.test.ts

Remove feature guard for token exchange (impersonation).

chore: remove feature guard for token exchange

---

packages/core/src/routes/experience/classes/experience-interaction.test.ts
packages/core/src/routes/experience/classes/utils.ts
packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.test.ts
packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/routes/experience/classes/verifications/verification-record.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts
packages/schemas/src/types/interactions.ts

To better infer the return type of the `toUserProfile` method for email or phone identifier type, we split the original `CodeVerification` class into `EmailCodeVerification` and `PhoneCodeVerification`.
- The old `CodeVerification` class has become an internal parent class that is no longer publicly visible. 
- The old `CodeVerification` type has been split into `EmailCodeVerification` and `PhoneCodeVerificaiton` as well. 
Note: By default, ts can not infer the return type correctly based on a given `identifier` with a generic type. 
integration test covered.

refactor(core,schemas): refactor `CodeVerification`

---

packages/core/src/routes/swagger/index.ts

When creating a new organization using the Go SDK that I generated from the OpenAPI spec doc, [go-api-client](https://github.com/mostafa/go-api-client), the `CreateOrganization` endpoint returns a `201 CREATED` HTTP status code and an `Organization` instance with a populated ID field (of the new org). However, the schema doesn't exist in the content key of the response:
This results in a normal `http.Response` object to be returned in Go, instead of an instance of a struct, which is unlike other endpoints that return a processed schema as an object. If the `content` key is added to the response of 201 status codes, it'll result in the processing of the `resp` (below) into a separate instance of the (generated) `Organization` struct and I can access the `newOrg` like an object: …

feat: add content schema to HTTP 201 CREATED messages

---

packages/console/src/components/CustomUiAssetsUploader/index.tsx
packages/console/src/components/FeatureTag/index.tsx
packages/console/src/ds-components/FormField/index.module.scss
packages/console/src/ds-components/FormField/index.tsx
packages/console/src/ds-components/Uploader/FileUploader/index.module.scss
packages/console/src/ds-components/Uploader/FileUploader/index.tsx
packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.module.scss
packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx
packages/phrases/src/locales/en/translation/admin-console/upsell/paywall.ts

Add "Bring your UI" feature paywall in console.
Locally

feat(console,phrases): add bring your UI feature paywall

---

AWESOME.md
README.md

refine content and applause our awesome community
n/a

chore: update README.md

---

packages/console/src/containers/ConsoleContent/Sidebar/index.module.scss

Sometimes the sidebar items are shrunk, when the main content contains wider elements. This PR ensures the sidebar width is not shrunkable.
Locally

fix(console): sidebar width should not be shrunk

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/utils.test.ts
packages/core/src/routes/experience/classes/utils.ts
packages/core/src/routes/experience/classes/validators/password-validator.ts
packages/core/src/routes/experience/classes/validators/profile-validator.ts
packages/core/src/routes/experience/classes/validators/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts

Extract a new `PasswordValidator` that will handle all the new password validation and encryption logic.
Make other validators like `SignInExperienceValidator` and `ProfileValidator` more pure. 
No extra logic added. 
integration test covered

refactor(core): extract password-validator

---

packages/core/src/routes/experience/classes/verifications/social-verification.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts

Fix, should not sync identifier from social identity if the identifier is registered. 

fix(core): should not sync registered identifier from social

---

.scripts/compare-database.js
packages/schemas/alterations/next-1721483240-multiple-app-secrets.ts
packages/schemas/src/consts/system.ts
packages/schemas/tables/application_secrets.sql
packages/schemas/tables/applications.sql

resolve LOG-9672, init table for multiple app secrets. for how they are used, see #6292.
alteration

feat(schemas): multiple app secrets

---

packages/console/src/components/CustomUiAssetsUploader/index.tsx
packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
packages/console/src/pages/SignInExperience/types.ts

Should be able to remove the uploaded zip on error occurred, and removing the zip should not dirty the form.
Previously, I used the parser functions to transform the DB data from and to the form data type, but it seems it's not necessary and causing issues, since setting the form value to `undefined` does not clear the value change in React Hook Form. Therefore, changing it back to its original type definition `CustomUiAssets | null` and it solves the issue naturally.
Locally tested

fix(console): should be able to remove the zip on upload error

---

packages/experience/src/containers/SocialLinkAccount/use-social-link-related-user.ts
packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
packages/experience/src/containers/VerificationCode/use-sign-in-flow-code-verification.ts
packages/experience/src/hooks/use-global-redirect-to.ts
packages/experience/src/hooks/use-password-sign-in.ts
packages/experience/src/hooks/use-send-mfa-payload.ts
packages/experience/src/hooks/use-skip-mfa.ts
packages/experience/src/hooks/use-social-link-account.ts
packages/experience/src/hooks/use-social-register.ts
packages/experience/src/pages/Consent/index.tsx
packages/experience/src/pages/Continue/SetPassword/index.tsx
packages/experience/src/pages/Continue/SetUsername/use-set-username.ts
packages/experience/src/pages/RegisterPassword/index.tsx
packages/experience/src/pages/SocialSignInWebCallback/use-single-sign-on-listener.ts

This PR refactors the global redirect functionality to maintain the loading state of interaction elements (e.g., buttons) until the page is fully redirected after a successful sign-in.
Key changes include:
- Updated useGlobalRedirectTo hook to return an async function that never resolves, ensuring the loading state persists.
- Modified all calls to redirectTo to use await, preventing premature state updates.
- Added detailed comments explaining the purpose and behavior of the useGlobalRedirectTo hook.
- Applied this change across various authentication flows, including social sign-in, password sign-in, MFA, and consent pages.
Test locally and everything works well.

refactor(console): keep button loading before redirecting to sign-in success page

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/helpers.ts
packages/core/src/routes/experience/classes/validators/provision-library.ts
packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/routes/experience/classes/verifications/verification-records-map.ts
packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
packages/core/src/routes/experience/verification-routes/social-verification.ts
packages/core/src/routes/experience/verification-routes/totp-verification.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts

Implement verification records map.
Originally we used TS native `Map`  to store the interaction verification records. However, a map variable can not strictly guard the value type by its key. So in this PR, we implement a `VerificationRecordsMap` wrapper class with key value getter and setter method redefined. 
Also implement a new `getVerificationRecordByTypeAndId` method, which will get the verification record with verification type and id assertions. 
integration test covered

refactor(core): implement verification records map

---

packages/experience/src/containers/SocialSignInList/index.tsx
packages/experience/src/containers/SocialSignInList/use-social.ts
packages/experience/src/hooks/use-global-redirect-to.ts
packages/experience/src/hooks/use-single-sign-on.ts
packages/experience/src/pages/SingleSignOnConnectors/index.tsx

This PR refactors the social sign-in and single sign-on (SSO) functionality to incorporate button loading states, improving user feedback during authentication processes.
By introducing the global redirection mechanism，this PR also fix a bug that the social connector button can be click more than once before 3rd-party sign-in page redirection. (Refer to this Slack thread: https://silverhand-io.slack.com/archives/C05TA6PH1T9/p1721376692062789)
Key changes:
1. Added loading states for social sign-in and SSO buttons
- Implemented in `SocialSignInList` and `SingleSignOnConnectors` components
- Provides visual feedback during authentication processes
2. Enhanced `useGlobalRedirectTo` hook
- Added options for clearing interaction context
- Allows choosing between `window.location.replace` and …

refactor(experience): use button loading for social sign-in

---

packages/core/src/middleware/koa-spa-proxy.ts
packages/demo-app/.parcelrc.arm64
packages/demo-app/index.html
packages/demo-app/package.json
packages/demo-app/tsconfig.json
packages/demo-app/vite.config.ts
pnpm-lock.yaml

[RIP parcel](https://github.com/parcel-bundler/parcel/discussions/9790) (i know the team's answer it's "not dead", but it's a duck death to us)
we loved parcel, bore its moodiness, but the latest version it can work properly stayed in 2.9.3, which released on Jun 25, 2023. after some research, i believe vite is the next cool kid's gear.
locally tested, sign-in/out demo app ok

refactor: use vite for demo app

---

packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials.tsx
packages/core/src/__mocks__/index.ts
packages/core/src/routes/applications/application.test.ts
packages/core/src/routes/applications/application.ts
packages/integration-tests/src/tests/api/application/application.secrets.test.ts
packages/schemas/src/utils/application.ts
packages/schemas/src/utils/index.ts

- generate a default secret for certain application creations
- add `hasSecrets` util to check if an application type should have secrets
updated integration tests accordingly

refactor: generate application secret on creation

---

packages/console/vite.config.ts

console doesn't work for cloud due to the wrong public url. this pull fixes it.
cloud console works

fix(console): use correct public url

---

packages/console/index.html
packages/console/package.json
packages/console/vite.config.ts
packages/demo-app/index.html
packages/experience/vite.config.ts
pnpm-lock.yaml
vite.shared.config.ts

> [!Note]
> React-related package bundling strategy has been updated to a dynamic version with more precise dependency checking. The graph above is out-dated but can still reflect the core concept.
fix favicon paths in demo app and console
locally previewed, mermaid ok, favicon ok

refactor(console, experience): optimize bundling

---

packages/console/src/containers/ConsoleContent/hooks.ts

the `scope` fallback will cause false positive on tenant access assertion, thus an accessible tenant will be removed from the list. sometimes `isLoading` may be `false` but the data is not loaded.
**Original**
```ts
const { scopes = [], isLoading } = useCurrentTenantScopes(); // `scopes` falls back to an empty array
useEffect(() => {
// `scopes` may not be loaded at all, which is `undefined` in the return of `useCurrentTenantScopes()`.
// However, the fallback value `[]` will be used here, while the fetching process is not started yet
// (`isLoading` is `false`) which causes a false positive.
if (isCloud && !isLoading && scopes.length === 0) {
removeTenant(currentTenantId);
navigateTenant('');
}
}, [currentTenantId, isLoading, navigateTenant, removeTenant, scopes.length]);
```
**Now** …

fix(console): check scope only when data is ready

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/libraries/password-validator.ts
packages/core/src/routes/experience/classes/libraries/profile-validator.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/profile.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
packages/core/src/routes/experience/const.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/profile-routes.ts
packages/core/src/routes/experience/types.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
packages/phrases/src/locales/en/errors/session.ts
packages/schemas/src/types/interactions.ts

This PR implements the profile fulfillment and reset password flow.
1. Refactor the original `profile` object in the interaction, and replace it with a new `Profile` class.  Move all the profile validation logic into this new class. 
2. Add the `guardProfileNotExistInCurrentUserAccount` and `getMissingUserProfile` two new methods in the `ProfileValidator`.
3. Implement two new profile API
- `POST /experience/profile` for profile fulfillment use
- `PUT /experience/profile/password` for reset password use
Integration tests will be in a separate PR.
Integration test added

feat(core,schemas): implement profile fulfillment flow

---

packages/integration-tests/src/client/experience/const.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
packages/integration-tests/src/tests/api/experience-api/profile/reset-password.test.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts

Add profile fulfillment integration tests. See PR #6293

test(core): add profile fulfillment integration tests

---

packages/console/src/components/SignInExperiencePreview/index.module.scss
packages/console/src/ds-components/TextInput/index.module.scss
packages/console/src/onboarding/pages/SignInExperience/InspireMe/index.module.scss
packages/console/src/pages/Welcome/index.module.scss

Remove `raw:` scheme from CSS `url()`, as this is previously a parcel specific workaround to load SVG files in CSS without being transformed into React components.
Now since we have migrated to Vite, this is no longer working and has caused issues loading the SVG.
Locally tested

fix(console): css loaded svg should be rendered properly

---

.changeset/fast-rats-talk.md
packages/core/src/routes/role.ts
packages/core/src/utils/SchemaRouter.ts
packages/integration-tests/src/tests/api/hook/WebhookMockServer.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
packages/integration-tests/src/tests/api/hook/utils.ts

We have received a report from our community indicating that the `Organizations.Membership.Updates` webhook event returns status 404 in the API response body.
The root cause is that the webhook payload was built and inserted into the webhook queue ahead of the response body and the status code is properly set. 
Fix this issue, with the integration test updated.

fix(core): fix some webhook api body status 404 bug

---

packages/console/src/components/CustomUiAssetsUploader/index.tsx
packages/console/src/ds-components/Uploader/FileUploader/index.tsx
packages/console/src/hooks/use-api.ts

Make request timeout in the `useApi()` hook configurable and increase custom UI assets upload request timeout to 5 mins.
Since the maximum allowed zip file size is 20MB, it might cause a timeout error on some poor network conditions.
Locally

refactor(console): increase custom ui assets upload timeout to 5 mins

---

packages/core/src/libraries/quota.ts
packages/core/src/libraries/sign-in-experience/index.ts
packages/core/src/middleware/koa-quota-guard.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/connector/index.ts
packages/core/src/routes/domain.ts
packages/core/src/routes/hook.ts
packages/core/src/routes/logto-config/jwt-customizer.ts
packages/core/src/routes/organization-role/index.ts
packages/core/src/routes/organization-scope/index.ts
packages/core/src/routes/organization/index.ts
packages/core/src/routes/resource.scope.ts
packages/core/src/routes/resource.ts
packages/core/src/routes/role.scope.ts
packages/core/src/routes/role.ts
packages/core/src/routes/sign-in-experience/custom-ui-assets/index.ts
packages/core/src/routes/sign-in-experience/index.ts
packages/core/src/routes/sso-connector/index.ts
packages/core/src/routes/subject-token.ts
packages/core/src/test-utils/quota.ts
packages/core/src/utils/subscription/index.ts
packages/core/src/utils/subscription/types.ts

Update the quota guard of management APIs in @logto/core.
Previously, we read the quota limit from Logto cloud API and calculate the quota usage in core.
Per our new pricing model design, we now put quota usage calculation to Logto cloud as well. Logto core now need to get quota limit and quota usage directly via Logto cloud APIs and compare them in-place.
This PR resolves LOG-6610, LOG-7871 and LOG-9650.
N/A
Further integration test should be added at @logto/cloud side.

refactor: update @logto/core quota guard logics

---

packages/console/package.json
packages/console/src/App.tsx
packages/console/src/ds-components/ColorPicker/index.module.scss
packages/console/src/ds-components/ColorPicker/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/NonThirdPartyBrandingForm.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Branding/index.tsx
packages/console/src/pages/SignInExperience/PageContent/Branding/BrandingForm/index.tsx
packages/integration-tests/src/tests/console/sign-in-experience/helpers.ts
pnpm-lock.yaml

This PR addresses issues with the color picker anchor is not draggable on the application branding page, updates the color picker library, and fixes a bug with the "Recalculate" button for dark mode colors.
Changes:
1. Fixed color picker re-rendering issue in application branding page
- Refactored `NonThirdPartyBrandingForm` to use `useFormContext` instead of `useCallback`, this prevents the color palette from closing unexpectedly when color value changed due to unnecessary re-renders
2. Replaced `react-color` with `react-color-palette` as `react-color` is no longer actively maintained
3. Fixed "Recalculate" button not marking form as dirty
- Added `{ shouldDirty: true }` when recalculating dark primary color to properly update form state …

fix(console): dragging anchor in the color picker on application branding page

---

packages/core/src/routes/experience/classes/mfa.ts
packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
packages/integration-tests/src/client/experience/const.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/totp-verification.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/happpy-path.test.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/sad-path.test.ts

implement the mfa binding integration tests

test(core): add the mfa binding integration tests

---

packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/GuideCard/index.module.scss

Add missing unit for `max-height` CSS prop of custom JWT guide card content.
It doesn’t work after using Vite, possibly due to Vite.

style(console): fix custom jwt guide card style

---

packages/console/src/components/CreateConnectorForm/Skeleton/index.module.scss
packages/console/src/components/DetailsPage/Skeleton/index.module.scss
packages/console/src/components/FormCard/Skeleton/index.module.scss
packages/console/src/components/Guide/StepsSkeleton/index.module.scss
packages/console/src/components/Topbar/UserInfo/UserInfoSkeleton/index.module.scss
packages/console/src/containers/ConsoleContent/Sidebar/index.module.scss
packages/console/src/ds-components/FormField/Skeleton.module.scss
packages/console/src/ds-components/Table/Skeleton/index.module.scss
packages/console/src/onboarding/pages/SignInExperience/Skeleton/index.module.scss
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/ProtectedAppSettings/index.module.scss
packages/console/src/pages/CustomizeJwtDetails/PageLoadingSkeleton/index.module.scss
packages/console/src/pages/Dashboard/components/Skeleton/index.module.scss
packages/console/src/pages/GetStarted/ProtectedAppCreationForm/index.module.scss
packages/console/src/pages/Profile/components/Skeleton/index.module.scss
packages/console/src/pages/SignInExperience/Skeleton/index.module.scss
packages/console/src/pages/SigningKeys/SigningKeyFormCard/index.module.scss
packages/experience/src/pages/Consent/OrganizationSelector/OrganizationItem/index.module.scss

move sass mixins to their "expected" position to avoid the [mixed declaration](https://sass-lang.com/documentation/breaking-changes/mixed-decls/) issue. no actual style change should apply.
no deprecation warning on building

refactor(console, experience): solve sass deprecations

---

packages/console/src/components/PlanName/index.tsx
packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx
packages/console/src/types/subscriptions.ts

Fix the plan title for subscription plan selector.
Also need to manually call subscription APIs when needed, in this PR we added such logic when add/delete resource.

fix(console): fix the plan title for subscription plan selector

---

packages/console/src/hooks/use-new-subscription-quota.ts
packages/console/src/hooks/use-new-subscription-scopes-usage.ts
packages/console/src/hooks/use-new-subscription-usage.ts

Add dev guard on new pricing model subscription hooks.
Since Cloud APIs `GET /subscription/{usage,quota}` and `GET /subscription/usage/:entityName/scopes` are also guarded by dev feature switch, we should not call these APIs in prod env, even though we have fallbacks.

fix(console): add dev guard on new pricing model subscription hooks

---

packages/core/src/routes/experience/classes/experience-interaction.test.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/middleware/koa-experience-interaction.ts
packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
packages/integration-tests/src/helpers/client.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/happpy-path.test.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/sad-path.test.ts
packages/integration-tests/src/tests/api/experience-api/interaction.test.ts
packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
packages/integration-tests/src/tests/api/experience-api/profile/reset-password.test.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/verification-code.test.ts

To better guard the experience interaction status, this PR makes the `interactionEvent` property mandatory. 
For new experience interaction initiation endpoint (`PUT /experience`):
- Skip the `koaExperienceInteraction` middleware.
- Create a new `ExperienceInteraction` instance by providing a new `interactionEvent`  value.
For existing experience interaction endpoints:
- User the `koaExperienceInteraction` middleware to retrieve the interaction data from the OIDC provider's interaction storage. 
- The `interactionEvent` property will be strictly guarded.  An `interaction_not_found` error will be thrown if the `interactionResult` data dose not satisfy the experience interaction data guard. 

refactor(core): make the interaction event mandatory

---

.changeset/cyan-bottles-call.md
packages/core/src/routes/swagger/consts.ts
packages/core/src/routes/swagger/index.ts

use the built-in feature for better auth demonstration

refactor(core): improve swagger auth description

---

packages/core/src/middleware/koa-security-headers.ts

allow cloudflare to inject and load scripts in experience. we will add custom csp soon.
need to test in an online environment.

refactor(core): allow cloudflare insights origin in csp

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
packages/core/src/routes/experience/verification-routes/backup-code-verification.ts
packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/new-password-identity-verification.test.ts
packages/phrases/src/locales/en/errors/session.ts
packages/schemas/src/types/interactions.ts

This PR implements a mandatory password guard and fulfillment flow on the user register using a verified email or phone. 
In the latest experience API design, we decoupled the new user creation (insert DB) and profile fulfillment (including bind MFA) into two separate steps.  A user account will be created as long as a valid unique identifier is provided:
- username + password
- verified email
- verified phone
- social
- enterprise sso
A new user account will be created and the user will be identified when sending the `POST /experience/identifier` request.
The user may, later on, provide additional profile and MFA registrations after the account is created. 
At the submit interaction step, we will guard the mandatory profile and MFA fulfillment status.  
In short, a missing profile won't …

feat(core,schemas): add mandatory password guard on register

---

packages/core/src/routes/swagger/index.ts
packages/core/src/routes/swagger/utils/parameters.ts

The `/api/users` (GET) endpoint (and [many others](https://github.com/logto-io/logto/pull/6358#discussion_r1698225283)) returns a list of users and supports [advanced search queries](https://docs.logto.io/docs/recipes/manage-users/advanced-user-search/). However, the OpenAPI spec documentation currently does not include any URL search (query) parameters for this functionality. This PR introduces a new dynamic parameter called `search_params`, defined as an `object` with `string` keys and values. This object will not appear in the generated OpenAPI client. Instead, users can pass a map of strings, which will append these keys and values to the URLSearchParams, thereby enabling advanced user search capabilities.
```go
user, _, err := …
```

feat: add advanced search params to all supported endpoints

---

.changeset/gold-mails-sin.md
.changeset/sweet-rules-hear.md
packages/console/src/assets/docs/guides/web-gpt-plugin/components/AlwaysIssueRefreshToken.tsx
packages/console/src/mdx-components/UriInputField/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/Settings.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/index.tsx
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/utils.ts
packages/core/src/queries/application.ts
packages/core/src/routes/applications/application-custom-data.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/applications/types.ts
packages/integration-tests/src/tests/api/application/application-custom-data.test.ts
packages/integration-tests/src/tests/api/application/application.test.ts
packages/integration-tests/src/tests/console/backchannel-logout.test.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts

Add the custom data JSON editor to the application details page. 
- console: Add a custom data field editor to the application details page
- core: fix the `PATCH /applications/:id` endpoint logic. Should use `replace` mode for all the JSON field data on patch method.
- core: simplify the `PATCH /application/:id/custom-data` API logic. By default `updateApplicationById` uses the `merge` mode for jsonb typed data field. No need to manually merge them ahead. 
- core: remove the `deepPartial`statement from the PATCH application API payload guard.  All the jsonb typed fields must be provided in full data structure. 
Update the integration test
AC test locally

feat(core,console,phrases): add custom data editor to application details page

---

packages/core/src/oidc/init.ts

the content body may be empty when `content-type` has value. we should allow a failed parsing as a temp fix.
locally tested ok

fix(core): allow non-json body type when parsing

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/new-password-identity-verification.test.ts

Make password optional in `NewPasswordIdentity` verification endpoints. So users may pre-validate their `identifier` ahead without providing the password.
Issue:
In our SIE design, the username + password registration flow is split into two forms. User will be asked to provide their username ahead. If the username is valid then jump to the password form. 
If the username is taken throws an error in the current page. 
Updates:
To better support that, we refactor the current `NewPasswordIdentity` verification endpoint, making the `password` field optional. So users may pre-validate their identifiers before specifying the password.  
integration tests updated

refactor(core): make password optional in NewPasswordIdentity

---

packages/console/package.json
packages/console/src/pages/CheckoutSuccessCallback/index.tsx
pnpm-lock.yaml

Get and check `skuId` from checkout session. Since we are migrating to new pricing model and we use `skuId` instead of `planId`. The CIs are expected to fail before we merge and publish [this cloud PR](https://github.com/logto-io/cloud/pull/847).
N/A

refactor(console): get and check `skuId` from checkout session

---

packages/core/src/oidc/init.ts
packages/integration-tests/src/tests/api/oidc/content-type-json.test.ts

update code to make it more reasonable as `querystring.parse` doesn't throw
added integration tests

refactor: add tests for content-type in oidc apis

---

packages/console/src/containers/ConsoleContent/index.tsx

Delay the display of the suspense fallback component (daisy spinner) by 500ms, so that we won't see this much often when navigating between page routes.

refactor(console): delay module loading suspense component display by 500ms

---

packages/console/src/components/Topbar/TenantSelector/index.module.scss

I'm not sure since when this `inline-size: stretch` failed to work, but after investigation it seems this is never a valid CSS property. So I decide to remove it and make the parent div a flex-column container.
https://developer.mozilla.org/en-US/docs/Web/CSS/inline-size
https://css-tricks.com/almanac/properties/i/inline-size/
Locally

fix(console): create tenant button should stretch to full width

---

packages/console/src/hooks/use-api.ts
packages/console/src/hooks/use-subscribe.ts
packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
packages/console/src/pages/ApiResourceDetails/index.tsx

Manually trigger subscription usage/quota update when adding/remove resources or when subscription plan changes.

fix(console): manual update subscription data when add/delete resources

---

packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx

Fix the subscription plan display in tenant dropdown.
Before this change, all non-dev tenant are using the plan of the current selected tenant, which is wrong. Should use the plan ID of the corresponding tenant as SKU ID in for new pricing model. (We use SKU ID to represent the plan ID in new pricing model)
N/A

fix(console): fix the subscription plan display in tenant dropdown

---

packages/core/src/queries/users-roles.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/tests/api/oidc/id-token.test.ts

Should not throw when not adding any new roles to a user when calling `PUT /users/{:userId}/roles` API.
Secured by adding integration test cases.

fix(core): should not throw when not adding any new roles to a user

---

packages/console/src/hooks/use-new-subscription-quota.ts
packages/console/src/hooks/use-new-subscription-scopes-usage.ts
packages/console/src/hooks/use-new-subscription-usage.ts

should not call cloud API when tenant ID is not valid
N/A

fix(console): should not call cloud API when tenant ID is not valid

---

.changeset/thirty-cups-joke.md
packages/core/src/libraries/user.test.ts
packages/core/src/libraries/user.ts
packages/schemas/alterations/next-1722926389-argon2d-argon2id.ts
packages/schemas/tables/users.sql

Add `Argon2d` and `Argon2id` to `UsersPasswordEncryptionMethod`.
They share the same verify function with `Argon2i`, and will be migrated to `Argon2i` upon sign in.
Unit tests, and local tested with the create user endpoint.

feat(core,schemas): add support for argon2d and argon2id

---

packages/core/src/routes/experience/classes/libraries/sentinel-guard.ts
packages/core/src/routes/experience/verification-routes/password-verification.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts

Add Sentinel guard to the password and verification code  verification flow
Test using the experience smoke test after migrating interaction API to experience API.

feat(core): add Sentinel guard

---

packages/core/src/routes/experience/classes/verifications/social-verification.ts
packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
packages/core/src/routes/experience/verification-routes/social-verification.ts
packages/core/src/routes/interaction/utils/social-verification.test.ts
packages/core/src/routes/interaction/utils/social-verification.ts
packages/integration-tests/src/tests/api/experience-api/verifications/social-verification.test.ts
packages/schemas/src/types/interactions.ts

Update the social verification routes to support google one tap authentication. 
For a Google one-tap verification flow, the user can directly call the `/verifications/social/:connectorId/verify` endpoint to create and verify the verification record. 
- change the `verificationId` input parameter to optional
- if the `connectorId` is google connector Id,  and oneTapParams is present, auto-create a SocialVerificaiton record. 
need to test manually

feat(core): support google one tap

---

packages/core/src/routes/experience/classes/experience-interaction.test.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/libraries/profile-validator.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/profile.ts
packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
packages/core/src/routes/experience/classes/verifications/web-authn-verification.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/profile-routes.ts
packages/core/src/routes/experience/types.ts
packages/core/src/routes/experience/verification-routes/new-password-identity-verification.ts
packages/core/src/routes/experience/verification-routes/web-authn-verification.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/username-password.test.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/verification-code.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/new-password-identity-verification.test.ts
packages/schemas/src/types/interactions.ts

This PR refactors the register interaction flow.
In a `register` interaction event:
1. The user can prepend any verified profile through `POST /profile` API. All the pending user info will be stored in the interaction profile data. 
2. Call the `createUser` method to create a new user account using the pending user info stored in the interaction profile.
3. A mandatory profile guard will be applied to make sure all the mandatory user identifiers and verification methods are provided. 
4. Interaction will become `identified` once the new user account is successfully created. The pending interaction profile data will be cleared. 
5. If a `verificationId` parameter is provided, this method will update the pending profile data first using the profile retrieved from the given verification …

refactor(core,schemas): refactor the register flow

---

packages/console/src/components/PlanUsage/ProPlanUsageCard/index.module.scss
packages/console/src/components/PlanUsage/ProPlanUsageCard/index.tsx
packages/console/src/components/PlanUsage/index.module.scss
packages/console/src/components/PlanUsage/index.tsx
packages/console/src/components/PlanUsage/utils.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/usage.ts

add new usage display for pro subscription plan.

feat(console): add new usage display for pro subscription plan

---

packages/core/package.json
packages/core/src/libraries/quota.ts
packages/core/src/middleware/koa-quota-guard.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/hook.ts
packages/core/src/routes/organization-role/index.ts
packages/core/src/routes/organization-scope/index.ts
packages/core/src/routes/organization/index.ts
packages/core/src/routes/resource.ts
packages/core/src/routes/sign-in-experience/index.ts
packages/core/src/routes/sso-connector/index.ts
packages/core/src/test-utils/quota.ts
packages/core/src/utils/subscription/index.ts
packages/core/src/utils/subscription/types.ts
pnpm-lock.yaml

report subscription usage updates. resolved LOG-8866
N/A

feat: report subscription usage updates

---

.changeset/popular-monkeys-complain.md
packages/core/src/oidc/utils.test.ts
packages/core/src/oidc/utils.ts
packages/experience/src/pages/Register/IdentifierRegisterForm/index.tsx
packages/experience/src/pages/SignIn/IdentifierSignInForm/index.tsx
packages/experience/src/pages/SignIn/PasswordSignInForm/index.tsx
packages/schemas/src/consts/oidc.ts

This PR adds support for the `login_hint` parameter in the sign-in URL, allowing pre-filling of the identifier field on sign-in/sign-up forms.
Key implementation details for `login_hint` (already aligned with designers):
1. Only applied on the first screen after initiating login.
2. User's cached input takes priority over `login_hint`.
- `login_hint` is cached as user input if used without modification.
- If modified by the user, the new value is cached instead.
3. Cached identifier input value is unaffected by `login_hint`.
4. The type of `login_hint` (email, phone, or username) is not validated or processed by our system. It's treated as a plain string and placed directly into the identifier input field. This approach leaves the responsibility of managing login_hint types to the …

feat: support `login_hint` params for sign-in url

---

packages/console/src/containers/AppContent/index.tsx
packages/console/src/contexts/SubscriptionDataProvider/index.tsx
packages/console/src/contexts/SubscriptionDataProvider/types.ts
packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
packages/console/src/hooks/use-api.ts
packages/console/src/hooks/use-subscribe.ts

Remove the `useSubscription` dependency from from the `useApi` hook. 
This fixes two issues:
- remove this missing security header error on console page reload 
- avoid unnecessary subscription calls on each page load.
test locally

refactor(console): avoid getSubscription call before authentication

---

packages/console/src/utils/form.ts

The `TimeoutError` from ky is not considered an `HTTPError`. However, the `beforeError` hook in ky only handles HTTP errors, which means we need to wrap every ky request in a `try...catch...` block (see: https://github.com/sindresorhus/ky/issues/508).
Fortunately, in our console, the `TimeoutError` only affects the user experience when submitting forms: the loading state of the submit button won't be reset:
Therefore, we added timeout error handling specifically for form submissions.

fix(console): catch timeout error when submitting form

---

packages/core/src/middleware/koa-slonik-error-handler.ts
packages/core/src/queries/personal-access-tokens.ts
packages/core/src/routes/admin-user/index.ts
packages/core/src/routes/admin-user/personal-access-token.openapi.json
packages/core/src/routes/admin-user/personal-access-token.ts
packages/core/src/tenants/Queries.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/tests/api/admin-user.personal-access-tokens.test.ts
packages/phrases/src/locales/en/errors/user.ts

Implement API: `POST /users/:userId/personal-access-tokens`

feat(core): create PAT

---

packages/console/package.json
packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/TenantStatusTag.tsx
packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
packages/console/src/consts/tenants.ts
packages/core/package.json
packages/core/src/libraries/quota.ts
packages/core/src/utils/subscription/index.ts
pnpm-lock.yaml

1. fix tenant selector dropdown data source, was relying on the current tenant's usage and quota.
2. update the cloud version for console and core
3. update the use of cloud API when guard paywall in core
CI.

fix: update tenant selector dropdown data source

---

packages/experience/src/App.tsx
packages/experience/src/Layout/FirstScreenLayout/index.module.scss
packages/experience/src/Layout/FirstScreenLayout/index.tsx
packages/experience/src/Layout/IdentifierPageLayout/index.module.scss
packages/experience/src/Layout/IdentifierPageLayout/index.tsx
packages/experience/src/Layout/LandingPageLayout/index.tsx
packages/experience/src/components/PageMeta/index.tsx
packages/experience/src/constants/env.ts
packages/experience/src/hooks/use-identifier-params.ts
packages/experience/src/pages/IdentifierSignIn/index.tsx
packages/experience/src/pages/IdentifierSignIn/use-identifier-sign-in-methods.ts
packages/experience/src/types/guard.ts
packages/phrases-experience/src/locales/de/description.ts
packages/phrases-experience/src/locales/en/description.ts
packages/phrases-experience/src/locales/es/description.ts
packages/phrases-experience/src/locales/fr/description.ts
packages/phrases-experience/src/locales/it/description.ts
packages/phrases-experience/src/locales/ja/description.ts
packages/phrases-experience/src/locales/ko/description.ts
packages/phrases-experience/src/locales/pl-pl/description.ts
packages/phrases-experience/src/locales/pt-br/description.ts
packages/phrases-experience/src/locales/pt-pt/description.ts
packages/phrases-experience/src/locales/ru/description.ts
packages/phrases-experience/src/locales/tr-tr/description.ts
packages/phrases-experience/src/locales/zh-cn/description.ts
packages/phrases-experience/src/locales/zh-hk/description.ts
packages/phrases-experience/src/locales/zh-tw/description.ts
packages/schemas/src/consts/experience.ts

This PR introduces a new identifier-based sign-in feature and refactors the first screen layout, improving the flexibility and consistency of our authentication flow.
- Identifier-based Sign-in:
- Add new `IdentifierSignIn` page allowing users to sign in using email, phone, or username
- Dynamic support for multiple identifier types based on configured sign-in methods
- Fallback to all sign-in methods if provided identifiers are not supported
- First Screen Layout Refactoring:
- Introduced new `FirstScreenLayout` component for consistent styling across initial screens
- Refactored `LandingPageLayout` to use `FirstScreenLayout`, improving code reuse
- New `IdentifierPageLayout` built on top of `FirstScreenLayout` for identifier-related pages
- Identifier URL parameter handling:
- Added …

feat(experience): add identifier sign-in page

---

packages/experience/src/App.tsx
packages/experience/src/pages/IdentifierRegister/index.tsx
packages/experience/src/pages/IdentifierRegister/use-identifier-sign-up-methods.ts
packages/phrases-experience/src/locales/de/description.ts
packages/phrases-experience/src/locales/en/description.ts
packages/phrases-experience/src/locales/es/description.ts
packages/phrases-experience/src/locales/fr/description.ts
packages/phrases-experience/src/locales/it/description.ts
packages/phrases-experience/src/locales/ja/description.ts
packages/phrases-experience/src/locales/ko/description.ts
packages/phrases-experience/src/locales/pl-pl/description.ts
packages/phrases-experience/src/locales/pt-br/description.ts
packages/phrases-experience/src/locales/pt-pt/description.ts
packages/phrases-experience/src/locales/ru/description.ts
packages/phrases-experience/src/locales/tr-tr/description.ts
packages/phrases-experience/src/locales/zh-cn/description.ts
packages/phrases-experience/src/locales/zh-hk/description.ts
packages/phrases-experience/src/locales/zh-tw/description.ts
packages/schemas/src/consts/experience.ts

This PR adds a new “identifier register” page to the experience.
- Created new `IdentifierRegister` page and related logic.
- Added a new route in App.tsx.
- Added new translations for multiple languages.
- Updated `experience.ts` constants file with new `identifierRegister` route.
This feature allows users to register using various identifier methods in the URL (e.g., email, phone number), providing a more flexible registration process.
- remove dev feature flag and add changeset
- integration tests
Test locally.

feat(experience): add identifier register page

---

packages/console/package.json
packages/console/src/cloud/types/router.ts
packages/console/src/components/MauExceededModal/index.tsx
packages/console/src/components/PlanUsage/index.tsx
packages/console/src/consts/tenants.ts
packages/console/src/contexts/SubscriptionDataProvider/types.ts
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
packages/console/src/pages/TenantSettings/Subscription/index.tsx
pnpm-lock.yaml

separate subscription based usage.

refactor(console): separate subscription based usage

---

packages/console/src/cloud/AppRoutes.tsx
packages/console/src/components/DelayedSuspenseFallback/index.module.scss
packages/console/src/components/DelayedSuspenseFallback/index.tsx
packages/console/src/containers/ConsoleContent/index.tsx

Should be able to edit password and email in profile in Logto Cloud.
Currently all the user fields that requires a fullscreen popup modal in profile page are broken, due to a `lazyLoad` refactoring. Root cause is the Cloud routes lack of a `<Suspense></Suspense>` wrapper.
The OSS distributions are not affected.
Locally tested

fix(console): should be able to edit password and email in profile

---

packages/core/src/routes/experience/anonymous-routes/index.openapi.json
packages/core/src/routes/experience/anonymous-routes/index.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/middleware/koa-experience-interaction.ts
packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.openapi.json
packages/core/src/routes/experience/verification-routes/enterprise-sso-verification.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/verifications/enterprise-sso-verification.test.ts

This PR redesigns the `GET /experience/verification/sso/connectors` endpoint.
The previous endpoint was defined under the /experience/verification path, which requires an active `ExperienceInteraction` instance in the current session.
During testing of the latest Experience API, we identified a bug: SSO connector fetch requests are being triggered without the initiation of an `ExperienceInteraction` (`PUT /experience`). These requests should not be dependent on an `ExperienceInteraction`.
Extract the existing GET /experience/verification/sso/connectors endpoint and relocate it to a new, anonymous route: `GET /experience/sso-connectors`. Whitelist this endpoint from `ExperienceInteraction` validation, allowing it to be triggered anytime without requiring an active experience interaction. …

refactor(core): redesign get sso connectors endpoint

---

packages/core/src/routes/experience/verification-routes/social-verification.ts

Fix the Google one tap validation error.  If the social verification request is from a google one tap callback. The input `validationId` is undefined. 
Should always return the latest verificaitonId returned from the update/created verification record.

fix(core): fix google one tap validation error

---

packages/core/src/oidc/utils.test.ts
packages/core/src/oidc/utils.ts
packages/experience/src/hooks/use-identifier-params.test.ts
packages/experience/src/hooks/use-identifier-params.ts
packages/schemas/src/consts/experience.ts
packages/schemas/src/consts/oidc.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts

This PR implements support for identifier page related parameters in the sign-in URL. It introduces new functionality for handling identifier-based sign-in and registration flows.
- Added support for new `FirstScreen` enum values:
- `IdentifierSignIn`
- `IdentifierRegister`
- `SingleSignOn`
- Introduced a new `Identifier` parameter in `ExtraParamsKey` enum.
- Updated `buildLoginPromptUrl` function to handle the new identifier parameter.
- Update the `useIdentifierParams` hook for parsing and validating identifier parameters from URL search params.
- Added and updated unit tests to cover new functionality.
- Extended schema definitions to include the new identifier-related types and guards.
- Remove the dev feature flag
- Add intergation tests for all identifier page rendering.
Test …

feat(core,experience,schemas): support identifier page related params for sign-in url

---

packages/console/src/components/AuditLogTable/components/EventName/index.tsx
packages/console/src/components/AuditLogTable/components/EventName/utils.ts
packages/console/src/components/AuditLogTable/index.tsx
packages/console/src/pages/AuditLogDetails/index.tsx
packages/schemas/src/foundations/jsonb-types/logs.ts

Fix the "impersonation" tag display condition:
1. the event key is token exchange
2. the subject token type is access token (new)
Because we are adding "PAT" feature that also uses the token exchange type, so the condition should be more specific.
Local tested.

fix(console): fix impersonation tag in audit log

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/index.module.scss
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/index.tsx

bring back accidentally deleted css file.
Before this change, the css file was deleted in [previous PR](https://github.com/logto-io/logto/pull/6466), which is unexpected. Bring the css file back to fix.

fix(console): bring back accidentally deleted css file

---

packages/console/src/pages/TenantSettings/TenantMembers/Invitations/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx

manually trigger usage api updates when
1. new invitations sent
2. tenant members deleted
3. pending invitations revoked
N/A

fix(console): manually trigger usage api updates

---

packages/experience/src/components/InputFields/SmartInputField/use-smart-input-field.ts
packages/experience/src/components/InputFields/SmartInputField/utils.ts

The initial `SmartInputField` could only determine the correct type when user is inputting in the input field.
When the `SmartInputField` has a `defaultValue`, its initial type will be `undefined`, which causes an error during validation of the default value due to the incorrect type.
This PR fixes the issue by inferring the initial type of the `SmartInputField` from the `defaultValue`.
Key changes:
- Refactored the original `detectInputType` function into a function that determines the type of the identifier.
- Applied the new function to the original logic and used it to compute the default type for the smart input field.
Test locally and all UT and IT passed.

fix(experience): smart input field should have correct initial type

---

.changeset/hip-cats-destroy.md
packages/connectors/connector-wecom/src/constant.ts
packages/console/src/components/CreateConnectorForm/Footer/index.tsx
packages/console/src/components/CreateConnectorForm/index.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
packages/core/src/routes/connector/index.openapi.json
packages/core/src/routes/connector/index.ts

Fix following issues:
1. wecom connector should have platform to be universal (`null` platform is only for passwordless connectors, thanks to @xiaoyijun for reporting this issue)
2. should show quota guard footer on connector creation modal for standard connectors, although we removed quota guard for standard connectors, but they will still be guarded by `socailConnectorsLimit`
3. add 403 response code for `POST /connectors` API since 403 could be reported by backend API level quota guard

fix(console,core,connector): fix display issues and POST /connectors API code guard

---

package.json
pnpm-lock.yaml

The monorepo root package.json contains a dependency referece to the newly added "@logto/translate" package. However, when referecing the dependency, a semver number `0.0.0` was used, and has caused a build error in CI of the master branch.
This PR removes the unnecessary trailing semver, and directly use `workspace:^` instead.
Master CI should be successful. Pending for further verification.

fix: translate cli workspace dependency reference

---

packages/console/src/pages/TenantSettings/TenantMembers/Members/index.tsx

manually trigger usage api updates on org member deletion.

fix(console): manually trigger usage api updates on org member deletion

---

packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.module.scss
packages/console/src/containers/AppContent/TenantNotificationContainer/CreateProductionTenantBanner/index.tsx
packages/console/src/scss/modal.module.scss
packages/console/src/scss/normalized.scss

Fixed a bug that cannot invite admin user, which is a regression bug caused by incorrect z-index config.
Currently all react-modal portals have been set at the same z-index value (#5948), as a result, the children elements z-index does not function.
This PR removes the global CSS class that sets the z-index value to all react-modal portals, and fix the #5948 by providing an absolute position parent. This way, the z-index will be applied to children element and won't affect other modal portals.
- The production banner does not show on top of modal dialogs
- The invite admin confirm modal can be displayed on top of the invite modal

fix(console): fix console z index issue on modals and banners

---

packages/schemas/alterations/next-1724229102-add-report-sub-updates-cloud-scope.ts

update alteration script
Context:
This alteration script is to add scope to the cloud API resource of admin tenant and assign this scope to a specific role, so that all the m2m apps which are assigned with this role can get this scope.
But the admin tenant only exists in the core DB corresponding to the region where the cloud DB is located (EU region), so in other regions, the corresponding cloud API resource cannot be found, and the alteration should be completed directly at this time.
In the original alteration script, the existence of cloud API resources in all regions of core DB is mandatory, which is incorrect. In this PR, we fix this problem and judge whether it is EU region by whether the cloud API resource exists. For the core DB without cloud API resource in non EU region, the …

fix: make alteration script compatible for core DB in all regions

---

packages/console/src/pages/UserDetails/UserSettings/components/PersonalAccessTokens/index.tsx
packages/phrases/src/locales/en/translation/admin-console/user-details.ts

Add a documentation link to personal access tokens.

feat(console): add doc link of pat

---

packages/core/src/oidc/extra-token-claims.ts
packages/core/src/oidc/grants/token-exchange/account.ts
packages/core/src/oidc/grants/token-exchange/index.test.ts
packages/core/src/oidc/grants/token-exchange/index.ts

Remove "grantId" value of the access token granted by "token exchange".
Token exchange is a special grant type that do not have a "grant" object, because it bypass the normal authentication flow. Normally, a "grant" object is genrated when the user passed the authentication check in sign in flow.
Previously, we assign a fake grantId to the access token, that is meaningless and cause introspection failure, see the code of `node-oidc-provider`, it'll check if the grant is valid if "grantId" is present:
```
if (token.grantId) {
const grant = await ctx.oidc.provider.Grant.find(token.grantId, {
ignoreExpiration: true,
});
if (!grant) return;
if (grant.isExpired) return;
if (grant.clientId !== token.clientId) return;
if (grant.accountId !== token.accountId) return;
ctx.oidc.entity('Grant', …
```

fix(core): remove grant id of token exchange

---

packages/cli/src/commands/tunnel/index.ts
packages/cli/src/commands/tunnel/utils.ts

Some improves on the "tunnel" CLI.
- Support port in-use detection and automatically retry with increased port number
- Add more informative logs in the CLI output

refactor(cli): show more info and add port in-use detection

---

packages/core/src/oidc/grants/token-exchange/index.ts
packages/integration-tests/src/tests/api/oidc/token-exchange/personal-access-token.test.ts

Per discussion, remove the requirement of secured app when exchanging token with PAT.

fix(core): remove the requirement of secured app for PAT

---

packages/core/src/oidc/utils.test.ts
packages/core/src/oidc/utils.ts
packages/experience/src/App.tsx
packages/experience/src/Layout/FocusedAuthPageLayout/index.tsx
packages/experience/src/hooks/use-send-verification-code.ts
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/experience/src/pages/ResetPasswordLanding/index.tsx
packages/experience/src/pages/ResetPasswordLanding/use-reset-password-methods.ts
packages/integration-tests/src/tests/experience/first-screen.test.ts
packages/integration-tests/src/ui-helpers/expect-experience.ts
packages/phrases-experience/src/locales/de/description.ts
packages/phrases-experience/src/locales/en/description.ts
packages/phrases-experience/src/locales/es/description.ts
packages/phrases-experience/src/locales/fr/description.ts
packages/phrases-experience/src/locales/it/description.ts
packages/phrases-experience/src/locales/ja/description.ts
packages/phrases-experience/src/locales/ko/description.ts
packages/phrases-experience/src/locales/pl-pl/description.ts
packages/phrases-experience/src/locales/pt-br/description.ts
packages/phrases-experience/src/locales/pt-pt/description.ts
packages/phrases-experience/src/locales/ru/description.ts
packages/phrases-experience/src/locales/tr-tr/description.ts
packages/phrases-experience/src/locales/zh-cn/description.ts
packages/phrases-experience/src/locales/zh-hk/description.ts
packages/phrases-experience/src/locales/zh-tw/description.ts
packages/schemas/src/consts/experience.ts
packages/schemas/src/consts/oidc.ts

Add a reset password first screen page for the dedicated password reset process, distinct from the password reset step in the regular login flow.
As the entry point for the password reset flow, it allows users to initiate the password reset process directly.
Developers can specify this page as the initial screen of the user's login flow by setting the `first_screen=reset_password` parameter in the authentication flow.
Typical use cases include:
- When system administrators create accounts for new users and require them to update their password upon first login.
- When users initiate an authentication flow with reset password as the first screen by clicking a link in a password reset email.
This approach ensures that users can seamlessly enter the password reset flow in specific scenarios, …

feat(experience): add reset password first screen

---

packages/console/src/App.tsx
packages/console/src/pages/Profile/containers/VerificationCodeModal/index.tsx
packages/core/src/libraries/verification-status.ts
packages/core/src/queries/verification-status.ts
packages/core/src/routes-me/user.ts
packages/core/src/routes-me/verification-code.ts
packages/schemas/alterations/next-1724316971-add-verified-identifier-to-verification-statuses.ts
packages/schemas/tables/verification_statuses.sql

fix(core,schemas): check email verification status in me api

---

packages/experience/src/components/IdentifierRegisterForm/index.test.tsx
packages/experience/src/components/IdentifierRegisterForm/index.tsx
packages/experience/src/components/IdentifierSignInForm/index.tsx
packages/experience/src/components/InputFields/SmartInputField/index.tsx
packages/experience/src/components/InputFields/SmartInputField/use-smart-input-field.ts
packages/experience/src/components/InputFields/SmartInputField/utils.ts
packages/experience/src/components/PasswordSignInForm/index.tsx
packages/experience/src/pages/Continue/IdentifierProfileForm/index.tsx
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.test.tsx
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/experience/src/pages/ForgotPassword/index.tsx
packages/experience/src/pages/Register/index.test.tsx
packages/integration-tests/src/tests/console/bootstrap.test.ts
packages/integration-tests/src/tests/experience/bootstrap.test.ts
packages/integration-tests/src/tests/experience/identifier-input-cache.test.ts
packages/integration-tests/src/tests/experience/mfa/backup-code/index.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/passcode-identifier-flow.test.ts
packages/integration-tests/src/tests/experience/mfa/totp/password-identifier-flow.test.ts
packages/integration-tests/src/tests/experience/mfa/user-controlled.test.ts
packages/integration-tests/src/tests/experience/mfa/webauthn/index.test.ts
packages/integration-tests/src/tests/experience/password-policy.test.ts

Now the `SmartInputField`'s default type can be inferred from the `defaultValue`, so we don't need to pass a `defaultType` to this component. This PR remove the redundant `defaultType` for the component.
This PR also rename the `input` component name from `id` to `identifier` on register pages to keep align with other pages.
Test locally and all IT an UT passed.

refactor(experience): remove redundant `defaultType` prop for `SmartInputField`

---

packages/experience/src/Providers/UserInteractionContextProvider/UserInteractionContext.tsx
packages/experience/src/Providers/UserInteractionContextProvider/index.tsx
packages/experience/src/hooks/use-prefilled-identifier.ts
packages/experience/src/pages/ForgotPassword/index.tsx
packages/experience/src/pages/ResetPassword/index.tsx
packages/experience/src/pages/ResetPasswordLanding/index.tsx

This PR supports caching input identifier for the reset password first screen page and also introduces several changes to the `usePrefilledIdentifier` hook to support retrieving cached forgot password identifier. and related components, aimed at optimizing the handling of user input for identifier types during forgot password flows.
1. **Refactor of `UserInteractionContext`:**
- Removed the `getIdentifierInputValueByTypes` method from the context, simplifying the context's API. This method was previously responsible for retrieving cached identifier values excluding forgot password identifier.
2. **Introduction of `getIdentifierInputValueByTypes` Function:**
- Moved the `getIdentifierInputValueByTypes` logic to a standalone utility function in the `use-prefilled-identifier` hook. This …

refactor(experience): cache input identifier for reset password first screen

---

packages/experience/package.json
pnpm-lock.yaml

Upgrade react-hook-form to `v7.53.0` so that we can retrieve the form’s `defaultValues` from `formState`.
None.

chore(experience): upgrade react-hook-form

---

packages/experience/src/components/IdentifierRegisterForm/index.tsx
packages/experience/src/components/IdentifierSignInForm/index.tsx
packages/experience/src/components/PasswordSignInForm/index.tsx
packages/experience/src/components/SingleSignOnForm/index.tsx
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx

Should apply form's default value to the smart input value rather than the current field value.
Test locally.

fix(experience): apply form default value to smart input filed

---

.changeset/tiny-fishes-bake.md
packages/core/src/middleware/koa-oidc-error-handler.ts

Add `error_code_key` query string param check in the `koaOidcErrorHandler`.
By default, we use the `code` key to represent the error code in the Logto API requests' error response body. However, it has been reported that in Google, `code` is considered a reserved OIDC key and is not allowed in any error response body. Therefore, we need to offer a way to override the default `code` key.
To address this, we are introducing a new query parameter, `error_code_key`, which allows developers to customize the error code key.
Defaul:
```
http://localhost:3001/oidc/token
```
```json
{
"code": "oidc.invalid_client",
"message": "An OIDC error occurred: oidc.invalid_client.",
"error": "invalid_client",
"error_description": "invalid client test"
}
```
With query param:
``` …
```

feat(core): add `error_code_key` query string param

---

.changeset/tiny-fishes-bake.md
packages/core/src/middleware/koa-oidc-error-handler.ts

Refactor oidc error response query param. Replace the query param with `parse_error`.
If set to false, do not parse the error detail, directly return.
Test locally

refactor(core): refactor oidc error response query param

---

packages/experience/src/pages/ResetPassword/index.tsx

Per offline discussion with @Rany0101 , we should not carry the identifier used in reset password flow to sign-in page.
Test locally.

fix(experience): avoid carring identifer from reset password page to sign-in page

---

packages/console/src/components/SkuName/index.tsx
packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
packages/console/src/types/subscriptions.ts
packages/phrases/src/locales/de/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/index.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/index.ts

Fixing following issues:
1. should use Basic Logto SKUs to validate the tenant's `planId`
2. support tenant plan display for admin and dev tenants
N/A

chore(console): should use SKU to filter tenant dropdown and add display of dev/admin plan

---

packages/core/src/libraries/jwt-customizer.ts
packages/core/src/oidc/extra-token-claims.ts
packages/core/src/routes/logto-config/jwt-customizer.ts
packages/core/src/utils/custom-jwt/index.ts
packages/integration-tests/src/__mocks__/jwt-customizer.ts
packages/integration-tests/src/tests/api/logto-config.test.ts
packages/schemas/src/types/logto-config/jwt-customizer.ts

Add API context to the customJwt script payload, including the new `denyAccess` API.
- Only localVM environment jwtCustomizer is updated in this PR. Cloud `azureFunction` updates will be made in the cloud repo.
example: 
```ts
const getCustomJwtClaims = async ({ token, context, environmentVariables, api }) => {
api.denyAccess('You are not allowed to access this resource.');
};
```
test locally

feat(core): add denyAccess api context to customJwt script

---

.changeset/polite-bats-learn.md
packages/core/src/__mocks__/user.ts
packages/core/src/routes/admin-user/basics.ts
packages/core/src/routes/admin-user/search.test.ts
packages/core/src/routes/admin-user/search.ts
packages/core/src/routes/admin-user/social.ts
packages/core/src/routes/role.user.ts
packages/core/src/utils/user.ts
packages/integration-tests/src/helpers/user.ts
packages/integration-tests/src/tests/api/admin-user.test.ts
packages/integration-tests/src/tests/api/organization/organization-user.test.ts

In the original implementation, `hasPassword` field is mentioned in the API doc, but missing in API response.
This PR fix this issue.
Test locally and all UT & IT passed.

fix(core): add `hasPassword` field to user API response

---

.changeset/modern-ghosts-sin.md
packages/tunnel/src/commands/deploy/index.ts
packages/tunnel/src/commands/deploy/types.ts
packages/tunnel/src/commands/deploy/utils.ts

New feature:
- Support `--zip` option in `deploy` command
If `--zip` or `--zip-path` is specified, the cli will directly read and upload the zip file to Cloud, instead of zipping first.
This PR also includes following improvements:
- Filter hidden files and directories when creating zip
- Improve error handling
Locally tested

feat(tunnel): support zip option in deploy command

---

.changeset/violet-beds-yawn.md
packages/connectors/connector-oauth2/README.md
packages/connectors/connector-oauth2/package.json
packages/connectors/connector-oauth2/src/utils.test.ts
packages/connectors/connector-oauth2/src/utils.ts

This MR introduces support for nested properties in the OAuth connector for Logto, allowing users to map and retrieve nested attributes from social vendor profiles. This enhancement builds upon the existing functionality, enabling more flexible and comprehensive user profile mappings.
- Updated the `userProfileMapping` function to handle nested properties.
- Modified the `ProfileMap` type to support nested attribute paths.
- Added unit tests to verify the correct mapping of nested properties.
- Updated the README to include documentation and examples for nested attribute mappings.
Imagine the social vendor user info returns something like 
```json
{
"id": "123456",
"contact": {
"email": "octcat@github.com",
"phone": "123-456-7890"
},
"details": {
"name": "Oct Cat",
"avatar": {
"url": …
```

feat: add support for nested attribute profile mapping

---

.scripts/compare-database.js

In `compare-database.js` script, `autoCompare(a, b)` can not compare the value of two objects, as a result, the sorting is not stable if it relies on object-typed values. (A lot of changes were made by code formatter)
This PR resolves LOG-9970.
Tested using CI in @logto/cloud, the [issue](https://github.com/logto-io/cloud/actions/runs/10771622211/job/29867539531?pr=943) resolved.

fix: fix object comparison util method used in DB alteration CI

---

.changeset/proud-books-itch.md
packages/experience-legacy/src/containers/SocialLinkAccount/index.tsx
packages/experience-legacy/src/hooks/use-social-register.ts
packages/experience-legacy/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
packages/experience/src/containers/SocialLinkAccount/index.tsx
packages/experience/src/hooks/use-social-register.ts
packages/experience/src/pages/SocialSignInWebCallback/use-social-sign-in-listener.ts
packages/integration-tests/src/tests/experience/automatic-account-linking.test.ts

Allow link new social identity to an existing user account when registration is disabled.
Sign-in with a social identity that does not have an existing user account will throw an `identity_not_exist` error. When the registration is disabled, the error message will be shown, the user will not be able to create a new account or link the social identity to an existing account via verified email or phone number.
When the registration is disabled, if a related user account is found, the user should be able to link the social identity to an existing account via a verified email or phone number.
When the registration is disabled:
- Show `identity_not_exist` error message if no related user account is found.
- Automatically link the social identity to the existing account if a related user …

fix(experience): allow link social account on sign-in only mode

---

packages/core/src/middleware/koa-auth/index.test.ts
packages/core/src/middleware/koa-auth/index.ts
packages/core/src/middleware/koa-auth/koa-oidc-auth.test.ts
packages/core/src/middleware/koa-auth/koa-oidc-auth.ts
packages/core/src/middleware/koa-auth/types.ts
packages/core/src/middleware/koa-auth/utils.ts
packages/core/src/routes/init.ts
packages/core/src/routes/profile/index.ts
packages/core/src/routes/types.ts
packages/core/src/utils/test-utils.ts

Add new middleware `koaOidcAuth`, similar to `koaAuth`, but consume opaque access token.
Will be used in profile API and verification API.
Unit tests.

feat(core): add koa oidc auth for profile API

---

.changeset/yellow-yaks-bathe.md
packages/core/src/routes-me/user.ts
packages/core/src/routes/sign-in-experience/index.openapi.json
packages/core/src/routes/sign-in-experience/index.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/core/src/utils/password.ts
packages/integration-tests/src/helpers/admin-tenant.ts
packages/integration-tests/src/tests/api/me.test.ts
packages/integration-tests/src/tests/api/sign-in-experience.test.ts

Add `POST /api/sign-in-exp/default/check-password` API to check if the password meets the password policy configured in the default sign-in experience. See changeset for details.
A lot of integration tests added.

feat(core): password checking api

---

packages/core/src/routes-me/user.ts

Allow no password user to set password in Console profile. Should skip the verification status check in this scenario.
Locally and CI

fix(core): allow no password user to set password in console profile

---

packages/core/src/routes/experience/profile-routes.openapi.json
packages/core/src/routes/experience/verification-routes/verification-code.openapi.json
packages/core/src/routes/swagger/utils/general.ts

Avoid duplicate operationId between Management API and Experience API. 
Add the duplicate operationId guard. 
test locally

fix(core): avoid duplicate operationId

---

packages/console/src/components/PlanUsage/index.tsx
packages/console/src/components/SkuName/index.tsx
packages/console/src/pages/Mfa/MfaForm/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.module.scss
packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx

fix enterprise console issues
1. add margin-top for inline notifications on settings -> Plan and billing tab
2. org usage display card follow `usage / limit` scheme (resolves LOG-9992)
3. fix MFA config switch disabled bug (for enterprise plan) (resolves LOG-9993)
4. should not display SKU ID for enterprise plan (resolves LOG-9999)

fix: fix enterprise console issues

---

packages/schemas/alterations/next-1725971571-add-verification-record.ts
packages/schemas/src/foundations/jsonb-types/index.ts
packages/schemas/src/foundations/jsonb-types/verification-records.ts
packages/schemas/src/types/interactions.ts
packages/schemas/src/types/log/interaction.ts
packages/schemas/tables/verification_records.sql

Add `verification_records` table, this table will be used to store verification records, and we'll migrate the `VerificationRecord` in experience API to use this table as well.
The type of `data` is intended to set to `JsonObject`, this can avoid complex typing. Because this field can not be used directly, it must be parsed according to the type, and to be used to rebuild verification class.
N/A

feat(schemas): add verification record table

---

packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
packages/console/src/components/CreateConnectorForm/Footer/index.tsx
packages/console/src/components/MauExceededModal/index.tsx
packages/console/src/components/SkuName/index.tsx
packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx

refactor `<SkuName />` component to make `isEnterprisePlan` as input
Since in previous implementation, the `isEnterprisePlan` value is got from the current tenant's context, which is used globally. In fact, `<SkuName />` can be used for other tenants or invoice items which has nothing to do with the current tenant's `isEnterprisePlan` context.
N/A

refactor: refactor SkuName component to make isEnterprisePlan as input

---

packages/integration-tests/src/api/connector.ts
packages/integration-tests/src/api/sign-in-experience.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/client/index.ts
packages/integration-tests/src/helpers/admin-tenant.ts
packages/integration-tests/src/helpers/client.ts
packages/integration-tests/src/helpers/connector.ts
packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/api/me.test.ts

Add new integration test for `/me/password` API. Should allow no-password user (from social sign-up) to set password. (Following-up #6572)
Locally passed.

test: add integration test for no password user setting password

---

packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/experience/bootstrap.test.ts

Add UI integration tests for "lang" and "dir" html attributes in experience.
For example:
- English: lang="en" dir="ltr"
- Arbic: lang="ar" dir="rtl"
CI

test: add ui integration test for lang and dir html attributes in experience

---

.changeset/witty-rivers-laugh.md
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/profile.ts
packages/core/src/routes/experience/profile-routes.openapi.json
packages/integration-tests/src/tests/api/experience-api/register-interaction/enterprise-sso.test.ts

Add enterprise SSO-only email guard to registration and profile-fulfilling flow. 
- Creating a new user with a verification record containing an SSO-only email identifier should return a 422 `RequestError` with the error code `session.sso_required`.
- Updating a user profile with an SSO-only email identifier should return a 422 `RequestError` with the error code `session.sso_required`.
test locally

fix(core): add sso only email guard

---

packages/console/src/ds-components/Button/index.tsx

When the button is in a loading state, the CSS hides the internal span elements. However, since the custom title element is not wrapped in a span, the button’s title remains visible in certain cases. This PR fixes the issue by ensuring the title is properly hidden during loading.

style(console): hide button title when loading

---

packages/experience-legacy/src/containers/SocialLinkAccount/index.tsx
packages/experience-legacy/src/hooks/use-webauthn-operation.ts
packages/experience/src/containers/SocialLinkAccount/index.tsx
packages/experience/src/hooks/use-webauthn-operation.ts

Fixed two issues:
- The loading state of the button on the ‘link account’ page was previously missing, and it has now been added.
- The sendMfaPayload method was previously called asynchronously, which caused the function call to end before the network processing was completed, resulting in the button’s loading state disappearing too early on the page.”

fix(experience): add missing button loading state

---

packages/console/src/components/BillInfo/index.tsx
packages/console/src/components/PlanUsage/index.tsx

Fixing 2 enterprise plan console issues:
1. fix PlanUsage not displayed for enterprise plan w/o subscription
2. hide next billing hint for enterprise plans
N/A

fix(console): fix PlanUsage not displayed for enterprise plan w/o subscription

---

packages/console/src/hooks/use-connector-form-config-parser.tsx
packages/console/src/pages/ConnectorDetails/ConnectorContent/index.tsx
packages/console/src/utils/connector-form.ts

This reverts commit [6963192ac5cf2285826799a34a20c9efaa1f343a.](https://github.com/logto-io/logto/pull/6268), which causes the bug that users can not update a field to empty string, bacause the field will be removed.
Local tested, a field can now be updated to empty.

fix(console): fix empty string update of connector config form

---

packages/console/src/components/PlanUsage/index.tsx
packages/phrases/src/locales/en/translation/admin-console/subscription/usage.ts

fix console resource usage tooltip.
1. do not show tooltip when usage is number-typed and basic quota is unlimited
2. show different tooltip for org usage card when org limit is number typed

fix(console): fix console resource usage tooltip

---

.changeset/tasty-kings-fetch.md
.changeset/tricky-mice-pay.md
packages/core/src/middleware/koa-serve-custom-ui-assets.test.ts
packages/core/src/middleware/koa-serve-custom-ui-assets.ts
packages/core/src/utils/storage/azure-storage.ts
packages/phrases/src/locales/en/errors/request.ts
packages/toolkit/core-kit/src/utils/url.test.ts
packages/toolkit/core-kit/src/utils/url.ts
packages/tunnel/src/commands/tunnel/utils.test.ts
packages/tunnel/src/commands/tunnel/utils.ts

Fix an issue that prevent MP4 video from playing in custom sign-in pages on Safari. (fixes #6623)
Safari uses "range requests" to load video data from server, and the response is partially read from the destination file, with a status code 206 instead of 200.
Tested on both Chrome and Safari, both worked.
Also tested the tunnel CLI hosting local html assets, worked.

fix(core,tunnel,phrases): support range requests when hosting custom ui assets

---

Dockerfile
packages/cli/src/commands/database/alteration/utils.ts

One possible approach to address #6327.
Ensures that /etc/logto/packages/cli/alteration-scripts is present and writable by gid 0.
Does not remove/replace this directory each time, just removes the contents. This ensures that
the writabiliy remains (and also allows this to be a separately-mounted directory.
The reasons for doing this are described in #6327, but briefly, the desire is to let logto be
run from within docker as a non-root user (although gid 0 would still be required unless
the alteration-scripts are on a separately-mounted directory with appropriate permissions).
I propose this approach rather than making all of /etc/logto/packages/cli as writable by gid 0 since keeping more things read-only just seems safer overall.
So far I have only tested by running with a custom …

refactor(cli): keep alteration scripts folder writable by gid 0

---

packages/core/src/routes/profile/index.openapi.json
packages/core/src/routes/profile/index.ts
packages/integration-tests/src/api/api.ts
packages/integration-tests/src/api/profile.ts
packages/integration-tests/src/api/verification-record.ts
packages/integration-tests/src/helpers/admin-tenant.ts
packages/integration-tests/src/helpers/profile.ts
packages/integration-tests/src/tests/api/profile/index.test.ts

Implement the API `PATCH /profile` to update `name` and `avatar`, will support more fields later.

feat(core): add update name and avatar endpoint

---

packages/core/src/libraries/verification.ts
packages/core/src/queries/verification-records.ts
packages/core/src/routes/profile/index.openapi.json
packages/core/src/routes/profile/index.ts
packages/core/src/routes/verification/index.openapi.json
packages/core/src/routes/verification/index.ts
packages/integration-tests/src/api/profile.ts
packages/integration-tests/src/api/verification-record.ts
packages/integration-tests/src/helpers/profile.ts
packages/integration-tests/src/tests/api/profile/email-and-phone.test.ts
packages/integration-tests/src/tests/api/profile/index.test.ts
packages/phrases/src/locales/en/errors/verification-record.ts

Update "primaryEmail" in profile API.

feat(core): add and change primary email

---

packages/console/src/cloud/types/router.ts
packages/core/src/utils/subscription/types.ts

Align cloud API response type definition.
Console and core depends rely on the subscription-related cloud APIs' response, we have type definitions with these types. Previously, we have two sets of subscription-related cloud APIs (one set for user access and one set for m2m access). Since not all of these APIs are being used, we are removing used ones. Before we remove these APIs, we need to align the type definitions and the actual Cloud API calls.
This change unblocks Linear issue LOG-10111.
N/A

refactor: align cloud API response type definition

---

packages/core/src/routes/interaction/verifications/profile-verification.forgot-password.test.ts
packages/core/src/routes/interaction/verifications/profile-verification.ts

This pull request fixes a bug that occurred when users were migrated from the old system to Logto ([migration guide](https://docs.logto.io/docs/recipes/migrations/)) using a different password encryption method than Argon2i. The issue caused a 500 error when users attempted to reset their password for the first time using the "Forgot my password" option. The error was due to a missing validation step where the system was incorrectly comparing the new password with the old one, despite the previous password being encrypted with a different method (not Argon2i).
Manual testing was conducted by creating user accounts with various encryption methods, resetting passwords, and verifying system behavior.

fix(core): forgot password on the first access of migrated users

---

packages/core/src/utils/subscription/types.ts

update Cloud API response type definition.
Since we are deprecating
1. `GET /tenants/my/subscription/quota`
2. `GET /tenants/my/subscription/usage`
Cloud APIs, we use `GET /tenants/my/subscription-usage` to get the type definition.
CI

refactor(core): update Cloud API response type definition

---

packages/schemas/alterations/next-1728526649-add-idp-initiated-saml-sso-sessions-table.ts
packages/schemas/src/foundations/jsonb-types/sso-connector.ts
packages/schemas/tables/idp_initiated_saml_sso_sessions.sql

Add add IdP initiated SAML SSO sessions table
This table stores the session context of the IdP-initiated SAML SSO authentication request, including the SAML assertion content and expiration time. 
Previously, without the support of IdP-initiated SAML SSO, all the SAML assertions were processed immediately. SSO  identities will be extracted and stored in the Logto SSO connector sign-in session. 
To support the IdP-initiated SAML SSO flow, we need to temporarily store the received SAML assertion content in DB, so it can be retrieved later by a newly initiated Logto OIDC sign-in session.  
This table is for IdP-initiated SAML SSO flow only. 
- id: The unique identifier of the record. 
- connector_id: The ID of the SAML connector
- assertion_content: Successfully parsed and verified SAML …

feat(schemas): add IdP initiated SAML SSO sessions table

---

packages/core/src/constants/index.ts
packages/core/src/libraries/sign-in-experience/index.test.ts
packages/core/src/libraries/sso-connector.ts
packages/core/src/queries/sso-connectors.ts
packages/core/src/routes/authn.ts
packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
packages/core/src/sso/SamlConnector/index.ts
packages/core/src/sso/SamlConnector/utils.ts
packages/integration-tests/src/__mocks__/sso-connectors-mock.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/tests/api/authn.test.ts
packages/integration-tests/src/tests/api/interaction/single-sign-on/sad-path.test.ts
packages/schemas/src/foundations/jsonb-types/sso-connector.ts

Add the IdP-initiated assertion request handle logic to the `/authn/single-sign-on/saml:connectorId` endpoint. 
```mermaid
sequenceDiagram
actor User
participant Client
Box Logto (SAML SP)
participant Core
participant LogtoDB
participant Experience
end
participant IdP as SAML IdP
User->>Client: Access the service
Client->>Core: OIDC authentication request
Core-->>+LogtoDB: Init OIDC auth session (jti)
LogtoDB-->>-Core: OIDC auth session created
Core->>Experience: Prompt for login
Experience->>Core: Get SAML SSO authentication url
Core-->>+LogtoDB: Create SSO connector verification (jti + connectorId)
LogtoDB-->>-Core: SSO connector verification created, return the SSO authentication url
Core->>IdP: Redirect to IdP for authentication (Use jti as the relay state)
User-->>IdP: Authenticate …
```

feat(core): handle idp initiated saml assertion request

---

packages/core/package.json
packages/core/src/libraries/sign-in-experience/index.test.ts
packages/core/src/libraries/sso-connector.test.ts
packages/core/src/libraries/sso-connector.ts
packages/core/src/routes/authn.ts
packages/core/src/routes/interaction/utils/single-sign-on-guard.test.ts
packages/core/src/test-utils/mock-libraries.ts
packages/integration-tests/src/tests/api/sso-connectors/sso-connector-idp-initiated-auth-config.test.ts
packages/schemas/src/foundations/jsonb-types/sso-connector.ts
pnpm-lock.yaml

Initiated the OIDC auth flow on the user's behavior once an IdP-initiated SAML SSO authentication request was received.
Redefine the `IdpInitiatedAuthParams` type in the `SsoConnecorIdpInitiatedAuthConfig` schema.
- Remove the `resources` param. Keep it hidden. It is risky to use `RBAC` in an IdP-initiated SSO flow, as the authentication request itself is unsolicited. Developers may still specify the `resource` query parameter, but doing so is at their own risk.
- Replace the array typed `scopes` param with string typed `scope`, as this is more consistent with the actual format we are using in the authentication request query parameters. 
1. Add the `@logto/js` dependency to Logto core, as we need to use it as an SSOT for those sign-in authorization parameters. 
2. Implement the …

feat(core,schemas): init auth flow for IdP initiated SAML SSO

---

packages/core/src/__mocks__/sso.ts
packages/core/src/libraries/sso-connector.test.ts
packages/core/src/libraries/sso-connector.ts
packages/core/src/queries/sso-connectors.ts
packages/core/src/routes/interaction/utils/single-sign-on.test.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/core/src/utils/test-utils.ts

Auto consume the IdP-initiated SAML SSO session on the SSO sign-in verification flow.
1. Check the current SSO connector type is SAML
2. Check if an IdP-initiated SAML SSO session ID exists in the cookie
3. Check if the  IdP-initiated SAML SSO session exists in DB and if connectorId matches the current SSO verification request connectorId.
4. Clear the session record in DB and cookie
5. If the IdP-initiated SAML SSO session is valid (not expired), consume the assertion content and assign the verification result directly to the SSO verification session.
6. Return the SSO verification callback URL instead of the IdP authorization URL. 
test locally 
unit test case added

feat(core): consume IdP initiated session on SSO verification flow

---

.changeset/tricky-mice-pay.md
.changeset/violet-ligers-carry.md
packages/toolkit/core-kit/CHANGELOG.md
packages/toolkit/core-kit/package.json
packages/tunnel/CHANGELOG.md
packages/tunnel/package.json

-   3c993d59c: add range request handling to url utilities
-   349a6a405: support range request for mp4 video source hosting
Safari browser uses range request to fetch video data, but it was not supported by the `@logto/tunnel` CLI tool. This prevents our users who want to build custom sign-in pages with video background. In order to fix this, we need to partially read the video file stream based on the `range` request header, and set proper response headers and status code (206).
-   Updated dependencies [3c993d59c]
-   @logto/core-kit@2.5.1

release: @logto/core-kit:2.5.1 and @logto/tunnel:0.2.1

---

packages/core/src/libraries/sso-connector.test.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/schemas/alterations/next-1728887713-add-client-idp-initiated-auth-callback-uri-columns.ts
packages/schemas/tables/sso_connector_idp_initiated_auth_configs.sql

Alternate the `sso_connector_idp_initiated_auth_configs` to support directly redirecting the user to the client app to initiate a standard OIDC authorization request. 
For better security and to support SPA applications, instead of automatically sending the OIDC authorization requests from the server side, we provide a more recommended option, redirect the user to the client side to initiate an OIDC authentication flow. 
Since the IdP-initiated SAML SSO authentication request is unsolicited, thus sending an OIDC authorization request directly from the server side can not provide the necessary CRSF attack protection. 
E.g. the `state` parameter and `PKCE` flow for SPA application. 
As a better recommendation, by default, we redirect the user to a given client callback URL to initiate a …

feat(schemas): add idp-initiated SSO client side callback url columns

---

packages/core/src/routes/authn.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/phrases/src/locales/en/errors/single-sign-on.ts
packages/schemas/src/types/sso-connector.ts

Add IdP-initiated SSO client sign-in redirect. If the `autoSendAuthorizationRequest` field is set to false, instead of sending OIDC authentication, redirect the user to the client side IdP-initiated auth callback uri. 
test locally

feat(core): add idp-initiated sso client sign-in redirect

---

packages/core/src/routes/verification/index.openapi.json
packages/core/src/routes/verification/index.ts
packages/integration-tests/src/api/verification-record.ts

Add `expiresAt` in the response body of verification record creations endpoints:
1. `POST /api/verifications/password`
2. `POST /api/verifications/verification-code`

feat(core): add expiresAt in response of verification record creation

---

.changeset/fifty-apes-arrive.md
packages/core/src/env-set/create-pool.ts
packages/core/src/env-set/index.ts
packages/shared/src/node/env/GlobalValues.ts

Adding environmental variable to overwrite default database connection timeout, as the default value is causing some instances fail to start.
Default value for createPool is documented [here](https://github.com/silverhand-io/slonik-fork?tab=readme-ov-file#default-timeouts)
Locally by verifying value is passed to `@silverhand/slonik createPool` and application starts

feat(core): database connection timeout env overwrite support (#6187)

---

packages/console/src/components/QuotaGuardFooter/index.module.scss
packages/console/src/components/QuotaGuardFooter/index.tsx
packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx

fix webhook modal paywall for enterprise plan.
When enterprise tenants hit webhook paywall, let user contact us instead of upgrade plan (upgrade plan is not feasible for enterprise plans).

fix(console): fix webhook modal paywall for enterprise plan

---

packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
packages/console/src/contexts/TenantsProvider.tsx

fix cloud CI failed issue by wrapping TenantsContext utils methods with useCallback to prevent unnecessary re-render.
This rerender sometimes triggers infinite loops.
Tested with [Cloud CI](https://github.com/logto-io/cloud/actions/runs/11472273073/job/31924778552?pr=998).

fix(console): refactor TenantxContext util methods

---

.changeset/light-clocks-retire.md
.changeset/tricky-walls-add.md
packages/connectors/connector-google/src/constant.ts
packages/console/src/utils/connector-form.ts

1. add google connector default prompt (`select_account`), this does not effect existing users. When creating a new google connector, the `select_account` checkbox will be checked automatically. (users with existing Google connector will not be affected)
2. fix the connector `initFormData()` method logic, only apply `formItem.defaultValue` on connector creation. (If not fixed, after making change descripted in 1, if the user unchecks `select_account` and creates the connector, then when entering the Google Connector's edit page, the prompt field's value will be overwritten by the defaultValue. This is a bug.)

chore: add google connector default prompt

---

packages/connectors/connector-logto-email/src/index.ts
packages/core/src/routes/experience/classes/experience-interaction.test.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts
packages/core/src/routes/verification/index.ts
packages/integration-tests/src/__mocks__/connectors-mock.ts
packages/toolkit/connector-kit/src/types/passwordless.ts

Refactor the class `CodeVerification`, replace the property `interactionEvent` to `templateType`, directly mapping to the connector.
And add 2 types: UserPermissionValidation and BindNewIdentifier.

refactor(core): use template type for code verification

---

packages/console/src/consts/logs.ts
packages/core/src/queries/log.ts
packages/core/src/routes/log.test.ts
packages/core/src/routes/log.ts

Show custom JWT error logs on the console.
Should return the customJwt logs in the logs API. 
test locally

fix(core,console): show custom jwt error logs

---

packages/core/src/libraries/user.ts
packages/core/src/routes/experience/classes/verifications/social-verification.ts
packages/core/src/routes/profile/index.openapi.json
packages/core/src/routes/profile/index.ts
packages/core/src/routes/verification/index.openapi.json
packages/core/src/routes/verification/index.ts
packages/integration-tests/src/api/profile.ts
packages/integration-tests/src/api/verification-record.ts
packages/integration-tests/src/tests/api/profile/social.test.ts
packages/phrases/src/locales/en/errors/verification-record.ts

Implement linking new social identities in profile API.
Steps to link a new social identity:
1. Verify permission, by password or existing phone/email
2. Call `POST /verificiations/social` to create a record and get `authorizationUri`
3. Redirect to it and perform social provider auth.
4. Redirect back to the front end (a callback page is required) and get callback data
5. Call `POST /verifications/social/verify` with the connector data to verify
6. Use the 2 verification record ids to link.
This PR also add some changes to `SocialVerification`, it no longer relys on "interaction session".

feat(core): add social identity

---

package.json
pnpm-lock.yaml

Align the d3-color dependency version. 
Overwrite the d3-color version under the package `d3-interpolate@3.0.1`. It should align with other `d3` packages. 
This will address the [security](https://github.com/logto-io/logto/security/dependabot/8) issue.

chore(deps): align the d3-color deps version

---

packages/core/src/routes/admin-user/mfa-verification.openapi.json
packages/core/src/routes/admin-user/mfa-verifications.test.ts
packages/core/src/routes/admin-user/mfa-verifications.ts
packages/core/src/routes/interaction/utils/backup-code-validation.ts
packages/core/src/routes/interaction/utils/totp-validation.test.ts
packages/core/src/routes/interaction/utils/totp-validation.ts
packages/phrases/src/locales/en/errors/user.ts

This adds the possibility to add user set mfa secrets (TOTP / backup codes). This is necessary for the creation of such secrets directly in the application, because the user has first to confirm the answer or that he printed the backup codes before really creating them in Logto.
Manually by creating a TOTP secret.

feat(core): initial implementation of user set mfa secrets / codes

---

package.json
pnpm-lock.yaml

override @75lb/deep-merge package version to address the [security](https://github.com/logto-io/logto/security/dependabot/48) issue

chore: override @75lb/deep-merge package version

---

packages/core/src/queries/user-sso-identities.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/helpers.ts
packages/core/src/routes/experience/classes/libraries/provision-library.ts
packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
packages/core/src/routes/experience/types.ts

Should sync the enterprise SSO identity detail on sign-in.
Previously, user enterprise SSO identity only synced once when a new SSO identity was created. All the SSO identity details should be synced every time on user sign-in. 
Create the logic to sync the SSO identity on existing SSO user's sign-in flow. 
test locally

fix(core): should sync the sso identity detail on sign-in

---

packages/core/src/queries/user-sso-identities.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/helpers.ts
packages/core/src/routes/experience/classes/libraries/provision-library.ts
packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
packages/core/src/routes/experience/types.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/core/src/utils/json.test.ts
packages/core/src/utils/json.ts

Fix enterprise SSO unknown field not syncing issue.
The `SocialUserInfo` guard filtered extended SSO user identity info. Replace the `socialUserInfoGuard`  in the enterpriseSsoVerification data with `extendedSocialUserInfoGuard`. So we may keep all the unknown extended SSO identity info in file. 
test locally.

fix(core): fix enterprise SSO unknown field not synced issue

---

packages/experience-legacy/src/App.tsx
packages/experience-legacy/src/Layout/AppLayout/index.tsx
packages/experience-legacy/src/containers/DevelopmentTenantNotification/index.tsx
packages/experience/src/App.tsx
packages/experience/src/Layout/AppLayout/index.tsx
packages/experience/src/containers/DevelopmentTenantNotification/index.tsx

update the devTenantNotification style
Update the dev tenant notification banner using the latest design.
- Style update: Move the position to the top of the page.
- Dom update: Move the dom element to the body level.

style(experience): update the devTenantNotification style

---

packages/schemas/alterations/next-1730689363-add-account-center.ts
packages/schemas/src/foundations/jsonb-types/account-centers.ts
packages/schemas/src/foundations/jsonb-types/index.ts
packages/schemas/tables/account_centers.sql

Add new table `account_centers`, will be used to control each user fields in Profile API.
CI jobs should pass.

feat(schemas): add account center table

---

packages/connectors/connector-vonage-sms/README.md
packages/connectors/connector-vonage-sms/logo.svg
packages/connectors/connector-vonage-sms/package.json
packages/connectors/connector-vonage-sms/src/constant.ts
packages/connectors/connector-vonage-sms/src/index.test.ts
packages/connectors/connector-vonage-sms/src/index.ts
packages/connectors/connector-vonage-sms/src/mock.ts
packages/connectors/connector-vonage-sms/src/types.ts
packages/console/src/components/CreateConnectorForm/index.tsx
pnpm-lock.yaml

feat(connector): add vonage connector

---

packages/cli/src/commands/database/seed/tables.ts
packages/core/src/queries/account-center.ts
packages/core/src/routes/account-center/index.openapi.json
packages/core/src/routes/account-center/index.ts
packages/core/src/routes/init.ts
packages/core/src/routes/swagger/utils/documents.ts
packages/core/src/tenants/Queries.ts
packages/integration-tests/src/api/account-center.ts
packages/integration-tests/src/tests/api/account-center.test.ts
packages/schemas/alterations/next-1731054001-init-account-center.ts
packages/schemas/src/foundations/jsonb-types/account-center.ts
packages/schemas/src/seeds/account-center.ts

Add GET/PATCH api of account center, this settings will be used the control the global access of Profile API.

feat(core): add account center api

---

packages/console/src/containers/TenantAccess/index.tsx
packages/console/src/contexts/SubscriptionDataProvider/index.tsx
packages/console/src/contexts/TenantsProvider.tsx

Support console URL with a wildcard tenant ID `default`. This is useful in documentation or blog sites, so we can use console URLs like this `https://cloud.logto.io/default/applications` to navigate users to the actual console page instead of landing on the "get-started" page.
Locally tested

feat(console): support console url with wildcard tenant id

---

packages/core/src/routes/experience/classes/verifications/social-verification.ts

In social verification class, set default value `{}` of `connectorSession`, because some connectors do not use this, and this may cause `session.connector_validation_session_not_found` error.
Local tested.

fix(core): set default social session

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/experience-legacy/src/__mocks__/logto.tsx
packages/experience/src/__mocks__/logto.tsx
packages/schemas/alterations/next-1731304920-add-support-email-and-website-to-sie-table.ts
packages/schemas/tables/sign_in_experiences.sql

Add support email and website URL to sign in to experience settings.
If provided, both values will be disabled on the error pages in the experience app.

feat(schemas): add suppport email and website url to sie

---

packages/experience-legacy/src/pages/ErrorPage/SupportInfo.tsx
packages/experience-legacy/src/pages/ErrorPage/index.module.scss
packages/experience-legacy/src/pages/ErrorPage/index.tsx
packages/experience/src/pages/ErrorPage/SupportInfo.tsx
packages/experience/src/pages/ErrorPage/index.module.scss
packages/experience/src/pages/ErrorPage/index.tsx
packages/phrases-experience/src/locales/ar/description.ts
packages/phrases-experience/src/locales/de/description.ts
packages/phrases-experience/src/locales/en/description.ts
packages/phrases-experience/src/locales/es/description.ts
packages/phrases-experience/src/locales/fr/description.ts
packages/phrases-experience/src/locales/it/description.ts
packages/phrases-experience/src/locales/ja/description.ts
packages/phrases-experience/src/locales/ko/description.ts
packages/phrases-experience/src/locales/pl-pl/description.ts
packages/phrases-experience/src/locales/pt-br/description.ts
packages/phrases-experience/src/locales/pt-pt/description.ts
packages/phrases-experience/src/locales/ru/description.ts
packages/phrases-experience/src/locales/tr-tr/description.ts
packages/phrases-experience/src/locales/zh-cn/description.ts
packages/phrases-experience/src/locales/zh-hk/description.ts
packages/phrases-experience/src/locales/zh-tw/description.ts

Display support email and website on the error page.
test locally

feat(experience): display support info in error page

---

packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/types/oidc.ts
packages/core/src/sso/AzureOidcSsoConnector/index.ts
packages/core/src/sso/types/index.ts
packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts

Add trust unverified email settings to Azure OIDC SSO connector.
Since we launched the EntraID OIDC SSO connector we have received several feedbacks that their customer's email address can not be populated to Logto's user profile when signing up through the EntraID OIDC SSO connector.
The root cause is that Logto only syncs trusted email addresses with `email_verified` claim present in the OIDC userinfo response. 
However, for EntraID, the user email address is manually management by admin users. Those emails are not verified-guaranteed.  So as a result when connecting EntraID through an OIDC-based SSO connector, the `email_verified`  claim will not be returned. 
As a work around,  we add this extra `trustUnverifiedEmail` config field for the EntraID OIDC connector. Developers may choose …

feat(core,console): add trust unverified email settings to Azure SSO

---

packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience/index.openapi.json
packages/core/src/routes/sign-in-experience/index.test.ts
packages/core/src/routes/sign-in-experience/index.ts
packages/experience-legacy/src/__mocks__/logto.tsx
packages/experience/src/__mocks__/logto.tsx
packages/schemas/alterations/next-1731377260-add-unknown-session-redirect-url-to-sie.ts
packages/schemas/tables/sign_in_experiences.sql

Add unknown session redirect URL config to sie settings.
Once set, user will be redirect to this fallback URL when access Logto sign-in page without a valid session.

feat(schemas,core): add unknown session redirect url to sie

---

packages/core/src/middleware/koa-spa-session-guard.test.ts
packages/core/src/middleware/koa-spa-session-guard.ts

Read and redirect users to the `unknownSessioniRedirectUrl`  from sie settings on session not found.
test locally

feat(core): redirect to redirect url from sie on session not found

---

packages/core/src/middleware/koa-cors.test.ts
packages/core/src/middleware/koa-cors.ts
packages/core/src/routes-me/init.ts
packages/core/src/routes/init.ts
packages/integration-tests/src/tests/api/profile/index.test.ts

Allow access from all origins for UserRoute, which includes `/profile` and `/verifications`.
Because thoese APIs are for end users directly.
Local tested and integration tests.

fix(core): allow all origins for profile and verification api

---

packages/core/src/libraries/verification.ts
packages/core/src/middleware/koa-auth/constants.ts
packages/core/src/middleware/koa-auth/index.ts
packages/core/src/middleware/koa-auth/koa-oidc-auth.test.ts
packages/core/src/middleware/koa-auth/koa-oidc-auth.ts
packages/core/src/middleware/koa-auth/types.ts
packages/core/src/routes/init.ts
packages/core/src/routes/profile/index.openapi.json
packages/core/src/routes/profile/index.ts
packages/integration-tests/src/api/profile.ts
packages/integration-tests/src/tests/api/profile/account-center-reject.test.ts
packages/integration-tests/src/tests/api/profile/email-and-phone.test.ts
packages/integration-tests/src/tests/api/profile/index.test.ts
packages/integration-tests/src/tests/api/profile/social.test.ts

Move `verificationRecordId` param to header, this is more secury and convenient.
Please notice that `newVerificationRecordId` is still on request body, because this is not for general use and it is only for a specific new identifier only.

refactor(core): move verification record id to header

---

packages/schemas/alterations/next-1731054001-init-account-center.ts

Fix account center alteration script, clear table first.
Local tested.

fix(schemas): resolve duplicates of init account center alter

---

packages/schemas/alterations/next-1731054001-init-account-center.ts

Fix alteration script of "init account center". Previously, the tenants selection is ordered by "created_at", but the DB has duplicated rows in the exact same datetime, so the splitting is unstable.
Local tested with rows more then 1000.

fix(schemas): fix alter script of init account center

---

packages/schemas/alterations/next-1731904029-add-saml-application-configs-table.ts
packages/schemas/src/foundations/jsonb-types/index.ts
packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
packages/schemas/tables/saml_application_configs.sql

add `saml_application_configs` table
We made `entity_id` and `acs_url` nullable because:
1. There is a one-to-one correspondence between records in `saml_application_configs` and SAML apps.
2. If a SAML app is created via the API without simultaneously inserting a record into `saml_application_configs`, we would need to determine, based on the DB state at that time, when to insert a `saml_application_configs` record. If these fields are not nullable, for a particular SAML app, when the SAML config record does not exist, it would be impossible to use the patch API to modify one of these fields individually.
Covered by CI.

feat(schemas): add `saml_application_configs` table

---

packages/core/src/caches/index.ts
packages/core/src/caches/well-known.ts

1. Add a Redis ping interval to prevent idle connections from being disconnected by Azure. For more details, refer to the [Azure documentation on idle timeout](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-best-practices-connection#idle-timeout).
2. Add `trySafe` wrapper to the `WellKnown`  cache getter method. Incase of any Redis connection failure,  it should not affect the Logto core functionality.

fix(core): add redis ping interval

---

packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
packages/console/src/components/CreateConnectorForm/Footer/index.tsx
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/index.tsx
packages/console/src/components/MauExceededModal/index.tsx
packages/console/src/components/PlanDescription/index.tsx
packages/console/src/components/SkuName/index.tsx
packages/console/src/components/Topbar/TenantSelector/TenantDropdownItem/index.tsx
packages/console/src/pages/ApiResourceDetails/ApiResourcePermissions/components/CreatePermissionModal/index.tsx
packages/console/src/pages/ApiResources/components/CreateForm/Footer.tsx
packages/console/src/pages/Applications/components/ProtectedAppForm/index.tsx
packages/console/src/pages/RoleDetails/RolePermissions/components/AssignPermissionsModal/index.tsx
packages/console/src/pages/Roles/components/CreateRoleForm/Footer.tsx
packages/console/src/pages/TenantSettings/BillingHistory/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
packages/console/src/pages/Webhooks/CreateFormModal/CreateForm.tsx
packages/console/src/types/subscriptions.ts
packages/schemas/src/consts/subscriptions.ts

Remove deprecated `ReservedPlanIds` and refactor the skuId usage in the console.  `Enterprise` is not a valid `skuId` in the Logto system, and should not define a `ReservedPlanIds.Enterprise` .

refactor(schemas, console): remove deprecated ReservedPlanIds

---

packages/schemas/alterations/next-1732851150-rename-saml-application-constraints.ts
packages/schemas/tables/saml_application_configs.sql
packages/schemas/tables/saml_application_secrets.sql

rename SAML application secrets/configs constraints, to unblock Cloud submodule update.
Tested with Cloud repo [CI](https://github.com/logto-io/cloud/pull/1040).

chore: rename SAML application secrets/configs constraints

---

packages/core/src/routes/init.ts
packages/core/src/saml-applications/libraries/saml-applications.ts
packages/core/src/saml-applications/libraries/utils.test.ts
packages/core/src/saml-applications/libraries/utils.ts
packages/core/src/saml-applications/queries/configs.ts
packages/core/src/saml-applications/queries/secrets.ts
packages/core/src/saml-applications/routes/anonymous.ts
packages/core/src/saml-applications/routes/index.ts
packages/core/src/utils/content-disposition.ts
packages/integration-tests/src/api/saml-application.ts
packages/integration-tests/src/tests/api/application/saml-application.test.ts
packages/phrases/src/locales/en/errors/application.ts
packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
packages/schemas/src/types/saml-application.ts

Add GET SAML app certificate and anonymous metadata APIs
1. GET /saml-applications/:id/metadata (resolves LOG-10118)
2. GET /saml-applications/:id/certificate (resolves LOG-10119, LOG-10525)
Also provide corresponding APIs for downloading metadata and certificate in file format.
1. GET /saml-applications/:id/metadata/download
2. GET /saml-applications/:id/certificate/download
Covered by CI.

feat: add SAML app anonymous metadata and certificate APIs

---

packages/core/src/routes/applications/application.ts
packages/integration-tests/src/tests/api/application/saml-application.test.ts

fix applications APIs status guard, we throws 400 when trying to PATCH/DELETE SAML apps, we should include 400 in status response guard to avoid throwing 500.
Should be covered by new integration tests.

fix(core): fix applications APIs status guard

---

packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/ConfigForm.tsx
packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/IdpInitiatedAuth/utils.ts
packages/core/src/libraries/sso-connector.test.ts
packages/core/src/libraries/sso-connector.ts
packages/phrases/src/locales/en/translation/admin-console/guide.ts
packages/schemas/alterations/next-1733212543-add-saml-application-type-to-idp-initiated-sso-application-allow-list.ts
packages/schemas/tables/sso_connector_idp_initiated_auth_configs.sql

Allow SAML application to use IdP-initiated SSO.
- Allow all `ApplicationType.SAML` typed applications to be used as the IdP-initiated SSO default application.
- Return the SAML IdP applications to the IdP-initiated SSO applications config page. So the user can pick the SAML IdP application in the dropdown list. 
*This whole feature is guarded by the `devFeature` and `isCloud` flags. 
test locally

refactor(console,core,schemas): allow SAML application to use  IdP-initiated SSO

---

packages/connectors/connector-http-email/README.md

add tips for HTTP email connector
N/A

chore: add tips for HTTP email connector

---

packages/console/src/hooks/use-logto-skus.ts

Replace the `api/sku` API using the `api/tenants/:tenantId/available-sku`.
This will address the bug that all enterprise tenant can not retrieve their SKU details properly. 
- `api/sku`: Only returns the public available SKUs
- `api/tenants/:tenantId/available-sku`: Returns all the public available SKUs plus the current tenant's basic SKU. This is essential for all enterprise plan users and grandfathered plan users. 
test locally

refactor(console): replace get sku api

---

.changeset/chilled-radios-cover.md
packages/cli/src/commands/connector/utils.ts

fix fetch official connector CLI error
Error reported by [community members](https://discord.com/channels/965845662535147551/1314281175686185032), the npm registry API has now changed to `text` fuzzy search, which will yield an infinite number of results. We need to filter the results again before processing them to avoid hitting npm registry API rate limit, which throws 429 response code.
Tested locally, without this fix, the CLI command seems will load forever.

fix: fix fetch official connector CLI error

---

packages/core/src/utils/subscription/index.ts
packages/core/src/utils/subscription/types.ts

Fix the `Subscription` response type received from the Cloud subscription API. All date-typed properties are defined as `Date` in the Cloud model. However, after JSON serialization, the client side receives these values in ISO 8601 string format, leading to a type mismatch issue.
To resolve this, manually convert the `currentPeriodStart` and `currentPeriodEnd` values to strings to ensure consistent and accurate response types.

fix(core): fix the subscription api response type

---

packages/console/src/hooks/use-logto-skus.ts

Reverts logto-io/logto#6861.
This change will break the empty tenant bootstrap flow.
We should update the SKU-catching API only in the `useSubscriptionData` hook. Keep the `useLogto` hook remain.

Revert "refactor(console): replace get sku api"

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/index.tsx
packages/console/src/contexts/SubscriptionDataProvider/use-new-subscription-data.ts
packages/console/src/hooks/use-logto-skus.ts
packages/console/src/pages/CheckoutSuccessCallback/index.tsx
packages/console/src/utils/subscription.ts

Fixing the enterprise tenant's current SKU always returns `dev` bug.
In the previous implementation, we used the `GET api/skus` API to fetch available Logto SKUs for a given tenant. However, this endpoint is intended exclusively for public Logto SKU access and does not include any private Logto SKUs, such as enterprise SKUs or grandfathered SKUs. 
As a result, this caused a bug where the `currentSku` value in the `SubscriptionContext` for an enterprise tenant always defaulted to dev, the fallback value. Enterprise users can not invite additional tenant members due the the limitation of the dev tenant quota. 
To fix this, we switch the `GET /api/skus`  API to the `GET /api/tenants/:tenantId/available-sku` API instead. It will return all the publicly accessible Logto SKUs plus any private …

fix(console): fix enterprise tenant current sku always return dev

---

packages/console/src/components/ApplicationCreation/CreateForm/index.tsx
packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/index.tsx
packages/console/src/components/FeatureTag/index.tsx
packages/console/src/components/Guide/GuideCard/index.tsx
packages/console/src/components/PlanDescription/index.tsx
packages/console/src/components/PlanUsage/index.tsx
packages/console/src/consts/plan-quotas.ts
packages/console/src/consts/subscriptions.ts
packages/console/src/ds-components/CardTitle/index.tsx
packages/console/src/pages/ApiResources/components/CreateForm/index.tsx
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx
packages/console/src/pages/CustomizeJwt/index.tsx
packages/console/src/pages/EnterpriseSso/SsoCreationModal/index.tsx
packages/console/src/pages/EnterpriseSso/index.tsx
packages/console/src/pages/Mfa/MfaForm/UpsellNotice/index.tsx
packages/console/src/pages/Mfa/PageWrapper/index.tsx
packages/console/src/pages/OrganizationTemplate/index.tsx
packages/console/src/pages/Organizations/CreateOrganizationModal/index.tsx
packages/console/src/pages/Organizations/index.tsx
packages/console/src/pages/SignInExperience/PageContent/Branding/CustomUiForm/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/AddOnUsageChangesNotification/index.tsx
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/MauLimitExceededNotification/index.tsx
packages/console/src/pages/TenantSettings/TenantMembers/InviteMemberModal/index.tsx
packages/console/src/pages/TenantSettings/components/NotEligibleSwitchPlanModalContent/index.tsx
packages/console/src/utils/subscription.ts

Refactor all the paywall guard logic to support the latest Pro plan migrations. This PR includes the following changes:
- Since we are going to have both the grandfathered `ReservedPlanId.Pro` plan and the new `ReservedPlanId.Pro202411` plan co-exist online, introduce a new `isProPlan` util function that maps both `planId` as a pro plan. 
- Refactor the `FeatureTag` component display logic. Currently, there is no mapping logic applied. We display the plain `planId` as the text for the `FeatureTag`. This is not friendly for the new `ReservedPlanId.Pro202411` pro plan ID. Thus we create a `planId` to `tag` map. So we may control the displayed text for each given plan.
- Create a `latestProPlanId` constant to replace all the current  `ReservedPlanId.Pro` reference. Use the dev feature guard …

refactor(console): refactor console paywall guards

---

packages/console/src/components/CreateTenantModal/SelectTenantPlanModal/SkuCardItem/FeaturedSkuContent/use-featured-sku-content.ts
packages/console/src/components/MauExceededModal/index.tsx
packages/console/src/components/PlanUsage/index.tsx
packages/console/src/consts/subscriptions.ts
packages/console/src/pages/TenantSettings/Subscription/CurrentPlan/index.tsx
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
packages/console/src/pages/TenantSettings/Subscription/SwitchPlanActionBar/index.tsx
packages/console/src/utils/subscription.ts
packages/core/src/libraries/quota.ts
packages/phrases/src/locales/ar/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/de/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/en/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/es/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/fr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/it/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ja/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ko/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pl-pl/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-br/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/pt-pt/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/ru/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/tr-tr/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-cn/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-hk/translation/admin-console/subscription/quota-table.ts
packages/phrases/src/locales/zh-tw/translation/admin-console/subscription/quota-table.ts

This PR refactors the console and core code to support our new Pro plan migration. 
1. Add some missing comments to make the context clear
2. Refactor the `PlanUsage` component. Make the `periodicUsage` props required. 
- For `MauExceededModel` we should use the usage data from the tenant context.
- For `Subscription/CurrentPlan` we should always fetch the latest usage data.
3. Extract the SKU sorting logic from `formatLogtoSkusResponses` method to the  `pickupFeaturedLogtoSkus` method. We only need those SKUs to be ordered in the subscription plan table. No need to sort the data on every Logto SKU request. 
4. Extract a new `SkuButton` child component, to avoid complicated inline element display logic. 
1. Update the `featuredPlanIds` list. Once the new plan is launched, the latest …

refactor(console, core): refactor console to support new pro plan

---

packages/console/src/pages/TenantSettings/Subscription/index.tsx

Should not apply dev guard on the `/api/tenants/${currentTenantId}/add-on-skus` request. This request is applied to both grandfathered plans and new plans. We should not guard this request using the `isDevFeature` guard. Otherwise it will break the current token-usage tooltip content on prod. 
test locally

fix(console): should not apply dev guard

---

packages/console/src/consts/subscriptions.ts
packages/console/src/pages/TenantSettings/Subscription/PlanComparisonTable/index.tsx
packages/console/src/pages/TenantSettings/Subscription/index.tsx

Remove the new pro plan dev feature guard.
Notice: merging this PR to the cloud will enable the Pro202411 plan on prod and block the public visibility of the grandfathered  Pro plan. 
cloud [PR](https://github.com/logto-io/cloud/pull/1058).

chore(console): remove new pro plan dev feature guard

---

packages/core/src/routes/experience/classes/mfa.ts
packages/core/src/routes/interaction/verifications/mfa-verification.ts
packages/integration-tests/src/tests/api/experience-api/bind-mfa/happpy-path.test.ts
packages/integration-tests/src/tests/api/interaction/mfa/totp.test.ts

This PR address this bug: if user's config has "mfa skipped" mark, then he can bypass mandatory MFA policy.

fix(core): should not be able to skip mandatory MFA

---

packages/core/src/caches/base-cache.ts
packages/core/src/caches/tenant-subscription.ts
packages/core/src/caches/types.ts
packages/core/src/caches/well-known.test.ts
packages/core/src/caches/well-known.ts
packages/core/src/routes/experience/classes/verifications/password-verification.ts
packages/core/src/sso/types/session.ts
packages/core/src/utils/subscription/types.ts
packages/schemas/src/consts/subscriptions.ts

To better support the tenant subscription data caching this PR includes the following updates:
1. Bump the @logto/cloud version to pick up the latest API response type
2. Refactor the `WellKnownCache` class. 
- Extract an abstract `BaseCache` class so we can share most of the methods but keep a distinct set of cache keys.
- Support set cache expiration time. We need to set the expiration time based on the tenant subscription's `currentPeriodEnd` time.
3. Implement a new `TenantSubscriptionCache` for tenant subscription data caching use. 
UT added

feat(core): add subscription cache class

---

packages/core/src/__mocks__/cloud-connection.ts
packages/core/src/caches/base-cache.ts
packages/core/src/caches/tenant-subscription.ts
packages/core/src/libraries/subscription.test.ts
packages/core/src/libraries/subscription.ts
packages/core/src/middleware/koa-token-usage-guard.ts
packages/core/src/oidc/init.test.ts
packages/core/src/oidc/init.ts
packages/core/src/queries/daily-token-usage.ts
packages/core/src/tenants/Tenant.ts
packages/core/src/test-utils/tenant.ts
packages/core/src/utils/subscription/types.ts
packages/phrases/src/locales/en/errors/auth.ts

Apply the token usage limit guard to Free and Dev tenants on the Logto cloud. This PR includes the following updates:
Apply a new `koaTokenUsageGuard` middleware to the `oidc/token` endpoint. This middleware will fetch the tenant's subscription info and calculate the token usage of the `Free` and `Dev` tenants. 
If the token usage exceeds the token limit in the tenant's current subscription period. A `exceed_token_limit` exception will be thrown. 
To reduce the latency this extra token usage validation step may cause we introduced two levels of the cache to the flow:
1. Subscription Redis Cache:
We store subscription responses from the cloud service in Redis to minimize reliance on direct cloud connection requests. By default, the cache expiration time is set to match the …

feat(core): add token usage guard

---

packages/core/src/saml-applications/libraries/consts.ts
packages/core/src/saml-applications/libraries/saml-applications.ts
packages/core/src/saml-applications/routes/anonymous.ts
packages/core/src/saml-applications/routes/utils.test.ts
packages/core/src/saml-applications/routes/utils.ts
packages/core/src/sso/OidcConnector/utils.test.ts
packages/core/src/sso/OidcConnector/utils.ts
packages/core/src/sso/types/oidc.ts
packages/phrases/src/locales/en/errors/application.ts
packages/phrases/src/locales/en/errors/oidc.ts

add SAML IdP `GET /saml-applications/:id/callback` API, this API (resolves LOG-10124, LOG-10125):
1. handles authorization code flow response
- get access token with auth code
- get user info with access token
2. send SAML assertion to configured ACS URL
Tested locally with Azure IdP-initiated flow.

feat(core): add SAML IdP `GET /saml-applications/:id/callback` API

---

packages/console/src/pages/TenantSettings/DevTenantNotification/index.tsx
packages/console/src/pages/TenantSettings/index.module.scss
packages/console/src/pages/TenantSettings/index.tsx
packages/phrases/src/locales/en/translation/admin-console/subscription/index.ts

Add token usage exceeded notification for dev tenants.
Since the dev tenant does not have the subscription page, we need to add a new usage exceed notification banner on the tenant page.

feat(console): add token usage exceed notification

---

packages/core/src/saml-applications/queries/sessions.ts
packages/core/src/tenants/Queries.ts
packages/schemas/alterations/next-1735012422-add-saml-application-sessions-table.ts
packages/schemas/src/foundations/jsonb-types/index.ts
packages/schemas/src/foundations/jsonb-types/saml-application-sessions.ts
packages/schemas/tables/saml_application_sessions.sql

Add `saml_application_sessions` table to help improve the security of OIDC and SAML proxy. (resolves LOG-10581)
1. when we receice SAML auth request, we create create a record (using `applicationId`, and `samlRequestId`) in this table
2. and then we start a OIDC auth request on backend, which should update the record and attach `oidcState`
3. on SAML proxy callback page, we check whether we have unexpired and unused OIDC state in record, if not, throw an error otherwise mark the OIDC state as used (this prevents replay attack)
4. after getting the OIDC token with the OIDC auth code, we get the unused `samlRequestId` and sent SAML response to the ACS URL in record and hence marked the `samlRequestId` as parsed
N/A

feat: add saml app sessions table

---

packages/core/src/constants/index.ts
packages/core/src/routes/swagger/utils/operation.ts
packages/core/src/saml-applications/libraries/saml-applications.ts
packages/core/src/saml-applications/queries/index.ts
packages/core/src/saml-applications/routes/anonymous.ts
packages/core/src/saml-applications/routes/utils.test.ts
packages/core/src/saml-applications/routes/utils.ts
packages/core/src/tenants/Queries.ts
packages/phrases/src/locales/en/errors/application.ts
packages/phrases/src/locales/en/errors/oidc.ts

Add add SAML auth request handling endpoints:
1. GET /api/saml/:samlAppId/authn (resolves LOG-10122)
2. POST /api/saml/:samlAppId/authn (resolves LOG-10121)
To receive single sign on auth requests. 
Tested locally. Can successfully parse SAML login request and init OIDC sign in request to Logto.

feat(core): add SAML auth request handling endpoints

---

packages/console/src/components/DateTime/index.tsx
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CertificateActionMenu/index.module.scss
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CertificateActionMenu/index.tsx
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/CreateSecretModal.tsx
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/Settings.tsx
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/index.module.scss
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/use-secret-table-columns.tsx
packages/core/src/saml-applications/libraries/saml-applications.ts
packages/core/src/saml-applications/libraries/utils.test.ts
packages/core/src/saml-applications/libraries/utils.ts
packages/core/src/saml-applications/routes/index.ts
packages/integration-tests/src/api/saml-application.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/phrases/src/locales/en/translation/admin-console/general.ts

Among which, 1-3 resolves LOG-10559.
1. add create SAML app secret function
2. enable customization on secret expiration time display
3. enable delete/activate/deactivate for SAML app secrets
4. update `POST /saml-applications/:id/secrets` API body from `lifeSpanInDays` to `lifeSpanInYears`, this is indeed a "breaking change", but since the API is not released, it is OK.
Updated integration tests for API changes. Console changes tested locally.

feat(core,console): enable create and activate/deactivate SAML app secrets

---

packages/core/src/saml-applications/libraries/utils.ts
packages/integration-tests/src/tests/api/application/saml-application.test.ts
packages/schemas/alterations/next-1735274337-add-encryption-config-to-saml-apps.ts
packages/schemas/src/foundations/jsonb-types/saml-application-configs.test.ts
packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
packages/schemas/src/types/saml-application.ts
packages/schemas/tables/saml_application_configs.sql

support SAML app encryption and nameIdFormat config
1. can specify the name ID format sent in SAML app assertion (resolves LOG-10616)
2. can setup encryption in SAML app assertion (resolves LOG-10603)
Add unit tests and integration tests.

feat: support SAML app encryption and nameIdFormat config

---

packages/console/src/components/ApplicationIcon/index.tsx
packages/core/src/saml-applications/routes/index.ts
packages/schemas/alterations/next-1735292380-make-saml-app-first-party-app.ts
packages/schemas/tables/applications.sql

make SAML apps to be first party apps (resolves LOG-10650)

refactor: make SAML apps to be first party apps

---

packages/console/src/consts/page-tabs.ts
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.module.scss
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.tsx
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/index.tsx
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/utils.ts
packages/core/src/saml-applications/libraries/saml-applications.ts
packages/integration-tests/src/tests/api/application/saml-application.test.ts
packages/phrases/src/locales/en/translation/admin-console/application-details.ts
packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts
packages/toolkit/core-kit/src/openid.ts

1. Add attribute mapping section in console (resolves LOG-10340).
2. Also fixed the bug, that updating only config related field(s) (entityId, acsUrl, or attributeMapping) with `PATCH /saml-applications/:id` API, the DB query method throws error. Add integration test to cover such cases.

feat(console,core): add attribute mapping

---

.changeset/afraid-otters-crash.md
packages/core/src/utils/storage/index.ts
packages/core/src/utils/storage/s3-storage.ts
packages/schemas/src/types/system.ts

Add support for configurable S3 endpoint and addressing style (path-style/virtual-hosted) to improve compatibility with S3-compatible storage services.
- Add forcePathStyle option to control URL addressing style
- Fix custom endpoint support implementation
- Improve URL generation logic for different configurations
Resolves: [#6920]

feat(core): support custom endpoint and addressing style for S3

---

packages/core/src/saml-applications/SamlApplication/index.test.ts
packages/core/src/saml-applications/SamlApplication/index.ts

Build SAML app sign in URL scope with attribute mapping (resolves LOG-10126).
According to least privileges principle, we build `scope` with attribute mapping to avoid access leak.
Add unit tests.

refactor(core): build SAML app sign in URL scope with attribute mapping

---

packages/core/src/saml-applications/SamlApplication/index.test.ts
packages/core/src/saml-applications/SamlApplication/index.ts
packages/core/src/saml-applications/SamlApplication/utils.ts
packages/core/src/saml-applications/routes/index.ts
packages/integration-tests/src/tests/api/application/saml-application.test.ts

1. add default redirect URI for SAML apps on creation (resolves LOG-10694)
2. refactor the `getScopesFromAttributeMapping()` class method as well.
Added both unit test and integration test cases to cover the changes.

feat(core): add default redirect URI for SAML apps on creation

---

packages/core/src/saml-applications/SamlApplication/index.ts
packages/core/src/saml-applications/libraries/saml-applications.ts
packages/core/src/saml-applications/routes/anonymous.ts

refactor GET saml app metadata endpoint, reuse SamlApplication class instead of using seprated methods to keep accordance. (resolves LOG-10699)
Previously we check all config attributes when construct the SamlApplication class, but in fact, we should only check those attributes when needed. E.g. when constructing IdP, we do not need to check the config of `acsUrl`, we hence update the implementation as well to fix this.
Should be covered by existing integration tests.

refactor(core): refactor GET saml app metadata endpoint

---

.changeset/soft-kings-grin.md
packages/experience-legacy/src/components/BrandingHeader/index.tsx
packages/experience-legacy/src/components/Button/SocialLinkButton.tsx
packages/experience-legacy/src/containers/SocialLanding/index.tsx
packages/experience/src/components/BrandingHeader/index.tsx
packages/experience/src/components/Button/SocialLinkButton.tsx
packages/experience/src/containers/SocialLanding/index.tsx

Remove the [cross-origin](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#crossorigin) attribute on experience image elements.  
Some public image resources may not have the proper cross-origin headers configured, those images may fail to load when the cross-origin="anonymous" attribute is present.
Since those image elements are only used for display purposes, Logto does not need to access the image data, so the cross-origin="anonymous" attribute is not necessary.
To make the image elements more compatible with public image resources, remove the cross-origin="anonymous" attribute from the image elements.
test locally.

refactor(experience): remove the image CORS attributes

---

packages/core/src/queries/log.ts
packages/core/src/routes/log.test.ts
packages/core/src/routes/log.ts
packages/core/src/saml-applications/routes/anonymous.ts

1. Make SAML related logs visible in audit listing page by updating log queries methods.
2. Use `applicationId` instead of `samlApplicationId` in log to improve the query UX.

fix(core,console): make SAML related log visible in audit log listing page

---

packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/utils.ts
packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts

fix SAML app console issues:
1. reorder the `nameIdFormat` options (resoves LOG-10732)
2. remove unwanted unsave changes alert in SAML app details page (resolves LOG-10730)
3. fix SAML app encryption configuration can not save bug (resolves LOG-10733)

fix: fix SAML app console issues

---

packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/AttributeMapping.tsx
packages/core/src/saml-application/SamlApplication/index.test.ts
packages/core/src/saml-application/SamlApplication/index.ts
packages/integration-tests/src/tests/api/application/saml-application.test.ts
packages/schemas/src/foundations/jsonb-types/saml-application-configs.ts

fix SAML app attribute mapping not working issue (resolves LOG-10729).
Tested locally, worked fine:

fix: fix SAML app attribute mapping not working issue

---

.changeset/blue-flowers-rule.md
packages/console/src/components/CreateConnectorForm/index.tsx

Add changset of http email connector.
N/A

chore: add changeset for http email

---

packages/core/src/routes/applications/application.ts
packages/core/src/routes/saml-application/index.ts
packages/integration-tests/src/tests/api/application/saml-application.test.ts

1. hide oidcClientMetadata of SAML apps when using GET app APIs (resolves LOG-10499), affect `GET /applications` and `GET /applications/:id` APIs.
2. also removed unnecessary guard for creating new secrets for SAML apps.
Covered by integration tests.

chore(core): hide oidcClientMetadata of SAML apps when using GET app APIs

---

packages/console/src/components/Guide/hooks.ts
packages/core/src/routes/applications/application.ts
packages/core/src/routes/init.ts

remove SAML app dev feature guard.
N/A

feat: remove SAML app dev feature guard

---

packages/console/src/components/ApplicationCreation/CreateForm/Footer/index.tsx
packages/console/src/components/FeatureTag/index.tsx
packages/console/src/components/Guide/GuideCard/index.tsx
packages/console/src/components/Guide/GuideCardGroup/index.tsx
packages/console/src/components/Guide/hooks.ts
packages/console/src/hooks/use-applications-usage.ts
packages/console/src/pages/Applications/components/GuideLibrary/index.tsx

add enterprise tag for SAML apps.

refactor: add enterprise tag for SAML apps

---

packages/experience-legacy/src/containers/TotpCodeVerification/index.tsx
packages/experience/src/containers/TotpCodeVerification/index.tsx

Fixes a bug with double submission on the OTP screen.
Issue:
https://github.com/logto-io/logto/issues/6991
Discovered by adding this line:
```ts
if (isSubmitting) {
alert('already submitting')
}
```
Every few otp attempts I got the alert, so replaced it with:
```ts
if (isSubmitting) {
return;
}
```
So far I haven't experienced the bug since.

fix: otp double signin bug

---

.changeset/afraid-turkeys-swim.md
packages/core/src/routes/organization-invitation/index.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.custom.data.test.ts

When an organization invitation is accepted, trigger the `Organization.Membership.Updated` webhook event.

fix(core): trigger webhook in organization invitation flow

---

.changeset/purple-glasses-fix.md
packages/console/src/consts/oidc.ts
packages/console/src/pages/ApplicationDetails/ApplicationDetailsContent/EndpointsAndCredentials/index.tsx
packages/phrases/src/locales/en/translation/admin-console/application-details.ts

Display jwks uri on application details page to make it easier for users to retrieve the JWKS URI when verifying access tokens.

feat(console): display jwks uri on application details page

---

.changeset/rotten-bugs-pretend.md
packages/cli/src/commands/connector/utils.ts

Fix add official connectors cli command missing connectors bug.
1. Fix the loop-breaking logic bug. 
2. Add additional `maintainer` query logic to reduce the number of irrelevant results. Otherwise, there will be 1000+ results returned from the npm repository. 
Test locally

fix(cli): fix cli add official connectors command missing connectors bug

---

packages/core/src/routes/user-assets.openapi.json

Update `user-asset.openapi.json` to include a missing request body property. Fixes #6994.
CI

fix(core): update openapi.json for post user asset api

---

packages/schemas/alterations/next-1738828268-add-email-templates-table.ts
packages/schemas/src/foundations/jsonb-types/email-templates.ts
packages/schemas/src/foundations/jsonb-types/index.ts
packages/schemas/tables/email_templates.sql

In the previous implementation, we only supported one copy of the email templates configured under the email connector's settings. This becomes a limitation for some of our customers who require i18n support for their email templates. Users from different regions may receive emails in different languages, just like our SIE i18n phrases. We need to support i18n templates to meet the requirements
In addition to the current default email templates stored in connector configs, we need to add an extra global setting to allow users to configure multiple email templates for different languages. This PR introduces the new `email_templates` table.
This table will be used to globally maintain custom email templates with i18n support for developers. We will detect the user's language preference and …

feat(schemas): add new email templates table

---

packages/core/src/queries/email-templates.ts
packages/core/src/routes/email-template/index.openapi.json
packages/core/src/routes/email-template/index.ts
packages/core/src/routes/init.ts
packages/core/src/routes/sso-connector/idp-initiated-auth-config.openapi.json
packages/core/src/routes/sso-connector/index.ts
packages/core/src/routes/swagger/utils/documents.ts
packages/core/src/routes/swagger/utils/parameters.ts
packages/core/src/tenants/Queries.ts
packages/integration-tests/src/__mocks__/email-templates.ts
packages/integration-tests/src/api/email-templates.ts
packages/integration-tests/src/helpers/email-templates.ts
packages/integration-tests/src/tests/api/email-templates.test.ts

Add new PUT and DELETE Management API for email-templates.
- `PUT /api/email-templates`: Create or replace a list of email templates based on the given `languageTag` and `templateType`.
- `DELETE /api/email-templates/:id/`: Delete an email template by ID.
Fix the swagger error caused by the supplement document of the dev feature endpoint `/api/sso-connectors/:id/idp-initiated-auth-config. 
The `Dev feature` tag must be specified under each operation method. 
Integration test added

feat(core): add PUT and DELETE email-templates api

---

packages/core/src/queries/email-templates.ts
packages/core/src/routes/email-template/index.openapi.json
packages/core/src/routes/email-template/index.ts
packages/integration-tests/src/api/email-templates.ts
packages/integration-tests/src/tests/api/email-templates.test.ts

Implement the email templates GET endpoints:
- `GET /api/email-templates`: Get all email templates.  `languageTag` and `templateType` filters are supported. 
- `GET /api/email-tempaltes/:id`: Get the email template by ID.
Integration test added

feat(core): add get email-templates api

---

packages/core/src/routes/email-template/index.openapi.json
packages/core/src/routes/email-template/index.ts
packages/integration-tests/src/api/email-templates.ts
packages/integration-tests/src/tests/api/email-templates.test.ts

Add update email template details API. `PATCH /api/email-templates/:id/details`.
This API allows for the partial update of an email template's details using its template ID for convenience.
integration test added.

feat(core): add update email template details api

---

packages/core/src/queries/email-templates.ts
packages/core/src/routes/email-template/index.openapi.json
packages/core/src/routes/email-template/index.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/integration-tests/src/api/email-templates.ts
packages/integration-tests/src/tests/api/email-templates.test.ts

Add APIs to delete multiple email templates by `languageTag` or `templateType`:
- `DELETE /api/email-templates/language-tag/:languageTag`
- `DELETE /api/email-templates/template-type/:templaetType`

feat(core): delete email template by langaugeTag or templateType

---

packages/core/src/routes/email-template/index.openapi.json
packages/core/src/routes/email-template/index.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/integration-tests/src/api/email-templates.ts
packages/integration-tests/src/tests/api/email-templates.test.ts
packages/phrases/src/locales/en/errors/connector.ts

Redesign email templates bulk delete API.
Remove the following API:
- `DELETE /api/email-templates/language-tag/:languageTag`
- `DELETE /api/email-templates/template-type/:templateType`
Replaced with:
- `DELETE /api/email-templates?languageTag=en`
- `DELETE /api/email-templates?templateType=SignIn`
Using query parameters instead of path parameters in the build deletion API, for the following reasons:
1. Query parameters are more flexible.
2. Reduce the number of API definitions.
3. Better align with our API design, as the path parameter with case-sensitive value does not follow our API path convention. 
integration test updated

refactor(core): redesign email templates bulk delete API

---

.changeset/pink-roses-confess.md
.changeset/rotten-bugs-pretend.md
packages/experience-legacy/src/utils/sign-in-experience.ts
packages/experience/src/utils/sign-in-experience.ts

Previously, platform-based social connector filtering was applied during the sign-in experience settings fetch process but not in the SSR sign-in experience data. As a result, platform-specific connectors were not correctly filtered when rendering the page using SSR data.
This update ensures that the same filtering logic is applied to SSR sign-in experience data, resolving the issue.
Affected connectors: WeChat Web and WeChat Native.
Test locally

fix(experience): filter wechat connectors by platform

---

.changeset/wise-cows-scream.md
packages/console/src/mdx-components/SsoSamlSpMetadata/index.tsx
packages/core/src/env-set/index.ts
packages/core/src/routes/authn.ts
packages/core/src/routes/interaction/utils/single-sign-on.test.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/core/src/routes/saml-application/anonymous.ts
packages/core/src/routes/saml-application/index.ts
packages/core/src/routes/sso-connector/index.ts
packages/core/src/routes/sso-connector/utils.test.ts
packages/core/src/routes/sso-connector/utils.ts
packages/core/src/saml-application/SamlApplication/index.test.ts
packages/core/src/saml-application/SamlApplication/index.ts
packages/core/src/sso/SamlConnector/index.ts
packages/core/src/sso/SamlSsoConnector/index.test.ts
packages/core/src/sso/SamlSsoConnector/index.ts

apply custom domain on SAML SSO and app
Previously, we didn't apply custom domains to the configuration items for SAML SSO and SAML applications. However, we did apply custom domains in the console frontend. This could lead to users using the entity ID and assertion consumer service URL obtained from the frontend, which are different from what the backend actually uses, thus affecting the normal use of the function. In this fix, we also applied the custom domain in the backend.
N/A, update unit test cases, need to test on dev.

fix(core): apply custom domain on SAML SSO and app

---

.changeset/gentle-rabbits-chew.md
packages/console/src/pages/ApplicationDetails/SamlApplicationDetailsContent/Settings.tsx

add missing `/api` segment in SAML app SSO URL.

fix(console): add missing `/api` segment in SAML app SSO URL

---

.changeset/rare-readers-cry.md
packages/core/src/errors/RequestError/index.ts
packages/core/src/errors/RequestError/request-error.test.ts
packages/core/src/middleware/koa-error-handler.test.ts
packages/core/src/middleware/koa-error-handler.ts
packages/core/src/middleware/koa-experience-ssr.test.ts
packages/core/src/middleware/koa-i18next.test.ts
packages/core/src/middleware/koa-i18next.ts
packages/core/src/middleware/koa-oidc-error-handler.test.ts
packages/core/src/middleware/koa-oidc-error-handler.ts
packages/core/src/oidc/init.ts
packages/core/src/tenants/Tenant.ts
packages/core/src/utils/i18n.ts
packages/core/src/utils/test-utils.ts

This PR resolves a concurrency issue in i18n handling by moving from a global i18next instance to request-scoped instances.
When handling concurrent requests:
- The shared global i18next instance's language was being modified via `changeLanguage()` calls
- This could lead to race conditions where requests might receive translations in unexpected languages
- Particularly problematic in our cloud multi-tenant environments. Error messages in random languages may occur.
- Updated `koaI18next` middleware to create a cloned i18next instance for each request
- Attach the request-scoped instance to Koa context (`ctx.i18n`)
- All subsequent middleware and handlers should now use `ctx.i18n` instead of the global instance
- Maintains the global instance for initialization while preventing …

fix(core): prevent i18n context contamination by using request-scoped instance

---

packages/core/src/libraries/domain.test.ts
packages/core/src/libraries/domain.ts
packages/core/src/libraries/saml-application/saml-applications.ts
packages/core/src/routes/domain.test.ts
packages/core/src/routes/domain.ts
packages/core/src/routes/saml-application/index.ts
packages/core/src/saml-application/SamlApplication/index.test.ts
packages/core/src/saml-application/SamlApplication/index.ts
packages/core/src/tenants/Libraries.ts

update SAML app custom domain logics.
1. use original domain for default redirect URI of SAML app upon creation.
2. apply custom domain when parsing SAML app configs.
3. update redirect URIs to SAML app when syncing custom domain status
- if custom domain removed or domain status is not health, remove redirect URIs with custom domain in SAML apps
- if custom domain is activated, add redirect URIs with custom domain applied to SAML apps'
N/A

refactor: sync SAML app redirectUris upon custom domain status updates

---

.changeset/seven-cows-look.md
packages/core/src/routes/verification/index.ts

Fixes an incorrect condition check in the verification code flow where `isNewIdentifier` was using inverted logic for email and phone comparisons.
- Corrected `isNewIdentifier` boolean logic to use `identifier.value !== user.primaryEmail` for email checks
- Fixed phone number comparison to properly use `identifier.value !== user.primaryPhone`
This fixes a regression where:
- Verification codes for existing emails/phones were incorrectly using the `BindNewIdentifier` template
- New identifiers were mistakenly getting the `UserPermissionValidation` template
- Affected both email and phone verification flows
integration test covered

fix(core): fix incorrect condition check

---

.changeset/loud-beds-obey.md
packages/experience/src/containers/VerificationCode/use-register-flow-code-verification.ts
packages/experience/src/hooks/use-sie.ts

fix the email/phone identifier conflict handling logic during user registration.
When a user attempts to register with an email/phone that already exists:
"Sign in instead" modal will be shown when:
- The email/phone identifier has been verified through a verification code validation
- Identifier type (email/phone) was enabled in sign-in methods
This caused an issue when:
- Only password authentication method was enabled in the sign-in method settings.
- When users clicked "Sign in instead" action button, the API call will throw an sign-in method not enabled error. Which is confusing for the user.
Expected behavior: Show the "Email/phone already exists" error modal directly. If only password authentication is enabled. User should not be able to sign in with email/phone directly.
Shows the …

fix(experience): fix email/phone identifier conflict handling logic during user registration

---

packages/core/src/libraries/saml-application/saml-applications.ts
packages/core/src/routes/domain.test.ts
packages/core/src/routes/domain.ts

fix SAML app redirect URIs sync custom domains logic, with following updates:
1. update `syncCustomDomainsToSamlApplicationRedirectUrls()` method, takes `domains` as second parameter, handle all domains once instead of iterating through domain lists, which can hurt performance.
2. previously we use `startsWith(host)` to find default redirectURI, which is wrong.
Tested locally, can successfully sync custom domains to SAML app redirect URIs.

fix(core): fix SAML app redirect URIs sync custom domains logic

---

packages/core/src/routes/saml-application/anonymous.ts
packages/schemas/src/foundations/jsonb-types/saml-application-sessions.ts

update SAML auth request info guard and add more info to log.
When looking into use Logto SAML app as IdP and connector to Google Workspace issue, we encountered such issue. By investigating our code, `request.destination` field is not used and can be safely updated to be optional.
Since Google Workspace can not use localhost, we need to deploy this change to logto dev to unblock our checks.
N/A

chore: update SAML auth request info guard and add more info to log

---

packages/core/src/routes/saml-application/anonymous.ts
packages/core/src/saml-application/SamlApplication/index.ts

fix: should not apply custom domain to SAML app SP entity ID
also rename SamlApplicationConfig.entityId to SamlApplicationConfig.spEntityId to avoid confusion.
N/A

fix(core): should not apply custom domain to SAML app SP entity ID

---

packages/cli/src/connector/utils.ts
packages/connectors/connector-mock-email/src/index.ts
packages/core/src/libraries/connector.ts
packages/core/src/libraries/passcode.ts
packages/core/src/queries/email-templates.ts
packages/core/src/routes-me/init.ts
packages/core/src/routes-me/types.ts
packages/core/src/routes-me/verification-code.ts
packages/core/src/routes/connector/config-testing.openapi.json
packages/core/src/routes/connector/config-testing.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/types.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts
packages/core/src/routes/interaction/additional.ts
packages/core/src/routes/interaction/utils/verification-code-validation.ts
packages/core/src/routes/verification-code.ts
packages/core/src/routes/verification/index.ts
packages/integration-tests/src/__mocks__/email-templates.ts
packages/integration-tests/src/api/connector.ts
packages/integration-tests/src/helpers/email-templates.ts
packages/integration-tests/src/helpers/index.ts
packages/integration-tests/src/helpers/profile.ts
packages/integration-tests/src/tests/api/email-templates/connector-test-api.test.ts
packages/integration-tests/src/tests/api/email-templates/index.test.ts
packages/integration-tests/src/tests/api/email-templates/organization-invitation.test.ts
packages/integration-tests/src/tests/api/email-templates/user-account-api.test.ts
packages/schemas/src/foundations/jsonb-types/email-templates.ts
packages/toolkit/connector-kit/src/types/email-template.ts
packages/toolkit/connector-kit/src/types/index.ts
packages/toolkit/connector-kit/src/types/passwordless.ts

Adds end-to-end localization support for email connectors by introducing locale propagation and template customization capabilities.
- **Connector Schema Update**  
- Extended `sendMessage` payload schema with optional `locale` property. If provided, this property will be used to find the preferred custom i18n email template. 
- Relocate the `emailTemplateDetailsGuard` and `EmailTemplateDetails` definitions from `@logto/schemas` to `@logto/connector-kit` so they can be shared across email connector packages.
- **Locale Propagation**  
- Client-facing API: `experience verification API`, `account verification API`, `me verification API`. Auto-inject `ctx.locale` into the `sendMessage` payload. 
- Management APIs: `connector test API`, `organization invitation API`. Added optional `locale` …

feat(core,toolkit): pass locale ctx to sendMessage method

---

packages/connectors/connector-aliyun-dm/src/index.test.ts
packages/connectors/connector-aliyun-dm/src/index.ts
packages/connectors/connector-aliyun-dm/src/mock.ts
packages/connectors/connector-aws-ses/src/index.test.ts
packages/connectors/connector-aws-ses/src/index.ts
packages/connectors/connector-aws-ses/src/mock.ts
packages/connectors/connector-aws-ses/src/utils.ts
packages/connectors/connector-mailgun/src/index.test.ts
packages/connectors/connector-mailgun/src/index.ts
packages/connectors/connector-mock-email/src/index.ts
packages/connectors/connector-sendgrid-email/src/index.test.ts
packages/connectors/connector-sendgrid-email/src/index.ts
packages/connectors/connector-sendgrid-email/src/mock.ts
packages/connectors/connector-smtp/src/index.test.ts
packages/connectors/connector-smtp/src/index.ts

This PR update all the Logto provided email connectors to support reading custom i18n email templates by a given language and template type. 
- AWS Direct Mail
- SendGrid
- Aliyun DM
- Mailgun
Unit test updated

feat(connector): update email connectors to support i18n

---

packages/core/src/caches/base-cache.ts
packages/core/src/caches/well-known.test.ts
packages/core/src/caches/well-known.ts
packages/core/src/queries/email-templates.ts

Add Redis cache for the email templates.
- Implement Redis caching for email templates using `languageTag` and `templateType` as cache keys to reduce DB queries
- Update WellKnownCache to support null values in Redis cache entries
- Add cache invalidation during template updates/deletions
1. Added Redis caching layer for email template `findByLanguageTagAndTemplateType` query method
- New Redis cache type `email-templates`
- Cache lookup using composite key: `<languageTag>:<templateType>`
- Cache null values to prevent DB lookups for non-existent templates
2. Enhanced WellKnownCache functionality to support nullable value
- Modified JSON serialization to handle null values
- Added null value detection in cache hydration logic
- Added WellKnown supported cache type `email-templates` and …

refactor(core): add email templates redis cache

---

.changeset/small-hairs-pretend.md
packages/connectors/connector-mock-email/src/index.ts
packages/connectors/connector-tencent-sms/src/index.ts
packages/core/src/caches/base-cache.ts
packages/core/src/libraries/organization-invitation.ts
packages/core/src/routes/organization-invitation/index.ts
packages/core/src/utils/connectors/extra-information.ts
packages/integration-tests/src/tests/api/email-templates/organization-invitation.test.ts
packages/toolkit/connector-kit/src/index.test.ts
packages/toolkit/connector-kit/src/index.ts
packages/toolkit/connector-kit/src/types/passwordless.ts

Enhanced handlebars template processing in the connector to support deep property access in email template variables. 
This enables more flexible template authoring, allowing nested object traversal in payload data.
- Updated `replaceSendMessageHandlebars` logic to handle nested property paths in template variables
- Latest template processing logic now supports:
- Direct replacement of primitive values (string/number/null/undefined)
- Deep property access using dot-notation (e.g., `organization.branding.logoUrl`)
- Graceful handling of missing properties (replaces with empty string)
- Preservation of original handlebars when variables aren't provided in payload
- Append extra organization context to the organization invitation sendMessage payload
1. Direct replacement
```ts …
```

feat(toolkit,core): support nested properties in email template variables

---

packages/core/src/caches/base-cache.ts
packages/core/src/libraries/organization-invitation.ts
packages/core/src/libraries/passcode.test.ts
packages/core/src/libraries/passcode.ts
packages/core/src/middleware/koa-auth/koa-oidc-auth.test.ts
packages/core/src/middleware/koa-auth/koa-oidc-auth.ts
packages/core/src/middleware/koa-auth/types.ts
packages/core/src/routes-me/verification-code.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts
packages/core/src/routes/interaction/additional.test.ts
packages/core/src/routes/interaction/additional.ts
packages/core/src/routes/interaction/utils/verification-code-validation.ts
packages/core/src/routes/organization-invitation/index.ts
packages/core/src/routes/verification-code.ts
packages/core/src/routes/verification/index.ts
packages/core/src/utils/connectors/extra-information.ts
packages/core/src/utils/connectors/types.ts
packages/integration-tests/src/helpers/index.ts
packages/integration-tests/src/tests/api/email-templates/experience-api.test.ts
packages/integration-tests/src/tests/api/email-templates/interaction-api.test.ts
packages/integration-tests/src/tests/api/email-templates/organization-invitation.test.ts
packages/integration-tests/src/tests/api/email-templates/user-account-api.test.ts

Passing extra context variables to the email templates in different conditions:
| API                                           | Template type                               | User context  | Application context | Organization context | Memo                                                                |
| --------------------------------------------- | ------------------------------------------- | ------------- | ------------------- | -------------------- | ------------------------------------------------------------------- |
| `/experience/verification/verification-code`  | SignIn, Register, ForgotPassword            | x             | ✅                  | ✅ (optional)        | read the applicationId and organizationId from cookie               |
| …

feat(core): pass extra context to email template

---

.changeset/four-houses-invite.md
packages/core/src/routes/interaction/utils/totp-validation.ts

Update the TOTP secret generation to use 20 bytes (160 bits), following the recommendation in RFC 6238 (TOTP) and RFC 4226 (HOTP).
This aligns with the standard secret length used by most 2FA applications and provides better security while maintaining compatibility with existing TOTP validators.
Reference:
- RFC 6238 (TOTP) Section 5.1: https://www.rfc-editor.org/rfc/rfc6238#section-5.1
- RFC 4226 (HOTP) Section 4, Requirement 6: https://www.rfc-editor.org/rfc/rfc4226#section-4
Related issue: https://discord.com/channels/965845662535147551/965845662979719198/1342073498897485844

refactor: adjust TOTP secret length to 20 bytes

---

.changeset/strange-oranges-sort.md
packages/core/src/routes/organization-role/index.openapi.json
packages/core/src/routes/organization-role/index.ts
packages/core/src/routes/organization-scope/index.openapi.json
packages/core/src/routes/organization-scope/index.ts
packages/core/src/utils/SchemaRouter.ts
packages/integration-tests/src/tests/api/hook/hook.trigger.data.test.ts
packages/integration-tests/src/tests/api/organization/organization-scope.test.ts
packages/integration-tests/src/tests/api/organization/organization-user.test.ts

Issue: #7064 
During the initial introduction of the organization feature, a limitation was introduced where the frontend only displayed the first 20 organization scopes (first page) due to default pagination settings. Despite several iterations and improvements to the organization features, this issue remained unnoticed.
This PR fixes the long-standing bug by making pagination optional for organization scopes GET API endpoints. The change ensures all available scopes are returned when needed, particularly in organization permissions management and scopes assignment scenarios.
Test locally and all scopes are returned.

fix(core): show all organization permissions

---

packages/connectors/connector-mailgun/src/index.test.ts
packages/connectors/connector-mailgun/src/index.ts
packages/connectors/connector-sendgrid-email/src/index.test.ts
packages/connectors/connector-sendgrid-email/src/index.ts
packages/connectors/connector-smtp/src/index.test.ts
packages/toolkit/connector-kit/src/types/email-template.ts

fix the misuse of the `replyTo` field. 
For some email providers, this field can indicate the reply email address.  Previously, it was confused with the alias of send to email address. 
Unit test updated

fix(connector): fix misuse of replyTo field

---

.changeset/spicy-pets-approve.md
packages/core/src/queries/organization/index.ts
packages/core/src/routes/organization/user/index.openapi.json
packages/core/src/routes/organization/user/role-relations.ts
packages/integration-tests/src/api/organization.ts
packages/integration-tests/src/tests/api/organization/organization-user.test.ts
packages/phrases/src/locales/en/errors/organization.ts

This PR address the feature request #7065.
This update enhances organization user role management APIs to support role assignment by both names and IDs, improving integration flexibility.
- Added `organizationRoleNames` parameter to:
- POST `/api/organizations/{id}/users/{userId}/roles` (assign roles)
- PUT `/api/organizations/{id}/users/{userId}/roles` (replace roles)
- Make both `organizationRoleNames` and `organizationRoleIds` optional in the above APIs
- If both are not provided, or empty, an invalid data error will be thrown
- Merge logic when both parameters are provided:
- Combines roles from `organizationRoleNames` and `organizationRoleIds`
- Automatically deduplicates entries
- Validates all names/IDs exist before applying changes
- Maintains backward compatibility with existing …

feat(core): assign organization roles by name

---

.changeset/hungry-olives-sell.md
packages/core/src/middleware/koa-spa-proxy.test.ts
packages/core/src/middleware/utils/experience-proxy.test.ts
packages/core/src/middleware/utils/experience-proxy.ts

Officially transitioned the user sign-in experience app from the legacy `@logto/experience-legacy` package to the latest `@logto/experience` package. This change fully adopts our new [Experience API](https://openapi.logto.io/group/endpoint-experience), enhancing the underlying architecture while maintaining the same user experience.
- Package update: The user sign-in experience now utilizes the `@logto/experience` package for OSS by default.
API Transition: The new package leverages our latest [Experience API](https://openapi.logto.io/group/endpoint-experience).
- No feature changes: Users will notice no changes in functionality or experience compared to the previous implementation.

feat(core):  migrate experience package for OSS

---

packages/integration-tests/src/tests/api/sign-in-experience.test.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts

Add `organizationRequiredMfaPolicy` settings to the sign-in experience Mfa settings. 
This policy is used to determine the MFA prompt behavior when the user is associated with one to more organizations that require MFA.

feat(schemas): add organizationRequiredMfa policy settings

---

packages/core/src/routes/experience/experience.openapi.json
packages/core/src/routes/experience/verification-routes/social-verification.openapi.json
packages/schemas/src/types/interactions.ts

update some experience API doc descriptions

chore(core): update some experience API doc descriptions

---

packages/core/src/libraries/one-time-token.ts
packages/core/src/queries/one-time-tokens.ts
packages/core/src/routes/one-time-tokens.openapi.json
packages/core/src/routes/one-time-tokens.ts
packages/core/src/routes/swagger/utils/documents.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/core/src/tenants/Libraries.ts
packages/integration-tests/src/api/one-time-token.ts
packages/integration-tests/src/tests/api/one-time-tokens.test.ts
packages/phrases/src/locales/en/errors/index.ts
packages/phrases/src/locales/en/errors/one-time-token.ts
packages/schemas/alterations/next-1741318144-add-one-time-token-unique-index.ts
packages/schemas/tables/one_time_tokens.sql

add `POST /one-time-tokens/verify` API, resolves LOG-10869
Should be covered by integration tests.

feat: add POST /one-time-tokens/verify API

---

packages/connectors/connector-aliyun-sms/src/index.test.ts
packages/connectors/connector-aliyun-sms/src/index.ts
packages/connectors/connector-tencent-sms/src/index.test.ts
packages/connectors/connector-tencent-sms/src/index.ts

Aliyun SMS only accepts `[a-z0-9A-Z]` value for verification template parameters.  
Need to filter out locale params in the Aliyun SMS connector.  E.g. `zh-CN` is not allowed.

fix(connector): filter out locale param in AliyunSMS

---

.changeset/dull-dolphins-return.md
packages/core/src/saml-application/SamlApplication/index.test.ts
packages/core/src/sso/OidcConnector/utils.test.ts
packages/core/src/sso/OidcConnector/utils.ts

Remove `client_id` from the OIDC SSO connector's token request body for better compatibility. 
This pull request addresses an issue with client authentication methods in the token request process. Previously, the `client_id` was included in the request body while also using the authentication header for client credentials authentication. 
This dual method of client authentication can lead to errors with certain OIDC providers, such as Okta, which only support one authentication method at a time.
Removal of `client_id` from Request Body: The `client_id` parameter has been removed from the token request body. According to the OAuth 2.0 specification, including the `client_id` in the body is optional when the authentication header is provided.
Test locally with all the OIDC SSO connectors in …

fix(core): fix OIDC SSO token request failed issue

---

packages/core/src/routes/experience/classes/helpers.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/routes/experience/classes/verifications/one-time-token-verification.ts
packages/core/src/routes/experience/classes/verifications/verification-record.ts
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/verification-routes/one-time-token.openapi.json
packages/core/src/routes/experience/verification-routes/one-time-token.ts
packages/core/src/sentinel/basic-sentinel.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/one-time-token.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/one-time-token.test.ts
packages/schemas/src/foundations/jsonb-types/sentinel.ts
packages/schemas/src/foundations/jsonb-types/verification-records.ts
packages/schemas/src/types/interactions.ts

Implement new experience API `POST /experience/one-time-token/verify`.
This API provides the ability to verify a one-time token in Logto Sign-in Experience. Thus, a new verification type `VerificationType.OneTimeToken` is introduced, as well as the new `OneTimeTokenVerification` class.
After successfully verifying the one-time token, a verification ID is returned, which can be used in the `/api/experience/identification` request later to help identify the user.
API integration tests. See test results in CI.

feat: implement verify one-time token experience api

---

packages/core/src/routes/applications/application.ts
packages/core/src/routes/sign-in-experience/index.ts

make report subscription usage to be non-blocking, resolves LOG-10880
we only need to trigger this function, and there is no need to wait for the result.
N/A

chore: make report subscription usage to be non-blocking

---

packages/core/src/libraries/quota.ts
packages/core/src/libraries/subscription.test.ts
packages/core/src/libraries/subscription.ts
packages/core/src/tenants/Libraries.ts
packages/core/src/tenants/Tenant.ts
packages/core/src/test-utils/tenant.ts
packages/core/src/utils/subscription/index.ts

Reuse subscription library cache in quota library to reduce cross region HTTP requests, resolves LOG-10881
Before this change, quota library relies on Logto Cloud service for checking whether some specific resources can be added. On our product environment, these kind of HTTP requests are in cross-region manner (e.g. request server locates in EU from AU/US regions, which are time-consuming). Since we now have subscription data cached in each region, the access to cached subscription data in the same region saves time and without affect existing logics.
Tested on local machine, subscriptions worked fine.

chore: reuse subscription library cache in quota library to reduce cross region HTTP requests

---

packages/console/src/hooks/use-console-routes/routes/security.tsx
packages/console/src/pages/CaptchaDetails/CaptchaContent/index.tsx
packages/console/src/pages/CaptchaDetails/index.tsx
packages/console/src/pages/Security/CreateCaptchaForm/ProviderRadioGroup/index.tsx
packages/console/src/pages/Security/CreateCaptchaForm/index.tsx
packages/console/src/pages/Security/Guide/index.module.scss
packages/console/src/pages/Security/Guide/index.tsx
packages/console/src/pages/Security/index.tsx
packages/console/src/pages/Security/types.tsx
packages/phrases/src/locales/en/translation/admin-console/security.ts

Add the guide of create captcha.
Will add README content later.

feat(console): create captcha guide

---

.github/CONTRIBUTING.md

use pnpm other than 9.x will report an error.
```
$ pnpm i
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)
Your pnpm version is incompatible with "/Users/hanyu/github/logto-io/logto".
Expected version: ^9.0.0
Got: 10.6.2
This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.
To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
```
ref commit:
https://github.com/silverhand-io/essentials/commit/2171b962a9881a8abf44aa91160f816751e65bfe

chore: fix pnpm requirements in CONTRIBUTING.md

---

.changeset/tame-snails-fold.md
packages/toolkit/language-kit/src/utility.ts
packages/translate/src/prompts.ts

Language tag check should be case insensitive. Our language tags in `phrases` and `phrases-experience` are in lowercase, such as `pt-br` and `zh-cn`. However, the language tag is case sensitive in toolkit, e.g., `pt-BR` and `zh-CN`.
This causes a bug that some language tags that contain regional variation suffixes will not be picked up by the translate CLI, and thus lots of phrases end up untranslated.
Locally

fix(toolkit): language tag check should be case insensitive

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpForm.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/SignUpIdentifierItem.module.scss
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/SignUpIdentifierItem.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.module.scss
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.module.scss
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/components/IdentifiersAddButton/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/utils.ts
packages/console/src/pages/SignInExperience/PageContent/constants.ts
packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
packages/console/src/pages/SignInExperience/types.ts
packages/core/src/libraries/sign-in-experience/sign-in.test.ts
packages/core/src/libraries/sign-in-experience/sign-in.ts
packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/sad-path.test.ts
packages/integration-tests/src/utils.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts

Removed the restriction rule in the sign-in experience settings:
- Previously, if the password was set as mandatory in the sign-up settings, all sign-in methods were required to enable password verification. For better flexibility, this restriction has now been removed.
Refactor the console sign-in and sign-up settings page to align with the recent sign-in experience validation rule updates.
1. Password is no longer mandatory when using `username` as a sign-up identifier.
The password option in the sign-up settings is now editable. Note: When `username` is selected as a sign-up identifier, the system will still auto-enable the password option by default. However, users can manually deselect it if they prefer.
2. Sign-up identifiers are no longer …

refactor(console): refactor SIE settings form

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpForm.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/happy-path.test.ts
packages/integration-tests/src/tests/console/sign-in-experience/sign-up-and-sign-in/helpers.ts

This PR fixes two console bug:
1. Sign-in methods cannot be removed if the identifier is enabled as a sign-up identifier.
2. Setting `EmailOrPhon`e as a sign-up identifier incorrectly appends duplicate email and phone sign-in methods.
New integration test cases added.

fix(console): fix sign-in method can not removed bug

---

.changeset/hungry-terms-smash.md
packages/translate/src/prompts.ts

Improve AI prompt in the translate CLI tool, in order to better support i18n plural form suffixes.
Used in #7166. See differences in Arabic and Russian translations in `phrases-experience` package.

refactor(translate): improve prompts to better support i18n suffixes

---

packages/experience/src/App.tsx
packages/experience/src/apis/experience/index.ts
packages/experience/src/apis/experience/one-time-token.ts
packages/experience/src/hooks/use-fallback-route.ts
packages/experience/src/pages/DirectSignIn/index.tsx
packages/experience/src/pages/OneTimeToken/index.tsx
packages/experience/src/utils/search-parameters.ts
packages/phrases-experience/src/locales/ar/error/index.ts
packages/phrases-experience/src/locales/de/error/index.ts
packages/phrases-experience/src/locales/en/error/index.ts
packages/phrases-experience/src/locales/es/error/index.ts
packages/phrases-experience/src/locales/fr/error/index.ts
packages/phrases-experience/src/locales/it/error/index.ts
packages/phrases-experience/src/locales/ja/error/index.ts
packages/phrases-experience/src/locales/ko/error/index.ts
packages/phrases-experience/src/locales/pl-pl/error/index.ts
packages/phrases-experience/src/locales/pt-br/error/index.ts
packages/phrases-experience/src/locales/pt-pt/error/index.ts
packages/phrases-experience/src/locales/ru/error/index.ts
packages/phrases-experience/src/locales/tr-tr/error/index.ts
packages/phrases-experience/src/locales/zh-cn/error/index.ts
packages/phrases-experience/src/locales/zh-hk/error/index.ts
packages/phrases-experience/src/locales/zh-tw/error/index.ts
packages/schemas/src/consts/experience.ts

Add the landing page to handle one-time token authentication in Experience app.
Locally

feat(experience): add one-time token landing page to handle magic link auth

---

packages/core/src/sso/AzureOidcSsoConnector/index.ts
packages/core/src/sso/OidcConnector/utils.ts

Merge `idToken` claims with the `userinfo` response in the Azure OIDC SSO connector, as Entra ID returns different claim sets in each request.
test locally

feat(core): merge idToken claims with userinfo response

---

packages/console/src/ds-components/Checkbox/Checkbox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/SignInMethodItem.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignInForm/SignInMethodEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpForm.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/SignUpIdentifiersEditBox/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/use-sign-up-password-listeners.ts
packages/core/src/libraries/sign-in-experience/sign-up.test.ts
packages/core/src/libraries/sign-in-experience/sign-up.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/username-password.test.ts
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts

1. Refactor sign-in method syncing logic when sign-up settings change:
- Trigger sign-in identifier syncing only when new sign-up identifiers are appended.
- Simplify the syncing logic for password and verification code configurations using the new `useSignUpPasswordListener` hook. Subscribe to `signUp.password` changes via useEffect.
2. Refactor sign-up verify logic:
- If sign-up identifiers include email or phone, `verify` must be mandatory.
- Update core SIE validation logic to enforce `signUp.verify` when email or phone is enabled in`secondaryIdentifiers`.
- Add a tooltip to the sign-up verify checkbox for better guidance.
3. Remove the tool tip of sign-in methods password settings checkbox.

refactor(console,core): refactor sign-up verify and sign-in syncing

---

packages/core/src/routes/experience/classes/libraries/profile-validator.ts
packages/experience/src/components/IdentifierRegisterForm/use-register-with-username.ts
packages/experience/src/hooks/use-sie.ts

1. Adjust the missing profiles'r prompt order
- username -> emailOrPhon -> email -> phone -> password
2. Update the experience user registration flow
- Directly navigate to the new password page only if the password is enabled for sign-up and no additional `secondaryIdentifiers` are required.
- otherwise let the backend to decide the next step. 
test locally

refactor(core,experience): adjust missing profiles prompt order

---

packages/core/src/middleware/koa-consent-guard.test.ts
packages/core/src/middleware/koa-consent-guard.ts
packages/core/src/tenants/Tenant.ts
packages/experience/src/App.tsx
packages/experience/src/pages/OneTimeToken/index.tsx
packages/experience/src/pages/Register/index.tsx
packages/experience/src/pages/SignIn/index.tsx
packages/experience/src/pages/SwitchAccount/index.module.scss
packages/experience/src/pages/SwitchAccount/index.tsx
packages/experience/src/utils/search-parameters.ts

- Guard one-time token on consent request. This makes sure even if the user has an active session, when they use magic sign-in link, the token is still checked before auto-consent.
- Change the client side navigation mechanism when `one_time_token` param is presented in the URL. The logic is now handled separately in both `/sign-in` and `/register` routes.
Local dev test

feat(core): guard one-time token on consent request

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/PasswordDisabledNotification.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/index.module.scss
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/index.tsx
packages/phrases/src/locales/en/translation/admin-console/sign-in-exp/sign-up-and-sign-in.ts

Add a password-not-enabled notification if the username is the only sign-up method enabled but password authentication is not enabled.

feat(console): add password not enabled notification

---

packages/core/src/middleware/koa-auto-consent.ts
packages/core/src/routes/interaction/consent/index.ts
packages/demo-app/src/App.tsx

Add better support for one-time token authentication in demo-app. So that even when the user is already authenticated in demo-app, the one-time token auth will still be triggered.
The PR also includes core API changes that allow using `/interaction/consent` APIs in demo-app.
Local dev testing

feat(demo-app,core): support one-time token in demo-app

---

packages/core/src/queries/organization/index.ts

Fix the issue that when no default roles are set in organizations, new users cannot be provisioned to these organizations via one-time token, even though the organization IDs are already included in the token context.
This PR resolves the issue by left joining `Organization` table and `OrganizationJitRoles` table in the corresponding DB query.
Locally tested

fix(core): fix provision organization by ids query

---

packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignIn/SignUpForm/use-sign-up-password-listeners.ts

Fix disabled sign-in password settings that can not be saved bug.
Using a `useRef` to store the current `submitCount` form state. This will prevent the `submitCount` change triggers the sign-up and sign-in password syncing effect.
test locally

fix(console): fix disable sign-in password settings bug

---

packages/phrases-experience/src/locales/en/description.ts
packages/phrases-experience/src/locales/en/secondary.ts

A small improvement to the wording of the "existing account" question on login prompts. Changes "Already had an account?" to "Already have an account?".
This is my first contribution to Logto so let me know if I did anything wrong!
Text-only change so didn't set up a local env

fix(phrases): improve wording of "existing account?" question

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/helpers.ts
packages/core/src/routes/experience/classes/libraries/provision-library.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.test.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/verifications/one-time-token-verification.ts
packages/core/src/routes/experience/types.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/one-time-token.test.ts

This PR skips sign-in mode check for verified one-time token verifications. So that adding users via the one-time token always work even if the registration is turned off.
It also includes code refactoring that provision user organizations on submitting interaction. This makes sure the user will always be provisioned to the organizations that linked with the one-time token, on both new registration and upcoming sign-in actions.
Tested locally. Will add test case later.

refactor(core): skip sign-in mode check for one-time token verification

---

packages/core/src/routes/experience/classes/libraries/captcha-validator.ts
packages/schemas/src/foundations/jsonb-types/captcha.ts

Add support for reCaptcha enterprise verification.
We may refactor the verification code to config based in the future.
Note: unlike Turnstile, reCaptcha enterprise does not provide test API keys with predicable results, so we don't do integration tests for it.
Tested locally with temp front-end.

feat(core): add recatpcha enterprise verification

---

packages/core/src/middleware/koa-security-headers.ts
packages/experience/src/components/ReCaptchaEnterprise/index.module.scss
packages/experience/src/components/ReCaptchaEnterprise/index.tsx
packages/experience/src/containers/CaptchaBox/index.tsx

Implement reCAPTCHA enterprise on frontend.
Created LOG-11107 to refactor providers into config-based.
Local tested.
By default, reCAPTCHA enterprise does not show a visible widget, but in the test, I can get token successfully.

feat(experience,core): add recaptcha enterprise to frontend

---

packages/console/src/pages/SignInExperience/PageContent/index.tsx
packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts

This PR addresses a bug where the diff modal incorrectly appears when the `signUp.secondaryIdentifiers` value is undefined but is filled with a default empty array by the SIE form parser.
**Background:**
The `secondaryIdentifiers` field is optional in the sign-in experience schema. However, the console form parser automatically populates this field with an empty array for data processing convenience. This behavior can lead to data inconsistencies when comparing the submitted data (parsed from form values) with the original data.
**Changes made:**
- Implemented a default value parser to ensure consistent comparison between the submitted data and the original data.
- Prevented the diff modal from displaying when the `secondaryIdentifiers` field is auto-filled with an empty array.
test …

fix(console): should not show diff modal for default values update

---

packages/demo-app/src/App.tsx
packages/demo-app/src/Callback.tsx

Improve demo app to better show case the best practices consolidated for implementing magic link feature.
- Do not clear tokens if user is already authenticated and use a new magic link (e.g. org invitation link), and this may end up losing authenticated status on the client side.
- Properly set browser history state when calling `signIn()` function to validate the magic link.
- Clear tokens first on the "Callback" page when sign-in is redirected back. In case the tokens are not cleared when calling `signIn()`.
1. User not authenticated, use magic link to sign-in and register, both worked. ✅
2. User is authenticated, use new magic link to join organization. Worked. ✅
3. User is authenticated, use a magic link intended for another account. The switch account page showed up. ✅
- Choose to …

refactor(demo-app): better showcase the magic link usage in demo app

---

packages/experience/src/pages/ErrorPage/index.tsx
packages/experience/src/pages/OneTimeToken/index.tsx
packages/experience/src/pages/SwitchAccount/index.tsx

Improve go back logic handling in one-time token related intermediate pages (switch account page & error page)
- In the error page, remove "Go back to application" button from bottom. Also hide top navbar since it contains a "< Back" link.
- In the switch account page, make sure the "Back to current account" button doesn't use consent API, as that might introduce unexpected scopes to the authed user. Simply use "history.back()".
Local dev testing

refactor(experience): improve go back logic handling in one-time token pages

---

packages/core/src/libraries/one-time-token.ts
packages/core/src/middleware/koa-consent-guard.test.ts
packages/core/src/middleware/koa-consent-guard.ts
packages/core/src/tenants/Tenant.ts
packages/experience/src/App.tsx
packages/experience/src/pages/OneTimeToken/index.tsx
packages/experience/src/pages/Register/index.tsx
packages/experience/src/pages/SignIn/index.tsx
packages/experience/src/pages/SwitchAccount/index.tsx
packages/schemas/src/consts/experience.ts

Provision user who has a valid sign-in session to organizations when using one-time token that contains `jitOrganizationIds` in its context.
This enables the already signed-in users to accept organization invitations via a magic link.
Locally dev testing + UT

fix(core): provision user who has valid sign-in session to organizations when using one-time token

---

packages/experience/src/pages/OneTimeToken/index.tsx

Set one-time token associated email identifier to the hidden identifier input when submitting the authentication requests, which guarantees the browser password manager can always pick up a sign-in identifier when trying to saving the password.
Tested locally. See screenshot above.
- SIE enable email as sign-up identifier, and check "Create password" checkbox
- Create a one-time token with a new user email, and use it as a magic link to register
- User registered successfully, and then asked for password before proceeding.
- User sets password, and then Chrome password manager pops-up the dialog to confirm saving password
- In the confirm dialog above, both the email and password are pre-populated.

fix(experience): browser password manager should pick up one-time token email from hidden input

---

packages/core/src/libraries/one-time-token.ts
packages/core/src/routes/one-time-tokens.openapi.json
packages/core/src/routes/one-time-tokens.ts
packages/integration-tests/src/api/one-time-token.ts
packages/integration-tests/src/tests/api/one-time-tokens.test.ts

Add new management API to update one-time token status.

feat(core): add management API to update one-time token status

---

packages/core/src/libraries/one-time-token.ts
packages/core/src/queries/one-time-tokens.ts
packages/core/src/routes/one-time-tokens.openapi.json
packages/core/src/routes/one-time-tokens.ts
packages/core/src/routes/swagger/utils/documents.ts
packages/integration-tests/src/api/one-time-token.ts
packages/integration-tests/src/tests/api/one-time-tokens.test.ts

Add management API to fetch one-time token by its ID. (LOG-10871)
API integration tests

feat(core): add management API to fetch one-time token by ID

---

packages/core/src/queries/one-time-tokens.ts
packages/core/src/routes/one-time-tokens.openapi.json
packages/core/src/routes/one-time-tokens.ts
packages/integration-tests/src/api/one-time-token.ts
packages/integration-tests/src/tests/api/one-time-tokens.test.ts

Add management API to delete one-time token by ID.
Integration tests

feat(core): add management API to delete one-time token

---

packages/core/src/queries/one-time-tokens.ts
packages/core/src/routes/one-time-tokens.openapi.json
packages/core/src/routes/one-time-tokens.ts
packages/integration-tests/src/api/one-time-token.ts
packages/integration-tests/src/tests/api/one-time-tokens.test.ts

Add management API to batch fetch one-time tokens, filtering by `email` and `status`, and with optional pagination.
API integration tests

feat(core): add management API to batch fetch one-time tokens

---

packages/console/src/pages/Security/CaptchaFormFields/index.tsx
packages/console/src/pages/Security/CreateCaptchaForm/constants.ts
packages/console/src/pages/Security/CreateCaptchaForm/types.ts
packages/phrases/src/locales/en/translation/admin-console/security.ts

Rename reCAPTCHA form fileds label, to avoid confusing.

fix(console): change recaptcha form fields label

---

packages/console/src/pages/CaptchaDetails/index.tsx
packages/console/src/pages/Security/Guide/index.tsx
packages/console/src/pages/Security/index.tsx
packages/console/src/pages/Security/use-data-fetch.ts
packages/core/src/routes/captcha-provider/index.ts

Fix captcha provider deletion behavior:
1. Disable in SIE when deleted, enable when added.
2. Reload front-end page when delete, because we are unable to recover the data.
Local tested.

fix(core,console): fix captcha deletion behavior

---

packages/core/src/routes/experience/verification-routes/one-time-token.ts
packages/integration-tests/src/tests/api/experience-api/captcha/index.test.ts

Similar to https://github.com/logto-io/logto/pull/7196, one-time token flow should skip CAPTCHA verification.

fix(core): skip catpcha for otp

---

packages/core/src/queries/one-time-tokens.ts
packages/phrases/src/locales/ar/errors/one-time-token.ts
packages/phrases/src/locales/de/errors/one-time-token.ts
packages/phrases/src/locales/en/errors/one-time-token.ts
packages/phrases/src/locales/es/errors/one-time-token.ts
packages/phrases/src/locales/fr/errors/one-time-token.ts
packages/phrases/src/locales/it/errors/one-time-token.ts
packages/phrases/src/locales/ja/errors/one-time-token.ts
packages/phrases/src/locales/ko/errors/one-time-token.ts
packages/phrases/src/locales/pl-pl/errors/one-time-token.ts
packages/phrases/src/locales/pt-br/errors/one-time-token.ts
packages/phrases/src/locales/pt-pt/errors/one-time-token.ts
packages/phrases/src/locales/ru/errors/one-time-token.ts
packages/phrases/src/locales/tr-tr/errors/one-time-token.ts
packages/phrases/src/locales/zh-cn/errors/one-time-token.ts
packages/phrases/src/locales/zh-hk/errors/one-time-token.ts
packages/phrases/src/locales/zh-tw/errors/one-time-token.ts

Update i18n error message when failed to fetch one-time token by token value.
N/A

refactor(phrases): update token not found error message

---

packages/core/src/routes/organization/index.ts
packages/core/src/utils/SchemaRouter.ts

refactor org apis, resolves LOG-10882
Org APIs are using SchemaRouter class, before the change, the middleware passed to SchemaRouter will be applied globally. This is not expected, we want finer grained control on middleware.
In this change, we enabled API-level middleware assignment.

refactor(core): refactor org apis

---

packages/console/src/hooks/use-console-routes/routes/security.tsx
packages/console/src/pages/Security/PasswordPolicy/PasswordOption/index.module.scss
packages/console/src/pages/Security/PasswordPolicy/PasswordOption/index.tsx
packages/console/src/pages/Security/PasswordPolicy/PasswordPolicyForm/index.module.scss
packages/console/src/pages/Security/PasswordPolicy/PasswordPolicyForm/index.tsx
packages/console/src/pages/Security/PasswordPolicy/index.module.scss
packages/console/src/pages/Security/PasswordPolicy/index.tsx
packages/console/src/pages/Security/PasswordPolicy/use-password-policy.ts
packages/console/src/pages/Security/index.module.scss
packages/console/src/pages/Security/index.tsx
packages/console/src/pages/SignInExperience/PageContent/index.tsx
packages/integration-tests/src/tests/console/security/password-policy.test.ts
packages/integration-tests/src/ui-helpers/expect-console.ts
packages/phrases/src/locales/en/translation/admin-console/security.ts

Migrate the password policy settings page under the security section.
Test locally

refactor(console): move password policy to security page

---

.changeset/six-rivers-lick.md
packages/translate/src/openai.ts
packages/translate/src/sync.ts

Translate CLI tool should correctly read LLM model name from `.env` or other environment variable configurations.
Previously, the `const model` is defined before loading dotenv configs, and thus the model name in env is always ignored.
Locally tested

fix(translate): translate cli tool should read model name from env

---

packages/core/src/sentinel/basic-sentinel.test.ts
packages/core/src/sentinel/basic-sentinel.ts
packages/core/src/tenants/Tenant.ts

Read custom sentinel policy settings from sign-in experience settings. If none is provided, fall back to the default settings. 
UT case added.

feat(core): read sentinel policy settings

---

packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/one-time-token.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/one-time-token.test.ts

Do NOT check sign-in method when sign-in user with magic link (one-time token).
Previously if the email sign-in method is not enabled, we'll see the error below when sign-in via magic link.
```
This sign-in method is not enabled.
```
More API integration tests added

fix(core): do not check sign-in method on one-time token verification

---

packages/core/src/queries/sentinel-activities.ts
packages/core/src/routes/init.ts
packages/core/src/routes/sentinel-activities.openapi.json
packages/core/src/routes/sentinel-activities.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/core/src/sentinel/basic-sentinel.ts
packages/core/src/tenants/Queries.ts
packages/integration-tests/src/tests/api/experience-api/basic-sentinel.test.ts
packages/schemas/alterations/next-1744357867-add-sentinel-activities-hash-index.ts
packages/schemas/tables/sentinel_activities.sql

Add API to clear sentinel activities. This is useful for the admin to unblock users by a given list of identifiers. 
test locally

feat(core, schemas): add API to clear sentinel activities

---

.scripts/packages-meta.js

Fix the CI error caused by having `assert` argument in js scripts. Update it to `with`, since the `assert` is deprecated in Node 22. (Follow-up #7272)
Master CI should not fail. Pending verification later.

fix: publish scripts

---

.changeset/selfish-zoos-worry.md
packages/connectors/connector-oidc/src/constant.ts
packages/connectors/connector-oidc/src/index.ts
packages/connectors/connector-oidc/src/types.test.ts
packages/connectors/connector-oidc/src/types.ts

Add an optional `acceptStringTypedBooleanClaims` configuration to `OidcConnectorConfig`, with default value `false`.
For standard OIDC protocol, some claims such as `email_verified` and `phone_verified` are boolean-typed, but some providers may return them as string-typed. Enabling this option will convert string-typed boolean claims to boolean-typed, which provides better compatibility.
By enabling this configuration, the connector will accept string-typed boolean ID token claims, such as `email_verified` and `phone_verified`.
Covered by unit tests.

fix(connector): support string typed boolean ID token claims for OIDC connector

---

.changeset/sweet-houses-lie.md
.github/workflows/alteration-compatibility-integration-test.yml
.github/workflows/integration-test.yml
packages/cli/src/commands/install/utils.ts

be more flexible with Node.js versions when installing Logto via CLI to enable more users.

refactor(cli): loose CLI version restriction on Node.js

---

.changeset/five-melons-kneel.md
packages/core/src/middleware/koa-spa-proxy.ts
packages/integration-tests/src/tests/api/spa-proxy.test.ts

Our single-page application proxy now responds with a 404 for non-existing paths in `/assets` instead of falling back to the `index.html` file.
This prevents the browser and CDN from caching the `index.html` file for non-existing paths in `/assets`, which can lead to confusion and unexpected behavior.
Since the `/assets` path is used only for static assets, it is safe and improves the user experience. 
integration tests added.

refactor(core): respond 404 for non-existing paths in `/assets`

---

packages/core/src/sentinel/basic-sentinel.test.ts
packages/core/src/sentinel/basic-sentinel.ts
packages/integration-tests/src/tests/api/experience-api/basic-sentinel.test.ts
packages/integration-tests/src/tests/experience/basic-sentinel.test.ts
packages/integration-tests/src/ui-helpers/index.ts
packages/schemas/src/consts/sentinel.ts

Loosen the default sentinel policy settings:
- maxAttempts: 100
- lockoutDuration: 60
test locally

refactor(schemas): change default sentinel settings

---

packages/console/src/components/SignInExperiencePreview/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/PasswordDisabledNotification.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/SignUpAndSignInDiffSection/index.tsx
packages/console/src/pages/SignInExperience/PageContent/SignUpAndSignInChangePreview/index.tsx
packages/console/src/pages/SignInExperience/PageContent/index.tsx
packages/console/src/pages/SignInExperience/PageContent/utils/form.ts
packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
packages/console/src/pages/SignInExperience/components/Preview/index.tsx
packages/console/src/pages/SignInExperience/types.ts

This PR refactors the sign-in experience page data parsing logic and type definitions on the console. 
We need to omit the `mfa`, `captchaPolicy`, and `sentinelPolicy` fields from the raw sign-in experience data, as they are not editable on the sign-in experience page. 
- Those keys should be omitted from the form data.
- Those keys should be omitted from the submitted data.
- Those keys should not be used in any data comparison logic.
test locally

refactor(console): refactor sign-in experience page data

---

.changeset/gorgeous-apricots-breathe.md
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/verification-routes/one-time-token.openapi.json
packages/core/src/routes/init.ts
packages/core/src/routes/one-time-tokens.openapi.json
packages/core/src/routes/swagger/utils/documents.ts
packages/core/src/routes/swagger/utils/general.ts
packages/core/src/routes/swagger/utils/operation-id.ts
packages/experience/src/App.tsx
packages/integration-tests/src/tests/api/experience-api/register-interaction/one-time-token.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/one-time-token.test.ts
packages/integration-tests/src/tests/api/experience-api/verifications/one-time-token.test.ts
packages/integration-tests/src/tests/api/one-time-tokens.test.ts

Remove dev feature guard and add changeset for one-time token feature.
CI

chore: prepare to release the one-time token feature

---

packages/console/src/components/Region/index.tsx

The original logic incorrectly fall back to a string for region flag matching. This pull fixes the issue.
tested with javascript. need to test again after deployed.

refactor(console): fix region flag logic

---

packages/console/package.json
packages/console/src/hooks/use-inkeep-configs.ts
pnpm-lock.yaml

Completely fix the crash issue caused by a mis-used code editor theme in the inkeep AI bot.
Previously I was using the theme from `react-syntax-highlighter` package for the prism code editors in the AI bot, since we also use it in the Console app. However, after further investigation, inkeep uses theme from `prism-react-renderer`, and themes from these two packages are not 100% compatible.
Therefore, the inkeep config is updated to use the correct prism theme, and the crash issue is fixed completely.
Also the code editor theme is now fixed to "Dracula" (dark only).
Locally tested with built js files. No more app crash.

fix(console): fix crash issue caused by mis-used inkeep code editor theme

---

packages/core/src/routes/captcha-provider/index.ts

Add paywall for CAPTCHA in core.
Local tested.

feat(core): add paywall of captcha

---

packages/experience/src/components/Button/SocialLinkButton.tsx
packages/experience/src/components/Button/index.module.scss
packages/experience/src/components/Button/index.tsx

A loading button can not be "clickable", so set it to disabled. And remove the disabled state for this case, it should be disabled but looks like "normal" button, because of the delayed loading state.
Local tested.

fix(experience): loading button should be disabled

---

packages/experience/src/components/LoadingLayer/index.tsx
packages/experience/src/pages/DirectSignIn/index.module.scss
packages/experience/src/pages/DirectSignIn/index.tsx

This PR fixes issue #7347. Replace the global loading layer in the direct sign-in landing page. 
- Enable terms of use, and set the policy to "Require checkbox agreement on both registration and sign-in".
- Use any social direct sign-in method
The loading layer displayed in the direct sign-in landing page should not block any user interaction.  As we do not have any form in this page so it is safe to keep it as a  in place loading icon. 
test locally

fix(experience): replace global loading layer

---

packages/cli/src/commands/database/alteration/index.ts

fix(cli): convert Windows absolute paths to file URLs for dynamic imports
The dynamic import in `importAlterationScript` was failing on Windows because it used an absolute file path without converting it to a valid file URL. This commit updates the code to use `pathToFileURL` for converting file paths, resolving the ERR_UNSUPPORTED_ESM_URL_SCHEME error during database alteration deployment.
This change fixes a bug where dynamic imports were failing on Windows due to the use of absolute file paths without the proper `file://` scheme. By converting these paths using Node's `pathToFileURL`, the error is resolved and the deployment process works consistently across platforms.
Tested on Windows by running the `logto db alt deploy` command with a sample database URL. Verified that the …

fix(cli): convert Windows absolute paths to file URLs for dynamic imports

---

packages/console/src/pages/SignInExperience/PageContent/utils/parser.ts
packages/console/src/pages/SignInExperience/types.ts
packages/core/src/__mocks__/sign-in-experience.ts
packages/core/src/libraries/sign-in-experience/email-blocklist-policy.test.ts
packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
packages/core/src/libraries/sign-in-experience/index.ts
packages/core/src/queries/sign-in-experience.test.ts
packages/core/src/routes/sign-in-experience/index.ts
packages/experience/src/__mocks__/logto.tsx
packages/phrases/src/locales/en/errors/sign-in-experiences.ts
packages/schemas/alterations/next-1745735646-add-email-blocklist-policy-column-to-sie-table.ts
packages/schemas/src/foundations/jsonb-types/sign-in-experience.ts
packages/schemas/tables/sign_in_experiences.sql

Add email blocklist policy field to the sign-in experience settings.
- `blockDisposableAddresses`: Boolean value, indicates whether to resrtrict the disposable email address from sign-up. 
- `blockSubaddressing`: Boolean value, indicates whether to restrict the email subaddressing from sign-up. 
- `customBlocklist`: String list, specifies custom email address or email domain blocklist. 
test locally
Unit test added

feat(core,schemas,console): add email blocklist policy to sie

---

.npmrc
packages/core/src/libraries/sign-in-experience/email-blocklist-policy.test.ts
packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/libraries/sign-in-experience-validator.ts
packages/core/src/routes/experience/classes/profile.ts
packages/integration-tests/src/tests/api/experience-api/register-interaction/email-blocklist.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
packages/phrases/src/locales/ar/errors/session.ts
packages/phrases/src/locales/de/errors/session.ts
packages/phrases/src/locales/en/errors/session.ts
packages/phrases/src/locales/es/errors/session.ts
packages/phrases/src/locales/fr/errors/session.ts
packages/phrases/src/locales/it/errors/session.ts
packages/phrases/src/locales/ja/errors/session.ts
packages/phrases/src/locales/ko/errors/session.ts
packages/phrases/src/locales/pl-pl/errors/session.ts
packages/phrases/src/locales/pt-br/errors/session.ts
packages/phrases/src/locales/pt-pt/errors/session.ts
packages/phrases/src/locales/ru/errors/session.ts
packages/phrases/src/locales/tr-tr/errors/session.ts
packages/phrases/src/locales/zh-cn/errors/session.ts
packages/phrases/src/locales/zh-hk/errors/session.ts
packages/phrases/src/locales/zh-tw/errors/session.ts

Add email blocllist validation to all the experience API email profile fulfillment flow.
- link profile
- account creation
Extract the email profile from the verification record and validate the value against the email blocklist policy settings in SIE. Reject the use to create account or link new profile if the email is restricted by the policy. 
Unit test added
Integration tests added

feat(core): add email blocklist guard

---

.changeset/nice-houses-sneeze.md
packages/core/src/libraries/social.ts
packages/core/src/queries/user.ts
packages/core/src/routes/experience/classes/utils.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
packages/shared/src/utils/phone.test.ts
packages/shared/src/utils/phone.ts

Enhanced user lookup by phone with phone number normalization.
In some countries, local phone numbers are often entered with a leading '0'. However, in the context of the international format this leading '0' should be stripped. E.g., +61 (0)2 1234 5678 should be normalized to +61 2 1234 5678.
In the previous implementation, Logto did not normalize the user's phone number during the user sign-up process. Both 61021345678 and 61212345678 were considered as valid phone numbers, and we do not normalize them before storing them in the database. This could lead to confusion when users try to sign-in with their phone numbers, as they may not remember the exact format they used during sign-up. Users may also end up with different accounts for the same phone number, depending on how they entered …

feat(core): enhanced user lookup by phone number

---

packages/console/src/pages/Security/Blocklist/BlocklistForm/index.tsx
packages/core/src/libraries/sign-in-experience/email-blocklist-policy.ts
packages/experience/src/hooks/use-email-blocked-error-handler.ts
packages/experience/src/hooks/use-submit-interaction-error-handler.ts
packages/phrases/src/locales/ar/errors/session.ts
packages/phrases/src/locales/de/errors/session.ts
packages/phrases/src/locales/en/errors/session.ts
packages/phrases/src/locales/es/errors/session.ts
packages/phrases/src/locales/fr/errors/session.ts
packages/phrases/src/locales/it/errors/session.ts
packages/phrases/src/locales/ja/errors/session.ts
packages/phrases/src/locales/ko/errors/session.ts
packages/phrases/src/locales/pl-pl/errors/session.ts
packages/phrases/src/locales/pt-br/errors/session.ts
packages/phrases/src/locales/pt-pt/errors/session.ts
packages/phrases/src/locales/ru/errors/session.ts
packages/phrases/src/locales/tr-tr/errors/session.ts
packages/phrases/src/locales/zh-cn/errors/session.ts
packages/phrases/src/locales/zh-hk/errors/session.ts
packages/phrases/src/locales/zh-tw/errors/session.ts
packages/shared/src/node/env/GlobalValues.ts

Add disposable email validation in the experience API.
- Call Azure function `disposable-email-domain-validation` to validate a given email against disposable email domain list
- Add Azure function endpoint and API key environment.
- Block the blockDisposableEmail form field for OSS on the console. This is a cloud-only feature. 
test locally

feat(core,experience): add disposable email validation

---

.changeset/funny-eels-wonder.md
.changeset/moody-turtles-bake.md
packages/translate/src/openai.ts
packages/translate/src/sync-keys/utils.ts

instead of throwing an error, treat non-existing `import` targets as empty files

refactor: use `gpt-4.1` as the default translate model

---

packages/core/src/libraries/user.ts
packages/core/src/queries/user.ts
packages/core/src/routes/account/email-and-phone.ts
packages/core/src/routes/admin-user/basics.test.ts
packages/core/src/routes/admin-user/basics.ts
packages/core/src/routes/admin-user/mfa-verifications.test.ts
packages/core/src/routes/experience/classes/experience-interaction.test.ts
packages/core/src/routes/experience/classes/libraries/profile-validator.ts
packages/core/src/routes/experience/classes/verifications/social-verification.ts
packages/core/src/routes/interaction/actions/helpers.ts
packages/core/src/routes/interaction/actions/submit-interaction.mfa.test.ts
packages/core/src/routes/interaction/actions/submit-interaction.test.ts
packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.test.ts
packages/core/src/routes/interaction/verifications/mandatory-user-profile-validation.ts
packages/core/src/routes/interaction/verifications/profile-verification.profile-exist.test.ts
packages/core/src/routes/interaction/verifications/profile-verification.profile-registered.test.ts
packages/core/src/routes/interaction/verifications/profile-verification.protected-identifier.test.ts
packages/core/src/routes/interaction/verifications/profile-verification.ts
packages/integration-tests/src/tests/api/account/email-and-phone.test.ts
packages/integration-tests/src/tests/api/admin-user.test.ts
packages/integration-tests/src/tests/api/experience-api/profile/fulfill-user-profiles.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/password.test.ts
packages/integration-tests/src/utils.ts

This PR is a follow-up to #7382.
It replaces hasUserWithPhone with the new hasUserWithNormalizedPhone. The updated logic checks for the existence of the phone number in both of the following formats:
Standard international format: 64 4 123 4567
National format with a leading zero: 64 04 123 4567
This ensures both formats are treated as the same phone number. If either format is found, a phone number conflict error will be thrown.
Integration tests added

refactor(core): has user with normalized phone number match

---

.changeset/dirty-mice-fail.md
packages/core/src/saml-application/SamlApplication/index.ts
packages/core/src/sso/AzureOidcSsoConnector/index.ts
packages/core/src/sso/OidcConnector/index.ts
packages/core/src/sso/types/oidc.ts

Make the userinfo_endpoint field optional in the OIDC connector configuration to support providers like Azure AD B2C that do not expose a userinfo endpoint.
We've received reports that [Azure AD B2C SSO](https://learn.microsoft.com/en-us/azure/active-directory-b2c/userinfo-endpoint?pivots=b2c-custom-policy) applications do not provide a `userinfo_endpoint` in their OIDC metadata by default. This has been a blocker for users attempting to integrate Azure AD B2C SSO with Logto, as our current implementation strictly follows the OIDC spec and relies on the userinfo endpoint to retrieve user claims after authentication.
- Updated the OIDC config response schema to make the userinfo_endpoint optional.
- If the `userinfo_endpoint` is missing, the system will now extract user data directly from …

refactor(core): make userinfo endpoint optional for OIDC SSO connectors

---

packages/console/src/pages/Security/Captcha/CaptchaForm.tsx

This PR addresses a bug related to the Captcha form submission process. After toggling the enable captcha status switch and submitting the form, the updated form data was not retained when the user navigated away from the form page and returned. 
This issue arose because the form was using the cached data from the sign-in experience (SIE) as its default values, which did not reflect the latest updates due to SWR's caching logic.
Implemented a mutation of the SWR data upon successful form submission in the Captcha form. This ensures that any updates made to the form data are reflected in the SWR cache, allowing the form to display the most current state when the user navigates back to it.
test locally

fix(console): mutate sie data on captcha settings update

---

packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/index.ts
packages/core/src/routes/account/mfa-verifications.ts
packages/core/src/routes/verification/index.openapi.json
packages/core/src/routes/verification/index.ts
packages/integration-tests/src/api/verification-record.ts
packages/integration-tests/src/helpers/index.ts
packages/integration-tests/src/helpers/sign-in-experience.ts
packages/integration-tests/src/tests/api/account/mfa.test.ts
packages/schemas/src/foundations/jsonb-types/account-centers.ts

New feature: add WebAuthn (Passkey) via account API.
1. Get registraction info from `POST /verifications/web-authn/registration`
2. Get webauthn response from local device
3. Verify response by `POST /verifications/web-authn/registration/verify` and get "verification record id".
4. Use this id to complete binding `POST /my-account/mfa-verifications`
Please notice that some APIs are not covered by integration tests, because we dont' have an easy way to generate mock webauthn response to pass the verification.
Integration tests & local test.

feat(core): add passkey via account api

---

packages/console/src/components/MfaFactorName/index.tsx

Hide passkey name when `name` and `agent` are both empty.
Local tested.

fix(console): hide name label if agent is empty

---

packages/core/src/routes/experience/classes/verifications/web-authn-verification.ts
packages/core/src/routes/experience/verification-routes/web-authn-verification.ts
packages/core/src/routes/interaction/utils/webauthn.test.ts
packages/core/src/routes/interaction/utils/webauthn.ts
packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
packages/core/src/routes/verification/index.ts

Set allow origin list for webauthn util functions:
1. Allow current URL and the origin list in `account_center` table.
2. Remove the expected `rpId` in verification, since this is already specific in registration options.
Local tested, successfully registered a new passkey in different domain.

feat(core): allow origin list for webauthn register and verify

---

packages/schemas/alterations/next-1749026308-add-oidc-session-extension-table.ts
packages/schemas/tables/oidc_model_instances.sql
packages/schemas/tables/oidc_session_extensions.sql

The `oidc_model_instances` table—maintained by the OIDC provider—stores only the standard session payload and offers no flexibility for product-specific fields. Yet our application must capture extra, business-driven details about each session, such as the authentication verification method or other user-interaction metadata that fall outside the provider’s schema.
Compounding the problem, every `Interaction` instance is deleted as soon as the flow completes, leaving no persistent record of those details.
To bridge this gap, we introduce `oidc_session_extensions`: a companion table keyed to the rows in oidc_model_instances where model_name = 'Session'. This extension table holds any additional session metadata our product requires. By cleanly separating custom data from the provider’s …

feat(schemas): add oidc_session_extensions table

---

.changeset/pink-rules-compare.md
packages/core/src/routes/interaction/additional.ts
packages/core/src/routes/interaction/utils/webauthn.ts
packages/integration-tests/src/tests/api/account/mfa.test.ts

Set "displayName" of WebAuthn registration options. Although this is an optional field, an empty value still causes errors on some cases. For example, on Windows with "scan with iPhone".
Local tested with Windows machine.

fix(core): add display name to webauthn registration options

---

packages/console/scripts/generate-jwt-customizer-type-definition.ts
packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/GuideCard/index.tsx
packages/console/src/pages/CustomizeJwtDetails/MainContent/SettingsSection/InstructionTab/index.tsx
packages/console/src/pages/CustomizeJwtDetails/utils/config.tsx
packages/console/src/pages/CustomizeJwtDetails/utils/type-definitions.ts
packages/core/src/oidc/extra-token-claims.ts
packages/core/src/queries/oidc-session-extensions.ts
packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/utils/zod.ts
packages/integration-tests/src/__mocks__/jwt-customizer.ts
packages/integration-tests/src/tests/api/oidc/get-access-token.test.ts
packages/phrases/src/locales/en/translation/admin-console/jwt-claims.ts
packages/schemas/src/types/logto-config/jwt-customizer.ts
packages/schemas/src/types/verification-records/enterprise-sso-verification.ts

Introduce user interaction context to the custom token claims script. Make the user's last submitted interaction verification records data accessible to the developers through a custom token claims script. 
1. Schemas: 
- Add a new interaction context guard and data type in the JWT customizer access token context. Including `interactionEvent`, `userId`, and `verificationRecords` with sensitive data filtered. 
2. Core:
- Retrieve the user interaction last submission data from the `odic_session_extenstions` using token's `sesssion_uid` and pass the formated interaction data as user interaction context to the JWT customizer.
- Update the Zod to openapi util method. Add a new `jsonGuard` type zod type parser.  By default, the `zodTypeToSwagger` parser …

feat(core,console,schemas): add interaction context to custom claims

---

packages/core/src/routes/interaction/utils/webauthn.ts
packages/integration-tests/src/tests/api/account/mfa.test.ts

Refactor `verifyWebAuthnAuthentication`:
1. The error code is now 400.
2. Show detailed message.

refactor(core): handle webauthn regsitration verify error

---

packages/console/src/hooks/use-subscribe.ts

Problem Analysis:
1. Safari has strict popup blocking policies, especially on mobile Safari (iPhone)
2. When window.open() is called after an async operation (API call), Safari considers
it as not being triggered directly by user action and blocks the popup
3. Previous attempts to work around this with pre-opened windows still involved hardcoded HTML
New Solution:
- Instead of opening a popup, navigate in the current window
- This completely bypasses popup blocking issues
- Provides better mobile experience
The payment portal will handle returning to the callback URL when done.
Tested on iPhone Safari (deployed this change to Logto Cloud dev).
https://github.com/user-attachments/assets/76c3ad26-5cda-4128-b45f-ca53a315744d

fix(console): fix payment page cannot open in iOS Safari issue

---

.changeset/lemon-walls-fry.md
packages/core/src/sso/AzureOidcSsoConnector/index.ts

Make `access_token` optional in Azure OIDC SSO connector token response.
Previously, the Azure OIDC connector strictly required an `access-token` in the token response, which caused issues with Azure B2C applications that only return ID tokens.
This change makes the connector more flexible by:
- Making access token optional in token response
- Conditionally fetching user claims from userinfo endpoint only when:
- Access token is present in the response
- Userinfo endpoint is supported by the provider
- Falling back to ID token claims when access token is not available
Guarded by integration test

fix(core): make access_token optional for Azure SSO

---

packages/integration-tests/src/__mocks__/profile-fields-mock.ts
packages/integration-tests/src/api/custom-profile-fields.ts
packages/integration-tests/src/api/index.ts
packages/integration-tests/src/tests/api/custom-profile-fields.test.ts

Add API integration tests for the CURD management APIs of custom profile fields.
CI

test: add API tests for custom profile fields management APIs

---

.changeset/sour-poems-whisper.md
packages/tunnel/package.json
pnpm-lock.yaml

Update `http-proxy-middleware` dependency in Logto Tunnel CLI package.
Locally

chore(tunnel): security updates for tunnel-cli dependencies

---

.changeset/olive-falcons-invite.md
packages/core/src/routes/admin-user/basics.ts
packages/integration-tests/src/tests/api/admin-user.test.ts
packages/schemas/alterations/next-1750663091-change-user-password-encrypted-length.ts
packages/schemas/tables/users.sql

change password encrypted length to 256, to support hash algorithm like `sha512`.
Local tested with sha512

fix(schemas): change password encrypted length to 256

---

.scripts/compare-database.js
.scripts/compare-database.test.js
package.json

update compare DB script data sorting logics.
When comparing and sorting objects, our current key sorting approach might have some issues. We filter out keys whose values are of boolean type when apply sort on array elements.
We add test script for DB compare functions and add the test to CI.
Test with Cloud CI. See [this PR](https://github.com/logto-io/cloud/pull/1251).

chore: update compare DB script data sorting logics

---

packages/experience/src/Providers/CaptchaContextProvider/index.tsx
packages/experience/src/include.d/global.d.ts

Added support for the new size property in the Cloudflare Turnstile widget component.
This allows the widget to scale responsively and fill the available space, making it easier to control its size via custom CSS, especially on the login screen.
By default, the Turnstile widget comes with size="normal" and a maximum width of 300px, which limits its responsiveness.
With this change, we now set the widget to use size="flexible", allowing it to stretch and fill the full container width.
Before:
The Turnstile widget was fixed at a maximum of 300px width, regardless of container size.
After:
By setting a flexible size, the widget can now scale to fill the full container, adapting to larger layouts such as the login screen.
Tested locally on the login page verifying that the widget now …

fix(experience): adding flexible size property in turnstile widget

---

packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/mfa-verifications.ts
packages/integration-tests/src/api/account-center.ts
packages/integration-tests/src/api/my-account.ts
packages/integration-tests/src/tests/api/account/mfa.test.ts

feat(core): add TOTP verification to MFA endpoints

---

packages/integration-tests/src/api/my-account.ts
packages/integration-tests/src/tests/api/account/mfa.test.ts

Add integration tests for delete user mfa verification. Previously, we are unable to add a verification in integration tests, so the test cases are missing.
Integration tesets.

test: add integration tests for delete mfa

---

packages/core/src/utils/secret-encryption.test.ts
packages/core/src/utils/secret-encryption.ts
packages/schemas/src/foundations/jsonb-types/secrets.ts
packages/schemas/src/types/index.ts
packages/schemas/src/types/secrets.ts
packages/schemas/tables/secrets.sql
packages/shared/src/database/types.ts
packages/shared/src/node/env/GlobalValues.ts

Add secret encryption utility methods to encrypt and decrypt given secrets.
- Add the `SecretBuffer` type annotation and the corresponding Zod custom buffer type guard to the `iv`, `authTag`, `ciphertext`, and `encryptedDek` fields. This ensures consistent data types across all secret encryption fields, which must be of type Buffer.
- Add `encryptSecret` and `decryptSecret`. 
- Add global KEK (Key encryption key) as a required environment variable.

feat(schemas, core): add secret encryption util method

---

packages/core/src/__mocks__/custom-profile-fields.ts
packages/core/src/__mocks__/index.ts
packages/core/src/libraries/sign-in-experience/index.test.ts
packages/core/src/libraries/sign-in-experience/index.ts
packages/integration-tests/src/tests/api/well-known.test.ts
packages/schemas/src/types/sign-in-experience.ts

Introduces support for custom profile fields in the sign-in experience. Updates tests and schema types to reflect the new `customProfileFields` property.
API integration test case added.

feat(core,schemas): add custom profile fields to sign-in experience well-known cache

---

packages/core/src/libraries/custom-profile-fields/utils.ts
packages/integration-tests/src/__mocks__/profile-fields-mock.ts
packages/integration-tests/src/tests/api/custom-profile-fields.test.ts
packages/phrases/src/locales/ar/errors/custom-profile-fields.ts
packages/phrases/src/locales/de/errors/custom-profile-fields.ts
packages/phrases/src/locales/en/errors/custom-profile-fields.ts
packages/phrases/src/locales/es/errors/custom-profile-fields.ts
packages/phrases/src/locales/fr/errors/custom-profile-fields.ts
packages/phrases/src/locales/it/errors/custom-profile-fields.ts
packages/phrases/src/locales/ja/errors/custom-profile-fields.ts
packages/phrases/src/locales/ko/errors/custom-profile-fields.ts
packages/phrases/src/locales/pl-pl/errors/custom-profile-fields.ts
packages/phrases/src/locales/pt-br/errors/custom-profile-fields.ts
packages/phrases/src/locales/pt-pt/errors/custom-profile-fields.ts
packages/phrases/src/locales/ru/errors/custom-profile-fields.ts
packages/phrases/src/locales/tr-tr/errors/custom-profile-fields.ts
packages/phrases/src/locales/zh-cn/errors/custom-profile-fields.ts
packages/phrases/src/locales/zh-hk/errors/custom-profile-fields.ts
packages/phrases/src/locales/zh-tw/errors/custom-profile-fields.ts

Do NOT allow configuring sign-in identifier fields in the "custom profile fields" feature, including:
- primaryEmail
- email
- primaryPhone
- phone
- username
These fields are sign-in identifiers related and can only be update through management API or account API.
Locally tested & UT + CI

refactor(core,phrases): disallow sign-in identifiers in custom profile fields

---

.github/workflows/alteration-compatibility-integration-test.yml
.github/workflows/integration-test.yml
packages/connectors/connector-mock-social/src/constant.ts
packages/connectors/connector-mock-social/src/index.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/api/connector.ts
packages/integration-tests/src/helpers/experience/index.ts
packages/integration-tests/src/tests/api/connector.test.ts
packages/integration-tests/src/tests/api/experience-api/profile/social-fullfill-user-profiles.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts

1. Update the mock-social-connector to support token storage
2. Update the GitHub interaction test action to include the `SECRET_VAULT_KEK` env variable.
3. Split the original social sign-in interaction API integration tests for a better test case structure.
4. Update the social sign-in interaction test cases to include token storage. Test the social connector authentication with the token secret storage enabled flow. 
integration test

test: add integration tests for token storage

---

packages/core/src/routes/experience/classes/libraries/mfa-validator.ts
packages/core/src/routes/interaction/verifications/mfa-verification.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/require-mfa-on-sign-in.test.ts

This PR implements the `requireMfaOnSignIn` user setting functionality that allows users to bypass MFA verification during sign-in, with proper policy override support. When `requireMfaOnSignIn` is set to false, users can skip MFA verification even if they have MFA factors configured, unless the MFA policy is set to `Mandatory`.
Because administrators can enforce MFA through policy regardless of user preference, there is no need to restrict this option.
Unit & Integration tests.

feat(core): apply requireMfaOnSignIn

---

packages/core/src/routes/interaction/utils/single-sign-on.test.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/core/src/sso/AzureOidcSsoConnector/index.ts
packages/core/src/sso/OidcConnector/index.ts
packages/core/src/sso/OidcConnector/utils.test.ts
packages/core/src/sso/OidcConnector/utils.ts
packages/core/src/sso/SamlSsoConnector/index.ts

This PR refactors the return type of the SSO connector’s `getUserInfo` method.
Previously, the `getUserInfo` method returned only a userInfo object. However, as we prepare to support token storage for OIDC SSO connectors, we need to return both the fetched user information and the token response to the upper scope. Therefore, the method's return type has been updated as follows:
- OIDC connectors: `{ userInfo, tokenResponse }`
- SAML connectors: `{ userInfo }`

refactor(core): refactor sso getUserInfo endpoint

---

packages/core/src/libraries/social.ts
packages/core/src/libraries/sso-connector.ts
packages/core/src/queries/secret.ts
packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/helpers.ts
packages/core/src/routes/experience/classes/libraries/provision-library.ts
packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
packages/core/src/routes/experience/types.ts
packages/core/src/routes/interaction/utils/single-sign-on.test.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/core/src/test-utils/mock-libraries.ts
packages/core/src/utils/secret-encryption.ts
packages/schemas/src/types/logto-config/jwt-customizer.ts
packages/schemas/src/types/secrets.ts
packages/schemas/src/types/verification-records/enterprise-sso-verification.ts
packages/schemas/src/types/verification-records/social-verification.ts
packages/toolkit/connector-kit/src/types/social.ts

This PR implements the token storage for the enterprise SSO authentication flow. 
- Extract the `encryptTokenResponse` util method from the social library to secret utils.  So the method can be shared by the enterprise SSO library. 
- Implement the query method and library method to store the token set secret from the enterprise SSO connector to the DB. 
- Update all OIDC SSO connectors to return the token response from the `getUserInfo` method.
- Update the `verifySsoIdentity` utility method used in experience interactions. If token storage is enabled for the connector, return the encrypted token set received from the SSO provider.
- Update the experience interaction SSO verification and profile classes to handle and store the encrypted enterprise SSO token set.
- During interaction …

feat(core,schemas): implement sso token storage

---

.changeset/README.md
.changeset/config.json
.changeset/shaggy-fans-remain.md
docker-compose.yml
packages/api/.gitignore
packages/api/README.md
packages/api/check-types.sh
packages/api/docker-compose.local.yml
packages/api/generate-types.sh
packages/api/package.json
packages/api/src/client-credentials.test.ts
packages/api/src/client-credentials.ts
packages/api/src/management.test.ts
packages/api/src/management.ts
packages/api/tsconfig.build.json
packages/api/tsconfig.json
pnpm-lock.yaml

This PR introduces `@logto/api`, a TypeScript SDK for Logto's APIs using client credentials flow. The initial version includes Management API.
- OAuth 2.0 M2M authentication with automatic token management
- Full TypeScript support with OpenAPI-generated types
- Supports both Logto Cloud and self-hosted deployments
- Middleware automatically includes access tokens in requests
```ts
import { createManagementApi } from '@logto/api/management';
// Logto Cloud
const { apiClient } = createManagementApi('tenant-id', {
clientId: 'client-id',
clientSecret: 'client-secret',
});
// Self-hosted
const { apiClient } = createManagementApi('default', {
clientId: 'client-id',
clientSecret: 'client-secret',
baseUrl: 'https://your-instance.com',
});
const response = await apiClient.GET('/api/users'); …
```

feat: init `@logto/api`

---

packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/index.ts
packages/core/src/routes/account/middlewares/koa-account-center.ts
packages/core/src/routes/account/third-party-tokens.ts
packages/core/src/routes/swagger/utils/documents.ts
packages/core/src/utils/sql.ts
packages/phrases/src/locales/en/errors/index.ts
packages/phrases/src/locales/en/errors/secrets.ts
packages/schemas/src/types/secrets.ts
packages/shared/src/database/types.ts

Add third-party token account APIs for users to retrieve access tokens issued by social or enterprise SSO providers. 
1. Add a new `GET /my-account/identities/:target/access-token` endpoint to retrieve social access token.
2. Add a new `GET /my-account/sso-identities/:connectorId/access-token` endpoint to retrieve the enterprise SSO access token.
3. Refactor the `koaAccountCenter` middleware. Whitelist the two newly added endpoints. By design, retrieving a third-party access token does not require the account center to be enabled. 
4. Bug fix. Update the `convertToPrimitiveOrSql`  SQL util method to handle the Buffer typed value properly. Previously, all `Buffer` typed values were handled as an object, converted using `JSON.stringify`, and stored in …

feat(core): add third-party token account API

---

packages/connectors/connector-github/src/index.ts
packages/core/src/libraries/social.ts
packages/core/src/libraries/sso-connector.ts
packages/core/src/routes/account/third-party-tokens.ts
packages/core/src/routes/interaction/utils/single-sign-on.ts
packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
packages/core/src/sso/OidcConnector/index.ts
packages/core/src/sso/OidcConnector/utils.ts
packages/core/src/test-utils/mock-libraries.ts
packages/core/src/utils/secret-encryption.ts
packages/toolkit/connector-kit/src/types/social.ts

This PR implements the token refresh flow for federated third-party access token exchange.
If the access token issued by a third-party social or enterprise SSO connector has expired and a refresh token is available, Logto will automatically refresh the access token and return the updated response.
1. connector-kit: Adds a new callback method type definition: `getAccessTokenByRefreshToken` for social connectors.
This method allows the connector to exchange a new access token using a refresh token.
It is required for all social connectors that have token storage enabled.
2. connector-github: Update the github connector with new `getAccessTokenByRefreshToken` method to support token refresh.
3. Social library and SSO library:  Adds a new `refreshTokenSetSecret` method to handle token refresh …

feat(core): implement token refresh flow

---

packages/core/src/libraries/custom-profile-fields/utils.ts
packages/experience/src/pages/Continue/ExtraProfileForm/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/use-validate-field.ts

Updated validation logic in custom profile field utilities and form validation to allow undefined values for optional fields. This change ensures that fields are only validated when values are present, preventing errors when optional fields are left empty. (fixes log-11822 log-11821 log-11819)
Locally tested

fix(core,experience): relax validation for optional custom profile field

---

packages/experience/src/components/InputFields/AddressField/index.tsx
packages/experience/src/components/InputFields/SelectField/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/FullnameSubForm/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/index.tsx

Revalidate the profile form status on field blur. Previously this did not work as the blur event was not passed into the customized `InputField` component, and broke the event bubble and handling.
Locally tested. Now the form field error state is revalidated on blur.

fix(experience): should revalidate the profile form on blur

---

.changeset/neat-points-invite.md
packages/core/src/routes/account/index.openapi.json
packages/core/src/routes/account/mfa-verifications.ts
packages/integration-tests/src/tests/api/account/mfa-backup-codes.test.ts
packages/integration-tests/src/tests/api/account/mfa-totp.test.ts

Add changeset and remove dev features guard of Account API for MFA.
N/A

chore: add changeset of account api mfa

---

packages/core/src/routes/admin-user/enterprise-sso.openapi.json
packages/core/src/routes/admin-user/enterprise-sso.test.ts
packages/core/src/routes/admin-user/enterprise-sso.ts
packages/core/src/routes/admin-user/social.openapi.json
packages/core/src/routes/admin-user/social.ts
packages/integration-tests/src/api/admin-user.ts
packages/integration-tests/src/tests/api/account/social.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts

This PR refactors the design of the GET user social identity and enterprise SSO identity API. 
1.  Replace the `GET /users/:userId/identities/:target/secret` with `GET /users/:userId/identities/:target`.
- Align API design with the GET sso-identity API
- This API is better suited for our console UI form, where we need to retrieve both the user identity details and associated secrets on the same page.
- Added a new includeTokenSecret query parameter to control whether the associated token secret should be included in the response.
2. Update the `GET /users/:userId/sso-identities/:target` API
- Renamed `enterpriseSsoIdentity` to `ssoIdentity` for consistency with other user SSO identity response bodies (e.g., GET /users/:userId).
- Renamed `tokenSet` to `tokenSecret` to match the social API …

refactor(core): refactor get user social/sso identities API

---

packages/core/src/queries/secret.ts
packages/core/src/routes/admin-user/enterprise-sso.openapi.json
packages/core/src/routes/admin-user/enterprise-sso.ts
packages/core/src/routes/admin-user/social.ts
packages/schemas/src/types/user.ts

Add new `GET /users/:userId/all-identities` API to retrieve the user's social identities and enterprise SSO identities. 
If the `includeTokenSecret` parameter is set, this API also returns the token secret associated with each identity. 
test locally
Will add integration tests later.

feat(core): add get user social and sso identities API

---

packages/core/src/routes/experience/classes/experience-interaction.ts
packages/core/src/routes/experience/classes/mfa.ts
packages/core/src/routes/experience/classes/profile.ts
packages/core/src/routes/experience/classes/utils.ts
packages/core/src/routes/experience/classes/verifications/backup-code-verification.ts
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/classes/verifications/enterprise-sso-verification.ts
packages/core/src/routes/experience/classes/verifications/index.ts
packages/core/src/routes/experience/classes/verifications/new-password-identity-verification.ts
packages/core/src/routes/experience/classes/verifications/one-time-token-verification.ts
packages/core/src/routes/experience/classes/verifications/password-verification.ts
packages/core/src/routes/experience/classes/verifications/social-verification.ts
packages/core/src/routes/experience/classes/verifications/totp-verification.ts
packages/core/src/routes/experience/classes/verifications/verification-record.ts
packages/core/src/routes/experience/classes/verifications/web-authn-verification.ts
packages/core/src/routes/experience/const.ts
packages/core/src/routes/experience/experience.openapi.json
packages/core/src/routes/experience/index.ts
packages/core/src/routes/experience/types.ts
packages/integration-tests/src/client/experience/const.ts
packages/integration-tests/src/client/experience/index.ts
packages/integration-tests/src/client/experience/types.ts
packages/integration-tests/src/tests/api/experience-api/interaction.test.ts
packages/schemas/src/types/verification-records/backup-code-verification.ts
packages/schemas/src/types/verification-records/enterprise-sso-verification.ts
packages/schemas/src/types/verification-records/new-password-identity-verification.ts
packages/schemas/src/types/verification-records/social-verification.ts
packages/schemas/src/types/verification-records/totp-verification.ts
packages/schemas/src/types/verification-records/web-authn-verification.ts

Introduces a new `GET /experience/interaction` endpoint for returning sanitized interaction data, including profile and verification records, excluding sensitive fields.
Also adds corresponding Zod guards, types, and integration tests to verify correct public data exposure for various verification flows.

feat(core): add sanitized interaction data API and tests

---

packages/core/src/routes/admin-user/enterprise-sso.test.ts
packages/core/src/utils/secret-encryption.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts
packages/schemas/src/types/secrets.ts

Since the secret details are now desensitized in all token secret management API responses, developers can no longer determine whether a `refresh_token` is available. To address this, we introduce a new field, `hasRefreshToken`, in the token secret metadata. This boolean field explicitly indicates whether a `refresh_token` is present in the underlying token secret, improving clarity and enabling the console to display the offline access status appropriately.  
Integration test updated

refactor(core): add `hasRefreshToken` to token secret response

---

packages/console/src/pages/EnterpriseSsoDetails/Connection/OidcMetadataForm/index.tsx
packages/console/src/pages/EnterpriseSsoDetails/types/oidc.ts
packages/core/src/sso/GoogleWorkspaceSsoConnector/index.ts
packages/phrases/src/locales/en/translation/admin-console/enterprise-sso-details.ts

Enable offline access in the Google Workspace SSO connector.
Unlike standard OAuth/OIDC connectors, Google Workspace does not support the `offline_access` scope. Instead, it uses an additional authorization parameter: `access_type=offline` to indicate that offline access is requested and a refresh token should be issued.
To support this, we've added a configuration option `offlineAccess` to the Google SSO connector. When enabled, the connector will include `access_type=offline` in the authorization request to Google.
test locally

refactor(console, core): add offline access to google SSO connector

---

packages/core/src/queries/secret.ts
packages/core/src/routes/connector/index.ts
packages/core/src/routes/sso-connector/index.ts
packages/integration-tests/src/api/sso-connector.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/enterprise-sso.test.ts
packages/integration-tests/src/tests/api/experience-api/sign-in-interaction/social.test.ts

Should delete all token secrets when token storage is disabled.
test locally integration test case updated

feat(core): delete token secrets on token storage disabled

---

.changeset/brave-boats-travel.md
packages/schemas/alterations/next-1753669579-add-organization-user-relations-foreign-key.ts
packages/schemas/tables/organization_user_relations.sql
packages/schemas/tables/users.sql

Add a tenant-aware foreign key constraint to `organization_user_relations` table
Developers could mistakenly assign a `user_id` from other tenants to an organization, causing 500 errors on organization users API endpoints. The original `organization_user_relations` table only had a foreign key constraint on `users (id)`, allowing any existing user ID to be assigned regardless of tenant isolation.
Logto applies Row Level Security (RLS) on all tables to isolate tenant data access. When joining the `users` table with `organization_user_relations`, the actual user data becomes inaccessible to the current tenant due to RLS restrictions, causing user data to return `null` and triggering 500 server errors.
Added a composite foreign key constraint `(tenant_id, user_id)` referencing `users …

fix(schemas): add tenant-aware foreign key constraint

---

packages/connectors/connector-oidc/src/constant.ts
packages/connectors/connector-oidc/src/index.ts
packages/connectors/connector-oidc/src/utils.ts

Enable token storage for the OIDC standard connector.
- introduce the `getTokenResponseAndUserInfo`  method that returns both the userInfo and the token response
- introduce the `getAccessTokenByRefreshToken` method that handle the access token refresh flow. 
test locally

feat(connector): enable token storage for OIDC standard connector

---

packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldDetails/ProfileFieldDetailsForm/index.module.scss
packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldDetails/ProfileFieldDetailsForm/index.tsx
packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldDetails/index.tsx
packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/hooks.ts
packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/utils.ts
packages/console/src/pages/SignInExperience/PageContent/components/ProfileFieldPartSubForm/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/AddressSubForm/index.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/FullnameSubForm/index.tsx
packages/experience/src/types/guard.ts
packages/schemas/src/foundations/jsonb-types/custom-profile-fields.ts
packages/schemas/src/types/custom-profile-fields.ts

Refactors the profile field details page, with the following major updates and fixes:
- Do not set label for built-in field types, leave the label empty and fallback to the i18n translation for display.
- Loose data guard on `label` field, make it optional on creating and updating fields.
- Refactor field details page, put the page header and form content together in one component, so that the header title can watch the form content and render dynamically in-sync with the `label` input.
- Improve the handling of SWR cache pupolation in the profile field list view. The list now updates when updating or deleting fields, without a splash of loading screen.
Fixes log-11929, log-11936, log-11938, log-11942
Locally
~~- [ ] …

fix(console,experience,schemas): refactor profile field details and improve label handling

---

packages/integration-tests/src/tests/api/organization/organization-user.test.ts

The `organization-user.test.ts` would fail randomly with `TimeoutError: Request timed out` failures in three specific test cases:
- "should be able to get organization users with pagination"
- "should be able to get organization users with search" 
- "should be able to get organization users with their roles"
The cause is that the test setup was creating 30 users concurrently using `Promise.all()`, and could run out db connection pool.
Solution: replaced concurrent user creation with sequential approach.

fix(test): resolve intermittent timeout in organization-user test

---

packages/core/src/queries/oidc-model-instance.test.ts
packages/core/src/queries/oidc-model-instance.ts

Handle duplicate payload field in `findPayloadByPayloadField` and clean up duplicates.  
We have observed unexpected 500 exceptions in production when calling the Experience API. Investigation revealed that `Session.findByUid` in `oidc-provider` was throwing a `DataIntegrity` error, which was caused by duplicate session `uid` values stored in the `oidc-model-instances` payload field. This is a very rare case, but when it occurs, it breaks the assumption of unique session identifiers and causes the API to fail.
To address this issue, we have updated the findPayloadByPayloadField query logic:
- The function now uses `pool.any` to fetch all matching records.
- If more than one record is found (i.e., duplicates), it deletes all of them as corrupted data and returns null.
- If exactly one …

refactor(core): refactor findPayloadByPayloadField query

---

packages/experience/src/pages/Continue/ExtraProfileForm/use-field-label.ts
packages/experience/src/types/guard.ts
packages/phrases-experience/src/locales/ar/profile.ts
packages/phrases-experience/src/locales/de/profile.ts
packages/phrases-experience/src/locales/en/profile.ts
packages/phrases-experience/src/locales/es/profile.ts
packages/phrases-experience/src/locales/fr/profile.ts
packages/phrases-experience/src/locales/it/profile.ts
packages/phrases-experience/src/locales/ja/profile.ts
packages/phrases-experience/src/locales/ko/profile.ts
packages/phrases-experience/src/locales/pl-pl/profile.ts
packages/phrases-experience/src/locales/pt-br/profile.ts
packages/phrases-experience/src/locales/pt-pt/profile.ts
packages/phrases-experience/src/locales/ru/profile.ts
packages/phrases-experience/src/locales/tr-tr/profile.ts
packages/phrases-experience/src/locales/uk-ua/profile.ts
packages/phrases-experience/src/locales/zh-cn/profile.ts
packages/phrases-experience/src/locales/zh-hk/profile.ts
packages/phrases-experience/src/locales/zh-tw/profile.ts

Fix a bug that the field i18n label is missing in error message when fulfilling profile in the SIE. Caused by the `??` operator fallback not being able to fallback empty strings.
Also found the "fullname" field name is mismatch with the i18n phrase key. Update it from `fullName` to `fullname`.
Locally tested and the field names can be displayed properly in error messages.

fix(experience): field i18n label should be displayed properly in error message on profile fulfulling page

---

packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/data-parser.ts

Introduces default values (1, 100) to `minLength` and `maxLength` configs for text-type custom profile fields.

refactor: add minLength and maxLength default values to profile fulfilling text fields

---

packages/experience/src/components/Dropdown/index.module.scss
packages/experience/src/components/InputFields/PrimitiveProfileInputField/index.tsx
packages/experience/src/components/InputFields/SelectField/index.module.scss

Refactor the select field component in Experience, including:
- Add extra padding (8px) around the dropdown area
- Cut off overflow text content and append ellipsis to the end

refactor(experience): select field should cut off overflow text and have extra dropdown padding

---

packages/core/src/libraries/user.utils.ts
packages/core/src/routes/experience/classes/helpers.ts
packages/core/src/routes/experience/classes/libraries/mfa-validator.ts
packages/core/src/routes/experience/classes/mfa.ts
packages/core/src/routes/interaction/actions/submit-interaction.ts
packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
packages/experience/src/apis/experience/mfa.ts
packages/experience/src/containers/VerificationCode/use-continue-flow-code-verification.ts
packages/experience/src/hooks/use-send-mfa-payload.ts
packages/schemas/src/foundations/jsonb-types/users.ts
packages/schemas/src/types/interactions.ts

Clean up unused code related to email SMS MFA functionality that is no longer needed after recent MFA implementation changes.
New binding information is stored in user profile, not `bindMfa` object. Verification information is stored as verification records.
Existing MFA tests continue to pass

refactor(core): remove unused email sms mfa code

---

packages/experience/src/types/guard.ts

Date type field should not report a type error when fulfilling missing profile properties. Previously there's a missing `placeholder` config in the superstruct data guard, which ends up with a runtime error on submitting form.
Locally tested

fix(experience): date field should not report type error when fulfilling profile

---

packages/core/src/libraries/custom-profile-fields/utils.ts
packages/integration-tests/src/tests/api/custom-profile-fields.test.ts
packages/phrases/src/locales/ar/errors/custom-profile-fields.ts
packages/phrases/src/locales/de/errors/custom-profile-fields.ts
packages/phrases/src/locales/en/errors/custom-profile-fields.ts
packages/phrases/src/locales/es/errors/custom-profile-fields.ts
packages/phrases/src/locales/fr/errors/custom-profile-fields.ts
packages/phrases/src/locales/it/errors/custom-profile-fields.ts
packages/phrases/src/locales/ja/errors/custom-profile-fields.ts
packages/phrases/src/locales/ko/errors/custom-profile-fields.ts
packages/phrases/src/locales/pl-pl/errors/custom-profile-fields.ts
packages/phrases/src/locales/pt-br/errors/custom-profile-fields.ts
packages/phrases/src/locales/pt-pt/errors/custom-profile-fields.ts
packages/phrases/src/locales/ru/errors/custom-profile-fields.ts
packages/phrases/src/locales/tr-tr/errors/custom-profile-fields.ts
packages/phrases/src/locales/zh-cn/errors/custom-profile-fields.ts
packages/phrases/src/locales/zh-hk/errors/custom-profile-fields.ts
packages/phrases/src/locales/zh-tw/errors/custom-profile-fields.ts

- Check the sub-component types of both the `Address` and `Fullname` composition type fields, as they can't have nested `Address` or `Fullname` type sub-components.
- Add new error message and sync translation of the phrases.
New API test case should cover the change. See CI for result.

fix(core): validate sub-component types in address and fullname fields

---

packages/experience/src/containers/SetPassword/Lite.tsx
packages/experience/src/containers/SetPassword/SetPassword.tsx
packages/experience/src/pages/Continue/ExtraProfileForm/index.tsx
packages/experience/src/pages/Continue/IdentifierProfileForm/index.tsx
packages/experience/src/pages/ForgotPassword/ForgotPasswordForm/index.tsx
packages/experience/src/pages/MfaVerification/BackupCodeVerification/index.tsx
packages/experience/src/pages/SignInPassword/PasswordForm/index.tsx

Await the `submit` functions in order to have the `isSubmitting` state to update correctly. This way we can have the loading spinner on the submit button working.
Tested in the profile fulfilling page. The "Continue" button shows a loading spinner until the page is navigated away.

fix(experience): display loading spinner on submit buttons when navigating to user app

---

packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldDetails/ProfileFieldDetailsForm/index.tsx
packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/ProfileFieldList/index.tsx
packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/utils.ts

Extract a util function to generate profile field tags, and use it on both the list page and details page. Providing consistent tags on both sides.
Locally tested

fix(console): use consistent field tags across list page and details page

---

packages/experience/src/components/Dropdown/DropdownItem.module.scss
packages/experience/src/components/Dropdown/DropdownItem.tsx
packages/experience/src/components/InputFields/SelectField/index.module.scss
packages/experience/src/components/InputFields/SelectField/index.test.tsx
packages/experience/src/components/InputFields/SelectField/index.tsx
packages/experience/src/jest.setup.ts

- Add better a11y and keyboard support to the SelectField component in Experience.
- Add unit test cases for the SelectField component.
https://github.com/user-attachments/assets/ea2fd23e-360b-4e6d-a5a9-fcd2f053d80a

refactor(experience): improve a11y and keyboard control on the select field

---

.changeset/tasty-panthers-cross.md
packages/connectors/connector-logto-email/src/index.ts
packages/connectors/connector-mock-email/docs/config-template.json
packages/connectors/connector-mock-sms/docs/config-template.json
packages/core/src/routes/experience/classes/verifications/code-verification.ts
packages/core/src/routes/experience/verification-routes/verification-code.ts
packages/integration-tests/src/__mocks__/connectors-mock.ts
packages/toolkit/connector-kit/src/types/passwordless.ts

Apply template type of verification code to MFA flows:
1. Bind Email/Phone MFA: use `BindNewIdentifier` type,
2. Verification: use new `MfaVerification` type.
I had to use `@ts-expect-error` due to the circular dependency, the cloud module imports `@logto/connector-kit`. I need to update this side first.
Local tested.

feat(core,connector): add new verification code type for mfa

---

packages/console/src/components/FeatureTag/index.tsx
packages/console/src/components/PlanDescription/index.tsx
packages/console/src/components/SkuName/index.tsx
packages/console/src/consts/plan-quotas.ts
packages/console/src/consts/subscriptions.ts
packages/console/src/utils/subscription.ts
packages/core/src/libraries/quota.ts
packages/core/src/libraries/subscription.test.ts
packages/schemas/src/consts/subscriptions.ts

This PR reserves a new Pro plan ID, `pro-202508`, in the Logto schema. This ID will represent the latest Logto Pro plan starting from 2025-09, and we will gradually deprecate the legacy Pro plans.
To satisfy TypeScript requirements, this PR also updates the console package to define the necessary constant value mapping for `pro-202508`.
test locally

feat(schemas,console): reserve new pro-202508 planId

---

packages/core/src/queries/oidc-model-instance.ts

Hot fix session relation not found error.
Related PR: #7650.
Previously, we observed an expected 500 error in production caused by a data integrity issue when querying a session by its UID — multiple session records with the same UID were found.
To address this, the previous PR introduced a fallback logic: if multiple records are found, delete the duplicates and return null. However, the SQL script mistakenly used the payload model name instead of the actual table name, which resulted in a Session relation not found error.
This PR fixes the query.
test locally with mock duplicate session record

fix(core): fix session relation not found error

---

packages/console/src/pages/SignInExperience/PageContent/CollectUserProfile/CreateProfileFieldModal/index.tsx

Should close the profile field creation modal on clicking ESC button.
Manually tested

fix(console): should close the profile field creation modal on esc

---

packages/connectors/connector-gatewayapi-sms/README.md

Modified the Gateway API documentation to point to the proper endpoint if the account is in the EU region.
I was able to send a test SMS using Gateway API on a live server with the .eu endpoint.

docs: update the EU region endpoint in the Gateway API guide

---

packages/core/src/libraries/sign-in-experience/index.ts
packages/integration-tests/src/tests/experience/overrides.test.ts

Add organization-level custom CSS support in the `GET /api/.well-known/sign-in-exp` API
API integration test

feat(core): add org-level custom css support in sign-in-exp API

---

packages/console/src/components/CreateTenantModal/index.tsx
packages/console/src/consts/tenants.ts
packages/console/src/contexts/TenantsProvider.tsx
packages/console/src/hooks/use-available-regions.ts
packages/console/src/pages/GetStarted/index.tsx
packages/console/src/pages/TenantSettings/TenantBasicSettings/ProfileForm/TenantEnvironment/index.tsx

for dev-only regions, we should hide convert-to-prod buttons as they won't work
locally tested, not seeing convert buttons when the current tenant is in a dev-only region

refactor(console): hide tenant convert buttons for dev-only regions

---

packages/core/src/__mocks__/mfa-verification.ts
packages/core/src/__mocks__/webauthn.ts
packages/core/src/routes/experience/classes/verifications/web-authn-verification.test.ts
packages/core/src/routes/experience/classes/verifications/web-authn-verification.ts
packages/core/src/routes/interaction/verifications/mfa-payload-verification.test.ts
packages/core/src/routes/interaction/verifications/mfa-payload-verification.ts
packages/schemas/src/foundations/jsonb-types/users.ts
packages/schemas/src/types/interactions.ts
packages/schemas/src/types/verification-records/web-authn-verification.ts

Background:
- Historically, we did not persist the WebAuthn rpId with passkeys.
- As we plan to support multiple custom domains, each passkey must be validated against the correct relying party ID (rpId). Without storing rpId, domain-to-passkey mapping can drift and cause ambiguous or incorrect validations over time.
What this PR does:
- Persist rpId for every passkey at registration time and ensure the correct rpId is used at authentication time.
- Save `registrationRpId` alongside the registration challenge during passkey setup; on successful registration, include `rpId` in `BindWebAuthn` and persist to the user’s MFA list.
- During authentication, derive `expectedRpId` from the request hostname and verify against it; if an existing WebAuthn MFA lacks `rpId` (legacy record), backfill it …

feat(core): save rpid for passkey

---

.changeset/thin-walls-tap.md
packages/core/src/routes/verification/index.ts
packages/integration-tests/src/tests/api/account/mfa-webauthn.test.ts

Fix account API WebAuthn registration to bind rpId to the request domain.
Background: The API mistakenly called `findActiveDomain` with a tenant id instead of a domain value. As a result, generated WebAuthn registration options used the Logto default domain as rpId, causing passkeys to bind to the Logto domain even when a custom domain was in use. This diverged from the intended behavior where passkeys should bind to a custom domain when available.
Change: Derive rpId from the incoming request hostname (the domain used to access this API). This aligns account API behavior with the experience flow: whichever domain the client uses to call the endpoint becomes the rpId.
Impact and rationale: We have not received any user reports for this issue, which suggests that no one is actively binding …

fix(core): bind WebAuthn rpId to request domain for account api

---

packages/core/src/routes/domain.test.ts
packages/core/src/routes/domain.ts
packages/integration-tests/src/tests/api/domains.test.ts
packages/shared/src/node/env/GlobalValues.ts

We introduce a new env `MULTIPLE_CUSTOM_DOMAINS_ENABLED` for multiple custom domains feature, since this feature is only available to some enterprise customers running private instances.
This PR also reverts related tests, since it's not a public feature at this moment.
Test locally.

refactor(core): introduce new env for multiple custom domains feature

---

packages/experience/src/Providers/SettingsProvider/use-sign-in-experience.ts
packages/experience/src/Providers/SettingsProvider/use-theme.ts

Fix initial render flash when dark mode is enabled in the sign-in experience settings (#7615).
- **Issue**: When dark mode is enabled in sign-in experience settings, the sign-in page flashes on first render.
- **Root cause**: We always use the `Light` theme as the default value when rendering the `PageContext` component. The `theme` context update runs in the same render cycle as the page content (`useTheme`), after the `experienceSettings` value is fetched and updated in `PageContext`. Since the color theme is applied via JavaScript, it lags one cycle behind content rendering, causing a flash from Light to Dark.
- <img width="1494" height="454" alt="image" src="https://github.com/user-attachments/assets/cac71e6e-61c9-4aa3-91c2-1a372d85ad08" />
- **Fix**: Set the `theme` value before …

fix(experience): fix page flashing issue on page load

---

packages/core/src/constants/index.ts
packages/core/src/routes/domain.ts
packages/phrases/src/locales/ar/errors/domain.ts
packages/phrases/src/locales/de/errors/domain.ts
packages/phrases/src/locales/en/errors/domain.ts
packages/phrases/src/locales/es/errors/domain.ts
packages/phrases/src/locales/fr/errors/domain.ts
packages/phrases/src/locales/it/errors/domain.ts
packages/phrases/src/locales/ja/errors/domain.ts
packages/phrases/src/locales/ko/errors/domain.ts
packages/phrases/src/locales/pl-pl/errors/domain.ts
packages/phrases/src/locales/pt-br/errors/domain.ts
packages/phrases/src/locales/pt-pt/errors/domain.ts
packages/phrases/src/locales/ru/errors/domain.ts
packages/phrases/src/locales/th/errors/domain.ts
packages/phrases/src/locales/tr-tr/errors/domain.ts
packages/phrases/src/locales/zh-cn/errors/domain.ts
packages/phrases/src/locales/zh-tw/errors/domain.ts

Set a temporary cap of 10 custom domains per tenant when the “multiple custom domains” feature is enabled. We’re not enforcing this via pricing yet because the feature is currently only available to selected private-instance customers.
Test locally.

feat: add limits for multiple custom domains

---

packages/core/src/middleware/koa-experience-ssr.ts
packages/core/src/oidc/init.ts
packages/core/src/utils/i18n.ts
packages/experience/src/i18n/utils.ts
packages/experience/src/utils/search-parameters.ts
packages/schemas/src/types/cookie.ts
packages/schemas/src/types/ssr.ts

Support `ui_locales` parameter in Experience UI.
- Fetch `ui_locales` value from URL query parameters and store the specified language tags in session storage
- Fetch `.wellknown/phrases` API with the specified `ui_locales`  values
- Support language specification in Experience SSR
Locally tested with the demo-app. Experience UI locale changed by the specified `ui_locales` parameter.

feat(core,experience,schemas): support ui_locales in Experience UI

---

packages/core/src/libraries/passcode.ts
packages/core/src/routes-me/verification-code.ts
packages/core/src/routes/experience/verification-routes/verification-code-helpers.ts
packages/core/src/routes/interaction/additional.ts
packages/core/src/routes/interaction/utils/verification-code-validation.ts
packages/core/src/routes/verification/index.ts
packages/core/src/utils/cookie.ts
packages/toolkit/connector-kit/src/types/passwordless.ts

Add `ui_locales` support to the email template context, so that users can also fetch the original parameter value of via variables.
Locally tested

feat(core,toolkit): add ui_locales support in email template variables

---

packages/console/src/ds-components/Select/index.module.scss

fix read-only state drop down icon color for select component

style(console): fix read-only state drop down icon color for select component

---

packages/experience/src/pages/OneTimeToken/index.tsx

The `||=` operator is an ES2021 feature and is supported in Chrome/WebView 85+. Devices with outdated WebView/embedded browsers may throw a SyntaxError when parsing this operator. To ensure broader compatibility (especially on older Android WebView versions), replace `||=` with equivalent, widely supported assignments.

fix(experience): replace `||=` operator with compatible assignments for broader browser stability
